### ISSUE TITLE
Fix "The response is not a valid JSON response" errors by using POST requests to REST API

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2988] opened 2021-03-18 18:00 UTC
At least one of our REST datapoints uses `GET` for requests where the respective Google API endpoint uses `POST` (the Analytics `batchGet` endpoint). There appears to be problems when using `GET` requests for too complex queries because they need to include fairly long query strings, which apparently can get blocked on some environments or by certain plugins, see https://github.com/google/site-kit-wp/issues/1412#issuecomment-801764927.

We should explore switching more complex requests to using `POST`, even in cases when they're semantically more a `GET`. Let's also check how exactly e.g. the iThemes Security Pro plugin causes those requests to fail.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment] 2021-04-26 22:35
Moving this one to _Stalled_ since changing the endpoint verb here only due to a questionable rule in iThemes security plugin is not really appropriate, and the last update was that they would remove this configuration in a future version of the plugin.

**Comment by aaemnnosttv** [comment] 2022-08-02 19:27
Closing this as the issue seemed to be primarily caused by the iThemes Security plugin which has since removed the problematic functionality as of v8.0.

> Removed: The following WordPress and System Tweaks have been removed: Remove Windows Live Writer Header, EditURI Header, Comment Spam, Mitigate Attachment File Traversal Attack, Protect Against Tabnapping, **Filter Long URL Strings**, Filter Non-English Characters, Filter Request Methods, Remove File Writing Permissions.

https://wordpress.org/plugins/better-wp-security/#developers

**Closed by aaemnnosttv** 2022-08-02 19:27 UTC
Labels: Type: Bug
