### ISSUE TITLE
Register new widget with highest priority to render the notification in the key metrics widget area

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#9345] opened 2024-09-12 10:12 UTC
## Feature Description

As part of the ongoing work within the ACR epic is the need to surface subtle notification style banner within the KMW widget area, but not replacing said KMW cards.

Refer to the [Subtle banner notification for detected events](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?pli=1&resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.4vc3htg11p6z) section of the design doc

The below screenshot shows an example of said inline banner being rendered between the widget area title and the widget area contents:

<img width="1194" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHpOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--024d8bfc486bf4ae5d26c0deab67d4bf37cd4b88/image.png" alt="image.png" />

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Register a new widget to the key metrics widget area
  * It should be having highest priority
  * It should be displayed as full width widget
  * For now it can render `null`, this will be replaced by notification in #9371  

## Implementation Brief

* [ ] Update `assets/js/googlesitekit/widgets/register-defaults.js`
  * Register new widget under `AREA_MAIN_DASHBOARD_KEY_METRICS_PRIMARY`  widget area
  * You can use `keyMetricsEventDetectionCalloutNotification` for the widget slug
  * For `width` use `widgetsAPI.WIDGET_WIDTHS.FULL`
  * For `priority` use `0`
  * For `modules` include `analytics-4`
  * In `isActive` check, if `conversionReporting` feature flag is disabled, return early. And you can also return `false` by default for now
  * Use `null` for component, this will be added in #9371

### Test Coverage

* No updates needed

## QA Brief

* No QA needed as there is no user-facing change here.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment] 2024-09-25 20:07
@10upsimon @zutigrm how about registering a new full width widget with the highest priority that will render that notification instead of introducing a new property to the widgets API? Adding new `subHeader` feels excessive since we already have `subTitle` there.

**Comment by zutigrm** [comment] 2024-09-26 12:14
@eugene-manuilov That's a good point, thanks. With new changes to the layout, to expand selection to 8 items, this would work as intended. I will update dependency and modify the approach.

**Comment by eugene-manuilov** [comment] 2024-09-26 13:40
Thanks, @zutigrm. AC ✔️

**Comment by 10upsimon** [comment] 2024-10-01 14:13
@zutigrm IB ✅ moving to EB

**Comment by eugene-manuilov** [comment] 2024-10-20 08:44
Moved to Approval since there is nothing to QA here.

**Comment by zutigrm** [comment] 2024-10-21 09:42
Moving it back to execution, since it breaks the dashboard, it seems `Component` prop has to contain component, `null` is throwing invariant error. I will quickly replace this with `WidgetNull` and send it to CR

**Comment by eugene-manuilov** [comment] 2024-10-21 10:42
Thanks, merged. Moving back to Approval.

**Closed** 2024-10-31 22:33 UTC
Labels: P0, Type: Enhancement, Module: Analytics, javascript, Team S
