### ISSUE TITLE
Migrate Analytics Unique Visitors / Bounce Rate / Goals dashboard widget to use Widgets API

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1898] opened 2020-08-11 01:41 UTC
The current Analytics `AnalyticsDashboardWidgetTopLevel` widget should be migrated to use the Widgets API (which is behind a feature flag), while maintaining the current version as legacy components. Those will be removed only once all widgets have been migrated so that we can do the entire switch.

Some general practices for migrating:
* The migration should happen by fully **re-implementing** the components: In other words, the existing components should keep their current functionality, they should **not** use the datastore. Those legacy components should be prefixed with `Legacy*`.
* A good starting point is probably to copy the components into new files and go from there, while renaming the old ones and leaving them untouched.
* For the refactored version, _only_ the actual widget components should be fully responsible for retrieving data from the datastore. If they rely on further `common` components for UI, these should receive such data via props.
* If there are UI parts that can be reused between the new and legacy components, those can be outsourced into `common` components, however as mentioned above **it is important that the legacy components keep using the legacy data API and are not switched to the datastore**. Only the new ones should be.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The [`AnalyticsDashboardWidgetTopLevel`](https://github.com/google/site-kit-wp/blob/1.13.1/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidgetTopLevel.js) component should be migrated to functional components using the datastore entirely, no globals and no legacy data API.
* Refactoring map:
    * `dashboard/AnalyticsDashboardWidgetTopLevel.js` should become `dashboard/DashboardUniqueVisitorsWidget.js` (refactored widget 1), `dashboard/DashboardBounceRateWidget.js` (refactored widget 2), `dashboard/DashboardGoalsWidget.js` (refactored widget 3), and `dashboard/LegacyAnalyticsDashboardWidgetTopLevel.js` (legacy) - i.e. this component should be split into three separate widget components for the refactoring. The refactored widget components should access the datastore for the main API data.
* The new `DashboardUniqueVisitorsWidget`, `DashboardBounceRateWidget` and `DashboardGoalsWidget` components should return `AnalyticsInactiveCTA` if the Analytics module is not active. _Only_ otherwise Analytics data should be requested, i.e. this part probably needs to go into separate components `DashboardUniqueVisitors`, `DashboardBounceRate` and `DashboardGoals`, since React hooks cannot run conditionally (we use `*Widget` as top-level entry point while the un-suffixed version is essentially the main part of it, without any extra checks for active modules etc.).
* The new `DashboardUniqueVisitors`, `DashboardBounceRate` and `DashboardGoals` components should rely on `select( CORE_SITE ).getCurrentReferenceURL()` so that they use the site URL vs the current entity URL as applicable (the latter e.g. when used in the `pageDashboard` context).
* The new `DashboardUniqueVisitorsWidget` component should be registered as a widget with priority 3, width `Widgets.WIDGET_WIDTHS.QUARTER`, and for the two widget areas `AREA_DASHBOARD_SEARCH_FUNNEL` and `AREA_PAGE_DASHBOARD_SEARCH_FUNNEL`.
* The new `DashboardBounceRateWidget` component should be registered as a widget with priority 4, width `Widgets.WIDGET_WIDTHS.QUARTER`, and for the widget area `AREA_PAGE_DASHBOARD_SEARCH_FUNNEL`.
* The new `DashboardGoalsWidget` component should be registered as a widget with priority 4, width `Widgets.WIDGET_WIDTHS.QUARTER`, and for the widget area `AREA_DASHBOARD_SEARCH_FUNNEL`.

#### Stage 1
* Rename the following files and components accordingly:
  * `assets/js/modules/analytics/dashboard/AnalyticsDashboardWidgetTopLevel.js` -> `assets/js/modules/analytics/dashboard/LegacyAnalyticsDashboardWidgetTopLevel.js`.
* Update:
  * `index.legacy.js` file to use `LegacyAnalyticsDashboardWidgetTopLevel` instead of `AnalyticsDashboardWidgetTopLevel`;
  * `stories/dashboard.stores.js` file to use `LegacyAnalyticsDashboardWidgetTopLevel` imported from the appropriate legacy files.

#### Stage 2
* Create a new goals datastore in the analytics module:
  * Use `createFetchStore` factory with the following settings:
    * `baseName` should be `getGoals`;
    * `controlCallback` should be a function that sends API request to the `goals` datapoint;
    * `reducerCallback` should be a function that returns a new state with results of the request saved under the `goals` key.
  * Define `getGoals` selector that returns `goals` from the state.
  * Define `getGoals` resolver that does nothing if the `goals` data exists in the state, otherwise dispatches `fetchGetGoals` action.
* Add the new goals datastore to the `combineStores` list in the `datastore/index.js` file.

#### Stage 3
* Create `assets/js/modules/analytics/dashboard/DashboardGoalsWidget.js` file;
* `DashboardGoalsWidget.js` file should:
  * Import `overviewReportDataDefaults` from the `assets/js/modules/analytics/utils/index.js` file.
  * Define a new functional component with `DashboardGoalsWidget` name;
  * Use `useSelect` hook and the following selectors to pull data required for the widget:
    * `getDateRange` selector from the `core/user` datastore to retrieve the current date range;
    * `getGoals` selector from the analytics datastore to retrieve goals data;
    * `getReport` selector from the analytics datastore with the following arguments:
      ```js
      {
        dateRange: ..., // use getDateRange value
        multiDateRange: 1,
        dimensions: 'ga:date',
        metrics: [ { expression: 'ga:goalCompletionsAll', alias: 'Goal Completions' } ],
        limit: 10,
      }
      ```
  * Return `PreviewBlock` component while data is being fetched (like it is done in the legacy component);
  * Replicate the logic from the legacy comonent to render goals widget;
    https://github.com/google/site-kit-wp/blob/8edad66b753af26c933e54ebf830d618f3a9bb32/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidgetTopLevel.js#L192-L209
* Export a component enhanced with `whenActive` HOC (see Stage 2 in #1896) that uses `analytics` as module name and `AnalyticsInactiveCTA` component as a fallback component.

#### Stage 4
* Create `assets/js/modules/analytics/dashboard/DashboardUniqueVisitorsWidget.js` file;
* `DashboardUniqueVisitorsWidget.js` file should:
  * Import `siteAnalyticsReportDataDefaults`, `overviewReportDataDefaults` and `userReportDataDefaults` from the `assets/js/modules/analytics/utils/index.js` file;
  * Define a new functional component with `DashboardUniqueVisitorsWidget` name.
  * Use `useSelect` hook and the following selectors to pull data required for the widget:
    * `getCurrentReferenceURL` selector from the `core/site` datastore to retrieve the current reference URL;
    * `getDateRange` selector from the `core/user` datastore to retrieve the current date range;
    * `getReport` selector from the analytics datastore to retrieve data for the sparkline.
      * Use `siteAnalyticsReportDataDefaults`, current reference URL and date range information to compose options object and pass it into the `getReport` selector.
    * `getReport` selector from the analytics datastore to retrieve data for the direct total users number.
      * Use `userReportDataDefaults`, current reference URL and date range information to compose options object and pass it into the `getReport` selector.
  * Replicate the logic from the legacy comonent to render Unique visitors widget.
    https://github.com/google/site-kit-wp/blob/8edad66b753af26c933e54ebf830d618f3a9bb32/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidgetTopLevel.js#L128-L145
* Export a component enhanced with `whenActive` HOC (see Stage 2 in #1896) that uses `analytics` as module name and `AnalyticsInactiveCTA` component as a fallback component.

#### Stage 5
* Create `assets/js/modules/analytics/dashboard/DashboardBounceRateWidget.js` file;
* `DashboardBounceRateWidget.js` file should:
  * Import `siteAnalyticsReportDataDefaults` and `overviewReportDataDefaults` from the `assets/js/modules/analytics/utils/index.js` file;
  * Define a new functional component with `DashboardBounceRateWidget` name.
  * Use `useSelect` hook and the following selectors to pull data required for the widget:
    * `getCurrentReferenceURL` selector from the `core/site` datastore to retrieve the current reference URL;
    * `getDateRange` selector from the `core/user` datastore to retrieve the current date range.
    * `getReport` selector from the analytics datastore to retrieve data for the sparkline.
      * Use `siteAnalyticsReportDataDefaults`, current reference URL and date range information to compose options object and pass it into the `getReport` selector.
    * `getReport` selector from the analytics datastore to retrieve bounce rate data using the following arguments:
      ```js
      {
        dateRange: ..., // use getDateRange value
        url: ..., // use getCurrentReferenceURL value
        multiDateRange: 1,
        dimensions: 'ga:date',
        metrics: [ { expression: 'ga:bounceRate', alias: 'Bounce Rate' } ],
        limit: 10,
      }
      ```
  * Return `PreviewBlock` component while data is being fetched (like it is done in the legacy component);
  * Replicate the logic from the legacy comonent to render goals widget;
    https://github.com/google/site-kit-wp/blob/8edad66b753af26c933e54ebf830d618f3a9bb32/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidgetTopLevel.js#L161-L180
* Export a component enhanced with `whenActive` HOC (see Stage 2 in #1896) that uses `analytics` as module name and `AnalyticsInactiveCTA` component as a fallback component.

#### Stage 6
* Update `domReady` callback in the `assets/js/modules/analytics/index.js` file (added in the #1896):
  * Register `DashboardUniqueVisitorsWidget` widget with the following arguments:
    * A string `analyticsUniqueVisitors` as widget slug;
    * Settings object where:
      * `component` is `DashboardUniqueVisitorsWidget`;
      * `width` is `Widgets.WIDGET_WIDTHS.QUARTER`;
      * `priority` is `3`;
      * `wrapWidget` is `true`.
    * Areas array that includes `AREA_DASHBOARD_SEARCH_FUNNEL` and `AREA_PAGE_DASHBOARD_SEARCH_FUNNEL` imported from `googlesitekit/widgets/default-areas`.
  * Register `DashboardBounceRateWidget` widget with the following arguments:
    * A string `analyticsBounceRate` as widget slug;
    * Settings object where:
      * `component` is `DashboardBounceRateWidget`;
      * `width` is `Widgets.WIDGET_WIDTHS.QUARTER`;
      * `priority` is `4`;
      * `wrapWidget` is `true`.
    * Areas array that includes just `AREA_PAGE_DASHBOARD_SEARCH_FUNNEL` imported from `googlesitekit/widgets/default-areas`.
  * Register `DashboardGoalsWidget` widget with the following arguments:
    * A string `analyticsGoals` as widget slug;
    * Settings object where:
      * `component` is `DashboardGoalsWidget`;
      * `width` is `Widgets.WIDGET_WIDTHS.QUARTER`;
      * `priority` is `4`;
      * `wrapWidget` is `true`.
    * Areas array that includes just `AREA_DASHBOARD_SEARCH_FUNNEL` imported from `googlesitekit/widgets/default-areas`.

## QA Brief

* In a development build, the new Analytics Unique Visitors and Goals widgets should render correctly in the Site Kit dashboard. They should behave the same way as the old ones.
* In a development build, the new Analytics Unique Visitors and Bounce Rate widgets should render correctly in the Site Kit single URL details view. They should behave the same way as the old ones.
* It should be tested that they display errors if e.g. the API request goes wrong - they shouldn't keep loading infinitely in such a case (try e.g. to block client-to-server requests to cause an error).
* The old/legacy Analytics Unique Visitors, Goals, and Bounce Rate widgets should continue to show up in both development and production builds and behave like before.

## Changelog entry

* Migrate Analytics Unique Visitors, Bounce Rate, and Goals widgets to new Widget API.

**Comment by eugene-manuilov** [comment] 2020-08-11 17:09
@felixarntz this is ready for initial IB review. The only thing that I am not sure about is duplicate requests with the same arguments caused by multiple `getReport` calls in different widgets. Is there a way to make sure that we send just one request per certain arguments?

I have just one idea off the top of my head: use similar approach that we use in the properties datastore where we have `waitForProperties` action. If I understand it correctly, we can create a similar action for the report datastore to wait for a report to be fetched to re-use its data if another report with similar arguments is already fetching. We will need to update `getReport` resolver to account for it. 

Let me know what you think.

**Comment by felixarntz** [comment] 2020-08-12 00:31
@eugene-manuilov Optimizing the request is something that I specifically would like to look at _after_ we've implemented these widgets, but before we would actually make the switch in production. For now, let's implement requests "naively" per widget. What we should do though is keep the request body minimal, for example we shouldn't blindly use `overviewReportDataDefaults`, but instead only request the dimensions/metrics really necessary for that widget.

> Wrap rendered component with the `Widget` component that has [...] slug and `googlesitekit-widget--no-padding` class, and return it.

Why not use `wrapWidget: true` for the three widgets here instead? I think they can all use the regular padding, so the default automated version of the `Widget` component can be used.

Last but not least I think the estimate is a bit low, maybe 19 is more appropriate? The widgets themselves are simple, but we shouldn't underestimate the split into 3 different widgets, and the supplemental logic to be added.

**Comment by eugene-manuilov** [comment] 2020-08-12 12:03
> @eugene-manuilov Optimizing the request is something that I specifically would like to look at _after_ we've implemented these widgets, but before we would actually make the switch in production. [...] What we should do though is keep the request body minimal, for example we shouldn't blindly use `overviewReportDataDefaults`, but instead only request the dimensions/metrics really necessary for that widget.

@felixarntz I thought about it too but I don't think that we need to try minizing bodies, because in this case we won't be able to optimize those requests since they will have different arguments. If we keep using the same request arguments for these three widgets, then once we optimize it, we will have just one request that will serve data for all three widgets.

Does it make sense to you or you have another idea how to optimize those requests? Maybe batching could help, but if i remember correctly, we are going to get away from it.

> > Wrap rendered component with the `Widget` component that has [...] slug and `googlesitekit-widget--no-padding` class, and return it.
> 
> Why not use `wrapWidget: true` for the three widgets here instead? I think they can all use the regular padding, so the default automated version of the `Widget` component can be used.

Because we can't know whether the analytics module is active when we register these widgets. That's why we need to use `whenActive` HOC to control when to display widgets or not. If we use `wrapWidget: true`, it will mean that widget API will always render `Widget` component itself even if we don't need it when the module is inactive.

> Last but not least I think the estimate is a bit low, maybe 19 is more appropriate? The widgets themselves are simple, but we shouldn't underestimate the split into 3 different widgets, and the supplemental logic to be added.

Yep, agreed, changed it to 19.

**Comment by felixarntz** [comment] 2020-08-12 17:55
@eugene-manuilov 
> @felixarntz I thought about it too but I don't think that we need to try minizing bodies, because in this case we won't be able to optimize those requests since they will have different arguments. If we keep using the same request arguments for these three widgets, then once we optimize it, we will have just one request that will serve data for all three widgets.
> 
> Does it make sense to you or you have another idea how to optimize those requests? Maybe batching could help, but if i remember correctly, we are going to get away from it.

I think we should for now implement the requests in the most targeted way possible, i.e. only request the data which is needed for the current widget. I understand eventually it may be better to use less minimal requests that work for multiple widgets, but for now let's not think about that so that we start from a clean slate. In other words, a widget shouldn't know what another widget is requesting to "optimize" the request. Any optimization to reduce the number of requests we can look at later on.

> > Why not use `wrapWidget: true` for the three widgets here instead? I think they can all use the regular padding, so the default automated version of the `Widget` component can be used.
> 
> Because we can't know whether the analytics module is active when we register these widgets. That's why we need to use `whenActive` HOC to control when to display widgets or not. If we use `wrapWidget: true`, it will mean that widget API will always render `Widget` component itself even if we don't need it when the module is inactive.

This shouldn't be a problem: When `wrapWidget` is `true`, the widget will still only be wrapped if it returns something other than `null`. We should only use `wrapWidget: false` for cases where we need to use an entirely custom component or e.g. get rid of the padding.

**Comment by eugene-manuilov** [comment] 2020-08-12 18:26
> This shouldn't be a problem: When wrapWidget is true, the widget will still only be wrapped if it returns something other than null. We should only use wrapWidget: false for cases where we need to use an entirely custom component or e.g. get rid of the padding.

Ah... ok, make sense then. @felixarntz do you want me to update it in other tickets as well or just this ticket?

**Comment by eugene-manuilov** [comment] 2020-08-12 18:47
> I think we should for now implement the requests in the most targeted way possible, i.e. only request the data which is needed for the current widget. I understand eventually it may be better to use less minimal requests that work for multiple widgets, but for now let's not think about that so that we start from a clean slate. In other words, a widget shouldn't know what another widget is requesting to "optimize" the request. Any optimization to reduce the number of requests we can look at later on.

Ok, updated. Ready for IB review.

**Comment by felixarntz** [comment] 2020-08-17 23:57
IB ✅

**Comment by felixarntz** [comment] 2020-09-01 18:38
@ryanwelcher Assigning to you to take over. Try to focus on #1897 first though so that we can get that in. The CR feedback here is almost entirely similar.

**Comment by cole10up** [comment] 2020-09-16 05:26
**Tested:**

Installed latest SK development build, activated and setup Analytics module.

Confirmed Dashboard:
![image](https://user-images.githubusercontent.com/57115907/93294985-e8283a80-f7a0-11ea-82f5-81005239fa22.png)

![image](https://user-images.githubusercontent.com/57115907/93295182-50771c00-f7a1-11ea-972e-3e3ee5297c50.png)

Analytics:
![image](https://user-images.githubusercontent.com/57115907/93295106-2291d780-f7a1-11ea-9a33-8e876e93485a.png)

![image](https://user-images.githubusercontent.com/57115907/93295069-10b03480-f7a1-11ea-9c31-c12bb18763a6.png)

![image](https://user-images.githubusercontent.com/57115907/93295132-32a9b700-f7a1-11ea-86f9-d299775ae5a5.png)

Development Single Page:
![image](https://user-images.githubusercontent.com/57115907/93295524-0e9aa580-f7a2-11ea-90cc-849c88073c60.png)

Release Single page:
![image](https://user-images.githubusercontent.com/57115907/93295539-1ce8c180-f7a2-11ea-839f-f0d32f36183a.png)

**Noticed the graph look and feel differs between Widgets API and current release**

Development Mobile view:
![image](https://user-images.githubusercontent.com/57115907/93295348-a946b480-f7a1-11ea-8b50-93b5cd462124.png)

Release mobile view:
![image](https://user-images.githubusercontent.com/57115907/93295401-c7acb000-f7a1-11ea-8c90-45d34aeb941d.png)

**Notice: Above differs from current release likely due to the padding around the new Widgets API** @felixarntz

**Comment by felixarntz** [comment] 2020-09-16 15:43
@cole10up Good catch! It is due to widget alignment via the new API. Let's move forward as is for now, I've taken a note of this in #1997 to revisit before we launch this in production.

**Comment by cole10up** [comment] 2020-09-17 05:30
Moving this onto approval.

Passed QA ✅

**Closed** 2020-09-24 16:25 UTC
Labels: P0, Type: Enhancement
