### ISSUE TITLE
Issue during setup: Unknown Error (code: Invalid JSON response) 

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1282] opened 2020-03-25 01:55 UTC
## Bug Description

A [user in the support forums](https://wordpress.org/support/topic/authentication-loop/)  persistently receives this error in the WordPress admin after attempting setup:

 
![Unknown Error - Invalid JSON Response](https://user-images.githubusercontent.com/8108643/77493581-c6a55200-6e00-11ea-8556-f1194e4dd4a0.png)

While the conditions to recreate the error are still under investigation, the topic has both detailed screenshots of the steps taken before it occurs and Site Health info.

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

This issue was reported in #777 during the early release, but hasn't reappeared until now.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by cole10up** [comment] 2020-03-30 16:57
Ran through a series of tests, setting up SK - mirroring the user from the support link above's setup. Turkish language and all plugins installed and active. I'm unable to reproduce on the latest production build.

![image](https://user-images.githubusercontent.com/57115907/77939751-7d278d80-726c-11ea-8927-4711bc0c13ce.png)

<details>
  <summary>Click to expand site health info</summary>
  
 `
### wp-core ###

version: 5.3.2
site_language: tr_TR
user_language: tr_TR
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /srv/users/usere24a396b/apps/usere24a396b/public
wordpress_size: 40,03 MB (41979502 bytes)
uploads_path: /srv/users/usere24a396b/apps/usere24a396b/public/wp-content/uploads
uploads_size: 266,00 B (266 bytes)
themes_path: /srv/users/usere24a396b/apps/usere24a396b/public/wp-content/themes
themes_size: 4,63 MB (4859674 bytes)
plugins_path: /srv/users/usere24a396b/apps/usere24a396b/public/wp-content/plugins
plugins_size: 97,10 MB (101813431 bytes)
database_size: 2,38 MB (2490368 bytes)
total_size: 144,14 MB (151143241 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Twenty Twenty (twentytwenty)
version: 1.1
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, custom-background, post-thumbnails, custom-logo, title-tag, html5, align-wide, customize-selective-refresh-widgets, editor-color-palette, editor-font-sizes, widgets, menus, editor-style
theme_path: /srv/users/usere24a396b/apps/usere24a396b/public/wp-content/themes/twentytwenty

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 1.4, author: the WordPress team
Twenty Seventeen: version: 2.2, author: the WordPress team
Twenty Sixteen: version: 2.0, author: the WordPress team

### wp-plugins-active (22) ###

Adminimize: version: 1.11.6, author: Frank Bültge
Advanced Custom Fields: version: 5.8.9, author: Elliot Condon
Akismet Anti-Spam: version: 4.1.4, author: Automattic
Boxzilla: version: 3.2.22, author: ibericode
Companion Plugin: version: 1.11, author: Osk
Custom Post Type UI: version: 1.7.4, author: WebDevStudios
Hello Dolly: version: 1.7.2, author: Matt Mullenweg
Hide/Remove Metadata: version: 1.1, author: Catch Plugins
Jetpack by WordPress.com: version: 8.3, author: Automattic
LiteSpeed Cache: version: 2.9.9.2, author: LiteSpeed Technologies
Master Slider: version: 3.5.8, author: averta
Ninja Forms: version: 3.4.24.1, author: Saturday Drive
Site Kit by Google: version: 1.6.0, author: Google
TablePress: version: 1.10, author: Tobias Bäthge
TablePress Extension: Chartist: version: 0.9, author: Silsha Fux
Toggle wpautop: version: 1.3.0, author: Linchpin & Jonathan Desrosiers
Ultimate Addons for Gutenberg: version: 1.14.8, author: Brainstorm Force
WP Force SSL: version: 1.55, author: WebFactory Ltd
WPFront Scroll Top: version: 2.0.2, author: Syam Mohan
WP Mail SMTP: version: 1.9.0, author: WPForms
WP Maintenance Mode: version: 2.2.4, author: Designmodo
YITH WooCommerce Ajax Product Filter: version: 3.9.0, author: YITH

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Uygun değil
imagemagick_version: Uygun değil
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 4.4.0-174-generic x86_64
httpd_software: Apache/2.4.41 (Unix) OpenSSL/1.0.2g
php_version: 7.3.16 64bit
php_sapi: fpm-fcgi
max_input_variables: 5000
time_limit: 30
memory_limit: 256M
max_input_time: -1
upload_max_size: 512M
php_post_max_size: 1024M
curl_version: 7.47.0 OpenSSL/1.0.2g
suhosin: false
imagick_availability: false
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.29-0ubuntu0.16.04.1-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /srv/users/usere24a396b/apps/usere24a396b/public/wp-content
WP_PLUGIN_DIR: /srv/users/usere24a396b/apps/usere24a396b/public/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### jetpack ###

site_id: false
ssl_cert: No
time_diff: false
version_option: 8.3:1585585322
old_version: 8.3:1585585322
public: Private
master_user: No master user set.
current_user: #1 demo (oskosk+jurassicninja+new+site+created@gmail.com)
tokens_set: None
blog_token: Not set.
user_token: Not set.
version: 8.3
jp_plugin_dir: /srv/users/usere24a396b/apps/usere24a396b/public/wp-content/plugins/jetpack/
plan: free
HTTP_HOST: fundamental-lynx.jurassic.ninja
SERVER_PORT: 443
HTTPS: on
HTTP_X_FORWARDED_FOR: 68.8.26.177
REMOTE_ADDR: 68.8.26.177
protect_header: false
full_sync: {"started":"Thu, 01 Jan 1970 00:00:00 +0000","finished":"Thu, 01 Jan 1970 00:00:00 +0000","progress":[],"config":[]}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/fundamental-lynx.jurassic.ninja","siteurl":"https:\/\/fundamental-lynx.jurassic.ninja","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: [{"name":"test__check_if_connected","pass":false,"message":"Jetpack is not connected.","resolution":"connect_jetpack","action":"https:\/\/fundamental-lynx.jurassic.ninja\/wp-admin\/admin.php?page=jetpack#\/dashboard","severity":"critical","label":"Your site is not connected to Jetpack","action_label":"Reconnect your site now","description":"<p>A healthy connection ensures Jetpack essential services are provided to your WordPress site, such as Stats and Site Security.<\/p><p><span class=\"dashicons fail\"><span class=\"screen-reader-text\">Error<\/span><\/span> Your site is not connected to Jetpack.<strong> We recommend reconnecting Jetpack.<\/strong><\/p>","group":["default"],"type":"direct"}]

### google-site-kit ###

version: 1.6.0
php_version: 7.3.16
wp_version: 5.3.2
reference_url: https://fundamental-lynx.jurassic.ninja
amp_mode: no
site_status: connected-site
user_status: authenticated
active_modules: site-verification, search-console
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
search_console_property: https://fundamental-lynx.jurassic.ninja/

### wp_mail_smtp ###

version: 1.9.0
license_key_type: lite
debug: No debug notices found.

`
</details>

Sending to Level 2 for more investigation

**Comment by aaemnnosttv** [comment] 2020-04-16 08:06
@felixarntz can you look into this on the proxy side? I wonder if you can see what the actual response is for this user when the auth token is fetched? It seems that this is where the failure is happening. Their domain is `https://tap.org.tr/.

**Comment by felixarntz** [comment] 2020-04-16 18:16
@aaemnnosttv I already looked at this a few weeks ago. I found a single occurrence on the proxy (edge-case for this to be ever hit) where it would have provided a non-JSON response. That instance has since been fixed, but even that would not have been reached for that user.

I have no clue on how this is happening, we may have to continue to work with that user to dig down to the issue. cc @ernee

**Comment by adamsilverstein** [comment] 2020-06-29 13:19
@ernee Reviewing the support ticket I am guessing this issue is resolved. Closing for now, if there is still an issue, please feel free to re-open.

**Closed by adamsilverstein** 2020-06-29 13:19 UTC
Labels: Group: Escalation, Type: Bug
