### ISSUE TITLE
Users unable to complete setup due to Error: Bad Request: missing parameter: ‘code’

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#5191] opened 2022-05-09 10:12 UTC
## Bug Description

There have been multiple reports over the past few days of users encountering an `Error Bad Request: Missing parameter: ‘code’` error during plugin setup. This occurs when clicking on the "Continue" button at the OAuth stage.

![image](https://user-images.githubusercontent.com/41326532/167389191-55b60742-82bf-4e65-8fd8-27d132c68254.png)

There were reports of a similar error previously, with various different causes. In these cases the error was slightly different - `invalid parameter: 'code'` ([screenshot](https://i.imgur.com/WN2NmH0.png)) This has been [documented internally](https://app.asana.com/0/1201238173167296/1202223112083748/f) and in some cases there has been a "re-do the plugin set up" option which did allow users to proceed.  

[One user](https://wordpress.org/support/topic/site-kit-error-bad-request-missing-parameter-code-2/) (Not the original poster) was able to successfully complete setup after re-attempting. In this users cases they has encountered a 400 error on a Site Kit URL:
`https://sitekit.withgoogle.com/v2/site-management/setup/ 400`

[Another user](https://example.com//?oauth2callback=1&authuser=0&error=access_denied&prompt=consent) who we suspect may be encountering the same reporting the below, indicating a possible permissions error. [Another user](https://wordpress.org/support/topic/stuck-on-a-loop-set-up-site-kit/), however, did specifically state they granted all permissions yet they encounter the same:
`https://example.com//?oauth2callback=1&authuser=0&error=access_denied&prompt=consent`

Other users have reported the same [after a site reset](https://wordpress.org/support/topic/stuck-on-a-loop-set-up-site-kit/) and [after using the Health Check & Troubleshooting plugin](https://wordpress.org/support/topic/error-bad-request-missing-parameter-code-2/#post-15627775), meaning no other plugins other than Site Kit active. Adam has tested the same hosting provider used by one reporter, without encountering any issue. Troubleshooting ongoing. 

Reports:
- https://wordpress.org/support/topic/error-bad-request-missing-parameter-code | **Open** | [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNiGqRHZb20j_Akcu3KJ5f2DzKPqdm2kK7F13XPD88QQaP2c919kSiPJMlmM32udZko)
- https://wordpress.org/support/topic/error-bad-request-missing-parameter-code-2 | **Open** | No SH info
- https://wordpress.org/support/topic/stuck-on-a-loop-set-up-site-kit/ | **Open** | [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNhCGG9xtYj83Sjxk9w9zfg7_HzUwkglOLjtUToXBHdL10IChgZ5PxzItDvhtBY0RjU)
- https://wordpress.org/support/topic/cant-install-sitekit-bad-request-missing-parameter-code-2  | **Open** | No SH info
- https://wordpress.org/support/topic/site-kit-error-bad-request-missing-parameter-code-2/  | **Open** | No SH info

It's possible the below may also also experiencing the same error, based on the experience, with no mention of this specific error in the dashboard:
- https://wordpress.org/support/topic/accessdenied | Open | No SH info

## Insights & Troubleshooting Checks performed 

- [x] Health Check & Troubleshooting plugin check - Same occurs
- [ ] Uninstalled and reinstalled plugin
- [ ] User confirmed no ""Critical errors"" in their Site Health status
- [ ] Attempted setup/viewing dashboards from another device 
- [ ] Temporary disabled WAF rules at host level - including ModSecurity
- [ ] Checked site setup and dashboard from another WordPress site on the same hosting platform
- [x] Reset Site Kit - [Same occurs](https://wordpress.org/support/topic/stuck-on-a-loop-set-up-site-kit/)
- [ ] Reset previous site records (on the SK service)
- [ ] Disconnected Site Kit
- [ ] Checked does the same occur from another WordPress administrator account

## Additional Context

 - Recent reports all started with SK 1.73.0
 - Unknown if these recent reports were all first time setup's at this point
 - Unknown if all the same hosting platforms at this point
 - Unreproducible in support during testing so far

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment] 2022-05-09 10:17
Based on [one users additional insights ](https://wordpress.org/support/topic/error-bad-request-missing-parameter-code/#post-15627799) Adam was able to reproduce this error using the Brave browser. Following up with other users to check the same. 

https://files.slack.com/files-pri/T048W193T-F03ELRYB4AW/image.png

**Comment by adamdunnage** [comment] 2022-05-09 11:01
Below is a recording of the experience with the '**Auto-redirect AMP pages**' setting first switched on(which it is by default in the Brave browser) and when it is switched off.


https://user-images.githubusercontent.com/91896826/167396761-6179f2e7-f1e0-4e03-9fa7-ec720c638822.mp4

**Comment by adamdunnage** [comment] 2022-05-09 13:18
**Update**

I can also recreate this in a Chrome browser with [this Chrome extension](https://chrome.google.com/webstore/detail/redirect-amp-to-html/kifkmmpiicbcnkjaliilaoeaojlldonl/related?hl=en-GB) installed. This seems to do the same as the Brave browser setting. 

I am unable to recreate with any of the in built Chrome settings found in privacy and security but there are no options to redirect or disable AMP pages.

**Comment by techanvil** [comment] 2022-12-12 11:58
Having taken a look, I was also able to reproduce this using Brave with the "Auto-redirect AMP pages" setting enabled.

This would be best looked into further by someone on the Site Kit Service engineering team, as the problem occurs due to the query params being stripped from the path between SKS requests as can be seen below.

One possible avenue to address this would be to encode the relevant information in the path rather than using query params.

_Error, with "Auto-redirect AMP pages" setting enabled:_
![image](https://user-images.githubusercontent.com/18395600/207038842-c8a4d9a7-f11b-4da4-a20c-d2bc88cfc287.png)

_Success, with "Auto-redirect AMP pages" setting disabled:_
![image](https://user-images.githubusercontent.com/18395600/207039056-37af307d-1e46-41bb-a241-d90a9b83eff8.png)

cc @aaemnnosttv @eugene-manuilov @felixarntz

**Comment by eugene-manuilov** [comment] 2022-12-12 13:18
Hm, this is strange... I checked the codebase and I see that we use the same redirect URL for AMP pages as for regular ones... 🤔

**Comment by techanvil** [comment] 2022-12-12 13:33
What's the implication there, @eugene-manuilov - should we be using a different redirect URL for AMP pages? Or are you commenting on the weirdness of the query params being stripped, which on the face of it seems down to Brave's behaviour when "Auto-redirect AMP pages" is enabled?

**Comment by eugene-manuilov** [comment] 2022-12-12 14:57
Yes, I mean that its weird that query params are stripped for the automatic AMP redirects case. In the code we use the same variable for both headers. Actually, I just noticed that we use `Redirect-To` and `AMP-Redirect-To` headers which is weird because the standard redirect header is `Location`. @felixarntz, do you know why we use the `Redirect-To` header?

**Comment by aaemnnosttv** [comment] 2022-12-17 16:50
@eugene-manuilov that's because it's not used as a regular redirect. It's used when syncing site fields or registering a site: https://github.com/google/site-kit-wp/commit/59c9b0f4912ee4eff66ae898e2d993084a5c76a6#diff-e3ac1fdfcae738afa70efaf4637416ebfae905a5fa75bfcbc459d7e172745890R485

We used `Redirect-To` to be the non-AMP version of the same AMP header.

**Comment by eugene-manuilov** [comment] 2023-01-03 19:19
Ah... yes, you are right, @aaemnnosttv. Forgot that we use it in the plugin.

**Comment by bethanylang** [comment] 2023-01-05 15:28
BCL to close this issue and instead add an Asana issue for service research.

**Comment by bethanylang** [comment] 2023-01-05 15:55
Asana task created; closing.

**Closed by bethanylang** 2023-01-05 15:55 UTC
Labels: Type: Bug, Type: Support, Group: Escalation
