### ISSUE TITLE
Blank Dashboard after activating Site Kit with this error in console: Uncaught TypeError: can't convert undefined to object

### ISSUE THREAD

**Issue by abdullah1908** [google/site-kit-wp#3846] opened 2021-08-12 09:28 UTC
## Bug Description
A user reported a bug on [support forum](https://wordpress.org/support/topic/blank-dashboard-page-after-activation/): On activating Site Kit it shows blank screen & seeing this error in browser console  `Uncaught TypeError: can't convert undefined to object`.   

This error still appears even user disabled all the plugins. Site Kit works fine on another site with the same host.
PS:  iThemes and MalCare Pro installed on the website.

Topic: https://wordpress.org/support/topic/blank-dashboard-page-after-activation/ | No SH Info yet 

Find the detailed error log below:

```
Uncaught TypeError: can't convert undefined to object
    a https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-api.3d45775cfc2dc95a166b.js:1
    85 https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-api.3d45775cfc2dc95a166b.js:16
    85 https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-api.3d45775cfc2dc95a166b.js:16
    __webpack_require__ https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/runtime.11204cf5d95ff56353f0.js:1
    361 https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-api.3d45775cfc2dc95a166b.js:1
    361 https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-api.3d45775cfc2dc95a166b.js:1
    __webpack_require__ https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/runtime.11204cf5d95ff56353f0.js:1
    783 https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-api.3d45775cfc2dc95a166b.js:16
    783 https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-api.3d45775cfc2dc95a166b.js:16
    __webpack_require__ https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/runtime.11204cf5d95ff56353f0.js:1
    _ https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/runtime.11204cf5d95ff56353f0.js:1
    r https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/runtime.11204cf5d95ff56353f0.js:1
    <anonymous> https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-api.3d45775cfc2dc95a166b.js:1
googlesitekit-api.3d45775cfc2dc95a166b.js:1:479
Uncaught TypeError: e._googlesitekitLegacyData is undefined
    280 https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-dashboard-splash.41d3b182a6aadaba2291.js:6
    280 https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-dashboard-splash.41d3b182a6aadaba2291.js:6
    __webpack_require__ https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/runtime.11204cf5d95ff56353f0.js:1
    959 https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-dashboard-splash.41d3b182a6aadaba2291.js:33
    959 https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-dashboard-splash.41d3b182a6aadaba2291.js:33
    __webpack_require__ https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/runtime.11204cf5d95ff56353f0.js:1
    _ https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/runtime.11204cf5d95ff56353f0.js:1
    r https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/runtime.11204cf5d95ff56353f0.js:1
    <anonymous> https://stranka.cz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-dashboard-splash.41d3b182a6aadaba2291.js:1
googlesitekit-dashboard-splash.41d3b182a6aadaba2291.js:6:6646
Content Security Policy: Nastavení stránky zablokovalo načítání zdroje na blob:https://stranka.cz/5adb8d42-4eb8-4d22-ae6e-efd010d74783 („default-src“). index.min.js:1:1547
Content Security Policy: Nastavení stránky zablokovalo načítání zdroje na blob:https://stranka.cz/821f2ec0-fa7b-49b9-9ec0-ba5d45c0f90a („default-src“). index.min.js:1:1547
Content Security Policy: Nastavení stránky zablokovalo načítání zdroje na blob:https://stranka.cz/b82ad878-e357-4771-a381-12248528d934 („default-src“). index.min.js:1:1547
Content Security Policy: Nastavení stránky zablokovalo načítání zdroje na blob:https://stranka.cz/4c95a929-898d-498c-8eec-4704f93a1c0a („default-src“). index.min.js:1:1547
Content Security Policy: Nastavení stránky zablokovalo načítání zdroje na blob:https://stranka.cz/82257c72-cab2-49b5-8dd2-7d889c3ce480 („default-src“). index.min.js:1:1547
Content Security Policy: Nastavení stránky zablokovalo načítání zdroje na blob:https://stranka.cz/85ebfe83-941c-47c7-af60-9960eed2e5ba („default-src“). index.min.js:1:1547
```

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2021-11-02 09:22
@bethanylang @jamesozzie the user reported this was caused by the [PublishPress Capabilities](https://wordpress.org/plugins/capability-manager-enhanced/) plugin. I'm not sure how this would happen (maybe similar to other issues we've had with Admin Menu Editor) but I wasn't able to reproduce the issue just by activating that plugin.

Is this worth investigating any further?

**Comment by bethanylang** [comment] 2021-11-02 13:52
@aaemnnosttv Thanks for taking a look. We haven't had any other reports, so I'm closing this out.

**Closed by bethanylang** 2021-11-02 13:52 UTC
Labels: Type: Support
