### ISSUE TITLE
Only render widget area when there are widgets

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2021] opened 2020-09-14 19:03 UTC
There is one minor thing still missing in the new widget API, which is correct handling of widget areas without widgets. At the moment, widget areas via the new API and components are always rendered, regardless of whether they actually include active widgets. Widget areas should only be rendered if they include active widgets.

This should both consider whether a widget area has widgets overall (this should be obvious), but also whether it has active widgets (i.e. if all widgets of an area return `null`, the widget area should be omitted as well).

Follow-up to #1300 and #1678.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A widget area via the new API should only be rendered if there are actual widgets to display inside it (i.e. **active widgets**).

## Implementation Brief

Edit `WidgetAreaRenderer` within `js/googlesitekit/widgets/components/WidgetAreaRenderer.js`

* Return `null` if `widgets.length === 0`
* Refactor `activeWidgets` to be handled directly within `WidgetAreaRenderer` without passing `activeWidgets` and `setActiveWidgets` to `WidgetRenderer`
  * Replace use of `useState`, set value of `activeWidgets` using `widgets.filter( isActiveWidget )`
    * See comment for `isActiveWidget` filter implementation: https://github.com/google/site-kit-wp/issues/2021#issuecomment-698894816
* Return `null` if `activeWidgets.length === 0`
* Modify `widgetClassNames` to account for `activeWidgets` being an array rather than an object
  * Use `activeWidgets.length` within `[].fill( ... )` call
  * Iterate over `activeWidgets` via `activeWidgets.forEach`
    * Can safely remove conditional & early return that checks if active widget as array only includes active widgets
* Modify `widgetOutput` to map over `activeWidgets` rather than `widgets`
* Modify `widgetOutput`, remove `activeWidgets` and `setActiveWidgets` props from `WidgetRenderer` component

Edit `WidgetRenderer` within `js/googlesitekit/widgets/components/WidgetRenderer.js`

* Remove use and logic associated with `activeWidgets` & `setActiveWidgets`, there are 2 conditionals that call `setActiveWidgets` with early `null` returns, these are no longer necessary as non-active widgets are not rendered.

## QA Brief

* Activate Site Kit in a development build without the AdSense module active.
* Prior to this fix, the **new** widget areas would include an empty "Earnings" area.
* After this fix, the "Earnings" area should not be present because it doesn't include actual content.
    * Activating AdSense should make the "Earnings" area appear again because now there _is_ content.

## Changelog entry

* Enhance new widget API so that only widget areas that have active widgets are rendered.

**Comment by felixarntz** [comment] 2020-09-22 22:25
@caseymorrisus IB mostly LGTM, one follow-up question: I'm not sure about this, but I was thinking that the check for whether `activeWidgets` is empty needs to happen after https://github.com/google/site-kit-wp/blob/1.16.0/assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js#L160? That's where the widget component is rendered, i.e. that's where the logic to determine whether it is active is run, so my trail of thought is we need to run it always, because otherwise it wouldn't work as expected (e.g. if a widget is inactive but a later state change makes it active). Is that something you considered?

**Comment by caseymorrisus** [comment] 2020-09-24 14:11
@felixarntz I looked into this previously, it's a little trickier. Line 160 is where the array of components is defined (`widgetsOutput`), it isn't rendered until line 199. `setActiveWidgets` is called within the render method of `WidgetRenderer` (items within `widgetsOutput`). This means that `activeWidgets` isn't updated until the 2nd render of the `WidgetAreaRenderer` component (calling `setActiveWidgets` within child components triggers a re-render). The updated value for `activeWidgets` is available anywhere within the render method after line 111, https://github.com/google/site-kit-wp/blob/1.16.0/assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js#L111. 

As a side note, I noticed that we're calling `setState` within the render method of `WidgetRenderer` which will throw an error if React is upgraded. This can be fixed by wrapping the `setActiveWidget` calls within `useEffect` but it should be noted that this slightly modifies rendering order/behavior (`useEffect` will wait for all `widgetOutput` components to render before calling `setActiveWidget`). This should not affect expected behavior in this instance.

**Comment by felixarntz** [comment] 2020-09-24 17:01
@caseymorrisus 
> I looked into this previously, it's a little trickier. Line 160 is where the array of components is defined (`widgetsOutput`), it isn't rendered until line 199.

Based on this, the piece that I'm wondering about is the following: If a widget component is executed, returns `null` and is therefore set as inactive by `WidgetRenderer` (we use a hack for that calling the component function directly), afterwards my understanding is that `WidgetAreaRenderer` won't render it again. Which that itself is of course the expected result. But if the widget component is then not executed again, it wouldn't be able to e.g. no longer return `null` (if the datastore state changed for it to actually render something for example). I'm not a React pro so maybe I'm misunderstanding something conceptually here in how React works, but I'm worried about that a widget that at any point returns `null` will never show up, even if the datastore state later would mean that it should.

Regarding this and the `setState` change you mentioned, can you add these things to the IB to explain in more detail?

**Comment by caseymorrisus** [comment] 2020-09-25 12:14
@felixarntz The `WidgetAreaRenderer` component will re-render any time an action is dispatched to the selected Redux store, triggered by the `useSelect` hook. This ensures that the returned value of `useSelect` is always up to date with Redux store changes (only actions should update the store, direct mutation is an anti-pattern). Let me know if the following refactor is okay with you and I'll add this to the IB and modify the estimate.

Taking another look at how `WidgetAreaRenderer` and `WidgetRenderer` are set up, we can refactor things a tiny bit to simplify the logic, fix the `setState` call in render issue, and avoid unnecessary renders. Rather than using `useState` within `WidgetAreaRenderer` and passing the `setActiveWidget` functions to later be called in render of `WidgetRender`, we can handle all of this logic within `WidgetAreaRenderer` directly.

```js
// within render of WidgetAreaRenderer.js
const isActiveWidget = ( widget ) =>
  widgets.find( ( item ) => item.slug === widget.slug ) &&
  typeof widget.component === 'function' &&
  widget.component( {} );

const activeWidgetsArray = widgets.filter( isActiveWidget );
```

This removes the need for `useState` within `WidgetAreaRenderer` and passing `setActiveWidget` to `WidgetRenderer` components. This removes a significant amount of logic out of the `WidgetRenderer` component, it is no longer needed if `activeWidgets` is handled within the parent using the logic above. Unnecessary renders are avoided in situations where widgets are both active and inactive.

**Rendering Chain Active Widget (with useState & setActiveWidget):**
1. WidgetAreaRenderer (`activeWidgets: {}`) - initial render
2. WidgetRenderer (`activeWidgets: {}`) - initial render
3. WidgetAreaRenderer (`activeWidgets: { foo: true }`) - update caused by `setActiveWidget` within `WidgetRenderer`
4. WidgetRenderer (`activeWidgets: { foo: true }`) - update caused by `activeWidgets` prop change

**Rendering Chain Active Widget (with `widgets.filter(...)` within `WidgetAreaRenderer`):**
1. WidgetAreaRenderer (`activeWidgets: { foo: true }`) - initial render
2. WidgetRenderer - initial render, no need to pass `activeWidgets`, was only used to render `null` which is now handled via `widgets.filter(...)`

**Rendering Chain Inactive Widget (with useState & setActiveWidget):**
_Same as Rendering Chain Active Widget (with useState & setActiveWidget), 4 renders._

**Rendering Chain Inactive Widget (with `widgets.filter(...)` within `WidgetAreaRenderer`):**
1. WidgetAreaRenderer (`activeWidgets: { foo: true }`) - initial render

**Comment by felixarntz** [comment] 2020-10-01 01:01
@caseymorrisus Sorry for the delayed response, and thanks for outlining this in so much detail. Your suggested approach sounds great to me, so this should be good once you've updated the IB. Once you've done so, feel free to reassign to me for review.

**Comment by felixarntz** [comment] 2020-10-01 02:07
IB ✅

**Comment by felixarntz** [comment] 2020-10-08 22:25
Moving this out of the upcoming release because it's not super critical (only affects development code).

**Comment by cole10up** [comment] 2020-10-18 21:08
**Tested**

Installed, activated and setup latest SK development build.

Checked dashboard without Adsense module activated:
![image](https://user-images.githubusercontent.com/57115907/96385786-fcb67480-114a-11eb-97f8-2aaf83cb646f.png)

Activated Adsense and confirmed earnings area is present.
![image](https://user-images.githubusercontent.com/57115907/96385823-3ab39880-114b-11eb-8f26-fdfbb8879b1a.png)

Confirmed Adsense functions properly for non widget. 

Passed QA ✅

**Comment by cole10up** [comment] 2020-10-18 22:10
Team has been notified about the double Analytics blocks in the search console widget in the 1st screenshot.

**Closed** 2020-10-26 18:48 UTC
Labels: P0, Type: Enhancement
