### ISSUE TITLE
Implement the full-tile error states for the Audience Tile

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8147] opened 2024-01-24 17:40 UTC
## Feature Description

Implement the error handling for Audience Tiles for the cases where an error occurs when retrieving the audience data.

Note that this entails showing the [Audience Tile Error](https://github.com/google/site-kit-wp/issues/8228) when an individual tile is in the error state, or the [Full Width Error Banner](https://github.com/google/site-kit-wp/issues/8230) in the case where all audience tiles are in an error state.

See [audience tiles > error states](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.b9x8clic313y) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- If an error occurs while retrieving the data for an audience, while other audiences in the selection have their data retrieved successfully:
  - The Audience Tile Error should be displayed instead of the Audience Tile for that audience, in the appropriate variant.
    - If a permission error is returned by one or more of the reports, the "insufficient permissions" variant of the error banner will be shown (see the AC for https://github.com/google/site-kit-wp/issues/8228).
    - Otherwise, the catch-all variant will be shown. Clicking the **Retry** button will retry the failed report(s).
- In the case where an error occurs while retrieving data for _all_ of the selected audiences:
  - The Full Width Error Banner should be displayed in the appropriate variant.
    - If a permission error is returned by one or more of the reports, the "insufficient permissions" variant of the error banner will be shown (see the AC for https://github.com/google/site-kit-wp/issues/8230).
    - Otherwise, the catch-all variant will be shown. Clicking the **Retry** button will retry the failed report(s).
  - The Audience Tiles and Info Notice should not be displayed.
- Note that error handling for syncing the audience selection will be handled separately, via #8190.

## Implementation Brief

In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTiles.js`:

* [x] Retrieve all the following report errors using the `getErrorForSelector` by passing the appropriate report options:
  - **For all tiles** (these reports apply to all tiles and should be handled collectively):
    - [x] `reportOptions`
    - [x] `totalPageviewsReportOptions`
  - **For individual tiles** (these reports apply to individual tiles and should be checked per `audienceResourceName`):
    - [x] `topCitiesReportOptions`
    - [x] `topContentReportOptions`
    - [x] `topContentPageTitlesReportOptions`
* [x] Create two local states to store errors:
  - [x] `individualTileErrors`: To track errors for each specific audience tile, especially for the per-tile reports (`topCitiesReportOptions`, `topContentReportOptions`, `topContentPageTitlesReportOptions`).
  - [x] `allTilesError`: To determine if errors occur in the reports that apply to all tiles collectively (`reportOptions` and `totalPageviewsReportOptions`), indicating that a full-width error banner should be displayed.
* [x] Use a `useEffect` hook to manage the error handling process:
  - [x] Loop through the `configuredAudiences` array.
  - [x] For each `audienceResourceName`, check if there are any errors associated with the per-tile reports (`topCitiesReportOptions`, `topContentReportOptions`, `topContentPageTitlesReportOptions`).
  - [x] Collect and store any found errors in the `individualTileErrors` state, mapping each `audienceResourceName` to its corresponding errors.
  - [x] Separately, check for errors in the collective reports (`reportOptions` and `totalPageviewsReportOptions`). If errors are found in these, set `allTilesError` to `true`.
  - [x] After collecting all errors, if every `configuredAudiences` entry has associated errors for the per-tile reports, or if there are errors in the collective reports, set `allTilesError` to `true`.
* [x] In the rendering logic:
  - [x] Conditionally render the `AudienceSegmentationErrorWidget` component if `allTilesError` is `true`, passing in all collected errors:
    - [x] Use `Object.values( individualTileErrors ).flat()` to consolidate all errors into a single, flat array.
    - [x] Combine these with any errors from the collective reports (`reportOptions`, `totalPageviewsReportOptions`) and pass this combined array to the `AudienceSegmentationErrorWidget` component as the `errors` prop.
  - [x] If `allTilesError` is `false`, and if an error exists in `individualTileErrors`, render the `AudienceTileError` component within the `Widget` directly within `AudienceTiles` (inside `visibleAudiences.map()`), passing the `errors` prop.
  - [x] If no error exists, render the `AudienceTile` component.
* [x] Lift the `AudienceTileLoading` logic into `AudienceTiles`:
  - [x] Move the `AudienceTileLoading` logic into `AudienceTiles` (inside `visibleAudiences.map()`) and conditionally render `AudienceTileLoading` directly in `AudienceTiles` based on the loading state before checking for errors or rendering the `AudienceTile` component.

In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.js`:

* [x] Remove the `AudienceTileLoading` component from the `AudienceTile` component as it will now be handled in `AudienceTiles`.
* [x] As we are now handing the loading state in `AudienceTiles`, remove the unnecessary props.

#### Hide the `InfoNoticeWidget` component when an error occurs:

In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationErrorWidget.js`:

* [x] Within a `useEffect` hook, set the global state to hide the `InfoNoticeWidget` using the `setValue` action from the `CORE_UI` store.
* [x] Implement the `handleRetry` callback function to reset the state (using `setValue` from `CORE_UI`) to show the `InfoNoticeWidget` again once the errors are cleared.
* [x] Pass the `handleRetry` function to the `onRetry` prop of the `ReportErrorActions` component.

In `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/InfoNoticeWidget/index.js`:

* [x] Retrieve the global state value which was set in `AudienceSegmentationErrorWidget` to hide the `InfoNoticeWidget` component.
* [x] Do not render the `InfoNoticeWidget` component if the global state value is set to `true`.
* [x] Otherwise, render the `InfoNoticeWidget` component as usual.

### Test Coverage

* Add storybook stories for the individual and full-width error states in `AudienceTilesWidget/index.stories.js` and `AudienceTile/index.stories.js.`
* Add test coverage for the individual and full-width error states in `AudienceTilesWidget/index.test.js`.
* Fix any broken stories.
* Fix any broken tests.

## QA Brief

Note: 
* Make sure https://oi.ie is added as "Custom Site URL" in tester settings.

* It may happen that the IDs given for `Returning visitors` and `All visitors` may get changed in case the audiences have been archived and re-created in Google Analytics. In this QAB, ID for `Returning visitors` is `8587716470` and `All visitors` is `2786548370 `. It's better to run `googlesitekit.data.select( 'modules/analytics-4' ).getAvailableAudiences();` command in browser and confirm the IDs for these audiences and replace with the correct one in case those are changed.

1. Enable the audience segmentation feature and enable `Visitor groups` in Site Kit settings.

2. Select `Returning visitors` and `All visitors` to show in audience tiles widget area from the selection panel.

3. Using the [Tweak](https://chromewebstore.google.com/detail/tweak-mock-and-modify-htt/feahianecghpnipmhphmfgmpdodhcapi?hl=en) Chrome extension, create a rule as follows.

**Rule 1**

  * URL: `.*/wp-json/google-site-kit/v1/modules/analytics-4/data/report.*8587716470.*`
  * Enable the use of regular expressions `(.*)`
  * HTTP Method: `GET`
  * Status code: `500`
  * Response payload.
  ```js
    {
      "code": 500,
      "message": "Some Error",
      "data": {
        "status": 500,
        "reason": "Some Reason"
      }
    }
  ```

**Rule 2**

  * URL: `.*/wp-json/google-site-kit/v1/modules/analytics-4/data/report.*8587716470(?!.*2786548370).*`
  * This will ensure to return error only when the data is requested for `8587716470` only and no other audience resource name (`2786548370`) is present in the request
  * Enable the use of regular expressions `(.*)`
  * HTTP Method: `GET`
  * Status code: `500`
  * Response payload.
  ```js
    {
      "code": 500,
      "message": "Some Error",
      "data": {
        "status": 500,
        "reason": "Some Reason"
      }
    }
  ```

4. In `Applications > Session storage` (in chrome) search for `report` and clear all report data.

#### Single tile error

  * Enable rule 2 above in tweak and refresh the dashboard, make sure there are no reports in session storage so that request can be intercepted.

  * Notice that `Returning visitors` tile should show error.

  * `All visitors` tile should show the data properly.

#### All tiles error
  * Enable rule 1 above in tweak and refresh the dashboard, make sure there are no reports in session storage so that request can be intercepted.

  * Notice that full width error banner is shown and no tile will be shown.

  * Also, info notice banner #8137 is not shown when full width error banner is being displayed.

## Changelog entry

* Show an Audience Tile in an error state if an error occurred while retrieving its data; show a combined error state if all audiences have an error.

**Comment by techanvil** [comment] 2024-01-30 19:41
Note, I've moved this to the backlog pending the addition of the [full width error state](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.xfl89g3zosvd) as a GitHub issue, which this issue may depend on.

**Comment by techanvil** [comment] 2024-02-06 10:46
The full width error state is now defined and added as a dependency for this issue, which is ready for AC.

**Comment by techanvil** [comment] 2024-03-28 14:20
Hi @hussain-t, just letting you know I've moved this back to Backlog as the final [in-progress changes to the design doc](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit?disco=AAABJiKQwSo), relating to audience caching, will probably affect the AC for this one (we probably need to handle an audience sync error here). Please feel free to get preliminary AC ready in the meantime.

**Comment by techanvil** [comment] 2024-04-05 14:45
Hi again @hussain-t! As the audience caching aspect of the design doc has been sufficiently finalised, I've moved this back to AC.

**Comment by techanvil** [comment] 2024-08-13 15:42
Thanks @hussain-t, nice work here so far on the IB. A couple of points:

> * [ ] Retrieve all the following report errors using the `getErrorForSelector` by passing the appropriate report options:
>   - [ ] `reportOptions`
>   - [ ] `totalPageviewsReportOptions`
>   - [ ] `topCitiesReportOptions`
>   - [ ] `topContentReportOptions`
>   - [ ] `topContentPageTitlesReportOptions`

It's worth bearing in mind that `reportOptions` and `totalPageviewsReportOptions` are both for reports that apply to _all_ tiles rather than per-tile. We should clarify this in the IB and consider how they will need to be handled differently to the other reports.

> * [ ] Modify the `AudienceTile` component to accept a new `error` prop.
> * [ ] Conditionally render the `AudienceTileError` component with in the `Widget` when an `error` is present.
> * [ ] Pass the `error` prop to the `AudienceTileError` component.

Hmm, I think it would be cleaner to conditionally render `AudienceTileError` directly in `AudienceTiles` rather than in `AudienceTile`. That way we can return early in the map over `visibleAudiences` rather than going through all the irrelevant logic of extracting the various data points (and running the various unneeded `useSelect()` calls in `AudienceTile`). We might want to lift the render of `AudienceTileLoading` out to `AudienceTiles` at some point for the same reason.

**Comment by techanvil** [comment] 2024-08-14 09:57
Thanks @hussain-t! Nice work, that LGTM.

IB :white_check_mark:

**Comment by techanvil** [comment] 2024-08-15 11:19
Hey @hussain-t, while working on the IB for #8190 I've noticed that one detail of the AC has been missed in the IB here.

> - In the case where an error occurs while retrieving data for _all_ of the selected audiences:
>   - ...
>   - The Audience Tiles and Info Notice should not be displayed.

As per the above point, we need to ensure the Info Notice is not displayed when we are showing the Full Width Error Banner. Please can you update the IB accordingly?

**Comment by hussain-t** [comment] 2024-08-15 16:11
Thanks, @techanvil. I've updated the IB.

**Comment by techanvil** [comment] 2024-08-16 11:45
Thanks @hussain-t! IB :white_check_mark: once again :)

**Comment by techanvil** [comment] 2024-08-22 12:34
Nice work on the QAB here @ankitrox. One suggestion - it's possible the audience IDs will change in the future if they are archived and recreated. So, I will suggest adding a point to run `googlesitekit.data.select( 'modules/analytics-4' ).getAvailableAudiences()` in the JS console and cross reference the IDs to make sure they are correct:

![image](https://github.com/user-attachments/assets/affe2a01-1537-4416-aaeb-16dc10c76509)

**Comment by techanvil** [comment] 2024-08-23 13:57
Hey @ankitrox, nice work on the PR which I have merged. Please can you take a look at my comment above re. the QAB.

**Comment by ankitrox** [comment] 2024-08-23 15:25
Hi @techanvil ,

Sorry for missing the QAB update. I've updated the QAB and added the point as note at the top of QAB.

**Comment by kelvinballoo** [comment] 2024-08-26 12:44
### QA update ⚠️ 

Hi @ankitrox , I tried to do a happy scenario without any rules on the tweak extension but I hit a permission error.
The permission error does appear in the dev console but doesn't appear in the FE. 
Is that expected?

Refer to the video below. Happy to jump on a call to discuss this.
<Details>

https://github.com/user-attachments/assets/5e40a65c-01d1-45d8-a232-2fa044d54e57


</Details>

**Comment by kelvinballoo** [comment] 2024-08-26 15:42
Confirmed with @ankitrox that the issue raised would be fixed under https://github.com/google/site-kit-wp/issues/8179 

Will continue testing this ticket.

**Comment by kelvinballoo** [comment] 2024-08-27 08:06
### QA update ⚠️ 

@ankitrox , given that there is an error and the panel doesn't show up...I'm eventually blocked because I can't do this part of the QAB:
`Select Returning visitors and All visitors to show in audience tiles widget area from the selection panel.`

Let me know if I missed anything or how best to navigate this.
Happy to jump on a call if that's easier.

**Comment by techanvil** [comment] 2024-08-29 17:07
Hi @kelvinballoo, thanks for raising these issues.

> **ITEM 1:** ⚠️ For the 2nd scenario where the full width error appears, the Info notice doesn't appear as expected. However, if I click on 'Retry', it will appear for a brief second before disappearing again. I think it would be a better experience if it doesn't show up, at least until there is no error detected.

Good shout, however the intention here is for the widget to show in its loading state while the reports are being retried. I've created a followup PR which fixes this: https://github.com/google/site-kit-wp/pull/9254

> **ITEM 2: Clarification** ⚠️ I tried to interchange the audience numbers for rule 2 such that 'All Visitors' would hit error and not 'Returning Visitors' but when I did it, the full width error banner showed up. I was expecting only the 'All Visitors' tile to have error. Or we can't really test it this way?
 
The audiences appear in a fixed order in the request URL, so to reverse the scenario, you'll need to keep the IDs in the same order but adjust the regular expression syntax as follows:

`.*/wp-json/google-site-kit/v1/modules/analytics-4/data/report(?!.*8587716470).*2786548370.*`

> **ITEM 3:** ⚠️ **Scenario 1:** Full width error banner On mobile and iPad mini, you will see at the top of the tile, the corners are square. It should have been rounded.
> ...
> **Scenario 2:** Two tiles with only one error In this scenario, the top corners should have been squared but they are rounded.

This is another good spot, I've included a fix for this in my followup PR.

**Comment by kelvinballoo** [comment] 2024-09-05 09:09
### QA Update ⚠️  

Thanks @techanvil 
This has been verified good overall. Just need your confirming on ITEM 1.

**ITEM 1** ⚠️ 
For item 1, I re-tested this and noticed that you have put the tiles in loading state. Agreed on that.
Just confirming as well that, it's fine for the 'Info notice' to appear below them, because it's part of the loading state?
<Details>
<img width="1074" alt="Screenshot 2024-09-05 at 13 00 54" src="https://github.com/user-attachments/assets/97318c23-4473-4d53-9490-e683c7b19c4c">

</Details>

______________________________________________

ITEM 2 ✅ 
Noted on that. I was able to do the proper change in the URL and I could interchange the positions.
Looking as expected.
<Details>
<img width="1185" alt="Screenshot 2024-09-05 at 12 53 52" src="https://github.com/user-attachments/assets/28b42611-451c-4dfc-b1b8-9d7bb168b7e1">
</Details>

______________________________________________

ITEM 3 ✅ 
The tiles on mobile and desktop are appearing as expected now.
<Details>
2/3 tiles present:
<img width="491" alt="Screenshot 2024-09-05 at 12 48 01" src="https://github.com/user-attachments/assets/0f34d7af-c359-4282-bb4c-b43565b85ea3">

<img width="540" alt="Screenshot 2024-09-05 at 12 48 21" src="https://github.com/user-attachments/assets/a6bef2a9-ad7f-4c35-a044-f2f229c2868a">

1 tile only present:
<img width="461" alt="Screenshot 2024-09-05 at 12 46 44" src="https://github.com/user-attachments/assets/dcdb5881-8e82-4306-a594-e68a732304ac">

</Details>
<img width="475" alt="Screenshot 2024-09-05 at 12 46 36" src="https://github.com/user-attachments/assets/e6156327-249a-4be7-9782-b5b474deedbb">

**Comment by techanvil** [comment] 2024-09-05 09:17
> **ITEM 1** ⚠️ For item 1, I re-tested this and noticed that you have put the tiles in loading state. Agreed on that. Just confirming as well that, it's fine for the 'Info notice' to appear below them, because it's part of the loading state?
> 
> <img alt="Screenshot 2024-09-05 at 13 00 54" width="1074" src="https://private-user-images.githubusercontent.com/125576926/364703847-97318c23-4473-4d53-9490-e683c7b19c4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1Mjc3MTAsIm5iZiI6MTcyNTUyNzQxMCwicGF0aCI6Ii8xMjU1NzY5MjYvMzY0NzAzODQ3LTk3MzE4YzIzLTQ0NzMtNGQ1My05NDkwLWU2ODNjN2IxOWM0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQwOTEwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTMyOGUxNjY5ZDJlYTM0MjI0MDM0YTlkMTFjOTllZjExNDg4MWI3MzcwNTZjMmM4MDI5ZTc3MGM3ODFmYjkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tQImuVzwTtaEHdL_k_DIsAFWUaEgIliltcOMwdnK5uE">

Thanks @kelvinballoo, this is indeed expected for now. We do have an issue to only show the info notice when there is relevant data for it, which implies it won't show up while the tiles are in the loading state, but this is currently in the backlog for post-launch:
https://github.com/google/site-kit-wp/issues/8140

**Comment by kelvinballoo** [comment] 2024-09-05 10:13
### QA Update ✅ 

Great, thanks for the confirmation @techanvil .
Moving this ticket to approval.

______________________________________________

I was able to do the proper change in the URL and I could interchange the positions. ✅
Looking as expected.
<Details>
<img width="1185" alt="Screenshot 2024-09-05 at 12 53 52" src="https://github.com/user-attachments/assets/28b42611-451c-4dfc-b1b8-9d7bb168b7e1">
</Details>

______________________________________________

The tiles on mobile and desktop are appearing as expected. ✅ 
<Details>
2/3 tiles present:
<img width="491" alt="Screenshot 2024-09-05 at 12 48 01" src="https://github.com/user-attachments/assets/0f34d7af-c359-4282-bb4c-b43565b85ea3">

<img width="540" alt="Screenshot 2024-09-05 at 12 48 21" src="https://github.com/user-attachments/assets/a6bef2a9-ad7f-4c35-a044-f2f229c2868a">

1 tile only present:
<img width="461" alt="Screenshot 2024-09-05 at 12 46 44" src="https://github.com/user-attachments/assets/dcdb5881-8e82-4306-a594-e68a732304ac">

</Details>
<img width="475" alt="Screenshot 2024-09-05 at 12 46 36" src="https://github.com/user-attachments/assets/e6156327-249a-4be7-9782-b5b474deedbb">

______________________________________________

The errors are showing up accordingly. ✅ 
<Details>
Rule 2 active:
<img width="1223" alt="Screenshot 2024-08-29 at 15 38 46" src="https://github.com/user-attachments/assets/4ae6ccbf-3bcf-4ba1-878f-5d9dfbf06e3b">

Rule 1 Active:
<img width="1206" alt="Screenshot 2024-08-29 at 15 43 50" src="https://github.com/user-attachments/assets/e606bc7a-576b-47a6-b29d-2292dd032409">

</Details>

**Comment by aaemnnosttv** [comment] 2024-09-05 16:23
@kelvinballoo it looks like only the catch-all error case was tested here. Was the permissions error case also tested as mentioned in the AC?

**Comment by kelvinballoo** [comment] 2024-09-05 16:39
@aaemnnosttv , apologies! Yes, only the catch-all error was tested. Missed out on the permissions error.

@ankitrox , could you update the QAB for how to test for the Permissions error please?

**Comment by kelvinballoo** [comment] 2024-09-05 17:17
### QA Update ✅ 

Permissions error variant tested by changing the tweak extension response to:
```
{
  "code": 403,
  "message": "Insufficient Permissions Test Error",
  "data": {
    "status": 403,
    "reason": "insufficientPermissions"
  }
}
```

The Permission error variant appeared accordingly and is looking good on desktop, mobile and tablet viewports.
- All tiles error ✅
   <Details>
   <img width="1089" alt="Screenshot 2024-09-05 at 20 58 45" src="https://github.com/user-attachments/assets/52b74e41-c800-40d0-83b1-04395ed1a478">
   
   <img width="484" alt="Screenshot 2024-09-05 at 20 59 00" src="https://github.com/user-attachments/assets/fd3b4370-e03a-48a2-8689-9872492a65cc">
   
   
   <img width="478" alt="Screenshot 2024-09-05 at 21 06 36" src="https://github.com/user-attachments/assets/5b089939-66dc-4981-9e54-9c70c409c84d">

   </Details>

- One tile error: ✅ 
   <Details>
   
   <img width="1213" alt="Screenshot 2024-09-05 at 21 01 00" src="https://github.com/user-attachments/assets/7b959225-8e0e-4b3d-8c1b-ad09d2c22ecb">
   
   
   <img width="494" alt="Screenshot 2024-09-05 at 21 01 42" src="https://github.com/user-attachments/assets/61afd5bb-626f-475a-b906-01211b547af7">

   <img width="400" alt="Screenshot 2024-09-05 at 21 01 56" src="https://github.com/user-attachments/assets/f86cedbf-0875-44ca-ba4e-99b2627ac59e">

   </Details>

____________________
The catch-all variant was tested good already ✅ 
<Details>
1 tile error:
<img width="491" alt="Screenshot 2024-09-05 at 12 48 01" src="https://github.com/user-attachments/assets/0f34d7af-c359-4282-bb4c-b43565b85ea3">

<img width="540" alt="Screenshot 2024-09-05 at 12 48 21" src="https://github.com/user-attachments/assets/a6bef2a9-ad7f-4c35-a044-f2f229c2868a">

<img width="1205" alt="Screenshot 2024-09-05 at 21 14 04" src="https://github.com/user-attachments/assets/d1169be1-ed18-4577-9a58-5ef1c4f62185">



All tiles error:
<img width="461" alt="Screenshot 2024-09-05 at 12 46 44" src="https://github.com/user-attachments/assets/dcdb5881-8e82-4306-a594-e68a732304ac">

<img width="475" alt="Screenshot 2024-09-05 at 12 46 36" src="https://github.com/user-attachments/assets/e6156327-249a-4be7-9782-b5b474deedbb">

<img width="1207" alt="Screenshot 2024-09-05 at 21 13 29" src="https://github.com/user-attachments/assets/f784bce8-7171-4a70-8084-435bc281bb58">




</Details>

**Comment by aaemnnosttv** [comment] 2024-09-05 17:20
Thanks @kelvinballoo !

**Closed by aaemnnosttv** 2024-09-05 17:20 UTC
Labels: P1, Type: Enhancement, Module: Analytics, Team M
