### ISSUE TITLE
Console error when module is not connected when logged in as a second admin user

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#7885] opened 2023-11-20 14:06 UTC
## Bug Description

While testing #7852 I noticed that the same error message appears when you're logged in as the 2nd admin user, and on loading the Site Kit settings screen.  Nahid mentioned that it occurs for a different endpoint, not the `sync-custom-dimensions` one.  

The error message is: `Module is not connected`

![image](https://github.com/google/site-kit-wp/assets/73545194/729739d7-4661-4529-ba46-3e90223f0539)

## Steps to reproduce

1. Login and connect Site Kit with a 2nd admin user. 
2. Make sure that Analytics is connected. 
3. Go to the Site Kit admin screen and observe error in console. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by kelvinballoo** [comment] 2024-08-30 15:55
@wpdarren ,

I've tried to recreate it but it seems like I can't reproduce it anymore.
Steps taken were as described in the ticket. Plugin was set to 'latest release' with no feature flag enabled.

- Login and connect Site Kit with a 2nd admin user.
- Make sure that Analytics is connected.
- Go to the Site Kit admin screen and observe error in console.

There was no error in the console though. We can potentially close this.
<Details>
<img width="1280" alt="Screenshot 2024-08-30 at 19 52 34" src="https://github.com/user-attachments/assets/72d6752d-ad9a-4fdb-b575-d0974fd7ca45">

</Details>

**Closed** 2024-09-02 11:05 UTC
Labels: Type: Bug
