### ISSUE TITLE
Add resolvers for key dependent selectors of `getModules`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4775] opened 2022-02-02 18:43 UTC
## Feature Description

There are a number of selectors on the `core/modules` store that depend on the result from `getModules` which has a resolver while its dependents do not. This results in us needing to await `getModules` manually in some cases which is unintuitive as the result is left unused.

E.g. https://github.com/google/site-kit-wp/blob/9d2f78ea330ac592e0953316a1264867aa398540/assets/js/feature-tours/index.js#L42-L43

Instead, we should add resolvers for a few key selectors such as `isModuleConnected` so that we can simply resolve select it directly.

The resolver itself in this case would only need to await `getModules`, as is already done in some places as well https://github.com/google/site-kit-wp/blob/9d2f78ea330ac592e0953316a1264867aa398540/assets/js/googlesitekit/modules/datastore/modules.js#L464-L466

This keeps the dependency in the store and avoids odd side-effect implementation details to leak out into consuming code.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following selectors of the `core/modules` store should have resolvers added for them which simply await the resolution of `getModules`:
	* `getModule`
	* `isModuleActive`
	* `isModuleConnected`
* Any existing use of `await registry.__experimentalResolveSelect( CORE_MODULES ).getModules()` should be refactored to resolve select the value from the enhanced selector instead (see description above for examples)

## Implementation Brief
* Using `assets/js/googlesitekit/modules/datastore/modules.js`,
	* Add resolvers for the selectors below which should await `getModules`. For e.g: https://github.com/google/site-kit-wp/blob/9d2f78ea330ac592e0953316a1264867aa398540/assets/js/googlesitekit/modules/datastore/modules.js#L464-L466
		* `getModule`
		* `isModuleActive`
		* `isModuleConnected`
* Remove the use of `await registry.__experimentalResolveSelect( CORE_MODULES ).getModules()` prior to calling the above selectors.
* Update the calls of the selectors above to instead use `await registry.__experimentalResolveSelect` to allow time for the resolvers to run and return data.

### Test Coverage
* No new tests to be added.

## QA Brief
* This is an internal change on enhancing the selectors in the AC.
* There should be no visual regressions or JS errors.
* Test the following feature tours, if they load correctly, without any errors: both idea hub tours, all traffic widget tour.
* To trigger a tour,
	* Get all the tours via the `getAllFeatureTours` selector and then dispatch the `triggerTour` action passing the tour object. In the example below, we are triggering the 4th tour from the array.
	```js
	const tours = await googlesitekit.data.select('core/user').getAllFeatureTours();
	await googlesitekit.data.dispatch('core/user').triggerTour(tours[3]);
	```

## Changelog entry

* N/A

**Comment by FlicHollis** [comment] 2022-05-26 08:55
Hi @techanvil are you still planning on working on this? If not, please unassign yourself so someone else can pick up - thanks!

**Comment by techanvil** [comment] 2022-05-26 08:59
Thanks for calling this out @FlicHollis, I've removed my assignment :+1:

**Comment by FlicHollis** [comment] 2022-09-01 14:20
Hey @kuasha420  Same with this one - Has this IB been started? If not, feel free to unassign yourself so that any of the team can pick it up. Thanks so much!

**Comment by hussain-t** [comment] 2022-09-01 14:44
Thanks for calling out @FlicHollis. I have unassigned myself.

**Comment by eugene-manuilov** [comment] 2022-09-23 10:12
> * Remove the use of `await registry.__experimentalResolveSelect( CORE_MODULES ).getModules()` within the codebase.

@asvinb, we can't just remove it from the codebase because it will cause failure. What we need to do is to replace `getModules` calls with a selector name that is actually needed. For example, if a function needs to check whether a module is connected, then we need to replace the resolveSelect call for the `getModules` selector with `const moduleConnected = await registry.__experimentalResolveSelect( CORE_MODULES ).isModuleConnected( slug )`.

**Comment by eugene-manuilov** [comment] 2022-09-23 13:58
> ... basically we no longer need to call `await registry.__experimentalResolveSelect( CORE_MODULES ).getModules()` before calling `getModule`, `isModuleActive` or `isModuleConnected`...

@asvinb, yes, we don't need to call `getModules` anymore, but we do need to call those selectors with `__experimentalResolveSelect` because otherwise selectors will return early with undefined results since resolvers won't be finished yet.

So, instead of https://github.com/google/site-kit-wp/blob/98bd026ca0f95f9db25536c0a99eeb7bf00b97cc/assets/js/feature-tours/all-traffic-widget.js#L41-L47 we should do it this way now:

```js 
const connected = await registry.__experimentalResolveSelect( CORE_MODULES ).isModuleConnected( 'analytics' );
if ( ! connected ) {
    return false;
}
```

**Comment by asvinb** [comment] 2022-09-26 08:19
Thanks @eugene-manuilov ! IB has been updated!

**Comment by eugene-manuilov** [comment] 2022-09-26 08:38
Thanks, @asvinb. IB ✔️

**Comment by aaemnnosttv** [comment] 2022-10-06 19:49
## ⚠️ Approval

Looking at the code, there are a few instances where refactoring was missed, as well as a few places where something was refactored improperly.

Will open a follow-up PR shortly.

**Comment by tofumatt** [comment] 2022-10-06 22:19
Moving this back to QA as a few small changes/refactoring were made to the code so it's worth testing this again before sending to approval again, but the QA steps are the same 👍🏻

**Comment by wpdarren** [comment] 2022-10-07 03:28
### QA Update: ❌ 

@aaemnnosttv @tofumatt the feature tours are triggered other than Idea hub draft posts tour. I've tested this via the forced version option in the tester plugin. Last time around when I was on the posts screen and ran the code in console, it triggered the tour, but it isn't doing that anymore. Could you look into this for me?  

It's saying undefined:
![image](https://user-images.githubusercontent.com/73545194/194461734-08f5fb02-f779-4734-bb62-25b3bf2d3a79.png)

```
 const tours = await googlesitekit.data.select('core/user').getAllFeatureTours();
 await googlesitekit.data.dispatch('core/user').triggerTour(tours[3]);
```

**Comment by asvinb** [comment] 2022-10-07 07:32
@wpdarren Sorry if that was missed in the QAB, but you'll need to delete the `wp_googlesitekitpersistent_dismissed_tours` user meta since we are saving which tours were dismissed in the database. Via WP-CLI, you can use the following command: 
`wp user meta delete 1 wp_googlesitekitpersistent_dismissed_tours`
where `1` is the user id or you delete the meta directly in the database in the `wp_usermeta` table.
Another option would be to set up a new burner site and test 😁

**Comment by wpdarren** [comment] 2022-10-07 07:47
### QA Update: ✅ 

**Verified:** 

- Tested feature tours and they load correctly, without any errors: both idea hub tours (dashboard and pages) and all traffic widget tour. I also tested to make sure that the dashboard sharing and the dashboard navigation menu tour worked too. 
- There are no visual regressions or JS errors.

<details>
 <summary>Screenshots / Screencasts</summary>

https://user-images.githubusercontent.com/73545194/194036880-746d0d58-95ed-4d60-8867-44d7270880fa.mp4

https://user-images.githubusercontent.com/73545194/194036904-a0533254-0e67-48d7-a200-a700080ccfcc.mp4

https://user-images.githubusercontent.com/73545194/194036940-40f1edf1-a5bd-4009-b110-66c3617dfecc.mp4

![image](https://user-images.githubusercontent.com/73545194/194036967-c90492f2-02ae-47cb-91ae-3014162c6db5.png)

</details>

**Closed** 2022-10-07 14:04 UTC
Labels: P2, Type: Enhancement
