### ISSUE TITLE
Analytics module fails set up flow

### ISSUE THREAD

**Issue by amedina** [google/site-kit-wp#11] opened 2019-06-20 14:31 UTC
**Describe the bug**
The flow for setting the Analytics module fails to complete with a blank screen.
**To Reproduce**
1. Activate Analytics module

**Expected behavior**
Displaying analytics properties selection
<img width="1524" alt="Screen Shot 2019-06-20 at 4 27 36 PM" src="https://user-images.githubusercontent.com/506089/59857237-d2974b80-9378-11e9-9814-c93ade1814c4.png">

**System Information (please complete the following information):**
 - Browser: Chrome
 - Plugin Version: beta1

**Comment by eduardogoncalves** [comment] 2019-06-20 14:36
I'm having the same issue #3

**Comment by lucymtc** [comment] 2019-06-21 13:07
@amedina the blocked script execution is expected behaviour, an iframe is used to check existing Analytics and AdSense tags from the front end and prevent scripts from running. It is planned to improve this in the future.

I am not able to reproduce the issue described. Can you provide information of the response to the request made to `get-accounts` in of the console > Network > filter with XHR only? 
Thanks!

**Comment by forcedlogic** [comment] 2019-06-21 16:37
Same here, tried in both firefox and Chrome. Neither will connect. Even deleted and tried readding it and it never connects to Google Analytics.

**Comment by PhotoWorkout** [comment] 2019-06-22 20:36
Hello, same here: Analytics not showing after connecting to analytics account /trying to set up modules in the Site Kit > Analytics Dashboard. 
Error message from chrome browser: 

_Blocked script execution in '<URL>' because the document's frame is sandboxed and the 'allow-scripts' permission is not set._

Search console works ok, but there is a _Data error in Search Console
Rate Limit Exceeded_ in some cases.

**Comment by Fu-San** [comment] 2019-06-23 01:05
@amedina @eduardogoncalves @forcedlogic @PhotoWorkout 
The temporary fix for this seems to add the analytics tracking code in the website header. If it can find the analytics tracking code it shows it and tells that it will be replaced if you remove the old code. Just don't remove it and continue.

**Comment by PhotoWorkout** [comment] 2019-06-23 12:53
Putting the analytics tracking code in the header worked fine to set up the site kit analytics module. 
I have thereafter removed the code from the website header again since I am using google tag manager for injecting the tracking code. The Site Kit seems to work fine after removing the analytics code from the header. I assume it was just needed (once) for the initial activation, which worked just fine. Thanks

**Comment by Fu-San** [comment] 2019-06-23 13:09
> Putting the analytics tracking code in the header worked fine to set up the site kit analytics module.
> I have thereafter removed the code from the website header again since I am using google tag manager for injecting the tracking code. The Site Kit seems to work fine after removing the analytics code from the header. I assume it was just needed (once) for the initial activation, which worked just fine. Thanks

Yeah it keeps the sitekit plugin activated alreight. But it doesn't fix the issue. If you remove the tracking code you won't be able to track any future visitors and only see old data in sitekit plugin.

**Comment by PhotoWorkout** [comment] 2019-06-23 15:23
Thanks for letting me know about tracking future events (and that the tracking code needs to be in the header for that to happen). I have moved it back into the header and removed it from the tag manager. 
It seems all to work fine, I just had to add my Content Groups via the tracking code (which was configured with the Google Tag manager before).

**Comment by lucymtc** [comment] 2019-06-24 09:31
Hi, I have tested across different sites and still unable to reproduce, in order to help debug, can you provide: 

List of other installed plugins
PHP version
WordPress version

Also can you verify the request to `get-accounts` is made in the Network tab of the console? if so, can you provide information of the response to this request?
Thanks!

**Comment by ivankristianto** [comment] 2019-06-24 18:07
@lucymtc I can reproduce this issue and did trace it to these lines: 
https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/setup.js#L796-L798
that's causing the blank dropdown.

To reproduce:
1. Authenticate Site Kit  with Google Accounts that has only 1 GA account
2. Activate GA service.

**Closed** 2019-06-26 13:33 UTC
Labels: Bug, P0
