### ISSUE TITLE
Provide support for an Google Ads conversion tag

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4834] opened 2022-02-10 11:15 UTC
## Feature Description

For Google Ads users who are looking to ad conversion tracking to their Site Kit enabled site consider integrated support to make the process easier. 

Any such feature would likely involve a text area where users can input their event snippet. 

At present Site Kit users can setup ads conversion tracking via one of the following:
1. Use Google Tag Manager with a Site Kit placed GA snippet (via an "Google Ads Conversion Tracking") tag
2. Using a manually placed snippet that includes an event snippet

<details>
<summary>Sample conversion tracking snippet output 
</summary>

([source - see 'Set up conversion tracking using the global site tag'](https://support.google.com/google-ads/answer/6331314?hl=en#set-up-conversion-tracking-using-the-global-site-tag) )

```
  <html>
  <head>
  <title>Sample HTML File</title>

  <!-- Global site tag (gtag.js) - Google Ads: 123456789 -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=AW-123456789"></script>
  <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'AW-123456789');
  </script>

  <!-- Event snippet for Example conversion page -->
    <script>
      gtag('event', 'conversion', {'send_to': 'AW-123456789/AbC-D_efG-h12_34-567',
        'value': 1.0,
        'currency': 'USD'
      });
    </script>

  </head>
  <body></body>
  </html>
```

</details>

## Additional Resources
- Google Ads Help Center: [Add a conversion tracking tag to your website](https://support.google.com/google-ads/answer/6331314?hl=en)
- Tag Manager Help Center: [Google Ads Conversations](https://support.google.com/tagmanager/answer/6105160)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by locksmithunit** [comment] 2022-04-26 10:09
Ok, i got this post from here:
https://wordpress.org/support/topic/site-kit-not-read-ga4-when-using-tag-manager/#post-15591008


The issue is, i want to understand the implantation of the AW tag from Site Kit ( site kit implant the AW much better than GTM )

**BUT HAVE RULES, AND HAVE RULES TO IMPLANT THE AW TAGS, LIKE CONVERSION LINKER:**
https://support.google.com/tagmanager/answer/7549390?hl=en

After all, Site kit is new.
Tag manager is a couple of years.

Have rules google did, like put remarketing tag with conversion linker (its by default in the google ads instructions)

i don’t want tag manager, and i don’t talk about implanting tag manager. ( i work 6 years with GTM i dont need technical help)
I am actually thinking opposite, i want to get rid of them. (tag manager)

**now, the problem is, before your plugin the implantation was different (by the book of google)**

For example: have the famous **conversion linker.**
**It must be with the REMARKETING tag you’re implanting throe SITE KIT.** (AW-)

Now, site kit don’t show any conversion linker…! ( I KNOW ITS BELONG TO TAG MANGER AND NOT YOU GUYS, BUT HAVE RULES! GOOGLE ADS CREATE IMPLANTATION RULES YOU CAN CHECK IT)

Again, i don’t need you, or tag manager to implanting tags, i work with tag manager for 6 years and Google Ads in different country, believe me, i can teach all the tag manager team how to implant a tag…


You can check it, Conversion Linker is MUST be present with the AW tag
AND AGAIN, I DON’T NEED YOU FOR IMPLANTING TAG IN TAG MANAGER.
I do it by my self and i have container in TAG MANAGER ready for with everything.

I only needs simple answers.
1. You implanted the AW tag with conversion linker and i maybe not see it?

2. It possibly implants the AW tag with you guys and use tag manager for conversion linker?

Send you screenshot throw TAG MANAGER this AW tag MUST conversion linker:
https://ibb.co/1b4VF6P
https://ibb.co/KbFC64n

**Comment by bethanylang** [comment] 2022-04-26 11:38
@locksmithunit We've replied to your questions in regards to Site Kit in your <a href="https://wordpress.org/support/topic/site-kit-not-read-ga4-when-using-tag-manager/">support topic</a>.

As you noted, the conversion linker is part of Google Tag Manager, which is a service that can be connected via Site Kit but is not managed or updated by the Site Kit team. If you have questions about why something has changed in Google Tag Manager, you'll need to reach out to [Google Tag Manager support](https://support.google.com/tagmanager/?hl=en#topic=3441530) directly. 

We'll continue to consider this feature request for a future release, though we don't have a timeline on when or if it may be added to the plugin.

**Comment by locksmithunit** [comment] 2022-04-26 12:04
Common, you're kidding me, read the questions carefully please,
it's not connected to GTM,
it's about the LAWS OF IMPLANTATION!

Conversion Linker MUST BE PRESENT WITH AW TAG!
CONVERSION LINKER IS NOT AW TAG!!!!!!

YOU MUST TELL TO CLIENTS IF IS NEEDED TOGHTER WITH SITE KIT AW IMPLANTATION!!!

Its so simple, yes or no,
add ONLY CONVERSION LINKER?
Or it will not work and i MUST work with GTM?

Is so simple, and this technical quastion only you can answer guys, beacuse site kit implanting the global AW tag!

comeon, comeon guys, i sure you know Google Ads and work before with that,
and i am sure you are smarter then this answer.

**Comment by bethanylang** [comment] 2022-04-26 13:12
@locksmithunit I understand that you're frustrated, but I can assure you that I'm not trying to ignore your question and I'm doing my best to help here.  :)

> beacuse site kit implanting the global AW tag!

Site Kit does not place any AW tags on your site. The only ad-related tags that Site Kit may place are for AdSense, if you have chosen to configure that via Site Kit.

Because the conversion linker is part of Google Tag Manager and AW scripts are from Google Ads – neither of which are part of Site Kit – I unfortunately cannot answer your question. As you know, Site Kit's sole function is to allow users to easily connect Google services like Tag Manager to their WordPress sites. Outside of that basic functionality, we're not able to assist with additional configuration related to each of the services that Site Kit connects to.

I'm sorry that we can't be of more help on your questions, but again, we will consider this feature request for a future release, so feel free to follow this issue for updates.

**Comment by locksmithunit** [comment] 2022-04-26 15:48
**I think we have an English problem and maybe is me ( i admit, where i wrong, i am wrong huh )**

But you're wrong too @bethanylang .
**Google Site kit actually install the AW GLOBAL TAG.**
Look on the head of this page for the topic of @jamesozzie 

**He put the code of the AW! Look, i swear in my life.**

To prove you that, i going send you screenshots as well from my backend:
**This is inside the Site Kit Plugin (right side), and left side this is the Google Ads with the global AW tag:**
https://ibb.co/ZTpdNLs

I marked you everything, 
really, you maybe think i am rocky.

You should listen to me and take me seriously, i am acutely improving the site kit plugin. ( I AM NOT A ROCKY )
**Really, I live and breath Google in all his aspects, from childhood, and professional around the 6 – 7 years.**


For our issue,
**you must understand, have people with families, big business invest their life inside Google Ads**
**Use Google Ads, and all the advertisement / remarketing depend on the AW tag!**
People invest 10K in a day (i am personalty with a budget of a $1000 per day)

**Please try to understand my side.**
I am a developer too and a business owner.
I understand you think i am crazy as you see they moderate me on Wordpress.org
**This is not fair, i provide here facts actually can improve a lot the plugin.**

As you see in the screenshot you're kind of, taking responsibility on this AW implantation... :\

Believe me, i was wish was conversion linker inside Google Site kit, but you didn't give this option...
i want to get rid of Tag Manger, i think this is unprofessional service, running by unprofessional people, old and heavy.
( Even destroy the SEO! - this i do as well )

And i really honest about that, **i prefer go with site kit, and delete GTM... FOREVER!**
But site kit not perfect.
And its more hard to understand how site kit works.
You must provide yours clients this information guys, please common, it's insane.

**Comment by bethanylang** [comment] 2022-04-26 16:48
@locksmithunit Thank you for clarifying. I think you're correct that there may be a miscommunication here.

The Ads Conversion ID option in Settings > Connected Services > Analytics is a basic text entry box that allows you to add your Ads Conversion ID for the purposes of placing it on your site. When you enter text in that field, it is dropped into the following script on the front-end:

`<script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=AW-[whatever you typed in the Ads Conversion ID box]&amp;l=dataLayer&amp;cx=c"></script>`

**This script cannot be modified or updated in any way via Site Kit.** The only thing that Site Kit does is use the Ads Conversion ID entered into that text box to add it into the script that you see above. Site Kit does not manipulate, alter, or otherwise do anything else with that script, nor does it add it unless the user has entered text into the box in the Settings screen. This script cannot be altered in any way when using Site Kit. 

This means that the conversion linker is not included in the script and it is not possible to include it in this script when using Site Kit. I hope this answers your question.

**Comment by bethanylang** [comment] 2022-04-26 18:01
@locksmithunit Again, all that Site Kit does is allow you to add the Ads Conversion ID script and it does not connect to anything else. So no, the conversion linker cannot be linked to the Ads Conversion ID script when it is inserted via the Site Kit setting. You must use GTM for the implementation that you are looking for.

**Comment by locksmithunit** [comment] 2022-04-26 18:31
**Please you so close to understand, we want to combine the two:**

1. Keep the Ads Conversion ID script when it is inserted via the Site Kit setting.

2. Insert ONLY conversion linker throw Google Tag Manager.

**it's possible? it will link automagically? or not?**

Or not? thats it. only this.

**Comment by bethanylang** [comment] 2022-04-26 19:54
@locksmithunit No, it is not possible.

**Comment by locksmithunit** [comment] 2022-05-06 12:21
Hello @bethanylang i come back again after little issue with tag manager team,
they approve my method and when i read the top of the post (screenshot):
https://ibb.co/MknVBdg

now, from what @jamesozzie  says:
`Use Google Tag Manager with a Site Kit placed GA snippet (via an "Google Ads Conversion Tracking") tag
`


In Google Tag Manager, they said the same.

It's mean the GTM (Google Tag Manager container) has only 2 tags.
1. Conversion Linker
2. Conversion Google Ads Conversion Tracking.


Without GA or GA4 inside the GTM.
OR i wrong and @jamesozzie 
**meant to something also?**
You must specify what is the best practice.

I am sorry i all the time digging on the subject is very important to me to understand how its work.
And if Google Tag Manager team actually right. ( i not trust them )

**Comment by locksmithunit** [comment] 2022-05-06 12:38
I only need understand to what @jamesozzie meant, he give 2 options to put the conversion tracker along with Site Kit plugin...
Tag Manager have one answer, and this what i say... (you said is not good)

So i don't know anymore the best practice to do it.

**Comment by bethanylang** [comment] 2022-05-06 12:47
@locksmithunit All I can do is echo what James noted in his original description on this issue:

> At present Site Kit users can setup ads conversion tracking via one of the following:
> 
> Use Google Tag Manager with a Site Kit placed GA snippet (via an "Google Ads Conversion Tracking") tag
> Using a manually placed snippet that includes an event snippet

I can't recommend a particular best practice here as, again, the Site Kit plugin does not do anything in relation to conversion tracking – all I can do is tell you what is possible to set up if you are using Site Kit. If you have questions about best practices for conversion tracking you will need to consult with the Google Tag Manager experts.

**Comment by Yossifsolman** [comment] 2022-05-17 00:38
Look what he wrote:
“ Site Kit placed GA snippet “

So, site kit must implant GA, and old analytics? Where he needs to go?
He didn't specify what with the rest…

Hard to work like that, i still struggling and thinking have some combination must be implanted by SitKit
as @jamesozzie says about  Site Kit placed GA snippet.

GA4 count outbound link, its included conversion tag,
toghter with that you implant the AW the must important tag of Google Ads.

**Comment by marrrmarrr** [comment] 2022-06-24 11:13
Hey everyone, closing this issue as we're looking at how to help Site Kit users better track conversions as a whole topic. 
Among other things, we'll look into the GTM conversion linker and how GA and AdWords work together for tracking particular events.

**Closed by marrrmarrr** 2022-06-24 11:13 UTC
Labels: Type: Enhancement, Module: Analytics

**Comment by Yossifsolman** [comment] 2022-06-24 15:22
It's not a completed answer, guys…
I have the same dilemma, and even Tag Manager team agents don't know the answer.

I think get rid of Tag manager and work without track my call buttons because nobody give me clean answer.

This topic of @jamesozzie was need gives answers to this issue.
But, you didn't give a clean when @locksmithunit asks you all this topic.

1. You should give a clean answer: if we can implant the main AW via your plugin.
2. What needs to be inside GTM in the same time your plugin (example: Conversion Linker and Tracking tag?)

It A-B-C of Google guys... and you should provide us a simple answer what supportive and what not.
**(Support its number 1 rule, if you want your product / plugin to be good.)**

**Comment by jroakes** [comment] 2022-07-29 17:15
Hi @bethanylang.  In the code you shared: 

```<script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=AW-[whatever you typed in the Ads Conversion ID box]&amp;l=dataLayer&amp;cx=c"></script>```

Do you have any idea what the parameter `cx=c` does?  I see this shared around, but no documentation on the parameter anywhere that I can find.  Sorry for coopting this issue, but this parameter causes linked GA4 properties to break when this is used for GA3 tracking.  I thought you might know.

**Comment by bethanylang** [comment] 2022-07-29 18:29
@jroakes Thanks for getting in touch!

That script is pulled directly from GTM and dropped into Site Kit, so it's not coming directly from the plugin. We can do some testing to see if we can replicate your issue and escalate this to the GTM team.

Since this issue is closed and we typically provide support on the WordPress.org support forum for Site Kit, can you please [open a new topic about this there](https://wordpress.org/support/plugin/google-site-kit/)? If you can include some more details about what you're seeing and how the parameter is breaking, that would be very helpful. We can then do testing on our side and follow up with you on your support topic.

I'm going to lock the conversation on this thread now, but we'll see you in the forums!
