### ISSUE TITLE
Improve nonce generation for proxy

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#756] opened 2019-10-31 21:34 UTC
## Feature Description

The nonce generated for the proxy is intentionally not using WordPress nonces
* because they're user-dependent
* because they're not really nonces and valid multiple times

The current mechanism is a proper once-off nonce, however we still use `wp_create_nonce()` to generate that value, which, if used within multiple times within a short timeframe will still generate the same value. We should therefore replace it with a different generator mechanism, such as `wp_generate_password()`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Use `wp_generate_password()` instead of `wp_create_nonce()` when generating the nonce for the proxy setup URL.

## Implementation Brief

* Use `wp_generate_password()` instead of `wp_create_nonce()` when generating the nonce for the proxy setup URL. :)

## Changelog entry

* Use more secure nonce generation mechanism for the authentication service.

**Comment by aaemnnosttv** [comment] 2019-11-01 11:53
IB ✅

**Comment by aaemnnosttv** [comment] 2019-11-20 16:32
This one is not ready to go yet and has introduced a bug since the nonce is not URL encoded; if the nonce contains an ampersand it breaks the value into separate parameters.

### Raw proxy setup URL
![image](https://user-images.githubusercontent.com/1621608/69257422-b3207b00-0bc3-11ea-9d02-c2af3849daad.png)

### Parsed Parameters
![image](https://user-images.githubusercontent.com/1621608/69257528-e19e5600-0bc3-11ea-87d0-25a8242fd682.png)

I will submit a PR for this shortly

**Comment by tofumatt** [comment] 2019-11-20 22:35
Whoops, good catch, sorry 'bout that one 😓

**Comment by aaemnnosttv** [comment] 2019-11-21 11:54
## QA ✅ 

Confirmed that I was able to complete setup using a nonce that contained special characters (particularly an `&`).

![image](https://user-images.githubusercontent.com/1621608/69335911-588c2b00-0c66-11ea-982f-933ec59f4e77.png)

Moving to Approval!

**Closed** 2019-11-21 13:11 UTC
Labels: P1, Size: XXS, Sprint: 11, Type: Enhancement
