### ISSUE TITLE
wp-activation.php fails if Site Kit is network activated on a multisite. New users can't complete registration. 

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#7653] opened 2023-10-02 11:20 UTC
## Bug Description

As [reported by one user in the support forums](https://wordpress.org/support/topic/fatal-php-error-when-activating-user-account), when Site Kit is network activated on a multisite (subdirectory install only), the wp-activation.php page and therefore link to activate a user account is broken. 

In my case when reproducing this the /wp-activation.php link fails only on the parent site and not the child sites. See recording below:
https://www.loom.com/share/b2d7dde73feb42d4a1ee8c543ebd6f23?sid=3b719595-b7ef-434c-959e-00fd1a86c277

The impacted user provided a a string check to bypass the critical error, as per the below (or view the related support topic):
```
if ( ! is_string( $raw_value ) ) {
    return false;
}
```

<details>
<summary>PHP Error trace</summary>

```
PHP Fatal error:  Uncaught TypeError: base64_decode(): Argument #1 ($string) must be of type string, array given in /.../wp-content/plugins/google-site-kit/includes/Core/Storage/Data_Encryption.php:90
Stack trace:
#0 /.../wp-content/plugins/google-site-kit/includes/Core/Storage/Data_Encryption.php(90): base64_decode()
#1 /.../wp-content/plugins/google-site-kit/includes/Core/Storage/Encrypted_Options.php(78): Google\Site_Kit\Core\Storage\Data_Encryption->decrypt()
#2 /.../wp-content/plugins/google-site-kit/includes/Core/Authentication/Credentials.php(65): Google\Site_Kit\Core\Storage\Encrypted_Options->get()
#3 /.../wp-content/plugins/google-site-kit/includes/Core/Authentication/Credentials.php(77): Google\Site_Kit\Core\Authentication\Credentials->get()
#4 /.../wp-content/plugins/google-site-kit/includes/Core/Authentication/Authentication.php(623): Google\Site_Kit\Core\Authentication\Credentials->has()
#5 /.../wp-content/plugins/google-site-kit/includes/Core/Permissions/Permissions.php(335): Google\Site_Kit\Core\Authentication\Authentication->is_setup_completed()
#6 /.../wp-content/plugins/google-site-kit/includes/Core/Permissions/Permissions.php(207): Google\Site_Kit\Core\Permissions\Permissions->map_meta_capabilities()
#7 /.../wp-includes/class-wp-hook.php(310): Google\Site_Kit\Core\Permissions\Permissions->Google\Site_Kit\Core\Permissions\{closure}()
#8 /.../wp-includes/plugin.php(205): WP_Hook->apply_filters()
#9 /.../wp-includes/capabilities.php(842): apply_filters()
#10 /.../wp-includes/class-wp-user.php(777): map_meta_cap()
#11 /.../wp-includes/capabilities.php(985): WP_User->has_cap()
#12 /.../wp-includes/capabilities.php(877): user_can()
#13 /.../wp-content/plugins/google-site-kit/includes/Core/Assets/Assets.php(108): current_user_can()
#14 /.../wp-content/plugins/google-site-kit/includes/Plugin.php(184): Google\Site_Kit\Core\Assets\Assets->register()
#15 /.../wp-includes/class-wp-hook.php(310): Google\Site_Kit\Plugin->Google\Site_Kit\{closure}()
#16 /.../wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#17 /.../wp-includes/plugin.php(517): WP_Hook->do_action()
#18 /.../wp-settings.php(632): do_action()
#19 /.../wp-config.php(111): require_once('...')
#20 /.../wp-load.php(50): require_once('...')
#21 /.../wp-activate.php(12): require('...')
#22 {main}
  thrown in /.../wp-content/plugins/google-site-kit/includes/Core/Storage/Data_Encryption.php on line 90

```

In this case, the array given (`$raw_value`) is
```
array(2) {
  ["oauth2_client_id"]=>
  string(0) ""
  ["oauth2_client_secret"]=>
  string(0) ""
}
```

</details>

## Steps to reproduce

Note: this only happens on PHP 8.0+

1. Set up a multisite network (subdirectory option) 
2. Ensure you can create and then activate user accounts (or that you can access the site via yoursite.com/wp-activate.php). Do this also for the subdirectory sites. 
3. Install Site Kit and network activate  
_(do not setup Site Kit, only activate)_
5. Attempt to activate via email or /activate.php. 
6. A critical error appears (test this again on the parent site and subdomain sites)

## Screenshots
 
![image](https://github.com/google/site-kit-wp/assets/41326532/22916abd-2791-47e1-bbe5-8f69858ed544)

![image](https://github.com/google/site-kit-wp/assets/41326532/85b196f0-8107-44eb-b2b2-ca4df7880542)

## Additional Context

 - SK 1.110.0
 - WordPress 6.3.1
 - PHP 8.2.10
 - [Support topic](https://wordpress.org/support/topic/fatal-php-error-when-activating-user-account) | SH info within support topic
- No invalid XHR response

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No error should be raised on `wp-activate.php`

## Implementation Brief

  * In `Options:has()` after the [existing check](https://github.com/google/site-kit-wp/blob/1b1cbb5181ed1b93adfd22092319ec4785339ee3/includes/Core/Storage/Options.php#L57-L62) for `$notoptions`, include an additional check
    * If `$notoptions` is `false`, then as a fallback, directly query the database to check for the option.
    * Return `true` if the option exists, otherwise return `false`
  * `Data_encryption:decrypt` should have additional safeguards against errors
    * Include additional `OR` check if `$raw_value` is not string in https://github.com/google/site-kit-wp/blob/533c98dc44346cee5c85427fd851107773a4b241/includes/Core/Storage/Data_Encryption.php#L86
    * In https://github.com/google/site-kit-wp/blob/533c98dc44346cee5c85427fd851107773a4b241/includes/Core/Storage/Data_Encryption.php#L90 
      * Rename `$raw_value` variable name to `$decoded_value` -> `$decoded_value = base64_decode( $raw_value, true );` 
      * After renaming the variable, check if `$decoded_value` is `false`. If it is, return the original `$raw_value` immediately.
      * Replace remaining `$raw_value` references
        * In the subsequent lines that use `$raw_value` (e.g., when setting `$iv`, re-setting `$raw_value`, and `decrypting`), replace them with the renamed `$decoded_value`

### To add a bit of context
The `Encrypted_Options->get` method is checking for `Options->has`, and if value is present, it proceeds with decryption. In case of multisite, on `wp-activate` page, WordPress is in installing state so loading of `notoptions` is bypassed and check https://github.com/google/site-kit-wp/blob/1b1cbb5181ed1b93adfd22092319ec4785339ee3/includes/Core/Storage/Options.php#L61 returns`false` which results in ! isset returning `true` so default value which is credentials array goes through and makes to the `decrypt` method, instead of it being returned early in raw value. The problem was present on < php 8 versions, but it was at `warning` level, with php 8+, a lot of warnings were converted to `errors` 

### Test Coverage

* This scenario can be updated in `tests/phpunit/integration/Core/Storage/OptionsTest.php`, and confirming that `decrypt` method properly decodes encrypted values, and returns raw value if passed parameter is not string in `tests/phpunit/integration/Core/Storage/Data_EncryptionTest.php`

## QA Brief

1. Set up a multisite network (subdirectory option) 
2. Ensure you can create and then activate user accounts (or that you can access the site via yoursite.com/wp-activate.php). Do this also for the subdirectory sites. 
3. Install Site Kit and network activate  
_(do not setup Site Kit, only activate)_
5. Attempt to activate via email or /activate.php. 
6. A critical error appears (test this again on the parent site and subdomain sites)
7. Verify there is no fatal error on `wp-activation.php`

## Changelog entry

* Fix bug that could cause an error when activating a new user on multisite when Site Kit isn't set up yet.

**Comment by aaemnnosttv** [comment] 2023-10-06 15:30
After some investigation, I found this only happens with PHP 8+. Thanks @jamesozzie 👍

**Comment by aaemnnosttv** [comment] 2023-10-09 19:28
Thanks for digging into this @zutigrm – this is a strange one 😄 

> * so if `$notoptions` is `false`, return `false` early.

Is it possible that we can ensure it is populated instead? That's essentially what we try to do at the beginning of the method to avoid this in the first place.
https://github.com/google/site-kit-wp/blob/1b1cbb5181ed1b93adfd22092319ec4785339ee3/includes/Core/Storage/Options.php#L54-L55
Do we need to do something else/additional in a MS context?

**Comment by zutigrm** [comment] 2023-10-10 07:25
@aaemnnosttv 
> That's essentially what we try to do at the beginning of the method to avoid this in the first place.

Yup, it is happening in the same context of network id, and it generally works on other dashboard pages, but not on the `wp-activate.php`, which can be due to different multisite/core behaviour

> Is it possible that we can ensure it is populated instead? 

I was looking into this approach first, before suggesting the current fix. But as mentioned in my reply above, this is only happening on `wp-activate`, while it works in all other cases. And digging into core behaviour and reason the `notoptions` cache is not populated here would be going down the rabbit hole, for one occurrence that we might not be able to affect, as it might require adjusting the logic to some later hook, etc. I checked with `is_network_mode()` activated as well, to see when  `network_id` is implicitly used https://github.com/google/site-kit-wp/blob/1b1cbb5181ed1b93adfd22092319ec4785339ee3/includes/Core/Storage/Options.php#L57-L59 which is in this case empty array.
So it might be that either this cache object is not set, or reset, or any other reason core is handling this on `wp-activate` page.

**Comment by aaemnnosttv** [comment] 2023-10-11 18:22
> I was looking into this approach first, before suggesting the current fix. But as mentioned in my reply above, this is only happening on `wp-activate`, while it works in all other cases. And digging into core behaviour and reason the `notoptions` cache is not populated here would be going down the rabbit hole, for one occurrence that we might not be able to affect, as it might require adjusting the logic to some later hook, etc. I checked with `is_network_mode()` activated as well, to see when `network_id` is implicitly used

Taking a look, it seems this is due to WP being in an "installing" state on this page, which bypasses the loading of `notoptions`

https://github.com/WordPress/WordPress/blob/3e66d7d2e4410cadd539ce900c4289f348950c8f/wp-activate.php#L9
https://github.com/WordPress/WordPress/blob/3e66d7d2e4410cadd539ce900c4289f348950c8f/wp-includes/option.php#L163-L212

We can see a similar guard around this being cached in `update_option` and `add_option`.

This should be the only situation where `notoptions` would be `false` I think.

While returning `false` early would avoid the error in this scenario, technically returning true or false based on an invalid `notoptions` is incorrect. In this case, I think we need to extend `Options:has` to fallback to a database query.

We should probably also address the underlying issue where `Encrypted_Options` can attempt to `decrypt` a non-string value, which is the other problem which is raising the error.

**Comment by zutigrm** [comment] 2023-10-12 07:45
@aaemnnosttv Thank you for the feedback and digging into the cause. Suggested approach is definitely a better route to take. Updated IB to reflect on them.

**Comment by aaemnnosttv** [comment] 2023-10-16 19:59
LGTM, thanks @zutigrm !

IB ✅

**Comment by tofumatt** [comment] 2023-10-30 22:34
Assigning to @zutigrm as I won't get to this today—I mostly spent time so far getting my multisite and development environment ready, but he's got that already and has background on this issue 😄

**Comment by wpdarren** [comment] 2023-11-08 11:33
### QA Update:  ✅ 

**Verified:**

- A critical error appears on the parent site and subdomain sites on the latest release. 
- When switching to develop branch, no fatal error on the parent site and subdomain sites appears. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/bb2ec587-3092-43a9-a9f2-f78e41c9a4ca)

</details>

**Closed** 2023-11-16 21:29 UTC
Labels: Type: Bug, Type: Support, P0, PHP
