### ISSUE TITLE
Add the "get help" link to the invalid nonce error message.

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#5482] opened 2022-06-30 14:17 UTC
## Feature Description

When a nonce is expired we show the wp_die screen with a custom message that says that the link has expired and the user needs to try again. We need to add the new "get help" link to the message that will lead users to the `{proxy}/support/?error_id=nonce_expired` URL which can be obtained using the getErrorTroubleshootingLinkURL selector introduced in https://github.com/google/site-kit-wp/issues/5423.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The message generated for the `wp_die` function call in the `Authentication::invalid_nonce_error` method should be updated to have a new "Get Help" link that leads users to the `{proxy}/support/?error_id=nonce_expired` URL.

## Implementation Brief

- In `includes/Core/Authentication/Authentication.php`, inside the `invalid_nonce_error` method:
    - In the last extension for the `$html` variable, locate the `sprintf()` function call.
    https://github.com/google/site-kit-wp/blob/8118271eedb7550fad8505604902d0e39bca5f54/includes/Core/Authentication/Authentication.php#L1466-L1470
     In the `sprintf()` function:
        - Update the string in the first parameter to have a period/full stop at the end followed by an `<a>` tag and another full stop at the end. The `<a>` tag should have:
            - an `href` attribute with the third placeholder as the value.
            - a `target` attribute with `_blank` as the value.
            - The fourth placeholder as the content.
        - The fourth parameter (third placeholder value) should be should be `/?error_id=nonce_expired` appended to the `get_proxy_support_link_url()` method of the same `Authentication` class. It should be escaped with `esc_url()`.
        - The fifth placeholder (fourth placeholder value) should be `Get Help` (translatable).

### Test Coverage

* No tests need to be added/updated.

## QA Brief

- To simulate an invalid nonce error, add the following snippet in the theme's `function.php` file:
```php
add_filter( 'nonce_life', 'wp_nonce_life_filter' );
function wp_nonce_life_filter(){
	return 1;
}
```
- After saving the changes, reset the Site Kit plugin
- Wait for a few seconds after clicking the `Signin with Google` button
- Verify the error screen has the `Get Help` link that takes to the expected URL
![Screenshot 2022-08-03 at 6 51 27 PM](https://user-images.githubusercontent.com/24408261/182654869-32f10a5c-e2d1-4173-9718-9eb09fe9aeee.png)
- Since we modified other places of the code rather than what's defined in the AC, verify both the **Setup** and the **Reset** functionality with and without the token expiration snippet to make sure everything is working as expected.

## Changelog entry

* Add the "get help" link to the error message displayed when an invalid nonce is provided.

**Comment by tofumatt** [comment] 2022-07-27 08:52
IB ✅

**Comment by mohitwp** [comment] 2022-08-10 10:31
### QA Update ⚠️ 

@hussain-t I followed QAB and tried to regenerate error. But I'm not getting any error screen. I reset the plugin waited for 5 mins . But no error page is getting displayed. I'm able to sign in successfully. Tested on old and new website. 

![image](https://user-images.githubusercontent.com/94359491/183880330-8e7b014d-2570-42e2-8f02-1280ec973576.png)

**Comment by hussain-t** [comment] 2022-08-10 10:39
@mohitwp, are you using the `Twenty Twenty` theme?

**Comment by hussain-t** [comment] 2022-08-10 11:25
@mohitwp, I can reproduce it in a site created with InstaWP. Let me know if you want the site URL and the credentials.

**Comment by mohitwp** [comment] 2022-08-10 13:47
### QA Update ✅ 

@hussain-t I'm able to reproduce it using instawp.

- Error screen have 'Get Help' Link.
- Link slug is {proxy}/support/?error_id=nonce_expired
- Link leads user to [support link](https://sitekit.withgoogle.com/documentation/troubleshooting/setup/#link-expired)

- Also, verified reset and sign in functionality without token expiration snippet. It is working as expected.

![image](https://user-images.githubusercontent.com/94359491/183916544-a05fcd52-76fc-4820-97dc-ede43211da66.png)

**Comment by felixarntz** [comment] 2022-08-11 18:52
@hussain-t @mohitwp Not necessarily a blocker to approving this, but looking at the above screenshot in https://github.com/google/site-kit-wp/issues/5482#issuecomment-1210699354, the UI for this looks a bit strange because, other than in most other places with "Get help" links, here the link immediately follows a completely similarly looking link.

I would suggest we move the "Get help" link for this type of notice right after the actual error text, above the "Please try again." link. What do you think @aaemnnosttv? cc @marrrmarrr

**Comment by aaemnnosttv** [comment] 2022-08-15 15:51
@felixarntz thinking about this again, do we need a get help link for an expired nonce? In this situation I think "try again" is the only direction the user needs is it not?

**Comment by felixarntz** [comment] 2022-08-15 15:57
@aaemnnosttv I think the same as for widget errors applies here. It could be that the retry doesn't solve the problem. So at that point we should provide a link to get help.

Maybe we could even use the same format, like: `<a>Please try again.</a> Retry didn't work? <a>Get help</a>`

**Comment by aaemnnosttv** [comment] 2022-08-15 18:11
> It could be that the retry doesn't solve the problem.

@felixarntz in this specific instance, I think retrying would be guaranteed to at least produce a different error if it didn't work since trying again should produce a fresh nonce.

**Comment by felixarntz** [comment] 2022-08-23 21:05
@aaemnnosttv In principle, yes, but when people for example report that in every setup flow at the end they get to this, then probably the same thing went wrong multiple times. So I would argue it still makes sense to provide the "Get help" link here.

Normally I would agree with you, since for a normal WordPress POST request for example it's fairly straightforward (though even there some weird problem could occur, where e.g. validation always fails due to some odd cookie problem). But even more since in our plugin this error can occur as the service is passing around the nonce several times, there's more chance for breakage that can't just be fixed by retrying.

**Comment by aaemnnosttv** [comment] 2022-08-24 17:58
Closing this to reflect that it already went out in the last release. I'll open a new issue for potentially iterating on the format of this and we can resume the discussion there.

**Closed by aaemnnosttv** 2022-08-24 17:58 UTC
Labels: P1, Type: Enhancement, PHP
