### ISSUE TITLE
Improve wording when a user doesn't grant full Analytics permissions

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3307] opened 2021-05-06 12:40 UTC
## Bug Description

In situations whereby a user has successfully connected Site Kit and then decides to connect the Analytics module the notice that appears if they don't grant full permissions could be improved. Users can use Site Kit, and are using Site Kit, just not the Analytics module. 

Change the below:
To **use Site Kit**, you’ll need to redo the setup for Analytics – make sure to approve all permissions at the authentication stage.

To the below or something similar:
To **view Analytics data**, you’ll need to redo the setup for Analytics – make sure to approve all permissions at the authentication stage.

![image](https://user-images.githubusercontent.com/41326532/117298979-ea462300-ae6f-11eb-9de1-53265142dc18.png)

## Steps to reproduce

1. Setup Site Kit
2. Start the Analytics setup process and don't grant full permissions  
3. The messaging as per the screenshot above appears

- Site Kit 1.31.0
- The same may be true for the other modules 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Update error message text to "To view Analytics data, you’ll need to redo the setup for Analytics – make sure to approve all permissions at the authentication stage."
* When there is more than one module that needs permissions, display text _"To view data from $SERVICE1 and $SERVICE2, you'll need to redo the setup for $SERVICE1 and $SERVICE2  – make sure to approve all permissions at the authentication stage."_

## Implementation Brief

In `assets/js/components/notifications/UnsatisfiedScopesAlert.js`

Change the translation string for `MESSAGE_SINGULAR` to
`__( 'Site Kit can’t access the relevant data from %1$s because you haven’t granted all permissions requested during setup. To view %1$s data, you’ll need to redo the setup for %1$s – make sure to approve all permissions at the authentication stage.', 'google-site-kit' ),`

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by danielgent** [comment] 2021-07-12 13:15
The same code creates the messages for not permissions not granted for multiple modules
https://github.com/google/site-kit-wp/blob/develop/assets/js/components/notifications/UnsatisfiedScopesAlert.js#L102

So by changing it for Analytics like the AC we're changing it for AdSense and Tag Manager

![tag-manager-new-warning](https://user-images.githubusercontent.com/8496063/125293746-ffce4200-e323-11eb-8890-bf77d1b867e5.png)

![adsense-new-warning](https://user-images.githubusercontent.com/8496063/125293754-01980580-e324-11eb-8f32-e39a9287fea0.png)

Which is probably fine but I'm just checking @jamesozzie

**Comment by danielgent** [comment] 2021-07-12 13:26
@jamesozzie  also there's extra functionality for when multiple modules don't have permissions granted e.g. AdSense and Analytics here
![multiple-needs-changing](https://user-images.githubusercontent.com/8496063/125295303-630ca400-e325-11eb-8b9c-645d3f31b7aa.png)

The messages looks like
`__( 'Site Kit can’t access all relevant data because you haven’t granted all permissions requested during setup. To use Site Kit, you’ll need to redo the setup for: %s – make sure to approve all permissions at the authentication stage.', 'google-site-kit' )`

I could easily change it so it reads like ` To use AdSense and Analytics, you’ll need to redo the setup for AdSense and Analytics` but I thought I'd check :smile:

**Comment by jamesozzie** [comment] 2021-07-12 13:51
@danielgent Looks good to me, thanks Daniel. 

In relation to when multiple modules require additional permissions I like the additional references, "_To use AdSense and Analytics, you'll need to ...._"

**Comment by danielgent** [comment] 2021-07-12 16:11
@marrrmarrr  Assigning this ticket to you so you can check the wording for the multiple modules message (see this comment https://github.com/google/site-kit-wp/issues/3307#issuecomment-878278587 )

**Comment by marrrmarrr** [comment] 2021-08-02 07:59
@danielgent The updated sentence (To use AdSense and Analytics...) sounds more natural, let's update it to that version when there's more than one module that needs permissions.

**Comment by aaemnnosttv** [comment] 2021-08-02 10:01
@marrrmarrr the problem with "X _and_ Y" language is that it's rather specific to only two. The variant for multiple modules should be able to handle two or more. I think the language around "redoing setup" could probably be improved since the problem is about permissions granted rather than module configuration which is how that reads to me. It makes it sound like the user needs to go through the full module setup flow again, but then mentions permissions that are part of the oauth flow. I'm not saying we should mention "OAuth" here because users won't know what that is of course, but I think we could come up with something a bit more clear 🙂

**Comment by jamesozzie** [comment] 2023-01-03 16:11
This is no longer as issue @bethanylang . The highlighted below now appears:
_The Site Kit setup was interrupted because you did not grant the necessary permissions. [Get help](https://sitekit.withgoogle.com/support?error_id=access_denied)_

![image](https://user-images.githubusercontent.com/41326532/210395949-ed09c72c-d1f4-4356-87b5-5a021cfc05e9.png)

**Comment by bethanylang** [comment] 2023-01-03 16:23
@jamesozzie Thank you! Closing.

**Closed by bethanylang** 2023-01-03 16:23 UTC
Labels: P2, Type: Enhancement
