### ISSUE TITLE
Improve Reset button UX (don't close modal on reset)

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#2347] opened 2020-11-10 23:37 UTC
## Feature Description

Currently the Reset flow is slightly awkward and doesn't provide the user much feedback of what's happening after they reset their site. See the following screencast:

![2020-11-10 23 31 26](https://user-images.githubusercontent.com/90871/98746382-4c383b00-23ad-11eb-8372-82952df33973.gif)

I outlined some of the issues with this UX and some suggestions here: https://github.com/google/site-kit-wp/pull/2268#discussion_r512715549

-----

I don't think showing a generic loading animation is a good indication of what's _currently happening_, because it would remove "Reset Site Kit" with "…" (some loading animation) so you might not _know_ what's loading/resetting.

I think it'd be nicer if the dialog didn't _close_ on `handleUnlinkConfirm`. Instead, the modal's content should update after the "Reset" button is clicked—changing the button to be disabled with the text "Site Kit is resetting" would be nice.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Clicking the "Reset" button should not close the modal because this action relies on a page reload, and closing it without any loading indicator results in confusing UX.
* A small loading indicator should appear next to the "Reset" button once clicked. It should persist until the page is reloaded (e.g. relying on `isNavigating` selector from #2497).

## Implementation Brief
* **Once #2497 has been merged**
* Using `/assets/js/components/Dialog.js`
	* Import the `Spinner` component. `/assets/js/components/Spinner.js`
	* Add a new boolean prop called `showSpinner` which is false by default.
	* if `showSpinner` is true, then show the `<Spinner/>` component. The `Spinner` component should be outputted next to the "Confirm" button.
* Using `/assets/js/components/ResetButton.js`
	* Query the navigation store via the `isNavigating` and `getNavigateURL` selectors.
	* If `isNavigating` is true, and `postResetURL` is equal to the URL returned by `getNavigateURL`, set `showSpinner` to true for the `Dialog` component.

### Test Coverage

* No changes needed.

### Visual Regression Changes

* No changes expected.

## QA Brief

* Reset Site Kit and you should see a spinning animation next to the "Confirm" button.

## Changelog entry

* Improve UX when clicking the Reset dialog button, keeping the dialog open in a loading state while completing the process.

**Comment by felixarntz** [comment] 2020-11-10 23:46
@tofumatt Probably a similar thing should happen for the Disconnect modal. I'm not sure we need to go as far as telling exactly what's happening, but it should be clear that the plugin is in a loading state and the button should be disabled until the user lands in the next URL (from the redirect afterwards).

**Comment by aaemnnosttv** [comment] 2021-01-11 10:58
@asvinb 

> Update `handleUnlinkConfirm` to not hide the dialog, i.e remove `setDialogActive( false );`

This call has already been removed from the component as part of #2595.

> Query the navigation store via the `isNavigating` selector, once #2497 has been merged.
> If `isNavigating` is true, then set `showSpinner` to true for the `Dialog` component.

This sounds good but we should only show the spinner here if we are navigating to the `postResetURL`. This should be checked against the `getNavigateURL` selector so that it only spins based on whether navigation is happening to that URL, rather than _any_ navigation.

Also, please complete all sections of the IB (VRT is blank).

**Comment by asvinb** [comment] 2021-01-11 11:27
Updated @aaemnnosttv

**Comment by aaemnnosttv** [comment] 2021-01-12 09:21
@asvinb IB ✅ 

Regarding your comment for the Test Coverage section "Existing tests should pass." – this is required for all PRs to be merged so it's unnecessary to say so; maybe meant "no changes expected" instead? This section is just for outlining expected test changes/additions/subtractions.

As for your comment under Visual Regression Changes, this section is specifically about changes to VRT reference images or scenarios. E.g. if we had an issue to change the border radius of all buttons, we would expect this to require our VRT reference images to be updated because there would be visual changes that would otherwise fail when compared with the existing reference files.

I'll update these to both indicate no changes are expected but just something to keep in mind going forward 👍

**Comment by tofumatt** [comment] 2021-01-12 14:39
A clarification on the UX intent of the issue here:

* I think putting it _next_ to the button but not _inside_ it would be visually preferable here given the spinner has a white background.
* Changing the text from “Reset” to “Resetting” would be good, and disabling it once clicked (`disabled` prop I’m guessing) would be good, so users can’t/don’t feel compelled to click it several times and know it’s updating.

The idea is to communicate to the user "we are in the process of resetting your site" and get them to not interact with anything until it's done.

Arguably we might want to disable the "cancel" button too at that point, since clicking it won't cancel the request and it'd be confusing to think it's an "Abort" button. But that's less an issue 😄

**Comment by aaemnnosttv** [comment] 2021-01-13 12:03
> Changing the text from “Reset” to “Resetting” would be good, and disabling it once clicked (`disabled` prop I’m guessing) would be good, so users can’t/don’t feel compelled to click it several times and know it’s updating.

I'm not a big fan of changing the text on click since that changes the size of the button and could be visually erratic, especially with a fast request/response. I think disabling the button is definitely a good idea though (do we not do this already?)

> I think putting it _next_ to the button but not _inside_ it would be visually preferable here

Agreed, that's how I had envisioned it as well. I suppose in the end, whatever looks better?

> Arguably we might want to disable the "cancel" button too at that point, since clicking it won't cancel the request and it'd be confusing to think it's an "Abort" button. But that's less an issue 😄 

Good point – that would only really be possible if we used `isResetting` state from the data store (perhaps in conjunction with `isNavigating` which doesn't exist yet) so may be good to raise as a follow-up issue.

**Comment by wpdarren** [comment] 2021-02-02 13:27
### QA Update: Engineer to confirm ⚠️ 

**Observations:** 

@johnPhillips @aaemnnosttv 

1) In the QAB it states that the animation should be next to the `confirm` button. I'm sure it's a typo, but it appears next to the 
`reset ` button as per screenshot above. I didn't want to assume anything. Is this correct? 

![image](https://user-images.githubusercontent.com/73545194/106605527-f6ce8d00-659b-11eb-80c3-f38c3f350cab.png)

2) This is not related to the issue, but I did notice when I clicked on the `Disconnect Site` link the `Checking compatibility` animation appeared directly next to the `Reset Site Kit` link. Should this be appearing when all we are doing is disconnecting? If this is the correct behaviour, is it an easy fix to adding some padding so the animation and link aren't so close? 

![Annotation on 2021-02-02 at 21-06-41](https://user-images.githubusercontent.com/73545194/106605106-7b6cdb80-659b-11eb-8108-4b488ec359c0.png)

**Verified:**

- When I disconnect my site and click on the `Reset Site Kit` a popup appears with a spinning animation next to the `Reset `button. - When I click on the `Reset Site Kit` within settings, a popup appears with a spinning animation next to the `Reset `button.

**Comment by aaemnnosttv** [comment] 2021-02-03 11:49
> In the QAB it states that the animation should be next to the `confirm` button. I'm sure it's a typo, but it appears next to the `reset ` button as per screenshot below. I didn't want to assume anything. Is this correct? 

@wpdarren yes, it should say "Reset" button. Looking at your screenshot though, the spinner should be much closer to the button itself though rather than centered. Can you refresh your cache to get the latest styles?

> This is not related to the issue, but I did notice when I clicked on the `Disconnect Site` link the `Checking compatibility` animation appeared directly next to the `Reset Site Kit` link. Should this be appearing when all we are doing is disconnecting? If this is the correct behaviour, is it an easy fix to adding some padding so the animation and link aren't so close? 

Good catch! You're right that it isn't related to the issue here but is likely triggered by the disconnect. Can you open a new issue for this? One thing to note is that this issue only affects the Reset functionality, it doesn't cover disconnecting (via the user menu).

**Comment by wpdarren** [comment] 2021-02-03 13:03
### QA Update: Pass ✅ 

- When I click on the Reset Site Kit link, a popup appears with a spinning animation next to the Reset button.

![image](https://user-images.githubusercontent.com/73545194/106750654-1086d780-6663-11eb-9ece-144d0c765d92.png)

> `One thing to note is that this issue only affects the Reset functionality, it doesn't cover disconnecting (via the user menu).` 

@aaemnnosttv  Noted. I initially tested the reset functionality by the admin settings and via disconnecting, just to make sure the behaviour was the same. I'll submit a ticket for the other issue I discovered.

**Closed** 2021-02-16 22:54 UTC
Labels: Good First Issue, P2, Rollover, Type: Enhancement
