### ISSUE TITLE
Release 1.69.0

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4869] opened 2022-02-21 09:50 UTC
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Release is prepared, tested, and deployed to wordpress.org.

## Implementation Brief

* N/A

## QA Brief

* N/A

## Changelog entry

* N/A

**Comment by wpdarren** [comment] 2022-02-24 10:10
With Unified Dashboard enabled and the feature tour triggered, an error appears when you click the 'Next' button to go to the 3rd part of the tour.  The error is: 

`Failed to construct 'IntersectionObserver': rootMargin must be specified in pixels or percent.

    in WidgetAreaRenderer
    in div
    in WidgetContextRenderer
    in DashboardMainApp
    in DashboardEntryPoint
    in RestoreSnapshots
    in ErrorHandler
    in Root`

![image](https://user-images.githubusercontent.com/73545194/155503502-5d0aac17-2c70-4125-bca5-6a2280c73bfc.png)

@adamdunnage initially mentioned this issue but he found it on 1.68.0, but it does not happen regularly. I wasn't able to recreate the issue on 1.68.0 but could every time on 1.69.0.

**Comment by wpdarren** [comment] 2022-02-24 12:21
### QA Update: ❌ 

With Unified Dashboard disabled (had to set Force enabled feature flags to always override because UD is appearing by default at the moment. This will be fixed in 4865), I browse to Analytics module page and on main branch, this error appears. 

`Cannot read properties of undefined (reading '0')

    in SiteStats
    in div
    in div
    in Widget
    in WithWidgetSlug(Widget)
    in ModuleOverviewWidget
    in WidgetRenderer
    in div
    in Cell
    in WidgetCellWrapper
    in div
    in Row
    in div
    in div
    in ForwardRef
    in WidgetAreaRenderer
    in div
    in WidgetContextRenderer
    in ModuleApp
    in GoogleSitekitModule
    in RestoreSnapshots
    in ErrorHandler
    in Root`

![image](https://user-images.githubusercontent.com/73545194/15 5522597-52d17592-e1ac-4246-8fea-a97fb730e69a.png)

When I switch to the latest release, this error does not appear, so appears to be a regression.  

This is a new site, only has Google Site Kit, Debug Bar and Query Monitor plugins installed on the latest version of WP.

**Comment by techanvil** [comment] 2022-02-24 12:50
## QA :white_check_mark:
* Smoke tested.
* Verified the changes I've been involved with.
* Performed some ad-hoc testing.

In my testing, I have not been able to reproduce the issues that @wpdarren has mentioned so far for this release -

I've been able to successfully complete the feature tour without seeing an error. I tried this on a few different browsers - Chrome and Safari on Mac, and Chrome and Firefox on Linux. This was with a fresh site, just Site Kit and the Tester plugin installed, on the `main` branch, production build.

Also, I've not seen an error on the Anaytics module page, despite using a fresh site, where the "gathering data" CTA displayed, and also trying an existing Analytics property with zero data.

I know this doesn't help all that much, but just indicates we might need to dig into how to reproduce these a bit more.

**Comment by wpdarren** [comment] 2022-02-24 13:03
> With Unified Dashboard disabled (had to set tester plugin `Force enabled feature flags` to always override because UD is appearing by default at the moment. This will be fixed in 4865).

With regard to my issue reported above. When I disconnected the site, the error did not appear anymore. I also created a new site and was unable to recreate it. I know that @bethanylang has mentioned this is an issue that [users have reported](https://github.com/google/site-kit-wp/issues/4837) before, so maybe its an issue on the service side.

**Comment by wpdarren** [comment] 2022-02-24 15:25
### QA Update: ✅ 

- I've been through our Release QA checklist.  
- Tested with Unified Dashboard enabled and disabled.
- Tested sites with live, zero and gathering data. 

Only issue is as [reported above](https://d.pr/i/xhIehu) to do with the feature tour on Unified Dashboard.

**Comment by tofumatt** [comment] 2022-02-24 19:13
> With Unified Dashboard enabled and the feature tour triggered, an error appears when you click the 'Next' button to go to the 3rd part of the tour. The error is:

Can you elaborate on which feature tour causes this error? Or how to reliably reproduce this bug? I keep trying to run into a scenario where the feature tour gets triggered on an existing or new site, including setting the "last version" back in the Tester Plugin, but to no avail.

From looking at the code it's unclear why any values passed to `rootMargin` (created at https://github.com/google/site-kit-wp/blob/153b9a47db06ebf99b2e1c9d9aacd32976c88b9b/assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js#L72) would be invalid and not a number.

I suspect changing the code generating the margins to:

```js
const gap = gridGaps[ breakpoint ] || 0;
const top = getHeaderHeight() + gap || 0;
```

would protect against any invalid values, but I want to be sure that's where the bug is first and I can't reproduce it.

**Comment by tofumatt** [comment] 2022-02-24 23:22
As mentioned I haven't been able to reproduce the issue above.

Aside from that all QA from me looks good, so QA ✅ from me 👍🏻

**Comment by tofumatt** [comment] 2022-02-24 23:24
As mentioned I haven't been able to reproduce the issue above.

Aside from that all QA from me looks good, so QA ✅ from me 👍🏻

**Comment by mohitwp** [comment] 2022-02-25 07:55
### QA Update ✅ 

- Verified Release QA checklist.
- Tested with Unified Dashboard enabled and disabled.
- Tested with IdeaHub enabled and disabled.
- Tested with ServiceSetupV2 enabled.

I could able to reproduce this issue https://github.com/google/site-kit-wp/issues/4869#issuecomment-1049692867 yesterday but this is not reproducing me now. Also, UFD is not showing default enable now.

cc @wpdarren

**Comment by wpdarren** [comment] 2022-02-25 08:54
@tofumatt the Unified Dashboard feature tour. 

Both @adamdunnage and myself could recreate this numerous times yesterday. I will provide a screencast.

**Comment by adamdunnage** [comment] 2022-02-25 09:13
@tofumatt here is a recording of this issue from yesterday. 

https://user-images.githubusercontent.com/91896826/155688036-77f6245e-988f-4c97-8686-4ba4202a6f08.mp4

**Comment by mohitwp** [comment] 2022-02-25 09:59
@wpdarren I'm able to reproduce the Feature tour error issue. But now it's not coming when we click on 'Next'. Error is coming when I scroll down the page.


https://user-images.githubusercontent.com/94359491/155695116-ac8fadfe-efda-44c7-b454-7ec44ca7a2cf.mp4

cc @tofumatt

**Comment by hussain-t** [comment] 2022-02-27 06:59
## QA ✅ 

- Verified the release QA check list.
- Smoke tested.
- Verified the changes I have been involved with.

**Comment by jimmymadon** [comment] 2022-02-27 23:27
## QA ✅  

✅  Went through the issues I was involved - LGTM.
✅  Smoke Testing on my MacBook Pro (Viewport approx. 1430 x 750).

Found _very_ minor issues related to #4641 when smoke testing on my larger screens. Pretty sure these are not release blocking 🙂 Not sure if they are worthy of creating separate issues (our user base does not predominantly use such large screens)

1. On large screens (viewport width approx. > 2700px) and with IdeaHub enabled (but not setup) - clicking on "Speed" and then refreshing the page creates a small layout shift and the chip changes to "Content". (I guess this is due to the loading of the IdeaHub banner which increases in height as the width of the window increases).

https://user-images.githubusercontent.com/1721319/155904192-fea97fe4-4177-4883-99d8-a10746da8e0b.mov

2. The below issue from my previous [comment](https://github.com/google/site-kit-wp/issues/4714#issuecomment-1027409795) on Release 1.50.0 still exists:

> 2. On large screens (viewport height approx. > 1400px), clicking on `Monetization` does not change the selected chip to `Monetization`. `Traffic` remains as the selected chip.

https://user-images.githubusercontent.com/1721319/152069887-50286ce8-eb96-444d-916a-5ada09a88c48.mov

**Comment by kuasha420** [comment] 2022-02-28 08:17
QA: :heavy_check_mark: 

* Went through the release checklist with a fresh site and a reset site without any issues. 
* Smoke tested a fair bit and didn't get any issues. 

LGTM.

**Comment by wpdarren** [comment] 2022-02-28 09:26
### QA Update: ✅ 

- Went through the QA checklist 

- The issues reported below have been fixed:

- Unified Dashboard feature tour crashing when you click on the next button to go to step 3. 
- Unified Dashboard feature tour crashing when you scroll down the page. 
- Unified Dashboard enabled by default on a new site. Now only is activated when you enable it in tester plugin.

**Closed** 2022-02-28 19:33 UTC
Labels: P0, Type: Task
