### ISSUE TITLE
Display Google Tag ID in Analytics Settings

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6916] opened 2023-04-19 13:35 UTC
## Description

As reported by @jamesozzie in Bug Bash:

Considering the Google tag ID is printed in a sites source code, consider adding this in the view only screen. It doesn't necessarily need to be a configurable option but I do think users will ask about this, unsure of what exactly is printed given it's not their GA4 measurement ID. 

![image](https://user-images.githubusercontent.com/12189958/233091227-cfa9a958-d388-4277-8b93-8d884895b0a2.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2023-04-20 23:58
Duplicate of #6769

**Closed by aaemnnosttv** 2023-04-20 23:58 UTC
Labels: P1, Type: Enhancement, Module: Analytics
