### ISSUE TITLE
Site Kit setup stuck on Step 3 "Set up Search Console"

### ISSUE THREAD

**Issue by strickes** [google/site-kit-wp#1191] opened 2020-03-01 10:58 UTC
## Bug Description

When I want to add Site Kit to a new website I was building I get no error message during the setup phase of Site Kit (see screenshots)
https://imgur.com/a/Ttj2thU
If I press the "Add site" button nothing happens. I can see that in the background the page is refreshing but I'm still stuck on that screen.
I also added the page manually to the Search Console, but it didn't help either.

## Steps to reproduce

1. Go to 'Site Kit in the Wordpress Dashboard'
2. Click on 'SIGN IN WITH GOOGLE'
3. Continue with Account Login
4. Verify site ownership is working
5. Allow Domain to access Google Account Data is working
6. Setup up Search Console is not working, no error is thrown

## Screenshots

https://imgur.com/a/Ttj2thU

## Additional Context

 - PHP Version: 7.3.15
 - OS: MacOS
 - Browser Chrome
 - Plugin Version 1.4.0
 - Device: MacBook Pro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment] 2020-03-02 15:51
@strickes Thanks for reporting. As your domain name features an umlaut it seems like you're running into the same issue as reported at #794. Can you confirm your URL and if so we can add your details to that related issue.

**Comment by strickes** [comment] 2020-03-02 17:13
yes I can confirm that. It's a Unicode Domain and I got the same issue as you described in #794 . So I guess we can link these two.

**Comment by jamesozzie** [comment] 2020-03-03 10:16
@strickes Perfect, thanks for the update. I will close this one as a duplicate, hopefully you won't have to wait too long for a resolution. 

Duplicate of #794

**Closed by jamesozzie** 2020-03-03 10:16 UTC
Labels: Type: Support
