### ISSUE TITLE
Unable to set up plugin in WordPress 4.9 when AMP plugin enabled

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#77] opened 2019-06-27 14:48 UTC
## Bug Description

Unable to set up Site Kit on WordPress 4.9 when AMP plugin is enabled.

## Steps to reproduce

1. Install WordPress 4.9.
2. Install and activate the AMP plugin (1.2)
3. Install and activate the Site Kit Plugin and attempt setup.
4. Note errors in console, blank screen.

## Expected behavior

The plugin should work with AMP plugin enabled in WordPress 4.9.

Note: setup works fine in WordPress 5.0 with both plugins enabled, or in 4.9 with the AMP plugin disabled.

## Screenshots

![image](https://user-images.githubusercontent.com/2676022/60274888-27295200-98b6-11e9-8960-042c4730bf5c.png)

## Additional Context

 - PHP Version: 5.4.45
 - OS: OSX
 - Browser Chrome Beta
 - Plugin Version 1.0.0-beta.1
 - Device: Mac Desktop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by jamesozzie** [comment] 2019-06-27 14:55
Duplicate of #14

**Comment by ivankristianto** [comment] 2019-06-27 15:30
Thanks @adamsilverstein 
This issue is related to amp-wp plugin, and it fixed in this PR:
https://github.com/ampproject/amp-wp/pull/2688

**Closed** 2019-06-27 15:51 UTC
