### ISSUE TITLE
Redirect authenticated users from splash to dashboard

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2529] opened 2020-12-14 22:19 UTC
## Bug Description

The `googlesitekit-splash` screen currently has an incorrect `<title>` tag where the main segment is missing. At the moment it looks like the following:

```
 < example.com — WordPress
```

However, there's currently no way for a user to reach the splash screen after they're already authenticated – even the activation notice shown after activating the plugin will link to the dashboard. This makes this situation only possible if the user navigated directly to the splash screen (from browser history/back, etc). The splash screen is only a stepping stone to send the user through Google OAuth; if they're already authenticated, there's no reason to go through it again so they should be sent straight to the dashboard.

If required scopes have changed, the user will still need to go through oAuth of course, but we already prompt the user to "Redo Setup" in this case.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `googlesitekit-splash` screen should redirect to `googlesitekit-dashboard` if the user is already authenticated (`Authentication::is_authenticated`)
* The connect and disconnect URLs should be updated to no longer use the base splash screen URL, but instead use their own admin `action` URLs, like we do for Google Proxy setup/settings URLs

## Implementation Brief

* Update screen definition of `googlesitekit-splash` to redirect to the dashboard if authenticated (preserving existing logic to ensure permissions first)
* Move connect/disconnect handlers from `googlesitekit-splash` URL to dedicated `admin_action_` URLs:
	- `index.php?action=googlesitekit_connect&nonce=...`
	- `index.php?action=googlesitekit_disconnect&nonce=...`
* Finish and merge https://github.com/google/site-kit-wp/pull/3037
	- Update references to these URLs in JS/fixtures
	- Updating tests

### Test Coverage

* Add/update tests for decoupled action handlers
* Update JS tests as necessary

### Visual Regression Changes

* None.

## QA Brief

This issue primarily updates the splash screen to redirect the user to the SK dashboard if they're already authenticated and have sufficient permissions.

The following cases should be tested to work (and continue to work) properly

**Unauthenticated / Site Kit not set up yet**
- Splash screen loads without redirecting
- Navigating directly to SK dashboard redirects to splash screen

**Authenticated / Site Kit set up**
- Navigating directly to splash screen redirects to SK dashboard
- SK dashboard does not redirect to splash

**Disconnect via user menu**
- User lands on splash screen with same disconnect messaging as today
- Session storage should be cleared

Secondarily, the URLs used for beginning the oAuth flow (connect) and disconnecting have been updated to use dedicated action URLs. This change should make no difference for the user.

## Changelog entry

* Redirect users from the splash screen to the dashboard if they are already authenticated.

**Comment by aaemnnosttv** [comment] 2020-12-15 16:29
@felixarntz after digging into this a little with @asvinb it seems that this only happens when navigating to the splash screen directly once Site Kit is already set up. The title shown on the splash screen on the initial set up is consistent with other Site Kit screens for both primary and secondary users.

The problem is related to how WP derives the page title which seems to depend on the page having a `parent`. When the current user already has permissions for the dashboard (i.e. the main Dashboard menu item is present) the splash page is not registered as a sub-menu of the main page since the titles are the same. Because of this, the `$title` is blank in this case (which is still odd) but it doesn't seem possible for a user to actually see this without navigating to it directly.

**Comment by felixarntz** [comment] 2021-01-07 19:32
@aaemnnosttv Ah, that makes sense. I'll deprioritize this for now, but still worth fixing in principle.

**Comment by benbowler** [comment] 2021-02-26 12:09
I tracked this down to, as @aaemnnosttv said, a bug/issue with Wordpress where title of the page is not set if the parent slug passed to `add_submenu_page` is `NULL`.

I found a solution and have added an IB.

**Comment by aaemnnosttv** [comment] 2021-03-01 09:56
The IB is pretty close, with a few things to iterate on:
* Let's use the current screen (`WP_Screen`) to for the logic in the conditional rather than query params
* We can't simply concatenate the title with the value coming through the filter. We should translate this [as its done in core](https://github.com/WordPress/WordPress/blob/630a593765af5a325d4954302f2375fca41da2b2/wp-admin/admin-header.php#L34-L53) to preserve an i18n-friendly result.

**Comment by eugene-manuilov** [comment] 2021-03-01 12:47
@aaemnnosttv @felixarntz I have a question: why do we add the splash screen page when the user already has permissions? What's the point to have it? I think if the user already has permissions, we should redirect them to the dashboard page instead of showing the splash screen again and confuse users. What do you think?

**Comment by aaemnnosttv** [comment] 2021-03-05 18:32
@eugene-manuilov – users shouldn't really land on this page in this state unless they navigated directly to it (from browser history perhaps?). I have found it useful to test things before by being able to navigate directly to it without disconnecting first, but I don't know if that is reason enough to keep this.

I agree that the issue as-is does not fix the the root cause, so a redirect to the dashboard would likely be a better experience. As mentioned previously, we already have a redirect in place from the dashboard to the splash page when the user is not authenticated, so we need to make sure this is well-documented and covered with tests to ensure this never results in a circular redirect loop, both now and in the future.

@felixarntz – if you agree, let me know and one of us can rewrite the issue/ACs accordingly.

**Comment by aaemnnosttv** [comment] 2021-03-29 13:07
@felixarntz ACs updated + IB which includes moving handlers for connect/disconnect since these don't really belong on the splash URL either and is more consistent with how we're handling other action URLs for proxy setup and settings.

**Comment by eugene-manuilov** [comment] 2021-04-23 17:07
@felixarntz assigning it to you since Evan also wants you to review it.

**Comment by wpdarren** [comment] 2021-05-03 13:47
### QA Update: Pass ✅ 

**Unauthenticated / Site Kit not set up yet**
Splash screen loads without redirecting
Navigating directly to SK dashboard redirects to splash screen
`/wp-admin/admin.php?page=googlesitekit-splash`

![image](https://user-images.githubusercontent.com/73545194/116431695-eb5bcc80-a83f-11eb-814f-183b3e2e20ee.png)

**Authenticated / Site Kit set up**

- Navigating directly to splash screen redirects to SK dashboard
- SK dashboard does not redirect to splash

**Disconnect via user menu**

- User lands on splash screen with same disconnect messaging.
- Session storage is cleared but then new data is entered when the splash loads. 

![image](https://user-images.githubusercontent.com/73545194/116884220-6517ff80-ac1e-11eb-9be1-37343a891bc5.png)

**Closed** 2021-05-06 17:47 UTC
Labels: P2, Rollover, Type: Bug
