### ISSUE TITLE
All Traffic Widget: pie slice is unselected when clicking anywhere outside

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4589] opened 2021-12-20 13:29 UTC
## Bug Description

On the `All Traffic` widget on the Current and Unified Dashboard there's a bug when you select a slice of the pie, i.e. Organic search, and then go to the date picker to filter for another period, i.e. 7 days.  When you click on the date picker the selected slice is unselected, so you are unable to retrieve data for a specific slice by period.   

https://user-images.githubusercontent.com/73545194/146774612-fca17dfd-2de0-43e0-9ceb-5d8f136de320.mp4

## Steps to reproduce

1. Go to 'Dashboard'
2. Click on '.Organic search (or any other slice'
3. Click on '7 days' within the date picker

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If a user has filtered the stats on the All Traffic widget by clicking on a slice of the chart, preserve that filtered view until the user changes it themselves. 
* The filtered view should not disappear if the user applies a second filter (e.g. changing the timeframe from the dropdown) or clicks somewhere else on the dashboard. 
 
## Implementation Brief

Within `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/UserDimensionsPieChart.js`:

- Rather than determining whether the tooltip is open via other stateful values, create a separate boolean state value to track it.
  - Create `isTooltipOpen` and `setIsTooltipOpen` via `useState()`.
- Remove the current `isTooltipOpen()` function, replacing its use with the `isTooltipOpen` boolean value.
- Remove the `closeTooltip()` function, replacing its use with a call to `setIsTooltipOpen( false )`.
- As we're no longer resetting the UI state values via `closeTooltip()`, add a call to `setValues()` to reset the values of `UI_DIMENSION_VALUE`, `UI_DIMENSION_COLOR` and `UI_ACTIVE_ROW_INDEX` in the `onEscape()` function to ensure the escape key still works as it does now. However, we don't want to reset these values in the `onExitClick()` function, so this can remain untouched.
- In the `onLegendClick()` function:
  - Call `setIsTooltipOpen( false )` at the point where the UI state values are being reset.
  - Call `setIsTooltipOpen( true )` at the point where the UI state values are being set for the dimension.
- In the `onSelect()` function:
  - Call `setIsTooltipOpen( true )` at the point where the UI state values are being set for the dimension.
- Change the condition that determines whether `options.tooltip.trigger` should be set to `'selection'` to a check for `isTooltipOpen`.
- Port the above changes to the GA4 version of this component that is being introduced via https://github.com/google/site-kit-wp/issues/6216.

### Test Coverage

* Update any failing tests.

## QA Brief
QA steps need to be undertaken on both non-GA4 and GA4 views. This can be done by activating and deactivating the `ga4Reporting` feature flag within the Site Kit Tester Settings screen. Perform the following steps in both non-GA4 and GA4 views:

- Navigate to the Google Site Kit Dashboard and scroll to the Traffic module area, containing the pie chart.
- Validate that - by default - no segments are selected and the green line graph shows.
- Toggle the date range and validate that it changes for the default selection.
- Click on a segment within the Pie chart itself.
- Validate that the segment is selected and the traffic type in the line graph changes accordingly. Also validate that it took only one single click on the segment to effect the change in reported metrics, this addresses the "double click" bug.
- With the chosen segment selected, toggle the date range in the top menu to a date range of your choice.
- Validate that the UI enters into a loading state as data is fetched.
- Validate that, once data is fetched, the UI updates with the applicable date range AND the chosen segment is still active. This is the main fix of this issue, that the selected pie chart segment remains active/selected when the date range is toggled and when the user clicks outside of the chart area.
- Select another segment within the pie chart, by clicking on it.
- Validate that the action changes the reporting graph accordingly.
- Next, click outside of the pie chart (anywhere on the screen) and validate that - while the tooltip closes - the segment remains in effect and the reporting metrics remain unchanged.
- Select another segment on the pie chart once more, by clicking on it.
- Validate that the action changes the reporting graph accordingly.
- This time, press the escape key to exit the graph area.
- User metrics should be reset when using this approach, and the default green "All Users" line graph reinstated.

## Changelog entry

* Fix issue in the All Traffic widget/Google Charts pie charts that caused selected elements to become de-selected.

**Comment by aaemnnosttv** [comment] 2022-01-26 08:53
@wpdarren I found that this isn't specific to the date range but actually clicking anywhere will do it.

**Comment by aaemnnosttv** [comment] 2022-01-26 08:58
@asvinb I feel like maybe this was done intentionally but don't recall where it changed. I think you worked on it, no?

**Comment by aaemnnosttv** [comment] 2022-01-26 08:59
cc: @felixarntz @marrrmarrr

**Comment by wpdarren** [comment] 2022-03-29 12:10
Just adding another issue I have found due to this bug. 

On entity dashboard, if select a data period, and then try and click on the page link in the top right, it does not work and no window is open directing you to the page. 

![image](https://user-images.githubusercontent.com/73545194/160607958-4e7725c9-73b0-41d8-88c0-9acf4cddb0cf.png)

To add, I have found the same behaviour as Evan mentioned. 

> @wpdarren I found that this isn't specific to the date range but actually clicking anywhere will do it.

**Comment by asvinb** [comment] 2022-06-09 12:21
> @asvinb I feel like maybe this was done intentionally but don't recall where it changed. I think you worked on it, no?

@aaemnnosttv The change was part of the following ticket: https://github.com/google/site-kit-wp/issues/2659 which I created and wrote the IB for. So it's intentional :)
Also for the entity dashboard issue that @wpdarren mentioned, whereby he cannot click on the URL, I think it's definitely related to https://github.com/google/site-kit-wp/issues/4735 . See my comment here: https://github.com/google/site-kit-wp/issues/4735#issuecomment-1151045003

**Comment by aaemnnosttv** [comment] 2022-12-16 15:06
@asvinb revisiting this – I think the main issue here is not about the tooltip, but that the selected segment within the pie chart is also lost in the process. @marrrmarrr has clarified this in the AC, so moving this forward 👍

**Comment by asvinb** [comment] 2022-12-19 11:53
@aaemnnosttv I spent some time looking into this. So far, from what I have read, the only way to programmatically toggle the tooltip within the chart is by selecting/deselecting a slice. That's how it's implemented but at the same time, you're right, it introduces a weird behaviour where we lose the selected slice. Thinking about that, maybe we should revert the code which hides the tooltip by deselecting the slice and just use the default behaviour that comes with Google Charts. What do you think?

**Comment by aaemnnosttv** [comment] 2022-12-20 17:36
Thanks @asvinb – it sounds like we need to review how we got here as we need to (re)consider this in the context of previous decisions that we've made. Would you please briefly summarize what we've done to get to where we are now? That is clarify what the default experience is, the customizations we've made until now and why? With that context I think we can decide with @marrrmarrr what we should do here, even if that means reverting a change/customization we made before but it's important to have the full picture to do so. Hopefully this doesn't take too long; thanks!

**Comment by asvinb** [comment] 2023-02-10 13:25
@aaemnnosttv So the original issue was more a UX related one as described in https://github.com/google/site-kit-wp/issues/2659 Basically when the tooltip is visible(open), after clicking on a slice in the `AllTrafficWidget`, it's more intuitive to press the `ESC` key or to click anywhere outside to close the tooltip. However the only way of doing so was to reset the pie chart state which means that unfortunately we also lost the selected slice. Maybe we can dig more and see if there are alternative ways of handling that or even Google Charts now allows that because technically Google Charts should have this functionality built in. Let me know what you think.

**Comment by aaemnnosttv** [comment] 2023-02-15 18:39
Thanks @asvinb – it seems like the solution here may be to (simply?) enhance the logic of the "click anywhere outside to close the tooltip" part so that it only closes the tooltip when clicking on any _non-interactive_ element, rather than _anywhere_. In that sense, clicking a button, menu/item, etc should not cause the pie chart to lose its state. Does that sound reasonable?

**Comment by bethanylang** [comment] 2023-02-20 16:05
Unassigning from Asvin as he's no longer on the project; anyone else is welcome to pick up!

**Comment by aaemnnosttv** [comment] 2023-02-20 22:33
Thanks @techanvil, this sounds good to me. One thing we want to avoid here is fixing this only in the UA component and not in the GA4 version I see you're already working on in #6216. Does this issue not affect that component as well? Either way, let's note that here. I'm guessing it does, in which case we'd want to make this issue dependent on 6216 and make sure the IB is clear about addressing both.

**Comment by aaemnnosttv** [comment] 2023-03-04 00:03
IB ✅

**Comment by wpdarren** [comment] 2023-06-21 13:56
### QA Update: ⚠️ 

@10upsimon I have two observations:

1. As you can see from the screencast, when I click outside of the chart, the tooltip remains there until I am some distance away from the pie chart. This might be expected but with it mentioning in the QAB that the tooltip should disappear, I thought I would double check this with you. 

This behaviour occurs on UA and GA4 dashboard and I was able to recreate it on main, entity and view only dashboards.

https://github.com/google/site-kit-wp/assets/73545194/2fe81e18-425b-491e-85ce-1bde1146377c

2. This issue is a good one! I was able to recreate it on the latest release (1.103.0) but unsure if its a quick fix, or, if I should create a ticket as it is probably out of scope.  Please let me know what you think. 

As you can see from the screencast. I select 7 days and then Organic search, the segment of the pie chart is purple.  I then select 14 days. The Organic search segment is still selected which is great but the colour has changed to Yellow. I had to laugh when I saw this because it's so surprising no user or QA have seen this before!    


https://github.com/google/site-kit-wp/assets/73545194/57a2178e-bc94-4c71-95a3-fe4273463714

I appreciate this is out of scope so happy to create a ticket, but would be interested in your thoughts on if its a quick fix.

**Comment by 10upsimon** [comment] 2023-06-21 14:25
@wpdarren thank you for the detailed reply following QA, appreciate it! To address your 2 points:

1. I actually changed the on click handler to use a larger portion of the chart container. I recall there being a reason for this, so I will re-visit this in code history to determine why I made this decision, I am quite sure it had to do with the double click bug though. Leave this with me to look into as part of this issue.

2. I had a good chuckle at this myself, as it _is_ obvious now that you point it out! While this may warrant a new issue, let me use this issues space to take a quick glimpse, as the first thing I notice is that when we click on 7 days we "lose" the "social" UI metric, so I'm wondering if this is purely a case of us using colours in an indexed fashion, but swapping the index order of the metrics themselves when we have N amount. 

Let me address point 1 and let's time box point 2 to ~30min perhaps to see if I can either fix it entirely or surface enough info to assist with AC and an IB on a new issue.

**Comment by 10upsimon** [comment] 2023-06-22 12:05
@wpdarren I've looked further into both points you've raised, and I actually think we need to live with the trade off of needing to click outside of the entire chart canvas/container as a means to prevent the double click bug from happening, but I am open to suggestions here. 

I did note, in testing, that I was _still_ getting the double click bug, even though I knew I had resolved it. It turns out that I only resolved it for the NON GA4 chart, so I've opened a new pull request at https://github.com/google/site-kit-wp/pull/7195 which is a continuation of the previously approved and merged pull request at https://github.com/google/site-kit-wp/pull/7161. This fixes the need to double click on a pie segment in order to activate it.

What I actually think the cause is regarding the double click bug, is the updating of state when we close the tooltip. If I add a slight setTimeout (just to test) with a value of around 100ms, I am able to make the click outside check less strict (i.e satisfy your point 1) but there will always be a noticeable "flash" of the tooltip. Quite honestly, I'd rather have the (current) smooth UI and need to click slightly further outside of the chart area, if you agree.

As for point 2 that you raised, where the colour of the chart and segment is changing, this is not actually a bug necessarily, and the behaviour is expected. The reason being is that we define a constant index of colours for pie chart segments. These are maintained in `UserDimensionsPieChart.chartOptions` for both non GA4 and GA4 charts. We dictate the colours based purely on the _order_ of the segments (and labels/legends) as per the array in the settings:

```
slices: {
	0: { color: '#fece72' },
	1: { color: '#a983e6' },
	2: { color: '#bed4ff' },
	3: { color: '#ee92da' },
	4: { color: '#ff9b7a' },
},
```
Therefore, if there is ever a change in the order of the returned metrics, the color would inherently changed, as a metric may be in position 3 (index 2) for one date range, but in another position/index for another date range.

This is exactly the case for `Organic Social` and `Referal` metrics for me when testing the 7 day vs 14 day date range. The reason/cause for this is that we dictate the order of the returned data to be order by `totalUsers`, and in my case the value of users is different between these date ranges to the point where the metrics returned are reordered.

As for solving this, I would be curious to hear from someone like @tofumatt to hear if we feel this is necessary? The only other way I could think of doing this would be to dictate, for certain charts, that slice colours are attached to metric names as opposed to indexes.

Thoughts?

As for now, the code review to correct the double click bug for GA4 is now open (again).

**Comment by tofumatt** [comment] 2023-06-22 14:07
Regarding point 2: the colours "changing" is definitely a separate bug if we consider it worth "fixing". It's behaving as-expected, in that colours used change based on the total amounts in the chart.

It _is_ a bit odd, but personally think it's fine. But the "fix" would be to store which labels have already been associated with a colour once they are assigned one, and then to maintain that colour selection on future renders, limiting the available colour pool for new labels. That way we don't need to hardcode labels with a particular colour, but we don't have them change around on render.

If you want to file a follow-up issue for that feel free—I'm happy to take a look at the ACs. 🙂

Out-of-scope for this issue though 👍🏻

**Comment by wpdarren** [comment] 2023-06-28 03:21
### QA Update: ✅ 

**Verified:**

For GA4 dashboard view (main, entity and view only)

- By default - no segments are selected and the green line graph shows. Checked for all reporting periods. 
- When segment is selected and the traffic type in the line graph changes accordingly. 
- It only took one single click on the segment to effect the change in reported metrics.
- With the chosen segment selected, the date range in the top menu is changed and the UI enters into a loading state as data is fetched.. Once data is fetched, the UI updates with the applicable date range and the chosen segment is still active. 
- When another segment within the pie chart is selected, the action changes the reporting graph accordingly.
- When I click outside of the pie chart the tooltip closes but the segment remains in effect and the reporting metrics remain unchanged.
- When another segment is selected, the reporting graph changes, and when the escape key, I am exited from the graph area, user metrics are reset and the default green "All Users" line graph reinstated.

For UA dashboard view (main, entity and view only)

- By default - no segments are selected and the green line graph shows. Checked for all reporting periods. 
- When segment is selected and the traffic type in the line graph changes accordingly. 
- It only took one single click on the segment to effect the change in reported metrics.
- With the chosen segment selected, the date range in the top menu is changed and the UI enters into a loading state as data is fetched.. Once data is fetched, the UI updates with the applicable date range and the chosen segment is still active. 
- When another segment within the pie chart is selected, the action changes the reporting graph accordingly.
- When I click outside of the pie chart the tooltip closes but the segment remains in effect and the reporting metrics remain unchanged.
- When another segment is selected, the reporting graph changes, and when the escape key, I am exited from the graph area, user metrics are reset and the default green "All Users" line graph reinstated.

**Closed** 2023-06-28 16:11 UTC
Labels: Type: Bug, P1, Module: Analytics, Exp: SP
