### ISSUE TITLE
PHP FATAL error if we use " UpdraftPlus WordPress Backup " + “Site Kit by Google”.

### ISSUE THREAD

**Issue by cecofuli** [google/site-kit-wp#383] opened 2019-08-06 15:09 UTC
Hello,

today I wanted to try this plug-in from Google.
With “bad" surprise, UpdraftPlus WordPress Backup give me this fatal error if both work together.
If I disable “Site Kit by Google”, everything is ok.

When I click “Scan Remote Storage” option on UpdraftPlus WordPress Backup, this pop-up in my WordPress Back-end appear

PHP Fatal error (TypeError) has occurred during rescan subaction. Error Message: Argument 1 passed to Google_Client::__construct() must be of the type array, object given, called in /home/customer/www/xxx.com/public_html/wp-content/plugins/updraftplus/methods/googledrive.php on line 825 (Code: 0, line 92 in /home/customer/www/xxx.com/public_html/wp-content/plugins/google-site-kit/vendor/google/apiclient/src/Google/Client.php)

Can you help us?

Thank you.

**Comment by swissspidy** [comment] 2019-08-07 09:14
Thanks for your report!

This looks like a duplicate of #246.

Basically, both plugins use the same API library, but UpdraftPlus uses an older one. At the moment there is no fix for this.

The proper solution would be to prefix Composer dependencies in Site Kit, as mentioned in that issue. Please follow #246 for any updates.

**Closed by swissspidy** 2019-08-07 09:14 UTC
Labels: Type: Support

**Comment by cecofuli** [comment] 2019-08-07 12:05
Thank you. 

UpdraftPlus wrote me: 

"there are already users who have reported this to Site Kit and this is also in our development list."
