### ISSUE TITLE
Add tooltip tour for Analytics All Traffic widget

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2739] opened 2021-02-01 16:28 UTC
There should be a tooltip tour explaining the new All Traffic widget. While it was already shipped in 1.25.0, it's still worth shipping this a bit later. The copy will be worded accordingly to reflect that.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new tooltip tour for the All Traffic widget. The following tooltips should be displayed:
     1. Element to attach the tooltip to: the new chronological trend chart, see [Figma](https://www.figma.com/file/lcOhMAcYcc4KMOZ3XsgNFe/Tooltips?node-id=132%3A149). Tooltip copy: 
          * Heading: "It's now easier to see your traffic at a glance!"  
          * Text: "Check the trend graph to see how your traffic changed over time"
     2. Element to attach the tooltip to: the donut chart, see [Figma](https://www.figma.com/file/lcOhMAcYcc4KMOZ3XsgNFe/Tooltips?node-id=132%3A294). Tooltip copy: 
          * Heading: "See where your visitors come from"  
          * Text: "Click on the chart slices to see how each segment changed over time"
     3. Element to attach the tooltip to: the date picker, see [Figma](https://www.figma.com/file/lcOhMAcYcc4KMOZ3XsgNFe/Tooltips?node-id=132%3A438). Tooltip copy: 
          * Heading: "Check how your traffic changed since you last looked"  
          * Text: "Pick a time frame to see the comparison with the previous period"
* This tooltip tour should be shown to everybody who initial Site Kit version is `1.25.0` or lower.

## Implementation Brief

**1. Updating API contexts**

Revert this commit (remove the comment)
https://github.com/google/site-kit-wp/commit/3936d3dd0

Create a new file, `/assets/js/googlesitekit/default-screen-contexts.js`, with the following content:

```js
const SCREEN_CONTEXT_ACTIVATION = 'Activation';
const SCREEN_CONTEXT_ADMINBAR = 'Adminbar';
const SCREEN_CONTEXT_DASHBOARD = 'Dashboard';
const SCREEN_CONTEXT_SETTINGS = 'Settings';
const SCREEN_CONTEXT_SINGLE = 'Single';
const SCREEN_CONTEXT_SPLASH = 'Splash';
const SCREEN_CONTEXT_USER_INPUT = 'UserInput';
const SCREEN_CONTEXT_WP_DASHBOARD = 'WPDashboard';

export default {
    SCREEN_CONTEXT_ACTIVATION,
    SCREEN_CONTEXT_ADMINBAR,
    SCREEN_CONTEXT_DASHBOARD,
    SCREEN_CONTEXT_SETTINGS,
    SCREEN_CONTEXT_SINGLE,
    SCREEN_CONTEXT_SPLASH,
    SCREEN_CONTEXT_USER_INPUT,
    SCREEN_CONTEXT_WP_DASHBOARD,
};
```

Search for `dataAPIContext` in the codebase and update it to reference the constants we just declared

```
/assets/js/googlesitekit-wp-dashboard.js
43:		render( <Root dataAPIContext="WPDashboard"><WPDashboardApp /></Root>, renderTarget );

/assets/js/googlesitekit-module.js
55:			<Root dataAPIContext="Single" dataAPIModuleArgs={ global.googlesitekitCurrentModule } >

/assets/js/googlesitekit-dashboard-details.js
42:		render( <Root dataAPIContext="Dashboard"><DashboardDetailsApp /></Root>, renderTarget );

/assets/js/googlesitekit-settings.js
42:		render( <Root dataAPIContext="Settings"><SettingsApp /></Root>, renderTarget );

/assets/js/googlesitekit-adminbar.js
47:		render( <Root dataAPIContext="Adminbar"><GoogleSitekitAdminbar /></Root>, renderTarget );

/assets/js/googlesitekit-dashboard-splash.js
52:		render( <Root dataAPIContext="Splash"><GoogleSitekitDashboardSplash /></Root>, renderTarget );

/assets/js/googlesitekit-dashboard.js
60:		render( <Root dataAPIContext="Dashboard"><GoogleSitekitDashboard /></Root>, renderTarget );

/assets/js/googlesitekit-activation.js
41:		render( <Root dataAPIContext="Activation"><ActivationApp /></Root>, renderTarget );

/assets/js/googlesitekit-user-input.js
42:		render( <Root dataAPIContext="UserInput"><UserInputApp /></Root>, renderTarget );

```

A few more updates to make for the `SCREEN_CONTEXT_` constants we defined above:

```
/assets/js/tooltip-tours/all-traffic-widget.js:27: contexts: [ 'Dashboard' ],
/assets/js/modules/search-console/components/dashboard/SearchConsoleDashboardWidgetOverview.js:157: context: [ 'Single', 'Dashboard' ],
/assets/js/modules/search-console/components/dashboard/SearchConsoleDashboardWidgetSiteStats.js:155: context: 'Single',
/assets/js/modules/search-console/components/dashboard/LegacyDashboardWidgetPopularKeywordsTable.js:144: context: [ 'Dashboard' ],
/assets/js/modules/search-console/components/dashboard/LegacySearchConsoleDashboardWidgetKeywordTable.js:132: context: [ 'Single', 'Dashboard' ],
/assets/js/modules/search-console/components/dashboard/LegacySearchConsoleDashboardWidgetTopLevel.js:198: context: [ 'Single', 'Dashboard' ],
/assets/js/
/assets/js/modules/adsense/components/dashboard/LegacyAdSenseDashboardMainSummary.js:206: context: 'Dashboard',
/assets/js/modules/adsense/components/dashboard/LegacyAdSenseDashboardMainSummary.js:224: context: 'Dashboard',
/assets/js/modules/adsense/components/dashboard/LegacyAdSenseDashboardMainSummary.js:243: context: 'Dashboard',
/assets/js/modules/analytics/components/dashboard/LegacyDashboardAcquisitionPieChart.js:143: context: [ 'Dashboard', 'Single' ],
/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidgetSiteStats.js:157: context: 'Single',
/assets/js/modules/analytics/components/dashboard/LegacyAdSenseDashboardWidgetTopPagesTableSmall.js:166: context: 'Dashboard',
/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidgetOverview.js:200: context: [ 'Single', 'Dashboard' ],
/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidgetOverview.js:216: context: [ 'Single' ],
/assets/js/modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetTopAcquisitionSources.js:138: context: [ 'Single', 'Dashboard' ],
/assets/js/modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetPopularPagesTable.js:120: context: [ 'Single', 'Dashboard' ],
/assets/js/modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetTopLevel.js:259: context: 'Dashboard',
/assets/js/modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetTopLevel.js:278: context: 'Dashboard',
/assets/js/modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetTopLevel.js:295: context: 'Dashboard',
/assets/js/modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetTopLevel.js:313: context: 'Dashboard',
/assets/js/modules/analytics/components/dashboard/AnalyticsAdSenseDashboardWidgetTopPagesTable.js:175: context: 'Single',
/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidgetTopPagesTable.js:156: context: [ 'Single', 'Dashboard' ],
```

**2. Add tooltip tour**

Create a new folder, this will contain all tooltip tours across the codebase:

`/assets/js/googlesitekit/tooltip-tours/`

Create a new js file `/assets/js/googlesitekit/tooltip-tours/index.js`, this will import/reference all of our tours

```js
import { allTrafficWidget } from './all-traffic-widget';

export const toolTipTours = {
	allTrafficWidget,
};
```

Create a new js file `/assets/js/googlesitekit/tooltip-tours/all-traffic-widget.js`

```
import { __ } from '@wordpress/i18n';

export const allTrafficWidget = {
	config: {
		tourID: 'allTrafficWidget',
		contexts: [ SCREEN_CONTEXT_DASHBOARD ],
		introducedVersion: '1.25.0',
	},
	steps: [
		{
			target: '.googlesitekit-widget--analyticsAllTraffic__user-count-chart',
			title: __( "It's now easier to see your site's traffic at a glance", 'google-site-kit' ),
			content: __( 'Check the trend graph to see how your traffic changed over time', 'google-site-kit' ),
		},
		{
			target: '.googlesitekit-widget--analyticsAllTraffic__dimensions-chart',
			title: __( 'See where your visitors come from', 'google-site-kit' ),
			content: __( 'Click on the chart slices to see how each segment has changed over time', 'google-site-kit' ),
		},
		{
			target: '.googlesitekit-header__date-range-selector-menu',
			title: __( 'Check how your traffic changed since you last looked', 'google-site-kit' ),
			content: __( 'Select a time frame to see the comparison with the previous time period', 'google-site-kit' ),
		},
	],
};

```
**N.B.** The copy differs from AC as it's what is in Figma.

**3. Add a selector to fetch the relevant tour**

Add a new selector to:
https://github.com/google/site-kit-wp/blob/ff78440/assets/js/googlesitekit/datastore/user/feature-tours.js#L130

Its purpose is to return an array of tooltip tours if any exist for the given context we're in (e.g. Dashboard view) and they haven't yet been dismissed / completed.

```js
import { toolTipTours } from '../../tooltip-tours';

getCurrentTourTooltips( state, context ) {
    // 1. Get the initial installed version, state.initialVersion
    // 2. Get the list of dismissed tours, see: getDismissedTours and isTourDismissed selectors
    // 3. Get all the toolTipTours from the import, 
    // 4. Filter out all matching dismissed tours (config.tourSlug)
    // 5. Filter out all tours where config.introducedVersion is greater than the initial installed version from 1.
    // 6. Filter out all tours where config.contexts doesn't contain the current context.
    // 7. Returns an array containing the matching toolTipTours that haven't been filtered out, or an empty array if no tooltip tours match.
},
```

Return value should match:
```js
[
  {
    tourID: 'allTrafficWidget',
	steps: [
		{
			target: '.googlesitekit-widget--analyticsAllTraffic__user-count-chart',
			title: __( "It's now easier to see your site's traffic at a glance", 'google-site-kit' ),
			content: __( 'Check the trend graph to see how your traffic changed over time', 'google-site-kit' ),
		},
		{
			target: '.googlesitekit-widget--analyticsAllTraffic__dimensions-chart',
			title: __( 'See where your visitors come from', 'google-site-kit' ),
			content: __( 'Click on the chart slices to see how each segment has changed over time', 'google-site-kit' ),
		},
		{
			target: '.googlesitekit-header__date-range-selector-menu',
			title: __( 'Check how your traffic changed since you last looked', 'google-site-kit' ),
			content: __( 'Select a time frame to see the comparison with the previous time period', 'google-site-kit' ),
		},
	],
  },
]
```

Make a change to Root component
https://github.com/google/site-kit-wp/blob/ff78440f65e0df5d55d42f17cf6f1502f5942037/assets/js/components/Root/index.js#L50

to render the **first** TourToolTip returned via the selector above if one applies, using `dataAPIContext` param. All other array elements can be ignored. See #2626 for the component to use, introduced in PR #2835.
<TourTooltip steps={steps} tourID={tourId} />

### Test Coverage

* Add storybook tests for the tooltip
* Update Jest tests for tour functionality

### Visual Regression Changes

* Storybook tests will be updated.

## QA Brief

* Disconnect/reset Site Kit
* Setup and activate Analytics
* See Analytics feature tour when navigating to the main SK dashboard
* Tour should only be shown on the main dash, not on any other screen
* Once going through the tour, it should not be shown again, even after resetting Site Kit
    * To force this to be cleared, run `googlesitekit.api.set( 'core', 'site', 'reset-persistent' )` in the browser console of a Site Kit screen
    * Then do a normal reset or user disconnect before connecting again
    * Note that when doing this, you will not see the tour because your "initial version" of Site Kit will be the current version.
    * To see the tour, without using other developer tools you would have to install the previous version of Site Kit 1.26.0 and set up Site Kit before updating back to this version
    * If you're comfortable with wp-cli you can use `wp user meta set your-user-name wp_googlesitekitpersistent_initial_version 1.2.3` where `1.2.3` is the initial version you want to set for Site Kit.

**Follow-up #3004 specific**
* Clear dismissed tours
* Set your browser to a width of 782px
* No tours should be shown, even if otherwise enabled/qualifying
* Any width below this width should also not display a tour
* A width of 783px or greater should display tours as normal

## Changelog entry

* Introduce tooltip tour guiding the user through the new version of the All Traffic widget.

**Comment by felixarntz** [comment] 2021-02-19 16:22
@ivankruchkoff The IB looks good overall, however I'm thinking it might make sense to keep tooltip tours in a central location in the codebase? For example, we would never want to run into a situation where two tooltip tours show at the same time, and for that we would need to have some central awareness.

I was thinking about tooltip tours more in the way that they apply to a certain screen (which also makes sense here for example, because e.g. the last tooltip here actually applies to an element that is not within the All Traffic widget). Maybe we could start with a `core/user` selector like `getCurrentTourTooltips( context )` (`context` would be e.g. `dashboard`), which includes all available tour configuration objects, performs the checks, and returns the current tooltip tour configuration object, or `null` if none. We could then have a high-level `CurrentTourTooltips` component that takes `context` as a prop and renders the current tooltip tour as needed. Every screen entrypoint file (e.g. `googlesitekit-dashboard.js`) would then include that component with the respective `context`.

What do you think? Also pinging @aaemnnosttv for feedback here.

Potentially we could do the centralized implementation in a follow-up issue and start with a more pragmatic approach like the current IB. That should be good to proceed with, since we won't have more than one tour in the beginning anyway. But overall, whether it's like I proposed above or not, we should definitely have these centrally managed in the long term.

**Comment by aaemnnosttv** [comment] 2021-02-22 16:14
> For example, we would never want to run into a situation where two tooltip tours show at the same time, and for that we would need to have some central awareness.

@felixarntz having multiple tours conditionally active at the same time is a situation we should plan for as I think that is fairly likely to happen once we start adding more. I think this is probably okay as long as they don't conflict with each other. That is, as long as there is a unified tour experience, showing multiple features in one tour should be fine (although this may raise other ideas about how to differentiate between tours). For example, if there were multiple feature tours which were "queued" and conditionally ready to show for different features, we should see how to best support this. Perhaps we don't need to fully implement support for this yet, since this will be the first and only tour, but we should have an idea as to how it will be done so that we can minimize unforeseen problems later.

Overall, I think we're on the same page regarding a centralized management of tours and it makes sense that we would use the datastore to handle it. Regarding the idea of context, we already have something similar in the `Root` for use with `CollectModuleData`, I wonder if it makes sense to plug tours in at the same level, or if we should be more selective about it and add it in the individual app components.

Regarding the use of CSS classes for tooltip targets, I think we should use a data attribute instead so that we don't have to worry about CSS classes changing and breaking behavior. Something like a `data-googlesitekit-tooltip-id={ tooltipID }` would be good.

**Comment by felixarntz** [comment] 2021-02-22 18:03
@aaemnnosttv 
> Overall, I think we're on the same page regarding a centralized management of tours and it makes sense that we would use the datastore to handle it. Regarding the idea of context, we already have something similar in the `Root` for use with `CollectModuleData`, I wonder if it makes sense to plug tours in at the same level, or if we should be more selective about it and add it in the individual app components.

Sounds good, we can use the `Root` component for that.

> Regarding the use of CSS classes for tooltip targets, I think we should use a data attribute instead so that we don't have to worry about CSS classes changing and breaking behavior. Something like a `data-googlesitekit-tooltip-id={ tooltipID }` would be good.

Why do we need specific CSS classes per tooltip tour? If we do though, I like the suggested alternative.

@ivankruchkoff Since this is not targeting the current release, I think it'd be best to do the centralized management approach for tooltip tours from the start, based on the previous feedback above. Can you update the IB accordingly? At a high level:
* add `getCurrentTourTooltips( context )` selector to `core/user` which returns relevant feature tour tooltips; basically, for now it should return the array of steps above if the `allTrafficWidget` criteria are matched, otherwise it should return an empty array; we can think later about how to deal with additional tours, but with this centralized layer we set the ground while not coding us into a corner where we're limited
* display any tooltips returned by the new selector in `Root`, which already receives the context
* the All Traffic widget component itself shouldn't need to be touched at all

This might slightly increase the estimate due to new selector, but I actually think it shouldn't be a lot of extra work, it largely just moves it elsewhere.

**Comment by ivankruchkoff** [comment] 2021-03-04 03:24
@felixarntz / @aaemnnosttv Thanks for the clarification in the comments.

I've gone through and updated the IB, with the idea that:
1) All tooltip tours can be stored in `/assets/js/tooltip-tours/`
2) We can add some config params that determine minVersion, and context to render the tooltip in.
3) The selector has the smart logic to take all of the tooltip tours and filter out any that don't match.

I think it makes sense to also take all of our `contexts` and break them out into a bunch of `const CONTEXT_DASHBOARD = Dashboard` so we know what valid values for `contexts` are. Here is what I have so far based on a search for `dataAPIContext`

- Activation,
- Adminbar,
- Dashboard,
- Settings,
- Single,
- Splash,
- UserInput,
- WPDashboard,

One other changes that I propose is:
**Priority** - If we want to show two tooltips in a given context (e.g. Dashboard), to be able to specify which one should load first, this can be denoted as config.priority. This will account for `helpVisibility` tour in #2847 to be shown after this one.

**Comment by felixarntz** [comment] 2021-03-04 20:25
@ivankruchkoff The updated IB looks great! Some follow-up feedback:

> I think it makes sense to also take all of our `contexts` and break them out into a bunch of `const CONTEXT_DASHBOARD = Dashboard` so we know what valid values for `contexts` are.

Sounds great, can you incorporate that into the IB?

> One other changes that I propose is:
**Priority** - If we want to show two tooltips in a given context (e.g. Dashboard), to be able to specify which one should load first, this can be denoted as config.priority.

That sounds like a great idea, _if_ we want to show multiple tooltip tours together, i.e. in a single consistent list of steps. I think we can leave this out for now to not increase scope further, especially since the components from #2626 do not support dealing with multiple tours at once yet (it only supports receiving a `tourID` and the `steps`, and it assumes that all steps belong to that single tour.

For now, let's only return the steps of a single tour, even if technically multiple tours qualify. We should revisit supporting multiple tours in a follow-up issue. However, one thing I would like to ask you to clarify is the shape of the return value of `getCurrentTourTooltips`. If it is simply an array of tooltips, we'd need to ensure each tooltip also includes the `tourID` it belongs to, so that the consuming component has that awareness. I think this format would prepare us for supporting multiple tours together, so I'd suggest to go with that. The main concern here is that this selector must also return the respective `tourID`, not just the `steps` without any tour ID association. (Still, for now let's keep returning steps for just a single tour at a time, so that we don't need to change the components as part of this issue.)

> 5. Filter out all tours where config.minVersion is greater than the initial installed version from 1.
> 6. Filter out all tours where config.maxVersion is less than the initial installed version from 1. (if the tour has a max version)

We don't need a `minVersion` and `maxVersion`. The initial version of the user never changes once set; the only important thing here is to ensure a tour isn't displayed if the user's initial version is _after_ that tour (or more precisely the related feature) was introduced. I suggest we use a single property and call it something like `introducedIn` or `introducedVersion`. Then, only tours where `introducedVersion` is greater than the user's initial version should be displayed.

> minVersion: '1.2.5',

Typo in your code sample for the All Traffic widget tooltip tour, this should be `1.25.0` :)

**Comment by ivankruchkoff** [comment] 2021-03-04 22:40
> That sounds like a great idea, if we want to show multiple tooltip tours together, i.e. in a single consistent list of steps. I think we can leave this out for now to not increase scope further, especially since the components from #2626 do not support dealing with multiple tours at once yet (it only supports receiving a tourID and the steps, and it assumes that all steps belong to that single tour.

Agreed, priority can be added later if needed, and the selector can then return the first matching tour based on priority if we need it.

- Changed `getCurrentTourTooltips` to `getCurrentTourTooltip`, because the component is called TourTooltip (in #2835)
- Added the shape we return { tourID: 'string', steps: 'array' }, or {} if no tour.
- Renamed minVersion to introducedVersion, no point for maxVersion, since we can just update a tour as we push a new version.
- Updated the typo for minVersion (1.25.0)
- Changed consts slightly to be `API_CONTEXT_` just to differentiate from  `assets/js/googlesitekit/widgets/default-contexts.js`, but I'm not particular fond of `API_CONTEXT`.

As part of Step 1. Updating API contexts, do we also need to update these files to match the new constants we're defining?

```
all relative to /assets/js


tooltip-tours/all-traffic-widget.js:27:		contexts: [ 'Dashboard' ],
modules/search-console/components/dashboard/SearchConsoleDashboardWidgetOverview.js:157:			context: [ 'Single', 'Dashboard' ],
modules/search-console/components/dashboard/SearchConsoleDashboardWidgetSiteStats.js:155:			context: 'Single',
modules/search-console/components/dashboard/LegacyDashboardWidgetPopularKeywordsTable.js:144:			context: [ 'Dashboard' ],
modules/search-console/components/dashboard/LegacySearchConsoleDashboardWidgetKeywordTable.js:132:			context: [ 'Single', 'Dashboard' ],
modules/search-console/components/dashboard/LegacySearchConsoleDashboardWidgetTopLevel.js:198:			context: [ 'Single', 'Dashboard' ],

modules/adsense/components/dashboard/LegacyAdSenseDashboardMainSummary.js:206:			context: 'Dashboard',
modules/adsense/components/dashboard/LegacyAdSenseDashboardMainSummary.js:224:			context: 'Dashboard',
modules/adsense/components/dashboard/LegacyAdSenseDashboardMainSummary.js:243:			context: 'Dashboard',
modules/analytics/components/dashboard/LegacyDashboardAcquisitionPieChart.js:143:			context: [ 'Dashboard', 'Single' ],
modules/analytics/components/dashboard/AnalyticsDashboardWidgetSiteStats.js:157:			context: 'Single',
modules/analytics/components/dashboard/LegacyAdSenseDashboardWidgetTopPagesTableSmall.js:166:			context: 'Dashboard',
modules/analytics/components/dashboard/AnalyticsDashboardWidgetOverview.js:200:			context: [ 'Single', 'Dashboard' ],
modules/analytics/components/dashboard/AnalyticsDashboardWidgetOverview.js:216:			context: [ 'Single' ],
modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetTopAcquisitionSources.js:138:			context: [ 'Single', 'Dashboard' ],
modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetPopularPagesTable.js:120:			context: [ 'Single', 'Dashboard' ],
modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetTopLevel.js:259:			context: 'Dashboard',
modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetTopLevel.js:278:			context: 'Dashboard',
modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetTopLevel.js:295:			context: 'Dashboard',
modules/analytics/components/dashboard/LegacyAnalyticsDashboardWidgetTopLevel.js:313:			context: 'Dashboard',
modules/analytics/components/dashboard/AnalyticsAdSenseDashboardWidgetTopPagesTable.js:175:			context: 'Single',
modules/analytics/components/dashboard/AnalyticsDashboardWidgetTopPagesTable.js:156:			context: [ 'Single', 'Dashboard' ],
```

**Comment by felixarntz** [comment] 2021-03-04 23:00
@ivankruchkoff 
> Changed `getCurrentTourTooltips` to `getCurrentTourTooltip`, because the component is called `TourTooltip` (in #2835)

This should remain as it previously was; the overall component is called `TourTooltips`, and this selector does (and should) return multiple tooltips.

> Added the shape we return { tourID: 'string', steps: 'array' }, or {} if no tour.

This would only work if the selector was returning tooltips for a single tour all the time, but as mentioned before we should prepare it for supporting multiple tours; therefore IMO an array of tooltips/steps, where each entry has the `tourID` associated with it would be more appropriate.

The current `TooltipTours` component is the main limitation here at this point, because it's built in a way that it only supports tooltips from a single tour. For now, we can simply only take the first x tooltips that use the same `tourID` from what the selector returns and pass them into the `TourTooltips` component. In general, we can always change components later since they are internally used, but with the datastore we should pay more attention about making it future-proof, so defining the shape in a way that also works for tooltips from multiple tours is crucial here.

> As part of Step 1. Updating API contexts, do we also need to update these files to match the new constants we're defining?

Yes, let's do that. I also think `API_CONTEXT` sounds a bit odd, but it is right now a quite general usage we have for this kind of context. Maybe `SCREEN_CONTEXT`?

**Comment by ivankruchkoff** [comment] 2021-03-05 00:19
Updated per last feedback.

**Comment by felixarntz** [comment] 2021-03-05 17:21
Excellent, IB ✅

**Comment by aaemnnosttv** [comment] 2021-03-09 21:35
@felixarntz regarding the ACs:

> This tooltip tour should be shown to everybody who initial Site Kit version is 1.25.0 or lower.

Shouldn't this be anyone with a initialVersion of Site Kit below 1.25.0 (rather than `<=`)? Feature tours shouldn't be shown for the same version that they are introduced if the user just started using Site Kit, correct?

**Comment by felixarntz** [comment] 2021-03-10 18:28
Since this is fairly short-term and now as new requirement needs to wait for #2944, I'll move this to the 1.29.0 release. Still, this is pretty much done, so can be merged soon.

**Comment by wpdarren** [comment] 2021-03-17 15:20
@aaemnnosttv @felixarntz I have followed the instructions to get the tour to appear again but unsuccessfully.  Please could you check the steps in the QAB, or offer any suggestions on an easy way to reset it.  Would it be something we could add into the tester plugin? We'd need to reset this a few times to test in different browsers/devices.

**Comment by wpdarren** [comment] 2021-03-18 12:13
### QA Update: Fail ❌ 

On desktop and mobile: On the 2nd and 3rd tour tip, it tells you to:

`Click on the chart slices to see how each segment has changed over time` or
`Select a time frame to see the comparison with the previous time period`

But the user is unable to do either of those actions while the tour is active because the elements are locked. 

Just wondering if the user should be able to interact with those elements during the tour, if not, do you think we need to change the wording? 

On mobile, here are a few UX/UI issues.

1) Above the tour tip we could do with a little padding at the top, this was tested on iOS and Android phones  - [Screenshot](https://user-images.githubusercontent.com/73545194/111621849-6b474d80-8823-11eb-8d5a-841c38b78660.png)

2) When you click on `Next` for the 2nd tip, the tour jumps down to the pie chart but you only see part of the tour tip. I created this screencast to show you what I mean.  You have to scroll down the page to view it. 

https://user-images.githubusercontent.com/73545194/111622066-b3ff0680-8823-11eb-9001-ed87218c3b5e.mov

3) For the third tip of the tour, the period dropdown is not highlighted properly as you can see on my screenshot.  This could be due to the issue with the 2nd tip, mentioned above.  - [Screenshot](https://user-images.githubusercontent.com/73545194/111623231-0ee52d80-8825-11eb-9468-abcff12c408f.png)

**Comment by aaemnnosttv** [comment] 2021-03-19 11:49
> On desktop and mobile: On the 2nd and 3rd tour tip, it tells you to:
> `Click on the chart slices to see how each segment has changed over time` or
> `Select a time frame to see the comparison with the previous time period`
> But the user is unable to do either of those actions while the tour is active because the elements are locked. 

@wpdarren I think that's fine. You shouldn't expect to be able to interact with elements as usual during a tour. It would also be odd to phrase every instruction as "after this tour is over [...]" 🙂 

> On mobile, here are a few UX/UI issues.

It seems there are some issues with the tour highlighting the proper area in mobile consistently.

@tofumatt can you take a look and see what we can do here?

**Comment by tofumatt** [comment] 2021-03-20 00:29
I don't think the scroll behaviour is too bad, though I agree we should look to scroll to `.googlesitekit-tour-tooltip` whenever the tooltip is moved back/forward.

I did, however, notice another mobile issue when moving to the last tooltip, then back to the beginning. The highlighted window into the content is in the wrong place:

![2021-03-20 00 25 03](https://user-images.githubusercontent.com/90871/111853498-31557480-8913-11eb-875a-4c059062fa57.gif)

So I think we can tweak the behaviour here a bit in general, but anything beyond that isn't needed? I don't think we should omit these on mobile though; they otherwise seem fine and quite useful there.

**Comment by aaemnnosttv** [comment] 2021-03-22 13:20
@tofumatt I've tracked down the point where the behavior of the tour changes to this breakpoint:
* window < 783px = bad
* window > 782px = good

This is a breakpoint used in WP admin in several places so it isn't exactly clear what specifically is broken but it seems related to this issue: https://github.com/gilbarbara/react-joyride/issues/594. Looking at [the PR for this](https://github.com/gilbarbara/react-joyride/pull/658) (just opened today!) it seems that the problem is with absolutely positioned elements. WordPress changes the `position` of some elements in this viewport size [here](https://github.com/WordPress/WordPress/blob/590d59e92fb79f233bce0f2f7de31018920e957d/wp-admin/css/common.css#L3760-L4066) and [here](https://github.com/WordPress/WordPress/blob/0bfb5f043bec9149cdb0216789f6b67d16763962/wp-admin/css/admin-menu.css#L754-L929) so it's likely that this problem is related to the same bug.

I would suggest we disable the tours below this viewport for now and open an issue to fix it in the future as this seems to be mostly an upstream issue. cc: @felixarntz

**Comment by felixarntz** [comment] 2021-03-22 14:28
@aaemnnosttv Sounds good, let's disable on those viewports for now. Can you open an issue to address this in the future?

**Comment by tofumatt** [comment] 2021-03-22 16:37
Agreed, disabling them on small viewports for now seems fine to me. I'm filing the follow-up issue now 🙂

**Comment by aaemnnosttv** [comment] 2021-03-22 18:56
@tofumatt – follow-up PR is ready for review!

**Comment by wpdarren** [comment] 2021-03-23 12:38
### QA Update: Pass ✅ 

**Verified:**

- When Google Analytics is activated, the tooltip tour appears
- As a user I am able to click on the next button to go through the tour steps. 
- The Tooltip tour only appears on Site Kit Dashboard
- When the screen size width is  782px then the tooltip does not appear. 
- When the X icon or "Got it' link is clicked then the tour is closed.
- When the user refreshes Site Kit Dashboard, the tour does not reappear. 

Here's a screencast of the tooltip tour and behaviour on desktop and mobile. 

https://user-images.githubusercontent.com/73545194/112147268-77624f00-8c17-11eb-9b62-bbb28aeeec2a.mp4

**Closed** 2021-03-29 17:44 UTC
Labels: Module: Analytics, P0, Rollover, Type: Enhancement
