### ISSUE TITLE
Add actions and selectors for managing module settings panel state

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2181] opened 2020-10-15 23:11 UTC
The `core/modules` store should support managing the state for the settings panels Site Kit Settings.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `core/modules` store should receive a new selector `getModuleSettingsPanelState( slug )` that returns for the module identified by the given slug in which state the panel is (e.g. whether it is closed, in "view" or "edit" mode etc.).
* The `core/modules` store should receive a new action `setModuleSettingsPanelState( slug, value )` that sets the panel state for the module identified by the given slug to the given value.
* The following settings panel states should be possible/valid to be passed to `setModuleSettingsPanelState`:
    * `closed`
    * `view`
    * `edit`
* There should be a separate `locked` "meta-state" which cannot be settable via the action, but selectable separately.
* Dedicated selectors should be added for each state:
    - `isModuleSettingsPanelOpen( slug )`
    - `isModuleSettingsPanelClosed( slug )`
    - `isModuleSettingsPanelEdit( slug )`
    - `isModuleSettingsPanelLocked( slug )`
* The initial value for every module's settings panel should be `closed`.
* The following rules should be applied when modifying the settings panel state or selecting from it:
    - Only a single module can be viewed/open/edited at a time
    - A module is locked when another module is being edited

## Implementation Brief

* Create a new file to house the selectors/actions: `assets/js/googlesitekit/modules/datastore/settings-panel.js`.
* It should have a `state` shape as follows where `ModuleSlug` is a string or `null`:  
    ```js
    {
        settingsPanel: {
            currentModule: ModuleSlug, // default `null`
            isEditing    : Boolean,    // default `false`
        }
    }
    ```
* Add a new selector `getModuleSettingsPanelState( slug )` that returns `view|closed|edit` as a string.
* Add state-specific selectors for each state
    - `isModuleSettingsPanelOpen( slug )` – (`slug === currentModule`)
    - `isModuleSettingsPanelClosed( slug )` – (`slug !== currentModule`)
    - `isModuleSettingsPanelEdit( slug )` – (`slug === currentModule && isEditing`)
    - `isModuleSettingsPanelLocked( slug )` – (`slug !== currentModule && isEditing`)
* Add a new action `setModuleSettingsPanelState( slug, value )` that allows setting `value` to one of: `'view' | 'edit' | 'closed'`.  
Trying to set any other value should result in an error.
    - If setting `slug` to `view`, set `currentModule` to `slug` and `isEditing` to `false`
    - If setting `slug` to `edit`, set `currentModule` to `slug` and `isEditing` to `true`
    - If setting `slug` to `closed`, set `currentModule` to `null` and `isEditing` to `false`

### Test Coverage

* Create a `assets/js/googlesitekit/modules/datastore/settings-panel.test.js`
* Add tests for
    - `actions.setModuleSettingsPanelState`
    - `selectors.getModuleSettingsPanelState`
    - `selectors.isModuleSettingsPanelOpen( slug )`
    - `selectors.isModuleSettingsPanelClosed( slug )`
    - `selectors.isModuleSettingsPanelEdit( slug )`
    - `selectors.isModuleSettingsPanelLocked( slug )`

### Visual Regression Changes

* None.

## QA Brief

* Tests should pass but otherwise there is nothing to directly QA for this issue.

## Changelog entry

* Add `core/modules` actions and selectors for managing module settings panel state.

**Comment by felixarntz** [comment] 2020-10-17 01:30
@tofumatt Mostly LGTM, but two things don't satisfy the ACs:

> Add a new selector `getModuleSettingsPanelState( slug )` that returns the value in `state.panelState[ slug ]` (or `undefined` if it's not set)

This should never return `undefined` as there is no "loading" stage here. The initial value for every settings panel should be `closed` per the ACs. We could consider returning `null` if `slug` is not for a valid module - but any valid module should always return a real value.

> Add a new action `setModuleSettingsPanelState( slug, value )` that allows setting `state.panelState[ slug ]` to one of: `'view' | 'locked' | 'closed'`.

Per the ACs `locked` shouldn't be allowed, but `edit` should.

**Comment by tofumatt** [comment] 2020-10-19 19:10
Ah, right on. Fixed! 🙂

**Comment by felixarntz** [comment] 2020-10-19 19:47
@tofumatt IB pretty much LGTM, however it's still missing a mention of `closed` being the default value.

> `undefined` should not be returned.

This is true, but it would be more clear saying that, if `state.panelState[ slug ]` is `undefined` and it _is_ a valid module, the function should return `closed`.

**Comment by tofumatt** [comment] 2020-10-20 17:56
Ah, right on. I think using a registry selector for modules that aren't yet defined in the panel state should cover that and create an effective default state—let me know what you think about that approach 😄

**Comment by felixarntz** [comment] 2020-10-23 18:00
IB ✅

**Comment by ivankruchkoff** [comment] 2020-10-24 23:47
Per https://github.com/google/site-kit-wp/issues/2182#issuecomment-710115194 this file `assets/js/googlesitekit/modules/datastore/settings.js` is being created in the PR https://github.com/google/site-kit-wp/pull/2265

**Comment by aaemnnosttv** [comment] 2020-10-28 13:23
@felixarntz @tofumatt – not sure if this was intended originally or not, but I don't think we should store `locked` in state since this is an easily calculable "meta-state". In particular, storing it in state prevents makes it more complicated to "unlock" the module because it isn't known what state it should go back to. This should be handled by the selector alone IMO. If a panel for a slug is `edit` and the given slug is not the one with the edit state, then it is `locked` or potentially still `null` if not exists without the need to change anything in state.

To simplify the lookup with our current model that limits editing to only a single module at a time, I think storing a `settingsEditing` key in state (or other name) that stores the slug of the module being edited would work well. I used a similar strategy in an earlier iteration of #1623 ([source](https://github.com/google/site-kit-wp/blob/33e827c4a457d340ded9dd047ccd92e6cad6cbcd/assets/js/googlesitekit/modules/datastore/settings-view.js)).

Thoughts?

**Comment by ivankruchkoff** [comment] 2020-10-29 19:43
Also from the CR https://github.com/google/site-kit-wp/pull/2266#discussion_r513446482
If a module is deactivated after it has state, shouldn't that panelState be removed? We could tie in to https://github.com/google/site-kit-wp/blob/97a3cf8/assets/js/googlesitekit/modules/datastore/modules.js#L194 otherwise our panelState is only a source of truth when the module is active, which could lead to some bugs down the line if we're depending on panelState.

**Comment by felixarntz** [comment] 2020-10-30 19:21
@aaemnnosttv @ivankruchkoff
> not sure if this was intended originally or not, but I don't think we should store `locked` in state since this is an easily calculable "meta-state".

That's a good point. We should be able to "dynamically" calculate it in the selector (based on whether anything else is in `edit` state). So I agree with that suggestion to not actually set it, but return it as a possible value in the selector. The ACs already describe that this state value shouldn't be externally available to be set, but actually not setting it at all makes most sense. Let's keep it as value to return by the selector though.

**Comment by ivankruchkoff** [comment] 2020-11-03 00:55
I've gone ahead and updated to dynamically calculate locked status. This makes a small change to the state implementation to have the following structure:
`{ editing: null, modules: {} };
`
where modules contains the 'view', 'edit', 'closed' for a slug and editing is null or the slug being edited, e.g.:
`
{ editing: 'analytics', modules: { analytics: 'edit'} };
`
With the derived _locked_ state it gives us this potential scenario:

panelState = 
`
{ editing: 'analytics', modules: { analytics: 'edit', 'search-console': 'edit'} };
`

Data.stores["core/modules"].selectors.getModuleSettingsPanelState('search-console') = 'locked' (because we are editing analytics)

**Comment by aaemnnosttv** [comment] 2020-11-09 10:01
@felixarntz I've updated the ACs (mostly additive for clarity) and IB here per our last conversation. Let me know if anything is out of place or missing here to prevent further unnecessary changes for @ivankruchkoff .

@ivankruchkoff – please take a look and let me know if you have any questions or concerns regarding these changes before resuming.

**Comment by felixarntz** [comment] 2020-11-09 18:48
@aaemnnosttv @ivankruchkoff ACs look accurate, I think the modified IB can be a bit simplified:
* Instead of `state.editingModule`, I think it would be sufficient to make this a boolean like `state.isEditing`. Having the module slug there is redundant, since it must always be the same module slug as in `state.currentModule`.
* In the case descriptions, "If setting `slug` to `view` and `slug` is the current module, do nothing" is not fully correct, if `state.editingModule` (or the above `state.isEditing`) is truthy, it should be unset (or set to `false`).

**Comment by aaemnnosttv** [comment] 2020-11-10 08:02
@felixarntz 

> * Instead of `state.settingsPanel.editingModule`, I think it would be sufficient to make this a boolean like `state.settingsPanel.isEditing`. Having the module slug there is redundant, since it must always be the same module slug as in `state.settingsPanel.currentModule`.

SGTM 👍  I've updated the IB to reference this name for the state instead.

> * In the case descriptions, "If setting `slug` to `view` and `slug` is the current module, do nothing" is not fully correct, if `state.settingsPanel.editingModule` (or the above `state.settingsPanel.isEditing`) is truthy, it should be unset (or set to `false`).

From a semantic perspective, I don't think we should implement a toggling behavior for a "set*" action. If we want to offer that capability from the datastore (which is totally reasonable, and something I had added originally as well), then I think it makes more sense to name the action like `toggleSettingsPanelEdit` and/or `toggleSettingsPanelOpen` although we can do without these by using the set action and delegate the toggling to the component.

```js
const isPanelOpen = useSelect( ( select ) => select( 'core/modules' ).isSettingsPanelOpen( slug ) );
const { setSettingsPanelState } = useDispatch( 'core/modules' );
const togglePanel = useCallback( () => {
    setSettingsPanelState( slug, isPanelOpen ? 'closed' : 'view' )
}, [ slug, isPanelOpen ] );
```

This is quite simple to implement so the question is whether or not it makes sense to build that into the datastore or not?
I've updated the section for how `setSettingsPanelState` should behave, which is even simpler than before and very straightforward. No objections from me about adding an action to toggle a specific state, but only ask that we do that with a separate action.

**Comment by felixarntz** [comment] 2020-11-17 03:10
As discussed last week, we had somewhat a misunderstanding regarding your latest comment @aaemnnosttv - the current IB LGTM!

**Comment by aaemnnosttv** [comment] 2020-11-20 08:14
@ivankruchkoff – this one is ready to resume if you haven't already 👍

**Comment by ivankruchkoff** [comment] 2020-11-23 05:20
@aaemnnosttv - addressed CR feedback and changed the implementation to match the new IB. Reassigned it back to you as you looked at initially.

**Comment by ivankruchkoff** [comment] 2020-11-25 05:32
Updated per CR feedback.

**Comment by cole10up** [comment] 2020-11-29 19:28
### QA ✅

Quick high level regressions of module settings with all modules connected looks good.

![image](https://user-images.githubusercontent.com/57115907/100551523-f5988100-3235-11eb-847c-c4e54ac81b54.png)

Sending to approval

**Closed** 2020-12-03 17:12 UTC
Labels: Good First Issue, P0, Type: Enhancement
