### ISSUE TITLE
AdSense: new intl.numberformat error on dashboard

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1107] opened 2020-02-07 12:55 UTC
## Bug Description

Some users are encountering errors on their AdSense dashboard. Reports of this issue started after the last plugin release (1.2.0)

![image](https://user-images.githubusercontent.com/41326532/74031206-c82dce80-49a8-11ea-88d0-f3569ef78742.png)

`new Intl.NumberFormat(navigator.language,{style:”currency”,currency:n}).formatToParts is not a function. (In ‘new Intl.NumberFormat(navigator.language,{style:”currency”,currency:n}).formatToParts(e)’, ‘new Intl.NumberFormat(navigator.language,{style:”currency”,currency:n}).formatToParts’ is undefined)`

Related WP Support Form threads:
- [https://wordpress.org/support/topic/adsense-and-analytics-error/](https://wordpress.org/support/topic/adsense-and-analytics-error/)
- https://wordpress.org/support/topic/cant-access-sitekit-section-of-wp-dashboard-or-place-ads-because-of-error-code/
- https://wordpress.org/support/topic/wp-site-kit-dashboard-adsense-error/

## Additional information

- Unable to reproduce on testing environment
- Possibly related to #1054

## Screenshots

Safari 12 (Mojave)
![image](https://user-images.githubusercontent.com/1621608/75706686-45a5df80-5cc6-11ea-9fa6-4f477d9ebb57.png)

Edge 17 (Win 10) - Different error than reported
![image](https://user-images.githubusercontent.com/1621608/75706706-55bdbf00-5cc6-11ea-81ed-d344e78dc0bc.png)
Interestingly, [this thread](https://stackoverflow.com/a/55527898) reports being on a more recent version of Windows and on an older version of Edge than they should be due to reported problems with auto-update.

## Additional Context

 - PHP Version: 
 - Browser: Safari 12, Edge 17
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Currency formatting should work in all major browsers, going back at least 2 major versions

## Implementation Brief

* Refactor number formatting to use existing `numberFormat()` utility function which does not use `formatToParts`
* Merge #1261 

## Changelog entry

* Fix JavaScript errors in AdSense screens that was a result of `Intl.NumberFormat.formatToParts` not being supported in Safari.

**Comment by jamesozzie** [comment] 2020-02-11 15:40
This error may be specific to the Safari browser, as mentioned by [one](https://wordpress.org/support/topic/wp-site-kit-dashboard-adsense-error/#post-12418602) user. 

Another [user](https://wordpress.org/support/topic/adsense-and-analytics-error/) is no longer encountering this issue, after using a Chrome incognito browser.

**Comment by cole10up** [comment] 2020-02-26 15:59
Ran through a series of tests using safari and chrome with our current Adsense test accounts. I was unable to reproduce this issue. Moving to level 2.

**Comment by ernee** [comment] 2020-02-29 05:40
is #293 related?

**Comment by aaemnnosttv** [comment] 2020-03-02 18:47
This issue has been replicated and moved forward to execution.

Additional context and screenshots have been added.

**Comment by tofumatt** [comment] 2020-03-03 01:17
The issue here is that Safari doesn't support `formatToParts` for `Int.NumberFormat`, but there are no straightforward/lightweight polyfills I could find that would fix the issue for the limited, affected, recent browsers.

Seemingly this issue only appears when doing currency formatting, which already seems messed up. If I add a unit test for currency conversion using that utility function:

```js
it( 'should format currencies', () => {
	expect( readableLargeNumber( 123456789, 'USD' ) ).toStrictEqual( '$123.5M' );
} );
```

I get this failure:
<img width="473" alt="Screenshot 2020-03-03 01 16 42" src="https://user-images.githubusercontent.com/90871/75733278-c4ae0e80-5cec-11ea-92f0-9d8b494ad2bf.png">

That formatting definitely seems off.

**Comment by felixarntz** [comment] 2020-03-05 00:55
I'm not entirely sure this is worth implementing, especially with the current IB as we'd be pulling in a dependency (which btw explicitly states not to use it!) only to address a shortcoming of an older browser. Yes we technically should support about 2 versions back, but I'd argue it's definitely not worth pulling in a dependency only for Safari 12.

Let's try to find an alternative solution that doesn't require us to add new 3P code. I'd even be okay to use some very rudimentary formatting if the function isn't supported.

**Comment by tofumatt** [comment] 2020-03-18 14:24
IB ✅

@aaemnnosttv's new solution in #1261 looks great and solves this one 👍

**Comment by cole10up** [comment] 2020-03-25 16:20
Ran a series of tests with @ivankristianto 

On our end we were able to identify that the issues persisted with international currency. Conscious of the timing around this fix, we ensured the plugin wasn't breaking current functionality.

![Screen Shot 2020-03-25 at 23 12 29](https://user-images.githubusercontent.com/57115907/77559739-c4330e80-6e79-11ea-9aea-042e5b8ced2f.png)

Passed QA ✅

**Closed** 2020-03-25 18:52 UTC
Labels: P0, Type: Bug
