### ISSUE TITLE
Release 1.103.0

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#7136] opened 2023-06-05 19:22 UTC
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Release is prepared, tested, and deployed to wordpress.org.

## Implementation Brief

* N/A

## QA Brief

* N/A

## Changelog entry

* N/A

**Comment by wpdarren** [comment] 2023-06-16 11:18
### QA Update: ⚠️ 

When I visit the Admin settings a console error appears:

`Google Site Kit API Error method:GET datapoint:key-metrics type:core identifier:user error:"No route was found matching the URL and request method."`

![image](https://github.com/google/site-kit-wp/assets/73545194/0e5aae16-fc32-4f5e-8397-922c0ac6ccc0)

When I switched to 1.102.0 this error does not appear, so looks like a regression.  It doesn't appear on any of the other settings tabs.  It doesn't appear to be linked with GA4Reporting because the error appears with the feature flag disabled.

**Comment by wpdarren** [comment] 2023-06-16 11:59
### QA Update: ⚠️ 

Think I have found a regression bug for `GA4Reporting`.  I have a new site, new GA4 property with GA4Reporting enabled.  

No migration between UA and GA4.  

When you go to the Site Kit settings for Analytics, the Dashboard view title, toggle and text appears. 

In my opinion this shouldn't appear for a brand new site / GA4 property. When I switched to 1.102.0 this does not occur, so can only assume that this is a regression.  The toggle is disabled, so, the user cannot change it. 

![image](https://github.com/google/site-kit-wp/assets/73545194/b93b3fd8-60a1-4276-984c-547bc6753ec4)

**Comment by mohitwp** [comment] 2023-06-16 12:25
@wpdarren The Analytics settings related changes are introduced in the ticket #6875. As per AC, it should always show up. 
![image](https://github.com/google/site-kit-wp/assets/94359491/89d19cb0-83cb-411b-a1f0-52701a1665be)

**Comment by techanvil** [comment] 2023-06-16 12:40
As discussed on Slack, the purpose of showing this in a disabled state is to avoid the layout shift that would otherwise occur when the toggle is subsequently displayed in response to a user action.

The only scenario where we can be sure this won't happen is when there is only one Analytics account, and this account has no UA properties. We could potentially treat that as a special case and not show the Dashboard View section, but this would need to be addressed as a new issue.

**Comment by tofumatt** [comment] 2023-06-19 16:23
QA ✅ 

Aside from issues noted above (the User Input one is now fixed, confirmed in my testing—and the other one isn't a bug), everything looks good to me. No issues with a new site setup using GA4, etc. 🙂

**Comment by kuasha420** [comment] 2023-06-20 07:17
QA: :heavy_check_mark: 

* Tested the latest `main`. 
* Tested on an InstaWP site with default feature flags. 
* Tested Plugin Setup flow (with and without Analytics as part of initial setup).
* Set up all modules.
* Tested Dashboard Sharing and view-only dashboard. 

Aside from the known issues, rest looks good to me and I didn't find any additional regressions and/or errors. :+1:

**Comment by hussain-t** [comment] 2023-06-20 08:16
Aside from the issues noted above, the rest LGTM!

### QA Verified :white_check_mark:
- Smoke tested.
- Verified the changes I’ve been involved with.
- Performed some ad-hoc testing.

**Comment by nfmohit** [comment] 2023-06-20 08:19
## Release Tested ✅

- Release tested 1.103.0 thoroughly.
- Set everything up from scratch on a live (InstaWP) site.
- Didn't spot any unexpected console errors.
- Verified UI in different device breakpoints.
- Verified changes I've been involved with.
- Used our release testing checklist to ensure everything is checked.

**Comment by mohitwp** [comment] 2023-06-20 13:39
### QA Update ✅ 

- Ran QA checklist.
- Verified main and entity dashboard when 'ga4Reporting' feature flag is enabled.
- Verified both Ga4 and UA dashboard.
- Verified analytics setup.
- Verified Dashboard sharing functionality.

**Comment by wpdarren** [comment] 2023-06-20 13:49
### QA Update: ✅ 

- Completed the tasks in the QA checklist 
- Went through Site Kit set up with gathering, zero and live data states. 
- Tested with GA4 feature flag enabled:
  - UA and GA4 dashboard views. 
  - Tested with only UA.
  - Tested with just GA4.
- Tested `ga4ActivationBanner` to make sure that the banner still appears telling the user they have X days left.  
- Tested Dashboard Sharing with 2nd admin and view only user
- Tested AdSense and all the appropriate statuses. 

Note: ran through some additional tests on Site Kit settings due to the console error mentioned above. 

Found a number of UX/UI non regression issues that I will create tickets for.

**Closed** 2023-06-20 18:12 UTC
Labels: P0, Type: Task
