### ISSUE TITLE
Implement RRM disconnection confirmation modal

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8845] opened 2024-06-08 12:56 UTC
## Feature Description

The module disconnection confirmation modal should be updated for Reader Revenue Manager to include a warning to let the user know that:
- Disconnecting the module will only remove the snippet added by Site Kit, but will not deactivate Reader Revenue Manager.
- They can visit the Reader Revenue Manager platform if they intend to deactivate it.

- [See relevant section in design doc](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#heading=h.sotmw0vc4x21).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The module features for Reader Revenue Manager that appear in the module disconnection confirmation dialog should be added as follows:
	* > Reader Revenue Manager publication tracking (your Reader Revenue Manager account will still remain active)

## Implementation Brief

1. In `assets/js/modules/reader-revenue-manager/index.js`, add the following in `features` array in `registerModule` function.

```js
    __(
        'Reader Revenue Manager publication tracking (your Reader Revenue Manager account will still remain active)',
        'google-site-kit'
    ),
```
Adding this would add the intended message in the modal.

2. Add a new css rule so that the feature text is visible completely. The rule can be like

```css
    .googlesitekit-settings-module--reader-revenue-manager .mdc-list-item__text {
        white-space: normal;
    }
```

This rule can be added to `assets/sass/vendor/_mdc-dialog.scss`.

### Test Coverage

1. Add a test that features for the module is available and the text should match which is in AC.

## QA Brief

Note: Although the module cannot be setup completely as of now, but this issue can be tested with the given steps below.

* Activate the module.
* Go to `Site Kit > Settings`,  click on `Reader Revenue Manager` and then click `Edit` CTA.
* Click on `Disconnect Reader Revenue Manager from Site Kit` CTA.
* A modal should get opened. Ensure that modal content matches with the AC and figma.
* Clicking on disconnect should deactivate the module.

## Changelog entry

* Populate the feature list in the Reader Revenue Manager disconnection confirmation modal.

**Comment by nfmohit** [comment] 2024-06-24 03:45
Hi @sigal-teller 👋 Would you be so kind as to help us with the UX here? For example, here is a module disconnection banner for the Analytics module:

![image](https://github.com/google/site-kit-wp/assets/20284937/eafc56f1-9eff-40a5-a0e5-750c78de7b01)

This is a common component that we use across all modules with just the module name and list of features changing between modules, so I don't think we'd want to change this too much. For the Reader Revenue Manager module, there is a requirement to let the user know at this stage the following:

> * Disconnecting the module will only remove the snippet added by Site Kit, but will not deactivate Reader Revenue Manager.
> * They can visit the Reader Revenue Manager platform if they intend to deactivate it.

In my opinion, a small notice before the disconnect action should be sufficient. Thank you!

**Comment by sigal-teller** [comment] 2024-06-30 14:53
@nfmohit I added the UX for the disconnect module [here](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=764-3592&t=QLXBRgK3mUWyl5Ur-1) with one comment for you to review.

**Comment by nfmohit** [comment] 2024-07-02 18:23
LGTM, thank you @sigal-teller !

**Comment by kuasha420** [comment] 2024-07-11 07:41
IB :white_check_mark:

**Comment by wpdarren** [comment] 2024-07-22 11:37
### QA Update: ❌ 

@ankitrox I have a very minor UX/UI issue that I would like to highlight.   The bulletpoint and subsequent paragraph are not aligned as per the figma designs. There needs to be some padding/margin.  

Test site:
![image](https://github.com/user-attachments/assets/8cb69d5c-8d37-491d-9d97-a157f446f0f3)

Figma design
![image](https://github.com/user-attachments/assets/06a5413c-12ca-4d5b-b47a-03348d300a53)


**Verified:**

- A modal appears and the content matches with the AC and figma.
- Clicking on disconnect should deactivate the module.

**Comment by ankitrox** [comment] 2024-07-22 15:52
I have added couple of lines of CSS fix to accommodate the design change. Please note that those bullets will be aligned in a similar fashion (as of RRM disconnection modal) for other disconnection modal as well; for example: Analytics-4 disconnection modal.

I have to added the screenshots for the same.

<img width="1332" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC82QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6604a973fb28d8dd1b2d69f52e9e5e0836b9004d/Screenshot%202024-07-22%20at%209.14.10%E2%80%AFPM.png" alt="Screenshot 2024-07-22 at 9.14.10 PM.png" />

<img width="1299" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUw2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--047fbbe19fa0eaf84133019f6ccd8a0aa9bc2248/Screenshot%202024-07-22%20at%209.14.29%E2%80%AFPM.png" alt="Screenshot 2024-07-22 at 9.14.29 PM.png" />

<img width="1346" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVA2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--76513981be4996c3484fb0c6619b5232277b657c/Screenshot%202024-07-22%20at%209.15.28%E2%80%AFPM.png" alt="Screenshot 2024-07-22 at 9.15.28 PM.png" />

<img width="1325" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWI2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f52a99c0377668e15424930fb25cb54ed2cb385/Screenshot%202024-07-22%20at%209.22.13%E2%80%AFPM.png" alt="Screenshot 2024-07-22 at 9.22.13 PM.png" />

**Comment by techanvil** [comment] 2024-07-22 16:25
Thanks @kuasha420, however, the proposed fix does introduce a regression, as the bullet points and feature descriptions are no longer centre-aligned vertically. For example this is how the Analytics modal currently looks, and the fix we introduce should retain this styling while ensuring the bullet point is correctly aligned when a feature description spans multiple lines of text.

![image](https://github.com/user-attachments/assets/ae84d900-9d96-4550-ba18-9951ea5724e5)

I've taken a look into it myself and can see that, while fairly trivial overall, the fix could be relatively time consuming compared to the severity of the defect.

I would therefore suggest we treat this as a known issue to address as part of the bug bash or post-launch. @wpdarren, could you please create an issue to track it? We can prioritise is as a P2 for the time being and reassess at bug bash time.

**Comment by wpdarren** [comment] 2024-07-23 04:33
### QA Update: ✅ 

**Verified:**

- A modal appears and the content matches with the AC and figma.
- Clicking on disconnect should deactivate the module.

Note: that is a styling issue where the bulletpoint is not aligned to the text like the figma designs and in additional the horizonal line has no space between the text underneath.  I will create a ticket for this since it should be fixed as it look odd. 

![image](https://github.com/user-attachments/assets/dbe5ba43-fccc-467b-91f1-61b4e76c04d5)

**Closed** 2024-07-25 18:55 UTC
Labels: P0, Type: Enhancement, Team M, Module: RRM
