### ISSUE TITLE
Remove `ga4Reporting` feature flag

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6856] opened 2023-04-11 21:19 UTC
## Feature Description

Once GA4 Reporting is available to all sites, and the flag is no longer needed, it should be removed entirely. It's likely that many other issues will be needed before this can be actioned but this will eventually be needed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `ga4Reporting` feature flag should be removed such that conditions that use it should keep the code path where the flag is `true`
* Any other references to the flag should be removed, except the changelog

## Implementation Brief

* In `assets/js/components/DashboardEntityApp.js` 
  * Remove this line `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );`
  * On the line `{ ga4ReportingEnabled && <DashboardViewIndicator /> }` remove `ga4ReportingEnabled` so there is no conditional rendereding of that component
* In `assets/js/components/DashboardMainApp.js`
  * Remove `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );`
  * Exclude `ga4ReportingEnabled` from `{ ga4ReportingEnabled && <DashboardViewIndicator /> }` conditional rendering
* In `assets/js/components/notifications/BannerNotifications.js`
  * Remove `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );` 
  * Remove `ga4ReportingEnabled` conditional check from rendering 2 conditional components `SwitchedToGA4Banner` and `SwitchGA4DashboardViewNotification`
* In `assets/js/feature-tours/ga4-reporting.js`
  * Remove `checkRequirements: () => isFeatureEnabled( 'ga4Reporting' )`
* In `assets/js/modules/analytics/components/common/AdsConversionIDTextField.js`
  * Remove `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );`
  * Remove `ga4ReportingEnabled` from this conditional check https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/components/common/AdsConversionIDTextField.js#L83-L88 so conditional check remains as :
```js
if (
	isValidValue &&
	( ! ( isUAEnabled && snippetEnabled ) && ! ga4SnippetEnabled ||  ! snippetEnabled )
) {
```
* In `assets/js/modules/analytics/components/common/AnonymizeIPSwitch.js`
  * Remove  `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );`
  * Remove `ga4ReportingEnabled` conditional check from 2 components, so they are rendered unconditionally
* From `assets/js/modules/analytics/components/common/ProfileSelect.js`
  * Remove  `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );`
  * Remove `ga4ReportingEnabled` from conditional check in `displayProfiles`
* In `assets/js/modules/analytics/components/common/UACutoffWarning.js`
  * Remove `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );`
  * Remove `ga4ReportingEnabled` conditional check from `shouldDisplayWarning`
* In `assets/js/modules/analytics/components/common/AccountCreate/index.js`
  * Remove `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );`
  * Remove `ga4ReportingEnabled` from `const { createAccount } = useDispatch(` so it uses `MODULES_ANALYTICS_4` by default - `const { createAccount } = useDispatch( MODULES_ANALYTICS_4 );`
  * `getAccountDefaults` should use `getAccountDefaultsGA4`
  * Remove `ga4ReportingEnabled` also from `hasRequiredScope`, `isDoingCreateAccount`, `canSubmitAccountCreate`, `accountTicketTermsOfServiceURL`, they should all use value that `ga4ReportingEnabled` enables, without conditional check
  * In `useEffect` hook, `await API.invalidateCache` should get `analytics-4` as second param without condition, and `ga4ReportingEnabled` should be removed from it's dependency array
  * In https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/components/common/AccountCreate/index.js#L292-L293 only `<WebDataStreamField />` component should render
  * Remove this block - https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/components/common/AccountCreate/index.js#L322-L329
* In `assets/js/modules/analytics/components/settings/GA4SettingsControls.js`
  * Remove `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );` and `ga4ReportingEnabled` from conditionally rendering `AccountSelect` component
* In `assets/js/modules/analytics/components/settings/GA4SettingsView.js`
  *  Remove `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );` and `ga4ReportingEnabled` from conditionally rendering `div` block
* In `assets/js/modules/analytics/components/settings/OptionalSettingsView.js`
  *  Remove `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );` 
  *  Remove `ga4ReportingEnabled` from `showIPAnonymizationSettings`:
```js
const showIPAnonymizationSettings =
		useSnippet &&
		ampMode !== 'primary' && isUAConnected;
``` 
  * Remove `ga4ReportingEnabled` from `showAdsConversionIDSettings`:
```js
const showAdsConversionIDSettings =
		canUseSnippet &&
		( ( isUAConnected && useSnippet ) || useGA4Snippet );
```
  * Keep only this part https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/components/settings/OptionalSettingsView.js#L83-L86
* In `assets/js/modules/analytics/components/settings/SettingsEdit.js`
  * Remove `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );` 
  * Remove https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/components/settings/SettingsEdit.js#L80-L82
* In `assets/js/modules/analytics/components/settings/SettingsForm.js`
  * Remove `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );`
  * For `showTrackingExclusion` leave: `const showTrackingExclusion =  isGA4Connected || isUAConnected` 
  * Remove https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/components/settings/SettingsForm.js#L107-L117
  * Remove https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/components/settings/SettingsForm.js#L140-L142
  * Remove https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/components/settings/SettingsForm.js#L162
  * Remove `ga4ReportingEnabled` from conditionally rendered components
*  In `assets/js/modules/analytics/components/settings/SettingsUACutoffWarning.js`
  *  Remove `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );`
  *  For `shouldDisplayWarning` leave only as `const shouldDisplayWarning = isAnalyticsConnected && ! isGA4Connected;`
* In `assets/js/modules/analytics/components/settings/SettingsView.js`
  *  Remove `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );
  *  Remove https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/components/settings/SettingsView.js#L117-L122
  *  Remove `ga4ReportingEnabled` from conditionally rendered components
* In `assets/js/modules/analytics/components/settings/UASettingsView.js`
  *  Remove `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );
  *  Remove https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/components/settings/UASettingsView.js#L76-L85
  *  `propetyMeta` should only display `propetyMeta = __( 'Universal Analytics Property', 'google-site-kit' );`
* In `assets/js/modules/analytics/components/setup/SetupForm.js`
  * Remove `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );
  * Remove https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/components/setup/SetupForm.js#L102
  * Remove https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/components/setup/SetupForm.js#L120
  * Remove https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/components/setup/SetupForm.js#L157-L161
  * In https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/components/setup/SetupForm.js#L180-L184 leave only `disabled={ ! canSubmitGA4Changes }`
* In `assets/js/modules/analytics/datastore/accounts.js`
  * Remove `! isFeatureEnabled( 'ga4Reporting' )` from conditional check
  * Remove https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/datastore/accounts.js#L425-L430
* In `assets/js/modules/analytics/datastore/settings.js`
  * Remove `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );
  * Remove `! ga4ReportingEnabled` from conditional check leave only `isUAEnabled`
  * Edit the comment https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/datastore/settings.js#L136-L137, remove `If `ga4Reporting` is enabled`. Since UA is still not officially removed, just remove `ga4ReportingEnabled` from conditional check bellow. No need to update default view, until UA support is removed 
* In `assets/js/modules/analytics/datastore/setup-flow.js`
  * Remove condition https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/datastore/setup-flow.js#L59 and only return `return SETUP_FLOW_MODE_GA4;`
  * Remove remaining part of unused code from that function - https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/datastore/setup-flow.js#L63-L97
* In `assets/js/modules/analytics-4/components/dashboard/ActivationBanner/SuccessBanner.js`
  * Remove `const ga4ReportingEnabled = useFeature( 'ga4Reporting' );`
  * Define `description` to hold proper ga4 enabled text:
```js
const description = __(
	'Google Analytics 4 has started collecting data for your site. As soon there is enough data, you’ll be able to switch your Site Kit dashboard to show data from Google Analytics 4.',
	'google-site-kit'
);
```
* In `includes/Core/Modules/Modules.php`
  * Remove  `Feature_Flags::enabled( 'ga4Reporting' )`
* In `includes/Modules/Analytics_4.php`
  * Remove conditional check `if ( Feature_Flags::enabled( 'ga4Reporting' ) )`
  * Remove https://github.com/google/site-kit-wp/blob/develop/includes/Modules/Analytics_4.php#L288-L290 leave the `$analytics_settings` and `$shareable` definitions without conditional check
  * Remove `Feature_Flags::enabled( 'ga4Reporting' )` from 2 remaining conditional checks
* In `includes/Modules/Analytics.php`
  * Remove https://github.com/google/site-kit-wp/blob/develop/includes/Modules/Analytics.php#L361-L372 
  * Remove `Feature_Flags::enabled( 'ga4Reporting' )` from conditional checks
* Remove `ga4Reporting` from `feature-flags.json`

### Test Coverage

* Update stories, remove `ga4Reporting` from features array
  * `assets/js/components/DashboardViewIndicator.stories.js`
  * `assets/js/components/adminbar/AdminBarWidgets.stories.js`
  * `assets/js/components/notifications/SwitchedToGA4Banner.stories.js`
  * `assets/js/components/notifications/SwitchGA4DashboardViewNotification.stories.js`
  * `assets/js/components/wp-dashboard/WPDashboardWidgets.stories.js`
  * `assets/js/modules/analytics/components/common/UACutoffWarning.stories.js`
  * `assets/js/modules/analytics/components/settings/SettingsForm.stories.js`
  * `assets/js/modules/analytics/components/settings/SettingsUACutoffWarning.stories.js`
  * `assets/js/modules/analytics/components/settings/SettingsView.stories.js`
  * `assets/js/modules/analytics/components/setup/SetupFormGA4.stories.js`
  * `assets/js/modules/analytics-4/components/dashboard/ActivationBanner/SuccessBanner.stories.js`
  * `stories/module-analytics-setup.stories.js`
* Update js tests removing usage of `ga4Reporting` feature from `features` array, or `enabledFeatures.add( 'ga4Reporting' );`
  * `assets/js/components/adminbar/AdminBarWidgets.test.js`
  * `assets/js/googlesitekit/modules/datastore/modules.test.js`
  * `assets/js/modules/analytics/components/common/ProfileSelect.test.js`
  * `assets/js/modules/analytics/components/common/PropertySelect.test.js`
  * `assets/js/modules/analytics/components/common/UACutoffWarning.test.js`
  * `assets/js/modules/analytics/components/common/AccountCreate/index.test.js`
  * `assets/js/modules/analytics/components/settings/SettingsUACutoffWarning.test.js`
  * `assets/js/modules/analytics/components/setup/SetupForm.test.js`
  * `assets/js/modules/analytics/datastore/settings.test.js`
  * `assets/js/modules/analytics/datastore/setup-flow.test.js`
* Update php tests, using `ga4Reporting` feature flag, remove `$this->enable_feature( 'ga4Reporting' );`
  * `tests/phpunit/integration/Core/Modules/ModulesTest.php`
  * `tests/phpunit/integration/Core/Modules/REST_Modules_ControllerTest.php`
  * `tests/phpunit/integration/Modules/Analytics_4Test.php`
  * `tests/phpunit/integration/Modules/AnalyticsTest.php`
* Update any failing tests/VRT images

## QA Brief

* GA4 reporting features should be unconditionally available now
* Additionally we want to make extra sure there are no regressions as this is a large change

## Changelog entry

* N/A

**Comment by tofumatt** [comment] 2023-09-11 10:21
The IB here looks good, but a heads up for the person working on it (and @zutigrm, the IB writer): a lot of the time a feature flag removal will cause E2E tests to need refactoring, as we tend to write E2E tests without feature flags enabled.

In this case I suspect that will be true, because we probably have some E2E tests that provide Analytics reports after module setup.

I've increased the estimate for that reason.

IB ✅

**Comment by aaemnnosttv** [comment] 2023-11-06 23:06
@techanvil would you please give this a look over? I've been involved in many of the most recent changes so I'd like to get a second set of eyes on it but it would be great if we could merge this sooner than later to make sure we have time to catch any potential regressions.

Note: the one user input E2E test has been disabled for now due to odd timeout failures that don't appear to actually be broken in the plugin. This is intentional but intended to be temporary.

It should be pretty straightforward to review, but there have been a few merge conflicts that have needed resolving along the way so just erring on the side of caution here.

Thanks!

**Comment by techanvil** [comment] 2023-11-07 10:10
Sure thing @aaemnnosttv, taking a look now.

**Comment by techanvil** [comment] 2023-11-08 16:21
Just noting here that @zutigrm has created the followup issues https://github.com/google/site-kit-wp/issues/7842 and https://github.com/google/site-kit-wp/issues/7842 to further remove unused code following the merge of this issue's PR.

**Comment by wpdarren** [comment] 2023-11-09 12:38
### QA Update: ⚠️ 

@zutigrm I noticed that nothing happens when Tag Manager is connected and I go into Analytics settings to edit. I just see the loading animation. I couldn't recreate this behaviour on the latest release, so it seems to be a regression. I am unsure if the issue arises from this ticket or elsewhere.  Any chance you could confirm this? 

![image](https://github.com/google/site-kit-wp/assets/73545194/2f4556b8-e487-496f-be4e-1260da32670c)

Also, I noticed in the Site Health that we still have UA Analytics entries appearing.  This is possibly out of scope, and I can recreate a ticket. What do you think? 

![image](https://github.com/google/site-kit-wp/assets/73545194/7c9e1071-e391-486d-bbbb-56071a923349)

**Verified:**

- Set up Site Kit and Analytics on a new site and account. 
- Checked a main and entity dashboard in gathering and zero data states. 
- Set up dashboard sharing for 2nd admin and editor role to ensure this still functions. 
- Set up Site Kit and Analytics on a site with live data. 

Testing still ongoing.

**Comment by zutigrm** [comment] 2023-11-09 12:54
@wpdarren Thanks for discovering that. I will debug it to see what's going on there.

> Also, I noticed in the Site Health that we still have UA Analytics entries appearing. This is possibly out of scope, and I can recreate a ticket. What do you think?

Yes please. Removal of UA usage was not part of the ticket, we will have several follow-up issues to remove other parts of unused code

**Comment by techanvil** [comment] 2023-11-10 10:53
Back with you for another pass, @wpdarren.

**Comment by wpdarren** [comment] 2023-11-13 00:02
### QA Update: ✅ 

**Verified:**

- Set up Site Kit and Analytics on a new site and account. 
- Checked a main and entity dashboard in gathering and zero data states. 
- Set up dashboard sharing for 2nd admin and editor role to ensure this still functions. 
- Set up Site Kit and Analytics on a site with live data. 
- Checked main and entity dashboard to ensure data was displayed. 
- The Tag Manager issue reported above, where I cannot edit Analytics settings, is fixed.
- I connected all over other modules and made sure I was able to edit Analytics and the module settings

The QA team will continue to monitor this change as we test other tickets and release testing.

**Closed** 2023-11-16 21:23 UTC
Labels: P1, Type: Infrastructure
