### ISSUE TITLE
Cannot read properties of undefined (reading ‘analyticsMainURL’)

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4768] opened 2022-02-02 06:18 UTC
## Bug Description

One user in the support forums reported the below error. With no follow up from the impacted user we don't have any additional insights. 

```
Cannot read properties of undefined (reading 'analyticsMainURL')

    in DashboardTopEarningPagesWidget
    in WhenAnalyticsActive(DashboardTopEarningPagesWidget)
    in WhenAdsenseActive(WhenAnalyticsActive(DashboardTopEarningPagesWidget))
    in WidgetRenderer
    in div
    in Cell
    in WidgetCellWrapper
    in div
    in Row
    in div
    in div
    in ForwardRef
    in WidgetAreaRenderer
    in div
    in WidgetContextRenderer
    in DashboardApp
    in DashboardEntryPoint
    in RestoreSnapshots
    in ErrorHandler
    in Root
```

From inspecting the users site it looks like they have WP Globus, CyberPress, Upvote plugin, WP Foro and Yoast active. 

This is the only occurrence of this error reported in the support forums. 

## Additional Context

 - Plugin version at time of report: 1.48.1
 - [Support topic](https://wordpress.org/support/topic/cannot-read-properties-of-undefined-reading-analyticsmainurl/)
 - No Site Health info or any other insights provided
 - The plugin does remain active with the AdSense snippet output

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment] 2022-02-02 22:46
@aaemnnosttv @tofumatt @eugene-manuilov Kind of similar question to https://github.com/google/site-kit-wp/issues/4767#issuecomment-1028427399 here. I wonder if the same problem is causing both of these errors.

Could it be for example that the widget is somehow rendered although Analytics isn't active or connected?

**Comment by aaemnnosttv** [comment] 2022-02-03 09:10
@felixarntz this is likely a similar issue (if not the same root cause) as the other, where again the error is due to `useSelect` returning `undefined` which cannot be destructured.
https://github.com/google/site-kit-wp/blob/680b90fee1de464b075391b724c9ea425cd282e4/assets/js/modules/adsense/components/dashboard/DashboardTopEarningPagesWidget.js#L59-L67

**Comment by felixarntz** [comment] 2022-02-03 15:07
@aaemnnosttv So I guess we could at least prevent that JS error by splitting into separate `useSelect` calls? It probably wouldn't fix the problem the user has encountered, but it would make the error "more clear", and indeed it would at least fix part of the problem on our end.

**Comment by aaemnnosttv** [comment] 2022-02-03 17:44
@felixarntz yes. The `useSelect` would return `undefined` which is something we should handle just fine in most cases, and then on a subsequent render the error should be rethrown with more details about the source of the error (if I understand the way `useSelect` correctly).

**Comment by felixarntz** [comment] 2022-02-03 18:24
@jamesozzie Since we're fairly certain this is due to the same problem as #4767, I'm going to close this as a duplicate. Let's follow along #4767.

**Closed by felixarntz** 2022-02-03 18:24 UTC
Labels: Type: Bug, Type: Support, Module: Analytics, Module: AdSense
