### ISSUE TITLE
Implement additional googlesitekit-user store selectors

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1176] opened 2020-02-26 00:51 UTC
## Feature Description

Following #1175, the `core/user` store should include further selectors for data that is passed to JS via PHP. These changes should be added to the `googlesitekit-user` script. This will be very similar to the work executed in #1000.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `core/user` store should have the following additional selectors (for data passed from PHP):
    * `getUser()`
    * `isVerified()`
* all these selectors should be sourced with data that is available on pageload via PHP; in other words, the script should receive a `before_print` callback in PHP that adds the data to some specific JS global (`_googlesitekitUserData`), solely for consumption by that script
    * `user` object with `id`, `name`, `email`, `picture` (see https://github.com/google/site-kit-wp/blob/1.3.1/includes/Core/Assets/Assets.php#L575-L580)
    * `verified` boolean
    * this data should run through a new `googlesitekit_user_data` filter
    * the filter should then be leveraged by the `Authentication` class to modify the data like in https://github.com/google/site-kit-wp/blob/1.3.1/includes/Core/Authentication/Authentication.php#L526-L530 and https://github.com/google/site-kit-wp/blob/1.3.1/includes/Core/Authentication/Authentication.php#L573-L577
    * none of the existing code around similar filters should be modified or removed (although duplicate code), as it will be faded out in the future once we migrate everything

## Implementation Brief

* Add a `data_callback` callback in `Assets.php` for `googlesitekit-datastore-user`, similar to the one here: https://github.com/google/site-kit-wp/pull/1276/files#diff-f878941036c14d763ba1cda6ed924dcdR365, for the extra data needed by `getUser()`.
* Add a `googlesitekit_user_data` filter in PHP that returns https://github.com/google/site-kit-wp/blob/1.3.1/includes/Core/Assets/Assets.php#L575 by default. Update https://github.com/google/site-kit-wp/blob/1.3.1/includes/Core/Authentication/Authentication.php#L526-L530 and https://github.com/google/site-kit-wp/blob/1.3.1/includes/Core/Authentication/Authentication.php#L573-L577 to use `add_filter('googlesitekit_user_data', function ($data) { return $new_data } )` to add data to the filtered data rather than getting and extending the object directly.
* Expose a `getUser()` selector that uses a resolver to get data from a global created with the `data_callback` callback in the `Assets.php` code (it should use the data from https://github.com/google/site-kit-wp/blob/1.3.1/includes/Core/Assets/Assets.php#L575 but with the `googlesitekit_user_data` filter mentioned above). This selector should be marked as private but can be built upon by other selectors that need this data (eg: `getPicture()`, `getEmail()`, etc.)
* We should add those additional selectors to this PR as well: `getID`, `getName`, `getEmail`, `getPicture` to keep the public selectors very specific. I'd imagine these selectors would see common usage through the plugin and by third-parties
* Expose a `isVerified()` selector that returns a boolean based on site verification
* Add appropriate Jest tests.

## QA Brief

* 

## Changelog entry

* Add user profile information and verification state to `core/user` datastore.

**Comment by felixarntz** [comment] 2020-04-01 17:05
@tofumatt This shouldn't use a `before_print` callback, but instead a `Script_Data` instance (named e.g. `googlesitekit-user-data`) with a `data_callback`, that the `googlesitekit-datastore-user` would then depend on. See https://github.com/google/site-kit-wp/pull/1276/files#diff-f878941036c14d763ba1cda6ed924dcdR365 for a similar example.

**Comment by tofumatt** [comment] 2020-04-01 17:05
Ah, right on. I'll update the IB 👍

**Comment by tofumatt** [comment] 2020-04-01 17:09
IB updated; added a few extra selectors as well, because I think we should expose very specific selectors for this data and keep `getUser` private.

**Comment by felixarntz** [comment] 2020-04-01 17:23
@tofumatt Sounds good regarding the specific selectors!

The one thing missing from the IB is using the new `googlesitekit_user_data` filter in the `Authentication` class (see ACs, which are almost like an IB for that anyway)

**Comment by tofumatt** [comment] 2020-04-01 17:33
Ah, whoops, right. I made a note of that now, saying we should replace the existing approach in the places you mentioned with an `add_filter` call. 👍

**Comment by felixarntz** [comment] 2020-04-01 18:30
@tofumatt IB ✅ 

Let's not do the `$new_data` part though, that doesn't make any difference in PHP, since these are associative arrays. Let's modify the `$data` directly, that's simpler here.

**Comment by ShahAaron** [comment] 2020-05-15 09:30
Installed develop and built
Ran php and js unit tests - passed
Ran e2e tests - passed
Ran Visual Regression tests - passed

QA :warning:

**Comment by aaemnnosttv** [comment] 2020-05-18 08:44
Thanks for pointing that out @ShahAaron. I've merged your PR to correct that, so this is ready for another pass in QA 👍

**Comment by ShahAaron** [comment] 2020-05-18 12:25
Installed develop and built
All tests run and passed

A/C
- New selectors added -getUser() & isVerified()
- Selectors sourced by callback function `get_inline_user_data()` 
- User object contains id, name, email & picture
- New `googlesitekit_user_data` filter added to process user data. Added to Authentication class
- Additional selectors added getID, getName, getEmail, getPicture
- isVerified() exposed returning a boolean

QA ✅

**Closed** 2020-06-01 04:15 UTC
Labels: P0, QA: Eng, Type: Enhancement
