### ISSUE TITLE
AdSense dashboard error: e.replace is not a function

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1092] opened 2020-02-03 17:54 UTC
Users are encountering an e.replace is not a function error on their AdSense Site Kit dashboard. 
**e.replace is not a function**

Reports only since the latest version of the plugin was released, users either updated or activated for first time. Occurs with AdSense module active only. More info below:

The following WordPress support threads all relate to this issue:
- https://wordpress.org/support/topic/e-replace-is-not-a-function/
- https://wordpress.org/support/topic/issue-afet-the-last-update-e-replace-is-not-a-function/
- https://wordpress.org/support/topic/bug-report-on-adsense-activation/
- https://github.com/google/site-kit-wp/issues/878
- https://wordpress.org/support/topic/site-kite-error-when-i-click-adsense-e-replace-is-not-a-function/#post-12383289
- [https://wordpress.org/support/topic/site-kit-encountered-an-error/](https://wordpress.org/support/topic/site-kit-encountered-an-error/)
- [https://wordpress.org/support/topic/site-kit-encountered-an-error-e-replace-is-not-a-function](https://wordpress.org/support/topic/site-kit-encountered-an-error-e-replace-is-not-a-function/#post-12547701)

Possibly related to #1054 or #1066

## Screenshots

![Screen Shot 2020-01-30 at 6 18 09 PM](https://user-images.githubusercontent.com/41326532/73672877-99141600-46a5-11ea-82b6-ab48f3e7f6d8.png)

Console Errors:
![consoleErrors](https://user-images.githubusercontent.com/41326532/73672656-34f15200-46a5-11ea-82e7-dbf235268bc2.png)

## Additional Context

- Occurs since plugin update 1.2.0
- Doesn't affect AdSense snippet (when already placed)
- Primary SK dashboard works fine when AdSense module is disconnected
- No identified plugins or hosting environments (waiting for more info from some users)
- Clearing cache, purging CDN and incognito doesn't resolve
- One [Site Health info](https://wordpress.org/support/topic/site-kite-error-when-i-click-adsense-e-replace-is-not-a-function/#post-12383289) provided

<details>
<summary>Response Data</summary>

```json
{
  "code": 400,
  "message": "Restricted metric(s): ga:adsenseRevenue, ga:adsensePageImpressions, ga:adsenseECPM can only be queried under certain conditions.\nFor details see https://developers.google.com/analytics/devguides/reporting/core/dimsmets.",
  "data": {
    "status": 500,
    "reason": "badRequest"
  }
}
```

```json
{
  "modules::adsense::earnings::e6a23163cd3fc119c2c2dd7336409c78": {
    "averages": [
      "21.65",
      null,
      "53896"
    ],
    "endDate": "2020-02-02",
    "kind": "adsense#report",
    "rows": [
      [
        "21.65",
        "1.42",
        "53896"
      ]
    ],
    "startDate": "2020-02-02",
    "totalMatchedRows": "1",
    "totals": [
      "21.65",
      "1.42",
      "53896"
    ],
    "warnings": [
      "Some of the requested ad clients do not support the requested combination of dimensions.",
      "Some of the requested ad clients do not support the requested combination of dimensions.",
      "Some of the requested ad clients do not support the requested combination of dimensions."
    ],
    "headers": [
      {
        "currency": "USD",
        "name": "EARNINGS",
        "type": "METRIC_CURRENCY"
      },
      {
        "currency": "USD",
        "name": "PAGE_VIEWS_RPM",
        "type": "METRIC_CURRENCY"
      },
      {
        "currency": null,
        "name": "IMPRESSIONS",
        "type": "METRIC_TALLY"
      }
    ]
  },
  "modules::adsense::earnings::a7be42621010ad758d66a22d67416f78": {
    "averages": [
      "34.56",
      null,
      "60236"
    ],
    "endDate": "2020-01-27",
    "kind": "adsense#report",
    "rows": [
      [
        "34.56",
        "1.49",
        "60236"
      ]
    ],
    "startDate": "2020-01-27",
    "totalMatchedRows": "1",
    "totals": [
      "34.56",
      "1.49",
      "60236"
    ],
    "warnings": [
      "Some of the requested ad clients do not support the requested combination of dimensions.",
      "Some of the requested ad clients do not support the requested combination of dimensions.",
      "Some of the requested ad clients do not support the requested combination of dimensions."
    ],
    "headers": [
      {
        "currency": "USD",
        "name": "EARNINGS",
        "type": "METRIC_CURRENCY"
      },
      {
        "currency": "USD",
        "name": "PAGE_VIEWS_RPM",
        "type": "METRIC_CURRENCY"
      },
      {
        "currency": null,
        "name": "IMPRESSIONS",
        "type": "METRIC_TALLY"
      }
    ]
  },
  "modules::adsense::earnings::bc151ea9244a09b4178d2d1936dc272b": {
    "averages": [
      "304.49",
      null,
      "659383"
    ],
    "endDate": "2020-02-02",
    "kind": "adsense#report",
    "rows": [
      [
        "304.49",
        "1.36",
        "659383"
      ]
    ],
    "startDate": "2020-01-27",
    "totalMatchedRows": "1",
    "totals": [
      "304.49",
      "1.36",
      "659383"
    ],
    "warnings": [
      "Some of the requested ad clients do not support the requested combination of dimensions.",
      "Some of the requested ad clients do not support the requested combination of dimensions.",
      "Some of the requested ad clients do not support the requested combination of dimensions."
    ],
    "headers": [
      {
        "currency": "USD",
        "name": "EARNINGS",
        "type": "METRIC_CURRENCY"
      },
      {
        "currency": "USD",
        "name": "PAGE_VIEWS_RPM",
        "type": "METRIC_CURRENCY"
      },
      {
        "currency": null,
        "name": "IMPRESSIONS",
        "type": "METRIC_TALLY"
      }
    ]
  },
  "modules::adsense::earnings::adba27fd336f62b657a1f1b81975c523": {
    "averages": [
      "815.91",
      null,
      "1339364"
    ],
    "endDate": "2020-01-26",
    "kind": "adsense#report",
    "rows": [
      [
        "815.91",
        "1.63",
        "1339364"
      ]
    ],
    "startDate": "2020-01-20",
    "totalMatchedRows": "1",
    "totals": [
      "815.91",
      "1.63",
      "1339364"
    ],
    "warnings": [
      "Some of the requested ad clients do not support the requested combination of dimensions.",
      "Some of the requested ad clients do not support the requested combination of dimensions.",
      "Some of the requested ad clients do not support the requested combination of dimensions."
    ],
    "headers": [
      {
        "currency": "USD",
        "name": "EARNINGS",
        "type": "METRIC_CURRENCY"
      },
      {
        "currency": "USD",
        "name": "PAGE_VIEWS_RPM",
        "type": "METRIC_CURRENCY"
      },
      {
        "currency": null,
        "name": "IMPRESSIONS",
        "type": "METRIC_TALLY"
      }
    ]
  },
  "modules::adsense::earnings::8dda3739b67f9a5b10dc618ace6aea29": {
    "averages": [
      "67.03",
      null,
      "154774"
    ],
    "endDate": "2020-02-03",
    "kind": "adsense#report",
    "rows": [
      [
        "67.03",
        "1.53",
        "154774"
      ]
    ],
    "startDate": "2020-02-01",
    "totalMatchedRows": "1",
    "totals": [
      "67.03",
      "1.53",
      "154774"
    ],
    "warnings": [
      "Some of the requested ad clients do not support the requested combination of dimensions.",
      "Some of the requested ad clients do not support the requested combination of dimensions.",
      "Some of the requested ad clients do not support the requested combination of dimensions."
    ],
    "headers": [
      {
        "currency": "USD",
        "name": "EARNINGS",
        "type": "METRIC_CURRENCY"
      },
      {
        "currency": "USD",
        "name": "PAGE_VIEWS_RPM",
        "type": "METRIC_CURRENCY"
      },
      {
        "currency": null,
        "name": "IMPRESSIONS",
        "type": "METRIC_TALLY"
      }
    ]
  },
  "modules::adsense::earnings::f56fc5b6762d70191c3423c0c34018dd": {
    "averages": [
      null,
      null,
      null
    ],
    "endDate": "2019-02-28",
    "kind": "adsense#report",
    "rows": null,
    "startDate": "2019-02-01",
    "totalMatchedRows": "0",
    "totals": [
      null,
      null,
      null
    ],
    "warnings": [
      "Some of the requested ad clients do not support the requested combination of dimensions.",
      "Some of the requested ad clients do not support the requested combination of dimensions.",
      "Some of the requested ad clients do not support the requested combination of dimensions."
    ],
    "headers": [
      {
        "currency": "USD",
        "name": "EARNINGS",
        "type": "METRIC_CURRENCY"
      },
      {
        "currency": "USD",
        "name": "PAGE_VIEWS_RPM",
        "type": "METRIC_CURRENCY"
      },
      {
        "currency": null,
        "name": "IMPRESSIONS",
        "type": "METRIC_TALLY"
      }
    ]
  },
  "modules::adsense::earnings::4d624fc436160bc59afb173d2ea99e06": {
    "averages": [
      "1870.65",
      null,
      "1633670"
    ],
    "endDate": "2020-01-05",
    "kind": "adsense#report",
    "rows": [
      [
        "1870.65",
        "2.70",
        "1633670"
      ]
    ],
    "startDate": "2019-12-09",
    "totalMatchedRows": "1",
    "totals": [
      "1870.65",
      "2.70",
      "1633670"
    ],
    "warnings": [
      "Some of the requested ad clients do not support the requested combination of dimensions.",
      "Some of the requested ad clients do not support the requested combination of dimensions.",
      "Some of the requested ad clients do not support the requested combination of dimensions."
    ],
    "headers": [
      {
        "currency": "USD",
        "name": "EARNINGS",
        "type": "METRIC_CURRENCY"
      },
      {
        "currency": "USD",
        "name": "PAGE_VIEWS_RPM",
        "type": "METRIC_CURRENCY"
      },
      {
        "currency": null,
        "name": "IMPRESSIONS",
        "type": "METRIC_TALLY"
      }
    ]
  }
}
```

</details>

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The AdSense report dashboard should display properly for all users. 

## Implementation Brief

* Simplify the `readableLargeNumber` utility using `numberFormat`
* Ensure various input types do not raise errors
* Merge #1261

## Changelog entry

* Fix JavaScript error `e.replace is not a function` in AdSense screens related to formatting numbers.

**Comment by jamesozzie** [comment] 2020-03-02 14:20
With latest version of plugin (1.4.0) one user(#878) reported a different error.

```
Site Kit encountered an error
e.replace is not a function


    in AdSenseDashboardMainSummary
    in NewComponent
    in DashboardEarnings
    in FilteredComponent
    in WithFilters(DashboardModule)
    in DashboardModules
    in DashboardMain
    in div
    in div
    in div
    in div
    in ErrorHandler
    in DashboardApp
    in ErrorHandler
    in GoogleSitekitDashboard
```

**Comment by cole10up** [comment] 2020-03-10 15:46
**Tested**

Installed 1.2.0 and added Adsense, confirmed functionality of the dashboard.

Updated to 1.4.0 and verified Adsense is still functional.

![Site Kit by Google AdSense ‹ Hellogoodbye — WordPress](https://user-images.githubusercontent.com/57115907/76330703-69ab8700-62ab-11ea-99cc-12bb46d14608.gif)

Moving to L2 for more investigation

**Comment by aaemnnosttv** [comment] 2020-03-12 17:01
Thanks to the trace provided by @jamesozzie I believe I was able to replicate this. It required a bit of forcing a particular code path but the error and trace it produced matches.

![image](https://user-images.githubusercontent.com/1621608/76545268-252e1000-6492-11ea-9b9a-6bb5fb51aac5.png)

The problem is that if `number` isn't a string (such as a `Number`), the `replace` method won't exist.

https://github.com/google/site-kit-wp/blob/1a91ac94ddb83e00fb7dfd7493a88b849aadd960/assets/js/util/index.js#L156

**Comment by AkiraDegawa** [comment] 2020-03-17 08:11
Hello. i am using wordpress plan, when install sitekit this happen, as myself not programmer i don't know what to do to fix this, please help me.
![image](https://user-images.githubusercontent.com/19325623/76835340-7870db80-6861-11ea-864f-41732884ea1a.png)

**Comment by aaemnnosttv** [comment] 2020-03-17 11:31
Hi @AkiraDegawa, this is a known issue and we're working on a fix for it. Unfortunately there likely isn't anything you can do at the moment. This should be fixed in an upcoming release, but I can't tell you exactly when that will be yet. Stay tuned here for updates.

**Comment by shanneygastelum** [comment] 2020-03-20 18:05
Hi. I have the same problem, I get the same error code in Google Site Kit. I have uninstalled, removed and reinstalled, but the same error continues.

Also, this is affecting my visit count on my site that tracks analytics and Adsense earnings. Since only less than a quarter of what is normally registered in AdSense is registered with the same traffic in terms of earnings.

The url of my page is www.estoessinaloa.com

This error started from the beginning of last week with unusually low numbers when I was not yet updating. When doing the update the numbers of adsense and analitycs fell by the floors, as I exposed above.

Could you help me?

**Comment by ernee** [comment] 2020-03-20 19:25
@shanneygastelum  thanks for the details. I have [replied to you](https://wordpress.org/support/topic/adsense-site-kit-encountered-an-error-e-replace-is-not-a-function/#post-12566295) in the support forums, but also encourage you to open [a new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) so we can track your specific case. Thank you!

**Comment by bviktor** [comment] 2020-03-22 12:36
Thank God, I thought it's only me...

**Comment by shanneygastelum** [comment] 2020-03-23 02:45
I thought I was the only one! Could you please confirm if you are also logging visits in analitycs and adsense incorrectly?

In my case, what affects me the most is that, although the ads are displayed normally and for everyone on the page, in my account I am not registering almost any benefit, I have been like this for three weeks, I am worried about losing money.

So far I get no answer or solution by any means, I have tried to uninstall and reinstall it, even manually install it with an older version and use alternative plugins to Google Site Kite, but nothing has solved the problem for me.

**Comment by bviktor** [comment] 2020-03-23 11:32
Sorry @shanneygastelum I meant the `e.replace is not a function` error. I can't tell much about earnings and stuff, I don't really monitor that part, I just want the SiteKit plugin to work lol.

**Comment by cole10up** [comment] 2020-03-25 16:17
**Ran a series of tests with @ivankristianto**

On our end we were able to identify that the issues persisted with international currency. Conscious of the timing around this fix, we ensured the plugin wasn't breaking current functionality.

![Screen Shot 2020-03-25 at 23 12 29](https://user-images.githubusercontent.com/57115907/77559449-728a8400-6e79-11ea-8430-777e9b2b55ff.png)

Passed QA ✅

**Closed** 2020-03-25 18:51 UTC
Labels: Group: Escalation, P0, Type: Bug

**Comment by Itechupdate** [comment] 2022-02-09 15:38
I tried above-mentioned fix to get this resolved. But its not working. My site health is good with no improvement or any suggestion. My adsense revenue is dropping drastically. Plz help.

**Comment by bethanylang** [comment] 2022-02-09 15:46
@Itechupdate All support for the Site Kit plugin is provided on our [WordPress.org support forum](https://wordpress.org/support/plugin/google-site-kit/). If you [create a new topic](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0) there, we'd be happy to take a look and help you troubleshoot. Thanks!
