### ISSUE TITLE
Connect modules briefly shows another module connected.

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#2796] opened 2021-02-11 20:54 UTC
## Bug Description

When I click connect service, it always shows the right mode service as connected before redirecting to Google for auth. 

## Steps to reproduce

1. Go to /wp-admin/admin.php?page=googlesitekit-dashboard&notification=authentication_success
2. Search Console = "Connected", AdSense, Analytics and PageSpeed Insights = "Connect Service"
3. Click on any Connect Service
4. Prior to redirect for auth, PageSpeed Insights shows as Connected.

## Screenshots

<img width="808" alt="Screen Shot 2021-02-11 at 12 47 45 PM" src="https://user-images.githubusercontent.com/373931/107697309-eab39100-6c67-11eb-9433-3a5635978304.png">

Added a video repro, intentionally not showing the Google Auth part:

https://user-images.githubusercontent.com/373931/107697424-0dde4080-6c68-11eb-98c0-a1b3e30794d7.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When activating a module from the "Congrats" notification (which shows up after connecting Site Kit or a module), every module should remain in its current UI state all the way until the user is redirected to OAuth (i.e. it should not visually change to looking as connected before then).

## Implementation Brief

* Comment out the automatic fetching of `getModules` when toggling module activation https://github.com/google/site-kit-wp/blob/47b723d1416fa48b4e9df73b2970e868e1ccece8/assets/js/googlesitekit/modules/datastore/modules.js#L219-L222
	- This will leave the module in the same state within the App until the page is refreshed, which is often needed anyways for the change to take effect to being setup, etc
	- Add a `TODO` comment to clarify that this should be restored later when Site Kit no longer relies on page reloads between module activation changes
* Remove localized workarounds added to fix this in module settings
	- https://github.com/google/site-kit-wp/blob/47b723d1416fa48b4e9df73b2970e868e1ccece8/assets/js/components/settings/SettingsActiveModules.js#L34-L36
	- https://github.com/google/site-kit-wp/blob/47b723d1416fa48b4e9df73b2970e868e1ccece8/assets/js/components/settings/SettingsInactiveModules.js#L38-L40
* Finish and merge https://github.com/google/site-kit-wp/pull/4141
    * Mostly just updates to tests left

### Test Coverage

* Update tests for module activation to not refetch all modules (and thus update state)
* Add tests if not covered by the last point to ensure activating or deactivating a module does not immediately change its active/connected state

## QA Brief

* Activate or deactivate a module in the settings and make sure that the list of modules doesn't change until the page is refreshed or after navigating back to the settings page.
* Activate a module from the congrats notification banner and verify that modules do not change their statuses until the page is refreshed.

## Changelog entry

* Fix a bug that could cause the wrong module to show that it's being connected during module setup.

**Comment by abdullah1908** [comment] 2021-02-15 12:13
@ivankruchkoff I am unable to reproduce this issue at my end. Would you mind to share more information so we can try to setup same environment & can replicate at my end.
cc: @jamesozzie

**Comment by bethanylang** [comment] 2021-03-09 16:39
@ivankruchkoff Just checking in here – are you able to share some more details so that @abdullah1908 can try to run some more tests? Thanks!

**Comment by bethanylang** [comment] 2021-03-22 14:44
@felixarntz Reassigning to you for triage. As Darren noted, this looks like a pretty isolated edge case, so probably not a priority.

**Comment by ivankruchkoff** [comment] 2021-05-19 05:31
So the easier way to resolve this particular issue is a cache invalidation param in the selector causing it to fire again in:
https://github.com/google/site-kit-wp/blob/d8e741b/assets/js/components/ModulesList.js#L51

```js
const cacheBust = +new Date;
const modulesData = useSelect( ( select ) => select( CORE_MODULES ).getModules( cacheBust ) );
```

The better solution here is to think of modules as having three states rather than two, currently we have a `boolean active` in `assets/js/googlesitekit/modules/datastore/modules.js`
https://github.com/google/site-kit-wp/blob/d8e741b1e75d3fbe7b44abe10b31408bdd5f3e02/assets/js/googlesitekit/modules/datastore/modules.js#L211

What we really need is `active`, `inactive`, and `pending activation` when activation is in progress, otherwise we go from inactive to active, before we've finished activation and we get unintended UI updates such as the following:

https://user-images.githubusercontent.com/373931/118760852-576e9680-b828-11eb-97c6-b2c04baa1261.mp4

After the UI update in the video, we are redirected to Google for auth to get permissions to activate `Analytics`, so any component that depends on whether or not the analytics module is active would behave the same.

What are your thoughts @felixarntz and @aaemnnosttv?

**Comment by aaemnnosttv** [comment] 2021-05-19 07:48
@ivankruchkoff the state change you highlighted in your last comment is a known issue, but isn't this different than the issue you originally reported above?

> What we really need is `active`, `inactive`, and `pending activation` when activation is in progress, otherwise we go from inactive to active, before we've finished activation and we get unintended UI updates such as the following:

I think this is probably the way to go, but the 3rd state should probably be a more generic "transitional" state since the same is possible when deactivating as well. The tricky thing is in settings for example, we want to show lists of all active/inactive modules that are resilient to activation changes. In this case we might need 4 states: active, activating, inactive, and deactivating.

Again, this seems to be a separate issue (although similar) to the one in this issue's description which I'm not sure is still an issue or not.

**Comment by danielgent** [comment] 2021-05-19 08:37
Just to confirm @aaemnnosttv @ivankruchkoff that I see the original error somewhat frequently! (and I keep ruining my train of thought thinking about this ticket :joy: )

**Comment by ivankruchkoff** [comment] 2021-05-19 20:55
> Again, this seems to be a separate issue (although similar) to the one in this issue's description which I'm not sure is still an issue or not.

Yes, you're quite right.

**Comment by ivankruchkoff** [comment] 2021-05-20 17:03
Still an issue @aaemnnosttv, here's a repro screen recording. 

https://user-images.githubusercontent.com/373931/119019971-900a8f00-b952-11eb-8be2-a60bd295659d.mp4

**Comment by aaemnnosttv** [comment] 2021-05-20 17:18
Thanks a lot for the screencast @ivankruchkoff – I just tried this out myself and wasn't able to reproduce it; when I click "Back" it shows connected for me 🤷‍♂️ . With that said, if this only happens after navigating back then I would say this isn't worth spending time on, at least any time soon 😄  Thoughts @felixarntz ?

**Comment by felixarntz** [comment] 2021-05-24 14:26
If it only occurs after navigating "back", I'd agree it's not highly crucial, however I'd say it's still a valid bug - maybe a P2? There may some related improvements also worth making though, for example, maybe the PSI module shouldn't show as connected until the redirect / page reload has happened. This is similar to various other enhancements that we've made (e.g. in the `ActivateModuleCTA` component) where it shouldn't change state before a redirect.

**Comment by aaemnnosttv** [comment] 2021-05-26 08:33
> This is similar to various other enhancements that we've made (e.g. in the `ActivateModuleCTA` component) where it shouldn't change state before a redirect.

@felixarntz I think we just need to update the activation actions to not change the activated state in the state since it requires a page reload to take effect anyways. This is very similar to what we did with the `reset` action.

**Comment by felixarntz** [comment] 2021-07-30 18:10
@aaemnnosttv While that would be an alternative way to fix, I'm not sure I'm onboard with that approach - technically, the module is already active, and we may e.g. not always require a redirect, let's say in the case the user already has granted the scopes before and we had a true single page application where then the setup UI would just show up.

I think the cause for this situation feeling off is the redirect, so IMO we should check for the redirect to avoid changing the message in the component.

**Comment by aaemnnosttv** [comment] 2021-09-28 08:38
@felixarntz while I agree that this approach isn't entirely compatible with the true SPA version of Site Kit that we are aiming towards, it is the simplest change we can make to address the problem with Site Kit as it is today. As mentioned previously, we already did this with the reset action which would likely need to change as well in a no-page-refresh version of Site Kit in the future.

The benefit of this approach is that it's a centralized solution. We shouldn't require all components that touch module active/connected state to also be concerned about whether or not a module state change navigation is about to happen. The simplest change it seems is to only receive such state on page load.

**Comment by felixarntz** [comment] 2021-09-28 19:04
@aaemnnosttv For now that's okay, but it still creates an inconsistency in our datastore where it doesn't accurately reflect the current state. So we should for sure have a `TODO` annotation or some other comment there to clarify. I'd even say we should not remove the module fetching code, but only comment it out and explain why it is commented out. If it wasn't for our particular navigation struggle, having it there would be correct. Can you add that to the IB?

**Comment by aaemnnosttv** [comment] 2021-09-29 07:20
> I'd even say we should not remove the module fetching code, but only comment it out and explain why it is commented out. If it wasn't for our particular navigation struggle, having it there would be correct. Can you add that to the IB?

@felixarntz sure, that sounds good to me. In the future, we'll need to add some additional state for modules, or change how we represent the active state to be more flexible than a simple boolean. IB updated 👍

**Comment by felixarntz** [comment] 2021-09-29 17:12
IB ✅

**Comment by kuasha420** [comment] 2021-09-30 01:16
// Accidentally picked up this ticket thinking it is in the sprint without filtering by current sprint. Oops.

**Comment by wpdarren** [comment] 2021-11-02 14:44
### QA Update ✅ 

- Activated a module in the settings and the list of modules doesn't change until the page is refreshed or after navigating back to the settings page.
- Activated a module from the congrats notification banner and the modules do not change their statuses until the page is refreshed.
- Also looked back at previous comments about connecting and then going back to see if the statuses change even though the module has not been connected.

**Closed** 2021-11-18 17:10 UTC
Labels: Type: Bug, P2
