### ISSUE TITLE
Incorrect Analytics CTA layout on Site Kit admin bar in gathering state

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4988] opened 2022-03-28 15:06 UTC
## Bug Description

The Site Kit Admin Bar is not consistent with the layout of the Analytics CTA.  As you can see on the screenshot below, the layout is not the same as the figma designs and is not in a grid, i.e. the text and button should be to the left.  

![image](https://user-images.githubusercontent.com/73545194/160427227-fce2e005-7b6d-458a-9f35-7030aa6dab0e.png)

When there is data, ie. in impressions or clicks then the CTA is displayed as expected.

![image](https://user-images.githubusercontent.com/73545194/160428376-b2afe587-6721-47a2-82b1-b2bfbd25441e.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2022-04-01 16:33
@wpdarren I was unable to reproduce your first screenshot above (SC gathering data with Analytics setup CTA). I only see the full-width "There is no data available for this content yet" notice. Anything special to reproduce this?

**Comment by wpdarren** [comment] 2022-04-04 10:53
@aaemnnosttv Mmm. Yes, you are right, I am not seeing the issue now.  I've spent some time trying to recreate it, but unsuccessfully. Let's close this and if I see it again, I'll reopen it.

**Comment by aaemnnosttv** [comment] 2022-04-04 17:32
Thanks @wpdarren – closing for now 👍

**Closed by aaemnnosttv** 2022-04-04 17:32 UTC
Labels: Type: Bug, P1
