### ISSUE TITLE
JavaScript error: Cannot read property 'clearPermissionScopeError' of null

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#2349] opened 2020-11-11 02:54 UTC
## Bug Description

Reported in a [support topic](https://wordpress.org/support/topic/site-kit-encountered-an-error-clearpermissionscopeerror/
), a user encountered this error upon activation:

```
Cannot read property 'clearPermissionScopeError' of null
    in PermissionsModal
    in ErrorHandler
    in Root
```
Not reproducible as of yet/ awaiting information from user for more context. 

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

Related support topic: 
https://wordpress.org/support/topic/site-kit-encountered-an-error-clearpermissionscopeerror/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by ernee** [comment] 2020-12-09 18:31
Another report in the forums: https://wordpress.org/support/topic/error-1451/

**Comment by eugene-manuilov** [comment] 2020-12-15 17:53
It's a weird issue... I have tried to replicate it on my end and haven't been able to do it... I think we can't figure it out without further details... I wish one of those guys could provide more information...

**Comment by Jaydal** [comment] 2020-12-16 09:25
Just encountered the same error after updating the plugin.

**Comment by eugene-manuilov** [comment] 2020-12-16 09:39
@Jaydal can you tell us which version of WordPress and PHP do you have or even submit your site health information?

**Comment by jamesozzie** [comment] 2020-12-16 11:18
One users [Site Health information provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit?urlBuilderDomain=get10up.com&gxids=7628), referencing the initial support topic.

**Comment by Jaydal** [comment] 2020-12-16 11:59
> @Jaydal can you tell us which version of WordPress and PHP do you have or even submit your site health information?

I sent the site health information [here](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/viewform?gxids=7628&edit_requested=true)

**Comment by jamesozzie** [comment] 2021-01-08 13:02
Some [useful insights](https://wordpress.org/support/topic/site-kit-encountered-an-error-clearpermissionscopeerror/#post-13879115) provided by one user on the WordPress support forums. Changes were made to their Content Security Policy on their NginX server in order to proceed.

**Comment by ernee** [comment] 2021-01-08 21:40
Another [report of this issue ](https://wordpress.org/support/topic/cannot-read-property-clearpermissionscopeerror-of-null/) in the forums with some interesting details. It appears the issue was browser related in their case. The error was no longer present when switching to an incognito window in Chrome or another browser (Firefox and Edge).

**Comment by jamesozzie** [comment] 2021-01-26 09:32
Similar report from [one user](https://wordpress.org/support/topic/site-kit-encountered-an-error-20/#post-13957698) in the support forums. Awaiting response regarding additional information.

**Comment by abdullah1908** [comment] 2021-02-04 20:16
Unable to reproduce at my end as I tried by setting up Site Kit in different websites.
cc: @jamesozzie

**Comment by bethanylang** [comment] 2021-03-02 14:21
@jamesozzie Since @abdullah1908 is unable to reproduce, should this go to L2?

**Comment by jamesozzie** [comment] 2021-03-02 19:27
@bethanylang Based on similar reports and from information kindly [provided by one user](https://wordpress.org/support/topic/site-kit-encountered-an-error-21/#post-14124449) it looks like this can occur in situations whereby a site was previously setup on another domain and then possibly migrated, or the site URL may have changed. 

Awaiting additional insights from end user before further action.

**Comment by bethanylang** [comment] 2021-03-02 19:32
Great, thank you for the update @jamesozzie!

**Comment by bethanylang** [comment] 2021-03-16 13:55
@jamesozzie @abdullah1908 Looks like an uninstall/reinstall did the trick for the most recent user who experienced this issue. Worth doing one more try at replicating?

**Comment by abdullah1908** [comment] 2021-03-17 14:25
Sure @bethanylang I'll give it a try 👍

**Comment by abdullah1908** [comment] 2021-03-22 20:21
@bethanylang I couldn't replicate this by using uninstall/reinstall trick.

**Comment by bethanylang** [comment] 2021-03-22 20:48
@abdullah1908 Apologies for not being clearer - the user said that they were able to fix the issue by uninstalling and reinstalling, so it makes sense that you did not see the error after doing that. In this case, you were unable to reproduce the original issue prior to uninstall/reinstall, correct?

**Comment by abdullah1908** [comment] 2021-03-23 10:56
@bethanylang yes you are right.

**Comment by jamesozzie** [comment] 2021-03-23 14:17
I did a review of the below support topics with users who experienced these errors:

- https://wordpress.org/support/topic/site-kit-encountered-an-error-21/ - **Resolved - uninstalled / reinstalled** ([SH info provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNiMzLUUPH0TroGcQQIAnojbfD3bP9rPAa8aQ8tPMhFfvh32r_jPyVe7fJHv3-74S14)) 
- https://wordpress.org/support/topic/need-for-my-site-kit/ - **Resolved - unknown exact solution applied.** No SH info provided
- https://wordpress.org/support/topic/site-kit-encountered-an-error-20/ - **Resolved - closed with no response from user.** ([Site Heath info provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNiwbOyZ6DxvS7RJ3qY2-87U1k_yDXD46TpxJg_x2Hq1NYMxpE8VE6stfDdh0lVz1Lw))
- https://wordpress.org/support/topic/site-kit-encountered-an-error-19/ - **Resolved - Incognito browsing** (No Site Health info)
- https://wordpress.org/support/topic/cannot-read-property-clearpermissionscopeerror-of-null/ - **Resolved - Incognito browsing** (Site Health info provided within topic)
- https://wordpress.org/support/topic/error-1451/ - **Unresolved - No response from user.** (no Site heath info)
- https://wordpress.org/support/topic/site-kit-encountered-an-error-clearpermissionscopeerror/ - **Resolved - nginx configuratin**. [(Site Health info provided)](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNjvKRuTYaybpjUMHc4iC3O3uGm0ov8ummCFacSY5--BhamL1__OtVIAdLyvz-n7CYc). 

Additional insights:
- 5/7 now resolved, as confirmed by users
- Various fixes, uninstalling & reinstalling, checking incognito. 
- Unsure whether the remaining 2 experience this issue, no recent response. 
- No common traits from inspecting provided Health Information
- 3/4 Site Health information reports provided have All in One WP Migration active, suggesting Site Kit may have been setup on another domain before migration (this was also evident from another report)
- 2/4 Site Health information reports have LiteSpeed cache active, which does have configurations that can result in non reporting of data although no reports of setup being impacted
- Started occurring in SK 1.22.0, the most recent support topic was from SK 1.26.0
- Different hosting providers
- 2/4 have additional htaccess rules

@abdullah1908 @bethanylang I suspect issues have have arose between migrating a site, with the new site maybe contain invalid tokens or references to the old site. I can't be sure. Maybe it's worth escalating to see if L2 have any additional insights.

**Comment by bethanylang** [comment] 2021-03-23 14:40
Thanks so much for pulling this all together, @jamesozzie. Escalating to L2 and reassigning to @aaemnnosttv.

**Comment by aaemnnosttv** [comment] 2021-04-01 07:32
@jamesozzie @bethanylang – any time a user reports an error like this, it's always a good idea to ask for a screenshot of the browser console, if possible (assuming it's reproducible for the user). I've noticed some other threads/issues have this.

This could be possible if the user had something in place which blocked one of our JS files from being loaded (either in browser, or something on the server perhaps). This isn't something we can deduce from Site Health info or error messages alone though. A content security policy (as referenced above) could cause problems but that would likely be more for all of Site Kit rather than a particular action or screen.

For anyone able to connect using an incognito window, that seems to indicate a browser extension blocking something. This would be easier to confirm if we could see the full output in the console though.

Definitely a bit of an edge case. Not much we can really do without more information unfortunately.

**Comment by jamesozzie** [comment] 2021-04-01 08:55
Will do @aaemnnosttv. Some console errors from the above topics below. In addition once user [provided a video](https://perties.sk/perties.mp4), with the video an error appears in the Site Kit homepage widget that their account isn't able to access Google account data. 

![image](https://user-images.githubusercontent.com/41326532/113268933-d9821a80-92cf-11eb-96dc-3d2af168c679.png)

![image](https://user-images.githubusercontent.com/41326532/113268968-e3a41900-92cf-11eb-9c0d-db0c789714e8.png)

**Comment by aaemnnosttv** [comment] 2021-04-01 09:30
Thanks @jamesozzie – I saw those ones which are helpful.

The part to note here are that _other scripts_ are also broken on the page:
![image](https://user-images.githubusercontent.com/1621608/113273423-4ce25700-92e5-11eb-85c1-31d65c78645b.png)

All of our scripts start with `googlesitekit-` so those other ones belong to some other plugin `v3.0.15` (this is where the Site Health info would help identify this plugin, but that's not necessarily the cause). This leads me to believe it may be a larger issue with the server itself, or something interfering with what scripts are loaded.

For "Invalid or unexpected token" errors specifically, it would be useful to have the user click on the link on the right side of the console which indicates the file, line, and column that the error happened. These can often be html (404 page) if the file is missing for some reason, or some other error response. When the browser tries to load html as JS, it breaks right away due to invalid syntax like that.

**Comment by jamesozzie** [comment] 2021-04-01 09:51
@aaemnnosttv Thanks for the insights Evan, good to know. I'll chase up with the users who reported this with an unresolved status.

**Comment by bethanylang** [comment] 2021-04-20 16:20
@jamesozzie Just checking in here - any updates?

**Comment by jamesozzie** [comment] 2021-04-20 16:27
@bethanylang No response from the [only support topic](https://wordpress.org/support/topic/error-1451/) with an unresolved status. Closing that topic now. 

What are you thoughts on keeping this issue open should other users encounter this issue? No definitive cause, or no indicators of a Site Kit bug at present.

**Comment by bethanylang** [comment] 2021-04-20 16:31
@jamesozzie Thanks for following up!

Given that this appears to be an edge case and we don't have much info, I'm going to close. If we do see it again in the future, we can open a new issue and refer back to this one.

**Closed by bethanylang** 2021-04-20 16:31 UTC
Labels: Group: Escalation, Type: Bug, Type: Support
