### ISSUE TITLE
Site Kit encountered an error: Loading chunk 1 failed

### ISSUE THREAD

**Issue by dalepgrant** [google/site-kit-wp#1433] opened 2020-04-24 02:22 UTC
## Bug Description

Possibly related to #1391 

On plugin activation, navigating to Site Kit dashboard produces a JS error:

```
Loading chunk 1 failed. (error: https://www.domain.com/wp-content/plugins/google-site-kit/dist/assets/js/chunk-googlesitekit-adminbar~chunk-googlesitekit-setup-wizard~chunk-googlesitekit-setup-wizard-proxy-2422cbe0801b8fe596c6.js)


    in Unknown
    in Suspense
    in DashboardSplashApp
    in ErrorHandler
    in GoogleSitekitDashboardSplash
```
The "setup" admin notice also disappears. This means if you don't set up the plugin immediately, you can't access the setup again without deactivating/reactivating the plugin.

## Steps to reproduce

1. Install and activate plugin
2. Ignore the set up steps and click 'Site Kit' in the left hand admin menu.
3. See error.

OR

1. Install and activate plugin
2. Follow setup steps successfully
3. Navigate to Site Kit > Settings > Admin Settings
4. Click Reset Site Kit and confirm
5. See error (and also have to deactivate/reactivate to setup again)

## Screenshots

<img width="1772" alt="Screen Shot 2020-04-24 at 12 00 08 pm" src="https://user-images.githubusercontent.com/12812394/80167289-5d914400-8623-11ea-8706-164ea3a60ebc.png">

<img width="1497" alt="Screen Shot 2020-04-24 at 12 11 57 pm" src="https://user-images.githubusercontent.com/12812394/80168072-53704500-8625-11ea-8143-f50d75efd64e.png">

## Additional Context

 - PHP Version: 5.6.40
 - Browser: Chrome on MacOS
 - Plugin Version: 1.7.1
 - WP Version 5.1.1

Confirmed same behaviour in incognito mode. 

Confirmed same behaviour with all plugins disabled

I am able to setup Site Kit on this site, but another admin user reported they were unable to access the Site Kit dashboard with a similar error (chunk 18 this time), which led me to debugging. Will create a new issue for that one when I can replicate myself, but screenshot below

<img width="1280" alt="Schermafbeelding 2020-04-23 om 21 40 43" src="https://user-images.githubusercontent.com/12812394/80168346-f3c66980-8625-11ea-894a-9a98094f234e.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by ernee** [comment] 2020-04-24 21:24
@dalepgrant much appreciation for your report of this issue. This does sound similar to #1391 which we're investigating. We currently provide support in the plugin's [WordPress Support Forum](https://wordpress.org/support/plugin/google-site-kit/). 

Could you open topic there when you can so we can continue to troubleshoot with you as well as keep track of the issue?

**Comment by dalepgrant** [comment] 2020-04-27 03:17
Sure thing, ticket opened here: https://wordpress.org/support/topic/site-kit-encountered-an-error-loading-chunk-1-failed/

Just as some further info: I now get the same error message after another admin user has setup Site Kit with their credentials successfully. I could deactivate/reactivate the plugin, but them I'm that will disconnect the other admin.

Let me know if I can give any more info.

**Comment by ernee** [comment] 2020-04-27 15:43
Closing in favor of #1391 where the issue is being worked on.

**Closed** 2020-04-27 15:43 UTC
Labels: Type: Support

**Comment by ketanpatel25** [comment] 2020-09-19 04:25
`Loading chunk 1 failed.
(error: https://groupsjoin.com/wp-content/plugins/google-site-kit/dist/assets/js/chunk-googlesitekit-adminbar~chunk-googlesitekit-setup-wizard-proxy-f262ebd34a6cc64e6bbf.js)

    in Unknown
    in Suspense
    in DashboardSplashApp
    in GoogleSitekitDashboardSplash
    in RestoreSnapshots
    in ErrorHandler
    in Root`

**Comment by jamesozzie** [comment] 2020-09-21 16:19
@ketanpatel25 Thanks for reaching out. Initial support requests can be submitted using the plugins WordPress support forum. 

If you open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there while providing your Site Health information using [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/) we'd be happy to assist.  Note also some users who encountered this notice were able to proceed with setup or viewing their dashboards after clearing their browsers cache.
