### ISSUE TITLE
In View Only context, unavailable custom dimension tile displayed 

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7741] opened 2023-10-24 19:53 UTC
## Bug Description

From @aaemnnosttv in Bug Bash ([Asana task](https://app.asana.com/0/1205508124049666/1205788136098460/f)):

In a view only context, users can't select or even see any metric tiles that depend on unavailable custom dimensions.

This works as expected in the metric selection panel for the most part, but it is possible for the user's personal choice of metrics to "override" this limitation if it was chosen while GA was connected to a different property where the dimensions existed at the time. This results in a kind of broken experience where the tile renders in the state with a CTA to update the property as clicking the CTA does nothing.

![image](https://github.com/google/site-kit-wp/assets/12189958/fc862bda-f947-4508-9bfd-862fdef4e402)

The other weird part about this case is that the selection panel only shows 3 selected metrics, but shows 4/4 are selected at the bottom and also shows the warning about needing to update the GA property. There is no way to unselect the custom dimension dependent metric that is hidden.

![image](https://github.com/google/site-kit-wp/assets/12189958/43153fc3-c716-433f-a750-d8d8e0e57572)

From @nfmohit:

> I think a solution here could be removing any widget slugs that depend on unavailable custom dimensions from KM settings for view-only users, which does sound a bit tricky.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- For a view-only user, any key metric widget tile that depends on a custom dimension that is not available should have no presence in the dashboard, as if it did not exist (similar to if a widget's module was not shared). This includes:
	- Rendering in the KMW area
	- Rendering in the metric selection panel as well as behavior within (if previously selected somehow, it should not be included in the set of selected metrics, affect selected count, etc)
	- Any non-user-facing side-effects from either of the above

## Implementation Brief

In `assets/js/googlesitekit/datastore/user/key-metrics.js`:

#### Refactor the `getKeyMetricsSettings` selector:

* **Determine View-Only Mode**:
    * Utilize the `isAuthenticated` selector to verify if the user is authenticated.
    * Utilize the `hasCapability` selector with the `PERMISSION_MANAGE_OPTIONS` capability to determine if the user has the required permissions.
    * If the user is neither authenticated nor has the appropriate permissions, they're considered to be in a "view-only" dashboard.

* **Widget Filtering in View-Only Mode**:
    * If "view-only" is `true`, initiate a filtering process on the `widgetSlugs` array:
        * Retrieve the widget object corresponding to the current slug from the `KEY_METRICS_WIDGETS` constant.
        * If the current widget has a `displayInList` callback (noting that currently, all custom dimension widgets possess this callback):
            * Invoke the `displayInList` callback, passing in the `select` and the derived view-only boolean.
            * Return the result of this callback to determine if the widget should be included.
        * For widgets without this callback, default to returning `true` to ensure their display.
    * Post-filtering, if there's only one widget remaining, assign an empty array to `widgetSlugs`. This will ensure the default behavior in the `getKeyMetrics` selector, ensuring the display of predefined metrics. [Reference discussion](https://github.com/google/site-kit-wp/issues/7741#issuecomment-1786117144) for additional insights.
    * If not in "view-only" mode, return the `keyMetricsSettings` from the state as is.

### Test Coverage

* Ensure that any tests broken due to the above modifications are fixed
* Add test cases for the `getKeyMetricsSettings` selector to validate the refactored behavior.

## QA Brief

* Set up Site Kit and connect to a GA4 property with custom dimensions.
* Select the custom dimension dependent metric tiles in the Key Metrics widget area.
* Create a view-only user and share the GA4 module with that user.
* Log in as the view-only user and select metric tiles dependent on the custom dimensions.
* Verify that the Key Metrics widget area has all the visible metric tiles that depend on the available custom dimensions.
* Select a different GA property that does not have the custom dimensions available.
* Verify the metric tiles are displayed with the CTA to create the custom dimensions as it works today for an admin user.
* Verify that the unavailable custom dimension dependent metric tiles are available in the metric selection panel.
* Verify that the Key Metrics widget area has no visible metric tile that depends on one or more "unavailable" custom dimensions for a view-only user.
* Verify that the unavailable custom dimension dependent metric tiles are not available in the metric selection panel for a view-only user.
* In the view only dashboard, verify if only one widget remains after removing the unavailable custom dimension dependent metric tiles, the default metrics are displayed in the Key Metrics widget area.

## Changelog entry

* Prevent view-only users from seeing Key Metric widget tiles that depend on unavailable custom dimensions.

**Comment by nfmohit** [comment] 2023-10-25 06:18
For the AC Reviewer:

I have added a potential solution to the ACs for this problem. An alternative could be showing a different error message that would say something like "This metric tile requires an update to the connected Analytics property and they need to contact the person who set up Analytics".

CC: @aaemnnosttv

**Comment by aaemnnosttv** [comment] 2023-10-25 17:37
@nfmohit there's a bit more to this one than just the display (despite the title). Essentially the metric tiles that depend on unavailable custom dimensions should "not exist". This is already the case in the metric selection panel but only in the list. The tile still exists in terms of consuming an available slot, and that's apparent in the "x of y selected" number as well. Of course it shouldn't appear on the dashboard, but there might be a more fundamental way to frame the AC here that addresses both.

**Comment by nfmohit** [comment] 2023-10-26 08:31
I have updated the ACs, please let me know if it looks good, thank you @aaemnnosttv!

**Comment by aaemnnosttv** [comment] 2023-10-26 19:19
Thanks @nfmohit – the AC was a bit too specific about what should change internally and would probably work better as part of an IB – apologies if the direction was unclear. I've updated the AC to move this forward, let me know if you have any questions 👍

**Comment by nfmohit** [comment] 2023-10-27 17:20
> Thanks @nfmohit – the AC was a bit too specific about what should change internally and would probably work better as part of an IB – apologies if the direction was unclear. I've updated the AC to move this forward, let me know if you have any questions 👍

No worries! Looks perfect now, thank you @aaemnnosttv !

**Comment by techanvil** [comment] 2023-10-30 14:01
Thanks @hussain-t! Just to clarify, it's really just point 2) that makes me feel we should reconsider this one, I'd imagine we can figure a way around point 1) if needs be. Anyhow, interested to hear Evan's thoughts here.

**Comment by aaemnnosttv** [comment] 2023-10-30 22:03
Thanks @hussain-t, good points to surface here.

> 1. There's a discrepancy in the shared dashboard needs to be corrected. If `availableCustomDimensions` still has a deleted custom dimension (because an admin hasn't re-synced), the KM widget that should be hidden is still visible.

This is okay – the setting indicates that the dimension is available, so this should be a rare case. I don't think anything special is needed here. If anything, we could see about potentially caching the response to avoid invoking an error repeatedly, but it's more likely that a user would simply choose a different metric I think (maybe not though).

> 2\. An edge case: If only two widget tiles are initially selected, and one custom dimension is deleted, the shared dashboard is left with just one tile. This makes the whole KM area hidden, which might be confusing for users.

This probably isn't worth investing a lot of effort in catering for. In this situation, I think we could simply fall back to a default set of key metrics (either answer-based or catch-all just as if another admin had set up KM and the user hadn't picked their own yet – essentially ignoring their invalid saved choices). Then, the user could choose their metrics again which would only allow them to pick a new valid set. This might be the cleanest option for now because it wouldn't require us to come up with anything new.

Aside from that, this case sounds similar to a recoverable module (is this even covered in KMW? 🤔 ) I could also see having a variant of the `+` tile for such a widget where it prompts the user to choose different metrics where the selection panel would not include the invalid choices as defined in the AC.

**Comment by hussain-t** [comment] 2023-10-31 13:01
Thanks for the insights, @aaemnnosttv.

In light of your suggestions, I believe addressing the widget slugs directly within the `getKeyMetricsSettings` might be a straightforward approach. This way, we can centralize the change, effectively resolving both the widget tiles discrepancy and the metrics selection panel. Otherwise, we will have to fix them separately in multiple places. Please correct me if I'm wrong.

I'd like to hear from @techanvil and @nfmohit.

>I think we could simply fall back to a default set of key metrics (either answer-based or catch-all just as if another admin had set up KM and the user hadn't picked their own yet – essentially ignoring their invalid saved choices).

Falling back to a default metric set in this scenario seems a good way to fix it.

**Comment by techanvil** [comment] 2023-10-31 15:01
Hi @hussain-t, I think that keeping the majority of the logic centralised within `getKeyMetricsSettings()` makes a lot of sense if it allows us to address all of the requirements here. It strikes me that it would also facilitate @aaemnnosttv's suggestion to fall back to the defaults as it would provide that single point whereby we can make the determination that we're on the view-only Dashboard and have reduced the widget count to <2.

Recognising the desire to avoid tightly coupling core selectors with module stores/states, I would suggest we can avoid that by following a similar pattern to the existing use of `displayInList()`, e.g. adding a `displayOnViewOnlyDashboard()` callback to each of the definitions for KM widgets which require custom dimensions, and calling that when filtering the metrics in `getKeyMetricsSettings()`.

https://github.com/google/site-kit-wp/blob/73868dca2ffdb31d3525780d96c669bfe8ba28e6/assets/js/components/KeyMetrics/key-metrics-widgets.js#L201-L209

**Comment by hussain-t** [comment] 2023-11-01 05:29
Thanks for the insights, @techanvil. SGTM 👍

**Comment by techanvil** [comment] 2023-11-01 09:57
Thanks @hussain-t, and good spot, it does look like the existing logic in `shouldDisplayWidgetWithCustomDimensions()` should fit the bill here.

**Comment by eugene-manuilov** [comment] 2023-11-02 21:02
IB ✔️

**Comment by wpdarren** [comment] 2023-11-14 13:49
### QA Update: ✅ 

**Verified:**

- For a view-only user, any key metric widget tile that depends on a custom dimension that is not available has no presence in the dashboard, as if it does not exist. This includes:
  - Rendering in the KMW area
  - Rendering in the metric selection panel as well as behavior within (if previously selected somehow, it is not be included in the set of selected metrics, affects the selected count, etc.)
  - Checked all the points in the QAB and confirmed the verified areas. See the screenshots below. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/677a0b50-7b04-4aaf-85da-a7d31c5a70de)
![image](https://github.com/google/site-kit-wp/assets/73545194/d58cedd8-7cd8-41b0-be61-cd2492f1c378)
![image](https://github.com/google/site-kit-wp/assets/73545194/d0b3dc66-8390-48be-ae5f-5ab34c27b05f)
![image](https://github.com/google/site-kit-wp/assets/73545194/7d6bff0f-4702-47bb-90ab-86b8fe76f8a5)
![image](https://github.com/google/site-kit-wp/assets/73545194/bc84feda-64bc-41c8-977a-c3bbc38b796e)
![image](https://github.com/google/site-kit-wp/assets/73545194/fac12281-727c-480e-a92f-4f84fbe97b3c)
![image](https://github.com/google/site-kit-wp/assets/73545194/06078975-d651-441d-abcc-2cbd0b0c82d6)
![image](https://github.com/google/site-kit-wp/assets/73545194/16a6f8b8-85cb-4fb4-9895-9ef0e0436620)




</details>

**Closed** 2023-11-16 22:48 UTC
Labels: Type: Bug, P0
