### ISSUE TITLE
"Most Popular Content" table displaying page titles in different languages since 1.42.0

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4165] opened 2021-09-29 17:54 UTC
## Bug Description

Since the release of 1.42.0 there have been reports of unusual page title tiles in the "Most Popular Content" table. The titles of some pages are in different languages, including Chinese and German. In one users case this is occurring on both of their sites. 

These sites don't have language variations of their content, or have any language plugin active. 

In a screenshot kindly provided by one user [within their SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNgyRGF_VdK9R6uv8wHNMAZYrciU6QQqdZnShg1ugExC3oyIZpxoFT_k7YFmwf9z1Ws) it displays this behavior.  You'll notice that while the page titles are in a different language within the "Most populate content" table they do seem to match the actual title if the titles were to be translated. 

https://wordpress.org/support/topic/most-popular-content-broken-2/#post-14921621 | **Open** | [SH info ](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNgyRGF_VdK9R6uv8wHNMAZYrciU6QQqdZnShg1ugExC3oyIZpxoFT_k7YFmwf9z1Ws)
https://wordpress.org/support/topic/error-message-translated-page-titles/ | **Open** | [SH info 1](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNhCtg4ZDz3TzdwvZmrsJqcHAGJK1PFsP5joUg2VcwT_698mA7HVBs5j5iYdLwP5Ge0) |  [SH info 2 ](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNhSzutVF7x7fhHxvLyL-9DEnsiNhCr1fojN_6cIEe4M1YNQpBczCLWMPDBHjqjr538)
- [One use](https://wordpress.org/support/topic/error-message-translated-page-titles/)r is also encountering what looks like Google Charts Library related issues. These dashboard errors are not evident for the other user. Possibly related to #4074 
- There were some recent changes to the chart libraries as of 1.42.0. Possibly related to #3070

## Additional Context

 - SK 1.42.0
 - This didn't occur previously for one of the impacted users ([previous topic](https://wordpress.org/support/topic/most-popular-content-broken/) | [related GH issue](https://github.com/google/site-kit-wp/issues/1867)) 
 - One impacted user confirmed they never had a language plugin active or title variations of their pages

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The page titles report, used in the `getPageTitles` selector, should sort response rows by page views descending.

## Implementation Brief

* Update the object of `options` used for the page titles report to include the `orderby` parameter, which should be an array with a single object:
    *  `fieldName: 'ga:pageviews'`
    *  `sortOrder: DESCENDING`

### Test Coverage

* No changes should be necessary, but it may require some VRT images are updated as a result of this change

## QA Brief

* Verify the `getPageTitles()` selector sorts page titles by their page views (eg. `ga:pageviews`) in descending order as per the ACs/IB. There aren't easy steps-to-reproduce this bug here to QA, so this should be sufficient to QA it 🙂 

## Changelog entry

* Fix a bug that could cause the page title in the "Most Popular Content" table to appear in an unexpected language

**Comment by jamesozzie** [comment] 2021-09-30 11:39
The same occurs for [one impacted user](https://wordpress.org/support/topic/most-popular-content-broken-2/#post-14924233) with all plugins deactivated and using a core theme - from a Chrome browser incognito window. Further checks being performed.

**Comment by bethanylang** [comment] 2021-09-30 20:12
Moving to L1; @jamesozzie leaving a note for you in Asana now.

**Comment by eugene-manuilov** [comment] 2021-10-04 12:02
Looks like Google Analytics somehow tracks pages translated by Chrome and then we pick this information by accident when we try to aggregate page views by page URLs. I think we can fix it by adding `orderby` to sort page titles by page views descendently. In this case, even if there are records with translated titles, they will be ignored because their page views should be much lower than for the main language.

**Comment by eugene-manuilov** [comment] 2021-10-04 12:12
@aaemnnosttv can you check my AC?

**Comment by aaemnnosttv** [comment] 2021-10-04 14:32
@eugene-manuilov ACs LGTM (I think we were planning on making this change anyways) – were you able to confirm that Google translate is the cause here or are we assuming?

**Comment by eugene-manuilov** [comment] 2021-10-04 14:38
> were you able to confirm that Google translate is the cause here or are we assuming?

@aaemnnosttv unfortunately, I wasn't. That's my best hunch.

**Comment by aaemnnosttv** [comment] 2021-10-04 14:47
Thanks @eugene-manuilov, it sounds reasonable but I'm not sure we should use this as the AC for this issue in particular without knowing that it would solve the problem. Maybe we should do this anyways in a separate issue and follow it here?

Thoughts @felixarntz ?

**Comment by eugene-manuilov** [comment] 2021-10-05 11:56
IB :heavy_check_mark:

**Comment by kuasha420** [comment] 2021-10-19 05:11
I am seeing that `orderby` with the parameters from IB is already implemented in develop here. 

https://github.com/google/site-kit-wp/blob/1f783fc39329df3dad98b0b072d8f368de5c3d30/assets/js/modules/analytics/components/dashboard/DashboardPopularPagesWidget.js#L80-L91

Did this get implemented as part of another issue or am I missing something here? 

cc @aaemnnosttv @eugene-manuilov

**Comment by eugene-manuilov** [comment] 2021-10-19 12:34
@kuasha420, we forgot to mention it in IB that report arguments need to be updated in storybook stories too. Please, update the following report arguments:

https://github.com/google/site-kit-wp/blob/1f783fc39329df3dad98b0b072d8f368de5c3d30/stories/module-analytics-components.stories.js#L363-L375
https://github.com/google/site-kit-wp/blob/1f783fc39329df3dad98b0b072d8f368de5c3d30/stories/module-analytics-components.stories.js#L457-L469

**Comment by kuasha420** [comment] 2021-10-19 21:49
@aaemnnosttv @eugene-manuilov not sure what to put in QA Brief for this one. Any help will be appreciated.

**Comment by tofumatt** [comment] 2021-10-20 23:52
@kuasha420 Given there aren't clear steps-to-reproduce here I think it's fine to mark this one as `QA:Eng` and have the QA steps be to verify the implementation. It's not ideal but I think it's fine for this one 🙂 

I added a simple QA brief and the `QA: Eng` label 👍🏻

**Closed** 2021-11-04 17:18 UTC
Labels: Type: Bug, Type: Support, P1, QA: Eng, Module: Analytics, Rollover

**Comment by raja-anbazhagan** [comment] 2021-11-04 17:25
I'm at 1.44.0 and I'm still seeing Spanish titles for my pages on English.

**Comment by jamesozzie** [comment] 2021-11-05 13:14
@raja-anbazhagan We'll have the latest version of Site Kit released early next week. This fix will be part of that release so hopefully you'll not longer encounter this behavior at that point. Be sure to let us know the outcome once you test it!

**Comment by raja-anbazhagan** [comment] 2021-11-05 14:34
@jamesozzie I misread the update from @ivankruchkoff. Is there a snapshot version available for me to test?

**Comment by bethanylang** [comment] 2021-11-05 17:43
@raja-anbazhagan We do not offer pre-release testing versions, but as @jamesozzie noted, this will likely be released on Monday. If you're still having trouble after updating, please open a <a href="https://wordpress.org/support/plugin/google-site-kit/#new-post" rel="noopener noreferrer" target="_blank">new support topic</a> on our support forum and we'd be happy to take another look – all support for Site Kit is provided there on the forums. Thank you!

**Comment by jamesozzie** [comment] 2021-11-09 09:52
@raja-anbazhagan Just to let you know that Site Kit 1.45.0 has been released. Can you give that a try and confirm that the most popular content table works as expected with these latest changes?

**Comment by raja-anbazhagan** [comment] 2021-11-09 10:09
@jamesozzie Works perfectly. Thanks.
