### ISSUE TITLE
Exclude Analytics for all logged in users opt out snippet not excluding site visits when using GT Analytics tag

### ISSUE THREAD

**Issue by adamdunnage** [google/site-kit-wp#7262] opened 2023-07-06 14:50 UTC
## Bug Description

Analytics site visits are not being excluded when using the exclude Analytics for all logged in users with an Analytics Google Tag GT- property.  When the `ga-disable-` script uses a Google Tag (GT-), Analytics are still being tracked. 

This does not happen when the `ga-disable-` script uses a GA4 measurement ID. The opt-out snippet was [updated earlier this year](https://github.com/google/site-kit-wp/issues/6666) to use the Google Tag if set but it doesn't appear to exclude the Analytics for this property.  

Most users now using Site Kit will have a GT- tag connected so this will be affecting many users who have this setting on currently. 

An example support topic for this can be found below:
https://wordpress.org/support/topic/excluded-from-analytics-all-logged-in-users-not-working-through-sitekit/ 

A recording of this in action can be seen below:

https://www.loom.com/share/0af3ba8f2ec64394991a182768d5b8c8

## Steps to reproduce

1.  Log into a site with an active GT- tag connected via Analytics or set up a new site and connect Analytics creating a new property.
2. Ensure the exclude Analytics for all logged in users option is switched on.
3. Check your site source code for the `ga-disable-` script to make sure the GT- is being used.
4. Open the real time data section at the Analytics platform for the Analytics property.
5. Visit the site frontend 
6. See the real-time data update.

## Additional Context

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The tracking opt-out snippet for GA4 should be updated to use the configured measurement ID in all cases rather than using the GT style Google tag when present

## Implementation Brief

* Update the tag ID used for the GA4 opt out to use the `get_measurement_id` method rather than `get_tag_id` which returns the GT tag when present
* Merge https://github.com/google/site-kit-wp/pull/7370

### Test Coverage

* Update existing test coverage to ensure proper ID is used

## QA Brief

* This can be verified in the GA realtime reporting
* The only change is to the opt out snippet which is independent on the page from the regular tracking snippet. It will now always use the measurement ID even when tagged with a Google tag (GT)
```
<script>
window["ga-disable-G-XXXXXXXXXX"] = true;
</script>
```
* Using the GA debugger extension, you can see that when the tracking opt-out is present, no `page_view` event is sent and no traffic is visible in realtime reporting

## Changelog entry

* Fix the tag ID used in the GA tracking opt-out for logged in users when tagging with a Google tag.

**Comment by aaemnnosttv** [comment] 2023-07-27 18:07
Moving to CR since the IB is already covered by the attached PR.

**Comment by aaemnnosttv** [comment] 2023-07-27 20:06
@wpdarren @mohitwp let me know if you have any questions about reviewing this. No need to test UA here. There's essentially 2 cases:

- GA4 connected with measurement ID only (no GT tag) – There is essentially no change here
- GA4 connected with GT tag

In both cases, the tracking opt-out will use the measurement ID and should not track data to GA. Of course, this only does anything when tracking is excluded for (logged_in|edit_posts) users.

**Comment by mohitwp** [comment] 2023-07-28 09:55
### QA Update ✅ 

@wpdarren Assigning it to you. Can you please have a one more look at this? 

- Tested on dev environment.
- I'm able to reproduce issue on latest environment.
- Verified now on `ga-disable` script use `measurement id.`
- Verified now if exclude analytics for all logged in users is opt out then no traffic is visible in real-time reporting.

<details>

Issue >

https://github.com/google/site-kit-wp/assets/94359491/d2506bbf-6a2d-45ac-9f1a-17036f8327e3


https://github.com/google/site-kit-wp/assets/94359491/90f50d2e-2cad-45ef-84b9-f0e61ff32735

On main-

![image](https://github.com/google/site-kit-wp/assets/94359491/174f34cd-96b9-4114-bf00-bdf08900f080)

On latest -

![image](https://github.com/google/site-kit-wp/assets/94359491/2e4abc40-766e-4c6e-865b-154b68b31992)

</details>

**Comment by mohitwp** [comment] 2023-07-28 10:48
Also, @wpdarren @aaemnnosttv  I noticed that debugger creating and showing UA tag whereas connected a/c only have GA4 tag. I'm not sure if this is expected or not ?  It is listed as a tracking ID so maybe it is different from UA tag. But, flagging here for to rule out any issue.


<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/5b6a1256-f1fc-4855-a3a3-f894734d881a)

![image](https://github.com/google/site-kit-wp/assets/94359491/c3511cb2-da87-4421-9066-457be38877bc)

![image](https://github.com/google/site-kit-wp/assets/94359491/80dc51f9-c61f-44c5-a7a8-6b656c8dc34c)

</details>

**Comment by wpdarren** [comment] 2023-07-28 12:01
Thanks @mohitwp I am just running through the testing now and will check the debugger to see if I can see the same. I'll put an update on the ticket soon.

**Comment by wpdarren** [comment] 2023-07-28 12:37
### QA Update: ✅ 

**Verified;**

- While on the latest release, I can see the issue that visitors are getting tracked in the live view and the debugger tool. 
- When switching to the main branch, I can see that the opt-in tag has changed in the source code to the measurement ID and when looking at Analytics live view the traffic isn't getting logged.  I also checked the debugger tool and nothing getting sent to Analytics there either. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/67f03bb6-0086-41a8-ab46-d6e2b60df0a3)
![image](https://github.com/google/site-kit-wp/assets/73545194/4ddf8f65-5f0c-45b7-8b41-4631c4c2c248)
![image](https://github.com/google/site-kit-wp/assets/73545194/f2d5cf1b-f07a-45ef-94ba-68edbb27d284)
![image](https://github.com/google/site-kit-wp/assets/73545194/f5ca6826-6771-4f2e-b4b3-86c04fdeb2e8)

</details>

@mohitwp the UA- you see in the logs must be something related to the Google debugger tool, because when I create a brand new site and do not even connect Site Kit, the same appears for me.  I don't feel this is anything to worry about but maybe Evan @aaemnnosttv can just confirm this - unsure why we see UA reference.

![image](https://github.com/google/site-kit-wp/assets/73545194/e3623c5a-ea32-4282-a2a9-284e54339b6c)

**Comment by aaemnnosttv** [comment] 2023-07-28 13:19
> I don't feel this is anything to worry about but maybe @aaemnnosttv can just confirm this - unsure why we see UA reference.

You must have opted-in to SK's usage tracking, the UA ID is from SK, which you'd only see if logged in and opted-in. https://github.com/google/site-kit-wp/blob/1e47ee62eecb718b25a4a1cb74b9d783b44f0eea/includes/Core/Tracking/Tracking.php#L30

**Closed** 2023-07-28 15:22 UTC
Labels: Type: Bug, Type: Support, P0, Module: Analytics
