### ISSUE TITLE
User Input Multi Select Has Weird Behaviour for "Other"

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#2828] opened 2021-02-18 18:20 UTC
## Bug Description

On any of the multiselects that have "Other" as an option, items can be oddly checked/unchecked, see screenshot and video for two examples.

## Steps to reproduce

- Pick one item (Publish News Item), and start typing in the other field. 
- Now deselect other and everything else may be greyed out. 
- Select and delete all text in other and see that the checkbox is re-checked. 
- Now uncheck it and nothing happens.

## Screenshots

<img width="641" alt="multibug" src="https://user-images.githubusercontent.com/373931/108402759-cbba7f00-71d2-11eb-89a1-2788f908da35.png">

https://user-images.githubusercontent.com/373931/108402722-bc3b3600-71d2-11eb-8dda-8c62dd1259fd.mp4

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

See screencast above for how to recreate the odd behavior that should be fixed:

* A checkbox that has been unchecked by a user should not be automatically rechecked.
* User selections should not be changed.
* If only one checkbox is selected, options should not be greyed out.

## Implementation Brief

Remove the `fieldRef` and test
https://github.com/google/site-kit-wp/blob/9f39e3a/assets/js/components/Checkbox.js#L44-L53

Draft PR: https://github.com/google/site-kit-wp/pull/2971

### Visual Regression Changes

None

## QA Brief

Regular QA:
Attempt to repro the weird checkbox behaviour on any question that has checkboxes requiring a multiselect, no need to check the checkbox for other it should autocheck when you type in the `Other` text field.

Check the storybook story (comparative link for master branch: https://google.github.io/site-kit-wp/storybook/master/?path=/story/global--checkboxes )

QA Eng:
Inspect the `checked` prop of the `Checkbox` component and ensure that its value corresponds to whether or not the checkbox is checked. See the attached QA vid with the quick and dirty implementation from the comments.

https://user-images.githubusercontent.com/373931/110428627-6f72ae80-805e-11eb-84cc-affc6e0bfc1e.mp4

## Changelog entry

* Fix some bugs in the behavior when checking or unchecking an "Other" option for one of the questions in the user input flow.

**Comment by ivankruchkoff** [comment] 2021-02-24 05:41
Still looking for a root cause / fix here, https://github.com/google/site-kit-wp/blob/develop/assets/js/components/user-input/UserInputSelectOptions.js#L49 does not trigger on the checkbox for the `other` checkbox, but I'm still trying to work out why.

**Comment by ivankruchkoff** [comment] 2021-03-08 06:48
There is an easier and hackier fix for this to do this:

1) Insert the disabled attribute here:
https://github.com/google/site-kit-wp/blob/e3bf45b2b2e06227505c77350e21b3fecfd482b4/assets/js/components/user-input/UserInputSelectOptions.js#L120
`disabled={ max > 1 && values.length >= max && ! values.includes( other ) }`

```js
<Input
  id={ `${ slug }-select-options` }
  value={ other }
  onChange={ onOtherChange }
  disabled={ max > 1 && values.length >= max && ! values.includes( other ) } />
```

2) Trigger the onClick handler here:
https://github.com/google/site-kit-wp/blob/e3bf45b2b2e06227505c77350e21b3fecfd482b4/assets/js/components/user-input/UserInputSelectOptions.js#L66

From:
```js
setOther( target.value );
setUserInputSetting( slug, newValues.slice( 0, max ) );
```

To:
```js
setOther( target.value );
const otherCheckBox = document.getElementById( 'goals-other' );
if ( ! otherCheckBox.checked ) {
	otherCheckBox.click();
}
setUserInputSetting( slug, newValues.slice( 0, max ) )
```

I believe we can do the same using `forwardRef` https://reactjs.org/docs/forwarding-refs.html to give the `onOtherChange` a ref to the `<ListComponent />` corresponding to the other checkbox.

**Comment by aaemnnosttv** [comment] 2021-03-08 09:29
@ivankruchkoff – the issue is in IBR but the IB is blank; did you forget to save perhaps? 😄

**Comment by ivankruchkoff** [comment] 2021-03-08 14:44
> @ivankruchkoff – the issue is in IBR but the IB is blank; did you forget to save perhaps? 😄

Looks to be that way, added it back. Please take a look, as well as at the comment for the alternate approach.

**Comment by aaemnnosttv** [comment] 2021-03-08 21:59
Thanks @ivankruchkoff, given the two approaches, the second simpler approach is easier to follow and looks okay although we should use `ref`s if at all possible rather than querying the DOM. See next point 😄 

> I believe we can do the same using `forwardRef` https://reactjs.org/docs/forwarding-refs.html to give the `onOtherChange` a ref to the `<ListComponent />` corresponding to the other checkbox.

I'm not sure if this will work without changing our `Radio` and `Checkbox` components as they don't currently pass refs to the native controls. Worth taking a look though.

Regarding this part from the current IB

> Remove everywhere we truncate the number of values, we shouldn't be able to set more values than max.

This may not be needed for settings values, but it's important that we keep it for the `dependencies` array since it needs to stay the same length across renders.

I think this is probably good to get a branch going (if you don't already have one) but please update the IB with your alternate approach and let's take it from there 👍

**Comment by ivankruchkoff** [comment] 2021-03-09 06:57
> Thanks @ivankruchkoff, given the two approaches, the second simpler approach is easier to follow and looks okay although we should use `ref`s if at all possible rather than querying the DOM. See next point 😄
> 
> > I believe we can do the same using `forwardRef` https://reactjs.org/docs/forwarding-refs.html to give the `onOtherChange` a ref to the `<ListComponent />` corresponding to the other checkbox.
> 
> I'm not sure if this will work without changing our `Radio` and `Checkbox` components as they don't currently pass refs to the native controls. Worth taking a look though.

Updated with the second approach, some cleanup, and using `ref`s if at all possible, with reference to the `Checkbox` component that may need updating.

> 
> Regarding this part from the current IB
> 
> > Remove everywhere we truncate the number of values, we shouldn't be able to set more values than max.
> 
> This may not be needed for settings values, but it's important that we keep it for the `dependencies` array since it needs to stay the same length across renders.

Updated to only be the values, not the `dependencies`.

> 
> I think this is probably good to get a branch going (if you don't already have one) but please update the IB with your alternate approach and let's take it from there 👍

`bug/2828-other-checkbox`

**Comment by eugene-manuilov** [comment] 2021-03-11 19:17
@ivankruchkoff I have taken a look at this issue and seems like all glitches are caused by the Checkbox component itself. In particular, the following code causes it: https://github.com/google/site-kit-wp/blob/f3eea273ba67e3319457f8b22601461e3813954b/assets/js/components/Checkbox.js#L46-L51
If you comment out those lines, everything will work as expected. Can you try it on your end? @tofumatt do you recall why we need those MDCFormField and MDCCheckbox instances?

**Comment by tofumatt** [comment] 2021-03-15 12:30
I honestly have no clue! 😅 

I think that code traces its origins back to the "original commit" when the plugin was open-sourced, but any of the component that use that approach (of creating elements from `new MDC*()` predate @aaemnnosttv and I, I think.

I don't think there's any clear benefit to that approach, and I bet we should be using Material React component directly and not attaching these classes to DOM elements…

**Comment by ivankruchkoff** [comment] 2021-03-16 22:31
Digging in a bit further, we initially had a class component
https://github.com/google/site-kit-wp/blame/05a4265cf21c4ed9a10d8623e756c953fd7b2bb8/assets/js/components/checkbox.js

Which we refactored to a functional one in #2189. We wrote a storybook story for it, and the same bug exists there see the attached video:
https://google.github.io/site-kit-wp/storybook/master/?path=/story/global--checkboxes

https://user-images.githubusercontent.com/373931/111388472-9176bd00-866c-11eb-9fbe-39be49cf3e57.mp4



I've updated the branch with @eugene-manuilov 's suggestion, updated the IB and created a draft PR https://github.com/google/site-kit-wp/pull/2971

The only other place where we use a Checkbox component is in the `<OptIn />` component https://github.com/google/site-kit-wp/blob/9f39e3a/assets/js/components/OptIn.js#L67

**Comment by aaemnnosttv** [comment] 2021-03-17 12:33
@ivankruchkoff – I can't actually reproduce this on `develop`; was this maybe fixed by one of the other "Other" related issues which was recently merged?
Can you reproduce here? https://google.github.io/site-kit-wp/storybook/develop/?path=/story/user-input--userinputapp

**Comment by ivankruchkoff** [comment] 2021-03-17 17:19
@aaemnnosttv yes I can on the checkbox component story, see https://google.github.io/site-kit-wp/storybook/develop/?path=/story/global--checkboxes, and also on the userinput story in https://google.github.io/site-kit-wp/storybook/develop/?path=/story/user-input--userinputapp see the attached video

https://user-images.githubusercontent.com/373931/111509660-2f6c9500-870a-11eb-84a4-c35737e93d36.mp4

**Comment by aaemnnosttv** [comment] 2021-03-18 08:01
Thanks @ivankruchkoff! I'm okay with the current IB as good for now if it solves the problem but part of the problem here is that we're somewhat unnecessarily reimplementing the checkbox component rather than using `@material/react-checkbox` (see #2510). I took a quick look to see if updating our `Checkbox` to use it would solve the problem and it didn't. It also does not support the `value` prop (which is a bit weird and perhaps why we don't/no-longer use it). We can leave that for another issue though.

IB ✅

**Comment by wpdarren** [comment] 2021-03-24 15:07
### QA Update: ⚠️ Engineer to clarify behaviour 

I would like to clarify what I am seeing:  

- On `step 3`, I select `Publish news content` 
- Then I type in text into the `Other` input text field. 
- This automatically, checks the `Other` checkbox option.  
- When I deselect `Other` all of the options become active and none are greyed out. 
- But, when I go to delete the text in the `Other` input text field, this automatically selects the `Other` checkbox option
- Also, all of the options are now greyed out. 

To get to a stage where I am able to select another option, I have to deselect the `Other` checkbox option.

In my opinion, when you remove the text, it should not select the `Other` checkbox option.  Thoughts? 

Hopefully, this all makes sense.  😄

**Comment by aaemnnosttv** [comment] 2021-03-24 17:12
Thanks @wpdarren – I think what you're describing is okay. I agree it might be better if clearing the input did not cause the field to become checked, but should not be a blocker here. You could extend the same thinking to the behavior of the checkbox – if we uncheck the checkbox should we also clear its input field? If we clear the input, should we also uncheck the box automatically? Most importantly, is the experience actually confusing or difficult to use without such behavior?

Thoughts @felixarntz ?

**Comment by felixarntz** [comment] 2021-03-24 17:23
@wpdarren @aaemnnosttv I'm not sure what's the best UX for this. I also first thought that maybe the text should be removed when unchecking the box, but that might also be annoying if you wanted to re-check it and then would have to type the same text again.

I think we can move forward with this as is. We're not going to launch it just yet, and another UX review at some point or users reporting this as confusing could inform our decision later. I don't think this is critical to block the issue.

**Comment by wpdarren** [comment] 2021-03-25 01:16
### QA Update: Pass ✅ 

**Verified:**

Reproduced the weird checkbox behaviour on any question that has checkboxes requiring a multiselect. On the develop branch though I could see though that when I deselect `Other` all of the options become active and none are greyed out, which it wasn't doing before.  Documented the [behaviour above](https://github.com/google/site-kit-wp/issues/2828#issuecomment-805900665) which is expected at this point.

**Comment by aaemnnosttv** [comment] 2021-03-25 09:37
## QA ✅ 

Multi-select with Other field seems to work as expected.

**Closed** 2021-03-26 20:53 UTC
Labels: P0, QA: Eng, Type: Bug
