### ISSUE TITLE
Filter Analytics API results to only include results for current domain

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2554] opened 2020-12-21 16:25 UTC
#2110 altered the API requests for Search Console to limit results to URLs within the current domain. It did that only for domain properties because for URL properties this is already the case by definition.

However, for Analytics a property is not limited to one domain. While it is intended to be used with one domain, in principle data from any domain can be sent there. We should therefore apply a dimension filter to all Google Analytics API requests to allow only URLs within the current site's domain to be included in the results.

This is a rather minor enhancement as it won't have an effect on most sites. However for certain types of properties that rely on data from more than one site it can help, as well as avoid confusion in [cases like this](https://github.com/google/site-kit-wp/issues/2540#issuecomment-748228990).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All Analytics API requests should (automatically on the server-side) apply a dimension filter that limits results to those within the current site's domain (via PHP).

## Implementation Brief

* Update `includes/Modules/Analytics.php` `create_analytics_site_data_request` function.
   * Add new code before the `$request->setDimensionFilterClauses( $dimension_filter_clauses );` (line 1000)  which includes a new dimension filter **on every request** with:
    * dimension [`ga:hostname`](https://ga-dev-tools.appspot.com/dimensions-metrics-explorer/?#ga:hostname)
    * operator `EXACT`
    * the site hostname `$hostname`
* Get the sites hostname from WP's `$this->context->get_reference_site_url()` like so:
```
$url = parse_url($this->context->get_reference_site_url());
$hostname = $url['host'];
```

* Remove the conditional block around `$request->setDimensionFilterClauses( $dimension_filter_clauses );` as a dimension filter will now be set on all requests.

### Test Coverage

* Create a new test in `tests/phpunit/integration/Modules/AnalyticsTest.php` to ensure that the `ga:hostname` dimension is automatically added to a request.

### Visual Regression Changes

* There will be no visual regressions.

## QA Brief

* Make sure that Analytics module works as usual;
* Go to the developer plugin settings and change the referrence URL to a different URL (let's say http://example.com/);
* Clear your browser session storage;
* Go to the dashboard page and make sure that all Analytics widgets display zero data state.

## Changelog entry

* Filter all Analytics API requests to only include results for the current domain.

**Comment by benbowler** [comment] 2021-01-30 12:02
Added IB and estimate.

**Comment by felixarntz** [comment] 2021-02-02 02:00
@benbowler IB looks close, but there are two pieces that likely need to be changed:
> * operator `contains`

I think this should rather be a regular equal comparison. We should only match entries where the domain matches exactly the site's domain, for example a subdomain would still contain the site's domain, but should still not be included.

> * the current reference site URL, without trailing slash `trim( $this->context->get_reference_site_url(), '/' )`

This needs to only get the site's domain, not the full site URL, which would also include protocol, and potentially even a path, e.g. if the site URL is something like `https://example.com/subsite/`.

**Comment by benbowler** [comment] 2021-02-15 13:30
Hey @felixarntz, I've addressed your comments above, let me know if this covers everything you were thinking of.

**Comment by felixarntz** [comment] 2021-02-17 20:41
@benbowler This is almost good to go, just one more thing:

> Get the sites hostname from WP's home_url() like so

The URL needs to come from the reference URL (`$this->context->get_reference_site_url()`), which _usually_ is the same as the `home_url()`, but it can be filtered e.g. for staging sites to pull data for another site URL than the current one.

**Comment by benbowler** [comment] 2021-02-18 13:12
Updated the IB.

**Comment by felixarntz** [comment] 2021-02-19 16:31
IB ✅

**Comment by aaemnnosttv** [comment] 2021-03-02 18:14
@eugene-manuilov would you please add a QA Brief?

**Comment by eugene-manuilov** [comment] 2021-03-03 11:25
@aaemnnosttv added and marked as `QA: Eng` since there are no visual changes.

**Comment by aaemnnosttv** [comment] 2021-03-03 18:25
@eugene-manuilov I think we should be able to QA this without an engineer. We after ensuring Analytics works as usual using a matching property and reference URL, we can update the reference URL, clear the cache and load it again and Analytics should then show zero data because the data would be filtered out.

**Comment by eugene-manuilov** [comment] 2021-03-03 18:48
@aaemnnosttv ok, is it better now?

**Comment by aaemnnosttv** [comment] 2021-03-04 09:18
Super! Thanks @eugene-manuilov 👍

**Comment by cole10up** [comment] 2021-03-05 07:43
### QA ✅

Ran a series of regression tests around the Analytics module, changing my reference URL and confirming Analytics reflect the current domain.

Analytics module without reference URL adjusted:
![image](https://user-images.githubusercontent.com/57115907/110082917-da607480-7d42-11eb-9ea2-4f9af11b7bd3.png)

Reference URL adjusted:
![image](https://user-images.githubusercontent.com/57115907/110083193-3deaa200-7d43-11eb-8ecc-45039cdc59de.png)

Confirmed dashboard functionality:
![image](https://user-images.githubusercontent.com/57115907/110083330-6b375000-7d43-11eb-9d08-48d49d395baa.png)

Sending to approval

**Closed** 2021-03-15 17:30 UTC
Labels: Module: Analytics, P2, Rollover, Type: Enhancement
