### ISSUE TITLE
Formatting and clarity issues on GA4 property creation message

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#3584] opened 2021-06-15 18:50 UTC
## Bug Description

When Analytics with a UA property is already connected and the user goes to Settings > Connected Services > Analytics and clicks Edit, the following message displays:

![image](https://user-images.githubusercontent.com/12189958/122106159-93752700-cde7-11eb-80fb-a935163947dc.png)

I've gone through this process on several sites today and the message displayed this way (with two stars) on most but not all of the sites – on at least one it displayed correctly. I'm not sure what specifically causes it display incorrectly like this.

Two issues here:

First, the extra star with an empty line should be removed.

Second, this message appears to be the same one that displays when a user is going through initial Analytics setup via the new GA4 workflow, where they are told that a UA property will be created *and* "a Google Analytics 4 property will also be created." 

However, in this case, this language is confusing because only *one* thing will be created, and it will be the GA4 property. It's also not clear to the user that clicking Confirm Changes is the next step to start the process of creating a new GA4 property to pair with their existing UA property.

Is it possible to change the message here to be different from the message in the initial setup workflow? Something like:

"This account currently does not have any associated GA4 properties. To create and connect a new GA4 property, click Confirm Changes."

## Steps to reproduce

1. Install and activate Site Kit with the tester plugin and main branch in order to test GA4
2. Ensure that a UA property is already connected in Analytics
3. Go to Settings > Connected Services > Analytics and click Edit
4. The message will display

## Screenshots

See above

## Additional Context

 - OS: macOS Big Sur
 - Browser: Replicated in both Chrome and Firefox
 - Plugin Version 1.34.1 + Tester v1.5.1 on main branch
 - Device: Mac

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GA4 notice around the respective other property (see ACs) should never display the star icon twice, it should look like in the Figma design.

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment] 2021-06-15 21:13
@bethanylang Good catch! Since this somewhat covers two problems and since you've also opened #3586 which talks about the confusing notice as well, I've limited the ACs and scope of this one here to just fix the double star. Let's focus the efforts on improving the overall process via #3586.

**Comment by eugene-manuilov** [comment] 2021-06-16 09:11
@bethanylang could you please share a site where you see the double stars issue? I can't reproduce it on my end.

**Comment by bethanylang** [comment] 2021-06-16 14:45
@eugene-manuilov I'm seeing it at https://s3.cmsdevrel.com – creds are in the sheet I shared with you yesterday.

**Comment by eugene-manuilov** [comment] 2021-06-17 07:14
@bethanylang hm... it works fine for me:

![Screenshot from 2021-06-17 10-12-03](https://user-images.githubusercontent.com/873049/122349154-a2c5b300-cf54-11eb-8639-2b756740cb72.png)

Could you please clear your browser cache and try again?

**Comment by bethanylang** [comment] 2021-06-17 13:20
@eugene-manuilov James had mentioned to me that this might be a tester plugin-specific issue – checking around to confirm.

**Comment by bethanylang** [comment] 2021-06-17 15:12
Reassigning to @wpdarren for some additional testing.

**Comment by wpdarren** [comment] 2021-06-18 13:04
@bethanylang I am unable to recreate this, and have tried on two sites that only have UA properties.  I'm wondering if its a caching issue. Could you use install and activate the [Version Assets](https://wordpress.org/plugins/version-assets/) plugin, and then go through the steps again, to see if this issue is fixed.  This plugin makes sure you are getting a fresh view of the content.  Also, what device/browser are you testing this on? 

I'll keep myself assigned to continue having a look.

**Comment by bethanylang** [comment] 2021-06-21 19:02
Thanks for taking a look, @wpdarren! @jamesozzie mentioned that he's seen this before and he's doing some testing on GA4 this week, so I'm going to assign over to him to report back on his findings.

**Comment by eclarke1** [comment] 2021-06-23 13:34
Neither @bethanylang @jamesozzie or @wpdarren can replicate this issue. Agreed to close this @felixarntz @aaemnnosttv FYI.

**Closed by eclarke1** 2021-06-23 13:34 UTC
Labels: Module: Analytics, P0, Type: Bug, Type: Support
