### ISSUE TITLE
Supporter Wall not showing on Widgets editor view

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5742] opened 2022-08-25 17:09 UTC
On the Widgets editor page the Supporter Wall doesn't show up, it just shows a spinner and there is an error in the console.
Just to be clear, it does show up correctly on the public facing site.

![Widgets editors page](https://user-images.githubusercontent.com/93320881/186727438-e8c121ef-34dc-4320-b16d-917e1f10b904.png)

![Public facing site](https://user-images.githubusercontent.com/93320881/186727453-7a63f1be-1206-460f-ba78-014d5323cc12.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2022-08-29 21:18
After discussing with the TwG team, this likely requires changes on their JS side rather than in the plugin but keeping this open for now until it is resolved.

**Comment by FlicHollis** [comment] 2022-08-31 08:25
Thanks @aaemnnosttv should this be removed from the current sprint then if we are likely not going to action anything here?

**Comment by eclarke1** [comment] 2022-08-31 09:57
Yes @FlicHollis , I just removed. William on the TwG side said he was aiming to have a fix for this yesterday. I have chased him this morning as to whether that did get deployed and once confirmed, we can test this again @wpdarren @mohitwp

**Comment by eclarke1** [comment] 2022-08-31 13:25
@wpdarren @mohitwp the fix for this has been deployed by the TwG team, please could you have a check and let us know if the issue is still present?
Moving to QA column for now.

**Comment by wpdarren** [comment] 2022-08-31 14:24
### QA Update: ✅ 

**Verified:**

- On the Widgets editor page the Supporter Wall does not show up and there is no error in the console.
- On the Front end the widget still appears as expected, in the correct widget area. 
- Tested this with a few different popular WordPress themes. 

![image](https://user-images.githubusercontent.com/73545194/187701681-0b8b3737-23fb-44a5-ae2f-3937d941c063.png)

@eclarke1 I will move this to Approved (although it's on the JS Library side) and update Asana.

**Comment by aaemnnosttv** [comment] 2022-08-31 14:29
Thanks @wpdarren – Closing this out as fixed as it didn't involve any changes on our end to address 😄

**Closed by aaemnnosttv** 2022-08-31 14:29 UTC
Labels: P0, Module: Thank with Google
