### ISSUE TITLE
Release 1.95.0

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6564] opened 2023-02-08 23:00 UTC
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Release is prepared, tested, and deployed to wordpress.org.

## Implementation Brief

* N/A

## QA Brief

* N/A

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment] 2023-02-23 22:49
I noticed an issue while testing but it does not appear to be a regression. I opened a new issue to fix it:

- https://github.com/google/site-kit-wp/issues/6633

**Comment by hussain-t** [comment] 2023-02-24 14:45
## QA Verified :white_check_mark:
- Smoke tested.
- Verified the changes I’ve been involved with.
- Performed some ad-hoc testing.

**Comment by kuasha420** [comment] 2023-02-26 07:14
:QA: :heavy_check_mark: 

* Went through the release checklist.
* Focused on Plugin initial setup, all the module setup and Dashboard Sharing test.

LGTM. :+1:

**Comment by wpdarren** [comment] 2023-02-27 04:03
### QA Update: ⚠️ 

I am coming across an issue with the tour tooltips that appear to be a regression because I am unable to recreate on 1.94.0. 

For the new dashboard navigation tour tooltip when a user updates Site Kit from a version older than 1.25.0.  On the main branch as you go through the steps, on the last tooltip, a fatal error appears.  

Just `dashboardSharing` and `ga4ActivationBanner` feature flags were enabled, but the issue still arises when they're disabled.  You can see it in action on the screencast:

https://user-images.githubusercontent.com/73545194/221470705-d66aab74-3125-4f23-8f1b-dd945054804b.mp4

**Comment by mohitwp** [comment] 2023-02-27 09:12
QA Update ⚠️ 

@wpdarren I'm able to reproduce  [mentioned](https://github.com/google/site-kit-wp/issues/6564#issuecomment-1445665515) issue on 1.95.0.

- Went through QA check list.
- Tested using PHP version 7.4, 8.1 and 8.2.
- Tested site for zero and gathering data state.
- Tested GA4 activation banner set up.
- Tested Dashboard sharing functionality.

**Comment by wpdarren** [comment] 2023-02-27 10:43
### QA Update: ⚠️ 

In AdSense settings, when you click on the `See full details in AdSense` link you redirected to a 404.  

When I change to the latest release the issue still exists, so the issue is on Google side, not the plugin. 

I wonder if we should investigate and fix in this release?  

I am unsure when the URL was removed but it might cause support tickets.   

Thought I would highlight it here for further investigation. 

https://user-images.githubusercontent.com/73545194/221541864-3b35cfd2-c95d-4f58-a9b6-48749b480cd6.mp4

**Comment by wpdarren** [comment] 2023-02-27 12:22
### QA Update: ✅ 

Observed two issues which I reported above. 

**Verified:**

- Went through the QA checklist
  - Tested with a site in gathering and zero data states
  - Tested with a site with real data
  - Tested using PHP version 7.4
- Tested GA4 notification banner
- Tested Dashboard Sharing

**Comment by techanvil** [comment] 2023-02-27 16:39
## QA :white_check_mark: 
- Smoke tested.
- Verified the changes I’ve been involved with.
- Performed some ad-hoc testing.

Found no issues beyond those that have already been raised. I have raised a [PR](https://github.com/google/site-kit-wp/pull/6646) to fix [this bug](https://github.com/google/site-kit-wp/issues/6564#issuecomment-1445665515) that @wpdarren spotted.

**Comment by tofumatt** [comment] 2023-02-27 23:09
QA ✅

Smoke tested and went through site setup and upgrades without any issues aside from existing ones; I tested before the above PR mentioned by @techanvil was merged but I tested that in the PR and it seemed fine 🙂 .

**Comment by nfmohit** [comment] 2023-02-28 00:55
## Release Tested ✅

- Release tested 1.95.0 thoroughly.
- Set everything up from scratch on a live (InstaWP) site.
- Didn't spot any unexpected console errors.
- Verified UI in different device breakpoints.
- Verified changes I've been involved with.
- Used our release testing checklist to ensure everything is checked.
- Smoke tested with available feature flags.
- I was able to replicate [this issue](https://github.com/google/site-kit-wp/issues/6564#issuecomment-1445665515) earlier, and have tested again after [this PR](https://github.com/google/site-kit-wp/pull/6646) was merged, which seems to have resolved it.

**Closed** 2023-02-28 20:23 UTC
Labels: P0, Type: Task
