### ISSUE TITLE
E2E tests take much longer on newer versions of WP

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5460] opened 2022-06-27 19:16 UTC
## Bug Description

![image](https://user-images.githubusercontent.com/1621608/176018138-2292a7f2-a58a-44c1-adca-e20d01f25dbe.png)

```diff
-PASS tests/e2e/specs/modules/tagmanager/setup.test.js (39.996s)
+PASS tests/e2e/specs/modules/tagmanager/setup.test.js (95.32s)
   Tag Manager module setup
     Setup without AMP active
-      ✓ displays account creation form when user has no Tag Manager account (5833ms)
-      ✓ displays available accounts and containers for the chosen account (4981ms)
-      ✓ displays instructions for account creation when "Set up a new account" option is selected (2763ms)
+      ✓ displays account creation form when user has no Tag Manager account (8214ms)
+      ✓ displays available accounts and containers for the chosen account (7330ms)
+      ✓ displays instructions for account creation when "Set up a new account" option is selected (4668ms)
     Setup with AMP active
       with Secondary AMP
-        ✓ renders both the AMP and web container select menus (3580ms)
+        ✓ renders both the AMP and web container select menus (7227ms)
         when validating
-          ✓ validates homepage AMP for logged-in users (9228ms)
-          ✓ validates homepage AMP for non-logged-in users (5952ms)
-PASS tests/e2e/specs/modules/analytics/setup-with-account-no-tag.test.js (16.195s)
+          ✓ validates homepage AMP for logged-in users (15478ms)
+          ✓ validates homepage AMP for non-logged-in users (9325ms)
+PASS tests/e2e/specs/modules/analytics/setup-with-account-no-tag.test.js (23.41s)
   setting up the Analytics module with an existing account and no existing tag
     using Proxy auth
-      ✓ pre-selects account and property if the tag matches one belonging to the user (6214ms)
-      ✓ prompts for account and property if the site URL does not match a property belonging to the user (4050ms)
+      ✓ pre-selects account and property if the tag matches one belonging to the user (8948ms)
+      ✓ prompts for account and property if the site URL does not match a property belonging to the user (6294ms)
     using GCP auth
-      ✓ includes an option to setup a new account (4633ms)
-PASS tests/e2e/specs/modules/analytics/write-scope-requests.test.js (15.806s)
+      ✓ includes an option to setup a new account (5887ms)
+PASS tests/e2e/specs/modules/analytics/write-scope-requests.test.js (24.419s)
   Analytics write scope requests
-    ✓ prompts for additional permissions during a new Analytics account creation if the user has not granted the Analytics provisioning scope (3906ms)
-    ✓ prompts for additional permissions during a new Analytics property creation if the user has not granted the Analytics edit scope (5273ms)
+    ✓ prompts for additional permissions during a new Analytics account creation if the user has not granted the Analytics provisioning scope (6069ms)
+    ✓ prompts for additional permissions during a new Analytics property creation if the user has not granted the Analytics edit scope (8065ms)
+    ✓ prompts for additional permissions during a new Analytics profile creation if the user has not granted the Analytics edit scope (8500ms)
+PASS tests/e2e/specs/modules/adsense/setup-new-user.test.js (106.684s)
+  setting up the AdSense module
+    ✓ displays “Your account is getting ready” when account is graylisted (5822ms)
+    ✓ displays “Your account is getting ready” when the Adsense account is pending review (5669ms)
+    ✓ displays “Your site isn’t ready to show ads yet” when the users account is disapproved (5656ms)
+    ✓ displays “Create your AdSense account” when the user does not have an AdSense account (6013ms)
+    AMP is setup
+      ✓ has valid AMP for logged-in users (43358ms)
+      ✓ has valid AMP for non-logged in users (38514ms)
+PASS tests/e2e/specs/admin-tracking.test.js (48.542s)
+  management of tracking opt-in/out via settings page
+    ✓ should be opted-out by default (3660ms)
+    ✓ should have tracking code when opted in (4327ms)
+    ✓ should check opt-in box when clicked (3485ms)
+    ✓ should uncheck opt-in box when clicked (3771ms)
+    ✓ should not have tracking code when not opted in (3566ms)
+  initialization on load for Site Kit screens
+    splash page
+      ✓ does not load tracking if not opted-in (1309ms)
+      ✓ loads tracking when opted-in (1786ms)
+    settings page
+      ✓ does not load tracking if not opted-in (2478ms)
+      ✓ loads tracking when opted-in (3030ms)
+    Site Kit dashboard
+      ✓ does not load tracking if not opted-in (3027ms)
+      ✓ loads tracking when opted-in (3676ms)
+    module pages
+      ✓ does not load tracking if not opted-in (3007ms)
+      ✓ loads tracking when opted-in (3496ms)
+  initialization on load for non-Site Kit screens
+    plugins page
+      ✓ does not load tracking if not opted-in (793ms)
+      ✓ does not load tracking if opted-in (1819ms)
+    WordPress dashboard
+      ✓ does not load tracking if not opted-in (1081ms)
+      ✓ does not load tracking if opted-in (1842ms)
+PASS tests/e2e/specs/dashboard/search.test.js (13.076s)
+  Site Kit dashboard post search
+    ✓ displays results when searching with a post title, and loads the details page when clicking View Data (2371ms)
+    ✓ displays results when searching with a URL, and loads the details page when clicking View Data (2548ms)
+    ✓ displays "No results found" when searching by title if no post is found (1388ms)
+    ✓ displays "No results found" when searching by URL if no post is found (1482ms)
+    ✓ works with post titles containing special characters (2099ms)
+PASS tests/e2e/specs/modules/optimize/activation.test.js (122.377s)
+  Optimize Activation
+    ✓ prompts to insert your Optimize ID when Analytics snippet is enabled (6599ms)
+    ✓ prompts to insert your Optimize ID when Analytics snippet is disabled, with extra instructions (5415ms)
+    Settings with AMP enabled
+      ✓ displays AMP experimental JSON field (35583ms)
+    Homepage AMP
+      ✓ validates for logged-in users (38448ms)
+      ✓ validates for non-logged-in users (34554ms)
+PASS tests/e2e/specs/modules/search-console/dashboard-date-range.test.js (11.981s)
+  date range filtering on dashboard views
+    ✓ loads new data when the date range is changed on the Site Kit dashboard (3939ms)
+    ✓ loads new data when the date range is changed on a dashboard details view for a single post (4348ms)
+PASS tests/e2e/specs/modules/search-console/admin-bar.test.js (9.437s)
+  Site Kit admin bar component display
+    ✓ loads when viewing the front end of a post with data in Search Console (782ms)
+    ✓ loads when editing a post with data in Search Console (3916ms)
+    ✓ links "More details" to the dashboard details view for the current post (1709ms)
+PASS tests/e2e/specs/modules/analytics/setup-with-account-with-tag.test.js (19.885s)
+  setting up the Analytics module with an existing account and existing tag
+    ✓ informs about an existing tag that matches the current selected property (6806ms)
+    ✓ allows Analytics to be set up with an existing tag that does not match a property of the user (4886ms)
+    ✓ does allow Analytics to be set up with an existing tag if it is a GA4 tag (6620ms)
+PASS tests/e2e/specs/modules/analytics/setup-gcp-no-account-no-tag.test.js (10.831s)
+  setting up the Analytics module using GCP auth with no existing account and no existing tag
+    ✓ displays account creation form when user has no Analytics account (9272ms)
+PASS tests/e2e/specs/user-input-questions.test.js (24.498s)
+  User Input Settings
+    ✓ should require new users to enter input settings after signing in (7135ms)
+    ✓ should offer to enter input settings for existing users (7946ms)
+    ✓ should let existing users enter input settings from the settings page (7876ms)
+PASS tests/e2e/specs/modules/analytics/setup-proxy-no-account-no-tag.test.js (14.18s)
+  setting up the Analytics module with no existing account and no existing tag via proxy
+    ✓ displays account creation form when user has no Analytics account (5409ms)
+    ✓ preserves user-filled values provided and auto-submits after approving permissions (7296ms)
+PASS tests/e2e/specs/dashboard/notifications.test.js (11.87s)
+  core site notifications
+    when using proxy
+      ✓ displays core site notifications on the main dashboard (6624ms)
+    when not using proxy
+      ✓ does not display core site notifications on the main dashboard (1046ms)
+PASS tests/e2e/specs/plugin-activation.test.js (12.852s)
+  plugin activation notice
+    using proxy auth
+      ✓ should be displayed (1520ms)
+      ✓ should not display noscript notice (1765ms)
+    using GCP auth
+      ✓ should be displayed (1503ms)
+      ✓ should not display noscript notice (1443ms)
+      ✓ should lead you to the setup wizard with GCP auth (2081ms)
+PASS tests/e2e/specs/auth/gcp-setup-verification.test.js (13.512s)
+  Site Kit set up flow for the first time with site verification
+    ✓ prompts for confirmation if user is not verified for the site (5927ms)
+    ✓ does not prompt for verification if the user is already verified for the site (5749ms)
+PASS tests/e2e/specs/auth/gcp-setup-search-console.test.js (12.97s)
+  Site Kit set up flow for the first time with search console setup
+    ✓ inserts property to search console when site does not exist (5608ms)
+    ✓ saves search console property when site exists (5786ms)
+PASS tests/e2e/specs/amp/admin-bar.test.js (43.307s)
+  AMP Admin Bar compatibility
+    ✓ it has a functional Site Kit admin bar in AMP (8427ms)
+PASS tests/e2e/specs/auth/gcp-flow.test.js (9.122s)
+  Site Kit set up flow for the first time
+    ✓ authenticates from splash page (4114ms)
+    ✓ disconnects user from Site Kit (3308ms)
+PASS tests/e2e/specs/auth/gcp-flow-admin-2.test.js (9.794s)
+  the set up flow for the second administrator
+    ✓ connects a secondary admin after the initial set up (7580ms)
+PASS tests/e2e/specs/modules/analytics/admin-bar.test.js
+  Site Kit admin bar component display
+    ✓ loads Analytics data when the module is active (1369ms)
+PASS tests/e2e/specs/plugin-reset.test.js (6.237s)
+  Plugin Reset
+    ✓ displays a confirmation dialog when clicking the "Reset Site Kit" link (980ms)
+    ✓ dismisses the reset confirmation dialog when clicking "Cancel" (832ms)
+    ✓ disconnects Site Kit by clicking the "Reset" button in the confirmation dialog (1418ms)
+PASS tests/e2e/specs/modules/analytics/setup-no-account-with-tag.test.js (6.602s)
+  setting up the Analytics module with no existing account and with an existing tag
+    ✓ allows Analytics to be set up with an existing tag that does not match a property of the user (5141ms)
+PASS tests/e2e/specs/dashboard/surveys.test.js
+  dashboard surveys
+    ✓ shows a survey (1095ms)
+PASS tests/e2e/specs/dashboard/dashboard-noscript.test.js
+  dashboard noscript notice
     with Javascript enabled
-      ✓ Should not display noscript notice (488ms)
+      ✓ Should not display noscript notice (627ms)
     with Javascript disabled
-      ✓ should not display plugin html (104ms)
-      ✓ should display noscript notice (97ms)
+      ✓ should not display plugin html (164ms)
+      ✓ should display noscript notice (154ms)
 PASS tests/e2e/specs/module-activation.test.js
   Module activation
-    ✓ should prevent non active modules to be set up (1140ms)
-    ✓ should render an error message when an invalid module slug is used to setup the module (1100ms)
-PASS tests/e2e/specs/modules/adsense/amp-auto-ads-tag.test.js (5.917s)
+    ✓ should prevent non active modules to be set up (1659ms)
+    ✓ should render an error message when an invalid module slug is used to setup the module (1661ms)
+PASS tests/e2e/specs/modules/adsense/amp-auto-ads-tag.test.js (39.87s)
   AMP <amp-auto-ads> tag
-    ✓ is output in primary mode (790ms)
-    ✓ is output in secondary mode (994ms)
-    ✓ is not output in secondary mode in web context (1364ms)
-PASS tests/e2e/specs/modules/analytics/amp-validation.test.js (7.952s)
+    ✓ is output in primary mode (30805ms)
+    ✓ is output in secondary mode (1437ms)
+    ✓ is not output in secondary mode in web context (1795ms)
+PASS tests/e2e/specs/modules/analytics/amp-validation.test.js (74.014s)
   AMP homepage validates with Analytics enabled
-    ✓ validates for logged-in users (4818ms)
-    ✓ validates for non-logged-in users (1892ms)
-PASS tests/e2e/specs/amp/home-validation.test.js (5.698s)
+    ✓ validates for logged-in users (37707ms)
+    ✓ validates for non-logged-in users (34117ms)
+PASS tests/e2e/specs/amp/home-validation.test.js (39.945s)
   AMP Homepage
     Logged-in user
-      ✓ has no validation errors (2388ms)
+      ✓ has no validation errors (3839ms)
     Non-logged-in user
-      ✓ has no validation errors (386ms)
+      ✓ has no validation errors (794ms)
 PASS tests/e2e/specs/auth/flow-proxy.test.js
   Site Kit set up flow for the first time
-    ✓ renders a splash page for proxy set up when no GCP credentials are provided (735ms)
+    ✓ renders a splash page for proxy set up when no GCP credentials are provided (963ms)
 Test Suites: 30 passed, 30 total
 Tests:       93 passed, 93 total
 Snapshots:   0 total
-Time:        329.451s
+Time:        823.471s
 Ran all test suites.
\ No newline at end of file
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The cause for the large difference in time it takes for E2E to run between different WP versions for the same tests should be identified
    * If possible, the E2E tests should run within a much closer threshold.  
 i.e. If WP 4.7 takes 11 min, WP nightly might take 13 min, but not 20
* This task is primarily about identifying the cause
    * If time allows, a fix can be included as part of this, otherwise a new issue should be opened with next steps informed by the findings here

## Implementation Brief

* Create a Request Interceptor using `useRequestInterception()`
  * Add this to the [activateAMPWithMode](https://github.com/google/site-kit-wp/blob/6551b8be34d798cc2eeb5b03934e53fd5ec325e1/tests/e2e/utils/activate-amp-and-set-mode.js#L49-L55) functions, so the interceptor is active on every AMP setup.
  * Intercepts all requests with a `&amp_validate` query parameter.
  * Resolve all these request with a 200 response and an empty JSON body.
  * Remove the interceptor after AMP is setup using the function returned from `useRequestInterception()`

### Test Coverage

* 

## QA Brief

- Ensure the E2E tests that use the `activateAMPWithMode` function execution time has reduced compared to the prior changes in the test files.
- Check the E2E tests locally and on the GitHub CI for the above. Please refer the below screenshot for the differences:
![Screenshot 2023-01-19 at 2 06 12 PM](https://user-images.githubusercontent.com/24408261/213393605-ecf10509-de34-44d6-aae7-82cfbab488e8.png)

## Changelog entry

* N/A

**Comment by derweili** [comment] 2022-11-28 16:19
@aaemnnosttv @tofumatt could you double check if my assumptions are correct? Do you have an Idea `waitForFetchRequest()` gets stuck?

I will do some more research, tomorrow.

**Comment by derweili** [comment] 2022-11-29 09:56
I did some more research but did not find the cause for this issue.

Somehow the `activateAMPWithMode` takes very long. Because this function is called within `beforeEach()` which has a timeout set, this timeout is will eventually be reached and all tests continue after this timeout.

I tested the behaviour with this test:
`npm run test:e2e:interactive -- tests/e2e/specs/modules/optimize/activation.test.js`

Maybe someone with more knowledge about the AMP plugin setup can take a look at this.

Some other notes: I found out there is a puppeteer function `page.waitForNetworkIdle()` that basically does what our custom `waitForFetchRequests()` function implements. Maybe it's worth checking if there are advantages in using the Puppeteer function instead of our own.

**Comment by derweili** [comment] 2022-12-02 12:48
By logging all requests captured by `waitForFetchRequests()`, I found out AMP sends some verification requests to existing pages/posts/categories/authors:

- `http://localhost:9002/author/admin?amp=1&amp_validate%5Bcache%5D=true&amp_validate%5Bcache_bust%5D=0.6660455284987832&amp_validate%5Bnonce%5D=e72960b5b773c80113baca686fa8be60&amp_validate%5Bomit_stylesheets%5D=true`
- `http://localhost:9002/category/uncategorized?amp=1&amp_validate%5Bcache%5D=true&amp_validate%5Bcache_bust%5D=0.9093137241958527&amp_validate%5Bnonce%5D=e72960b5b773c80113baca686fa8be60&amp_validate%5Bomit_stylesheets%5D=true`
- `http://localhost:9002/sample-page?amp=1&amp_validate%5Bcache%5D=true&amp_validate%5Bcache_bust%5D=0.6057021260655233&amp_validate%5Bnonce%5D=e72960b5b773c80113baca686fa8be60&amp_validate%5Bomit_stylesheets%5D=true`
- `http://localhost:9002/hello-special-characters?amp=1&amp_validate%5Bcache%5D=true&amp_validate%5Bcache_bust%5D=0.07170241685322676&amp_validate%5Bnonce%5D=e72960b5b773c80113baca686fa8be60&amp_validate%5Bomit_stylesheets%5D=true`
- `http://localhost:9002/?amp=1&amp_validate%5Bcache%5D=true&amp_validate%5Bcache_bust%5D=0.22699842968952133&amp_validate%5Bnonce%5D=e72960b5b773c80113baca686fa8be60&amp_validate%5Bomit_stylesheets%5D=true`

All these requests fail and eventually hit a timeout.
There requests are not important for the AMP setup so we could skip/mock them.

**Comment by techanvil** [comment] 2022-12-02 13:11
Nice find there @derweili. I was taking a look at this yesterday to refresh my memory on the AMP plugin.

It looks like these requests are made due to the response of the call to `scannable-urls` that the AMP plugin makes, so it could be a bit more efficient/robust to mock the response of `scannable-urls` to return an empty array:

![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/dad25aad-9d80-4ccd-a980-de47dedaa650)

Full URL path: `/wp-json/amp/v1/scannable-urls?_fields[0]=url&_fields[1]=amp_url&_fields[2]=type&_fields[3]=label&_fields[4]=validation_errors&_fields[5]=stale&_locale=user`

Here's the related code in the plugin - https://github.com/ampproject/amp-wp/blob/203d057f746b2b23386c7ac66cab0fae13857722/assets/src/components/site-scan-context-provider/index.js#L461-L473

**Comment by derweili** [comment] 2022-12-02 14:09
@techanvil I double checked intercepting the `scannable-urls` REST endpoint, but this doesn't fix the error.
AMP makes use of `apiFetch.createPreloadingMiddleware` to preload the REST response. So before calling the REST-endpoint (maybe as a fallback) AMP already knows the urls to verify.

https://github.com/ampproject/amp-wp/blob/5fc17b69954468cb3e65b58f27d4c565fa546f41/src/Admin/RESTPreloader.php#L47-L58

So intercepting the `scannable-urls`

**Comment by techanvil** [comment] 2022-12-02 14:35
Ahh - thanks for taking a look @derweili, good hunting. Sounds like intercepting the individual requests is probably the best way to address this after all then.

**Comment by techanvil** [comment] 2022-12-06 13:02
Hi @derweili, the IB looks good, I just have a question about the last point:

> - Configure Jest to fail a tests when a the `beforeEach` or `beforeAll` timeout is hit, so that such errors are detected earlier in the future.

We have a rather deliberate-looking call to `jest.setTimeout` here, so we should probably tread carefully here. Maybe simply removing the point in question. What do you think?

https://github.com/google/site-kit-wp/blob/4104893789c1130de061d9cef69cd5eaacae796b/tests/e2e/config/bootstrap.js#L75-L76

**Comment by derweili** [comment] 2022-12-07 10:14
@techanvil makes sense, I created a followup issue.

**Comment by techanvil** [comment] 2022-12-07 21:59
Hey @derweili, I just noticed that you increased the estimate to 19, which seems a bit on the high side to me for this issue. Was this intentional?

**Comment by techanvil** [comment] 2022-12-07 21:59
Hey @derweili, I just noticed that you increased the estimate to 19, which seems a bit on the high side to me for this issue. Was this intentional?

**Comment by techanvil** [comment] 2022-12-07 22:00
Hey @derweili, I just noticed that you increased the estimate to 19, which seems a bit on the high side to me for this issue. Was this intentional?

**Comment by techanvil** [comment] 2022-12-08 11:47
@derweili the estimate should only be for the execution & review phases of the issue, it doesn't need to cover the time already spent on the IB etc. Also, it's only natural there will be overhead for ramping up on new areas especially as you've only recently started, so don't worry about spending more time on the IB than the estimate!

So, yes, as the execution should be pretty straightforward I think reducing the estimate would be in order here. I will leave it to you to provide a new value, but I would probably go with a 7 for this one, based on my understanding of it (and the fact it's an E2E issue which always have the potential to take a bit longer than might be expected).

**Comment by derweili** [comment] 2022-12-09 11:47
@techanvil got it. Changed the estimate to 7.

**Comment by techanvil** [comment] 2022-12-09 12:10
Thanks @derweili!

IB :white_check_mark:

**Comment by kuasha420** [comment] 2023-01-27 10:30
### QA:Eng :heavy_check_mark: 

* Checked and confirmed that E2E tests that are using activateAMPWithMode` are completing faster in both local and CI. 
* As a result, E2E tests on WP latest and nightly are finishing faster. 

LGTM.

**Closed** 2023-01-27 17:19 UTC
Labels: P1, QA: Eng, Type: Infrastructure
