### ISSUE TITLE
Release 1.50.0

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4714] opened 2022-01-25 09:38 UTC
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Release is prepared, tested, and deployed to wordpress.org.

## Implementation Brief

* N/A

## QA Brief

* N/A

## Changelog entry

* N/A

**Comment by wpdarren** [comment] 2022-01-27 16:03
### QA Update: ⚠️ 

I am seeing a few odd behaviours that I haven’t seen before.  I haven’t had chance to test if the same issues occur on 1.49.1.  I need to spend some time tomorrow checking if they are regressions. 

1.  This seems to be only consistent when you change the date period to 7 days and have zero data. As you can see from my screencast. I have a small amount of data of this site - I select 7 days, go through the pie chart tabs and when I click on the location tab, the date period is changed to 90 days. 

https://user-images.githubusercontent.com/73545194/151392369-4e077ec8-8b02-4120-a118-cc5a0d25d40c.mp4

2. This is inconsistent. On the All Traffic widget, when switch the date period and then navigating around the pie chart, an error appears.  As you can see in this screencast, it appears after switch the tabs. It could be a temporary API issue but with the service issues I wanted to highlight it. 

https://user-images.githubusercontent.com/73545194/151393040-0137ae7c-978d-445a-a28c-1db473165725.mp4

3. This is inconsistent. Go to the dashboard, scroll down to the Page Speed widget.  It loads, and then when you click on the desktop icon, it runs again. It only seems to appear when you navigate away from the dashboard and the go back. 

https://user-images.githubusercontent.com/73545194/151393068-88d62d6b-04e7-4fe7-8178-ed10033e09ac.mp4

I would be interested to know if anyone can recreate these issues.  I'll look and see if they are regressions in the morning.

c.c @felixarntz @aaemnnosttv @mohitwp

**Comment by aaemnnosttv** [comment] 2022-01-27 18:26
@wpdarren 

1. This looks like something I've seen once before (but not sure how to reproduce) where the menu is still open but invisible and you simply selected the item in the menu. I've managed to reproduce this in a screencast below, but I don't think it's a regression because I've seen it before. I'll open a new issue for this  

    https://user-images.githubusercontent.com/1621608/151420478-4c0c5954-b9e3-4de4-893f-c120d38897b2.mp4

2. The error is from the survey trigger endpoint which is known to take too long and times out after 15 sec (which is why you see the error). This is service related.
3. I'm not sure what's happening here; I wasn't able to reproduce it

**Comment by wpdarren** [comment] 2022-01-28 10:33
@aaemnnosttv thank you for going through these. 

> 2. The error is from the survey trigger endpoint which is known to take too long and times out after 15 sec (which is why you see the error). This is service related. 

Just noting that this is the first time I have noticed this. Is it something we need to report to Felix/Adam? 

> 1.. This looks like something I've seen once before (but not sure how to reproduce) where the menu is still open but invisible and you simply selected the item in the menu. I've managed to reproduce this in a screencast below, but I don't think it's a regression because I've seen it before. I'll open a new issue for this

Thank you! 

> 3. I'm not sure what's happening here; I wasn't able to reproduce it

I'll have another look at this today to see if I can reproduce the issue, and see if it happens on 1.49.1

**Comment by wpdarren** [comment] 2022-01-28 11:44
### QA Update: ✅ 

I have completed release QA with our checklist.  A few notes.

> 3. This is inconsistent but has happened a few times. Go to the dashboard, scroll down to the Page Speed widget. It loads, and then when you click on the desktop icon, it runs again. It only seems to appear when you navigate away from the dashboard and the go back.

I've not been able to reproduce this today, which is always frustrating but will keep a look out for it. 

Other than the issues reported above, there are some non regression issues specific to a site with low data. I'll investigate these further and create tickets.  

We've not been able to test Idea Hub during 1.50.0 testing because oi.ie has been removed from the API.  This has been reported this to the appropriate team. I understand that we might also have a quota issue for Idea Hub. I tried connecting with elasticpress.io but do not have permissions.  When I do, I will run through the testing on this.

**Comment by mohitwp** [comment] 2022-01-28 12:03
### QA Update: ✅
I have completed release QA with our checklist.

**Comment by tofumatt** [comment] 2022-02-01 18:24
QA ✅ 

Smoke testing looks good to me. 👍🏻

**Comment by jimmymadon** [comment] 2022-02-02 00:06
✅  Went through the issues I was involved with, including 4682 and they LGTM.
✅  Smoke Testing on current dashboard. LGTM.

Smoke testing on Unified Dashboard:
Besides #4741 which is set to be fixed in the next release 1.68.0, I noticed two issues on the Unified Dashboard. Both of them will (or should?) be resolved in #4641 - just mentioning these here for now so we can test once #4641 is resolved.
1. When PSI is loading, clicking on `Monetization` does not change the selected chip to `Monetization`. `Traffic` remains as the selected chip.
2. On large screens (viewport height approx. > 1400px), clicking on `Monetization` does not change the selected chip to `Monetization`. `Traffic` remains as the selected chip.
https://user-images.githubusercontent.com/1721319/152069887-50286ce8-eb96-444d-916a-5ada09a88c48.mov

**Comment by aaemnnosttv** [comment] 2022-02-02 08:28
> 1. When PSI is loading, clicking on `Monetization` does not change the selected chip to `Monetization`. `Traffic` remains as the selected chip.

@jimmymadon I wasn't able to reproduce this. Would you please double check, perhaps on a fresh site?

**Closed** 2022-02-02 18:28 UTC
Labels: P0, Type: Task
