### ISSUE TITLE
Remove legacy PHP-to-JS context/routing variables in favor of data attributes

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3647] opened 2021-06-29 17:14 UTC
With the legacy JS architecture removed, certain variables that are passed from PHP to JS should be replaced with data attributes instead (partly a follow-up to #2653). Variables to no longer pass from PHP to JS are e.g.:
* `global.googlesitekitCurrentModule`
* `global._googlesitekitLegacyData.showModuleSetupWizard`
* `global._googlesitekitLegacyData.moduleToSetup`

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `#js-googlesitekit-module` container (see `Module_With_Screen_Trait` trait) should from the server-side receive a `data-module-slug` attribute with the current module's slug.
* Both the `#js-googlesitekit-dashboard` container (see `Screens` class) and the `#js-googlesitekit-module` container (see `Module_With_Screen_Trait` trait) should behave as follows: If the `reAuth` query parameter is set/non-empty and there is also a non-empty `slug` query parameter, the container should from the server-side receive a `data-setup-module-slug` attribute with the module slug from the `slug` query parameter.
* On the client-side, the `googlesitekit-dashboard.js` and `googlesitekit-module.js` files should be modified to check for the above data on the render targets and pass them as props to the React components as provided.
    * `moduleSlug` prop for `data-module-slug`
    * `setupModuleSlug` prop for `data-setup-module-slug`
    * The components should rely on those prop values to render accordingly, i.e.:
        * In `googlesitekit-module.js`, rely on `moduleSlug` prop instead of `googlesitekitCurrentModule` global.
        * In `googlesitekit-dashboard.js` and `googlesitekit-module.js`, rely on `setupModuleSlug` prop (and whether it's not empty) instead of `_googlesitekitLegacyData.setup.showModuleSetupWizard` and `_googlesitekitLegacyData.setup.moduleToSetup` global.
* The `googlesitekitCurrentModule`, `_googlesitekitLegacyData.setup.showModuleSetupWizard`, and `_googlesitekitLegacyData.setup.moduleToSetup` global variables should be entirely removed in favor of the new data attribute & prop-based system - also where they're set on the server-side.
    * They should also be removed in Storybook, where it looks like they're already without a purpose there actually.
* Support for the practically unused `editmodule` query parameter and the related `_googlesitekitLegacyData.editmodule` global should be entirely removed.

## Implementation Brief

* Remove the global variable `googlesitekitCurrentModule` in https://github.com/google/site-kit-wp/blob/5e17a1df7657ae41541a2c7ff04f8dae0d4cf84d/includes/Core/Modules/Module_With_Screen_Trait.php#L74-L75, and output `data-module-slug="<?php echo wp_json_encode( $module_info[ 'slug' ] ); ?>"` as part of the `#js-googlesitekit-module` div.
* For `#js-googlesitekit-dashboard` (`Screens`) and the `#js-googlesitekit-module` (`Module_With_Screen_Trait`) should add a `data-setup-module-slug="$slug_from_query_param"` attribute if all of the following is true:
  * the `reAuth` query parameter is set/non-empty
  * there is a non-empty `slug` query parameter
* On the client-side, the `googlesitekit-dashboard.js` and `googlesitekit-module.js` files should be modified to check for the above data on the render targets and pass them as props to the React components as provided.
    * `moduleSlug` prop for `data-module-slug`
    * `setupModuleSlug` prop for `data-setup-module-slug`
    * The components should rely on those prop values to render accordingly, i.e.:
        * In `googlesitekit-module.js`, rely on `moduleSlug` prop instead of `googlesitekitCurrentModule` global.
        * In `googlesitekit-dashboard.js` and `googlesitekit-module.js`, rely on `setupModuleSlug` prop (and whether it's not empty) instead of `_googlesitekitLegacyData.setup.showModuleSetupWizard` and `_googlesitekitLegacyData.setup.moduleToSetup` global.
* The `googlesitekitCurrentModule`, `_googlesitekitLegacyData.setup.showModuleSetupWizard`, and `_googlesitekitLegacyData.setup.moduleToSetup` global variables should be removed on the client.
    * They should also be removed in Storybook, where it looks like they're already without a purpose there actually.
    * They should be removed from PHP, here: https://github.com/google/site-kit-wp/blob/5e17a1df7657ae41541a2c7ff04f8dae0d4cf84d/includes/Core/Authentication/Authentication.php#L791-L793
* Remove the `editmodule` variable + query parameter should be removed https://github.com/google/site-kit-wp/blob/5e17a1df7657ae41541a2c7ff04f8dae0d4cf84d/includes/Core/Assets/Assets.php#L851. Remove the related `_googlesitekitLegacyData.editmodule` global usage from https://github.com/google/site-kit-wp/blob/5e17a1df7657ae41541a2c7ff04f8dae0d4cf84d/assets/js/components/settings/SettingsModules.js#L40-L46

### Test Coverage

* All tests should pass, but no new tests are needed.

### Visual Regression Changes

* N/A

## QA Brief

Ensure ACs met.
On the following page: `/wp-admin/admin.php?page=googlesitekit-module-analytics&slug=analytics&reAuth=true`

These variables shouldn't exist:
```
window.googlesitekitCurrentModule
window._googlesitekitLegacyData.setup.showModuleSetupWizard
window._googlesitekitLegacyData.setup.moduleToSetup
```

## Changelog entry

* N/A

**Comment by tofumatt** [comment] 2021-07-29 12:39
I'm proposing a solution where we use data attributes for everything, as requested in the ACs.

But it looks like, in one spot, we can get data right from query params rather than reading query params on the server side, then setting a data attribute on the client:

https://github.com/google/site-kit-wp/blob/5e17a1df7657ae41541a2c7ff04f8dae0d4cf84d/assets/js/googlesitekit-module.js#L34-L59

Performing the `reAuth` and `slug` query param check here, then loading the appropriate module, would be straightforward to do in JS. It seems like `ModuleApp` would even play well with unknown module slugs—though that would only happen if a user changed to an invalid URL.

We could simplify the logic for that component by using `window.location` query params directly. But I suppose we need the `dataAPIModuleArgs` anyway, so maybe it's not worth it 🤷🏻‍♂️

**Comment by felixarntz** [comment] 2021-07-29 17:24
@tofumatt IB mostly lgtm, just one thing: `data-module-slug` should not be set to `$module_info`, it should only have the module's slug.

Regarding your point of the query parameters, I was considering that, but I think relying on data attributes is a better approach since it decouples our React apps from certain URLs. I think eventually (not necessarily this issue though) we should also update `googlesitekit-dashboard-details.js` to not rely on the `permaLink` query parameter, but rather a data attribute on the render target - _that_ can on the server-side still depend on the query parameter, but I think it's a good idea to decouple the client.

**Comment by tofumatt** [comment] 2021-08-02 16:15
Ah, yes, good catch—that was just a mistake, I meant to add the `['slug']` key but missed it; should be good now.

**Comment by tofumatt** [comment] 2021-08-02 16:16
Again: leaving unassigned in the interest of time, but Felix said it was good aside from changing `data-module-slug="<?php echo wp_json_encode( $module_info ); ?>"` to `data-module-slug="<?php echo wp_json_encode( $module_info[ 'slug' ] ); ?>"` 🙂

**Comment by eugene-manuilov** [comment] 2021-08-03 13:18
> Again: leaving unassigned in the interest of time, but Felix said it was good aside from changing `data-module-slug="<?php echo wp_json_encode( $module_info ); ?>"` to `data-module-slug="<?php echo wp_json_encode( $module_info[ 'slug' ] ); ?>"`

IB :heavy_check_mark:

**Comment by ivankruchkoff** [comment] 2021-08-04 08:58
This makes sense:
> and output data-module-slug="<?php echo wp_json_encode( $module_info[ 'slug' ] ); ?>" as part of the #js-googlesitekit-module div.

This is a duplicate of the above.
> For ... the #js-googlesitekit-module (Module_With_Screen_Trait) should add a data-setup-module-slug="$slug_from_query_param" attribute if all of the following is true:
> the reAuth query parameter is set/non-empty
> there is a non-empty slug query parameter

**Comment by johnPhillips** [comment] 2021-08-13 10:43
### QA ❓

The following were all verified and looking really good, I just had one question (at the bottom).

- On the module pages, the `#js-googlesitekit-module` container with`data-module-slug` data attribute is all present and correct.

- When the `reAuth` query parameter is set/non-empty and there is also a non-empty `slug` query parameter, both `js-googlesitekit-dashboard` and `#js-googlesitekit-module`  containers have a `data-setup-module-slug` attribute with the module slug from the `slug` query parameter.

- Looks like `googlesitekit-dashboard.js` and `googlesitekit-module.js` are correctly passing the parameters as per AC.

- The globals listed in the QAB were not present on `/wp-admin/admin.php?page=googlesitekit-module-analytics&slug=analytics&reAuth=true`

- Searched codebase for the  `googlesitekitCurrentModule`, `_googlesitekitLegacyData.setup.showModuleSetupWizard` globals and the `editmodule` query parameter / `_googlesitekitLegacyData.editmodule` global and found none.
___

❗️ However, the `_googlesitekitLegacyData.setup.moduleToSetup` global was present in the following files:
```
stories/module-optimize-setup.stories.js
48:	global._googlesitekitLegacyData.setup.moduleToSetup = 'optimize';

stories/module-adsense-setup.stories.js
66:	global._googlesitekitLegacyData.setup.moduleToSetup = 'adsense';

stories/module-analytics-setup.stories.js
58:			global._googlesitekitLegacyData.setup.moduleToSetup = 'analytics';
65:	global._googlesitekitLegacyData.setup.moduleToSetup = 'analytics';

stories/modules-tagmanager-setup.stories.js
63:	global._googlesitekitLegacyData.setup.moduleToSetup = 'tagmanager';
```

Looking at the AC, this appears to be a requirement.  @ivankruchkoff can you advise?

**Comment by ivankruchkoff** [comment] 2021-08-16 05:36
@johnPhillips valid find and great catch.

I've put out a subsequent PR and searched through stories and the rest of the codebase for those variables.
https://github.com/google/site-kit-wp/pull/3873

Putting this back in CR and can then go back through to QA.

**Comment by aaemnnosttv** [comment] 2021-08-17 17:31
Thanks @ivankruchkoff – back to you for another pass @johnPhillips 👍

**Comment by johnPhillips** [comment] 2021-08-18 10:56
QA ✅

Can't find any references to `_googlesitekitLegacyData.setup.moduleToSetup` in the codebase now.

Nice work @ivankruchkoff 👍

**Closed** 2021-08-30 19:23 UTC
Labels: P1, QA: Eng, Rollover, Type: Infrastructure
