### ISSUE TITLE
UFD> If any banner is showing then navigation tour focus is not correct.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#5990] opened 2022-10-10 14:18 UTC
## Bug Description

If any banner is showing (Zero data state banner) then focus is not correct for navigation tour. After refresh focus get correct but initially it is wrong.

## Steps to reproduce

1. Set Up fresh Site kit set up.
2.  Set older version of plugin from tester plugin to show chip navigation tour.
3.  Go to dashboard.
4. See issue.

## Screenshots

![image](https://user-images.githubusercontent.com/94359491/194887214-5281769f-ac44-4bf2-a7c3-05c076486119.png)

## Additional Context

 - Plugin Version: [1.48,0]
 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2022-12-16 19:11
Duplicate of #5701

**Closed by aaemnnosttv** 2022-12-16 19:11 UTC
Labels: Type: Bug
