### ISSUE TITLE
Cannot redeclare GuzzleHttp\Psr7\_caseless_remove()

### ISSUE THREAD

**Issue by Samsonator** [google/site-kit-wp#349] opened 2019-07-30 10:19 UTC
## Bug Description

Attempting to activate SiteKit on a WordPress install that already has an active plugin that loads GuzzleHttp causes a fatal error as it can't be redeclared. 

## Steps to reproduce

Install and Activate any plugin that loads GuzzleHttp (in my case it was https://github.com/humanmade/S3-Uploads but I believe this would affect any plugin making use of the AWS SDK). 

Then attempt to activate SiteKit.

## Additional Context

 - PHP Version: 7.3.2
 - Plugin Version: 1.0.0-beta.1.0.2

I came across this other GitHub issue that seems related - https://github.com/aws/aws-sdk-php/issues/1616. 
They suggest to load functions_include.php instead of functions.php to resolve the issue. Not sure how relevant that is here but hope it helps.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment] 2019-07-31 10:36
Related: #223

**Comment by swissspidy** [comment] 2019-09-05 14:21
Closing as a duplicate of #223 where we're already tracking this. See also #246, #41.

**Closed by swissspidy** 2019-09-05 14:21 UTC
Labels: Type: Support
