### ISSUE TITLE
Migrate Analytics All Traffic dashboard widget to use Widgets API

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1896] opened 2020-08-11 01:41 UTC
The current Analytics `AnalyticsAllTraffic` widget should be migrated to use the Widgets API (which is behind a feature flag), while maintaining the current version as legacy components. Those will be removed only once all widgets have been migrated so that we can do the entire switch.

Some general practices for migrating:
* The migration should happen by fully **re-implementing** the components: In other words, the existing components should keep their current functionality, they should **not** use the datastore. Those legacy components should be prefixed with `Legacy*`.
* A good starting point is probably to copy the components into new files and go from there, while renaming the old ones and leaving them untouched.
* For the refactored version, _only_ the actual widget components should be fully responsible for retrieving data from the datastore. If they rely on further `common` components for UI, these should receive such data via props.
* If there are UI parts that can be reused between the new and legacy components, those can be outsourced into `common` components, however as mentioned above **it is important that the legacy components keep using the legacy data API and are not switched to the datastore**. Only the new ones should be.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The [`AnalyticsAllTraffic`](https://github.com/google/site-kit-wp/blob/1.13.1/assets/js/modules/analytics/components/dashboard/AnalyticsAllTraffic.js) component, and its suplementary [`DashboardAcquisitionPieChart`](https://github.com/google/site-kit-wp/blob/1.13.1/assets/js/modules/analytics/components/dashboard/DashboardAcquisitionPieChart.js) and [`AnalyticsAllTrafficDashboardWidgetTopAcquisitionSources`](https://github.com/google/site-kit-wp/blob/1.13.1/assets/js/modules/analytics/components/dashboard/AnalyticsAllTrafficDashboardWidgetTopAcquisitionSources.js) components should be migrated to functional components using the datastore entirely, no globals and no legacy data API.
* Refactoring map:
    * `dashboard/AnalyticsAllTraffic.js` should become `dashboard/DashboardAllTrafficWidget.js` (refactored) and `dashboard/LegacyAnalyticsAllTraffic.js` (legacy). The refactored component should access the datastore for the main API data.
    * `dashboard/DashboardAcquisitionPieChart.js` should become `common/AcquisitionPieChart.js` (refactored) and `dashboard/LegacyDashboardAcquisitionPieChart.js` (legacy). The refactored component should receive its relevant data via props.
    * `dashboard/AnalyticsAllTrafficDashboardWidgetTopAcquisitionSources.js` should become `common/AcquisitionSources.js` (refactored) and `dashboard/LegacyAnalyticsAllTrafficDashboardWidgetTopAcquisitionSources.js` (legacy). The refactored component should receive its relevant data via props.
* The new `DashboardAllTrafficWidget` should return `null` if the Analytics module is not active. _Only_ otherwise Analytics data should be requested, i.e. this probably needs to go into a separate component `DashboardAllTraffic`, since hooks cannot run conditionally (we use `*Widget` as top-level entry point while the un-suffixed version is essentially the main part of it, without any extra checks for active modules etc.).
* The new `DashboardAllTraffic` component should rely on `select( CORE_SITE ).getCurrentReferenceURL()` so that it uses the site URL vs the current entity URL as applicable (the latter e.g. when used in the `pageDashboard` context).
* The new `DashboardAllTrafficWidget` component should be registered as a widget with priority 1, width `Widgets.WIDGET_WIDTHS.FULL`, and for the two widget areas `AREA_DASHBOARD_ALL_TRAFFIC` and `AREA_PAGE_DASHBOARD_ALL_TRAFFIC`.

#### Stage 1
* Rename the following files and components accordingly:
  * `assets/js/modules/analytics/dashboard/AnalyticsAllTraffic.js` -> `assets/js/modules/analytics/dashboard/LegacyAnalyticsAllTraffic.js`
  * `assets/js/modules/analytics/dashboard/DashboardAcquisitionPieChart.js` -> `assets/js/modules/analytics/dashboard/LegacyDashboardAcquisitionPieChart.js`
  * `assets/js/modules/analytics/dashboard/AnalyticsAllTrafficDashboardWidgetTopAcquisitionSources.js` -> `assets/js/modules/analytics/dashboard/LegacyAnalyticsAllTrafficDashboardWidgetTopAcquisitionSources.js`
* Update:
  * `index.legacy.js` file to use `LegacyAnalyticsAllTraffic` instead of `AnalyticsAllTraffic`;
  * `LegacyAnalyticsAllTraffic` component to use `LegacyDashboardAcquisitionPieChart` instead of `DashboardAcquisitionPieChart` and `LegacyAnalyticsAllTrafficDashboardWidgetTopAcquisitionSources` instead of `AnalyticsAllTrafficDashboardWidgetTopAcquisitionSources`;
  * `stories/dashboard.stores.js` file to use `LegacyDashboardAcquisitionPieChart` and `LegacyAnalyticsAllTrafficDashboardWidgetTopAcquisitionSources` imported from the appropriate legacy files.

#### Stage 2
* Create `assets/js/utils/when-active.js` file with a `whenActive` HOC that accepts options object and returns enhancing function;
* Options object should expect two properties: module name and optional fallback component (by default `null`) to display when selected module is not active. 
* The enhancing function should do the following:
  * Accept a component to wrap;
  * Define a new functional component which:
    * Uses `useSelect` hook and `getModule` selector of the modules datastore to get selected module info;
    * Returns fallback component (if provided) or null if selected module is not active;
    * Renders and returns the wrapped component passing unrelated properties through to the wrapped comonent.
  * Set `displayName` for the new component to be `When{ModuleName}Active` where `{ModuleName}` is the module name passed to the HOC function in PascalCase format.
    * If the wrapped component has `displayName` or `name` static properties, append enhancing function component's `displayName` with `({ComponentName})` where `{ComponentName}` is either `displayName` or `name` of the wrapped component (as an example, it could be: `WhenAnalyticsActive(AllTrafficWidget)`).
  * Return the new component.

#### Stage 3
* Create the following files:
  * `assets/js/modules/analytics/dashboard/DashboardAllTrafficWidget.js`
  * `assets/js/modules/analytics/common/AcquisitionPieChart.js`
  * `assets/js/modules/analytics/common/AcquisitionSources.js`
* `DashboardAllTrafficWidget.js` should:
  * Import `trafficSourcesReportDataDefaults` from the `assets/js/modules/analytics/utils/index.js` file.
  * Define `DashboardAllTrafficWidget` functional component:
    * Use `useSelect` hook and the following selectors to pull data required for the widget:
      * `getCurrentReferenceURL` selector from the `core/site` datastore to retrieve the current reference URL;
      * `getDateRange` selector from the `core/user` datastore to retrieve the current date range;
      * `getReport` selector from the `analytics` datastore to retrieve report data. 
    * Use `trafficSourcesReportDataDefaults`, current reference URL and date range information to compose options object and pass it into the `getReport` selector.
    * Render and return `AcquisitionPieChart` and `AcquisitionSources` components wrapped with `Widget` component that has `analyticsAllTraffic` slug and `googlesitekit-widget--no-padding` class.
      * Pass selected report data to the pie chart and sources components via `data` property.
  * Export enhanced version of the `DashboardAllTrafficWidget` component by wrapping it with the `whenActive` HOC (using `analytics` as module name).
* `AcquisitionPieChart.js` should define and export a functional component that replicates the logic defined in the `LegacyDashboardAcquisitionPieChart` component to render a pie chart using data provided via `data` property.
* `AcquisitionSources.js` should define and export a functional component that replicates the logic defined int the `LegacyAnalyticsAllTrafficDashboardWidgetTopAcquisitionSources` comonent to render acquisition sources table using data provided via `data` property.

#### Stage 4
* Update `assets/js/googlesitekit/widgets/register-defaults.js` file to use `WIDGET_AREA_STYLES.BOXES` style for `AREA_DASHBOARD_ALL_TRAFFIC` and `AREA_PAGE_DASHBOARD_ALL_TRAFFIC` areas.
* Update `assets/js/modules/analytics/index.js` file:
  * Import `domReady` from `@wordpress/dom-ready` and `Widgets` from `googlesitekit-widgets`;
  * Call `domReady` with a callback function that registers a new widget using `Widgets.registerWidget` function and passing the following arguments:
    * A string `analyticsAllTraffic` as widget slug;
    * Settings object where:
      * `component` is `DashboardAllTrafficWidget`;
      * `width` is `Widgets.WIDGET_WIDTHS.FULL`;
      * `priority` is `1`;
      * `wrapWidget` is `false`.
    * Areas array that includes `AREA_DASHBOARD_ALL_TRAFFIC` and `AREA_PAGE_DASHBOARD_ALL_TRAFFIC` imported from `googlesitekit/widgets/default-areas`.

#### Scenario 1 - analytics module is not active:
* Disconnect analytics module;
* Go to the dashboard page and make sure that you don't see All Traffic widget there;
* Go to the page dashboard and make sure that you don't see All Traffic widget there too.

#### Scenario 2 - analytics module is active but not connected:
* Activate analytics module but not configure it;
* Go to the dashboard page and make sure that you don't see All Traffic widget there;
* Go to the page dashboard and make sure that you don't see All Traffic widget there too.

#### Scenario 3 - analytics module is active and connected:
* Configure analytics module;
* Go to the dashboard page, make sure that you see All Traffic widget there and it has the same values which the legacy widget has;
* Go to the page dashboard page, make sure that you see All Traffic widget there and it has the same values which the legacy widget has.

## Changelog entry

* Migrate Analytics All Traffic widget to new Widget API.

**Comment by felixarntz** [comment] 2020-08-11 14:58
@eugene-manuilov IB looks great, I really like the approach of separating into different stages, which makes it a lot easier to understand 👍 

> If the wrapped component has `displayName` or `name` static property, append enhancing function's `displayName` with `({ComponentName})` where `{ComponentName}` is either `displayName` or `name` of the wrapped component.

Can you clarify this bit? I don't think I understand what's the purpose of this. What is `displayName` used for overall?

> Render and return `AcquisitionPieChart` and `AcquisitionSources` components wrapped with `Widget` component that has `analyticsAllTraffic` slug and `googlesitekit-widget--no-padding` class.

At the moment, the `googlesitekit-widget--no-padding` class only works on widgets which are in a regular `boxes` style widget area. We could add CSS rules to make it work for `composite` widget area widgets too, but that may end up a bit hacky because the "padding" in those actual comes from the widget area's grid, so we'd probably need to use negative margins etc. A more straightforward solution here would be to modify the two `*AllTraffic` widget area registrations to use the regular `boxes` style. I originally thought we'd use `composite` and then have the two columns as individual widgets, but since they're referring to the same data, I now think it makes more sense as a single widget with two columns, at which point the widget area also works with `boxes` style.

**Comment by eugene-manuilov** [comment] 2020-08-11 15:28
> Can you clarify this bit? I don't think I understand what's the purpose of this. What is displayName used for overall?

@felixarntz it's intended for debugging and a kind of "best practices" for HOC. Check [Convention: Wrap the Display Name for Easy Debugging](https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging) section in the React documentation for more details.

> At the moment, the googlesitekit-widget--no-padding class only works on widgets which are in a regular boxes style widget area. We could add CSS rules to make it work for composite widget area widgets too, but that may end up a bit hacky because the "padding" in those actual comes from the widget area's grid, so we'd probably need to use negative margins etc. A more straightforward solution here would be to modify the two *AllTraffic widget area registrations to use the regular boxes style. I originally thought we'd use composite and then have the two columns as individual widgets, but since they're referring to the same data, I now think it makes more sense as a single widget with two columns, at which point the widget area also works with boxes style.

So, what do we need to do then? Remove the class or adjust widget areas?

**Comment by felixarntz** [comment] 2020-08-11 16:05
@eugene-manuilov 
> > Can you clarify this bit? I don't think I understand what's the purpose of this. What is displayName used for overall?
> 
> @felixarntz it's intended for debugging and a kind of "best practices" for HOC. Check [Convention: Wrap the Display Name for Easy Debugging](https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging) section in the React documentation for more details.

Thanks, makes sense, I wasn't aware of this ability.

> > At the moment, the googlesitekit-widget--no-padding class only works on widgets which are in a regular boxes style widget area. We could add CSS rules to make it work for composite widget area widgets too, but that may end up a bit hacky because the "padding" in those actual comes from the widget area's grid, so we'd probably need to use negative margins etc. A more straightforward solution here would be to modify the two *AllTraffic widget area registrations to use the regular boxes style. I originally thought we'd use composite and then have the two columns as individual widgets, but since they're referring to the same data, I now think it makes more sense as a single widget with two columns, at which point the widget area also works with boxes style.
> 
> So, what do we need to do then? Remove the class or adjust widget areas?

Let's alter the two `*AllTraffic` widget areas to use `boxes` style.

**Comment by eugene-manuilov** [comment] 2020-08-11 16:12
@felixarntz updated.

**Comment by felixarntz** [comment] 2020-08-11 16:40
IB ✅

**Comment by tofumatt** [comment] 2020-08-26 17:52
Code is reviewed and approved, but assigning to Felix or Evan to merge 🙂

**Comment by aaemnnosttv** [comment] 2020-08-26 18:11
Almost! Just a few things left to address. Moving back to Execution, but hopefully should be quick.

**Comment by aaemnnosttv** [comment] 2020-08-26 18:11
Also – @eugene-manuilov this needs a QA Brief before the issue can move to QA 😄

**Comment by eugene-manuilov** [comment] 2020-08-26 19:18
QA Brief is added.

**Comment by cole10up** [comment] 2020-09-09 04:44
**Tested**

With a development build I activated SK and checked Analytics widget (Scenario 1)
![image](https://user-images.githubusercontent.com/57115907/92554807-0f1fc300-f21b-11ea-8624-6113127328a0.png)

Analytics module is active but not setup (Scenario 2)
![image](https://user-images.githubusercontent.com/57115907/92555055-adac2400-f21b-11ea-87e9-7914f85d2844.png)

![image](https://user-images.githubusercontent.com/57115907/92555069-b4d33200-f21b-11ea-9c51-a560063a75f3.png)

Analytics active and setup (Scenario 3)
![image](https://user-images.githubusercontent.com/57115907/92555147-e1874980-f21b-11ea-9500-5b1043761e3f.png)

![image](https://user-images.githubusercontent.com/57115907/92555179-eea43880-f21b-11ea-9858-eb7f56535b61.png)

Adjusted duration:
![image](https://user-images.githubusercontent.com/57115907/92555245-10052480-f21c-11ea-8b26-c627fde7d293.png)

![image](https://user-images.githubusercontent.com/57115907/92555260-1bf0e680-f21c-11ea-86b9-c76d5b6dcf35.png)

Confirmed release build functions properly:
![image](https://user-images.githubusercontent.com/57115907/92555377-607c8200-f21c-11ea-8599-aef1b890a267.png)

Passed QA ✅

**Comment by felixarntz** [comment] 2020-09-09 17:19
@cole10up Similar to #1897, did you cover the single URL details page as well for the new All Traffic widget?

**Closed** 2020-09-10 01:17 UTC
Labels: P0, Type: Enhancement
