### ISSUE TITLE
Ga4 feature tour focus on session and engagement is not align correctly.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#7030] opened 2023-05-12 11:26 UTC
## Bug Description

Under Ga4 feature focus on session and engagement is not properly aligned.

## Steps to reproduce

1. Create new analytics a/c. 
2. Enable 'ga4Reporting' feature flag.
3. Click on 'Update' button under banner on main dashboard, which will trigger ga4 widgets feature tour.
4. See focus on session and engagement. 

## Screenshots

![image](https://github.com/google/site-kit-wp/assets/94359491/3edfe89a-6b99-49f8-bfcd-7d571eced6b1)

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment] 2023-05-12 13:20
Hey @mohitwp, this is a duplicate of https://github.com/google/site-kit-wp/issues/6973.

**Comment by techanvil** [comment] 2023-05-12 13:21
Closing as this is a duplicate of #6973.

**Closed by techanvil** 2023-05-12 13:21 UTC
Labels: Type: Enhancement
