### ISSUE TITLE
Sitekit blocks Updraft Plus plugin from backing up to Google Drive

### ISSUE THREAD

**Issue by FinOp** [google/site-kit-wp#647] opened 2019-10-13 02:59 UTC
## Bug Description

Sitekit blocks Updraft Plus WP plugin from backing up to Google Drive

## Steps to reproduce

1. Updraft Plus plugin free version installed and activated (prior to installing Sitekit was operating correctly)
2. Sitekit downloaded and activated
3. subsequently both scheduled and manual backup attempts failed
4. See error as it appears in the log
0138.434 (0) Beginning dispatch of backup to remote (googledrive) (instance identifier s-87457d8bd3cbe15cf766e35992379a77)
0138.475 (0) PHP Fatal error (TypeError) has occurred during backup uploads to the googledrive. Error Message: Argument 1 passed to Google_Client::__construct() must be of the type array, object given, called in /home/finan135/public_html/wp-content/plugins/updraftplus/methods/googledrive.php on line 825 (Code: 0, line 92 in /home/finan135/public_html/wp-content/plugins/google-site-kit/vendor/google/apiclient/src/Google/Client.php)
0138.477 (0) An error condition has occurred for the first time during this job
0138.477 (0) Resume backup (6e65b8daf9d6, 0): finish run
0138.479 (0) Decremented the semaphore (fd) by 1
0138.481 (0) Semaphore (fd) unlocked
0138.482 (0) There were errors in the uploads, so the 'resume' event is remaining scheduled
0138.484 (0) Rescheduling resumption 1: moving to 100 seconds from now (1570751635)
0138.486 (0) The backup has not finished; a resumption is scheduled.

Updraft attempted download nine(9) times all failed on multiple days

SiteKit de-activated, backup completes successfully
Sitekit re-activated, backup attempts fail. Backups will only complete successfully when SiteKit not activated.
## Additional Context

 - PHP Version: 5.3
 - OS: [e.g. iOS] Google Drive via GSuite
 - Browser Chrome
 - Plugin Version Updraft Plus V. 1.16.17
 - Device: Windows 10 laptop

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment] 2019-10-14 06:43
@FinOp We have an open issue (#612) which should resolve this issue when fixed. You can find more information in that open issue.

**Comment by swissspidy** [comment] 2019-10-14 11:08
Closing as a duplicate of #612.

**Closed by swissspidy** 2019-10-14 11:08 UTC
Labels: Type: Support
