### ISSUE TITLE
Release 1.83.0

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5799] opened 2022-09-06 13:47 UTC
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Release is prepared, tested, and deployed to wordpress.org.

## Implementation Brief

* N/A

## QA Brief

* N/A

## Changelog entry

* N/A

**Comment by wpdarren** [comment] 2022-09-09 02:53
### QA Update: ✅ 

- Completed testing on 1.83.0:
- Went through sites with zero, gathering data and live data. 
  - Went through QA checklist and found a few non regressions that I'll create tickets for. 
  - Didn't complete any QA on TwG, Dashboard Sharing or GA4 as they are behind feature flag and will be tested separately when required. 
  - Ran some additional checks on zero and gathering data states due to the removal of the feature flag.
  - Ran through some additional checks on internal and external links due to #5410 where it was highlighted that changes had been made to links.

**Comment by tofumatt** [comment] 2022-09-09 15:02
QA ✅ from me.

Didn't focus on Dashboard Sharing or other features behind a flag.

Zero data states looked good on new sites. External links look good too. Aside from that mostly standard smoke testing and all seems good 👍🏻

**Comment by nfmohit** [comment] 2022-09-10 10:56
## Release Tested ✅

- Release tested 1.83.0 thoroughly.
- Set everything up from scratch on a live (InstaWP) site.
- Didn't spot any unexpected console errors.
- Verified changes I've been involved with.

**Comment by jimmymadon** [comment] 2022-09-10 14:22
QA ✅ 

- Went through the handbook checklist and also smoke tested features I was involved (DS and GA4 activation banner) which are behind a feature flag but merged in.

**Comment by kuasha420** [comment] 2022-09-11 19:57
QA: :heavy_check_mark: 

* Went through the release testing on a new site (no data) and an old site and didn't see any issues in UI or console. 
* Did some brief smoke testing. 

LGTM.

**Comment by makiost** [comment] 2022-09-11 20:45
## QA ✅ 

* Went through own changes
* Smoke tested the app
* Checked for any apparent console or UI errors

**Comment by mohitwp** [comment] 2022-09-12 05:40
### QA Update ✅ 

- Went through QA Check list
- Zero Data state related scenarios.
- Verified changes under settings view.
- Not tested Dashboard Sharing, TwG and GA4 related scenarios.

**Comment by hussain-t** [comment] 2022-09-12 05:58
## QA Verified :white_check_mark:
- Smoke tested.
- Verified the changes I’ve been involved with.
- Performed some ad-hoc testing.

**Closed** 2022-09-12 20:15 UTC
Labels: P0, Type: Task

**Comment by techanvil** [comment] 2022-09-23 17:17
## QA: :warning: 

- Smoke tested :white_check_mark: 
- Verified the changes I’ve been involved with :warning: 
- Performed some ad-hoc testing :white_check_mark: 

I noticed that a detail from the AC/IB in #5805 was missed. According to the issue, the "You will need to give Site Kit permission..." message should only show up when "Set up a new property" is selected in the dropdown.
   
However I have also realised that this condition is incomplete with a bit of detail missing. With that in mind and considering the GA4 Activation Banner is not yet released, I think we can address this in the next release via a follow-up issue, and have created one accordingly: #5882.

Additionally, I have not attempted to verify #5851 in the wild due to a requirement for a WP install with multi-byte UTF-8 characters e.g. éxämplę.com which I do not readily have to hand. It seems InstaWP doesn't support these characters in a custom domain. Nor does my usual DNS provider in fact, although I found a free one that does.
