### ISSUE TITLE
Admin 2 not having GA4 property access causes permanent loading state when "gathering data" in GA4 widgets

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#7006] opened 2023-05-03 18:20 UTC
## Bug Description

If a second admin tries to access the authenticated dashboard when GA4 is in "Gathering Data" state and if they do not have access to the GA4 property set up by the original admin, then all GA4 widgets are in a permanent loading state.

## Steps to reproduce

1. With the GA4 Reporting feature flag on, set up Site Kit with a new GA4 property (so that the site is in Gathering data state).
2. Now log in as another admin (say Admin 2) and connect Site Kit to view the authenticated dashboard. Ensure that the google account used by admin 2 does NOT have access to the GA4 property/account created in Step 1.
3. Visiting the dashboard as Admin 2 will show all GA4 widgets in a permanent loading state. The console will throw the following errors: 
`GET http://sitekit.10uplabs.com/wp-json/google-site-kit/v1/modules/analytics-4/data/property?propertyID=373877631&_locale=user 403 (Forbidden)` and `Google Site Kit API Error method:GET datapoint:property type:modules identifier:analytics-4 error:"The caller does not have permission"` 

Note: If the widgets do load correctly after the above steps, remove the `_transient_googlesitekit_analytic-4_data_available` and `_transient_timeout_googlesitekit_analytics-4_data_available` rows from the `wp_options` table in the DB. This will clear the new cached values for the data available state.

## Screenshots

[](https://user-images.githubusercontent.com/73545194/235662549-bd4f60ca-f38b-4d01-b4a9-5c0b38f23b78.mp4)

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

On some preliminary investigation, this issue occurs because the `propertyID` check below returns an error from the Google Service. 

https://github.com/google/site-kit-wp/blob/41ca2a713d361ef93f7adc1ddaa420f9f899a2b4/assets/js/modules/analytics-4/datastore/report.js#L142

However, commenting out this check and simply returning `true` does render the widgets in a "Zero data" state rather than throwing the "Insufficient permissions" `<ReportError>` which would happen if GA4 was not in a gathering data / zero data state. The report requests return normal responses as shown in the below screenshot (rather than failing due to insufficient permissions after making a call to the Google Analytics Service):
![Screenshot 2023-05-03 at 19 06 41](https://user-images.githubusercontent.com/1721319/236010668-4fbf0a87-b731-48e3-8a3e-875eb5d1a04c.png)

What happens when site is not in gathering data state:
<img width="3006" alt="Screenshot 2023-05-03 at 18 33 14" src="https://user-images.githubusercontent.com/1721319/236010414-e52d30f8-b4bd-47bb-9fbb-e6427a45241d.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- When a user is on the authenticated Dashboard with the GA4 Dashboard View enabled and they don't have permission to the connected GA4 property, the GA4 widgets should display the "Insufficient permissions" report error for the Analytics module.
- This should be the case regardless of whether the property is in a with/gathering/zero data state, and whether the current user is the user who connected the property or not.

![image](https://user-images.githubusercontent.com/18395600/236202600-f5b7fee8-d266-40a2-ba2e-f9a007327c85.png)

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by mohitwp** [comment] 2023-05-12 09:18
@jimmymadon I'm able to reproduce this issue in below scenario.

- 'ga4Reporting' feature flag is enabled.
- Both UA and Ga4 properties are connected.
- Dashboard view is ga4.
- Analytics is in gathering state.
- Sign in with Admin 2 who don't have access to connected analytics a/c.
- Access main dashboard.
- See widgets appears in continuous loading state with console error.

<details>


https://github.com/google/site-kit-wp/assets/94359491/a546e3b6-9cba-4eff-88d7-af0574573bca

</details>

**Note :** I found another case when analytics immediately changing state to zero when admin 2 sign in into SK. 
Scenario - 
- Create new InstaWP site.
- When 'ga4Reporting' is enabled, create a/c using only ga4 from Admin A a/c.
- Analytics and Search console will appear in gathering state.
- Now sign in with Admin 2 and set up site kit.
- Access main dashboard. 
- Notice analytics showing in zero state.
- Search console is in gathering state banner is showing with 72 hours time which is not correct for analytics.
- I think because here analytics changing it's state immediately to zero that's why loading issue is not producing in this case. Should i create separate issue for this scenario ?

<details>


![image](https://github.com/google/site-kit-wp/assets/94359491/1ee5ab86-ef37-4908-94ae-6f1f95c22141)

</details>

cc @bethanylang

**Comment by mohitwp** [comment] 2023-05-15 11:27
@jimmymadon 

I tested it more to reproduce this issue here and another 2 issues issue listed below which we notice. that on set up second admin (who don't have access to analytics a/c) getting 4 steps and analytics changing its state immediately to zero after second admin sign into site kit.

**Comment by mohitwp** [comment] 2023-05-17 08:31
@bethanylang Created new ticket #7054 for the issue of analytics changing its state from gathering to zero when Admin 2 (not having access to connected analytics a/c) Sign in into SK. Closing this issue for now.

**Closed by mohitwp** 2023-05-17 08:31 UTC
Labels: Type: Bug, P1, Module: Analytics, P1 Med
