### ISSUE TITLE
Add new Site Kit illustrations

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2616] opened 2021-01-13 16:30 UTC
Tracking issue for exchanging the existing illustrations in the plugin for new branding illustrations, all SVG. Somewhat related is #2468. This should either be behind the `userInput` flag (since those will be rolled out together), or behind a separate illustration-specific flag.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following images should be removed and replaced by corresponding new "side kick" illustrations:
    * `rocket.svg`: With green success illustration
    * `person-sitting.svg`: With user input prompt illustration (used only in user input)
    * `congrats.svg`: With blue milestone illustration (used only in user input for now)
    * `sun-small.svg`: With notification alert illustration (used only for module alerts, i.e. AdSense, for now)
    * `thumbs-up.svg`: With award illustration (used when all modules have been activated)
    * `person-walking.svg`: With welcome illustrations (used for setup behind `serviceSetupV2` feature flag)

## Implementation Brief

* Exchange all SVG graphics per the ACs.
* Merge #3077.

### Test Coverage

* N/A

### Visual Regression Changes

* VRT reference images have to be refreshed to account for expected difference in illustrations.

## QA Brief

* Ensure the SVG files outlined in the ACs are no longer in the codebase.
* Ensure the following areas have the above graphics:
    * In the success notification for connecting Site Kit or activating a module, the green jumping sidekick should appear.
    * When having activated all modules and going to "Connect more services", the yellow sidekick holding an award should appear.
    * When there is a remote AdSense alert notification (shows in the AdSense module page if you have one), it should show the blue sidekick's arm holding a red warning sign.
    * With the `serviceSetupV2` feature flag active:
        * The Site Kit setup screen should show the four sidekicks as a welcome.
    * With the `userInput` feature flag active:
        * When visiting the dashboard as an existing user that has not filled the user input, the user input prompt notification should show the green sidekick with a pencil filling the user input.
        * When completing the user input questions, the success notification should show the blue sidekick holding up a star.

## Changelog entry

* Update assets across the plugin with new side kick-based branding illustrations.

**Comment by aaemnnosttv** [comment] 2021-04-05 06:57
IB ✅ 

Going to bump the estimate a tiny bit though to allow a little more time for CR + QA (particularly the latter).

**Comment by wpdarren** [comment] 2021-04-07 14:02
Adding a note to confirm I have asked on Slack for the illustrations in Figma, so we can compare what is on the  test site.

**Comment by wpdarren** [comment] 2021-04-08 11:54
### QA Update: Checking with Engineer re. one test. ⚠️ 

**Verified:**

_AC checks:_

- `rocket.svg` this is replaced with the green success side kick illustration 

![image](https://user-images.githubusercontent.com/73545194/114011261-9e678480-9897-11eb-9884-093a4c022203.png)

- `person-sitting.svg` this is replaced with the green onboarding side kick illustration

![image](https://user-images.githubusercontent.com/73545194/114017745-f655b980-989e-11eb-9668-05cd21bf7533.png)

- `congrats.svg` this is replaced with the new blue milestone side kick illustration 

![image](https://user-images.githubusercontent.com/73545194/114014033-c3a9c200-989a-11eb-9ab8-2ec4982a9d44.png)

- `sun-small.svg`

Unable to find this illustration. It's triggered via an Alert in Adsense module.  Asked @aaemnnosttv on Slack to assist. 

- `thumbs-up.svg` this is replaced with the new yellow awards side kick illustration 

![image](https://user-images.githubusercontent.com/73545194/114015211-04eea180-989c-11eb-92af-a1be045ce04e.png)

- `person-walking.svg` this is replaced with the new welcome side kick illustrations

![image](https://user-images.githubusercontent.com/73545194/114015670-880ff780-989c-11eb-9722-99c948f72355.png)

- In the success notification for connecting Site Kit or activating a module, the green jumping sidekick  appears .
- When having activated all modules and going to "Connect more services", the yellow sidekick holding an award appears.
- With the `serviceSetupV2` feature flag active: Site Kit setup screen shows the four sidekicks as a welcome.
- When completing the user input questions, the success notification shows the blue sidekick holding up a star.
- When visiting the dashboard as an existing user that has not filled the user input, the user input prompt notification shows the green sidekick with a pencil filling the user input.

**Comment by aaemnnosttv** [comment] 2021-04-08 14:52
## QA ⚠️ 

- [`sun-small.svg`](https://github.com/google/site-kit-wp/blob/98fcde0affabcaef07f567f96eb71fbe42fc5599/assets/svg/sun-small.svg) -> [`notification-alert.svg`](https://github.com/google/site-kit-wp/blob/7a9bc2e2dfd27abdfbfb370cb22b55ee63a7f061/assets/svg/notification-alert.svg)

**Before**
![sitekit 10uplabs com_wp-admin_admin php_page=googlesitekit-dashboard (3)](https://user-images.githubusercontent.com/1621608/114047359-509c4d80-9892-11eb-8818-ec5467748de2.png)

**After**
![prime-reef jurassic ninja_wp-admin_admin php_page=googlesitekit-dashboard](https://user-images.githubusercontent.com/1621608/114047430-5a25b580-9892-11eb-9dae-77428e200df1.png)

Closer inspection shows the width matches but the height is a bit taller than before.

| sun-small | notification-alert |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1621608/114047645-80e3ec00-9892-11eb-9ed5-9aaea58a98d9.png) | ![image](https://user-images.githubusercontent.com/1621608/114047664-84777300-9892-11eb-95a1-5ff83081a8a4.png) |

If we want the two to match vertical height instead it should be fairly easy to update. What do you think @felixarntz ?

**Comment by aaemnnosttv** [comment] 2021-04-08 15:01
Updating the alert with a height of `136` matches
![Kapture 2021-04-08 at 17 57 57](https://user-images.githubusercontent.com/1621608/114049450-2186db80-9894-11eb-9353-2c82a494dd04.gif)

I'll open a follow-up PR with this change and Felix can merge it if we feel this should change. The newer version does look a bit too big to me due to the added height, especially if there isn't much content in the alert as shown.

**Comment by wpdarren** [comment] 2021-04-08 15:16
@aaemnnosttv @felixarntz  I have just checked on smaller screen sizes and the new illustrations do not seem to be
responsive. Take the green success side kick illustration as an example. This is 200x200 pixels on desktop and mobile.  

I am not sure if this is expected. 

![image](https://user-images.githubusercontent.com/73545194/114050935-42b0f180-98bf-11eb-96e9-786654282d05.png)

Not all of the icons are this size, so will probably be okay, i.e. yellow awards side kick illustration looks fine on desktop and mobile but is the same pixels 75.5 x 75.5

![image](https://user-images.githubusercontent.com/73545194/114052156-5e68c780-98c0-11eb-999a-49c8c5b0604a.png)

**Comment by aaemnnosttv** [comment] 2021-04-08 15:21
@wpdarren would you please compare with the previous release so we know if this would be a regression or not?

**Comment by wpdarren** [comment] 2021-04-08 15:27
@aaemnnosttv actually, I just did that, and no it's not a regression, the pixel sizes were the same before on desktop and mobile, so I think the only difference is that the new illustrations are just slightly larger. 

![image](https://user-images.githubusercontent.com/73545194/114053885-ed2a1400-98c1-11eb-8713-bc83df945a9e.png)

**Comment by felixarntz** [comment] 2021-04-08 15:36
@wpdarren @aaemnnosttv I think the PR is worth merging to fix the warning illustration size. The other one for the success notification is okay as is.

**Comment by aaemnnosttv** [comment] 2021-04-08 15:59
@wpdarren the size tweak for the notification alert was merged so I think we can consider the last good to go now 👍

**Comment by wpdarren** [comment] 2021-04-09 03:52
### QA Update: Pass ✅ 

**Verified:**

_AC checks:_

- `rocket.svg` this is replaced with the green success side kick illustration 

![image](https://user-images.githubusercontent.com/73545194/114011261-9e678480-9897-11eb-9884-093a4c022203.png)

- `person-sitting.svg` this is replaced with the green onboarding side kick illustration

![image](https://user-images.githubusercontent.com/73545194/114017745-f655b980-989e-11eb-9668-05cd21bf7533.png)

- `congrats.svg` this is replaced with the new blue milestone side kick illustration 

![image](https://user-images.githubusercontent.com/73545194/114014033-c3a9c200-989a-11eb-9ab8-2ec4982a9d44.png)

- `sun-small.svg` this is replaced with the new blue side kick with alert illustration. 

![image](https://user-images.githubusercontent.com/73545194/114125879-e33bfb80-9929-11eb-8536-ccd5112fff55.png)

- `thumbs-up.svg` this is replaced with the new yellow awards side kick illustration 

![image](https://user-images.githubusercontent.com/73545194/114015211-04eea180-989c-11eb-92af-a1be045ce04e.png)

- `person-walking.svg` this is replaced with the new welcome side kick illustrations

![image](https://user-images.githubusercontent.com/73545194/114015670-880ff780-989c-11eb-9722-99c948f72355.png)

_QAB checks_

- In the success notification for connecting Site Kit or activating a module, the green jumping sidekick  appears .
- When having activated all modules and going to "Connect more services", the yellow sidekick holding an award appears.
- With the `serviceSetupV2` feature flag active: Site Kit setup screen shows the four sidekicks as a welcome.
- When completing the user input questions, the success notification shows the blue sidekick holding up a star.
- When visiting the dashboard as an existing user that has not filled the user input, the user input prompt notification shows the green sidekick with a pencil filling the user input.  
- When there is a remote AdSense alert notification, it shows the blue sidekick's arm holding a red warning sign.

**Closed** 2021-04-12 21:34 UTC
Labels: P1, Type: Enhancement
