### ISSUE TITLE
URLs displayed with duplicate path segment (for language/WPML, but also generally)

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1116] opened 2020-02-11 01:22 UTC
## Bug Description
**Modified for UI issue only** 

URLs are displayed with a duplicate path when using the [WPML plugin](https://wpml.org/) _different languages in directories_ setting with the _use directory for default language_ sub-option checked: 

<img width="1100" alt="WPML different languages in directories" src="https://user-images.githubusercontent.com/8108643/78640051-eb1f1680-7863-11ea-93aa-7b159a21f863.png">

Site Kit chooses the default language URL as the Site URL:

<img width="1054" alt="Screen Shot 2020-04-10 at 11 09 40 AM" src="https://user-images.githubusercontent.com/8108643/79472863-34383e80-7fb9-11ea-9de4-b20c631ac713.png">

URLs reported in the UI append the directory additionally:

<img width="519" alt="Screen Shot 2020-04-13 at 6 36 05 PM" src="https://user-images.githubusercontent.com/8108643/79473003-6184ec80-7fb9-11ea-880a-b8532afffa7a.png">

Further context about the setting:

https://wpml.org/faq/server-setting-for-languages-in-directories/
https://wpml.org/documentation/getting-started-guide/language-setup/cannot-activate-language-directories/

Related support topic:

https://wordpress.org/support/topic/doesnt-handle-multiple-languages-correctly/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should be fully compatible with WPML.
* In particular: with the WPML settings: "different languages in directories" and "use directory for default language sub-option" checked, and the SiteURL set to `{domain}/{default_language}`, the URLS displayed in the "Top content over the last 28 days" table on the WordPress Dashboard, and for the "Most popular content" table on the Site Kit Dashboard should appear correctly.

## Implementation Brief

* When constructing the url to display for top a pages use only the `url` (path) data returned from the API (don't prepend the site URL):
  -  In **WPAnalyticsDashboardWidgetTopPagesTable** [`assets/js/modules/analytics/wp-dashboard/wp-dashboard-widget-top-pages-table.js`](https://github.com/google/site-kit-wp/blob/d0c0d9dc0f89e8516d17eb8b78d600a1780130ac/assets/js/modules/analytics/wp-dashboard/wp-dashboard-widget-top-pages-table.js#L52) and
  -  In **AnalyticsDashboardWidgetPopularPagesTable** -[`assets/js/modules/analytics/dashboard/dashboard-widget-popular-pages-table.js`](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/dashboard/dashboard-widget-popular-pages-table.js#L83):

`links[ i ] = siteURL + url;` should change to `links[ i ] = url;`

## QA Brief

* 

## Changelog entry

* Display only paths instead of full URLs in Analytics tables for better visibility and consistency with Analytics frontend.

**Comment by ernee** [comment] 2020-02-11 01:35
Just noting that values for the _WordPress URL_ and _Site URL_ under **Settings > General**  from the Dashboard don't change for this setting in WPML. 

In some cases, the affect may be similar to those reported in #922

**Comment by ernee** [comment] 2020-02-27 21:52
Similar behavior is seen in the [TranslatePress plugin](https://translatepress.com/), with the setting _Use a subdirectory for the default language_. Results in a **‘redirect_uri’ mismatch** error. More about the setting:

https://translatepress.com/docs/settings/#default-launguage-subdirectory

Related support topic: https://wordpress.org/support/topic/unable-to-sign-in-redirect_uri-mismatch/

**Comment by felixarntz** [comment] 2020-04-07 17:01
@ernee The `redirect_uri_mismatch` problem is a different one. They're both related to subdirectories, but the original one outlined here is UI-related, while the one in your last comment is setup-related.

I'll open a separate issue for that.

**Comment by felixarntz** [comment] 2020-04-07 17:19
This problem here is not strictly related to a language plugin - it most likely affects all sites which are in a subdirectory. I assume it is because we combine the full paths returned from Google APIs with the site URL in the wrong way: If the site URL includes a path already, that path should not be included twice in the combined URL.

cc @adamsilverstein

**Comment by ernee** [comment] 2020-04-07 18:25
@felixarntz thanks for the clarification! I tested this again and got the **‘redirect_uri’ mismatch** with the noted WPML settings. 

<img width="641" alt="WPML redirect uri error" src="https://user-images.githubusercontent.com/8108643/78705495-6adbce00-78c2-11ea-94e6-d5fbe747f254.png">


I'm not sure if recent updates changed the outcome, but noting this here.

**Comment by ernee** [comment] 2020-04-07 18:32
Regarding WPML, I am also investing this issue which a user said the different domains per language option leads to a 404 (note the callback URL): https://wordpress.org/support/topic/doesnt-support-multidomain-config/

I haven't been able to recreate it, but should this be a separate issue ?

**Comment by adamsilverstein** [comment] 2020-04-09 13:53
> I haven't been able to recreate it, but should this be a separate issue ?

This is likely a related issue so you can leave it here. All these `redirect_uri` errors are at least potentially related to the issue we are working on in https://github.com/google/site-kit-wp/issues/1357 - and will be resolved with the fixes there.

**Comment by aaemnnosttv** [comment] 2020-04-10 12:39
@felixarntz / @adamsilverstein - can you clarify if this is still an issue? I see that the `redirect_uri_mismatch` problem is separate than this one, but it isn't very clear what the remaining issue is, if there is one.

**Comment by felixarntz** [comment] 2020-04-10 13:22
@aaemnnosttv I think there's some confusion in this issue overall, things got mixed up. The issue description talks about a 404 in setup, but the linked support thread talks about a completely different problem, related to how URLs are displayed. My comment further above applies to that URL problem.

We should separate these into distinct issues. cc @ernee

**Comment by adamsilverstein** [comment] 2020-04-10 21:35
@ernee - Regarding the WPML plugin, I did some testing with the latest version of wpml and site kit.  Running with languages in a subdirectory, setup worked fine and was not blocked...

Some things worth noting:

* My site was set up in search console and verified as `{domainname}/default_language` - meaning by default I wouldn't get Search Console data for any other languages. If the user wanted to collect data for all languages they could probably set up a domain property (for {domainname}) in search console and connect to that in the setup flow (it is offered during setup in a dropdown if found). 

* For Analytics, I see the tag output on both sites so data for all languages would be combined in the display. This feels like expected behavior.

Tested on a `jurassic.ninja` 
My settings:

![image](https://user-images.githubusercontent.com/2676022/79024231-90294000-7b3f-11ea-9851-5ec0daaeda98.png)

**Comment by adamsilverstein** [comment] 2020-04-10 21:41
> @felixarntz / @adamsilverstein - can you clarify if this is still an issue? I see that the redirect_uri_mismatch problem is separate than this one, but it isn't very clear what the remaining issue is, if there is one.

In my testing WPML no longer has a setup issue. It might be worth noting the search console limitation (noted above) in our FAQ or so people aren't confused. I think we can close this one once we have a follow up issue for the linked support thread item ("the linked support thread talks about a completely different problem, related to how URLs are displayed.").

**Comment by felixarntz** [comment] 2020-04-10 21:55
Let's follow up separately on the setup issue - the support thread linked above is about displaying incorrect URLs, so it's purely a UI issue. If needed, let's create a separate one for the setup part.

**Comment by adamsilverstein** [comment] 2020-04-13 18:16
Looking at the code, in the plugin displays full URLS when displaying the "Top content over the last 28 days" on the WordPress Dashboard, and for the "Most popular content" List on the Site Kit Dashboard.

These data points come from the Analytics API, which returns paths (not full urls). The  plugin constructs the url to display by appending the item path to the site URL:

https://github.com/google/site-kit-wp/blob/d0c0d9dc0f89e8516d17eb8b78d600a1780130ac/assets/js/modules/analytics/dashboard/dashboard-widget-popular-pages-table.js#L83

https://github.com/google/site-kit-wp/blob/d0c0d9dc0f89e8516d17eb8b78d600a1780130ac/assets/js/modules/analytics/wp-dashboard/wp-dashboard-widget-top-pages-table.js#L52

In the case of the user reporting the issue, I suspect that they have configured `{domain}/{default_language}` as their WordPress site URL (which matches the WPML configuration where users put their default language into a subfolder). When the Analytics API responds with the full file path, the resulting constructed path duplicates the `/{default_language}` part.

For the purposes of displaying URL's we should construct the URLs to display by using only the domain name from the siteURL before adding the API returned path.

**Comment by felixarntz** [comment] 2020-04-13 19:16
IB ✅ 

@adamsilverstein Would the URLs ever _not_ start with the path that's actually part of the site? E.g. site URL is `https://example.com/blog`, and the path to display as URL is `/something-other-than-blog/something`. Probably we can ignore that case, shouldn't make a difference, but it's something to consider.

Also this needs an estimate.

**Comment by adamsilverstein** [comment] 2020-04-13 22:26
> Would the URLs ever not start with the path that's actually part of the site? E.g. site URL is https://example.com/blog, and the path to display as URL is /something-other-than-blog/something.

@felixarntz - Fair point - I'm not certain. 

Perhaps we should take a step back and consider **showing only the paths in these tables**? That is what I see in the Analytics UI so I am not sure why we show full URLs in Site Kit.  From a UX perspective, I feel like the site URL is extraneous information that doesn't help the user.

What do you think?

One other option: we could also use the [ga:hostname](https://ga-dev-tools.appspot.com/dimensions-metrics-explorer/#ga:hostname) value instead of the local URL, which should be more accurate.

**Comment by felixarntz** [comment] 2020-04-13 22:45
@adamsilverstein I like these ideas. Let's talk through it with @marrrmarrr

**Comment by marrrmarrr** [comment] 2020-04-22 18:44
Discussed with Felix, SGTM to show only relative URL paths.

**Comment by felixarntz** [comment] 2020-04-22 19:27
@adamsilverstein Can you update the IB to account for the decision of showing only paths? Would be good to include where to do it (we have multiple places, like dashboard, Analytics module page, WP dashboard widget).

**Comment by felixarntz** [comment] 2020-04-23 15:40
@aaemnnosttv I was just including these examples based on where I _thought_ it may be displayed from the top of my head - no need to add it elsewhere :)

**Comment by cole10up** [comment] 2020-05-07 05:58
Confirmed with the help of @ernee that this is fixed.

<img width="530" alt="Screen Shot 2020-05-06 at 11 50 19 AM" src="https://user-images.githubusercontent.com/57115907/81259609-293b6180-8fed-11ea-9ae3-dd306a126ef5.png">


Passed QA ✅

**Closed** 2020-05-12 15:34 UTC
Labels: Good First Issue, P1, Type: Bug
