### ISSUE TITLE
I can't use google site kit... just show blank page

### ISSUE THREAD

**Issue by Sanjoy123456** [google/site-kit-wp#552] opened 2019-09-17 16:36 UTC
Hello, I'm using google site kit on my Wordpress site. I'm not an expert programmer. when I upgrade 1.0.5 to 1.0.6 I see the blank page problem. when I click google site kit from collapse menu I see this page...
See my problem from this link(i upload ss): https://prnt.sc/p7d74n

**Comment by jamesozzie** [comment] 2019-09-17 17:18
@Sanjoy123456 Can you please provide the following information
- Share your [Site Health information](https://i.imgur.com/Rtkmsba.png)
- Confirm the search console errors you see

**Comment by Sanjoy123456** [comment] 2019-09-18 07:03
Hello, Sir, my site health is 93% and i copy clipboard (If you want, I can share my site clipboard)

SIte Health SS = https://prnt.sc/p7lgy3
console error ss = https://prnt.sc/p7li6k
                              https://prnt.sc/p7lie7

**Comment by adamsilverstein** [comment] 2019-09-18 18:00
Hi @Sanjoy123456 thanks for reporting this issue, I am working on trying to resolve it.

Can you please try the Site Health data again, if you are running the latest version of WordPress it is under `Tools`, click the 'Copy site info to Clipboard' button and paste the results back here. Thanks!

**Comment by jamesozzie** [comment] 2019-10-04 16:36
@Sanjoy123456 Did you get a chance to extract your Site Health information?

**Comment by Sanjoy123456** [comment] 2019-10-04 17:32
@jamesozzie sir now I stop using google site kit. 😩😩😩 when google releases the full version of the site kit then I'm starting to using this plugin.

**Comment by jamesozzie** [comment] 2019-10-07 08:14
@Sanjoy123456 I will close this ticket so, if you want to reopen feel free to share your Site Health info. You can also try attempt another site on the same web host to see if the same issue occurs.

**Closed by jamesozzie** 2019-10-07 08:14 UTC
Labels: Type: Support

**Comment by TheWebGuruDotNet** [comment] 2019-11-21 12:38
The issue is with the plugin itself not the connection to outside or server related as far as i know
![image](https://user-images.githubusercontent.com/56264102/69338580-67b9ab80-0c5b-11ea-8577-dc7559818313.png)
I have removed the plugin from everywhere and i guess might try it out in few months
Google provided wordpress plugins should be tested in all environments before publishing them, knowing that millions will install it. 
Sadly this plugin gave Google a bad image! at least so far.
but i am sure at a later stage when this becomes stable it is going to kill many other plugins. the concept is a BOMB!

so best of luck
