### ISSUE TITLE
Helper text has incorrect font size

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#4510] opened 2021-12-08 13:15 UTC
## Bug Description
We have a global CSS rule for paragraphs where we set the font size to `1rem`. However, in some cases, for e.g helper texts which are `p` having the `mdc-text-field-helper-text` class name should have a smaller font size, `0.75rem` rather than `1rem` which looks quite big.

## Screenshots

Font size set to `1rem`:
![image](https://user-images.githubusercontent.com/31818/145214543-4b276e05-7aa5-498d-beb4-bdee814b13e4.png)

Font size set to `0.75rem`:
![image](https://user-images.githubusercontent.com/31818/145214600-d358eb74-065f-41dd-a90e-1b237b7d3e0c.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The [default font-size for Site Kit `p` tags](https://github.com/google/site-kit-wp/blob/a27f08668b1d738f72672bfc5d7c61e90bef981c/assets/sass/base/_defaults.scss#L144-L147) should not override material styles

## Implementation Brief

* Update `p` to not match `p` tags that contain a material class prefix (i.e. `p:not([class*="mdc-"])` in the default styles https://github.com/google/site-kit-wp/blob/a27f08668b1d738f72672bfc5d7c61e90bef981c/assets/sass/base/_defaults.scss#L144-L147

### Test Coverage

* May require VRT updates

## QA Brief

- Go to the Site Kit settings page
- Edit Analytics
- Type an incorrect value in the `Ads Conversion ID` text field
- Verify the `font-size` of the helper text should be `0.75rem`
- Verify the text length is smaller than the text field

## Changelog entry

* Update sizing of input helper text to be consistent with Material styles.

**Comment by aaemnnosttv** [comment] 2021-12-22 21:17
cc: @felixarntz

**Comment by asvinb** [comment] 2021-12-23 07:50
IB 👍

**Comment by wpdarren** [comment] 2022-02-02 14:37
@aaemnnosttv as discussed on [Slack](https://10up.slack.com/archives/CBKKQEBR9/p1643720952525489) yesterday, 

> I have noticed that the ‘connect service’ font size is different. The font size in main is as expected so doesn’t impact 1.50.0. Develop is 16px where main is 12px. 

It was confirmed that the font size change above was because of the work in this ticket. It's possible we could have other font size issues across the plugin, so in my opinion we need to compare `develop` to the latest release.  Do you feel any differences should be addressed in this ticket or create new one?  Thoughts appreciated! 

c.c. @hussain-t @asvinb

**Comment by aaemnnosttv** [comment] 2022-02-02 16:57
@wpdarren any unintended changes should be handled as part of this issue but probably on a case-by-case basis. That is to say, let's identify any changes outside of those addressed by this issue intentionally and assess if those require changing or not. The one you found about the "connect service" heading _should be fixed_ so there will need to be a follow-up here but let's check to see what else may have been affected. For now, probably comparing the Storybooks for [`main`](https://google.github.io/site-kit-wp/storybook/main/?path=/story/analytics-module-setup--loading) and [`develop`](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-setup--loading) would be most efficient to start.

**Comment by wpdarren** [comment] 2022-02-03 11:06
### QA Update: ❌ 

@aaemnnosttv @hussain-t @asvinb  as discussed previously, there are a few font size differences that I could find between `main` (left screenshot) and `develop` (right screenshot) as detailed below. 

- When connecting all modules the 'Connect Service' text is larger.
- The format texts underneath the fields on Optimize and Tag Manager
- Text 'AdSense accounts are...' when connecting AdSense
- The topics on Idea Hub widget, for new, saved and drafts. (also on the tour too)

While this does pass the QAB, I do wonder if 0.75rem is too small.  When I played around with this, 0.85rem was easier to read and the text length is smaller than the text field. This is just a personal preference though. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/152328733-a954b1e2-5a2d-4fda-8680-8fa42f53d979.png)

![image](https://user-images.githubusercontent.com/73545194/152330073-d51461df-6870-4516-b676-07ef80058364.png)

![image](https://user-images.githubusercontent.com/73545194/152330122-977c86ed-e8c1-4fba-bb9b-6f391a5f4e57.png)

![image](https://user-images.githubusercontent.com/73545194/152330178-4b5b6d21-0395-4f13-9c66-82f4601338cc.png)

![image](https://user-images.githubusercontent.com/73545194/152329862-e8912140-1c37-4781-b54a-6214d0530e14.png)

![image](https://user-images.githubusercontent.com/73545194/152329120-533984cd-56bd-4455-a665-290cfcf35cf9.png)

![image](https://user-images.githubusercontent.com/73545194/152329493-3d17a62b-3a3f-425e-b818-aee989244daf.png)

![image](https://user-images.githubusercontent.com/73545194/152330010-efb891a0-22ac-46d4-b868-f113720b3a98.png)

</details>

**Verified:** 

The font-size of the helper text is 0.75rem, and the text length is smaller than the text field

![image](https://user-images.githubusercontent.com/73545194/152330603-f3c586b1-80bf-4d95-9c9f-0559f4b5c60f.png)

**Comment by aaemnnosttv** [comment] 2022-02-03 15:19
Thanks @wpdarren!

> When connecting all modules the 'Connect Service' text is larger.

This should be fixed 👍 

> The format texts underneath the fields on Optimize and Tag Manager

These are both helper text and are part of the intended changes of this issue. ✅ 

> Text 'AdSense accounts are...' when connecting AdSense

Should be fixed 👍 

> The topics on Idea Hub widget, for new, saved and drafts. (also on the tour too)

`.googlesitekit-idea-hub__idea--text` should be fixed, but not sure what you mean about "also on the tour too". Did you mean the _Idea Hub > Feature Tour_ story? The idea text would be the same there, but that story is more about the feature tour that can be triggered by clicking the "Reset Tour" button. I don't see any visual differences with the feature tour tooltips though.

**Comment by asvinb** [comment] 2022-02-04 08:48
Follow up PR:
https://github.com/google/site-kit-wp/pull/4787
@wpdarren I checked the tour as well and I didn't see any regressions. Can you provide more info about that and we are not using `p` tags anywhere in the tooltips, so there shouldn't be any regressions.

**Comment by wpdarren** [comment] 2022-02-04 10:18
@asvinb @aaemnnosttv sorry about the confusion.  When I checked Storybook, I noticed the font size difference on the Feature tour page and it said reset tour button above, so incorrectly assumed it was the tour. 

![image](https://user-images.githubusercontent.com/73545194/152330010-efb891a0-22ac-46d4-b868-f113720b3a98.png)

**Comment by aaemnnosttv** [comment] 2022-02-08 17:59
@wpdarren ready for another pass 👍

**Comment by wpdarren** [comment] 2022-02-09 09:50
### QA Update: ✅ 

**Verified:**

- The font sizes have been fixed as per the [comment above](https://github.com/google/site-kit-wp/issues/4510#issuecomment-1028871822)
- The font-size of the helper text is 0.75rem, and the text length is smaller than the text field.

![image](https://user-images.githubusercontent.com/73545194/153171148-69c2aeca-b197-46d1-9d76-c3287acddd7d.png)

**Closed** 2022-02-14 20:30 UTC
Labels: P2, Type: Enhancement, Rollover
