### ISSUE TITLE
Android - Galaxy 22 and 22 ultra UI issues

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5436] opened 2022-06-27 13:10 UTC
## Bug Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202424752772575 please see Asana for background

We should hide the "Site Kit" part of the logo in screens that small.

## Screenshots

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/be8b4f89-dfa1-4c18-83f6-c1cf9913280b)
![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/565074fc-c276-4256-8af9-5f7808ffcf39)
![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/db92e2b8-57b5-4c21-bc4e-650949ca6269)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On our smallest viewport (`$width-xsmall: 450`), the words Site Kit from the Site Kit logo should be hidden and only the G logo icon should be shown.

## Implementation Brief
* Using `assets/sass/components/global/_googlesitekit-logo.scss`,
    * Hide `.googlesitekit-logo__logo-sitekit` using `display: none` till the 449px breakpoint (`$bp-xsmallOnly`)

### Test Coverage
* VRT images might need to be updated

## QA Brief

* Open SK on mobile with a width <449px
* Text part of a logo should not appear as per the screenshot: 
<img width="522" alt="Screenshot 2022-12-15 at 13 37 19" src="https://user-images.githubusercontent.com/16494321/207872961-5032583a-b1c1-4750-903d-c3eaf6769bb5.png">

## Changelog entry

* Fix Site Kit logo being cut-off on Samsung Galaxy S22 and other similarly-sized phones.

**Comment by aaemnnosttv** [comment] 2022-10-11 23:58
@jimmymadon I think most of the desired outcome is probably obvious here where things are overflowing. We should consider reducing the logo to just the G in portrait-phone viewports though. Last I recall checking this I wasn't able to reproduce, but I also didn't see it with a Galaxy device 😄

**Comment by jimmymadon** [comment] 2022-10-19 11:41
@aaemnnosttv I checked this on my personal Galaxy S21 Ultra too (which has the same screen width as the S22 Ultra). Everything looks good as per the below screenshots. The logo does overflow on smaller screens when testing on the browser.

<details>
 <summary>Screenshots</summary>

![Screenshot_20221019-121601_Chrome](https://user-images.githubusercontent.com/1721319/196679123-d18ed96a-f7b5-4318-a2a5-679516fef868.jpg)
![Screenshot_20221019-122321_Chrome](https://user-images.githubusercontent.com/1721319/196679130-1f5adcdb-b1c7-48fa-8a0b-bad3ba80a4bc.jpg)
![Screenshot_20221019-122332_Chrome](https://user-images.githubusercontent.com/1721319/196679133-c62fb528-fbb3-4a80-b6fd-100273ae0dff.jpg)
![Screenshot_20221019-122402_Chrome](https://user-images.githubusercontent.com/1721319/196679134-313aa18b-b70c-4bce-aa99-cdee62787d33.jpg)

</details>

@mohitwp I can reproduce the Logo overflows on smaller screen widths (< 375px). However, I cannot reproduce the overflows in the second screenshot anymore - I believe the Dashboard Sharing popup overflows may have been resolved in another [similar issue](https://github.com/google/site-kit-wp/issues/5358). Can you please check again?

**Comment by FlicHollis** [comment] 2022-11-09 10:12
@aaemnnosttv just following up here so we can potentially get this one moving. 
Also ccing @eugene-manuilov if you can help?

**Comment by aaemnnosttv** [comment] 2022-11-11 23:23
@jimmymadon is this the only issue remaining here?

<details>
<summary>Screenshot</summary>

<img width="326" alt="image" src="https://user-images.githubusercontent.com/1621608/201443592-a7878b25-801d-41cb-946f-957807ea21de.png">

</details>

If anything, I wonder if we should hide the "Site Kit" part of the logo in mobile. Thoughts @marrrmarrr ?

**Comment by mohitwp** [comment] 2022-11-14 08:26
@jimmymadon 

Actually there are different versions of Galaxy device available on BrowserStack. I checked in Galaxy S21 device which viewports is 360X649. Issue not appearing in Galaxy S22+ which have width >375. So, yes issue coming only in devices <375. 
Regarding 2nd issue related to Dashboard sharing modal - I'm also not able to reproduce it now. 
Thank you !

<details>

![image](https://user-images.githubusercontent.com/94359491/201610865-bdd28344-bf95-4568-ae18-74611c26581c.png)

![image](https://user-images.githubusercontent.com/94359491/201610918-e65b54f1-31b4-4a31-a84b-dbd2e2dfe68c.png)

![image](https://user-images.githubusercontent.com/94359491/201611174-9e847523-d8ce-43e7-ae74-77dff4b5cdec.png)


</details>

**Comment by aaemnnosttv** [comment] 2022-11-14 23:44
Recapping discussion about this one earlier it seems the only thing left here is the "Site Kit" portion of the logo getting cut off in viewports with a width < 375 px. For our smallest breakpoint we should hide this part of the logo.

Anything else to mention here @jimmymadon ?

**Comment by tofumatt** [comment] 2022-12-06 20:43
ACs here are good 👍🏻

**Comment by aaemnnosttv** [comment] 2022-12-08 01:33
IB ✅

**Comment by wpdarren** [comment] 2022-12-22 11:08
### QA Update: ✅ 

**Verified:**

-  Opened SK on mobile with a width <449px and the text part of a logo does not appear.
- Tested on the devices in the ticket and a few other Android and iPhone devices
- Tested on devices with different browsers, i.e. chrrome, firefox, and safari. 

![image](https://user-images.githubusercontent.com/73545194/209121034-ab53ce68-c3f8-40a3-aef0-11b43595f809.png)

**Closed** 2023-01-12 21:22 UTC
Labels: Type: Bug, P1, Rollover
