### ISSUE TITLE
Duplicate messages creating odd UX/UI when 2nd Admin user does not have access to Analytics

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#7004] opened 2023-05-03 14:52 UTC
## Bug Description

Bug found during testing #6224.  When you edit Analytics settings as a second admin user who does not have access to the Analytics account/property, a notice appears underneath the drop downs.  We now have red error messages appearing within the UI which in my opinion makes for an odd user experience.  

From chatting with Tom. 

> I think the new errors in red are appearing as a result of the work in https://github.com/google/site-kit-wp/issues/6831. It doesn't seem problematic to me, although we could discuss it on a separate issue to see if we'd like to prevent certain types of error messages from displaying when we're also showing the grey notices.

![image](https://user-images.githubusercontent.com/73545194/235952767-6af87f68-14fb-4a9e-823e-9b8106c452bd.png)

In my opinion, we should remove the red error messages when there are grey warning notices on the settings. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When a user without access to an Analytics account (like the 2nd user in this case) edits Analytics settings, requests that cause the red permissions error to appear (like in the screenshot) should not be made. Instead, only the messages in grey, below the account select, should appear.
* The red error messages in the GA4 and UA settings should not appear when a 2nd admin edits Analytics setting, with and without the GA4 Reporting feature flag enabled.

## Implementation Brief

* In `assets/js/modules/analytics/components/settings/SettingsForm.js`:
    * When fetching properties using `getProperties`, check if `hasAnalyticsAccess` OR `hasAnalytics4Access` are falsy in addition to the `accountID` check. 
* In `assets/js/modules/analytics/components/common/AccountSelect.js`:
    *  When fetching properties using `getProperties`, check if `hasModuleAccess` is falsy in addition to the `accountID` check. 
* In `WebDataStreamSelect.js` and `PropertyOrWebDataStreamNotAvailableError.js`:
    * When fetching `webDataStreams` using `getMatchingWebDataStreamsByPropertyID`, check if `hasModuleAccess` is not false in addition to the `isValidPropertyID( propertyID )` check. 

### Test Coverage

* No new tests required.

## QA Brief

* NOTE: QA this issue once both #7004 and #7005 have been merged since the below QAB will be very similar for both issues.
* Verify the ACs in the following scenarios:
    * With `ga4Reporting` feature flag disabled and UA is connected.
    * With `ga4Reporting` feature flag enabled and only GA4 is connected.
    * With `ga4Reporting` feature flag enabled and both GA4 and UA are connected.
* In addition to the ACs, verify the setup of UA and GA4 works with and without the `ga4Reporting` feature flag. Also, verify using an account with existing properties rather than only creating a new account / property on a new site.

## Changelog entry

* Prevent duplicate error messages from appearing in Analytics settings when another user does not have access to the Analytics account.

**Comment by tofumatt** [comment] 2023-05-05 16:51
IB ✅ 

Assigning to @jimmymadon since he's working on #7005 and they're closely related.

**Comment by aaemnnosttv** [comment] 2023-05-08 14:58
> I realised there are a few places in the code which completely hide the "Universal Analytics" toggle and settings if there are no properties available. I am not sure if this is desirable. I believe we would still want to show the toggle and the settings but they should be disabled like the rest of the settings.

@jimmymadon If the interface would otherwise include the toggle, then that means that UA wasn't already connected, so it wouldn't be possible to enable UA in this situation and the only enhancement to make here would be to show the toggle but in a disabled state. I don't think it would make sense to allow enabling it only to not be able to do anything (no point in toggling it only to reveal disabled controls).

I suppose rather than hiding the toggle entirely, we could render it in a disabled OFF state so that it wouldn't introduce loading-related layout shifts. Does that make sense?

**Comment by mohitwp** [comment] 2023-05-12 06:52
### QA Update ✅ 

**Verified** 

- The red error messages in the GA4 and UA settings are not appearing when a 2nd admin edits Analytics setting, with and without the GA4 Reporting feature flag enabled.
- Tested on dev environment.
- When 'ga4Reporting' feature flag is enabled and only GA4 is connected.
- When 'ga4Reporting' feature flag is enabled and both GA4 and UA is connected.
- Verified for both ga4 and UA dashboard view when 'Ga4Reporting' feature flag is enabled.
- Also when 'ga4Reporting' feature flag is not enabled.
- When 'ga4Reporting' feature flag is not enabled and only UA is connected.
- Also, done regression testing of analytics setup when 'ga4Reporting' feature flag is not enabled.

<details>

When 'ga4Reporting' feature flag is enabled and only GA4 is connected.

https://github.com/google/site-kit-wp/assets/94359491/1c401714-9af7-4a4a-98ff-ffa483af6829


When 'ga4Reporting' feature flag is enabled and both GA4 and UA is connected.

https://github.com/google/site-kit-wp/assets/94359491/4ba4d3ba-b947-44c7-a0c5-98b1b5a8f0f9


When dashboard view is UA.

https://github.com/google/site-kit-wp/assets/94359491/29db98c2-d564-492e-ac29-d25dd974f788


When 'ga4Reporting' feature flag is not enabled.

https://github.com/google/site-kit-wp/assets/94359491/6adc5962-e579-46a6-ae92-88b6b94eb5d7


When 'ga4Reporting' feature flag is not enabled and only GA4 is connected.

https://github.com/google/site-kit-wp/assets/94359491/0ff4a48e-8bcc-4b92-b524-12fb3d4429f4


</details>

**Comment by aaemnnosttv** [comment] 2023-05-18 18:23
LGTM 👍

**Closed by aaemnnosttv** 2023-05-18 18:23 UTC
Labels: Type: Bug, P1, Module: Analytics, UX, P1 Med
