### ISSUE TITLE
Analytics:  existing account not found, re-fetching account does not work 

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1575] opened 2020-05-19 01:14 UTC
## Bug Description

Several users have reported the Analytics module is not able to detect their existing accounts. Clicking "Re-fetch my account" also does not locate the account. 

-- Various browser console errors are on the request to connect the service (locale=user): _404_, _500_ (sometimes includes a _WP Error data in response, curl error 2_) 
-- Can happen in various hosting environments, but unable to replicate
-- Still occurs in an incognito browser

## Screenshots

**Console errors:**

![404 error re-fetch analytics](https://user-images.githubusercontent.com/8108643/82259796-fb212000-9910-11ea-9f70-6821b20a5a5b.jpg)

<img width="1238" alt="500 error re-fetch analytics" src="https://user-images.githubusercontent.com/8108643/82259401-5c94bf00-9910-11ea-9e0a-ba4977e77694.png">

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

related support topics/ issues:

https://wordpress.org/support/topic/problems-with-analytics/
https://wordpress.org/support/topic/google-kit-does-not-find-google-analytics-accoun/
https://github.com/google/site-kit-wp/issues/1569
(Site Health available in topics or through form)

#1548 might also be related

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by ernee** [comment] 2020-05-19 18:38
Another related topic: https://wordpress.org/support/topic/analytics-error-curl-erro-2-easy-handle-already-used-in-multi-handle/

Console error: 

```
Google Site Kit API Error 
{…}
​
code: "unknown"
​
data: {…}
​​
reason: ""
​​
status: 500
​​
<prototype>: Object { … }
​
message: "cURL error 2: easy handle already used in multi handle"
​
<prototype>: {…}
​​
__defineGetter__: function __defineGetter__()
​​
__defineSetter__: function __defineSetter__()
​​
__lookupGetter__: function __lookupGetter__()
​​
__lookupSetter__: function __lookupSetter__()
​​
__proto__: 
​​
constructor: function Object()
​​
hasOwnProperty: function hasOwnProperty()
​​
isPrototypeOf: function isPrototypeOf()
​​
propertyIsEnumerable: function propertyIsEnumerable()
​​
toLocaleString: function toLocaleString()
​​
toString: function toString()
​​
valueOf: function valueOf()
​​
<get __proto__()>: function __proto__()
​​
<set __proto__()>: function __proto__()
googlesitekit-api.js:1:11004
    g https://peacerivercampground.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-api.js?ver=1.8.0:1
    k https://peacerivercampground.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.js?ver=1.8.0:1
    _invoke https://peacerivercampground.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.js?ver=1.8.0:1
    e https://peacerivercampground.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.js?ver=1.8.0:1
    k https://peacerivercampground.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.js?ver=1.8.0:1
    e https://peacerivercampground.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.js?ver=1.8.0:1
    e https://peacerivercampground.com/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.js?ver=1.8.0:1
```

**Comment by ernee** [comment] 2020-05-22 21:39
Possible related topic: https://wordpress.org/support/topic/site-kit-connected-to-search-console-cant-complete-analytics-setup/

**Comment by vladarte** [comment] 2020-05-23 16:38
Same happened to me in Safari. Worked fine in Chrome

**Comment by jamesozzie** [comment] 2020-05-25 08:34
@ernee Sounds similar to #1548

**Comment by cole10up** [comment] 2020-07-13 06:59
**Tested**

Ran a series of tests around Analytics setup and re-fetching my account. Was unable to reproduce this with the latest 1.11.1 release.

Sending to L2.

**Comment by ernee** [comment] 2020-07-14 01:47
Just noting here that we're suspecting some of these issues to be related to this issue with Guzzle: https://github.com/guzzle/guzzle/issues/2617

**Comment by eugene-manuilov** [comment] 2020-07-24 14:45
@felixarntz I haven't able to reproduce this issue either. After researching it a little bit, I tend to say that it is not our issue at all. This seems to be cURL related problem that happened on some hosting poviders like GoDaddy or its resellers. See this [comment](https://wordpress.org/support/topic/curl-error-2-easy-handle-already-used-in-multi-handle/page/3/#post-12797482) for reference.

Plus, it looks like this issue has stopped appearing for folks that makes me think that it might be already fixed by hosting providers and we have nothing to do here. Assigning this to you to make a decision what to do next with it.

**Comment by felixarntz** [comment] 2020-07-29 00:36
@ernee This issue (like the other cURL issues we've been seeing) are most likely out of our control. We're working on detecting this problem early on, per #1549, so that users should be informed before even setting up Site Kit. Let's keep an eye on these issues and support threads and inform the reporters that this is likely a host-specific problem, and we're working on some changes to detect it earlier.

**Closed by felixarntz** 2020-07-29 00:36 UTC
Labels: Group: Escalation, Type: Bug

**Comment by jamesozzie** [comment] 2020-08-11 17:03
Downgrading the libcurl version resolved this issue for one user, as reported [here](https://wordpress.org/support/topic/error-curl-error-2/#post-13237544).
