### ISSUE TITLE
JS error on setup screen

### ISSUE THREAD

**Issue by swissspidy** [google/site-kit-wp#808] opened 2019-11-07 10:12 UTC
## Bug Description

When resetting the plugin and opening the setup screen, there is a JS error in the console.

## Steps to reproduce

1. Reset Site Kit
2. Open Site Kit setup screen
3. See error

## Screenshots

![Screenshot 2019-11-07 at 11 08 18](https://user-images.githubusercontent.com/841956/68380042-619dd800-014f-11ea-85b0-6699bed143b2.png)

## Additional Context

 - PHP Version: 7.2
 - Browser: Chrome on macOS
 - Plugin Version: 1.0.1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be no JS console errors on the setup screen after resetting the plugin.

## Implementation Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment] 2019-11-11 21:29
I wasn't able to reproduce this bug in Firefox or Chrome on Mac OS using either the latest `develop` branch or the `1.0.1` tag, as reported here when run using `npm run watch`. I'm going to try building a zip and seeing if I can recreate the error, but I also don't find reference to `alignToolTip` anywhere in our codebase or the property `.top` anywhere in our codebase. I tried with both the developer set up flow and the proxy set up flow. Here's me resetting in Chrome:

![2019-11-11 21 25 50](https://user-images.githubusercontent.com/90871/68622493-2a6e5480-04ca-11ea-9a9e-75fefdd9a95f.gif)

**Comment by tofumatt** [comment] 2019-11-11 21:50
I just installed the release ZIP of 1.0.1 on a new Jurassic Ninja site, followed the steps here, and did not get the error.

I don't think there's an issue with the plugin set up screen; I'm not able to reproduce the issue here.

**Comment by tofumatt** [comment] 2019-11-13 12:35
I'm still not able to reproduce this locally or on a new site. If this is still happening and you can provide specific steps to reproduce we should open this back up, but closing for now as I can't reproduce the issue and haven't seen other reports of it.

**Closed by tofumatt** 2019-11-13 12:35 UTC
Labels: P1, Type: Bug
