### ISSUE TITLE
Release 1.49.0

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4633] opened 2022-01-11 06:47 UTC
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Release is prepared, tested, and deployed to wordpress.org.

## Implementation Brief

* N/A

## QA Brief

* N/A

## Changelog entry

* N/A

**Comment by wpdarren** [comment] 2022-01-14 14:15
### QA Update: ❌ 

@aaemnnosttv @felixarntz Found an issue that doesn't exist in latest release. 

For Idea Hub, when you're on the Draft tab, and then click `View draft` link, you are redirected to the post editor, but a 404 message appears in the console and the notification that should appear in the editor does not load. 

`GET https://dayura.us2.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-idea-hub-notice.js?ver=1.49.0 net::ERR_ABORTED 404`

https://user-images.githubusercontent.com/73545194/149529159-73300bfe-3cde-49bc-a474-1236d734d359.mp4

**Comment by felixarntz** [comment] 2022-01-14 14:27
@wpdarren I also discovered this and flagged it in https://github.com/google/site-kit-wp/issues/4107#issuecomment-1013062547, since that issue is likely the cause.

**Comment by techanvil** [comment] 2022-01-14 15:53
## QA :white_check_mark:
* Smoke tested.
* Verified the changes I've been involved with.
* Performed some ad-hoc testing.

**Comment by wpdarren** [comment] 2022-01-14 16:09
### QA ✅ 

LGTM.  Completed our QA checklist.

**Comment by mohitwp** [comment] 2022-01-14 16:43
### QA ✅ 

Completed our QA checklist.

**Comment by hussain-t** [comment] 2022-01-14 17:58
### QA ✅ 

- Completed smoke testing
- Verified the changes I have executed
- Performed some ad-hoc testing

**Comment by kuasha420** [comment] 2022-01-15 00:07
# QA: :heavy_check_mark: 

Went through the release checklist. All the outstanding issues that were raised last minute has been fixed and changes merged to `main`. 

LGTM. :+1:

**Comment by jimmymadon** [comment] 2022-01-16 14:10
## QA :white_check_mark:
* Followed Release QA / Smoke testing guidelines.
* Verified the issues I was involved with.

LGTM!

**Closed** 2022-01-17 19:15 UTC
Labels: P0, Type: Task, Rollover
