### ISSUE TITLE
Browser navigation is broken after selecting different tabs in the ideas widget

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#3796] opened 2021-08-03 15:11 UTC
## Bug Description

When I switch tabs in the ideas widget multiple times, my browser history is full of similar records with just different hashes. It causes a bad user experience because if I want to go back to the previous page, I'll need to click on the back button the same number of times that I switched tabs. Plus, when I click back and the URL changes to the previous one (with a different hash), the selected tab in the ideas widget doesn't change.

We need to either update tabs in the ideas widget to follow the hash changes or update how we change hashes to avoid generating duplicate records in the browser history.

https://user-images.githubusercontent.com/873049/128038754-267dd890-58a1-4116-95f1-7c1c2bcc5542.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Changing tabs on the Idea Hub dashboard widget should not add new items to the browser history
   * I.e. clicking "Back" should invoke a page navigation rather than a hash change

## Implementation Brief

Using the files from the existing open `react-use` PR https://github.com/streamich/react-use/pull/1435
 
1. Create `assets/js/hooks/useHash.js`
1. Copy the contents of https://github.com/streamich/react-use/blob/ed831e6db478d739d3638a8efca37418aba1328e/src/useHash.ts into this file
1. Remove the TypeScript typings
1. Fix the imports (need to import dependency hooks from `react-use`)
1. Fix eslint warnings (`window` should be `global`)

The code should now build.

In `assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js`
1. Import new `useHash` hook (instead of from `react-use`)
1. Where `setHash` is used, pass in `false` as a new second argument

See this all done on existing PR https://github.com/google/site-kit-wp/pull/3862

### Test Coverage

* Copying existing tests from PR to new `assets/js/hooks/useHash.test.js` https://github.com/streamich/react-use/blob/ed831e6db478d739d3638a8efca37418aba1328e/tests/useHash.test.ts
* Fix the imports (need to import `useHash` from the same folder)
* Fix eslint warnings

### Visual Regression Changes

* None

## QA Brief

* Visit any page that is not the Site Kit dashboard
* Navigate to the Site Kit dashboard by the menu bar
* Change tabs on the Idea Hub widget
* Observe that the query param has updated in the browser URL
* Use the back button
* Observe that the back button works as expected and goes back to the previously visited page

## Changelog entry

* Prevent Idea Hub tab navigation from adding to the browser's history.

**Comment by aaemnnosttv** [comment] 2021-08-04 14:42
@eugene-manuilov the problem is due to the way `setHash` works. See https://github.com/streamich/react-use/issues/1434. cc: @tofumatt 

The maintainers are open to a change that allows for replacing the history on set, but that PR seems to have stalled out. Should we roll our own `useHash` in the meantime? It seems like a fairly straightforward hook 🙂

**Comment by eugene-manuilov** [comment] 2021-08-04 15:40
> Should we roll our own useHash in the meantime? It seems like a fairly straightforward hook

I wish we could get rid of that `setHash` hook completely and just use vanilla javascript to get and set hashes.

**Comment by aaemnnosttv** [comment] 2021-08-05 11:11
@eugene-manuilov we don't have to use `useHash` but it is a nice wrapper around getting and setting the hash. I've added ACs so we can look into alternate solutions in the IB.

**Comment by danielgent** [comment] 2021-08-12 17:28
I've just taken the `useHash` from that openPR, got rid of the TypeScript typings, fixed the imports and eslint warnings, and it works


https://user-images.githubusercontent.com/8496063/129239573-f2005782-8a77-4993-bf23-ecedfaf03a2a.mp4

I'll put this into an IB now and link to the `useHash` in that PR as it currently is (the current commit, just in case any changes are made).

**Comment by tofumatt** [comment] 2021-08-17 09:35
Given the implementation here is already done and there is some urgency to Idea Hub tickets, I think this IB/approach is worth merging, but I agree with @eugene-manuilov that we should ditch this hook.

In this case, we should be using React Router here—if we were, it'd be quite straightforward to make this change to replace the history rather than add the hash to the stack as well.

Looking at the component, changing it to use a router would be quite straightforward, but it's still more effort than what's already here. I think this is the one hash that was in-progress during the huge React Router merge and I meant to get it… but never did 😓 . I've created #3886 for said issue 🙂 

So let's use this fix for now in the interest of time, but fix it properly using a router in the future.

IB ✅

**Comment by tofumatt** [comment] 2021-08-17 21:35
For what it's worth I took a look at re-implementing Idea Hub's widget with React Router and it was quite straightforward.

We might be able to close this with #3897 instead, fwiw.

**Comment by aaemnnosttv** [comment] 2021-08-19 07:47
Thanks @tofumatt – do you think this would make it easier to transition to the generic dashboard? If so then I think that's a bit more of a case to go this route now, otherwise if it makes more work later then let's not 😄

**Comment by tofumatt** [comment] 2021-08-19 18:06
It certainly doesn't make it any _more_ effort to convert, and could possibly ease the transition. Worst case it's a wash, but given it won't complicate the generic dashboard implementation I say we go for it 😄

**Comment by tofumatt** [comment] 2021-08-23 11:59
Update: #3886 is a cleaner and more complete implementation that solves this issue and removes the `useHash` hook. Given it's largely ready for CR already, I'm leaving this in CR with me but I think #3886 will fix this issue.

**Closed** 2021-09-27 19:34 UTC
Labels: Type: Bug, P1, Rollover, Module: Idea Hub
