### ISSUE TITLE
Successful set up banner icon is small as compare to Figma design

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5934] opened 2022-09-27 20:09 UTC
Asana bug bash task: https://app.asana.com/0/1202913874897532/1203046400278414

Successful set up banner icon is small as compare to Figma design. It is looking very small and cornered on big screens.

![image (11)](https://user-images.githubusercontent.com/93320881/192625415-4719017a-5895-49e5-8ba5-ed0b94c30b12.png)
![image (12)](https://user-images.githubusercontent.com/93320881/192625432-0ed44cb1-6a27-4c11-ab75-144c52032c8a.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The image size for the Success Banner should be increased as per the [Figma design](https://www.figma.com/file/vMaCWwr6lpk4PrJWb7jIpz/GA4-Banner-Input?node-id=1082%3A1901).  
* Additionally, the image should appear besides (and not above) the title as shown in [Figma for mobile](https://www.figma.com/file/vMaCWwr6lpk4PrJWb7jIpz/GA4-Banner-Input?node-id=1082%3A2478) screen sizes.
* These changes should apply to all icons for every success banner, not just the Thank with Google ones. See @sashadoes's comment below: https://github.com/google/site-kit-wp/issues/5934#issuecomment-1277966586
  * Essentially, the success banners should be consistent regarding icon size/placement, in line with what's in the Figma design for Thank with Google.

## Implementation Brief

* Inside `BannerNotification` https://github.com/google/site-kit-wp/blob/48952f8f09ed585bb3b6b1cf3fd4fd7f88b4fafc/assets/js/components/notifications/BannerNotification/index.js#L266-L272
* Place a new block with `WinImageSVG` next to the `.googlesitekit-publisher-win__title` wrapper (containing the title and the badge) and make it visible only on mobiles. At the same time, the "original" `WinImageSVG` should be hidden for mobiles. With this scenario FE will show "original" `WinImageSVG` on tablet+ screens and "small" `WinImageSVG` on mobiles.
* Wrap`.googlesitekit-publisher-win__title` block and `WinImageSVG` in a new `flex` container and make them inline as on design
* `WinImageSVG` should be styled as per the Figma designs. (`105px` `height` on tablet+ screens and `72px` on mobiles)
* If there's no `WinImageSVG` provided, the wrapper containing the title and the badge should expand to be `100%` wide

### Test Coverage
* Add a new scenario to VRT suite (if not already present)
* VRT images will need to be updated

## QA Brief
* Trigger the setup success banner by setting up a new module, or access the following URL if module is already set up: `/wp-admin/admin.php?page=googlesitekit-dashboard&notification=authentication_success&slug=analytics#traffic`
* Ensure the SVG within the banner is besides the title on small screens with an updated size.
* Setup all modules to ensure there are no regressions.
* Note that the dimensions in the Figma designs are incorrect based on existing SVGs we have. The height should be 75px on small screens and 105px on large ones, with the width set automatically.

## Changelog entry

* Increase size of banner icons in setup notification.

**Comment by tofumatt** [comment] 2022-10-12 19:50
ACs look good, moving this to IB.

**Comment by sashadoes** [comment] 2022-10-13 17:46
Hi @FlicHollis. 
Checked the implementation for this one. 
I see that FE uses one implementation for several success banners. 
So eg. for `Add a Thank with Google supporter wall` banner we have the same appearance on mobiles.
<img width="502" alt="Screenshot 2022-10-13 at 18 12 32" src="https://user-images.githubusercontent.com/16494321/195668620-393c0fb3-9058-4cf9-9043-514079c0332c.png">
Do we need to fix it as part of this ticket?
Thanks in advance!

cc @EvanHerman @tofumatt

**Comment by aaemnnosttv** [comment] 2022-10-13 18:03
@sashadoes you're asking if this should apply to all success banners or just the one for TwG? If so, I believe the change should be consistent for all rather than only for TwG. I think that should make it a bit more straightforward to do as well. Was that your understanding as well @tofumatt ?

**Comment by tofumatt** [comment] 2022-10-13 19:10
I didn't actually realise the other banners were off as well, but I think fixing any other affected banners that use the same/similar code/styles makes sense to do as part of this issue, yes 👍🏻 

So let's make all of the banners consistent as part of this issue. I've amended the ACs, let me know if something is off but otherwise should be ready for an IB 🙂

**Comment by sashadoes** [comment] 2022-10-17 17:40
Hi @EvanHerman and @tofumatt. 
After some time spent on this, I came up with 2 possible ways to fix it. I would like to ask you for a review and advice as it seems to be more complex than just tweaking styles. The approaches are down below: 

1. Change the `BannerNotification` layout: create a new block (eg `Header`) where place `WinImageSVG`https://github.com/google/site-kit-wp/blob/develop/assets/js/components/notifications/BannerNotification/index.js#L455-L469 next to the `title` https://github.com/google/site-kit-wp/blob/develop/assets/js/components/notifications/BannerNotification/index.js#L267-L271inside `<Row>/<Cell>`. Then adjust the `getContentCellSizeProperties`& `getImageCellSizeProperties` helpers to work with new layout.  This looks like a good option, but we should `WinImageSVG` a 0px height for the tablet+ screens in order to avoid unnecessary space under the title before the description. 
<img width="1291" alt="Screenshot 2022-10-17 at 18 31 56" src="https://user-images.githubusercontent.com/16494321/196244878-a08d15e4-24f2-4ee0-805d-35a3747673a5.png">
Alternatively,  FE can use `grid-template-areas` in order to recompose grind blocks for different screens.

4. Place an extra block with `WinImageSVG` next to `title` and make it visiable *only* in mobiles. On the same time the "origianl" `WinImageSVG` should be hidden for mobiles. With this scenarion FE will show "origianl" `WinImageSVG` for desctops + tablets and "small" `WinImageSVG` for mobiles.

Also, I would consider breaking down `BannerNotification` into smaller and more dedicated layout components. As the 545 line component which serves so many cases looks not so easy to support and adjust.

**Comment by tofumatt** [comment] 2022-10-17 18:53
The `0px` height trick strikes me as a _bit_ of a CSS hack; I'd prefer us avoid them whenever possible. 🙂 

In this case, using different markup for mobile/non-mobile viewports is fine with me if it's just imagery and not actual content, which it seems to be here.

So I think I'm more a fan of number 2 👍🏻 

In terms of refactoring the component into smaller chunks—fair point, but we should probably do that as a separate issue so we can review the refactoring separately from this fix 🙂

**Comment by asvinb** [comment] 2022-10-18 08:52
+1 for the second option @sashadoes

**Comment by asvinb** [comment] 2022-10-19 13:06
@sashadoes Thanks for the IB and I suggest we make the following tweaks to it:
* Let's avoid putting code in the IB as it can prompt the engineer working on the code to just copy and paste, and the IB reviewer will tend to CR the code at the IB stage. For e.g we are trying to avoid nesting CSS selectors within media queries.
* About the comment to implement option 2, instead having the engineer to go through the list of comments, can you copy over the approach within the IB?
* About the following:
	> Inside BannerNotification put a new WinImageSVG block next to title
	* Can you be more explicit (without the code), and rather mention putting `WinImageSVG` next to the wrapper containing the title and the badge? Reading the IB, I thought we should put `WinImageSVG` next to the `title` variable.
* Instead of using `display: inline-block`, how about we use `flex` on the parent element and the set the `googlesitekit-publisher-win__title` to grow if there's no `WinImageSVG`.
* Why should we set the `height` of `WinImageSVG` to `120px`? :thinking: [Checking at the designs](https://www.figma.com/file/vMaCWwr6lpk4PrJWb7jIpz/GA4-Banner-Input?node-id=1082%3A1904), I noticed the icon is `105px`. Let me know if am missing something here :grin: .
* About the tests needed, I don't think we need unit tests, rather we should add a new scenario to our VRT suite (if not already present). Most likely since it's a global change, VRT images will need to be updated.

**Comment by sashadoes** [comment] 2022-10-19 21:35
Thanks, @asvinb for your feedback. I have updated the IB.

**Comment by asvinb** [comment] 2022-10-20 07:20
Thanks @sashadoes . A few more tweaks:

1. Can you update the "Test Coverage" section to remove unit tests and instead add scenarios within the VRT suite?
2. Let's make sure that if there's no `WinImageSVG` provided, the wrapper containing the title and the badge should expand to be 100% wide.
3. Can you let me know about the height of the SVG? As per my previous comment, the height is 105px, but in the IB you suggested 110px.

Thanks!

**Comment by asvinb** [comment] 2022-10-21 10:59
@sashadoes IB looks good. However can you let me know about the following?
> Can you let me know about the height of the SVG? As per my previous comment, the height is 105px, but in the IB you suggested 110px.

**Comment by sashadoes** [comment] 2022-10-21 23:40
@asvinb I changed it to `105px` 🙂

**Comment by asvinb** [comment] 2022-10-25 09:17
Thanks @sashadoes . LGTM. For future IBs, instead of adding the height and width of the SVGs in the IB, you can just say to style the SVG as per the designs in Figma (which I added in the designs). That'll reduce confusion and the designs will be the single source of truth :)

**Comment by asvinb** [comment] 2022-10-25 09:18
IB 👍

**Comment by mohitwp** [comment] 2022-11-09 11:06
### QA Update ❌ 

Thank you @wpdarren 

@sashadoes @asvinb 

Apart from the issue reported [above ](https://github.com/google/site-kit-wp/issues/5934#issuecomment-1307469932) by Darren. I've found that Idea hub set up banner image is got tiny on develop. Let me know if this is not due to changes introduced in connected PR.

![image](https://user-images.githubusercontent.com/94359491/200814158-882c4784-6e64-4ffb-9812-0d47eae49f8d.png)

**Comment by asvinb** [comment] 2022-11-09 13:28
@tofumatt Can you review [followup PR](https://github.com/google/site-kit-wp/pull/6127) please? Basically there was a CSS regression but most importantly the [Idea Hub notification](https://google.github.io/site-kit-wp/storybook/main/?path=/story/modules-idea-hub-notifications-promptbannernotification--ready) is different from other notifications due to the large SVG. Not sure if we can have the notification consistent with the other ones since that'll mean a new SVG.
Let me know what you think

**Comment by mohitwp** [comment] 2022-11-14 07:34
### QA Update ❌ 

**Issues**

1. On dev Idea hub setup banner SVG looking bigger than latest and orange part of Image is missing in both banner and widget.
2. In mobile banner svg looking very small.

<details>

dev

![image](https://user-images.githubusercontent.com/94359491/201600144-e2369997-d30f-48cb-b26e-a20b46e1a4b4.png)

![image](https://user-images.githubusercontent.com/94359491/201600195-348e5cee-9949-41fc-8f14-c1d165d3c851.png)

![image](https://user-images.githubusercontent.com/94359491/201600595-a1101e92-c647-4a8f-8504-39bff915bc0a.png)


**latest-**

![image](https://user-images.githubusercontent.com/94359491/201600755-fb3fd467-d5cd-49c4-bb44-8a85720aa7e8.png)

![image](https://user-images.githubusercontent.com/94359491/201600993-f5368e7e-ec7d-4c10-8fc5-7974b7c66c61.png)

![image](https://user-images.githubusercontent.com/94359491/201600396-6d15f8b1-7eff-48e3-871b-25c6471da620.png)

</details>

**Comment by aaemnnosttv** [comment] 2022-11-15 16:48
Back to you for another pass @mohitwp 👍

**Comment by mohitwp** [comment] 2022-11-16 14:00
### QA Update ✅ 

Verified on main branch.
Verified all success set up banners, Idea hub set up banner and GA4 banners.
Issues reported above are now resolved.
Idea hub set up banner is looking fine on desktop and mobile.

<details>

![image](https://user-images.githubusercontent.com/94359491/202190002-c4c85340-efeb-4ab7-a439-ef2f8d633c78.png)

![image](https://user-images.githubusercontent.com/94359491/202190064-4a74070a-907b-4693-9d56-bebabe323fd1.png)

![image](https://user-images.githubusercontent.com/94359491/202190121-2a881397-4d45-4531-ab8f-b053daa4b5fd.png)

![image](https://user-images.githubusercontent.com/94359491/202190247-6bef61cf-e88e-43e9-a852-4d59ff620b3a.png)

![image](https://user-images.githubusercontent.com/94359491/202190667-b7b83ee2-151f-47a5-a5f0-24cd6dc8573b.png)

![image](https://user-images.githubusercontent.com/94359491/202190735-716c02c5-781f-4b7b-a1ab-95570ae9fd6d.png)

![image](https://user-images.githubusercontent.com/94359491/202192782-3942df66-7d68-44b2-b6e2-e38f052efc63.png)

![image](https://user-images.githubusercontent.com/94359491/202193093-08d4e799-00e6-4256-b38f-66da76be64f4.png)

![image](https://user-images.githubusercontent.com/94359491/202193156-1ee517f5-4439-4074-bfd1-3611b2d1b892.png)

![image](https://user-images.githubusercontent.com/94359491/202193397-ae30d44c-7842-4aec-b3ed-e89b4bc60bdf.png)

![image](https://user-images.githubusercontent.com/94359491/202199273-d11c8999-5bf4-4cea-8cec-6981b109f664.png)

![image](https://user-images.githubusercontent.com/94359491/202199375-c5f0afe0-80db-4412-8997-447ea95303ea.png)

![image](https://user-images.githubusercontent.com/94359491/202199492-26dcddfb-ab53-4495-ba4e-907248941048.png)

![image](https://user-images.githubusercontent.com/94359491/202200501-50566f3d-5f42-4c78-a73d-0cfb3a8e344c.png)


</details>

**Closed** 2022-11-17 16:12 UTC
Labels: Type: Bug, P2
