### ISSUE TITLE
Pageviews not triggered for Universal Analytics - with Newspack plugin & Campaigns extension

### ISSUE THREAD

**Issue by yogeshbeniwal** [google/site-kit-wp#3764] opened 2021-07-27 09:43 UTC
## Bug Description

Latest update seems to be resulting in Universal Analytics code not sending PageViews. GA4 is working fine.

## Steps to reproduce

With Newspack Plugin activated

```javascript
window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}
gtag("js", new Date());
gtag("set", "developer_id.xxxxxxx", true);
gtag("config", "UA-xxxxxxxxx-1", {"send_page_view":false,"dimension1":"category","dimension2":"Author","dimension3":175,"dimension4":"2021-07-19 20:05"});
gtag("config", "G-xxxxxxxxxx");
```

With Newspack Plugin deactivated

```javascript
window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}
gtag("js", new Date());
gtag("set", "developer_id.xxxxxxx", true);
gtag("config", "UA-xxxxxxxxx-1", {"send_page_view":false});
gtag("config", "G-xxxxxxxxxx");
```

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment] 2021-07-27 18:39
This is reproducible support side. Steps to recreate:

1. Install & activate the [Newspack Plugin](https://github.com/Automattic/newspack-plugin/releases/tag/v1.49.0) (1.49.0 current version) on a site that already has Site Kit active  - with the Analytics module active & the UA tracking snippet inserted via Site Kit
2. Activate the [campaigns extension](https://i.imgur.com/3I7ZVn7.png) (formerly "Newspack popup") from with the Newspack sub plugin options
3. The default Analytics snippet is modified. `{"send_page_view":false});` is added, while other features remain active. The Site Kit developer ID remains the same. 

Note that the below is also removed upon activating the Campaigns extension: 
`gtag('set', 'linker', {"domains":["example.com"]} );`

Setting up the campaigns in full does require [additional steps](https://github.com/Automattic/newspack-popups/blob/master/README.md#config-file) however even after doing so the snippet remains modified, with no page hits being tracked. 

In my case see below:

_SK Analytics snippet before Newspack with the campaigns plugin active below_ 

```
<script type='text/javascript' src='https://www.googletagmanager.com/gtag/js?id=UA-200719916-1' id='google_gtagjs-js' async></script>
<script type='text/javascript' id='google_gtagjs-js-after'>
window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}
gtag('set', 'linker', {"domains":["sitename.com"]} );
gtag("js", new Date());
gtag("set", "developer_id.dZTNiMT", true);
gtag("config", "UA-200719916-1", {"anonymize_ip":true});
gtag("config", "G-EBP3TGYXRC");
</script>

```
_SK Analytics snippet after Newspack with the campaigns plugin active below_ 

```
<script type='text/javascript' id='google_gtagjs-js-after'>
window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}
gtag("js", new Date());
gtag("set", "developer_id.dZTNiMT", true);
gtag("config", "UA-200719916-1", {"send_page_view":false});
gtag("config", "G-EBP3TGYXRC");
</script>
```

**Comment by eugene-manuilov** [comment] 2021-07-28 14:53
@yogeshbeniwal looks like this is expected behavior for the Newspack Campaigns plugin. That plugin intentionally disables page view tracking when a certain condition is met. See comments in the plugin source code [here]( 
https://github.com/Automattic/newspack-popups/blob/master/includes/class-newspack-popups-segmentation.php#L59-L67).

We can't do anything with that. So I would recommend you to reach out to the Newspack Campaigns development team to help you figure out what needs to be done to re-activate page views tracking.

cc @jamesozzie

**Comment by eugene-manuilov** [comment] 2021-07-28 14:55
@jamesozzie @bethanylang I think we can close this ticket.

**Comment by eugene-manuilov** [comment] 2021-07-28 16:41
@adamsilverstein Evan said that you worked with Newspack plugins and may help with it. Do you mind taking a look at this ticket too? Maybe you have a quick solution for the reported issue.

**Comment by adamsilverstein** [comment] 2021-07-28 18:23
Sure @eugene-manuilov. As you stated, I believe this is the expected behavior in Newspack based on the source code. I'm not sure what the reasoning is, @adekbadek may be able to tell us why this is set up this way.

@yogeshbeniwal - is this a new issue in recent Site Kit versions, or something generally affecting Newspack with Site Kit? 

Based on this issue - https://github.com/Automattic/newspack-popups/issues/102 - it looks like page views were previously being counted more than once.

I agree with @eugene-manuilov - we can close this issue. If there is something to change here, that would need to happen in the campaigns plugin in Newspack, not in Site Kit. @yogeshbeniwal if you feel   tis is still an issue, can you please open a new issue on the Campaigns plugin repo?

**Closed by adamsilverstein** 2021-07-28 18:23 UTC
Labels: Group: Escalation, Module: Analytics, Type: Support, wontfix

**Comment by adekbadek** [comment] 2021-07-28 19:33
> I'm not sure what the reasoning is, @adekbadek may be able to tell us why this is set up this way.

Newspack Campaigns is gathering data about visitors, and that data is sent as custom dimensions to GA. To do that, the plugin takes over the page view reporting - in order to append some custom dimensions values to the pageview. It's true that if plugin is active but not yet configured, this will break pageview reporting. Opened https://github.com/Automattic/newspack-popups/issues/591

**Comment by adamsilverstein** [comment] 2021-07-28 19:54
Excellent, thank you @adekbadek!
