### ISSUE TITLE
Remove Analytics module as requirement for Tag Manager module

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1380] opened 2020-04-13 17:49 UTC
## Feature Description

It should not be mandatory for the Analytics module to be set up before being able to set up the Tag Manager module.

**PR for this should be opened against `feature/ga-gtm-separation`.**

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Tag Manager should no longer have the Analytics module as a dependency.
* All messaging related to this dependency should no longer be visible.

## Implementation Brief

* In `includes/Modules/Tag_Manager::setup_info` remove the `depends_on` array entry.
* in `assets/js/components/setup-module.js` capture the name of `requiredModule` and display it via a placeholder in where the text is currently displayed as `Set up Analytics to gain access to %s`

## QA Brief

* 

## Changelog entry

* Remove Analytics module as requirement for Tag Manager module, decoupling them to be individual.

**Comment by aaemnnosttv** [comment] 2020-05-06 08:08
A little context to help with the definition here: Site Kit has the concept of dependencies between modules. Currently Tag Manager can only be activated after Analytics is activated because it declares Analytics as a dependency in `Tag_Manager::setup_info`.

This is used on the client side in a few places:
https://github.com/google/site-kit-wp/search?q=requiredModule&unscoped_q=requiredModule

Most of the behavior is not specific to Analytics, but there is some Analytics specific messaging. This messaging should become dynamic rather than assuming any module that is blocked by a parent needs Analytics 😄 

Analytics is also a dependency for Optimize, although I'm not sure why. @felixarntz is this still necessary?

**Comment by felixarntz** [comment] 2020-05-06 14:42
@aaemnnosttv Thanks for providing some extra context here.
> Analytics is also a dependency for Optimize, although I'm not sure why. @felixarntz is this still necessary?

I don't think so, but let's look at that separately. Not as big of a priority to decouple.

**Comment by aaemnnosttv** [comment] 2020-05-12 17:14
✅ IB

**Comment by ShahAaron** [comment] 2020-05-14 18:05
@felixarntz should I just replace the work `Analytics` in the text `Set up Analytics to gain access to %s` with the required module ?

**Comment by aaemnnosttv** [comment] 2020-06-11 15:43
PR is merged but not adding a release here as it is still only targeting a feature branch.

**Comment by cole10up** [comment] 2020-06-17 15:36
**Tested**

Built a feature/ga-gtm-separation zip

Installed SK and activated.

Notice dashboard shows Tag Manager separate and available to install outside of Analytics:
![image](https://user-images.githubusercontent.com/57115907/84916356-d5ec1280-b072-11ea-9c14-22878222298b.png)

Checked alignment of the icons:
![image](https://user-images.githubusercontent.com/57115907/84917307-fff20480-b073-11ea-9826-54809f6a3714.png)

Confirming setup of Tag manager without Analytics:
![image](https://user-images.githubusercontent.com/57115907/84917443-32036680-b074-11ea-8907-466434dd4eb4.png)

![image](https://user-images.githubusercontent.com/57115907/84917468-3a5ba180-b074-11ea-91ba-cf4db8d8af44.png)

Tested setting up Analytics prior to Tag Manager:
![image](https://user-images.githubusercontent.com/57115907/84917581-5d865100-b074-11ea-83a8-80a8ba1e7c31.png)

Confirmed functionality of snippet:
![image](https://user-images.githubusercontent.com/57115907/84917686-7c84e300-b074-11ea-8901-ca6cb14f2d89.png)

![image](https://user-images.githubusercontent.com/57115907/84917807-a807cd80-b074-11ea-90ad-42de634401d9.png)

Confirmed editing Tag Manager without Analytics functions properly:
![image](https://user-images.githubusercontent.com/57115907/84918032-f61cd100-b074-11ea-85a1-04bdc6e736a8.png)

Confirmed disconnecting module functions properly

Checking setup from Settings page:
![image](https://user-images.githubusercontent.com/57115907/84918236-2f554100-b075-11ea-8b5f-cf103fb56ca0.png)

Confirmed Tag manager is able to be setup outside of Analytics from settings page:
![image](https://user-images.githubusercontent.com/57115907/84918310-4b58e280-b075-11ea-96e8-76a11e49327b.png)

Ran exploratory testing canceling or hitting the back button to stall the setup:
![image](https://user-images.githubusercontent.com/57115907/84918430-6fb4bf00-b075-11ea-8bc7-dd367dd849f0.png)

![image](https://user-images.githubusercontent.com/57115907/84918451-76dbcd00-b075-11ea-847e-255a6af339d6.png)

![image](https://user-images.githubusercontent.com/57115907/84918480-7e9b7180-b075-11ea-9e5c-8ae16a352d7b.png)

Confirmed all cases function.

Passed QA ✅

**Closed** 2020-10-12 19:42 UTC
Labels: Good First Issue, P1, Type: Enhancement
