### ISSUE TITLE
Site Kit adding duplicate GTM Snippet

### ISSUE THREAD

**Issue by abdullah1908** [google/site-kit-wp#3789] opened 2021-08-02 06:25 UTC
## Bug Description
As per the [user on WordPress Support](https://wordpress.org/support/topic/site-kit-inserting-inappropriate-gtm-tags/) reported Site Kit doesn't recognize already added snippet & adds additional snippet while setting up GTM through Site Kit. I can [reproduce this issue](https://www.loom.com/share/40cbcd1bd0464a148f21d56d16e934c4) at my end as well.

## Steps to reproduce

1. Add manual GTM snippet in theme's header `<head>`
2. Setup GTM through Site Kit
3. You'll see messaging for already existing snippet.
4. While proceeding to next step Site Kit adds the snippet on setup completion. 

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment] 2021-08-02 09:19
Thanks Abdullah, I can confirm the same using a basic Tag Manager setup with only a custom HTML tag. Site Kit does recognise the manually inserted snippet, so the issue is that _**it also inserts**_ an additional Tag Manager snippet. 

![2021-08-02-10-14-33](https://user-images.githubusercontent.com/41326532/127836532-dda42f94-df2b-4c3a-9caa-819d3c2ccbdc.gif)

A temporary workaround is to revisit your Tag Manager settings and toggle off the "Let Site Kit place code on your site" setting, to ensure duplicate Tag Manager snippets are not inserted.

**Comment by aaemnnosttv** [comment] 2021-08-03 15:28
@jamesozzie @bethanylang this looks like a duplicate of #3338 – if so, let's close it accordingly and add any additional context to that one 👍

**Comment by bethanylang** [comment] 2021-08-03 15:37
Thanks @aaemnnosttv! @abdullah1908 Please add any additional details to #3338. Closing.

**Closed by bethanylang** 2021-08-03 15:37 UTC
Labels: Module: Tag Manager, Type: Bug, Type: Support
