### ISSUE TITLE
Add options to manage tracking internal traffic from Analytics

### ISSUE THREAD

**Issue by ernexto** [google/site-kit-wp#536] opened 2019-09-14 16:06 UTC
## Feature Description

Hello guys, is it possible to add an option to exclude internal (users logged in) traffic from Analytics?

![2019-09-14_180434](https://user-images.githubusercontent.com/48352699/64910737-21efdc80-d71a-11e9-8e29-aa8d01c83d00.jpg)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment] 2021-04-05 19:18
Duplicate of #88 (i.e. this has been in place since Site Kit 1.1.0).

**Closed by felixarntz** 2021-04-05 19:18 UTC
Labels: Type: Enhancement
