### ISSUE TITLE
Dashboard Screen Options looks out of place

### ISSUE THREAD

**Issue by robwent** [google/site-kit-wp#236] opened 2019-07-12 20:37 UTC
## Feature Description

On the dashboard screen, when enabling and disabling panels, site kit uses an SVG rather than normal text.

This looks out of place with the other options and (correct me if I'm wrong) makes it inaccessible.

Why not just use standard text so that it fits in with the other options?

![screen-options](https://user-images.githubusercontent.com/411678/61157156-37b00e00-a4ed-11e9-802f-54d123e83271.PNG)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2019-08-22 08:57
Here's how it appears now after changes applied in #365 

![image](https://user-images.githubusercontent.com/1621608/63501147-d4de6900-c4d3-11e9-804f-9c414cbe0ff1.png)

Any further action needed on this one @felixarntz ?

**Comment by ThierryA** [comment] 2019-11-19 11:33
Duplicate of #877 https://github.com/google/site-kit-wp/issues/877

**Closed by ThierryA** 2019-11-19 11:33 UTC
Labels: Type: Enhancement
