### ISSUE TITLE
Pass specific dates in Analytics deep links

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2287] opened 2020-10-29 17:43 UTC
After #2236, all dynamic JS Analytics deep links in the new widgets should be updated to pass the correct dates in the URLs.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All widgets (using the Widget API) that include Analytics deep links should be updated to pass the exact dates from the currently selected date range in the URL:
    * The path of the URL should include "query parameter-like" values like `_u.date00=YYYYMMDD&_u.date01=YYYYMMDD` (they need to be in the path though, not actual query parameters). Go to  the Analytics FE and select a custom date range to see an example. Note that there may already be other "query-parameter-like" values in the URL in which case they need to be combined accordingly (concatenated with `&`).
* For widgets that also _compare_ with a second date range (i.e. `compareStartDate` and `compareEndDate`), those dates _also_ need to be passed in the URL in addition to the above, e.g. `_u.date10=YYYYMMDD&_u.date11=YYYYMMDD`.
* A full example (with all four dates) could be `_u.date00=20201023&_u.date01=20201029&_u.date10=20201016&_u.date11=20201022`.
* The additional arguments should be provided via `getServiceReportURL` (as probably already in place for all of these widgets anyway).

## Implementation Brief
* **Once #2405 has been merged**,
* Using `/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidgetTopPagesTable.js`
	- Query the user store to get the date range:
	```js
		const dateRangeDates = useSelect( ( select ) => select( CORE_USER ).getDateRangeDates( {
			offsetDays: DATE_RANGE_OFFSET,
		} ) );
	```
	- The `DATE_RANGE_OFFSET` should be imported from `/assets/js/modules/analytics/datastore/constants.js`
* Create new file `/assets/js/modules/analytics/util/report-date-range-args` and using newly created file,
	- Create a new function `generateDateRangeArgs` which accepts the returned object from the `getDateRangeDates` selector. The object contains the following keys:
		- `startDate`
		- `endDate`
		- `compareStartDate` : if `compare` is true when calling `getDateRangeDates`. See example below.
		- `compareEndDate`: if `compare` is true when calling `getDateRangeDates`. See example below.
	- The `generateDateRangeArgs` should return an object with the following keys:
		- `'_u.date00': startDate.replace( /-/g, '' ),`
		- `'_u.date01': endDate.replace( /-/g, '' ),`
		- `'_u.date10': compareStartDate.replace( /-/g, '' ),` if `compareStartDate` is present
		- `'_u.date11': compareEndDate.replace( /-/g, '' ),` if `compareEndDate` is present
* Using `/assets/js/components/dashboard/AnalyticsAdSenseDashboardWidgetTopPagesTable.js`,
	- Call the `generateDateRangeArgs` function and spread the returned object as args to the `getServiceReportURL` selector.
* Review other components where `getServiceReportURL` is used for Analytics deep links and apply same logic.
	- `/assets/js/components/dashboard/DashboardAllTrafficWidgetV2/index.js`
	- `/assets/js/modules/analytics/components/dashboard/AnalyticsDashboardWidgetTopPagesTable.js`
* If we need to compare with a second date range,
	- query the user store by adding the `compare` key, like that:
		```js
			const dateRangeDates = useSelect( ( select ) => select( CORE_USER ).getDateRangeDates( {
				compare: true,
				offsetDays: DATE_RANGE_OFFSET,
			} ) );
		```

### Test Coverage
* Add new tests for the `generateDateRangeArgs` function.

### Visual Regression Changes
* There should be no visual regressions.

## QA Brief
* To to the `Analytics` dashboard and check if the links for the content in the "Top content over the last xxx days" table contain the following extra parameters:
	- `'_u.date00'`
	- `'_u.date01'`
* When clicking on the Analytics links, they should bring you to the accurate report in the Analytics FE, already with the correct dates specified (same dates as in Site Kit).

## Changelog entry

* Include current dates in Analytics deep links so that the service frontend shows the same time period as Site Kit.

**Comment by aaemnnosttv** [comment] 2021-01-05 17:02
@asvinb IB looks good for the most part, just a few comments:

> Review other components where `getServiceReportURL` is used for Analytics deep links and apply same logic.

The issue is currently estimated as a 3 which seems a little low, but it's hard to say without having a better idea as to how many components are being touched here. The logic is largely the same but my gut feel is that this is probably closer to a 7. Would you please list out the components you see that would be affected by this?

> If we need to compare with a second date range

There is an opportunity to simplify this a good deal by introducing a little utility function that takes `dateRangeDates` as its input and returns an object of the appropriate report args. The mapping of the specific date report arg key and the rewriting of the date, as well as the conditional presence of the `compare*` dates justifies a utility for this. Then the return value can be simply spread into the args for the `getServiceReportURL` selector.

I thought about potentially integrating this into the selector itself, but we don't always want to include the date ranges in the args and the date range selector will always return dates so it would require changes to the signature of that selector which I would prefer to avoid.

This utility should probably get a few tests as well which justifies a slightly larger estimate too.

**Comment by asvinb** [comment] 2021-01-06 10:18
@aaemnnosttv IB and estimate updated as per your comments.

**Comment by aaemnnosttv** [comment] 2021-01-06 16:35
IB ✅

**Comment by tofumatt** [comment] 2021-01-25 22:50
Moving back to Execution and marking as blocked by #2674; I can't get the E2E tests passing to review this.

Once #2674 is merged and this issue's PR/branch merges in the latest `develop`, this should be unblocked.

**Comment by felixarntz** [comment] 2021-01-25 23:39
@tofumatt Is every e2e test failing? I've seen these failures too but usually it works after 2-3 attempts. It's definitely worth fixing this, but we shouldn't block issues because of that unless they _really_ consistently make e2e tests fail.

**Comment by wpdarren** [comment] 2021-02-19 10:25
### QA Update: Pass ✅ 

**Verified:**

- On the Analytics dashboard the links for the content in the "Top content over the last xxx days" table contain the extra parameters: '_u.date00' and '_u.date01'

- When clicking on the Analytics links, they should bring you to the accurate report in the Analytics FE, with the correct dates specified, i.e. 7, 14, 28, and 90 days. 

7 days:  `https://analytics.google.com/analytics/web/?authuser=darren.cronian%40get10up.com#/report/content-drilldown/a110825622w205695307p198802416/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath%3A~2F&_u.date00=20210212&_u.date01=20210218/`

![image](https://user-images.githubusercontent.com/73545194/108491183-8aaf9100-72de-11eb-8e8f-1667aa0fd6f9.png)

14 days: `https://analytics.google.com/analytics/web/?authuser=darren.cronian%40get10up.com#/report/content-drilldown/a110825622w205695307p198802416/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath%3A~2Fremote-jobs-demand~2F&_u.date00=20210205&_u.date01=20210218/`

![image](https://user-images.githubusercontent.com/73545194/108491408-d3ffe080-72de-11eb-818b-d6426f2f7cd8.png)

28 days: `https://analytics.google.com/analytics/web/?authuser=darren.cronian%40get10up.com#/report/content-drilldown/a110825622w205695307p198802416/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath%3A~2Ffind-remote-jobs-2021~2F&_u.date00=20210122&_u.date01=20210218/`

![image](https://user-images.githubusercontent.com/73545194/108491632-1cb79980-72df-11eb-9fa3-910dde75139b.png)

90 days: `https://analytics.google.com/analytics/web/?authuser=darren.cronian%40get10up.com#/report/content-drilldown/a110825622w205695307p198802416/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath%3A~2Fsubscribe~2F&_u.date00=20201121&_u.date01=20210218/`

![image](https://user-images.githubusercontent.com/73545194/108491832-5d171780-72df-11eb-9fab-7dbbea8f7143.png)

**Closed** 2021-03-01 18:00 UTC
Labels: Good First Issue, Module: Analytics, P1, Rollover, Type: Enhancement
