### ISSUE TITLE
Reword "Existing Tag" messages and other language changes for SAM

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#8405] opened 2024-03-17 20:00 UTC
## Feature Description

This issue covers the following Asana E2E testing issues which deal with "language" changes:
https://app.asana.com/0/1206822627583085/1206848566636390/f
https://app.asana.com/0/1206822627583085/1206830601119693/f

A. Existing Tag Message 
Within the GA4 "setup" and "edit settings" forms, a message is displayed which informs the user if an existing GA4 tag is found on their site. All of these messages were originally created for UA settings where a duplicate tag would duplicate events sent to UA. We still decided to port the existing tag detection functionality along with the messages over even for GA4 ([Slack thread](https://10up.slack.com/archives/CBKKQEBR9/p1707301232119229?thread_ts=1706716275.995299&cid=CBKKQEBR9)). If the existing tag matches the tag for the currently selected property (Case 1 and 2 in the screenshots below), the message sounds like a warning that suggests that something bad could happen in terms of duplication if two tags are placed on the site. This is no longer true for GA4 and so we should update the message to something more lenient.

<Details>
<Summary>Case 1: Setup with existing duplicate tag</Summary>

![image](https://github.com/google/site-kit-wp/assets/1721319/234e8c8f-1b22-4efa-8e60-a8d0de10ed7f)
</Details>

<Details>
<Summary>Case 2: Settings with existing duplicate tag</Summary>

![image (2)](https://github.com/google/site-kit-wp/assets/1721319/a6b3dd18-6393-4042-b021-cd6c15eae3f6)
</Details>

<Details>
<Summary>Case 3: Setup with existing different tag</Summary>

![image (3)](https://github.com/google/site-kit-wp/assets/1721319/a1e0a6a6-fda1-45b8-ac98-88cb26ae2045)
</Details>

<Details>
<Summary>Case 4: Settings with existing different tag</Summary>

![image (3)](https://github.com/google/site-kit-wp/assets/1721319/506ae55c-706d-4bc4-a355-d489c1d841bb)
</Details>

B. Other GA4 references
Furthermore, for simplicity, we should consider removing older lingering references to GA4.
<Details>
<Summary>GA4 reference in Settings</Summary>

![image](https://github.com/google/site-kit-wp/assets/1721319/0ee33131-3001-46fd-8b78-692f694ea701)
</Details>

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Within the GA4 and Tag Manager module's "Setup" and "Settings" forms, if an existing tag is detected and it matches the tag found within the currently selected property / container, then the original message below should be modified to the new message as follows:
    * Original Message: 
    `A tag G-ABCDE12FGH for the selected property already exists on the site`
    `Make sure you remove it if you decide to place the same GA4 tag via Site Kit, otherwise they will be duplicated`
    * New Message:
    `A tag G-ABCDE12FGH for the selected property already exists on the site`
    `Consider removing the existing tag to avoid loading both tags on your site.`

* Within the GA4 "Setup" and "Settings" forms, remove all references to "GA4".
    * Original Messages: 
        1. `Site Kit will add the GA4 code automatically`
        2. `Site Kit will not add the GA4 code to your site`
    * New Messages (use the same language as in Tag Manager currently):
        1. `Site Kit will add the code automatically`
        2. `Site Kit will not add the code to your site`
    
## Implementation Brief

* [ ] Within the `SettingsUseSnippetSwitch` and `SetupUseSnippetSwitch` components in both, `analytics-4` and `tagmanager`, update the description messages as per the AC.

### Test Coverage

* No new tests required.

## QA Brief

* Use the tester plugin to add a valid Measurement ID within the Analytics Existing tag setting. Now set up Analytics and edit the Analytics settings as well as set up GTM and edit GTM settings to see the messages within the AC.
* Note: I have had issues replicating the "Settings with existing different tag" scenarios - please enquire on Slack or ask Nahid on how he was able to replicate these.

## Changelog entry

* Update wording for sites with existing Analytics tags.

**Comment by marrrmarrr** [comment] 2024-03-18 16:56
this all looks great, thanks @jimmymadon !

**Comment by wpdarren** [comment] 2024-03-27 10:57
### QA Update: ⚠️ 

@tofumatt  I have tried this with two new sites, but I cannot see the new text.  It should say:

`A tag G-SHXWZ83GQY for the selected property already exists on the site. Consider removing the existing tag to avoid loading both tags on your site.` 

I still see: 

`A tag G-SHXWZ83GQY for the selected property already exists on the site. Make sure you remove it if you decide to place the same GA4 tag via Site Kit, otherwise they will be duplicated
`
![image](https://github.com/google/site-kit-wp/assets/73545194/abd1c59e-72b8-40a3-b3b9-76fabcf996ae)

I refreshed the development branch a few times.  Any idea why I do not see the text change?

**Comment by wpdarren** [comment] 2024-03-27 11:12
QA Update: ❌ 

As per conversation with @tofumatt on Slack, sending this back to execution for a fix.

**Comment by wpdarren** [comment] 2024-03-29 10:39
### QA Update: ⚠️ 

@tofumatt I feel a scenario has been missed here in the ACs. I see the correct copy when the duplicate Measurement ID is the same when setting up Analytics. The issue is when the duplicate Measurement ID differs from the property/web data stream you've selected when setting up Analytics.  As you can see from the screenshot below, the GA4 is still referenced. 

It was my understanding that we would remove the GA4 reference.

Interested in your thoughts. 

![image](https://github.com/google/site-kit-wp/assets/73545194/7440a26d-d927-46e8-8a0b-2afc80b5707a)

**Comment by tofumatt** [comment] 2024-04-01 15:26
@wpdarren Hmm, fair enough. Might as well do that as part of this issue, I'll take this over and look for any remaining "GA4" text.

**Comment by tofumatt** [comment] 2024-04-02 00:20
Looks like that's the only instance aside from https://google.github.io/site-kit-wp/storybook/develop/?path=/story/consent-mode-settingscardconsentmode--with-ads-connected, which makes sense to keep as GA4 🙂

**Comment by nfmohit** [comment] 2024-04-02 17:57
> ### QA Update: ⚠️
> @tofumatt I feel a scenario has been missed here in the ACs. I see the correct copy when the duplicate Measurement ID is the same when setting up Analytics. The issue is when the duplicate Measurement ID differs from the property/web data stream you've selected when setting up Analytics. As you can see from the screenshot below, the GA4 is still referenced.
> 
> It was my understanding that we would remove the GA4 reference.
> 
> Interested in your thoughts.
> 
> ![image](https://private-user-images.githubusercontent.com/73545194/318026330-7440a26d-d927-46e8-8a0b-2afc80b5707a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzc4MTEsIm5iZiI6MTcxMjA3NzUxMSwicGF0aCI6Ii83MzU0NTE5NC8zMTgwMjYzMzAtNzQ0MGEyNmQtZDkyNy00NmU4LThhMGItMmFmYzgwYjU3MDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE3MDUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZWU3ZjkzYjU4NDE4NTdlNDllMzM3N2JmNDQxOWFjYjU2OGJjOTkwMDMzOTU4MTVkYTc5MzljMzZlZTQ2MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oH3PcF_1AHpxVFHTZqOBT-WSR-dT_BrcT7CV9AQwqAQ)

This has now been addressed and merged. Back with you for another pass, thanks @wpdarren!

**Comment by wpdarren** [comment] 2024-04-03 05:05
### QA Update: ✅ 

**Verified:**

- I went through all of the scenarios for the setup and settings screens to ensure that the GA4 references were removed and, where appropriate, the copy in the AC matches.  This was tested when the measurement ID for an existing tag was the same as that used to set up Analytics on Site Kit and a different one.  I also made sure that the GA4 reference when no existing tag was removed from the copy.  All good 👍 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/9c7bd5bd-3f92-4877-b41f-7d3ca0971a0f)
![image](https://github.com/google/site-kit-wp/assets/73545194/bbe633a9-515d-451e-9a08-4a986fe52e66)
![image](https://github.com/google/site-kit-wp/assets/73545194/9610cfae-8561-415c-b384-75aac868be49)
![image](https://github.com/google/site-kit-wp/assets/73545194/722b5499-c7e1-450d-9250-a796ec1cd0b5)
![image](https://github.com/google/site-kit-wp/assets/73545194/98f2f250-0119-4eaa-8397-3a7aa6e652bc)

</details>

**Closed** 2024-04-04 21:42 UTC
Labels: P1, Type: Enhancement, Module: Analytics
