### ISSUE TITLE
Looping back to Site Kit setup screen after following "Sign in with Google" steps

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2924] opened 2021-03-05 15:46 UTC
## Bug Description

As reported in the [WordPress support forums](https://wordpress.org/support/topic/sign-in-loop/#topic-14086343-replies) one user is unable to setup Site Kit, after clicking on the sign in with google the user is being redirected to the primary Site Kit setup page. 

This site was used previously on a staging site, with Site Kit possibly setup at some stage on this staging site, although no resets on the service side so far have allowed setup to proceed. 

## Insights & Troubleshooting Checks performed 

- [x] Health Check & Troubleshooting plugin check
- [x] Incognito mode 
- [x] Checked users Site Health info, no identified causes
- [x] Additional .htaccess rules applied
- [x] Confirmed no modification of Site Kit placed snippet
- [ ] Uninstalled and reinstalled plugin
- [x] Site Health status check - **Updated - There are REST API Restrictions**
- [ ] Attempted setup/viewing dashboards from another device 
- [ ] Temporary disabled WAF rules at host level - including ModSecurity
- [x] Checked site setup and dashboard from another WordPress site on the same hosting platform - **Update: Same setup failure**
- [x] Reset Site Kit (on the SK service)
- [x] Reset previous site records (on the SK service)
- [ ] Checked does the same occur from another Google account during setup
- [ ] Checked setup / viewing dashboards from another WordPress administrator account
- [x] Modified WordPress site settings (switching https > http, logging in once once more & reverting to https)
- [ ] Reviewed error logs 
- [ ] Reviewed XHR requests 
- [x] Checked setup after applying language/translation plugin filter

## Screenshots

Console errors at the OAuth stage - occur after clicking on the users email
![image](https://user-images.githubusercontent.com/41326532/110136670-df1b3c00-7dc7-11eb-894f-3fc88ce8af80.png)

## Additional Context

- Plugin version: 1.27.0
- php_version: 7.4.8
- wp_version: 5.5.3
- [Site Health information provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNiztf8CqdA7ofT-jcIbjh2MiolAtvCSTH_WlJ6sszLEOGvukqx3Qqb1akRt2j_MHMw)
- Video showcasing experience provided (URL in Site Health info)
- Previous sites used reset on the service side (2 sites located, both reset)
- Not possible to reset on user side, with no reset button available
- wp-admin path was modified at some stage
- No additional htaccess rules
- There is a "WP REST Cache - Must-Use Plugin" although setup didn't proceed with this deactivated (as pre Health Check & Troubleshooting plugin)
 
Additional plugins of interest active - dropin plugins:
 - advanced-cache.php: true
- db.php: true
- object-cache.php: true

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment] 2021-03-26 16:10
@abdullah1908 Assigning to L1 for review. [HAR file](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNjrLpExFyhagr0-UlAYeCMXoUxRDSWOP3vUqG-E6lf-Q_7oXxLiR-J1BL1NfsQVdL4) kindly provided by user.

**Comment by abdullah1908** [comment] 2021-04-02 19:41
I couldn't replicate this issue after the long activity as following:
- Setup Site Kit with the Google Services
- Migrated the site to other subdomain on different host
- Couldn't find any issue regarding Looping Back Sign
- Reset Site Kit
- Tried again & all fine for me

**Comment by jamesozzie** [comment] 2021-04-06 19:20
@abdullah1908 Further insights provided by the impacted user in their [support topic](https://wordpress.org/support/topic/sign-in-loop/page/2/), with another site facing similar issues.

**Comment by abdullah1908** [comment] 2021-04-07 11:06
Thanks @jamesozzie I'll further look into this issue based on the [new details](https://wordpress.org/support/topic/sign-in-loop/page/2#post-14256960).

**Comment by abdullah1908** [comment] 2021-04-20 15:44
I am unable to reproduce this issue by configuring Cloudflare on a demo site.  Tried to setup same setup as user have based on SH info:
- Installed WPML plugin & its Addons 
- Cache plugin along with the theme(Newspack) that user is using
It would be great if we can wait for the user to setup the fresh install on the same server. Maybe we can get new insights about this issue.

**Comment by bethanylang** [comment] 2021-04-26 14:00
@abdullah1908 I'm escalating this to L2.

**Comment by jamesozzie** [comment] 2021-04-30 12:03
The same issue occurs on another site with the same hosting provider. Thanks to the new REST API notices it looks like the issue is as a result of such restrictions, with the below evident during setup:
`Site Kit cannot access WordPress REST API`

Awaiting hosting provider for further checks support side, happy to close also given this is something we're unable to address on the Site Kit side.

**Comment by bethanylang** [comment] 2021-06-01 15:41
Closing as this will not require a Site Kit fix, per @jamesozzie's note above.

**Closed by bethanylang** 2021-06-01 15:41 UTC
Labels: Group: Escalation, Type: Bug, Type: Support
