### ISSUE TITLE
Don't render the Key Metrics Selection Panel into the DOM until the feature has been set up

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9468] opened 2024-10-07 15:17 UTC
## Feature Description

As mentioned on [Asana](https://app.asana.com/0/0/1208489517112450/1208489517112485/f) the Key Metrics Selection Panel is unnecessarily rendered into the DOM before the feature has been set up.

It should only be rendered once the feature has been set up.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Key Metrics Selection Panel should only be rendered into the DOM once Key Metrics has been set up.

## Implementation Brief

* [x] Wrap the `<MetricsSelectionPanel />` with the condition `isKeyMetricsWidgetHidden === false`. Changing this will prevent rendering of the setup panel if Key Metrics isn't enabled.
   * https://github.com/google/site-kit-wp/blob/638dbd972e2663626037a4e8f13e21fc8b54521a/assets/js/components/DashboardMainApp.js#L295-L295

### Test Coverage

* No additional test coverage required, confirm existing tests pass.

## QA Brief

1. Ensure Key Metrics is enabled in Site Kit settings.

2. Visit the Site Kit dashboard and search for `googlesitekit-km-selection-panel` element in browser console. It must be present when Key Metrics is enabled.

![Image](https://github.com/user-attachments/assets/63beb318-f899-4e4d-9a1f-7eb9d5591e19)

3. Disable the Key Metrics is enabled in Site Kit settings. The above element should not be present in the dashboard.

4. Ensure that when the Key Metrics feature is not yet setup and the setup banner is being shown, `googlesitekit-km-selection-panel` element should be present in the markup.

5. When the Key Metrics feature is not yet setup and the setup banner is not showing up, `googlesitekit-km-selection-panel` element should not be present in the markup.

## Changelog entry

* Don't unnecessarily render the Key Metrics Selection Panel into the DOM.

**Comment by eugene-manuilov** [comment] 2024-10-15 22:46
IB ✔

**Comment by ankitrox** [comment] 2024-11-07 07:39
@techanvil There was a mistake in previous PR for the condition to display the component. I've created a follow up PR https://github.com/google/site-kit-wp/pull/9630 and assigning it to you for review.

Thanks

**Comment by mohitwp** [comment] 2024-11-11 02:19
### QA Update ❌ 

- Tested on dev environment.
- Verified that `googlesitekit-km-selection-panel` is not present in markup when the Key Metrics is disabled under Site Kit settings.
- Verified that `googlesitekit-km-selection-panel` is present in markup when the Key Metrics is enabled under Site Kit settings.

@ankitrox I found that in the following cases, the googlesitekit-km-selection-panel is present in the markup, but it is not expected:

**1)** The site is in the gathering data state. The Key Metrics feature is not yet set up, and the setup banner is not displaying. However, `googlesitekit-km-selection-panel` is still present in the markup. (In this case, the user cannot set up KMW, and the KM option does not appear under settings because site is in gathering data state.)

<details>

![Image](https://github.com/user-attachments/assets/9d0b1fa6-7e98-4217-b564-149b9f45e9e1)

</details>

**2)**  Key Metrics feature is not yet setup and the setup banner is being shown, `googlesitekit-km-selection-panel` is still present in the markup. (This scenario occurs when a user visits the dashboard for the first time after setup. On the first load of the main dashboard, the KM setup banner should not display, and the markup should not be present in this case. You can use oi.ie to reproduce this.).

<details>

![Image](https://github.com/user-attachments/assets/4c3837df-bee3-4b01-85cd-6f658df743a1)

</details>

**Comment by ankitrox** [comment] 2024-11-11 11:32
Thanks for testing this @mohitwp and highlighting the issue.

I have raised a [follow-up PR](https://github.com/google/site-kit-wp/pull/9652) for this problem.

**Comment by nfmohit** [comment] 2024-11-11 19:33
Hi @ankitrox 👋 

We just found out that this issue has caused all E2E tests to fail, most likely because the `useDisplayCTAWidget` hook makes calls to Analytics selectors without checking if the module is connected. Sending this back to Execution. See conversation [here](https://fueled10up.slack.com/archives/CBKKQEBR9/p1731352092430989).

CC: @techanvil @mohitwp @aaemnnosttv

**Comment by nfmohit** [comment] 2024-11-11 19:54
I've created [a quick PR](https://github.com/google/site-kit-wp/pull/9663) to address the above issue. Thanks!

**Comment by mohitwp** [comment] 2024-11-13 07:35
### QA Update ✅ 

- Tested on dev environment.
- Tested when 'conversionReporting' feature flag is not enabled.
- Tested when 'conversionReporting' feature flag is enabled.
- Tested on main and view only dashboard.
- Verified that when the Key Metrics feature is not yet setup and the setup banner is being shown, googlesitekit-km-selection-panel element  present in the markup.
- Verified When the Key Metrics feature is not yet setup and the setup banner is not showing up, `googlesitekit-km-selection-panel` element is not present in the markup.
- Verified the Key Metrics Selection Panel only  rendered into the DOM once Key Metrics has been set up.
- Verified that `googlesitekit-km-selection-panel` element not present in the markup if Key metrics visibility is disabled under admin settings.
- Verified that all issues reported above are now resolved.


<details>

<details>

![Image](https://github.com/user-attachments/assets/055e9ec3-75a1-4673-a073-4e9fec78e4c3)

</details>

**Issue 2 : FIXED**

<details>

![Image](https://github.com/user-attachments/assets/78700319-47c3-4c12-886b-43d96721124b)

</details>

**Issue 3 : FIXED**

<details>

![Image](https://github.com/user-attachments/assets/85d3a791-aae7-4d79-bb59-4f8e4980e9ca)

</details>
**PASS CASES -**

<details>

![Image](https://github.com/user-attachments/assets/ac285f1a-d294-4555-8fe7-cc39d77e40ac)

![Image](https://github.com/user-attachments/assets/385ef924-28dc-42ec-bc1b-6fe48b6a2ec4)

https://github.com/user-attachments/assets/1ae0fbc3-4af9-4996-ae84-1060ce4b29fa

View only Dashboard

![Image](https://github.com/user-attachments/assets/b1ce16f8-a673-43a9-984a-500651708017)

</details>

**Closed** 2024-11-16 01:01 UTC
Labels: P2, Type: Enhancement, Team M
