### ISSUE TITLE
Implement main `Survey` component

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3380] opened 2021-05-19 11:51 UTC
## Feature Description

The `Survey` component is the main component for rendering a single survey. This component is responsible for managing state for answers and rendering the appropriate inner components implemented in #3379.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `Survey` component should be created in `assets/js/components/surveys/` as a functional, hook-based, hybrid-connected component
* It should (for now) retrieve its array of `question` objects (see `.question` in the [survey JSON](https://docs.google.com/document/d/1jqUg4blDUFu6BCyHQVgzlz9smxK0UGrzsOpPojo2EJM/edit?ts=609c08e3#heading=h.2ksz9wryvy2j)) and array of `completion` objects (see `.completion` in the [survey JSON](https://docs.google.com/document/d/1jqUg4blDUFu6BCyHQVgzlz9smxK0UGrzsOpPojo2EJM/edit?ts=609c08e3#heading=h.2ksz9wryvy2j)) from the `currentSurvey` in the data store (added in #3355)
	- The component can assume that this exists if it is being rendered
* The component should keep track of the answered state of each question  
_For the initial implementation there will only be a single question, but it should be capable of handling multiple_
* The component should send a `survey_shown` event when rendered for the first time (e.g. on mount)
	- See `sendSurveyEvent` action added in #3355 for all events that are sent (i.e. not `trackEvent`)
* The component should keep track of the current question (if any are left to be answered) and render the proper `SurveyQuestion*` component based on the question type (these components are implemented in other issues)
	- Note that the only question type that will be implemented at this point will be `rating` but the proper component-per-question-type should be considered here (for any other type `null` should be rendered for now)
	- An `answerQuestion` prop should be passed to the question which when called should set and submit the answer for the question by sending a `question_answered` event which should include event data with the [`QuestionAnswer` object answer which will vary in shape based on the question type](https://docs.google.com/document/d/1jqUg4blDUFu6BCyHQVgzlz9smxK0UGrzsOpPojo2EJM/edit?pli=1#heading=h.qxbkeiyvcd7o)
	- All `question_answered` events for all question types will have the following top-level properties:
		- `question_ordinal` – from the current question
		- `answer` [object] – value varies by question type
	- For the `question_answered` event for a **`rating`** type question, the full event data should have the following shape:
		```json
		{
			"question_ordinal": 1,
			"answer": {
				"answer": {
					"answer_ordinal": 4
				}
			}
		}
		```
		Using the above as an example, the following should be how `answerQuestion` would be called in the child for a rating component:  
		```js
		answerQuestion( { answer: { answer_ordinal: 4 } } )
		```
		The full `event` object is composed and sent to the server by the `sendSurveyEvent` action added in #3355
	- Only the `rating` question type needs to be handled as part of this issue
* Once all questions have been answered, the first qualifying completion should be rendered using the `SurveyCompletion` component (implemented in #3379)
	- For qualifying logic, see the `trigger_condition` defined for each completion object. The first completion that matches all conditions should be used. There should always be one that matches, but in the event that one does not the first completion is to be used as a fallback.
	- The component should send a `completion_shown` event when its completion is rendered for the first time (e.g. on mount)
		- The event data should include the `completion_ordinal` of the completion
	- A `ctaOnClick` function prop should be passed which when called sends a `follow_up_link_clicked` survey event with the `completion_ordinal` of the current completion
		- This should also cause the survey to no longer be displayed
* A `dismissSurvey` prop should be passed to both question and completion components which when invoked:
	- Sends a `survey_closed` event (no additional data)
	- Causes the survey to be no longer displayed  
	_Note this does not need to be persisted at this point as surveys are not cached/persisted either_
* Intermediate state should be stored in `core/forms` with a survey-specific form ID
* Jest component tests should be added to cover the behavior of this component

## Implementation Brief

(Form ID should come from the `Session` object (`session.session_id`) returned by the `/survey/trigger/` request/selector.)

* Create `assets/js/components/surveys/Survey.js` to house the new `Survey` component.
    * It should take a `questions` prop—an array of questions, see the ACs for the format
    * It should take a `completions` prop—an array of completed questions, see the ACs for the format
    * It should accept an `id` prop used to get/store the survey's data in the `core/forms` datastore (see below). A key like `user-survey-form-${id}` should suffice. The ID supplied should probably be the `session.session_id` value, but could also be `survey_id`.
    * Keep track of each question's state in the `core/forms` data store using the `id` prop.
    * Keep track of which question in the array of questions the user is "on"/eg. is active in the `core/forms` data store using the ID.
    * (The ACs mention keeping track of both of these internally, but using the `core/forms` store instead should be fine and more robust.
    * Using [`sendSurveyEvent`](https://github.com/google/site-kit-wp/issues/3355), send a `'survey_shown'` event when it is first mounted, eg `sendSurveyEvent( 'survey_shown' )` Every time the survey is mounted this should be shown, not just the first time it's shown.
    * Render each survey question using the `SurveyQuestion` component and passing the `answerQuestion` prop.
        * The `answerQuestion` prop should be a function that dispatches an action that sends the `question_answered` event.
        * The `answerQuestion` prop function should accept an `answer` object that can be filled-in according to the question type and answer selected by the user. Each survey answer has a different shape, see: https://docs.google.com/document/d/1jqUg4blDUFu6BCyHQVgzlz9smxK0UGrzsOpPojo2EJM/edit?ts=609c08e3#heading=h.qxbkeiyvcd7o. The `question_ordinal` prop can be pre-set/handled internally because the question we're answering is always the same despite the answer. So the `answerQuestion` function should allow each answer to set the `answer` object so that an action like this is dispatched:
            ```js
                // Example action for a **`rating`** type question.
                sendSurveyEvent( 'question_answered', {
                    "question_ordinal": 1, // Set by the SurveyQuestion component.
                    "answer": {
                        // The following would be customised by each answer and passed to the `answerQuestion` function prop.
                        "answer": {
                            "answer_ordinal": 4 // If this is the 4th answer.
                        }
                    }
                } );
            ```
            Using the above as an example, the following should be how `answerQuestion` would be called in the child for a rating component: `answerQuestion( { answer: { answer_ordinal: 4 } } )`
* Once an entire survey is marked as answered, render `SurveyCompletion` instead of any question. (See ACs for implementation, as they're quite thorough.). **Note: We know a survey is completed if the question answered is the same index as the total number of questions for this survey.**
    * Pass a `ctaOnClick` event handler to the `SurveyCompletion` if there is a follow-up link to click in the survey completion. If it is clicked, use `sendSurveyEvent( 'follow_up_link_clicked' )` to send an event letting the proxy know the user has clicked the "completion follow-up link". After that event, also send `sendSurveyEvent( 'survey_closed' )` so the proxy knows the survey shouldn't be shown.
    * If there is no follow-up link, then sending the `completion_shown` event will be sufficient to tell the proxy not to show the survey anymore.
* Pass a `dismissSurvey` prop (function) to both "question" and "completed" components to allow the user to dismiss the survey. This would send a `survey_closed` event. This tells the proxy not to show the survey.
* Render `null` from the `Survey` component if the survey is "fully-completed" or dismissed and shoud not be shown.

### Test Coverage

* Add Jest/unit tests to ensure that each type of question we support (right now only "rating") is rendered appropriately.
* Add tests to ensure if an unknown question type is encountered we render `null`.
* Add tests to ensure the proper events/action (via `sendSurveyEvent`) are dispatched based on user interaction/component loading.
* Add tests to ensure a fully-completed survey ("question-complete") shows the `SurveyCompletion` component instead of any questions.
* Add tests to ensure `null` is output if the survey is "fully-completed" or dismissed.

### Visual Regression Changes

* N/A.

## QA Brief

* Visit the `CurrentSurvey` components in Storybook, disabling the [`fetchMock.post`](https://github.com/google/site-kit-wp/blob/ba3463f818de7adccc0c969360ab6db5d5d075dc/assets/js/components/surveys/CurrentSurvey.stories.js#L39) calls in the stories. Then test each story to ensure it is behaving as-expected and dispatching the proper survey events as outlined in the ACs.

## Changelog entry

* Add React components for rendering and managing user surveys.

**Comment by felixarntz** [comment] 2021-05-19 18:44
@aaemnnosttv Mostly lgtm, just a few things:

> Note that the only question type that will be implemented at this point will be `rating` but the proper component-per-question-type should be considered here

For those cross-issue etc references and future considerations, it would be good to clearly outline in the ACs what _should_ happen here: E.g. should empty `SurveyQuestionSingleSelect` etc. components be scaffolded per this issue or should the `Survey` component just return `null` for those question types?

> An `answerQuestion` prop should be passed to the question which when called should set and submit the answer for the question by sending a `question_answered` event which should send the following properties in the event data:

Note that the format of the event data also needs to differ based on the question type, so that's important to point out here I think. Again, here we only need to fully implement the `rating` variant for now.

One more thing: Apologies that may not have been clear from the design doc, but the [protobuffer definition for a `QuestionAnswer` object](https://docs.google.com/document/d/1jqUg4blDUFu6BCyHQVgzlz9smxK0UGrzsOpPojo2EJM/edit?pli=1#heading=h.qxbkeiyvcd7o) specifies that the `answer` field must be one of the objects below, i.e. there needs to be an `answer` field nested in the `answer` object. This may look unintuitive and unnecessary at first, but is required per the data structures (the inner `answer` field may have different data types) and allows for enhancements in the future, should a question type eventually require more than just an `answer` field. So the data sent to the API should be like this:
```json
{
    "event": {
        "question_answered": {
            "question_ordinal": 1,
            "answer": {
                "answer": {
                    "answer_ordinal": 4
                }
            }
        }
    }
}
```

> The component should send a `completion_shown` event when its completion is rendered for the first time (e.g. on mount)

Are you saying this should be added to `Survey` or to the `SurveyCompletion` rendered? Technically it might be more appropriate in the latter, but since that is otherwise an unconnected component, `Survey` seems more appropriate. What's your take on this?

**Comment by aaemnnosttv** [comment] 2021-05-19 19:51
> For those cross-issue etc references and future considerations, it would be good to clearly outline in the ACs what _should_ happen here: E.g. should empty `SurveyQuestionSingleSelect` etc. components be scaffolded per this issue or should the `Survey` component just return `null` for those question types?

Good point – I think as far as the ACs are concerned, we should just return `null` for such questions since a scaffolded component would end up doing the same anyways, so I don't see much benefit in doing that ahead of time.

> Note that the format of the event data also needs to differ based on the question type, so that's important to point out here I think. Again, here we only need to fully implement the `rating` variant for now.

Yeah, although it's hard to see what it would be for the others without example objects. From what I could tell that structure was more/less provided in the individual `answer_choice` objects (with the exception of `open_text`). What specifically should we add here to clarify?
 
> One more thing: Apologies that may not have been clear from the design doc, but the [protobuffer definition for a `QuestionAnswer` object](https://docs.google.com/document/d/1jqUg4blDUFu6BCyHQVgzlz9smxK0UGrzsOpPojo2EJM/edit?pli=1#heading=h.qxbkeiyvcd7o) specifies that the `answer` field must be one of the objects below, i.e. there needs to be an `answer` field nested in the `answer` object. This may look unintuitive and unnecessary at first, but is required per the data structures (the inner `answer` field may have different data types) and allows for enhancements in the future, should a question type eventually require more than just an `answer` field. 

Yeah, I found that definition to be a bit difficult to follow. E.g. `RatingAnswer rating` appears to have a key of `rating` in the aforementioned `answer` object, but it doesn't according to your example JSON. Is this format documented somewhere?

> > The component should send a `completion_shown` event when its completion is rendered for the first time (e.g. on mount)
> 
> Are you saying this should be added to `Survey` or to the `SurveyCompletion` rendered? Technically it might be more appropriate in the latter, but since that is otherwise an unconnected component, `Survey` seems more appropriate. What's your take on this?

I initially had it passed to the `SurveyCompletion` as an `onShown` prop that the component would need to use, but later changed it to live in the `Survey` here since we already send the `survey_shown` event which is very similar, and the component is already aware of when the completion is rendered so it seemed to make more sense to co-locate them both in this component.

**Comment by felixarntz** [comment] 2021-05-20 02:51
https://developers.google.com/protocol-buffers/docs/overview#oneof
@aaemnnosttv 
> Good point – I think as far as the ACs are concerned, we should just return `null` for such questions since a scaffolded component would end up doing the same anyways, so I don't see much benefit in doing that ahead of time.

Sgtm.

> Yeah, although it's hard to see what it would be for the others without example objects. From what I could tell that structure was more/less provided in the individual `answer_choice` objects (with the exception of `open_text`). What specifically should we add here to clarify?

The exact structure of each type is defined as a "proto" in the [design doc](https://docs.google.com/document/d/1jqUg4blDUFu6BCyHQVgzlz9smxK0UGrzsOpPojo2EJM/edit?pli=1#heading=h.qxbkeiyvcd7o),. However, for now it's fine here again to only implement support for the `rating` type, i.e. it needs to have the format like in the JSON I posted in my previous comment here.

> Yeah, I found that definition to be a bit difficult to follow. E.g. `RatingAnswer` rating appears to have a key of `rating` in the aforementioned `answer` object, but it doesn't according to your example JSON. Is this format documented somewhere?

The structure definitions in the design doc are in so-called "proto" format, which is the [OS protocol buffers format](https://developers.google.com/protocol-buffers/docs/overview). It's commonly used at Google to precisely describe entities and APIs in a code language-independent way. To your question specifically, the `rating` name there is irrelevant for the eventual code / JSON to represent this "proto", since it's just part of a [`oneOf` definition](https://developers.google.com/protocol-buffers/docs/overview#oneof).

Summarizing, can you iterate on the ACs a bit to clarify the format for the `question_answered` event? We only need to cover a `rating` answer for now, for other question types, the implementation could just bail early / do nothing. For the `rating` answer format, you could also refer to the example JSON I posted above. I think with that in place this should be good for IB.

**Comment by aaemnnosttv** [comment] 2021-05-20 16:16
> The structure definitions in the design doc are in so-called "proto" format, which is the [OS protocol buffers format](https://developers.google.com/protocol-buffers/docs/overview). It's commonly used at Google to precisely describe entities and APIs in a code language-independent way. To your question specifically, the `rating` name there is irrelevant for the eventual code / JSON to represent this "proto", since it's just part of a [`oneOf` definition](https://developers.google.com/protocol-buffers/docs/overview#oneof).

Thanks, that's really helpful 👍 

> Summarizing, can you iterate on the ACs a bit to clarify the format for the `question_answered` event? We only need to cover a `rating` answer for now, for other question types, the implementation could just bail early / do nothing. For the `rating` answer format, you could also refer to the example JSON I posted above.

I've updated the ACs to elaborate on these points, let me know what you think.

**Comment by felixarntz** [comment] 2021-05-20 16:23
@aaemnnosttv Almost lgtm, one thing to improve though:

> `answerQuestion( { answer_ordinal: 4 } )`

This approach doesn't have the necessary flexibility to support any kind of question type. The variable piece that differs per question type is the outer `answer` entry. So it would be more appropriate for `answerQuestion` to reflect that, i.e. for a rating answer it should be like `answerQuestion( { answer: { answer_ordinal: 4 } } )`.

**Comment by aaemnnosttv** [comment] 2021-05-20 16:57
Ah okay, thanks for clarifying @felixarntz – updated!

**Comment by felixarntz** [comment] 2021-05-20 17:24
LGTM!

**Comment by tofumatt** [comment] 2021-05-25 12:29
I had a few questions about the ACs here—they weren't entirely clear to me:

What are the "events" that the ACs refer to here? I assumed it was a `trackEvent` at first, but I don't think that's correct. But I can't find any reference to the events that we should be submitting for User Surveys. Presumably it should include a Form ID, but I don't see any mention of where we get that from the docs/linked issue either. Maybe I'm not looking deep enough, but I can't immediately understand _where we get the form ID from_ or _what kind of event we should be submitting_.

But I've since realised they're in the design docs for the Survey, it just took me a sec to spot it.

That said… we don't seem to have actions or any datastore for these events. Is the intention to submit these REST API requests directly from the components? That doesn't seem like a good idea because we won't be managing the state of the application based on the datastore but instead based on the component managing the response from these API requests.

@aaemnnosttv @felixarntz I think we need to add Redux code to manage submitting these events, their responses, and the state of forms in the app (using the REST controller in #3374). Or am I missing something?

**Comment by felixarntz** [comment] 2021-05-25 15:12
@tofumatt Have you read the [design doc section on this](https://docs.google.com/document/d/1jqUg4blDUFu6BCyHQVgzlz9smxK0UGrzsOpPojo2EJM/edit?ts=609c08e3#heading=h.rq7ydzj8v084)? I'd recommend reviewing it as it should provide clarity.

The "events" referred to here are specific "survey events" that are sent via a dedicated [endpoint](https://docs.google.com/document/d/1jqUg4blDUFu6BCyHQVgzlz9smxK0UGrzsOpPojo2EJM/edit?ts=609c08e3#heading=h.on3f22l5qjhz), so they are unrelated to the GA event tracking.

A `sendSurveyEvent` datastore action is being implemented in #3355 - @aaemnnosttv should this maybe become a dependency here? Regarding handling responses, note that these requests can be made asynchronously and the components don't even need to wait for the response since that response is just an empty 200 or an error if something fails, but such an error shouldn't have user-facing consequences.

**Comment by aaemnnosttv** [comment] 2021-05-26 08:25
Sorry for the confusion @tofumatt – I've added #3355 as a dependency here (I thought it was already but must have been missed). The event sending is mentioned in the ACs but it's maybe out of place after all of the events are listed:

> The full `event` object is composed and sent to the server by the `sendSurveyEvent` action added in #3355

---

> Create `assets/js/components/surveys/index.js` to house the new `Survey` component.

The directory here is intended to contain all the `Survey` components. While `Survey` will be composed of _most_ of the other components in this directory, there are others that are higher-level (currently only `CurrentSurvey`) so this directory is just for organization. Also, components defined in an index should always have the directory named the same as the component.

> * Keep track of each question's state in the `core/forms` data store using the form's ID—while initially we'll only have a one-question-survey, ensure multi-question surveys work and can be "navigated" across questions
> * Keep track of which question in the array of questions the user is "on"/eg. is active in the `core/forms` data store using the form's ID.

You mention the form ID a few times but it isn't clear where this comes from. Should we add a new prop for this or is this something we can derive from `questions` and `completions` props maybe?

> Using `trackEvent`, send a `'survey_shown'` event with the ID of the survey when it is first mounted

As @felixarntz mentioned in the previous comment, these events are sent using a dedicated `sendSurveyEvent` action, which is mentioned in the ACs but perhaps not in the best place (I'll update this). See #3355 for more about how this action should be used.

Also, note that the client doesn't currently store/expose the survey ID as it isn't needed by anything on our end. Events are associated with the survey by the `session` which is included in the data (handled automatically by the action).

> See the above ACs for how to render each survey question, using the `SurveyQuestion` component and passing the `answerQuestion` prop

This is a bit complicated so it would be good to provide a bit more detail as to what's needed here. For example, the `answerQuestion` prop function which is passed is question-specific and needs to wrap the value it's called with with some additional data before sending the event. This is outlined in the ACs but may not be obvious.

> * Once a question is marked as answered, render `SurveyCompletion` instead of a question. (See ACs for implementation, as they're quite thorough.)

Note that a completion is only shown after all questions have been answered, but this might be interpreted as each question has its own completion to show.

> Jest/unit tests to ensure the proper events are submitted based on user interaction would be useful to add here.

This sounds rather optional, but component tests are required by the ACs :smile:

Testing submitted events would be good, but there is a fair amount of complexity around the display of questions and completions which I think is important to cover as well as making sure the Survey is no longer shown when dismissed/completed.

---

Finally, let's also add some detail around the logic for when the survey has been **completed** and should no longer be displayed – see `ctaOnClick`. The `dismissSurvey` prop should also do the same thing, with the added event.

Regarding the estimate, I think this one is probably the largest in the epic and probably closer to a 19.

**Comment by tofumatt** [comment] 2021-05-26 11:05
Thanks for the feedback and clarification! I think I've addressed everything, though there's one UX question I have. There seem to be two ways to cause a survey not to be shown again: dismissing the survey (`survey_dismissed` event) and clicking the follow-up link (`follow_up_link_clicked` event).

Maybe I missed it in the doc, but what happens if I complete a survey, but don't dismiss/CTA link it, and then refresh the page or navigate away and then back to the page that causes the survey to render? It seems annoying to prompt the user with a completed survey, _especially_ if there's no CTA and only a "dismiss" action.

If there isn't a CTA link should be automatically dismiss the survey on page navigation? Or is that covered in the survey trigger check and I missed it? If so: apologies.

Understanding more of the issue and especially the tests needed—I agree this is at least a 19. Arguably it's maybe more like a 19-25, but we don't have that and 30 points seems excessive, but flagging that here as it's on the upper-end of a 19 estimate I think! 🙂

**Comment by aaemnnosttv** [comment] 2021-05-26 18:24
> though there's one UX question I have. There seem to be two ways to cause a survey not to be shown again: dismissing the survey (`survey_dismissed` event) and clicking the follow-up link (`follow_up_link_clicked` event).
> Maybe I missed it in the doc, but what happens if I complete a survey, but don't dismiss/CTA link it, and then refresh the page or navigate away and then back to the page that causes the survey to render?

Surveys aren't persisted in the cache so it wouldn't be shown again until it was triggered again. For this one, it's triggered by viewing the main dashboard but it has the cooldown period of 1 hour between showing which would be the soonest one would see it again if not completed/dismissed (assuming the proxy returned it again when triggered). 

> If there isn't a CTA link should we automatically dismiss the survey on page navigation? Or is that covered in the survey trigger check and I missed it? If so: apologies.

Not 100% sure about this, but I believe we can assume there will always be a CTA text and link for every completion. @felixarntz ?

> Understanding more of the issue and especially the tests needed—I agree this is at least a 19. Arguably it's maybe more like a 19-25, but we don't have that and 30 points seems excessive, but flagging that here as it's on the upper-end of a 19 estimate I think! 🙂

Yeah, 30 does seem a bit high but it also probably depends a bit who's doing it. Better to err on the safe side and come in under, but maybe you should even plan on taking this one since you're the most familiar with it now :wink:

---

> * Using [`sendSurveyEvent`](https://github.com/google/site-kit-wp/issues/3355), send a `'survey_shown'` event when it is first mounted, eg `sendSurveyEvent( 'survey_shown', { session_id, session_token } )` Every time the survey is mounted this should be shown, not just the first time it's shown.

The second argument of `sendSurveyEvent` corresponds to event data only – the session part of it is provided for you by the action so your example there only needs the first argument.

> Note that we know a survey is completed when the question answered matches the `completion_ordinal` value for this survey, obtained from the `Completion` object.

Not sure exactly what you mean here – the `completion_ordinal` is not related to a question, but essentially defines the order that the completions should be checked in, determining which should be displayed based on their `trigger_condition`.

Also, it would be good to disambiguate "survey is completed" between all questions being answered, and the survey being fully-completed and should no longer be shown. Maybe these can be referred to as question-complete and completion-complete although maybe there's a better way to describe it? :smile:

I think the only detail that might still be missing is handling the conditions when it should render `null` due to being completion-complete or dismissed.

---

Regarding the test coverage, what you have is great, I would just ammend the completion-related point to note that we should test that the correct completion is shown since there is logic around which one should be displayed.

Otherwise, I think this is quite close, just a few minor details left to address.

**Comment by felixarntz** [comment] 2021-05-26 18:50
@aaemnnosttv @tofumatt 

> > If there isn't a CTA link should we automatically dismiss the survey on page navigation? Or is that covered in the survey trigger check and I missed it? If so: apologies.
> 
> Not 100% sure about this, but I believe we can assume there will always be a CTA text and link for every completion. @felixarntz ?

We should not assume there will always be a CTA link in a confirmation prompt, so the displaying needs to be conditional.

Great question though about when to close the survey exactly. I suggest to do the following:
1. If there is a CTA and the user clicks it, the survey should be closed. In other words, first send the `follow_up_link_clicked` event, then the `survey_closed` event. The links here are expected to be external and should therefore open in a new tab. That is why here Site Kit needs to close the survey, so that, when they come back, it's no longer open.
2. If the user manually closes the survey, of course the `survey_closed` event should be sent.
3. Otherwise, we _should not_ send the `survey_closed` event. If the user saw the completion, the proxy will also know that the user has completed the actual survey (via `completion_shown` event), so in that case it won't surface the survey again from the trigger API call. When they hit the dashboard again, the survey will be gone anyway.

Does that make sense?

**Comment by tofumatt** [comment] 2021-05-27 11:34
Thanks a lot @felixarntz, that totally makes sense! 👍🏻 

@aaemnnosttv There's just one thing I'm not clear on, which is how we know the survey is completed. Do we base it on the number of questions from the survey matching the question index? I guess that makes sense, but just confirming that's the approach.

**Comment by aaemnnosttv** [comment] 2021-05-27 14:49
> There's just one thing I'm not clear on, which is how we know the survey is completed. Do we base it on the number of questions from the survey matching the question index? I guess that makes sense, but just confirming that's the approach.

That's one way to do it I suppose since the ordinals are 1-based indexes. It could be as simple as the number of answers provided matching `questions.length` but maybe using ordinals would be better? Either way would work I think.

---

Almost there @tofumatt !

> Keep track of each question's state in the `core/forms` data store using the Session ID (`session.session_id`, obtained from the [`getCurrentSurveySession()` selector](https://github.com/google/site-kit-wp/issues/3355).)

I should have mentioned this before, but since this component is intended to be for _a survey_ rather than the current survey specifically, it shouldn't use any `currentSurvey` selectors. Instead I think we can just pass the `formID` as a prop and pass this through from `CurrentSurvey` which is the more appropriate place to select the session. Let's update any references to `session.session_id` with `props.formID`.

Alternatively we could pass `state` and `setState` as props, and then this component doesn't need to be aware of how it's stored. Then the parent could pass these from `getValues` (object) and `setValues` (function) scoped to the session ID as the `formID`. Maybe that's overly abstract though, just an idea.

> * Pass a `dismissSurvey` prop (function) to both "question" and "completed" components to allow the user to dismiss the survey. This would send a `survey_dismissed` event with the user's Session ID and Session Token. This tells the proxy not to show the survey either.

There is no `survey_dismissed` event, `survey_closed` is used for both dismissal and closed by completion.

Also, this still refers to using the session which can't be provided to the action, only event data can; the session is provided internally.

**Comment by tofumatt** [comment] 2021-05-27 15:57
Feel free to assign this issue to me if it's approved 👍🏻

**Comment by aaemnnosttv** [comment] 2021-05-27 16:41
@tofumatt looks great, just one thing – let's rename the `sessionID` prop to `id`. It can still receive the `session.session_id` for this from the parent, but as far as the component is concerned, it's just a unique identifier (it doesn't actually care about the session). Later, if needed we can pass the actual survey ID through the same prop if we decide that is better but it wouldn't require any changes here. Otherwise, this LGTM 👍

**Comment by tofumatt** [comment] 2021-05-27 16:45
I thought about that, but was worried it might get confusing because there's a `surveyID` and a `sessionID`. But fair enough, I'll make it more generic 🙂

**Comment by aaemnnosttv** [comment] 2021-05-27 16:48
IB ✅ 🎉 😂

**Comment by aaemnnosttv** [comment] 2021-06-03 16:02
@felixarntz after discussing with @tofumatt, we decided to use `currentSurvey*` selectors inside of `Survey` rather than taking the questions and completions as props for now. The main reason being that the `sendSurveyEvent` is still scoped to the current survey anyways and it doesn't make much sense to decouple this right now (e.g. also passing as a prop). It still makes sense to keep this separate from `CurrentSurvey` since that handles the portal and conditional logic, but for now they will both be current-survey specific. @tofumatt felt this would be easier to implement for now as well so I'll go ahead and amend the ACs with this minor change and we can revisit decoupling these more in the future as we iterate on survey infrastructure as a whole.

**Comment by felixarntz** [comment] 2021-06-03 16:18
@aaemnnosttv @tofumatt That's fair, but I think we should then not name that component `Survey`. How about we call that one `CurrentSurvey` and the other one `CurrentSurveyPortal` or `CurrentSurveyLoader` or something like that?

**Comment by tofumatt** [comment] 2021-06-03 19:33
@felixarntz That works for me; I'll adjust the component names in the PR for this issue 👍🏻

**Comment by ivankruchkoff** [comment] 2021-06-14 12:34
QA ❌

Following story isn't loading:
https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-surveys-currentsurvey--survey-answered-positive-story

**Comment by aaemnnosttv** [comment] 2021-06-15 07:28
Back to you for another pass @ivankruchkoff.

**Comment by ivankruchkoff** [comment] 2021-06-15 13:52
QA ✅
Confirmed the events are sending per AC following removing the fetchMock calls.

**Closed** 2021-06-22 04:00 UTC
Labels: P0, QA: Eng, Rollover, Type: Enhancement
