### ISSUE TITLE
Behaviour of the Tooltip is different on mobile

### ISSUE THREAD

**Issue by FlicHollis** [google/site-kit-wp#5932] opened 2022-09-27 20:03 UTC
Asana bug bash board: https://app.asana.com/0/1202913874897532/1202986570111446

While testing [5621](https://github.com/google/site-kit-wp/issues/5621) I noticed when I test on smaller screen sizes like mobile devices, the tooltip hovers over the top of the GA4 area, but when you scroll it jumps to above the property. You can find a screencast below detailing the issue.  In my opinion, it's minor so not a launch blocker.

https://user-images.githubusercontent.com/73545194/190143950-7db443de-2938-4af1-aa54-3a368577178b.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria
* Tooltips positioning should be consistent across breakpoints and upon page interaction (for e.g scroll).

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by asvinb** [comment] 2022-09-28 16:31
@wpdarren Not sure if it was fixed as part of other tickets but I can't reproduce the issue. Check the video recording below:

https://user-images.githubusercontent.com/31818/192835499-3d2b8d82-c521-4d8f-9981-6969cccd84d8.mp4

**Comment by wpdarren** [comment] 2022-09-29 08:50
@asvinb that's rather annoying when this happens 😃 but I agree this no longer appears to be an issue.  

Just double checked. I think we can close this ticket.

**Comment by asvinb** [comment] 2022-09-29 08:52
@FlicHollis @eclarke1 As per @wpdarren 's comment, we can close this ticket.

**Comment by FlicHollis** [comment] 2022-10-05 09:31
Thanks @asvinb I will move to closed

**Closed** 2022-10-05 09:33 UTC
Labels: Type: Bug, P1
