### ISSUE TITLE
Add delay to tooltips for all Menu Icons

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6520] opened 2023-02-02 14:40 UTC
## Bug Description

While testing #5775 I noticed that the tooltip still has the user name and email address in it.  Since this is already in the user menu dropdown, it felt unnecessary to include it again.   I started a conversation with Seba and Mariya and they decided that it would be better to remove the tooltip for the new look user menu dropdown. 

The only area we wanted to check was that removing it would not cause any accessibility issues.  

here is a screencast of the tooltip UX. 

https://user-images.githubusercontent.com/73545194/216354787-475a5ff3-b5a7-488e-ac36-ca82607598fa.mp4

## Steps to reproduce

1. Set up Site Kit 
2. Go to the header navigation on the dashboard
3. Hover over the User menu dropdown (avatar in the top right) 
4. See the users name and email address in the tooltip. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Tooltips in all `<Button>` components having an `icon` prop, which when clicked, display a `<Menu>` should have a 500ms delay before appearing. 
  * Once this tooltip is visible, moving the mouse to another component with a tooltip should not result in that second component's tooltip also being delayed `500ms`. This is already the default behaviour of the tooltip, see: https://github.com/google/site-kit-wp/issues/6520#issuecomment-1702635291. This behaviour should be preserved and not overriden.
* This should be the default behaviour for all such `<Button>` components with the ability to easily "disable" this delay if needed via a prop.
* When the icon button is clicked, the tooltip should disappear "instantly" and not have a slower fading out "transition" that it currently has.
* The following components should have their behaviour updated as above:
    * `DateRangeSelector`
    * `HelpMenu`
    * `UserMenu`
* The tooltip implemented in GMail and other Google products can be used as a guide.

https://user-images.githubusercontent.com/1721319/219363287-f8966251-402b-4123-9ba4-2e2fbfa91afb.mov

## Implementation Brief

* Inside `assets/js/googlesitekit/components-gm2/Tooltip.js`:
    * Introduce a new `enterDelay` prop in the `Tooltip` component with `undefined` as the default value, meaning it will rely on MUI's defaults by default.
    * Pass this value to `<MuiTooltip>`, eg. `<MuiTooltip enterDelay={ enterDelay }>`
* Inside `assets/js/googlesitekit/components-gm2/Button.js`:
    * Introduce a new `tooltipEnterDelayInMS` prop in the `Button` component
    * If `tooltipEnterDelayInMS` is present, pass it as `enterDelay` to the `Tooltip` in the `Button` component
* Locate the appropriate  `Button` components in `DateRangeSelector`, `HelpMenu`, and `UserMenu`  and configure `tooltipEnterDelayInMS` to be `500`

### Test Coverage

* No tests needed.

## QA Brief

* Navigate to Site Kit Dashboard
* Hover over account icon - verify that tooltip shows with delay
* Navigate away bellow
* Hover over next icon on the left, verify that tooltip shows with delay
* Navigate away for few seconds, and repeat with remaining menu items - help, sharing and date range
* When navigating right away between icons, tooltip is not expected to show with delay

## Changelog entry

- Add tooltip appearance delay for header icon buttons.

**Comment by wpdarren** [comment] 2023-02-02 23:27
@jimmymadon you make a good point, but I will let @marrrmarrr @sebastianmantel make the call here. 😄

**Comment by sebastianmantel** [comment] 2023-02-05 08:50
Hey @jimmymadon Can we add a delay appearance to the tooltip to avoid overlapping with the dropdown?

**Comment by aaemnnosttv** [comment] 2023-02-07 14:31
@sebastianmantel I think this is possible and would be preferable as an enhancement here as the brief overlapping of tooltip and menu applies to other elements in the SK header today, such as the Help and Date Range controls.

I would suggest we redefine this issue to be a more general enhancement for elements that have a tooltip and a menu. Does that sound good to you?

**Comment by bethanylang** [comment] 2023-02-08 12:15
Thanks @sebastianmantel and @aaemnnosttv! @jimmymadon, reassigning back to you to make this issue more general and work on ACs, if that's okay!

**Comment by aaemnnosttv** [comment] 2023-02-15 20:33
@jimmymadon @sebastianmantel compared to the Gmail interface, our tooltips do show nearly right away while Gmail seems to have ~.5sec before the tooltip is shown. Another big difference that you alluded to @jimmymadon is that our tooltips seem to have a transition when they disappear which is largely responsible for the overlapping tooltip + menu that gives that interaction a bit of a clumsy feel. Tooltips in Gmail for example disappear immediately when a menu is clicked which eliminates the overlap.

I agree that the focus here seems to be more about the transition from tooltip showing to menu opening, but a delay in the tooltip display would make for a less "busy" interaction when the user intends to click on an element there like you said. I think it would make sense to address both here.

**Comment by aaemnnosttv** [comment] 2023-03-03 17:26
AC LGTM, thanks @jimmymadon 👍

**Comment by tofumatt** [comment] 2023-03-08 21:21
My one concern here was around keyboard navigation and delay, because while the delayed hover effect is fine, the delay in the tooltip appearing when navigating with the keyboard struck me as a bit odd.

It _is_ how it's implemented in Gmail:

![CleanShot 2023-03-08 at 21 17 48](https://user-images.githubusercontent.com/90871/223852393-f042dd87-6ed7-4143-ae3d-fda77336ee42.gif)

Personally I find it a bit odd and "slow" feeling when the button focus is instant but the hover takes some time, but I think it's acceptable.

**Comment by tofumatt** [comment] 2023-03-08 21:29
@sashadoes The ACs here call for a `500ms` delay, why the `100ms` default delay value for the `Tooltip` component?

Oh, wait, I see, that's for the delay in the tooltip being closed, right? Let's use a clearer name for that, like `msBeforeTooltipCloses` or something.

Maybe `msToDelayTooltipAppearing` would be a clearer name than `tooltipDelay` (typo in the IB is `tooltipBelay` as well.

> In order to make `Tooltip` disappear "instantly" the new function for `onClose` action in `MuiTooltip` can be used

Isn't `onClose` a handler for when the tooltip _is_ closed? Can you provide an example for how that would look? I don't quite follow.

**Comment by tofumatt** [comment] 2023-05-24 13:14
The IB here needed some adjustments as there are built-in MUI props for this behaviour, but I've made the adjustments so this can now go into EB.

**Comment by zutigrm** [comment] 2023-09-01 11:59
Noting one edge case. The original delay of 500ms for showing tooltip works as intended on original hover. But if you proceed to go immediately to next icons after tooltip shows for one menu item, delay is ignored by component:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzlmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cc4ba8f748e8b07aafe2e06547c1837660e9c87c/Screen%20Recording%202023-09-01%20at%2012.45.02.mov)

Which is how this component (from material UI core - external library), behaves:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEJmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--76209cbf74829e42c75b3a4aafc110b706892263/Screen%20Recording%202023-09-01%20at%2012.45.37.mov)

Which is actually pretty useful feature in this case, as it address the Accessibility concern @tofumatt raised - while switching between menu items, tooltip will not be delayed. But for original intent - user going just for a click, tooltip will not be shown, and for users just hovering to see tooltip, they won't need to wait in between the menu items to see tooltips.

**Comment by nfmohit** [comment] 2023-09-05 06:13
> Noting one edge case. The original delay of 500ms for showing tooltip works as intended on original hover. But if you proceed to go immediately to next icons after tooltip shows for one menu item, delay is ignored by component:

Hi @zutigrm. This can be resolved using the [`enterNextDelay`](https://mui.com/material-ui/api/tooltip/#Tooltip-prop-enterNextDelay) prop from the Tooltip API.

> Which is actually pretty useful feature in this case, as it address the Accessibility concern @tofumatt raised - while switching between menu items, tooltip will not be delayed. But for original intent - user going just for a click, tooltip will not be shown, and for users just hovering to see tooltip, they won't need to wait in between the menu items to see tooltips.

That is a good call. However, I think that contradicts the original purpose of this issue. The subsequent tooltips still show instantly in this case. @tofumatt Do you think we should retain this behaviour, or should we implement the delay for all the menu items?

**Comment by tofumatt** [comment] 2023-09-05 09:55
Nothing in the ACs here says we can't have subsequent delays be "immediate", but I can understand that it's confusing. I've amended the ACs to be clearer about that, but only the "first" tooltip should have a delay.

Once a tooltip is visible, it's fine for the others to "immediately" show.

**Comment by wpdarren** [comment] 2023-10-09 09:41
### QA Update: ✅ 

**Verified:**

- When navigating to Site Kit Dashboard and hovering over account icon, the tooltip shows with delay.
- When navigating away, and I hover over next icon on the left, the tooltip shows with delay.
- When navigating away for few seconds, and repeat with remaining menu items - help, sharing and date range
the tooltip does not show with a delay.

The delay has dealt with the initial issue of tooltip appearing at the same time as the user menu appears 👍 

<details>
 <summary>Screencasts</summary>

https://github.com/google/site-kit-wp/assets/73545194/8bcc0346-499b-4ca0-bc2e-393e48638499
https://github.com/google/site-kit-wp/assets/73545194/fc418879-b00c-4742-a551-ebe7d7959e7a

</details>

**Comment by aaemnnosttv** [comment] 2023-11-03 19:26
This looks good but could be enhanced slightly in that the tooltip is can be invoked for an open menu if another item is hovered and then the open menu's item is hovered. It's not blocking here but worth addressing in a small follow-up.

<img width="284" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/866f6930-06fe-4443-8071-270979f9f3d7">

**Closed by aaemnnosttv** 2023-11-03 19:26 UTC
Labels: P2, Type: Enhancement, Good First Issue, Exp: SP
