### ISSUE TITLE
Release 1.99.0

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6854] opened 2023-04-11 18:12 UTC
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Release is prepared, tested, and deployed to wordpress.org.

## Implementation Brief

* N/A

## QA Brief

* N/A

## Changelog entry

* N/A

**Comment by wpdarren** [comment] 2023-04-21 11:00
### QA Update: ✅ 

- I went through our usual release checklist.
- Double checked the Analytics module. While GA4 Reporting is in a feature flag, I wanted to make sure everything worked as expected.
- Completed testing with `GA4 Reporting` and `GTE Support` feature flags disabled as we'll be testing before launch.

**Comment by mohitwp** [comment] 2023-04-21 11:02
### QA Update ✅ 

- Tested QA checklist.
- Tested both gathering and zero data state.
- Verified functionality without enabling 'ga4reporting' and 'GTESupport' feature flag.
- Tested Ga4Activation banner functionality.

**Comment by techanvil** [comment] 2023-04-21 15:51
## QA :white_check_mark: 
- Smoke tested.
- Verified the changes I’ve been involved with*
- Performed some ad-hoc testing.

:warning: I did spot a bug while testing, however this is not a regression and so it should not impact this release. The bug is that the Entity Ownership Changed notice is being displayed even when there are no shared roles for the module (this makes the notice text a bit misleading as it states "you're granting other users view-only access"). I've created a new issue for it: https://github.com/google/site-kit-wp/issues/6952

\* I also noticed the AC for #6838 are not fully met due to a console error when on the view-only dashboard while GA4 is gathering data. However, this has been raised separately in #6944 and a comment on that issue indicates it should be fixed in #6897.

**Comment by tofumatt** [comment] 2023-04-21 19:31
### QA ✅ 

* Tested issues in the release
* Smoke tested features, mostly Analytics + Tag Manager
* Tested an existing and previous site with GTE support enabled and disabled
* Didn't do any testing with the GA4 Reporting flag enabled as we all did lots of testing just a few days ago with it on 🙂 

All looks good to me 👍🏻

**Comment by nfmohit** [comment] 2023-04-23 10:46
## Release Tested ✅

- Release tested 1.99.0 thoroughly.
- Set everything up from scratch on a live (InstaWP) site.
- Didn't spot any unexpected console errors.
- Verified UI in different device breakpoints.
- Verified changes I've been involved with.
- Used our release testing checklist to ensure everything is checked.
- Tested with the `gteSupport` feature flag on and off.
- Didn't test with the `ga4Reporting` feature flag as we'll we just tested it with E2E testing and bug bash.

**Comment by hussain-t** [comment] 2023-04-24 11:08
## QA Verified :white_check_mark:
- Smoke tested.
- Verified the changes I’ve been involved with.
- Performed some ad-hoc testing.

**Closed** 2023-04-24 19:17 UTC
Labels: P0, Type: Task
