### ISSUE TITLE
Add datastore infrastructure to dismiss notifications.

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#8974] opened 2024-07-08 01:44 UTC
## Feature Description

This issue focuses on adding an action and a selector as wrappers to the `dismissed-items` partial functions to dismiss notifications within `core/notifications`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `dismissNotification(id, { expiresInSeconds })` action should add a dismissed notification as a dismissed item. 
* An `isNotificationDismissed(id)` selector should check if the notification is dismissed or not.

## Implementation Brief

Wait for #8973 to be merged so the datastore has been scaffolded. 

* [x] Within `assets/js/googlesitekit/notifications/datastore/notifications.js`:
  * [x] Add a new action to `baseActions` as defined in the AC.    
    * Include invariants for the notification's `id` since the invariant for the `dimissItem` action assumes the item to be a tour.
    * Forward / dispatch a call to the `dismissItem(slug, {expiresInSeconds})` action within the `core/user` datastore.
   * [x] Similarly, create a new selector to baseSelectors as defined in the Ac.
     * Return the result of a call to the `isItemDismissed(slug)` selector to check if a given notification is dismissed or not.
* [ ] Add the new partial datastore to the `combineStores` function call in the `index.js` file.
### Test Coverage

* Add tests for the new action and selector.

## QA Brief

*Smoke test the plugin, mainly the dashboard to check for any new console errors.

### QA: Eng

* Use the console to test the new action and selector.
  ```javascript
  await googlesitekit.data.dispatch('core/notifications').dismissNotification('some-notification', { expiresInSeconds: 3 });
  ```

  ```javascript
  await googlesitekit.data.select('core/notifications').isNotificationDismissed('some-notification');
  ```

## Changelog entry

* Implement the dismiss functionality for the new notifications infrastructure.

**Comment by eugene-manuilov** [comment] 2024-07-09 17:20
AC + IB ✔️, but the estimate is too high, I will reduce it to 7 since that is more than enough for this task.

**Comment by jimmymadon** [comment] 2024-07-10 14:57
@eugene-manuilov Yes ok - I think the real estimate here was probably slightly more than 3 (making it a 7). So thats why I just went up one level like we do for all issues.

**Comment by mohitwp** [comment] 2024-07-23 09:55
### QA Update ✅

- Tested on dev environment.
- Verified plugin setup.
- Verified main and entity dashboard.
- Verified no console error appearing on main and entity dashboard.
- Verified data according to date range.
- Verified zero and gathering data state.
- Verified all modules setup.
- Verified all functionalities working same as latest environment and as expected.


<details>


https://github.com/user-attachments/assets/275779ab-5828-4611-851a-6170331e5512

https://github.com/user-attachments/assets/d4cd0df8-d27e-41d4-a5a6-fe6f7e84963e


https://github.com/user-attachments/assets/d8d99255-a45f-43fb-8250-644d0df4c685


https://github.com/user-attachments/assets/96d1d8b2-928d-4ccd-bb51-9b10b97ea66f


https://github.com/user-attachments/assets/97e22dd3-9ca6-4dcf-8ccf-db0bcb35651c

</details>

**Comment by 10upsimon** [comment] 2024-07-23 13:15
### ENG:QA Update ✅

- Tested within the console on latest `develop` branch
- ✅ API request to dismiss banner ID passed
- ✅ API to retrieve dismissal status for said banner ID passed

See details below. I did have one observation that I synced with @jimmymadon on where a notice ID was still marked as expired even after the expiry time _unless the page was reloaded or another notifications API request was made_. It turns out this is intended behaviour as we never want a notice to show again (even if dismissed) on the same page view session.

<details>

https://github.com/user-attachments/assets/85fec1e4-d0b1-48ee-a478-23653be76d34

</details>

**Closed** 2024-07-25 18:12 UTC
Labels: P2, Type: Enhancement, QA: Eng, Team S
