### ISSUE TITLE
Search Console data is not yet available: Investigate API data to improve dashboard notice

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1742] opened 2020-07-06 16:55 UTC
## Bug Description

At present users may see data when checking the Search Console web interface yet their Site Kit dashboard will display the following notice:

`Search Console data is not yet available `

![image](https://user-images.githubusercontent.com/41326532/86616364-a2374500-bfad-11ea-9a8e-94e0a83e9f42.png)

This blue box may occur in the following conditions:
- Search traffic is low  
- A site is new and not ranking in Google
- Visitors are all direct traffic 
- A new property was just created

With our current setup if there is data in Search Console **yet no data returned from the API** it may require more research into the endpoints being used or how we're using them. 

Is there is some data being passed via the API yet the notice appears we should provide a more suitable description other than _data is not yet available_,. Something along the lines of "Awaiting sufficient traffic to populate dashboards"

 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment] 2020-07-29 15:33
Duplicate of #467, let's follow up there. Unfortunately the API itself doesn't provide any of this information, but we're still going to improve these messages as much as we can.

**Closed by felixarntz** 2020-07-29 15:33 UTC
Labels: Type: Task
