### ISSUE TITLE
Release 1.96.0

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6655] opened 2023-02-28 19:04 UTC
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Release is prepared, tested, and deployed to wordpress.org.

## Implementation Brief

* N/A

## QA Brief

* N/A

## Changelog entry

* N/A

**Comment by tofumatt** [comment] 2023-03-10 00:22
Ran through usual smoke tests and tested changes I've been involved with (minimal given I've been doing a lot of definition work this/last week!) Tested feature tour behaviours a fair bit as well.

I took the time to test Google Charts behaviour with some extra scrutiny after filing #6708. From what I tested everything was fine and there aren't any _production_ issues with Google Charts right now, just Storybook for now.

All looks good to me, QA ✅

**Comment by wpdarren** [comment] 2023-03-10 06:04
### QA Update: ⚠️ 

I am seeing a console error when I try and set up Analytics via the widget CTA. This is not a regression because I can recreate it on 1.95.0 but I feel this _could be_ a hotfix, so we might want to fix it in the release.  I am unsure when it was introduced but I feel it could be related to the work we've been completing on the SK widget on WP Dashboard.  

The error message is:

```
googlesitekit-vendor-d427c15d17559d7f7544.js:1 Uncaught (in promise) Invariant Violation: url must be a valid URI.
    at e.exports (https://sitekit-196.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-d427c15d17559d7f7544.js:1:2499)
    at https://sitekit-196.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-datastore-location-415b4bf6e1a95f2a5089.js:1:1014
    at https://sitekit-196.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-data-4e9075769c0976070731.js:1:4922
    at https://sitekit-196.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-d427c15d17559d7f7544.js:7:502597
    at https://sitekit-196.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-modules-search-console-2b2573c0a27621d3b1e3.js:17:17078
    at u (https://sitekit-196.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-d427c15d17559d7f7544.js:7:631011)
    at Generator._invoke (https://sitekit-196.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-d427c15d17559d7f7544.js:7:630764)
    at forEach.e.<computed> [as next] (https://sitekit-196.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-d427c15d17559d7f7544.js:7:631450)
    at n (https://sitekit-196.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-d427c15d17559d7f7544.js:1:76260)
    at _next (https://sitekit-196.instawp.xyz/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-d427c15d17559d7f7544.js:1:76475)

```

Please note if you have a site set up with Analytics previously, this issue does not occur, it only appears on the first attempted connection of Analytics on the site.  I was unable to recreate the error on the other Set up Analytics CTA, i.e. admin bar, main and entity dashboard, etc. 

See screencast below.

https://user-images.githubusercontent.com/73545194/224236002-01ba948d-51bf-4d96-a819-e8129b958711.mp4

**Comment by wpdarren** [comment] 2023-03-10 11:13
### QA Update: ⚠️ 

This seems to be a regression because I am unable to recreate it on 1.95.0

We had a similar issue in `1.95.0`  that Tom fixed as you can [see here](https://github.com/google/site-kit-wp/issues/6564#issuecomment-1445665515). 

i think this is the [PR](https://github.com/google/site-kit-wp/pull/6646) that fixed it. 

I am running through the dashboard navigation tooltip tour and if you click 'back' on the final tip, a fatal error appears. In the last release, we had an issue where the error appeared when you landed on the final tooltip, but that does not happen this time around. I am able to complete the tour. 

It's only an issue if `back` on the final tour.  

All the other tooltips behave as expected. 

https://user-images.githubusercontent.com/73545194/224300789-d9752f63-32e7-41b2-b60d-448315e408af.mp4

**Comment by wpdarren** [comment] 2023-03-10 12:07
### QA Update: ✅ 

Other than [this issue](https://github.com/google/site-kit-wp/issues/6655#issuecomment-1463320231) (non regression but ticket created for it) and [this issue](https://github.com/google/site-kit-wp/issues/6655#issuecomment-1463652670)  (Is a regression, Tom investigating) all of my checks have passed:

- Ran through our QA checklist on different sites:
  - A site in gathering state 
  - A site in zero data state 
  - A site with real data
 - Checked GA4 activation banner 
 - Checked Dashboard Sharing (including ensuring the service is enabled without feature flag) 
 - Checked through Site Kit Site Health information. We don't have any test cases for this yet, but I noticed an issue recently so thought I would include it in my testing.

**Comment by techanvil** [comment] 2023-03-10 12:59
## QA :white_check_mark: 
- Smoke tested.
- Verified the changes I’ve been involved with.
- Performed some ad-hoc testing.

Spent some time trying to reproduce the second [issue](https://github.com/google/site-kit-wp/issues/6655#issuecomment-1463652670) mentioned above, but was unable to do so. Found no further issues beyond the [other one](https://github.com/google/site-kit-wp/issues/6655#issuecomment-1463320231) that @wpdarren has raised.

**Comment by nfmohit** [comment] 2023-03-11 08:55
## Release Tested ✅

- Release tested 1.96.0 thoroughly.
- Set everything up from scratch on a live (InstaWP) site.
- Didn't spot any unexpected console errors.
- Verified UI in different device breakpoints.
- Verified changes I've been involved with.
- Used our release testing checklist to ensure everything is checked.
- Smoke tested with available feature flags.
- I wasn't able to replicate [this issue](https://github.com/google/site-kit-wp/issues/6655#issuecomment-1463652670).
- I was able to replicate [this issue](https://github.com/google/site-kit-wp/issues/6655#issuecomment-1463320231).

**Comment by hussain-t** [comment] 2023-03-12 04:51
### QA Update ⚠️ 
- Smoke tested.
- Verified the changes I’ve been involved with.
- Performed some ad-hoc testing.

I spotted an issue with `SearchFunnelWidgetGA4` (GA4 version) when the data is in a zero state. It's not a blocker for the release since it's behind the `ga4Reporting` feature flag. However, it needs to be fixed.


https://user-images.githubusercontent.com/24408261/224524991-a48d96c7-6c47-4a2c-9d86-60f42c855733.mov

**Comment by kuasha420** [comment] 2023-03-12 17:47
:QA: :heavy_check_mark: 

* Went through the release testing checklist on a real site with data and on local. 
* Tested with `userInput` and `gteSupport` and didn't spot any borkeness or console error. 
* Verified the changes I've been involved with. 
* Expect for the known issue that's already in the works, everything LGTM :+1:

**Comment by mohitwp** [comment] 2023-03-13 06:47
### QA Update ✅ 

- **Note** - I've faced the similar issue which Darren mention [above](https://github.com/google/site-kit-wp/issues/6655#issuecomment-1463652670), but when dashboard sharing feature tour appears. Although, error appears only one time for me and on new sites . I'm not able to replicate this.
- Run QA Checlist.
- Tested site on zero and gathering data state.
- Tested Dashboard Sharing functionality and verify that DS icon appears and function properly without enabling Dashboard sharing feature flag.
- Not tested GA4 reporting functionality.

**Closed as completed** 2023-03-13 17:03 UTC
Labels: P0, Type: Task
