### ISSUE TITLE
Refactor `SettingsModules` component

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2184] opened 2020-10-15 23:21 UTC
The `SettingsModules` component should be refactored to be a functional component, relying fully on the datastore. It should be split into sub-components where it makes sense.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SettingsModules` component should be refactored into two new functional, hook-based, datastore-driven components `SettingsActiveModules` and `SettingsInactiveModules`.
* Both of these components should render a list of `SettingsModule` components. The `SettingsModule` component should be refactored at a later point though, to not make this too much work in one issue/PR - all props that `SettingsModule` currently requires should be passed. This can be simplified later once the `SettingsModule` component gets simplified.
* The only thing that should be changed which also affects `SettingsModule` a bit is that the `handleButtonAction` function should be split into more targeted separate action handlers which should be passed as separate props from `SettingsModules` to `SettingsModule`:
    * `handleEdit` should be invoked when the user clicks on the "Edit" button (current action is `edit`)
    * `handleConfirm` should be invoked when the user clicks on the "Confirm" button when editing (current action is `confirm`)
    * `handleCancel` should be invoked when the user clicks on the "Cancel" button when editing (current action is `cancel`)
    * In `SettingsModule`, the three functions should then be invoked on the relevant buttons, instead of the single `handleEdit` with an action passed.
* Both new components should rely on the `getModules` selector of `core/modules` instead of the legacy `getModulesData()` function, then filter out active/inactive modules respectively, and then they should provide props based on the registered module data.
    * There are some pieces of information which are only present in `getModulesData` right now, but not in the data from the `getModules()` selector. When writing the IB, please list these pieces of data. We can then discuss the best way to make them available in the datastore-driven approach.

#### Step 1

* Add a new property `forceActive` to module information data that is returned from the `Modules::prepare_module_data_for_response` method. Use `$module->force_active` to get a value for this property.
* In the `assets/js/googlesitekit/modules/datastore/modules.js` file:
  * Add the new `features` property to the `moduleDefaults` object with an empty array value;
  * Add the new optional `features` argument to the `registerModule` action;
  * Add the new `getModuleFeatures` selector that returns `features` for a module.
* Update modules to set their `features` during module registration in javascript instead of defining the `provides` array in their PHP classes:
  * AdSense: https://github.com/google/site-kit-wp/blob/8cdc1bb03800a297c0d931f0a0213d25079b6165/includes/Modules/AdSense.php#L121-L124
  * Analytics: https://github.com/google/site-kit-wp/blob/8cdc1bb03800a297c0d931f0a0213d25079b6165/includes/Modules/Analytics.php#L158-L162
  * Optimize: https://github.com/google/site-kit-wp/blob/8cdc1bb03800a297c0d931f0a0213d25079b6165/includes/Modules/Optimize.php#L76-L80
  * PageSpeed Insights: https://github.com/google/site-kit-wp/blob/8cdc1bb03800a297c0d931f0a0213d25079b6165/includes/Modules/PageSpeed_Insights.php#L203-L205
  * Tag Manager: https://github.com/google/site-kit-wp/blob/8cdc1bb03800a297c0d931f0a0213d25079b6165/includes/Modules/Tag_Manager.php#L121-L123
* Delete `prepare_info_for_js` methods from the aforementioned module classes.

#### Step 2

* Create a new `SettingsActiveModules` components in the `assets/js/components/settings` folder:
  * Create a new state variable using the `useState` hook to store an error;
  * Get modules using the `getModules` selector from the `core/modules` datastore and filter out inactive and internal modules;
  * Select module features using the `getModuleFeatures` selector from the `core/modules` datastore which should be used instead of the legacy `provides` list;
  * Grab the `submitChanges` dispatch function from the `core/modules` datastore;
  * Create a new callback `onEdit` that accepts a single module slug argument and calls the `setModuleState` prop callback using the module slug and `edit` string parameters;
  * Create a new callback `onConfirm` that accepts a single module slug argument and does the following:
    * Calls the `submitChanges` function passing the module slug parameter;
    * Sets the error object state if the `submitChanges` function returns an error;
    * If no error received, then clear web storage using the `clearWebStorage` function and call the `setModuleState` prop callback using the module slug and `view` string parameters;
  * Create a new callback `onCancel` that accepts a single module slug argument and calls the `setModuleState` prop callback using the module slug and `view` string parameters;
  * Render active modules using a similar approach from the legacy component. Use the `forceActive` module property instead of `autoActivate`.
* Create a new `SettingsInactiveModules` components in the `assets/js/components/settings` folder:
  * Grab modules using the `getModules` selector from the `core/modules` datastore and filter out active and internal modules;
  * Render inactive modules using a similar approach from the legacy component (if there are inactive modules) but use `SetupModule` elements instead of `SettingsModule` ones;
  * If there are no inactive modules, render the appropriate notification as the legacy component does.

#### Step 3

* Update the `SettingsApp` component:
  * Render the `SettingsActiveModules` element passing `activeModule`, `moduleState`, and `setModuleState` properties when the `activeTabID` equals to `settings` value;
  * Render the `SettingsInactiveModules` element passing `activeModule`, `moduleState`, and `setModuleState` properties when the `activeTabID` equals to `connect`;
  * Remove usage of the `SettingsModules` component.
* Update the `SettingsModule` component:
  * Add `onEdit`, `onConfirm`, and `onCancel` properties;
  * Call the `onConfirm` callback with the module slug in the `onClick` handler for the confirm button if the current module has settings and setup is completed, otherwise, call the `onCancel` callback;
  * Call the `onEdit` function with the module slug in the `onClick` handler for the edit link element;
  * Call the `onCancel` function with the module slug in the `onClick` handler for the cancel link element;
  * Update the `activateOrDeactivate` method not to use `active` state and always call the `activateOrDeactivateModule` function with `false` as the third argument (`status`);
  * <s>Update the usage of the `autoActivate` property, it should be converted to a regular variable which should be equal to `'search-console' === props.slug`;</s>
  * Remove alternative markup which is used when the module is not active (where it renders the `SetupModule` element);
  * Remove all usages of the `active` property state;
  * Remove `submitChanges` and `active` properties;
  * Remove the `withDispatch` settings.
* Delete the `SettingsModules` component.

### Test Coverage

* Update existing tests if any is failing due to the aforementioned changes.

### Visual Regression Changes

* Not expected.

## QA Brief
* Go to the Site Kit settings page.
* The "Connected Services" tab should render the `SettingsActiveModules` component.
* The "Connect More Services" tab should render the `SettingsInactiveModules` component.
* Everything should work as before, i.e, modules can be deactivated/activated.

## Changelog entry

* Update modules settings to use separate components for active and inactive modules.

**Comment by eugene-manuilov** [comment] 2021-02-09 17:51
@felixarntz this is ready for review.

> There are some pieces of information which are only present in getModulesData right now, but not in the data from the getModules() selector. When writing the IB, please list these pieces of data. We can then discuss the best way to make them available in the datastore-driven approach.

We miss `learnMore`, `autoActivate` and `provides` fields in module information received from the `getModules` selector.

**Comment by felixarntz** [comment] 2021-02-17 19:04
@eugene-manuilov IB looks solid! Regarding the missing module fields:
* Let's expose a `forceActive` property for every module in the REST API endpoints, replacing `autoActivate`. This is essential, so it should come from the server.
* Let's remove the `learnMore` / `learnmore` fields in JS, since they don't seem to be actually used.
* Let's add a `features` argument to `registerModule` in JS `core/modules` store, which expects an argument of strings and is optional. We can also add a `getModuleFeatures` selector for them, if needed. These should then be registered as needed for all applicable modules and replace `provides`.

Does that sound good to you? Can you add it to the IB please?

**Comment by eugene-manuilov** [comment] 2021-02-18 12:43
> Let's expose a forceActive property for every module in the REST API endpoints, replacing autoActivate. This is essential, so it should come from the server.

Looks like we use it only in the settings module component and only for the search-console module. I think we can hardcode it in the SettingsModule component in this case and not introduce a new property in the REST API endpoints. Added a note in the IB about it.

> Let's remove the learnMore / learnmore fields in JS, since they don't seem to be actually used.

:+1: We don't call out it in the IB anyway.

> Let's add a features argument to registerModule in JS core/modules store, which expects an argument of strings and is optional. We can also add a getModuleFeatures selector for them, if needed. These should then be registered as needed for all applicable modules and replace provides.

:+1: Added it to the IB.

**Comment by eugene-manuilov** [comment] 2021-02-18 12:44
Also updated estimates to 19 since we extended the scope for this ticket.

**Comment by felixarntz** [comment] 2021-02-19 16:30
@eugene-manuilov 

> Looks like we use it only in the settings module component and only for the search-console module. I think we can hardcode it in the SettingsModule component in this case and not introduce a new property in the REST API endpoints. Added a note in the IB about it.

This shouldn't be hard-coded; on the PHP side this is already controlled, so it's not something we'd need to introduce infrastructure for. The only problem is that it's not exposed via the REST API. The responsibility for force-active modules needs to come from the server either way, since it also needs to be considered for validation purposes (server should never allow a deactivate request for a force-active module). Let's add it to the REST endpoint, the same way that e.g. `internal` is exposed in the REST endpoint.

> Also updated estimates to 19 since we extended the scope for this ticket.

👍 

Other than my one feedback above, this would be good to go.

**Comment by eugene-manuilov** [comment] 2021-02-19 16:48
Ok, should be good now. IB is updated.

**Comment by felixarntz** [comment] 2021-02-19 18:14
IB ✅

**Comment by aaemnnosttv** [comment] 2021-03-19 12:41
Thanks @asvinb – assigning this to @caseymorrisus to take over since this ties in with the work he's doing in #2514 to hopefully result in minimal conflicts.

**Comment by wpdarren** [comment] 2021-03-31 14:57
### QA Update: Fail ❌ 

@asvinb I have confirmed that `SettingsActiveModules` and `SettingsInactiveModules` components are rendered, but when I started to go through the settings functionality, I noticed that when you try and disconnect a module it does not do this successfully. The screencast shows the issue for the PageSpeed module, but the same occurs for all other modules. 

https://user-images.githubusercontent.com/73545194/113165180-4f589880-9274-11eb-8937-042932915e96.mp4

**Comment by aaemnnosttv** [comment] 2021-04-01 09:05
@wpdarren ready for another pass!

**Comment by wpdarren** [comment] 2021-04-01 12:50
### QA Update: Fail ❌ 

@asvinb @aaemnnosttv there's a minor observation. When you click to set up a new module within settings, the load icon appears and then you are taken back to the settings page for around 3-4 seconds before the Google login page appears.  On the latest release this does not happen.  When you click on the 'Set up' link after a few seconds you are taken directly to the Google login page. You are not sent back to the settings page.   Here's a screencast which explains it. 

https://user-images.githubusercontent.com/73545194/113295970-76be6c80-932b-11eb-8844-767366b39dd0.mp4

**Comment by wpdarren** [comment] 2021-04-06 13:03
### QA Update: Pass ✅ 

**Verified:**

- The "Connected Services" tab renders the SettingsActiveModules component. - [Screenshot](https://user-images.githubusercontent.com/73545194/113712955-59b5df00-9719-11eb-8880-d9e1f17dc12c.png)

- The "Connect More Services" tab renders the SettingsInactiveModules component. - [Screenshot](https://user-images.githubusercontent.com/73545194/113712972-5e7a9300-9719-11eb-90ea-6efb7d4490ea.png)

- Everything works as before. All modules can be deactivated/activated with no errors.

**Closed** 2021-04-08 18:03 UTC
Labels: P1, Rollover, Type: Enhancement
