### ISSUE TITLE
Implement new design for Review screen of User Input page with the new Inline Edit interface

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#5891] opened 2022-09-25 20:58 UTC
## Feature Description

The review screen of the User Input page should be updated to implement the new Figma design for User Input v2.

Also,  'Edit' functionality of User Input Review screen is a way for users to make changes to their answers before submitting. Currently, clicking it takes the user back to the questions screen which is a cumbersome UX. To make the experience better, the new Inline edit interface from the Figma design should be implemented. It is similar to how Edit Settings behaves on the Connected Services page. ie. expend the question for editing, lock out other questions, etc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The review screen of User Input page should follow the new design for [desktop](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/SummaryWidget?node-id=1623%3A55374) and [mobile](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/SummaryWidget?node-id=1764%3A46633). 
* This screen should also implement the new inline 'Edit' functionality as seen in the [Figma](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/SummaryWidget?node-id=2076%3A61567) design. 
* Clicking on Edit should expand the question with all available answers where user can update their choice(s).
* Clicking "Edit" on an already opened question should close it and update the answer.
* Clicking "Edit" on a different question while another one is open should close the previously opened one and expand the new one. 
* If the minimum answer requirement is not met and the user closes the inline editor, an error message should be raised as seen in the [design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/SummaryWidget?node-id=2196%3A62664).  
* Similar error message should also be displayed when the user tries to save the answers while not answering a question. 
* The layout, typography, positioning of various UI elements and text copies should exactly follow the design

## Implementation Brief
* Once #5890 has been merged.
* Using `assets/js/components/user-input/UserInputPreview.js`,
	* Style the component and sub components as per the designs in Figma.
	* Add a new heading for the "Review your answers" text.
* Using `assets/js/components/user-input/UserInputPreviewGroup.js`,
	* Add a new prop `slug` which is the question slug.
	* Use the `core/ui` datastore to store the edit state of the preview group, i.e whether the values are being edited or displayed.
		* Style the edit/non edit states as per the designs which should be triggered by toggling the new "Edit" button.
		* When a question group is being edited, the other question groups should no longer be in "edit" state and just the values being displayed.
	* If the state is in edit mode, display the `UserInputQuestionWrapper`, passing on the appropriate `slug` and other props as in `assets/js/components/user-input/UserInputQuestionnaire.js`.
		* There should not be any `next` or `back` buttons, which can be implemented by setting the `back` and `next` props to `false`.
	* When closing a question group, check if there are no invalid values via the `hasInvalidValues` function and display the appropriate error message as per the designs in Figma.
* Using `assets/js/components/user-input/UserInputPreview.js`,
	* Update the `UserInputQuestionnaire` by adding the `slug` prop. The value is hard coded for now and `assets/js/components/user-input/UserInputQuestionnaire.js` can be used as reference for the slugs to be used for each question.

### Test Coverage
* No new tests to be added.

## QA Brief

* Enable the `userInput` feature flag.
* Navigate to `/wp-admin/admin.php?page=googlesitekit-user-input` in order to display the User Input feature.
* Step through the initial three questions to get to the Review section.
* Verify that the Review section has been updated to match the Figma designs (note that some minor variations are expected as discussed [here](https://github.com/google/site-kit-wp/issues/5890#issuecomment-1331083988)).
* Verify the inline Edit functionality behaves as defined in the AC.
* Please note that the error messages will display with the following logic (this is slightly different from what is seen in Figma):
  * If the user has selected "Other" but hasn't entered a value the error message will be _"Please select a valid answer"_.
  * If the question is single-choice and the user hasn't selected a value the error message will be _"Please select an answer"_.
  * If the question is multiple-choice and the user hasn't selected a value the error message will be _"Please select at least 1 answer"_.
* Verify the above in the **User Input > Default** Storybook story.

## Changelog entry

* Improve the User Input review screen and editing interface in Settings.

**Comment by aaemnnosttv** [comment] 2022-10-12 21:12
@kuasha420 I'm not sure it's worth separating the design implementation of the questions and the review step into their own issues. I would think these should be doable together without much extra work. What do you think?

**Comment by kuasha420** [comment] 2022-10-18 06:13
@aaemnnosttv Instead of bloating #5890, how about adding this one with #5893 ?

**Comment by kuasha420** [comment] 2022-10-18 06:58
@aaemnnosttv I have updated this issue to address Inline Edit interface here. We can further tweak this one and close #5893 . What do you think?

**Comment by tofumatt** [comment] 2022-11-01 18:15
Looks good, but the mocks in the Figma design don't seem to show other questions as being "greyed out"/"disabled" when not open:

<img width="597" alt="CleanShot 2022-11-01 at 18 14 09" src="https://user-images.githubusercontent.com/90871/199307566-68bf722e-a20f-4728-9ba2-99db2317e6f9.png">

Should that be part be omitted from the IB?

**Comment by kuasha420** [comment] 2022-11-01 21:36
@tofumatt good spot, the other question should be off screen or not visible at all. There was a discussion about adding some animation ie. sliding in and out the questions, but that discussion got stalled and we didn't have anything definitive from the UX team. 

cc @eclarke1

**Comment by asvinb** [comment] 2022-11-02 08:35
@kuasha420 It'll be a weird UX experience when the user clicks on a question to "Edit" and the other questions are not visible. Consider editing the third question and the first 2 questions are no longer visible which will trigger a big layout shift and can be confusing for the user. I can still see the greyed out other questions on small screens designs:
https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/SummaryWidget?node-id=1764%3A46682

I think for consistency with the Module Settings page and the user input settings, #5897 we should keep the greyed out feature when a question is being edited. Curious to hear your thoughts @tofumatt @aaemnnosttv

**Comment by tofumatt** [comment] 2022-11-02 12:07
I agree with @asvinb… greying them out seems like a good compromise and I think indicates better how it should work. It's also more consistent with the rest of our UIs.

Also I see the greyed out is in mobile but not desktop. I think I mostly looked at the desktop so thought it wasn't part of the design.

Let's go with the greyed out inactive questions, so let's adjust the IB for that, even though it's not in the desktop design. 👍🏻

**Comment by tofumatt** [comment] 2022-11-02 18:28
@asvinb Oh! I just noticed, the mobile view with the greyed out "inactive" questions is actually the admin screen, editing the questions, and not the "initial" User Input page, outside of Site Kit settings. On the non-settings view, there's no greying out of "inactive" questions.

It looks like there's intentionally a difference in the design, probably partially because of what you pointed out. I don't think we should be adding more buttons to the UI; I think for the non-settings UI we shouldn't be greying things out.

Since this is the review screen, let's not do the greyed-out UI at all.

**Comment by asvinb** [comment] 2022-11-03 07:54
@tofumatt IB updated and ready for review.

**Comment by tofumatt** [comment] 2022-11-08 15:33
IB ✅

**Comment by wpdarren** [comment] 2023-01-06 08:41
### QA Update: ❌ 

@kuasha420 I have a number of observations between figma and what I am seeing on my test site.  It's possible that these are known issues, but didn't want to make any assumptions. 

The header `Customize Site Kit to match your goals` is font size 22px in figma but is showing up as 24px.

![image](https://user-images.githubusercontent.com/73545194/210959511-7fb21bb7-9846-43be-b0f9-5255d48ebb8d.png)

The sub header text `Get metrics and suggestions that are specific to your site by telling Site Kit more about your site` has a font color of `#6C726E` but I see `#5f6561` on my test site. 

![image](https://user-images.githubusercontent.com/73545194/210959970-df8eec27-5fd6-4729-96aa-9ee11b2a9556.png)

The progress bar is `#45655C` on figma but on my site it is `#3c7251`

![image](https://user-images.githubusercontent.com/73545194/210960327-7ea18a0c-0780-4dea-ac6e-32a9489f8298.png)

The `Review your answers` text is `Google Sans Text at 12px` on figma but my site is `Google Sans Display at 14px`

![image](https://user-images.githubusercontent.com/73545194/210960894-7fc7480d-d1c6-47c1-ada9-e6827797ddd2.png)

The answers with the shade of green background are different. On figma it is `#B8E5CA` but on my site it is `#b0e6c5`

![image](https://user-images.githubusercontent.com/73545194/210962691-3c67da45-96e3-4070-b2c1-e9251105e3d8.png)

The text `You can always edit your answers later from Settings` has a font color of `#6C726E` on figma but `#5f6561` on my test website. 

![image](https://user-images.githubusercontent.com/73545194/210963169-13fd76c9-7a2b-4fe6-8f94-5bf5b103bc78.png)

**Comment by kuasha420** [comment] 2023-01-08 22:59
@wpdarren As far as I recall, Most of the styling inconsistencies are the result of we sticking with our own size/colors defined in SCSS instead of following Figma. Since @techanvil originally worked on this one, I'm delegating this one to him for further clarification and tweaks if needed. Cheers.

**Comment by techanvil** [comment] 2023-01-09 17:15
@wpdarren thanks for raising these, I've looked into each point.

- 1, 2, 5 and 6: These have been implemented using the correct token/variable, and will be fixed via #6328.
- 3: This is a mistake on Figma, confirmed by Sigal on Slack who is updating the Figma files. The implementation is correct as it stands.
- 4: This needs an update to use the correct token/variables, which I have created a followup PR for: #6387.

**Comment by wpdarren** [comment] 2023-01-12 09:49
### QA Update:  ⚠️ 

@techanvil @kuasha420 

Just one observation:

Re the Figma design [here](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=2196%3A62889&t=liz9jK5PAO0oZnCz-0) -  for the radio button questions. It’s suggesting that you can save without selecting an option, which is not true for the first two questions.  I am assuming this figma design does not apply here, correct? I didn't want to make an incorrect assumption.

**Verified:**

- The review screen of User Input page follows the new design for desktop and mobile. 
- Tested the review screen on supported browsers and various devices. 
- This screen implements the new inline 'Edit' functionality.
- Clicking on Edit expands the question with all available answers where user can update their choice(s).
- Clicking "Edit" on an already opened question closes it and updates the answer in the review screen.
- Clicking "Edit" on a different question while another one is open closes the previously opened one and expands the new.
- On the 3rd question. When the minimum answer requirement is not met and the user closes the inline editor, an error message is raised as seen in the figma design. 
- The layout, typography, positioning of various UI elements and text copies follows the design, other than issues [highlighted](https://github.com/google/site-kit-wp/issues/5891#issuecomment-1373352531). Note: issue 4 in the highlighted comment has been fixed as per screenshot below. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/212033751-4d45d13e-3f19-4e23-a280-27d4a885dbc8.png)
![image](https://user-images.githubusercontent.com/73545194/212033667-988d92fd-79a6-434e-adef-1963001c1802.png)
![image](https://user-images.githubusercontent.com/73545194/212033692-b6a2fe40-b43b-4e22-a287-cc69b40f7e05.png)
![image](https://user-images.githubusercontent.com/73545194/212033720-be5c2ea7-8375-4f0a-80a1-3e14bc96fa5f.png)

</details>

**Comment by kuasha420** [comment] 2023-01-12 10:42
@wpdarren thanks for raising this.

1. Our implementation is correct. This was decided in this issue by @tofumatt to disable the save button.

2. This is another of those GM2+ inconsistencies that will be fixed up by the follow up issue created by Evan.

3. This is also expected as we have removed the text field from the other field and turned it into a regular answer.

Cheers.

**Comment by wpdarren** [comment] 2023-01-12 12:01
### QA Update: ✅ 

**Verified:**

- The review screen of User Input page follows the new design for desktop and mobile. 
- Tested the review screen on supported browsers and various devices. 
- This screen implements the new inline 'Edit' functionality.
- Clicking on Edit expands the question with all available answers where user can update their choice(s).
- Clicking "Edit" on an already opened question closes it and updates the answer in the review screen.
- Clicking "Edit" on a different question while another one is open closes the previously opened one and expands the new.
- On the 3rd question. When the minimum answer requirement is not met and the user closes the inline editor, an error message is raised as seen in the figma design. 
- The layout, typography, positioning of various UI elements and text copies follows the design, other than issues [highlighted](https://github.com/google/site-kit-wp/issues/5891#issuecomment-1373352531). Note: issue 4 in the highlighted comment has been fixed as per screenshot below. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/212033751-4d45d13e-3f19-4e23-a280-27d4a885dbc8.png)
![image](https://user-images.githubusercontent.com/73545194/212033667-988d92fd-79a6-434e-adef-1963001c1802.png)
![image](https://user-images.githubusercontent.com/73545194/212033692-b6a2fe40-b43b-4e22-a287-cc69b40f7e05.png)
![image](https://user-images.githubusercontent.com/73545194/212033720-be5c2ea7-8375-4f0a-80a1-3e14bc96fa5f.png)

</details>

**Closed** 2023-01-12 21:39 UTC
Labels: P1, Type: Enhancement, Rollover
