### ISSUE TITLE
Update module use/insert snippet settings UI for consistency

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1048] opened 2020-01-16 09:59 UTC
## Feature Description

Update use/insert snippet toggles for consistency with to use a switch rather than radio buttons

### Analytics
![image](https://user-images.githubusercontent.com/1621608/72513912-68834e00-3856-11ea-80ef-186bdc9f7319.png)
![image](https://user-images.githubusercontent.com/1621608/72513950-7cc74b00-3856-11ea-86ff-e8e7e5f624c8.png)

> Analytics in particular is rather confusing due to options changing positions, and the wording is almost entirely different

### AdSense
![image](https://user-images.githubusercontent.com/1621608/72514332-28709b00-3857-11ea-89f8-1bfc2fbaa059.png)
![image](https://user-images.githubusercontent.com/1621608/72514331-26a6d780-3857-11ea-970b-363524d03a4a.png)

### Tag Manager
![image](https://user-images.githubusercontent.com/1621608/72514114-bf892300-3856-11ea-8f6e-5804c89b7b0a.png)
![image](https://user-images.githubusercontent.com/1621608/72514117-c0ba5000-3856-11ea-84ee-06423f35fd6b.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Switch GA settings to use the same toggle UI as all other modules. 
* Add sentence: "Let Site Kit place code on your site"
* Toggle on: 
    * toggle text "Site Kit will add the code automatically" 
    *  If the user toggles this on when there's already a GA snippet, display warning below the toggle: "Placing two snippets at the same time is not recommended."  
* Toggle off: "Site Kit will not add the code to your site"

## Implementation Brief

* 

## Changelog entry

* Update Analytics control for whether to place snippet to use a toggle instead of radio buttons for consistency.

**Comment by aaemnnosttv** [comment] 2020-02-07 11:55
This should probably be handled as part of #1101

**Comment by felixarntz** [comment] 2020-04-07 14:49
Assigning to you @aaemnnosttv since you're working on #1101.

**Comment by cole10up** [comment] 2020-05-06 05:42
This is confirmed while testing https://github.com/google/site-kit-wp/issues/1101

Passed QA ✅

**Closed** 2020-05-06 17:24 UTC
Labels: P1, Type: Enhancement
