### ISSUE TITLE
Site verification fails with roots.io's Bedrock environment

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1523] opened 2020-05-07 15:28 UTC
## Bug Description

As reported in a WordPress support topic a standard Roots.io Bedrock setup results in a site verification failure. 

When using Bedrock the default WordPress directory structure is modified, placing all WP files into a `/web` directory. The index.php in the root directly reflects this as below:
`require( dirname( __FILE__ ) . '/wp/wp-blog-header.php' );`

The default admin URL with a Bedrock install is set to /wp/wp-admin.

A solution to #1474 may also apply to this issue. 

## Steps to reproduce
1. Setup site as described following [this guide](https://roots.io/docs/bedrock/master/installation/)
2. Install Site Kit and follow setup steps
3. Verification fails 

## Additional Context

- [Original support topic](https://wordpress.org/support/topic/infinite-verification-loop/#post-12796243)
- Requires further testing from support (tested locally using help plugin)
- Requires testing with workaround as per #1474 (placing redirection in .htaccess file while moving index.php file into WP files)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by Sidlegionair** [comment] 2020-05-07 16:11
Hi @jamesozzie,

I don't suspect the issue is with bedrock's folder structure because we have multiple sites running the same setup (just a branch of same repository with some small mods) and working just fine, the only difference seems to be the absense of Varnish on this website. In fact I just verified https://zzpservicedesk.nl, and it went through just fine.

**Comment by jamesozzie** [comment] 2020-05-07 16:25
@Sidlegionair Thanks for the input, very useful. We'll continue to test from our side.

**Comment by ernee** [comment] 2020-05-15 05:24
Possible related topic: https://wordpress.org/support/topic/redirects-to-google-login-after-logging-in-and-accepting-permissions-to-account/

**Comment by cole10up** [comment] 2020-06-04 07:01
**Tested**

Ran through a series of tests to install bedrock - Exhausted efforts to mimic with roots.io in the environment. This is more of a L2 issue. Sending over to L2.

**Comment by ernee** [comment] 2020-06-11 18:44
Adding additional info here: the user in the initial topic clarified that they do not get redirected back to the dashboard when attempting setup, but are instead looped back/ redirected to the proxy with the following URL in this response: https://wordpress.org/support/topic/infinite-verification-loop/#post-12936405

Site Health info for the site with the issue here: https://wordpress.org/support/topic/infinite-verification-loop/#post-12797811

**Comment by ernee** [comment] 2020-06-22 23:16
another report: https://wordpress.org/support/topic/plugin-setup-stuck-in-a-loop-without-any-error-notice/ 

(Site Health sent via form)

**Comment by brandomeniconi** [comment] 2020-07-10 08:44
If there is something I can do to help please let me know. We have more than 100 sites on bedrock and we will to upgrade all of them to SiteKit, but we are stuck to this bug. In few sites we are able to make it work, but every one we are trying now it's failing to authenticate.

Thanks!

**Comment by aaemnnosttv** [comment] 2020-07-10 09:07
Hi @brandomeniconi - are there any common differences between the sites that are not able to authenticate and the sites that work? As someone with so many sites this would help a lot as it seems that Bedrock itself is compatible with Site Kit as far as I can tell.

**Comment by brandomeniconi** [comment] 2020-07-13 10:10
Hi @aaemnnosttv I've sent some SiteHealts reports to @ernee via this topic https://wordpress.org/support/topic/plugin-setup-stuck-in-a-loop-without-any-error-notice/ of working and non-working sites. I have a wide range of combos of WP setups (multisite, single site, etc) and they all share the same environment (Google App Engine). 

This is our deploy procedure that's actually failing to activate SiteKit:
1) Develop the site code on Docker-based local environment
2) Deploy it to App Engine on a staging 4th level domain (`sitename.staging.example.com`)
3) Setup WP, plugins, theme and insert contents
4) Connect the final 1st level domain to App Engine (this requires search console domain verification)
5) Switch WP to the final domain
6) Setup SiteKit with the same Google account for all websites

Some of the sites where SiteKit is working, are ones that are already been published (step 5) in the past, then SiteKit has been installed directly when the site was already on the final domain. Maybe that's a difference.

Also be aware that Berock usually uses 2 different URLs for `siteurl` and `home` WP options:
`siteurl`: `https://example.com/wp`
`home`: `https://example.com/`
 and that is some that can maybe disrupt the OAuth redirect/return URL.

Unfortunately I cannot debug myself easily the live sites  because I don't have shell access on GAE. But I can plant some debug lines and output them in Cloud Logging if required.

If there is anything I can do please ask because this bug is delaying the publishing of many sites and I'm thrilling to resolve it 😉

**Comment by aaemnnosttv** [comment] 2020-07-13 14:30
@brandomeniconi thanks for the detailed reply. I've tested a standard Bedrock install (with home and siteURLs like you mentioned) a few times now and have yet to replicate the issue you're experiencing, so it's possible it's not Bedrock-specific.

One thing I noticed is that the URL for the file verification method returned a 404 on the site you referenced in the linked support ticket:
![image](https://user-images.githubusercontent.com/1621608/87315868-a0c9c780-c52d-11ea-8154-5c3809384e64.png)

We do not actually place a file there but serve it via PHP if requested. It should also fallback to using a meta tag if that fails though, but that may not work if you have full-page caching on the front-end.

If it's only the site verification step that is a problem, a temporary workaround would be to [manually verify your user](https://www.google.com/webmasters/verification/home) using any of the supported methods
![image](https://user-images.githubusercontent.com/1621608/87315587-4466a800-c52d-11ea-95b1-4b783cc9dbaa.png)

This is not an ideal solution, I'm only suggesting it as a means of unblocking you quickly.

Let me know if that helps?

**Comment by brandomeniconi** [comment] 2020-07-14 15:39
Hi @aaemnnosttv ,
I don't think the domain verification is a problem because by using App Engine we must verify the domain in search console before applying it to the site. We use the same Google Account. Something I forgot to mention is that we use Cloudflare on all our sites, but the issue is happening also when it's completely disabled (DNS pointing to GAE directly) so I don't think it will be  affecting this. 

I suspect that the redirect is caused by this line here:
https://github.com/google/site-kit-wp/blob/3590c624a075e9d9cb28bc9bf6ee313dd7aba516/includes/Core/Authentication/Clients/OAuth_Client.php#L665

I will do further investigation and let me know if I need to do something else.

**Comment by brandomeniconi** [comment] 2020-07-15 17:27
I confirm that is shouldn't be a domain verification failure, here is a Search Console result of one of our staging domains:

![google_verification](https://user-images.githubusercontent.com/393114/87575441-34d39480-c6d0-11ea-91fd-24f6df4fc158.png)

The HTML verification fails because the Google App Engine configuration treats `.html` URLs as static file and doesn't pipe those to the WP's php entry script.

Here is another one which says that is already verified even before I tried to authenticate SiteKit:

![google_verification2](https://user-images.githubusercontent.com/393114/87575963-f8546880-c6d0-11ea-8ce5-c4dbb56acd2a.png)

They both fail SiteKit authentication.

**Comment by brandomeniconi** [comment] 2020-07-15 18:43
I've also logged all the WP incoming and outgoing requests in Google Cloud Logging and the authentication secrets seems to be issued. Does the plugin has some internal validation?

![google_sitekit_log2](https://user-images.githubusercontent.com/393114/87582584-e24ba580-c6da-11ea-93ab-6c03c527fc0b.png)

![google_sitekit_log](https://user-images.githubusercontent.com/393114/87582530-cfd16c00-c6da-11ea-9f38-a8e5af45a496.png)

Sorry for flooding this issue 😸 .

This is also our Bedrock/AppEngine boilerplate if you want to give it a try: https://github.com/silverbackstudio/wp-website

**Comment by aaemnnosttv** [comment] 2020-07-16 10:15
If your Google user is already a verified owner for the domain/site then that step should already be completed without going through the flow between the authentication service and your site to facilitate it.

Looking back at [your gif of the loop](https://user-images.githubusercontent.com/393114/84866021-704f5480-b079-11ea-8ec5-4120bf98c8c4.gif), you aren't getting to that step anyways which is really odd.

> This is also our Bedrock/AppEngine boilerplate if you want to give it a try: https://github.com/silverbackstudio/wp-website

This is great, I'll give this a shot 👍

**Comment by jamesozzie** [comment] 2020-07-28 10:08
Another reported issue on the below WordPress topic:
https://wordpress.org/support/topic/unable-to-complete-setup/#post-13179635

- Site Health information provided in form 
- Log files included 
- Subdomain setup

**Comment by jamesozzie** [comment] 2020-08-04 12:23
Additional findings on this issue below:
https://wordpress.org/support/topic/unable-to-complete-setup/#post-13207950

User attempted site verification in Search Console manually before trying to setup Site Kit. Unfortunately the setup loop issue remains, presumably at the "Proceed" button stage, directing the user back.

**Comment by Sidlegionair** [comment] 2020-12-28 13:41
@jamesozzie Any progress?

**Comment by jamesozzie** [comment] 2020-12-28 15:35
@Sidlegionair No update on this just yet, but the team are aware of this and will be working on it.

**Comment by aaemnnosttv** [comment] 2021-04-28 07:06
After giving this another try with a fresh site, I'm still unable to reproduce any problem setting up Site Kit on Bedrock.

It certainly may be possible to have trouble completing the Site Kit-facilitated site verification process though for a number of reasons such as improper web server configuration. It does not seem however that Bedrock itself is responsible for this as this has worked as expected every time I have tested it. This leads me to conclude that other factors are likely causing problems with site verification and that using Bedrock is one thing that some of these sites have in common.

As a result, I'm going to close this out for now but happy to reopen in the future given more information about how to reproduce this.

**Closed by aaemnnosttv** 2021-04-28 07:06 UTC
Labels: Group: Escalation, Type: Bug, Type: Support

**Comment by Sidlegionair** [comment] 2021-05-31 10:08
@aaemnnosttv I'm willing to give more information to get this fixed, what would you need? As long as this issue isn't fixed (or a workaround has not yet been found) I cannot reliably deploy the plugin to all of my customers websites.

**Comment by aaemnnosttv** [comment] 2021-06-01 12:10
@Sidlegionair we have yet to identify any incompatibility with Bedrock specifically or be able to reproduce the reported problem.

[As you mentioned previously](https://github.com/google/site-kit-wp/issues/1523#issuecomment-625350898), the plugin works fine for you in some environments with Bedrock and not in others, so it seems Bedrock is not the source of the conflict.

Please try again with the latest version of the plugin and if you're still having trouble, [please reach out via support](https://wordpress.org/support/plugin/google-site-kit/) and we'll do our best to help 👍
