### ISSUE TITLE
Refactor AudienceSegmentationSetupSuccessSubtleNotification to use the new Notifications datastore

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9281] opened 2024-09-03 12:33 UTC
## Feature Description

This issue should refactor the `AudienceSegmentationSetupSuccessSubtleNotification` so that it uses the new datastore infrastructure to register and queue the notification. It should also incorporate the newly introduced `SubtleNotification` component as a new "layout"

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SetupSuccessSubtleNotification` component should be refactored so that it is registered and rendered (queued) using the new `core/notifications` datastore. 
* This notification component should not be called directly (i.e. directly in `<SubtleNotifications>`) but only via the generic `getQueuedNotifications` selector.
* The refactored component should not contain any business logic that hides it / prevents it from rendering. This logic should be contained in a callback function defined during registration.
* It should make use of the newly introduced `SubtleNotification` component.

## Implementation Brief

* [ ] Update `AudienceSegmentationSetupSuccessSubtleNotification` component
  * Check the `PAXSetupSuccessSubtleNotification` for an example 
  * Include 2 new props - `id` and `Notification`
  * Wrap the component with `Notification` component passed as the prop 
  * Instead of the currently rendered `SubtleNotification` component use the new layout - `assets/js/components/notifications/SubtleNotification.js`, with existing props.
* [ ] Update `assets/js/googlesitekit/notifications/register-defaults.js`
  * Register the notification, following the existing patterns already added
  * For `checkRequirements` transfer the existing checks from `AudienceSegmentationSetupSuccessSubtleNotification` component itself  - the conditionals and their logic from `shouldShowNotification` variable, and it's usage can be removed. Checking for `! shouldShowNotification` to return early is not needed, as showing of notification is handled in this `checkRequirements` property
  * And transfer the feature flag check `audienceSegmentationEnabled` from `assets/js/components/notifications/SubtleNotifications.js` to be included early in `checkRequirements`
  * For priority, bump it by `10` from the last added subtle notification (not including error ones, which start from `150`).
  * Use `NOTIFICATION_AREAS.BANNERS_BELOW_NAV` for `areaSlug`
  * Include `isDismissible` property with `true` for value
* [ ] Remove `AudienceSegmentationSetupSuccessSubtleNotification` from the `assets/js/components/notifications/SubtleNotifications.js`

### Test Coverage

* Update existing `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupSuccessSubtleNotification.stories.js`

## QA Brief

* Test the Audience Segmentation Setup Success Notification thoroughly by completing AS setup. 
* For additional retesting, you can change Analytics property or reconnect Analytics (disconnect and reconnect) and perform the AS setup again. Verify the view notification event is tracked when the notification is rendered.
* Test the "Got it" dismiss button and check the GA event is correctly tracked.
* Test the "Show me" button and check the confirm event is tracked and the page is scrolled correctly.
* Also test this notification when the site is in Gathering, Zero data and/or Unsatisfied Scope alert test. This notification will appear "first" and all others will appear later once this is dismissed.

## Changelog entry

* Refactor the setup success subtle notification for Audience Segmentation.

**Comment by eugene-manuilov** [comment] 2024-09-03 20:51
AC ✔️

**Comment by eugene-manuilov** [comment] 2024-09-05 17:27
@zutigrm, could you please expand IB to provide more details what exactly needs to be moved to the `checkRequirements` function, what should be deleted from the component, etc.

**Comment by zutigrm** [comment] 2024-09-06 08:59
@eugene-manuilov Thanks, I expanded IB where possible

**Comment by eugene-manuilov** [comment] 2024-09-06 15:33
Thanks, @zutigrm. IB ✔️

**Comment by kelvinballoo** [comment] 2024-10-15 14:34
### QA Update ⚠ 

Hi @jimmymadon , checking on this: there are a couple of things to be clarified around the QAB:

- GA events have not been implemented yet (e.g. https://github.com/google/site-kit-wp/issues/9497). Can you confirm that we'll need to ignore all the GA event reference in the QAB?
- Under Gathering State, we would not have any success notification. We won't be able to set up even the tiles. I assume this needs to be disregarded as well. Can you confirm?
- For 'Unsatisfied Scope alert test', can you confirm if this needs to be tested. From QA POV, this looks unrelated to the subtle success notification.

**Comment by jimmymadon** [comment] 2024-10-16 13:04
@kelvinballoo 

> GA events have not been implemented yet (e.g. https://github.com/google/site-kit-wp/issues/9497). Can you confirm that we'll need to ignore all the GA event reference in the QAB?

No, actually, the GA events are automatically implemented for all newly refactored notifications. So please do test the events as follows:
- Category will always be: `mainDashboard_setup-success-notification-audiences`
- Actions are: 
  - view_notification when viewed. 
  - dismiss_notification when clicking on "Got it"
  - confirm_notification when clicking on "Show me"

>Under Gathering State, we would not have any success notification. We won't be able to set up even the tiles. I assume this needs to be disregarded as well. Can you confirm?

Oh yes, the Gathering data notification will never be displayed alongside this notification. However, it would be good to try this on a site with Zero Data just to see if this "success notification" appears first and then the Zero Data notification should appear next.

> For 'Unsatisfied Scope alert test', can you confirm if this needs to be tested. From QA POV, this looks unrelated to the subtle success notification. 

So there are 3 types of notifications being refactored as part of this epic: Banners (Gathering, Zero, etc), Errors (UnsatisfiedScopesAlert, etc) and Subtle (Audience Segmentation, etc). And this refactor changes the code which "queues" notifications and shows them one after another. So the point of testing the other "unrelated" notifications is just to make sure that this success notification appears above the other types of notifications. That is why it is nice to mock somehow the Zero data banner notification and the Unsatisfied Scopes Alert error notification. This will ensure that this notification once dismissed still shows other notifications afterwards if their respective conditions are fully met.

**Comment by kelvinballoo** [comment] 2024-10-16 16:52
### QA Update ⚠ 

Hi @jimmymadon , thanks for the clarification.

I've got a couple of things to highlight:

**ITEM 1:**
There are sometimes I noticed other banners that would appear on top even though the success AS subtle notification is there. E.g. in the attached screenshot, there is the banner 'Congrats on completing the setup for Analytics'.
Should this have been hidden as well?
<Details>

![Image](https://github.com/user-attachments/assets/d46ddc59-0a3a-46ff-9e76-8d0d467b1cd6)

</Details>
__________________________________________________________________________________________

**ITEM 2:**
confirm_notification event when clicking on "Show me" is not being triggered.
There was mainly a tab_scroll event.

I think this needs to be fixed.

<Details>

https://github.com/user-attachments/assets/0124ec5a-6b31-4365-aa9c-6ce77c26ae08


</Details>

__________________________________________________________________________________________

**ITEM 3:**
It seems like it will be challenging to test the unsatisfactory scope.
The way I am testing this is to amend the **iwp658f_googlesitekit_auth_scopes** to the following in the DB editor:

`a:4:{i:0;s:46:"https://www.googleapis.com/auth/userinfo.email";i:1;s:48:"https://www.googleapis.com/auth/siteverification";i:2;s:6:"openid";i:3;s:48:"https://www.googleapis.com/auth/userinfo.profile";}`

However, after changing and reloading the SK dashboard with the AS success subtle notification, the latter vanishes. It doesn't stay there.
I also tried to amend the auth_scopes prior to the clicking on 'Enable groups' on the AS setup banner so that when the success AS notification appears, it should hide the reduced scope error. However, doing it this way will hit error when enabling groups.
<Details>

![Image](https://github.com/user-attachments/assets/de58b840-c3c2-4cc2-aee2-88f1665a8f70)

</Details>

Let me know if there is another way to test it for the unsatisfactory scope scenario.

__________________________________________________________________________________________


Other than that, view_notification and dismiss_notification were verified good. ✅ 
<Details>
Dismiss notification
![Image](https://github.com/user-attachments/assets/8cc32449-7c2e-43d6-83f7-f71bcdc50118)

View Notification
![Image](https://github.com/user-attachments/assets/fce0659a-114c-4f6a-a223-d45952a2d57f)


</Details>

**Comment by jimmymadon** [comment] 2024-10-16 19:04
@kelvinballoo Thanks for the thorough testing here!

>ITEM 1:

This is fine as the "Analytics Setup Success Banner Notification" is still on the old code and is yet to be refactored. So this is expected. The Gathering/Zero data and some other banners have been already refactored which aren't being displayed simultaneously as expected.

>ITEM 2:

This is a "minor" bug and I realised this was also present in the [PAX Setup Success Notification](https://github.com/google/site-kit-wp/issues/8980). I have created a follow up PR for this. @tofumatt if you think this can be merged for this release, that would be great! I have targeted `main` but this can also be merged into the next release I think.

>ITEM 3:

Again, my apologies but this would not happen in a real life scenario. So there is no point in testing this! I should've thought about this before! However, it is good to know that the other types of refactored notifications still work and no regressions were added here.

**Comment by kelvinballoo** [comment] 2024-10-17 05:26
Thanks for confirming on ITEM 1 and 3 @jimmymadon .
Item 2 was tested and it's working as expected now.
Moving ticket to Approval.

The following were verified good:  ✅ 
- Banner appears - View Notification
   <Details>

   ![Image](https://github.com/user-attachments/assets/fce0659a-114c-4f6a-a223-d45952a2d57f)
   
   </Details>

- "Got it" dismiss button - Dismiss notification
   <Details>

   ![Image](https://github.com/user-attachments/assets/8cc32449-7c2e-43d6-83f7-f71bcdc50118)

   </Details>

- "Show me" button - Confirm notification
   <Details>

   ![Image](https://github.com/user-attachments/assets/8df9654d-f694-4a0f-ab22-7b1b4e232362)

   </Details>

- Zero data mode
   <Details>

   ![Image](https://github.com/user-attachments/assets/23f8bcea-02cd-4a39-9586-2dcda2ed01f0)

   ![Image](https://github.com/user-attachments/assets/e7b81a1e-a2b0-4993-a44b-fd4ad84f46db)

   ![Image](https://github.com/user-attachments/assets/8ba36921-a3c2-410c-934f-ac12c7bfb3f6)

   </Details>
- Gathering state cannot be tested because during the setup, we can't set up tiles when it's in gathering mode.
- Unsatisfied Scope alert cannot be tested because when we amend the user_meta table and reload the SK dashboard to simulate unsatisfactory scope, the AS success subtle notification vanishes. It doesn't stay there.
- Did a quick round of test on Ads Pax setup success notification and the confirm_event is triggered. There was no detailed testing for that.
   <Details>

   ![Image](https://github.com/user-attachments/assets/ab6e607c-a86a-4b84-80fd-491d422084f6)

   </Details>

**Closed** 2024-10-18 17:32 UTC
Labels: P2, Type: Enhancement, Team S
