### ISSUE TITLE
Fix too much spacing between Optimize input field and errors

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4028] opened 2021-09-13 20:27 UTC
## Bug Description

See https://google.github.io/site-kit-wp/storybook/main/?path=/story/optimize-module-setup--start-with-invalid-values: The space between the Optimize ID field and the error text below is way too much. This is likely happening because the error text is placed outside the `.googlesitekit-setup-module__inputs` wrapper, which shouldn't be the case as it includes extra margin etc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In the Optimize setup (and settings as well), any input error text should have the correct space from its associated input field, specifically an error for the Optimize ID shouldn't have the extra margin that it currently has (compared to e.g. an error for the AMP experiment JSON field).

## Implementation Brief

* The extra space is caused by the following CSS Rules in the `assets/sass/components/setup/_googlesitekit-setup-module.scss` file. 
* https://github.com/google/site-kit-wp/blob/8bff83f9f11742dee8aca49b04f0f55121d040e1/assets/sass/components/setup/_googlesitekit-setup-module.scss#L109-L115
* Add new CSS Rules that overrides and sets the bottom margin (ie. `margin-bottom: 0`) to the `div.mdc-text-field--error` and the following helper text `div.mdc-text-field-helper-line` elements inside `div.googlesitekit-setup-module__inputs` of `form.googlesitekit-optimize-setup__form`.
    * We can keep the change limited to the Optimize ID input field by targeting the div with `[name="optimizeID"]` attribute selector. 

### Test Coverage

* N/A

### Visual Regression Changes

* May need updating. 

## QA Brief
* Check whether spacing has been reduced in the following story: https://google.github.io/site-kit-wp/storybook/main/?path=/story/optimize-module-setup--start-with-invalid-values

## Changelog entry

* Fix styles for errors on Optimize setup and settings forms.

**Comment by eugene-manuilov** [comment] 2021-11-04 17:17
Moving back to the IB column since it has been moved to the Execution column by accident.

**Comment by eugene-manuilov** [comment] 2021-11-11 21:01
@kuasha420 let's not remove the existing css rules because it will affect something else, instead, left's add one more css rule that will fix the issue for the Optimize module. We can use `.googlesitekit-optimize-setup__form` and `.googlesitekit-setup-module--optimize` selectors to restrict style changes to work only for the Optimize module.

**Comment by kuasha420** [comment] 2021-11-12 21:54
@eugene-manuilov changed the wording and mentioned the form class in the updated IB. I think the changes needed should be understandable now.

**Comment by eugene-manuilov** [comment] 2021-11-14 13:59
Thanks, @kuasha420. IB :heavy_check_mark:

**Comment by wpdarren** [comment] 2021-11-30 15:45
### QA Update: ❌ 

@asvinb two things:

1. The URL in the QAB is [Main branch](https://google.github.io/site-kit-wp/storybook/main/?path=/story/optimize-module-setup--start-with-invalid-values) which still shows the spacing. Since this is labelled 1.48.0 I changed the URL to [Develop branch](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/optimize-module-setup--start-with-invalid-values) and that does show the spacing is fixed underneath the Optimize Container ID box.  

Should I see the change on the main branch on Storybook? 

2. I had a look at this on my test site on the develop branch and the spacing is fixed but what I noticed is that the text `Analytics is currently set to not track some logged-in users. ` underneath the Optimize Container ID box is right up to the input field where before it had a space between it. 

This is what I see on `develop` branch

![image](https://user-images.githubusercontent.com/73545194/144079241-77fbfb9e-7f41-4e31-937c-6d7a32d01817.png)

This is what I see on latest version (1.46.0)

![image](https://user-images.githubusercontent.com/73545194/144079456-175d625f-4b07-4148-89d9-40376c073fe7.png)

Is this expected?

**Comment by asvinb** [comment] 2021-12-01 12:38
@eugene-manuilov Can you check @wpdarren 's comment about the release. I saw the PR was merged against develop but did not make its way to the main branch even though it's tagged for the release.
Also, updated PR to fix the issue Darren mentioned.

**Comment by eugene-manuilov** [comment] 2021-12-01 13:44
> 1. The URL in the QAB is [Main branch](https://google.github.io/site-kit-wp/storybook/main/?path=/story/optimize-module-setup--start-with-invalid-values) which still shows the spacing. Since this is labelled 1.48.0 I changed the URL to [Develop branch](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/optimize-module-setup--start-with-invalid-values) and that does show the spacing is fixed underneath the Optimize Container ID box.
>
> Should I see the change on the main branch on Storybook?

@wpdarren, no, you should see it on the develop branch because `1.48.0` is not the next release. The next release is `1.47.0`.

**Comment by wpdarren** [comment] 2021-12-01 16:46
@eugene-manuilov thank you, I thought so but wanted to check.

### QA Update: ✅ 

**Verified:** 

- The spacing has been reduced in the storybook.
- Also tested this on a site and can confirm the spacing is reduced and the issue reported is fixed.

![image](https://user-images.githubusercontent.com/73545194/144276347-23029f78-999c-47af-b6c8-b64587e70571.png)

**Comment by asvinb** [comment] 2021-12-07 14:49
@wpdarren I think we should review the UI/UX for this section, especially where the "Format: GTM..." hint is displayed. The implementation is weird, whereby we are are setting the opacity of the element which is not ideal. If we don't use the opacity, the other option would be to use `display: none`, `block` which will result in big layout shift which can be annoying. Maybe we should open a new issue to look into possible options, like always displaying the hint below the input text, in smaller characters.
Interested to hear your thoughts @aaemnnosttv @felixarntz

**Comment by aaemnnosttv** [comment] 2021-12-08 09:57
> The implementation is weird, whereby we are are setting the opacity of the element which is not ideal.

@asvinb this how Material does it so we shouldn't change how the component works. We could change how we use it though - the `AdsConversionIDTextField` component conditionally adds the helperText validation message. I think it would make sense to do the same here

The interface could be polished a bit as well, so +1 for a new issue for that.

One of the other problems here I think is related to this style which is resulting in a double margin between these divs
![image](https://user-images.githubusercontent.com/1621608/145186611-5aa29425-9cc9-4c1f-aa31-22fcc2613f2a.png)

<table>
<tr>
	<td>

![image](https://user-images.githubusercontent.com/1621608/145186753-8aee7e0c-31f2-4822-b2da-dc57830a8571.png)

</td>
	<td>

![image](https://user-images.githubusercontent.com/1621608/145186739-3d246a55-5b5b-470b-9b89-f2332d59b544.png)

</td>
</table>

This adds an incorrect amount of spacing even without the error

**Comment by asvinb** [comment] 2021-12-08 13:18
@aaemnnosttv I created a new PR which solves some of the awkwardness for this particular section. Can you take a look and let me know what you think? The layout has changed a little bit but I think it's a better experience for the user.

Additionally I created the following issue: https://github.com/google/site-kit-wp/issues/4510 while working on the current ticket.

**Comment by asvinb** [comment] 2021-12-14 17:11
@aaemnnosttv On small screens, I feel the input text should be 100% wide because it's a bit weird, with how the helper text is longer than the input text.
![image](https://user-images.githubusercontent.com/31818/146046333-2e28e9df-2fdd-4db3-a92e-bba790685711.png)

What are your thoughts?

**Comment by aaemnnosttv** [comment] 2021-12-14 19:25
@asvinb it's a bit weird but it's something we should address holistically as it isn't specific to this one input.

Back to you @wpdarren for another pass!

**Comment by wpdarren** [comment] 2021-12-15 12:39
### QA Update:  ✅ 

**Verified:**

- The spacing has been reduced in the storybook.
- Also tested this on a site and can confirm the spacing is reduced and the issue reported is fixed
- Confirmed that the mobile styling issues are fixed. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/146188017-046bfc19-5ab9-46cd-92cb-0a9cec267a1e.png)

![image](https://user-images.githubusercontent.com/73545194/146188040-84b4fe65-091f-434f-9536-8310ce888309.png)

</details>

**Closed** 2021-12-16 17:53 UTC
Labels: Type: Bug, P2, Module: Optimize, Rollover
