### ISSUE TITLE
GTM Container Dropdown With Container Name + Container ID

### ISSUE THREAD

**Issue by ivankristianto** [google/site-kit-wp#131] opened 2019-07-05 04:24 UTC
## Bug Description

When selecting GTM container from dropdown, it only show Container ID.

## Steps to reproduce

1. Activate Tag Manager from the settings
2. Tag Manager setup flow show up
3. See container dropdown as the screenshot below:
![Screen Shot 2019-07-05 at 09 45 59](https://user-images.githubusercontent.com/656006/60697963-4c057100-9f17-11e9-9067-ee210c1b1512.png)

## Expected behavior 

Show the Container name along with the container id, for example "Site Kit for WordPress (GTM-XXXXXX)".

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by swissspidy** [comment] 2019-11-06 14:54
Duplicate of #591.

**Closed by swissspidy** 2019-11-06 14:54 UTC
