### ISSUE TITLE
Excluding all logged in users from Analytics results in invalid JSON in Web Stories preview debug mode

### ISSUE THREAD

**Issue by LuckynaSan** [google/site-kit-wp#3572] opened 2021-06-14 19:06 UTC
## Bug Description

1.) When you enable the option to exclude all logged in users from Analytics in Site Kit by Google, Story [passes AMP validator](https://search.google.com/test/amp?id=u72qIF-C6TtMMeWXq6miOg), but Story's debug mode in the story preview is outputting the below warning 
<img width="1228" alt="Screen Shot 2021-06-11 at 12 06 36 PM" src="https://user-images.githubusercontent.com/66372350/121945308-3f9c0c80-cd19-11eb-9701-98ef18598353.png">
<img width="1260" alt="Screen Shot 2021-06-11 at 12 08 40 PM" src="https://user-images.githubusercontent.com/66372350/121945318-43c82a00-cd19-11eb-99b9-fc686d067bf0.png">

## Steps to reproduce

1. Go to Site Kit settings
2. Click on edit Analytics > Exclude from Analytics all logged-in users
3. Go to Web Stories
4. Open in editor > preview a story
4. See debug tab and notice invalid JSON error

## Additional Context
Related Github issue https://github.com/google/web-stories-wp/issues/7939

 - PHP Version: 
 - Browser [e.g. chrome, safari] chrome
 - Plugin Version [e.g. 22] 1.34.0
 - Device: [e.g. iPhone6] macOS

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The GA opt-out element output for AMP should not raise any validation errors or warnings for HTML or AMP markup validation

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/3593. 
See conversation on https://github.com/google/web-stories-wp/issues/7939 issue for more information

### Test Coverage

* No changes

### Visual Regression Changes

* N/A

## QA Brief

* Set up and configure Analytics to exclude tracking for logged in users (default)
* Enable Web Stories and create a new story
* Leave blank and click Preview
* On the preview screen, click the Debug tab
* Review the results, ensure the `__gaOptOutExtension` element is not reported (there may be other validation errors/warnings not from Site Kit)

## Changelog entry

* Fix AMP validation error caused by the GA opt-out snippet conditionally placed by Site Kit.

**Comment by felixarntz** [comment] 2021-06-17 16:08
IB / CR ✅

**Comment by felixarntz** [comment] 2021-06-17 16:14
@eclarke1 @fhollis Adding this to Sprint 51 since it was a quick fix.

**Comment by wpdarren** [comment] 2021-06-22 16:34
@aaemnnosttv  I am seeing the same error and tested this on two different sites. Would you be able to check that it has successfully merged, and if you still see the errors or not? 

![image](https://user-images.githubusercontent.com/73545194/122965277-ec146900-d37f-11eb-953f-cc8a18bd795f.png)

**Comment by aaemnnosttv** [comment] 2021-06-23 08:21
@wpdarren the problem is that Site Kit isn't setting the proper AMP mode when Web Stories is active. This should be fixed in https://github.com/google/site-kit-wp/issues/2998 but there is a problem with the implementation there which I will follow up on now.

**Comment by aaemnnosttv** [comment] 2021-06-23 10:08
@wpdarren actually, sorry, it should be good – I just tested this again and while there are errors that show Site Kit, it's mostly because the output is minified and line 6 starts with our opt-out comment there which is normal. The main error we don't want to see is the first one in your screenshot there about invalid JSON.

Here's what I see 
![image](https://user-images.githubusercontent.com/1621608/123078889-17509400-d424-11eb-81c4-c3e7fc69345b.png)

**Comment by wpdarren** [comment] 2021-06-24 12:02
### QA Update: Pass ✅ 

- The invalid JSON is not reported as per the QAB. 

![image](https://user-images.githubusercontent.com/73545194/123259464-6530cf00-d4ec-11eb-97bb-96597d783dcb.png)

**Closed** 2021-07-01 00:54 UTC
Labels: P2, Rollover, Type: Bug
