### ISSUE TITLE
Split the "Sell products or services" answer in the User Input app

### ISSUE THREAD

**Issue by benbowler** [google/site-kit-wp#9489] opened 2024-10-11 08:41 UTC
## Feature Description

As part of the updates to the User Input app, the existing "Sell products or services" question should be split into to separate questions, this requires some additional changes to logic to handle the behaviour with the legacy answer, as well as a banner for users who have previously selected the combined option. As part of this issue, only answer split should be added, banner will be implemented as separate issue

The proposed solution was discussed in a thread with @aaemnnosttv and @sigal-teller (message @benbowler for details), the summary of which is the following. Existing users who have selected the combined option should *not* be automatically migrated, these users should see [a new banner](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=2770-51230&node-type=frame&t=MUFu0DSphAxF5AvA-0) in the Admin Settings screen when editing their metrics encouraging them to update the answer. The app metrics selection should continue working with the legacy combine answer selected.

This additional scope was first identified in #9374.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Existing purpose answer  "Sell products or services" is split into two new answers: 
  * `Sell products`
  * `Provide services`
* New descriptions should be included under each answer, and answers should be added in order shown in Figma [here](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=1773-19282&node-type=frame&t=gejNlcLG8c8JhLme-0) and [here](https://www.figma.com/design/S2CNc1toIzC7UrGMgs79S6/Conversions?node-id=2770-52328&node-type=frame&t=gejNlcLG8c8JhLme-0)
* The legacy answer "Sell products or services" should still have an effect with the existing users that previously saved it, but it should be hidden from the answers list in the user input - both for new setup, and in the list when answer is edited in the key metrics section of the admin settings.
  * For existing users, when editing the answer, `Sell products` which should be the first answer in the list, should be preselected by default
* Tailored metrics should be adapted for each new answer, following the KMW grouping from this table: ![Image](https://github.com/user-attachments/assets/2af86f28-406d-4d7c-b570-b054c2da955a)

* Check [Splitting “Sell products or services” site purpose answer](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?pli=1&resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.tobctwt5ojmh) section of the design doc

## Implementation Brief

* [x] Within the `user-input` data store constants file at `assets/js/components/user-input/util/constants.js`
    * [x] Define the new answers for `Sell products` and `Provide services` within the existing `getUserInputAnswers()` function 
    * [x] Define the new answer descriptions for `Sell products` and `Provide services` within the existing `getUserInputAnswersDescription()` function
* [x] Within the `key-metrics` user datastore  partial at `assets/js/googlesitekit/datastore/user/key-metrics.js`
    * [x] Update the `getAnswerBasedMetrics` selector, mapping the correct metrics to the respective `Sell products` and `Provide services` answer types
    * [x] Leave the existing mapping for `sell_products_or_service` intact
* [x] Within the `UserInputSelectOptions` component at `assets/js/components/user-input/UserInputSelectOptions.js`
    * [x] If the `slug` attribute is equal to `USER_INPUT_QUESTIONS_PURPOSE`, add/update the following logic: 
        * [x]  If the currently chosen value is that of the legacy `sell_products_or_service` type/value, ensure that the `Sell products` option is pre-selected

### Test Coverage

* Update the tests at `assets/js/googlesitekit/datastore/user/key-metrics.test.js` and ensure that the correct metrics are returned for the 2x newly added purpose types.

## QA Brief

* Switch to a release or branch prior to this change
* Set up Site Kit with KMW, using the tailored option, choosing "Sell products or services" as a site purpose
* Switch to the branch containing this body of work
* Navigate to Site Kit > Settings > Admin
* Under Key Metrics header, validate that the correct purpose shows: "Sell products or services"
* Click on the edit CTA next to purpose
* Validate that "Sell products or services" is no longer an option in the list and that "Sell products" is now selected
* Confirm that the "Apply change" CTA button is present at the bottom of the settings edit group
* Cancel (do not apply) and confirm the label returns to "Sell products or services"
* Edit the purpose again, but this time apply the changes (Note this specific scenario will not trigger the modal, as both answers have the same metrics)
* Confirm that "Sell products" is now the selected purpose, and persists as such on page reload
* See attached gif below for an example

![Image](https://github.com/user-attachments/assets/deb0600c-50ee-4e0d-9a88-d44025e0a370)

## Changelog entry

* Split the "Sell products or services" answer in the User Input app.

**Comment by zutigrm** [comment] 2024-10-17 12:39
Taking this back to AC with me, pending the new tailored metrics that should be added for each new answer. Current thread for [this](https://fueled10up.slack.com/archives/C01CA828ZPZ/p1729164249903509)

**Comment by jimmymadon** [comment] 2024-11-21 11:21
@10upsimon I noticed the PR here created 5 metric tiles for the `provide_services` option. If ACR is not active, then the max number of tiles should be 4. Could we please bring this back down to 4 metrics?

https://github.com/google/site-kit-wp/blob/8913261d60a8593fe7bff01fac23086f7b5c6e71/assets/js/googlesitekit/datastore/user/key-metrics.js#L338-L344

**Comment by mohitwp** [comment] 2024-11-25 01:49
### QA Update ⚠ 

Tested on dev environment.
Tested when `'connversionReporting' `feature flag is not enabled.
Tested when `'connversionReporting' `feature flag is enabled.


@10upsimon 


_Issue 1) `'connversionReporting' `feature flag is not enabled. When I select purpose 'Provide services' then 5 metric tiles are showing. It should display 4 metric tiles._


<details>

![Image](https://github.com/user-attachments/assets/48bdf253-cf95-40ea-9f96-5b1e59a29cf8)

</details>


_Issue-2 ) When I select purpose 'Sell Products" and if "WooCommerce" plugin is active then 4 metric tiles are showing._

- Most popular products by pageviews
- Top traffic source
- Most engaged traffic source
- Top performing keywords

_As per AC metric list  "Most engaged traffic source" should be listed when purpose is "Provide Services". 
When `'connversionReporting' `feature flag is enabled then metrics are showing correctly as per table mentioned under AC._


<details>

![Image](https://github.com/user-attachments/assets/1a162312-da51-4a73-a940-54bbd8fa8289)


'conversionReporting' feature flag is enabled

"Sell Products"

![Image](https://github.com/user-attachments/assets/9d53c91e-d55c-416d-a985-cfbb86d68178)


</details>


_Q -3) The Figma design for the "Answers Edit Screen" also includes a description, but this has not been implemented yet. I also tested this with ACR enabled. Do we have a separate ticket to implement this?_

<details>

![Image](https://github.com/user-attachments/assets/98a44432-7aa6-44c0-8584-8f9624c744cb)


</details>

**Comment by mohitwp** [comment] 2024-11-27 04:43
### QA Update ✅ 

@10upsimon Above listed issues are resolve now. Please find additional observations below -


Issue 4 : I missed this earlier due to metrics having similar names, but I’ve now noticed that when I select the purpose **_‘Sell Products’_**, the following metrics are displayed. Out of these four, the “Top Traffic Source” metric is not part of the AC metrics list for **_‘Sell Products’_**

- Top earning pages
- Most popular products by pageviews
- **_Top traffic source_**
- Top performing keywords

<details>

![Image](https://github.com/user-attachments/assets/c20c925c-df30-47b4-9f4b-f5656f79b1df)

</details>

Issue 5: Now, 5 metrics are not showing when we select the purpose **_"Provide Services"_**. However, in this case as well, the “Top Performing Keywords” metric is not part of the AC metrics list for **_"Provide Services"_**.

<details>

![Image](https://github.com/user-attachments/assets/cc8b9405-3ca2-4a97-b066-8250b4e4d333)


</details>

**Comment by mohitwp** [comment] 2024-11-28 10:36
### QA Update ✅ 


- Tested on main environment.
- Tested when `'connversionReporting'` feature flag is not enabled.
- Tested when `'connversionReporting'` feature flag is enabled.
- Verified issue number 4 reported above is resolved now.
- Verified correct metrics tiles are showing as per list under AC when `'connversionReporting'` feature flag is not enabled.

@10upsimon I noticed one regression issue that if `'connversionReporting'`  feature flag is selected and if user selects purpose **_"Provide Services"_** then only 7 metrics are showing instead of 8. Upon comparing with the AC metrics list, I found that the “Top Pages by Returning Visitors” metric tile is missing. Additionally, this metric tile is also absent from the tailored metric suggestions. I created a separate ticket and assigned it to you since this issue is behind a feature flag. I believe creating a follow-up now wouldn’t be ideal, especially with the release scheduled for Monday.

<details>

![Image](https://github.com/user-attachments/assets/b2ce4a83-646a-4ad1-ae54-e0b3650fee03)

![Image](https://github.com/user-attachments/assets/1232c026-6a6f-4d3d-872b-0d258bab82b3)

![Image](https://github.com/user-attachments/assets/11f74984-ca6f-42ea-8b79-672e454a3245)

</details>

**PASS CASES**

**_Sell Products_**

<details>

![Image](https://github.com/user-attachments/assets/0449c3df-cb62-402c-bd68-22463ffd7c3f)

When` conversionReporting` feature flag is enabled

![Image](https://github.com/user-attachments/assets/f8b5df86-f09d-41ba-9420-c6ad78dcd352)

</details>


**_Provide Services_**

<details>

![Image](https://github.com/user-attachments/assets/074b4cca-d37b-45fe-ad0c-52881313aa28)



</details>

**Closed** 2024-11-28 16:05 UTC
Labels: P0, Type: Enhancement, Team S
