### ISSUE TITLE
Idea Hub widget remains in loading state

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5362] opened 2022-06-15 15:24 UTC
## Bug Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202442610474594 refer to Asana issue for background

I granted another user to view the Idea Hub widget but the latter does not load. Furthermore there's an error in the console, not sure if it's related.
To reproduce, assign the Idea Hub module only to a user and login as the user to view the widget on the main dashboard.
Prior to adding the IH module to the user, the latter had the Analytics module.

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/ad38b5c0-a0e2-4b56-83f1-05bb733f4b3a)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2022-06-16 22:23
@eclarke1 I wasn't able to reproduce it, sorry I thought I followed up on here!

@asvinb @wpdarren can you confirm this is reproducible?

**Comment by asvinb** [comment] 2022-06-17 09:39
@aaemnnosttv @wpdarren Try clearing your local storage, do a hard refresh. I just tried it and Idea Hub does not load/

**Comment by wpdarren** [comment] 2022-06-17 10:59
@aaemnnosttv @asvinb Mmm it was certainly working for me when I completed E2E, but once 1.77 is out of the way, I will take a look and see if I can create it.

**Comment by aaemnnosttv** [comment] 2022-06-17 13:42
@asvinb I just tried this with an editor that only had access to Idea Hub with a clear state and made sure the requests were going through. No new ideas come back but it is not stuck in the loading state and I see the appropriate zero state. Maybe it has to do with the site you're trying to source ideas for? 🤔

**Comment by aaemnnosttv** [comment] 2022-06-17 14:15
@wpdarren – @asvinb and I were able to track down the cause here. Closing this one in favor of https://github.com/google/site-kit-wp/issues/5388

**Closed by aaemnnosttv** 2022-06-17 14:15 UTC
Labels: Type: Bug
