### ISSUE TITLE
User Input: Add label for keyword input

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#2901] opened 2021-03-01 21:44 UTC
## Feature Description

The keywords `input` has no label because it renders the `label` attribute on the `TextField` as a `placeholder` HTML attribute. This isn't accessible, so let's add a label.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Because the `label` prop supplied to the `TextField` component here is rendered as a `placeholder`, there should also be a manually-created `<label>` added for the `TextField` for assistive technology. Ensure there is always a `<label>` tag for the `TextField` with the text `"Keywords (minimum one, maximum three)"`.

## Implementation Brief

*  edit `assets/js/components/user-input/UserInputKeywords.js`
*  add a `<label>` to the `TextField` with the text `"Keyword"` and hide it with the `VisuallyHidden` component.

### Test Coverage

* No tests needed for this change.

### Visual Regression Changes

* VRT changes to the placeholder being empty after a value is entered might occur; otherwise none should occur.

## QA Brief

* Check that the term text fields have hidden labels

## Changelog entry

* Introduce hidden labels for search term fields of the User Input Settings flow.

**Comment by tofumatt** [comment] 2021-03-11 20:37
While the label for this text input isn't _great_, it is instructive for screenreaders and shouldn't be removed as it then lacks context, especially because we shift focus to it after creating a new keyword.

Instead we should move the label into the top of the text field as many component do elsewhere for `TextField`/`Input` components, like "Text Field" in this screenshot:

<img width="380" alt="Screenshot 2021-03-11 at 20 36 30" src="https://user-images.githubusercontent.com/90871/110851821-78a38b80-82a9-11eb-90ee-68a4ecb268c4.png">

----

Failing that, though, we should use a `className` to _visually_ hide the label rather than delete its text, so it's still usable for assistive technologies.

**Comment by Hazlitte** [comment] 2021-03-15 13:00
@tofumatt On further investigation at present the input fields don't have a label at all.  When the prop `noLabel` is passed to the `TextField` component the `label` prop text is rendered as a `placeholder`.  We could remove the `noLabel` prop, remove the conditional setting of the label text and set the `floatingLabelClassName` prop of the `TextField` to `screen-reader-text` if no text has been entered.

I also noted that `display: inline-flex` is missing from the input wrapper which is causing it to render below entered keywords.  I'm not sure if this is intended behaviour.
![Screenshot 2021-03-15 at 11 45 08](https://user-images.githubusercontent.com/5174233/111156980-3e2e3d00-858e-11eb-94f9-6b1a7d7395c1.png)

**Comment by tofumatt** [comment] 2021-03-15 20:18
Oh boy, so it seems like the label prop here is a bit of a mess.

What we _should_ do is leave the placeholder as-is when it should appear (eg when the input is "empty"—no tags exist), but get rid of what is effectively the _placeholder_ after that. So we should remove the `label` prop then.

But separately, let's add a `<label>` tag for this element that's more helpful for assistive technology anyway: something like `"Keywords (minimum one, maximum three)"`.

I've adjusted the ACs accordingly, so we should be able to write a more complete IB for this now 👍🏻

**Comment by tofumatt** [comment] 2021-03-17 11:54
Just a note that I meant that the `<label>` here would be entirely visually-hidden. @Hazlitte and I just chatted about it and he's going to tweak the IB a bit more based on that clarification 😅

**Comment by tofumatt** [comment] 2021-03-17 12:00
IB ✅

**Comment by eugene-manuilov** [comment] 2021-03-22 16:14
@tofumatt could you please take a look at https://github.com/google/site-kit-wp/pull/2984#discussion_r598668340?

**Comment by tofumatt** [comment] 2021-03-22 22:06
@felixarntz I agree with @eugene-manuilov's review of this—I think we might want to close it out as the input doesn't behave the same way as the screenshot, so this isn't needed anymore to prevent the placeholder from getting awkwardly cut off. Plus the change actually makes the input _less_ obvious and usable.

**Comment by felixarntz** [comment] 2021-03-24 17:18
@tofumatt @eugene-manuilov Those are good points, we can amend the ACs. However, I don't think we should close it as the ACs also mention an accessibility fix that is still relevant as far as I can tell?

**Comment by tofumatt** [comment] 2021-03-25 13:05
Sounds good, I've edited the ACs/IBs to just deal with the accessibility issue 👍🏻

**Comment by wpdarren** [comment] 2021-03-26 13:43
### QA Update: Pass ✅ 

Verified that the term text fields have hidden labels

![image](https://user-images.githubusercontent.com/73545194/112640351-39b23000-8e7c-11eb-9ac4-6b1cb9afa8a2.png)

**Closed** 2021-04-08 18:01 UTC
Labels: P1, Type: Enhancement
