### ISSUE TITLE
Add Key metrics enabled/disabled and user chosen or tailored metrics details to Site Health report

### ISSUE THREAD

**Issue by adamdunnage** [google/site-kit-wp#9112] opened 2024-08-01 15:03 UTC
## Feature Description

As part of the Analytics Conversion Reporting epic, it has been identified that it would be useful to update the Site Health section for Google Site Kit with the following 3 new entries:

1. `key_metrics_status`: setup/enabled/disabled
2. `key_metrics_source`: user chosen/tailored
3. ~~`key_metrics_selection`: A list of selected KMW's (regardless of whether tailored or manually chosen)~~

See [Site Health](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?pli=1&resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.hppr5cex19dy) section in the design doc

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit site health info tab is updated to include:
  * `Key Metrics Status`
    * Show setup status - If key metrics is setup or not
    * Once KMW is setup, it can be either `Enabled` or `Disabled`
    * If KMW is not setup, show only "Not setup" status
    * If KMW has been setup, show "Setup and Enabled/Disabled" status 
  * `Key Metrics Source`
    *  Depending on whether KMW was setup using manual selection or through user input, display "Manual Selection" or "Tailored metrics" status

## Implementation Brief

* [ ] Update the `Debug_Data` class at `includes/Core/Site_Health/Debug_Data.php`
    * [ ] Include `Google\Site_Kit\Core\Key_Metrics\Key_Metrics_Settings` and `Google\Site_Kit\Core\Key_Metrics\Key_Metrics_Setup_Completed_By` classes and assign them to their respective class properties
        * [ ] Instantiate them in the constructor 
    * [ ] Within the existing `get_fields()` method, create a new line that (array) merges existing `$fields` with the values obtained from a new class method, `get_key_metrics_fields()`, i.e:
        * [ ] `$fields = array_merge( $fields, $this-> get_key_metrics_fields() );`
    * [ ] Create said new method `get_key_metrics_fields()`, which will return the necessary debug fields for the Key Metrics site health entries. Within this method:
        * [ ] Determine whether setup is completed, using `$this->options->get()` and using the option value from `$this->key_metrics_setup_completed_by::OPTION`
        * [ ] Reference the KMW settings via `$this->key_metrics_settings->get()`
        * [ ] Determine if KMW is disabled via the `isWidgetHidden` array key of the above settings
        * [ ] Output an initial array entry via key `key_metrics_status` (referenced to a variable) and store the `Key Metrics Status` against it, i.e:
            * [ ] Label the debug entry accordingly via the `label` key: `Key Metrics Status`
            * [ ]  If setup is complete and KMW is not disabled, output the value `Set Up Complete - Enabled` via the arrays `label` key
            * [ ] If setup is complete and KMW is disabled, output the value `Set Up Complete - Disabled`  via the arrays `label` key
            * [ ] If setup is not yet complete, output the value `Not Set Up`  via the arrays `label` key
        * [ ] Only if set up is complete, append a 2nd array via key `key_metrics_source` to the initial array above. 
            * [ ] Label the debug entry accordingly via the `label` key: `Key Metrics Source`
            * [ ] If the value of the `widgetSlugs` array key from the `$this->key_metrics_settings->get()` array is not empty, the output value of the  `value` array key should be `Manual Selection`
            * [ ] If it is empty, the value of the `value` array key should be `Tailored Metrics`

### Test Coverage

* No tests are required.

## QA Brief

Verify the cases in the AC as follows (use values in AC to compare fields): 
* On a site where Site Kit has been reset, check site health and verify the Key Metrics Status is Not setup.
* Now answer the User Input Questionnaire and verify the new site health Key Metrics fields shows Enabled and Tailored metrics .
* Now pick your own metrics (Change Metrics) on the main dashboard in the Key Metrics widget. Verify the fields show Enabled and Manual Selection.
* Finally, go to Admin Settings and toggle the "Hide Key Metrics" button. Verify the Key Metrics Status is Setup and Disabled.

## Changelog entry

* Add Key Metrics info to Site Health report.

**Comment by 10upsimon** [comment] 2024-11-01 06:24
@zutigrm this AC LGTM, moving to IB.

**Comment by zutigrm** [comment] 2024-11-04 10:56
Thanks @10upsimon almost there, just few suggestion for clarity/simplification:

> Update the Debug_Data class at includes/Core/Site_Health/Debug_Data.php
Include the following classes via the use statement:
  Google\Site_Kit\Core\Key_Metrics\Key_Metrics_Settings
  Google\Site_Kit\Core\Key_Metrics\Key_Metrics_Setup_Completed_By
Define 2x new private class properties:
  $key_metrics_settings - Will hold an instance of Key_Metrics_Settings
  $key_metrics_setup_completed_by - Will hold an instance of Key_Metrics_Setup_Completed_By
Within the existing class constructor:
  Set the value of $this->key_metrics_settings to be a new instance of Key_Metrics_Settings, passing $user_options as a class construction parameter
  Set the value of $this->key_metrics_setup_completed_by to be a new instance of Key_Metrics_Setup_Completed_By, passing $options as a class construction parameter 

This is a bit lengthy, we don't need to describe each step, it will suffice to say something like:
Update the Debug_Data class at includes/Core/Site_Health/Debug_Data.php
* Include `Google\Site_Kit\Core\Key_Metrics\Key_Metrics_Settings` and `Google\Site_Kit\Core\Key_Metrics\Key_Metrics_Setup_Completed_By` classes and assign them to their respective class properties
  * Instantiate them in the contructor

> Within the existing get_fields() method, create a new line that (array) merges existing $fields with the values obtained from a new class method, get_kmw_fields(), i.e:

Let's call this method `get_key_metrics_fields` to avoid having acronyms in the method names for better clarity and readability

> Create said new private method get_kmw_fields()

See the previous comment, also it might be redundant to include method visibility, since all other `get_*` methods in the file are already `private`

**Comment by zutigrm** [comment] 2024-11-04 14:34
@10upsimon Thanks, IB ✅

**Comment by mohitwp** [comment] 2024-11-22 13:08
### QA Update ❌ 



- Tested on dev  environment.
- Verified all cases as mentioned under AC.
- 

**Issue :** 


@jimmymadon 

1) I noticed that if a user disconnects sites where KM was already connected and disabled, the KM Site Health status change to the status and source mentioned below, regardless of whether the source was manually selected or KM was disabled before disconnecting Site Kit.

```
Key Metrics Status | Setup and Enabled
Key Metrics Source | Tailored Metrics
```

<details>

Before disconnect (Status - Setup and Disabled , Source-Manual)
After disconnect ( Status -Setup and Enabled . Source - tailored


https://github.com/user-attachments/assets/48cab949-4bcb-4ece-ae9b-8fcb9a8bad00


Before disconnect (Status - Setup and Disabled , Source-Tailored metrics)
After disconnect ( Status -Setup and Enabled . Source - Tailored metrics)

https://github.com/user-attachments/assets/b983caf9-911f-4dc2-8375-860a8605170a


</details>

**Comment by jimmymadon** [comment] 2024-11-23 23:59
@mohitwp The above is expected behaviour based on the following 'default' behaviour in Site Kit:

When a user "disconnects" from Site Kit, ALL of their individual user data is deleted (`wp_usermeta` table). This includes "user picked metrics" and the "enabled/disabled" status of Key Metrics. Both of these pieces of data is individual to the user, i.e. different users can have the Key metrics widget enabled/disabled and have their own selected metrics as well. However, the "data" that stores whether key metrics was setup already on a site is site data (`wp_options` table). This data does not get deleted as there might be other users connected to the site.

So in effect, when a user disconnects, the Key Metrics setup is still complete and the site shows the default enabled status and default "tailored metrics" state. This would be also the case when the user simply re-connects without changing anything.

**Closed** 2024-11-28 17:14 UTC
Labels: Type: Support, P0, Type: Enhancement, Team S
