### ISSUE TITLE
Implement "Idea Hub is generating ideas" as overall Idea Hub widget state

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3356] opened 2021-05-13 21:24 UTC
If there are no ideas at all to display in the Idea Hub widget, the entire widget should display in a special "Idea Hub is generating ideas" state (see [Figma](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=20332%3A6443)).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When there are neither any new ideas nor saved ideas nor draft post ideas to display in the Idea Hub widget, the entire widget should display in the "Idea Hub is generating ideas" state, i.e. the tabs and other widget components should not be shown.
* Essentially, this should look like [in this Figma design](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=20332%3A6443).

## Implementation Brief
* Once #3276 has been merged,
* Update `DashboardIdeasWidget` to check if the number of ideas returned by the `getNewIdeas`, `getSavedIdeas` and `getDraftPostIdeas` selectors are all `0`.
    * If this is the case, then render the same component/use the same logic which is used to render the empty state in the "New" tab within the `.googlesitekit-idea-hub` container.
    * If any of the above values from selectors are _not_ zero, render the `DashboardIdeasWidget` markup.

### Test Coverage
* No tests to be added.

### Visual Regression Changes
* N/A

## QA Brief

* See new state added here -> https://google.github.io/site-kit-wp/storybook/pull/3396/?path=/story/modules-idea-hub-widgets-dashboardideaswidget--data-unavailable-all
* Observe other states are rending fine

## Changelog entry

* N/A

**Comment by asvinb** [comment] 2021-05-17 09:00
@felixarntz Looks like the current issue is a duplicate of #3276 where the yellow sidekick when there is no data will be implemented. What do you think?

**Comment by asvinb** [comment] 2021-05-18 10:56
Actually nvm @felixarntz . This is the case when we have no data for all 3 tabs, whereas in #3276, it's per tab. Reassigning ticket to me.

**Comment by tofumatt** [comment] 2021-05-20 21:22
IB ✅

**Comment by wpdarren** [comment] 2021-05-26 13:44
### QA Update: Pass ✅ 

**Verified:**

Within Storybook I went through all of the screens on the `DashboardIdeasWidget` and everything rendered. 

@danielgent the only observation I have is on `Data Unavailable: All` there is a full stop/period on the description. `This could take 24 hours.` Unsure if you want me to highlight this in another ticket. All of the other descriptions are fine. 

![image](https://user-images.githubusercontent.com/73545194/119670293-ad4acc00-be30-11eb-9b96-72c1874fa7d0.png)

**Closed** 2021-06-04 00:22 UTC
Labels: Good First Issue, Module: Idea Hub, P0, Type: Enhancement
