### ISSUE TITLE
Fix rounding error on Visit length tile

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7760] opened 2023-10-25 14:47 UTC
## Bug Description

As reported by @10upsimon and @techanvil in Bug Bash ([Asana task](https://app.asana.com/0/1205508124049666/1205794035261776/f)):

The Visit length tile currently incorrectly floors the time as opposed to rounding it to the nearest integer:

![image](https://github.com/google/site-kit-wp/assets/12189958/7761cdf4-d6f2-4499-b379-0a4895a39432)

![image](https://github.com/google/site-kit-wp/assets/12189958/76d37cd0-fcde-4bb2-8190-c4b3b1bdafd8)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2023-10-30 17:18
Downgrading this one as it requires some investigation to determine the way these values are presented in GA to know whether or not any change in rounding is necessary. For now, it will be done consistently with the way we do all other number formatting via #7768.

**Comment by bethanylang** [comment] 2023-10-30 17:20
Thanks @aaemnnosttv! Updated this accordingly in <a href="https://app.asana.com/0/1205508124049666/1205794035261776/f">the Bug Bash board</a> as well.

**Comment by nfmohit** [comment] 2023-10-30 19:30
I have investigated this further and it seems in analytics.google.com, the durations actually seem to floor the values instead of rounding it to the nearest integer, which is consistent with how we do it in Site Kit. Screenshots:

GA Dev Tools:
![image](https://github.com/google/site-kit-wp/assets/20284937/160a13c8-c54f-417a-a76c-4416f2d72b59)

analytics.google.com:
![image](https://github.com/google/site-kit-wp/assets/20284937/d4ce13b6-7ff8-437a-9bc7-dec6bb05feab)

I'm moving this to Triage to determine if we should close this as expected behaviour.

CC: @aaemnnosttv

**Comment by aaemnnosttv** [comment] 2023-11-15 14:38
Closing for now as it seems to be consistent. Thanks @nfmohit !

**Closed by aaemnnosttv** 2023-11-15 14:38 UTC
Labels: P2, Type: Enhancement
