### ISSUE TITLE
Help, date picker and account hover state background

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3069] opened 2021-04-01 09:28 UTC
On all the menu items such as Help, date picker, and accounts:
Mouse hover grey bg needs to be kept active as long as the dropdown is open. Currently if the user clicks one of these menu items and then move the mouse outside these controls, the grey bg disappears like this:

![image.png](https://images.zenhubusercontent.com/60644f95230dae16dabe0ca1/5c8f4cb2-37e3-4a7f-bbcb-00cd375a1a48)

It should be like as shown below in the image, even if the mouse pointer is moved away.
This grey BG should be active as long as the dropdown options are open.

![image.png](https://images.zenhubusercontent.com/60644f95230dae16dabe0ca1/a81e0d8a-250c-4117-9356-dcd2a1f3d17b)

**This applies to all the header menu items.**

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When opening any of the three available menus in the Site Kit header bar (user, date picker, help menu, from right to left), the respective button that toggles the menu should remain in its grey background color as long as its menu is open.
    * In other words, in this scenario each toggle button should look the same way it does when hovering over it.

## Implementation Brief
* Using `assets/sass/config/_variables.scss`
	* Add a new variable for `#f0f0f0`
* Using `assets/sass/components/global/_googlesitekit-dropdown-menu.scss`,
	* Add new selector for `mdc-button--dropdown[aria-expanded="true"]` having
		* `background-color` set to `#f0f0f0` using the variable added in bullet point 1.
		* `color` set to `rgba(0, 0, 0, 0.87)`

### Test Coverage
* N/A 

### Visual Regression Changes
* The background color of the dropdowns in the header will change when they are expanded.

## QA Brief

* View the Site Kit Dashboard
* Click any of the items in the menu
* Assert that the menu item maintains the hover state styling when open (like the second image in the description)

## Changelog entry

* Update the background color of open menu buttons in the Site Kit header.

**Comment by tofumatt** [comment] 2021-04-21 12:58
IB ✅

**Comment by cole10up** [comment] 2021-04-27 06:36
### **QA ⚠️**

Question testing this ticket, when testing using tab and enter keys on the keyboard. Should we retain the hover state after selecting the drop down for the date picker? Currently if you tab to the date picker and press the enter key, if you tab again the hover state is removed.

![Uploading Site Kit by Google Dashboard ‹ SupremeQA — WordPress (1).gif…]()

**Comment by tofumatt** [comment] 2021-04-27 11:55
The "hover" state is also the "focus" state, which should be preserved after selection because it's where the keyboard focus is after selection. Until the user tabs away from that item, it should remain in the "focus"/"hover" state, so yes, that's correct.

**Comment by danielgent** [comment] 2021-05-03 19:18
Ok there are a few things going on here.

We have state in React for all these menus to say if they're open *but* we don't actually listen to the tab key event.  So when tab is pressed, the browser is moving focus to the next element *but* we're not setting the state to false.  So the CSS rule that I added in my previous PR is still active because the `aria-expanded` attribute is still `"true"`
```
	.mdc-button--dropdown[aria-expanded="true"] {
		background-color: $c-gallery;
		color: rgba(0, 0, 0, 0.87);
	}
```

Notice that to open any menu again **after** tabbing away you need to click **twice** (first click sets the menu open state to false, the second click sets it to true which opens it again)

**Comment by danielgent** [comment] 2021-05-03 19:23
The reason the above bug wasn't spotted and the menu stayed open is because the menu `/assets/js/components/Menu.js` is built with a non-React library `@material/menu`

This is passed a ref to the menu `const menuComponent = new MDCMenu( menuRef.current );` and then it has its own state for closing the menu

In React we are toggling it imperatively with a `useEffect`, but it is also responding to key events
```
useEffect( () => {
	if ( menu ) {
		menu.open = menuOpen;
		menu.setDefaultFocusState( 1 );
	}
}, [ menu, menuOpen ] );
```

**Comment by danielgent** [comment] 2021-05-03 19:28
*and* there's another bug which haven't spotted and `@material/menu` has covered up!

There is a bug in the three menus' logic. The `handleMenuClose` mixes a click outside handler with a keypress one so it disregards all `Escape` key presses (because the event.target **is** the button)

```
if (
	( ( 'keyup' === event.type && ESCAPE === event.keyCode ) || 'mouseup' === event.type ) &&
	! menuButtonRef.current.contains( event.target ) &&
	! menuRef.current.contains( event.target )
) {
	setMenuOpen( false );
}
```
https://github.com/google/site-kit-wp/blob/main/assets/js/components/DateRangeSelector.js#L52

This looks like a bug and there should be extra parenthesis after the `||`

This means that if you open the menu pressing `enter`, then close pressing `escape`, you have to hit `enter` twice to open it again (same bug as above with the first keypress resetting the state)

**Comment by danielgent** [comment] 2021-05-03 20:15
I managed to fix the weirdness with the menu taking two clicks to open *but* when I tab when `@material/menu` is focused it doesn't play well with React and the tabbing breaks. 

Here you can see the problem on a branch I've done where I tried to fix the key press and click outside handling with `react-use` hooks
https://github.com/google/site-kit-wp/compare/enhancement/3069-help-date-picker-key-event-bug-fix

**Comment by felixarntz** [comment] 2021-05-04 18:35
@tofumatt Can you review #3279 (since it's a11y-related)?

**Comment by wpdarren** [comment] 2021-05-05 15:13
### QA Update:  Engineer clarification ⚠️ 

@tofumatt this is looking good other than an observation when you use tab to move around the navigation. This is only an issue when you press enter for the dropdown list to appear. When I tab to account, the date picker navigation is still highlighted.  This screencast below highlights the issue better than I can explain it. 

Is this an issue, possibly not linked to this ticket, but thought I would highlight. 

https://user-images.githubusercontent.com/73545194/117163816-f07ac780-adbb-11eb-9647-d885e5330c83.mp4

**Comment by tofumatt** [comment] 2021-05-05 15:21
Hmmm, that's not the right effect, I'll take a look and see if it's a regression or if that's a separate bug.

**Comment by tofumatt** [comment] 2021-05-05 16:01
@wpdarren I think the issue was that the fix wasn't in `develop`, but should be there now. Can you try again on the `develop` branch—we just merged the fix over 👍🏻

**Comment by wpdarren** [comment] 2021-05-05 16:24
### QA Update: Pass ✅ 

- Verified that the menu item maintains the hover state styling when open. This was tested on Chrome, Firefox and Safari. I also ran this through mobile devices and smaller screens to make sure that the behaviour was the same. 
- Verified that the navigation can be used without a mouse, so keyboard (tab, enter, arrow keys) to make sure that the behaviour was the same on the hover state. 

[Screenshot 1](https://user-images.githubusercontent.com/73545194/117175211-7e5bb000-adc6-11eb-81a8-0fcfaf6c3bfa.png) - [Screenshot 2](https://user-images.githubusercontent.com/73545194/117175226-8287cd80-adc6-11eb-8f66-c7e780368bee.png) - [Screenshot 3](https://user-images.githubusercontent.com/73545194/117175291-959a9d80-adc6-11eb-8a0c-9127f7bb7373.png)

**Closed** 2021-05-06 17:58 UTC
Labels: Good First Issue, P1, Type: Enhancement
