### ISSUE TITLE
Implement default Snippet Toggle behavior when there is an existing GTM property

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#5141] opened 2022-04-27 15:14 UTC
## Feature Description

We should implement logic (either in `useExistingTagEffect` or somewhere else) that turns on/off Snippet Toggle when there's an existing GTM property. It should behave similarly to #4913. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

Some background information: The ACs here mostly update the Tag Manager enforcement behavior to be GA property-specific, rather than apply regardless of _which_ GA property is used in Tag Manager. For the time being, we will keep using this approach, i.e. we will not incorporate the Tag Manager tag into a `useExistingTagEffect`-like handler. The `useSnippet` setting of GA should for now remain untouched in favor of sticking with the `canUseSnippet` filter control. This ensures that, if the Tag Manager module is deactivated again later, the Analytics snippet is placed again.

* The `googlesitekit_analytics_can_use_snippet` filter should be enhanced to receive the current UA property ID as second parameter.
    * In the case of the option default being used, it should simply pass an empty string since in that case no property ID is set.
* The Tag Manager usage of that filter should be adjusted to only set the value to `false` if the GA property in Tag Manager is set _and_ is the same one as the GA property in the Analytics module (i.e. the one passed to the filter, see above).
* Since this is now a bit more dynamic based on taking the current UA property ID into account, that needs to be reflected on the client-side as well. Therefore, the `analytics` store's `getCanUseSnippet` selector should be re-implemented as an actual selector, rather than just using the generated selector that directly returns the value of the `canUseSnippet` setting.
    * It should first call `getSettings` to get the Analytics settings.
    * It should then check if the `tagmanager` module is active and whether the `modules/tagmanager` store is loaded.
    * If it both conditions are true, it should call that store's `getGAPropertyID` selector to get a potential GA property ID within Tag Manager, and if there is one, compare it to the current UA `propertyID` in Analytics. If they match, it should return `false`, otherwise it should return `true`.
    * If one of the conditions is false, it should just return the value from the `canUseSnippet`.
* The Analytics `SetupUseSnippetSwitch` component should include the same check present in the module's `SettingsUseSnippetSwitch` component: If `canUseSnippet` is `false`, the same text should be displayed (_The code is controlled by the Tag Manager module._).
* Both the `SetupUseSnippetSwitch` and the `SettingsUseSnippetSwitch` should be updated to also display the toggle as off when `canUseSnippet` is `false`, **without modifying the `useSnippet` setting though**. In other words, `canUseSnippet` overrides `useSnippet`, while the latter setting should remain unmodified.
* The result from the changes above should be that the snippet toggle is always displayed as visually disabled, with the value as off, and accompanied by a corresponding text when there is a Tag Manager GA property that is the same as the selected UA property.

## Implementation Brief

in `Google\Site_Kit\Modules\Tag_Manager` class:

* in the `can_analytics_use_snippet` method:
    * Take `ua_property` as the second param which is empty string by default. 
    * Return `false` if the `gaPropertyID === $ua_property_id`
    * Return `original_value` otherwise. 
* in the `register` method:
    * Update the `add_action` hook call of `googlesitekit_analytics_can_use_snippet` to receive 2 arguments. 
        * change `add_action` to `add_filter` as it's a actually a filter. 
        * `add_filter( 'googlesitekit_analytics_can_use_snippet', $this->get_method_proxy( 'can_analytics_use_snippet' ), 10, 2 );`

In `Google\Site_Kit\Modules\Analytics\Settings` class:

* In the `register` method:
    * Inside the callback of `default_option_*` filter, pass empty string as the third parameter of googlesitekit_analytics_can_use_snippet` filter. ie. `apply_filters( 'googlesitekit_analytics_can_use_snippet', true, '' );`
    * Inside the callback of `option_*` filter, pass `property_id` as the third parameter of googlesitekit_analytics_can_use_snippet` filter. ie. `apply_filters( 'googlesitekit_analytics_can_use_snippet', true, $property_id );`

In `assets/js/modules/analytics/datastore/base.js`:

* Re implement  `getCanUseSnippet` as a REAL selector.
    * See `assets/js/modules/tagmanager/datastore/base.js` for an example on how to override generated store selector. 
    * Using `createRegistrySelector` function, redefine the getCanUseSnippet selector.
    * Check if tagmanager store is available by checking the value of `isModuleConnected`  selector of `CORE_MODULES` store. 
    * Check if the Tag Manager Snippet is enabled using the `useSnippet` selector.
    * If Tag Manager is connected and it's snippet is enabled, get the potential UA property within GTM using `getGAPropertyID` selector.
        * If it's available and `isValidPropertyID`, compare it with the `propertyID` of analytics module.
            * return false if both property IDs match. 
            * return true otherwise. 
    * Return the value of `canUseSnippet` otherwise. 

In `assets/js/modules/analytics/components/common/SetupUseSnippetSwitch.js`:

* Get `canUseSnippet` using the newly reimplimented selector. 
* Return `null` from the component when there's no `existingTag` or the value of `canUseSnippet` is `undefined` or `true`
* Render the `UseSnippetSwitch` with the same copy as used in `SettingsUseSnippet` of the same module when `canUseSnippet === false`.
* Update all usage of the component to be rendered unconditionally.

In `assets/js/modules/analytics/components/common/UseSnippetSwitch.js`:

* Update the `checked` prop of the switch component to be `false` when `canUseSnippet === false`. ie. `checked={ canUseSnippet === false ? false : useSnippet }`
* Update the `disabled` prop to be `disabled={ canUseSnippet === false }`

### Test Coverage

* Update all the failing PHP and JS tests. 

## QA Brief

* Add an UA tag inside the Tag Manager Container.
* Make sure both Analytics and Tag Manager are Completely disconnected. (Incomplete setup will pose problems, ie. neither module should be in Connected Modules. Reset site kit if needed.)
* Attempt to setup Tag Manager with same container. 
* See that There's a `Continue to Analytics Setup` Blue button and the following copy on top of the page. 
    * Copy: `Looks like you’re already using Google Analytics within your Google Tag Manager configuration. Activate the Google Analytics module in Site Kit to see relevant insights in your dashboard.`
* Click on the Blue CTA to continue to Analytics Setup.
* See that the AC is met there.     
## Changelog entry

* Update Analytics snippet toggle behavior to be disabled when the same property is set in the Tag Manager container.

**Comment by felixarntz** [comment] 2022-05-02 18:54
@aaemnnosttv Assigning to you for review of the ACs. Let's stick with the current approach around `canUseSnippet`, but make it specific to only when the same property that is in Tag Manager is selected in the Analytics module.

**Comment by aaemnnosttv** [comment] 2022-05-02 21:01
> * The value of the toggle itself (i.e. whether it's toggled on or off) should not change though, it should just be shown as disabled.

@felixarntz I think if `canUseSnippet` is `false`, the toggle should be `disabled` and the `value` should be off (indicating that the Analytics snippet will not be output). The important thing I think you're getting at is that the `useSnippet` setting value _in the store_ does not change as a result.

That is, if `canUseSnippet` is `false`, if `useSnippet` is `true`, the toggle would still show as both disabled and toggled off, but `useSnippet` in the store would be unchanged. Does that make sense?

E.g.
```js
<Switch
    value={ canUseSnippet === false ? false : useSnippet }
    disabled={ canUseSnippet === false }
/>
```

**Comment by felixarntz** [comment] 2022-05-03 16:32
@aaemnnosttv Ah, yeah that makes sense. I've clarified the ACs. Assigning back to you for another pass, feel free to move to IB.

**Comment by aaemnnosttv** [comment] 2022-05-03 17:10
> * The `googlesitekit_analytics_can_use_snippet` filter should be enhanced to receive the current UA property ID as second parameter.

@felixarntz ACs LGTM, just one question left – looking ahead to tag detection in GTM for GA4, do you expect we will implement a similar filter for the GA4 module in the future if this one is specific to UA?

**Comment by felixarntz** [comment] 2022-05-03 17:40
@aaemnnosttv Yeah, if we do that at some point, I think that should be a separate filter (e.g. prefixed with `googlesitekit_analytics-4`).

**Comment by felixarntz** [comment] 2022-05-04 18:15
@aaemnnosttv 
> > * The Tag Manager usage of that filter should be adjusted to only set the value to `false` if the GA property in Tag Manager is set _and_ is the same one as the GA property in the Analytics module (i.e. the one passed to the filter, see above).
> 
> @felixarntz it should preserve the condition that this only applies when the GTM snippet is enabled, correct?

Correct, that should still apply, good point. The GTM `useSnippet` setting has to be `true` for Tag Manager to override the Analytics snippet. If it's `false`, Analytics `getCanUseSnippet` should return the regular `true` no matter what.

**Comment by kuasha420** [comment] 2022-05-04 18:57
@aaemnnosttv @felixarntz 

> Correct, that should still apply, good point. The GTM useSnippet setting has to be true for Tag Manager to override the Analytics snippet. If it's false, Analytics getCanUseSnippet should return the regular true no matter what.

In that case, how can we still do it if there's an Existing Tag Manager Tag that contains the right UA Property? Right now, the UA inside GTM is still detected if it's an Existing GTM tag. Or is this too edge-case-y to be considered? 

@aaemnnosttv I will update the IB as par your feedback.

**Comment by felixarntz** [comment] 2022-05-04 19:02
@kuasha420 
> > Correct, that should still apply, good point. The GTM useSnippet setting has to be true for Tag Manager to override the Analytics snippet. If it's false, Analytics getCanUseSnippet should return the regular true no matter what.
> 
> In that case, how can we still do it if there's an Existing Tag Manager Tag that contains the right UA Property? Right now, the UA inside GTM is still detected if it's an Existing GTM tag. Or is this too edge-case-y to be considered?

Not sure I understand, can you clarify?

I think the logic requirements for the `getCanUseSnippet` selector should be:
* Is the Tag Manager module active? If not, return `true`.
* Is the Tag Manager store available? If not, return `true`.
* Is the Tag Manager `useSnippet` setting set to `true`? If not, return `true`.
* Is there a UA property in the Tag Manager container that matches the current `propertyID` in the `analytics` module? If not, return `true`.
* Only then, return `false` (i.e. all of the above conditions must be satisfied).

Also remember that all of this only applies to the UA toggle. Since we don't support GA4 in GTM yet, we don't need to worry about the GA4 toggle here at all.

**Comment by aaemnnosttv** [comment] 2022-05-04 19:03
> In that case, how can we still do it if there's an Existing Tag Manager Tag that contains the right UA Property? Right now, the UA inside GTM is still detected if it's an Existing GTM tag. Or is this too edge-case-y to be considered?

Great question. I think for now we don't consider this case as there is no way to know from the settings alone if the configured container is from an existing tag or not. We could check for an existing tag here as well but I think this is going to far for this issue and is something we could potentially do as a future enhancement.

**Comment by kuasha420** [comment] 2022-05-04 19:33
@felixarntz @aaemnnosttv thanks for the clarification. I have updated the IB.

**Comment by aaemnnosttv** [comment] 2022-05-04 20:07
> * Check if the Tag Manager Snippet is enabled using the `useSnippet` selector.

@kuasha420 my comment before was in regards to the changes in Tag Manager's `can_analytics_use_snippet` method in PHP – just clarifying that the condition still includes `useSnippet` as part of its logic. I don't think it's necessary to check this on the client side because it wouldn't change during Analytics setup meaning if the `canUseSnippet` setting is `false` the GTM snippet must have be enabled on page load. It doesn't hurt to check this on the client as well but since the new enhanced selector falls back to the value of the setting I think this might not be necessary. This is a rather minor detail though.

IB ✅

**Comment by wpdarren** [comment] 2022-05-07 11:10
### QA Update: ✅ 

**Verified:**

There's a `Continue to Analytics Setup Blue` button and the following copy `Looks like you’re already using Google Analytics within your Google Tag Manager configuration. Activate the Google Analytics module in Site Kit to see relevant insights in your dashboard.`

![image](https://user-images.githubusercontent.com/73545194/167251541-6e97425c-c421-4b1e-a8ce-83228363974b.png)

When I click on the Blue CTA to continue the Analytics is per the AC. 
Confirmed that the snippet toggle is disabled in this scenario.  

![image](https://user-images.githubusercontent.com/73545194/167251679-2be7fed4-e66d-4710-b286-f1a6290e0873.png)

Also checked Site Kit Settings for Google Analytics to make sure that it shows that the Universal Analytics Code Snippet
text was `The code is controlled by the Tag Manager module.`

![image](https://user-images.githubusercontent.com/73545194/167251710-aae86a87-e6b8-4324-816a-0967b79f00d1.png)

![image](https://user-images.githubusercontent.com/73545194/167251755-f9137e17-43dd-44b3-a89c-a7e400bf1191.png)

**Closed** 2022-05-19 16:23 UTC
Labels: P0, Type: Enhancement, Module: Analytics, End of Sprint
