### ISSUE TITLE
Modules remain loading: no route was found matching the url and request method

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1233] opened 2020-03-09 12:01 UTC
## Bug Description

![image](https://user-images.githubusercontent.com/41326532/76211050-475b3000-61fd-11ea-8100-290c18e5b832.png)

Reported issue whereby Site Kit module status (and possibly dashboard) are not populating. 
`no route was found matching the url and request method
`
Website: [https://plotperty.com](https://plotperty.com)
Additional info: [WordPress topic](https://wordpress.org/support/topic/site-kit-keeps-on-loading/)

Additional context:
- User did not deactivate all plugins, difficult to determine whether plugin related
- Same issue arises with Site Kit version 1.4.0 (as it did previously)
- Not caching/browser related (checked using incognito window)
- Internal Server Error – The REST API has been deleted error has appeared
- No issues with accessing standard REST endpoints from [front end of site](https://plotperty.com//?rest_route=/)

Site Health info:
```
### wp-core ###

version: 5.3.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /zameen/%category%/%postname%
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/plotnmzs/public_html
wordpress_size: 50.16 MB (52593494 bytes)
uploads_path: /home/plotnmzs/public_html/wp-content/uploads
uploads_size: 12.41 MB (13011489 bytes)
themes_path: /home/plotnmzs/public_html/wp-content/themes
themes_size: 4.60 MB (4822549 bytes)
plugins_path: /home/plotnmzs/public_html/wp-content/plugins
plugins_size: 102.01 MB (106962827 bytes)
database_size: 71.40 MB (74872568 bytes)
total_size: 240.58 MB (252262927 bytes)

### wp-dropins (3) ###

advanced-cache.php: true
db.php: true
object-cache.php: true

### wp-active-theme ###

name: Twenty Twenty (twentytwenty)
version: 1.0 (latest version: 1.1)
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, custom-background, post-thumbnails, custom-logo, title-tag, html5, align-wide, customize-selective-refresh-widgets, editor-color-palette, editor-font-sizes, widgets, menus, editor-style
theme_path: /home/plotnmzs/public_html/wp-content/themes/twentytwenty

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 1.4, author: the WordPress team
Twenty Seventeen: version: 2.2, author: the WordPress team
Twenty Sixteen: version: 2.0, author: the WordPress team

### wp-plugins-active (20) ###

Custom Field Finder: version: 0.1, author: Joost de Valk
Display Posts: version: 3.0.2, author: Bill Erickson
Google XML Sitemaps: version: 4.1.0, author: Arne Brachhold
Insert PHP Code Snippet: version: 1.3.1, author: xyzscripts.com
Permalink Manager Lite: version: 2.2.7.6, author: Maciej Bis
Post Views Counter: version: 1.3.1, author: Digital Factory
Query Monitor: version: 3.5.2, author: John Blackbourn
Redux Framework: version: 3.6.17, author: Team Redux
Site Kit by Google: version: 1.2.0, author: Google
Social Media and Share Icons (Ultimate Social Media): version: 2.4.9, author: UltimatelySocial
W3 Total Cache: version: 0.13.1, author: BoldGrid
WhatsApp Chat: version: 4.6.0, author: QuadLayers
WP All Export: version: 1.2.5, author: Soflyy
WP All Import: version: 3.5.2, author: Soflyy
WPForms Lite: version: 1.5.8.2, author: WPForms
WP Sheet Editor: version: 2.16.0, author: WP Sheet Editor
WP Sheet Editor - Taxonomy Terms: version: 1.2.5, author: WP Sheet Editor
WP Sheet Editor - YOAST SEO: version: 1.1.5, author: WP Sheet Editor
WP Statistics: version: 12.6.12, author: VeronaLabs
Yoast SEO: version: 13.0, author: Team Yoast

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1684
imagemagick_version: ImageMagick 6.9.4-10 Q16 x86_64 2017-11-14 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 251 GB
	imagick::RESOURCETYPE_DISK: 1.844674407371E+19
	imagick::RESOURCETYPE_FILE: 12288
	imagick::RESOURCETYPE_MAP: 251 GB
	imagick::RESOURCETYPE_MEMORY: 126 GB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 8.70

### wp-server ###

server_architecture: Linux 2.6.32-896.16.1.lve1.4.49.el6.x86_64 x86_64
httpd_software: Apache
php_version: 7.2.27 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 0
memory_limit: 256M
max_input_time: 300
upload_max_size: 512M
php_post_max_size: 512M
curl_version: 7.62.0 OpenSSL/1.0.2k
suhosin: false
imagick_availability: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.1.44-MariaDB-cll-lve
client_version: 10.1.43-MariaDB

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/plotnmzs/public_html/wp-content
WP_PLUGIN_DIR: /home/plotnmzs/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### 0 ###

version: 1.5.8.2
license: undefined
lite: Feb 3, 2020 @ 11:46am
db_tables: Not found
total_forms: undefined
total_entries: undefined
```

## Screenshots

![image](https://user-images.githubusercontent.com/41326532/76210295-bdf72e00-61fb-11ea-83ae-deb2537d0d82.png)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment] 2020-03-16 12:13
Another report of this same issue below, awaiting further information:
[https://wordpress.org/support/topic/no-services-will-work/](https://wordpress.org/support/topic/no-services-will-work/)

**Comment by cole10up** [comment] 2020-03-23 06:08
Mocked the user above's WP setup including all plugins, installed all of them and activated. Setup all modules and checked functionality. Looked good. Was unable to reproduce on 1.5.1

<details>
  <summary>Click to expand for Site Health info</summary>
`
### wp-core ###

version: 5.3.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /srv/users/usera322a36b/apps/usera322a36b/public
wordpress_size: 37.88 MB (39723828 bytes)
uploads_path: /srv/users/usera322a36b/apps/usera322a36b/public/wp-content/uploads
uploads_size: 0.00 B (0 bytes)
themes_path: /srv/users/usera322a36b/apps/usera322a36b/public/wp-content/themes
themes_size: 4.63 MB (4859674 bytes)
plugins_path: /srv/users/usera322a36b/apps/usera322a36b/public/wp-content/plugins
plugins_size: 109.92 MB (115254707 bytes)
database_size: 3.34 MB (3506176 bytes)
total_size: 155.78 MB (163344385 bytes)

### wp-dropins (2) ###

advanced-cache.php: true
db.php: true

### wp-active-theme ###

name: Twenty Twenty (twentytwenty)
version: 1.1
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, custom-background, post-thumbnails, custom-logo, title-tag, html5, align-wide, customize-selective-refresh-widgets, editor-color-palette, editor-font-sizes, widgets, menus, editor-style
theme_path: /srv/users/usera322a36b/apps/usera322a36b/public/wp-content/themes/twentytwenty

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 1.4, author: the WordPress team
Twenty Seventeen: version: 2.2, author: the WordPress team
Twenty Sixteen: version: 2.0, author: the WordPress team

### wp-plugins-active (20) ###

Akismet Anti-Spam: version: 4.1.3, author: Automattic (latest version: 4.1.4)
Companion Plugin: version: 1.11, author: Osk
Display Posts: version: 3.0.2, author: Bill Erickson
Google XML Sitemaps: version: 4.1.0, author: Arne Brachhold
Hello Dolly: version: 1.7.2, author: Matt Mullenweg
Insert PHP Code Snippet: version: 1.3.1, author: xyzscripts.com
Jetpack by WordPress.com: version: 8.3, author: Automattic
Permalink Manager Lite: version: 2.2.8.4, author: Maciej Bis
Post Views Counter: version: 1.3.1, author: Digital Factory
Query Monitor: version: 3.5.2, author: John Blackbourn
Redux Framework: version: 3.6.17, author: Team Redux
Site Kit by Google: version: 1.5.1, author: Google
Social Media and Share Icons (Ultimate Social Media): version: 2.5.3, author: UltimatelySocial
W3 Total Cache: version: 0.13.1, author: BoldGrid
WhatsApp Chat: version: 4.6.2, author: QuadLayers
WP All Export: version: 1.2.5, author: Soflyy
WP All Import: version: 3.5.2, author: Soflyy
WPForms Lite: version: 1.5.9.5, author: WPForms
WP Sheet Editor - WooCommerce Products: version: 1.4.1, author: WP Sheet Editor
WP Statistics: version: 12.6.12, author: VeronaLabs

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 4.4.0-174-generic x86_64
httpd_software: Apache/2.4.41 (Unix) OpenSSL/1.0.2g
php_version: 7.3.15 64bit
php_sapi: fpm-fcgi
max_input_variables: 5000
time_limit: 0
memory_limit: 256M
max_input_time: -1
upload_max_size: 512M
php_post_max_size: 1024M
curl_version: 7.47.0 OpenSSL/1.0.2g
suhosin: false
imagick_availability: false
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.29-0ubuntu0.16.04.1-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /srv/users/usera322a36b/apps/usera322a36b/public/wp-content
WP_PLUGIN_DIR: /srv/users/usera322a36b/apps/usera322a36b/public/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### jetpack ###

site_id: false
ssl_cert: No
time_diff: false
version_option: 8.3:1584941712
old_version: 8.3:1584941712
public: Private
master_user: No master user set.
current_user: #1 demo (oskosk+jurassicninja+new+site+created@gmail.com)
tokens_set: None
blog_token: Not set.
user_token: Not set.
version: 8.3
jp_plugin_dir: /srv/users/usera322a36b/apps/usera322a36b/public/wp-content/plugins/jetpack/
plan: free
HTTP_HOST: classic-elk.jurassic.ninja
SERVER_PORT: 443
HTTPS: on
HTTP_X_FORWARDED_FOR: 68.8.26.177
REMOTE_ADDR: 68.8.26.177
protect_header: false
full_sync: {"started":"Thu, 01 Jan 1970 00:00:00 +0000","finished":"Thu, 01 Jan 1970 00:00:00 +0000","progress":[],"config":[]}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/classic-elk.jurassic.ninja","siteurl":"https:\/\/classic-elk.jurassic.ninja","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: [{"name":"test__check_if_connected","pass":false,"message":"Jetpack is not connected.","resolution":"connect_jetpack","action":"https:\/\/classic-elk.jurassic.ninja\/wp-admin\/admin.php?page=jetpack#\/dashboard","severity":"critical","label":"Your site is not connected to Jetpack","action_label":"Reconnect your site now","description":"<p>A healthy connection ensures Jetpack essential services are provided to your WordPress site, such as Stats and Site Security.<\/p><p><span class=\"dashicons fail\"><span class=\"screen-reader-text\">Error<\/span><\/span> Your site is not connected to Jetpack.<strong> We recommend reconnecting Jetpack.<\/strong><\/p>","group":["default"],"type":"direct"}]

### wpforms ###

version: 1.5.9.5
license: false
lite: Mar 23, 2020 @ 6:02am
total_forms: undefined
total_entries: undefined

### google-site-kit ###

version: 1.5.1
php_version: 7.3.15
wp_version: 5.3.2
reference_url: https://classic-elk.jurassic.ninja
amp_mode: no
site_status: connected-site
user_status: authenticated
active_modules: site-verification, search-console, adsense, analytics, pagespeed-insights
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
	https://www.googleapis.com/auth/adsense: ✅
	https://www.googleapis.com/auth/analytics: ✅
	https://www.googleapis.com/auth/analytics.readonly: ✅
	https://www.googleapis.com/auth/analytics.manage.users: ✅
	https://www.googleapis.com/auth/analytics.edit: ✅
search_console_property: https://classic-elk.jurassic.ninja/
adsense_account_id: none
adsense_client_id: none
adsense_account_status: none
adsense_use_snippet: yes
analytics_account_id: 2230••••
analytics_property_id: UA-2230••••••
analytics_profile_id: 1354•••••
analytics_use_snippet: yes

`
</details>

**Comment by aaemnnosttv** [comment] 2020-04-15 17:25
The error they're seeing is correct. There is no `GET` route defined for the batch `data` endpoint, it's `POST` only.

The only way I can think that this would be possible for some, and not others would be a redirect; perhaps `http` -> `https` as redirects all become GET requests. I can reproduce this but I don't see anything from installed plugins, etc that might be responsible.

@felixarntz I suggest we close this as it seems to be an edge case that is likely environment specific.

**Comment by felixarntz** [comment] 2020-04-20 19:32
@aaemnnosttv Agreed, the request that is being made there is actually incorrect, and the Site Kit codebase is only making `POST` requests there as expected. _Many_ months ago we were using a `GET` request, but that is not what's happening here (the request had all the data as query parameters), so it's not caused by over-aggressive caching. Potentially the setup is weird blocking `POST` requests and turning them into `GET` on the client?

I agree this issue should be closed, it's not a Site Kit problem.

@jamesozzie The only thing I could think of to reply is related to Evan's idea above - maybe the site is on HTTP via the settings, but uses an HTTPS redirect? I doubt it's that, but I also really don't have any clue 🤷‍♂️

**Closed by felixarntz** 2020-04-20 19:32 UTC
Labels: Group: Escalation
