### ISSUE TITLE
Link to Site Kit service permissions screen in localized version

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1860] opened 2020-07-30 21:28 UTC
## Bug Description

The Site Kit service permissions screen is currently not accessed in its localized version even though these versions are available. This was missed in #1726.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The URL to the proxy permissions screen should also include the `hl` query parameter with the user language.

## Implementation Brief

* Merge #1861.

## QA Brief

* On a site with a locale supported by the Site Kit service (e.g. German, Spanish, Japanese, ...), when opening the Site Kit user account dropdown on the top right and clicking "Manage sites", the content on that page should be localized.

## Changelog entry

* Link to the Manage sites screen including an `hl` query parameter for a localized experience.

**Comment by aaemnnosttv** [comment] 2020-07-31 09:21
IB ✅

**Comment by cole10up** [comment] 2020-08-07 00:56
**Tested**

Built latest develop build, activated and setup SK.

Checked and **Manage Sites** is missing from develop and dev.

This is production:
![image](https://user-images.githubusercontent.com/57115907/89596938-7954da80-d80d-11ea-91cb-0bc091cc8c3f.png)

![image](https://user-images.githubusercontent.com/57115907/89596954-85409c80-d80d-11ea-8ef9-126ec5555294.png)

This is build:dev:
![image](https://user-images.githubusercontent.com/57115907/89597015-c173fd00-d80d-11ea-8f38-5f1a929d5e70.png)

This is release:
![image](https://user-images.githubusercontent.com/57115907/89597083-f5e7b900-d80d-11ea-9d7e-a5aaac70db31.png)

Console:
![image](https://user-images.githubusercontent.com/57115907/89597129-157ee180-d80e-11ea-8c9b-7de6267cd8ab.png)

@felixarntz - Sending back to CR

**Comment by aaemnnosttv** [comment] 2020-08-07 08:57
@cole10up @felixarntz not sure that there is a problem here - at least looking at the screenshots. The error seems to be from a browser extension as we don't have a `showNag.js`.

The WP error warning shown is related to [this issue](https://github.com/google/site-kit-wp/issues/1858), so not a regression here.

**Comment by felixarntz** [comment] 2020-08-07 17:51
@aaemnnosttv I haven't yet looked into it, but the link missing entirely should never be the case. I'm not sure this was introduced as part of the PR here, but there's definitely something wrong.

**Comment by aaemnnosttv** [comment] 2020-08-07 17:55
Oh I see what you mean, I missed that part; you're right something is definitely off there 👍  Good catch @cole10up !

**Comment by felixarntz** [comment] 2020-08-11 02:10
One reference to `_googlesitekitLegacyData.admin.proxyPermissionsURL` was missed while removing that piece of information in https://github.com/google/site-kit-wp/commit/f8efdb0fd73694c50386593c3794ff7ff23dbfe6, that's why the link now no longer displays in the user menu. I'll open a follow-up PR.

**Comment by eugene-manuilov** [comment] 2020-08-12 11:17
@felixarntz #1903 is approved and can be merged. Assigning this ticket to you to merge the PR.

**Comment by cole10up** [comment] 2020-08-13 17:55
**Tested**

Installed, activated and setup latest SK release candidate.

Switched my site's language and checked 'Manage Sites' link.

**German:**
![image](https://user-images.githubusercontent.com/57115907/90169195-215d2d00-dd53-11ea-9ac7-f4dc95d93773.png)

**Spanish**
![image](https://user-images.githubusercontent.com/57115907/90169298-42be1900-dd53-11ea-81fb-c0b3f281ab87.png)

**Japanese**
![image](https://user-images.githubusercontent.com/57115907/90169459-75681180-dd53-11ea-99fc-4d3f2f223bd0.png)

**Notice 'Remove Access' button isn't translated**

Sending back for confirmation @felixarntz @adamsilverstein

**Comment by felixarntz** [comment] 2020-08-13 18:34
@adamsilverstein Can you look into that on the service?

@cole10up Good catch! Since this problem is unrelated to the plugin though, good to go 👍

**Closed** 2020-08-13 19:57 UTC
Labels: P1, Type: Bug

**Comment by adamsilverstein** [comment] 2020-08-14 22:52
@felixarntz will do, I added an internal task to track this.
