### ISSUE TITLE
Site Kit plugin is active but requires setup

### ISSUE THREAD

**Issue by dspurlock** [google/site-kit-wp#805] opened 2019-11-07 00:25 UTC
## Bug Description

11/4/19 8:00 PM
I installed Site Kit last night and spent a couple hours setting everything up. When I was finished everything was working fine. Today when i hover over “Site Kit” in the navigation bar I see the Dashboard and all the other links are gone. When I click on Dashboard it says “Site Kit plugin is active but requires setup”. I clicked “Start Setup” and it has me sign in to my google account, then returns to this same page.

11/5/19 9:00 PM
You ask me to follow the guide and report back. So here is your report.

Update to the latest version of Site Kit: VERSION 1.0.1
Check your site settings: go to Settings > General. Verify that the WordPress Address (URL) and Site Address (URL) values match. THEY MATCH
Deactivate potential conflicting plugins: Below is a list of plugins ALL which I deactivated.
GA Google Analytics
MailPoet 3
MetaSlider
UpdraftPlus – Backup/Restore
WP-Optimize
Yoast SEO
Switch your active WordPress theme: DONE, NO CHANGE
Disable any potential security/ad blocker or firewall software: DON’T HAVE ANY.
Install Site Kit with an incognito window: DONE
Use a different computer to set up Site Kit: DON’T HAVE ANOTHER COMPUTER
Ensure that your environment fulfill all minimum requirements: PHP version 7.1 WordPress version 5.2.4
Webhost: Hostgator

After deactivating the above plugins, I deactivated and deleted Site Kit. Then re-Installed Site Kit with an incognito window. I reconnected all Google products and everything was working correctly. I then re-activated all the plugins and closed the incognito window. I then logged back into my admin panel from Chrome and everything was working correctly. I just hope it is tomorrow. It worked great last night when I logged off.
 
11/5/19 6:00 PM

Also, my fears were correct. Site Kits is back to the same state again this afternoon. It says “The Site Kit plugin is active but requires setup”. It was working fine last night.

I would greatly appreciate any assistance you could give me.

## Additional Context

 - PHP Version: 7.1
 - OS: [e.g. iOS] Windows 7
 - Browser [e.g. chrome, safari] Chrome
 - Plugin Version [e.g. 22]1.0.1
 - Device: [e.g. iPhone6] Desktop - HP Pavilion

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by ThierryA** [comment] 2019-11-07 09:53
@dspurlock as mentioned on [this thread](https://wordpress.org/support/topic/site-kit-plugin-is-active-but-requires-setup-2/), our support team typically respond within 24 – 48 hours during working days, please bare with us. Rest assured that we are actively investigating your issue.

We will provide more details asap on [your original support request](https://wordpress.org/support/topic/site-kit-plugin-is-active-but-requires-setup/).

Closing this as it is a duplicate of two existing thread.

**Closed by ThierryA** 2019-11-07 09:53 UTC
Labels: Type: Support
