### ISSUE TITLE
Consider using bundlesize as a "check"

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1084] opened 2020-01-30 14:29 UTC
## Feature Description

We currently run [`bundlesize`](https://github.com/siddharthkp/bundlesize) to ensure webpack-built bundles are within reasonable sizes during our JS Tests that run on Travis.

This works fine as a pass/fail but is currently implemented as a pass/fail as part of the Travis build as a whole. The executable also supports a closer integration with GitHub by [integrating as a check](https://github.com/siddharthkp/bundlesize#2-build-status) that runs on all PRs. This could be required to pass or not for merging separately from the Travis build it runs on.

The main benefit seems to be that it makes bundle size changes introduced by a PR more visible

Example from the readme:
![](https://camo.githubusercontent.com/d3906ea9d5a3dcfd57d1d9ea4b87dc799910fd03/68747470733a2f2f63646e2e7261776769742e636f6d2f7369646468617274686b702f62756e646c6573697a652f6d61737465722f6172742f7374617475732e706e67) 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment] 2021-02-16 18:18
This is a duplicate of #2539. In fact, #2539 is a duplicate of this, but since that one has a PR for it and discussions, let's close this and keep working on this issue in #2539.

**Closed by tofumatt** 2021-02-16 18:18 UTC
Labels: Type: Enhancement
