### ISSUE TITLE
Allow changing Analytics view name when creating a new view

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#716] opened 2019-10-25 18:28 UTC
## Bug Description

Analytics new view creation duplicates default “All Web Site Data” view. No indication that the view was created, that the user needs to modify the view, or where to do it (on Analytics platform). Also referenced in #522 .

## Steps to reproduce

1. Go to the Analytics Module
2. Click on the View dropdown and select _Setup a new view_
3. Click on the button _Confirm Changes_
4. After the page refreshes, the new view named “All Website Data” is selected, which is the same as the default view in Analytics.
5. Navigating to the Analytics account, one gets a notification that there are “Redundant Views”

## Screenshots

**Duplicate All Website Data View in Site Kit**

![Duplicate All Website Data View in Site Kit](https://user-images.githubusercontent.com/8108643/67594652-ad955980-f719-11e9-8757-2758a65efc69.png)

**Duplicate All Website Data View in Google Analytics** 

![Duplicate All Web Site Data View in Analytics](https://user-images.githubusercontent.com/8108643/67594774-ef260480-f719-11e9-9cb9-b4cc98b984de.png)

**Redundant View Notification in Google Analytics** 

![Redundant View Notification in GA](https://user-images.githubusercontent.com/8108643/67594852-17156800-f71a-11e9-96cb-b4bca8e1250d.png)

## Additional Context

 - PHP Version: 7.1.30
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version:  1.0.0-rc.1.1
 - Device: MacBook Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

If the user selects "Setup a new view": 
* display a field below the dropdown boxes where they can name the new view something different than the default ("All website data")
* display a message "You can make changes to this view (e.g. exclude URL query parameters) in Google Analytics.", without a link. 

Once the user creates the new view and saves it by clicking "configure analytics":
* in the Settings section display the same text ("You can make changes to this view (e.g. exclude URL query parameters) in Google Analytics.") and a deep link to the relevant part of GA FE where they can make more changes to the specific view (link would be in the format `https://analytics.google.com/analytics/web/?authuser={email}#/a[accountID]w[webPropertyID]p[profileID]/admin/view/settings`)

## Implementation Brief

* When the "Set up a new view" option is chosen during module set up or settings edit, render an additional text input for the new view name (likely right below the dropdown), which defaults to "All Web Site Data"
    - The state for the input should be stored in the `core/forms` datastore under the `analyticsSetup` or `analyticsSettings` formID depending on the context and passed through to the `create-profile` request in the `submitChanges` action which handles the form submit for both set up and settings.
    - ~~Validate the view name to meet naming requirements~~  
    [There don't appear to be any restrictions on view names](https://user-images.githubusercontent.com/1621608/83510586-eaa6a300-a4d5-11ea-9a44-8c571b34b897.png)
    - Display a warning notice if the name matches an existing view of the selected property  
    Look into using `leadingIcon` and `helperText` props on `TextField` conditionally for this ([reference](https://github.com/material-components/material-components-web-react/blob/master/packages/text-field/README.md))
    _Don't prevent the user from creating a new view with the same name if they want to_
    - Add a descriptive message (text only) below the input:  
    _You can make changes to this view (e.g. exclude URL query parameters) in Google Analytics_
    - Add a link to the view edit screen in Analytics to the `SettingsView` component
        - href `https://analytics.google.com/analytics/web/?authuser={email}#/a[accountID]w[webPropertyID]p[profileID]/admin/view/settings`  
        where `email` is the value of `select( 'core/user' ).getEmail()`
        - text "You can make changes to this view (e.g. exclude URL query parameters) in Google Analytics"
* Update `POST:create-profile` to take a new optional `name` parameter to override the default if provided

## Changelog entry

* Allow specifying Analytics view name when creating a new one, and display a deep link to modify view settings in Analytics module settings.

**Comment by felixarntz** [comment] 2019-10-28 23:34
@marrrmarrr Any idea how we can prevent (or at least guide away) the user from doing this?

It's expected in the current plugin behavior that this theoretically is possible, but as pointed out, it might not make sense if you just set up a duplicate identical profile. I'm not even sure we can determine that, but let's think about it.

**Comment by felixarntz** [comment] 2020-01-16 11:27
@aaemnnosttv The IB doesn't include the part about adding a message (with link if possible) to the relevant area in GA.

> Extend the same behavior for creating a new property

I'm not sure I understand this part, there should not be an input field to name a new property - it only applies to a new profile.

**Comment by felixarntz** [comment] 2020-01-17 10:22
IB ✅ 

@aaemnnosttv Note that the link should only be displayed if actually valid, based on the currently selected values. For example, if a dropdown is set to "Select..." or "Setup new...", there should be no link because there's no ID to include.

**Comment by aaemnnosttv** [comment] 2020-02-05 16:53
Moving this back as it now dependent on #1101

**Comment by tofumatt** [comment] 2020-05-01 14:45
Now that the analytics refactoring is complete, I think this IB can be revisited and confirmed/updated to work with the new analytics code. Note that it may need to be entirely replaced from the JS side as the JS code here is totally new.

After that it can be moved to IB review. Feel free to adjust the estimate and entire IB if needed. 😄

**Comment by aaemnnosttv** [comment] 2020-06-02 10:52
IB updated!

**Comment by tofumatt** [comment] 2020-06-02 12:31
IB sounds good to me, IB ✅

**Comment by cole10up** [comment] 2020-06-24 06:58
**Tested**

Installed latest develop SK, setup Analytics module. Navigating to setup and selecting 'New View'

Notice:
![image](https://user-images.githubusercontent.com/57115907/85510383-19cba400-b5ac-11ea-824b-262ce9f5f82e.png)

Clicking confirm prompts:
![image](https://user-images.githubusercontent.com/57115907/85510452-3071fb00-b5ac-11ea-9878-b3c011230897.png)

Ran through confirmation which landed me here:
![image](https://user-images.githubusercontent.com/57115907/85510519-4f708d00-b5ac-11ea-906e-ff19111aa824.png)

I added 2 'a's to my View name and selected confirm

Notice:
![image](https://user-images.githubusercontent.com/57115907/85510588-6d3df200-b5ac-11ea-9752-2d91fbeaad52.png)

![image](https://user-images.githubusercontent.com/57115907/85510614-76c75a00-b5ac-11ea-8941-7238dbeb484f.png)

Confirmed user can adjust and select the new view and prior default 'All Website Data'

One thing to note for consistency's sake. 

Setting up a new account we use the term 'All website traffic' for the View

![image](https://user-images.githubusercontent.com/57115907/85510990-f81eec80-b5ac-11ea-8e7b-90a047f4c9e7.png)

Adjusting in settings defaults to 'All Web Site Data'

![image](https://user-images.githubusercontent.com/57115907/85511086-12f16100-b5ad-11ea-9e8c-2438a5f2ad65.png)

Sending this back to @eugene-manuilov for an adjustment. 

Suggesting we choose either 'All Web Site Data' or 'All website traffic' for consistency's sake.

**Comment by aaemnnosttv** [comment] 2020-06-24 07:24
Good catch @cole10up -

In this case I think we should change the default used by the account provisioning screen as the default name for a new view is consistent with what is in place here:
![image](https://user-images.githubusercontent.com/1621608/85514173-6fcc3600-b604-11ea-829d-6cee0a4ba999.png)

@marrrmarrr is it okay for us to change the default view name used on the new Analytics create account screen to "All Web Site Data" instead of "All website traffic"?

**Comment by felixarntz** [comment] 2020-06-24 14:50
@aaemnnosttv Just talked to @marrrmarrr, let's make the change.

**Comment by aaemnnosttv** [comment] 2020-06-24 15:11
@felixarntz just to clarify, we're changing the default used in the account creation form, correct?

**Comment by felixarntz** [comment] 2020-06-24 15:36
@aaemnnosttv Yep 👍

**Comment by cole10up** [comment] 2020-06-30 06:51
**Retested**

Confirmed the use of 'All Website Data' is now being displayed on the account provisioning screen

![image](https://user-images.githubusercontent.com/57115907/86093048-37dd4c80-ba63-11ea-87a7-fd2a41bcdc43.png)

Ran a series of regression tests removing Analytics module, trying to setup module with the same view name (warning message displayed).

![image](https://user-images.githubusercontent.com/57115907/86093193-65c29100-ba63-11ea-897d-a26892c812d2.png)

Passed QA ✅

**Comment by aaemnnosttv** [comment] 2020-06-30 13:53
I just ran into an error with this locally due to undefined `profiles`. Sending this back to execution for a quick follow-up fix.

<details>
<summary>Error</summary>

```
Site Kit encountered an error
Cannot read property 'some' of undefined


    in ProfileNameTextField
    in div
    in div
    in SettingsForm
    in div
    in SettingsEdit
    in SettingsMain
    in InnerComponent (created by WithFilters(ModuleSettingsDetails))
    in WithFilters(ModuleSettingsDetails)
    in div
    in div
    in div
    in div
    in div
    in SettingsModule
    in div
    in Layout
    in div
    in SettingsModules
    in div
    in div
    in div
    in SettingsApp
    in RestoreSnapshots
    in ErrorHandler
    in Root
```

</details>

**Comment by cole10up** [comment] 2020-07-02 07:31
**Tested**

Ran a series of regression tests with latest Develop focusing on new Analytics account creation, adjusting view names, proxy setup, uninstalling and reinstalling the module.

No issues on my end

Passed QA ✅

**Closed** 2020-07-07 21:39 UTC
Labels: Good First Issue, P1, Type: Enhancement
