### ISSUE TITLE
Create the entry point `Key_Metrics` and `Key_Metrics_Settings` classes

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6308] opened 2022-12-09 13:54 UTC
## Feature Description

A new `Key_Metrics` class, within a new namespace `Google\Site_Kit\Core\Key_Metrics` will serve as the entry point to the Key Metrics feature. In preparation for the interface for managing user-selected Key Metrics and the "Show/Hide Widget" admin settings toggle, we need a new class for managing the value like we have for other settings and options.

The architecture and purpose of the new classes created can be similar to the existing `Dismissals` (`Key_Metrics`), `Dismissed_Items` (`Key_Metrics_Settings`) and `REST_Dismissals_Controller` (`REST_Key_Metrics_Controller`) classes.

Relevant design doc sections: 
[`Key_Metrics` PHP Classes](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.rakn1j3j4oqp)
[User Selection of Metrics](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.vhwfv6130t0d)
[Admin Settings Toggle](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#heading=h.sqot9tnmfnyx)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `Key_Metrics` class, within a new namespace `Google\Site_Kit\Core\Key_Metrics`, should be created to serve as an entry point to the Key Metrics feature.
* A new `Key_Metrics_Settings` class which extends `User_Setting` should be created to store user-selected metrics and the toggle to denote if the
  * The option name it manages should be `googlesitekit_key_metrics_settings`
  * The default value should be an empty array
  * The type it is registered with should be `object`
  * Its `sanitize_callback` should enforce the following structure:  
    ```
    {
        widgetSlugs: [],    // array of strings
        isWidgetHidden: true | false    // boolean
    }
    ```

## Implementation Brief

- In `includes/Core`, create a new folder named `Key_Metrics`. In this folder:
    - Namespace for all classes created in this folder should be `Google\Site_Kit\Core\Key_Metrics`.
    - Create a new file named `Key_Metrics_Settings.php`. In this file:
        - Create a new class matching the file name, extending the `Google\Site_Kit\Core\Storage\User_Setting` class. In this class:
            - In order to constitute this class, the contents of `Google\Site_Kit\Core\User_Input\User_Specific_Answers` can be used as an example.
            - Create an `OPTION` constant with the value as mentioned in the ACs as option name (currently `googlesitekit_key_metrics_settings`).
            - Create a `get_type()` protected method that should return the string `object`.
            - Create a `get_default()` protected method that should return an empty array.
            - Create a `get_sanitize_callback()` protected method that should return a function having `$settings` as its parameter. This `$settings` parameter will contain the input data that is intended to be saved into this user setting. Use this function to sanitize the input data so that it is saved in a structure as shown in the ACs.
    - Create a new file named `Key_Metrics.php`. In this file:
	    - Create a new class matching the file name. In this class:
            - Create a protected property named `$key_metrics_settings` with assigning no value yet. This will eventually hold an instance of the new `Google\Site_Kit\Core\Key_Metrics\Key_Metrics_Settings` class created above.
            - Make the class constructor accept the following parameters:
                - `$context`: An instance of `Google\Site_Kit\Context`.
                - `$user_options`: An instance of `Google\Site_Kit\Core\Storage\User_Options`.
            - In the class constructor, assign a new instance of `Google\Site_Kit\Core\Key_Metrics\Key_Metrics_Settings` to the `$key_metrics_settings` property. Pass `$user_options` to it if available, otherwise create a new instance of `Google\Site_Kit\Core\Storage\User_Options` passing `$context` to it.
            - Create a new `register()` public method that should in turn call the `register()` method of the `$key_metrics_settings` property.
- In `includes/Core/Authentication/Authentication.php`:
    - Create a private property named `$key_metrics` with assigning no value yet. This will eventually hold an instance of the new `Google\Site_Kit\Core\Key_Metrics\Key_Metrics` class created above.
    - In the class constructor, assign a new instance of `Google\Site_Kit\Core\Key_Metrics\Key_Metrics` to the `$key_metrics` property. Pass the `$context` variable and the `$user_options` property to it.
    - In the `register()` method, call the `register()` method of the `$key_metrics` property.

### Test Coverage

- In `tests/phpunit/integration/Core`, create a new folder `Key_Metrics` that should contain a new file `Key_Metrics_SettingsTest.php`. In this file, add test case(s) for the `Google\Site_Kit\Core\Key_Metrics\Key_Metrics_Settings` class' `get_sanitize_callback()` method. As an example, `tests/phpunit/integration/Core/User_Input/User_Specific_AnswersTest.php` can be used.

## QA Brief

* This issue has no UI changes - hence, a simple smoke test of the plugin (and checking for any errors/console errors) should be enough.

### QA:Eng

* Another code review to ensure the ACs are met would be helpful.

## Changelog entry

* N/A

**Comment by tofumatt** [comment] 2022-12-14 20:35
ACs are good here 👍🏻

**Comment by tofumatt** [comment] 2022-12-19 21:07
IB ✅

**Comment by jimmymadon** [comment] 2023-01-06 16:45
>- In `includes/Core/Authentication/Authentication.php`:
    - Create a private property named `$key_metrics` with assigning no value yet. This will eventually hold an instance of the new `Google\Site_Kit\Core\Key_Metrics\Key_Metrics` class created above.
    - In the class constructor, assign a new instance of `Google\Site_Kit\Core\Key_Metrics\Key_Metrics` to the `$key_metrics` property. Pass the `$context` variable and the `$user_options` property to it.
    - In the `register()` method, call the `register()` method of the `$key_metrics` property.

@nfmohit @tofumatt Any specific reason why the `Key_Metrics` entry point class should be registered within `Authentication`? Don't we generally register all entry point classes in `includes/Plugin.php`'s `register()` method? I'll proceed adding it to `Plugin` for now as it is just a one liner and can change if necessary in CR. 🙂

**Comment by nfmohit** [comment] 2023-01-08 17:21
> @nfmohit Any specific reason why the `Key_Metrics` entry point class should be registered within `Authentication`?

I think it is absolutely fine to register in `Plugin`. I was following the pattern of the `User_Input` class here which is registered in `Authentication`, but I believe that should also be moved to `Plugin` at this point. Thank you for checking, @jimmymadon!

**Comment by wpdarren** [comment] 2023-01-18 01:19
@jimmymadon I'm taking a look at the QAB. For the smoke test, I am assuming we should focus this on the widgets and data on the main and entity dashboard, plus check the view only dashboard too.  

Is there anything else we should focus our smoke testing on?

**Comment by wpdarren** [comment] 2023-01-20 13:28
### QA Update: ✅ 

**Verified:**

- Ran through smoke testing on:

  - Set up Site Kit and Analytics. 
  - Checked widgets on main and entity dashboard for zero and gathering states.
  - Checked widgets on main and entity dashboard with live data. 
  - Checked widgets on main and entity view only dashboard. 

All looks good, no regressions found or any new warning/error console messages.

**Comment by nfmohit** [comment] 2023-01-23 20:08
### QA:Eng Update: ✅

> Another code review to ensure the ACs are met would be helpful.

LGTM 👍

**Comment by felixarntz** [comment] 2023-01-27 20:09
## Approval ⚠️ 

@jimmymadon @nfmohit Cross-posting https://github.com/google/site-kit-wp/issues/6256#issuecomment-1407023445 here, since it in a way also ties to this issue. Let's discuss in that issue how we want to best address that.

Leaving this one open for now until we have a resolution.

**Comment by nfmohit** [comment] 2023-01-27 21:04
Very valid point and an excellent catch, thank you @felixarntz! Eugene was very kind to update the follow-up PR #6486 of #6256 to conditionally instantiate the `Key_Metrics` class when the `userInput` feature flag is enabled.

Approach duly noted for future features behind a feature flag, thanks!

**Comment by felixarntz** [comment] 2023-01-27 21:30
Thanks @nfmohit! Closing this issue since #6486 will address the problem.

**Closed by felixarntz** 2023-01-27 21:30 UTC
Labels: P1, Type: Enhancement, QA: Eng, PHP
