### ISSUE TITLE
Prevent permissions modal and feature tour from displaying at the same time

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6941] opened 2023-04-20 14:28 UTC
## Bug Description

As reported by @jamesozzie in Bug Bash:

If there happens to be a permissions scope missing at the same time as the feature tour, the CTA's within the feature tour (close or next) can't be actioned, nor can the CTAs related to the permissions be clicked on. The only way out is to refresh the page and quickly grant permissions before the feature tour appears. 

See recording of this behavior below:
https://recordit.co/UVYGpXprbH

![image](https://user-images.githubusercontent.com/12189958/233397435-e7dde15a-fbf0-4b57-ac99-1abddf3c9e9e.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2023-11-08 22:04
Duplicate of #6266

**Closed by aaemnnosttv** 2023-11-08 22:04 UTC
Labels: Type: Bug, P1
