### ISSUE TITLE
Use a separate application name when WordPress multisite is used

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3118] opened 2021-04-08 17:20 UTC
When making requests to the authentication service, the `application_name` request parameter is passed. If the site's environment is using WordPress multisite, an alternate identifier should be used.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When using WordPress multisite, the application name prefix that is sent should be "wordpress-multisite/google-site-kit" instead of "wordpress/google-site-kit".
* A new method `get_platform` should be introduced for that purpose in the same class, which should return only the "application name prefix" referred to above. Essentially, `get_application_name` should then return `get_platform()` followed by a slash and `GOOGLESITEKIT_VERSION`.

**This requires changes on the Site Kit authentication service, which are being worked on. Before merging this, please confirm with @felixarntz.**

## Implementation Brief

* edit `includes/Core/authentication/Google_Proxy.php`
* create a new method `get_platform` which uses the [is_multisite](https://developer.wordpress.org/reference/functions/is_multisite/) function to determine when multisite is in use and returns  `wordpress` or `wordpress-multisite` accordingly
* modify the `get_application_name` method to use the new 'get_platform' method
* modify the `get_features` method to use the new 'get_platform` method

### Test Coverage

* update `test/phpunit/integration/Core/Authentication/Google_Proxytest.php` to test this change

### Visual Regression Changes

* N/A

## QA Brief

* Use a WordPress multisite installation.
* Install and activate Site Kit for a single site within that installation.
* Go through the plugin setup flow and verify it can be completed as usual.

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment] 2021-04-28 08:58
> modify the `get_features` method to use the [is_multisite](https://developer.wordpress.org/reference/functions/is_multisite/) function to determine when multisite is in use and set the `platform` to `wordpress/google-site-kit` or `wordpress-multisite/google-site-kit` accordingly

@Hazlitte the `application_name` is returned from `Google_Proxy::get_application_name` so this should be the only place where the change is needed to the name specifically.

Regarding the reference in `get_features`, I think this should use the same `get_application_name` method for the platform instead of the hardcoded string we have now, although this would include the version as well.
@felixarntz is this okay? I would imagine this was probably how it was intended to be done initially and perhaps overlooked.

**Comment by felixarntz** [comment] 2021-04-28 18:14
@aaemnnosttv Yes, the application name effectively _is_ platform plus version. So maybe we should introduce private `get_platform` and `get_version` methods and rely on those in both `get_application_name` and `get_features`.

**Comment by aaemnnosttv** [comment] 2021-04-29 14:39
@felixarntz re: `get_version` it seems unnecessary to create a method to return a constant unless we were implementing an interface or something that other platforms would use. Maybe a `Core\Platform` class would be better to create at some point than putting all of this on the proxy class. For now I think a single `get_platform` method would be fine which would simply return `wordpress` or `wordpress-multisite` for now. Then the composite strings can be assembled in their respective methods. How does that sound?

**Comment by felixarntz** [comment] 2021-04-29 17:19
@aaemnnosttv Sounds good, updated the ACs.

@Hazlitte Can you update the IB based on the above feedback and updated requirements?

**Comment by aaemnnosttv** [comment] 2021-05-04 09:43
@Hazlitte while not explicitly required by the ACs, let's also update `Google_Proxy::get_features` to use the new method as well. See https://github.com/google/site-kit-wp/issues/3118#issuecomment-828282400 https://github.com/google/site-kit-wp/issues/3118#issuecomment-828672507

Otherwise, the IB looks good, let's just update it to include this extra change.

**Comment by aaemnnosttv** [comment] 2021-05-04 10:11
IB ✅

**Comment by eugene-manuilov** [comment] 2021-06-07 14:28
> This requires changes on the Site Kit authentication service, which are being worked on. Before merging this, please confirm with @felixarntz.

@felixarntz #3487 has been approved but not merged yet. I assign this ticket to you to merge it when the SK authentication service is ready.

**Comment by felixarntz** [comment] 2021-06-29 15:58
The service-side enhancement will soon be deployed, so that we can merge this for 1.37.0.

**Comment by wpdarren** [comment] 2021-07-14 14:54
### QA Update: ✅ 

**Verified:**

- Using a WordPress multisite installation, I was able to install and activate Site Kit for a single site within a network. Not only did I go through the set up flow but also activated all of the modules.

**Closed** 2021-07-15 19:12 UTC
Labels: P1, Rollover, Type: Infrastructure
