### ISSUE TITLE
Add missing survey trigger to the unified dashboard

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#4786] opened 2022-02-03 20:27 UTC
The `DashboardMainApp` component used in the unified dashboard is missing the survey trigger logic for the `view_dashboard` trigger ID. That is a critical problem since it means no surveys related to viewing the dashboard are being triggered in the unified dashboard.

We have to take over the existing functionality from the current/legacy dashboard here.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `view_dashboard` survey trigger should be executed in the unified dashboard as well (similar to the old dashboard, with TTL of 1 hour).

## Implementation Brief

* Copy the usage of `SurveyViewTrigger` from `DashboardApp` into [`DashboardMainApp`](https://github.com/google/site-kit-wp/blob/1bc57c4c6d14779952f356746999a75cfbb76e12/assets/js/components/DashboardMainApp.js).
https://github.com/google/site-kit-wp/blob/1bc57c4c6d14779952f356746999a75cfbb76e12/assets/js/components/dashboard/DashboardApp.js#L50

### Test Coverage

* No new tests needed.

## QA Brief

* Create a new site.
* Enable the `unifiedDashboard` feature flag.
* Go to the unified dashboard page and verify that you can see surveys triggered there.

## Changelog entry

* N/A

**Comment by felixarntz** [comment] 2022-02-03 21:52
@eclarke1 @FlicHollis This is the new (small) issue we need to get into 1.68.0 related to https://10up.slack.com/archives/CFFRMC5DE/p1643919858115499.

**Comment by FlicHollis** [comment] 2022-02-08 09:15
No problem, thanks @felixarntz

**Comment by eugene-manuilov** [comment] 2022-02-08 12:06
IB ✔️

**Comment by wpdarren** [comment] 2022-02-09 10:16
### QA Update: ⚠️ 

@eugene-manuilov @jimmymadon the only survey I can think of that would be triggered on the unified dashboard is the Idea hub one.  For this to be triggered we have activated Idea Hub at least 2 days ago. Since we don't have 2 days to QA this ticket, can you think of any way to trigger it straightaway?  🤔

**Comment by wpdarren** [comment] 2022-02-09 12:57
@eugene-manuilov @jimmymadon I have set up a test for this and will check back on Friday afternoon to see if the survey is triggered.  Initially, I wondered if there's a quicker way to generate it but doesn't appear to be one. 👍

**Comment by wpdarren** [comment] 2022-02-09 17:52
@eugene-manuilov I have assigned this to you and tagged it `QA:Eng` as per the engineering call.

**Comment by aaemnnosttv** [comment] 2022-02-09 18:04
Thanks @wpdarren – I can confirm the trigger request is firing as expected. The request is timing out for me, but I believe this is a known issue on the service.

![image](https://user-images.githubusercontent.com/1621608/153262371-269af5c5-9a1e-4011-954b-aecfae8d745b.png)

**Comment by wpdarren** [comment] 2022-02-11 04:10
### QA Update: ✅ 

- Verified that the survey appeared on Unified dashboard using the plugin. 

@eugene-manuilov thank you! 👍 

![image](https://user-images.githubusercontent.com/73545194/153536289-9e02a542-3cb7-45ba-9aae-5d5bcedf33f8.png)

**Closed** 2022-02-14 20:28 UTC
Labels: Type: Bug, P0, QA: Eng, Good First Issue
