### ISSUE TITLE
Analytics: GA accounts with no existing property /  InternalWebPropertyID notice

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#398] opened 2019-08-13 14:42 UTC
## Bug Description

In some cases users might have already setup an Analytics account but they have no properties set (or maybe they have deleted all properties). 

Rather than ask users to access Analytics to create a property there should be an option in the property dropdown to "Setup a new property" (just as there is for accounts with existing properties).

A couple of other suggestions for this flow:
- Remove the loading effect from the property and view dropdowns
- If there is no dropdown to create a new property provide a link to Analytics
- Grey out or restrict the "Configure Analytics" button if it's not possible to proceed. At present clicking on that button results in a visible "InternalWebPropertyID" notice.

## Steps to reproduce

1. Setup new Analytics account
2. Don't create any property in this Analytics account (or delete any existing properties)
3. Setup Site Kit & Analytics module
4. See error as described in screenshot below

## Screenshots

![ICoRlwAoem](https://user-images.githubusercontent.com/41326532/62950311-ada2e000-bddf-11e9-925d-3faae39eb7d9.gif)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* In Analytics setup / settings, if a user has an Analytics account but no properties in that account, ...
    * the user should not see a warning about a missing parameter
    * the user should see the property and profile dropdowns as usual, with the property dropdown only containing the option to "Setup a new property".

## Implementation Brief

In `\Google\Site_Kit\Modules\Analytics`

* In `GET get-properties` datapoint, don't return a `WP_Error` if empty/none, instead return `$response` early
* In `GET get-profiles` datapoint, don't return a `WP_Error` if empty/none, instead return `$response` early

## Changelog entry

* Fix infinite loading state when selecting an Analytics account without any existing properties.

**Comment by felixarntz** [comment] 2019-08-28 13:15
@aaemnnosttv I don't think the IB here solves the issue, for similar reasons as outlined in #346 for Tag Manager.

It is counter-productive to return an error from the server just because there are no properties (e.g. WordPress doesn't return an error just because there are no posts). `properties` should be an empty array in that case (and `profiles` too of course). Here in this scenario, I believe the error message about no properties being found can be entirely removed, since we'd just show the "Setup new Property" option then.

**Comment by felixarntz** [comment] 2019-08-30 09:05
IB ✅

**Comment by adamsilverstein** [comment] 2019-10-09 14:23
This ticket did not pass QA, moving back to "To Do".

### Testing procedure

* Create an Analytics account with no properties (when I created my account I had to add a property during the setup flow, I then deleted the property). 
* Activating and setting up Analytics module, and select the new account.

**Verify** property dropdown only shows 1 option “Setup a new property”, view dropdown contains only “Setup a new view”. This works correctly.

* Click on Configure Analytics

**FAILED** I see an error message, then another error message when clicking again. 

Screencast: https://share.getcloudapp.com/yAu44Lv6

Two errors are shown:
First click: 
**Error: Request parameter is empty: propertyId.**

Second and subsequent clicks:
**Request parameter is empty: internalWebPropertyId.**

**Comment by adamsilverstein** [comment] 2019-10-10 16:20
This passes QA, moving to Approval.  testing procedure [above](https://github.com/google/site-kit-wp/issues/398#issuecomment-540024321).

**Comment by marrrmarrr** [comment] 2019-10-10 18:00
Confirmed this works as intended on a brand new site with a GA account where I deleted the property before going through GA module setup in the plugin. 

![GA-new-property](https://user-images.githubusercontent.com/13304791/66594077-a35f5100-eb98-11e9-92e7-c85ee3d38d71.png)

**Closed** 2019-10-11 09:19 UTC
Labels: P1, Size: XXS, Sprint: 8, Type: Bug
