### ISSUE TITLE
Help icon needs circular mouse hover 

### ISSUE THREAD

**Issue by Pratheep-lab** [google/site-kit-wp#3058] opened 2021-03-31 14:43 UTC
The help icon that is yet to be launched has a rectangular mouse hover. This needs to be changed to a circular mouse hover. 

**Current:** 
![image](https://user-images.githubusercontent.com/81642523/113162656-6331d980-9237-11eb-9612-dc9d240d6a74.png)

**The shape of the grey mouse hover has to look like this:**
![image](https://user-images.githubusercontent.com/81642523/113162870-8e1c2d80-9237-11eb-857f-06c02d2a5925.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The background for the global help icon (behind `helpVisibility` feature flag) that is shown e.g. when hovering, clicking etc. should be circular instead of rectangular (see screenshots above).

## Implementation Brief
* Using `assets/sass/components/global/_googlesitekit-help-menu-link.scss`,
	* Add new styles for the `.googlesitekit-help-menu` class name, targeting the following class names:
		* `.mdc-button--dropdown`
			* Set the `border-radius` to `50%`
			* Set the `min-width` to `36px`
			* Set the `padding` to `0`
* Using `assets/sass/components/global/_googlesitekit-header.scss`,
	* Add the `.googlesitekit-dropdown-menu + .googlesitekit-dropdown-menu` selector and set the `margin-left` to `24px`. Instead of adding `margin-right` to the `.googlesitekit-dropdown-menu` element, we are adding `margin-left` to the adjacent element so that the dropdown menu for the help icon is aligned with the button.
	* Update the `.googlesitekit-date-range-selector` class to remove the `margin-right`.
* The help icon looks slightly smaller than the calendar icon next to it because the dimension of the path within the help icon is `16px` whereas it should  have been `20px`. To fix that, update `assets/svg/help.svg` with the following SVG:
	```js
	<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
		<path d="M9 16H11V14H9V16ZM10 0C4.48 0 0 4.48 0 10C0 15.52 4.48 20 10 20C15.52 20 20 15.52 20 10C20 4.48 15.52 0 10 0ZM10 18C5.59 18 2 14.41 2 10C2 5.59 5.59 2 10 2C14.41 2 18 5.59 18 10C18 14.41 14.41 18 10 18ZM10 4C7.79 4 6 5.79 6 8H8C8 6.9 8.9 6 10 6C11.1 6 12 6.9 12 8C12 10 9 9.75 9 13H11C11 10.75 14 10.5 14 8C14 5.79 12.21 4 10 4Z" fill="currentColor"/>
	</svg>
	```

### Test Coverage
* N/A

### Visual Regression Changes
* The help icon in the header will be slightly bigger, having the same height as the calendar icon next to it.

## QA Brief

View SiteKit dashboard
Observe header is like above screenshot but has fixes:
* circular hover on help icon
* even spacing between menu items

## Changelog entry

* Improve styling for Site Kit header, especially on mobile devices.

**Comment by aaemnnosttv** [comment] 2021-04-07 09:44
> * `+ .googlesitekit-date-range-selector`
			* Set the `margin-left` to `24px`. Instead of adding `margin-right` to the `.googlesitekit-help-menu` element, we are adding `margin-left` to the adjacent element so that the dropdown menu for the help icon is aligned with the button.

@asvinb this part goes beyond the ACs but it looks like a good change to make for consistency (cc @felixarntz)

If we make this change, we should probably apply this style to `.googlesitekit-dropdown-menu + .googlesitekit-dropdown-menu` (in the header specifically) rather than only to the date range selector since I think this is something we will want for all adjacent dropdowns here. That way we can get rid of this special margin too 
![image](https://user-images.githubusercontent.com/1621608/113845539-4e58c700-979e-11eb-8d4f-a28a21c449b0.png)

> The help icon looks slightly smaller than the calendar icon next to it because the dimension of the path within the help icon is `16px` whereas it should  have been `20px`. To fix that, update `assets/svg/help.svg` with the following SVG:

I don't think this is necessary as the icon is being output at 20px 
![image](https://user-images.githubusercontent.com/1621608/113845650-6892a500-979e-11eb-8b48-f25f52ba7f71.png)
https://github.com/google/site-kit-wp/blob/ebf9df2049f4b8cbceaabfa48286b8ad522b3efa/assets/js/components/help/HelpMenu.js#L79
Also, as an aside the proposed svg has a hardcoded path fill, whereas the current one uses `currentColor` which we should always use for icons.

**Comment by asvinb** [comment] 2021-04-08 11:31
@aaemnnosttv IB updated to cater for the margin for adjacent drop downs. For the icon, check screenshot below:
![image](https://user-images.githubusercontent.com/31818/114019305-491f7900-987f-11eb-8e74-970b3b795b4e.png)
Notice that the icons are not aligned, even though both have the same height. This is because there is some extra whitespace around the help icon and the actual path height is `16px`. So the new SVG does not have the whitespace around and the path height is set to `20px`.

**Comment by aaemnnosttv** [comment] 2021-04-13 08:44
> This is because there is some extra whitespace around the help icon and the actual path height is `16px`. So the new SVG does not have the whitespace around and the path height is set to `20px`.

Thanks for clarifying @asvinb.

IB ✅

**Comment by tofumatt** [comment] 2021-04-15 00:36
Assigning @asvinb and @Pratheep-lab to get your thoughts on my comment in the PR: https://github.com/google/site-kit-wp/issues/3058#issuecomment-814773079

Looks like the IB here might cause some regressions, so we should take the bits about margin out or we should tweak them to work better on mobile.

**Comment by asvinb** [comment] 2021-04-15 11:13
@tofumatt I just updated the PR where I reduced the margin on small screens. Can you check again?

Thanks!

**Comment by tofumatt** [comment] 2021-04-15 20:05
I'm assigning this back to you @asvinb because you worked on the IB and the tweaks to the PR, but let me know if you can't get to it and feel free to reassign this 😅

**Comment by asvinb** [comment] 2021-04-16 07:32
@tofumatt I replied to you here: https://github.com/google/site-kit-wp/pull/3143#issuecomment-820978323 Basically in Storybook we have extra padding on the sides which is causing the content area to shrink :)

**Comment by wpdarren** [comment] 2021-04-20 13:23
### QA Update: Pass ✅ 

**Verified:**

- The help icon has a circular hover. This was tested on desktop and various smaller screen sizes on mobile and tablet.  - [Desktop](https://user-images.githubusercontent.com/73545194/115402325-3b54e680-a1e3-11eb-8825-89a6b6130f81.png) and [Mobile](https://user-images.githubusercontent.com/73545194/115402682-8a028080-a1e3-11eb-95f6-7713640eaffc.png)

- There is an even spacing between menu items, help icon and date range selector.  This was tested on desktop and various smaller screen sizes on mobile and tablet.

**Closed** 2021-04-26 17:37 UTC
Labels: Good First Issue, P0, Type: Enhancement
