### ISSUE TITLE
Remove periods from Analytics settings view

### ISSUE THREAD

**Issue by ryanwelcher** [google/site-kit-wp#1401] opened 2020-04-17 17:08 UTC
## Feature Description
Remove any periods in sentences that appear in the Analytics settings panel. 

Related: #585

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Single sentences in module settings view copy should not end in periods (e.g. "IP addresses are being anonymized" instead of "IP addresses are being anonymized.").

## Implementation Brief

* Merge #1311 (see https://github.com/google/site-kit-wp/pull/1311/files#diff-8e1553529a35b86ebd04230dcc7940cdR97).

## QA Brief

* 

## Changelog entry

* Remove periods from single sentences in settings panel lists.

**Comment by aaemnnosttv** [comment] 2020-04-17 17:24
This is already the case with the upcoming changes (at least the settings view).

![image](https://user-images.githubusercontent.com/1621608/79596499-5df08300-80e9-11ea-80b9-e23aab0cd4a0.png)

The settings edit view has them but it's consistent, so I'm not sure if these should be removed, but I wouldn't be opposed to it for more consistency between views.

Edit view (excluding dropdowns):
![image](https://user-images.githubusercontent.com/1621608/79596543-6cd73580-80e9-11ea-8149-30eadf17e865.png)

**Comment by felixarntz** [comment] 2020-04-17 18:06
@aaemnnosttv @ryanwelcher Ah that's a good point. If that is the case, we can probably just close the issue via #1311. I think for the `SettingsEdit` view input descriptions we can keep them because those are less a list of things. Technically they're only one sentence as well, but I'd consider them more of an actual description (plus one has a learn more link, which would be weird without having a period before it).

**Comment by cole10up** [comment] 2020-04-30 07:14
**Tested**

Confirmed all periods are consistent with the above screenshot including toggle adjustments.

![image](https://user-images.githubusercontent.com/57115907/80682420-5204a980-8a77-11ea-887b-ab58180965d9.png)

![image](https://user-images.githubusercontent.com/57115907/80682452-62b51f80-8a77-11ea-8ec5-98702d2b142d.png)

![image](https://user-images.githubusercontent.com/57115907/80682462-68ab0080-8a77-11ea-8977-69d95883fc8b.png)

Passed QA ✅

**Closed** 2020-05-06 17:22 UTC
Labels: P2, Type: Enhancement
