### ISSUE TITLE
User Input Styling issue When Using Safari Browser

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3419] opened 2021-05-26 15:46 UTC
## Bug Description

There is a styling issue when navigating `User Input` feature on Safari browser.  

The font colour of the active `next` button is blue, rather than white. 

![image](https://user-images.githubusercontent.com/73545194/119690238-6913f780-be41-11eb-9c2b-806e319548cb.png)

When you use the `back` button though, the font colour on the `next` button changes to white. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2021-06-01 15:22
@wpdarren I'm not able to reproduce this (at least in [Storybook](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/user-input--userinputapp)). Does it only happen in WP?

**Comment by wpdarren** [comment] 2021-06-07 12:55
@aaemnnosttv Ah, this must be an issue with Browserstack because when I tested this on Safari on my laptop, the issue does not arise on WP or Storybook.  We can close this ticket, will double check in future.

**Comment by aaemnnosttv** [comment] 2021-06-07 14:02
Thanks @wpdarren - closing for now.

**Closed by aaemnnosttv** 2021-06-07 14:02 UTC
Labels: Type: Bug
