### ISSUE TITLE
If we cannot pull through stats for a module, we should provide a more contextual error message

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#191] opened 2019-07-10 21:34 UTC
For any case where the reason why we're not showing stats is that the user needs to complete setup, let's tell them that. Make this less severe (not "Data error in $PRODUCT") and add a CTA.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment] 2019-07-18 10:16
This is a duplicate of issue #52.

**Closed by marrrmarrr** 2019-07-18 10:16 UTC
Labels: Type: Enhancement
