### ISSUE TITLE
Analytics setup never completes - permissions issues mean a UA property can't be created

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#6994] opened 2023-04-28 13:20 UTC
## Bug Description

During Analytics setup, if a user only has "Viewer" access to the selected Analytics account, and that Analytics account only has a GA4 property, the plugin will mention that a UA property will be created. This isn't the case, as the user doesn't have the ability to create a UA property. This results in the Analytics set up never completing, remaining in a loading state with various console errors present. 

![image](https://user-images.githubusercontent.com/41326532/235158172-18c71f27-ed1d-4d33-857d-5e091e41411f.png)

![image](https://user-images.githubusercontent.com/41326532/235158044-9e772d38-998e-477e-bfed-625765b1a595.png)

See full recording of this behavior, which is easily reproducible, below the steps to reproduce below. This issue was first highlighted by [one user in the support forums](https://wordpress.org/support/topic/unable-to-connect-to-analytics/), who kindly shared screen recordings of their own experience. 

## Steps to reproduce

1. Setup a new Analytics account from analytics.google.com, with a GA4 property. Do not create a UA property. This account should only have a GA4 property
2. Grant "viewer" access to another user (at Account level) 
3. Set up Site Kit on a new site, using the Google account which only has "view" access to the above Analytics property
4. Attempt to connect the Analytics module, connecting to the Analytics account above. As there is is only a GA4 property this will be auto selected when you select the account from the dropdown. The plugin will mention that a UA property will be created, despite this not being the case due to permissions. There is no permissions warning or errors, and when proceeding the set up remains in a loading state. 

## Screenshots

https://user-images.githubusercontent.com/41326532/235154364-307baaeb-af0f-440a-8e36-29e1634810f7.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics setup flow should surface an error when failing to create any new entities
	* The setup flow should never be stuck in an infinite loading state
	* This is only required for GA4 entities as UA entity provisioning will no longer be possible soon

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2023-05-11 19:45
Lack of knowledge about what role/permissions a user's Google account has for a given service-side entity has always been an issue, but hasn't actually manifested as a substantial problem for our users. The Analytics Admin API provides endpoints for reading and managing ["access bindings"](https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/accounts.accessBindings) so we could for example query all of the users who have access to an account or property to see which roles they have for it. It's worth noting that this endpoint is only available in the Alpha version of the API, so we'll likely want to wait for it to stabilize before using it.

Also, this endpoint requires `analytics.manage.users(.readonly)` scopes that we haven't used before.

**Comment by nfmohit** [comment] 2023-10-16 07:05
Hi @aaemnnosttv & @jamesozzie.

I started looking into this and since UA has been removed now, the current "Steps to reproduce" no longer apply. However, I followed the ACs and tried to ensure that the Analytics setup screen surfaces any errors it counters while creating entities, and it does seem to do so already. Here's a screenshot:

![image](https://github.com/google/site-kit-wp/assets/20284937/f376f26b-eef9-4f69-a937-3a22b384d563)

This was most likely resolved as a part of #6831.

Should we close this issue? Thank you!

**Comment by aaemnnosttv** [comment] 2023-10-20 16:14
Thanks @nfmohit – this can be closed as the proper feedback is present.

We should address the duplication of the errors however, I'm not sure if we have an issue for that or not. Would you please take a look and create one if needed? Thanks 👍

**Closed by aaemnnosttv** 2023-10-20 16:14 UTC
Labels: Type: Bug, Type: Support, P1, Module: Analytics

**Comment by nfmohit** [comment] 2023-10-23 09:20
> We should address the duplication of the errors however, I'm not sure if we have an issue for that or not. Would you please take a look and create one if needed? Thanks 👍

Looks like we have #7276 to address this, thank you @aaemnnosttv!
