### ISSUE TITLE
Object caching can interfere with module activation

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#419] opened 2019-08-19 18:47 UTC
## Bug Description
 
When attempting to activate a module (eg. Analytics) in an object cached environment, the activation status update may appear to fail.

## Steps to reproduce

1. In an object cached environment set up the plugin and attempt to activate the Analytics module

**Expected result:**
Module is activated, setup flow continues.

**Actual results:**
Module not activated, page shows error. Clearing the object cache at this point and reloading causes setup to continue as expected.

## Screenshots
Failure:
![image](https://user-images.githubusercontent.com/2676022/63290269-5937ae80-c27e-11e9-9175-3fc9aa278844.png)

REST request to module/analytics active:true returns active: false: 
![image](https://user-images.githubusercontent.com/2676022/63290337-7b313100-c27e-11e9-815c-65930cb1ba6c.png)

Analytics Module missing after activating: 
![image](https://user-images.githubusercontent.com/2676022/63290368-8e440100-c27e-11e9-9765-f9619916df74.png)

## Additional Context
@westonruter can you provide any additional details around your caching environment?

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by westonruter** [comment] 2019-08-19 19:15
I was trying this on my Pantheon-hosted production environment:

* PHP 7.2
* [WP Redis](https://wordpress.org/plugins/wp-redis/) object caching plugin
* Plugin version: 1.0.0-beta.1.0.4

**Comment by marrrmarrr** [comment] 2019-10-10 12:44
@adamsilverstein agree this is quite a frustrating issue, I've encountered it a few times myself while testing and doing demos. It could stump a lot of users, especially the less savvy ones. 
If it's possible to figure out what exactly is causing this and how we can clear that specific part of the object cache, that would be great. Then I can define more specific ACs for what should change.

**Comment by adamsilverstein** [comment] 2019-10-10 12:47
I'll dig into this a bit further to see how we can mitigate.

**Comment by tofumatt** [comment] 2019-10-10 13:00
Sorry, but for clarification: what does "object caching" mean here? Is it specifically using the https://wordpress.org/plugins/wp-redis/ plugin or any other type of server-side/PHP object cache?

**Comment by aaemnnosttv** [comment] 2019-11-15 10:52
> Sorry, but for clarification: what does "object caching" mean here? Is it specifically using the https://wordpress.org/plugins/wp-redis/ plugin or any other type of server-side/PHP object cache?

Object caching is essentially [`WP_Object_Cache`](https://developer.wordpress.org/reference/classes/wp_object_cache/) which is core's caching layer where things like posts, meta, and options are kept to prevent querying the database every time these are requested. By default, this is a simple in-memory implementation which only lasts for the current request. However, it is possible (and sometimes necessary) to use alternate implementations of `WP_Object_Cache` which use other backends as persistent, external object caches. The two most popular options are Redis and Memcache. In order to use them, you need to have access to the cache backend, not just the plugin 😄

**Comment by marrrmarrr** [comment] 2020-01-10 15:13
@cole10up it would be great to have a look if this is still an issue. If not, we can close it.

**Comment by cole10up** [comment] 2020-01-14 05:12
**Tested:**

Enabled Object Cache
![image](https://user-images.githubusercontent.com/57115907/72315771-d9551b00-3648-11ea-84b7-783f95f1473e.png)

Confirmed Existing configuration of Analytics functions
![image](https://user-images.githubusercontent.com/57115907/72315799-f1c53580-3648-11ea-94ac-bc29336c268e.png)

Uninstalled and tried new setup
Also functioned. Going to chat with @aaemnnosttv about other scenarios to try on the backend tomorrow.

**Comment by aaemnnosttv** [comment] 2020-01-14 07:54
@cole10up I see you installed the Redis plugin but it looks like it's not connected to a Redis backend so the persistent object cache won't work yet.
![image](https://user-images.githubusercontent.com/1621608/72324447-a5fba600-36b3-11ea-97bc-d51e676aa235.png)
 Ping me and I'll see about helping you get this set up locally.

**Comment by cole10up** [comment] 2020-01-14 16:25
**Tested**
Ran some tests with @aaemnnosttv using evanmattson.10uplabs.com 

![image](https://user-images.githubusercontent.com/57115907/72362001-41d2e500-36a7-11ea-9840-1b359e9557d2.png)

Didn't see this issue. Going to reach out to try on a Pantheon hosted environment next.

**Comment by marrrmarrr** [comment] 2020-01-28 14:04
Hey @cole10up, have you heard anything from Pantheon on this one?

**Comment by cole10up** [comment] 2020-01-28 17:19
Hey @marrrmarrr, we've got a service ticket in on our end to get access to a Pantheon environment as of yesterday. I will followup tomorrow on the status of the ticket if I don't get access today.

**Comment by cole10up** [comment] 2020-01-29 19:20
I have access to Pantheon, working through the setup and will have feedback tomorrow.

**Comment by cole10up** [comment] 2020-01-30 04:59
**Tested**

Setup Pantheon server with Redis object caching. 
![image](https://user-images.githubusercontent.com/57115907/73420980-34d60880-42d9-11ea-9351-6c8e52c1c253.png)

Installed and activated latest develop build of SK (1.3.0)
![image](https://user-images.githubusercontent.com/57115907/73421031-5cc56c00-42d9-11ea-8d36-5776290fb5e5.png)

Setup SK and configured Analytics
![image](https://user-images.githubusercontent.com/57115907/73421094-91392800-42d9-11ea-9876-908de78e87b5.png)

Confirmed Analytics on the dashboard is displayed and no errors occured
![image](https://user-images.githubusercontent.com/57115907/73421151-bb8ae580-42d9-11ea-8e95-4c56c8144847.png)

Confirmed Tag Manager, Search Console, and Page Speed Insights also functioned properly. 

Wasn't able to reproduce this issue on 1.3.0 @marrrmarrr

**Comment by ThierryA** [comment] 2020-02-11 14:27
Closing since it is not reproducable

**Closed by ThierryA** 2020-02-11 14:27 UTC
Labels: Type: Bug
