### ISSUE TITLE
Error configuring client code in site kit by google

### ISSUE THREAD

**Issue by justusKe** [google/site-kit-wp#290] opened 2019-07-17 07:27 UTC
I keep getting this error when I try to paste and proceed with the client configuration code  "The response is not a valid JSON response."
How do I go about it?

#242

**Comment by jamesozzie** [comment] 2019-07-17 09:51
@justusKe Thanks for reporting. In order to try and proceed you can try and recreate the credentials using the steps below:

1. In your browser address bar paste the following in:
https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com
2. Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. (Including the https or http)
3. Press enter, with your cursor in the address bar (as if you are visiting that URL)
4. Press the "GET OAUTH CREDENTIALS" button
5. The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit 


An alternative is to also change the language of wordpress to English US before changing your "Site Title" and "Tagline" to English from the settings menu.

**Comment by jamesozzie** [comment] 2019-07-22 09:09
@justusKe I am closing this as a duplicate of #242.

**Closed by jamesozzie** 2019-07-22 09:09 UTC
Labels: Type: Support
