### ISSUE TITLE
WooCommerce compatibility: Admin pages do not load

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#1637] opened 2020-06-04 21:59 UTC
## Bug Description

When Site Kit is activated, some [WooCommerce](https://wordpress.org/plugins/woocommerce/) admin pages do not load intermittently. A [user in the forums](https://wordpress.org/support/topic/it-is-compatible-with-woocommerce-customers-page/) reported specifically that the _WooCommerce > Customers_  admin page experienced the issue, however I was able to replicate the issue on other admin pages such as _Analytics > Revenue_ and _Orders_ pages (sometimes they work and sometimes they do not). 

## Steps to reproduce

1. On a site with [WooCommerce](https://prnt.sc/stm1au), activate Site Kit
2. View the WooCommerce admin pages
3. Encounter an admin page attempting to load (most frequently the pages mentioned above)
4. See browser console error referencing Site Kit

# Screenshots
<img width="1267" alt="Woocommerce admin page error" src="https://user-images.githubusercontent.com/8108643/83812987-5709d980-a671-11ea-84f4-a40a4d19f462.png">

## Additional Context

 - PHP Version:  7.3.16 
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.9.0
 - Device: MacBook Air
 - WooCommerce version: 4.20

#1638 experienced at same time

Support topic reference: https://wordpress.org/support/topic/it-is-compatible-with-woocommerce-customers-page/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* WooCommerce screens should load as expected when Site Kit is active, and Site Kit's "minimal admin script" should not result in an error.

## Implementation Brief

* Set `output.jsonpFunction` in the webpack config to a unique, Site Kit specific value to prevent a conflict with the default. See https://webpack.js.org/configuration/output/#outputjsonpfunction
* Merge #1690 

## QA Brief

* 

## Changelog entry

* Fix incompatibility with WooCommerce due to Webpack conflict.

**Comment by ernee** [comment] 2020-06-13 00:52
Additional reports in the forum:
https://wordpress.org/support/topic/site-kit-and-woocommerce/
https://wordpress.org/support/topic/woocommerce-analytics-fails-to-load-with-sitekit-active-js-error/

**Comment by tofumatt** [comment] 2020-06-18 12:33
IB ✅

**Comment by tofumatt** [comment] 2020-06-18 13:15
Just assigning for merge, but code is reviewed and looks good.

**Comment by cole10up** [comment] 2020-06-18 17:38
Moving this to approval per @ernee's retest

![image](https://user-images.githubusercontent.com/57115907/85053717-cc84a800-b14f-11ea-8c89-0e4fb710bfa8.png)

**Closed** 2020-06-18 17:42 UTC
Labels: Next Up, P0, Type: Bug

**Comment by DavidCamelo** [comment] 2020-08-24 23:43
I'm getting this error when I activated the Site kit plugin, It breaks the Dashbord
/wp-admin/index.php
![image](https://user-images.githubusercontent.com/1959395/91106912-95dc7980-e639-11ea-988c-1b18c5aeb7ad.png)

**Comment by jamesozzie** [comment] 2020-08-25 10:47
@DavidCamelo I suspect it may be a minification feature of some plugin you may have active. Feel free to open a [WordPress support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) and we'd be happy to investigate this further.

**Comment by DavidCamelo** [comment] 2020-08-25 13:55
@sannjayy I deactivated all my plugins and started to activate them one by one and found that the problem is with the YITH WooCommerce Wishlist plugin. Do you know of any known incompatibility with this plugin and how to solve it?

**Comment by DavidCamelo** [comment] 2020-08-25 13:55
@sannjayy Going deeper, I found that is a mix of plugins that breaks the dashboard: WooCommerce, Elementor, YITH WooCommerce Wishlist and Site Kit by Google :(

**Comment by ernee** [comment] 2020-08-25 13:59
@DavidCamelo thanks for the details. It would be best for us to investigate this further in support topic in the [WordPress forums](https://wordpress.org/support/plugin/google-site-kit/) Please [open support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there and we'll be happy to assist.

**Comment by DavidCamelo** [comment] 2020-08-25 14:40
@ernee I just created a support topic:
https://wordpress.org/support/topic/mix-of-plugins-breaks-the-dashboard/
![image](https://user-images.githubusercontent.com/1959395/91186640-e80eb080-e6b4-11ea-8384-b482e6121bc6.png)

**Comment by DavidCamelo** [comment] 2020-08-25 15:43
@jamesozzie @ernee Looks like is a problem with the latest version of Elementor plugin. I downgrade the version and now is working. I'll delete the support topic due is not a problem from Site Kit. Thanks for your comments!

**Comment by jamesozzie** [comment] 2020-08-25 15:57
@DavidCamelo Many thanks for the update, nice troubleshooting. I'll check this myself as others have reported similar issues. Appreciate the updates.
