### ISSUE TITLE
Enhancement - Use Analytics Stats for Widget and/or Shortcode Front-End Display

### ISSUE THREAD

**Issue by robin-scott** [google/site-kit-wp#1093] opened 2020-02-04 09:24 UTC
## Feature Description

A widget to display "Show most popular X posts from Y days" as a widget using the Analytics stats. Also or instead, a shortcode to display a simple ordered list of most popular content with title and hyperlink to each of X posts from Y days.

Got a lot of love for Site Kit for news / big content sites, and this would be a nice addition, to expose most popular content to visitors without adding too much weight (it's the same data used in admin).

Note I can assist on this with a PR :) 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment] 2021-04-12 19:28
Duplicate of / related to #785

**Closed by felixarntz** 2021-04-12 19:28 UTC
Labels: Type: Feature
