### ISSUE TITLE
Translations lost on plugin update

### ISSUE THREAD

**Issue by kebbet** [google/site-kit-wp#4592] opened 2021-12-21 07:49 UTC
## Bug Description

Every time the plugin is updated the UI is in English, even though I have correct translations files. The issue is solved when new translations are added via translate.wordpress.org and the language packs are updated. 
The added translations at wordpress.org are not the ones that are not translated in the UI after a plugin update. 

## Steps to reproduce

1. Install the plugin on a site where the website language is set to sv_SE (Swedish).
2. See the translated UI.
3. Wait for a new plugin release.
4. Update to the newest plugin version.
5. See the not translated UI (even though translations exists in the language pack)

## Screenshots

![image](https://user-images.githubusercontent.com/11491369/146891528-eb27b150-8270-4b18-8d0c-e2fd3f110d6f.png)

## Additional Context

 - Plugin Version 1.48.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The changes in #4436 should be reverted so that our JS files do not end in `.min.js`.

## Implementation Brief

* Merge https://github.com/google/site-kit-wp/pull/4595

### Test Coverage

* N/A

## QA Brief

* Check built JS files in release zip file to ensure none of them end in `.min.js` but only `.js`

## Changelog entry

* Revert fix to prevent minification of already minified JS files by other plugins as it caused JS translations to no longer be delivered by wordpress.org.

**Comment by aaemnnosttv** [comment] 2021-12-21 16:17
@felixarntz it seems as though we may have broken translation extraction for JS in https://github.com/google/site-kit-wp/issues/4436 by changing the generated file names to match one of the default exclusion patterns used by wp-cli's `make-pot` command ([source](https://github.com/wp-cli/i18n-command/blob/17606058b2d269c1434a9e2269043dec9bf81300/src/MakePotCommand.php#L50)).

Unless there's a way to ignore this exclusion then we'll need to revert that change.

**Comment by felixarntz** [comment] 2021-12-21 17:29
@aaemnnosttv Hmm that's a weird exclusion role in `make-pot` I guess? Why would `.min.js` files be different from `.js` files? I guess the assumption is that the minification would be more "naive" and not keep the `__` etc function calls?

That's not great, but I'm also not sure we can change that, at least not in a short time. For a start though, could you open an issue on https://github.com/wp-cli/i18n-command to inquire about that?

For the time being, we may need to revert #4436. To me personally, breaking translations for everyone seems worse than breaking entirely due to plugin conflicts with comparably few. @ThierryA @marrrmarrr What's your take on this?

**Comment by felixarntz** [comment] 2021-12-21 17:29
@bethanylang Any reports on this yet in the support forums?

**Comment by aaemnnosttv** [comment] 2021-12-21 18:16
Moving this forward to revert #4436 for now after discussing with @felixarntz

**Comment by felixarntz** [comment] 2021-12-21 19:03
IB / CR ✅

**Comment by felixarntz** [comment] 2021-12-21 19:05
Leaving a comment here for now: This is happening due to https://github.com/wp-cli/i18n-command/issues/45 - worth following up there _why_ that change was made, as the issue there doesn't really provide a reason.

**Comment by felixarntz** [comment] 2021-12-21 19:24
QAd via https://github.com/google/site-kit-wp/pull/4595#issuecomment-999013642

**Closed** 2021-12-21 20:10 UTC
Labels: Type: Bug, Type: Support, P0

**Comment by kebbet** [comment] 2021-12-21 20:47
Thanks for fixing this!

**Comment by aaemnnosttv** [comment] 2021-12-22 08:22
Confirmed this is fixed in 1.48.1 

![image](https://user-images.githubusercontent.com/1621608/147059841-82df89f1-82d1-4250-af18-9de0d23bcfa1.png)
