### ISSUE TITLE
"Edit in Analytics" and "Edit in Tag Manager" settings links lack visual whitespace due to HTML markup

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#7968] opened 2023-12-08 16:56 UTC
## Bug Description

The "Edit in" links for Analytics recently had their `display` changed to `inline-flex`, preventing the whitespace from rendering properly, leading to the text looking like "Editin Analytics".

The same is likely true for Tag Manager, as the HTML markup is the same.

## Steps to reproduce

1. Set up Site Kit with Analytics
2. Go to Site Kit Settings
3. View Analytics

## Screenshots

![CleanShot 2023-12-08 at 16 50 52](https://github.com/google/site-kit-wp/assets/90871/7845b03a-233f-4330-8d55-1369525606c7)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Edit in Analytics" and "Edit in Tag Manager" links should have visual whitespace between each word.

## Implementation Brief

The issue will apply to any link with `<VisuallyHidden>` content, as the [recent change to `display: inline-flex;`](https://github.com/google/site-kit-wp/pull/7847) causes the whitespace around the `<VisuallyHidden />` component to be "squashed".

* [x] Change `.googlesitekit-cta-link` from `display: inline-flex;` to `display: inline-block;`
* [x] Add `vertical-align: text-bottom;` to `.googlesitekit-cta-link .googlesitekit-icon-wrapper` 
* [ ] Merge #7969 (PR is ready and can be moved directly to Code Review after IB Review)

### Test Coverage

* VRTs may need updating, but no new tests are needed.

## QA Brief

* Visit Analytics settings and Tag Manager settings in Site Kit.
* The "Edit in Analytics" and "Edit in Tag Manager" should not appear to have "Editin" as one word.

## Changelog entry

* Fix whitespace issue in Analytics and Tag Manager settings.

**Comment by aaemnnosttv** [comment] 2023-12-12 20:23
> Change .googlesitekit-cta-link from display: inline-flex; to display: inline-block;

👍 

@tofumatt I think we can avoid the need for adding the `top` positioning by using `vertical-align` (middle or maybe text-bottom) on `.googlesitekit-cta-link .googlesitekit-icon-wrapper`. WDYT?

<img width="638" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/758c6c55-6cad-473e-90cf-ffe87006f51b">

**Comment by tofumatt** [comment] 2023-12-12 21:29
@aaemnnosttv Nice, yeah, looks like that does the trick 👍🏻

**Comment by aaemnnosttv** [comment] 2023-12-13 00:54
IB ✅ moving to CR

**Comment by wpdarren** [comment] 2023-12-14 00:03
### QA Update: ✅ 

**Verified:**

- The "Edit in Analytics" and "Edit in Tag Manager" do not have "Editin" as one word in settings.

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/216365ce-cfac-4b8a-b7f1-f199cba03666)
![image](https://github.com/google/site-kit-wp/assets/73545194/03ab896e-0bd3-4c83-9d6b-d8c105455ff5)

</details>

**Comment by wpdarren** [comment] 2023-12-14 10:16
### QA Update: ❌ 

@tofumatt I have just noticed that the link text and icon aren't aligned with the text.  It's only slightly off but noticeable. 

![image](https://github.com/google/site-kit-wp/assets/73545194/a2244836-53b2-4776-9f08-15289fd41b3d)
![image](https://github.com/google/site-kit-wp/assets/73545194/32c0bb89-e45d-46ec-bf80-7a00a39c368b)

**Comment by aaemnnosttv** [comment] 2023-12-15 04:05
@wpdarren ready for another look 👍

**Comment by aaemnnosttv** [comment] 2023-12-15 04:18
Actually it still has at least one more thing to fix 
<img width="354" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/8fd5db31-56e1-4a6c-9186-903423b3219b">

**Comment by wpdarren** [comment] 2023-12-15 08:16
Mmm, yes, those Edit links were working before, so it seems a regression.

**Comment by mohitwp** [comment] 2023-12-15 13:21
@tofumatt 

Please found  all  issues details below with description and screenshots cc @wpdarren @bethanylang @aaemnnosttv @eclarke1 

**1)** _Main dashboard and entity dashboard > All Traffic widget> text moved to next line._

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/2c8862e9-6011-4591-bf4e-786086840fce)

</details>

**2)** _Key metrics widget > 'Change metrics' button SVG is not aligned properly with text on main._

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/06dce826-ff3d-427b-a091-ac1f96c3b831)

</details>

**3)** _User Input Customize site goals screen and under settings - No Space between icon and edit label._

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/8659ff2e-5638-47a5-860c-eac14a6a12a8)

![image](https://github.com/google/site-kit-wp/assets/94359491/5324cc09-1dce-4e7c-b1c3-86ce2d1775c0)

</details>

**4)** _Key metrics :Ellipsis are missing on main environment for KM "Most engaging pages" widget and similar widgets._

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/28f92891-1cfa-4b88-9de8-ebce78d271f8)

![image](https://github.com/google/site-kit-wp/assets/94359491/8adfce7d-21a9-4f8d-96e8-aca60b67df3e)

</details>

**5)** _The icon against the URL on the entity dashboard is misaligned again. This was fixed previously._

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/3dd9c20a-3882-46d6-9079-a0b8f1893138)

</details>

**6)** _Source CTA svg icons are not looking bold now on main. I noticed that for svg icons we have different <span class = "googlesitekit-icon-wrapper"> is getting apply on main which is not the case on latest. This same issue exist wherver we are using this icon like under notifications, Settings page >Connected services, Admin Settings> tracking services, main and entity dashboard, Settings> Connected Services> Analytics._ 

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/608e313e-f6f9-4afa-b907-cd800b710886)

![image](https://github.com/google/site-kit-wp/assets/94359491/65d4864b-827e-4ffc-9bc9-2dfce3b91145)

![image](https://github.com/google/site-kit-wp/assets/94359491/4586f5a9-3cfc-4dbc-97a0-c0346f5a7736)

![image](https://github.com/google/site-kit-wp/assets/94359491/fb9fdc26-53bf-4748-a105-569f3a08df3b)

![image](https://github.com/google/site-kit-wp/assets/94359491/7d34a59a-6faa-4090-b9e7-e8731b17cfe1)

![image](https://github.com/google/site-kit-wp/assets/94359491/72362393-2f60-4c80-97ef-64bcbb2f7719)

![image](https://github.com/google/site-kit-wp/assets/94359491/dbddf8e1-9ca0-4a69-8ef8-52880a4b5387)

![image](https://github.com/google/site-kit-wp/assets/94359491/96a56841-6032-4f6a-9622-0cccd3dfa4d6)


</details>

**7)** _Connected Services > Arrows under green circle are not center aligned on main._

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/b334e3c3-8394-4f3b-97ff-286fa3f50954)

![image](https://github.com/google/site-kit-wp/assets/94359491/0f60463a-90ab-49a2-837c-60e3573bf0de)

</details>

**8)** _Connected services> Disconnected button for all modules is not aligned properly._

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/c16ba94e-eaf9-41c8-ad05-6f21bc55c0e8)

![image](https://github.com/google/site-kit-wp/assets/94359491/fcc24daf-ea6a-4f1f-988c-939405c20774)

</details>

**9)** _Settings> Connected Services> 'Edit' icons for all modules not aligned with the text._

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/8b568649-21b8-4ee0-beac-a2f255a46a81)

![image](https://github.com/google/site-kit-wp/assets/94359491/0fa6bc40-29e7-4ea2-b813-a8859071da82)

</details>

**10)** _Settings> Connect More Services > Set up arrow is not aligned with the text._

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/144726bc-f1a2-4451-bafd-5bc531b5d4d9)

</details>

**11)** _The Edit links for Analytics and Tag Manager settings are slightly misaligned._

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/c73bebc2-0735-438f-8bdf-902eccf9c992)

</details>

**Comment by tofumatt** [comment] 2023-12-15 13:51
For context, the change to `display: inline-flex;` for `.googlesitekit-cta-link` has had a _lot_ of knock-on effects throughout the plugin. For instance, the ellipsis bug mentioned in 4 caused the link to have a width wider than the widget, and thus never overflow.

I'm going to mark which of these are totally fixed and which are either issues for a follow-up, acceptable changes, etc. here.

- [x] 1. Main dashboard and entity dashboard > All Traffic widget> text moved to next line.
- [x] 2. Key metrics widget > 'Change metrics' button SVG is not aligned properly with text on main.
- [x] 3. User Input Customize site goals screen and under settings - No Space between icon and edit label.
- [x] 4. Key metrics :Ellipsis are missing on main environment for KM "Most engaging pages" widget and similar widgets.
- [ ] 5. The icon against the URL on the entity dashboard is misaligned again. This was fixed previously.
- [ ] 6. Source CTA svg icons are not looking bold now on main.
- [ ] 7. Connected Services > Arrows under green circle are not center aligned on main.
- [ ] 8. Connected services> Disconnect buttons for all modules are not aligned properly.
- [ ] 9. Settings> Connected Services> 'Edit' icons for all modules not aligned with the text.
- [ ] 10. Settings> Connect More Services > Set up arrow is not aligned with the text.
- [ ] 11. The Edit links for Analytics and Tag Manager settings are slightly misaligned.

**Comment by aaemnnosttv** [comment] 2023-12-15 19:04
This should be good now @wpdarren @mohitwp. @tofumatt and I went through everything pretty thoroughly. Back to you guys 👍

**Comment by wpdarren** [comment] 2023-12-18 02:21
### QA Update: ⚠️ 

@mohitwp would appreciate a second pair of eyes on this, but the only issue I can find is that the Edit in Analytics link highlighted below is slightly off.  Everything else seems fixed, and I can't see any regressions. 

![image](https://github.com/google/site-kit-wp/assets/73545194/3b4764d0-4087-4691-bf5e-9cf2ccd76e7d)

**Verified:**

 1. Main dashboard and entity dashboard > All Traffic widget> text fixed with alignment of chart legends. 
 2. Key metrics widget > 'Change metrics' button SVG is aligned properly with text.
 3. User Input Customize site goals screen and under settings - Space between icon and edit label is fixed.
 4. Key metrics :Ellipsis are appearing for KM "Most engaging pages" widget and similar widgets.
 5. The icon against the URL on the entity dashboard is aligned correctly.
 7. Connected Services > Arrows under green circle are center aligned.
 8. Connected services> Disconnect buttons for all modules are aligned properly.
 9. Settings> Connected Services> 'Edit' icons for all modules are aligned with the text.
 10. Settings> Connect More Services > Set up arrow is aligned with the text.
 11. The Edit links for Analytics and Tag Manager settings are misaligned. See note above. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/103ed02b-761c-4f8c-bde0-eea0be3eb919)
![image](https://github.com/google/site-kit-wp/assets/73545194/f3eac9d6-270c-431a-9f90-595080b574eb)
![image](https://github.com/google/site-kit-wp/assets/73545194/7e7d77b6-9013-4510-a64f-e9a3242e7b27)
![image](https://github.com/google/site-kit-wp/assets/73545194/9ebc293a-9c40-45a8-a1fb-840f6ba1d8e9)
![image](https://github.com/google/site-kit-wp/assets/73545194/9bd3bcf3-769a-41e7-9da6-36cb958eae95)
![image](https://github.com/google/site-kit-wp/assets/73545194/063ce792-ae7a-4325-abe1-394e9bef9fa9)
![image](https://github.com/google/site-kit-wp/assets/73545194/4bb94305-e5f3-44bb-9838-df099b7130f8)
![image](https://github.com/google/site-kit-wp/assets/73545194/f2cb3a63-8e4c-4724-8189-08eddc1d916b)
![image](https://github.com/google/site-kit-wp/assets/73545194/9975543f-35c8-4683-8a8c-3a80ad70e991)
![image](https://github.com/google/site-kit-wp/assets/73545194/b7c51126-e181-400f-9c78-75b448426b9e)
![image](https://github.com/google/site-kit-wp/assets/73545194/da872ed6-ba9f-444d-a480-63d8462a1728)
![image](https://github.com/google/site-kit-wp/assets/73545194/b5fa3da6-9602-4845-9f77-2b7863e1ef7a)
![image](https://github.com/google/site-kit-wp/assets/73545194/d1bc3fc2-d30b-4544-b392-21ec78908a2a)

</details>

**Comment by mohitwp** [comment] 2023-12-18 07:49
### QA Update ✅ 

@wpdarren Tested all the points and all issues are fixed.

The issue you highlighted is basically a part of point 6 because we are using same icons here and now these icons are not bold on main environment after new changes. For 6 @tofumatt replied that it is intended. Other issues are fixed now. 

>  6. Source CTA svg icons are not looking bold now on main. This is correct and an intended effect.

**Closed** 2023-12-18 19:37 UTC
Labels: Type: Bug, P0
