### ISSUE TITLE
Implement new selectors for sharing settings

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4795] opened 2022-02-04 18:16 UTC
## Feature Description

Similar to #4794, there are a number of new selectors that will be needed around dashboard sharing settings.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

The `core/modules` store should be extended with the following new selectors

* `getShareableRoles()`  
Gets the list of role objects for all shareable roles (not specific to any module)  
Roles are objects with an `id` and `displayName` property (both strings) as set on `_googlesitekitDashboardSharing.roles`
    - Should have a resolver and action `receiveShareableRoles` to recieve the shareable roles from the global  
* `getSharingManagement(moduleSlug: string)`  
Gets the value for a module's sharing management. Should return one of `all_admins` or `owner` (default)
* `getSharedRoles(moduleSlug)`  
Gets the list of all shareable roles (see related selector above) the module is shared with.
* `getSharingSettings()`  
Gets sharing settings for all modules.  
    - Should have a resolver to receive the sharing settings from `_googlesitekitDashboardSharing.settings`.  
    The action to receive sharing settings will be implemented in #4794.
* `haveSharingSettingsChanged()`  
Similar to `haveSettingsChanged` for module settings, but specific to sharing settings.
* `canSubmitSharingChanges()`  
Similar to `canSubmitChanges` for module settings, but specific to sharing settings. See `createValidationSelector`.  
Should return `true` if the sharing settings have changed, otherwise `false`
* Test coverage should be added for all new selectors

## Implementation Brief

As part of creating new actions for sharing settings, a new file is being created in #4794 within the `assets/js/googlesitekit/modules/*` directory.

**Resolvers:**
- In that file, create a resolver generator function (method) `*getSharingSettings()` with the following:
    - Destructure `settings as sharingSettings`  from  `global._googlesitekitDashboardSharing`
    - Dispatch `receiveGetSharingSettings` action to set `sharingSettings` in the state. Note this action is being implemented in #4794
- Create a `*getShareableRoles()` resolver method with the following:
    - Destructure `roles as shareableRoles`  from `global._googlesitekitDashboardSharing`
    - Dispatch `receiveShareableRoles` action to set `shareableRoles` in the state. 
    - See `*getSiteInfo()`:
    https://github.com/google/site-kit-wp/blob/6ba2897937775f8522eb746ec1610fb7d16e7841/assets/js/googlesitekit/datastore/site/info.js#L145

**Action:**
 -  Create `receiveShareableRoles()` action method:
    -  It should accept `shareableRoles` as a parameter
    - Return `shareableRoles` within the payload and type `RECEIVE_SHAREABLE_ROLES`
    
**Reducer:**
- Create a reducer function with the following:
    - Set a case `RECEIVE_GET_SHARING_SETTINGS`
    - Return the previous state and the new state `sharingSettings` from the payload
    - Set a case `RECEIVE_SHAREABLE_ROLES`
    - Return the previous state and the new state `shareableRoles` from the payload

**Selectors:**
- Create `baseSelectors` object with the following selectors:
    - `getShareableRoles()` gets roles object not specific to any module:
        - Return `shareableRoles` from the state
    - `getSharingSettings()` gets sharing settings for all modules:
        - Get `sharingSettings` from the state
        - Return the object in the shape that has `moduleSlug` as the key and `sharingSettings` object as the value `[moduleSlug]: sharingSettings`
    - `getSharingManagement` that takes `moduleSlug` as the parameter:
        - Return the `management` object from `getSharingSettings()[moduleSlug].management` selector
    - `getSharedRoles` with `moduleSlug` as the parameter:
        - Get `shareableRoles` from `getShareableRoles()` selector
        - Get `sharedRoles` array from `getSharingSettings()[moduleSlug].sharedRoles` selector
        - Returns the `shareableRoles[]` that matches the `sharedRoles` array item with `shareableRoles` array of object's property `id`
    - `haveSharingSettingsChanged()`: 
        - Get `sharingSettings` and `savedSharingSettings` from the state
        - Return `true` if `sharingSettings` have changed, `false` otherwise using the `isEqual` helper function
        - See `haveSettingsChanged` as described in the AC:
        https://github.com/google/site-kit-wp/blob/cbb153d4bf4b46303426c7ebef930e33f3e530c1/assets/js/googlesitekit/data/create-settings-store.js#L282-L286
    - `canSubmitSharingChanges()`: 
        - Validate the `moduleSlug`: `invariant( moduleSlug, 'slug is required.' )`
        - Validate has the sharing settings changed: `invariant( haveSharingSettingsChanged(), "cannot submit changes if sharing settings have not changed" )`
        - Get the `storeName` from `getModuleStoreName()` selector
        - Pass the `storeName` to `select` to get `canSubmitSharingChanges()` selector
        - Return `true` if the module supports submitting sharing changes, `false` otherwise
        - See `canSubmitChanges` as described in the AC:
        https://github.com/google/site-kit-wp/blob/cbb153d4bf4b46303426c7ebef930e33f3e530c1/assets/js/googlesitekit/modules/datastore/settings.js#L146-L150

### Test Coverage

 - Add test cases for `receiveShareableRoles()` action
 - Add test cases for all the new selectors

## QA Brief

**QA**
This will be further tested in subsequent issues that use these selectors so these won't be easily QA-able in practice yet. For now, a high-level smoke test should be sufficient to catch any potential regressions with/without dashboard sharing enabled.

**QA:Eng**

- Ensure the `dashboardSharing` feature flag is enabled.
- Ensure the selectors work from the browser console by running `googlesitekit.data.select('core/modules').[selector-name]()`

## Changelog entry

* Implement new selectors for sharing settings.

**Comment by eclarke1** [comment] 2022-02-09 15:02
@hussain-t please could you add an estimate to this one, thanks

**Comment by eugene-manuilov** [comment] 2022-02-10 19:13
> `getSharingManagement` that takes `moduleSlug` as the parameter:
> * Create a resolver function (method) `getSharingManagement` that gets the `sharingManagement` array of objects from  `global._googlesitekitDashboardSharing.settings`

> `getSharedRoles` with `moduleSlug` as the parameter:
> * Create a resolver method `getSharedRoles` that gets the `roles` array of objects from `global._googlesitekitDashboardSharing`

> `getSharingSettings()` gets sharing settings for all modules
> * Create a resolver method `getSharingSettings` that gets the `settings` array of objects from `global._googlesitekitDashboardSharing`

@hussain-t no need to create resolvers for each selector. We need to create one resolver for the `getSharingSettings()` selector that reads data from the global variable and dispatches an action to set read data in the state. It also means that you need to add an action and a new case to the reducer to save data in the state. Check out the `receiveSiteInfo` action for example.

Other selectors that need to get some information from the sharing settings should call the `getSharingSettings()` selector instead of trying to read the data from the state directly. See how we use the `createRegistrySelector` helpers.

> * `haveSharingSettingsChanged()`:
>   * Return a boolean value similar to `haveSettingsChanged` as described in the AC
> * `canSubmitSharingChanges()`:
>   * As described in the AC it should be similar to `canSubmitChanges`
>   * Use `createValidationSelector` function that takes a validate callback function to get the `safeSelector`
>   * Return `true` if the sharing settings have changed, otherwise `false`

Could you please provide more information about what needs to be done in these selectors? Also selectors that return information - which information do they return? Initial or modified?

**Comment by hussain-t** [comment] 2022-02-14 07:22
Thanks @eugene-manuilov. `receiveSiteInfo` action was really helpful 👍 

I like the idea of having one resolver that dispatches an action to set the data in the state. However, as per the AC, we get only the `settings` object from `global._googlesitekitDashboardSharing` for `getSharingSettings()`:
>Should have a resolver to recieve the sharing settings from _googlesitekitDashboardSharing.settings

Currently, we have `recoverableModules`, `roles`, and `settings` objects in `global._googlesitekitDashboardSharing`. If we are getting only the `settings` in the `getSharingSettings()` resolver as defined the AC, we do need to create a resolver for 
`getSharedRoles`, right? Otherwise, can we set all the data from `_googlesitekitDashboardSharing` instead of only `settings`?

**Comment by eugene-manuilov** [comment] 2022-02-14 11:02
@hussain-t see how site info datastore works. There is also one resolver, but many selectors that return data from the global object. We need to use the same approach here.

https://github.com/google/site-kit-wp/blob/develop/assets/js/googlesitekit/datastore/site/info.js

**Comment by hussain-t** [comment] 2022-02-15 16:56
@eugene-manuilov I have updated the IB and increased the estimate to 15.

@aaemnnosttv We have to update the the AC for adding `getSharingData()` resolver. I think we will have to update the AC in #4794 as well.

**Comment by aaemnnosttv** [comment] 2022-02-16 14:58
@hussain-t noting here after our conversation earlier that after some consideration, I think  individual resolvers are still probably best. The reason for this is that it ensures we have a respective action for receiving the data in the store (which we will want for tests without needing to pass the entire shape of the global) and that this action is the only way we set this in the store. There isn't a substantial cost to having a few more resolvers here so let's go this route (as initially defined, I think) rather than adding a higher level selector+resolver for all the data.

cc: @eugene-manuilov

**Comment by hussain-t** [comment] 2022-02-16 15:02
Thanks @aaemnnosttv 👍

**Comment by tofumatt** [comment] 2022-03-01 20:21
Inline with @aaemnnosttv's request to use separate resolvers here this looks good. IB ✅

**Comment by hussain-t** [comment] 2022-05-16 09:21
@aaemnnosttv, after discussing with @eugene-manuilov, it became clear that #4794 and 4795 are interdependent. He suggested working on 4795 first and then 4794. Also, the `receiveGetSharingSettings` action must be moved from 4794 to 4795 since we need to dispatch `sharingSettings` to the `receiveGetSharingSettings` action.

**Comment by hussain-t** [comment] 2022-05-16 09:39
@aaemnnosttv, however, it’s better to move the `getSharingSettings` selector and resolver to #4794 since we need to get the `sharingSettings` from the `getSharingSettings` selector to use it in the `saveSharingSettings` action to pass it to the `fetchSaveSharingSettings` action like this:
<img width="726" alt="Screenshot 2022-05-16 at 3 06 40 PM" src="https://user-images.githubusercontent.com/24408261/168563995-8d4649cf-f45c-492e-bd50-160a3a1895ce.png">

Instead of the above [comment](https://github.com/google/site-kit-wp/issues/4795#issuecomment-1127433501).

**Comment by aaemnnosttv** [comment] 2022-05-16 21:34
@hussain-t we should be able to do these sequentially as defined. Please see my response https://github.com/google/site-kit-wp/issues/4794#issuecomment-1128155108 🙂

**Comment by wpdarren** [comment] 2022-05-25 04:45
### QA Update: ⚠️ 

@hussain-t  Hello!  I feel we need more clarification in the QAB. 

> For now, a high-level smoke test should be sufficient to catch any potential regressions with/without dashboard sharing enabled.

Can you tell me where I should be focusing the testing on this.  On other ticket I was asked to focus on the checking for regressions in the settings, main and entity dashboard, so not sure what to focus this time around?  BTW, I ran the code in the `QA:Eng` section `googlesitekit.data.select('core/modules').[selector-name]()` on the Site Kit dashboard but received an error message. `VM372:1 Uncaught SyntaxError: Unexpected token '['` Not sure if that's expected?

**Comment by hussain-t** [comment] 2022-05-25 06:09
@wpdarren, `[selector-name]` I mean, the specified selector names in the AC. We should execute them one by one. For example:
`googlesitekit.data.select('core/modules').getSharingSettings()`

For context, it seems @aaemnnosttv has updated the QAB.
<img width="640" alt="Screenshot 2022-05-25 at 11 36 26 AM" src="https://user-images.githubusercontent.com/24408261/170191950-f4ba6f35-cc94-4138-b7b9-8260833adeec.png">

**Comment by wpdarren** [comment] 2022-05-30 08:47
### QA Update: ⚠️ 

@hussain-t  Sorry, only just had a chance to look at this ticket again. 

The selectors are part of the `QA:Eng` section of the QAB. I can run through and run the code from the console but I have no idea if the results I see are correct or not.   My query was really on the QA section, where it is just says a `high-level smoke test` but doesn't really say what in particular I should be smoke testing.

**Comment by techanvil** [comment] 2022-06-01 09:07
Hi @wpdarren, as these selectors are all new and unused, there's no particular area to focus on. Just a very simple sanity check of a smoke test to load the Dashboard should suffice, maybe in view-only mode and open the sharing controls considering the subject matter, but the code changes basically don't touch anything "live" so that should be more than enough detail.

**Comment by wpdarren** [comment] 2022-06-01 11:36
### QA Update: ✅ 

**Verified:**

- Went through the main and entity dashboard with `dashboardSharing` feature flag enabled and disabled.
- Went through the main and entity dashboard as a non admin user in view only mode. 
- We are waiting for 4822 to be merged so unable to test the sharing controls at this point. We will be doing this testing when QA-ing the ticket mentioned above. 

Labelled this `QA:Eng` because it references checked in the QAB.

- Ensure the dashboardSharing feature flag is enabled.
- Ensure the selectors work from the browser console by running `googlesitekit.data.select('core/modules').[selector-name]`()

**Comment by techanvil** [comment] 2022-06-01 17:03
## QA :white_check_mark: 

`QA:Eng`:

- Exercised the new selectors in the JS console:
![image](https://user-images.githubusercontent.com/18395600/171460464-e71dca77-28d8-4d54-bc52-fb3cc777c87a.png)

**Closed** 2022-06-16 17:51 UTC
Labels: P0, Type: Enhancement, QA: Eng, Rollover
