### ISSUE TITLE
Enhance survey trigger infrastructure to persist surveys beyond a single page view and orchestrate showing

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#6306] opened 2022-12-08 18:23 UTC
Right now, when the `/survey/trigger/` request returns a survey, it is immediately shown. This mostly works for the case where we request a generic survey in the `view_dashboard` trigger, but for more event-based triggers it has major limitations: For example, if an event happens right before navigating to a different page (e.g. activating a module), if we wanted to trigger a survey for it, it would just be triggered right before the page navigation, but then it would be gone immediately before the user can possibly interact with it.

We need to enhance the infrastructure to cater for actual event based surveys better. At a minimum, surveys should not be displayed right away when they were triggered. There needs to be some kind of survey queue where these surveys are added to and stored in some way (e.g. client-side cache, or even persistently on the server). We also need to come up with heuristics / logic where, when, and how frequently to show surveys. For example, if there are 3 surveys in the queue, we also don't want to show all of them right after each other, since we want to avoid overloading the user with surveys.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Survey display should be decoupled from the survey trigger request
* The `getCurrentSurvey` selector should be updated to be fulfilled by the new `GET:core/user/data/survey` endpoint
	- The response should be cached on the client using the standard/default `useCache:true` behavior
* The `survey-trigger` response should be modified to return a simplified object with the shape `{ status: Boolean }` (this is somewhat redundant but necessary that the request returns valid JSON)
	- The corresponding `triggerSurvey` action should be updated accordingly such that it is only concerned with the trigger request and no longer concerned with survey state apart from the timeouts which should still apply
* Survey display should be limited to the main Site Kit dashboard only, and happen only after the `view_dashboard` trigger has completed
* No survey should be displayed more than once in a 12 hour period – this should also use a persistent mechanism for storing the timeout which does not rely on client-side cache
* Survey timeouts should only be set when a survey is displayed (no longer as part of a trigger)
* Survey related functionality should only function for authenticated users

## Implementation Brief

* In `REST_User_Surveys_Controller`, update the `survey-trigger` endpoint
	* Change the response shape to a simple `{ success: Boolean }`, this can probably always be `true` since there isn't any use case for having knowledge of whether or not a survey was really enqueued or not on the client

**Datastore**

`core/user`
* Add a new fetch store for `getSurvey`
	- Fetches the new `GET:core/user/data/survey` endpoint
	- Receives `currentSurvey` state similar to `triggerSurvey` today
	- Use default `useCache` behavior
* Update `fetchTriggerSurveyStore`
	- Remove `reducerCallback` – the response will no longer include anything to be received into state
* Update `triggerSurvey`
	- Remove bypass if there is a current survey – trigger should only be skipped if user lacks permissions or trigger is timed-out
* Update the `getCurrentSurvey` selector
	- Add a resolver that fetches the new `GET:survey` route via the `getSurvey` fetch store above if no survey state is present (similar to other resolvers)

**Survey Display**

* `CurrentSurveyPortal`
	* Remove from `Root`; add to `DashboardMainApp` only
	* Add a condition to return `null` if the `global` survey is on cooldown (`isTimingOutSurvey`)
* `DashboardMainApp`
	* Add a delay in rendering `CurrentSurveyPortal` so that it is only rendered after 5 seconds

### Test Coverage

* Changes to `survey-trigger` endpoint
* Update Jest coverage for the `getCurrentSurvey` selector
* Update tests for `triggerSurvey` action
* Add component tests for `CurrentSurveyPortal`

## QA Brief

* Setup a new site and connect the plugin to site-kit-local.
* Ask @eugene-manuilov to help you set up a survey for your site.
* Verify that survey appears on the dashboard and you can can interact with it as usual.

## Changelog entry

* Enhance survey infrastructure to be more flexible.

**Comment by aaemnnosttv** [comment] 2023-01-27 21:54
@felixarntz I've drafted some initial AC here which I think covers almost everything except how we handle serving/displaying surveys now that they will not be directly tied to the screen/context that they were triggered from. Should we opt to only show them on the main dashboard? I don't believe we finalized this aspect of the survey lifecycle. Let me know what you think.

**Comment by felixarntz** [comment] 2023-01-31 18:38
@aaemnnosttv I think the ACs look good, the only thing I would suggest to clarify is to point out a concrete REST endpoint to implement for adding a survey to the queue. I also wonder whether we really need the endpoint to return surveys from the queue, shouldn't it rather be an endpoint to return a single survey to display or `null`?

Other than that, we should indeed also cover the logic about displaying surveys. How about the following:
* Add logic that happens after the `view_dashboard` trigger to display the first survey in the queue if there is one based on the REST endpoint. (This should only happen on the Site Kit main dashboard.)
* In the endpoint, only return the first survey available if the last survey was shown to the user more than 12 hours ago (rely on a persistent timeout).
* We would also need another endpoint like `mark-survey-shown` that removes a survey from the queue as it is being shown in the UI and resets the persistent timeout for showing _any_ surveys from the point above.

Let me know your thoughts.

**Comment by aaemnnosttv** [comment] 2023-02-02 18:19
> the only thing I would suggest to clarify is to point out a concrete REST endpoint to implement for adding a survey to the queue

@felixarntz I'm not quite sure what you mean. I was thinking the survey would be added to the queue as part of the backend handling for the trigger endpoint since those will continue to happen on-demand as they do now, as the response on the client side won't really be used/needed anymore.

> I also wonder whether we really need the endpoint to return surveys from the queue, shouldn't it rather be an endpoint to return a single survey to display or `null`?

I suppose it could be only a single survey if we limit surveys to only be shown in one place/context. Otherwise, I see them potentially being similar to feature tours where multiple could exist but be context-specific. Apart from that, we could make it specific to returning a single survey or none.

> Other than that, we should indeed also cover the logic about displaying surveys. How about the following

Sounds good to me, I'll iterate on the AC to include this 👍

**Comment by felixarntz** [comment] 2023-02-02 18:34
@aaemnnosttv 
> I was thinking the survey would be added to the queue as part of the backend handling for the trigger endpoint since those will continue to happen on-demand as they do now, as the response on the client side won't really be used/needed anymore.

Ah thanks for clarifying, that makes sense. Can you please clarify that in the ACs? Also: Would the trigger endpoint then still return the survey, or should we change it to just return some kind of `{success:true}` response? That may be better, to clarify the use-case, since any returned survey should not be displayed anyway.

> I suppose it could be only a single survey if we limit surveys to only be shown in one place/context. Otherwise, I see them potentially being similar to feature tours where multiple could exist but be context-specific. Apart from that, we could make it specific to returning a single survey or none.

I think we only have a single place to display surveys, and we would never want to show 2 right after each other, so I think changing the endpoint to always return a single survey or `null` makes most sense.

**Comment by aaemnnosttv** [comment] 2023-02-02 19:47
> Ah thanks for clarifying, that makes sense. Can you please clarify that in the ACs (that it should happen _in_ the trigger endpoint)?

Will do 👍 

> Would the trigger endpoint then still return the survey, or should we change it to just return some kind of `{success:true}` response? That may be better, to clarify the use-case, since any returned survey should not be displayed anyway.

Yes, a minimal response would suffice; SGTM. Aside from a status, we could maybe also return a value as to whether a survey was queued or not but we can keep that in mind if/when it's needed.

> I think we only have a single place to display surveys (bottom right corner of the screen), and we would never want to show 2 right after each other, so I think changing the endpoint to always return a single survey or `null` makes most sense.

Sure, I was more thinking of the screen, but if we're only ever going to surface surveys on the main dashboard then this wouldn't be a problem 👍

**Comment by aaemnnosttv** [comment] 2023-02-02 20:55
@felixarntz I've updated the AC here, which should cover everything now. Once this looks good to you I will add the IB.

A few final points/questions for you:

- The endpoint and selector for getting the survey now has a singular name to better reflect that only a single survey may be returned
- Question: the current survey timeouts we have are survey-specific and the TTL comes from the trigger. Do we want to preserve survey-specific timeouts _in addition to a "global" survey timeout_ of 12 hours? I don't think that would be necessary anymore since we're serving surveys from a queue so users should only see the next one as early as 12 hours later. It sounds like this could be simplified a fair bit into a single timeout that is specific to survey display only. Does that sound right to you?
- > * We would also need another endpoint like `mark-survey-shown` that removes a survey from the queue as it is being shown in the UI and resets the persistent timeout for showing _any_ surveys from the point above.
	- Could we not use the existing `survey_shown` event for this? 

Let me know if anything else seems to be missing or needs clarification 👍

**Comment by felixarntz** [comment] 2023-02-02 23:19
@aaemnnosttv ACs LGTM ✅ 

One thing that's not explicitly mentioned is whether the logic regarding survey timeouts etc should happen on the client or on the server. The ACs state that `GET:core/user/data/survey` should (unconditionally?) return the first survey in the queue, but I was wondering whether we shouldn't also do those survey timeout checks on the server and only return the first survey if none was completed/dismissed in the last 12 hours already.

I think it's okay to not force this to be a certain way in the ACs, but we should cover it in the IB.

**Comment by felixarntz** [comment] 2023-02-15 21:16
@aaemnnosttv Some notes on the IB:

It seems a point on execution order for when the `view_dashboard` trigger is being executed is missing.

> Add a new fetch store for `getSurvey`

Maybe clarify what this should use (`core/user/data/survey`) as otherwise this may not be clear? Also, how does this relate to the existing `getCurrentSurvey` selector? Shouldn't we rather use that one and add a reducer (fetch store based) for it? Otherwise this seems like a duplicate. You already mention that `fetchTriggerSurveyStore` needs to be modified to no longer populate `state.currentSurvey` at which point the `getCurrentSurvey` selector is effectively broken if we don't tweak it.

> `enqueue( Survey ) : bool` - adds the given survey to the end of the queue, only if it does not exist in the queue (returns `bool` to indicate if it was enqueued or not)

Nit-pick: Maybe a `bool` is a bit limiting here, since it would not allow returning an error indicator? Unless the idea is to use an exception. Just thinking about how to differentiate between "yes, enqueued", "not enqueued, but expected since it's already in the queue", and "not enqueued because of an actual error".

**Comment by aaemnnosttv** [comment] 2023-02-20 16:49
> It seems a point on execution order for when the `view_dashboard` trigger is being executed is missing.

I now that we're significantly delaying the request for getting the survey, I was thinking it might not be necessary to add in an additional mechanism to make sure this always happens afterwards since the trigger would not be delayed. What do you think?

> Also, how does this relate to the existing `getCurrentSurvey` selector? Shouldn't we rather use that one and add a reducer (fetch store based) for it? Otherwise this seems like a duplicate. You already mention that `fetchTriggerSurveyStore` needs to be modified to no longer populate `state.currentSurvey` at which point the `getCurrentSurvey` selector is effectively broken if we don't tweak it.

Good call – I was thinking that we'd still use `getCurrentSurvey` but hadn't specified where `getSurvey` would be used going forward. I've since merged the two so that still only have the one going forward.

> Nit-pick: Maybe a `bool` is a bit limiting here, since it would not allow returning an error indicator? Unless the idea is to use an exception. Just thinking about how to differentiate between "yes, enqueued", "not enqueued, but expected since it's already in the queue", and "not enqueued because of an actual error".

For the queue itself, this is probably more for testing since there isn't necessarily anything we can do if a survey isn't queued, e.g. because it is already present in which case it isn't necessarily an error (it's working as intended). The other option is of course that an error happened (e.g. DB error) but the underlying meta functions don't return this either – they also return a boolean – but this could also mean that the saved value is unchanged. [We've seen this result in a user-facing error in the past](https://github.com/google/site-kit-wp/issues/2513) when we interpreted this to mean an error happened, but it can happen under normal circumstances too. I agree the return value could be better, but we're limited by the underlying WP meta/option APIs. Ultimately, unless there is behavior related to something we would do differently if a survey was not queued, then this probably isn't worth changing, but we could always update it if needed. Is there anything here you have in mind that we might not be considering?

---

IB has been updated, let me know if there's anything else!

**Comment by felixarntz** [comment] 2023-02-22 03:34
@aaemnnosttv 
> I now that we're significantly delaying the request for getting the survey, I was thinking it might not be necessary to add in an additional mechanism to make sure this always happens afterwards since the trigger would not be delayed. What do you think?

Good point, that makes sense.

IB ✅

**Comment by bethanylang** [comment] 2023-02-22 14:31
@aaemnnosttv Can you please add an estimate on this issue? Thanks!

**Comment by aaemnnosttv** [comment] 2023-02-22 18:57
@felixarntz I've split this issue into a separate one for the backend work (which may be better suited to a different engineer) in #6625. It's almost a clean split, the only thing which I've left in here as a backend related change is the response for `trigger-survey` since changing that should happen together with the front-end changes or it may leave things in a broken state.

Aside from that I think we want these two to go in the same release, but I think we should be able to start on both at the same time, 6625 is more of a blocker for this one to be completed rather than started. I've assigned these both to you for a final look over, otherwise I think they should be good to go 👍

**Comment by felixarntz** [comment] 2023-02-22 22:43
@aaemnnosttv Sounds good, LGTM!

**Comment by aaemnnosttv** [comment] 2023-03-10 18:16
@bethanylang Adding this to the upcoming release now that #6625 has been merged as these need to go together.

**Comment by eugene-manuilov** [comment] 2023-03-14 19:15
@aaemnnosttv this is ready for review. Could you please take a look at my PR #6704?

**Comment by mohitwp** [comment] 2023-03-27 10:11
### QA Update ✅ 

Verified -

- Tested on dev.
- Survey showing only on main dashboard.
- Survey timeouts only be set when a survey is displayed.
- Survey is showing only for authenticated users.

<details>

![image](https://user-images.githubusercontent.com/94359491/227903517-4019721f-55f0-41e3-bbcc-d28dfe877687.png)

</details>

**Closed** 2023-04-06 22:40 UTC
Labels: P1, Type: Enhancement, Exp: SP
