### ISSUE TITLE
"Disconnect from Site Kit" errors despite sign out success

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#508] opened 2019-09-09 16:03 UTC
## Bug Description

A user can sign out of Site Kit by selecting the "Disconnect" option in the top-right menu, but after confirming they want to sign out and the HTTP request to disconnect their account is sent, the UI is not updated (even after the request is successful). The page remains in the same state and it appears the user is still signed in until a full-page reload is completed. Afterward it's obvious the user has, in fact, signed out.

An error `uncaught exception: Object` is raised after the sign out request's response is returned from the server.

(Related E2E issue: #252.)

## Steps to reproduce

1. Sign into any Site Kit account
2. Click on your Google Account's name in the top-right corner of the page
3. Select "Disconnect"
4. Confirm by selecting the large "Disconnect" button
5. Wait for error to appear in console; notice UI is not updated
6. Refresh page to see sign out was successful

## Screenshots
![2019-09-09 16 57 41](https://user-images.githubusercontent.com/90871/64546876-5f6ff680-d323-11e9-887c-5b8deabb5f15.gif)

## Additional Context

 - PHP Version: 7.3.7
 - OS: MacOS 10.14
 - Browser Firefox Developer Edition 70.0b3 (64-bit)
 - Plugin Version `develop` branch
 - Device: Mac

This happens for several of my Google accounts which sign in without issue.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment] 2019-10-10 19:08
I tried these steps on two separate sites, and after clicking "Disconnect", I get redirected to the main WP dashboard (which is the expected behaviour). 
@felixarntz let's have a look at this together tomorrow.

**Comment by marrrmarrr** [comment] 2020-01-10 15:08
Still can't replicate this, seeing the "You revoked access to Site Kit for [site]" notification (WAI). 
@cole10up could you have a look to verify if this is still an issue?

**Comment by marrrmarrr** [comment] 2020-01-21 15:30
hey @cole10up, just checking if you might have had any luck identifying if this is still an issue?

**Comment by cole10up** [comment] 2020-01-22 06:34
@marrrmarrr - tried a few different accounts. Using my local and Jurassic Ninja. Was unable to reproduce this. See below for my local.

![Site Kit by Google Dashboard ‹ googlekitlocal 10uplabs com — WordPress](https://user-images.githubusercontent.com/57115907/72870801-01262d80-3c9e-11ea-8933-6ab2585901bc.gif)

**Comment by marrrmarrr** [comment] 2020-01-28 14:05
Thanks for checking the different setups, @cole10up . 
Marking this as closed.

**Closed by marrrmarrr** 2020-01-28 14:05 UTC
Labels: Type: Bug
