### ISSUE TITLE
Error state flicker when navigating to Dashboard after changing connected property

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7774] opened 2023-10-25 15:46 UTC
## Bug Description

As reported by @techanvil in Bug Bash ([Asana task](https://app.asana.com/0/1205508124049666/1205784257171326/f)):

I am seeing the error state flicker having just switched to a different GA4 property and navigated to the Dashboard.

https://github.com/google/site-kit-wp/assets/12189958/b4813c8f-3fa2-47f7-b3f9-a53da31ba817

**NOTE:** This could be related to / use the same fix as #7739; check back to see if this is fixed by that issue.

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by nfmohit** [comment] 2023-10-26 09:18
Hi @techanvil.

I just also responded in the Asana task, but I cannot reproduce the issue anymore in the latest `develop`.

If anyone else cannot reproduce it anymore, I think we can close this one.

Thanks!

CC: @bethanylang

**Comment by techanvil** [comment] 2023-10-26 10:47
Thanks @nfmohit. Closing this one as no longer relevant.

**Closed** 2023-10-26 10:49 UTC
Labels: P2, Type: Enhancement
