### ISSUE TITLE
Conflict with other plugins that using Google API Client (UpdraftPlus and Super Socializer)

### ISSUE THREAD

**Issue by tunakode** [google/site-kit-wp#610] opened 2019-09-27 17:27 UTC
## Bug Description

Have conflict with others plugins ([updraftplus](https://id.wordpress.org/plugins/updraftplus/) and s[upersocializer](https://id.wordpress.org/plugins/super-socializer/))

## Steps to reproduce

**1. Updraft Plus**
1. Go to https://doman/wp-admin/options-general.php?page=updraftplus#updraft-navtab-settings-content
2. Click on **Authenticate with Google:**
3. error happens

**2 SuperSocializer**
Just tryin login with Google from frontend, similar error occur

## Screenshots

```
Error Details
=============
An error of type E_ERROR was caused in line 92 of the file /wp-content/plugins/google-site-kit/vendor/google/apiclient/src/Google/Client.php. Error message: Uncaught TypeError: Argument 1 passed to Google_Client::__construct() must be of the type array, object given, called in /wp-content/plugins/updraftplus/methods/googledrive.php on line 825 and defined in /wp-content/plugins/google-site-kit/vendor/google/apiclient/src/Google/Client.php:92
Stack trace:
#0 /wp-content/plugins/updraftplus/methods/googledrive.php(825): Google_Client->__construct(Object(Google_Config))
#1 /wp-content/plugins/updraftplus/methods/googledrive.php(512): UpdraftPlus_BackupModule_googledrive->bootstrap(Array)
#2 /wp-includes/class-wp-hook.php(286): UpdraftPlus_BackupModule_googledrive->show_authed_admin_success('')
#3 /wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#4 /wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#5 /wp-admin/admin-header.php(289): do_action('all_admin_not
```

## Additional Context

 - PHP Version: 7.3.9
 - OS:  Linux 2.6.32-896.16.1.lve1.4.49.el6.x86_64  
 - Browser: Any
 - Plugin Version 1.0.0-beta.1.0.7
 - Device: Server

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by ernee** [comment] 2019-09-27 18:27
Hi @tunakode

Thanks for your report! We’re aware of this conflict with UpdraftPlus and are actively investigating it [here](https://github.com/google/site-kit-wp/issues/246).  

You also mention a conflict with Super Socializer. Could you provide the details of the error message you received for that?  We have [an open issue](https://github.com/google/site-kit-wp/issues/540) with a plugin called LoginPress, so would be good to know if this is something similar.

Thank you!

**Comment by tunakode** [comment] 2019-09-29 13:47
Sorry for late reply, SuperSocializer conflict might related to Google Library

`PHP Fatal error:  Cannot declare class Google_Service, because the name is already in use in /wp-content/plugins/super-socializer/library/Google/Service.php on line 18`

I;m not found any kind error in my logs except the one above, recording every I;m tryin to login with Google login.

**Comment by swissspidy** [comment] 2019-10-01 10:45
We're now tracking work on this in #612.

**Comment by swissspidy** [comment] 2019-10-14 11:08
Closing as a duplicate of #612.

**Closed by swissspidy** 2019-10-14 11:08 UTC
Labels: Type: Support
