### ISSUE TITLE
Fix more flaky JS tests.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#9074] opened 2024-07-25 10:26 UTC
## Feature Description

Some new flaky JS tests have come to light, which would be good to fix.

Two of these have emerged in a CI test run for a PR, but were determined to be unrelated to the changes on the branch. The third was noticed by @hussain-t in local testing.

Tests can sporadically fail for the following components:

### `AudienceSelectionPanel/ErrorNotice`

This is the easiest to reproduce locally, and can be seen [failing in CI](https://github.com/google/site-kit-wp/actions/runs/10089724993/job/27897718463#step:7:477).

<details>
<summary>Here's a copy of the failing test output for `ErrorNotice`.</summary>

```
FAIL assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/ErrorNotice.test.js
  ● ErrorNotice › should render a "Retry" button when resyncing available audiences fails

    expect(jest.fn()).not.toHaveWarned(expected)

    Expected mock function not to be called but it was called with:
    ["Unmatched GET to /google-site-kit/v1/modules/analytics-4/data/audience-settings?_locale=user"]

      at Object.assertExpectedCalls (node_modules/@wordpress/jest-preset-default/node_modules/@wordpress/jest-console/build/@wordpress/jest-console/src/index.js:36:4)

  ● ErrorNotice › should render a "Retry" button when resyncing available audiences fails

    expect(jest.fn()).not.toHaveErrored(expected)

    Expected mock function not to be called but it was called with:
    ["Google Site Kit API Error", "method:GET", "datapoint:audience-settings", "type:modules", "identifier:analytics-4", "error:\"fetch-mock: No fallback response defined for GET to /google-site-kit/v1/modules/analytics-4/data/audience-settings?_locale=user\""]

      at Object.assertExpectedCalls (node_modules/@wordpress/jest-preset-default/node_modules/@wordpress/jest-console/build/@wordpress/jest-console/src/index.js:36:4)
```

</details>

### `AudienceSegmentationSetupCTAWidget`

This one hasn't been reproduced locally by myself or Hussain yet. It can be seen [failing in CI](https://github.com/google/site-kit-wp/actions/runs/10089724993/job/27897718463?pr=9070#step:7:425). As it's not easy to reproduce locally we should keep an eye on the frequency of test failures in CI; if it turns out to be extremely low frequency and not seen locally then we can park this one.

<details>
<summary>Here's a copy of the failing test output for `AudienceSegmentationSetupCTAWidget`.</summary>

```
FAIL assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.test.js
  ● AudienceSegmentationSetupCTAWidget › CTA actions › should initialise the list of configured audiences when CTA is clicked.

    expect(jest.fn()).not.toHaveWarned(expected)

    Expected mock function not to be called but it was called with:
    ["Unmatched POST to /google-site-kit/v1/core/user/data/dismiss-item?_locale=user"]

      at Object.assertExpectedCalls (node_modules/@wordpress/jest-preset-default/node_modules/@wordpress/jest-console/build/@wordpress/jest-console/src/index.js:36:4)

  ● AudienceSegmentationSetupCTAWidget › CTA actions › should initialise the list of configured audiences when CTA is clicked.

    expect(jest.fn()).not.toHaveErrored(expected)

    Expected mock function not to be called but it was called with:
    ["Warning: An update to %s inside a test was not wrapped in act(...).·
    When testing, code that causes React state updates should be wrapped into act(...):·
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */·
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act%s", "AudienceSegmentationSetupCTAWidget", "
        in AudienceSegmentationSetupCTAWidget (created by WithWidgetComponentProps(AudienceSegmentationSetupCTAWidget))
        in WithWidgetComponentProps(AudienceSegmentationSetupCTAWidget) (created by WhenAnalytics4Active(WithWidgetComponentProps(AudienceSegmentationSetupCTAWidget)))
        in WhenAnalytics4Active(WithWidgetComponentProps(AudienceSegmentationSetupCTAWidget))
        in Router (created by Wrapper)
        in Wrapper"],["Warning: An update to %s inside a test was not wrapped in act(...).·
    When testing, code that causes React state updates should be wrapped into act(...):·
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */·
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act%s", "AudienceSegmentationSetupCTAWidget", "
        in AudienceSegmentationSetupCTAWidget (created by WithWidgetComponentProps(AudienceSegmentationSetupCTAWidget))
        in WithWidgetComponentProps(AudienceSegmentationSetupCTAWidget) (created by WhenAnalytics4Active(WithWidgetComponentProps(AudienceSegmentationSetupCTAWidget)))
        in WhenAnalytics4Active(WithWidgetComponentProps(AudienceSegmentationSetupCTAWidget))
        in Router (created by Wrapper)
        in Wrapper"],["Warning: An update to %s inside a test was not wrapped in act(...).·
    When testing, code that causes React state updates should be wrapped into act(...):·
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */·
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act%s", "AudienceSegmentationSetupCTAWidget", "
        in AudienceSegmentationSetupCTAWidget (created by WithWidgetComponentProps(AudienceSegmentationSetupCTAWidget))
        in WithWidgetComponentProps(AudienceSegmentationSetupCTAWidget) (created by WhenAnalytics4Active(WithWidgetComponentProps(AudienceSegmentationSetupCTAWidget)))
        in WhenAnalytics4Active(WithWidgetComponentProps(AudienceSegmentationSetupCTAWidget))
        in Router (created by Wrapper)
        in Wrapper"],["Google Site Kit API Error", "method:POST", "datapoint:dismiss-item", "type:core", "identifier:user", "error:\"fetch-mock: No fallback response defined for POST to /google-site-kit/v1/core/user/data/dismiss-item?_locale=user\""]

      at Object.assertExpectedCalls (node_modules/@wordpress/jest-preset-default/node_modules/@wordpress/jest-console/build/@wordpress/jest-console/src/index.js:36:4)
```

</details>

### `SettingsModules`

This wasn't spotted in CI although it could exist in historical runs. Hussain noticed it while running tests locally. Again, if it's not appearing in CI we may take the pragmatic decision to park it.

<details>
<summary>Here's a copy of the failing test output for `SettingsModules`.</summary>

```
 FAIL  assets/js/components/settings/SettingsModules.test.js
  ● SettingsModules › should redirect from #admin to #/admin-settings

    expect(jest.fn()).not.toHaveWarned(expected)

    Expected mock function not to be called but it was called with:
    ["Unmatched GET to /google-site-kit/v1/modules/search-console/data/searchanalytics?startDate=2024-05-30&endDate=2024-07-24&dimensions=date&_locale=user"]
```

</details>

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The tests for the `AudienceSelectionPanel/ErrorNotice`, `AudienceSegmentationSetupCTAWidget` and `SettingsModules` components should be assessed for failures in CI and locally and fixed where possible.

## Implementation Brief

* [ ] `AudienceSelectionPanel/ErrorNotice` error 
  * This is not reproducible locally so far,  but seems it is most likely caused by a race condition when retry button is clicked on, and occasionally the `/settings` endpoint is called later after test is executed.
  * Edit `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/ErrorNotice.test.js` add default timeout wrapped within `act` after the click https://github.com/google/site-kit-wp/blob/b3295e850b1e3e87fa22d797ba858d74f48ef2bc/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/ErrorNotice.test.js#L263  `act( waitForDefaultTimeouts )`
* [ ] `AudienceSegmentationSetupCTAWidget` error
  * Edit https://github.com/google/site-kit-wp/blob/d777ba46d301a82eed849815f67ade8d12ee941f/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.test.js#L489 include `waitForRegistry` and await it bellow, to prevent things lingering after test is executed.
* [ ] `SettingsModules`
  * Can't reproduce this one locally also, but if it fails in CI again, we can try to await for registry after component is rendered https://github.com/google/site-kit-wp/blob/d777ba46d301a82eed849815f67ade8d12ee941f/assets/js/components/settings/SettingsModules.test.js#L107 to prevent any lingering state 

### Test Coverage

* No updates needed

#### QA:Eng
* Verify that tests are passing. I have reset JS tests several times in CI, couldn't detect failure in the mentioned tests

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment] 2024-07-29 15:43
IB ✔️

**Comment by eugene-manuilov** [comment] 2024-07-29 15:45
I think we need to bump the estimate here because we still have some unknowns and those problems are not reproducible on local. Let's set `7` instead of `3`.

**Comment by eugene-manuilov** [comment] 2024-08-13 15:36
Moving to approval directly since tests seem to work fine now and there is nothing else to QA here.

**Closed** 2024-08-23 16:42 UTC
Labels: P1, Type: Enhancement, QA: Eng, Team S
