### ISSUE TITLE
`Module::is_connected` should return `false` if the module is inactive

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7274] opened 2023-07-10 06:43 UTC
## Feature Description

A module being active is a prerequisite before it can be connected. However, the `Module::is_connected` method returns `true` unconditionally at the moment. This is a problem for modules that do not have a definite connection logic in place, for example, `PageSpeed_Insights`, which doesn't overwrite its `is_connected` method.

This problem was discovered while working on #7197, see [discussion](https://github.com/google/site-kit-wp/pull/7273#discussion_r1257449707) in PR #7273.

A potential solution could be introducing a `Module::is_active` class, which would receive its value from the DB option. We could then use that to return `false` for `Module::is_connected` if it was not active.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2023-07-11 20:47
I think the problem is somewhat semantic where it can be assumed that `Module::is_connected` should be the same as `Modules::is_module_connected( slug )`, where `is_connected` is about the module's criteria for being connected – it's assumed that it's already active in that context (similar to its `register` method).

It's also a bit misleading that on the client, `module.connected` is the `is_module_connected( slug )` value.

So, while I agree that things could be more clear, I'm not sure the suggested change in the title is the correct one to make.

**Comment by nfmohit** [comment] 2023-07-13 10:40
Understood, thank you, @aaemnnosttv. Any feedback on what could be an ideal solution here to ensure Site Kit doesn't assume that PSI is connected when it is not? Thanks!

**Comment by aaemnnosttv** [comment] 2023-07-17 18:51
@nfmohit looks like we've already addressed the issue you're referring to. I agree it's a bit confusing, but both methods are public and around since the initial release so we shouldn't just rename one of them for accuracy. If anything, we should update the inline docs to clarify and also audit the usage to make sure we're not using one incorrectly.

We have very few real uses of the module's method so I think we should be okay for now. Let me know if you find any other instances you feel should change though.

**Comment by jimmymadon** [comment] 2024-05-30 16:44
@nfmohit @aaemnnosttv Closing this based on the discussion above. Let me know otherwise.

**Closed by jimmymadon** 2024-05-30 16:44 UTC
Labels: Type: Infrastructure, PHP
