### ISSUE TITLE
Dialog buttons show more clearly when browser is unfocused

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1437] opened 2020-04-24 10:13 UTC
## Bug Description

Currently there is an inconsistent styling of the primary button in a modal dialog.

When the browser is unfocused, it appears more clearly (it seems as if this should be how it is by default) than when the page is focused.

## Steps to reproduce

1. Click on the link to Rest Site Kit on the plugin's Admin Settings
1. See dialog appear
1. Note color of primary button
1. Open developer tools
1. Note color is brighter more clear

## Screenshots

![Kapture 2020-04-24 at 13 06 19](https://user-images.githubusercontent.com/1621608/80201378-b87b6900-862c-11ea-8b85-a68ad70e8e19.gif)

It's hard to see exactly why this is happening because it is inconsistent based on devtools being open or not. It isn't specifically about devtools though as the same behavior can be seen when clicking on other things in the menu bar for example.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment] 2020-07-13 19:06
@aaemnnosttv I've looked into this for quite a bit now, and apparently this is not actually a bug; it's due to how the dialog component works: For accessibility reasons, it has to keep the focus within the dialog. And the way that the Material dialog component is built is that it re-focuses the initial focusable element whenever the entire page with the dialog opens receives focus again. The lighter color of the button is then simply the focused state.

You can check that e.g. by clicking into dev tools, clicking back into the page (anywhere). At this point, no matter where you clicked the primary dialog button here will be focused. If you hit the space key at this point (without even clicking on the button), the button action is triggered (because it was auto-focused).

I agree it can feel slightly weird, but from an accessibility and style perspective this is correct. The underlying problem here is actually that we're not sticking to Material design principles for our dialogs (see https://material.io/components/dialogs, they shouldn't include any regular buttons). Something for your consideration @marrrmarrr whether we should change our dialogs to align with that. The main difference with Material UI is that there is no "danger" variant then for dialog buttons.

I'll close this one since it's technically behaving as intended.

**Closed by felixarntz** 2020-07-13 19:06 UTC
Labels: Good First Issue, P2, Type: Bug
