### ISSUE TITLE
Update spacing on connected Ads module in Settings

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#8533] opened 2024-04-11 16:50 UTC
## Feature Description

See Figma: https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=653-2136&mode=design&t=EJdYdoUwknNE2Yh9-0.

cc @sigal-teller 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment] 2024-04-11 19:54
I'm not quite clear what the issue is here, actually.

I can see the discrepancy between the Figma design and the Site Kit settings page:

### Site Kit:

![Screenshot 2024-04-11 at 20 49 57](https://github.com/google/site-kit-wp/assets/90871/552fedd2-3806-4cca-a79f-136a294f060e)

### Figma

![Screenshot 2024-04-11 at 20 50 59](https://github.com/google/site-kit-wp/assets/90871/8402cf5c-156c-473e-ad68-f9f1a31811a0)

------

Eg. The "edit" button/link lacks the spacing seen in the Figma design.

But that's true of all modules and is nothing specific to Ads module. (Additionally, the "edit" link being pushed in with more margin than the rest of the module's setting text does strike me as a bit "off", in that it seems to be floating unaligned to other content.)

If this change to the "edit" links should be made though, we should do it everywhere and not just to ads. cc @sigal-teller for clarification, maybe I'm missing what needs to be done re: spacing here 🙂

**Comment by bethanylang** [comment] 2024-04-12 11:51
@tofumatt As discussed in https://10up.slack.com/archives/CBKKQEBR9/p1712850399584629, there is slightly less space vertically in the Figma design between the "row" with the Conversion Tracking ID and the "row" with the Edit / See full details links, which was a request from the Ads team.

That said, we're discussing this further with them and it may not be something we need to change, so let's hold on this for now and I'll share an update here and in Slack later today. Thanks!

**Comment by aaemnnosttv** [comment] 2024-04-12 14:56
Closing for now as the panel is consistent with other modules that only have a single row/setting such as Search Console 👍

**Closed by aaemnnosttv** 2024-04-12 14:56 UTC
Labels: P0, Type: Enhancement, Module: Ads, Squad 1
