### ISSUE TITLE
Improve error notification after OAuth error

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7597] opened 2023-09-19 19:26 UTC
## Feature Description

Currently, a user who has already authenticated Site Kit may need to go through the OAuth flow again to grant additional scopes. If the user refuses to permission request in this flow, or the OAuth flow encounters an error, they are presented with the following error in the SK dashboard:

![image](https://github.com/google/site-kit-wp/assets/20284937/a19954be-1ea2-44dc-a5bb-c0c7ae72c785)

While the error text is appropriate, the "Redo setup" CTA which goes on to grant the original scopes required by Site Kit is misleading here because in this case, it only occurred while granting additional scopes, and redoing the plugin setup isn't necessary to resolve this.

This error notification should be improved so that if SK encounters an OAuth error after authentication (e.g. for additional scope requests), the CTA only retries granting the scopes that failed to be granted causing this error.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The "Permission Error" notification's "Redo setup" should act like the following:
  - If the error notification appears during Site Kit setup, it should direct to the `setupErrorRedoURL` like it does today.
  - If the error notification appears while requesting additional scopes for the user and if it is possible to determine what scopes were requested, the CTA should make a request to request the same scopes again.
    - Necessary infrastructure should be updated so that the requested scopes are temporarily locally persisted to be requested again.
  - Otherwise, the CTA should not be displayed.

## Implementation Brief
* In `assets/js/googlesitekit/datastore/user/constants.js`
  * Introduce new constant that will be used as key for temporary storing permission error, e.g. `FORM_TEMPORARY_PERSIST_PERMISSION_ERROR`
* In `assets/js/components/PermissionsModal/AuthenticatedPermissionsModal.js`
  * Inside the [`onConfirm`](https://github.com/google/site-kit-wp/blob/8897c2be356938b8b1aed1b4bb0529058c95e920/assets/js/components/PermissionsModal/AuthenticatedPermissionsModal.js#L59) callback use `setValues` action from `CORE_FORMS` to store `permissionsError` (which is already defined in the component) for the `FORM_TEMPORARY_PERSIST_PERMISSION_ERROR`, ie. `setValues( FORM_TEMPORARY_PERSIST_PERMISSION_ERROR, {permissionsError} )`. Set the form value before `snapshotAllStores` call in that function, so new form value can be snapshotted.
*  Then use `getValue` selector on `CORE_FORMS` to retrieve `permissionsError` from `FORM_TEMPORARY_PERSIST_PERMISSION_ERROR` in:
   * `assets/js/components/notifications/UnsatisfiedScopesAlertGTE.js`
     * Edit [redirect url](https://github.com/google/site-kit-wp/blob/8897c2be356938b8b1aed1b4bb0529058c95e920/assets/js/components/notifications/UnsatisfiedScopesAlertGTE.js#L38) to check for `permissionsError?.data?.redirectURL || global.location.href` if `permissionsError` value is present
   * `assets/js/components/notifications/UnsatisfiedScopesAlert.js`
     * If `permissionsError` is present [`getConnectURL`](https://github.com/google/site-kit-wp/blob/8897c2be356938b8b1aed1b4bb0529058c95e920/assets/js/components/notifications/UnsatisfiedScopesAlert.js#L83-L85) should use properties from `permissionsError` like [here](https://github.com/google/site-kit-wp/blob/8897c2be356938b8b1aed1b4bb0529058c95e920/assets/js/components/PermissionsModal/AuthenticatedPermissionsModal.js#L46-L49)
     * `ctaLabel` should also display `Grant permission` if previous condition is met
   * `assets/js/components/notifications/ErrorNotifications.js`
     * if there is `permissionError`, a [`setupErrorRedoURL`](https://github.com/google/site-kit-wp/blob/8897c2be356938b8b1aed1b4bb0529058c95e920/assets/js/components/notifications/ErrorNotifications.js#L52-L54) should return `connectURL` value like in previous case.
     * In this [check](https://github.com/google/site-kit-wp/blob/8897c2be356938b8b1aed1b4bb0529058c95e920/assets/js/components/notifications/ErrorNotifications.js#L73-L76), if `permissionsError` has value, return `Grant permission` text for `ctaLabel`, otherwise set `ctaLabel` and `setupErrorRedoURL` to `null` or `undefined` to skip including the CTA
* In `assets/js/components/DashboardMainApp.js`
  * Define new variable, say `grantedScopes` and assign it a value from `getGrantedScopes` selector on `CORE_USER`
  * Get the stored `permissionError` from `FORM_TEMPORARY_PERSIST_PERMISSION_ERROR` form, like before
  * Check if `permissionsError?.data?.scopes` are present in `grantedScopes` array
    * If they are unset the value for `permissionError` in `FORM_TEMPORARY_PERSIST_PERMISSION_ERROR` form, by setting it to empty object `{}` for example. This will ensure this value is only temporary persisted, and does not conflict with other error that are not related to additional scopes.

### Test Coverage

* You can update `assets/js/components/notifications/ErrorNotifications.stories.js` to add a story when `access_denied` setup error code is present, and maybe `EDIT` scope from analytics 4 module in the unsatisfied scopes to replicate new behaviour
* Also add test case for new behaviour in `assets/js/components/notifications/ErrorNotifications.test.js`

## QA Brief
One way to test this is:
* During site kit setup, when redirected to OAuth flow and asked to grant permission, click cancel
  * `Permission error` notification should show with `redo the plugin setup` CTA
* After setup is done (without any module), and then proceeding to connect Analytics module/or some other module, canceling the permission grant, `Permission error` should not render CTA
* During the Analytics module setup, when asked to choose account, property and web data stream, select to create new web data stream for example, and then cancel the permissions when redirected to OAuth. `Permission error` should render `Grant permission` CTA
  * Granting that permission, going back to complete the setup for analytics, web data stream should be successfully created without asking again for permission/redirecting to the OAuth

## Changelog entry

* Update the permission error shown when returning from the OAuth flow via an error or cancellation to handle more scenarios.

**Comment by bethanylang** [comment] 2023-09-25 18:33
@jamesozzie @adamdunnage Curious for your thoughts on this one – I feel like we may have flagged this in the past?

**Comment by jamesozzie** [comment] 2023-09-26 09:52
Agree with @nfmohit. As it happens there is an update on this yesterday, with wording changes now present to account for this! See https://github.com/google/site-kit-wp/issues/6662

I think this one can be closed as duplicate, and since addressed @bethanylang .

**Comment by nfmohit** [comment] 2023-09-26 11:19
Thank you @jamesozzie! I noticed this update a while ago and have been meaning to get back here. This is how the new error looks:

![image](https://github.com/google/site-kit-wp/assets/20284937/b80fbb00-e4c7-4c24-8bcb-c6c6be340ffe)

The copy here actually looks good now, however, the "Redo setup" action doesn't really redo granting the scope that was requested, but grants the default scopes that Site Kit needs.

So, we either should remove the action entirely to avoid confusion, or improve the "Redo setup" action so that it grants the scopes that were originally requested resulting in the error.

**Comment by jamesozzie** [comment] 2023-09-26 11:31
Thanks for the update @nfmohit. Just to be clear, the error can occur also if there are issues during OAuth flow, such as a first time user exited or ran into problems before granting the initial required scopes (ie. the issue is the "redo" wording, as it was never "done")? If so, if a wording or label change would account for all scenarios here, that sounds good to me.

**Comment by nfmohit** [comment] 2023-09-28 20:54
Thank you for pointing that out, @jamesozzie! I've updated the issue description to be more aligned to our goals here now that the error notification has been updated.

**Comment by tofumatt** [comment] 2023-10-16 10:31
ACs here look good; I've added a priority label so moving to IB 👍🏻

**Comment by tofumatt** [comment] 2023-11-06 18:28
Looks good to me. 👍🏻 

IB ✅

**Comment by zutigrm** [comment] 2023-11-10 11:36
@nfmohit Since this issue is around the `Permissions error` notification, should we also open an issue to revisit the notification that uses the `permissionError` to show different banner later on:
<img width="1155" alt="image" src="https://github.com/google/site-kit-wp/assets/10414808/6f001ee3-a8a7-49bc-adc2-2e8681b8b7db">

Potentially CTA can be revisited to check if permission is generic `readonly` one. What do you think?

**Comment by wpdarren** [comment] 2023-11-15 13:43
### QA Update: ❌ 

@zutigrm I have a few observations to share with you:

> During site kit setup, when redirected to OAuth flow and asked to grant permission, click cancel
Permission error notification should show with redo the plugin setup CTA

1. Two permission notifications appear. This is a regression because it doesn't occur in the latest release. 

![image](https://github.com/google/site-kit-wp/assets/73545194/c1ef4468-d90c-4084-9331-00c20a98df9b)

>  Granting that permission, going back to complete the setup for analytics, web data stream should be successfully created without asking again for permission/redirecting to the OAuth

2. The first part of the QAB works, I see the Permission error and renders `Grant permission CTA`. When I click on the CTA, I am taken to oAuth to give permission to create the new web stream.  Once permission is given, I am redirected back to the dashboard. What I noticed, though, is that the Analytics CTA on the dashboard says 'Complete setup' 

![image](https://github.com/google/site-kit-wp/assets/73545194/6e905193-56d8-4970-80e0-f8c0a72703a1)

![image](https://github.com/google/site-kit-wp/assets/73545194/4decbcba-1830-4f52-bb2c-b6cac8e39a25)

**Comment by zutigrm** [comment] 2023-11-15 13:50
@wpdarren Thanks for the update. 

1. This is weird, haven't seen that before, will inspect what's happening
2. Yes, as mentioned in QAB, the `Grant permission` button will grant the last declined permission, it will not handle the setup, it will only ensure that when you got to complete setup next time you will be able to do it, since permission for that step is satisified, vs old flow where you would be taken again to grant the permission

**Comment by wpdarren** [comment] 2023-11-15 13:58
@zutigrm apologies, I misunderstood! Yes, that makes sense on point 2.  Let me know if you need any more information regarding point 1.  I was able to recreate this a few times, and I am happy to jump on a huddle if you can't recreate it.

**Comment by wpdarren** [comment] 2023-11-16 02:18
### QA Update: ✅ 

**Verified:**

- During site kit setup, when redirected to OAuth flow and asked to grant permission, I clicked cancel and the 
`Permission error notification` shows. with `redo the plugin setup` CTA
  - The issue with two banners appearing as mentioned above is fixed. 
  - Tested this with and without Analytics included in the set up. 

![image](https://github.com/google/site-kit-wp/assets/73545194/607db676-9ef9-4e45-b0ae-7a9a58a5f5e0)

- After setup is done without Analytics, and then proceeding to connect Analytics module, then canceling the permission grant, the `Permission error` does not render a CTA

![image](https://github.com/google/site-kit-wp/assets/73545194/77f00fe3-752c-4c54-94fb-27bf7d15e685)

- During the Analytics module setup, when asked to choose account, property and web data stream, I selected to create new web data stream, and then cancelled the permissions when redirected to OAuth. The `Permission error` did render with `Grant permission` CTA.

![image](https://github.com/google/site-kit-wp/assets/73545194/239a2e8e-498b-40b7-a1d1-5ea84b1dbd9d)

- Granting that permission, going back to complete the setup for analytics, the web data stream was successfully created without asking again for permission/redirecting to the OAuth.

**Closed** 2023-11-16 21:11 UTC
Labels: P1, Type: Enhancement
