### ISSUE TITLE
Improve translations: avoid concatenating strings

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#1952] opened 2020-08-25 14:59 UTC
## Bug Description

Concatenated strings cause problems in the context of translations and we should avoid them in our codebase. In `assets/js/components/notifications/invalid-credentials-warning.js` We concatenate a string to insert a link in the middle of a sentence (after "Please"):

![image](https://user-images.githubusercontent.com/2676022/91190298-aaa82400-e6b0-11ea-99c0-1e62c6977e82.png)

These strings should be combined, then the link can be added after the text with the CTA/Button "Reauthenticate"

`We’re unable to retrieve your data because your security token is expired or revoked. Please reauthenticate your account.`

[Reauthenticate] (Button)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment] 2020-09-22 17:24
I accidentally opened #2049 which somewhat is a duplicate of this, but since I already worked against that, I'll close this one.

**Closed by felixarntz** 2020-09-22 17:24 UTC
Labels: Good First Issue, P1, Type: Bug
