### ISSUE TITLE
Migrate Search Console page "Overview" widget to use Widget API

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2063] opened 2020-09-18 00:01 UTC
The "Overview for the last x days" widget on the Search Console module page should be refactored as a new component that is registered and rendered using the Widget API.

The existing component should be untouched and only be renamed, giving it a `Legacy` prefix.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component `ModuleOverviewWidget` should be added in `assets/js/modules/search-console/components/module/ModuleOverviewWidget.js`.
* It should be implemented as a functional, hook-based, datastore-driven widget component that renders a new version of the existing "Overview for the last x days" block on the Search Console module page, in a refactored way
    * It should display similar metrics to what the legacy `SearchConsoleDashboardWidgetOverview` and `SearchConsoleDashboardWidgetSiteStats` components display.
    * **However, the UI should be slightly different from the current version:** It should follow the same conventions and use the same visual components as the overview graphs on the Analytics and AdSense modules pages respectively.
        * It should no longer be possible to have multiple metrics selected at the same time; i.e. the graph should always have only one x-axis.
        * The graph line chart should also include the dashed line for the previous period (i.e. extra metrics need to be included here).
        * At a high level, even though this refactoring here also changes the expected behavior, at the same time it makes it simpler in some ways as a similar component implementation that was used for the refactored Analytics and AdSense module page overview widgets can be reused here (see the components from #2067 and #2065).
    * Sub-components can be implemented as necessary. If reusable, they should go into `assets/js/modules/search-console/components/common`. Otherwise (if specific to just this widget), they should go into a new `assets/js/modules/search-console/components/module/ModuleOverviewWidget` directory; in this case, the main widget component should go into the `index.js` file within that directory.
* The new component should be used to register a new widget in `assets/js/modules/search-console/index.js` (for testing, requires to enable the `widgets.moduleScreens` feature flag):
    * slug: `searchConsoleModuleOverview`
    * width: `WIDGET_WIDTHS.FULL`
    * priority: `1`
    * wrapWidget: `false` (since it needs to render `Widget` manually to add the `Header` prop
    * widget area: `AREA_MODULE_SEARCH_CONSOLE_MAIN`
* `SearchConsoleDashboardWidgetOverview` and `SearchConsoleDashboardWidgetSiteStats` should be renamed to have a `Legacy*` prefix added.

## Implementation Brief

* Implement requirements defined in the AC
More specifically:
* Look to the `AdSensePerformanceWidget` component for how to implement the Search Console Overview component (pictured below)
 https://github.com/google/site-kit-wp/blob/857b07eae65ad4f5ca367c4f8eccd48419a17411/assets/js/modules/adsense/components/dashboard/AdSensePerformanceWidget.js#L39-L84
* Note that the previous period for Search Console data should be selected, for an example using AdSense see: https://github.com/google/site-kit-wp/blob/857b07eae65ad4f5ca367c4f8eccd48419a17411/assets/js/modules/adsense/components/dashboard/AdSenseDashboardWidgetSiteStats.js#L38-L59. Unfortunately, the Search Console API does not support the `compareStartDate` options as it has no sense of a "previous period"—see comment https://github.com/google/site-kit-wp/issues/2063#issuecomment-802060619 below. The logic to be used for getting the reports ("previous" and "current") needs to request "both periods at once" and then separate out the data—get all dates inside `compareStartDate`-`compareEndDate` as the "previous" report, and all other dates as the "current" report. The old data request can be found here: https://github.com/google/site-kit-wp/blob/857b07eae65ad4f5ca367c4f8eccd48419a17411/assets/js/modules/search-console/components/dashboard/SearchConsoleDashboardWidgetOverview.js#L146-L159 and should be transferred to a `useSelect( ( select ) => select( MODULES_SEARCH_CONSOLE ).getReport() )` call that spans from the `compareStartDate` to the `endDate`, with the report then filtering out the relevant periods. (It might be nicer to modify the `getReport` selector to handle this automatically. What do you think @FelixArntz? It would mean more requests but our API would be more consistent and easier to reason about. 🤷🏻‍♂️ )
* Note that the [`selectedStats` behaviour](https://github.com/google/site-kit-wp/blob/857b07eae65ad4f5ca367c4f8eccd48419a17411/assets/js/modules/adsense/components/dashboard/AdSensePerformanceWidget.js#L49-L51) should also be copied—only one item should be allowed to be selected. Essentially, this sort of state:

<img width="1320" alt="Screenshot 2021-03-17 at 18 16 45" src="https://user-images.githubusercontent.com/90871/111517516-0faa9080-874d-11eb-8ae8-02c4fcbeecda.png">

should not be allowed. Only one stat can be selected at a time, eg:

<img width="1305" alt="Screenshot 2021-03-17 at 18 19 57" src="https://user-images.githubusercontent.com/90871/111517823-63b57500-874d-11eb-8dc4-d70c7153780d.png">

### Test Coverage

* N/A

### Visual Regression Changes

* The new Search Console widget will only allow for a single metric to be selected, so won't:
  * start with two metrics selected
  * allow 2, 3, or 4 metrics to be selected at the same time
  * ever hide the labels for metrics because no more than 1 (or 2) metrics can be selected

This won't affect VRT tests for legacy components, but it's worth highlighting.

## QA Brief
* Visit the "Search Console" dashboard.
* The new "Overview" widget should be displayed above the current legacy component. Both widgets, legacy and new one should display the same data.
* The new widget should not allow the selection of multiple metrics at the same time and there should be a graph line chart should also include the dashed line for the previous period.

## Changelog entry

* Migrate Search Console module page overview widget to use Widget API.

**Comment by felixarntz** [comment] 2021-03-15 17:58
@eugene-manuilov (or whoever is taking over this): I've previously accepted similar IBs for these refactored versions, since there was pre-existing code for pretty much everything that just needed to be copied/combined and since the ACs already had enough detail. In this particular case here though, the issue includes visual/functional changes from how the old component works so the IB should have _some_ detail on that: We need to use UI that is already present for e.g. the similar AdSense overview graph, but display the Search Console data in it. So something to particularly call out here is where the different pieces of logic would come from and, most importantly, how to call the Search Console API to get the data (e.g. to get every day's result for the previous period too, which is not included in the current version of the Search Console graph).

**Comment by tofumatt** [comment] 2021-03-17 18:28
I've taken this one over and since the [`getReport` selector for Search Console gets us the appropriate data](https://github.com/google/site-kit-wp/blob/857b07eae65ad4f5ca367c4f8eccd48419a17411/assets/js/modules/search-console/datastore/report.js#L38-L40) it seems the examples in AdSense code provided in the IB should be sufficient to give a sense of how to implement this component for Search Console data.

I explicitly highlighted the change in behaviour as well—this new component shouldn't allow more than one `selectedStats` value. 👍🏻

**Comment by felixarntz** [comment] 2021-03-18 16:17
@tofumatt There is a nuance with Search Console about getting data for the previous period that would be good to add to the IB. Although this has been relevant everywhere we do this in Search Console, let's clarify here too: There is no notion of previous period in the Search Console API, so we basically have to request both periods as a single period (`compareStartDate` as start, `endDate` as end) and then split the results in two halfs (previous period and current period).

**Comment by felixarntz** [comment] 2021-03-19 17:05
IB ✅ 

@tofumatt Regarding your question about date range splitting: It would be neat if the `getReport` selector for Search Console would automatically handle our regular 4 date range fields and combine them into a single request. However, the problem with that is then that the response would still include all dates together without any notion of what belongs to the compare period or current period, which would be confusing behavior IMO. At the same time, we shouldn't alter the shape of what it returns since then we would diverge from the API responses.

Let's think about this further (outside of this issue) - maybe we can just have two extra utility functions, one that "prepares report args for Search Console" and another one that "splits response based on report args" or something like that.

**Comment by wpdarren** [comment] 2021-04-01 14:32
### QA Update: Fail ❌ 

@asvinb I am unable to select more than one metric at the same time on the new "Overview" widget in Search console. 

https://user-images.githubusercontent.com/73545194/113309362-a70d0780-9339-11eb-87be-9417514e25c7.mp4

**Comment by wpdarren** [comment] 2021-04-01 15:00
### QA Update: Engineer to confirm ⚠️ 

@asvinb I tested the new "Overview" widget on a few mobile devices because of the changes and noticed that the graph is pushed slightly over to the right.  I know we've made changes to the graph, so this is probably the cause, but I am wondering if we can make use of that extra space?  I have two screenshots below. 

1) This is how the graph looks on the legacy widget.  - [Screenshot](https://user-images.githubusercontent.com/73545194/113312848-44b60600-933d-11eb-91c2-55e1e9d24f8b.png)

2) This is how the graph looks on the new widget - [Screenshot](https://user-images.githubusercontent.com/73545194/113312934-5c8d8a00-933d-11eb-8bd3-bc54cbf9ea86.png)

Only a minor observation because you can view the graph.

**Comment by aaemnnosttv** [comment] 2021-04-02 08:44
@asvinb looks like we need to adjust the `options.chartArea` (and maybe others) to account for there no longer being a text label on the vertical axis since only a single stat can be selected now.

**Comment by asvinb** [comment] 2021-04-02 11:10
@aaemnnosttv I've issued another PR to tweak the `chartArea` values. Can you check it out?

**Comment by aaemnnosttv** [comment] 2021-04-02 16:56
@wpdarren we've merged a follow-up PR which makes the chart area more consistent with what we currently have on AdSense for example, but there's still room for improvement IMO, but I'm opening a new issue for that.

Ready for another pass 👍

**Comment by wpdarren** [comment] 2021-04-05 12:41
### QA Update: Pass ✅ 

- The new "Overview" widget is displayed above the current legacy component. Both widgets, legacy and new one display the same data.
- The new widget does not allow the selection of multiple metrics at the same time and there is a graph line chart that includes the dashed line for the previous period.

![image](https://user-images.githubusercontent.com/73545194/113574646-18f19380-964f-11eb-9ccb-d751d41c14dc.png)

**Closed** 2021-04-08 18:02 UTC
Labels: Module: Search Console, P0, Rollover, Type: Enhancement
