### ISSUE TITLE
SiteKit conflict with Amelia Booking Plugin

### ISSUE THREAD

**Issue by seanmsmitty** [google/site-kit-wp#620] opened 2019-10-03 15:39 UTC
## Bug Description

The current build of Google Sitekit Version 1.0.0-beta.1.0.7 causes a conflict with the Amelia Booking plugin. When Sitekit is active, it renders the Amelia admin pages blank, making it difficult to manage appointments and tracking analytics for bookings and sales.

## Steps to reproduce

1. Login to the WordPress admin
2. Click on Plugins from the left menu
3. Click on "Add New"
4. Search for and Install the Amelia - Events & Appointments Booking Calendar plugin
5. Activate the Amelia plugin
6. Activate Google Sitekit
7. Click on Amelia from the left admin menu in the Wordpress dashboard.
8. View the Amelia dashboard as a blank page as caused by the conflict between Amelia and Google Sitekit.

## Screenshots

<img width="1680" alt="Screen Shot 2019-10-03 at 10 36 38 AM" src="https://user-images.githubusercontent.com/56125899/66141755-d4a0b580-e5c9-11e9-8882-ca2d18abe30b.png">

## Additional Context

 - PHP Version: 7.2
 - OS: MacOS Mojave 10.14.6
 - Browser: Chrome Version 77.0.3865.90, Safari Version 13.0.1
 - Plugin Version: Google Sitekit Version Version 1.0.0-beta.1.0.7, Amelia Version 1.0.8
 - Device: MacBook Pro 15 inch 2017

---------------

The following console error appears when  occurs when both Amelia Booking Plugin (free version 1.0.8) &  Site Kit plugin (1.0.0-beta.1.0.7) is active 
<img width="457" alt="Screen Shot 2019-10-07 at 11 13 07 AM" src="https://user-images.githubusercontent.com/41326532/66303677-750d1780-e8f3-11e9-9b1b-06b61e390041.png">

Also depending on the tabs clicked on other console errors appear:
`
util.js:226 Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
My.i @ util.js:226
(anonymous) @ js?key&libraries=places&ver=5.2.3:141
Promise.then (async)
(anonymous) @ js?key&libraries=places&ver=5.2.3:141
util.js:226 Google Maps JavaScript API warning: InvalidKey https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key
`

The following is the XHR Response 
![Screen Shot 2019-10-07 at 11 19 22 AM](https://user-images.githubusercontent.com/41326532/66304089-5c513180-e8f4-11e9-9b20-a9361f364aa8.png)

Google API PHP Client in use:
        "name": "google/apiclient",
        "version": "v1.1.8",
        "version_normalized": "1.1.8.0",

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment] 2019-10-04 10:32
@seanmsmitty Thanks for reporting. I will test out compatibility with this plugin. If you want to share your [Site Health information](https://i.imgur.com/Rtkmsba.png) I can setup the plugin alongside a similar environment, otherwise please let me know if you are using the free or pro version of this plugin.

**Comment by seanmsmitty** [comment] 2019-10-04 11:49
Hi James, thanks for your reply.

I am currently using the free version of Amelia with plans to upgrade to the pro version soon.

Here is my site health info as requested:

`
### wp-core ###

version: 5.2.3
site_language: en_US
user_language: en_US
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /www
wordpress_size: 43.89 MB (46021084 bytes)
uploads_path: /www/wp-content/uploads
uploads_size: 10.73 MB (11254815 bytes)
themes_path: /www/wp-content/themes
themes_size: 5.14 MB (5386917 bytes)
plugins_path: /www/wp-content/plugins
plugins_size: 91.19 MB (95620077 bytes)
database_size: 11.05 MB (11583488 bytes)
total_size: 162.00 MB (169866381 bytes)

### wp-dropins (1) ###

db-error.php: true

### wp-active-theme ###

name: Astra
version: 2.1.1
author: Brainstorm Force
author_website: https://wpastra.com/about/
parent_theme: none
theme_features: astra_hooks, align-wide, automatic-feed-links, title-tag, post-thumbnails, html5, post-formats, custom-logo, customize-selective-refresh-widgets, editor-style, woocommerce, amp, widgets, menus
theme_path: /www/wp-content/themes/astra

### wp-themes (1) ###

Twenty Nineteen: version: 1.4, author: the WordPress team

### wp-plugins-active (13) ###

Amelia: version: 1.0.8, author: TMS
Astra Premium Sites: version: 1.3.20, author: Brainstorm Force
Astra Pro: version: 2.1.1, author: Brainstorm Force
Elementor: version: 2.7.3, author: Elementor.com
Elementor Pro: version: 2.7.1, author: Elementor.com
Envato Elements: version: 1.1.3, author: Envato
Gravity Forms: version: 2.4.14, author: rocketgenius
Gravity Forms Zapier Add-on: version: 3.2, author: rocketgenius
SEOPress: version: 3.7, author: Benjamin Denis
SEOPress PRO: version: 3.7, author: Benjamin Denis
Site Kit by Google: version: 1.0.0-beta.1.0.7, author: Google
Ultimate Addons for Elementor: version: 1.18.0, author: Brainstorm Force
Wicked Folders: version: 2.13.4, author: Wicked Plugins

### wp-plugins-inactive (1) ###

Akismet Anti-Spam: version: 4.1.2, author: Automattic

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1673
imagemagick_version: ImageMagick 6.8.9-9 Q16 x86_64 2019-06-15 http://www.imagemagick.org
imagick_limits:
imagick::RESOURCETYPE_AREA: 16 GB
imagick::RESOURCETYPE_DISK: -1
imagick::RESOURCETYPE_FILE: 768
imagick::RESOURCETYPE_MAP: 16 GB
imagick::RESOURCETYPE_MEMORY: 8 GB
imagick::RESOURCETYPE_THREAD: 4
gd_version: 2.2.5
ghostscript_version: unknown

### wp-server ###

server_architecture: unknown
httpd_software: Flywheel/4.1.0
php_version: 7.2.20-2+ubuntu16.04.1+deb.sury.org+1 64bit
php_sapi: fpm-fcgi
max_input_variables: 4000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_size: 300M
php_post_max_size: 300M
curl_version: 7.47.0 OpenSSL/1.0.2g
suhosin: false
imagick_availability: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.6.32-1+deb.sury.org~precise+0.1
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $

### wp-constants ###

WP_HOME: https://stylemeupdigital.com
WP_SITEURL: https://stylemeupdigital.com
WP_CONTENT_DIR: /www/wp-content
WP_PLUGIN_DIR: /www/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`

Sean Smith
CEO
Style Me Up Digital
p: (913) 933-3410
w: stylemeupdigital.com

**Comment by jamesozzie** [comment] 2019-10-11 18:12
@seanmsmitty This plugin uses a Google API PHP Client which is likely conflicting with Site Kit. There is an open issue, #612 which you can keep track of. This will hopefully fix this incompatibility.

**Comment by seanmsmitty** [comment] 2019-10-11 20:23
Awesome! Thanks for the update James.

Sean Smith
CEO
Style Me Up Digital
p: (913) 933-3410
w: stylemeupdigital.com

**Comment by swissspidy** [comment] 2019-10-14 11:11
Closing as a duplicate of #612. Please follow that issue for progress 👍 

We can always reopen this one in case the problem persists even after that one has been fixed.

**Closed by swissspidy** 2019-10-14 11:11 UTC
Labels: Type: Support
