### ISSUE TITLE
"All users" metric remains at 0 despite traffic existing for sites with low numbers

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3073] opened 2021-04-01 17:14 UTC
## Bug Description

[One user in the support forums](https://wordpress.org/support/topic/dashboard-traffic-at-a-glance/#post-14265557) doesn't see any users when looking at their primary Site Kit dashboard. Despite the "Total Users" count being zero there are users evident in the graph below the user count. 

## Screenshots

![image](https://user-images.githubusercontent.com/41326532/113329172-2a683200-9315-11eb-94b9-977302a47312.png)

## Insights & Troubleshooting Checks performed 

- [x] Health Check & Troubleshooting plugin check
- [x] Incognito mode 
- [x] Checked users Site Health info, no obvious conflict although registered site on service looks to be http, despite site https (with redirection)
- [x] Additional .htaccess rules applied - Yes, applied
- [ ] Uninstalled and reinstalled plugin
- [ ] User confirmed no "Critical errors" in their Site Health status
- [ ] Attempted setup/viewing dashboards from another device 
- [ ] Temporary disabled WAF rules at host level - including ModSecurity
- [ ] Checked site setup and dashboard from another WordPress site on the same hosting platform
- [ ] Disconnected Site Kit
- [ ] Disconnected impacted service and connected once more
- [ ] Checked does the same occur from another admin users account
- [ ] Checked setup / viewing dashboards from another WordPress administrator account
- [ ] Reviewed error logs 
- [ ] Reviewed XHR requests 

## Additional Context

 - Occurs across all reporting periods select - although the 28 day period did show figures correctly at one point today during testing
 - [Site Health information provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit?urlBuilderDomain=google.com&gxids=7826#response=ACYDBNgrfjLG5eYNaDud1fqA7h4-FontEu_4EQrlhpBimLTTFnmAbhss4jChVpp_Fl4qTI8) - with the user kindly providing a video within the form

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment] 2021-04-02 10:30
I've been able to reproduce this in support on a site. The site doesn't have a high volume of traffic, but the same occurs. 
- No console errors or invalid XHR response
- Occurs across all reporting periods but inconsistently. Reload the page and it might show data for a 7 day reporting period only but not others. Revisit the page once more and it might show data for a 14 day reporting period only, but not a 7 day or 28 day reporting period

![2021-04-02-11-28-30](https://user-images.githubusercontent.com/41326532/113408188-cf7f1b00-93a6-11eb-9602-b35d476488d4.gif)




![2021-04-02-11-28-30](https://user-images.githubusercontent.com/41326532/113408098-9f377c80-93a6-11eb-8002-c532dcae67a7.gif)

**Comment by aaemnnosttv** [comment] 2021-06-09 08:08
@jamesozzie I've seen 0 users come back from the API for one of @cole10up 's sites which was quite new and didn't have much data, even though the chart was showing more than zero. This looks like a similar problem, but I've never seen the inconsistency like you're referring to here.

Do you have a site that I can see this on?

**Comment by jamesozzie** [comment] 2021-06-09 09:32
@aaemnnosttv Non at present but I did just setup a couple of new test sites. I expect I may be able to replicate it tomorrow with minimal traffic once there is data. 

On the site where I recreated this experience this was no longer occurring once there was more traffic. I'll keep you updated.

**Comment by aaemnnosttv** [comment] 2021-06-28 10:02
@cole10up is this something you can still see on any date range? If this was still an issue I would expect it would still show on the 90 day.

**Comment by aaemnnosttv** [comment] 2021-06-28 10:09
@jamesozzie can you see if this can still be reproduced?

**Comment by jamesozzie** [comment] 2021-06-28 17:35
@aaemnnosttv I have a couple of sites active that exhibit this behavior, both new domain setups, not registered with Search Console or Analytics previously. Happy to share a login. Some details below based on 1 site:

- No related console errors
- No invalid XHR responses
- Data does appear using the Analytics query explorer
- Based on previous tests this only occurs on new sites registered on Search Console. In my experience after there is more consistent traffic or after a period of time this no longer occurs

_Site Kit primary dashboard view below:_

![image](https://user-images.githubusercontent.com/41326532/123678859-c0d9c000-d83e-11eb-95c1-a7daffa6de1f.png)


_analytics.google.com view below:_

![image](https://user-images.githubusercontent.com/41326532/123678749-a0aa0100-d83e-11eb-84d5-81c92630c6ea.png)

_Analytics query explorer data below:_

![image](https://user-images.githubusercontent.com/41326532/123679470-6a20b600-d83f-11eb-9c43-0ed8ebe0e008.png)

**Comment by bethanylang** [comment] 2021-11-03 14:18
@felixarntz @aaemnnosttv @marrrmarrr Checking in on this one as it's been around for awhile and was reported by a user in the forums.

**Comment by aaemnnosttv** [comment] 2021-11-05 09:16
@bethanylang last I checked, this seemed to be independent of Site Kit as in it was entirely based on the request to the Analytics API.

From what I recall, it only happened when we were requesting the additional date range for comparison for the previous period. Do we have a site/property where this can still be observed? If so, I can take another look and get more details.

**Comment by bethanylang** [comment] 2021-11-09 18:34
@aaemnnosttv Thanks! This is out of Escalation since we had been able to replicate it, but not sure if we're still able to. @jamesozzie Can you please let us know if you're still able to replicate, and if so, share the appropriate site with Evan?

**Comment by jamesozzie** [comment] 2021-11-09 18:47
@aaemnnosttv @bethanylang Not a problem. I'll setup new domains with Search Console and let you know if I'm able to recreate it once more.

**Comment by aaemnnosttv** [comment] 2021-11-10 07:49
> I'll setup new domains with Search Console and let you know if I'm able to recreate it once more.

@jamesozzie I believe the issue here is specific to Analytics rather than SC. This is probably what you meant but just wanted to clarify 🙂

**Comment by jamesozzie** [comment] 2021-11-11 16:06
I can't recreate this on any test sites, including on [new domains with no previous GA data](https://i.imgur.com/REfpip1.png). 

@bethanylang Happy for me to close this for the time being while checking in with the user who reported this?

**Comment by bethanylang** [comment] 2021-11-11 16:25
@jamesozzie Yup, closing.

**Closed by bethanylang** 2021-11-11 16:25 UTC
Labels: Type: Bug, Type: Support, Module: Analytics
