### ISSUE TITLE
In proxy mode, splash screen should always show proxy setup UI

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#704] opened 2019-10-24 09:24 UTC
## Bug Description

In #642 a landing page for the authentication proxy setup flow was implemented. However, when directly accessing `/wp-admin/admin.php?page=googlesitekit-splash` after I've gone through the flow, I see the old splash page content that just provides information about the plugin.

When the proxy is in use, the splash screen should always show the new UI. The old content should remain around for non-proxy usage, but shouldn't display ever for proxy users.

We'd like to link users to that screen if they cancel at any point in the proxy setup flow or if they reset, but we need to rule out that they ever see the old screen content (unless it's local development / without proxy).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When manually accessing `/wp-admin/admin.php?page=googlesitekit-splash` (not linked anywhere typically after setup) in proxy mode, the screen should display the new proxy UI even when the connection has already been set up.

## Implementation Brief

* If there is a `googlesitekit.admin.proxySetupURL` present, we should _always_ show the setup flow in https://github.com/google/site-kit-wp/blob/29ab646f1d1b471fb590f6d43fdc00be61e4df50/assets/js/components/dashboard-splash/dashboard-splash-app.js.
* A straightforward way to do this is to add `! proxySetupURL && ` to the `if () {}` in https://github.com/google/site-kit-wp/blob/29ab646f1d1b471fb590f6d43fdc00be61e4df50/assets/js/components/dashboard-splash/dashboard-splash-app.js#L119
* @marrrmarrr pointed out in Slack that we might want to conditionally change this text if the user had previously authenticated but since revoked the plugin's access. @felixarntz: does the proxy code set a flag anywhere saying access was revoked? If so we could easily change the text to something like "Site Kit is no longer active because you revoked access from the authentication service; if you'd like to activate it again, start setup" if we know there _was_ authentication but it was revoked.

## Changelog entry

*

**Comment by tofumatt** [comment] 2019-10-24 16:50
Sorry, but could you attach screenshots to the pages you're encountering vs the pages you expect to see? I'm trying to re-create this but don't have a proxy site handy to test and currently the proxy is failing to authenticate me so I'm not able to reproduce this error. (My proxy sites are all temporary jurassic.ninja sites and I don't have an old one handy to test.)

**Comment by tofumatt** [comment] 2019-10-24 19:42
(Note: @aaemnnosttv walked me through these screens and steps-to-reproduce in Slack, no need to reply 😄)

**Comment by felixarntz** [comment] 2019-10-24 20:09
IB ✅ 

Let's not adjust the UI for now (also since there is currently no flag or anything like that). We can refine in the future if needed.

**Comment by tofumatt** [comment] 2019-10-24 21:16
In that case this is a very simple change; I'll get a PR sorted now 😄

**Comment by aaemnnosttv** [comment] 2019-10-25 11:18
### QA ✅ 

- Reset Site Kit
- Visit splash page
    - See proxy setup
- Setup Site Kit using GCP credentials
    - Visit splash page: see old splash page  
![image](https://user-images.githubusercontent.com/1621608/67567224-2bfdf580-f732-11e9-926b-7b16436adfbc.png)
- Filter proxy credentials (authenticated with GCP)
    - Visit splash page: see proxy setup  
![image](https://user-images.githubusercontent.com/1621608/67567239-34563080-f732-11e9-88e6-325fdda09f9b.png)

Moving to Approval.

**Comment by marrrmarrr** [comment] 2019-10-28 15:55
LGTM. Will update text in #724

**Closed by marrrmarrr** 2019-10-28 15:55 UTC
Labels: P0, Size: XXS, Sprint: 10, Type: Bug
