### ISSUE TITLE
GA4 > After successful set up GA4 banner showing when user click back to navigate on dashboard.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#5989] opened 2022-10-10 14:07 UTC
## Bug Description

After successful GA4 set up if user do not remove "GA4 successful set up banner". Then click on settings or any other tab and click on browser back button to navigate dashboard then 'Set Up GA4' banner showing again.

Expected : On Site kit dashboard "GA4 successfully set up banner" must display when user navigate back to dashboard through

## Steps to reproduce

1. Set up GA4.
2. Do not remove "Successful set up 
3. Click on settings.
4. Click on browser back button to navigate back to dashboard.
5. See "Set Up GA4 banner is showing.

## Screenshots

https://user-images.githubusercontent.com/94359491/194881109-4e3575cd-92dc-44db-aaa3-de58b7361400.mp4

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2022-10-11 23:17
This experience is consistent with others in the plugin and is due to the nature of how the back button works which is out of our control. For example, from the WordPress dashboard, if you log out via the admin bar, you'll land on `wp-login.php`. If you subsequently use the back button, you'll be "back in wp-admin" even though you're not actually logged in anymore. Your user isn't authenticated and can't actually perform any meaningful actions, but the dashboard would be visible in the same way here even though the user technically wouldn't be able to if they had navigated to the same URL as a new/forward navigation. This is because the browser is showing a cached state.

The same thing is happening in this case, and is possible in others as well. I'm not sure there is anything we can do to fix this as it seems to be standard browser behavior.

**Comment by hussain-t** [comment] 2022-10-12 06:32
I agree with @aaemnnosttv. Probably it might work some workaround with React-Router and dispatching some particular actions to keep the state synced. However, that's lots of work for a relative edge case that is out of control.

**Comment by FlicHollis** [comment] 2022-10-12 08:59
Thanks @aaemnnosttv and @hussain-t , Mariya also confirmed via Slack that this can be left as is. 
I will close this ticket and if we feel this needs addressing in the future we ca open a new one. 
cc @mohitwp @eclarke1

**Closed by FlicHollis** 2022-10-12 08:59 UTC
Labels: Type: Bug, P0
