### ISSUE TITLE
Introduce method for disabling auto-ads for logged-in users

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2681] opened 2021-01-25 08:48 UTC
## Feature Description

In #88 we introduced a new option for Analytics which controls the output of the tracking script specifically for logged-in users. By default, the module is configured to exclude tracking for logged-in users so the option essentially functions as a way to enable tracking for logged-in users which may be desirable in some cases (such as a membership site).

By contrast, AdSense does not have such an option and will be output regardless of user authentication.

Forum threads:
* https://wordpress.org/support/topic/is-there-a-way-to-show-ads-only-to-people-who-arent-logged-in/
* https://wordpress.org/support/topic/disable-site-kit-for-logged-in-administrator/

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a group of toggles within the AdSense settings panel that allows to not render auto ads...
    * ...either when the user is logged in (`is_user_logged_in()`)
    * ...or when the user is at least a contributor (`current_user_can( 'edit_posts' )`)
* The UI and technical implementation should mostly follow the approach that is used in the Analytics module (see particularly also the change made to that in #1891), with the auto-ads exclusions being saved as an array, supporting either a `loggedinUsers` ("All logged-in users") or a `contentCreators` ("Users that can write posts") entry.
    * What should be different though is the default value of the option: For the AdSense one, by default ads should show for everyone, for two reasons:
        * Not seeing ads is a more obvious change and users might be confused if they initially _don't_ see ads although they enabled everything.
        * Using another default then the empty array would disrupt existing sites since it would suddenly change behavior.

### Adding new settings to AdSense
* Inside the `Settings.php` class in the AdSense module, 
  * Add a `autoAdsDisabled` property to the array returned by `get_default`. It should point to an empty array by default:
  ```php
    protected function get_default() {
      return array(
        autoAdsDisabled => array(),
        /* ... */
      )
  }
  ```
  * Inside `get_sanitize_callback`, add a line that checks if the `'autoAdsDisabled'` option is set, and sanitises it if so:
  ```php
  $option['autoAdsDisabled'] = (array) $option['autoAdsDisabled'];
  ```
### AdSense guard class 
* Create a new AdSense guard class, `Google\Site_Kit\Modules\AdSense\Auto_Ad_Guard`, which implements the `Module_Tag_Guard` interface.
* Implement a `can_activate` method that will check if tracking is disabled or not:
	* grab the settings, e.g. `$settings = $this->settings->get();`
	* Return false if:
		* the settings array includes `loggedinUsers` and the current user is logged in (`is_user_logged_in();`) 
		* or  the settings array includes `contentCreators` and the current user is a content creator (`current_user_can( 'edit_posts' );`), 
		* otherwise return true. 
* Add PHP unit tests for the new class
* Add the new guard class to the tag instance in the `AdSense::register_tag` method

### JS / UI implementation
* On the JS side now, add a new component to the AdSense module, `assets/js/modules/adsense/components/common/AutoAdExclusionSwitches.js`
	* Grab the selector and action needed to access this setting in the store, i.e.:
	```js
		const autoAdsDisabled = useSelect( ( select ) => select( STORE_NAME ).getautoAdsDisabled() );
		const { setautoAdsDisabled } = useDispatch( STORE_NAME );
	```
	* Following the example in the Analytics module's `TrackingExclusionSwitches` component, render `Switch` components to allow the user to set whether auto ads are enabled or disabled for the given user groups.
		* Note that if `loggedinUsers` is selected, then the switch for `contentCreators` is hidden. See issue #1891 for more context.
* Update storybook with the new `AutoAdExclusionSwitches` component

### Test Coverage

* As described, we will need new PHP unit test coverage for the new Guard class. Existing tests may need to be updated to reflect the new settings. No tests needed on the JS side.

### Visual Regression Changes

* The images for the AdSense settings panel will likely need to be updated.

## QA Brief
* Test on a site where AdSense is connected and ads are showing on the FE
* Go to the AdSense settings and there will be toggles under "Exclude from displaying ads".
* Check different combinations and check if ads are not showing/showing on the FE.

## Changelog entry

* Add method for disabling auto-ads for logged-in users.

**Comment by jamesozzie** [comment] 2021-01-26 11:13
Similar GitHub issue exists at #828

**Comment by aaemnnosttv** [comment] 2021-01-27 08:54
Thanks @jamesozzie – I forgot about that one 👍  That issue is specific to admins though, while this is just about any logged-in user, just like we have with Analytics.

**Comment by frkn64modding** [comment] 2021-02-17 17:17
Hello, I am the person who created the forum thread, and I'm waiting for this feature for a long time. Is there any news?

**Comment by felixarntz** [comment] 2021-02-17 17:23
@frkn64modding Thanks, I've just prioritized this. We'll be able to ship this in the 1.28.0 release of Site Kit.

**Comment by frkn64modding** [comment] 2021-02-17 17:29
Great! Thank you very much for giving priority, @felixarntz.

**Comment by RalfKo** [comment] 2021-03-29 12:52
> @frkn64modding Thanks, I've just prioritized this. We'll be able to ship this in the 1.28.0 release of Site Kit.

hi, did not work out, didi it? (can't find it on the releasenotes)

**Comment by frkn64modding** [comment] 2021-04-13 11:44
> @frkn64modding Thanks, I've just prioritized this. We'll be able to ship this in the 1.28.0 release of Site Kit.

Hello, you mentioned that you will be able to ship this feature with 1.28 release. Today, version 1.30 has been released but the feature is still not added. I am still waiting for this.

**Comment by felixarntz** [comment] 2021-04-13 21:02
@frkn64modding Yes, apologies for this getting delayed a bit more. The issue is now ready to be worked on for engineering, so it should be in a release soon (I'd envision 1.31.0 or 1.32.0).

**Comment by tfk2** [comment] 2021-04-24 15:37
Am waiting to see this in 1.31/1.32
useful feature for sure
It will also positively affect the behaviour of Adsense and direct traffic, which can cause sometimes unfair adsense account suspensions.

**Comment by tfk2** [comment] 2021-04-27 09:26
oh i just got this. AdSense now ignores the analytics data for logged in users. I was kinda hoping I could just stop adsense entirely loading for logged-in users. 
logged in users are typically DIRECT traffic and AdSense doesn't like DIRECT traffic.

**Comment by eugene-manuilov** [comment] 2021-05-05 15:33
Thanks, @johnPhillips. The IB looks very solid. Just found two issues that we need to update in the IB. Could you please take a look at it?

> Add a autoAdsDisabled property to the array returned by get_default. It should point to an array, which contains the string 'loggedinUsers' by default

Let's not include `loggedinUsers` by default because it should be done intentionally and by a user.

> Inside get_sanitize_callback, add a line that checks if the 'autoAdsDisabled' option is set, and sanitises it if so:
> `$option['trackingDisabled'] = (array) $option['trackingDisabled'];`

It uses `trackingDisabled` key in your example. Could you please update it to use the relevant setting slug?

**Comment by aaemnnosttv** [comment] 2021-05-05 16:21
> Let's not include `loggedinUsers` by default because it should be done intentionally and by a user.

@eugene-manuilov I think @felixarntz may need to clarify this bit which is not explicitly mentioned in the ACs but this is how Analytics works which is the basis for the implementation here.

**Comment by johnPhillips** [comment] 2021-05-05 16:37
> It uses trackingDisabled key in your example. Could you please update it to use the relevant setting slug?
Thanks for spotting that @eugene-manuilov - edited.

> Let's not include loggedinUsers by default because it should be done intentionally and by a user.
Yes as @aaemnnosttv says I was working off the example in analytics. Happy to change this as required, just let me know. 👍

**Comment by eugene-manuilov** [comment] 2021-05-05 18:37
> > Let's not include `loggedinUsers` by default because it should be done intentionally and by a user.
> 
> eugene-manuilov I think felixarntz may need to clarify this bit which is not explicitly mentioned in the ACs but this is how Analytics works which is the basis for the implementation here.

@aaemnnosttv I think AdSense should have a different behavior because site owners make money using it and turning it off by default will break the cash flow for them :laughing: 

Assigned this ticket to @felixarntz for the final decision.

**Comment by felixarntz** [comment] 2021-05-05 21:08
@eugene-manuilov  @aaemnnosttv Good point, this was indeed missing from the ACs. I tend to agree the default should be the same as the current behavior, showing the ads for everyone because they are user-facing - i.e. not seeing ads although you configured AdSense may be unexpected and could result in various support requests, and due to the visual nature of the ads this is probably more sensitive than Analytics, for which the user would need to inspect the source code.

But I could also see from another perspective how showing the ads for logged-in users by default may skew interaction metrics (impressions vs revenue), so maybe the behavior _should_ be the same as in Analytics.

I'll clarify this with @marrrmarrr.

**Comment by marrrmarrr** [comment] 2021-05-17 13:45
@felixarntz it might make sense to be more granular here in terms of which segments of logged-in users this affects exactly. E.g. if a site has a set of users who pay to see the "ads-free" version but still see ads even as they log in as subscribers, that's suboptimal (example in the [original support thread](https://wordpress.org/support/topic/is-there-a-way-to-show-ads-only-to-people-who-arent-logged-in/)). 
But if they were the ones who set up the ads and then are wondering why they don't see them, that would also be suboptimal. 

How about adding the ability to disable ads per [user role](https://wordpress.org/support/article/roles-and-capabilities/)? So that e.g. subscribers would not see the ads, but editors would?

**Comment by frkn64modding** [comment] 2021-05-17 16:03
> How about adding the ability to disable ads per [user role](https://wordpress.org/support/article/roles-and-capabilities/)? So that e.g. subscribers would not see the ads, but editors would?

This is exactly what I need.

**Comment by felixarntz** [comment] 2021-05-19 15:54
@marrrmarrr The current approach is already to do it like we just recently established it in Analytics via #1891: You can either disable ads for all logged-in users or for only (logged-in) users that can create content - that should give the desired flexibility here while avoiding a ton of user-facing choices.

My question above is still valid though, what should the default value of these new toggles be? The same as today?

**Comment by marrrmarrr** [comment] 2021-06-08 10:54
@felixarntz keeping the UI copy to match what exists in Analytics SGTM:
- "Users that can write posts"
- "All logged-in users"

**Comment by felixarntz** [comment] 2021-06-08 18:59
@johnPhillips @eugene-manuilov @aaemnnosttv After revisiting with Mariya, the default for this setting should be different from Analytics, it should be essentially how Site Kit behaves now. I've clarified this in the ACs.

In other words, the following part of the IB needs to be changed:
> Add a `autoAdsDisabled` property to the array returned by `get_default`. It should point to an array, which contains the string `'loggedinUsers'` by default:

**Comment by felixarntz** [comment] 2021-06-09 15:33
IB ✅

**Comment by cbstudiomx** [comment] 2021-06-18 17:24
For the moment I change lines for render() function in the plugin files includes/Modules/AdSense/Web_Tag.php with this, and I have no auto-ads for logged in users, subscribbers and bbpress default user roles:

`protected function render() {
		// If we haven't completed the account connection yet, we still insert the AdSense tag
		// because it is required for account verification.
				$user = wp_get_current_user();
$allowed_roles = array('bbp_participant', 'subscriber');
if( array_intersect($allowed_roles, $user->roles ) ) {
} else {
		printf(
			'<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"%s></script>', // // phpcs:ignore WordPress.WP.EnqueuedResources.NonEnqueuedScript
			$this->get_tag_blocked_on_consent_attribute() // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
		);

		printf(
			'<script>(adsbygoogle = window.adsbygoogle || []).push(%s);</script>',
			wp_json_encode(
				array(
					'google_ad_client'      => $this->tag_id,
					'enable_page_level_ads' => true,
					'tag_partner'           => 'site_kit',
				)
			)
		);
	}
	}`

**Comment by asvinb** [comment] 2021-07-28 09:42
@aaemnnosttv @felixarntz @marrrmarrr There are some things missing in the AC, specially about the text to be used. Can you check the text in the screenshots below (Exclude from displaying ads section) :
![image](https://user-images.githubusercontent.com/31818/127300736-2a72cfbc-eac2-4bd3-9d55-07240ce7bc31.png)
![image](https://user-images.githubusercontent.com/31818/127300916-a5576c7c-5084-4537-b03c-16f43c5dd518.png)

Can you provide me with the correct text to be used or if you're fine with using what we currently have?

Thanks!

**Comment by marrrmarrr** [comment] 2021-07-28 10:45
Hey @asvinb, here are some suggestions on how to update this text: 

For the first screenshot: 
_Don't display ads for:_ (note the colon here)
_* All  logged-in users_
_* Users who can write posts_
_Ads will be displayed for all users_ (in the case where both toggles are off)

For the second screenshot: 
_Excluded from ads_
_Logged-in users_

**Comment by cole10up** [comment] 2021-08-10 18:22
### **QA ⚠️**

Toggled ads off:
![image](https://user-images.githubusercontent.com/57115907/128912893-c5b4743f-5217-439d-b714-8a1d10569361.png)

![image](https://user-images.githubusercontent.com/57115907/128913851-0c75abe6-6d2b-4c17-a97b-976737be57f0.png)

FE:
![image](https://user-images.githubusercontent.com/57115907/128912949-cb118b66-53a8-4cea-81fb-4ac7491a7c22.png)

Toggled ads on:
![image](https://user-images.githubusercontent.com/57115907/128913014-ba03d57a-7223-4cc8-abd7-543511757df4.png)

FE:
![image](https://user-images.githubusercontent.com/57115907/128913425-2dae03fd-9f04-452c-93eb-271071a73d53.png)

Toggled ads off for user's who can write posts:
![image](https://user-images.githubusercontent.com/57115907/128913553-6fdb4407-4c4d-485f-b6ad-d353f66e144e.png)

FE:
![image](https://user-images.githubusercontent.com/57115907/128913613-292ec7f1-e840-479d-881e-6efe6f12a7cf.png)

@asvinb - can we remove the period at the end of the sentence "Ads are currently displayed for all visitors."? Just to stay consistent with each message in the settings - this is the only sentence with a period.

**Comment by asvinb** [comment] 2021-08-11 12:03
Good catch @cole10up . Follow up PR has been created here:
https://github.com/google/site-kit-wp/pull/3829

**Comment by eugene-manuilov** [comment] 2021-08-11 12:31
@cole10up this is ready for another round of QA.

**Comment by cole10up** [comment] 2021-08-12 14:47
### **QA ✅**

Confirmed fixed.

![image](https://user-images.githubusercontent.com/57115907/129217784-2cae9970-2eb9-4a67-9022-0a57efddc768.png)

Sending to approval

**Comment by felixarntz** [comment] 2021-08-12 16:50
## Approval ❌

There's one problem in the implementation as far as I can tell - it may not be widely relevant, but I think https://github.com/google/site-kit-wp/pull/3770/files#diff-b23cf410a1dd58ea054aef1d56fa863889c75b7706748bfbfb503fd88c56b65bR34-R36 is problematic: _If_ for whatever reason the sub-setting to disable auto-ads is not set, the method should return `true` - since that is the default behavior. Otherwise we may unexpectedly not render the tags, which worst case would affect even the frontend for non-logged-in users.

I think in reality this value will always be set due to our defaults, but I think the logic here is still technically incorrect and risky and therefore should be fixed.

cc @asvinb @eugene-manuilov

**Comment by eugene-manuilov** [comment] 2021-08-12 17:06
Yes, good catch, @felixarntz. I have created a follow-up PR that updates it. Do you mind reviewing it? #3861

**Comment by felixarntz** [comment] 2021-08-12 17:39
Thanks @eugene-manuilov - with that change, this is good to release!

**Closed by felixarntz** 2021-08-12 17:39 UTC
Labels: P1, Type: Enhancement, Module: AdSense, Rollover
