### ISSUE TITLE
Site Kit is not recognizing web page having non-English version created through WPML

### ISSUE THREAD

**Issue by abdullah1908** [google/site-kit-wp#3125] opened 2021-04-12 12:53 UTC
## Bug Description

Site Kit is not recognizing web page having non-English version created through WPML. Its showing stats by [hovering on Site Kit tab](https://imgur.com/a/uSsaJDP) while we are logged -in. 

While clicking on Analytics details it shows as following:
It looks like the URL [site.com/es](https://imgur.com/a/rgDFYgP ) is not part of this site, therefore there is no data available to display.

**Actual URL of the website:** https://site.com
**Non-English version (i.e Spanish):** https://site.com/es

## Steps to reproduce

1. Setup WPML
2. Add a non-English language you want to add in the website
3. Select Language URL format as _**Different languages in directories**_
4. Create a non-English version of the post/page by clicking on plus sign.
4. Visit the frontend of the page/post while you are logged-in
5. On hovering Site Kit tab you'll see Analytics stats, click on [details](https://imgur.com/a/uSsaJDP).
6. You'll see [error](https://imgur.com/a/rgDFYgP)

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2021-04-13 10:55
Duplicate of #2862

**Closed by aaemnnosttv** 2021-04-13 10:55 UTC
Labels: Type: Bug
