### ISSUE TITLE
Analytics top acquisition sources: Referral traffic not counted 

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1554] opened 2020-05-13 13:44 UTC
## Bug Description

Site Kit is only displaying traffic acquisitions for organic, direct and social traffic. There is no referral traffic in the Site Kit pie chart despite referral traffic in Analytics Web UI (although 1.9% only)

Within Analytics web UI - 7 day report:
- Organic: 77.6%
- Direct: 17%
- Social: 4.5%
- Referral: 1.9%

![image](https://user-images.githubusercontent.com/41326532/81819205-eb779500-9526-11ea-9e7d-771a45787af0.png)

Site Kit
- Organic: 75.2%
- Direct: 19%
- Social (although labelled as Referral - separate issue as per #1553): 5.8%

![image](https://user-images.githubusercontent.com/41326532/81819789-b15ac300-9527-11ea-8b44-0f19f8b8dab9.png)

## Additional Context

- Personal site, happy to troubleshoot further
- Minimal referral traffic, possible reason
- Despite referral traffic missing in pie chart other sources amount to full 100% of traffic

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by cole10up** [comment] 2020-06-11 07:25
**Tested**

Installed lates SK, activated Analytics module. Opened Acquisition overview in GA and filtered by 7 days in both and compared.

![image](https://user-images.githubusercontent.com/57115907/84357003-d455b280-ab79-11ea-8511-a163df7b4ba4.png)

Notice SK shows 13 new users for referral

![image](https://user-images.githubusercontent.com/57115907/84357083-f2231780-ab79-11ea-90b5-d2f53ee80388.png)

Notice GA shows 10 referral and 3 social

![image](https://user-images.githubusercontent.com/57115907/84357126-023af700-ab7a-11ea-9cd3-c0a6fd1aec4f.png)

Looks to me that we're combining referral and social.

Sending to Execution.

**Comment by felixarntz** [comment] 2020-07-02 01:27
This is technically a different bug, but actually caused by the same problem as #1719. Let's track the work there and close this one which will be fixed by the other one at the same time.

**Closed by felixarntz** 2020-07-02 01:27 UTC
Labels: Group: Escalation, Type: Bug
