### ISSUE TITLE
Add visual indicator for GA4 vs. UA dashboard

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6938] opened 2023-04-20 12:08 UTC
## Feature Description

As reported by @bethanylang in Bug Bash:

I know that there's a toggle in Settings to indicate if you're using the GA4 vs. UA dashboard, but there isn't any indicator on the dashboard itself. Because users already get confused about what data is displaying in their dashboard (UA vs. GA4) even without having the option, it would be really helpful to have some kind of indicator on the dashboard to say if it's using GA4 or UA data. 

[Figma design from Sigal is available here](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=1%3A4962&t=qGcfLjAa00zlJ7KH-1) showing the green indictor for either "Universal Analytics view" or "Google Analytics 4 view."

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- Site Kit should have a chip indicating if the site is using the UA or GA4 dashboard view added to the Site Kit dashboard, if the `ga4Reporting` feature flag is enabled.
- The chip should be positioned to the right end of the title of the first widget area displayed in the Site Kit dashboard, according to [this Figma design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=1%3A4962&t=qGcfLjAa00zlJ7KH-1).
- The chip should exactly follow [this Figma design](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?node-id=1%3A4962&t=qGcfLjAa00zlJ7KH-1).
- The chip should say `Google Analytics 4 view` if the `analytics` `isGA4DashboardView` selector is truthy, otherwise say `Universal Analytics view`.
- This chip should be displayed in all Site Kit dashboard contexts, i.e. main, entity, and view-only.

## Implementation Brief

While it would be nice to solve this by including a badge in the `WidgetAreaRenderer`, having looked into it, it turns out to be rather difficult to determine which is the first area that's actually displayed on the page. Therefore, we take a simpler approach with a new component that we render above the first widget context.

Within new file `assets/js/components/DashboardViewIndicator.js`, create the `DashboardViewIndicator` component:

- Render a wrapper `div`, and a `Badge` within it.
- The `Badge` should display the label depending on the value of the `isGA4DashboardView()` selector, as per the AC.
- Add CSS classes to the wrapper `div` and the badge and style them to match Figma.
  - Note the badge should appear above the first area's title in mobile view, as per [Figma](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?type=design&t=0KB8qjwhj5BywtXS-0).
  - At non-mobile viewports, use a CSS technique e.g. absolute positioning for the badge so as to collapse the wrapper `div`'s height.

Create a new SCSS file for the styling: `assets/sass/components/global/_googlesitekit-dashboard-view-indicator.scss`.
- Refer to the styling for the "New" badge in `assets/sass/components/global/_googlesitekit-new-badge.scss` for pointers on the badge stying.

Within `assets/js/components/DashboardMainApp.js` and `assets/js/components/DashboardEntityApp.js`:
- Render the new `DashboardViewIndicator` component just below the `Header` / above the first `WidgetContextRenderer`.

### Test Coverage

- Add a story and VRT scenario for `DashboardViewIndicator`.
- Update any VRT reference images as needs be.
- Fix any failing tests.

## QA Brief

* Switch between the UA and GA4 dashboard views and make sure that the new dashboard indicator view badge is correctly displayed.
* Verify this on the mobile, tablet, and desktop screens.
* Make sure that the badge doesn't overlap any of the section title or subtitle text at various viewport widths (see https://github.com/google/site-kit-wp/pull/7053#discussion_r1196408655).
  * Test in view-only mode with only PageSpeed Insights shared, so we have the most amount of section title/subtitle text.
  * Test in different languages, looking for the widest title content.
* Ensure the chip doesn't appear when the Analytics module isn't connected.
* Verify the storybook [stories](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-dashboardviewindicator--dashboard-view-indicator-ga-4-view) for the DashboardViewIndicator component.

## Changelog entry

* Add badge to the dashboard to show which version of Analytics (UA/GA4) is used when connected.

**Comment by techanvil** [comment] 2023-04-20 12:18
I seem to recall this being spoken about at some point and a deliberate decision being made to not take this approach.

We'd better ask @marrrmarrr to confirm on this one.

**Comment by techanvil** [comment] 2023-04-20 12:25
Ah, ok cool - thanks for clarifying @bethanylang!

**Comment by tofumatt** [comment] 2023-05-05 11:52
IB ✅

**Comment by wpdarren** [comment] 2023-05-26 06:39
### QA Update: ⚠️ 

@hussain-t  the visual indicator appears even when `GA4Reporting` is not enabled.  

Reading the AC, it shouldn't be. I don't feel that this is an issue since the feature will be rolling out at the same time as this ticket is in production, but wanted to check. 

![image](https://github.com/google/site-kit-wp/assets/73545194/c0bf4885-966c-4b2f-a960-205b75f4cb71)

**Comment by hussain-t** [comment] 2023-05-26 09:23
Thanks, @wpdarren. Regarding your comments:

>the visual indicator appears even when GA4Reporting is not enabled.

Yes, according to the AC, it shouldn't be displayed. It's not an issue, as you mentioned. However, I'm happy to make the changes if it shouldn't be displayed at all if the `ga4Reporting` feature is not enabled. WDYT @techanvil?

>Also, in the AC it mentions that the chip should be at the right side of the title, which is fine on desktop, but on mobile and tablet, the indicator is above. This makes sense for mobile, but for tablet there is probably space to display it on the right. Looking in responsive mode it moves to above the title at around 959 pixels wide.

Initially, I implemented the chip to be displayed on the right for tablets. However, @techanvil spotted an issue with text overlapping with the chip. Please refer to this [comment](https://github.com/google/site-kit-wp/pull/7053#pullrequestreview-1430521395) for more information.

>What do you think as we don't have any designs for mobile/tablet in Figma?

There is a [Figma](https://www.figma.com/file/0UCIE3hPeiu4NYdpAODASd/GA4-Updates?type=design&node-id=1734-8492&t=0QtgQUx6svsTRolv-0) design for the mobile view.

**Comment by wpdarren** [comment] 2023-05-26 09:43
### QA Update: ⚠️ 

I will wait for clarification on the feature flag before moving this ticket to approval.

**Verified:**

- When switching between the UA and GA4 views the new dashboard indicator view badge is correctly displayed.
- Verified this on the mobile, tablet, and desktop screens.  Note that on mobile and tablet that the chip appears ABOVE the title and not to the right as mentioned in the AC.  Engineer confirmed that this is expected. 
- Made sure that the badge doesn't overlap any of the section title or subtitle text at various viewport widths. I also tested this with translation on.various languages including Vietnamese, Khmer, Arabic and Spanish. 
- Tested in view-only mode with only PageSpeed Insights shared.
- Verified the storybook stories.

<details>
 <summary>Details</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/d6d112c1-f320-4e86-82ed-6bab26632a84)
![image](https://github.com/google/site-kit-wp/assets/73545194/3f98277c-67cc-40f5-89a3-94777c93b838)
![image](https://github.com/google/site-kit-wp/assets/73545194/2e8605bc-db4b-49e0-b5f0-9216f11f2a8a)
![image](https://github.com/google/site-kit-wp/assets/73545194/a7cb1db7-f97e-4fd2-ba0d-cc2dced63687)
![image](https://github.com/google/site-kit-wp/assets/73545194/231338f1-0541-40db-b3a9-0fbbc3f3e1ca)
![image](https://github.com/google/site-kit-wp/assets/73545194/21754847-3019-4cb5-bd8f-a9ee0ad3c07e)
![image](https://github.com/google/site-kit-wp/assets/73545194/5cc58536-9de8-4deb-aa56-a62f027994fa)
https://github.com/google/site-kit-wp/assets/73545194/9596c238-d930-4bd5-a99d-66586eca0671
![image](https://github.com/google/site-kit-wp/assets/73545194/e97ef1a7-d39c-4e72-aca4-8118c4c1f9d1)

</details>

**Comment by techanvil** [comment] 2023-05-26 10:23
Thanks @hussain-t and @wpdarren.

I should have spotted the feature flag aspect during code review (and perhaps been more explicit when writing the IB). We should definitely be putting this behind the feature flag, regardless of the release schedule, so the feature flag works properly We tend to do a staggered release so without being behind the flag some users could get an odd experience. Or something unexpected could happen and we have to delay the release, and so forth.

**Comment by hussain-t** [comment] 2023-05-26 10:26
Thanks, @techanvil. I will create a follow-up fix shortly.

**Comment by hussain-t** [comment] 2023-05-26 12:25
@techanvil @wpdarren I have created a follow-up [PR](https://github.com/google/site-kit-wp/pull/7095) to fix this.

**Comment by wpdarren** [comment] 2023-05-29 12:28
### QA Update ✅ 

Went through all of the tests again and the visual indicator no longer appears when `GA4Reporting` is disabled.

![image](https://github.com/google/site-kit-wp/assets/73545194/138218b2-2990-4ea9-a807-c0e7a342f272)

**Verified:**

- When switching between the UA and GA4 views the new dashboard indicator view badge is correctly displayed.
- Verified this on the mobile, tablet, and desktop screens.  Note that on mobile and tablet that the chip appears ABOVE the title and not to the right as mentioned in the AC.  Engineer confirmed that this is expected. 
- Made sure that the badge doesn't overlap any of the section title or subtitle text at various viewport widths. I also tested this with translation on.various languages including Vietnamese, Khmer, Arabic and Spanish. 
- Tested in view-only mode with only PageSpeed Insights shared.
- Verified the storybook stories.

<details>
 <summary>Details</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/d6d112c1-f320-4e86-82ed-6bab26632a84)
![image](https://github.com/google/site-kit-wp/assets/73545194/3f98277c-67cc-40f5-89a3-94777c93b838)
![image](https://github.com/google/site-kit-wp/assets/73545194/2e8605bc-db4b-49e0-b5f0-9216f11f2a8a)
![image](https://github.com/google/site-kit-wp/assets/73545194/a7cb1db7-f97e-4fd2-ba0d-cc2dced63687)
![image](https://github.com/google/site-kit-wp/assets/73545194/231338f1-0541-40db-b3a9-0fbbc3f3e1ca)
![image](https://github.com/google/site-kit-wp/assets/73545194/21754847-3019-4cb5-bd8f-a9ee0ad3c07e)
![image](https://github.com/google/site-kit-wp/assets/73545194/5cc58536-9de8-4deb-aa56-a62f027994fa)
https://github.com/google/site-kit-wp/assets/73545194/9596c238-d930-4bd5-a99d-66586eca0671
![image](https://github.com/google/site-kit-wp/assets/73545194/e97ef1a7-d39c-4e72-aca4-8118c4c1f9d1)

</details>

**Comment by hussain-t** [comment] 2023-05-31 14:27
Thanks @kuasha420. I've created a follow-up [PR](https://github.com/google/site-kit-wp/pull/7113) to fix this issue.

**Comment by aaemnnosttv** [comment] 2023-05-31 20:06
@wpdarren back to you for another pass. It should now only appear if the feature is enabled, GA is connected, and (if on view-only dashboard) GA is shared with the user.

**Closed** 2023-06-01 13:44 UTC
Labels: P1, Type: Enhancement, Module: Analytics, Exp: SP, P1 High
