### ISSUE TITLE
Analytics Top content is sorted by title and not by views

### ISSUE THREAD

**Issue by gmmedia** [google/site-kit-wp#1867] opened 2020-08-04 05:44 UTC
## Bug Description

The Google Analytics **Top content** widget is sorted by the **title column** and not by the views column.

## Steps to reproduce

Same wrong sorting on the 3 pages:
* WordPress Dashboard widget
* Site Kit Dashboard
* Analytics

## Screenshots
![2020-08-04_074049](https://user-images.githubusercontent.com/7474702/89257311-3389ed80-d626-11ea-910d-50aed4cc3516.png)

## Additional Context

 - PHP Version: 7.3
 - OS: Win7
 - Browser: Chrome
 - Plugin Version: 1.13.0

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For Analytics top content displays (and underlying queries), results should be sorted by descending views/pageviews. Top content appears in the following locations:

  * WordPress Dashboard - "Top content over the last 28 days"
  * Site Kit Dashboard - "Most popular content"
  * Analytics Module page - "Top content over the last [28] days"

## Implementation Brief

* In `includes/Modules/Analytics.php`, in the handler for `case 'GET:report'`, in the orderby handling immediately following the inline comment `// Order by.`:
  * remove `[0]` from the `if` condition block which checks whether `$orderby` is a numeric array or not:
```js
// When just object is passed we need to convert it to an array of objects.
if ( ! wp_is_numeric_array( $orderby[0] ) ) {
	$orderby = array( $orderby );
}
```
* Create a new protected method `parse_data_orderby` in the `includes/Modules/Analytics.php` that accepts an instance of the `Data_Request` class and returns `$orderby` result using algorithm from the `GET:report` handler.
  * Create unit tests for this method.
* Update `GET:report` handler to use the new method to get orderby settings.

## QA Brief

* Go to each of the following pages and check top content report, it should be sorted descendingly by the number of page views.
  * WordPress Dashboard widget
  * Site Kit Dashboard
  * Analytics

## Changelog entry

* Fix regression where Analytics top content wouldn't be sorted correctly by views.

**Comment by adamsilverstein** [comment] 2020-08-04 18:01
Thanks for the bug report @gmmedia.

I can confirm I am seeing this as well, top content is sorted by page title in version 1.9.0:


![image](https://user-images.githubusercontent.com/2676022/89323522-11eb2f00-d643-11ea-9bc5-14d033b20bc0.png)


In 1.8.1 I see pages forted by descending Views:

![image](https://user-images.githubusercontent.com/2676022/89323328-bde04a80-d642-11ea-8e41-63113a013818.png)

Using `git bisect` I tracked down the issue to commit 2a0eb8f3e083108d497fa80a9a2e01752d8c46ff. After this commit, the sorting no longer works as expected. cc: @eugene-manuilov

**Comment by eugene-manuilov** [comment] 2020-08-04 19:46
Thanks @adamsilverstein! This issue is caused by a typo here: https://github.com/google/site-kit-wp/blob/897c92e479c3577ceceb3355b8c58c5c7287c4e3/includes/Modules/Analytics.php#L977

We don't need `[0]` there, it should be just `if ( ! wp_is_numeric_array( $orderby ) )`. Once it's removed, everything will work as expected. We need to udpate IB to state that we just need to remove `[0]` from that line.

**Comment by eugene-manuilov** [comment] 2020-08-04 20:49
IB is updated

**Comment by adamsilverstein** [comment] 2020-08-04 21:48
✅ IB looks good to me!

**Comment by eugene-manuilov** [comment] 2020-08-04 22:01
Created a new PR against `master` branch: #1875

**Comment by aaemnnosttv** [comment] 2020-08-05 17:03
@eugene-manuilov would you please add a QA Brief here so this can be merged?

Assigning to @felixarntz for a final pass on the PR.

**Comment by eugene-manuilov** [comment] 2020-08-05 17:34
@aaemnnosttv QA Brief is added.

**Comment by cole10up** [comment] 2020-08-05 19:05
**Tested:**

Installed 1.13.0 and activated SK and Analytics with a site having lots of data:

Notice error:
![image](https://user-images.githubusercontent.com/57115907/89451481-2564cb80-d711-11ea-9751-336cf93800ea.png)

![image](https://user-images.githubusercontent.com/57115907/89451598-4cbb9880-d711-11ea-8c91-986da39011f6.png)

![image](https://user-images.githubusercontent.com/57115907/89451873-b63ba700-d711-11ea-8f74-ef13e4844319.png)

Reset SK, uninstalled, deleted and installed 1.13.1. Activated SK and Analytics with the same above site:

Notice fix:
![image](https://user-images.githubusercontent.com/57115907/89452227-26e2c380-d712-11ea-8815-6cf96c06a709.png)

![image](https://user-images.githubusercontent.com/57115907/89452258-3530df80-d712-11ea-8c3c-7cb2f73e0d1f.png)

![image](https://user-images.githubusercontent.com/57115907/89452309-4bd73680-d712-11ea-95a1-4852e413e449.png)

Confirmed adjusting duration functions properly for sort:
![image](https://user-images.githubusercontent.com/57115907/89452559-b6887200-d712-11ea-8835-54a07cd59e90.png)

Checked each duration - confirmed functional
Checked links driving to GA - confirmed functional within SK

One thing to note - Clicking links within WP Dashboard drive to the actual page and not GA:
![image](https://user-images.githubusercontent.com/57115907/89452803-1717af00-d713-11ea-8992-0ee272892766.png)

![Dashboard ‹ Hellogoodbye — WordPress](https://user-images.githubusercontent.com/57115907/89452938-50e8b580-d713-11ea-95a2-5d1cb84b9055.gif)

Checked see full stats link - confirmed functional
Checked removing and re-installing analytics - confirmed functional
Checked adding new properties, views and accounts functions properly

![image](https://user-images.githubusercontent.com/57115907/89453279-db311980-d713-11ea-8227-4c2fc8d74745.png)

Passed QA ✅

**Closed** 2020-08-05 22:24 UTC
Labels: P0, Type: Bug
