### ISSUE TITLE
Graph Output Issues on 'Unique Visitors from Search' data within SK Dashboard URL-Specific Pages

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#3774] opened 2021-07-28 14:00 UTC
## Bug Description

While testing #1997 I noticed that the graph on the Site Dashboard URL-specific pages, underneath the `Unique Visitors from Search` is not functioning. Initially, I thought it might be related to the ticket, but could recreate the issue on the latest version (1.37.0).  There are two issues that occur with the graph as detailed:

1. When there is just 1 visitor from search, the graph does not fully display. 

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/b9f075d4-7689-468f-a577-7cfaa5d7ebc8)

2.  When you have a single digit value from search, the graph looks in a zero state. 

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/63d1f65d-3bce-4d31-b710-d6c564a9d070)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Analytics "Unique Visitors from Search" widget should render an accurate sparkline also in case there are fewer than 10 users. Right now the line in that case is flat (see screenshot above), when a few bumps of 1-2 users a day should probably be expected.
    * This may have some overlap with #4237, so make sure to cross-check (although that issue is purely focused on fixing the sparkline for the case of 0 visitors).

## Implementation Brief
* Create `assets/js/util/date.js` which contains date related utility functions.
	* Create new function `getDatesBetween` which returns an array of dates between 2 given dates. It should accept 2 mandatory parameters:
		* `startDate`
		* `endDate`
* Using `assets/js/modules/analytics/components/dashboard/DashboardSearchVisitorsWidget.js`,
	* Check if the number of rows in `sparkLineData` (exclusing the first line item which is the header) is less than the number of dates between the user selected range. This can be obtained by querying the `core/user` datastore via the `getDateRangeNumberOfDays` selector.
	* If it is less, it means that for some dates there are no data. Thus, call the `getDatesBetween` function to generate all the dates, passing the `compareStartDate` and `endDate` as parameters.
	* Loop through the array of dates and check if there is a value for the currently iterated date in the `sparkLineData` array.
	* In the date is not present in `sparkLineData`, add a new line item to the `sparkLineData` array with the date and a value of `0`.

### Test Coverage
* Tests for the `getDatesBetween` function

### Visual Regression Changes
* N/A

## QA Brief

* 

## Changelog entry

*

**Comment by asvinb** [comment] 2021-11-01 12:44
@wpdarren @felixarntz I tried to manually reproduce the issue and looks like when there's no data for a particular date, the date is not present in the returned data. Which might explain why there's no graph when the unique visitors are `0`. @wpdarren For the second issue for number 6, I don't think the issue is with single digits. Rather it might be that you had the same number of users across several days which totals to 6. For e.g you could have 1 single user every  6 days, or 2 users every 3 days which explains the flat line. That's the most plausible explanation so far since i can't really reproduce the issue.
@felixarntz The IB is basically to backfill the data with missing dates between a range , with `0` as value.

Let me know what you think.

**Comment by felixarntz** [comment] 2021-11-02 23:38
@asvinb Thanks, that explanation makes sense. @wpdarren Could you check on the site where you encountered the issue with the flat line for a count >0 <10 what the Analytics frontend shows you there? In other words, when you click on the Analytics source link below the flat chart, I'm curious what the chart for the same data in Analytics itself looks like. Is it also flat? When you hover over a particular day there, what are the numbers, are they really all the same?

@asvinb Since this issue is pending some follow-up by @wpdarren, maybe let's focus on #4237 for now (i.e. the 0 data issue). The current IB here is in parts related to that issue, so let's move the applicable parts over there.

**Comment by asvinb** [comment] 2021-11-03 09:06
Thanks @felixarntz I've copied the same IB over to #4237 since it's exactly the same thing. Hopefully the tickets which gets done first will fix both issues, i.e the current issue and #4237

**Comment by wpdarren** [comment] 2021-11-03 16:08
@felixarntz This was reported back in July so my memory is a little rusty, but I have found an example on the Dashboard URL-specific pages (`Detailed Page Stats` page), where this issue occurs as you can see from the screenshot. This issue does not occur on the main dashboard page from the testing I've completed.  

@asvinb  This example is on my live site so will give you access to my search console and analytics accounts then with the developer plugin you should be able to see the data.  Will send you a message on Slack. 

![image](https://user-images.githubusercontent.com/73545194/140097606-cb42fb59-985e-41f0-bec3-8e9c153a1bd0.png)

**Comment by felixarntz** [comment] 2021-11-03 18:35
@asvinb @wpdarren While debugging #4237 I found a solution for that problem, which could possibly solve the issue here as well. Since it's a rather obscure problem, maybe we should implement the fix there first and see whether it resolves the issue here too.

**Comment by asvinb** [comment] 2021-11-17 13:40
Sounds good @felixarntz . @wpdarren Can you check again once #4237 has been merged?

**Comment by wpdarren** [comment] 2021-11-17 16:13
@felixarntz @asvinb I have checked this on the same site I found the issue on and the line charts are now displaying as they should on the Dashboard URL specific pages. 👏 - [Screenshot](https://user-images.githubusercontent.com/73545194/142237090-9c865794-de22-4302-9094-972988c772ab.png)

**Comment by wpdarren** [comment] 2021-12-01 17:01
@asvinb  as per our Slack chat, yes, I think this can be closed because these issues were resolved with 4237.

**Comment by asvinb** [comment] 2021-12-01 17:04
@felixarntz @aaemnnosttv As per @wpdarren 's [comment](https://github.com/google/site-kit-wp/issues/3774#issuecomment-983840780) , we can close this issue.

**Comment by felixarntz** [comment] 2021-12-01 18:59
Excellent!

**Closed by felixarntz** 2021-12-01 18:59 UTC
Labels: Type: Bug, P2, Module: Analytics
