### ISSUE TITLE
Analytics: Inconsistent reporting periods / incorrect dates

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1099] opened 2020-02-05 10:46 UTC
## Bug Description

The Analytics dashboard in Site Kit shows inconsistent and possibly incorrect reporting dates based on dropdown selection selection, in particular 90 days reporting period. 

![image](https://user-images.githubusercontent.com/41326532/73834306-62541200-4803-11ea-94bd-a1f327d68bb9.png)

Examples below:

**From WordPress user**
Current date is Feb 5th 2020. Below are examples or incorrect reporting periods
- [7 days preview](http://www.mediafire.com/view/9nidky2h09h4hto/Screenshot%202020-02-05%20um%2009.16.14.jpg)
- [14 days preview](http://www.mediafire.com/view/zsz44b85goayyyp/Screenshot%202020-02-05%20um%2009.16.03.jpg)
- [28 days preview](http://www.mediafire.com/view/uqw5wjtouk84d7t/Screenshot%202020-02-05%20um%2009.15.48.jpg)
- [90 days preview](http://www.mediafire.com/view/kbv2vvbxzc5jwnp/Screenshot%202020-02-05%20um%2009.16.28.jpg)

Related WordPress support topic
https://wordpress.org/support/topic/wrong-date-with-analytics/

**Reproduced**

- [7 day preview: no issue](https://i.imgur.com/dMbIV1s.png)
- [14 day preview: no issue](https://i.imgur.com/1vXQRXg.png)
- [28 day preview: no issue](https://i.imgur.com/nr27CsT.png)
- [90 day preview: incorrect reporting periods](https://i.imgur.com/RxPE1lw.png)

## Additional Context

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The timeframe displayed in GA report should be within 1-3 days at most of the actual timeframe (i.e. if the user selects "90 days", the chart should display 87 days the least) 

## Implementation Brief

* When constructing the Analytics chart in `AnalyticsDashboardWidgetSiteStats`, add `hAxis.minValue` and `hAxis.maxValue` to the chart options:
  - In `extractAnalyticsDashboardData` - return `minDate` and `maxDate` values. `maxDate` is the date of the last returned entry. Because the query compares [two time periods](https://github.com/google/site-kit-wp/blob/2a960555bfdbbddcbd890d6751a138455109c0fa/assets/js/modules/analytics/util/index.js#L153) `minDate` is the date of the row that starts the latter half of the rows (`lastMonth`).
  - In `AnalyticsDashboardWidgetSiteStats`,  pass the min/max values to the call to `setOptions`:
`const options = this.setOptions( dataMap.minDate, dataMap.maxDate );`
  - Adjust `setOptions` to accept min/max values, using them for `hAxis.minValue` and `hAxis.maxValues`.

## Changelog entry

*

**Comment by hagbard231** [comment] 2020-02-06 15:15
Hi guys,
thanks for looking into this. 

The date issue of the Analytics section of SiteKit is really very weird in my Wordpress installation. When I'm clicking through the various tabs in Analytics the date in my timeline changes constantly. I made a screen recording for you:

https://www.mediafire.com/file/zl0fi20mv4tykwb/Site_Kit_Date.mov/file

Hope this helps to reproduce this behaviour.
Best
Hagbard

**Comment by adamsilverstein** [comment] 2020-02-06 22:02
@hagbard231 Thanks for reporting this issue. I believe the reported data is correct and the real issue here is with the chart labelling. 

Can you try a couple of things to verify that this is true:

* Check the your Analytics account data for the same 90 day period: do the numbers line up closely or exactly with what you see in Site Kit?
* Try making your window as wide as possible and/or reducing the view magnification (making the font smaller) - when I tried this I was able to see a start date that looked more accurate on the chart (generated Feb 6th):

![image](https://user-images.githubusercontent.com/2676022/73982385-f946ca00-48e8-11ea-995d-bccc5ddc3db6.png)

If these check out I would say we still have an issue we can _possibly_ improve - that is the date labelling isn't clear/accurate. However we are limited somewhat by the underlying (Google Charts) API we use to generate these graphs so I am not certain we can address this directly until we dig in a bit further.

**Comment by hagbard231** [comment] 2020-02-07 08:16
Hi Adam,
thanks for the tips. I compared the data for the 90 day period - and the data is fine. Unfortunately, I can't make my window wider - I'm working on a MacBook Pro and it's the max-width.

I dug a bit deeper into this and made you another screen recording:
When I'm on the range of e.g. 28 days, at first the dates are wrong. But with each click on the tabs, the timeline shifts a bit more until it sticks to a certain length. But this length does not represent 28 days. In the film, you can see that it's between 01-21-02 and 06-02-02. There are 16 days, not 28. The same is for the other time periods. It looks like the plugin is pulling more data each time I click on one of the tabs.

My website is really small and doesn't have a lot of traffic. So, for now, I can live with it - as It's only the visualisation, not the data itself.

**Comment by cole10up** [comment] 2020-02-27 05:52
Checking into this one, I'm able to reproduce this consistently.

Currently seeing what @adamsilverstein mentioned as the graph is off. Data isn't skewed.

90 day drop down shows only 85 days.

![image](https://user-images.githubusercontent.com/57115907/75416045-2bdd5480-58e2-11ea-8eb6-96d5d42def59.png)

![image](https://user-images.githubusercontent.com/57115907/75415993-11a37680-58e2-11ea-924e-74f396966abb.png)

Moving this to Execution.

**Comment by marrrmarrr** [comment] 2020-03-16 16:51
Idea from Felix and Adam: explore whether the chart library can display the exact start and end dates.

**Comment by adamsilverstein** [comment] 2020-04-20 13:48
Related docs on xAxis config: https://developers.google.com/chart/interactive/docs/customizing_axes - currently we do not specify any options here.

**Comment by adamsilverstein** [comment] 2020-04-20 14:46
Investigating this a bit further I determined that we can enforce the labels used for the left hand and right hand end of the x Axis using the minValue and maxValue properties: https://developers.google.com/chart/interactive/docs/gallery/linechart#configuration-options

eg for a chart for 90 days from 1/20-4/20 we would pass:
```js
			hAxis: {
				format: 'M/d/yy',
				gridlines: {
					color: '#fff',
				},
				textStyle: {
					color: '#616161',
					fontSize: 12,
				},
				minValue: new Date( '01/20/2020' ),
				maxValue: new Date( '04/20/2020' ),
			},
```
Resulting in a chart that tries to use those values for the left/right end regardless of available width:

![image](https://user-images.githubusercontent.com/2676022/79764730-fa31aa00-82e2-11ea-9650-7e040a9d165c.png)

![image](https://user-images.githubusercontent.com/2676022/79764948-411f9f80-82e3-11ea-82cf-b3f469e969a3.png)

This is a big improvement, although at very small sizes this stops working:

![image](https://user-images.githubusercontent.com/2676022/79765072-64e2e580-82e3-11ea-9440-d6b559ce676f.png)

**Comment by aaemnnosttv** [comment] 2020-04-22 16:09
@adamsilverstein `minValue` and `maxValue` seem to require a number but the IB references dates which I assume are strings.

![image](https://user-images.githubusercontent.com/1621608/80005594-776c4300-84cc-11ea-86d6-7fce82996357.png)
https://developers.google.com/chart/interactive/docs/gallery/linechart#configuration-options

Can you clarify?

**Comment by adamsilverstein** [comment] 2020-04-22 16:47
> @adamsilverstein minValue and maxValue seem to require a number but the IB references dates which I assume are strings.

The type of value depends on the way you have configures the x- axis. In our case, the type here is specified as "date" (https://github.com/google/site-kit-wp/blob/0eacc17f4c2627ad4f7e4ba81d666dbe3058d738/assets/js/modules/analytics/util/index.js#L147) and it is constructed from Date objects (https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics/util/index.js#L82-L84).  I tested the code in the IB and observed an improvement of the x-axis labeling. eg, adding:

```
minValue: new Date( '01/20/2020' ),
maxValue: new Date( '04/20/2020' ),
```
resulted in the chart showing those dates at the left and right hand end of the x axis (except at very small screen sizes).

**Comment by aaemnnosttv** [comment] 2020-04-22 17:09
Thanks for clarifying @adamsilverstein 

✅ IB

**Comment by ryanwelcher** [comment] 2020-04-23 17:03
After implementing the change in the IB, it seems that setting the min/max values doesn't address the issue of the date range being less than that queried range. As the min/max value needs to be set before and after the start and after the end range dates. 

In @adamsilverstein example, the dates being passed work but programmatically doing this is proving to be arbitrary as providing the offset numbers - for example offsetting the start date while working on this yesterday by 3 does display the correct range, but today it required 5.

I have found another option that may address this issue in https://developers.google.com/chart/interactive/docs/gallery/linechart#configuration-options called `viewWindowMode`.

When this is set to `pretty`, and no values are set for `minValue` or `maxValue`, the 90-day reports is displayed like this:

![viewWindowMode](https://user-images.githubusercontent.com/1259027/80118187-112c0280-8556-11ea-8300-1544e2803bb2.png)

**Comment by adamsilverstein** [comment] 2020-04-23 22:24
> As the min/max value needs to be set before and after the start and after the end range dates.

Ugh, really?! those showed the axis incorrectly when min/max are set to match the query? I must have been lucky the date i was testing this. I used the actual dates from the query and saw them displayed as the min and max values on the chart.

> When this is set to pretty, and no values are set for minValue or maxValue, the 90-day reports is displayed like this:

Thats great if that fixes it - the docs indicate that `pretty` is the default? Can you push a PR with this approach for testing?

**Comment by ryanwelcher** [comment] 2020-04-24 13:19
> ps. noticing in your chart, the ends of the graph part are empty which looks odd.

That's the way it gets rendered with the with `viewWindowMode` explicitly set to `pretty`. I agreed that it looks a bit odd though. The only other way I was able to get the dates to display was by increasing the range, ie `startDate - 5 days`.

**Comment by ryanwelcher** [comment] 2020-04-24 13:58
@adamsilverstein I've added the PR, it does push the ends of the graph out for all ranges. If we decide this isn't the best approach, I have the other approach in separate PR locally.

**Comment by adamsilverstein** [comment] 2020-04-27 13:20
Thanks for the careful exploration here @ryanwelcher. I feel like the solutions we explored weren't much of an improvement over (or are worse than) the current version. 

Ultimately, this feels like an upstream bug in Google charts or perhaps "expected behavior". Although the dates don't look great currently when displaying a large range (90 days), the data shown is correct, and even the date marking is correct, it just fails to mark the ends of the period which is confusing to users.

I recommend closing this issue and accepting the x-axis marking as a limitation of the Charts API.

**Comment by felixarntz** [comment] 2020-04-27 19:58
I think in terms of the ACs the solution using `viewWindowMode` set to `pretty` works fairly well. But there is the side effect of the graph now being pushed out.

Honestly, I think we are a little off the original goal of this issue. The real problem here was that the dates displayed were potentially _completely_ off (see screenshot in issue description). This is not about the date range being 5-7 days off just because these exact dates are not displayed, it's completely off there, as in more than 10 days, which shouldn't be just a UI problem. The "issue" that the first and last dates are not actually displayed is very minor I'd argue. This has been a while, have we actually been able to replicate a state similar to James's screenshot? I think this is the only thing we should fix here.

**Comment by felixarntz** [comment] 2020-04-27 20:00
I'm going to move this back into IB, let's try to figure out what was going wrong in the case of the issue description - how did the dates get off _so far_ in there?

**Comment by adamsilverstein** [comment] 2020-04-27 21:24
> I'm going to move this back into IB, let's try to figure out what was going wrong in the case of the issue description - how did the dates get off so far in there?

Reviewing the comments here, @hagbard231 mentioned that the graph changed each time they selected a tab (https://github.com/google/site-kit-wp/issues/1099#issuecomment-583282355) and attached a video. I watched the attached video and what is shows is repeatedly click back and forth between "Users" and "Sessions" with each click a little bit of the graph is removed until the far off dates we see in the screenshot are displayed.

I was able to reproduce this slightly with my data. On initial load of 90 days I see 1/29-4/24 which is correct.
![image](https://user-images.githubusercontent.com/2676022/80421770-38f2d180-889a-11ea-9be3-a3ad3f82ab67.png)

switching to sessions and back to users, the chart dates have changed: I now see 2/1-4/24 - I lost the last few days of Jan by switching "tabs" which feels like a bug. Apparently this user is loosing far more than that. 

I'm going to examine the code that switches this view to see if it might be mangling the data, perhaps something like 0 values being removed is causing this.

**Comment by felixarntz** [comment] 2020-05-12 18:10
Any update on this one @adamsilverstein?

**Comment by adamsilverstein** [comment] 2020-05-13 18:21
@felixarntz I haven't had a chance to look - thanks for the reminder. I will review this again.

**Comment by adamsilverstein** [comment] 2020-05-21 14:22
I have an update about the data discrepancy we are seeing here:

An apparent bug in the Analytics dashboard causes inaccurate date ranges used on the Analytics home page for the 90 day report. In particular, there is a **one day gap** between compared date ranges.

For example:

On May 15th I ran the 90 day report and by hovering over the chart I can see the start and end date of the reporting period.

The 90 day period compares:
Feb15-May14 (yesterday->90 days ago)
Nov 16-Feb 13 (92 days ago ->182 days ago?) - **note Feb 14th is missing**

When I use these date ranges for the 90 day period, the percent changes match - other than the user datapoint, which I am guessing is due to aggregation, like we saw with the total. Testing that and then I will add a new IB for this issue.

**Comment by adamsilverstein** [comment] 2020-05-21 22:01
One more update: Working on the IB I found that with the date modified I can reproduce every number exactly in my 90 day report **except user percent change**:

![image](https://user-images.githubusercontent.com/2676022/82610322-61a97680-9b7b-11ea-8eb9-48d6730afe43.png)

Still trying to determine the correct date/query/calculation used for this number, I've tried several variations.

Worth noting the date ranges shown in analytics suggest an aggregation by nth week (week of the year). In this short screencast you can see each data point is a week of data and the first and final weeks are partial weeks.

![Screen Recording 2020-05-21 at 11 48 AM](https://user-images.githubusercontent.com/2676022/82610702-19d71f00-9b7c-11ea-948d-a3df058a312b.gif)

**Comment by adamsilverstein** [comment] 2020-06-11 16:50
I re-tested this and was unable to reproduce the issues describe in the comment: https://github.com/google/site-kit-wp/issues/1099#issuecomment-583282355 

The primary issue raised here about the chart labeling feels like a very minor issue that is more of a limitations of the charts API. I suggest we close this as won't fix.

The most important points, which we have worked on getting right elsewhere are:
* The data shown for each period matches what the user would see on the Analytics dashboard.
* The dates/data remains stable even when switching "tabs" eg clicking "Users" "Session" etc. to see those graphs.
* The chart shows reasonably correct dates, even if the exact start and end dates are not shown.

**Comment by felixarntz** [comment] 2021-03-16 23:14
Closing as this seems no longer relevant.

**Closed by felixarntz** 2021-03-16 23:14 UTC
Labels: Good First Issue, Group: Escalation, P2, Type: Bug
