### ISSUE TITLE
Remove legacy wizard CSS classes from proxy splash screen UI

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2238] opened 2020-10-22 16:16 UTC
The default Site Kit splash UI (using the proxy) currently uses some CSS classes that are a remainder of the previous legacy setup wizard (which is only displayed when _not_ using the proxy). The default screen should be cleaned up to only use classes related to `googlesitekit-setup` instead of `googlesitekit-wizard` (the latter are the old classes).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The splash UI (using the proxy, i.e. `SetupUsingProxy` component) should not use any CSS classes start with `googlesitekit-wizard`. Instead it should use classes starting in `googlesitekit-setup`. New CSS classes may be added as needed.
* The splash UI furthermore should no longer use the class `googlesitekit-setup__footer` around its main UI (that doesn't make any sense, it's not a footer).
* Existing CSS rules should not be modified, unless it's certain that won't change anything in another screen.
* The appearance should not look different from how it is now.

## Implementation Brief
- Using the `/assets/js/components/setup/setup-proxy.js`
  - Update [class name]( https://github.com/google/site-kit-wp/blob/develop/assets/js/components/setup/setup-proxy.js#L118) from `googlesitekit-wizard` to `googlesitekit-setup` 
  - Remove the [container](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/setup/setup-proxy.js#L124) with the class name `googlesitekit-setup__footer` since it does not do anything.
  - Update [class name](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/setup/setup-proxy.js#L123) from `googlesitekit-wizard-progress` to `googlesitekit-setup__splash` 
- In `/assets/sass/components/setup/_googlesitekit-setup.scss`, add the following styles:
```
.googlesitekit-setup__splash {
	border-bottom: 1px solid #e6e6e6;
	padding-left: 10px;
	padding-right: 10px;
}

.googlesitekit-setup__splash .googlesitekit-setup__title {
	font-family: "Google Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
	margin: .67em 0;
}
```

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* Disconnect and reset the plugin
* Viewing the setup page - the layout should be visually identical to the pre-commit version.  
_Check for both default proxy and legacy (GCP) splash screens_

## Changelog entry

* N/A

**Comment by felixarntz** [comment] 2020-10-29 21:34
@asvinb 
> - Remove the class name from the title on the [following line](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/setup/setup-proxy.js#L155).

Why do we need to remove this class? Its class of `googlesitekit-setup__title` fits into the desired naming paradigm - is there styling that messes it up currently?

**Comment by asvinb** [comment] 2020-10-30 13:27
@felixarntz If we keep the `googlesitekit-setup__title` class, it'll introduce visual regressions on the splash screen. The reason being we already have some defined styles for `.googlesitekit-setup .googlesitekit-setup__title`. I don't think we need to add another class name to style the title whereas the default styles for h1 is enough.

**Comment by felixarntz** [comment] 2020-11-02 18:32
@asvinb I think in that case we should still make sure the CSS classes between the new and old screens are completely separated:
* Let's rename all classes in the old setup flow that start with `googlesitekit-setup*` to something like `googlesitekit-wizard*` and also migrate the style rules for those.
* Then let's use `googlesitekit-setup__title` and `googlesitekit-setup__description` for the respective pieces in the new UI and provide CSS rules as needed.

**Comment by asvinb** [comment] 2020-11-04 11:33
@felixarntz I updated the IB, let me know what you think. I'll bump the estimates to 3 just in case there are some visual regressions.

**Comment by felixarntz** [comment] 2020-11-04 16:47
@asvinb As far as I understand the updated IB, it sounds like the opposite of what should happen: The `SetupProxy` component should _only_ use classes like `googlesitekit-setup*` (which is the "new" setup flow), but now the IB says to rename some of those classes to `googlesitekit-wizard*`, which shouldn't be the case.

In the **old** setup flow, `googlesitekit-setup*` classes should be renamed to `googlesitekit-wizard*`, not in the new one.

**Comment by asvinb** [comment] 2020-11-06 09:45
@felixarntz The IB has been updated. Let me know if that makes sense now. Guess I was confused by the older setup flow and the new one. I've gone through the files in `/assets/js/components/setup-wizard` to check if we have any `googlesitekit-setup*` to be refactored to` googlesitekit-wizard*` and there is none. To cater for the issue I mentioned here: https://github.com/google/site-kit-wp/issues/2238#issuecomment-719551624, we'll be adding new class names to target the title on the splash screen and style it accordingly as per the IB.

**Comment by felixarntz** [comment] 2020-11-06 20:17
@asvinb IB ✅ 

One detail: I think `.googlesitekit-setup__splash .googlesitekit-setup__title` could be simplified to `.googlesitekit-setup__title`, which would be specific enough.

**Comment by benbowler** [comment] 2020-11-18 15:31
Hey @tofumatt, I'd incorrectly based this branch so it had some changes from other work, sorry about that. I've updated it now to include only these CSS changes. Best. Ben

**Comment by wpdarren** [comment] 2020-11-24 14:31
### QA Update: ⚠️ QA observation

@aaemnnosttv  

Observation: the proxy splash screen on the develop branch, there is not as much white space around the content.  It's very minimal to be honest but wanted to highlight. 
[Develop branch](https://user-images.githubusercontent.com/73545194/100107120-46aa1d00-2ea4-11eb-81a0-5131db1afc12.png) and [latest release](https://user-images.githubusercontent.com/73545194/100107240-69d4cc80-2ea4-11eb-8d75-a311e4befb3c.png) 

**Verified:**

- The splash page for default proxy and legacy on the develop branch display as latest release.  - 
[Screenshot 1](https://user-images.githubusercontent.com/73545194/100106425-7dcbfe80-2ea3-11eb-9bb5-4f1046270718.png)   [Screenshot 2](https://user-images.githubusercontent.com/73545194/100106460-87556680-2ea3-11eb-9b8c-61154df16a9f.png)

**Comment by aaemnnosttv** [comment] 2020-11-24 15:44
Thanks for raising @wpdarren. As far as I can tell there has been no change here between `master` and `develop`. See this screen cap comparing the proxy setup component (this shows a reconnect message but it's the same component – unfortunately we don't have a different state in storybook for that currently).

![Kapture 2020-11-24 at 17 37 46](https://user-images.githubusercontent.com/1621608/100116390-5a418d80-2e7c-11eb-8b60-05d3934d0c2e.gif)

As far as I can tell, the dimensions haven't changed between branches. Can you double check the numbers you're seeing in the devtools?

As for the legacy setup screen, we have this covered by an existing visual regression test using this view https://google.github.io/site-kit-wp/storybook/master/?path=/story/setup--step-one (not all stories have corresponding VRT tests though).

**Comment by wpdarren** [comment] 2020-11-24 16:29
@aaemnnosttv I've compared the dimensions between branches and I'm not seeing any differences.  When I looked at the CSS there's a margin-top and margin-bottom within `.googlesitekit-opt-in` on the latest release, but this does not appear in the develop branch. I think this could be the issue. 

`.googlesitekit-opt-in` on latest release  

![image](https://user-images.githubusercontent.com/73545194/100122751-b7f1cc00-2eb4-11eb-8148-ca015b8d3a5d.png)
 
`.googlesitekit-opt-in` on develop branch 

![image](https://user-images.githubusercontent.com/73545194/100122790-c3dd8e00-2eb4-11eb-931b-fa8ae9faf19e.png)

**More screenshots:**

Develop branch  - [Screenshot](https://user-images.githubusercontent.com/73545194/100122984-0010ee80-2eb5-11eb-8111-8b8243cbe564.png)

Latest release - [Screenshot](https://user-images.githubusercontent.com/73545194/100122958-f8e9e080-2eb4-11eb-9901-1d687f85c939.png)

**Comment by aaemnnosttv** [comment] 2020-11-24 16:34
I see what you mean now, you're right – good catch! Moving this back to execution for a quick follow up 👍

**Comment by aaemnnosttv** [comment] 2020-11-24 21:46
@felixarntz see my PR above to fix the issue that @wpdarren found.

**Comment by wpdarren** [comment] 2020-12-03 12:48
@aaemnnosttv @felixarntz I'm not seeing this fixed on `develop` branch. Please could you check that it has merged?

**Comment by aaemnnosttv** [comment] 2020-12-03 14:15
@wpdarren [it is merged](https://github.com/google/site-kit-wp/pull/2427#event-4064918214).

It may be though that the user input specific changes are only visible in non-release builds (i.e. using develop with the tester plugin won't work currently for testing features behind feature flags).

Can you maybe confirm using Storybook?
* https://google.github.io/site-kit-wp/storybook/develop/?path=/story/setup-using-proxy--start
* https://google.github.io/site-kit-wp/storybook/develop/?path=/story/setup-using-proxy--start-user-input

**Comment by wpdarren** [comment] 2020-12-03 14:29
### QA update:  Pass ✅ 

- Viewing the setup page - the layout should be visually identical to the pre-commit version. [Screenshot](https://user-images.githubusercontent.com/73545194/101039858-ebb8aa00-35b6-11eb-969f-27de7027d84f.png)
- Check for both default proxy and legacy (GCP) splash screens  - [Screenshot](https://user-images.githubusercontent.com/73545194/101039927-f115f480-35b6-11eb-9204-6554be736258.png)

**Closed** 2020-12-03 17:08 UTC
Labels: Good First Issue, P1, Type: Enhancement
