### ISSUE TITLE
Integrate `<ConversionTrackingToggle />` Component Into Ads and GA4 `<SettingsEdit />` Components

### ISSUE THREAD

**Issue by 10upsimon** [google/site-kit-wp#8618] opened 2024-04-25 09:33 UTC
## Feature Description

With the Conversion Tracking UI toggle component and associated settings/datastore now complete (see #8616), the toggle is ready to be integrated into both the settings _edit_ area of the Ads module, as well as the GA4 module.

This issue focusses on the _edit_ view of the settings area of said modules, i.e the `<SettingsEdit />` component of each module.

The enabled/disabled status for Conversion Tracking should be displayed in UI toggle form based on the state of the toggle (i.e if conversion tracking enabled (`true`) or disabled (`false`) via the applicable datastore selector). Toggling the element on or off will result in the applicable Conversion Tracking setting being updated, and UI reflected as such.

Please reference the _"Conversion Event Tracking Toggle & Settings"_ area of the design doc for more detailed information.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* `ConversionTrackingToggle` component implemented in [8616](https://github.com/google/site-kit-wp/issues/8616) should be added to the `SettingsEdit` component of `Ads` and `Analytics` modules

## Implementation Brief

* [ ] Update `assets/js/modules/ads/components/settings/SettingsForm.js`:
  * Include `ConversionTrackingToggle` component
  * It should be placed as on [figma design](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=1181-2559&mode=design&t=62S9Ke0zBYEQ1dJh-0) 
  * If needed styling can be applied in `assets/sass/components/ads/_googlesitekit-ads-settings.scss`
* [ ] Update `assets/js/modules/analytics-4/components/settings/SettingsForm.js`
  * Do the same as for Ads module settings form
  * Follow the [figma design](https://www.figma.com/file/THG1FJw5SaUxmiq38Mkf1x/Ads?type=design&node-id=1183-6953&mode=design&t=4wI79a5K8Xe3cFNU-0)  

### Test Coverage

* Update failing VRT

## QA Brief

**NON PAX:**
* Set up Ads in a non PAX manner, i.e using a regular conversion tracking ID entered into the field
* Navigate to Site Kit > Settings > Google Analytics
* Click the Edit CTA
* Validate that the Enhanced conversion tracking toggle is displayed as per the screenshot below

<img width="1283" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/22275980-f1af-4cae-b0b6-311f6878e495">

* Validate that toggling the value and saving persists the value on the next page load/reload

**PAX:**

* Set up Ads in a PAX manner, you can paste the following into console to fake this:

```
await googlesitekit.data.dispatch( 'modules/ads' ).setConversionID('');
await googlesitekit.data.dispatch( 'modules/ads' ).setPaxConversionID('AW-12345');
await googlesitekit.data.dispatch( 'modules/ads' ).setExtCustomerID('C-123456789');
await googlesitekit.data.dispatch( 'modules/ads' ).submitChanges();
```

* Navigate to Site Kit > Settings > Google Analytics
* Click the Edit CTA
* Validate that the Enhanced conversion tracking toggle is displayed as per the screenshot below

<img width="1282" alt="image" src="https://github.com/google/site-kit-wp/assets/72872375/6814f4eb-9938-4fdc-bbbb-1a1e6a28f707">

* Validate that toggling the value and saving persists the value on the next page load/reload

## Changelog entry

* Add a conversion tracking toggle to the Ads' module's settings page.

**Comment by 10upsimon** [comment] 2024-05-06 11:22
AC ✅ 

Moving to IB

**Comment by zutigrm** [comment] 2024-05-08 16:53
@eugene-manuilov Thanks, IB updated

**Comment by eugene-manuilov** [comment] 2024-05-09 11:53
Thanks, @zutigrm. IB :heavy_check_mark:

**Comment by mohitwp** [comment] 2024-06-05 13:31
### QA Update ❌ 

- Tested on dev environment.
- Verified Ads module edit settings view for non PAX manner and PAX manner. 
- Verified that toggling the value and saving persists the value on the next page load/reload.

@10upsimon 

**Issue**

If the user does not click the "Save" button after changing the toggle value, the toggle value is still getting updated under the settings view. Upon reloading the page, the toggle value reverts to its original status.

Expected Behavior: If the user does not click the "Save" button, the toggle value should not change under the edit view.

**Steps to Reproduce:**

1. Disable/Enable the toggle button.
2. Click on the "Cancel" button.
3. Notice that the toggle value updates as per the selection in step 1.
4. Reload the page.
5. Observe that the toggle value reverts to the value before step 1 because the "Save" button was not clicked.


<details>


https://github.com/google/site-kit-wp/assets/94359491/796c551f-4e6e-4171-be2c-4618dd4d2c59

</details>

**Pass Cases**
<details>

Ads module Non Pax manner

![image](https://github.com/google/site-kit-wp/assets/94359491/c444e3e8-4133-486a-a08c-e2474c125825)


**Ads module Pax Manner**


![image](https://github.com/google/site-kit-wp/assets/94359491/68b062c6-1c6f-40b2-acd6-95033602f860)


https://github.com/google/site-kit-wp/assets/94359491/f7c56803-0946-402f-b1c5-03c00270e16c


</details>

**Comment by zutigrm** [comment] 2024-06-11 09:39
@mohitwp This has been fixed in #8821 , you can confirm the fix there once it lands in QA

**Comment by mohitwp** [comment] 2024-06-13 12:47
**QA Update**

Blocked due to #8821.

**Comment by mohitwp** [comment] 2024-06-14 06:26
### QA Update ✅ 

- Tested on dev environment.
- Verified Ads module edit settings view for non PAX manner and PAX manner. 
- Verified that toggling the value and saving persists the value on the next page load/reload.
- Issue reported above is resolve under https://github.com/google/site-kit-wp/issues/8821.

<details>

Ads module Non Pax manner

![image](https://github.com/google/site-kit-wp/assets/94359491/c444e3e8-4133-486a-a08c-e2474c125825)


**Ads module Pax Manner**


![image](https://github.com/google/site-kit-wp/assets/94359491/68b062c6-1c6f-40b2-acd6-95033602f860)


https://github.com/google/site-kit-wp/assets/94359491/f7c56803-0946-402f-b1c5-03c00270e16c


</details>

**Closed** 2024-06-18 16:44 UTC
Labels: P0, Type: Enhancement, Module: Analytics, javascript, Module: Ads, Team S
