### ISSUE TITLE
The necessary verification token could not be found on your site.

### ISSUE THREAD

**Issue by userfriendly125** [google/site-kit-wp#151] opened 2019-07-06 20:39 UTC
## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment] 2019-07-08 10:23
@userfriendly125 Thanks for reporting. Do you mind trying to reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit) before attempting to install again? 

Please also install Site Kit by opening an incognito window, to ensure a new session and all potential conflicting browser extensions are inactive. If that fails please confirm the issue arises at the initial step stage (verification) and 

Duplicate of #85

**Comment by RockyIRL** [comment] 2019-07-12 14:27
I just had this issue. But it was due to my site being in construction mode.

**Comment by jamesozzie** [comment] 2019-07-17 16:15
@userfriendly125 Were you eventually able to setup Site Kit? If not please provide the following in order to troubleshoot further:
- Security / Caching plugins in use
- Any chrome console error messages that appear

**Comment by jamesozzie** [comment] 2019-07-25 09:43
@userfriendly125 I will close this issue as I didn't get a response. But feel free to reopen if the issue persists

**Closed by jamesozzie** 2019-07-25 09:43 UTC
Labels: Type: Support
