### ISSUE TITLE
Anonymize your IP address data in Google Analytics

### ISSUE THREAD

**Issue by sviluppomania** [google/site-kit-wp#33] opened 2019-06-21 13:20 UTC
Hello,
you should add the possibility to anonymize the IP address between the settings (Google Analytics) of the plugin, other plugins that integrate Analytics grant this possibility.

**Comment by jamesozzie** [comment] 2019-06-21 13:36
#18

**Comment by jamesozzie** [comment] 2019-06-21 13:39
Duplicate of #18

**Comment by sviluppomania** [comment] 2019-06-21 13:49
@jamesozzie 
There is a solution?

**Comment by jamesozzie** [comment] 2019-06-21 13:54
@sviluppomania I have marked this as an enhancement for further investigation on issue #18

**Closed** 2019-06-25 12:35 UTC
