### ISSUE TITLE
Inconsistencies between number of drafts in WP posts page and Drafts tab

### ISSUE THREAD

**Issue by simonchampion** [google/site-kit-wp#3856] opened 2021-08-12 16:13 UTC
## Bug Description

As I use the Idea Hub service more and more. and move ideas around between Saved, Drafts etc, I am finding inconsistencies between the counts in Saved and Drafts tabs, versus the number of Draft posts on WP posts page

For example, in WP posts page I have 4 draft articles, however on my Idea Hub module, I somehow have 2 in Saved and 2 in Drafts.

This seems to rectify itself after ~10 minutes or so. 
![image](https://user-images.githubusercontent.com/83005909/129231116-932b0b97-a5c5-4bc5-ae33-2bd576e55dfd.png)

![image](https://user-images.githubusercontent.com/83005909/129231138-55d3e3fe-7e83-4831-96b1-702f491ee58b.png)

**Mariya Moeva**
2 hours ago
_This seems to be a duplicate of another ticket we discussed yesterday, but I can't find it right now. Definitely something to be resolved._

**Asana** https://app.asana.com/0/1200491083500938/1200757691632158

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by eugene-manuilov** [comment] 2021-08-12 19:14
I can't reproduce it on my local machine. Perhaps Emily used not the latest version of the `develop` branch. @marrrmarrr did you see the same behavior or it worked for you?

**Comment by marrrmarrr** [comment] 2021-08-23 11:52
I can't reproduce this any more either. Closing.

**Closed by marrrmarrr** 2021-08-23 11:52 UTC
Labels: Type: Bug, P0, Module: Idea Hub
