### ISSUE TITLE
Continuous Analytics loading screen if GTM module is connected

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#7973] opened 2023-12-12 12:24 UTC
## Bug Description

If Tag Manager is connected within Site Kit, and you then try to connect Google Analytics, set up never completes, with the Analytics screen remaining in a loading state after OAuth. 

![image](https://github.com/google/site-kit-wp/assets/41326532/99e9648d-832e-405c-b1f7-81d0784522d3)

- There doesn't have to be any tags active in the connected GTM container
- There are no console errors or invalid XHR response
- Tested on 3 different sites with different hosting providers
- Discovered this while trying to recreate a previous issue #4082

For those impacted, one workaround is to reset Site Kit before including Analytics in the initial setup process. 

## Steps to reproduce

1. Set up SK without GA
2. Connect the GTM module (Ideally with a UA & GA4 tag active - may not be required, further testing underway)
3. Don't continue with GA set up once SK recognizes the GA tags and suggests you do so
4. Complete GTM setup
5. Revisit your GTM settings and toggle off the option for SK to place the GTM snippet
6. Connect the GA module
7. Continuous loading occurs

## Screenshots

![image](https://github.com/google/site-kit-wp/assets/41326532/05713a6c-d11c-4486-ab6d-38e70c0c32c9)

## Additional Context

 - SK 1.115.0
 - Tested on TasteWP, InstaWP and WebDock sites

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment] 2023-12-12 12:38
@jamesozzie Looks like this is a duplicate of #7961 and #7335. As [noted in Slack yesterday](https://10up.slack.com/archives/CBKKQEBR9/p1702309540231109), we're aware of this not working right now and are planning on updating this soon as part of the Singular Analytics Module epic. We'll create a separate set of issues for this work, so I'll close this out for now. Thanks!

**Closed by bethanylang** 2023-12-12 12:38 UTC
Labels: Type: Bug, Type: Support, Module: Analytics
