### ISSUE TITLE
Fix URL-based entity detection within the admin

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1978] opened 2020-08-31 19:23 UTC
As found during testing #1896, entity detection may not work correctly in the admin when viewing stats for the homepage. After some investigation, I found that this is because `WP_Query` looks at `is_admin()` as part of the logic to determine whether the current context `is_home`. Because the Site Kit URL details view is loaded in the admin, `WP_Query::$is_home` will never be set to `true` as it should - this is why the logic works in the frontend (e.g. for the admin bar) and passes our tests, but not within the backend.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* URL-based entity detection for the home page should also work within the admin.

## Implementation Brief

There is a single `is_admin()` check in `WP_Query::parse_query()` which causes this problem - everywhere else (fortunately) `WP_Query` seems to not rely on contextual information.

* Introduce `Google\Site_Kit\Core\Util\WP_Context_Switcher_Trait` with static methods `with_frontend_context()` and `with_admin_context()`, which allows to temporarily change WordPress context between frontend and admin (via `$current_screen`) and returns a closure to restore the previous context.
    * Implement the behavior by overriding the `$current_screen` WordPress global.
    * Document that the closure to restore should always be called as soon as possible after the context switch.
* In `WP_Query_Factory::from_url` use `WP_Context_Switcher_Trait::with_frontend_context()` before calling `WP_Query::parse_query`. Then restore the original context.
* In `Entity_Factory::from_url` use `WP_Context_Switcher_Trait::with_frontend_context()` before calling `WP_Query::get_posts` (unfortunately this re-parses the query, there is no way to get around it). Then restore the original context.
* Merge #1979.

## QA Brief

1. Use a site that has some stats on Search Console / Analytics.
2. Go to your home page and open the Site Kit admin bar menu.
3. Click on More Details.
    * Prior to this fix, you should see the box that is supposed to contain the title be empty. The stats there incorrectly display stats for the entire site, not the URL you're looking for.
    * After this fix, you should see the home page title in the box, alongside the correct stats.

## Changelog entry

* Fix bug with URL-based entity detection where home page stats in Site Kit URL details view would not show up as expected.

**Comment by aaemnnosttv** [comment] 2020-08-31 20:17
@felixarntz the IB looks good for the most part, but I think we can simplify this a bit.

Similar to `Module::with_client_defer`, we only really need a single method `with_context( $hook_name )` which might look something like this:

```php
with_context( $hook_name ) {
	global $current_screen;
	$previous_screen = $current_screen;
	$current_screen  = WP_Screen::get( $hook_name );
	// Returns a function which when called will restore the previous screen context.
	return function () use ( $previous_screen ) {
		$GLOBALS['current_screen'] = $previous_screen;
	};
}
```

It's still on the consumer to restore the previous context, but the utility class isn't needed for that as the restore function is provided.

Also, this can be used for any screen rather than only `admin` or `front`, but if we wanted an even cleaner API, we could have helper methods for these cases specifically,
e.g.
```php
with_front_context() {
	return static::with_context( 'front' );
}
with_admin_context() {
	return static::with_context( 'dashboard' );
}
```

What do you think?

**Comment by felixarntz** [comment] 2020-08-31 20:24
@aaemnnosttv I like that suggestion. I've updated the IB to rely on a `WP_Context_Switcher_Trait::with_context( $context )`. I think we can go with that for now instead of providing more specific methods. I'll update the PR shortly.

**Comment by aaemnnosttv** [comment] 2020-08-31 20:38
+1 for a trait here 👍 . As for the method name, maybe `with_current_screen` would be more accurate? I get the idea of "context" but we already have `Context` and `Entity_Factory::from_context` which are both different from each other and from this. It may also be a _little_ more clear that this is modifying the current screen.

How about `WP_Current_Screen_Trait::with_current_screen( $hook_name )` ?

**Comment by felixarntz** [comment] 2020-08-31 21:33
@aaemnnosttv I think `with_current_screen` is a bit too low-level. I could see us expanding the trait to support e.g. network admin at some point, but it shouldn't actually go as granular as per current screen since there wouldn't be a use-case for that I think.

But I agree the name could be improved. How about we do not expose `with_context( $context )`, but instead only `with_admin_context()` and `with_frontend_context()`? This is close to your suggestion above, and it clarifies what kind of context switching exactly this trait allows.

**Comment by aaemnnosttv** [comment] 2020-08-31 22:03
SGTM 👍 

IB ✅

**Comment by cole10up** [comment] 2020-09-09 06:24
**Tested**

Installed latest SK and checked admin on the home page:
![image](https://user-images.githubusercontent.com/57115907/92561885-e3580980-f229-11ea-961f-9a53d4ff0a6d.png)

Clicking 'More Details' link:
![image](https://user-images.githubusercontent.com/57115907/92561926-f8349d00-f229-11ea-964b-13d1bd49549f.png)

**Notice page stats link shows blank**

Checked individual page:
![image](https://user-images.githubusercontent.com/57115907/92562084-3df16580-f22a-11ea-8af9-ccd20522a589.png)

More details link:
![image](https://user-images.githubusercontent.com/57115907/92562109-4a75be00-f22a-11ea-9829-fd237a945e03.png)

Sending back to CR to check blank page stats for the Home page @felixarntz

**Comment by aaemnnosttv** [comment] 2020-09-09 07:17
@cole10up I just gave this a test and couldn't reproduce what you were seeing there.

I noticed in your screenshot thought that the tester plugin shows you're currently using the "latest release" rather than the develop branch so it seems you may have been testing the pre-fix version of the plugin.

After updating with the latest develop, the details page displays the entity information as expected:
![image](https://user-images.githubusercontent.com/1621608/92566853-84c07900-f285-11ea-8cbf-606e0f321cc4.png)

Sending this back to QA for a second pass 👍

**Comment by cole10up** [comment] 2020-09-09 16:20
After flipping to develop, clearing cache - I was able to see detailed pages stats for the home page.

![image](https://user-images.githubusercontent.com/57115907/92625594-b2092900-f27d-11ea-88b1-573d9de0a96c.png)

Thanks @aaemnnosttv for checking!

Passed QA ✅

**Closed** 2020-09-10 01:17 UTC
Labels: P0, Type: Bug
