### ISSUE TITLE
Fix flaky VRT tests.

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#6324] opened 2022-12-13 16:34 UTC
## Feature Description

We still have some VRT tests that are sporadically failing.

For example, in this test run, two unrelated VRT tests failed.

Test run: https://github.com/google/site-kit-wp/actions/runs/3686487465/jobs/6238780311

_Failed test cases:_
![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/9703f4a1-b8fe-41ea-ae97-7fdbc33b551e)

Looking at these a bit more closely it's evident the correct font hasn't loaded for the scenarios, for example:

_Reference:_
![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/e93dc02e-b624-48b2-9468-ae28dfe61738)

_Test:_
![image.png](https://images.zenhubusercontent.com/6133937d41f397090b8344a7/3216b2f5-7644-4b4e-be05-2041af7213e5)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The VRT workflow should not contain any test cases which sporadically fail.
* The fonts for VRT tests should always load correctly.

### Wait for web fonts to load

At present we have some code that is intended to ensure the web fonts are loaded before the VRT scenario is run. However, this is not functioning as intended and a fix is needed.

- Replace the call to `await document.fonts.ready` in `preview-head.html` with an `await Promise.all`, where the promises are the mapped result of calling `font.load()` on all the fonts in `document.fonts`.
- Remove `readySelector` from the global Backstop config where it doesn't have any effect and instead add the same ready selector to each scenario, ensuring that any scenario-specific `readySelector` is retained by appending it.
- See PR https://github.com/google/site-kit-wp/issues/6324, which can be finished off.

### Fix incorrect reference images

The following reference images have been generated with the wrong font, and should be regenerated:

- `google-site-kit_Modules_Analytics_Setup_SetupFormGA4Transitional_WithGA4AndUAExistingTag_0_document_0_small.png`
- `google-site-kit_Modules_Analytics_Setup_SetupFormUA_WithoutExistingTag_0_document_0_small.png`

### Remove `CoreSiteBannerNotifications` story

As discussed on Slack the `CoreSiteBannerNotifications` story is not a good example of a VRT story due to the long delay inherent in the story. Additionally, it's evident that neither `CoreSiteBannerNotifications` nor `CoreSiteBannerNotification` add any visual difference to the underlying `BannerNotification`, which has its own VRT coverage via `stories/notifications.stories.js`. Therefore the `CoreSiteBannerNotifications` scenario is superfluous for the purpose of VRT and can simply be removed. The behaviour of `CoreSiteBannerNotifications` can instead be tested using React Testing Library.

- Remove the `scenario` definitions for the stories in `assets/js/components/notifications/CoreSiteBannerNotifications.stories.js`.
- Remove the associated VRT reference files.

### Test Coverage

- Add a new JS test suite for the `CoreSiteBannerNotifications` component.

## QA Brief

* Verify VRT Tests are successful
* Verify the updates VRT reference images show the correct font families.

## Changelog entry

* N/A

**Comment by tofumatt** [comment] 2022-12-13 23:30
Marking this a P0 because it's messing with a lot of code reviews, and I added a note to the ACs about the font specifically, but ACs looks good 👍🏻 

Moving to IB.

**Comment by asvinb** [comment] 2022-12-15 14:07
Unassigning ticket since I'll be on PTO (16/12), but here are my updates:
* Definitely it's the font not being rendered. If we set the font display to `block` [here](https://github.com/google/site-kit-wp/blob/develop/.storybook/preview-head.html#L5), we can clearly see the font is not loading.
* Tried looking into installing the fonts directly in the container, however the font we are using are restricted. Might need some further exploration if we manage to get the ttf version of the fonts.
* Tried using `webfontloader` however issue still persists. https://gist.github.com/asvinb/3bc0bbf891ab417e675a0d6c64268505 Might need to tweak things to make things work.

**Comment by tofumatt** [comment] 2022-12-19 19:26
Thanks for checking into the failures and determining it's specifically that test. Sounds good to remove it then 👍🏻 

IB ✅

**Comment by aaemnnosttv** [comment] 2022-12-21 18:45
@techanvil I saw the above scenario in the settings fail again here:
https://github.com/google/site-kit-wp/actions/runs/3751886473/jobs/6373412417

![image](https://user-images.githubusercontent.com/1621608/208980307-f9d5f114-7929-4714-9b14-925e3baee573.png)

**Comment by techanvil** [comment] 2022-12-22 20:22
@aaemnnosttv hmm just seen it and a couple more fail again here: https://github.com/google/site-kit-wp/actions/runs/3760146657/jobs/6390542700

![image](https://user-images.githubusercontent.com/18395600/209218919-045ee15c-f847-48d5-adc1-162e1ad38cda.png)

![image](https://user-images.githubusercontent.com/18395600/209219108-c35469d0-cef4-448b-ba69-5549ebdcd55c.png)

The middle one's odd as only the service name is different!

Clearly, happening often enough that we still need to look further into it. I would suggest that we keep this issue as-is because removing the `CoreSiteBannerNotifications` scenarios is straightforward and will make things a lot more stable.

Then, we could follow up with an issue to dig into the font rendering in more depth. Possibly, locally reinstating `CoreSiteBannerNotifications` scenarios for the purposes of the investigation if that helps to reproduce it with the others failing only sporadically.

**Comment by techanvil** [comment] 2022-12-22 21:44
@aaemnnosttv, it looks like the VRT suite has become more flaky recently, I'm seeing consistent failures other than `CoreSiteBannerNotifications` in recent workflow runs.

At first I thought https://github.com/google/site-kit-wp/issues/1769 would be the most likely reason, but it doesn't seem to correlate.

I wonder if it's related to the `@storybook/react` version bump on Dec 19th, 3c0677b54aec5dc9c60c235d1b282f53daacf3a1 🤔

**Comment by techanvil** [comment] 2023-01-03 11:27
Moving this back to IB, as it's clear the current IB as specced is no longer sufficient to address the failures we are seeing in the VRT workflow.

**Comment by aaemnnosttv** [comment] 2023-01-04 18:18
Thanks @techanvil – nice detective work 👍 

Odd that `document.fonts.ready` is not working as intended. Apparently there is [a related bug raised in webkit](https://bugs.webkit.org/show_bug.cgi?id=174030) but I didn't see one in Chrome. At any rate, I'll be very happy if we can finally resolve this issue 😄 

The IB LGTM, the only thing is I think we'll want to allow for a little more time to cover the added JS tests that will replace the VRT for `CoreSiteBannerNotifications`. I'll bump the estimate to a 7 but feel free to amend that if you'd like.

IB ✅ ✅

**Comment by bethanylang** [comment] 2023-01-10 16:46
@derweili Moving this to Execution since you've assigned to yourself.  :)

**Comment by derweili** [comment] 2023-01-16 10:15
@wpdarren no I don't think so, at least I don't know what to add as QA:Eng.
I think it's enough to verify the updated VRT reference images are correct, and match the storybook stories.

**Comment by techanvil** [comment] 2023-01-19 16:47
## QA:Eng :white_check_mark: 

I've verified that the VRT references images are correct, in that they match the Storybook stories with the correct fonts and so forth.

However, I've noticed a bug in the Connect More Services story, and have created a separate issue to address it: #6438.

**Closed** 2023-01-26 22:00 UTC
Labels: P0, QA: Eng, Rollover, Type: Infrastructure
