### ISSUE TITLE
Console error on Site Kit dashboard when using PHP 8.2.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#6380] opened 2023-01-06 12:56 UTC
## Bug Description

I've noticed that when we are using PHP 8.2 then sometimes console error is showing on SK dashboard. There are no defined steps to reproduce this. This error is showing randomly when user visits SK dashboard.
`wp-auth-check.min.js?ver=6.1.1:2 Uncaught TypeError: Cannot read properties of undefined (reading 'hasClass')
    at HTMLDocument.<anonymous> (wp-auth-check.min.js?ver=6.1.1:2:655)
    at HTMLDocument.dispatch (load-scripts.php?c=0&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils&ver=6.1.1:2:43064)
    at y.handle (load-scripts.php?c=0&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils&ver=6.1.1:2:41048)
    at Object.trigger (load-scripts.php?c=0&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils&ver=6.1.1:2:71659)
    at HTMLDocument.<anonymous> (load-scripts.php?c=0&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils&ver=6.1.1:2:72254)
    at Function.each (load-scripts.php?c=0&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils&ver=6.1.1:2:3003)
    at s.fn.init.each (load-scripts.php?c=0&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils&ver=6.1.1:2:1481)
    at s.fn.init.trigger (load-scripts.php?c=0&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils&ver=6.1.1:2:72230)
    at Object.<anonymous> (heartbeat.min.js?ver=6.1.1:2:2186)
    at c (load-scripts.php?c=0&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils&ver=6.1.1:2:28327)`

## Steps to reproduce

1. Set Up  site using PHP 8.2.
2. Set Up Site Kit.
3.  Connect /disconnect modules.
4. Visit SK dashboard multiple times and try to reproduce the error.
5. I noticed this error on develop branch, but Adam getting this on main branch.

## Screenshots

![image](https://user-images.githubusercontent.com/94359491/211016621-bec016ea-479f-4bd2-a540-34b88bffe1b4.png)

## Additional Context

 - PHP Version: 8.2

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2023-02-16 20:43
This may not have anything to do with SK because WP does not fully support the latest versions of PHP 8 yet.

On a fresh install on PHP 8.2, you can see there are quite a few notices raised (if you have `WP_DEBUG` enabled), even without SK installed.

```
Deprecated: Return type of Requests_Cookie_Jar::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/Requests/Cookie/Jar.php on line 63

Deprecated: Return type of Requests_Cookie_Jar::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/Requests/Cookie/Jar.php on line 73

Deprecated: Return type of Requests_Cookie_Jar::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/Requests/Cookie/Jar.php on line 89

Deprecated: Return type of Requests_Cookie_Jar::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/Requests/Cookie/Jar.php on line 102

Deprecated: Return type of Requests_Cookie_Jar::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/Requests/Cookie/Jar.php on line 111

Deprecated: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/Requests/Transport/cURL.php on line 345

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php on line 40

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php on line 51

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php on line 68

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php on line 82

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php on line 91

Warning: Cannot modify header information - headers already sent by (output started at /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php:15) in /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-admin/includes/misc.php on line 1416

Warning: Cannot modify header information - headers already sent by (output started at /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php:15) in /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/functions.php on line 6865

Deprecated: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/Requests/Transport/cURL.php on line 345

Warning: Cannot modify header information - headers already sent by (output started at /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php:15) in /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-admin/admin-header.php on line 9

Warning: Cannot modify header information - headers already sent by (output started at /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php:15) in /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/option.php on line 1138

Warning: Cannot modify header information - headers already sent by (output started at /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php:15) in /home/rewukowiso2333/web/gucormorant-nuto.instawp.xyz/public_html/wp-includes/option.php on line 1139
```

I wasn't able to reproduce this on the SK dashboard though. The error itself does not seem to indicate SK as the source though. Closing for now!

**Closed by aaemnnosttv** 2023-02-16 20:43 UTC
