### ISSUE TITLE
Fix mid-way loading of Key Metrics Widget 

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7466] opened 2023-08-18 17:01 UTC
## Feature Description

As reported by @wpdarren in Bug Bash:

The key metrics widget suddenly appears when the Site Kit Dashboard is loaded.  This feels like an odd UI/UX.  Usually we would see the widget have a loading state before it loads, rather than loading when all of the other widgets have completed.  

## Additional Context

When the KMW is not set up, the KM Setup Banner CTA is displayed only if both SC and GA4 are not in a gathering data state. This information was preloaded to ensure the KMW area is either rendered or not without it "appearing" and pushing other content further down on the screen.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If the Key Metrics widget area is renderable (i.e. any of its widget CTAs or tiles are going to be rendered), then it should be rendered on page load without it "appearing" mid-way and pushing other content further down on the screen. (See Additional Context section above).
    * If the Key Metrics widget is not setup, the Key Metrics widget CTA should be rendered on page load.
    * If the Key Metrics widget is setup, the Key Metric tiles should be rendered on page load. The tiles themselves can have their loading state until their data is fetched.
    * In both cases, the Key Metrics Navigation Chip should also be rendered on page load and should be selected appropriately as per the AC of #7442. 
    * The Key Metrics widget area should not appear and then disappear as per the bug mentioned in this [comment](https://github.com/google/site-kit-wp/issues/7466#issuecomment-1727788613). Once loaded, it should stay consistently on the page.

## Implementation Brief

* NOTE TO IB AUTHOR: This issue might be fixed with the solution within #7442. 

### Test Coverage

* 

## QA Brief

* This issue should be QA'd as part of #7442.

## Changelog entry

* N/A

**Comment by tofumatt** [comment] 2023-08-28 14:38
ACs here are good; might be worth waiting to do the IB until #7442 is sorted 🙂

**Comment by bethanylang** [comment] 2023-09-07 13:37
Sounds great, thanks @jimmymadon!

**Comment by mohitwp** [comment] 2023-09-20 13:57
### QA Update ❌ 


@jimmymadon 

- Tested on dev environment.
- **Issue** >  I've noticed flicker when key metrics is not setup. Then on page load Key metrics set up banner quickly appears and hide 2 times before it shows up. 


https://github.com/google/site-kit-wp/assets/94359491/42e9e41b-17f5-4f31-b166-8f4347244842

**Comment by 10upsimon** [comment] 2023-09-25 08:56
@mohitwp (cc @jimmymadon @wpdarren  ) I've been largely unable to reproduce the loading issues, so I suspect that they were fixed as part of #7442.

I am attaching 2x screencasts, one showing the KMW set up CTA component, and another showing it post set up with 3 KMW tiles. Both appear to be loading as expected to me. 

In both cases, the components are loaded within a throttled 1mbps connection (which is by no means "fast"):

### 1. KMW Setup CTA Component:
https://github.com/google/site-kit-wp/assets/72872375/05b3acc4-e6ae-43fb-b6a8-3eaebc938787

### 2. KMW Component /w KMW Tiles Configured
https://github.com/google/site-kit-wp/assets/72872375/29d42305-062a-4521-a360-a1905aae12f0

@mohitwp I am assigning to you for now, and moving over to QA.

**Comment by mohitwp** [comment] 2023-09-25 10:31
@10upsimon I'm still able to reproduce issue on main branch.

- Tested on main branch.
- Tested using oi.ie site.
- Tested on chrome version - Version 116.0.5845.188
- Feature flag enabled - `ga4Reporting`, `AdsenseSetupV2` and `userinput`

cc @wpdarren can you please confirm if you are able to see flicker before KM CTA loads ?



https://github.com/google/site-kit-wp/assets/94359491/09e60e7a-d9a9-4e7a-96f9-5161ec85df9c

**Comment by wpdarren** [comment] 2023-09-25 10:47
@mohitwp  I am unable to recreate this.  I used Slow 3G on Chrome, using a Macbook Pro. 

https://github.com/google/site-kit-wp/assets/73545194/ff535515-3b6f-4d55-bfc5-b3bcb2e57b73

I noticed that you have 3 other feature flags enabled, could you share what those are other than userInput?

**Comment by 10upsimon** [comment] 2023-09-25 10:54
@mohitwp @wpdarren I am also unable to reproduce it on slow 3G, the render behaviour and end result is the same as my prior screenshots, save for maybe a few ms slower. I am only using the `userInput` flag.

**Comment by mohitwp** [comment] 2023-09-25 12:08
### QA Update ✅ 

- Tested on main environment.
- This issue is reproducible only on my system. [See this discussion](https://10up.slack.com/archives/CBKKQEBR9/p1695632322253109)
- @wpdarren @10upsimon are not able to reproduce this issue.
- We will keep a close eye on it and will create new ticket if it f it becomes more of a problem. 

@aaemnnosttv we can close this for now.

**Closed** 2023-09-25 15:18 UTC
Labels: P0, Type: Enhancement
