### ISSUE TITLE
Implement `<PublicationOnboardingStateNotice>` component

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#8838] opened 2024-06-08 10:06 UTC
## Feature Description

A `<PublicationOnboardingStateNotice>` component should be implemented for the Reader Revenue Manager module that renders a notice based on the onboarding state of the current publication.

<details>
<summary>Screenshot for reference</summary>

![image](https://github.com/google/site-kit-wp/assets/20284937/9bcf7fc9-f5b3-4ee7-b9e4-5d1b3a1c2329)

</details>

- [See relevant section in design doc](https://docs.google.com/document/d/14CxsQjTpdPrQpd8NoQtXnUd1DG7FVtmF5GTVvYdixVY/edit#bookmark=id.x1w8ud9hb76o).
- [See Figma designs](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=192-3190&t=44sz1QCJ3moErPIh-4)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A `<PublicationOnboardingStateNotice>` component should be added to the Reader Revenue Manager module according to [the Figma designs](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=192-3190&t=44sz1QCJ3moErPIh-4) that renders a notice based on the onboarding state of the current publication.
* If the current/selected publication is awaiting review or needs additional steps, that should be conveyed to the user via this notice, otherwise, it should output nothing.
* If the publication is awaiting review:
	* This can be determined if the onboarding state of the publication is `PENDING_VERIFICATION`.
	* Text: "_Your publication is still awaiting review. you can check its status in Reader Revenue Manager._"
	* CTA: "Check publication status" (with external link icon). This should open the publication in the publisher center in a new browser tab.
* If the publication needs additional steps:
	* This can be determined if the onboarding state of the publication is `ONBOARDING_ACTION_REQUIRED`.
	* Text: "_Your publication requires further setup in Reader Revenue Manager_"
	* CTA: "_Complete publication setup_" (with external link icon). This should open the publication in the publisher center in a new browser tab.

## Implementation Brief

Note: `PropertySelect` component in #8837 will be responsinble for setting the onboarding state in the settings using the `setPublicationOnboardingState` action. This has already described in IB for #8837.

- [x] Create a new component in `assets/js/module/reader-revenue-manager/components/common/PublicationOnboardingStateNotice`.
  - [x] Component should make use of `useSelect` hook to check for the `publicationOnboardingState` and call `getPublicationOnboardingState` selector.
  - [x] If the value of the onboarding is not `PENDING_VERIFICATION` or `ONBOARDING_ACTION_REQUIRED`, return null.
  - [x] If the onboatding state is within one of `PENDING_VERIFICATION` or `ONBOARDING_ACTION_REQUIRED`, display the notice text and CTA text as per AC mentioned above.
  - [x] Use the `SettingsNotice` component to display the notice. Pass following props to it.
    - [x] `Icon` - Pass `warning` as we need to display the warning notice.
    - [x] `notice` - This will be the notice text as per AC.
    - [x] `OuterCTA` - This should be CTA which will open the publication center (https://publishercenter.google.com/) in a new tab. Use `Link` component to display CTA link with `external` prop set to true. We should use `getServiceURL` selector to get the URL for the CTA. Pass publication ID to the selector.
- [x] Refer the [figma design](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=192-3190&t=v9UNhP1LBda84g0N-0) for `PublicationOnboardingStateNotice` component to match the notice component with the design.

### Test Coverage

Add tests for component with different onboarding states.

## QA Brief

- Verify the `Modules -> ReaderRevenueManager -> Common -> PublicationOnboardingStateNotice` Storybook story and verify that the notice looks according to the Figma designs and functions according to the ACs.
- This notice is rendered in the RRM module setup and settings screens when the selected publication does not have its onboarding completed. Verify that the notice appears correctly according to the Figma designs and acts according to the ACs.
	- If your selected publication already has its onboarding completed, or you do not have such a publication, this can be mocked by using the following script in the browser console:
	```js
	googlesitekit.data.dispatch( 'modules/reader-revenue-manager' ).setPublicationOnboardingState( "PENDING_VERIFICATION" );
	// You can also try `ONBOARDING_ACTION_REQUIRED` instead of `PENDING_VERIFICATION`.
	```
	- **Note:** Some of the spacings around the notice may not exactly match the Figma designs. This is expected and is consistent with reusable components used across other modules.

## Changelog entry

* Add the `PublicationOnboardingStateNotice` component, rendering a notice based on the onboarding state of the current publication and presented in Storybook.

**Comment by nfmohit** [comment] 2024-06-30 02:08
Thank you for the excellent IB here, @ankitrox !

One small point about the CTA link. We should use the `getServiceURL` selector with the current publication ID passed to get the URL for the CTA. Could you please update it?

Thanks!

**Comment by ankitrox** [comment] 2024-07-01 04:47
@nfmohit Thank you for reviewing the IB.

I've amended the suggested point. Assigning back to you.

**Comment by nfmohit** [comment] 2024-07-03 08:32
Thanks @ankitrox ! IB LGTM 👍 ✅

**Comment by kelvinballoo** [comment] 2024-08-02 12:05
### QA Update ⚠️ 

Couple of things to flag.
I understand that some of these could arise due to us trying to keep things consistent across the whole plugin and if that's the case, that's fine and these can be ignored. 

**ITEM 1:**
Colour of the icon with the exclamation mark is almost dark. It should have been brown at #4E3300
Also, the icon size is implemented as 19x19. It should have been 22x 22

<Details>
<img width="522" alt="Screenshot 2024-08-02 at 15 34 25" src="https://github.com/user-attachments/assets/9374a571-be22-4ebc-8f89-c5f9c5b8b807">

Icon size:
<img width="956" alt="Screenshot 2024-08-02 at 15 32 40" src="https://github.com/user-attachments/assets/0c2516c4-34a4-4d6e-8551-e2d11a801746">

Figma icon size and colour:
<img width="947" alt="Screenshot 2024-08-02 at 15 32 20" src="https://github.com/user-attachments/assets/20d3e51f-7726-469f-96bb-3d2517f1ac90">

</Details>

_________________________________________________________________

**ITEM 2:**

I could not verify the font weight of the CTA text "Your publication is still awaiting review. You can check its status in Reader Revenue Manager." as I could not see the attribute in dev tools.
It feels like it's 400 though.

Based on Figma, it's supposed to be 500px

<Details>
<img width="924" alt="Screenshot 2024-08-02 at 16 03 10" src="https://github.com/user-attachments/assets/65f10526-2279-485f-8a00-224c7c22af31">
</Details>


_________________________________________________________________

**ITEM 3:**
Marins around the button is supposed to be 18px top and bottom and 24px on the side.
Currently, it's 16px on all sides.

<Details>
**Figma:**
<img width="538" alt="Screenshot 2024-08-02 at 15 38 35" src="https://github.com/user-attachments/assets/8a1bbda2-8b6e-4ebb-8d0f-a4aa3c94cf62">

**Implementation:**
<img width="922" alt="Screenshot 2024-08-02 at 15 37 15" src="https://github.com/user-attachments/assets/7417da65-e1ed-4e06-a44f-62527890c17e">


</Details>

**Comment by ankitrox** [comment] 2024-08-05 05:58
As per the conversation in [this slack thread](https://fueled10up.slack.com/archives/C077DB69US2/p1722600439442479), this issue will be on hold in Execution till #8840 is merged so that we can use `SubtleNotification` instead of `SettingsNotice` and address other styling concerns that it may have.

CC: @kelvinballoo @wpdarren

**Comment by tofumatt** [comment] 2024-08-06 22:29
Just a note here, that the existing work merged in (see PR #9037) was entirely self-contained and only affected Storybook/Jest tests; the actual component is not yet in use anywhere and there are no other changes.

To simplify things I'm going to remove it from being tagged with the current release, since it's dependent on another issue (#8840), which won't be ready in time, and this issue will not be merged into this release (`1.133.0`).

Normally we'd revert this change from `develop`/`main`, but in this case we can simplify untag it. In the future please keep in mind issues that are tagged with the release should be removed if they won't be completed for the release 🙂

**Comment by ankitrox** [comment] 2024-08-08 12:44
As discussed previously, I have created a follow-up PR #9177  for this issue which uses `SubtleNotification` component. Also, there are couple of changes in `SubtleNotification` component to allow a notification without dismiss CTA and added related story for it.

Moving this for code review.

**Comment by nfmohit** [comment] 2024-08-22 00:37
Hi @kelvinballoo . This is now back with you for a re-check.

> **ITEM 1:**
> Colour of the icon with the exclamation mark is almost dark. It should have been brown at #4E3300
> Also, the icon size is implemented as 19x19. It should have been 22x 22

This has been fixed.

> **ITEM 2:**
> 
> I could not verify the font weight of the CTA text "Your publication is still awaiting review. You can check its status in Reader Revenue Manager." as I could not see the attribute in dev tools. It feels like it's 400 though.
> 
> Based on Figma, it's supposed to be 500px

It is 500.

<details>
<summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/64efcfde-c67e-4ad4-9bff-b622d918b387)

</details>

> **ITEM 3:**
> Marins around the button is supposed to be 18px top and bottom and 24px on the side.
> Currently, it's 16px on all sides.

This has been fixed.

Please let us know if you have any other questions, thank you!

**Comment by kelvinballoo** [comment] 2024-08-26 17:03
### QA Update ✅ 

Thanks @nfmohit ,

Verified this and it's looking good.

**ITEM 1:**
Icon size is roughly 24px which is same as figma and the icon now has a brown background colour.

<Details>
<img width="1009" alt="Screenshot 2024-08-26 at 20 58 24" src="https://github.com/user-attachments/assets/e6c517d5-d5a8-49ac-bae2-f55cdd1fbf76">

<img width="868" alt="Screenshot 2024-08-26 at 20 59 09" src="https://github.com/user-attachments/assets/dc1018f8-f630-4d79-be0d-3c101074858f">
</Details>
____________________________________________________

**ITEM 2:**
Noted on that.

____________________________________________________

**ITEM 3:**
I can confirm the button margins/paddings are now 18px top and bottom and 24px on the sides.
<Details>
<img width="903" alt="Screenshot 2024-08-26 at 21 00 15" src="https://github.com/user-attachments/assets/ed457bc4-fe18-4296-bf25-e921d545cd6d">

</Details>

**Closed** 2024-09-05 15:52 UTC
Labels: P0, Type: Enhancement, Team M, Module: RRM
