### ISSUE TITLE
The period is orphaned on a new line in the Terms & Privacy text of the survey popup.

### ISSUE THREAD

**Issue by eugene-manuilov** [google/site-kit-wp#9021] opened 2024-07-16 10:32 UTC
## Bug Description

We need to make sure the period does not wrap to the next line.

## Screenshots

![image](https://github.com/user-attachments/assets/3037e612-bda0-466d-9541-4fa553faea08)

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment] 2024-07-25 18:07
Duplicate of #9075 (or rather, #9075 is a duplicate of this, but I've already added ACs to #9075 so I'll close this one out instead 😅 )

**Closed by tofumatt** 2024-07-25 18:07 UTC
Labels: Type: Bug, P2
