### ISSUE TITLE
Review accessibility on module settings page.

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#6037] opened 2022-10-20 14:53 UTC
## Feature Description

When trying to navigate through the "Settings" page via the keyboard, it's impossible for the user to know what is the focused element due to the lack of visual indicators. This applies for both the tabs and the "accordion". 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2022-12-16 19:35
Duplicate of #173

**Closed by aaemnnosttv** 2022-12-16 19:35 UTC
