### ISSUE TITLE
Adapt GTM integration with GA to support GA4

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7990] opened 2023-12-15 11:19 UTC
## Feature Description

UPDATE 29 Jan 2024: Refer to this [comment](https://github.com/google/site-kit-wp/issues/7989#issuecomment-1915654586) for decisions taken regarding this issue.

The existing integration between GTM and GA modules in Site Kit only supports UA and since UA has been removed, this integration is no longer functional. [#7989](https://github.com/google/site-kit-wp/issues/7989) already started an effort to adapt this integration to support GA4.

This issue should be focused on using the datastore infrastructure introduced in [#7989](https://github.com/google/site-kit-wp/issues/7989) in Tag Manager module components/datastore replacing any usage of the legacy `analytics` module/datastore.

To summarise, across the Tag Manager module components/datastore, this should work to:
1. Replace the usage of legacy UA `tagmanager` `(get|has)AnalyticsPropertyID*()` selectors with GA4 counterparts.
2. Check for the active status of the `analytics-4` module instead of `analytics`.
3. Compare with `analytics-4` `measurementID` instead of `analytics` `propertyID`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When setting up Tag Manager and editing Tag Manager settings, the legacy message shown when a UA property ID was found within a GTM container tag's property ID should be adapted to work with GA4 and the new Google Tag as follows: 
    * When GA4 is not connected, but the selected Tag Manager container has a Google Tag (`googtag`) which is a valid Google Tag ID, then display the following screen:
        * Screenshot: 
        ![Screenshot 2024-01-06 at 20 59 03](https://github.com/google/site-kit-wp/assets/1721319/53cb2f6c-95ce-425e-a6be-ed8b73ce728b)
        * The message should be adapted as follows:
            * _Looks like you may be using Google Analytics within your Google Tag Manager configuration. Activate the Google Analytics module in Site Kit to see relevant insights in your dashboard._
        * The CTAs should match the above screenshot.
    * Clicking on "Continue to Analytics setup" should take the user to the Connect Service Analytics screen. (`/wp-admin/admin.php?page=googlesitekit-dashboard&slug=analytics&reAuth=true`). 
        * On the subsequent Analytics settings page, no additional message should be added above the "Please select the account information below.", even if the selected measurement ID matches or does not match the Google Tag ID found above.
* Since there is [no support for adding GA4 tags to an AMP container](https://github.com/google/site-kit-wp/issues/7989#issuecomment-1873974408), we should remove existing infrastructure (datastore selectors and React components) that solely "check" for Amp containers and give the user a message as before. [Note this comment](https://github.com/google/site-kit-wp/issues/7990#issuecomment-1942191192): We still intend to allow users to setup GTM with an AMP container and that should not be removed.
* Remove any other unused/unreachable infrastructure used to fetch the current GTM live container's UA tags and their associated property ID. (Note to AC Reviewer: This point was originally part of 7992 - but since we are already removing AMP container functionality, it makes sense to remove the other unreachable code here as well. The UA code is already unreachable and not being used, so there is no risk of removing and updating the selectors in a single PR. Also, the scope of our GTM - GA4 integration has been reduced so this issue is not as big as it was originally planned to be.)

## Implementation Brief

* [x] Within `assets/js/modules/tagmanager/datastore/versions.js`, create the following new selectors and implement them as below:
  * [x] `getLiveContainerGoogleTag`: Similar to `getLiveContainerAnalyticsTag`, use the `getLiveContainerVersion` selector and check for the `liveContainerVersion?.tag` property. If it exists, return the first tag with a type of `googtag`.
  * [x] `getLiveContainerGoogleTagID`: Similar to `getLiveContainerAnalyticsPropertyID`, check for the `parameter` property having a key of `tagId` within `analyticsTag`. If it does, this should be the Google tag ID. If this value is wrapped within `{{ }}` brackets, then find a variable (using `getLiveContainerVariable()`) within the container with this value as the name. Iff this variable is of type `c` (constant), then the value of the first parameter should be the Google tag ID. This [comment](https://github.com/google/site-kit-wp/issues/7989#issuecomment-1881129089) shows the shape of the container data returned. Ignore logic that tried to find the property ID within a `gaSettings` variable. Validate any of the IDs found using `isValidMeasurementID()`.
  * [x] `getCurrentGTMGoogleTagID`: This selector should first fetch the `accountID` and `internalContainerID` saved in Tag Manager settings as done in `getAnalyticsPropertyIDs()`. Pass these values to the `getLiveContainerGoogleTagID` selector created above to fetch the current container's associated Google Tag ID (if any).
  * [x] Remove all other selectors in this file that were not created above or used within the above selectors.
    * [x] Note that some (or all) of these selectors might also be used for functionality that prevents Analytics from adding the snippet when GTM is connected (e.g. in `useGAPropertyIDEffect`). This functionality will be removed as part of #8196 and removing this here is out of scope for this issue.

* [x] Within `assets/js/modules/tagmanager/components/common/FormInstructions.js`:
  * [x] Remove calling the following selectors and all `if` blocks that use their values:
    * [x] isSecondaryAMP
    * [x] singleAnalyticsPropertyID
    * [x] hasMultipleAnalyticsPropertyIDs
    * [x] analyticsPropertyID
  * [x] Modify the `analyticsModuleAvailable` and `analyticsModuleActive` constants to check for the `analytics-4` module instead of the `analytics` module.
  * [x] Call the new `getCurrentGTMGoogleTagID` selector saving its result in a constant, say `currentGTMGoogleTagID`. Modify the legacy `if` block where `analyticsModuleAvailable` is true AND `analyticsModuleActive` is false. Check if the `currentGTMGoogleTagID` has a value (instead of checking for `singleAnalyticsPropertyID`). Modify the message as per the AC.
  * [x] So effectively, this component should only call three selectors and have one if block for the above condition and the `isSetup` block which needs no modification.

* [x] Within `assets/js/modules/tagmanager/components/setup/SetupForm.js`:
  * [x] Instead of selecting the `singleAnalyticsPropertyID`, select the `currentGTMGoogleTagID` using `getCurrentGTMGoogleTagID`. Replace its usage when defining the `isSetupWithAnalytics` constant.

### Test Coverage

* [x] Add new tests for all the selectors created above to mirror the existing tests in `versions.test.js`.

## QA Brief

* Within GTM setup, perform a regression test to verify:
    * creating a new account
    * creating a new container
    * selecting/saving existing account and container
* Perform the same regression tests for editing GTM settings once it is set up. 
* Verify existing Google Tag within a GTM Container:
    * Ensure Google Analytics is disconnected.
    * Once you have set up Tag Manager, go to settings and view the Tag Manager settings. Click on "Edit in Tag Manager" to open the appropriate dashboard for the account / container that you have configured. 
        * In the default Overview tab that will open, click on "New Tag" -> click "Tag Configuration" -> click "Google Analytics" -> click "Google Tag" from the list. Give the tag a name in the upper left side. Add any valid Google Tag value, say `G-ABC12DE34F` in the "Google Tag ID" field. Click "Triggering" and choose any trigger (say All Pages). After adding this new tag, click on "Submit" in the upper right corner, give the version a name and description and click "Publish".
        * Go back to the plugin settings, and try selecting the same Account and Container, both, when setting up Tag Manager from scratch again and when editing its settings. Verify the new message as per the AC. However, note that the button CTA's to setup Google Analytics will only appear when setting up Tag Manager and not when editing settings.
        * Edit the tag created above to an invalid Google Tag ID (publish changes again) and verify that the message does not appear.
* Verify existing Google Tag via a Constant variable within a GTM Container: 
    * Follow the same steps as above to create a new tag or edit the same one that is created. If creating a new one, ensure the old tag is deleted. However, instead of adding a valid Google Tag ID, add a string with brackets in the Tag ID field like `{{My Google Tag ID}}`. After saving this tag, go to the "Variables" tab, click on "New" within the "User defined variables" list. Then click "Variable Configuration" -> Constant (under Utlities). The value here should be a valid Google Tag ID like `G-ABC12DE34F`. Now click on "Submit" and publish a new live version. Verify that the message 
    * Edit the tag created above to an invalid Google Tag ID (publish changes again) and verify that the message does not appear.

## Changelog entry

* Update setup flow for Tag Manager to be GA4 aware.

**Comment by techanvil** [comment] 2024-01-11 12:04
Hey @nfmohit, the AC is most of the way there, however, as noted in a related [comment](https://github.com/google/site-kit-wp/issues/7989#issuecomment-1886941254), the `tagId` is actually a Google tag ID, so we need to check if any of the corresponding Google tag's containers are a match for the current measurement ID rather than assuming the measurement ID will be tracked directly in the tag ID field.

If not, we'll determine the most relevant measurement ID for the Google tag following similar logic to that used in [GoogleTagIDMismatchNotification](https://github.com/google/site-kit-wp/blob/bfac18802ced43074450f4f568fc7e37956848f7/assets/js/components/notifications/GoogleTagIDMismatchNotification.js#L63-L81), although falling back to the first valid measurement ID if none of them exist in the available Analytics accounts (TBC as per the linked comment - maybe the AC should refer to that issue for the details).

**Comment by nfmohit** [comment] 2024-01-12 07:31
Hi @techanvil!

I'm handing this over to @jimmymadon as Jimmy actually added the ACs for this one. @jimmymadon Let's sync if needed to discuss the ACR feedback.

Thank you folks!

**Comment by techanvil** [comment] 2024-01-12 11:16
Oh, sorry @nfmohit, I should have realised that. Thanks for letting me know.

**Comment by aaemnnosttv** [comment] 2024-01-31 19:08
> we are waiting to hear back from Mariya and possibly the GTM team on this one.

This is still in progress, although if it stalls out, I agree with @jimmymadon that we can essentially prune the unused/unreachable AMP code and re-add it later if/when it becomes necessary, but let's hold on this a bit longer.

**Comment by bethanylang** [comment] 2024-02-05 12:09
Thanks @jimmymadon! @ivonac4 is the PM for this one, so pinging her in here, as well.

**Comment by bethanylang** [comment] 2024-02-08 14:42
@jimmymadon Should this be assigned back to you to update the AC, since we've determined we're not going to support AMP?

**Comment by aaemnnosttv** [comment] 2024-02-13 18:56
> Remove the AMPContainerSelect component and all of its usage.

@jimmymadon while GTM doesn't support configuring GA4, removing GTM support for AMP _entirely_ is out of scope for this issue but also isn't something on our foreseeable roadmap. Folks should still be able to set up GTM using AMP as today, they just can't implement GA4 with it, which is fine since Analytics supports it and makes things a bit easier for us actually. This means we'd always check the web container for a Google tag and suggest setting up Analytics regardless of whether or not the site was using AMP or not.

I'm not sure if this significantly impacts the rest of the IB (which LGTM), but anything which was based on this point about removing AMP support for GTM would need to be reverted/revised.

**Comment by wpdarren** [comment] 2024-02-21 14:56
### QA Update: ✅ 

**Verified:**

- Within the GTM setup, I performed a regression test to verify:
  - creating a new account
  - creating a new container
  - selecting/saving existing accounts and container
- Performed the same regression tests for editing GTM settings once set up.
- Verified existing Google Tag within a GTM Container:
- Verified the new message as per the AC. 
- I edited the tag created above to an invalid Google Tag ID and verified the message does not appear.
- Verified existing Google Tag via a Constant variable within a GTM Container:
- Tested all steps in the QAB and AC. 
- I also did some additional testing around AMP on the scenarios highlighted above. 
- I also checked the snippets in the source code for GTM with AMP activated and not. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/b4f643f6-88e5-4769-9f12-f0d507ab1717)
![image](https://github.com/google/site-kit-wp/assets/73545194/4f72c430-bfac-45ca-abea-d0328de9ede8)
![image](https://github.com/google/site-kit-wp/assets/73545194/14285e9e-6447-44fb-88bd-aac563317144)
![image](https://github.com/google/site-kit-wp/assets/73545194/b8efcdba-5d3b-48e6-ad72-7bfb3ea86771)
![image](https://github.com/google/site-kit-wp/assets/73545194/fd2eb822-d643-433b-9a7e-a30fe8967a52)
![image](https://github.com/google/site-kit-wp/assets/73545194/13d1ef90-cace-4128-aaba-a4832c1bbdd1)
![image](https://github.com/google/site-kit-wp/assets/73545194/1a9b3654-3f91-4301-898b-678b32ac4100)
![image](https://github.com/google/site-kit-wp/assets/73545194/12c365c2-0023-4fd7-8943-d2d53d883cd2)
![image](https://github.com/google/site-kit-wp/assets/73545194/71291686-c9a5-4fa8-9319-5067b6ba91ef)
![image](https://github.com/google/site-kit-wp/assets/73545194/f430f09b-3911-432c-9786-c6779c8cb053)
![image](https://github.com/google/site-kit-wp/assets/73545194/8281920a-aaf3-4eb4-8e12-23f6e25fa521)

</details>

**Closed** 2024-02-26 18:31 UTC
Labels: P2, Type: Enhancement, Module: Tag Manager
