### ISSUE TITLE
JavaScript error: An error occurred while running 'mapSelect': Cannot read property 'isModuleActive' of null

### ISSUE THREAD

**Issue by ernee** [google/site-kit-wp#2350] opened 2020-11-11 03:17 UTC
## Bug Description

Reported in[ a support topic](https://wordpress.org/support/topic/an-error-occurred-while-running-mapselect/), a user encountered this error after install and navigating to the dashboard ([screenshot](https://ibb.co/CsMzPpL)):

```
An error occurred while running 'mapSelect': Cannot read property 'isModuleActive' of null
The error may be correlated with this previous error:
TypeError: Cannot read property 'isModuleActive' of null
    at Object.current (https://www.socomtactical.net/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-dashboard.41176eb144adcaf84380.js:64:39347)
    at e (https://www.socomtactical.net/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.7f2f98d6cb7f1a6a3ca1.js:1:230780)
    at https://www.socomtactical.net/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.7f2f98d6cb7f1a6a3ca1.js:1:230889
    at Ui (https://www.socomtactical.net/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.7f2f98d6cb7f1a6a3ca1.js:1:538697)
    at ba (https://www.socomtactical.net/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.7f2f98d6cb7f1a6a3ca1.js:1:561620)
    at t.unstable_runWithPriority (https://www.socomtactical.net/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.7f2f98d6cb7f1a6a3ca1.js:1:581243)
    at Nr (https://www.socomtactical.net/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.7f2f98d6cb7f1a6a3ca1.js:1:506349)
    at Yj (https://www.socomtactical.net/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.7f2f98d6cb7f1a6a3ca1.js:1:558049)
    at Lj (https://www.socomtactical.net/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.7f2f98d6cb7f1a6a3ca1.js:1:548409)
    at https://www.socomtactical.net/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.7f2f98d6cb7f1a6a3ca1.js:1:506640

Original stack trace:

    in PostSearcher
    in FilteredComponent
    in WithFilters(LegacyDashboardPopularityInner)
    in LegacyDashboardPopularity
    in FilteredComponent
    in WithFilters(DashboardModule)
    in DashboardModules
    in DashboardMain
    in div
    in div
    in div
    in div
    in DashboardApp
    in GoogleSitekitDashboard
    in RestoreSnapshots
    in ErrorHandler
    in Root
```

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

- Related support topic: https://wordpress.org/support/topic/an-error-occurred-while-running-mapselect/
- Site Health Info available
- Possible related issue: #1819 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by ernee** [comment] 2020-11-12 02:25
Update: the user from the related support topic reported the error [resolved after updating ](https://wordpress.org/support/topic/an-error-occurred-while-running-mapselect/#post-13647769)to version 1.20.0

**Comment by jamesozzie** [comment] 2020-12-01 09:16
[Another report](https://wordpress.org/support/topic/site-kit-encountered-an-error-15/) of the same issue in the support forums.

**Comment by jamesozzie** [comment] 2020-12-01 12:20
One user mentioned this started occurring after ads were not being served due to "[Invalid traffic](https://support.google.com/adsense/answer/1112983?hl=en)". From inspecting the site I don't see any ads being served.

**Comment by jamesozzie** [comment] 2020-12-03 10:36
Update on [one impacted user](https://wordpress.org/support/topic/site-kit-encountered-an-error-15/#post-13739622. It was [an AbBlocker](https://www.getadblock.com/) causing the issue in this instance.

**Comment by ernee** [comment] 2021-01-18 22:18
[Another report](https://wordpress.org/support/topic/site-kit-encountered-an-error-17/) for the `An error occurred while running 'mapSelect': Cannot read property 'getServiceAccountSiteURL' of null` variation.

**Comment by lontano75** [comment] 2021-02-20 21:45
Hi! I've the same problem :(

An error occurred while running 'mapSelect': Cannot read property 'getProxySetupURL' of null
The error may be correlated with this previous error:
TypeError: Cannot read property 'getProxySetupURL' of null
    at Object.current (https://www.futuroprossimo.it/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-activation.d3921b016589fe6b0142.js:10:18542)
    at e (https://www.futuroprossimo.it/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.f774f9c7df0ac2b8a251.js:1:230892)
    at https://www.futuroprossimo.it/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.f774f9c7df0ac2b8a251.js:1:231001
    at Ui (https://www.futuroprossimo.it/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.f774f9c7df0ac2b8a251.js:1:652747)
    at va (https://www.futuroprossimo.it/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.f774f9c7df0ac2b8a251.js:1:675670)
    at t.unstable_runWithPriority (https://www.futuroprossimo.it/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.f774f9c7df0ac2b8a251.js:1:695293)
    at Pr (https://www.futuroprossimo.it/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.f774f9c7df0ac2b8a251.js:1:620399)
    at Yj (https://www.futuroprossimo.it/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.f774f9c7df0ac2b8a251.js:1:672099)
    at Lj (https://www.futuroprossimo.it/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.f774f9c7df0ac2b8a251.js:1:662459)
    at https://www.futuroprossimo.it/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.f774f9c7df0ac2b8a251.js:1:620690

Original stack trace:
    in ActivationApp
    in RestoreSnapshots
    in ErrorHandler
    in Root

**Comment by jamesozzie** [comment] 2021-02-23 13:44
@lontano75 Many thanks for the useful insights. As we're still investigating this can you share the following: 
- Has this occurred previously on this site or did you just notice this recently when accessing your site via the Chrome browser?
- Does the same occur when checking a Chrome browser incognito window?
- Can you share what's occurring in the form of a video or screen recording, with Chrome developer tools open while you encounter this notice, in particular on the front end of your site. You can use a service such as [Loom](https://www.loom.com/) or [RecordIt](https://www.recordit.co/) to easily share a screen recording.

**Comment by bethanylang** [comment] 2021-03-15 18:59
@lontano75 Thanks again for sharing those troubleshooting details. Are you still experiencing these issues with the plugin?

**Comment by jamesozzie** [comment] 2021-03-25 10:15
Another "Mapselect" error just reported [in the support forums](https://wordpress.org/support/topic/just-set-it-up-says-report-this-error-no-name-of-it/):
`‘mapSelect’: Cannot read property ‘getReport’ of null`

Awaiting additional insights.

**Comment by abdullah1908** [comment] 2021-04-14 08:14
Another [error](https://wordpress.org/support/topic/site-kit-encountered-an-error-28/) reported by user krohit on WP Support Forum.
`
An error occurred while running 'mapSelect': Cannot read property 'getReport' of null
The error may be correlated with this previous error:
TypeError: Cannot read property 'getReport' of null
    at Object.current (https://www.ientrepreneur.co.in/wp-content/cache/asset-cleanup/js/item/googlesitekit-adminbar-v09430a63e26705d9a20c5d159dc5d4665da917a7.js:3:208666)
    at e (https://www.ientrepreneur.co.in/wp-content/cache/asset-cleanup/js/item/googlesitekit-vendor-v14f8d47d0a098bcc47ab2e11273e9d94d024ffe5.js:2:277065)
    at https://www.ientrepreneur.co.in/wp-content/cache/asset-cleanup/js/item/googlesitekit-vendor-v14f8d47d0a098bcc47ab2e11273e9d94d024ffe5.js:2:277174
    at Ui (https://www.ientrepreneur.co.in/wp-content/cache/asset-cleanup/js/item/googlesitekit-vendor-v14f8d47d0a098bcc47ab2e11273e9d94d024ffe5.js:2:779627)
    at va (https://www.ientrepreneur.co.in/wp-content/cache/asset-cleanup/js/item/googlesitekit-vendor-v14f8d47d0a098bcc47ab2e11273e9d94d024ffe5.js:2:802554)
    at t.unstable_runWithPriority (https://www.ientrepreneur.co.in/wp-content/cache/asset-cleanup/js/item/googlesitekit-vendor-v14f8d47d0a098bcc47ab2e11273e9d94d024ffe5.js:2:822179)
    at Mr (https://www.ientrepreneur.co.in/wp-content/cache/asset-cleanup/js/item/googlesitekit-vendor-v14f8d47d0a098bcc47ab2e11273e9d94d024ffe5.js:2:747279)
    at Yj (https://www.ientrepreneur.co.in/wp-content/cache/asset-cleanup/js/item/googlesitekit-vendor-v14f8d47d0a098bcc47ab2e11273e9d94d024ffe5.js:2:798981)
    at Lj (https://www.ientrepreneur.co.in/wp-content/cache/asset-cleanup/js/item/googlesitekit-vendor-v14f8d47d0a098bcc47ab2e11273e9d94d024ffe5.js:2:789339)
    at https://www.ientrepreneur.co.in/wp-content/cache/asset-cleanup/js/item/googlesitekit-vendor-v14f8d47d0a098bcc47ab2e11273e9d94d024ffe5.js:2:747570
Original stack trace:
  in AdminBarSessions
    in WithWidgetComponentProps(AdminBarSessions)
    in div
    in Cell
    in div
    in Row
    in AdminBarWidgets
    in div
    in div
    in div
    in AdminBarApp
    in RestoreSnapshots
    in ErrorHandler`

**Comment by bethanylang** [comment] 2021-04-29 17:16
[Another report here](https://wordpress.org/support/topic/message-from-site-kit/):

```
An error occurred while running 'mapSelect': Cannot read property 'getReport' of null
The error may be correlated with this previous error:
TypeError: Cannot read property 'getReport' of null
    at Object.current (https://cafewenzel.com.br/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-adminbar.83e89a96df29af6952f0-de30c5f6cb3f444ebe1a0e7597e45ce4.js:2:208666)
    at e (https://cafewenzel.com.br/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.0c15cc710eaf5d89baf6-e8a84941c88b1c67794420adc2eaf4c3.js:1:277065)
    at https://cafewenzel.com.br/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.0c15cc710eaf5d89baf6-e8a84941c88b1c67794420adc2eaf4c3.js:1:277174
    at Ui (https://cafewenzel.com.br/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.0c15cc710eaf5d89baf6-e8a84941c88b1c67794420adc2eaf4c3.js:1:779627)
    at va (https://cafewenzel.com.br/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.0c15cc710eaf5d89baf6-e8a84941c88b1c67794420adc2eaf4c3.js:1:802554)
    at t.unstable_runWithPriority (https://cafewenzel.com.br/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.0c15cc710eaf5d89baf6-e8a84941c88b1c67794420adc2eaf4c3.js:1:822179)
    at Mr (https://cafewenzel.com.br/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.0c15cc710eaf5d89baf6-e8a84941c88b1c67794420adc2eaf4c3.js:1:747279)
    at Yj (https://cafewenzel.com.br/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.0c15cc710eaf5d89baf6-e8a84941c88b1c67794420adc2eaf4c3.js:1:798981)
    at Lj (https://cafewenzel.com.br/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.0c15cc710eaf5d89baf6-e8a84941c88b1c67794420adc2eaf4c3.js:1:789339)
    at https://cafewenzel.com.br/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor.0c15cc710eaf5d89baf6-e8a84941c88b1c67794420adc2eaf4c3.js:1:747570

Original stack trace:

    in AdminBarSessions
    in WithWidgetComponentProps(AdminBarSessions)
    in div
    in Cell
    in div
    in Row
    in AdminBarWidgets
    in div
    in div
    in div
    in AdminBarApp
    in RestoreSnapshots
    in ErrorHandler
    in Root
```

**Comment by tofumatt** [comment] 2021-05-17 14:00
I am still trying to 100% reliably reproduce this, but after looking through the issue and trying some custom adblocker scripts I think the issue is our `googlesitekit-modules-adsense.js` file.

I think our public JS file `googlesitekit-modules-adsense` is likely being blocked by ad blockers, as they frequently will have rules that block **all** scripts containing `ad` or `adsense`. If that file doesn’t load, it can cause the errors users are reporting.

But ad blockers are always tough to diagnose because users can have custom filter sets, rules, etc. that cause it. So I’m trying to see if there are common blockers/lists/etc. that cause it. The easy solution might be to rename that file. 🙂

**Comment by tofumatt** [comment] 2021-05-17 15:46
I still think it’s Ad Blockers causing this but I’ve yet to find one out-of-the-box that actually triggers the error on my development site 😢

I had a look through the support tickets, and in _some cases_ in that issue the modules not available are unrelated to ads (`CORE_SITE` selectors aren't available), and in that case it might just be caching errors. Or some sort of aggressive ad-blocking rules that prevent any script tag with `google` in it from loading, but that's not a common scenario I'm aware of 😅

I'd love to find a way to reproduce this consistently, but I do wonder about renaming our `adsense` JS files no matter what as a preventative fix? 🤷🏻‍♂️

**Comment by jamesozzie** [comment] 2021-05-18 12:32
@tofumatt I've been unable to reproduce this after performing checks using various ad blockers, tests below. For those who've encountered this via the admin toolbar it may be related to JS minification or asset combining. 

**Tests Complete**
- **Firefox with Ultimate Ad Blocker** - default config - Unreproducible, "You are offline" errors appear on 2/3 sites, 1 that "needs attention" before ads are served and another that has AdSense traffic - [Screenshot & console errors](https://i.imgur.com/udTMNBL.png). The other sites have a standard Ad Blocker detected message
- **Opera Browser (with in built Ad Blocker)** - Unreproducible, "You are offline" appears as above for 1 site. 
- **Chrome with [AdBlock ](https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom?hl=en-US)** - Unreproducible, "You are offline" appears as above for 2 sites, with 1 site encountering a "Gathering data" notice despite this site already having an approved AdSense account and site (with ads) - [console errors](https://i.imgur.com/nInFkEf.png).

All checks above done on 3 different sites, all with SC, Analytics & AdSense connected with traffic. 2 of those have AdSense data, with 1 site not approved. SK main dashboard, Analytics, AdSense & Admin toolbar checked on each. 

**Impacted users:** 3/9 unresolved. Various fixed for those who confirmed a resolution (Ad Blocker & Optimisation plugin - where is the issue occurred on the front end via the admin toolbar)
- https://wordpress.org/support/topic/error-mapselect-cannot-read-property-by-google-site-kit-2/ | **Unresolved** | No SH info - Occurs from admin toolbar
- https://wordpress.org/support/topic/sitekit-error-on-toolbar-when-viewing-site/ | **Resolved** | [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNiLom0uqfUg31H3U0KDl9OTkrP4BnTdvHidpj30N90YVt_02LVxNgQo-aSpcV-UrQs) | Occurs from admin toolbar - WP Rocket minification or combining of assets
- https://wordpress.org/support/topic/message-from-site-kit/ | **Unresolved** | No SH info | Awaiting info
- https://wordpress.org/support/topic/site-kit-encountered-an-error-28/ | **Resolved** | No response from user, WP Rocket evident
- https://wordpress.org/support/topic/site-kit-encountered-an-error-28/| **Unresolved** | No SH info | No obvious optimisation plugins
- https://wordpress.org/support/topic/just-set-it-up-says-report-this-error-no-name-of-it/| **Resolved** | No response from user - Hummingbird cache evident
- https://wordpress.org/support/topic/site-kit-encountered-an-error-17/| **Resolved** | No response from user - occirs from SK dashboard, no evident optimization plugin (Although Photon CDN used)
- https://wordpress.org/support/topic/site-kit-encountered-an-error-15/| **Resolved** | Possible AdBlock - getadblock.com referenced (this plugin was tested as above)
- https://wordpress.org/support/topic/an-error-occurred-while-running-mapselect/| **Resolved** | Plugin update resolved this users issue

**Comment by bethanylang** [comment] 2021-05-18 13:16
@abdullah1908 Reassigning to you for testing WP Rocket as noted in Slack.

**Comment by jamesozzie** [comment] 2021-05-19 10:49
The most recent report of this issue is now resolved, with the error appearing in this users case via the admin toolbar, as a result of WP Rocket optimisations applied. 

The user defined the below exclusion to ensure the Site Kit admin toolbar is not impacted by WP Rocket optimizations (JS asset combination or minification):
`/wp-content/plugins/google-site-kit/dist/assets/js/(.*).js` 

@bethanylang What are your thoughts on testing various popular optimisation plugins and testing admin bar functionality compatibility with the various optimizations enabled. Maybe we can come up with troubleshooting guides or exclusions.

**Comment by abdullah1908** [comment] 2021-05-19 19:51
@jamesozzie I couldn't reproduce the actual JS error but I can see **Site Kit Admin Toolbar** is not working when WP Rocket & Asset Cleanup plugins are configured.  Please see recording [here](https://www.loom.com/share/9ddeca3d324048bba458699bf49e51aa).

**Comment by jamesozzie** [comment] 2021-05-20 11:28
Likewise with a combination of options enabled the Site Kit tab doesn't load. I have been able to recreate the original issue with only the minify JS option enabled in WP Rocket, all other configurations default. 

![2021-05-20-12-20-13](https://user-images.githubusercontent.com/41326532/118970150-d0273d00-b965-11eb-8a1e-1935ac543dd2.gif)

Adding the below exclusion allows the Site Kit tab to operate successfully:
`/wp-content/plugins/google-site-kit/dist/assets/js/(.*).js`

There is a warning when [these features](https://i.imgur.com/mj67Z0W.png) are operated within WP Rocket.

**Comment by jamesozzie** [comment] 2021-05-26 16:08
Closing this as reproducible only with particular configurations with WP Rocket. Compatibility testing with multiple optimization plugins TBC and tracked internally.

**Comment by abdullah1908** [comment] 2021-05-31 14:47
Another [error](https://wordpress.org/support/topic/an-error-occurred-while-running-mapselect-2/) reported & @jamesozzie research on WP Rocket was useful.
Kudos to @jamesozzie 🎉

**Comment by jamesozzie** [comment] 2021-06-23 12:14
Reopening this as it looks like it may be possible to [programmatically deactivate](https://docs.wp-rocket.me/article/1564-list-of-pre-get-rocket-option-filters) the minify option for WP Rocket, specifically using `pre_get_rocket_option_minify_js`. 

For additional context in order to recreate this JS error follow the steps below:
1. Install and setup SK with WP Rocket
2. Activate the Minify JS option within WP Rocket (File Optimization > Minify JavaScript files)
3. [enable caching for logged in users](https://imgur.com/undefined). 
4. Visit your site as a logged in user and view statistics from the admin toolbar

**Comment by bethanylang** [comment] 2021-08-24 13:26
@felixarntz @jamesozzie Checking in on this one. Sounds like we need to make a decision on how/if we want to programatically deactivate minification for SK files with WP Rocket. Should this move to Triage instead?

**Comment by jamesozzie** [comment] 2021-08-24 14:11
@bethanylang We discussed this in a previous internal sync, at what point it was assigned. As these minification conflicts are not specific to WP Rocket we've also done some [internal testing](https://app.asana.com/0/1185360131189553/1200384634437887) for other popular plugins. Happy to triage for further team discussion.

**Comment by adamsilverstein** [comment] 2021-11-30 20:29
James suggested adding `.min.js` as the suffix to our built files. They are minified after all, and this convention helps script optimization code know they can/should skip these scripts. What do you think @aaemnnosttv? We could give this approach a test with wp-rocket where we have a reproducible issue.

**Comment by aaemnnosttv** [comment] 2021-12-01 08:37
@adamsilverstein that sounds good to me. Do we know if other optimization plugins use this naming convention for exclusion logic as well?

**Comment by aaemnnosttv** [comment] 2021-12-01 09:05
Opened #4436 to support this, after which this issue may no longer be relevant but I suppose we'll have to wait and see 😄 

cc: @felixarntz

**Comment by devjoynal** [comment] 2022-04-27 16:30
I am facing this problem,

**Comment by jamesozzie** [comment] 2022-07-19 15:06
Closing this, with the causes being identified typically as a third party plugin minification or other optimization feature. As these plugins can change how other plugins operate, a fix or exclusion can usually be applied within that plugins settings, to ensure Site Kit resources are not included. 

Both `/wp-content/plugins/google-site-kit/dist/assets/js/(.*).js` or`/wp-content/plugins/google-site-kit/` are examples of exclusions known to work for various optimization plugins. 

For those who may encounter this, or a similar error based on a third party plugin optimization configuration, we've added [documentation to the plugin website](https://sitekit.withgoogle.com/documentation/troubleshooting/analytics/#mapselect). If you're unsure of the plugin which may be causing this, you can [use the Health Check & Troubleshooting plugin](https://sitekit.withgoogle.com/documentation/troubleshooting/using-troubleshooting-mode/). 

Note also that should you encounter this on one of your sites, from the Site Kit admin toolbar, this is only visible to you, as a logged in administrator.

**Closed by jamesozzie** 2022-07-19 15:06 UTC
Labels: Type: Support
