### ISSUE TITLE
Create GA4 `WPDashboardUniqueVisitors`

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6212] opened 2022-11-29 04:27 UTC
## Feature Description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component `WPDashboardUniqueVisitorsGA4` should be created based on the existing `WPDashboardUniqueVisitors`
* The component should source its report data from the `analytics-4` store
	* [See here for a table of equivalent metrics for GA4](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6)
* No changes should be made in the dashboard yet
* Storybook stories should be added to cover the following cases (with and without a current entity URL set: [example](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics-widgets-dashboardoverallpagemetricswidget--ready)):
    * Loading
    * Gathering data ("Data unavailable")
    * Zero data (data available but metric is `0`) 
    * Error
    * Ready (data available and non-zero)

## Implementation Brief
* Once #6173 and #6174 have been merged.
* Create `assets/js/components/wp-dashboard/WPDashboardUniqueVisitorsGA4.js` which exports the `WPDashboardUniqueVisitorsGA4` functional component.
    * Component should be similar to the one in `assets/js/components/wp-dashboard/WPDashboardUniqueVisitors.js` with the following updates:
        * Replace occurrences of the Analytics data store (`MODULES_ANALYTICS`) by the GA4 Analytics data store (`MODULES_ANALYTICS_4`).
        * Replace the metrics and dimensions by their GA4 counterparts [as per the doc here](https://docs.google.com/document/d/17RKIrdm5PBK8j6rP0GV_2QlztSLXqYQX8ikz3kQmrAo/edit?resourcekey=0-njOU7bn1dhvi5Yp2jeX5zw#bookmark=id.2cvsdbn818e6), including the metric names.
    * Stories should be within `assets/js/components/wp-dashboard/WPDashboardUniqueVisitorsGA4.stories.js` and make use of the Analytics 4 response mock data added from #6174
        * Refer to the AC for the different stories to be added.

### Test Coverage
* No new tests to be added.

## QA Brief
* This is currently only testable in Storybook.
* Check the stories under `Views/WPDashboardApp/WPDashboardUniqueVisitorsGA4`. These should be broadly in line with the existing UA version under `Views/WPDashboardApp/WPDashboardUniqueVisitors`. Please note that the data will be different.

## Changelog entry

* Add GA4-based "Unique Visitors Widget" to codebase.

**Comment by techanvil** [comment] 2022-12-19 12:20
IB :white_check_mark:

**Comment by techanvil** [comment] 2023-02-20 17:40
I've made the change that I would have applied here to the PR for #6559 instead, as other GA4 Reporting issues may also need it and this should allow it to be merged to `develop` sooner

**Comment by tofumatt** [comment] 2023-02-22 21:21
Hey @techanvil, I'm a bit unclear on what's left in this issue from your last comment. I see #6559 is in approval, does that mean we can move this issue right to QA because the fix here was included in that issue's PR?

**Comment by tofumatt** [comment] 2023-02-23 12:25
@techanvil Oh, cheers, it didn't have an associated PR and I wasn't sure which of the related ones here it was for. I've found it and marked it, and I'll review it. 👍🏻

**Comment by techanvil** [comment] 2023-02-23 15:09
Ahh, thanks - sorry, I didn't realise the PR wasn't associated with the issue!

**Comment by wpdarren** [comment] 2023-03-01 13:46
### QA Update: ⚠️ 

@techanvil I would just like to check it's expected that under `Views/WPDashboardApp/WPDashboardUniqueVisitorsGA4` we have stories for `Loading` and `Error` but we don't have these for `Views/WPDashboardApp/WPDashboardUniqueVisitors`

![image](https://user-images.githubusercontent.com/73545194/222156238-bed0f033-7d61-457d-a9ef-96094c737277.png)

**Comment by techanvil** [comment] 2023-03-01 13:49
Thanks for raising this @wpdarren, and sorry for not being more clear in the QAB. This is indeed to be expected.

**Comment by wpdarren** [comment] 2023-03-01 13:55
### QA Update: ✅ 

**Verified:**

- Checked the stories under `Views/WPDashboardApp/WPDashboardUniqueVisitorsGA4` and confirmed that these are the same as the existing UA version under `Views/WPDashboardApp/WPDashboardUniqueVisitors` as per the QAB.
- Noted that Loading and Error stories do not appear for `WPDashboardUniqueVisitors` but this is expected. 

![image](https://user-images.githubusercontent.com/73545194/222159115-0a9aa2f2-0464-4709-a2d7-b5631248191d.png)

**Closed** 2023-03-09 20:30 UTC
Labels: P0, Type: Enhancement, Exp: SP
