### ISSUE TITLE
WP post list CTA language could be improved for consistency with dashboard CTA

### ISSUE THREAD

**Issue by simonchampion** [google/site-kit-wp#3852] opened 2021-08-12 16:09 UTC
## Bug Description

[See WP dashboard CTA inconsistent with latest design and language](https://app.asana.com/0/1200491083500938/1200759450014532)

![image](https://user-images.githubusercontent.com/83005909/129230533-cad6637c-7e3d-449f-881d-6311a9d21381.png)

**Asana**: https://app.asana.com/0/1200491083500938/1200759450014538

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

**For the case where the user has already saved some ideas**
- Update text to: "Want some inspiration for a new post? Revisit your saved ideas in Site Kit"
- The link CTA is this part of the second sentence: "Revisit your saved ideas" 
- Remove the separate "See saved ideas" link CTA that currently exists. 

**For the case where the user has no saved ideas**
- Update text to: "Want some inspiration for a new post? Review your new ideas in Site Kit"
- The link CTA is this part of the second sentence: "Review your new ideas" 
- Remove the separate "See new ideas" link CTA that currently exists. 

Eg. 
![image](https://user-images.githubusercontent.com/1621608/129882609-69d5e33b-8407-413c-a86d-a66cff7ac021.png)

## Implementation Brief
* Using `includes/Modules/Idea_Hub.php`, update the notices in the `admin_notice_idea_hub_ideas` function as per the AC.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief
* Check if the notices in the WP post list page are updated as per the AC when there are/are not saved ideas.

## Changelog entry

* Update CTA language for WP post list notifications.

**Comment by aaemnnosttv** [comment] 2021-08-18 10:26
@marrrmarrr I added a screenshot to the ACs, I think this is all set now 👍

**Comment by eugene-manuilov** [comment] 2021-08-18 13:17
IB :heavy_check_mark:

**Comment by wpdarren** [comment] 2021-08-19 13:44
### QA Update: ❌ 

Within idea hub I have [no saved ideas](https://user-images.githubusercontent.com/73545194/130078073-43bdc8f4-f78e-4fff-a768-3959081bcd00.png) but the message in the posts screen is: `Want some inspiration for a new post? Revisit your new ideas in Site Kit.` which does not match the AC. 

![image](https://user-images.githubusercontent.com/73545194/130078292-9c4dae09-0efa-4d71-8055-4558544bfddd.png)

**Verified:**

Within Idea hub, when I have ideas saved and I go to the posts page the correct message `Want some inspiration for a new post? Revisit your new ideas in Site Kit.` appears.  When I click on the `Revisit your new ideas` link I am taken to the idea hub widget on SK dashboard.

![image](https://user-images.githubusercontent.com/73545194/130078547-fe7b181e-6185-4dca-9ad2-7d30f2f22f48.png)

**Comment by eugene-manuilov** [comment] 2021-08-19 13:53
> Within idea hub I have no saved ideas but the message in the posts screen is: `Want some inspiration for a new post? Revisit your new ideas in Site Kit.` which does not match the AC.

@wpdarren that's correct, when you have **no saved ideas** it should show you `... Revisit your new ideas in Site Kit.` message. If you have saved ideas, it will display `... Revisit your saved ideas in Site Kit`.

**Comment by wpdarren** [comment] 2021-08-19 13:56
@eugene-manuilov so is the AC wrong because it says for no saved ideas the text should be `Want some inspiration for a new post? Review your new ideas in Site Kit`

**Comment by eugene-manuilov** [comment] 2021-08-19 14:00
Ah... yes, good catch, @wpdarren. Sorry, I missed that there is a difference in just one word. Assigning back to @asvinb to fix it.

**Comment by asvinb** [comment] 2021-08-19 15:34
Good catch @wpdarren . @eugene-manuilov Follow up PR:
https://github.com/google/site-kit-wp/pull/3917

**Comment by eugene-manuilov** [comment] 2021-08-19 16:21
@wpdarren this is ready for another pass.

**Comment by wpdarren** [comment] 2021-08-20 12:36
### QA Update: ❌ 

@asvinb @eugene-manuilov Sorry, there is still some odd behaviour with this.   Initially, I did not save any ideas and went to post page and the `revisit` CTA link appeared.  So, I decided to disconnect Site Kit and reset.  When I reconnected the correct CTA of `review` appeared with no saved ideas.  I celebrated and then went to save an idea and go straight back to the post page and the CTA link is still set to `review` I have cleared cache, refreshed, and the same appears. It should say `revisit` so I am wondering if there's an issue with the API or something.  Any ideas?

**Comment by johnPhillips** [comment] 2021-08-21 15:07
I had a poke around the code for this and although the logic seems fine (caveat: my PHP isn't the best!), I am seeing the same behaviour as @wpdarren. 
Inside `Idea_Hub.php:: admin_notice_idea_hub_ideas`, it seems `$has_saved_ideas` seems to be truthy even when I have unpinned the saved idea, with `saved_ideas` logging out the idea I have just un-saved. 
I wonder if something could be persisting somewhere?
Assigning to you @aaemnnosttv as Eugene and Asvin are on leave this week, hope that's ok.

**Comment by asvinb** [comment] 2021-08-23 08:10
@aaemnnosttv @wpdarren I wonder if we need to open a new ticket since the bug that @wpdarren is describing is not related to the text updates. 🤔 
cc @johnPhillips

**Comment by wpdarren** [comment] 2021-08-23 10:22
@asvinb it is related to text updates. When I have saved ideas I should expect to see `revisit` but currently it says `review` From the AC it is suggesting that the word should change.

**Comment by aaemnnosttv** [comment] 2021-08-23 11:39
@wpdarren this issue is just about updating the notices although you've raised a valid point that the notice which is shown should change based on activity. What happens is that the ideas which are requested for the logic of which notice to show are cached in transients which expire after 1 day. The problem is that they are never deleted/invalidated. You can do this manually though via wp-cli or using a plugin like [Transients Manager](https://wordpress.org/plugins/transients-manager/).

When there are no saved ideas, the message to "review your new ideas" is shown ✅ 
When there are saved ideas, the message to "revisit your saved ideas" is shown ✅ 

The issue of caching and invalidation is separate here so I'll open a separate issue for that.

We can consider this QA ✅  though, no further review is needed as the ACs are met. Moving to Approval.

**Comment by aaemnnosttv** [comment] 2021-08-23 11:50
See https://github.com/google/site-kit-wp/issues/3922 for the follow-up.

**Closed** 2021-08-30 19:04 UTC
Labels: P0, Type: Enhancement, Good First Issue, Module: Idea Hub
