### ISSUE TITLE
A site url with an internationalized domain name (IDN) will not show data for the Analytics portion of GSK

### ISSUE THREAD

**Issue by HFigarella** [google/site-kit-wp#3606] opened 2021-06-21 11:06 UTC
## Bug Description

A site url with an [internationalized domain name (IDN)](https://www.icann.org/resources/pages/idn-2012-02-25-en#:~:text=Internationalized%20Domain%20Names%20(%20IDNs%20)%20enable,allowed%20by%20relevant%20IDN%20protocols.) will not show data for the Analytics portion of GSK.

## Steps to reproduce

If the web site url is an IDN such as this sample: ([click here to convert IDN to ASCII](https://converter-idn.com/))

unicodenáme.xxx (**unicode**)

xn--unicodenme-z4a.xxx (**ASCII**)

1. Go to 'G Site Kit' on the WordPress Dashboard'
2. Click on 'Dashboard' or 'Analytics'
4. See message:

'Analytics Gathering Data
Analytics data is not yet available, please check back'

## Additional Context

This issue was presented to WordPress Support and I followed all instruction there with no avail.

https://wordpress.org/support/topic/analytics-gathering-data-analytics-data-is-not-yet-available-please-check-back-9/

By digging into the GSK plugin version 1.34.1 myself, I found the following temporary solution:

Sending site url in unicode shows the Analytics data. So, instead of sending xn--unicodenme-z4a.xxx, send unicodenáme.xxx

**I accomplish that as a temporary solution by hardcoding**

…\google-site-kit\includes\Modules\Analytics.php around line 613

```
/* Added by Horacio to make the IDN work on this plugin */
$request['dimensionFilterClauses'][0]->filters[0]->expressions[0] = 'unicodenáme.xxx';
$request['dimensionFilterClauses'][0]->filters[0]->expressions[1] = 'www.unicodenáme.xxx';
```

**And now Analytics shows fine everywhere in my IDN web site.**

Note: obviously my website's url is not as shown here, this is just a sample of what an IDN url is.

Of course, a permanente solution will depend on Google developers to make Site Kit by Google compatible with IDN web sites. Perhaps by using the viewID instead of the url.

Please understand that this issue have nothing to do with environment (device, OS, platform, PHP and WordPress version, other plugins, etc.).

It is simply that the GSK plugin is sending information to the Analytics Reporting API that it does not understand and it reports no data.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Module::permute_site_url` method should be enhanced so that it also considers permutations for a Unicode or Punycode URL if needed.
    * If the site URL is an international URL with unicode characters, also create the punycode version.
    * If the site URL is an international URL in punycode format, also create the unicode version.
    * These permutations also need to go through the other permutation of considering HTTP vs HTTPS and `www.` vs non-`www.`, so any site that uses an international URL now should end up with 8 permutations - non-international URLs should be kept as now (i.e. 4 permutations).
* In other words, the above change should result in Analytics and AdSense report requests correctly filtering by domain even for international site URLs (no matter whether stored in WordPress as unicode or punycode).

## Implementation Brief

Update the `Module::permute_site_url` method:
* Add a `hosts` array
* add the `wp_parse_url` parsed hostname to the `hosts` array
* if the hostname is prepended by the IDN `xn--` string
  * convert the hostname to unicode
     `idn_to_utf8( $hostname, 0, INTL_IDNA_VARIANT_UTS46 )`
* otherwise convert the hostname to IDN ASCII
      `idn_to_ascii( $hostname, IDNA_DEFAULT, INTL_IDNA_VARIANT_UTS46 )`
* if the `hosts` array does not already contain the converted hostname, add it to the `hosts` array
* for each of the items in the `hosts` array add the http, https and www permutations. 

### Test Coverage

* n/a

### Visual Regression Changes

* n/a

## QA Brief

* Create a release zip and upload it to a site which has an IDN domain name
* Check that Analytics data is being displayed in GSK
@jamesozzie has a suitable site with an IDN.

## Changelog entry

* Fix bug where the filter behavior used for Analytics and AdSense report data was not working for sites with a unicode or punycode domain.

**Comment by abdullah1908** [comment] 2021-06-21 12:39
@HFigarella thanks for submitting the issue along with the useful information. We really appreciate your efforts & research. We'll surely try to recreate this issue at our end & then get back to you with any possible information.

**Comment by HFigarella** [comment] 2021-06-23 06:01
**GSK 1.35.0 the same issue**

Temporary solution (_until next plugin update_):

1. Edit …\google-site-kit\includes\Modules\Analytics.php
2. Insert these 2 lines  at line 623

```
/* Added by Horacio to make the IDN work on this plugin */
$request['dimensionFilterClauses'][0]->filters[0]->expressions[0] = 'unicodenáme.xxx';
$request['dimensionFilterClauses'][0]->filters[0]->expressions[1] = 'www.unicodenáme.xxx';
```

where 'unicodenáme.xxx' is your IDN as explained above

**Comment by jamesozzie** [comment] 2021-06-23 19:07
@HFigarella Thanks for the update. Just to let you know we're awaiting traffic on a couple of tests sites to replicate your setup. We've used subdomains with similar characters to your own. We'll keep you posted here, thank you.

**Comment by bethanylang** [comment] 2021-06-25 14:24
@jamesozzie Assigning to you for follow-up.

**Comment by jamesozzie** [comment] 2021-06-25 14:39
Still awaiting significant traffic, while also awaiting the site to be listed in Search. 

For additional context we've created a subdirectory install using the same "unicodenáme" within the path of a domain that features an umlaut. Screenshot below. Note that there is traffic when accessing this site on Google Analytics, although minimum.   With no console errors we're awaiting both search and Analytics traffic before further testing. 

![image](https://user-images.githubusercontent.com/41326532/123440850-2291f400-d5cb-11eb-8360-9e2910272fdf.png)

**Comment by HFigarella** [comment] 2021-06-26 02:37
J,

The good news is that I am noticing the url of the site you are testing on this image is an **IDN** (because the second character 'ü' is Unicode)

türkxxx.xxx [Unicode] = xn--trkxxx-3ya.xxx (ASCII)

for the purpose of the issue of GSK talking to the Analytics Reporting API what follows the domain name ($_SERVER['REQUEST_URI']) is irrelevant.

Therefore,

1. If the domain name türkxxx.xxx has an Analytics account and https://analytics.google.com/analytics/web/ shows data **and**
2. …\google-site-kit\includes\Modules\Analytics.php is edited to add the following 2 lines on line 623

```
/* Added by J. to make the IDN work on this plugin */
$request['dimensionFilterClauses'][0]->filters[0]->expressions[0] = 'türkxxx.xxx';
$request['dimensionFilterClauses'][0]->filters[0]->expressions[1] = 'www.türkxxx.xxx';
```

You will see Analytics data for the site türkxxx.xxx

Of course, you have to replace the x with the actual characters of your domain name shown in the image above.

You have to understand that the message "Analytics Data is not yet available ..." for this case is the GSK's javascript response for "it did not get a reply from the API [because the url is provided in ASCII and it is expected to be Unicode]"

**Comment by HFigarella** [comment] 2021-06-26 04:34
**FURTHER DETAILED ANALYSIS OF GSK HANDLING OF IDN WEB SITES**

**Summary**: the solution is to get rid of an unnecessary $dimension_filter and its $dimension_filter_clause.

**Explanation**

The communication between the **GSK plugin** for WP and **Reporting API v4**  is done with this JSON representation:

```
{
"reportRequests": [
    {
      "viewId": "xxxxxxxxx",
```

where **viewId** is all is needed to identify the data to be displayed inside the Analytics windows of the plugin. That is all **Reporting API v4** needs to show the data.

GSK gets the **viewId** on line 919 of file ....\google-site-kit\includes\Modules\Analytics.php

`		$request->setViewId( $profile_id );`

_For reasons which do not make sense to me_, GSK up to version 1.35.0 adds an unneeded filter to the hostname on line 945 of the same file

```
		$dimension_filter = new Google_Service_AnalyticsReporting_DimensionFilter();
		$dimension_filter->setDimensionName( 'ga:hostname' );
		$dimension_filter->setOperator( 'IN_LIST' );
		$dimension_filter->setExpressions( $hostnames );
		$dimension_filter_clause = new Google_Service_AnalyticsReporting_DimensionFilterClause();
		$dimension_filter_clause->setFilters( array( $dimension_filter ) );
		$dimension_filter_clauses[] = $dimension_filter_clause;
```

which create the following values for the $request array to be sent to the **Reporting API v4**

```
	"dimensions": [
	{
	  "name": "ga:hostname",
	  
	  "dimensionFilterClauses": [
		{
			[expressions] => Array
				(
					[0] => **siteurl**
				)

			[not] => 
			[operator] => IN_LIST
		}
	  ],
```

**AND that is what creates an issue for cases where the siteurl is an IDN**

the filters says:

`show data for "ga:hostname" that are in the list of "siteurl".`

The result is none, and this is why: (please refer to file ....\google-site-kit\includes\Modules\Analytics.php)

1. On line 934 the value for **$hostnames** is created from the value of **$site_url:**

```
		$hostnames = array_values(
			array_unique(
				array_map(
					function ( $site_url ) {
						return wp_parse_url( $site_url, PHP_URL_HOST );
					},
					$this->permute_site_url( $this->context->get_reference_site_url() )
				)
			)
		);
```

**$site_url** is defined on line 438 of file ....\plugins\google-site-kit\includes

`		$site_url = untrailingslashit( $this->get_canonical_home_url() );`

AND that is when the issue with IDN starts. WordPress (PHP) will always report the site_url as the ASCII format.

2. the value for "ga:hostname" is always in the Unicode format as reported by 'https://analytics.google.com/analytics/web/'

3. The filter translate to:

`show data for "türkxxx.xxx" (_Unicode_) that are in the list of "xn--trkxxx-3ya.xxx" (_ASCII_).`

4.  **GSK** does not get data returned from **Reporting API v4** and shows:

```
Analytics Gathering Data
Analytics data is not yet available, please check back
```

which is the result of the API not returning data when it is told to gimme "apple" from your list of "animals".

I said at the beginning that this filter does not make any sense to me because the plugin is installed on ONE web site with one site url with one domain name. So why filter it?

Therefore, **THE SOLUTION IS SIMPLE**. Get rid of that filter!

by deleting all these lines starting with line 945 on file ....\google-site-kit\includes\Modules\Analytics.php

```
/* Modified by Horacio to make plugin compatible with Reporting API v4 when site url is IDN */
//		$dimension_filter = new Google_Service_AnalyticsReporting_DimensionFilter();
//		$dimension_filter->setDimensionName( 'ga:hostname' );
//		$dimension_filter->setOperator( 'IN_LIST' );
//		$dimension_filter->setExpressions( $hostnames );
//		$dimension_filter_clause = new Google_Service_AnalyticsReporting_DimensionFilterClause();
//		$dimension_filter_clause->setFilters( array( $dimension_filter ) );
//		$dimension_filter_clauses[] = $dimension_filter_clause;
```
**THE ISSUE IS GONE.**

GSK shows **all the data** on regular domain names AND on [internationalized domain name](https://www.icann.org/resources/pages/idn-2012-02-25-en#:~:text=Internationalized%20Domain%20Names%20(%20IDNs%20)%20enable,allowed%20by%20relevant%20IDN%20protocols.) (IDN) 

This is  ALL what **Reporting API v4** is expecting on $request to show Analytics data on line 540

`				$request = $this->create_analytics_site_data_request( $request_args );`

The content of the array is: _(Please notice that only the **[viewId]** => xxxxxxxxx is actually needed. Not the hostname, not the siteurl)_

```
$request = Google\Site_Kit_Dependencies\Google_Service_AnalyticsReporting_ReportRequest Object
(
    [collection_key:protected] => segments
    [cohortGroupType:protected] => Google\Site_Kit_Dependencies\Google_Service_AnalyticsReporting_CohortGroup
    [cohortGroupDataType:protected] => 
    [dateRangesType:protected] => Google\Site_Kit_Dependencies\Google_Service_AnalyticsReporting_DateRange
    [dateRangesDataType:protected] => array
    [dimensionFilterClausesType:protected] => Google\Site_Kit_Dependencies\Google_Service_AnalyticsReporting_DimensionFilterClause
    [dimensionFilterClausesDataType:protected] => array
    [dimensionsType:protected] => Google\Site_Kit_Dependencies\Google_Service_AnalyticsReporting_Dimension
    [dimensionsDataType:protected] => array
    [filtersExpression] => 
    [hideTotals] => 
    [hideValueRanges] => 
    [includeEmptyRows] => 1
    [metricFilterClausesType:protected] => Google\Site_Kit_Dependencies\Google_Service_AnalyticsReporting_MetricFilterClause
    [metricFilterClausesDataType:protected] => array
    [metricsType:protected] => Google\Site_Kit_Dependencies\Google_Service_AnalyticsReporting_Metric
    [metricsDataType:protected] => array
    [orderBysType:protected] => Google\Site_Kit_Dependencies\Google_Service_AnalyticsReporting_OrderBy
    [orderBysDataType:protected] => array
    [pageSize] => 10
    [pageToken] => 
    [pivotsType:protected] => Google\Site_Kit_Dependencies\Google_Service_AnalyticsReporting_Pivot
    [pivotsDataType:protected] => array
    [samplingLevel] => 
    [segmentsType:protected] => Google\Site_Kit_Dependencies\Google_Service_AnalyticsReporting_Segment
    [segmentsDataType:protected] => array
    [viewId] => xxxxxxxxx
    [internal_gapi_mappings:protected] => Array ()
    [modelData:protected] => Array ()
    [processed:protected] => Array ()
    [dimensions] => Array
        (
            [0] => Google\Site_Kit_Dependencies\Google_Service_AnalyticsReporting_Dimension Object
                (
                    [collection_key:protected] => histogramBuckets
                    [histogramBuckets] => 
                    [name] => ga:date
                    [internal_gapi_mappings:protected] => Array ())
                    [modelData:protected] => Array ()
                    [processed:protected] => Array ()

                )
        )
    [dimensionFilterClauses] => Array ()
)
```

**Comment by bethanylang** [comment] 2021-06-28 18:45
@HFigarella Thank you for your detailed review and suggestions here, as well as your patience as we worked to investigate this issue on our end. I'm going to escalate this to our engineering team so that they can review your replies, ask any follow-up questions, and ultimately identify the best solution. We'll be back in touch here soon!

**Comment by Hazlitte** [comment] 2021-06-29 15:46
I've had a look into this and to maintain the dimensions filter functionality we could create a second array of unicode hostnames:
* Parse the `$hostnames` array
* if a hostname is `punycode` ( prepended by `xn--` ) create a unicode version using `idn_to_utf8`
Then concatenate the arrays before passing the unified array of unicode and `punycode` domains to the dimensions filter.

**Comment by felixarntz** [comment] 2021-06-29 15:57
One additional note: The same bug also affects AdSense, where we don't transform URLs as needed either. I'll include that in the ACs.

**Comment by HFigarella** [comment] 2021-06-29 20:20
These are the times where **GSK** refers to the value of **site url** given by PHP in the **ASCII format**

```
....\google-site-kit\includes\Context.php (6 hits)
	Line 438: 		$site_url = untrailingslashit( $this->get_canonical_home_url() );
	Line 448: 		 * @param string $site_url Reference site URL, typically the WordPress home URL.
	Line 450: 		$reference_site_url = apply_filters( 'googlesitekit_site_url', $site_url );
	Line 455: 			$reference_site_url = $site_url;
	Line 464: 		if ( $reference_site_url !== $site_url ) {
	Line 465: 			$url = str_replace( $site_url, $reference_site_url, $url );
....\google-site-kit\includes\Core\Assets\Assets.php (6 hits)
	Line 646: 		$site_url     = $this->context->get_reference_site_url();
	Line 651: 			'referenceSiteURL' => esc_url_raw( trailingslashit( $site_url ) ),
	Line 652: 			'userIDHash'       => md5( $site_url . $current_user->ID ),
	Line 735: 		$site_url     = $this->context->get_reference_site_url();
	Line 740: 			'siteURL'          => esc_url_raw( $site_url ),
	Line 742: 			'siteUserID'       => md5( $site_url . $current_user->ID ),
....\google-site-kit\includes\Core\Modules\Module.php (3 hits)
	Line 651: 	 * @param string $site_url Site URL to get permutations for.
	Line 654: 	final protected function permute_site_url( $site_url ) {
	Line 658: 		$host = wp_parse_url( $site_url, PHP_URL_HOST );
....\google-site-kit\includes\Modules\AdSense.php (2 hits)
	Line 542: 				function ( $site_url ) {
	Line 543: 					return 'DOMAIN_NAME==' . wp_parse_url( $site_url, PHP_URL_HOST );
....\google-site-kit\includes\Modules\Analytics.php (2 hits)
	Line 937: 					function ( $site_url ) {
	Line 938: 						return wp_parse_url( $site_url, PHP_URL_HOST );
....\google-site-kit\includes\Modules\Analytics_4.php (3 hits)
	Line 236: 		$site_url = $this->context->get_reference_site_url();
	Line 239: 		$datastream->setDisplayName( wp_parse_url( $site_url, PHP_URL_HOST ) );
	Line 240: 		$datastream->setDefaultUri( $site_url );
....\google-site-kit\includes\Modules\Search_Console.php (17 hits)
	Line 219: 				$site_url = $data['siteURL'];
	Line 220: 				if ( 0 === strpos( $site_url, 'sc-domain:' ) ) { // Domain property.
	Line 221: 					$site_url = 'sc-domain:' . $url_normalizer->normalize_url( str_replace( 'sc-domain:', '', $site_url, 1 ) );
	Line 221: 					$site_url = 'sc-domain:' . $url_normalizer->normalize_url( str_replace( 'sc-domain:', '', $site_url, 1 ) );
	Line 223: 					$site_url = $url_normalizer->normalize_url( trailingslashit( $site_url ) );
	Line 223: 					$site_url = $url_normalizer->normalize_url( trailingslashit( $site_url ) );
	Line 226: 				return function () use ( $site_url ) {
	Line 231: 						$site = $this->get_searchconsole_service()->sites->get( $site_url );
	Line 235: 						$response = $this->get_searchconsole_service()->sites->add( $site_url );
	Line 246: 						$site = $this->get_searchconsole_service()->sites->get( $site_url );
	Line 250: 					$this->get_settings()->merge( array( 'propertyID' => $site_url ) );
	Line 301: 								$site_url = untrailingslashit( $entry['siteURL'] );
	Line 303: 									$site_url = $this->strip_url_scheme( $site_url );
	Line 303: 									$site_url = $this->strip_url_scheme( $site_url );
	Line 304: 									$site_url = $this->strip_domain_www( $site_url );
	Line 304: 									$site_url = $this->strip_domain_www( $site_url );
	Line 307: 								$match = $this->is_url_match( $site_url, $current_url );
```

If that filter mentioned above is to be kept, then as mentioned by H, **site url** has to be converted using `idn_to_utf8`

An easy way to accomplish that for the **Analytics data** is to modify line **934** of ....\google-site-kit\includes\Modules\Analytics.php) changing the value for $hostnames created from the value of $site_url:

```
		$hostnames = array_values(
			array_unique(
				array_map(
					function ( $site_url ) {
						return wp_parse_url( idn_to_utf8( $site_url ), PHP_URL_HOST );
					},
					$this->permute_site_url( $this->context->get_reference_site_url() )
				)
			)
		);
```

**Comment by jamesozzie** [comment] 2021-06-30 15:07
@Hazlitte While you're looking into this I have a site setup with the same "unicodenáme" as part of the site URL where I can reproduce this issue. The site has traffic in both Search Console and Analytics directly, no issue with Site Kit's Search Console reporting, only Analytics.

**Comment by Hazlitte** [comment] 2021-07-01 09:09
@jamesozzie Thank you for doing some more testing to confirm this.  @felixarntz reported that the Adsense module is subject to the same bug.  Is your site connected to Adsense and is it exhibiting the same problem?

**Comment by jamesozzie** [comment] 2021-07-01 09:52
@Hazlitte I've connected the site to AdSense although it's in the approval process. Happy to share a login should you need it.

**Comment by eugene-manuilov** [comment] 2021-07-01 16:05
Thanks, @Hazlitte. I have made a tiny change in the IB, but it looks good. Could you please add an estimate to this ticket?

**Comment by Hazlitte** [comment] 2021-07-01 16:54
@eugene-manuilov Yes of course, I thought I had done that.  I must have jumped onto something else.

**Comment by eugene-manuilov** [comment] 2021-07-01 19:51
IB :heavy_check_mark:

**Comment by aaemnnosttv** [comment] 2021-07-07 07:45
@felixarntz @eugene-manuilov – regarding the current IB, we can't rely on `idn_to_*` functions as these are provided by the `intl` PHP extension that isn't required by WordPress, or otherwise guaranteed to be available.

I noticed we use `\Requests_IDNAEncoder` in `\Google\Site_Kit\Core\Util\Google_URL_Normalizer` which allows for encoding UTF8 to ASCII without relying on this extension. However, there doesn't seem to be an equivalent for decoding the ASCII punycode (`xn--unicodenme-z4a.example`) to UTF8 (`unicodenáme.example`).

We could solve this by adding [`true/punycode`](https://packagist.org/packages/true/punycode) which is PHP only, with a single dependency: `symfony/polyfill-mbstring` (although previous versions require `ext-mbstring` instead). What do you guys think? Any reason why we shouldn't add this to handle both cases?

**Comment by Hazlitte** [comment] 2021-07-07 14:43
@aaemnnosttv I tested `idn_to_*` on a  few dedicated hosting providers (WPEngine, Webfaction...) and the functions work.  However I then tested them on some servers I installed from scratch on Rackspace, Digital Ocean and Linode and in those environments they do not.  So the required PECL extensions are not installed by default and these functions are not guaranteed.  Perhaps we could use `function_exists` for now.

**Comment by felixarntz** [comment] 2021-07-07 19:29
@aaemnnosttv I think pulling in `symfony/polyfill-intl-idn` sounds good. We don't need to update ACs since they don't specify the requirements - let's make this change in the PR, or we could also add it to the IB if that helps.

**Comment by HFigarella** [comment] 2021-07-08 07:59
**GSK 1.36.0** the same issue.

**My temporary solution to be able to see Analytics data on my IDN web site:**
by deleting all these lines starting with line 956 on file ....\google-site-kit\includes\Modules\Analytics.php

'ga:hostname' is Unicode
$hostnames is ASCII

Because **$hostnames** is not 'IN_LIST' of **'ga:hostname'**, **Reporting API v4** returns no data without any message

```
/* Modified by Horacio to make plugin compatible with Reporting API v4 when site url is IDN */
//		$dimension_filter = new Google_Service_AnalyticsReporting_DimensionFilter();
//		$dimension_filter->setDimensionName( 'ga:hostname' );
//		$dimension_filter->setOperator( 'IN_LIST' );
//		$dimension_filter->setExpressions( $hostnames );
//		$dimension_filter_clause = new Google_Service_AnalyticsReporting_DimensionFilterClause();
//		$dimension_filter_clause->setFilters( array( $dimension_filter ) );
//		$dimension_filter_clauses[] = $dimension_filter_clause;
```


**By the way, GSK 1.36.0 works fine on my own server at home running:**

**WordPress** 5.8-RC2-51376 (today's Bleeding Edge)

**Operating System** : Windows Server 2019 64 Bit
**Web Server** : Microsoft-IIS/10.0
**MYSQL** Version : 8.0.25
**PHP** Version : 8.0.8

**Jetpack** Bleeding Edge | 10.0-alpha-1010741769-gd0a5970

and no conflict with 70 plugins many of which are created by me, and not published anywhere else.

**Comment by aaemnnosttv** [comment] 2021-07-08 17:45
@felixarntz after taking a quick look at this, I think it will be easier to use the `true/punycode` package since it only adds a class. The reason is that we have to wrestle with our PHPScoper config a bit to prevent some things from being prefixed (as we would in the case of a polyfill).

From the example, the usage looks quite nice as well.

```php
<?php

// Import Punycode
use TrueBV\Punycode;

$Punycode = new Punycode();
var_dump($Punycode->encode('renangonçalves.com'));
// outputs: xn--renangonalves-pgb.com

var_dump($Punycode->decode('xn--renangonalves-pgb.com'));
// outputs: renangonçalves.com
```

We should probably go this route for now for simplicity.

**Comment by felixarntz** [comment] 2021-07-08 17:56
@aaemnnosttv Great find - using that sgtm.

**Comment by HFigarella** [comment] 2021-07-21 03:30
**GSK 1.37.0** the same issue. I am still applying my temporary solution mentioned above

**Comment by bethanylang** [comment] 2021-07-21 13:23
Thanks for your patience here, @HFigarella. We're planning to work on a fix for this issue in our next sprint and we'll update here when it's been released.

**Comment by cole10up** [comment] 2021-07-30 17:13
### **QA ❌**

@jamesozzie I tried with the latest zip with the domain you used above. I tried a few different Analytics accounts with known data. 

![image](https://user-images.githubusercontent.com/57115907/127688157-026d81e7-7102-4a08-980e-f753605ef711.png)

Going to shift this one back to Execution.

**Comment by aaemnnosttv** [comment] 2021-08-02 09:11
@cole10up I tested this on the same site and it worked for me. Maybe a cache issue before?

Here's last 28 days 
![image](https://user-images.githubusercontent.com/1621608/127833923-c5d86ed3-96bf-4f44-8923-051c78b99e2f.png)

You need to go back to the 90 day range to see the actual data.
![image](https://user-images.githubusercontent.com/1621608/127834073-6de2a734-2b42-4414-849a-9c13b3f41179.png)

Also, the site stores its URL as punycode as well, so I've tested with the UTF-8 version with a leading `www` too as part of the issue here is to include these combinations.

Real site settings
![image](https://user-images.githubusercontent.com/1621608/127835084-94ac53b9-8d36-4445-ac41-9da7dd7888db.png)

Test site custom URL (note added www subdomain)
![image](https://user-images.githubusercontent.com/1621608/127835192-53a42d5f-bdc1-4191-ab4b-f556d9190715.png)

Default URL set on property
![image](https://user-images.githubusercontent.com/1621608/127835661-61ee85f6-8a18-4059-8188-af9ed642ff5e.png)

* All traffic widget looks the same (requires cache clear to refetch again using new URL)
* Also, top pages/content widget has data as well 
![image](https://user-images.githubusercontent.com/1621608/127835893-94d14bc1-2e74-4b8f-b84f-cccd4660a3e1.png)

Sending back to QA for another pass.

**Comment by jamesozzie** [comment] 2021-08-02 09:30
@aaemnnosttv They are actually different sites, there is the https://xn--trkish-3ya.com site but also the https://xn--trkish-3ya.com/xn--unicodenme-z4a2/ site, which is a separate WP install. This includes the path matching the users setup. 

I'll grant you access to the https://xn--trkish-3ya.com site now if you want to take a look.

**Comment by wpdarren** [comment] 2021-08-02 13:52
### QA Update: ⚠️ 

@aaemnnosttv I noticed in the AC it also mentions AdSense, but it's not in the QAB. Should we be checking to make sure that the data is appearing on that module too, and if we do, would the tester plugin suffice to manipulate data? 

**Verified:**

- With Analytics connected I am able to see data in the Dashboard and also on the module page.  

![image](https://user-images.githubusercontent.com/73545194/127872358-e585db0c-ed4e-46be-9d5b-7f5f15441735.png)

![image](https://user-images.githubusercontent.com/73545194/127872463-cf0da89a-adf8-412d-bb02-8c367143f48e.png)

**Closed** 2021-08-02 20:29 UTC
Labels: Group: Escalation, Module: AdSense, Module: Analytics, P1, Rollover, Type: Bug, Type: Support

**Comment by HFigarella** [comment] 2021-08-02 21:23
GSK Version **1.38.0** works fine with an internationalized domain name (IDN)!

**Site**: (_something like_) unicodenáme.xxx (unicode)
Self hosted at home and on production with thousands of visitor a day.
OS Windows Server 2019 - Microsoft-IIS/10.0
WordPress version 5.9-alpha-51524
MySQL version 8.0.26 for Windows
PHP version 8.0.9 64bit
Jetpack version 10.1-alpha:1627440389
Plus more than 70 other plugins, some of them mine not published anywhere else

Muchas gracias a todos
