### ISSUE TITLE
Don't show "Analytics gathering data" message (blue box at the top) if Analytics is actually not connected

### ISSUE THREAD

**Issue by bjackson27** [google/site-kit-wp#180] opened 2019-07-10 19:50 UTC
For any case where the reason why we're not showing stats is that the user needs to complete setup, let's tell them that. Make this less severe (not "Data error in $PRODUCT") and add a CTA. 

If this is possible. In this case, we can say "Complete the setup of Analytics to see more stats." and add a link to Settings as CTA.

<img width="672" alt="0af077d109a7547169578f4051a20631" src="https://user-images.githubusercontent.com/28811945/60999947-fd464580-a321-11e9-8f67-8dc7864cc0a2.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment] 2019-07-18 10:23
Duplicate of #52 and #191

**Closed by felixarntz** 2019-07-18 10:23 UTC
