### ISSUE TITLE
Dashboard: inconsistent Analytics widget state when no account

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#731] opened 2019-10-28 20:39 UTC
## Bug Description

The Site Kit dashboard shows inconsistent states for Analytics widgets if the user is signed in with a Google account that has no Analytics account.

Specifically, the Analytics widget under "Search Funnel" shows a zero-data state, while the Analytics widget under "Popularity" shows a data error state.

## Steps to reproduce

1. Setup Site Kit using a site with a user that has no Analytics account
1. Visit Site Kit dashboard

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/67715840-44d90600-f9d3-11e9-8ed6-de7bc6d69764.png)

![image](https://user-images.githubusercontent.com/1621608/67715835-41457f00-f9d3-11e9-8c45-7a3e00be45df.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

For users who set up a new GA account during the GA module setup, display zero-state message in all relevant tiles: "Analytics gathering data"

## Implementation Brief

* 

## Changelog entry

*

**Comment by marrrmarrr** [comment] 2019-11-19 14:10
@aaemnnosttv 
To understand the triggering conditions better, are these screenshots from before or after GA module setup, and for first or second admin user? 

IIRC in the case where the user just completed initial setup as first admin and doesn't have a GA account, the plugin would display the "set up GA" CTA in those blocks:
<img width="569" alt="Screenshot 2019-11-19 at 15 07 51" src="https://user-images.githubusercontent.com/13304791/69153357-644ce580-0ade-11ea-97aa-01e58551645c.png">

**Comment by aaemnnosttv** [comment] 2019-11-19 22:05
I believe it is after Analytics setup (no CTA), with a new property that has no data.

**Comment by aaemnnosttv** [comment] 2019-11-21 16:35
Checking this again, I see all blue CTAs before and after Analytics setup so it may have been a special case.

![image](https://user-images.githubusercontent.com/1621608/69357267-7a4cd880-0c8d-11ea-9e49-4138cf72173a.png)

Going to move this to revisit later, until this comes up again.

**Comment by aaemnnosttv** [comment] 2019-11-21 16:56
As a follow up, the last user I tested was not without an Analytics account as described in this issue (and shown in the errors in the screenshot).

I tried again with a user that has no Analytics account and confirmed the same state on the main dashboard:

![image](https://user-images.githubusercontent.com/1621608/69358983-72dafe80-0c90-11ea-82a3-e9eca4af5e7a.png)

Going to set up the Analytics module displays a no-account notice as expected:

![image](https://user-images.githubusercontent.com/1621608/69359055-91d99080-0c90-11ea-8395-aa861e714590.png)

**Comment by ThierryA** [comment] 2020-02-11 14:13
Moving this to escalation to try and reproduce. If not reproducible, let's close this one

**Comment by cole10up** [comment] 2020-03-03 07:29
I couldn't reproduce this one. Setting to Approved. 

Ran a series of tests with members that don't have Analytics accounts. Logging in, installing SK, resetting SK. I didn't see the data error.

**Comment by marrrmarrr** [comment] 2020-03-12 16:47
Closing.

**Closed by marrrmarrr** 2020-03-12 16:47 UTC
Labels: Group: Escalation, P1, Type: Bug
