### ISSUE TITLE
Implement the “no audiences” banner happy path view

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#8155] opened 2024-01-25 11:28 UTC
## Feature Description

Implement the banners shown in the scenarios where all of the selected audiences have been archived in Analytics. This includes both variants of the banner that will be shown to the primary user.

The error state and the [secondary user variants](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.rgbjg9iot5sc) of the banner will be implemented separately, see https://github.com/google/site-kit-wp/issues/8190 and https://github.com/google/site-kit-wp/issues/8577.

See [no audiences banner](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit#heading=h.axdcbrrlug4p) in the design doc.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- Given there is a populated audience selection:
  - Upon the next sync of the cached audience list, if all of the audiences in the selection have been removed from Analytics, the "no audiences" banner should be displayed instead of the set of audiences tiles on the dashboard.
  - The "no audiences" banner will be shown in one of two variants:
    - If there are still audiences available to select, the banner will include a _select other groups_ link button.
      - The variant should follow the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1399-11690&mode=design&t=ncplA7YLtzqUq2gL-0) with the following copy:
        - _It looks like your visitor groups aren’t available anymore. [Select other groups]()._  
          _You can deactivate this widget in [Settings]()._
      - The _select other groups_ link button should open the Selection Panel.
      - The _Settings_ link should navigate to the Settings section.
    - If there are no audiences available to select, the banner will include a link to a relevant support article.
      - The variant should follow the [Figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1509-26878&mode=design&t=ncplA7YLtzqUq2gL-0) with the following copy:
        - _It looks like your visitor groups aren’t available anymore. Learn more about how to group site visitors in [Analytics]()._  
          _You can deactivate this widget in [Settings]()._
      - The _Analytics_ link should open the [introduction to audiences in Google Analytics](https://support.google.com/analytics/answer/12799087) article in a new tab.
      - The _Settings_ link should navigate to the Settings section.
  - The "no audiences" banner should continue to be shown in the appropriate variant until a new audience selection has been saved.
- The [Info Notice Widget](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-infonoticewidget--default)  should only be displayed when the Audience Tiles Widget is displayed. 

---

- Ensure the mobile designs are implemented as per [Figma](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1669-40490&mode=design&t=ncplA7YLtzqUq2gL-0).
- Note that all copy should be verified with Figma as the source of truth.

## Implementation Brief

- [ ] Create following 4 new components inside `assets/js/modules/analytics-4/components/audience-segmentation/dashboard/`
  - [x] `NoAudienceBannerWidget` - Component responsible for returning the appropriate component, either `NonConfigurableNoAudienceBannerContent` or `ConfigurableNoAudienceBannerContent`. Component should accept the `Widget` and `WidgetNull` just like `AudienceTilesWidget` component mentioned above.
  - [ ] `ConfigurableNoAudienceBannerContent` -  This component is respondible for rendering the "no audience" banner **when dashboard is not in view only context**.
  - [ ] `NonConfigurableNoAudienceBannerContent` -  This component is respondible for rendering the "no audience" banner **when dashboard is in view only context**.
  - [x] `AudienceTiles` - This component will be respondible to display the configured audiences tiles. This will only be called from inside `AudienceTilesWidget` component, when we made a successful check that at least one of the configured audiences exist in the Google analytics.

- [x] `AudienceTilesWidget` component. Accepts `Widget` and `WidgetNull` props. `WidgetNull` should be passed already, we just need to destructure it in the component.
  - [x] Inside this component only retrieve the configured audiences and the available audiences using useSelect hook. This should be already there in the component.
  - [x] All other business logic which is mainly related to fetching different reports for audiences, needs to be moved to `AudienceTiles` component as mentioned in `AudienceTiles` component brief.
  - [x] If none of selected audiences are available in getAvailableAudiences:
  - [x] Return `WidgetNull` from the component if none of the configured audiences present in the available audiences. This implies that we need to display the `NoAudienceBannerWidget` component described below.

- [x] `NoAudienceBannerWidget` component. Accepts `Widget` and `WidgetNull` prop.
  - [x] Inside this component only retrieve the configured audiences (`configuredAudiences`) and the available audiences (`getAvailableAudiences`) using `useSelect` hook, refer `AudienceTilesWidget` [component](https://github.com/google/site-kit-wp/blob/d4418084f18231f5605d576d76234d1674fec2f3/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget.js#L58-L66) for the same.
  - [x] Return `WidgetNull` from component if any of the audience in `configuredAudiences` is available inside `getAvailableAudiences`.
  - [x] If none of selected audiences are available in `getAvailableAudiences`:
    - [ ] If the dashboard is not in view only context, return `ConfigurableNoAudienceBannerContent` component.
    - [ ] If the dashboard is in view only context, return `NonConfigurableNoAudienceBannerContent` banner component.

- [ ] `ConfigurableNoAudienceBannerContent` component. Accepts `Widget` prop.
  - [ ] If there are audiences available (apart from the one selected previously) in `getAvailableAudiences`, then the banner should match the [figma design](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1399-11690&t=9ucLC0kM4mSxyXu0-0).
  - [ ] This component should be created from the `Widget` component.
    - [ ] "Select other groups" will open the selection panel. To open the panel, `AUDIENCE_SELECTION_PANEL_OPENED_KEY` needs to be set to `true` in `CORE_UI` data store as can be seen [here](https://github.com/google/site-kit-wp/pull/8751/files#diff-ba13f7ddf6e1ed8fd9c55178c6306476e32bba59cb70eabebe429f64d198a682R46).
    - [ ] "Settings" link should navigate to the Site Kit's `Admin Settings > Visitor groups`.
  - [ ] If there are audiences unavailable in `getAvailableAudiences`, we should display a different text in the banner as shown in [figma design](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=1509-26878&t=9ucLC0kM4mSxyXu0-0).
    - [ ] The "Analytics" link should open the introduction to audiences in Google Analytics [article](https://support.google.com/analytics/answer/12799087) in a new tab.

- [ ] `NonConfigurableNoAudienceBannerContent` component. Accepts `Widget` prop.
  - [ ] This component should be created from the `Widget` component and should match the [figma design](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=2602-21140&t=IsqfA6VFaKtWbyPY-0).
  - [ ] "Temporarily Hide" link should dismiss the banner and make use of dismissible items infra to note that banner should not get dismissed.
  - [ ] Hiding the banner would effectively hide the widget altogether. So add an additional check [here](https://github.com/google/site-kit-wp/blob/dc7c43eae8fe00068f401eabe43e4d7bb4cae004/assets/js/modules/analytics-4/index.js#L132-L136) before registring widget to check if the item is in the dismissed items list.

- [x] `AudienceTiles` component. Accepts Widget prop.
  - [ ] This can be taken as is from the existing AudienceTilesWidget component.
  - [ ] Remove the call for below from the component as it is no longer needed.
  ```js
    export default whenActive()
  ```

- [x] In `assets/js/modules/analytics-4/index.js`, register a new widget using `widgets.registerWidget(...)` after `analyticsAudienceTiles`.
  - [x] Pass component as `NoAudienceBannerWidget`.

- [x] Most of the styling from #8798 can be reused for the banner as those are mostly similar in aesthetics.
- [x] Ensure that mobile design is matching the [figma design](https://www.figma.com/file/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?type=design&node-id=1669-40490&mode=design&t=ncplA7YLtzqUq2gL-0)
  - [ ] Use the `Cell` component within the widget to stack the components vertically for the mobile design.
  - [ ] A reference of ConsentModeSetupCTAWidget can be take [here](https://github.com/google/site-kit-wp/blob/develop/assets/js/components/consent-mode/ConsentModeSetupCTAWidget.js) for how it uses `Grid` and `Cell` components to take into account about the mobile design.

### Test Coverage

1. Add the tests for `NoAudienceBannerWidget`, `ConfigurableNoAudienceBannerContent` and `NonConfigurableNoAudienceBannerContent` components.
2. Add the tests for AudienceTiles component.
3. Update tests for `AudienceTilesWidget` component as we need to test whether it is returning appropriate components from it based on audiences availability and dashboard view context.
4. Update tests for `AudienceTilesWidget` component as we need to test whether it is returning `WidgetNull` when no configured audiences available anymore.
5. Fix any other failing VRTs.

## QA Brief

* Enable Audience Segmentation feature flag. 
* Connect Analytics module. 
    * At this point, only the Setup CTA should be present. (Ignore the `InfoNoticeWidget` always being there, it is being tackled in a separate issue.)
* Setup Audience Segmentation Feature. 
    * The Audience Tile should appear. 
* Delete one of the currently selected audiences. 
    * The audience tiles should continue to  appear with the available audiences
* Delete all currently selected audience. 
    * The No Audience Banner should appear as described in AC instead of the Audience Tiles. 
        * If there are still audience to select, the "Select other groups" CTA should appear. 
            * Clicking that will open Audience Selection Panel.
    * If there is no additional audience available to select, the alternate version should appear with a support link to analytics as described in AC.
* Confirm that the [Info Notice Widget](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-infonoticewidget--default) is only displayed when the actual Audience Tiles Widget is also being displayed. 

**TIP:** It may  be necessary to sync available audiences after archiving/deleting them in Analytics. You can force this using the following snippet. 

```js
await googlesitekit.data.dispatch('modules/analytics-4').syncAvailableAudiences()
```

For Quickly testing the banner. You can set configured audience to a non-existent one.

```js
await googlesitekit.data.dispatch('modules/analytics-4').setConfiguredAudiences(['garboge'])
```

And for seeing the alternate version, sett the available audiences to an empty array so no audience is available. 

```js
await googlesitekit.data.dispatch('modules/analytics-4').setAvailableAudiences([])
```

## Changelog entry

* Implement the Audience Segmentation "no audiences" banner.

**Comment by techanvil** [comment] 2024-03-28 14:27
I've moved this back to Backlog as the final [in-progress changes to the design doc](https://docs.google.com/document/d/1MGD5Djy6AeeZC4zBtHqS-lQEWD9jw0kf-IIWw-jLCFU/edit?disco=AAABJiKQwSo), relating to audience caching, will probably affect the AC for this one

**Comment by kuasha420** [comment] 2024-06-06 10:34
Hey @ankitrox, Thanks for drafting the IB. A few suggestions:

Instead of baking this inside `AudienceTilesWidget`, what about we create a separate `NoAudienceBannerWidget` widget, and we can encapsulate the logic for the banner with/without configurable audiences inside this new widget. 

The implication is that we need to render `WidgetNull` from either widget when they're not relevant, ie. return `WidgetNull` when configured audiences are not available from `AudienceTilesWidget` and reverse for `NoAudienceBannerWidget`.

Also instead of having two banners, we can keep the logic in a single one, since the difference is only copy and link. Should be manageable in one place. 

Cheers.

**Comment by ankitrox** [comment] 2024-06-07 14:09
Thank you for reviewing the IB @kuasha420 

Adding the `NoAudienceBannerWidget` seems like a good approach. I have updated the IB to include that component, using this will no longer need a new `AudienceTiles` component so I removed it.

However, I think we should keep the `ConfiguarblesNoAudienceBanner` and `NonConfiguarblesNoAudienceBanner` components separate just to keep them simpler. Earlier, a similar feedback has been [received](https://github.com/google/site-kit-wp/issues/8143#issuecomment-2122515480) in IBR from @techanvil on #8143

Assigning this to you for re-review.

Thanks again!

**Comment by kuasha420** [comment] 2024-06-10 00:56
Hi @ankitrox, Thank you for updating the IB. Looking pretty good. Just a couple of points:

1. A separate `AudienceTiles` component may still provide some value. Essentially, we can rename the current `AudienceTilesWidget` to `AudienceTiles`, and keep the reporting and other logic inside it, and render the markup without the `Widget` wrapper. And in the "new" `AudienceTilesWidget` we will essentially render the `AudienceTiles` wrapped in `Widget` if the audiences are available, and `WidgetNull` otherwise. This will probably save us from making bunch of API requests and getting hit with API errors when audiences are not available. 
2. I'm not super opposed to separate `ConfiguarblesNoAudienceBanner` and `NonConfiguarblesNoAudienceBanner`, but seeing that their design is identical, and the logic to determine the difference in copies relies on same thing, I don't see a lot of value in it. We can probably make the separate components for the inner parts, which will essentially be just UI components, and keep the styling and layout in `NoAudienceBanner`, but  doing that vs a couple of conditions in JSX markup doesn't really make much of a difference. 
3. Finally, if we decide to keep the separate components, the suggested name should be something like `ConfiguarbleNoAudienceBannerContent` and `NonConfiguarbleNoAudienceBannerContent`, to make it clear that they only render the inner content, also not the singular term `Configuarble`. 

Cheers.

**Comment by ankitrox** [comment] 2024-06-10 16:37
Thank you @kuasha420 

I have made the necessary changes as suggested, but kept the configurable and non-configurable components separate with the changes in name as suggested.

Assigning this to you for re-review.

Cheers!

**Comment by kuasha420** [comment] 2024-06-11 06:46
Thanks @ankitrox. IB LGTM. :white_check_mark:

**Comment by techanvil** [comment] 2024-06-12 09:59
Thanks guys! Just a heads up, I tweaked the IB to correct the "Configuarble" -> "Configurable" typo.

**Comment by nfmohit** [comment] 2024-07-07 05:27
Hi @kuasha420 . As discussed internally, this issue is back with you to review if its PR needs any changes post the reversal of pivot reports. The `AudienceTilesWidget` component resulted in significant changes and your PR changes its file structure. Thank you!

**Comment by kelvinballoo** [comment] 2024-07-18 15:03
### QA Update ⚠️ 

I tried to do the first test about archiving one audience.
- Upon running the script to force the audience sync, the label for my archived audience is gone but the tile remains. Is that the expectation?
- If I open the dashboard in a new tab, the tile doesn't really appear but the tile box keeps on loading. I was not expecting this. Could we clarify on the expectation for this?

I have attached a video for reference as well:
<Details>
https://github.com/user-attachments/assets/e07c6335-7a5e-4c3d-bf3b-60620f328336

</Details>

**Comment by techanvil** [comment] 2024-07-18 15:17
Hi @kelvinballoo, thanks for flagging this. These points are known issues, and we will be addressing them you've raised via https://github.com/google/site-kit-wp/issues/8145, ensuring the list of selected audiences is updated following the sync.

**Comment by kelvinballoo** [comment] 2024-07-22 12:47
### QA Update ✅ 

Thanks @techanvil for checking. We are good to go on this issue.

- First variant is showing up accordingly when there is no audience selected but there are selectable ones. Copy and layouts are looking good on desktop and mobile viewport. ✅ 
   <Details>
   <img width="396" alt="Screenshot 2024-07-22 at 14 22 02" src="https://github.com/user-attachments/assets/6cc4cd9a-480e-4dfa-8888-b4b7fd5934d7">

   <img width="1135" alt="Screenshot 2024-07-22 at 14 26 03" src="https://github.com/user-attachments/assets/997c68f2-bcce-4a05-ae60-7877e8beaaf9">
   </Details>

- Second variant is showing up accordingly when there is no selectable audience. This was achieved by running the script:
   `await googlesitekit.data.dispatch('modules/analytics-4').setAvailableAudiences([])` 
   
   Copy and layouts are looking good on desktop and mobile viewport. ✅ 
   <Details>
   <img width="1143" alt="Screenshot 2024-07-22 at 14 04 42" src="https://github.com/user-attachments/assets/76e3aa08-96e3-45c0-8342-31a19f691ce6">
   
   <img width="410" alt="Screenshot 2024-07-22 at 14 20 58" src="https://github.com/user-attachments/assets/92734eab-b66b-495e-8e81-1387efa7de1b">
   </Details>

- It's confirmed that the Info Notice Widget is only displayed when the actual Audience Tiles Widget is also being displayed. ✅ 
   <Details>
   <img width="1146" alt="Screenshot 2024-07-22 at 14 03 36" src="https://github.com/user-attachments/assets/ea589c2d-36d1-4a20-b3b3-31036dfda1b2">

   </Details>

**Closed** 2024-07-25 16:00 UTC
Labels: P1, Type: Enhancement, Module: Analytics, Team M
