### ISSUE TITLE
Analytics dashboard fatal error and services disconnected

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1422] opened 2020-04-22 16:01 UTC
## Bug Description

One user reporting being disconnected from Site Kit randomly today, on 2 different sites. A fatal error message appeared from within the Analytics module, while the _“Analytics/Search Console data not available_” notices also appear

The "Header Footer Code Manager" plugin was used to insert Analytics tracking code into the site. No previous issues on this site. 

The below html output appears with the Analytics module:
![image](https://user-images.githubusercontent.com/41326532/79992558-8e4e6d80-84ab-11ea-8403-43c49d1a6e37.png)
 
Console errors when visiting site:
![image](https://user-images.githubusercontent.com/41326532/80004412-2f442500-84ba-11ea-96f1-ae4a18408c53.png)

WordPress support topic:
https://wordpress.org/support/topic/site-kit-not-working-today/

Site Health info:
```
### wp-core ###

version: 5.4
site_language: pt_BR
user_language: pt_BR
timezone: America/Sao_Paulo
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 230
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/showmetechcom/public_html
wordpress_size: 105,95 GB (113768292998 bytes)
uploads_path: /home/showmetechcom/public_html/wp-content/uploads/
uploads_size: 105,49 GB (113265311931 bytes)
themes_path: /home/showmetechcom/public_html/wp-content/themes
themes_size: 10,22 MB (10712077 bytes)
plugins_path: /home/showmetechcom/public_html/wp-content/plugins
plugins_size: 173,50 MB (181924659 bytes)
database_size: 1,68 GB (1803992383 bytes)
total_size: 213,30 GB (229030234048 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Herald (herald)
version: 2.2.4
author: meks
author_website: https://mekshq.com
parent_theme: none
theme_features: post-thumbnails, title-tag, post-formats, html5, automatic-feed-links, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, editor-styles, editor-style, align-wide, responsive-embeds, editor-color-palette, editor-font-sizes, widgets, menus
theme_path: /home/showmetechcom/public_html/wp-content/themes/herald

### wp-themes-inactive (1) ###

Twenty Twenty: version: 1.2, author: a equipe do WordPress

### wp-plugins-active (36) ###

Accelerated Mobile Pages: version: 1.0.42, author: Ahmed Kaludi, Mohammed Kaludi
Ads for WP - Advanced Ads & Adsense Solution for WP & AMP: version: 1.9.15.4, author: Magazine3
Advanced Database Cleaner PRO: version: 3.1.0, author: Younes JFR.
Akismet Anti-Spam: version: 4.1.4, author: Automattic
AMP Pro Extension Manager: version: 1.0.6, author: AMPforWP Team
Blog2Social: Social Media Auto Post & Scheduler: version: 6.2.0, author: Blog2Social, Adenion
Comment Link Remove: version: 2.1.1, author: QuantumCloud
Custom 404 Pro: version: 3.2.17, author: Kunal Nagar
Easy Table of Contents: version: 2.0.10, author: Steven A. Zahm
Entry Views: version: 1.0.0, author: Justin Tadlock
Envato Market: version: 2.0.3, author: Envato
Force Regenerate Thumbnails: version: 2.0.6, author: Pedro Elsner
Header Footer Code Manager: version: 1.1.7, author: 99robots
Herald Buddy: version: 1.0, author: meks
ImageMagick Engine: version: 1.6.2, author: Orangelab
Imagify: version: 1.9.9, author: WP Media
Jetpack by WordPress.com: version: 8.4.2, author: Automattic
MailPoet 3 (New): version: 3.46.11, author: MailPoet
MailPoet 3 Premium (New): version: 3.0.83, author: MailPoet
Meks Easy Ads Widget: version: 2.0.4, author: Meks
Meks Easy Social Share: version: 1.2.1, author: Meks
MyThemeShop Theme & Plugin Updater: version: 3.0.3, author: MyThemeShop
Newspaper AMP Theme: version: 2.0.8, author: Mohammed Kaludi, Ahmed Kaludi
OneSignal Push Notifications: version: 2.1.2, author: OneSignal
PublishPress: version: 2.0.6, author: PublishPress
Rank Math SEO: version: 1.0.42.3, author: Rank Math
Redux Framework: version: 3.6.18, author: Team Redux
Schema & Structured Data for WP & AMP: version: 1.9.33, author: Magazine3
Site Kit by Google: version: 1.7.0, author: Google
VaultPress: version: 2.1.1, author: Automattic
WP 404 Auto Redirect to Similar Post: version: 1.0.2, author: hwk-fr
WP Forms for AMP: version: 1.3.2, author: Ahmed Kaludi, Mohammed Kaludi
WPForms Lite: version: 1.6.0.1, author: WPForms
WP Mail SMTP: version: 1.9.0, author: WPForms
WP Review Pro: version: 3.4.5, author: MyThemeShop
WP Rocket: version: 3.5.3, author: WP Media

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: 1656
imagemagick_version: ImageMagick 6.7.8-9 2019-08-08 Q16 http://www.imagemagick.org
gd_version: bundled (2.1.0 compatible)
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.4.10-x86_64-linode132 x86_64
httpd_software: Apache
php_version: 7.3.16 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 300
memory_limit: 2048M
max_input_time: 300
upload_max_size: 100M
php_post_max_size: 512M
curl_version: 7.69.1 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.29-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/showmetechcom/public_html/wp-content
WP_PLUGIN_DIR: /home/showmetechcom/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 2048M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### jetpack ###

site_id: 87979966
ssl_cert: No
time_diff: undefined
version_option: 8.4.2:1586957464
old_version: 8.4.1:1586276387
public: Public
master_user: #8139 bruno.martinez (brmartinez@gmail.com)
current_user: #8139 bruno.martinez (brmartinez@gmail.com)
tokens_set: Blog User
blog_token: eVHCnWbi1N#b%fKyHr$m%v!bX5e9#giT
user_token: O@pzw$ykvq(xE@vnToHzzU@vxPd#l6xc
version: 8.4.2
jp_plugin_dir: /home/showmetechcom/public_html/wp-content/plugins/jetpack/
plan: personal
HTTP_HOST: www.showmetech.com.br
SERVER_PORT: 443
HTTPS: on
HTTP_CF_CONNECTING_IP: 200.148.8.175
HTTP_X_FORWARDED_FOR: 200.148.8.175, 172.69.69.17
HTTP_X_VARNISH: 18029966
REMOTE_ADDR: 200.148.8.175
protect_header: {"trusted_header":"HTTP_X_FORWARDED_FOR","segments":0,"reverse":false}
full_sync: {"started":"Wed, 15 Apr 2020 00:02:39 +0000","finished":"Wed, 15 Apr 2020 00:02:44 +0000","progress":{"options":{"finished":true},"functions":{"finished":true},"constants":{"finished":true},"users":{"total":"1","sent":1,"finished":true,"last_sent":"8112"}},"config":{"options":true,"functions":true,"constants":true,"users":[8112]}}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/www.showmetech.com.br","siteurl":"https:\/\/www.showmetech.com.br","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

### wpforms ###

version: 1.6.0.1
license: false
lite: Maio 6, 2019 @ 10:40am
total_forms: 2
total_entries: 26

### google-site-kit ###

version: 1.7.0
php_version: 7.3.16
wp_version: 5.4
reference_url: https://www.showmetech.com.br
amp_mode: no
site_status: connected-site
user_status: authenticated
active_modules: site-verification, search-console, adsense, analytics, pagespeed-insights, tagmanager
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
	https://www.googleapis.com/auth/adsense: ✅
	https://www.googleapis.com/auth/analytics: ✅
	https://www.googleapis.com/auth/analytics.readonly: ✅
	https://www.googleapis.com/auth/analytics.manage.users: ✅
	https://www.googleapis.com/auth/analytics.edit: ✅
	https://www.googleapis.com/auth/tagmanager.readonly: ✅
	https://www.googleapis.com/auth/tagmanager.edit.containers: ✅
	https://www.googleapis.com/auth/tagmanager.manage.accounts: ✅
search_console_property: https://www.showmetech.com.br/
adsense_account_id: pub-303•••••••••••••
adsense_client_id: ca-pub-303•••••••••••••
adsense_account_status: account-connected
adsense_use_snippet: yes
analytics_account_id: 1074••••
analytics_property_id: UA-1074••••••
analytics_profile_id: 3786••••
analytics_use_snippet: yes
tagmanager_account_id: 3354••••••
tagmanager_container_id: GTM-N5K••••
tagmanager_amp_container_id: none
tagmanager_use_snippet: yes

### publishpress ###

PUBLISHPRESS_VERSION: 2.0.6
PUBLISHPRESS_BASE_PATH: /home/showmetechcom/public_html/wp-content/plugins/publishpress
PUBLISHPRESS_FILE_PATH: /home/showmetechcom/public_html/wp-content/plugins/publishpress/publishpress.php
PUBLISHPRESS_URL: https://www.showmetech.com.br/wp-content/plugins/publishpress/
PUBLISHPRESS_SETTINGS_PAGE: https://www.showmetech.com.br/wp-admin/admin.php?page=pp-modules-settings&module=pp-modules-settings-settings
PUBLISHPRESS_LIBRARIES_PATH: /home/showmetechcom/public_html/wp-content/plugins/publishpress/libraries
PUBLISHPRESS_BASENAME: publishpress/publishpress.php
WP_CONTENT_DIR: /home/showmetechcom/public_html/wp-content
WP_CONTENT_URL: https://www.showmetech.com.br/wp-content
option::date_format: j \d\e F \d\e Y
option::time_format: H:i
option::timezone_string: America/Sao_Paulo
option::gmt_offset: -3
php::date_default_timezone_get: UTC
Framework::FRAMEWORK_BASE_PATH: /home/showmetechcom/public_html/wp-content/plugins/publishpress/vendor/alledia/wordpress-plugin-framework/src
Framework::TWIG_PATH: /home/showmetechcom/public_html/wp-content/plugins/publishpress/vendor/alledia/wordpress-plugin-framework/src/twig
Framework::ASSETS_BASE_URL: https://www.showmetech.com.br/wp-content/plugins/publishpress/vendor/alledia/wordpress-plugin-framework/src/assets
Framework::PLUGIN_NAME: publishpress
Framework::PLUGIN_TITLE: PublishPress

### publishpress-modules (16) ###

modules_settings: on [/home/showmetechcom/public_html/wp-content/plugins/publishpress/modules/modules_settings]
calendar: on [/home/showmetechcom/public_html/wp-content/plugins/publishpress/modules/calendar]
editorial_metadata: on [/home/showmetechcom/public_html/wp-content/plugins/publishpress/modules/editorial_metadata]
content_overview: on [/home/showmetechcom/public_html/wp-content/plugins/publishpress/modules/content_overview]
custom_status: on [/home/showmetechcom/public_html/wp-content/plugins/publishpress/modules/custom_status]
notifications: on [/home/showmetechcom/public_html/wp-content/plugins/publishpress/modules/notifications]
improved_notifications: on [/home/showmetechcom/public_html/wp-content/plugins/publishpress/modules/improved_notifications]
async_notifications: on [/home/showmetechcom/public_html/wp-content/plugins/publishpress/modules/async_notifications]
notifications_log: on [/home/showmetechcom/public_html/wp-content/plugins/publishpress/modules/notifications_log]
roles: on [/home/showmetechcom/public_html/wp-content/plugins/publishpress/modules/roles]
user_groups: on [/home/showmetechcom/public_html/wp-content/plugins/publishpress/modules/user_groups]
dashboard: on [/home/showmetechcom/public_html/wp-content/plugins/publishpress/modules/dashboard]
editorial_comments: on [/home/showmetechcom/public_html/wp-content/plugins/publishpress/modules/editorial_comments]
settings: on [/home/showmetechcom/public_html/wp-content/plugins/publishpress/modules/settings]
efmigration: on [/home/showmetechcom/public_html/wp-content/plugins/publishpress/modules/efmigration]
debug: off [/home/showmetechcom/public_html/wp-content/plugins/publishpress/modules/debug]

### wp_mail_smtp ###

version: 1.9.0
license_key_type: lite
debug: No debug notices found.
```

## Additional Context

- Header and Footer Code Manager used to add Analytics previously
- Same issue occurs with second site, at the same time disconnected
- Other plugins with Analytics features active, such as JetPack
- UA tracking code existings on site at present, Site Kit not recognising when setting up

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by estraatios** [comment] 2020-04-24 08:16
Same problem to me.

A website with 4 admin users. For me, the plugins work normally but for all the other users they get this error.

Also, the plugin is not giving the correct visits. I have it for a month and my website from 10.000 visitors dropped to 2.000.

In the Google analytics the active users were 0. I disable the plugin and add the code directly to the heading. Immediately the active users went to 15. 

The plugin is not working as it is supposed to. I missed a whole month of visiting analytics.

**Comment by jamesozzie** [comment] 2020-04-24 12:55
@estraatios Thanks for the information. Do the other users you mentioned encounter the same message within the Analytics configuration screen? If you could share your [Site Health information](https://i.imgur.com/Rtkmsba.png) we can hopefully identify some common aspects. 

If you want to open a support topic in relation to the incorrect Analytics figures we can look into that further if you'd like to create a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-topic-0).

**Comment by jamesozzie** [comment] 2020-04-27 14:57
Tested a demo site on same hosting providers platform although I was unable to reproduce the same error or discover any hosting security or firewall application which may be causing this error. I didn't install the same plugins during testing. 

Awaiting follow up from user to check whether the same issue arose.

**Comment by cole10up** [comment] 2020-06-08 06:34
**Tested**

Installed latest develop and activated SK. Installed Header Footer Code Manager plugin and activated it. Placed snippet in the header via HFCM

![image](https://user-images.githubusercontent.com/57115907/83998966-99a01000-a916-11ea-831e-3bca1acdbd59.png)

Activated Analytics module.
![image](https://user-images.githubusercontent.com/57115907/83999311-53977c00-a917-11ea-8f3a-02376f99fd23.png)

Was unable to cause the issue.

Moving to L2

**Comment by jamesozzie** [comment] 2020-06-09 22:22
No additional reports of this issue occurring, and unable to reproduce. 

In addition the issue no longer persists for the user who initially reported.

**Comment by eugene-manuilov** [comment] 2020-07-22 18:17
@felixarntz I can't reproduce it neither. I have created a test environment and tried to replicate it as close to the original as possible, but i don't see that error. Looks like this is a unique case and i doubt we can reproduce it.

**Comment by felixarntz** [comment] 2020-07-29 00:37
@jamesozzie Closing this one since it seems to no longer be a problem and we cannot replicate it. It may have been a very specific plugin conflict, but we don't know with which one. Let's reopen if someone reports the same error later.

**Closed by felixarntz** 2020-07-29 00:37 UTC
Labels: Group: Escalation, Type: Bug
