### ISSUE TITLE
Change Analytics setup description

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5046] opened 2022-04-06 20:21 UTC
Related to #4913 and #5045, some of the descriptive text in the Analytics setup flow should be simplified as it is now replaced with the new toggles displayed there.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

**Relying on the `feature/existing-tag-simplification` branch:**

* The Analytics `ExistingTagNotice` should be simplified to only keep the information around GTM tags, but no longer inform about "existing" tags, as these are covered via #4913 and #5045 now.
    * In other words, the only check that should remain in the component is `hasGTMAnalyticsProperty`, and then it should display the notice from `getNoticeForExistingGTMProperty()`.
* Throughout all scenarios of the Analytics setup flow, the following minor copy adjustment should be made:
    * _Please select the account information below. You can change this view later in your settings._ --> _Please select the account information below. You can change this later in your settings._

## Implementation Brief

**Any PR for this must be based on and target the `feature/existing-tag-simplification` branch.**
* Using `assets/js/modules/analytics/components/common/ExistingTagNotice.js`,
	* Keep only the check for `hasGTMAnalyticsProperty` and all the logic associated to it. This means removing the following:
		* `getNoticeForExistingUAAndGA4Tags`
		* `getNoticeForExistingUATag`
		* `getNoticeForExistingGA4Tag`
* Using the files below, update the text as per the second bullet point of the AC.
	* `assets/js/modules/analytics/components/setup/SetupFormGA4.js`
	* `assets/js/modules/analytics/components/setup/SetupFormGA4Transitional.js`
	* `assets/js/modules/analytics/components/setup/SetupFormLegacy.js`
	* `assets/js/modules/analytics/components/setup/SetupFormUA.js`

### Test Coverage
* No new tests to be added.

## QA Brief

* GTM Notices will be shown in the top of the Setup and Settings page when relevant.
* Existing Tag Notice for UA and GA4 will be shown on their respective toggles in Setup page. 
* Existing Tag Notice will continue to surface on top of Settings View and Settings Edit page. 
* The Updated Copy from the AC will be shown on all relevant places. 

## Changelog entry

* N/A

**Comment by tofumatt** [comment] 2022-04-07 14:48
IB ✅

**Comment by wpdarren** [comment] 2022-04-20 14:08
### QA Update: ⚠️ 

@kuasha420 it's possible that this is mentioned on a ticket I've not got to yet, but an observation:  When I edit settings there is no mention of the existing tags, which I found odd. There is also no message above the account, property and view fields, I am sure previously we had a message telling the user to select the account information below. 

So, is what I see in the screenshot below correct? 

![image](https://user-images.githubusercontent.com/73545194/164248877-ca9f322b-dee5-4213-8034-dd3dc916389c.png)
 
**Verified:**

For thee `ExistingTagNotice` Throughout the Analytics setup flow, the minor copy adjustment is made:
`Please select the account information below. You can change this view later in your settings.` 
`Please select the account information below. You can change this later in your settings.`

![image](https://user-images.githubusercontent.com/73545194/164246278-5f894190-8e25-468e-87c9-6f2a1fc94735.png)

**Comment by kuasha420** [comment] 2022-04-20 15:13
@wpdarren That definitely looks odd, I'll have a look. Thanks!

**Comment by wpdarren** [comment] 2022-04-20 15:49
@kuasha420 I have assigned this back to Execution since you're investigating.

**Comment by kuasha420** [comment] 2022-04-22 06:31
There is a big slack discussion on the problem that @wpdarren found. I'm here documenting what went wrong and where we are now regarding this. Also what needs to be done to potentially resolve this issue. 

**What happened?** 
* We used to have separate `ExistingGTMPropertyNotice` and `ExistingTagNotice` before ETS.
* We merged them together in #4703 
    * At that point, if there was both GTM and UA tag, the message for UA would take precedence and shown. 
* In #4913 and #5045 we added Snippet toggle to the Setup flow of the Analytics(UA and GA4). We also `copied` the messaging related to Existing Tag below the toggle. 
    * Note that, this existing tag related messages are only shown under Snippet Toggles in Setup flow. Settings is not changed. 
    * At this point, the setup flow is showing two similar existing tag notices in Setup flow - one above the form and one under the toggles. 
* With this issue, we tried to take care of the duplicate Existing Tag messages by removing them from the top of the Setup screen by removing them from the `ExistingTagNotice` component. 
    * This solves the duplicate message problem in Setup flow. 
    * However, as we haven't implemented Existing Tag messages in the Snippet Toggle for Settings page, the Settings View and Settings Edit screens no longer has any notices related to Existing Tag. 

**Solution**
* Re-purpose current [`ExistingTagNotice`](https://github.com/google/site-kit-wp/blob/202f633bacfc9c1526cb49bfc1f2f6666e98f73f/assets/js/modules/analytics/components/common/ExistingTagNotice.js) as the `ExistingGTMPropertyNotice` which will be used directly on top of Setup Form.
* Restore old combined (GTM and ET) [`ExistingTagNotice`](https://github.com/google/site-kit-wp/blob/4418f58f98244bfd355d5f853ffad6bffb4b40cf/assets/js/modules/analytics/components/common/ExistingTagNotice.js) as the notice that will be shown on Settings(View/Edit) screens. We can refactor it to use `ExistingGTMPropertyNotice` when there is no UA and there is GTM.

**Caveats**
Copies need to be checked and confirmed/corrected. 

@felixarntz I'm assigning this back to you. Please review my finding and proposed solution and let me know how to move forward. Cheers.

**Comment by felixarntz** [comment] 2022-04-25 18:17
@kuasha420 We need to differentiate between the message about **existing tags** vs **GTM properties**. The latter must remain because the toggle doesn't cover it. The first one is now covered by the toggle in setup, so we don't need to show it as a separate message which would be a duplicate. So both setup and settings need to inform about GTM properties at the top if relevant.

I think one point of confusion is that for some reason the current [`ExistingTagNotice`](https://github.com/google/site-kit-wp/blob/202f633bacfc9c1526cb49bfc1f2f6666e98f73f/assets/js/modules/analytics/components/common/ExistingTagNotice.js) component is called "ExistingTagNotice", but does not inform about existing tags, but about GTM properties. So it should probably be renamed to "ExistingGTMPropertyNotice". This wasn't part of the ACs of course, but reviewing this again now, I think it makes things confusing. When renaming this to `ExistingGTMPropertyNotice`, it becomes more clear that this still needs to surface in both the setup flow and settings, because it has nothing to do with the toggle.

Regarding existing tags: We definitely need to maintain one way or the other in settings, informing about existing tags. My take on this is the following:
* Eventually, we should use a message on the toggle like in setup.
* It may be quicker for now to bring back the message in settings, if so, let's do that for now.

In other words:
* Option A: If it's trivial to use the same toggle **with existing tag message** in settings (with the difference that in settings it should _always_ display, not only when there's an existing tag), let's do that.
    * If we do that, let's still duplicate the wrapper component instead of using the same, basically to have something like `SetupUseSnippetSwitch` and `SettingsUseSnippetSwitch`. This way we can easily alter the copy because it may very well need to be slightly different in settings from setup.
* Option B: If it's easier to bring back the notice on existing tags to settings and leave the toggle as it is today in settings, let's do that.

The main thing at this point is that the message remains there in one way or the other. I'll let you assess which one is more straightforward to implement. See also related https://github.com/google/site-kit-wp/issues/4934#issuecomment-1100218663

**Comment by kuasha420** [comment] 2022-04-26 18:56
@felixarntz I have created a follow up PR restoring the existing tag notice for settings page on top of the page as it was the old and already defined UX and identical to the Tag Manager Settings UX. However, I agree that we should revisit this in the future for both Analytics and Tag Manager. 

Couple of questions: 

1. When both existingGTMProperty and existingTag are present, which notice should be shown on Settings? 
2. As users can override the default behavior, we may need to update copies such as `Since this tag refers to the same property selected here, Site Kit will not place its own tag and rely on the existing one` to something like `Since this tag refers to the same property selected here, by default Site Kit will not place its own tag and rely on the existing one. ` or something like that. 
3. Or, we can update the messages based on the toggle state of the Use snippet switches as we do for Setup, but then we're better off putting them in toggle. In that case, I'd still prefer if we have a new well defined issue with copies and designs for Settings page. 

What do you think? Cheers.

**Comment by felixarntz** [comment] 2022-04-27 17:58
@kuasha420 Thanks, that approach you currently have in the PR looks good for now, showing both notices as needed.

I will open a separate issue for finalizing this:
* Keep only the GTM property notice at the top in Settings.
* Use UA and GA4 toggles similar to the ones in setup, including a message about an existing tag if applicable.
* Make similar updates to the Tag Manager settings (related #4934).

**Comment by kuasha420** [comment] 2022-04-27 18:10
@felixarntz I have updated the QA brief. Cheers.

**Comment by wpdarren** [comment] 2022-04-28 13:12
### QA Update: ⚠️ 

@kuasha420 a few observations:

1. Am I assuming correctly that the `but no longer inform about "existing" tags` in the AC does not apply to the Tag Manager settings and Analytics right now?  As you can see from my screenshot the settings does have a note saying `An existing tag was found on your site (GTM-PZMRZQD).` and it doesn't really mention this in the AC or QAB.  

In the settings page __
![image](https://user-images.githubusercontent.com/73545194/165751805-f14858ba-4dad-4759-baf8-11490fe84e58.png)

_When editing settings_
![image](https://user-images.githubusercontent.com/73545194/165751739-d73acda2-d971-463d-a144-2d6c3a1c736e.png)

2. The text on the edit settings screen is `Please select your Tag Manager account and container below. You can change these later in your settings.` which does not make sense when I'm on the settings page.   I am assuming that needs removing? 

**Verified:**

![image](https://user-images.githubusercontent.com/73545194/165755393-93cde169-2fae-441b-882a-b0bd64397cb1.png)

For thee `ExistingTagNotice` Throughout the Analytics setup flow, the minor copy adjustment is made:
`Please select the account information below. You can change this view later in your settings.` 
`Please select the account information below. You can change this later in your settings.`

![image](https://user-images.githubusercontent.com/73545194/164246278-5f894190-8e25-468e-87c9-6f2a1fc94735.png)

**Comment by kuasha420** [comment] 2022-04-28 15:19
@wpdarren you are correct, it's a bit confusing at the moment. 

 1. The AC is only for Setup pages now. Settings is going to be addressed in #5143 
 2. This message will also be modified/removed on the aforementioned issue. 

This can be moved forward, just add a note that this only applies to Setup and we're having another go at it for Settings separately.

**Closed** 2022-05-19 16:23 UTC
Labels: P0, Type: Enhancement, Module: Analytics, Rollover, End of Sprint
