### ISSUE TITLE
Potential fatal error on `auto_update_plugin` filter

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#6624] opened 2023-02-22 13:08 UTC
## Bug Description

There have been reports in the support forums of users encountering a fatal error. This is occurring with the plugin auto updates enabled. 

[One of the impacted users](https://wordpress.org/support/topic/fatal-error-4369/#post-16491856) reported the below response. This response came from their theme provider. 

> The issue is caused by the SiteKit plugin, that plugin is passing incorrect data to a WP function that is also used by Themify Updater plugin which causes it to crash. The issue does not come from the Updater plugin however.The error is in google-site-kit/includes/Core/Util/Auto_Updates.php file, on:
> $is_auto_update_forced_for_sitekit = wp_is_auto_update_forced_for_item( ‘plugin’, null, $sitekit_plugin_data );
> 
> The wp_is_auto_update_forced_for_item function (codex reference: https://developer.wordpress.org/reference/functions/wp_is_auto_update_forced_for_item/) expects an “object” for the third parameter passed to it, the $sitekit_plugin_data, however, is an “array”.
> 
> Fixing this is rather very easy:
> $is_auto_update_forced_for_sitekit = wp_is_auto_update_forced_for_item( ‘plugin’, null, (object) $sitekit_plugin_data );

This started to occur from updates to Site Kit 1.92.0 upwards, based on the reports we've encountered (listed below). 

For those impacted, a temporary workaround may be to disable auto updates while we investigate this further. 

## User reports

- https://wordpress.org/support/topic/fatal-error-4369 | **Open** | Awaiting SH info (_Themify theme_)
- https://wordpress.org/support/topic/auto-updates-fatal-error-report | **Open** | [SH info ](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNjb3suaZsuleA7DcQEZb2lZ15YatoZlIBRUl9P9KpfmZ1rL8mX-4bWce1DNhJ4Yitw) (_Themify theme_)
- https://wordpress.org/support/topic/php-error-572 | **Open** | [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNjEJWYRCGSdaDL3wSILTwg4xsl3geWaFVB6L7mK4timwBkRHzKs6eYXcNIcEfPKNPI) (Divi theme)

Possibly related, although more likely a Google Charts Library conflict (https://github.com/google/site-kit-wp/issues/6524):
- https://wordpress.org/support/topic/fatal-errors-in-the-wordpress-backend-after-latest-site-kit-update/ | **Resolved** | [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNhqhbp0W7EYjpL7wRxlBO2gUWJleN8LRdjbp3NSbLV2j5YRoO2jBilVARL_pwYw1_c) (Themeco theme)

## Steps to reproduce

Unable to recreate as this point. Testing site set up for this purpose, awaiting plugin auto update. ([Details in Asana task](https://app.asana.com/0/1185360131189553/1204016695345815/f))

## Additional Context

 - [Internal testing](https://app.asana.com/0/1185360131189553/1204016695345815/f) - with a site set up using the same theme and plugin environment and one impacted user. Awaiting auto update 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should pass the proper (`object`) type to the core `wp_is_auto_update_forced_for_item` function

## Implementation Brief

* Update `Auto_Updates::sitekit_forced_autoupdates_status` to call the function, casting the plugin data to an object

### Test Coverage

* Add a test to cover this fix

## QA Brief

* This issue fixes a potential error if another plugin or theme hooks into `auto_update_plugin` and access the specific `$item`. It would not happen in SK by itself because WP core does not hook onto this filter (only exposes it as a point of extensibility)
* There is only one instance in the codebase where this was used and it has been covered by an added test
* No precise steps were identified to reproduce this but the potential for the error was fixed

## Changelog entry

* Fix potential type error on `auto_update_plugin` filter.

**Comment by mohitwp** [comment] 2023-02-24 12:41
### QA Update ⚠️ 

@aaemnnosttv I tried to reproduce this issue on test site with the requirement environment and also on InstaWP site, but I'm not able to reproduce this issue.
Also, tried to reproduce issue via updating plugin manually. But not getting any critical error in back end.

Tested using -

- Site Kit Version 1.92.0
- Themify Updater - 1.4.3
- Themify Ultra Theme - Version: 7.1.3

**Comment by wpdarren** [comment] 2023-02-27 15:07
### QA Update: ⚠️ 

@aaemnnosttv @mohitwp 

I have also spent some time trying to recreate this issue but have been unable to.  While the issue is with the Site Kit auto update change, I do wonder if we are unable to recreate because we do not have a licence key.  There seems to be some settings for auto updates but they do not appear unless you have a licence.  Just guessing at this point. 

I feel the only way that we are able to test this, is if we send them a zip file of the `main` branch of Site Kit and see if this fixes the issue for the users.  As it stands it's not something we can test because we are unable to recreate the issue.

**Comment by wpdarren** [comment] 2023-02-27 16:50
Just an update to this ticket.  @jamesozzie has reached out to two of the affected users to see if the fix has resolved the issue.  If the users confirm it is fixed, we can moved this to approved.

**Comment by wpdarren** [comment] 2023-02-28 06:46
### QA Update: ✅ 

While we have been unable to recreate the issue, we sent the main branch zip file to two users, and [one of them](https://wordpress.org/support/topic/auto-updates-fatal-error-report/#post-16510397) has come back and said that it has fixed the issue.  I am moving this to approval as the change has fixed the issue for at least one user.

**Closed** 2023-02-28 14:51 UTC
Labels: Type: Bug, Type: Support, P0
