### ISSUE TITLE
Migration does not flush object cache

### ISSUE THREAD

**Issue by swissspidy** [google/site-kit-wp#810] opened 2019-11-07 10:26 UTC
## Bug Description

I had a weird scenario where I update Site Kit from RC to stable (on a Composer setup), but the object cache was not flushed.

It seems it's because `\Google\Site_Kit\Core\Util\Beta_Migration::migrate_old_credentials` does a migration without flushing the cache.

`\Google\Site_Kit\Core\Util\Migration_1_0_0::migrate_install` is run right after that, but does nothing because the beta migration has already deleted this exact option. So this method seems pretty much useless.

When the cache is not flushed, the setup screen still shows the old non-proxy steps. A manual reset didn't work because of #809. I had to manually clear the object cache using WP-CLI.

## Steps to reproduce

1. Install old RC and update to stable on a Composer installation
2. Try to setup Site Kit again

## Additional Context

 - PHP Version: 7.2
 - Server: nginx, with Memcached object cache dropin
 - Browser: macOS on Chrome
 - Plugin Version: 1.0.1

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* After migrating from a Beta or RC (make sure to test both) version to a stable version, the user should see the proxy setup screen on `googlesitekit-splash`.
* This needs to be specifically verified on a site with an object cache.

## Implementation Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2019-11-12 15:02
I'm not quite sure why flushing the cache would be necessary since the migrations only manipulate individual options and user options. The underlying core functions all handle the necessary updates to the wp cache, so there shouldn't be stale values laying around as long as the `object-cache.php` is implemented correctly.

The `Migration_1_0_0` class only has a call to `wp_cache_flush` since originally the user options were going to be being deleted with a direct DB query. This was changed at some point and the function call stayed, but I don't think it's necessary.

Also, I found that some memcached object cache implementations (including the one I have locally) do not even allow flushing the cache via a web request:

https://github.com/livinglab/openlab/blob/1f47b4b2391ede2660014b0de507ea4914728283/wp-content/object-cache-memcached.php#L281-L289

(I couldn't find the exact one I have, but this is basically the same as the one I have)

@swissspidy can you point me to the `object-cache.php` you use so I can try to reproduce with that?

**Comment by aaemnnosttv** [comment] 2019-11-21 15:51
I tried testing this out as best I could and could not reproduce this. 

I'm not sure how you had installed Site Kit with Composer during the beta, so I didn't test this specifically.

What I did test was setting up a site using Automattic's [memcache object cache](https://github.com/Automattic/wp-memcached), installing and setting up the plugin using `beta-1.0.7` and then updating to the latest version via WP.

![image](https://user-images.githubusercontent.com/1621608/69353085-a1ec7280-0c86-11ea-96e9-7ec4c6fe6376.png)
![image](https://user-images.githubusercontent.com/1621608/69353098-a87aea00-0c86-11ea-9e6e-54b59fd8aa2c.png)

After performing the update on the plugins page, I navigated directly to the Site Kit dashboard. Since we suppress regular notices on the Site Kit dashboard, I saw this:
![image](https://user-images.githubusercontent.com/1621608/69353230-d7915b80-0c86-11ea-97fb-27fd77f77525.png)

The migration/update notice was rendered properly everywhere else though
![image](https://user-images.githubusercontent.com/1621608/69353257-e546e100-0c86-11ea-82c5-1d79b82d539a.png)

Looking at the settings, I can confirm that the old credentials were removed by the migration
![image](https://user-images.githubusercontent.com/1621608/69353300-f7288400-0c86-11ea-8338-b5dfe0ab9d3b.png)

From there, setup using the 1.x flow went smoothly as expected.

---

Moving this back for further refinement.

**Comment by marrrmarrr** [comment] 2020-01-10 15:19
closing, since we weren't able to reproduce and the big majority of users should be off of RC versions now.

**Closed by marrrmarrr** 2020-01-10 15:19 UTC
Labels: Type: Bug
