### ISSUE TITLE
Getting a blank screen 

### ISSUE THREAD

**Issue by amedina** [google/site-kit-wp#14] opened 2019-06-20 15:07 UTC
I am getting a blank screen when trying to access the Site Kit admin screen.
<img width="1672" alt="Screen Shot 2019-06-20 at 5 03 28 PM" src="https://user-images.githubusercontent.com/506089/59859787-b5b14700-937d-11e9-94a5-5a6c48eba7b4.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Changelog entry

* 

## Acceptance criteria

*

**Comment by ivankristianto** [comment] 2019-06-20 15:52
@amedina 
I cannot reproduce the issue even with WP 5.2.2 + Gutenberg 5.9.2 activated.
Can you let me know if you compile Gutenberg from the source or using the plugin from the repo?

**Comment by ThierryA** [comment] 2019-06-25 12:42
_Moved this issue to "Support" label until we can reproduce_

**Comment by ivankristianto** [comment] 2019-06-27 15:30
This issue is caused by the amp plugin,
which is currently fixed by this PR: https://github.com/ampproject/amp-wp/pull/2688

**Comment by ThierryA** [comment] 2019-07-04 11:26
Fixed on the AMP Plugin side https://github.com/ampproject/amp-wp/issues/2679

**Closed by ThierryA** 2019-07-04 11:26 UTC
Labels: P1, Sprint: 2, Type: Bug
