### ISSUE TITLE
Enhanced measurement toggle not respected when creating a new property that requires granting scope

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#8446] opened 2024-03-29 16:01 UTC
## Bug Description

The toggle/control for whether or not a property should have Enhanced Measurement enabled is always being set to ON when the user first needs to grant the additional scope when creating a new property.

This has been captured below in the setup flow, additional testing is needed to also see if this happens in settings or account creation flows.

## Steps to reproduce

- Set up SK
- Connect GA by creating a new property for an existing account and enhanced measurement toggled OFF
- Grant scope when requested
- When returning to SK the property is created automatically but EM is enabled

## Screenshots

https://github.com/google/site-kit-wp/assets/1621608/5b136f89-3476-46ab-9e41-1c0c24a0966c

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The toggled state for Enhanced Measurement should always be respected when creating an account, property, or datastream whether or not an additional scope is required to do so

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment] 2024-03-29 16:27
@aaemnnosttv Is this a duplicate of #8409, or is it different? Thanks!

**Comment by tofumatt** [comment] 2024-03-31 13:38
I noticed that, this one seemed familiar.

Indeed, this is a duplicate of #8409, so closing this one as we already have the other issue in the backlog 😄

**Closed by tofumatt** 2024-03-31 13:38 UTC
Labels: Type: Bug, P1, Module: Analytics
