### ISSUE TITLE
Update usage of deprecated commands in GitHub actions

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#6104] opened 2022-11-03 19:12 UTC
## Bug Description

See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

This also applies to dependencies that need upgrading in some cases.

For example, the GitHub `actions/cache@v2` action raises these deprecation messages as well. See https://github.com/actions/cache/issues/953

The fix for this only seems to exist in the newer v3 of the action, so we should upgrade to that.

**These commands will stop working as of June 1st, 2023**

## Screenshots

![image](https://user-images.githubusercontent.com/1621608/199811328-9d28ec47-480e-4de2-9d84-e30349ca5c9f.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All usage of the deprecated `save-state` and `set-output` commands in GitHub actions should be updated to use non-deprecated methods ([more information](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/))
	* This includes upgrading any actions as needed

## Implementation Brief
* Update the ".yml" files in `.github/workflows` to
	* use `actions/cache@v3` instead of `actions/cache@v2`
	* replace `set-output` and `save-state` (if any) as [per the docs](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#examples).

### Test Coverage
* N/A

### QA:Eng
* Check the PR and make sure there's no deprecation warnings related to commands. 
* Once merged, also check the tests on the merge commit to make sure everything is ok. 

## Changelog entry

* N/A.

**Comment by eugene-manuilov** [comment] 2022-11-17 17:28
IB ✔️

**Comment by techanvil** [comment] 2022-11-22 12:56
@kuasha420, apologies but I've merged this without spotting an indentation error, which is now preventing the workflow from running on  `develop`, see https://github.com/google/site-kit-wp/pull/6190/files#r1029288649

Please could you file a followup PR to address this?

**Comment by techanvil** [comment] 2022-11-25 10:28
## QA :white_check_mark: 

- Confirmed that deprecated `save-state` and `set-output` warnings are no longer occurring since merging this to `develop`.
- For example here's the **E2E (WordPress 5.2, AMP 1.x)** workflow before and after:

_[Before:](https://github.com/google/site-kit-wp/actions/runs/3517977788/jobs/5896369762)_
![image](https://user-images.githubusercontent.com/18395600/203962571-59f024f8-1a52-42b0-89ac-f545266dfa9f.png)

![image](https://user-images.githubusercontent.com/18395600/203962698-8afabb5e-1921-4e26-8d73-4c00afab83c3.png)

_[After:](https://github.com/google/site-kit-wp/actions/runs/3540406660/jobs/5943419878)

![image](https://user-images.githubusercontent.com/18395600/203962843-09549e85-50cd-4efb-9149-18204445d2d4.png)

![image](https://user-images.githubusercontent.com/18395600/203962948-1282fd85-bd21-4507-ab33-d94da1b7eeb2.png)

- Checked across all workflows.
- Note, we still have the "Node.js 12 actions are deprecated..." warning but this will be address in https://github.com/google/site-kit-wp/issues/6188.

**Closed** 2022-12-02 04:17 UTC
Labels: P1, QA: Eng, Type: Infrastructure
