### ISSUE TITLE
Output dashboard sharing details in a users Site Health information

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4440] opened 2021-12-01 18:16 UTC
## Bug Description

With the upcoming dashboard sharing (#6) feature there should be additional flags output in the users Site Health information, displaying the current configurations per module.

These could include the below or something similar:

- ** Product *** dashboard sharing active: Yes || No
- ** Product *** dashboard sharing - who can view: NA || Administrators, Editors, Authors, Contributors
- ** Product *** dashboard sharing - manage view access: NA || Only me || Admins
- ** Product *** dashboard sharing - module owner:  
 

 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment] 2021-12-14 17:03
Duplicate of #4534; closing.

**Closed by bethanylang** 2021-12-14 17:03 UTC
Labels: Type: Feature
