### ISSUE TITLE
Issue with Site Kit menu on Ad Blocking Recovery and User Input screens

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#7215] opened 2023-06-28 02:07 UTC
## Bug Description

While testing #6966 I noticed that the Site Kit menu in the WordPress side bar navigation is broken on the Ad Blocking Recovery screens.  @nfmohit also found that it also appears on the UserInput screens.   Currently, the Dashboard section of the menu appears to load behind the Site Kit header making it hard to navigate.  

AdBlocker Recovery
![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/beaf3749-09ec-4a29-b1dd-6d526f28b773)

UserInput
![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/8024a68e-3734-44ab-a4eb-4d9389544b5b)

We should fix this before we roll out Ad Blocking Recovery because while minor, is a launch blocking issue. 

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment] 2023-06-28 11:23
This isn't specifically related to ABR and it's a duplicate of #6907. Closing as we'll resolve in that issue!

**Closed by bethanylang** 2023-06-28 11:23 UTC
Labels: Type: Bug
