### ISSUE TITLE
Use classnames library for building className values

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#1072] opened 2020-01-24 08:55 UTC
## Feature Description

Gutenberg, WP Core, and many React apps use the popular `classnames` library to build up their `className` values, especially when outputting conditional `className` values or concatenating values.

Right now our usual approach is to do simple string interpolation. _See: https://github.com/google/site-kit-wp/pull/1070#discussion_r370286900 for context_

It'd be nice if we moved to using the `classnames` package instead.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All non-static string `className` props use the `classnames` package to output.

## Implementation Brief

* Add `classnames` to the project's dependencies.
* Search for all instances of `className` props that use string interpolation and replace them with `classnames()` calls.

## Changelog entry

* N/A

**Comment by felixarntz** [comment] 2020-01-24 12:49
That makes sense to me, moving to IB.

**Comment by tofumatt** [comment] 2020-01-27 17:07
IB set; this one's pretty easy; largely just a search+replace 😄

**Comment by aaemnnosttv** [comment] 2020-01-30 15:41
IB ✅

**Comment by cole10up** [comment] 2020-03-03 08:10
General regression of develop passes QA.

Able to setup SK, setup all services, adjust services, reset SK, deactivate and remove.

**Comment by aaemnnosttv** [comment] 2020-03-03 08:37
QA ✅ 

I did find one instance which was from another PR which would have been handled in this issue but wasn't since these were worked on at the same time.

https://github.com/google/site-kit-wp/blob/afe494712f41ce29b23deaff091f579d5e109787/assets/js/modules/tagmanager/setup.js#L674-L677

This can be addressed in #1139 since there is no logic related to the presence of the classname.

Moving to approval 🚀

**Closed** 2020-03-12 18:23 UTC
Labels: P1, QA: Eng, Type: Enhancement
