### ISSUE TITLE
Option to use existing Search Console property for subdomains

### ISSUE THREAD

**Issue by ThomasKujawa** [google/site-kit-wp#792] opened 2019-11-05 09:33 UTC
https://wordpress.org/support/topic/installation-in-subdirectory-2/#post-12087453
## Bug Description

Although there is a GSC property for the domain, a new property is created with the subdirectory.

I wouldn’t want that.

I want to use the data within the domain property.

Also, the links in the widget become erroneous after I have connected Analytics.

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment] 2019-11-27 08:49
@ThomasKujawa Closing this as a duplicate of #325.

**Closed by jamesozzie** 2019-11-27 08:49 UTC
Labels: Type: Enhancement
