### ISSUE TITLE
Unable to Set up Tag Manager and Analytics on a GA4 Property

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#7961] opened 2023-12-07 13:09 UTC
## Bug Description

While testing #6584 I noticed that Site Kit does not allow users to set up Google Tag Manager and Analytics simultaneously.  When Universal Analytics was available, we would go into Tag Manager and enter the UA property ID into the tag container configuration. Back on Site Kit, we would set up Tag Manager, and there would be an option to set up Analytics with Tag Manager. 

This does not seem to be functioning for GA4.   I tried using a GA event with the measurement ID and a Google tag. 

## Steps to reproduce

1. Create Ga4 property on Google Analytics. 
2. Copy the measurement ID and/or Google Tag
3. Go to Tag Manager and create an account for the URL of your test site. 
4. Create a tag and select Google Analytics GA4 Event (or Google Tag) 
5. Paste in the measurement ID for the GA4 property. 
6. Make sure all items in the tag are set up as normal. 
7. Save and Submit the container tag 
8. Go to your test site and Set up Site Kit without Analytics. 
9. Set up Tag Manager and observe that the `Continue to Analytics setup` link does not appear.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by bethanylang** [comment] 2023-12-11 15:42
@wpdarren Closing this as a duplicate of #7335, which may also be closed; we'll be addressing this as part of the Singular Analytics Module epic and I'm checking with @nfmohit on the best way to handle these issues.

**Closed by bethanylang** 2023-12-11 15:42 UTC
Labels: Type: Bug, Module: Analytics, Module: Tag Manager
