### ISSUE TITLE
Show visits by post in WordPress

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1870] opened 2020-08-04 11:11 UTC
## Feature Description

When viewing all posts from within a WordPress admin dashboard display the total number of visits once the Analytics module is connected via Site Kit.

More on this feature request can be viewed in the below WordPress support topic:
https://wordpress.org/support/topic/show-visits-by-post-in-wordpress/

![image](https://user-images.githubusercontent.com/41326532/89287092-377c3680-d64b-11ea-94ad-0463b1895c3b.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by Antera** [comment] 2020-08-10 05:52
Great idea, can't wait to have this feature

**Comment by felixarntz** [comment] 2021-04-19 20:57
This is somewhat of a duplicate of #296, which we are planning to review in the near future.

**Closed by felixarntz** 2021-04-19 20:57 UTC
Labels: Type: Feature, duplicate
