### ISSUE TITLE
Cannot read properties of undefined (reading 'isAdSenseLinked')

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4767] opened 2022-02-02 06:00 UTC
## Bug Description

One [user in the support forums](https://wordpress.org/support/topic/%D8%B1%D8%B3%D8%A7%D9%84%D8%A9-%D8%AE%D8%B7%D8%A3/) reported the following error:

```
Cannot read properties of undefined (reading 'isAdSenseLinked')

    in ModuleTopEarningPagesWidget
    in WhenAnalyticsActive(ModuleTopEarningPagesWidget)
    in WidgetRenderer
    in div
    in Cell
    in WidgetCellWrapper
    in div
    in Row
    in div
    in div
    in ForwardRef
    in WidgetAreaRenderer
    in div
    in WidgetContextRenderer
    in ModuleApp
    in GoogleSitekitModule
    in RestoreSnapshots
    in ErrorHandler
    in Root
```

This was the sole occurrence and unfortunately we don't have more insights other than the above. 

While we don't have the users site heath information from checking their site it looks like they have Advanced Ads active, along with WC Font end manager, elementor and Google Analytics for WordPress. I also noticed they have the AdSense snippet from Site Kit placed twice, also something we haven't came across previously:

![image](https://user-images.githubusercontent.com/41326532/152100598-29bd6eb4-dbe1-490e-9207-6f2367c9d94e.png)

## Steps to reproduce

Unable to reproduce, with no further insights provided. 

## Additional Notes
- SK 1.48.1
- Unknown if issue remains or where this appears
- No response from impacted user

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* No errors should be raised due to destructuring a potentially `undefined` value due to a problem with `useSelect`:
    * `useSelect` calls that include multiple `select` usages to return an object with multiple values should be split into individual calls to `useSelect`, unless that's not possible in a straightforward manner (e.g. if there is logic relating to multiple `select` usages in there).
    * All `useSelect` calls where the result is then destructured (i.e. expects an object), should be rewritten to include a `|| {}`, to avoid a JS error in case the return value is `undefined`.

## Implementation Brief

* Find all the instances of `useSelect` calls where the returned value is being destructured. ie. by searching for `} = useSelect`.
* The `getDateRangeDates` can be safely destructured and should be kept as is. 
* In `assets/js/components/notifications/WPVersionBumpNotification.js`
    * Instead of destructuring `version` from the `getWPVersion` selector, make sure the selector is not `undefined` and return the `version` directly, otherwise return `undefined`.
* Do the same in the following files for the mentioned selectors. 
    * `getModule`
        * `assets/js/components/ViewOnlyMenu/Service.js`
        * `assets/js/modules/idea-hub/components/dashboard/DashboardCTA.js`
        * `assets/js/modules/idea-hub/components/setup/SetupForm.js`

### Test Coverage

* No tests should be failing. 

## QA Brief

- Note: The changes implemented don't include any feature/UI changes.
- Set up Sit Kit and all the modules and ensure no regressions.
- Connect and disconnect the modules and ensure no regressions.
- If possible, ensure the JS error `Cannot read properties of undefined` is not reproducible.
- Areas to focus:
   * Splash screen
   * Analytics, Adsense, Tag Manager setup and settings screens
   * View only menu dropdown

## Changelog entry

* Update certain selector usage to avoid crashing the dashboard in the event of an error.

**Comment by jamesozzie** [comment] 2022-02-02 12:31
Just noting that this occurred around the same time as another one off report, #4768.

**Comment by felixarntz** [comment] 2022-02-02 22:43
@aaemnnosttv @tofumatt @eugene-manuilov Any idea why this might be happening? When looking at the `ModuleTopEarningPagesWidget` implementation, I'm not sure how `isAdSenseLinked` could possibly come from an `undefined` 🤔 

Do you see any circumstance where we need to adjust this code to be more defensive, or could it simply be that the datastore is not loaded (for some reason, we've had that before)?

**Comment by aaemnnosttv** [comment] 2022-02-03 08:17
@felixarntz I believe this happens in the destructuring of the return from the `useSelect` ([here](https://github.com/google/site-kit-wp/blob/680b90fee1de464b075391b724c9ea425cd282e4/assets/js/modules/adsense/components/module/ModuleTopEarningPagesWidget/index.js#L47)), not the actual `getAdsenseLinked` selector as this would return `null` if the store didn't exist and errors would be raised much earlier if wp data wasn't available. I'm not sure exactly what may have been the cause here but I was able to reproduce this by raising an error in the `useSelect` function – I don't think it could happen any other way.

![image](https://user-images.githubusercontent.com/1621608/152303284-5efb2e6e-a55c-413c-9274-0835e8c4be27.png)

Due to the way `useSelect` works, the original error that results in the `undefined` result from `useSelect` is never shown in the console. Looking at [the source](https://github.com/WordPress/gutenberg/blob/3e867dd7c6560e4b2cb9a59cc02856e055be6142/packages/data/src/components/use-select/index.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L92-L110), it looks like the usual `An error occurred while running 'mapSelect'` with the original error isn't rethrown if the `mapSelect` throws on the first invocation because the `latestMapOutputError.current` wouldn't be set yet 🤔  

Unfortunately we probably wouldn't be able to pinpoint the exact point of failure even if we could see the full console output. The good news is that newer versions of this component have multiple `useSelect`s as is our convention so it should be easier to track down if it were to happen again.

https://github.com/google/site-kit-wp/blob/1.50.0/assets/js/modules/adsense/components/module/ModuleTopEarningPagesWidget/index.js#L47

**Comment by aaemnnosttv** [comment] 2022-02-03 15:31
@felixarntz what I meant was that the component has changed since 1.48.1 to use multiple `useSelect` hooks rather than [one that returns the larger object](https://github.com/google/site-kit-wp/blob/680b90fee1de464b075391b724c9ea425cd282e4/assets/js/modules/adsense/components/module/ModuleTopEarningPagesWidget/index.js#L47) which is destructured. While it still uses destructuring for that value in 1.50.0, it's more isolated as to what could cause that.

**Comment by felixarntz** [comment] 2022-02-03 17:37
@aaemnnosttv Ah okay, that makes sense. I'm wondering whether there's a way for us to update our code holistically so that we don't destructure in such an error case 🤔

**Comment by aaemnnosttv** [comment] 2022-02-03 17:42
@felixarntz the easiest change would be to always have `useSelect() || {}` which would result in `undefined` values for every item destructured. It's better to not return an object from `useSelect` though whenever possible. Ideally `useSelect` would do a better job of reporting errors here too. Maybe newer versions of wp data don't have this problem? 🤔

**Comment by felixarntz** [comment] 2022-02-03 18:22
@aaemnnosttv Added ACs - what do you think?

**Comment by aaemnnosttv** [comment] 2022-02-21 11:44
SGTM 👍

**Comment by FlicHollis** [comment] 2022-09-01 14:21
Hey @kuasha420 Same with this one - Has this IB been started? If not, feel free to unassign yourself so that any of the team can pick it up. Thanks so much!

**Comment by kuasha420** [comment] 2022-10-10 14:30
# IB Update: 

This issue has been in the Triage/AC and IB for quite a bit. When I initially started on the IB, there was a few instances of the violations in the codebase. However, when I checked again this weekend, I realized that we have already fixed all the combined `useSelect` calls and destructuring as part of other issues. If someone else can confirm this, we may be able to go ahead and close this as complete without requiring further work. 

cc @eugene-manuilov @aaemnnosttv @felixarntz

**Comment by aaemnnosttv** [comment] 2022-10-10 20:25
@kuasha420 from what I can see there seems to be some instances left where this would still be applicable (e.g. https://github.com/google/site-kit-wp/blob/c917262802f0da1e598a466b4f57908b55850819/assets/js/components/setup/SetupUsingProxyWithSignIn.js#L98) – you can find them by looking for `} = useSelect`. I think there is some nuance around this too as some selectors should be safe to destructure, e.g. date range dates.

Anything that is destructuring a value from a selector that is fulfilled by a resolver should have a fallback (or just not destructure). E.g. https://github.com/google/site-kit-wp/blob/c917262802f0da1e598a466b4f57908b55850819/assets/js/modules/idea-hub/components/setup/SetupForm.js#L37-L39 here we should just be selecting the description within the function rather than destructuring because the module could be undefined initially. This may not be possible in actual use but is technically based on how the datastore works.

**Comment by aaemnnosttv** [comment] 2022-10-17 18:14
IB ✅

**Comment by wpdarren** [comment] 2022-12-08 09:23
### QA Update: ✅ 

**Note:** I am unable to recreate the issue in the ticket but have completed QA based on QAB.

**Verified:**

- Set up Sit Kit and all the modules and no regressions found.
- Connected and disconnected the modules and no regressions found.
- Also focused tests on Splash screen, Analytics, Adsense, Tag Manager setup and settings screens
- Tested View only menu dropdown with Dashboard Sharing enabled.

**Closed** 2022-12-15 18:20 UTC
Labels: Type: Bug, Type: Support, P2, Module: Analytics, Module: AdSense, Rollover
