### ISSUE TITLE
Woo Empty Cart Error Message

### ISSUE THREAD

**Issue by ramonolivencia** [google/site-kit-wp#282] opened 2019-07-15 21:06 UTC
## Bug Description

 I was constantly getting an error message at checkout on my site ("Your cart is empty") while using WooCommerce, particularly on the mobile version, even after adding some products to the shopping cart.

## Steps to reproduce

Problem solved by GoDaddy, with this message received by email: "Deactivated ´Site Kit by Google´ in order to deactivate "Google Tag Manager" and it seems it resolved the issue."
## Additional Context

 - PHP Version: 7.2
 - OS: [e.g. iOS] 10.14.5
 - Browser [e.g. chrome, safari] Chrome,
![Woo - Error 2019-07 Cart Empty](https://user-images.githubusercontent.com/15330078/61249106-c5416700-a754-11e9-9c7c-a3883b5c0ab7.jpg)
 Safari
 - Plugin Version [e.g. 22] Version 1.0.0-beta.1.0.1
 - Device: [e.g. iPhone6] iPhone X

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment] 2019-07-16 13:55
@ramonolivencia Thanks for reporting, and great that you found a fix. It would be interesting to look further into this issue, if you already have Google Tag Manager container code on your website Site Kit should have given you an option to use that container ID. 

Can you try and add Site Kit again, including the Tag Manager module, selecting your existing container ID in the "Container" dropdown (if you have an existing container setup). If the same issue arises can you send any console errors you see?

**Comment by ramonolivencia** [comment] 2019-07-16 20:57
Before doing as you suggest, here is the email I received from GoDaddy:

"The cause of this issue is "Google Tag Manager", but it's being loaded by "Site Kit by Google" plugin, so that's why I [the GoDaddy technician) disabled the plugin.

On the following WordPress support topic, you can see that there were other people who had the same issue with Google Tag Manager: https://wordpress.org/support/topic/cart-is-empty-5/ <https://wordpress.org/support/topic/cart-is-empty-5/>"


On 16Jul//2019, at 3:55 PM, James G <notifications@github.com> wrote:

@ramonolivencia <https://github.com/ramonolivencia> Thanks for reporting, and great that you found a fix. It would be interesting to look further into this issue, if you already have Google Tag Manager container code on your website Site Kit should have given you an option to use that container ID.

Can you try and add Site Kit again, including the Tag Manager module, selecting your existing container ID in the "Container" dropdown (if you have an existing container setup). If the same issue arises can you send any console errors you see?

**Comment by jamesozzie** [comment] 2019-08-02 15:04
@ramonolivencia There is a similar issue outlined [here](https://ie.godaddy.com/community/Managed-WordPress-Hosting/EMPTY-CART-30sec-cache-issue-on-Cart/td-p/128490) on the GoDaddy support forums. As the issue is not specific to Site Kit and more Tag Manager in general I will close this issue

**Closed by jamesozzie** 2019-08-02 15:04 UTC
Labels: Type: Support
