### ISSUE TITLE
Dashboard notices not appearing on the Site Kit dashboard header, yet appearing elsewhere on wp-admin

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#4998] opened 2022-03-29 18:09 UTC
## Bug Description

Not all toolbar notices are appearing within the Site Kit dashboards, yet they are elsewhere. 

_**Example below of a non Site Kit admin tab** - the notice appears:_

![image](https://user-images.githubusercontent.com/41326532/160675714-96b2f9d9-9f85-4612-ad7c-80f04f7e6c4f.png)

_**Example below of a Site Kit admin tab** - the error doesn't appear. There is a console error that appears relating to the head error that should appear._ 

![image](https://user-images.githubusercontent.com/41326532/160676804-c9b483aa-0bc3-44be-8ea9-c5ab47463a61.png)

Video below of experience below

https://user-images.githubusercontent.com/41326532/160675609-77498c54-1152-489c-b80d-31b0e9b75eca.mp4

## Steps to reproduce

1. Set up Site Kit
2. Open a new tab and navigate to the Site Kit dashboard
3. Click on your user profile icon in the header and select "Manage Sites" from the dropdown
4. Click the button to "Remove access" for the site you are using
5. Close the browser tab - do not click "Back" to go back to your site as this will trigger a disconnect
6. Wait 1 hour for the cached content to expire
7. Revisit your Site Kit dashboard

## Additional Context

- Site Kit 1.70.0
- This is occurring on a site which has the Unified Dashboard feature enabled. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should display the proper auth error on its dashboard when an authentication error is present such as when a new token is unable to be received due to missing delegation consent

## Implementation Brief

* Update a reference to `credentials` to be via Authentication rather than as a member property (this is currently raising a fatal which is returning a different error rather than the expected auth error which is why it isn't showing up as expected)
* Merge #5024

### Test Coverage

* Extend coverage for `Module::exception_to_error` to include a case for handling a `Google_Proxy_Code_Exception` 

## QA Brief

* Follow steps for reproducing the issue
* See banner notification and report error in widgets as shown above rather than "invalid JSON error"

## Changelog entry

* Ensure WordPress dashboard notices appear in Site Kit.

**Comment by jamesozzie** [comment] 2022-03-29 18:10
Keeping this self assigned while I recreate on other sites, confirming this does occur consistantly.

**Comment by jamesozzie** [comment] 2022-03-29 20:46
I was able to recreate this on another site also. This time I used alternative steps to recreate:
1. Setup Site Kit
2. Create a separate WP administrator (admin2)
3. Login as admin2 from a separate browser session and setup the plugin. Use the same Google account as admin1 during connection
4. Disconnect from your Google account with the admin2 account
5. Back on the other browser session where admin1 is logged in await 1 hour for dashboard response caches to expire
6. Refresh the page
7. The dashboard error appears only on non Site Kit tabs. Within the Site Kit tabs the error only appears within the widgets
8. 
https://recordit.co/vpotV6PKU2

**Comment by aaemnnosttv** [comment] 2022-04-01 18:50
Thanks @jamesozzie – I confirmed this earlier and put together a fix that should go out in the next release 👍

**Comment by tofumatt** [comment] 2022-04-04 12:57
IB ✅ 

I'll review and test as well 👍🏻

**Comment by wpdarren** [comment] 2022-04-06 12:57
### QA Update:  :x

@aaemnnosttv a few observations:

1. On the main dashboard, the `Top content over the last X days` widget,  the message does not load and the loading animation continuously appears. All the other widgets have the error as expected.

![image](https://user-images.githubusercontent.com/73545194/161979544-845930df-9f71-433a-adbd-e16c0d308104.png)

2. On the entity dashboard, the `Overall page metrics over the last X days` widget, the message does not load and the loading animation continuously appears.  All the other widgets have the error as expected.
3. 
![image](https://user-images.githubusercontent.com/73545194/161978253-f9299a97-7d7e-4947-b29b-5118e33c3280.png)

A 401 Error appears in the console but I could not see anything specific to these widgets.  

**Verified:**

This is what I see after following the instructions in the ticket. 

Unified Dashboard:
![image](https://user-images.githubusercontent.com/73545194/161977202-282a7f4e-583a-4205-8cb9-2b8631e8f40a.png)

WordPress dashboard.
![image](https://user-images.githubusercontent.com/73545194/161977352-d10156a0-0d27-46a0-a7c6-bb4079024593.png)

**Comment by aaemnnosttv** [comment] 2022-04-06 16:33
@wpdarren this looks correct to me. The important difference here is the error shown in the component, as shown above – it mentions an error on the Google service and includes the link to "redo the plugin setup". Before this change, it was a generic critical error from WP as shown in the description because something was broken internally.

Your observation about the loading state is a valid, but this is what will be fixed in https://github.com/google/site-kit-wp/issues/4542

So I agree it doesn't look entirely right yet, but for the purpose of this issue, everything looks as expected so far unless there's anything else?

**Comment by wpdarren** [comment] 2022-04-06 16:46
### QA Update: ✅ 

@aaemnnosttv thanks for the clarification. 

**Verified:**

- Can see that the banner notification and report error in widgets appears rather than `invalid JSON error`

![image](https://user-images.githubusercontent.com/73545194/162025654-fca0e481-c42f-4a8e-82f9-6dd6304a2799.png)
![image](https://user-images.githubusercontent.com/73545194/162025687-51512fa7-839b-415e-89cd-fa328e8f6784.png)

**Closed** 2022-04-07 16:46 UTC
Labels: Type: Bug, P0
