### ISSUE TITLE
No Error Message in UI if user does not have permissions to a Tag Manager container

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6305] opened 2022-12-08 15:58 UTC
## Bug Description

Theres a Site Kit API error message when you do not have permission to a particular Google Tag Manager container. The user would go to Site Kit settings and change the container that they do not have access to. This message only appears in the console, and nothing is displayed in the UI for the user. The confirm changes button is disabled so it's confusing for the user. 

It's rare that a user would not have permission but it is possible within the Tag Manager UI to remove access for a user to a container. Once you do this and try and select the account and container, the error message in the screenshot below appears.

![image](https://user-images.githubusercontent.com/73545194/206494701-6ee31da1-a60f-4faa-a56b-314eaace7c8b.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2022-12-16 20:04
Duplicate of #5556

**Closed by aaemnnosttv** 2022-12-16 20:04 UTC
Labels: Type: Enhancement, Module: Tag Manager
