### ISSUE TITLE
Google Site Kit - Wordpress

### ISSUE THREAD

**Issue by lokeshsangtani** [google/site-kit-wp#574] opened 2019-09-23 14:36 UTC
While I am trying to open "Get OAuth Credentials", instead of OAuth Credentials it generates only API key, I did not get the reason.

If anyone know the reason, pl revert!

**Comment by felixarntz** [comment] 2019-09-23 15:01
Thanks for the report @lokeshsangtani. This is a duplicate of #561. We're working on fixing this issue. Until then, please refer to the existing issue.

**Closed by felixarntz** 2019-09-23 15:01 UTC
