### ISSUE TITLE
Reduce vertical spacing for idea panel

### ISSUE THREAD

**Issue by simonchampion** [google/site-kit-wp#3853] opened 2021-08-12 16:09 UTC
## Bug Description

The spacing and vertical space of the idea panel does not make it seem like there's another page of content here (even if the "1-4 of 9" says there is). I think the reason the idea panel looks this way is to have the same height as the "Top Search Queries" panel next to it, but it is still a bit confusing. 

![image](https://user-images.githubusercontent.com/83005909/129164578-34537ec4-9508-47ee-8266-7eaa96b8d4e2.png)

**Asana link**: https://app.asana.com/0/1200491083500938/1200763426754102

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2021-08-16 14:14
@felixarntz I think this is a duplicate of #3843 unless this is just about not requiring the two to be the same height?

**Comment by felixarntz** [comment] 2021-08-16 14:30
@aaemnnosttv Yes I think this is different: This one is about a problem where there was extra white-space below the ideas on mobile, which in that viewport should never happen as there's nothing next to it where we need to match height. #3843 is about altering the number of ideas to be something more fitting.

**Comment by felixarntz** [comment] 2021-08-16 14:36
@aaemnnosttv Actually - I may have been confusing this one, it's actually similar to a mix between #3843 and #3841? We can probably close this as a duplicate.

**Comment by aaemnnosttv** [comment] 2021-08-17 17:37
@felixarntz I think this issue may no longer be relevant as this may have been addressed as part of another issue already. This is using the iOS simulator on the current develop 5c20216de55d97d9d583ad33c82f1e53042c5cb1


https://user-images.githubusercontent.com/1621608/129774005-954cc182-88fd-4bff-9a8b-51547c950a60.mp4

**Comment by eclarke1** [comment] 2021-08-25 09:27
@aaemnnosttv @felixarntz can you please confirm we are ok to close this ticket?

**Comment by aaemnnosttv** [comment] 2021-08-25 12:01
Yes, this is no longer needed as it does not maintain the same height between tabs as on desktop in mobile. 
![image](https://user-images.githubusercontent.com/1621608/130786966-e935ffa6-dc1e-4bea-b90a-3be289b69542.png)

**Closed by aaemnnosttv** 2021-08-25 12:01 UTC
Labels: P0
