### ISSUE TITLE
Last section not at top when activated

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#4490] opened 2021-12-08 10:47 UTC
## Bug Description

As per bug bash ticket: https://app.asana.com/0/1201438453642602/1201479361460039

This is a bit dependent on the height of the area, but the default monetization section is barely centered when scrolled to as it is the last section and there is no extra space at the bottom.

I would suggest we apply a minimum height (~80vh) to the last widget context on the dashboard to allow this to be properly scrolled to (see second screenshot).  Maybe even every context should have this minimum height?

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/c3807990-188c-4869-9e4d-93985a460aa5)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* On the main and entity dashboards, the last visible navigable section (via the dashboard navigation chips) should have a minimum height that allows the area to be properly located at the top of the visible area when the user activates the scroll/jump navigation for it, regardless of the height of its content

## Implementation Brief

In `assets/js/components/DashboardMainApp.js`:
* Find out which widget contexts are active using `isWidgetContextActive` selector from `CORE_WIDGETS`. 
* Calculate `lastWidgetContext` using the order of widgets. ie: 
    * if `isMonetizationActive` is true then the value should be `CONTEXT_MAIN_DASHBOARD_MONETIZATION`
    * If all widget contexts are false, set the value to `null`. 
* Conditionally add `googlesitekit-widget-context--last` class to the `WidgetContextRenderer` that is active. 

In `assets/js/components/DashboardEntityApp.js`:
* Do the same as we did in the previous file, but make sure that-
    * We are using correct context name. ie. `CONTEXT_MAIN_DASHBOARD_MONETIZATION` -> `CONTEXT_ENTITY_DASHBOARD_MONETIZATION`.

In `assets/sass/widgets/_widget-context.scss`: 
* add `&.googlesitekit-widget-context--last` class inside the `.googlesitekit-widget-context` class and add the following rules:
    * `min-height` : `80vh`. 

### Test Coverage

* N/A

## QA Brief

* Enable Unified Dashboard. 
* Make sure Adsense is Enabled.
* Click on the Monetization Navigation Chip.
* Monetization Section should be on top. 
* Disconnect Adsense and dismiss the Adsense CTA. The Monetization Chip should disappear. 
* Click on the Speed Chip. 
* Speed section should now be on top. 
* In both cases, the last Widget Context should have the `min-height` applied. 

## Changelog entry

* N/A

**Comment by kuasha420** [comment] 2021-12-14 02:48
Hello,

I think the AC won't work here. When the monetization section is hidden, we will have a different section at the end so AC will have no effect there. 

I have added IB for the current AC if it's acceptable, but I think we should do one of the following
* Add min height to all the contexts. (CSS Only Solution).
* Add min height to the last `googlesitekit-widget-context` that doesn't have `googlesitekit-hidden` class (JS Based Solution). 

Let me know what you think. 

cc @eugene-manuilov @aaemnnosttv

**Comment by aaemnnosttv** [comment] 2021-12-14 08:51
@kuasha420 I agree that the AC shouldn't be specific to the monetization section, but more generally to the last section as this was found to affect others as well. I've updated the AC accordingly (cc @eugene-manuilov).

I also thought about potentially applying it to all sections like you mentioned which would of course be a more substantial change, but could also be more beneficial from a performance standpoint once we're using `useInViewSelect` for all the widgets. Let's keep it to only the last one for now as changing all of them would be a more substantial change although something worth considering for the future (cc @felixarntz @tofumatt).

I think we should be able to solve this with CSS only (for the most part). We need to add a way to select non-hidden contexts though without relying on `:not()`. Here's what I would suggest: let's add an `aria-hidden` attribute to `.googlesitekit-widget-context` divs (should have probably done this anyways for accessibility 😅 ) with the appropriate value based on its hidden state. Then in CSS, we can simply target the last one like this: `.googlesitekit-widget-context[aria-hidden="false"]:last-of-type { ... }`

Regarding the current IB, `va` is not a valid CSS viewport unit as far as I know. Did you mean `vh`?

**Comment by kuasha420** [comment] 2021-12-14 18:54
@aaemnnosttv I don't think that `last-of-type` works here. I have tried that approach without success. See: https://jsfiddle.net/6zLfq7jo/1/

**Comment by aaemnnosttv** [comment] 2021-12-15 09:18
@kuasha420 ah you're right. I misunderstood the way it works. "type" is essentially element/tag type only, rather than an arbitrary selector. In that case, the simplest approach would be to apply the min-height to all contexts (not sure if we're open to that @felixarntz ?).

For now, let's assume this should still only apply to the last visible widget context as described in the AC and use JS to identify that if necessary (which it seems like it is 😄 ).

**Comment by aaemnnosttv** [comment] 2021-12-16 11:52
IB ✅  👍

**Comment by mohitwp** [comment] 2022-01-07 06:36
Hi @kuasha420 

**Issue 1:** Whenever user visits Site Kit Dashboard page and clicks on the last chip, then user gets navigate to one widget placed before the last widget. It happens only one time after visiting the page, after that if user clicks again on chips then navigation works fine. 
**Issue 2:** After user clicks on monetization chip and navigates to monetization widget. If that time PSI data is loading then once the PSI results will display, then focus will move from monetization to speed widget because of height of the speed widget.
cc @wpdarren 

<Details>

https://user-images.githubusercontent.com/94359491/148502357-72a6183b-237a-4daa-9267-f65fc4da8a7c.mp4


https://user-images.githubusercontent.com/94359491/148502368-acf9ddde-8852-4687-bc32-b3024b9bf00a.mp4

</details>

**Comment by kuasha420** [comment] 2022-01-10 18:01
@mohitwp I can reproduce issue 1 but not sure why it's happening. Maybe @aaemnnosttv can have a look. 

Issue 2 seems out of scope for this one, but we should definitely try to fix it if possible. It would probably be better creating a seperate issue. @jimmymadon  also mentioned something related to it that's affecting another issue.

@aaemnnosttv assigning it to you to decide on my above observations.

**Comment by aaemnnosttv** [comment] 2022-01-11 08:20
> **Issue 1:** Whenever a user visits Site Kit Dashboard page and clicks on the last chip, then the user gets navigate to one widget placed before the last widget. It happens only one time after visiting the page, after that if user clicks again on chips then navigation works fine.

@kuasha420 @mohitwp I don't quite understand the issue here. It sounds very similar to # 2 but I could use some clarification 😄 

> **Issue 2:** After user clicks on monetization chip and navigates to monetization widget. If that time PSI data is loading then once the PSI results will display, then focus will move from monetization to speed widget because of the height of the speed widget.

@kuasha420 # This would be fixed by the approach outlined in #4634, but this is still just a proposal.

**Comment by aaemnnosttv** [comment] 2022-01-11 17:22
After reviewing with @kuasha420, both issues flagged in QA would be fixed by #4634 by changing the way `inView` state is set. The scrolling added in this issue works fine, the problem is related to sections becoming "activated" as they are scrolled past, which moves the target being scrolled to.

IMO this works as intended and working around the loading state shifts is probably out of scope here, but I'll defer to @felixarntz .

**Comment by felixarntz** [comment] 2022-01-12 11:50
@aaemnnosttv @kuasha420 @mohitwp I agree that, while this is not the experience we want, fixing this falls more under #4410.

However, while this comes way too late, I'm just seeing now that this issue has moved forward and I'm not actually sure about it. We had discussed this during the bug bash and didn't think we had come to a conclusion. My concern is the extra whitespace at the bottom which @asvinb had pointed out in https://app.asana.com/0/0/1201479361460039/1201480648448653/f too - I personally find that more weird than the heading not appearing at the top, but that's just my take.

Do we have any reference to other examples of this type of anchor link navigation that shows this pattern? I don't want to argue about whether one or the other is the more acceptable trade-off, but what we had before this issue is the "browser-default", so I think this issue and its ACs are only good to keep if we have a reference on why we decided this or direct input from UX.

**Comment by wpdarren** [comment] 2022-01-13 00:58
### QA Update: ⚠️ 

@felixarntz @aaemnnosttv this ticket is in QA, but from reading the latest comments, it appears there's still some discussion. I spent a little of time looking at this:

1. With AdSense enabled: when I click on the `Monetization` chip, I am taken to the PSI widget as it's loading, rather than AdSense widget. If I wait until PSI widget is loaded then I am taken to the AdSense widget as expected. From reading the comments, it appears that this will be picked up with #4410, which is now in approved, because the issues reported are going to be picked up in another ticket. It's a little confusing, so would like clarification on this. 

2. When you dismiss the Adsense CTA, the `Monetization` Chip does disappear, but when I click on the `Speed` Chip, as PSI widget is loading, I am not taken to the top of the Speed widget, as you can see from my screenshot. If I wait until PSI widget has loaded and I click on Speed chip, I am taken to the correct location. 

![image](https://user-images.githubusercontent.com/73545194/149246587-942221ab-e4c3-4f71-b64f-baff5d2caabb.png)

Could we get some clarification on if this needs fixing, or, if these issues will be fixed in another ticket?

**Comment by aaemnnosttv** [comment] 2022-01-13 08:20
@wpdarren as discussed on our sync yesterday, the remaining quirks here related to scroll position along with #4410 will be addressed in a follow-up issue (particularly #4641). The design around this particular issue may still change as well. So to simplify the QA here slightly, we're mostly concerned now that the scrolling is attempting to reach the correct location (essentially ignoring inaccuracy due to changing loading states), and that the last visible section has a minimum height of ~80%.

**Comment by wpdarren** [comment] 2022-01-13 09:44
### QA Update: ✅ 

- Verified that the monetization chip sends the user to the Monetization Section. 
- Verified that when monetization is dismissed that the user is sent to the PageSpeed widget when Speed chip is clicked.
- Verified that the last visible section has a minimum height of 80% 

![image](https://user-images.githubusercontent.com/73545194/149305740-1bf099bd-a4fc-46af-937c-61d5a01fa7c5.png)

**Closed** 2022-01-14 10:47 UTC
Labels: P0, Type: Enhancement, Rollover
