### ISSUE TITLE
Search Console and Page Speed Insights widgets not appearing on Dashboard Sharing when Analytics is not connected

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#7116] opened 2023-06-01 13:17 UTC
## Bug Description

I have found a bug when `GA4Reporting` is `enabled` but Analytics _is not connected_.  

On Dashboard Sharing view only the Search Console and Page Speed Insight widgets are not appearing. 

A console error also appears: 

`Google Site Kit API Error method:GET datapoint:settings type:modules identifier:analytics error:"Sorry, you are not allowed to do that."`

This appears to be an issue since implementing GA4 Reporting and not a regression for 1.102.0

Note: this appears _not to be an issue_ when the admin user has not shared Analytics, only when the module isn't connected. 

## Steps to reproduce

1. Enable `GA4Reporting` feature flag
2. Setup Site Kit _without_ Analytics. 
3. Share `Search Console` and `PSI` for Dashboard Sharing
4. Create a user role, i.e. `Editor`
5. Login as that user and see that no widgets appear on the view only dashboard, and the error is in the console. 

## Screenshots

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/84806816-fdd6-4da1-b29f-2e6fed719ee2)

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/c7e00fcb-190e-4d17-9492-5b981ed66957)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The shared dashboard should not be empty when GA4 reporting is enabled if Analytics is not connected

## Implementation Brief

- In `assets/js/modules/analytics/datastore/settings.js`:
  - Update the `isGA4DashboardView` selector to avoid attempting to resolve the current Analytics dashboard view until it has been detected that GA4 is connected.
- In `assets/js/googlesitekit/datastore/user/permissions.js`:
  - Update the `getViewableModules` selector so that its response doesn't pick between the Analytics & Analytics 4 and include one of them. It should include both if applicable.
- The above changes have been included in #7117, a PoC PR that aided the exploration for this issue. You can choose to build on top of this PR, or use it as a general direction.
- In `assets/js/googlesitekit/modules/datastore/modules.js`:
  - Update the `getShareableModules` selector:
    - It should no longer check for the Analytics dashboard view and optionally replace Analytics with Analytics 4.
    - A module not being internal should no longer be a requirement for it to be included in the response.
    - Please consider testing this widely to make sure it doesn't affect anything else.
- In `includes/Modules/Analytics.php`:
  - Update the `get_datapoint_definitions` method so that the datapoints that include the `shareable` property should additionally (if `ga4Reporting` is enabled) only return `true` for `shareable` if the `dashboardView` module setting is `universal-analytics` (besides the existing conditions).
- In `includes/Modules/Analytics_4.php`:
  - Update the `get_datapoint_definitions` method so that the datapoints that include the `shareable` property should additionally (if `ga4Reporting` is enabled) only return `true` for `shareable` if the `dashboardView` `Analytics` module setting is `google-analytics-4` (besides the existing conditions).

### Test Coverage

- Update test case(s) for `modules/analytics` `isGA4DashboardView` selector to reflect the applied changes.
- Update test case(s) for `core/permissions` `getViewableModules` selector to reflect the applied changes.
- Update test case(s) for `core/modules` `getShareableModules` selector to reflect the applied changes.
- Update any other failing tests.

## QA Brief

1. Enable `GA4Reporting` feature flag
2. Setup Site Kit _without_ Analytics. 
3. Share `Search Console` and `PSI` for Dashboard Sharing
4. Create a user role, i.e. `Editor`
5. Log in as that user—the dashboard should have Search Console and PSI widgets visible with no console errors.

After the above steps are complete, test the same site _with Analytics_ set up as both an admin and user viewing the shared dashboard with both UA and GA4 dashboard enabled to ensure it still functions without issues/regressions.

## Changelog entry

* Fix broken view-only dashboard when Analytics isn't shared.

**Comment by nfmohit** [comment] 2023-06-01 13:37
### Note to AC Reviewer

I have went ahead and added an IB including a draft PR so that we can move this forward fast.

**Comment by aaemnnosttv** [comment] 2023-06-01 17:20
> * The `isGA4DashboardView` selector in the `analytics` datastore shouldn't attempt to resolve the current Analytics dashboard view until it has been detected that GA4 is connected.

This is more of an implementation detail, that while it does fix the problem, there is a concrete user-facing fix here which could be addressed in other ways. I'll update the AC to reflect this and move the current one down into the IB which is more relevant. Otherwise LGTM!

IB ✅

**Comment by nfmohit** [comment] 2023-06-02 10:39
That is a great spot, thank you for sharing the observation, @aaemnnosttv!

This was introduced as a part of #6862, primarily in an attempt to prevent both Analytics modules from appearing in the view-only menu, however, I think it may have also solved other problems caused by having both modules as viewable under the hood.

We could remove this logic from `getViewableModules ` and implement the logic within the view-only menu on the client side to show only one Analytics module based on the dashboard view, but then we'd also want to be cautious of other potential problems that may appear having both modules returned as viewable modules.

Please feel free to assign it to me if you want me to look deeper into this next week, thanks!

**Comment by aaemnnosttv** [comment] 2023-06-05 18:18
> We could remove this logic from `getViewableModules ` and implement the logic within the view-only menu on the client side to show only one Analytics module based on the dashboard view, but then we'd also want to be cautious of other potential problems that may appear having both modules returned as viewable modules.

@nfmohit yes I had considered that as well. This could also be solved by restricting the "viewable" state to be limited to one module or the other at the capability level such that the existing filtering that happens within that selector would already solve for this. The thing that comes to mind there is that we'd need to make a change to the CTA banner for switching to the GA4 version of the dashboard as I think it would need to refresh the user's permissions, although this banner wouldn't be shown to view only users so maybe that wouldn't even be a problem 🤔 

Sending back your way for revision 👍

**Comment by nfmohit** [comment] 2023-06-07 20:00
> @nfmohit yes I had considered that as well. This could also be solved by restricting the "viewable" state to be limited to one module or the other at the capability level such that the existing filtering that happens within that selector would already solve for this. The thing that comes to mind there is that we'd need to make a change to the CTA banner for switching to the GA4 version of the dashboard as I think it would need to refresh the user's permissions, although this banner wouldn't be shown to view only users so maybe that wouldn't even be a problem 🤔
> 
> Sending back your way for revision 👍

Thank you, @aaemnnosttv. This is back to you for another look, thanks!

**Comment by aaemnnosttv** [comment] 2023-06-09 14:34
@nfmohit I've left a comment or two on the PR (depending on when you last saw it) but we're nearly ready to move forward here. At this point, let's solidify the approach and iterate on the PR afterwards. It's been useful for the review so far but is getting a bit too far into CR during definition 😄 With that said, let's add the missing bits as to what we're planning to do to the IB, but please see my most recent comments as there are some new things to consider. Thanks 👍

**Comment by aaemnnosttv** [comment] 2023-06-13 22:02
@nfmohit I think this would also address the following special case in `getShareableModules` where the dashboard view is used in the same way
https://github.com/google/site-kit-wp/blob/9cddf7c7c7cf153d47c22db694462607198212d1/assets/js/googlesitekit/modules/datastore/modules.js#L1392-L1405

Otherwise I think this should be good. I only see one use of this selector so it should be safe to change without introducing other unexpected changes.

**Comment by nfmohit** [comment] 2023-06-14 08:31
Hi @aaemnnosttv.

I actually gave this a thought as well yesterday, however, if we do remove [this special case](https://github.com/google/site-kit-wp/blob/9cddf7c7c7cf153d47c22db694462607198212d1/assets/js/googlesitekit/modules/datastore/modules.js#L1392-L1401), `Analytics 4` would not be shown in the Dashboard Sharing settings modal, due to the following block:

https://github.com/google/site-kit-wp/blob/9cddf7c7c7cf153d47c22db694462607198212d1/assets/js/googlesitekit/modules/datastore/modules.js#L1403-L1405

This is because `Analytics 4` is specified as an "internal" module.

Let me know what you think. Thank you!

**Comment by aaemnnosttv** [comment] 2023-06-14 16:07
@nfmohit I saw that too when I tried it but I think the `internal` check here was only added for GA4 because there is no other shareable module that would qualify, so I think we can remove that from the condition here. From my quick testing, it seems to work okay. I don't want to introduce too big of a change here though, so let's do it but as a nice to have only if it doesn't require additional substantial changes. I still think it makes sense to do, but it doesn't all need to happen as part of this issue unless it's a small addition.

**Comment by nfmohit** [comment] 2023-06-14 17:22
I just did some wide tests and that does seem to work. I've included in the IB, and also suggested some further tests for reassurance. Back to you for another pass, thanks @aaemnnosttv!

**Comment by aaemnnosttv** [comment] 2023-06-14 18:49
Thanks @nfmohit, regarding the changes to `shareable` based on `dashboardView` – this should only change if `ga4Reporting` is enabled, otherwise there is only 1 dashboard view, regardless of the setting. This is probably only relevant for us who are changing this around all the time and changing features but makes sense to include. I'll tweak this in the IB but otherwise this LGTM! 👍 

IB ✅

**Comment by nfmohit** [comment] 2023-06-14 19:03
Ah, excellent catch, thank you for the update, @aaemnnosttv!

**Comment by mohitwp** [comment] 2023-06-27 11:03
### QA Update ✅ 

- Tested on dev environment.
- Tested when GA4Reporting feature flag is enabled and analytics is not connected.
- Verified that now Search Console ,PSI and AdSense Widgets are showing on 'View Only Dashboard.'
- Verified for editor as well as for Admin for 'View only dashboard'.
- Verified The shared dashboard is not empty when GA4 reporting is enabled if Analytics is not connected.

<details>


https://github.com/google/site-kit-wp/assets/94359491/f586dfa8-5b3f-4b91-b293-294f57031e30

</details>

**Closed** 2023-06-28 16:14 UTC
Labels: Type: Bug, P1, Exp: SP
