### ISSUE TITLE
Update UserDimensionsPieChart to render an empty circle graphic when in "Zero Data" state

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4675] opened 2022-01-19 02:14 UTC
## Feature Description

As mentioned in the [Zero States Design Doc](https://docs.google.com/document/d/1gRBpyGYA0IEE0wVw1cA__lG23xZCmAo68RS8SNGYRto/edit#heading=h.fpcc8syobjwb), the `UserDimensionsPieChart` should render an empty pie chart when Analytic's `hasZeroData()` selector (#4673).

### Populated Design

<img width="458" alt="CleanShot 2022-01-19 at 02 05 49" src="https://user-images.githubusercontent.com/90871/150050109-aebdc7c3-f907-44f0-bfeb-e43b86988d4b.png">

### Proposed Zero State Design

<img width="482" alt="CleanShot 2022-01-19 at 02 07 42" src="https://user-images.githubusercontent.com/90871/150050185-ee288874-c05c-44e5-acb2-7c8f5a8bf9b7.png">

It seems wasteful (and possibly buggy) to render a Google chart for this component. If straightforward, we should render a static, responsive SVG/element that mimics an empty, grey pie chart whenever Analytics is in a "Zero Data state" eg. `select( MODULE_ANALYTICS ).hasZeroData() === true`.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The changes for this issue should only happen when the `zeroDataStates` feature flag is enabled. #4726
* When `select( MODULE_ANALYTICS ).hasZeroData() === true`, `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/UserDimensionsPieChart.js` should render an empty grey Pie Chart. See: https://www.figma.com/file/lPdnmgVoPqOEO82AMle9gH/Zero-State?node-id=435%3A2481
* It could be worth, briefly, exploring using Google Charts to render this pie chart programatically with no report data to show, but I suspect it might cause an error. Otherwise, this should be rendered using a component rendering an SVG/element (eg. a responsive representation of the empty pie chart, like in the Figma mockup).
* Other parts of this component's redesign will be handled in another issue; this is specific to the Pie Chart rendering empty data.

## Implementation Brief

* Implement the following only when the `zeroDataStates` feature flag is enabled.
* Export the empty chart icon from Figma and save it as `assets/svg/icons/pie-chart-zero-data.svg`.

Within `assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/UserDimensionsPieChart.js`:

* Import the new `pie-chart-zero-data.svg` icon as `PieChartZeroData`.
* Retrieve `hasZeroData` via  `useSelect` -> `select( MODULE_ANALYTICS ).hasZeroData()`.
* Replace the current unconditional rendering of `GoogleChart` with a conditional render. When `hasZeroData` is true, render the following, otherwise render `GoogleChart` as usual.
```js
<div className="googlesitekit-widget--analyticsAllTraffic__chart-zero-data">
	<PieChartZeroData />
</div>
```

Within `assets/sass/components/dashboard/_googlesitekit-dashboard-charts.scss`:

* Add the class `googlesitekit-widget--analyticsAllTraffic__chart-zero-data` as follows:
```scss
.googlesitekit-widget--analyticsAllTraffic__chart-zero-data {
	align-items: center;
	display: flex;
	justify-content: center;
	min-height: 368px;

	> svg {
		height: 300px;
		width: 300px;
	}
}
```

### Test Coverage

* Add a new **Zero Data (zeroDataStates enabled)** variants to the **All Traffic Widget** stories in `stories/module-analytics-components.stories.js`.

## QA Brief

Note: The empty chart is displayed using the colour #CCC, making use of the current palette.

* Connect Analytics using an account with zero data.
* Enable the `zeroDataStates` feature flag.
* Navigate to the Dashboard.
* Verify the empty chart is displayed as per the AC.
* Navigate to the Entity Dashboard.
* Verify the empty chart is displayed as per the AC.
* Verify the two new *Zero Data (zeroDataStates enabled)* [Storybook](https://google.github.io/site-kit-wp/storybook/develop/) stories display correctly:
![image](https://user-images.githubusercontent.com/18395600/157665048-83808284-d4fc-430f-822d-df44a14aa7d8.png)

## Changelog entry

* Improve the zero state design in the All Traffic Widget.

**Comment by eugene-manuilov** [comment] 2022-01-26 13:11
IB :heavy_check_mark:

**Comment by techanvil** [comment] 2022-03-04 11:13
Hi @tofumatt, having picked this up to implement, it looks like we've overlooked something.

This ticket is about updating `UserDimensionsPieChart` to render the empty chart when Analytics `hasZeroData`.

However - looking at the component that _renders_ `UserDimensionsPieChart`, which is the `DashboardAllTrafficWidget`, there's already a check for the pie chart report being zero, and if so, a graphic & notice is displayed via the `EmptyPieChart` component:

https://github.com/google/site-kit-wp/blob/c217a9449a065b0fab4057dbca05553868047218/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/index.js#L314-L324

_`EmptyPieChart` graphic & notice:_
![image](https://user-images.githubusercontent.com/18395600/156751685-00bc28f4-daf7-4802-9005-db36f03f02ce.png)

The conditions for the pie chart report being zero and Analytics being in the zero data state seem to be pretty closely intertwined; I can't imagine a likely scenario where the pie chart report is non-zero, yet Analytics is in the zero data state.

Therefore, in order to be able to actually display the empty chart that this ticket describes, we'll have to add another check to the `pieChartReportIsZero` check and only render the `EmptyPieChart` if `pieChartReportIsZero` _and_ the `zeroDataStates` feature is enabled.

That would be a pretty straightforward change. However, I am wondering if the result would actually be desirable. The aim of the [Zero States Design](https://docs.google.com/document/d/1gRBpyGYA0IEE0wVw1cA__lG23xZCmAo68RS8SNGYRto/edit#heading=h.jdw2sacewb2a) is ultimately to improve the UX, getting rid of visually bland and unhelpful aspects of the current design.

I question whether the empty chart, devoid of any messaging, is actually an improvement over a friendly graphic and informative notice?

![image](https://user-images.githubusercontent.com/18395600/156752862-f44583e4-6b92-4aa3-a1e3-3eacb21aacb5.png)

So, I guess my question is - do we simply tweak the condition for showing `EmptyPieChart`, or should we reconsider this ticket entirely?

cc @felixarntz @marrrmarrr

**Comment by felixarntz** [comment] 2022-03-04 18:31
@techanvil The UI with the side kick graphic was intended to be temporary, so you're right in that we shouldn't have both. That side kick graphic variant should basically be replaced with the new "empty pie chart" UI.

**Comment by techanvil** [comment] 2022-03-07 10:19
Cool, thanks for clarifying @felixarntz. In that case, I'll add a condition to not render the `EmptyPieChart` when `zeroDataStates` is enabled for now, until we remove the feature flag.

**Comment by wpdarren** [comment] 2022-03-11 10:14
### QA Update: ⚠️ 

@techanvil Generally this past the QAB, I have a few observations/thoughts.

1. The size of the pie chart is different between my test site (300px x 300px) and what is on the Figma designs (238px x 238px) I have a feeling that this might have always being the case but from UX/UI QA perspective, it's worth mentioning. 

2. After the pie chart is loaded, when you click the location and devices tabs, the legend animation loads again. Not a huge issue at all but found it odd. The figma file does show the legends displayed, but assuming that's wrong. 

https://user-images.githubusercontent.com/73545194/157845949-47456a41-5745-4f60-8bc9-85fe91bdf96f.mp4

3. From a UI/UX perspective I found the grey pie chart not very user friendly. I personally feel that it would be better with the text 'gathering data...' inside the pie chart.  Interested in thoughts on this. 

**Verified:**

- For main dashboard: the empty chart is displayed as per the AC/Figma file. 
- For entity dashboard: the empty chart is displayed as per the AC/Figma file.
- The two new Zero Data (zeroDataStates enabled) on Storybook display correctly.
- Checked with `unifiedDashboard` enabled and disabled.
- Checked on small screen sizes.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/157847494-01e09b70-8bf9-44b6-97d7-3efbc5b7640e.png)
![image](https://user-images.githubusercontent.com/73545194/157847231-5d03bb0a-7f55-4517-b537-5f120a47fa61.png)
![image](https://user-images.githubusercontent.com/73545194/157847622-45c42aa9-84cf-437b-a5ac-90e67ffea2bc.png)
![image](https://user-images.githubusercontent.com/73545194/157847313-06d67997-4500-4c1f-9e20-22b4795dbd7b.png)

</details>

**Comment by techanvil** [comment] 2022-03-11 12:55
Hi @wpdarren, thanks for the observations here.

> 1. The size of the pie chart is different between my test site (300px x 300px) and what is on the Figma designs (238px x 238px) I have a feeling that this might have always being the case but from UX/UI QA perspective, it's worth mentioning.

I can confirm that the pie chart hasn't changed size, and it's simply the case that the dimensions on the Figma design are smaller than the actual implementation. This does relate to the broader topic of Figma mocks and how closely or not they relate to the final product, but should not be an issue for this particular ticket.

> 2. After the pie chart is loaded, when you click the location and devices tabs, the legend animation loads again. Not a huge issue at all but found it odd. The figma file does show the legends displayed, but assuming that's wrong.

The legend was discussed on the standup call on Wedneday, and the outcome of that was the decision to remove it when the chart is in a zero data state, as part of this story - as mentioned on this [comment](https://github.com/google/site-kit-wp/pull/4924#issuecomment-1063259542).

Regarding the loading animation, it's a good point, but I think it's out of scope here and we'll need to figure out the solution in a separate issue. Would you mind creating a new issue about this?

>  atw.mp4 
> 3. From a UI/UX perspective I found the grey pie chart not very user friendly. I personally feel that it would be better with the text 'gathering data...' inside the pie chart.  Interested in thoughts on this.

We were talking about potentially displaying some text below the chart, along the lines of "There is no data to display" or something to reflect the zero data state. This could still be iterated on in future to improve the UX. However,  the specific "gathering data" text you have suggested is actually something that the chart does display in a gathering data, as opposed to zero data state, as described in issue #4699.

**Comment by wpdarren** [comment] 2022-03-11 13:04
### QA Update: ✅ 

**Verified:**

- For main dashboard: the empty chart is displayed as per the AC/Figma file. 
- For entity dashboard: the empty chart is displayed as per the AC/Figma file.
- The two new Zero Data (zeroDataStates enabled) on Storybook display correctly.
- Checked with `unifiedDashboard` enabled and disabled.
- Checked on small screen sizes.

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/157847494-01e09b70-8bf9-44b6-97d7-3efbc5b7640e.png)
![image](https://user-images.githubusercontent.com/73545194/157847231-5d03bb0a-7f55-4517-b537-5f120a47fa61.png)
![image](https://user-images.githubusercontent.com/73545194/157847622-45c42aa9-84cf-437b-a5ac-90e67ffea2bc.png)
![image](https://user-images.githubusercontent.com/73545194/157847313-06d67997-4500-4c1f-9e20-22b4795dbd7b.png)

</details>

**Comment by techanvil** [comment] 2022-03-11 13:07
> @techanvil re. the gathering data, yes, I ended up editing my comment after because I'd realised my mistake smile As for the out of scope point, sure will create a ticket for that. Thanks for looking at this!

No problem! Sorry I didn't spot your edit, and thanks for creating the issue.

**Closed** 2022-03-24 18:12 UTC
Labels: P1, Type: Enhancement
