### ISSUE TITLE
The error component rendered by the `UserCountGraph` of the All Traffic widget overflows its container

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#4495] opened 2021-12-08 11:03 UTC
## Bug Description

As per bug bash ticket: https://app.asana.com/0/1201438453642602/1201476082622565

The error state overflows the widget area when on the entity dashboard page.

![image.png](https://images.zenhubusercontent.com/5e2ad3803c374569231d8cd7/cd5ddd36-9b23-4148-9b3c-5e8366d41e54)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Styles of the left column of the All Traffic widgets are updated to display the error in the user count graph correctly. By "correctly" means that the error element shouldn't overflow the widget layout.

## Implementation Brief

* Using `assets/sass/widgets/_googlesitekit-widget-analyticsAllTraffic.scss`,
	* Set the the following styles for the `.googlesitekit-widget--analyticsAllTraffic__totals .googlesitekit-cta--error`.
		* `height` to `auto`
		* `margin-top` set to `16px` (`$grid-gap-phone`) on small screens and `24px` (`$grid-gap-desktop`) on desktop and up screens.

### Test Coverage

* N/A

## QA Brief

- Go to the Site Kit dashboard
- To simulate the error state, open [`assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/index.js`](https://github.com/google/site-kit-wp/blob/6f37894b54d27361a07f261435dfde59f62a261d/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/index.js#L298) component in the code editor
- Set `error="error"` on [line no. 298](https://github.com/google/site-kit-wp/blob/6f37894b54d27361a07f261435dfde59f62a261d/assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/index.js#L298)
- Refresh the page and verify the error state doesn’t overflow
- Verify the same in small screens as well as on the desktop screens
- Open the developer tools
- Search for `.googlesitekit-cta--error` class
- Small screens should have `margin-top: 16px` set
- Desktop screens should have  `margin-top: 24px` set

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment] 2021-12-09 15:10
This isn't specific to the unified dashboard as it's possible today so I don't think it justifies a P0 or being a part of the epic. 
![image](https://user-images.githubusercontent.com/1621608/145422006-3126df32-4358-49f5-a391-ad4f19a875b6.png)

**Comment by aaemnnosttv** [comment] 2021-12-13 10:01
@asvinb please open another issue for the stylistic enhancement/tweak and let's keep this one to be specific to fixing the more obvious bug for now 👍

**Comment by aaemnnosttv** [comment] 2021-12-13 10:07
IB ✅

**Comment by wpdarren** [comment] 2021-12-13 15:33
### QA Update: ⚠️ 

@aaemnnosttv @eugene-manuilov Help! 😄 I have spent quite a bit of time trying to trigger the error both in looking in the sources within chrome console and also using the react developer tools extension. I jumped on a call with @hussain-t and can see that the issue is fixed on his local site but can't recreate it myself.  Any advice on how we can trigger the error?

**Comment by wpdarren** [comment] 2021-12-13 15:33
### QA Update: ⚠️ 

@aaemnnosttv @eugene-manuilov Help! 😄 I have spent quite a bit of time trying to trigger the error both in looking in the sources within chrome console and also using the react developer tools extension. I jumped on a call with @hussain-t and can see that the issue is fixed on his local site but can't recreate it myself.  Any advice on how we can trigger the error?

**Comment by hussain-t** [comment] 2021-12-13 15:57
@wpdarren as we discussed React dev tools extension doesn’t allow us to edit the props for third-party sites. In other words, it allows only the local sites. So, the best way to test it is in the local environment.

**Comment by wpdarren** [comment] 2021-12-14 04:01
@hussain-t thank you.  I think this is unfortunately, going to have to be a `QA:Eng` ticket unless @eugene-manuilov @aaemnnosttv have any other suggestions.  I've tried with Local by Flywheel and I am unable to edit the component using the react developer tools extension.

**Comment by hussain-t** [comment] 2021-12-14 06:05
@wpdarren It's strange that you were not able to edit it on your local. LMK if we can look into it together :-)

**Comment by aaemnnosttv** [comment] 2021-12-14 09:00
@wpdarren it doesn't require a local install for components to be editable via React Devtools, it only requires a development build which can also be installed via the Tester plugin.

I don't think that you should be trying to edit the file to simulate an error though so maybe you can pair with an engineer to reproduce it or this can be QA'd by an engineer. It's a rather simple stylistic fix so we should be mindful of the effort vs benefit.

**Comment by eugene-manuilov** [comment] 2021-12-14 10:14
@wpdarren you can do the following to test that error:

1. Go to the dashboard page and clear the session storage
    ![image](https://user-images.githubusercontent.com/873049/145978413-91d81b42-b410-4604-89b4-e6444e98c4f8.png)
2. Refresh the page and open the network tab in the dev tools
3. Filter requests by the `report` keyword
    ![image](https://user-images.githubusercontent.com/873049/145978242-612f606f-2844-4516-9ced-dd586ae95385.png)
4. Block the request that has the following payload (usually it goes the first in the requests list)
    ![image](https://user-images.githubusercontent.com/873049/145978555-1909a228-9fbc-4f07-8891-d3d2b3ffe34a.png)
    ![image](https://user-images.githubusercontent.com/873049/145978771-759fa5f1-bd15-4e9b-aca8-efe46eacf570.png)
5. Clear the web session storage once again and refresh the page
6. You should see the error

**Comment by wpdarren** [comment] 2021-12-14 12:53
### QA Update: ✅ 


**Verified:**

- The error state doesn’t overflow with the container/pie chart on desktop and mobile. 
- The `.googlesitekit-cta--error class` is margin-top: 16px for small screen sizes and 24px for desktop. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/146001903-e6b9c43b-4474-4bab-afe8-cdd0676ef51c.png)

![image](https://user-images.githubusercontent.com/73545194/146001931-e996e548-ed0e-4848-874f-4aa860948e52.png)

</details>

**Closed** 2021-12-16 16:44 UTC
Labels: Type: Bug, P1, Good First Issue, Module: Analytics
