### ISSUE TITLE
"Error: Ad Client not found" error and continuous AdSense loading bar in place of "We're getting your site ready for ads" 

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2812] opened 2021-02-16 16:52 UTC
## Bug Description

There have been numerous support topics open this week which all feature an AdSense related error as below:
`connection Error: Ad Client not found.`

This notice appears in the dashboard for users, I suspect when users have non approved AdSense accounts (or they may have been flagged for having multiple accounts)

In addition to the dashboard notice the AdSense module progress bar remains loading if a user us to press the "Continue" button - when this notice re-appears as a console error, see below:

![image](https://user-images.githubusercontent.com/41326532/108195831-44a4d280-7110-11eb-9f1e-6a1617ab47cd.png)

These are new issues which only started occurring in the past 24 hours. Awaiting additional information from end users impacted below:
- [Sitekit Adsense connection Error: Ad Client not found.](https://wordpress.org/support/topic/sitekit-adsense-connection-error-ad-client-not-found/)  
- [Ad client not found](https://wordpress.org/support/topic/ad-client-not-found/) - User provided their [SH info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNjYwgaU4bNKHLypZF8AMRFY8HiW9ECVU2UaFZYlyNgmmhRa2yzDRXWANFoB6tjtws4)
- [Error: Ad client not found.](https://wordpress.org/support/topic/error-ad-client-not-found/)
- [Sitekite Adsense connection Error: Ad Client not found.
](https://wordpress.org/support/topic/error-ad-client-not-found/)
- [site kit error with adsense]( https://wordpress.org/support/topic/site-kit-error-with-adsense/) - [SH Info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNj9rxauIFDDLhJEEdsSlAiU8PKJHpJpUa8y2uDTIS8Hxh7m85infF7obWxeJYYhn1o)

## Steps to reproduce

1. Setup Site Kit on a Google account which is not associated with a an AdSense account
2. Connect the AdSense module
3. An AdSense account won't be found, follow the AdSense account setup procedure by following the steps within Site Kit
4. Issue occurs

## Additional Context

- Occurs with both new and existing AdSense users (one who reported ads working previously, although account may have since been flagged at AdSense level)
- Some sites have the Site Kit placed AdSense code evident in their source code
- From the user who shared their SH info they do have an **approved AdSense account,** awaiting feedback on their site level approval
- [One user reports](https://wordpress.org/support/topic/site-kit-error-with-adsense/) that they **do not have an approved AdSense account** yet. They attempted to fix the issue and reapplied. 
- No ads rendering on any of the sites listed
- One support topic references not being able to manually ad their site (before SK). 
- No redirects are in place for 2 of the sites impacted, with their site non secure and a 404 when accessing their https site
- Awaiting any console errors, no screenshots or videos of this experience so far
- No common console errors on the front page of a users site when checking support side (one user does have a "message: "adsbygoogle.push() error: Only one 'enable_page_level_ads' allowed per page." error although this doesn't impact ads rendering. 

Ideally a user would see a "We're getting your site ready for ads" notice within Site Kit, as impacted users would see when they access their AdSense platform. This was the way it worked previously within Site Kit. 

![image](https://user-images.githubusercontent.com/41326532/108200001-b6334f80-7115-11eb-8407-169df8b21495.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* During AdSense setup / settings, if the `getURLChannels` API request results in an error "Ad Client not found", it should result in the `ACCOUNT_STATUS_PENDING` status to be used.
* In other words, the `determineAccountStatus` function should also support receiving a `urlChannelsError` and if it's the above error, it should return `ACCOUNT_STATUS_PENDING`. This should be handled via a new `urlChannelsErrorToStatus` function, which is also called by `errorToStatus`, so that that particular error message does not actually show to the user as an error.

## Implementation Brief

* Check whether the `existingURLChannels.error` is not empty in the `getURLChannels` resolver and yield `receiveError( existingURLChannels.error, 'getURLChannels', [ accountID, clientID ] )` before returning;
* Select the error for the `getURLChannels` selector in the `SetupMain` component and pass it to the `determineAccountStatus` function;
* Update the `determineAccountStatus` function to check the error for the `getURLChannels` selector and if it is not empty and the message contains `Ad Client not found`, then return `ACCOUNT_STATUS_PENDING`;
* Add a new function `urlChannelsErrorToStatus` next to the `alertsErrorToStatus` function (and use it as an example);
  * This function should return the `ACCOUNT_STATUS_PENDING` if the current error is `Ad Client not found`. Otherwise return `undefined`.
* Update the `errorToStatus` function to call the `urlChannelsErrorToStatus` and return its results if `accountsErrorToStatus` and `alertsErrorToStatus` returned nothing.

### Test Coverage

* Update `determineAccountStatus` tests to test the new selector;
* Update other tests if any is broken due to the aforementioned changes.

### Visual Regression Changes

* N/A

## QA Brief

* Setup Site Kit on a Google account which is not associated with a an AdSense account
* Connect the AdSense module
* An AdSense account won't be found, follow the AdSense account setup procedure by following the steps within Site Kit
* You should see the message "We’re getting your site ready for ads. This usually takes less than a day, but it can sometimes take a bit longer", not the "ad client not found" error message.

## Changelog entry

* Fix AdSense bug where `Ad Client not found` error would be displayed in certain cases where an account is still pending.

**Comment by jamesozzie** [comment] 2021-02-17 10:27
Some interesting insights on [one impacted user](https://wordpress.org/support/topic/site-kit-error-with-adsense/), they don't have an approved AdSense account yet. 

Testing done support side:
- Attempted setup using an account which is approved on AdSense but with **a site which was previously not approved**. Conformed I've addressed the issues before attempting setup ("_I confirm I've fixed the policy violations on x.com_" within AdSense). **Unable to reproduce** ([video](https://recordit.co/xN9Rk99k0G)). 
- Attempted setup on a brand new AdSense account

**Comment by jamesozzie** [comment] 2021-02-17 11:16
@adamsilverstein @felixarntz I've added the reproduction steps for this issue users are encountering if you want to take a look. When a user encounters an "_Ad Client not found_" response should there be a different message output in the dashboard?

**Comment by jamesozzie** [comment] 2021-02-17 11:26
For those impacted please check whether you have an approved AdSense account and site. From testing so far this can occur on an account which is not yet approved, evident from accessing the [AdSense platform](https://adsense.google.com). 
  
![image](https://user-images.githubusercontent.com/41326532/108197907-df061580-7112-11eb-8313-ed1b879f028b.png)

**Comment by adamsilverstein** [comment] 2021-02-17 23:59
Thanks for opening this and adding steps to reproduce @jamesozzie!

**Comment by jamesozzie** [comment] 2021-02-18 12:29
- One user provided their Site Health information which displayed a `adsense_account_status: none`. 
- Another impacted user had an AdSense account previously and it looks like their account has been flagged for multiple AdSense accounts
- Finally one user today encounters the same despite having an `adsense_account_status: approved` status. Awaiting additional info, their site may have be approved or the account may be flagged.

**Comment by jagalca87** [comment] 2021-02-24 16:27
Hi, 
I had the same problem with "Error: Ad client not found". However I confirmed in the checkbox in Adsense that my script code just was copy and then Adsense is show me right now a message "we are reviewing your website". Meanwhile, in Wordpress always is the same status. Is that correct?  Can someone guide me a little if this is correct?
![image](https://user-images.githubusercontent.com/79593902/109031623-2d905280-76c5-11eb-88db-3343dea20a26.png)

**Comment by jamesozzie** [comment] 2021-02-25 17:38
@jagalca87 If your website is in review on the AdSense side we'll have the messaging within Site Kit improved soon, with a fix on the way. Thanks for sharing, be sure to subscribe to this issue for updates.

**Comment by eugene-manuilov** [comment] 2021-03-01 14:50
@felixarntz this is ready for IB review. The IB is slightly different from what is expected in the AC. Let me know if it works for you. As to the `errorToStatus` function changes, I think it won't be needed because that function shows errors with `noAdSenseAccount`, `disapprovedAccount`, and `accountPendingReview` reasons (the error in this ticket has `noFound` reason).

**Comment by epushor** [comment] 2021-03-01 20:04
having the same bug.

**Comment by bethanylang** [comment] 2021-03-01 21:11
Thank you for letting us know, @epushor. We are working on a fix for this issue. Please follow this issue for further updates.

**Comment by felixarntz** [comment] 2021-03-02 18:32
@eugene-manuilov A few comments for the IB:
> Move the `determineAccountStatus` function from the `modules/adsense/util/status.js` file into the `modules/adsense/datastore/accounts.js` file, convert it to be a selector, and rename it to `getAccountStatus`.

Let's not do this kind of refactoring here, as it's unrelated; we can think about doing that, but should be in its own dedicated issues. Having a utility function vs selector is an architectural decision we should discuss separately. For now, let's work with the existing approach.

> As to the `errorToStatus` function changes, I think it won't be needed

This function _does_ need to be modified because it is also used elsewhere, to figure out whether an AdSense store error should be displayed to the user. So the "Ad Client not found" error needs to be covered by that, in order for it to not be displayed (since in that case it should instead show the regular UI for the account status determined, similar to how it is for the other "special" errors used for that).

**Comment by eugene-manuilov** [comment] 2021-03-03 11:34
@felixarntz ok, updated. Ready for review.

**Comment by felixarntz** [comment] 2021-03-03 17:00
IB ✅

**Comment by wpdarren** [comment] 2021-03-11 10:39
### QA Update: Fail ❌ 

@eugene-manuilov I am still seeing the error message (with the master zip file that Evan has provided due to Github issues) 

![image](https://user-images.githubusercontent.com/73545194/110773535-cf07ce80-8297-11eb-8623-151a77f687ea.png)

Here are the actions I took:

1. I created a new Google account that had no Adsense account set up. 
2. I have a live website that currently has Site Kit activated, so I disconnected Site Kit, and reset.
3. Set up Site Kit, with the new Google account.  Everything worked fine. 
4. Set up Google Adsense. This screen initially appeared confirming I do not have an Adsense account. - [Screenshot](https://user-images.githubusercontent.com/73545194/110773799-18581e00-8298-11eb-97ed-6e33a2ccd0dd.png)
5. I then followed the on-screen instructions to create my Adsense account. 
6. A new window opened with Google Adsense dashboard to add payment info.
7. I went back to the tab with my website and this message appeared `Error: Ad client not found.` 

I do not see the message `We’re getting your site ready for ads. This usually takes less than a day, but it can sometimes take a bit longer`

**Comment by wpdarren** [comment] 2021-03-11 11:09
### QA Update: Fail ❌ 

@eugene-manuilov the error message no longer appears but I wanted to share this observation. 

Two different messages appear on the screen as you can see from the screencast. 

When you have created your Adsense account. One message appears and then a few seconds later another message appears.  Also, on the final message, it's slightly different that what is highlighted in the QAB. 

Here is the message I see:

`Site Kit has placed AdSense code on every page across your site. After you’ve finished setting up your account, we’ll let you know when your site is ready to show ads. This usually takes less than a day, but it can sometimes take a bit longer.`

In the QAB it states:

` We’re getting your site ready for ads. This usually takes less than a day, but it can sometimes take a bit longer`

https://user-images.githubusercontent.com/73545194/110778008-c06fe600-829c-11eb-8168-c43e9fdda78d.mov

**Comment by eugene-manuilov** [comment] 2021-03-11 13:32
I think this effect happens because we load URL channels information slightly later than showing the setup form and we don't know yet whether getURLChannels returns an error or not. Maybe we should wait for the response from the getURLChannels selector before showing the setup form? @felixarntz what do you think? :thinking:

**Comment by felixarntz** [comment] 2021-03-11 16:53
@eugene-manuilov
> Maybe we should wait for the response from the getURLChannels selector before showing the setup form?

Yes, that makes sense. For simplicity, let's do that via `determineAccountStatus`, the same way it is done for the other requests, to keep the code changes minimal:
* Pass `urlchannels` response to `determineAccountStatus`.
* Move the newly added `urlChannelsError` logic **to the very bottom** of the function, since `urlchannels` are the last thing that need to be checked (e.g. the `determineClientID` check right before is needed to be successful before the `urlchannels` response is even relevant). Having it at the top of the function is also a partial cause of the problem.
* Change that clause to be similar to the other ones above, i.e. check if `urlchannels` is `undefined`, and if so, return the `urlChannelsErrorToStatus( urlChannelsError )` result.

This ensures the account status remains `undefined` until that data is loaded, which is already catered for throughout the UI, which will keep the loading bar active. Can you open a PR for this?

@wpdarren 
> Here is the message I see:
>
> `Site Kit has placed AdSense code on every page across your site. After you’ve finished setting up your account, we’ll let you know when your site is ready to show ads. This usually takes less than a day, but it can sometimes take a bit longer.`
>
> In the QAB it states:
>
> `We’re getting your site ready for ads. This usually takes less than a day, but it can sometimes take a bit longer`

The QAB is off here. The message you're seeing is correct for the AdSense setup flow. The message in the QAB is only used in AdSense settings for the same status.

**Comment by wpdarren** [comment] 2021-03-12 10:43
### QA Update:  Pass ✅ 

Verified:

- The `Error: Ad client not found.` error message does not appear. 
- When the Adsense account was created and you go back to Site Kit, the message appears `Site Kit has placed AdSense code on every page across your site. After you’ve finished setting up your account, we’ll let you know when your site is ready to show ads. This usually takes less than a day, but it can sometimes take a bit longer.`

**Comment by aaemnnosttv** [comment] 2021-03-12 12:32
⚠️ @felixarntz your PR #2953 for this issue was merged to `develop` rather than `master` to be included in the release.

**Comment by felixarntz** [comment] 2021-03-15 14:40
@aaemnnosttv Done!

**Closed** 2021-03-15 17:31 UTC
Labels: Module: AdSense, P0, Type: Bug
