### ISSUE TITLE
Combine "Report Error Actions" into single component.

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#6515] opened 2023-02-01 18:04 UTC
## Feature Description

We currently have two very similar links to report JS errors in the WordPress support forums for Site Kit, one says "Report this error" (`GoogleChartErrorHandler`) and the other "Report this problem" (`ErrorHandler`). They're otherwise exactly the same, and it makes sense to combine them with the `Copy error contents` button into a single `ReportErrorActions` component.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Copy error contents" button and the "Report this error" components here (https://github.com/google/site-kit-wp/blob/3265d05b540c0e320b2b5323b0f1462b14c3f6aa/assets/js/components/GoogleChartErrorHandler/index.js#L93-L106) should be combined into a single component named `ReportErrorActions` and used in both `ErrorHandler` and `GoogleChartErrorHandler`.
* The text used should be "Report this problem", as it's a bit more friendly and less precise than "error", which I think is appropriate for our catch-all handler.

## Implementation Brief
* Create `assets/js/components/ReportErrorActions.js` which exports the `ReportErrorActions` functional component.
* It accepts the following props:
    * `message`
    * `componentStack`
* It should copy most of the markup from `assets/js/components/ErrorHandler/index.js`, i.e `.googlesitekit-error-handler__error-actions` wrapper with the following changes:
    * the `message` and `componentStack` props for `ReportErrorButton` should take the values of the `message` and `componentStack` prop respectively.
    * class name should be updated to `.googlesitekit-report-error-actions`
* The text used in the `Link` component should be as per the AC.
* Styles for `.googlesitekit-report-error-actions` should live in `assets/sass/components/global/_googlesitekit-report-error-actions.scss` and should be similar to `.googlesitekit-error-handler__error-actions`.
* Update `assets/js/components/GoogleChartErrorHandler/index.js` and `assets/js/components/ErrorHandler/index.js` to use the new `ReportErrorActions` component.
* Delete `assets/sass/components/global/_googlesitekit-googlechart-error-handler.scss` and remove the styles for `.googlesitekit-error-handler__error-actions` from `assets/sass/components/global/_googlesitekit-error-handler.scss`

### Test Coverage
* No new tests to be added.

#### Testing the Generic `ErrorHandler` and `GoogleChartErrorHandler`

To ensure the proper functioning of both error handlers, you'll need to simulate certain error states. Follow the steps below:

1. **Setting up the simulation**:
   - Navigate to `assets/js/components/GoogleChart/index.js`.
   - Introduce the `ThrowErrorComponent` just above where the `Chart` component is rendered. When doing this, ensure that the `throwErrorOnMount` prop is set to `true`.

2. **Verifying the `GoogleChartErrorHandler`**:
   - After making the change mentioned above, check the Site Kit (SK) dashboard where Google Charts are displayed.
   - Ensure that the error component (indicative of the `GoogleChartErrorHandler`) appears as expected.

3. **Testing the generic `ErrorHandler`**:
   - In the same file, modify either the `chartEvents` or the `data` prop of the `Chart` component to pass an empty array.
   - This should trigger the generic `ErrorHandler`. Verify its proper display and behavior.

4. **Link Text Verification**:
   - In both error states (from the previous two steps), ensure that the link text reads `Report this problem`.

## Changelog entry

* Combine the main and Google Chart error handling components into a single component.

**Comment by tofumatt** [comment] 2023-02-02 23:04
Allowing the "on-click" function to be customised probably isn't needed here, since the behaviour for error reporting (and the accompanying text, including the change in text when the user copies the error) should be consistent.

At minimum we should have a default behaviour, I suppose we could have a function that did extra but I actually think for now it's fine if we just remove the callback.

Also, the IB should include using the styles from https://github.com/google/site-kit-wp/blob/5edc568b6aed809e46c606c6a9b6f2f0aafb72bc/assets/sass/components/global/_googlesitekit-error-handler.scss#L34-L40 and removing the "duplicate" ones for the Google Charts Error handler here: `assets/sass/components/global/_googlesitekit-googlechart-error-handler.scss` (that file can probably just be removed entirely).

**Comment by asvinb** [comment] 2023-02-03 09:36
@tofumatt Turns out the IB was outdated after #6391 has been merged yesterday. I've updated the IB taking that into account. Can you take another look?

**Comment by tofumatt** [comment] 2023-02-03 17:48
Looks good!

IB ✅

**Comment by techanvil** [comment] 2023-08-15 15:01
Hi @hussain-t, code-wise this LGTM and I've merged the PR.

However, please can you provide some more explicit QAB instructions? The updated error handlers are designed for catching and handling exceptions, but I'm not aware of where a failed report would cause an exception to be thrown. :thinking:

**Comment by hussain-t** [comment] 2023-08-16 10:16
Thanks, @techanvil. I've revised the QA Brief. Given that this can't undergo manual testing, I've marked it as QA:Eng.

**Comment by techanvil** [comment] 2023-08-16 10:42
Top stuff, thanks @hussain-t.

**Comment by tofumatt** [comment] 2023-08-17 13:15
### QA ❌ 

I followed the QA Brief here, which I think might be missing a step, because leaving the `<ThrowErrorComponent />` in there with the empty `data={ [] }` prop still triggers the Google Chart error:

<img width="747" alt="CleanShot 2023-08-17 at 14 14 28" src="https://github.com/google/site-kit-wp/assets/90871/2a6040d7-b45d-4900-800b-b22b52a5bd63">

Removing the `<ThrowErrorComponent />` and setting `data={ [] }` as in the QA Brief shows this:

<img width="1029" alt="CleanShot 2023-08-17 at 14 12 13" src="https://github.com/google/site-kit-wp/assets/90871/3fd9db6e-6e4e-479c-abe6-66e60946798c">

**Comment by hussain-t** [comment] 2023-08-17 13:35
@tofumatt, can you pass `null` to the `data` prop and try again? Sometimes the code is broken with an empty array and sometimes with `null`.


https://github.com/google/site-kit-wp/assets/24408261/f1f637ae-87bc-47f4-bc80-5b2ade05d584

**Comment by tofumatt** [comment] 2023-08-17 20:17
@hussain-t Using the latest `develop`, I see this:

<img width="787" alt="CleanShot 2023-08-17 at 21 16 07" src="https://github.com/google/site-kit-wp/assets/90871/faed0014-1584-4201-92c6-70f75c134b93">

After modifying the `Chart` to look like this:

<img width="691" alt="CleanShot 2023-08-17 at 21 16 54" src="https://github.com/google/site-kit-wp/assets/90871/bc3ae9f1-6278-4d82-8f1a-d1eeaa7dd8d1">

I'm not triggering the same errors you see on the Site Kit Dashboard. 🤔

**Comment by hussain-t** [comment] 2023-08-18 09:23
@tofumatt, that's weird. Did you checkout to `main` or any other branch which doesn't have these changes to verify if you see the same behavior? Because there is no reason for this to work differently. We just extracted the code to a new component as part of this issue.

Perhaps you can try rendering the `ThrowErrorComponent` in any other component. For e.g., `SearchFunnelWidgetGA4`.

I tried it, and it works.


https://github.com/google/site-kit-wp/assets/24408261/1cca2886-d085-4a85-b72a-5879d54f7add

**Comment by tofumatt** [comment] 2023-08-22 22:33
@hussain-t Did you mean to include the part in the QA Brief about changing the props passed to `Chart`?

<img width="836" alt="CleanShot 2023-08-22 at 23 32 17" src="https://github.com/google/site-kit-wp/assets/90871/ac0976c6-d56f-4dcf-a8aa-7bb7161c53af">

Because when I do that on `1.106.0` and `develop` I see this:

https://github.com/google/site-kit-wp/assets/90871/2268c069-41d7-444e-8a74-3114007ba838

But in your screencast you're using the `ThrowErrorComponent` someplace else? Is the QA brief here accurate? If so I can't reproduce, can you make a test site or a test case to show this working?

**Comment by hussain-t** [comment] 2023-08-23 05:57
@tofumatt, while the QA Brief specifies modifying the props of the `Chart` component to trigger an error, the goal is not exclusive to that particular component. The primary objective is to simulate a broken code scenario to observe the error state. This is why I've illustrated using `ThrowErrorComponent` within a different component—so you can see how the error state is displayed under such conditions. 

Based on your screencast, the error state isn't visible even in the older code. So, it's not an issue with the new code changes.

@techanvil, would you be able to test this behavior and confirm it?

**Comment by techanvil** [comment] 2023-08-23 09:30
QA :white_check_mark: 

I've run through the QAB, and have confirmed that in my testing the error component is displayed correctly in the two scenarios, with the link text _Report this problem_.

`GoogleChartErrorHandler`:
![image](https://github.com/google/site-kit-wp/assets/18395600/379db38d-da5b-45e4-82a4-82bed0605b37)

`ErrorHandler`:
![image](https://github.com/google/site-kit-wp/assets/18395600/ad23b9ce-79cd-4292-ae61-176cb88a6e75)

In my testing, overriding the chart props with empty arrays briefly shows the "Table has no columns" error, then the page switches to `ErrorHandler`. I'm not sure what's causing the difference in @tofumatt's testing but I don't think we need to dig into it at this point.

**Comment by hussain-t** [comment] 2023-08-23 10:13
Thanks for testing it, @techanvil 🥇

**Closed** 2023-08-28 17:27 UTC
Labels: P2, Type: Enhancement, QA: Eng, Exp: SP
