### ISSUE TITLE
Changed GA4 property and measurement IDs are not showing under Analytics Settings edit mode

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6765] opened 2023-03-23 15:54 UTC
## Bug Description

As part of the new Google Tag ID mismatch banner notification, if the Google Tag within Site Kit's settings now points to a new GA4 Property (new destination / measurement ID), we allow the user to "automatically update" Site Kit's settings to this new GA4 Property. If this new GA4 property was selected from a different GA4 Account, then it will not show up in the list of GA4 properties within Site Kit's Analytics settings.

This is because we fetch GA4 properties connected to the UA account ID - which was not updated when the GA4 property was updated by the Google Tag ID mismatch banner notification.

https://github.com/google/site-kit-wp/blob/a70063a605ee0355c46d9345314e4e070ace3bbe/assets/js/modules/analytics-4/components/common/PropertySelect.js#L61-L71
 

## Steps to reproduce
1. Setup Site Kit and connect a GA4 Property. For easy testing purposes, go to Site Kit settings and click "Edit in Analytics" next to the Google Analytics 4 Property and rename it to say "GA4 Property 1". Also, in Site Kit settings, note the "Measurement ID" of "GA4 Property 1".
2. Go to [Tag Manager admin](https://tagmanager.google.com) and sign in using the same Google Account which has access to the above "GA4 Property 1". On the "Google tags" tab, find the row where one of the Tag IDs is the same as the "Measurement ID" above. The Tag Name would by default be the domain name associated to the GA4 Property. Click on this tag name. On the Tag details pop-up, note down the tag ID beginning with GT (say GT-100000). Delete the destination (GA4 Property 1) from the Destinations list. When asked to attach a tag to the destination, create a new tag. This will make the original GT-100000 tag not linked to any destination.
3. Click the "+ Destination" button to add a new destination. Add another GA4 Property from the list of destinations, say "GA4 Property 2". Ensure this property is part of another Analytics 4 Account. (If there are no destinations in this list, ensure your google account has admin access to another GA4 Property).
4. Now go back to the Site Kit plugin and in the browser console, run the following command which forces the Google Tag settings to "sync".
  ```javascript
  googlesitekit.api.set('modules', 'analytics-4', 'settings', {'googleTagLastSyncedAtMs': 0});
  ```
5. Reload the plugin and there should be a Banner Notification where the Primary CTA should ask you to update the property to GA4 Property 2.
6. Now go to Site Kit settings and try to edit the Analytics settings. The GA4 Property and Web Data Stream fields will be blank.

## Screenshots

[](https://user-images.githubusercontent.com/94359491/226796818-1cedecc4-cc3a-4c2f-997d-47fb2160bcfb.mp4)

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by techanvil** [comment] 2023-03-24 15:51
I'm closing this issue, as the error was raised on https://github.com/google/site-kit-wp/issues/6373#issuecomment-1478881388 and has been fixed in a followup PR to that issue. I'm unable to reproduce the error myself on `develop`, and @mohitwp can QA it again as part of #6373.

**Comment by aaemnnosttv** [comment] 2023-03-28 21:01
Thanks @jimmymadon – that makes sense. It's important to understand that GA accounts are not different between UA and GA4, those differences only start at the property level which is why you can have both UA and GA4 properties in the same account. So there is no such thing as a UA or GA4 account ID, all GA accounts are the same kind, even though they can be interacted with via the UA management API or the newer Admin API.

In this case, it makes sense that a user could have access to a different property under a different account ID than the one that is currently set for the module. One solution here would be to allow GA4 to use a separate GA account but this might not make sense since we won't have two versions of GA for very much longer. Adding an account select for GA4 would be a potential solution, but we've always required the two to use the same GA account.

Another option would be to limit the properties that GA4 can be updated to in the mismatch reconciliation to only those of the same account but it's not clear how the experience should play out here (should it be an error? etc).

Finally, we could have a variant case of the mismatch notification for this scenario but only if UA was connected and the new property belonged to a different GA account. If UA wasn't connected, then changing the account ID would be fine here, but otherwise this would break the population of the UA selects in the same way.

Really the account ID is only used for populating these dropdowns, it doesn't affect tagging or reporting so it seems a bit odd that we'd go out of our way to prevent different values for this for the two modules, but again UA is going away so soon it doesn't make sense to sink much time into.

Thoughts @felixarntz ?

**Comment by felixarntz** [comment] 2023-03-29 00:32
@aaemnnosttv @jimmymadon Hmm, this really seems like a short-term edge-case.

Since we're going to have to migrate the `accountID` setting to the GA4 module in the future anyway (or change the current UA module to become the GA4 module), maybe we should introduce that setting in the GA4 module already? We could set it to the new GA4 property's account ID if that was different from the current main / UA account ID. This will technically mean we use a different account for the UA property than GA4, which may be fine.

The way this could then work for GA4 is:
* If there is a GA4 specific `accountID` set, use that for the dropdowns.
* Otherwise, reuse the `accountID` from the UA / `analytics` module.

**Comment by aaemnnosttv** [comment] 2023-03-29 13:54
> Got too far into GTE and data streams to forget that both UA and GA4 can have the same account! 😄

@jimmymadon Until now, they've always had the same account 😄 

> Since we're going to have to migrate the `accountID` setting to the GA4 module in the future anyway (or change the current UA module to become the GA4 module), maybe we should introduce that setting in the GA4 module already? We could set it to the new GA4 property's account ID if that was different from the current main / UA account ID. This will technically mean we use a different account for the UA property than GA4, which may be fine.

@felixarntz I can see this being potentially problematic if GA4 could be using a property of a different account without showing it. E.g. I can see it being confusing as to what to expect when creating a new property: should the new property be created under the selected account as before or the same account as the property? It seems like potentially a substantial amount of effort to cater for a case that is otherwise only possible via the GTE mismatch correction which is itself also likely an edge case.

I think the only way to solve this while allowing the same mismatch sync to happen is to give GA4 its own account select, even for configurations that use the same for both although I guess we could only expose it if they were different. I feel like we shouldn't support a configuration that you couldn't get to yourself though (as in manually configure things in this way).

Doesn't feel like there is a clear best way to handle this.

**Comment by aaemnnosttv** [comment] 2023-06-26 16:53
After discussing with @marrrmarrr, we've decided to close this as it should be a very uncommon edge case and will no longer be an issue after UA is removed. With GA4 reporting, the account select should always match the GA4 property anyways so this would only affect the display of UA fields.

**Closed by aaemnnosttv** 2023-06-26 16:53 UTC
Labels: Type: Bug, P1, Module: Analytics
