### ISSUE TITLE
Minus figure appearing in AdSense chart when no earnings made

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#6479] opened 2023-01-27 13:56 UTC
## Bug Description

When AdSense is connected and the account and site has been approved.  The AdSense `Performance over the last X days` displays minus figures in the y-axis section of the chart, when no earnings have been made in the period.   

What's unusual is that the issue only occurs on 28 days.  The chart looks fine for 7, 14 days.  I am unsure about 90 days because the site did generate a huge £0.01 within this period. 

![image.png](https://images.zenhubusercontent.com/5f99965247ef5a1da6985d7d/06bcb3b1-1a97-4418-9b17-4512c51a449a)

**Please note:**  I have a site where you can see this in action without the tester plugin, if this helps. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* All charts of the AdSense dashboard widget should have a minimum y-axis of `0` regardless of the amount of data it has

## Implementation Brief

* Update `assets/js/modules/adsense/util/is-zero-report.js`:
  * Beside `report` parameter, include new `selectedStatsIndex` parameter (it is of type number)
  * Change this check https://github.com/google/site-kit-wp/blob/ab9d76bebe8a3368eaf73b194edf941fd42f2ec5/assets/js/modules/adsense/util/is-zero-report.js#L42 curretly it does not take into account the value of the selected tab, but checks against all tabs. The proper check should be `if ( +totals.cells[ selectedStatsIndex ]?.value === 0 )`
* Update `assets/js/modules/adsense/components/module/ModuleOverviewWidget/Stats.js`:
  * Update the usage of `izZeroReport` function https://github.com/google/site-kit-wp/blob/ab9d76bebe8a3368eaf73b194edf941fd42f2ec5/assets/js/modules/adsense/components/module/ModuleOverviewWidget/Stats.js#L137-L138, to include second parameter `selectedStats + 1`

### Test Coverage

* Adjust `assets/js/modules/adsense/util/is-zero-report.test.js` to take into the account second parameter

## QA Brief

* Test the site in the "Bug Description" section above, where the error first occurred. The chart's y-axis should start at 0, not a value below 0.

## Changelog entry

* Fix a bug that could cause the AdSense chart to display earnings values below "0" when no earnings have been made.

**Comment by aaemnnosttv** [comment] 2023-02-16 21:55
Related issues

- https://github.com/google/site-kit-wp/issues/3564
- https://github.com/google/site-kit-wp/issues/4742

**Comment by bethanylang** [comment] 2023-11-27 15:43
@wpdarren Reassigning this to you, can you please see if this is still occurring? TY!

**Comment by wpdarren** [comment] 2023-12-05 11:22
@aaemnnosttv  There's nothing more to share about how to recreate this other than that I set up AdSense, and within 90 days, there is a small amount of money, now $0.05.  No issue occurs on 7 and 14 days, but on 28 days on the `Earnings` and `Page CTR` tabs it displays as per the screenshot.  I also noticed that in 90 days, the same happened on `Page CTR`

I tested this again on the latest release, and the issue still occurs.  

It's possible that it's an edge case. 

Can I give you access to the Search Console AdSense account to test it yourself?

https://github.com/google/site-kit-wp/assets/73545194/bb8231c9-cbe6-4017-8ce1-7159919ebf89

**Comment by nfmohit** [comment] 2023-12-23 20:46
Update: I tried various variations of AdSense reporting simulation using the tester plugin but wasn't able to reproduce this. I also looked into the related similar issues and verified that the fix there is applied in the AdSense chart. It would be helpful to take a look at a site where the error can be seen. @wpdarren (when you're back from the holiday break), could you share access details to the site internally? Thanks!

**Comment by bethanylang** [comment] 2024-01-08 14:33
@wpdarren Reassigned to you to help with the site detail info, thanks!

**Comment by wpdarren** [comment] 2024-01-09 10:28
@bethanylang, apologies. I should have updated this ticket with a comment.  I have already provided @nfmohit with details for the site where this issue can be re-created on 2 January.  I'll assign the ticket to Nahid.

**Comment by nfmohit** [comment] 2024-01-21 09:14
### 💡 Investigation update 💡 

Thank you for sharing access to the account, @wpdarren. I was able to reproduce the issue and I have been able to find the root cause.

For curious minds, here's what I have found so far. In order for the chart's V-axis to start at 0 (non-negative), the `vAxis.viewWindow.min` and `vAxis.viewWindow.max` values need to be defined. While we set `vAxis.viewWindow.min` to `0` in the default configuration:

https://github.com/google/site-kit-wp/blob/1bdb01fb8007d6b39200ab5cd925db583cc64100/assets/js/modules/adsense/components/module/ModuleOverviewWidget/Stats.js#L107-L109

We only set `vAxis.viewWindow.max` to a ceiling of `100` when we have a zero report:

https://github.com/google/site-kit-wp/blob/1bdb01fb8007d6b39200ab5cd925db583cc64100/assets/js/modules/adsense/components/module/ModuleOverviewWidget/Stats.js#L136-L143

However, in the case of this specific site, the previous range data is _not_ zero, it actually has data:
![image](https://github.com/google/site-kit-wp/assets/20284937/41874696-bfb8-49fd-8451-0a1b9bc7fb3b)

Which is why, the `vAxis.viewWindow.max` ceiling is set to `undefined`, causing the V-axis to go negative.

Even though the previous range has some data, it doesn't show up in the chart:

![image](https://github.com/google/site-kit-wp/assets/20284937/0279d013-60ff-4989-bee6-f91877da346f)

I'll continue my investigation to find out why that is the case.

**Comment by eugene-manuilov** [comment] 2024-02-14 15:49
IB ✔️

**Comment by zutigrm** [comment] 2024-02-14 16:10
@eugene-manuilov Added, sorry about that.

**Comment by tofumatt** [comment] 2024-02-23 14:07
Assigning @wpdarren as he has a site to test this behaviour on (and will know which site it is 😄).

**Comment by wpdarren** [comment] 2024-02-27 11:20
### QA Update: ✅ 

- Verified that the chart's y-axis does not show a value below 0.
- Tested this with all data on the Monetization chart for 7, 14, 28 and 90 days. 
- Checked that the above applies also to the view only dashboard. 

https://github.com/google/site-kit-wp/assets/73545194/72be99b2-9522-4a19-a0f2-ea004b0fcc02

**Closed** 2024-03-07 16:17 UTC
Labels: Type: Bug, P2, Module: AdSense
