### ISSUE TITLE
Avoid double-triggering of survey and additional prompts

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3508] opened 2021-06-08 15:56 UTC
## Feature Description

Let's make sure the prompt doesn't show when there's a second prompt on a different part of the dashboard (e.g. in the future this could happen with the UXR study recruitment form).

![image](https://user-images.githubusercontent.com/56588136/121218172-6d490780-c87a-11eb-81b0-15bd67f83293.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When a remote-controlled survey is being displayed, no remote-controlled top notification (i.e. from `core/site/data/notifications`) must be displayed at the same time.
    * In other words, the surveys always take precedence. Furthermore, since the notifications are cached on the client-side, they can still easily be displayed again on next page load.
    * Technically, if a survey is being rendered, it needs to be ensured the site notifications state in the data store is emptied or kept empty to avoid those notifications from appearing.

## Implementation Brief

1. Use some state to determine whether or not a survey is being displayed. `getCurrentSurvey()` (this already exists)
https://github.com/google/site-kit-wp/blob/38a001c4b564a9cf0b5c4fcccaf8f97c187ed00e/assets/js/googlesitekit/datastore/user/surveys.js#L157

2. Make some changes `assets/js/components/legacy-notifications/dashboard-core-site-alerts.js` 
  - Copy the file to `assets/js/components/legacy-notifications/DashboardCoreSiteAlerts.js`
  - Set a timeout to only render content after `5 seconds`, though returning `null` doesn't need to block.
  - Refactor it to a stateless functional component, instead of the call to `getNotifications()` from `assets/js/components/legacy-notifications/site/get-notifications.js`, use the `getNotifications()` selector `window.googlesitekit.data.stores['core/site'].selectors.getNotifications()`.
  - After the five seconds timeout completes, add another call to the `getCurrentSurvey()` in case a remote survey has come in and if it returns a survey, return `null`, otherwise implemenent the remainder of the `return` statement as per the legacy `render` function.

  - Combining the changes from above, we do the following:
  - When the component loads, start the `5s` timer, 
  - If `getCurrentSurvey()` returns a survey, we return null and don't render notifications.
  - If we don't have a survey, we call `getNotifications`, 
  - After the 5s have passed, we once more call `getCurrentSurvey()`, if it returns a survey, we return null, otherwise we return the notifications as per the current `render()` function of the legacy dashboard-core-site-alerts.

3. Remove the `assets/js/components/legacy-notifications/site/get-notifications.js` and `assets/js/components/legacy-notifications/dashboard-core-site-alerts.js` files, any tests for them.

4. Update `components/legacy-notifications/index.js` to call the new Component in `const addCoreSiteNotifications = createAddToFilter( <DashboardCoreSiteAlerts />);`

5. Create storybook component stories for `assets/js/components/notifications/DashboardCoreSiteAlerts.js`

### Test Coverage

Update `tests/e2e/specs/dashboard/notifications.test.js` to cover the following scenarios:
- surveys and notifications to display, the notifications should not display.
- no current survey but one appearing in 3 seconds, the notifications should not display.
- no current survey but one appearing in 6 seconds, the notifications should display.

### Visual Regression Changes

* Add VRT for the storybook stories.

## QA Brief

* Storybook components cover off the scenarios for render / no render of the component depending on presence of surveys, so see https://google.github.io/site-kit-wp/storybook/pull/3603/?path=/story/components-dashboardcoresitealerts--notification-cta-with-survey-longer-delay (when merged the link will be https://google.github.io/site-kit-wp/storybook/develop/?path=/story/components-dashboardcoresitealerts--notification-cta-with-survey-longer-delay )
* You can also reproduce the same scenario by triggering notifications and surveys the same way that the storybook story does in https://github.com/google/site-kit-wp/blob/67ddf556799b060cd8910123bcd0e4579afd0ad8/assets/js/components/legacy-notifications/DashboardCoreSiteAlerts.stories.js#L87-L91

## Changelog entry

* Don't show notifications if a user survey has already been displayed.

**Comment by aaemnnosttv** [comment] 2021-06-14 12:38
> Create some state to show when a survey is being displayed.

@ivankruchkoff for now I think we can simply rely on `getCurrentSurvey` since this is essentially "the current survey to display".

> Use the state to selectively render a notification only when we aren't showing a survey.

The current IB calls for making this change in `assets/js/components/legacy-notifications/notification.js` however we don't need to change individual notifications. Instead, we want to suppress all core/site notifications, which are rendered by `assets/js/components/legacy-notifications/dashboard-core-site-alerts.js`.

As an aside, it would be nice if we updated `DashboardCoreSiteAlerts` to use modern APIs. The component is already very simple but it essentially tries to fetch notifications every time rather than use the datastore. `getNotifications` via the `core/site` store is actually unused right now. We essentially need to update this component to return `null` if there is a current survey and using hooks with selectors would probably be a bit cleaner than the current state with fetch on mount.

There's one more thing we need to consider as well which is avoiding a flicker of the core site notifications (since these may be cached and available to show right away) if a survey is triggered to show, since surveys take precedence. Unfortunately, we can't simply wait on a resolver to show notifications since `getCurrentSurvey` doesn't have one. Instead I think we may need to introduce a delay in showing core site notifications to see if any are triggered on page load. Even if a trigger is hit, we won't know if a survey will actually be shown until that request finishes and then we'd need to check `getCurrentSurvey` again. Given that surveys can be triggered after page load (although not currently) it may not be possible to handle this in all cases so some overlap may be unavoidable if we were to have other event-based survey triggers in the future. cc @felixarntz 

All that to say, maybe we should have a 5 second timeout or something. If no current survey is returned in that time, then notifications should be displayed, regardless if a survey comes up after that since it would be a worse experience to hide notifications again after showing them, even if a survey was also shown. What do you think @felixarntz ?

**Comment by felixarntz** [comment] 2021-06-14 17:22
@aaemnnosttv 
> All that to say, maybe we should have a 5 second timeout or something. If no current survey is returned in that time, then notifications should be displayed, regardless if a survey comes up after that since it would be a worse experience to hide notifications again after showing them, even if a survey was also shown.

Good point, that sounds good to me. We should not remove a notification once it is already displayed, just because a survey started showing up. Let's instead defer the entire call to get the notifications by the 5 seconds you're suggesting, but only if there is no survey by then.

Regarding refactoring `DashboardCoreSiteAlerts`, refactoring this to use the datastore sounds good to me. I completely missed that this part was still using the legacy data API - let's update it as part of this. @ivankruchkoff Can you include that bit in your IB (in addition to the comments by @aaemnnosttv above)? It's okay if this increases the scope/estimate slightly.

**Comment by ivankruchkoff** [comment] 2021-06-15 12:09
My concern with the ```waiting  five seconds before showing notifications``` is that the page can load, I can go about my sitekiting business, scroll down the page and then find that for some reason the content scrolls away from me because a notification was slid into the dom.

**Comment by aaemnnosttv** [comment] 2021-06-15 17:12
@ivankruchkoff that's a good point about the layout shift as that wouldn't be a great user experience. I discussed this with @felixarntz earlier and we decided that this can be handled separately so it need not block this issue 👍 

I'll create an issue to handle this now.

**Comment by ivankruchkoff** [comment] 2021-06-16 09:42
@aaemnnosttv updated to call notifications before the 5s are up.

Moved the component to the `legacy-notifications`, my rationale for the `notifications` folder was that this new component is a refactored functional component rather than the legacy class based, but I can see the rationale for moving it as a block of functionality.

Back over to you for review @aaemnnosttv.

**Comment by aaemnnosttv** [comment] 2021-06-16 10:32
IB ✅

**Comment by ivankruchkoff** [comment] 2021-06-21 07:30
Over to CR now, copying the comment from the CR here for posterity:

Slight deviations from the IB:
E2E: I've updated the e2e tests to pass by removing the waiting for endpoint since we're now using the selector, however the test coverage scenarios are now covered in the storybook stories, with a VRT.
Storybook: Storybook now contains these scenarios e.g. https://google.github.io/site-kit-wp/storybook/pull/3603/?path=/story/components-dashboardcoresitealerts--notification-cta-with-survey-longer-delay , and combined with Backstop, they will also allow us to capture regressions such as when we resolve the layout shift issue per this comment: https://github.com/google/site-kit-wp/issues/3508#issuecomment-861679079

**Comment by Hazlitte** [comment] 2021-06-24 10:48
** QA ✅  **
I checked the stories, had a look at the code and forced a notification.

**Comment by tofumatt** [comment] 2021-06-24 16:54
@Hazlitte Did you trigger a notification when the User Survey is displayed, ensuring that the notification _didn't_ appear if the User Survey shows up? I can't tell from the comment you wrote above, but the issue here is about ensuring notifications don't appear if a User Survey appears—is that what happened?

**Comment by Hazlitte** [comment] 2021-06-28 08:08
@tofumatt Yes if the User Survey shows up within 5 seconds the notification is not displayed.

**Closed** 2021-07-01 16:06 UTC
Labels: P0, QA: Eng, Rollover, Type: Enhancement
