### ISSUE TITLE
Blank Screen for Site Kit dashboard

### ISSUE THREAD

**Issue by debabratakarfa** [google/site-kit-wp#813] opened 2019-11-07 12:24 UTC
## Bug Description

I run `wp google-site-kit reset` and then I visit https://local.wordpress.test/wp-admin/admin.php?page=googlesitekit-splash, getting a blank screen.

## Steps to reproduce
1. Go to iTerm / any terminal and then run `wp google-site-kit reset`, then go to /wp-admin of your site.
2. Click on `Site Kit` from the sidebar.
3. See error

 - PHP Version: PHP 7.3.5-1+ubuntu18.04.1+deb.sury.org+1
 - OS: Ubuntu 18.04 - using VVV
 - Browser: Chrome
 - Plugin Version: 1.0.1
 - Device: Macbook

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by debabratakarfa** [comment] 2019-11-07 12:27
I was trying to debug #809 and then it happened.

**Comment by lightson** [comment] 2019-11-10 22:06
Updated to Version 1.0.2 today and now experiencing this issue. 

I use cloudflare CDN however disabling caching does nothing to help.

**Comment by tofumatt** [comment] 2019-11-12 12:26
I wasn't able to reproduce this issue either. Could you provide a bit more info about your setup or exact steps to reproduce so we can verify this issue and work on fixing it? Thanks! 😄

**Comment by lightson** [comment] 2019-11-13 13:06
Was just about to @tofumatt, then spotted the 1.0.3 update and... my issue is gone. No idea what was going on but least it appears fixed. Will report back if it re-occurs.

**Comment by tofumatt** [comment] 2019-11-13 14:09
@debabratakarfa Could you let us know if you're still seeing this bug using the 1.0.3 update? 😃

**Comment by tofumatt** [comment] 2019-11-15 12:28
I think this is a duplicate of #767; we should close it as such and keep track of this issue in #767.

**Closed by tofumatt** 2019-11-15 12:28 UTC
Labels: Type: Bug
