### ISSUE TITLE
Buttons with tooltip raise deprecation warning in StrictMode

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5378] opened 2022-06-16 09:11 UTC
## Bug Description

Initially raised as part of the bug bash for dashboard sharing, this issue is not DS-specific and applies to all `Button` component use with tooltips.

To reproduce, open the browser console and then hover a button that has a tooltip (e.g. user menu, help menu, idea hub action button, etc). They all raise the same warning (with a different trace):

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
```

<details>
    <summary>Bug bash issue</summary>
    
Bug bash issue: https://app.asana.com/0/1202258919887896/1202436389160100 please refer to Asana issue for background

Not sure exactly how I triggered this but noticed it in the console. We don't use this prop directly anywhere but the trace indicates `UserRoleSelect`.

```
Warning: Failed prop type: Material-UI: The `anchorEl` prop provided to the component is invalid.
The anchor element should be part of the document layout.
Make sure the element is present in the document or that it's not display none.
    in ForwardRef(Popper) (created by ForwardRef(Tooltip))
    in ForwardRef(Tooltip) (created by WithStyles(ForwardRef(Tooltip)))
    in WithStyles(ForwardRef(Tooltip)) (created by Button)
    in Button (created by UserRoleSelect)
    in div (created by UserRoleSelect)
    in UserRoleSelect (created by Module)
    in div (created by Module)
    in div (created by Module)
    in Module (created by DashboardSharingSettings)
    in div (created by DashboardSharingSettings)
    in div (created by DashboardSharingSettings)
    in DashboardSharingSettings (created by DashboardSharingSettingsButton)
    in div (created by DashboardSharingSettingsButton)
    in div
    in Unknown (created by DashboardSharingSettingsButton)
    in div (created by e)
    in div (created by e)
    in div (created by e)
    in e (created by DashboardSharingSettingsButton)
    in Portal (created by DashboardSharingSettingsButton)
    in DashboardSharingSettingsButton (created by DashboardMainApp)
    in div (created by Cell)
    in Cell (created by Header)
    in div (created by Row)
    in Row (created by Header)
    in div (created by ForwardRef)
    in ForwardRef (created by Header)
    in header (created by Header)
    in Header (created by DashboardMainApp)
    in DashboardMainApp (created by DashboardEntryPoint)
    in DashboardEntryPoint
    in RestoreSnapshots (created by Root)
    in ErrorHandler (created by Root)
    in Root
```

</details>

## Steps to reproduce

Note: this warning will only appear in development builds because it is triggered by React's [Strict Mode](https://reactjs.org/docs/strict-mode.html)

1. Go to the Site Kit dashboard
1. Hover a button that has a tooltip (e.g. user menu avatar button)
1. See warning in console

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Buttons with tooltips should not raise deprecation warnings when interacting with them

## Implementation Brief

* Within `assets/js/components/Root/index.js`:
    * As per this [comment](https://github.com/mui/material-ui/issues/13394#issuecomment-815452717), within say `<ViewContextProvider>`, add  `<ThemeProvider theme={createTheme}>` where `createTheme` is `unstable_createMuiStrictModeTheme()` only when in dev mode, otherwise it is `createTheme()`. `<ThemeProvider>`, `unstable_createMuiStrictModeTheme` and `createTheme` should all be imported from `'@material-ui/core'`

### Test Coverage

* No new tests required.

## QA Brief

* In addition to verifying the ACs:
    * This issue makes a change to the `<Root>` component which is used by all pages of the plugin. Hence, smoke testing should be done on all pages, including the WP Admin Bar and WP Dashboard.

## Changelog entry

* Fix React `StrictMode` warning when using Material button tooltips in development mode.

**Comment by eugene-manuilov** [comment] 2022-06-16 14:02
This is weird issue... I check our codebase and the material library and everything looks okay to me. Not sure why it happened. @aaemnnosttv what do you think if we ask Darren to try to reproduce this issue and if he can't, then close it?

**Comment by eclarke1** [comment] 2022-06-16 14:08
@wpdarren see comment above, could you please try to reproduce this one again?

**Comment by aaemnnosttv** [comment] 2022-08-10 18:53
@eugene-manuilov I still see this all the time, do you not see it? 🤔

**Comment by jimmymadon** [comment] 2022-08-12 14:20
The summary of all options is given in this [comment](https://github.com/mui/material-ui/issues/13394#issuecomment-776862251).

Bumping the estimate to 7 just for testing this change properly as it is a `<Root>` component change which I am not usually comfortable with. But the only other option is to upgrade to MUI 5.

**Comment by aaemnnosttv** [comment] 2022-08-12 17:19
@jimmymadon is there a reason we're not already using v5? It's been released for a while now (Sept 2021), with many releases since then. I'm guessing there's probably a reason but let's rule out this option before we go with your proposed solution to use the unstable API workaround.

cc: @asvinb as I think you were the one to pull in this library as part of the work on GM2+?

**Comment by jimmymadon** [comment] 2022-08-16 12:08
@aaemnnosttv Just did a bit of digging and MUI 5 requires React > 17 and we are on 16. Perhaps that is why we are using v4? @asvinb

**Comment by aaemnnosttv** [comment] 2022-08-16 18:30
@jimmymadon ah that makes sense. Thanks for checking 👍

**Comment by jimmymadon** [comment] 2022-08-16 18:39
@aaemnnosttv Should we move this to execution then? I am not sure if we are planning on bumping up to React 17/18 and if there are any reasons why we haven't done so already. We can use this 'slightly hacky' fix until we do so.

**Comment by aaemnnosttv** [comment] 2022-08-18 21:00
@jimmymadon overall it sounds ok to me but would be nice to know a bit more as to what the compromise is here (as far as I can tell it just passes an additional param in the theme config but not clear what it does). We don't use the theme provider currently so I'm guessing it's falling back to a default?

Also, looking at the source it seems that this would raise a new warning in development due to the function being renamed :)

**Comment by jimmymadon** [comment] 2022-08-20 14:42
@aaemnnosttv So in v4, it isn't mandatory to use `ThemeProvider` (it is in v5 from a quick read of the docs). Which warning do you mean - the ESLint Rule for camel case?

**Comment by aaemnnosttv** [comment] 2022-08-23 17:14
> Which warning do you mean - the ESLint Rule for camel case?

Oops, sorry – I thought I had linked it. Clipboard history to the rescue! 😄 https://github.com/mui/material-ui/blob/a563a60219f7f6519fb0f34f6d8e3bf0974e6495/packages/material-ui/src/styles/createTheme.js#L105-L113

**Comment by jimmymadon** [comment] 2022-08-30 23:18
@aaemnnosttv Have updated the IB to use `createTheme` but as discussed, in production, it wouldn't throw the warning. But better to use `createTheme`. Thanks.

**Comment by aaemnnosttv** [comment] 2022-08-31 15:01
SGTM, thanks @jimmymadon 

IB ✅

**Comment by wpdarren** [comment] 2022-09-16 11:23
### QA Update: ✅ 

**Verified:**

- Buttons with tooltips do not raise deprecation warnings when interacting with them. 
- I tested this on develop branch and also on the development build. 
- I went through all of the pages within Site Kit and did not discover any additional warnings or errors in the console. 

![image](https://user-images.githubusercontent.com/73545194/190628265-463bebf0-ff02-4efa-afe2-934029928a9e.png)

**Closed** 2022-09-22 15:13 UTC
Labels: Type: Bug, P2
