### ISSUE TITLE
Detailed Page Stats wrong "Unique Visitors from Search"

### ISSUE THREAD

**Issue by phamquangbaoplus** [google/site-kit-wp#1371] opened 2020-04-10 09:34 UTC
## Bug Description

Detailed Page Stats wrong "Unique Visitors from Search". It showing total website visitors instead of showing the number of visitors of the post.

## Steps to reproduce

1. Go to a single page with some traffic.
2. Using the admin bar Site Kit menu, note the "Total users" for that URL.
3. Click "More details" in the dropdown to visit the "Dashboard detail view".
4. Note the number of users ("Unique Visitors from Search") is the total number of visitors to the site, not the expected total users from step 2.

## Screenshots

Detail view for my about page, the "Unique Visitors from Search" number is actually for the entire site, not the "/about" URL. The other numbers are correct.

![image](https://user-images.githubusercontent.com/2676022/79005383-fb5d1d00-7b13-11ea-819c-424308955b7c.png)

## Additional Context

 - PHP Version:  7.4
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Plugin Version [e.g. 22] 1.7.0
 - Device: [e.g. iPhone6] Windows

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When viewing the "Dashboard detail view" for a URL, the "Unique Visitors from Search" should be the total for that URL.

## Implementation Brief

* In `assets/js/modules/analytics/dashboard/dashboard-widget-top-level.js` - in the `withData` data object, change the query with `userReportDataDefaults` to also include the `url` parameter. 
	- Follow pattern used for `siteAnalyticsReportDataDefaults` just below.

## QA Brief

* 

## Changelog entry

* Fix bug where single post stats would display the unique visitors from Search for the overall site instead of only that post.

**Comment by jamesozzie** [comment] 2020-04-10 13:07
@phamquangbaoplus We've moved Site Kit support to the WordPress support forum. You can open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there and we can assist. We can re-open this GitHub issue if we're able to determine any action required. 

Within your support topic please include any screenshots showing the same results after testing various individual posts.

**Comment by adamsilverstein** [comment] 2020-04-10 15:11
I have confirmed this issue is a regression caused by leaving the url out of the datapoint added in https://github.com/google/site-kit-wp/issues/1202. Reopening to triage.

**Comment by adamsilverstein** [comment] 2020-04-10 16:19
@phamquangbaoplus Thanks for the bug report. We have a fix in the works for this issue which should be in the next release.

**Comment by felixarntz** [comment] 2020-04-10 16:26
IB ✅

**Comment by felixarntz** [comment] 2020-04-13 15:12
@adamsilverstein Did you move this back from QA to CR on purpose?

**Comment by adamsilverstein** [comment] 2020-04-13 21:42
Not intentionally, I'm not sure how that happened. Moving back.

**Comment by felixarntz** [comment] 2020-04-13 22:43
@adamsilverstein Happened to me earlier on another one as well. Seems to be a strange side effect if you attach a PR to an issue after the PR was already merged.

**Comment by cole10up** [comment] 2020-04-21 07:04
**Tested**

Setup latest develop on hellogoodbye.today, activated Analytics and over a few days confirmed Analytics metrics showed up. 

Verified single page metrics in the admin matched details and not total visitors.
![image](https://user-images.githubusercontent.com/57115907/79834568-27716d00-8362-11ea-8448-49c7df8895d4.png)

![image](https://user-images.githubusercontent.com/57115907/79834708-6b647200-8362-11ea-8ccc-61a2ffdc705e.png)

Compared with total Unique visitors

![image](https://user-images.githubusercontent.com/57115907/79835325-618f3e80-8363-11ea-8d50-4dbb570b9659.png)
![image](https://user-images.githubusercontent.com/57115907/79835372-75d33b80-8363-11ea-85bb-6fa30d2e76bc.png)

Passed QA ✅

**Closed** 2020-04-22 19:32 UTC
Labels: P0, Type: Bug
