### ISSUE TITLE
E2E AMP Tests failing, only on CI, for WordPress 4.9/Gutenberg 4.9

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4889] opened 2022-02-24 23:34 UTC
## Bug Description

Two E2E tests related to the AMP Plugin are failing, but strangely only on CI/GitHub Actions. When run locally, myself (@tofumatt), @techanvil, and @kuasha420 all saw the tests pass. See: https://github.com/google/site-kit-wp/issues/4598#issuecomment-1049463374 for context.

It looks like these failing tests need to be debugged in CI, which as @techanvil points out, probably requires a PR that excludes other jobs whilst testing/debugging. Maybe even running them with `it.only` for the tests in question, which are:

* `specs/modules/tagmanager/setup.test.js > Tag Manager module setup › Setup with AMP active › with Secondary AMP › when validating › validates homepage AMP for logged-in users `
* `specs/modules/adsense/setup-new-user.test.js > setting up the AdSense module › AMP is setup › has valid AMP for logged-in users `

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The two above tests should pass when run on GitHub Actions.
* All other tests should still pass. 😄 

## Implementation Brief

* Merge #5029 

### Test Coverage

* No additional changes necessary

## QA Brief

* E2E amp-related tests should no longer fail with a `["Object"]` console error (e.g. https://github.com/google/site-kit-wp/runs/5824589583?check_suite_focus=true#step:13:244)

## Changelog entry

* N/A

**Comment by felixarntz** [comment] 2022-03-14 19:11
It would be great if we could prioritize this one soon. cc @FlicHollis @eclarke1

**Comment by kuasha420** [comment] 2022-03-22 22:27
renders both the AMP and web container select menus

## Update
I have spent quite a bit of time chasing this one and unfortunately couldn't pinpoint the problem. I had a few hopeful moment but various things prevented me from reaching the bottom of it. Here's a brief summery of my investigation in case it helps the next person investigating this. 

### Not just the two tests
First, the random test failures are not limited to the two tests mentioned in the issue. It also sometimes happen to many other "AMP" related tests, including, not limited to-

* Tag Manager module setup › Setup with AMP active › with Secondary AMP › renders both the AMP and web container select menus
* tting up the AdSense module › AMP is setup › has valid AMP for non-logged in users
* etc. 

Also, sometimes the error doesn't happen at all and the test passes as normal making it even more problematic to debug. 

### Nature of failed tests
For the most part, when the tests fail, the message is similar to either of the following: 

```
expect(jest.fn()).not.toHaveErrored(expected)

    Expected mock function not to be called but it was called with:
    ["Object"]
```
```
TimeoutError: Navigation timeout of 30000 ms exceeded
```

### The Error ["Object"] 
Once I disabled the `jest-console` and console logged the `message` object. It was something like this:

````js
   
console.error
    ConsoleMessage {
      _type: 'error',
      _text: 'JSHandle@object',
      _args: [
        JSHandle {
          _disposed: false,
          _context: [ExecutionContext],
          _client: [CDPSession],
          _remoteObject: [Object]
        }
      ],
      _stackTraceLocations: [
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 369225
        },
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 371658
        },
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 335429
        },
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 372904
        },
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 389324
        },
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 418115
        },
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 331716
        },
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 386063
        },
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 382343
        },
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 331939
        },
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 418115
        },
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 331716
        },
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 331884
        },
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 331819
        },
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 379503
        },
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 351313
        },
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 608106
        },
        {
          url: 'http://localhost:9002/wp-content/plugins/amp/assets/js/amp-settings.js?ver=c0c29c7b9065691edaad9c67d4939b2f',
          lineNumber: 0,
          columnNumber: 609378
        }
      ]
    }

````

Looks like something to do with the `amp-settings.js` file. Unfortunately, when I changed the workflow to run on debug build `npm run build:dev` this error disappeared completely and I couldn't go further than that. 

### Self Hosted
Once I set up the action to run on a self hosted-vm running ubuntu 20.04 (same version as github managed ci machine ubuntu-latest), the tests always passed. Maybe this can be a potential solution if all else fail. 

Good luck to whoever takes this next. Cheers :grin: 

Link of my personal fork where you can see some of the things I tried. https://github.com/kuasha420/site-kit-wp/pulls

**Comment by aaemnnosttv** [comment] 2022-04-04 23:30
Thanks @techanvil, that helps a lot! It seems we may only need to make sure the fetch requests that are made are waited for (as you found) – we have a utility for this – although I'm still seeing some failures, but I think we're on the right track 👍

**Comment by aaemnnosttv** [comment] 2022-04-26 22:16
I've done some additional digging on this one and I think #5029 will do the trick which adds waiting for fetch requests before continuing on when we change the AMP mode.

The underlying cause is from requests to `/amp/v1/scannable-urls` which are being cancelled (resulting in unexpected console errors) when we navigate without waiting for them to finish. This is essentially what the `createWaitForFetchRequests` utility was created to address.

The Amp plugin makes a few additional requests in WP 4.9 than in newer versions of WP due to the lack of support for preloading WP REST Requests. We preload requests in SK as well but [we have a backwards-compatible solution](https://github.com/google/site-kit-wp/blob/a206183b842adc8908c523e3ceaa462b95641fc1/includes/Core/Util/BC_Functions.php#L58) for it that works pre 5.0 😄 
 
See 
![image](https://user-images.githubusercontent.com/1621608/165400530-c5eb550c-883b-4f34-81c7-8be5d8849bf5.png)

I will also note that I found this was consistently reproducible locally using the `specs/modules/adsense/setup-new-user.test.js` test but only after deleting all `amp*` options.

Will update the IB now with the suggested fix. Note E2E is still failing (for a similar reason) but this appears to be due to #5091, although that should stop once 5091 is merged 🙂

**Comment by techanvil** [comment] 2022-04-27 08:53
> I've done some additional digging on this one and I think #5029 will do the trick which adds waiting for fetch requests before continuing on when we change the AMP mode.
>
> :scissors:  ...
>
> Will update the IB now with the suggested fix. Note E2E is still failing (for a similar reason) but this appears to be due to #5091, although that should stop once 5091 is merged slightly_smiling_face

Looks great, nice one for digging in further @aaemnnosttv, will be great to get this fix in place! :tada:

**Comment by eugene-manuilov** [comment] 2022-04-27 16:14
IB :white_check_mark:

**Comment by hussain-t** [comment] 2022-05-02 14:03
## QA Verified ✅ 

- Verified E2E amp-related tests no longer fail with a `["Object"]` console error
<img width="860" alt="Screenshot 2022-05-02 at 7 30 46 PM" src="https://user-images.githubusercontent.com/24408261/166247085-abf86033-10cc-4fba-b852-5d2af09e7b55.png">

**Comment by felixarntz** [comment] 2022-05-05 16:46
@eugene-manuilov @tofumatt @aaemnnosttv Note that there is still a failure happening (at least occasionally?) for `specs/modules/tagmanager/setup.test.js > Tag Manager module setup › Setup without AMP active`.

I realize this was not explicitly part of the ACs, so I'm going to approve this, but (also related to my Slack message) we should follow up to explore and fix the remaining e2e failures.

**Closed by felixarntz** 2022-05-05 16:46 UTC
Labels: P1, QA: Eng, Type: Infrastructure

**Comment by kuasha420** [comment] 2022-05-05 17:45
@felixarntz We have a follow up issue about it [here](https://github.com/google/site-kit-wp/issues/5154).
