### ISSUE TITLE
Authenticate error

### ISSUE THREAD

**Issue by srivastava903** [google/site-kit-wp#685] opened 2019-10-22 16:04 UTC
## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by ernee** [comment] 2019-10-22 21:08
duplicate of #688

**Closed by ernee** 2019-10-22 21:08 UTC
Labels: Type: Support
