### ISSUE TITLE
Adjust styling of the SiWG button on login pages

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#9722] opened 2024-11-20 15:38 UTC
## Bug Description

From the SiWG bug bash. Asana ticket can be found [here](https://app.asana.com/0/1208661003027471/1208781779069766/f).

The SiWG button doesn't stretch across the input fields, which is different than the figma designs. 

It does initially load in this way but then resizes. 

@tofumatt also noted:

> Stretching the button is something I noticed in WooCommerce but might actually be against the button styling guidelines. It might be better to centre this and shrink the WooCommerce one, but in any case this does need to be tweaked 👍

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Sign in with Google button on the WordPress and WooCommerce login pages should not "stretch" or otherwise fill the container it is placed in. The button should render at the appropriate/default size and never be stretched (as is currently done on the WooCommerce page)
* The button can be centred in its container rather than left-aligned, as is currently the case on the WordPress login page.

## Implementation Brief

* [ ] 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jimmymadon** [comment] 2024-11-24 15:43
@wpdarren I can't reproduce the unaligned version of the button on either the WP Login Page or the WooCommerce login page. I even tried throttling the network speed to 3G and it still appears fine to me.

@tofumatt If the button is already stretched by default due to the parent containers that the button falls in, should we spend time on resizing and centring this?

**Comment by tofumatt** [comment] 2024-11-28 19:45
I wasn't able to replicate this bug in Chrome or Safari, and it seems best we don't modify the styles, as mentioned in the Asana ticket.

@wpdarren Can you provide steps to reproduce the login button being non-full-width? I can't seem to make it happen.

If it's full-width, we can close this.

**Comment by wpdarren** [comment] 2024-12-02 14:37
@tofumatt odd this was as an issue but I agree, I am unable to recreate this.   Closing the ticket.

**Closed** 2024-12-02 14:37 UTC
Labels: Type: Bug, P0, Next Up, Team S, Module: Sign in with Google
