### ISSUE TITLE
Fatal Error when using Site Kit with full site editor

### ISSUE THREAD

**Issue by Greatdane** [google/site-kit-wp#4485] opened 2021-12-08 07:17 UTC
## Bug Description

If using the `Full Site Editor` and `Gutenberg` plugin, then activating the new Full Site Editor beta which is due to come out fully in WordPress 5.9, a critical error occurs related to Site Kit. 

## Steps to reproduce

1. Install and Activate the `Full Site Editor` and `Gutenberg` plugin.
2. Activate a block-based theme, such as `Zoologist`. 
3. Enable 'Site Editor' via Appearance > Site Editor (beta)
4. Install and Activate `Site Kit by Google`. 
5. See error;

Regarding Step 2:

<img width="1130" alt="Markup 2021-12-08 at 16 11 28" src="https://user-images.githubusercontent.com/5075840/145165117-9c3211d6-b855-46f9-8f83-6605257c00e6.png">

Error:
```
08-Dec-2021 06:08:16 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Google\Site_Kit\Core\Admin\Screens::Google\Site_Kit\Core\Admin\{closure}() must be of the type array, null given, called in /wordpress/core/5.8.2/wp-includes/class-wp-hook.php on line 303 and defined in /srv/htdocs/wp-content/plugins/google-site-kit/includes/Core/Admin/Screens.php:154
Stack trace:
#0 /wordpress/core/5.8.2/wp-includes/class-wp-hook.php(303): Google\Site_Kit\Core\Admin\Screens->Google\Site_Kit\Core\Admin\{closure}(NULL)
#1 /wordpress/core/5.8.2/wp-includes/plugin.php(189): WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/core/5.8.2/wp-admin/includes/menu.php(279): apply_filters('menu_order', Array)
#3 /wordpress/core/5.8.2/wp-admin/menu.php(341): require_once('/wordpress/core...')
#4 /wordpress/core/5.8.2/wp-admin/admin.php(158): require('/wordpress/core...')
#5 /wordpress/core/5.8.2/wp-admin/index.php(10): require_once('/wordpress/core...')
#6 {main}
  thrown in /srv/htdocs/wp-content/plugins/google-site-kit/includes/Core/Admin/Screens.php on line 154
```

## Additional Context

 - PHP Version: Any (7.4)
 - OS: Mac
 - Browser: Chrome 96 on macOS (Monterey)
 - Plugin Version: Any
 - Device: Macbook Pro

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by henrywright** [comment] 2021-12-08 10:50
This happens because the anonymous function argument in `Screens.php` has an `array` type declaration applied to it. If an external theme or plugin author did the following, for example, a fatal error would occur in Site Kit because the passed string would violate the expected array type:

```php
add_filter(
    'menu_order',
    function ( $menu_order ) {
        return 'I am a string';
    },
    1
);
```

If Site Kit was the only user of the `menu_order` filter, this problem could be avoided but the hook is available to code external to Site Kit. The solution is to not type hint the function argument in a this context.

**Comment by henrywright** [comment] 2021-12-08 17:48
@Greatdane with reference to fixing the problem for you specifically, check all of the plugins and theme you are using for usage of the `menu_order` filter. It is highly likely a callback hooked to `menu_order` isn't returning as expected

**Comment by Greatdane** [comment] 2021-12-09 02:03
Thanks for the infomation! I will pass this on.

**Comment by henrywright** [comment] 2021-12-09 10:50
@Greatdane there is a PR for this issue that hasn't been reviewed yet. Can you reopen this?

**Comment by aaemnnosttv** [comment] 2022-01-24 12:06
Thanks for the information @henrywright! While your PR would prevent Site Kit from being the point of failure, it doesn't solve the root cause which is (as you pointed out) something which is using the [`menu_order` filter](https://developer.wordpress.org/reference/hooks/menu_order/#parameters) incorrectly and changing `$menu_order` into a non-array. Unfortunately there isn't a very good solution for users to track down the source of the problem here. Thoughts @felixarntz ?

**Comment by felixarntz** [comment] 2022-01-24 12:34
@aaemnnosttv @henrywright This is indeed a problem elsewhere. We could remove the type hint, but then whatever plugin is _actually_ causing this problem is doing it wrong. The `menu_order` filter expects an array, changing the type of a filtered value is generally problematic, unless multiple types are declared as possible - which is not the case for `menu_order`, see https://developer.wordpress.org/reference/hooks/menu_order/

@Greatdane @henrywright Which other plugins do you have active on the site? Is there a chance one of them is using the filter incorrectly? We should report it there when we identify one.

**Comment by Addison-Stavlo** [comment] 2022-01-25 18:55
As noted above, the issue is with another plugin. I think it is safe to close this issue here.

The screenshot in this issue's description above shows a toggle screen added by the Editing Toolkit plugin. It turns out this plugin was calling `menu_order` with a custom menu order that was once defined in Gutenberg (`gutenberg_menu_order`) but that was removed in the last couple months. Removing the call to this undefined menu order resolves the conflict between these two plugins.

Thanks everyone here for your time and insight regarding this issue!

**Comment by aaemnnosttv** [comment] 2022-01-26 07:56
Thanks @Addison-Stavlo, closing this one for now 👍

**Closed by aaemnnosttv** 2022-01-26 07:56 UTC

**Comment by henrywright** [comment] 2022-02-02 17:39
agreed the problem is caused by a different plugin. Site Kit isn't the problem
