### ISSUE TITLE
Idea row actions have reduced contrast on hover

### ISSUE THREAD

**Issue by simonchampion** [google/site-kit-wp#3842] opened 2021-08-12 08:29 UTC
## Bug Description

When the browser is resized to 960px, upon hovering an idea, the icons are displayed on top of the idea name.

## Steps to reproduce

1. Activate Idea Hub module and visit the Site Kit dashboard
2. Set your browser width to be at least `961px`.
3. On desktop: Hover over an Idea Hub suggestion with a title that spans multiple lines (On mobile: tap the idea to activate the "Hover" state and see the icons)
4. See icon overlapping the title

## Screenshots

![image](https://user-images.githubusercontent.com/83005909/129164695-168d3afe-889d-435c-9934-04c9ba0cd9d4.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When icons are activated by hovering (or tapping, on mobile), there should be a white, gradient and/or semi-opaque background behind the icons that provides them with more contrast against the text behind the icons.

## Implementation Brief

* In the `assets/sass/components/idea-hub/_googlesitekit-idea-hub-dashboard-ideas-widget.scss` file:
  * Add the `background-color` property to the `.googlesitekit-idea-hub__idea--actions` class with `rgba(255, 255, 255, 0.75)` value.

### Test Coverage

* N/A

### Visual Regression Changes

* N/A

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2021-08-17 09:13
@eugene-manuilov oddly for me the dismiss/delete button does not visually appear to be within the `.googlesitekit-idea-hub__idea--actions` div even though it shows that it is in the inspector.

![image](https://user-images.githubusercontent.com/1621608/129697999-bb4ed7f7-2c87-4932-b9b1-6158d96756aa.png)

Can you take another look and see if you also see this?

How about we put the translucent background as the color of the icons themselves (circle) to not add square corners around round elements. This would help increase the contrast of the buttons when the row is hovered as well.

**Comment by eugene-manuilov** [comment] 2021-08-17 11:21
@aaemnnosttv looks like this ticket is a duplicate of #3839. I think we can close this ticket, can't we?

**Comment by aaemnnosttv** [comment] 2021-08-17 14:52
@eugene-manuilov looking at the ACs I think it may actually be more about this one which I think is still valid: https://app.asana.com/0/1200491083500938/1200759450014507/f

@felixarntz ?

**Comment by eugene-manuilov** [comment] 2021-08-17 17:45
@felixarntz yes, I agree with it. #3839 should fix the contrast issue as well. Going to close this ticket.

**Closed by eugene-manuilov** 2021-08-17 17:45 UTC
Labels: Type: Bug, P0, Good First Issue, Module: Idea Hub
