### ISSUE TITLE
Modify refresh button in PageSpeed widget

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#2391] opened 2020-11-18 18:46 UTC
The refresh button ("Run test again") in the PageSpeed widget should be moved next to the device toggle buttons. Furthermore it should use a refresh icon instead.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The refresh button in the PageSpeed Insights widget should be moved from the bottom ("Run test again") to left of the device toggle buttons, and it should use an icon, like in [this Figma file](https://www.figma.com/file/niZV5sVfeaE5sqnJAUgR3G/PageSpeed-Insights?node-id=160%3A37).
* The button label (for screen readers only) should remain the current "Run test again".
* This change should apply to both the current PSI widget and the new PSI widget using the widgets API (likely trivial because they already reuse the same components for the most part).

## Implementation Brief

* Edit the `assets/js/modules/pagespeed-insights/components/dashboard/DashboardPageSpeed.js` file:
  * Import `Icon` and `update` from the `@wordpress/icons` library;
  * Copy `updateReport` callback from the `assets/js/modules/pagespeed-insights/components/common/LabReportMetrics.js` file;
  * Add a new button component to the div with `googlesitekit-pagespeed-widget__device-size-tab-bar-wrapper` class:
    * Use `<Icon className="mdc-button__icon" icon={ update } />` for the `icon` attribute;
    * Use `updateReport` callback for the `onClick` attribute;
    * Use `isFetchingMobile || isFetchingDesktop` for the `disabled` attribute to disable the button when reports are being fetched;
    * Adjust styles to make sure the new button and size tabs look correctly on all breakpoints.
* Update the `assets/js/modules/pagespeed-insights/components/common/LabReportMetrics.js` file:
  * Remove `Run test again` link;
  * Remove `updateReport` callback;
  * Remove unused dependencies.

### Test Coverage

* Update existing tests if something fails due to the aforementioned changes.

### Visual Regression Changes

* PSI refresh button should be moved to the header of the PSI widget.

## QA Brief

* Set up Site Kit and activate PSI module;
* Go to the dashboard page;
* Make sure you see the new refresh button with the [rotate icon](https://developer.wordpress.org/resource/dashicons/#image-rotate) in the header of the new PSI widget and the legacy one;
* Make sure you don't see the `Run test again` link in the bottom of neither the new PSI widget nor the legacy one.

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2020-11-20 08:57
@felixarntz – regarding the ACs, I don't see an added button for the refresh action in the linked Figma file.

@eugene-manuilov assuming that the icon used isn't already chosen in the design (as it doesn't appear to be there at all?) then I would suggest we use `update`, `controlsRepeat`, or `rotateRight` instead, which all have a "forward" rotation rather than backwards/left.

![image](https://user-images.githubusercontent.com/1621608/99778969-0ef64a80-2b1d-11eb-95f5-ff06248e11e3.png)

![image](https://user-images.githubusercontent.com/1621608/99778964-0c93f080-2b1d-11eb-9c34-0469837085dc.png)

![image](https://user-images.githubusercontent.com/1621608/99779065-31886380-2b1d-11eb-912b-2d32550b6573.png)

Of the three that fit the intention, I like `rotateRight` the most, since it resembles the refresh icon in Chrome the closest 
![image](https://user-images.githubusercontent.com/1621608/99779310-89bf6580-2b1d-11eb-856a-41f154da9dbe.png)

However, I think at the scale of the button, it will be hard to see, since the line is a bit thin at that size. For that reason I think using `update` is preferable here, or maybe `controlsRepeat` which is also clear at small size, but the square edges are a bit odd on that one IMO.

Thoughts @felixarntz ?

A few other thoughts about the IB:

> Add a new button component to the div with `googlesitekit-pagespeed-widget__device-size-tab-bar-wrapper` class
  
This class is for an element containing a `TabBar` component, so this may not appear as intended when rendering just a single button.

---

We should also disable the button while the reports are being resolved, to prevent repetitive API calls should a user accidentally click it more than once, or before it has finished.

**Comment by eugene-manuilov** [comment] 2020-11-23 10:24
@aaemnnosttv IB is updated.

**Comment by felixarntz** [comment] 2020-11-23 21:02
@aaemnnosttv @eugene-manuilov Apologies on that, the button was in the Figma file when I wrote the ACs 🤷‍♂️ 

Let me double-check with UX here - maybe this was some old leftover, in which case this issue isn't even relevant. I'll check.

**Comment by aaemnnosttv** [comment] 2021-05-03 12:23
@felixarntz is this still something we're going to do or we're not sure? If so, should we remove the current ACs and IB since it will likely need to be redefined?

**Comment by felixarntz** [comment] 2021-05-03 15:25
@aaemnnosttv Maybe, we can review in an eventual Stalled triage meeting.

Let's keep the ACs and IB in there until we know for sure they need to be updated or rewritten, as they may still be (almost) valid or at least good for reference.

**Comment by aaemnnosttv** [comment] 2022-08-02 18:52
Closing this one as this widget is going to be entirely reworked in the near future.

**Closed by aaemnnosttv** 2022-08-02 18:52 UTC
Labels: Type: Enhancement, Good First Issue, Module: PageSpeed
