### ISSUE TITLE
Compatibility check: add service & API connection detection 

### ISSUE THREAD

**Issue by adamsilverstein** [google/site-kit-wp#1549] opened 2020-05-12 17:26 UTC
## Feature Description

When users first set up Site Kit, the plugin checks that the user's setup is completely compatible with Site Kit. We can improve these checks by adding a connection check to services the plugin depends on. If the connections fail (because of a firewall for example), we should inform the user they may not be able to use Site Kit.

### Existing compatibility check.

Currently, the `CompatibilityChecks` component is responsible for checking compatibility and includes checks for caching (which prevents tag verification from working) or a `localhost` domain. 

![image](https://user-images.githubusercontent.com/2676022/81719395-43849d80-943a-11ea-8098-5df7c0062c79.png)

### Adding connection tests
We can extend these checks to also verify the user can connect to required services:

* Site Kit Service (aka "the proxy"): test a request to a route on the service work? (eg. `https://sitekit.withgoogle.com/site-management/setup/`)
* Oauth URL: test a request to `https://myaccount.google.com/` (or the oauth route `https://accounts.google.com/signin/oauth/`) work?
* Search console and other APIs: Site Kit needs access to APIs from PHP - we should check a request to `https://www.googleapis.com` or a specific API endpoint from PHP. The server side check is important because it is possible the client can connect while the server is blocked.
* AMP project - test a request to `cdn.ampproject.org`. The service/proxy currently uses AMP, if the user is unable to connect to `cdn.ampproject.org` Site Kit will not work for them.

A response status check should be sufficient for testing. When we detect an issue we can warn the user that their setup may not be compatible with Site Kit. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Site Kit should issue a server-side request to `https://www.googleapis.com/analytics/v3/management/accounts` (essentially _any_ Google API endpoint requiring OAuth) - i.e. `( new Google_Service_Analytics(...) )->accounts->listManagementAccounts()` -  with an arbitrary access token. If the request fails with an error code other than `401` (e.g. cURL error), it should display message: 
_"Looks like your site is having a technical issue with requesting data from Google services._ {new line}
_To get more help, ask a question on our [support forum](https://wordpress.org/support/plugin/google-site-kit/) and include the text of the original error message:_ {new line} 
_{errorMessage}_"
(Note that `401` is the expected error response here, since the token is invalid.)
    * This should happen via a new REST route that uses the regular OAuth client, but then attaches an arbitrary access token for the request. This could theoretically be tried without any access token too, but this would have the PHP client try out a different method of authorizing, so providing an invalid access token should be more straightforward.
* ~~Site Kit should issue a client-side request to `https://accounts.google.com/o/oauth2/auth`. On failure it should display message: 
_"Looks like the Google authorisation service is restricted in your region which would prevent you from connecting to Google services via Site Kit._ {new line} 
_To get more help, ask a question on our [support forum](https://wordpress.org/support/plugin/google-site-kit/) and include the text of the original error message:_ {new line} 
_{errorMessage}_"~~
* Site Kit should issue a client-side request to `https://cdn.ampproject.org/v0.js`. On failure it should display message: 
_"Looks like the AMP CDN is restricted in your region, which could interfere with setup on the Site Kit service._ {new line} 
_To get more help, ask a question on our [support forum](https://wordpress.org/support/plugin/google-site-kit/) and include the text of the original error message:_ {new line} 
_{errorMessage}_"

## Implementation Brief

* Add a new `Core\Util\Health_Checks` class
    - Registers a new `core/site/data/health-checks` endpoint, returns an object of results for various checks.  
    Each check has its own key in the response object and maps to its own results object which includes a minimum of a boolean `pass`, but could potentially include any other arbitrary data.
        - `googleAPI: { pass, errorMsg }` - tests a request to the Search Console API
    - See https://github.com/google/site-kit-wp/blob/enhance/1549-compatibility-checks/includes/Core/Util/Health_Checks.php  
    _Needs to be updated to use above endpoint or otherwise match ACs_

#### `assets/js/components/setup/compatibility-checks.js`

* Add a new function to the list of `checks` to request `core/site/data/health-checks` (`useCache: false`)
    - If `response.checks.googleAPI.pass === false`, throw an error to display the warning in the AC
* Add a new function to the list of `checks` to make a `fetch` request to `https://cdn.ampproject.org/v0.js`
    - If `response.ok === false` throw an error to display the warning in the AC
* Follow existing convention for `checks` by throwing named errors when warning conditions are met
* Replace legacy `dataAPI` usage with `googlesitekit-api`

## QA Brief

* Should test that a failed connection to the `search.google.com` will cause the checks to fail, as well as a failed connection from the client to `cdn.amppproject.com`.
* To test the region-specific problems, a VPN should be used to e.g. request the AMP CDN from a country like Egypt where it is currently restricted.

## Changelog entry

* Detect potential problems with issuing API requests to Google services and AMP prior to setup and inform the user about it.

**Comment by felixarntz** [comment] 2020-06-29 19:21
@adamsilverstein I added some ACs, let me know whether that makes sense for you. I omitted the request to `sitekit.withgoogle.com` for now since I wasn't sure why we need it, can you clarify? Did we have issues with the site itself being blocked anywhere? I've been under the impression it had only been AMP and Google service APIs.

**Comment by felixarntz** [comment] 2020-07-01 16:34
Ready for IB, the messages can be refined as we move along.

**Comment by aaemnnosttv** [comment] 2020-07-20 10:08
@felixarntz 

> * Site Kit should issue a server-side request to `https://www.googleapis.com/analytics/v3/management/accounts` (essentially _any_ Google API endpoint requiring OAuth) - i.e. `( new Google_Service_Analytics(...) )->accounts->listManagementAccounts()` -  with an arbitrary access token. If the request fails with an error code other than `401` (e.g. cURL error), it should display message

This seems a bit heavy-handed to use the `apiclient` to make an arbitrary request simply to test that the server can connect to the Google API. We aren't concerned with any valid authentication, just that a request should be possible. For this I think using [`fsockopen`](https://www.php.net/manual/en/function.fsockopen.php) would be a simpler test for this. If a connection can be opened to `www.googleapis.com` on port `443`, that should be good enough to satisfy this check.

I would think this would be closer to what the AC seems to be for this point (the for the server ability to connect to the Google API) as well.

> Site Kit should issue a client-side request to `https://accounts.google.com/o/oauth2/auth`. On failure it should display message

We can't do this because of CORS. We could maybe hack around it by using an `img` tag with an `onLoad` handler, but that would be pretty hacky. This could also potentially cause a false positive (although fairly unlikely) due to a content security policy on the client's site, which like CORS would block the request, but wouldn't prevent them from navigating to it as they would during the set up. I'm not sure there is a reliable way we can check this from the client and checking from the server likely wouldn't be useful.

> Site Kit should issue a client-side request to `https://cdn.ampproject.org/v0.js`. On failure it should display message

This should be fine as it has `Access-Control-Allow-Origin: *`. Has this being blocked been a problem for anyone yet?

**Comment by felixarntz** [comment] 2020-07-20 17:50
@aaemnnosttv 
> > * Site Kit should issue a server-side request to `https://www.googleapis.com/analytics/v3/management/accounts` (essentially _any_ Google API endpoint requiring OAuth) - i.e. `( new Google_Service_Analytics(...) )->accounts->listManagementAccounts()` -  with an arbitrary access token. If the request fails with an error code other than `401` (e.g. cURL error), it should display message
> 
> This seems a bit heavy-handed to use the `apiclient` to make an arbitrary request simply to test that the server can connect to the Google API. We aren't concerned with any valid authentication, just that a request should be possible. For this I think using [`fsockopen`](https://www.php.net/manual/en/function.fsockopen.php) would be a simpler test for this. If a connection can be opened to `www.googleapis.com` on port `443`, that should be good enough to satisfy this check.

We don't need to be concerned with valid authentication here (that's why the API returning a `401` is okay), but the reason to make an actual API call here is that way we'd be using the exact same infrastructure Site Kit uses later. If there is a detail in the API client implementation that makes requests fail, we should get them too.

> > Site Kit should issue a client-side request to `https://accounts.google.com/o/oauth2/auth`. On failure it should display message
> 
> We can't do this because of CORS.

I've removed this bit from the ACs for now, we had just added this check here for "completeness" anyway. I believe nobody has reported access errors to us specifically related to the OAuth flow.

> > Site Kit should issue a client-side request to `https://cdn.ampproject.org/v0.js`. On failure it should display message
> 
> This should be fine as it has `Access-Control-Allow-Origin: *`. Has this being blocked been a problem for anyone yet?

Yes, apparently the AMP CDN is blocked in a few countries. Sometimes it's an on-and-off thing it seems, e.g. in Egypt.

**Comment by aaemnnosttv** [comment] 2020-07-21 16:20
Thanks @felixarntz this should be ready for another review.

One difference from the AC is that I used the Search Console API for the test request since it's the only API which is required for all installs, whereas not all Site Kit users may use Analytics. If it should use Analytics instead, that's an easy change to make I just thought it would make more sense to use something that applies to all sites (even though we don't really request that API anymore from Site Kit). Alternatively, maybe we could request something from the Site Verification API as it's the only other module which is always active.

**Comment by felixarntz** [comment] 2020-07-22 17:05
@aaemnnosttv IB pretty much ✅ , just let's stick to using `core/site` as REST route prefix for these kinds of endpoints, I think we should use a name like `core/site/data/health` or `core/site/data/health-checks` instead.

**Comment by aaemnnosttv** [comment] 2020-07-22 17:20
@felixarntz IB updated.

**Comment by felixarntz** [comment] 2020-07-22 17:56
IB ✅

**Comment by cole10up** [comment] 2020-08-13 07:18
**Tested:**

**Comment by cole10up** [comment] 2020-08-13 07:33
**Tested**

Installed latest release candidate, activated and ran through the setup process.

Blocking specific connections:

![image](https://user-images.githubusercontent.com/57115907/90106315-188d3c80-dcfc-11ea-8beb-43e05c223952.png)

Confirmed blocking connections raises an error message.

Passed QA ✅

**Comment by felixarntz** [comment] 2020-08-13 15:01
@cole10up @aaemnnosttv Looks like the actual error message is missing? There should be a text describing what's wrong below that warning headline (see ACs for text content).

**Comment by tofumatt** [comment] 2020-08-13 18:25
I was able to get:

<img width="995" alt="Screenshot 2020-08-13 at 19 20 10" src="https://user-images.githubusercontent.com/90871/90172059-5c368380-dd9a-11ea-9f41-e5f44457f7db.png">

when using Charles to abort requests made to the domain cdn.ampproject.org. Worth noting though: I only had the error come up and display in Firefox, not Chrome. I suspect this is due to Chrome not respecting my proxy settings (I usually do proxy debugging in Firefox) or maybe its use of DNS caching/prefetching that I'm not aware of.

At any rate, I could produce that message. I don't have a VPN service with servers in Egypt, so I'm not able to reproduce the geolocated issue as described, but the general CDN issue I can reproduce.

**Comment by cole10up** [comment] 2020-08-13 18:46
I also don't have VPN servers in Egypt - unable to test that case.

Moving to approved per @tofumatt's test above.

**Comment by felixarntz** [comment] 2020-08-13 18:51
@tofumatt @cole10up What about the Google API connection error? Did you test that / see the corresponding message?

**Comment by cole10up** [comment] 2020-08-13 19:25
**Retested**

Blocked a series of connections and saw the above warning without the corresponding message.

![image](https://user-images.githubusercontent.com/57115907/90177749-d72e7880-dd5f-11ea-80f7-2e9c21ad041e.png)

Ran a series of other attempts blocking connections as they came in. Still unable to see the corresponding message.

![image](https://user-images.githubusercontent.com/57115907/90177923-0fce5200-dd60-11ea-800c-cd60cec9f415.png)

**Comment by felixarntz** [comment] 2020-08-13 19:49
@cole10up You're blocking requests from your client to the server, but in order to invoke this error the outgoing request _from_ the server needs to be blocked or otherwise forced to fail.

I've temporarily added a random `throw Exception( 'test error' );` to the release's `Google\Site_Kit_Dependencies\Google_Client::execute()` method in PHP and got the expected result:
![Screenshot 2020-08-13 at 12 46 53](https://user-images.githubusercontent.com/3531426/90180146-68531e80-dd63-11ea-9aba-5166e557f159.png)

QA ✅

**Closed** 2020-08-13 19:57 UTC
Labels: P1, Type: Enhancement
