### ISSUE TITLE
Fatal error on clicking engagement rate and unique visitor from search data when site is in zero data state.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#6788] opened 2023-03-29 11:37 UTC
## Bug Description
When site is in zero data state and under GA4 dashboard view then on clicking "unique visitors from search" and Conversions data creates Fatal error on Main dashboard. 
On entity dashboard, clicking on "unique visitors from search" and "engagement rate" creates a fatal error.
 
```
`Cannot read properties of null (reading '__eventTarget')

    in GoogleChart
    in div
    in Cell
    in div
    in Row
    in div
    in Grid
    in AnalyticsStats
    in div
    in div
    in Widget
    in WithWidgetSlug(Widget)
    in SearchFunnelWidgetGA4
    in GA4DashboardWidgetSwitcher
    in Component
    in WidgetRenderer
    in div
    in Cell
    in WidgetCellWrapper
    in div
    in Row
    in div
    in div
    in Grid
    in WidgetAreaRenderer
    in div
    in WidgetContextRenderer
    in DashboardMainApp
    in DashboardEntryPoint
    in RestoreSnapshots
    in ErrorHandler
    in ThemeProvider
    in StrictMode
    in Root`

```
## Steps to reproduce

1. Set up Site kit. 
2. Enable GA4reporting feature flag.
3. Set the dashboard view to GA4 by executing the following in the browser console:
`googlesitekit.api.set('modules', 'analytics', 'settings', {'dashboardView': 'google-analytics-4'}) `
4. Refresh main dashboard.
6. Click on "unique visitors from search" under "Search traffic over the last 28 days" widget.
7. See error.
8. Check same on entity dashboard.

## Screenshots

<details>

![image](https://user-images.githubusercontent.com/94359491/228523495-bfb8e728-1650-49a9-8a06-94b43f2a9142.png)

![image](https://user-images.githubusercontent.com/94359491/228523556-1eab4d9a-096f-4afa-82d4-9981da5a7393.png)

![image](https://user-images.githubusercontent.com/94359491/228523667-678c4a72-8c5a-424e-adf9-5111f4dc2ff0.png)

</details>

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- No errors should arise from interacting with the selected Search Funnel metrics on the Site Kit dashboard, regardless of the zero or gathering state for either Search Console or Analytics
    - This was already fixed for the UA version in https://github.com/google/site-kit-wp/issues/6587, so this issue is specific to the GA4 version of the dashboard

## Implementation Brief

* N/A.

### Test Coverage

* N/A.

## QA Brief

* Please retest, this should no longer occur.

## Changelog entry

* N/A.

**Comment by techanvil** [comment] 2023-03-30 14:43
It might be worth retesting this once the PR for https://github.com/google/site-kit-wp/issues/6623 has been merged...

**Comment by aaemnnosttv** [comment] 2023-03-31 16:28
This looks like the same issue that we had in the UA version in https://github.com/google/site-kit-wp/issues/6587, it looks like the fix there didn't get ported to the GA4 version though as mentioned in the IB (https://github.com/google/site-kit-wp/pull/6606/files).

**Comment by aaemnnosttv** [comment] 2023-03-31 16:52
Taking a closer look here, this seems to be more about the zero state rather than gathering, which seems to work correctly. Could be #6623 is related here as well, but we can at least provide the AC.

**Comment by bethanylang** [comment] 2023-04-03 08:12
FYI @eclarke1 I've scheduled this for Sprint 99 as we've flagged it as a known issue for Bug Bash: https://app.asana.com/0/1204237371873197/1204290577888659/f

**Comment by techanvil** [comment] 2023-04-06 11:49
As the PR for #6623 has now been merged, I've checked this on `develop` and the error no longer occurs. Sending over to QA for a confirmation check.

**Comment by aaemnnosttv** [comment] 2023-04-06 18:02
Thanks @techanvil – once confirmed that this is no longer an issue, we can close this as a duplicate since nothing was actually done against this issue.

**Comment by mohitwp** [comment] 2023-04-13 08:58
### QA Update ⚠️ 

@techanvil @aaemnnosttv 

I set up Analytics on InstaWP site. Verified analytics status after 2 days but still Analytics showing under gathering mode if dashboard view set to GA4. Can we determine in how many days Analytics move from gathering to zero data state by default in case of GA4 property ?
It will help us to determine if it is correct as per time set for GA4 property or it is a potential issue of analytics not moving from gathering to zero data state.

cc @wpdarren 

<details>

![image](https://user-images.githubusercontent.com/94359491/231708609-6e4d0a17-5267-42e6-9235-903c4f0f4474.png)

![image](https://user-images.githubusercontent.com/94359491/231708731-1ffd3a85-ad1f-4479-8670-6cf9617baa79.png)

</details>

**Comment by mohitwp** [comment] 2023-04-14 05:23
### QA Update ✅ 

- Tested on dev environment.
- Verified on 3 day older site.
- Now fatal error is not showing on clicking engagement rate and unique visitor from search data when site is in zero data state. 
- Verified on both main and entity dashboard.

<details>


https://user-images.githubusercontent.com/94359491/231948590-406aad34-4bce-4c95-9a09-727aa054b6ed.mp4

</details>

**Closed** 2023-04-21 00:39 UTC
Labels: Type: Bug, P0
