### ISSUE TITLE
Clean dist directory without direct system command

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1106] opened 2020-02-07 10:26 UTC
## Feature Description

Currently our npm scripts for running the build include `rm -rf dist` which is not cross-platform friendly. We should use the [`CleanWebpackPlugin`](https://webpack.js.org/guides/output-management/#cleaning-up-the-dist-folder) to clear the destination output directory as part of the webpack process rather than calling this directly as a system command.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* System commands should not be used directly in npm commands

## Implementation Brief

* Add [`clean-webpack-plugin`](https://www.npmjs.com/package/clean-webpack-plugin) to npm `devDependencies`
* Remove `remove-dist` npm script and usage
* Reorder build commands to run webpack first when combined with other dist-producing tasks

## QA Brief

* Add some arbitrary files to the `./dist` directory
* Run `npm run build`
* Ensure the `./dist` directory no longer contains the added files

## Changelog entry

* N/A

**Comment by felixarntz** [comment] 2020-02-07 11:08
IB ✅

**Comment by aaemnnosttv** [comment] 2020-02-07 12:00
Waiting for #1098 to be merged first to avoid conflicts with npm script changes.

**Comment by tofumatt** [comment] 2020-04-01 18:14
Assigned to @aaemnnosttv mostly to merge (I've approved the PR), but feel free to take another look if desired as well 😄

**Comment by felixarntz** [comment] 2020-04-01 18:44
Taking over :)

**Comment by felixarntz** [comment] 2020-04-03 20:13
Looks like we're no longer removing the `dist` directory during `npm run build` - I'm suspecting it has something to do with these changes. Let's double-check that. Whenever you run e.g. `npm run build`, the `dist` directory should be removed in the beginning.

**Comment by felixarntz** [comment] 2020-04-03 20:27
Looks like it's better to use a general directory deletion package rather than the `CleanWebpackPlugin`, which doesn't seem to do it for us.

**Comment by cole10up** [comment] 2020-04-09 06:54
**Tested**

Added a file to /dist prior to npm run build 

![image](https://user-images.githubusercontent.com/57115907/78866260-e721fe80-79f3-11ea-8b3d-2e4c496a592c.png)

Confirmed script ran:
![image](https://user-images.githubusercontent.com/57115907/78866397-24868c00-79f4-11ea-83ec-875dcfb85c54.png)

Confirmed file was deleted:
![image](https://user-images.githubusercontent.com/57115907/78866427-323c1180-79f4-11ea-82cf-fc24ef8f233b.png)

Passed QA ✅

**Closed** 2020-04-09 16:44 UTC
Labels: Good First Issue, P1, QA: Eng, Type: Enhancement
