### ISSUE TITLE
Remove legacy `search_console_error` event

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#5116] opened 2022-04-20 17:53 UTC
## Feature Description

There are a few uses in the codebase of an old tracked event that are no longer relevant and should be removed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following tracked event and [all instances](https://github.com/google/site-kit-wp/search?q=search_console_error) that have the same category, action, and label should be removed https://github.com/google/site-kit-wp/blob/955f12bc0ec84127bfdaf2b708131e23318bed1d/assets/js/modules/search-console/components/dashboard/DashboardImpressionsWidget.js#L116

## Implementation Brief

* Remove all `trackEvent` calls with `search_console_error` as the second argument, eg. from:
  * `assets/js/components/wp-dashboard/WPDashboardClicks.js`
  * `assets/js/components/wp-dashboard/WPDashboardImpressions.js`
  * `assets/js/modules/search-console/components/dashboard/DashboardClicksWidget.js`
  * `assets/js/modules/search-console/components/dashboard/DashboardImpressionsWidget.js`

### Test Coverage

* Tests should not need updating.

## QA Brief

* In the current revision, the plugin tracks data loading errors in the following four locations through GA with the `plugin_setup` category and `search_console_error` action:
  * In the WordPress Dashboard "Site Kit Summary" widget, the "Total Impressions" section.
  * In the WordPress Dashboard "Site Kit Summary" widget, the "Total Clicks" section.
  * In the Site Kit Dashboard "Search Funnel" section, the "Impressions" widget.
  * In the Site Kit Dashboard "Search Funnel" section, the "Clicks" widget.
* QAing this would require making sure this event is not tracked anymore for the above locations.
* This can be done by simulating errors in the above locations and not letting these widgets load data, and then using the Google Analytics Debugger Chrome Extension to make sure these errors are not tracked.
* The above-mentioned error can be simulated by setting a "Custom Site URL" using the Dev Settings plugin after the plugin setup and clearing the session storage.
* In order to see these events being tracked in the **Site Kit Dashboard**, the `unifiedDashboard` feature flag must be **unchecked** in the tester plugin.

## Changelog entry

* N/A

**Comment by eugene-manuilov** [comment] 2022-04-21 13:13
IB ✔️

**Comment by mohitwp** [comment] 2022-06-06 06:42
### QA Update ⚠️ 

@nfmohit I tried to reproduce this issue as per QAB on latest release. I'm not getting any `search_console_error ` event on latest as well as on develop branch. How can I get this event ? Let me know if I missed any step here.

![image](https://user-images.githubusercontent.com/94359491/172108968-7bb3ad9d-7319-4523-8e4e-a32322b2ed58.png)

![image](https://user-images.githubusercontent.com/94359491/172109231-84096f43-bc63-470a-84e7-53aebd1d7289.png)

**Comment by wpdarren** [comment] 2022-06-15 08:35
### QA Update: ⚠️ 

@nfmohit going on the QAB, the `plugin_setup category` and `search_console_error` action should be appearing on the WP and Site Kit Dashboard on the latest release.   I can confirm on the WP Dashboard, the GA event category and action can be found on 1.75.0 and when I switch to develop branch, it does not appear in the log ✅ 

The issue is, on the Site Kit Dashboard, the `plugin_setup category` and `search_console_error` action does not appear on 1.75.0. Can you confirm if it 100% should? Are you able to see these on the Site Kit Dashboard?  In these types of situations it's good to see the initial issue so we know it has been fixed on develop.

**Comment by nfmohit** [comment] 2022-06-15 10:55
@wpdarren I have updated the QAB. I had mistakenly forgotten to include that in order to see these events being tracked in the **Site Kit Dashboard**, the `unifiedDashboard` feature flag must be **unchecked** in the tester plugin.

Could you check if the feature flag is checked in your test setup, uncheck it and see if you can see the event being tracked?

I should also mention that:
- according to my tests, the `unifiedDashboard` feature is enabled by default in a fresh installation of 1.75.0. So, you'd need to install the tester plugin, in the tester plugin settings, set the `Force enabled feature flags` to `Always override` to track these events from the Site Kit Dashboard.
- These events won't be relevant within the Site Kit Dashboard anymore in the future anyway because the `unifiedDashboard` feature flag and relevant unused code is being removed as a part of #5047.

**Comment by wpdarren** [comment] 2022-06-15 11:23
### QA Update: ✅ 

Nice work @nfmohit - that worked perfectly.  Thank you for your help. 

**Verified:**
 
I can confirm on the WP Dashboard and Site Kit Dashboard, the GA event category and action can be found on 1.75.0 and when I switch to develop branch, it does not appear in the log

**Closed** 2022-06-16 17:43 UTC
Labels: P2, Type: Enhancement, Good First Issue, Rollover
