### ISSUE TITLE
Detect malformed REST responses and display a specific error/help page link

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#8936] opened 2024-06-26 17:09 UTC
## Feature Description

Based on #8442, we should detect specific malformed WP REST API JSON responses and display a bespoke error message for them with links to a help document that addresses those errors.

The help page should reference plugin(s) (like Transliterator plugin in #8442) that are known to cause these errors.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Any malformed JSON response from the WP REST API (at least for Site Kit endpoints) should be detected by our API client/fetch store and raise a specific error.
  * The ability to retry the request should be maintained.
  * The message should warn the user that an unexpected response was received from WordPress.
  * There should be a link to learn more on a Site Kit documentation page (TBD) that explains what might cause this issue and fixes.

## Implementation Brief

*To get a malformed response, [install version 1.13.0 or lower, of the Transliterator plugin](https://wordpress.org/plugins/serbian-transliteration/advanced/). Clear local and session storage, reload the dashboard and inspect the Analytics report responses.*

**Add response validation infrastructure**
- [ ] Update `assets/js/googlesitekit/data/create-fetch-store.js`, adding an optional prop, `validateReponse`.
   - [ ] Update the `RECEIVE` reducer case to check if a function was passed to `validateResponse`, if it was, run this function passing the response as the only prop, before calling `reducerCallback`.

**Add Analytics 4 report, response validation**
- [ ] Update `assets/js/modules/analytics-4/datastore/report.js` passing a new function to the `validateResponse` prop on, `createFetchStore`:
    - [ ] In this function, check the first data row is returned as an array, if it's a numerically keyed object, throw a new error of type `ERROR_INVALID_JSON`. 
       - Confirm this is handled and displayed correctly in each key analytics report widget.

**Show custom error message with support link.**
 * [ ] Update `assets/js/util/errors.js` to support the new error type, return the same text as `ERROR_INVALID_JSON` but add a link to the new support documentation.

### Test Coverage

* Create new tests in `assets/js/googlesitekit/data/create-fetch-store.test.js` for the new `validateResponse` prop confirming there is no change in behaviour if no validation function is provided, confirm the new error is thrown if the response does not validate and no error is returned with a valid response.

## QA Brief

* 

## Changelog entry

*

**Comment by binnieshah** [comment] 2024-07-17 13:36
@jamesozzie @tofumatt please could you confirm next steps on this one?

**Comment by jamesozzie** [comment] 2024-07-17 14:17
@binnieshah I have a [documentation task](https://app.asana.com/0/1185360131189553/1207715413812397/f) for this which I'll update today and send to @adamdunnage for review. 

@tofumatt Do you know the error code for this, so I can add to the mapping sheet?

**Comment by benbowler** [comment] 2024-08-30 13:09
Hey @tofumatt I've written the IB here, the key challenge here is that we don't have a schema definition consistently for each REST API. The closest we have for some APIs in on the PHP side:

https://github.com/google/site-kit-wp/blob/41f0bbaec9736ba334cccc7b469ce1a5e2cdfc71/includes/Core/Consent_Mode/REST_Consent_Mode_Controller.php#L124-L148

To roll this out across all of our APIs will require defining the schema across all of these APIs in a reliable way. In the IB I propose an approach for this and suggest starting with the `getReport` request as it is the most used API as well as the one that it effected by the issue caused by the Transliterator plugin. As we apply this to different stores we could extract the logic that compares the schema to the response into a reusable helper to use in other stores.

**Comment by eugene-manuilov** [comment] 2024-09-03 20:48
@benbowler, i think the main idea here is not to verify responses to match certain schemas but to detect when an API request returns a response that is not a JSON object. In other words, if the request fails and returns non-JSON response, we should craft a special error and dispatch it in the `catch` section: https://github.com/google/site-kit-wp/blob/45ca3ddd422f59f2ae0250c038783887c913d8c7/assets/js/googlesitekit/api/index.js#L183-L209

**Comment by benbowler** [comment] 2024-09-04 09:08
@eugene-manuilov well in the issue that caused this ticket to be created (#8442) the json returned from the API was still valid JSON, but the expected JSON format for the report had been modified by the Transliterator plugin. Specifically, arrays had been restructured to numerically indexed objects in the response.

**Comment by eugene-manuilov** [comment] 2024-09-05 16:58
@benbowler, ah.. thanks for clarifying that, i didn't notice that.

> * Update `assets/js/googlesitekit/data/create-fetch-store.js`, adding an optional prop, `validateResponse`, which defaults to an empty function that simply passes through all props unchanged.

Let's probably just add a new property `schema` to `createFetchStore` arguments instead of `validateResponse`. If a schema is passed the fetch store should automatically verify it.

**Comment by benbowler** [comment] 2024-09-12 06:35
While thinking about this over coffee, I found [this super popular library](https://www.npmjs.com/package/ajv) that we can use to build and validate JSON schemas without re-inventing the wheel here.

**Comment by benbowler** [comment] 2024-09-12 09:10
With the use of this package, and limiting to the analytics reporting infrastructure for now I've reduced the estimate slightly. The main work here will be defining the report structure fully.

I could expand this to other modules too, for now I suggest we build this out for the analytics module and if it's effective, create follow up tickets for other modules. With the analytics module only, the original issue will be covered.

**Comment by eugene-manuilov** [comment] 2024-09-13 18:02
Thanks, @benbowler. My main concern is that `ajv` is a quite big library. I would probably like to ask @tofumatt to chime in. Perhaps he has some ideas.

**Comment by benbowler** [comment] 2024-09-16 15:19
Taking his back to IB after my 1:1 with @aaemnnosttv. I'll aim to use a MVP response validation function for now. Also I need to add points for updating the widget to show a custom error message and support link.

CC @tofumatt @eugene-manuilov

**Comment by benbowler** [comment] 2024-09-17 12:01
Looking into this again today, I retested with the latest version of the Transliterator plugin as I was updating the IB and I can no longer repeat the error [taking these steps](https://github.com/google/site-kit-wp/issues/8442). Can you confirm @eugene-manuilov @tofumatt ?

If this is the case then this ticket can be closed.

**Comment by eugene-manuilov** [comment] 2024-09-17 16:22
> I retested with the latest version of the Transliterator plugin

@benbowler, how about older versions? Does the issue persist for older versions of that plugin?

**Comment by benbowler** [comment] 2024-09-18 08:32
@eugene-manuilov I'll test a few versions and check.

**Comment by benbowler** [comment] 2024-09-18 09:25
@eugene-manuilov I tested this and the error occurs on [version 1.13 or lower of the plugin](https://wordpress.org/plugins/serbian-transliteration/advanced/). ~65% of users are still on these versions of the plugin:
 
<img width="773" alt="Screenshot 2024-09-18 at 11 19 48" src="https://github.com/user-attachments/assets/74f0c474-6ec7-4e5b-a5f2-34ed167c1718">

IB updated to address this.

**Comment by benbowler** [comment] 2024-09-18 09:27
Note for the documentation, we should suggest users update the Transliterator plugin if they have it installed as it is fixed in the 2.0 versions.

**Comment by eugene-manuilov** [comment] 2024-09-18 17:38
> ... I tested this and the error occurs on version 1.13 or lower of the plugin. ~65% of users are still on these versions of the plugin ...

Thanks, @benbowler. I wonder if we know that the problem is caused by another plugin that already has a fix for it then do we still need to do something in our plugin then? Perhaps we should just update the documentation to make it clear that users need to upgrade their plugin in order to fix the problem. @aaemnnosttv, what do you think?

**Comment by aaemnnosttv** [comment] 2024-11-05 21:48
Thanks both, let's close this for now and revisit if it really becomes a problem. Aside from this one incident, I don't think it's really been an issue in all these years.

**Closed by aaemnnosttv** 2024-11-05 21:48 UTC
Labels: P2, Type: Enhancement, Needs Documentation
