### ISSUE TITLE
PHP Deprecation notices, PHP 8.1 & 8.2

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#7091] opened 2023-05-25 17:47 UTC
When checking the a site with PHP 8.1 or great, various deprecation notices appear. Errors also appear on the front end of a site while not logged in. 

Recording of errors below:

https://github.com/google/site-kit-wp/assets/41326532/0d131104-43cb-489d-abaf-27a86d5789f9

```
Deprecated:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /s2-chasetray/wordpress/wp-content/plugins/google-site-kit/includes/Core/REST_API/REST_Routes.php on line 69

Deprecated:  Creation of dynamic property Google\Site_Kit\Modules\Analytics\Web_Tag::$module_slug is deprecated in /s2-chasetray/wordpress/wp-content/plugins/google-site-kit/includes/Core/Modules/Tags/Module_Tag.php on line 42

Deprecated:  Creation of dynamic property Google\Site_Kit\Modules\Analytics_4\Web_Tag::$module_slug is deprecated in /s2-chasetray/wordpress/wp-content/plugins/google-site-kit/includes/Core/Modules/Tags/Module_Tag.php on line 42
```

**Below**: Errors with SK 8..1.17

![image](https://github.com/google/site-kit-wp/assets/41326532/b504d74d-b344-458d-988e-e4431fd22df7)

**Below**: Errors with PHP 8.2

![image](https://github.com/google/site-kit-wp/assets/41326532/6b3b9b79-ad9a-4cbd-bee5-7d903f5599e8)

**Below**: Errors appearing while not logged in (with error reporting enabled)

![image](https://github.com/google/site-kit-wp/assets/41326532/0fb1936b-d70a-4771-8bf6-900a29e4bd51)

## Steps to reproduce

1. Set up Site Kit on a TasteWP site
2. Connect Analytics during setup
3. Enable error reporting and check for PHP errors

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2023-07-11 20:16
Duplicate of 
* https://github.com/google/site-kit-wp/issues/7147
* https://github.com/google/site-kit-wp/issues/7202

**Closed by aaemnnosttv** 2023-07-11 20:16 UTC
Labels: Type: Bug, Type: Support
