### ISSUE TITLE
"Additional Permissions Required" for PSI - Infinite Loop

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#5357] opened 2022-06-15 14:24 UTC
## Bug Description

Bug bash issue: https://app.asana.com/0/1202258919887896/1202443434724992 please refer to Asana issue for additional context.

## Steps to reproduce

1. Using an administrator user (say admin1), connect all modules.
2. Create another administrator user (say admin2).
3. Login as admin2 to delete admin1
4. Sign into SiteKit using admin2's google account. A list of recoverable modules will be displayed.
5. Scroll down to the PSI widget until the Additional Permissions Required popup appears. 
6. Follow the CTA to grant those permissions which will redirect you back to the dashboard.
7. Scroll down and the popup will appear again.

## Screenshots

https://user-images.githubusercontent.com/90871/174117957-4c202b66-f95e-4588-b020-e7e25d9dcfa1.mov

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When an admin ("admin2") recovers another user's ("admin1") modules and grants additional permissions for PageSpeed Insight, the "Addition Permissions Required" should not appear again after "admin2" grants permissions.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment] 2022-06-16 16:30
@aaemnnosttv Just a quick check on this—should PSI even be _asking_ for additional permissions? It seems odd, because I thought it didn't require any permissions and that "connecting" PSI is really just a matter of enabling it, since it doesn't require any authentication to use.

My understanding was the only reason we "authenticate" is to associate the request with a particular Google Account. But I didn't think that would require granting any permissions and should "just work", even when changing which user PSI is associated with.

So maybe the issue here is that PSI should never ask for additional permissions—when recovered, it should just be transferred to the new user?

**Comment by aaemnnosttv** [comment] 2022-06-16 19:20
@tofumatt – @felixarntz raised a similar issue he came across and the problem is that the request is attempting to be made as a shared request here when we know that won't work because the module is recoverable. I opened #5383 which should fix this too as this isn't specific to PSI.

Closing in favor of #5383

**Closed by aaemnnosttv** 2022-06-16 19:20 UTC
Labels: Type: Bug, P0
