### ISSUE TITLE
Page Speed widget - "Mobile" & "Desktop" icon change

### ISSUE THREAD

**Issue by Pratheep-lab** [google/site-kit-wp#3162] opened 2021-04-15 14:54 UTC
On the Page Speed widget found at the bottom of the SK dashboard, the mobile and desktop icons need to be changed to standard material design icons. 

Current screenshot showing Page speed widget: 
![image](https://user-images.githubusercontent.com/81642523/114890072-9b721400-9e02-11eb-90d2-f4aec513ba3a.png)

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The icons used for the PageSpeed insights widget for toggling device-specific reports should be updated to use the following Material icons (new svg files linked):
    * [`computer`](https://fonts.gstatic.com/s/i/materialicons/computer/v10/24px.svg)
    * [`smartphone`](https://fonts.gstatic.com/s/i/materialicons/smartphone/v11/24px.svg)
* The source of the new icons should be amended to inherit the fill color using `currentColor` instead of a fixed hex code 
* The previous icons which are no longer used should be deleted  

## Implementation Brief
* Replace `assets/svg/device-size-mobile-icon.svg` by the `smartphone` icon in the AC.
* Replace `assets/svg/device-size-desktop-icon.svg` by the `computer` icon in the AC.
* In both SVGs, add the `fill` attribute with the `currentColor` value to the last `path` element.
* Using `assets/sass/components/global/_googlesitekit-DeviceSizeTabBar.scss`,
    * Add the `color` styles to `svg`, both including the one for `.mdc-tab--active`, having the same value as the corresponding `svg path fill` styles.
    * Remove the `fill` styles for `svg path`, and the resulting empty `path` selector.

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* Expected change to the Page Speed dashboard component with the icon changes.

## QA Brief

On the Page Speed widget found at the bottom of the SK dashboard:
* Toggle between the mobile and desktop icons
* Verify that they have been updated with icons in AC

## Changelog entry

* Update viewport icons used in PageSpeed Insights widget.

**Comment by aaemnnosttv** [comment] 2021-04-20 14:24
@Pratheep-lab are the current icons not from Material? I believe whatever is there was provided by @aarondruck in the original designs but perhaps he can confirm.

cc: @felixarntz @marrrmarrr

**Comment by aarondruck** [comment] 2021-04-20 21:14
Sorry, I think we can close this.  I was mostly tripped up on the
difference between the mobile icons, of what was designed and what's in
production.  But it's minimal, so we can just close this.

Original icon:
[image: image.png]

Icon in production:
[image: image.png]

**Comment by aaemnnosttv** [comment] 2021-05-03 12:15
@aarondruck here they are side-by-side which makes it a bit easier to compare.
![image](https://user-images.githubusercontent.com/1621608/116874155-80d0d500-ac21-11eb-962d-3b3ffb570021.png)

The color looks more balanced with the new phone icon, but I think I prefer the laptop icon to the monitor.

How about `smartphone` and `computer` icons?

![image](https://user-images.githubusercontent.com/1621608/116874699-69deb280-ac22-11eb-8a0b-a7681ec2e418.png)
![image](https://user-images.githubusercontent.com/1621608/116874709-6cd9a300-ac22-11eb-9919-6155fe7568b5.png)


What do you think?

**Comment by aarondruck** [comment] 2021-05-05 15:25
The *Smartphone* and *Computer* icons work, thank you for looking into it!

**Comment by eugene-manuilov** [comment] 2021-07-12 14:52
IB :heavy_check_mark:

**Comment by danielgent** [comment] 2021-08-11 14:07
This is ready to go into CR but as it is outside of the current sprint I'm leaving it in execution

**Comment by danielgent** [comment] 2021-08-16 15:35
Setting to Code Review as I'm unassigning tickets from myself :smile:

**Comment by felixarntz** [comment] 2021-08-23 18:00
Adding to the 1.40.0 release since this is a trivial enhancement and good to go. cc @aaemnnosttv

**Comment by wpdarren** [comment] 2021-08-24 13:12
### QA Update: ❌ 

@aaemnnosttv @felixarntz in my opinion the icons look a lot smaller than the previous ones. Maybe it's my eyes 😃 

The icons are 24x24 according to the SVG files. I'm not sure what the old icons size were.   What are your thoughts?

On `Develop/Main`
![image](https://user-images.githubusercontent.com/73545194/130621345-a1131b5a-06f3-426e-b7a0-0d872748c3af.png)

On `latest release`
![image](https://user-images.githubusercontent.com/73545194/130622240-74887dff-51c4-40f2-8027-3edc7f247542.png)

**Comment by aaemnnosttv** [comment] 2021-08-24 15:28
Thanks @wpdarren, they are a bit smaller now you're right. I've opened a PR to fix this 👍

**Comment by wpdarren** [comment] 2021-08-25 11:49
### QA Update: Pass ✅ 

**Verified:**

- On the Page Speed widget: confirmed that the new icons appear as per the AC. 
- Checked the icons on desktop and mobile screen sizes. 

![image](https://user-images.githubusercontent.com/73545194/130785270-c5a9c71b-ab8f-4a3f-83fe-e96167f65177.png)

**Closed** 2021-08-30 19:02 UTC
Labels: P2, Type: Enhancement, Good First Issue, Module: PageSpeed, UX
