### ISSUE TITLE
Enhance service report URLs to include date range

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#2551] opened 2020-12-21 11:25 UTC
## Feature Description

Currently our service report URLs (deep links to report pages on the service – currently only Analytics) link to a specific report view, but do not include the date range. This can be passed in the same report args that we already use, it just needs to be included.

E.g. `/_u.date00=20201201&_u.date01=20201220/`

```js
{
    // Report args...
    '_u.date00': '20201201', // Start date
    '_u.date01': '20201220', // End date
}
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2020-12-21 11:26
@felixarntz

**Comment by felixarntz** [comment] 2020-12-21 14:53
@aaemnnosttv Duplicate of #2287 - but good reminder that we can move that forward now :)

**Closed by felixarntz** 2020-12-21 14:53 UTC
Labels: Module: Analytics, P1, Type: Enhancement
