### ISSUE TITLE
Subdomain sites not getting added to AdSense platform when connected via Site Kit

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#6036] opened 2022-10-20 13:06 UTC
## Bug Description

If a user connects a subdomain site to their AdSense account using Site Kit, this subdomain site never gets listed within the "Sites" tab on the AdSense platform. 

https://recordit.co/yHS9Jiyxhp

This was tested on 2 different subdomain sites (using 2 different parent domains, which are already approved for ads). 

## Steps to reproduce

1. Set up Site Kit on a subdomain site. The parent domain must already be approved for ads
2. Connect the AdSense module
3. Set up should complete successfully
4. When checking the AdSense platform the subdomain site is not listed

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by adamdunnage** [comment] 2022-11-03 15:05
While troubleshooting [another issue](https://github.com/google/site-kit-wp/issues/5693) I noticed that I was getting the same outcome when connecting a new subdomin to AdSense where the parent domain is already approved for Ads.

Once the subdomain is connected and I navigate to **AdSense Platform > Sites > Parent Domain** the newly connected subdomain is not part of the list. 

AdSense connected on adam.oi.ie:

![image](https://user-images.githubusercontent.com/91896826/199757703-c0199199-d047-438f-9f96-0a19aafe1c68.png)

adam.oi.ie subdomain not listed on AdSense account:

![image](https://user-images.githubusercontent.com/91896826/199757941-9e3458fe-bfca-4b2a-8f73-107c2f5d7131.png)

**Comment by aaemnnosttv** [comment] 2022-12-16 20:00
Moving to escalation as we need some investigation here.

**Comment by bethanylang** [comment] 2023-01-05 15:24
This issue has been lingering for some time and is coming up consistently in the support forums. We have a workaround that we've been sharing with users, but we had a recent report that the workaround wasn't working.

**Comment by aaemnnosttv** [comment] 2023-01-07 04:34
@jamesozzie did this behave differently in the past? If anything, I think something may have changed on the AdSense side as Site Kit cannot make any changes on the AdSense side. Should the user not have to add the subdomain site on the platform side as well?

**Comment by jamesozzie** [comment] 2023-01-09 11:58
I can't be sure if this was the case previously. I don't recall setting up subdomains on AdSense and checking if they were added on the "sites" tab previously. I also can't find any information on changes at AdSense level. The [official AdSense guide on subdomain approvals](https://support.google.com/adsense/thread/44677775/adsense-on-subdomains) isn't accessible via the Waymachmachine 

It may be the case that subdomain sites needed to be approved previously, and not auto approved as they are now (subdomain sites are auto approved for ads if the root domain is already approved). If there were changes to subdomain sites and auto approvals, maybe there were changes at AdSense level. There is very little publicly available on this, with [mixed answers from the product experts](?hl=en) on whether subdomain sites needed site reviews previously. 

I'm happy to check older versions of the plugin for the same behavior if you think that would be useful @aaemnnosttv

**Comment by bethanylang** [comment] 2023-02-14 17:05
@jamesozzie Evan and I discussed this one today and he confirmed that the AdSense API is read-only, so Site Kit would not be capable of adding sites to the Sites tab. Since we once again have some contacts at AdSense, can you follow up with them (if this remains an issue) and see if something changed on their side so that we can advise our users? 

For now, I'll close this issue out as it's not something that could be changed in Site Kit.

**Closed by bethanylang** 2023-02-14 17:05 UTC
Labels: Type: Bug, Type: Support, Group: Escalation, Module: AdSense

**Comment by jamesozzie** [comment] 2023-03-13 14:38
@aaemnnosttv Just a note on this. The AdSense team stated that they rewrote their API extensively by Sep. 2022, and it's therefore possible that something unintentionally broke that impacted Site Kit setup. 

I'm uncertain if at any stage were subdomain sites added. Regardless subdomains are being retired from the AdSense platform as of next week anyway.
