### ISSUE TITLE
Show Idea Hub context for post based on Idea Hub idea in WordPress block editor / Gutenberg

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3272] opened 2021-05-03 21:49 UTC
The WordPress block editor (Gutenberg) should indicate if the current post is a draft based on an Idea Hub idea.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When editing a WordPress post that has Idea Hub idea metadata set in the block editor (Gutenberg), a notice [like in this Figma file](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=289%3A2479) should be displayed on top of the editor.
    * The copy used should actually differ from the Figma design and say: _This post was created from an idea you picked in Site Kit's Idea Hub: {idea}_ The bold "Google Site Kit" prefix from the Figma design should not be included.
    * The notice should be dismissible. When dismissed, that dismissal should be cached temporarily for an hour, it doesn't need to be persistently stored. Editing a particular post doesn't happen all the time, and it's okay to remind the user again if they open the same post in the editor after a while.
    * This functionality should rely on the [Gutenberg Notice API](https://developer.wordpress.org/block-editor/reference-guides/components/notice/).
    * The entire integration should be implemented in a separate JS file that is loaded only in the block editor (from the `Idea_Hub` class in PHP), if necessary for the current post. Other than typical for Site Kit JS code, the code here should actually rely on WordPress's included versions of `@wordpress/*` dependencies (e.g. reference `wp.data` instead of `@wordpress/data`, and include `wp-data` in the dependencies for the asset in PHP) and not come with any of our own bundled dependencies, to not double-load dependencies and minimize the footprint in the block editor.

#### PHP

* Edit the `Asset` class: 
  * Add the following constants to the class:
    * `CONTEXT_ADMIN_GLOBAL = 'admin-global'`
    * `CONTEXT_ADMIN_POST_EDITOR = 'admin-post-editor'`
    * `CONTEXT_ADMIN_POSTS = 'admin-posts'`
    * `CONTEXT_ADMIN_SITEKIT = 'admin-sitekit'`
  * Add `'load_contexts' => array( self::CONTEXT_ADMIN_SITEKIT ),` to the array of default values for the `$args` property.
  * Add a new public method `has_context( $context )` that returns `TRUE` if the incoming `$context` exists in the `$this->args['load_contexts']` array.
* Update the `enqueue_assets` method of the `Module_With_Assets` interface to accept `$context = Asset::CONTEXT_ADMIN_SITEKIT` argument.
* Edit the `enqueue_assets` method of the `Module_With_Assets_Trait` trait to have the same new `$context = Asset::CONTEXT_ADMIN_SITEKIT` argument and to filter out assets that don't have provided context before enqueueing assets.
* Add a new hook for the `enqueue_block_editor_assets` action in the `Assets::register` method to enqueue registered gutenberg assets. Use `Assets::get_assets()` method to return registered assets and filter out assets that don't support the `CONTEXT_ADMIN_POST_EDITOR` context.
* Edit the `Idea_Hub::setup_assets` method to define a new Script for the `dist/js/googlesitekit-idea-hub-notice.js` with the `CONTEXT_ADMIN_POST_EDITOR` context and `wp-data` as a dependency.

#### JS

* Create `assets/js/googlesitekit-idea-hub-notice.js` which has the `showIdeaHubNotice` function and the file which will be enqueued in the block editor only.
* Update `webpack.config.js` to add a new entry for the above file similar to `analytics-advanced-tracking`.
* The `showIdeaHubNotice` function should do the following:
    * Check if the current post has idea hub metadata via the `getEditedPostAttribute` selector of `core/editor` data store. As per the IB, `wp.data` should be used. For e.g:
        ```js
        const postMeta = wp.data.select( 'core/editor' ).getEditedPostAttribute( 'meta' );
        ```
    * The following meta keys should be present and not empty to identify an idea hub post:
        * `googlesitekitpersistent_idea_name`
        * `googlesitekitpersistent_idea_text`
        * `googlesitekitpersistent_idea_topics`
    * Import the `setItem` and `getItem` from `assets/js/googlesitekit/api/cache.js`.
    * Use the `getItem` function to check if there is an item in local storage with the key `modules::idea-hub::dismissed-editor-notice-<post_ID>` where `<post_ID>` is the ID of the currently edited post. To get the current post ID, query the `core/editor` data store via the `getCurrentPostId` selector.
    * If `cacheHit` is `false` from the result of `getItem`, then the user has not dismissed the notice. The [Gutenberg notice API](https://developer.wordpress.org/block-editor/reference-guides/data/data-core-notices/) will be used to display the notice but the `onDismiss` callback did not work until [recently](https://github.com/WordPress/gutenberg/issues/31571). To circumvent that, we can create listen to data store changes checking whether the notice is still present on the page or has been dismissed.
    * To display the notice:
        * Use the [Gutenberg notice API ](https://developer.wordpress.org/block-editor/reference-guides/data/data-core-notices/)to create an info dismissable notice as per the designs in Figma by using the `createInfoNotice` action of the `core/notices` data store. For e.g:
        ```js
        wp.data.dispatch( 'core/notices' ).createInfoNotice( 'My custom notice', options ); // options is an object
        ```
        * The text for the notice should be as per the second bullet point from the AC where `{idea}` is the value from the post meta with the `googlesitekitpersistent_idea_text` key.
        * The `id` of the notice should be `googlesitekit-idea-hub-notice`.
        * Since we want to know when the user dismisses the notice and the `onDismiss` property does not work, listen to the data store to see if the notice is still present.
            * Define a function, `hasNotice` which returns `true` if the notice id defined in the previous bullet point is in the list of notices. To get the list of notices, use the `getNotices` selector of the `core/notice` data store.
            * Define another function, `handleDataChange` change, which checks whether `hasNotice` returns `true`. If this is the case, then the notice is currently being displayed on the page. If `hasNotice` returns `false`, this means that the user has dismissed the notice. In that case, do the following:
                * Use the `setItem` to set the key `modules::idea-hub::dismissed-editor-notice-<post_ID>` to have `true` as value.
                * We can only pass the `key` and `value` parameters to the `setItem` function since the default parameters set the expiry for the item in local storage to 1 hour.
            * Listen to the changes to the data store using the `subscribe` function of `wp.data`, passing `handleDataChange` as parameter. The `subscribe` function returns a unsubscribe function used to stop the subscription. This should occur in the `handleDataChange` function when `hasNotice` returns `false`.
    * If `cacheHit` is `true` from the result of `getItem`, do not do anything. It means that the user has seen the notice and dismissed it in the past hour.

* POC for listening to data changes: https://github.com/google/site-kit-wp/issues/3272#issuecomment-865895705

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief

**To the engineer writing the QA Brief:** Similar to #3271, this issue should be testable by our QA team and not require `QA: Eng`. Include a sample datastore call to do in the browser console (e.g. `window.googlesitekit.data.dispatch( 'modules/idea-hub' ).createIdeaDraftPost( ... )`) so that a draft post is created that can then be checked.

* 

## Changelog entry

* Add the Idea Hub notification to the WordPress block editor

**Comment by asvinb** [comment] 2021-05-06 13:13
@felixarntz @aaemnnosttv  A couple of things I caught out when working on this IB:

1. The `Google Site Kit` text is bold as per the designs, and in order to achieve that, we need to use the `unstableHTML` property in the options to create a notice.
2. The `Google Site Kit` text has some margin right applied to it in the designs. In order to achieve that, either we add some inline styles and wrap the text between `span` or we add a custom class name and then load a stylesheet which contains the styles for the class name. I think it might be overkilled to do that, and to instead just use the normal spacing between the words and use ":" maybe to separate "Google Site Kit" from the other text.
3. The background color for the info notice should be blue as per https://developer.wordpress.org/block-editor/reference-guides/components/notice/ and the designs. However when I tested using the latest WordPress release, the background for the info notice was white. Not sure if something has changed and the docs are not up to date. 
![image](https://user-images.githubusercontent.com/31818/117303854-37d18880-ae8e-11eb-815f-2eb42d90eedb.png)

**Comment by felixarntz** [comment] 2021-05-06 15:36
@asvinb Thanks for raising these points, it leads me to question a little bit the wording we use here in the first place.

@marrrmarrr Is the wording like we have it [in this Figma design](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=289%3A2479) really what we should have here? The primary concern is that this doesn't use proper language while typical WordPress notices do, i.e. full sentence (e.g. `This draft post was created based on the Site Kit idea "..."`). Could we adjust this to be 1-2 sentences instead of what it currently is?

**Comment by marrrmarrr** [comment] 2021-05-14 16:34
@felixarntz the wording in Figma is not final, it was purely to help explain the flows, and definitely open to edits. 
We could change this to be more descriptive, e.g. "This draft post was created from an idea you picked in Site Kit's Idea Hub: <idea text>"
We could keep the idea text on a new line for clarity. LMKWYT.

**Comment by felixarntz** [comment] 2021-05-14 17:05
@marrrmarrr Sounds good, with just one remark: Let's use just "This post..." instead of "This draft post..." so that it also works for published posts based on an Idea Hub idea.

@asvinb Can you update the relevant bits of the IB accordingly? In the future, to simplify this I'd recommend to not re-phrase exact wording and rather say "the copy from the ACs" or "the copy from the Figma design" or so.

**Comment by asvinb** [comment] 2021-05-17 07:49
Sounds good @felixarntz . Thanks!

**Comment by eugene-manuilov** [comment] 2021-05-18 17:50
Thanks, @asvinb. IB looks solid overall, as usual, but I have two comments for you:

> Edit includes/Modules/Idea_Hub.php to load dist/js/googlesitekit-idea-hub-notice.js using the enqueue_block_editor_assets hook and having wp-data as dependency.

I think we need to introduce a new approach of enqueueing Gutenberg-related assets that will follow the similar logic that we use for regular admin assets. Here is what we need to do:

1. Create a new interface `Module_With_Gutenberg_Assets` that replicates the `Module_With_Assets` interface but uses `*_gutenberg_assets` instead of `*_assets` method names.
1. Create a new trait `Module_With_Gutenberg_Assets_Trait` that replicates the `Module_With_Assets_Trait` trait and also uses `*_gutenberg_assets` instead of `*_assets` method names.
1. Update the `Idea_Hub` class to implement the `Module_With_Gutenberg_Assets` interface and use the `Module_With_Gutenberg_Assets_Trait` trait.
1. Add a new protected method `setup_gutenberg_assets` to the `Idea_Hub` class which should return an array of Script objects (in our case it will be an array with a single Script for the new `googlesitekit-idea-hub-notice.js` script).
1. Add a new private method `get_gutenberg_assets` to  the `Assets` class that applies a new filter `googlesitekit_gutenberg_assets` on an empty array and returns returned results from the filter call.
1. Update the `Assets::register_assets` method to register gutenberg assets as well using the new `get_gutenberg_assets` method to get gutenberg scripts.
1. Add a new hook for the `enqueue_block_editor_assets` action in the `Assets::register` method to enqueue registered gutenberg assets.
1. Add a new hook for the `googlesitekit_gutenberg_assets` filter that copies the logic used for `googlesitekit_assets` but calling Gutenberg related methods: https://github.com/google/site-kit-wp/blob/1181d49b512d3fb79ebd6ff858a96db32197fd12/includes/Core/Modules/Modules.php#L217-L227

cc @felixarntz @aaemnnosttv in case you want to add or change something

> Check if there is the googlesitekit-idea-hub-notice-<post_ID> cookie set via the js-cookie package where <post_ID> is the ID of the currently edited post

Let's use the localStorage instead of cookies.

**Comment by felixarntz** [comment] 2021-05-19 16:22
@eugene-manuilov +1 for the suggested approach!

We can later also consider implementing similar infrastructure for any frontend assets (which we'll need for some future functionality that has been discussed in the past).

**Comment by aaemnnosttv** [comment] 2021-05-20 08:10
@eugene-manuilov I'm not sure we should replicate `Module_With_Assets` with a Gutenberg-specific variant. That would certainly work, but Gutenberg assets are still assets so to me these should be returned with all the other assets. Maybe instead we should add a way to guard (or otherwise control) assets from being enqueued based on the context?

**Comment by eugene-manuilov** [comment] 2021-05-20 08:45
@aaemnnosttv yes, we can add a context (`'admin'`, `'gutenberg'`, `'frontend'`) parameter to the get_assets function and return a specific set of assets based on provided context, but I think it would be better if separate concerns because it will be easier to understand, test and maintain.

**Comment by asvinb** [comment] 2021-05-20 09:20
@eugene-manuilov IB updated to use localStorage instead of cookies. Once @aaemnnosttv, @felixarntz  and you are aligned on the way to enqueue Gutenberg assets, I'll update the IB with your approach.

**Comment by felixarntz** [comment] 2021-06-15 18:20
@eugene-manuilov @aaemnnosttv Enhancing `Module_With_Assets` to support different contexts makes sense to me. Let's do the following:
* Enhance `Google\Site_Kit\Core\Assets\Asset` to have a new `$load_context` field (string), with "admin-sitekit" being the default (indicates that the asset should be loaded on Site Kit admin screens).
* Enhance `Google\Site_Kit\Core\Modules\Module_With_Assets` (and its trait) so that both `get_assets` and `enqueue_assets` support an optional `$load_context` parameter, that also relies on "admin-sitekit" as default. The trait should be adjusted so that the two method implementations then consider only the assets that use the specified `$load_context`.
* The individual `setup_assets` implementations don't need to be updated (since they all implicitly use "admin-sitekit"), but now it is possible to specify alternative load context values, which is what's needed here.

For now, let's specify the following load context values:
* `admin-general` (throughout the entire admin): `googlesitekit-base` only should rely on this
* `admin-sitekit` (default: any primary Site Kit area, including admin bar): relevant for all existing Site Kit assets
* `admin-post-edit` (Gutenberg / block editor): relevant for this issue
* `admin-posts` (admin posts list table, i.e. `wp-admin/edit.php`); relevant for #3359

Let me know if this sounds good to you, if so we can proceed with the IB.

**Comment by aaemnnosttv** [comment] 2021-06-16 08:34
@felixarntz that sounds good to me for the most part, although I think each `Asset` needs to support multiple contexts – e.g. `admin-sitekit, admin-posts`.

Also, maybe `admin-general` might be more clear as `admin-global`?

**Comment by eugene-manuilov** [comment] 2021-06-16 13:10
@felixarntz yes, that sounds good to me too, plus I second Evan that assets need to support multiple contexts. :+1:

**Comment by felixarntz** [comment] 2021-06-16 20:58
@aaemnnosttv @eugene-manuilov I agree with both of your points, let's support multiple contexts, and use `admin-global` instead of `admin-general`.

@asvinb I've updated https://github.com/google/site-kit-wp/issues/3272#issuecomment-861730783 with the additional modifications, so you should now be able to continue the IB following that comment.

**Comment by eugene-manuilov** [comment] 2021-06-17 12:53
@felixarntz @aaemnnosttv IB is updated. Do you mind reviewing it?

**Comment by eugene-manuilov** [comment] 2021-06-17 17:19
@aaemnnosttv I have updated IB based on your comments except the last one.

> Unfortunately, this option does not work for info notices although it was just recently fixed (see WordPress/gutenberg#31571). onDismiss was not part of the original API for core/notices either, and was added in v2.x of the library (not sure exactly what version of WP this correlates to but it seems like it may have been added as recent as 5.7 – added in Gutenberg in Dec 2020. Not sure what the best solution here, but I don't think we can rely on options.onDismiss.

@asvinb could you please take a look at it and update your portion of IB?

**Comment by asvinb** [comment] 2021-06-18 08:36
@aaemnnosttv The cache key name has been updated. You're right about the `onDismiss` property 😞 It does not work. I'am thinking whether we should just listen to the click event of the button to dismiss the notification and whether the notice content starts with the "This post was created from an idea you picked in Site Kit's Idea Hub:" string since we don't have a way to target the notice that was rendered. There might be several notices on the page and there is no class/id which uniquely identifies each notice.
What do you think?

**Comment by aaemnnosttv** [comment] 2021-06-21 17:09
@asvinb per our conversation, can you take a look and see when the [`__unstableHTML`](https://github.com/WordPress/gutenberg/blob/1074fb3219fcf5f257b9bdeec1a0eb31a6b1ed19/packages/notices/src/store/actions.js#L60) option was added? Maybe we can use this to pass our own content that includes a data attribute we can use for a selector.

As a fallback, if the above isn't available for the event listener option, we should probably treat the notice as dismissed after showing it once.

cc: @felixarntz

**Comment by asvinb** [comment] 2021-06-22 08:57
@aaemnnosttv I checked and the `__unstableHTML` option was added as from v1.1.1 of the package which is around 3 years ago. My worry about the `__unstableHTML` option is that it's not documented anywhere. I'am wondering whether it's safe to use this option 🤔

**Comment by aaemnnosttv** [comment] 2021-06-22 09:31
@asvinb good call – according to Gutenberg developers, this shouldn't be used: https://github.com/WordPress/gutenberg/pull/11604#issuecomment-456468735

Let's see how we can do this without that 👍

**Comment by aaemnnosttv** [comment] 2021-06-22 11:17
@asvinb let's not manually insert the notice into the DOM, as this would violate this condition of the ACs:
_This functionality should rely on the Gutenberg Notice API._

After thinking about this a bit more, I think we can still leverage the datastore for knowing when the notice is dismissed after it's added. We can do this by subscribing a listener on `wp.data` which will be called each time the state changes (this is what `useSelect` and other reactive parts use internally as well). The notices API supports adding a notice with an `id`, which although isn't used in the DOM, is used in the notices internal state. Using this ID (we give it), we can check to see if the notice is still present or not, and since our subscribed function will be invoked on every change to the datastore, we'll know right away as soon as it's removed.

Here's a POC

![image](https://user-images.githubusercontent.com/1621608/122915015-f32d7e00-d363-11eb-9050-cf32b323ee22.png)

The only thing missing here is unsubscribing the listener once we no longer need it (the `unsubscribe` function is returned from [`subscribe()`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#subscribe)).

All of this should be available going back to the [initial `core/notices` package](https://github.com/WordPress/gutenberg/commit/cad4c05e29def06fb624e7e224a2e4aaf9d6a392).

**Comment by aaemnnosttv** [comment] 2021-06-22 14:33
Thanks @asvin, I think we're just about good to go.

> The `id` of the notice should be `googlesitekit-idea-hub-notice-<post_ID>` where `<id>` is the post ID.

Including the post ID in the `id` of the notice is unnecessary since these aren't persisted, so it's inherently scoped to the current post. It is important to include in the key that we cache, because that is of course global to the whole site.

So unless it is important for some reason to include the `<post_ID>` in the notice `id`, then let's remove that part the `id`.

Otherwise this is IB ✅ and can be moved forward without further review.

**Comment by asvinb** [comment] 2021-06-22 14:43
Sounds good @aaemnnosttv . IB updated.

**Comment by cole10up** [comment] 2021-07-09 08:07
### **QA ✅**

Confirmed the idea hub banner is displayed on a Gutenberg post in draft mode.

![image](https://user-images.githubusercontent.com/57115907/125045278-ab8c3f00-e051-11eb-8ab4-d7f90bea1f9b.png)

Was able to close the banner properly and confirmed the dialogue is correct.

One thing I noticed is the banner doesn't come back if the user closes it, leaves the drafted post without saving any edits then navigates back into the draft. 

Moving to approval.

**Closed** 2021-07-15 19:13 UTC
Labels: Module: Analytics, P0, Rollover, Type: Enhancement
