### ISSUE TITLE
Include referrers within site overview and page reports

### ISSUE THREAD

**Issue by lightson** [google/site-kit-wp#761] opened 2019-11-01 15:15 UTC
## Feature Description

When viewing either the Site Overview or detailed page stats, it'd be great if a referrers table was also displayed showing webpages that referred to the site/page within the selected time frame.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment] 2021-04-05 19:26
Duplicate of #36 (now being tracked via #3052)

**Closed by felixarntz** 2021-04-05 19:26 UTC
Labels: Type: Enhancement
