### ISSUE TITLE
Update tailored metrics to also include new ACR metrics

### ISSUE THREAD

**Issue by zutigrm** [google/site-kit-wp#9437] opened 2024-09-30 10:56 UTC
## Feature Description

Accompanying the update to the KMW area to support up to 8 metric widgets, tailored metrics included based on the site purpose answer, will also be expanded to include ACR metric widgets.

See [ACR tailored metrics based on the site purpose answer](https://docs.google.com/document/d/1JvA3LK5SNfGH2o4OVnwjDdsAFuQMA9ZJj0T09RTqoy8/edit?pli=1&resourcekey=0-e90bcFGzAI6NhNu_D5i6hQ#heading=h.4xwyivtn05ig) section in the design doc

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Given the ACR feature is enabled, when a user answers the User Input questionnaire, then the answer-based tailored metrics selected for the user should be 8 (instead of the usual 4 when ACR is not enabled).
* The new set of 8 tailored metrics for each answer is given in the table below. Note that these include a mix of old and new metrics:
  *  ![Image](https://github.com/user-attachments/assets/b85c913d-387e-4ef3-83ec-c2e53109e444)
* If the KMW was already set up by the user and then the ACR feature is enabled, then the answer based metrics returned should not change (the original set of 4 metrics should persist).

## Implementation Brief

* [x] Update `includes/Core/Key_Metrics/Key_Metrics_Settings.php`
  * Add new setting to the list `includeConversionTailoredMetrics`, `false` by default
    * This setting will be used to confirm that existing user who has tailored metrics setup, will not see ACR widgets automatically as soon as the new events are detected
* [x] In `assets/js/googlesitekit/datastore/user/key-metrics.js`
  * Update `getAnswerBasedMetrics` selector
    * Expand on the existing metrics by assigning ACR metrics under their respective site purpose answer, following the list provided in the AC. Each new group of ACR metrics should be conditionally added to the existing list, if either `includeConversionTailoredMetrics` KMW setting is `true` OR if user input is completed - retrieve this value from `isUserInputCompleted` selector from `CORE_USER` datastore.
      * This will ensure that ACR widgets are included if it is a new KMW setup using user input

### Test Coverage

* Update `assets/js/googlesitekit/datastore/user/key-metrics.test.js`
  * Specifically expand on tests for `getAnswerBasedMetrics` selector to include ACR metrics
* Update `tests/phpunit/integration/Core/Key_Metrics/Key_Metrics_SettingsTest.php` , expand on settings list to include new setting

## QA Brief

**Note**: For the latest follow up, verify that when feature flag is disabled, only 4 old tailored metrics are showing
* Setup Site Kit with Analytics module and `conversionReporting` feature flag enabled
* Setup Key Metrics, using `tailored metrics` option
* Verify that selected site purpose answer matches the tailored metrics from the AC list
* Go to `Serttings > Admin Settings` and under key metrics settings section, edit the site purpose answer, and verify that for each answer tailored metrics list is matching the ones in AC table
* Note: one exception is that `Top device driving purchases` KMW is not yet merged in the codebase, so it will be missing from the list at this time

## Changelog entry

* Update tailored metrics to also include new ACR metrics.

**Comment by 10upsimon** [comment] 2024-09-30 14:50
@zutigrm AC looks good to me, moving to IB.

**Comment by 10upsimon** [comment] 2024-10-02 13:28
@zutigrm IB ✅ Moving to EB

**Comment by 10upsimon** [comment] 2024-10-03 12:06
@zutigrm IB ✅ Moving to EB

**Comment by jimmymadon** [comment] 2024-10-09 19:35
@10upsimon @zutigrm I feel, the `includeConversionTailoredMetrics` is a "Key Metrics" specific setting used only to include tailored metrics or not. As such, it might be better placed in the `Key_Metrics_Settings` class instead of GA4 settings which contain settings specific to Google Analytics within SK.

This isn't a big deal but I've updated the IB here for this after speaking to @10upsimon and having another look at the existing settings in both classes.

**Comment by jimmymadon** [comment] 2024-10-09 20:08
@andreylipattsev @sigal-teller Currently, we have 4 "answer-based" metrics selected depending on the answer that a user selects to the User Input Questionnaire. These are listed below.

<Details>
<Summary>Existing Answer Based Metrics</Summary>

  * `Publish a blog`
    * Returning visitors
    * New visitors
    * Top traffic source
    * Most engaged traffic source
  * `Publish news content`
    * Pages per visit
    * Visit length
    * Visits per visitor
    * Most engaging pages
  * `Share a business card or portfolio to represent me or my company online` or `Other`
    * New visitors
    * Top traffic source
    * Most engaged traffic source
    * Top performing keywords
  * `Sell products or services`
    * Popular products (or Popular content if product post types aren't tracked)
    * Most engaged traffic source
    * Top performing keywords
    * Top traffic source
  * `Monetize content`
    * Popular content
    * Most engaged traffic source
    * New visitors
    * Top traffic source
</Details>

I just wanted to flag a few things as per the current ACs which include new ACR widget tiles:
1. There is a varying number of tiles being added. This seems to be fine but just wanted to make sure this is good UX and we are consciously making this decision. Some users will end up with 6 tiles and some will end up with more.
2. The `Sell products or services` section is containing 5 new ACR tiles. This would make the total 9 and that will be a problem as we want to allow only 8 in total. We can remove one of the old tiles here but for a user that already has KMW setup, they will end up having an existing tile changed! So should we stick to just 4 new tiles or remove an older one? Which final 8 should make the cut here?
3. The `Monetize content` answer has no new ACR tiles added. Which new ACR tiles should be added if this option were to be selected?

**Comment by jimmymadon** [comment] 2024-10-10 17:37
@10upsimon I have updated the ACs as per the discussion in [this Slack thread](https://fueled10up.slack.com/archives/CFFRMC5DE/p1728504744260639) and after @andreylipattsev consequently updated the [Key Metrics Mapping](https://docs.google.com/spreadsheets/d/1Fvr1xryK-yePIcdAj_iZlMx8k6bETGAtVyH3B4NHXP8/edit?gid=1777331786#gid=1777331786).

**Comment by 10upsimon** [comment] 2024-10-11 05:39
Thanks @jimmymadon I noticed the IB still references GA4 settings instead of KMW settings:

> Each new group of ACR metrics should be conditionally added to the existing list, if either includeConversionTailoredMetrics GA4 setting is true OR if user input is completed 

For the sake of time, I am going to update that and approve so long.

**Comment by 10upsimon** [comment] 2024-10-11 05:40
@jimmymadon AC & IB ✅ moving to EB, cc @zutigrm

**Comment by kelvinballoo** [comment] 2024-10-14 13:46
### QA Update ⚠ 

@benbowler , I'm trying to set up a site for the first time and selected the main purpose of the site as 'Publish a blog'

Based on the AC table, the metric tabs should be starting with 'Top categories by pageviews', 'Top converting traffic source', etc...
But current implementation has it as 'New visitors', Returning visitors', etc...
The tiles are not the same/in order and also, there are only 6 that appear. I was expecting 8.
<Details>
AC order:
![Image](https://github.com/user-attachments/assets/a07616d4-973e-41bb-84a2-e9259cddf949)

Current implementation:
![Image](https://github.com/user-attachments/assets/f76aed46-3b73-4455-868d-732bf56864d0)


![Image](https://github.com/user-attachments/assets/8956aed2-464d-4400-adad-334160314806)

VIDEO:

https://github.com/user-attachments/assets/18924398-c3fd-435e-82b8-f11848a09615


</Details>

**Comment by benbowler** [comment] 2024-10-14 14:58
Thanks @kelvinballoo, taking this back into execution to update the list of metrics to match the AC and update the logic to ensure that the metric order matches the sheet.

**Comment by benbowler** [comment] 2024-10-15 09:02
Note for @kelvinballoo during QA, the list of metrics for each survey setting should not match the image in the ticket:

![Image](https://github.com/user-attachments/assets/b85c913d-387e-4ef3-83ec-c2e53109e444)

*Note: the KM_ANALYTICS_TOP_DEVICE_DRIVING_PURCHASES metrics is not yet implemented so when sell_products_or_service is selected there will only be 7 widgets shown.*

Also @zutigrm has confirmed in Slack that the order of the widgets shown in the Key Metrics section is not important as long as they are all there.

**Comment by kelvinballoo** [comment] 2024-10-16 07:59
### QA Update ✅ 

Verified for each metric/site type, the Key metrics appear accordingly:

- Publish Blog
   <Details>

   ![Image](https://github.com/user-attachments/assets/a85e35a7-dac8-4c53-8ffc-683c3796140d)

   ![Image](https://github.com/user-attachments/assets/ff2a6623-f062-4d54-b1c7-733c5fba824b)

   </Details>

- Publish News
   <Details>

   ![Image](https://github.com/user-attachments/assets/ac32ea10-2272-4542-ab1f-917645cf5473)

   ![Image](https://github.com/user-attachments/assets/92cda972-e92c-49d9-8abc-bfc5235c05f3)

   </Details>
- Monetize content
   <Details>

   ![Image](https://github.com/user-attachments/assets/f389d273-3e1b-4428-8cfb-fd4078b0790c)

   ![Image](https://github.com/user-attachments/assets/d02e994b-20ec-4f4f-8fd8-791166470ab0)

   </Details>
- Portfolio site/other default
   <Details>

   ![Image](https://github.com/user-attachments/assets/55412ade-4422-4061-ab7a-7dcc05db808f)

   ![Image](https://github.com/user-attachments/assets/9465c4e8-1b16-492b-b94e-f5e54a8d160b)

   </Details>
- eCom
   <Details>

   ![Image](https://github.com/user-attachments/assets/cedfd39a-cc4b-40da-a814-4937cf572c17)

   ![Image](https://github.com/user-attachments/assets/8881ff76-2a77-4678-814b-6b1589a9accb)

   </Details>

- If the KMW was already set up by the user and then the ACR feature is enabled, then the answer based metrics returned does not change (the original set of 4 metrics persists).
   <Details>

   https://github.com/user-attachments/assets/45b545aa-9dda-4bef-96e3-71f07c4b8373

   </Details>

**Comment by techanvil** [comment] 2024-10-16 12:04
Hey @benbowler, as per my [comment](https://github.com/google/site-kit-wp/pull/9509#issuecomment-2416620058) on the PR, the followup PR has caused the `assets/js/googlesitekit/datastore/user/key-metrics.test.js` suite to fail.

Please can you raise another followup to fix the tests?

**Comment by techanvil** [comment] 2024-10-16 15:39
Having merged the followup PR and confirmed all JS tests pass in `main` post-merge, I'm moving this back to Approval.

![Image](https://github.com/user-attachments/assets/34f5afb2-a4a8-46c4-82d7-ef2559006f08)

**Comment by zutigrm** [comment] 2024-10-17 13:28
Moving it back to execution, as we need to guard new list of tailored metrics with feature flag, it seems I forgot to include it in AC as well. I will quickly add a follow up

**Comment by wpdarren** [comment] 2024-10-17 17:53
### QA Update: ✅ 

**Verified:**

- Tested that more than 4 tiles appear before refreshing the main branch when the `conversionReporting` feature flag is not enabled.
- When I refreshed the main branch, only 4 key metric tiles appear when the `conversionReporting` feature flag is not enabled.  
- Quickly tested that when `conversionReporting` is enabled then the 8 key metric tiles appear. 

<details>
 <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/16bc04a7-a51f-4daf-a26f-c1f7ef5e5a47)
![Image](https://github.com/user-attachments/assets/1ed36b62-a1cc-43e0-9be2-7fe436157cc8)
![Image](https://github.com/user-attachments/assets/6f363087-f177-46ee-b57e-969e4c600cdc)

</details>

**Comment by tofumatt** [comment] 2024-10-17 21:06
Moving this back to Execution to fix unit test failures.

**Comment by tofumatt** [comment] 2024-10-17 21:27
Just needed a unit test tweak, no user-facing change has been made so moving back to Approval.

**Closed** 2024-10-18 17:08 UTC
Labels: P0, Type: Enhancement, Team S
