### ISSUE TITLE
Display total number of connected users within Site Health information

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1556] opened 2020-05-14 14:45 UTC
## Feature Description

Along with the existing Site Kit information that is contained within a users Site Health info display the total number of users connected.

Along with assisting in supporting users this may prove useful for site owners, who might like to keep track of what other administrators have signed in and availed of the dashboards and metrics. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by felixarntz** [comment] 2021-01-20 21:36
Duplicate of #1932.

**Closed by felixarntz** 2021-01-20 21:36 UTC
Labels: Type: Enhancement
