### ISSUE TITLE
Implement gathering data state for custom dimensions

### ISSUE THREAD

**Issue by nfmohit** [google/site-kit-wp#7638] opened 2023-09-28 20:24 UTC
## Feature Description

After creating custom dimensions as a part of [#7599](https://github.com/google/site-kit-wp/issues/7599) and [#7601](https://github.com/google/site-kit-wp/issues/7601), Google Analytics needs adequate time to gather sufficient data for those custom dimensions to show reports in metrics dependent on those custom dimensions. These metric tiles should show a gathering data state when this data is being gathered.

[See relevant section in design doc](https://docs.google.com/document/d/1htqStvvyXq_eg5GsHSbdBBgm4Tu_Z6KXsIOBfjWQ5oM/edit?resourcekey=0-Px-yDiCQOTz30DBKllhU3g#heading=h.of5xn635lzqj).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The key metric tiles that depend on one or more custom dimensions for their reporting should have a gathering data state implemented that lets the user know that Analytics is gathering data for a respective metric tile.
- The gathering data state should look like the existing "zero data" state of key metric tiles with the copy changed. Screenshot for reference:
![image](https://github.com/google/site-kit-wp/assets/20284937/920fabef-1d2e-4a27-8928-75883e1f24d2)
- The copy should be: `Setup successful: Analytics is gathering data for this metric`
- A key metric tile should be in a gathering data state based on the following conditions:
  - If the `analytics-4` module itself is in a gathering data state; or
  - If the required custom dimensions for the metric tile do not have any data collected yet.

### Backend

* Add `includes/Modules/Analytics_4/Custom_Dimensions_Data_Available.php` class
  * Use [`Module_With_Data_Available_State_Trait`](https://github.com/google/site-kit-wp/blob/c6325c0c86773fb83ba643538eea4d4c02cf302f/includes/Core/Modules/Module_With_Data_Available_State_Trait.php#L20) as a starting point, transient name should be `googlesitekit_{customDimensionName}_data_available`, and methods should accept `customDimensionName` as parameter.
* For custom dimension data to be available on load, it can be included as part of `_googlesitekitModulesData` global
  * In `Analytics_4` class, hook into `googlesitekit_inline_modules_data` filter, similar to how it is done in [Modules](https://github.com/google/site-kit-wp/blob/c6325c0c86773fb83ba643538eea4d4c02cf302f/includes/Core/Modules/Modules.php#L293), and add new method `inline_custom_dimensions_data`, which should be used as a callback
  * Within the `inline_custom_dimensions_data` method, return a multidimensional array with the key `customDimensionsDataAvailable`. This key should map to an array of custom dimension names. For each name, use the name as a key, and pair it with the result of the `is_data_available(dimension_name)` call as its value.
  * Custom dimension data should be grouped under `analytics-4` key so it can be distinguished from other general module data, so structure of `_googlesitekitModulesData` would look like this: 
```js
{
  // previously hooked data
  'data_available_analytics': true,
  'data_available_analytics-4': false,
  // etc
  // data returned by inline_custom_dimensions_data method
  'analytics-4': {
    'customDimensionsDataAvailable': {
      googlesitekit_post_date: true,
      googlesitekit_post_author: false,
      // etc
    }
  }
}
```

* In the `includes/Modules/Analytics_4.php` 
  * Include `Custom_Dimension_Data_Available` class
  * add `POST:custom-dimension-data-available` route 
    * To the `get_datapoint_definitions`, hidden behind `newsKeyMetrics` feature flag. No `service` or `scopes` are needed, although it should be `sharable`
    * To the `create_data_request` method. Use `set_data_available` method of `Custom_Dimension_Data_Available` class for setting the data
  * To support data reset on property change, hook into `update_option_googlesitekit_analytics-4_settings` to detect `propertyID` changes, similarly how it is done for [modules](https://github.com/google/site-kit-wp/blob/c6325c0c86773fb83ba643538eea4d4c02cf302f/includes/Modules/Analytics_4.php#L113-L123)
    * Call `reset_data_available` method of `Custom_Dimensions_Data_Available` for each dimension when the change is detected

#### Data Store
* Create a new custom dimensions gathering data store, similar to what is returned by [`createGatheringDataStore`](https://github.com/google/site-kit-wp/blob/c6325c0c86773fb83ba643538eea4d4c02cf302f/assets/js/googlesitekit/modules/create-gathering-data-store.js), but specific to the `analytics-4` module.
  * This should be created in `assets/js/modules/analytics-4/datastore/custom-dimensions-gathering-data.js`.
  * `createFetchStore` can use `custom-dimension-data-available` for `datapoint`
    * Include the custom dimension parameter name in API, eq `customDimensionName`, so it will be sent to the backend, and tied to the transient name
  * For `initialState` you can include `customDimensionsGatheringData` object with the list of available custom dimensions names 
    * They are currently not exported, so move them from [here](https://github.com/google/site-kit-wp/blob/c6325c0c86773fb83ba643538eea4d4c02cf302f/assets/js/modules/analytics-4/datastore/custom-dimensions.js#L47) under [constants](https://github.com/google/site-kit-wp/blob/c6325c0c86773fb83ba643538eea4d4c02cf302f/assets/js/modules/analytics-4/datastore/constants.js) so they can be shared across the files.
  * Add `customDimensionsDataAvailableOnLoad` that will hold the global data availability:
```js
const initialState = {
  customDimensionsGatheringData: {
    googlesitekit_post_date: undefined,
    googlesitekit_post_author: undefined,
    // etc
  },
  customDimensionsDataAvailableOnLoad:
    global._googlesitekitModulesData?.['analytics-4']?.customDimensionsDataAvailable,
};
```
  * Include `isGatheringCustomDimensionData` resolver and selector (similar to how `isGatheringData` one works), but they should accept `customDimensionName` param. So when resolver dispatches fetch action it will save `customDimensionName` transient and update `customDimensionsGatheringData[ customDimensionName ]` state, and selector will return proper dimension name from the state.
  * So data can be accessible with `.isGatheringCustomDimensionsData( customDimensionName )` on `analytics 4` store
  * `isDataAvailableOnLoad()`, `receiveIsGatheringData()`, etc should also accept `customDimensionName` param so they can access proper dimension name from `customDimensionsGatheringData` state, and `customDimensionsDataAvailableOnLoad `
* Include new gathering data store to `assets/js/modules/analytics-4/datastore/custom-dimensions.js` introduced in [#7598](https://github.com/google/site-kit-wp/issues/7598)
* `selectDataAvailability` ([re-use what is needed from here](https://github.com/google/site-kit-wp/blob/9c5f9dc6714c657488ae99a9d193d12bfba8fa4c/assets/js/modules/analytics-4/datastore/report.js#L164)), should be modified in the following way:
  * It should check if custom dimension is available via `.hasCustomDimensions` selector - introduced in [#7598](https://github.com/google/site-kit-wp/issues/7598) 
  * Check for property creation date ([example](https://github.com/google/site-kit-wp/blob/e9a4baa675590329a511dfc514c18702f8ea6e9a/assets/js/modules/analytics-4/datastore/report.js#L201-L219))
  * Check if sample report has data, modify the report options to include `customEvent:<parameter name>` for dimension and no metrics are needed ([example](https://github.com/google/site-kit-wp/blob/e9a4baa675590329a511dfc514c18702f8ea6e9a/assets/js/modules/analytics-4/datastore/report.js#L169-L177))
  * If the resulting report contains exactly one row, and the dimension value for that row is the special value ["(not set)"](https://support.google.com/analytics/answer/13504892), it means it's still gathering data.
  * Otherwise, data is available and it can return true.

#### Widgets
* Create new gathering data message component for analytics 4, you can re-use part of `assets/js/modules/analytics/components/common/ZeroDataMessage.js` and change the copy as defined in AC
* Modify `Top recent trending pages` ([#7603](https://github.com/google/site-kit-wp/issues/7603)), `Most popular authors by pageviews` ([#7605](https://github.com/google/site-kit-wp/issues/7605)) and `Top categories by pageviews` ([7607](https://github.com/google/site-kit-wp/issues/7607)) to include gathering data conditions as defined in AC, and pass  gathering data message component to `ZeroState` prop of the metric tile, when conditions are met. Otherwise regular `ZeroDataMessage` should still be used.

### Test Coverage

* Add `Gathering Data` story to the edited widgets stories
* Add jest test for new gathering data store, you can re-use some logic from `assets/js/googlesitekit/modules/create-gathering-data-store.test.js`
* Update PHP tests to support new additions
* Update VRT reference images for new gathering data stories

## QA Brief

- Setup Site Kit with the `newsKeyMetrics` feature flag enabled and GA4 connected, and setup Key Metrics.
- For each of the "Top recent trending pages", "Top categories by pageviews" and "Most popular authors by pageviews" widgets, check the gathering data state is shown as per the AC.
  - The gathering data state should be displayed from when the custom dimension for the tile is created, to when there is data available for the custom dimension. The gathering data state uses a report to check for data, so as with any report there will be a delay from the data being tracked to when it's visible in the report. In other words, it'll take a day or so for the custom dimension to get out of the gathering data state assuming the site is receiving traffic (specifically, traffic to individual posts).
- Verify that the first time data _is_ available for a custom dimension, a `POST` request is made to the `custom-dimension-data-available` endpoint with the `customDimension` specified in the payload, e.g.:
![image](https://github.com/google/site-kit-wp/assets/18395600/1de65afa-23ee-471c-8c95-e8e1359529c9)
- On subsequent page loads this endpoint should not be hit.
- Verify that upon changing the measurement ID in settings, or upon disconnecting Analytics, the data availability state is reset. This can be confirmed as follows:
  - First, ensure the custom dimension is not in a gathering data state and the `custom-dimension-data-available` has been hit.
  - Query the options table in the database for the stored transient state. For example, here is the transient state for various custom dimensions on an InstaWP site via the DB web UI:
![image](https://github.com/google/site-kit-wp/assets/18395600/01ec2f60-4bbc-414a-8418-b6393e22cb66)
  - Change the measurement ID or disconnect Analytics.
  - Verify that the stored transient state has been deleted from the DB.

## Changelog entry

* Implement gathering data state for custom dimensions

**Comment by tofumatt** [comment] 2023-10-02 13:09
ACs are good 👍🏻

**Comment by zutigrm** [comment] 2023-10-04 11:21
@marrrmarrr Can you please confirm if suggested copy `No data to display: Analytics is gathering data for this metric` from the screenshot in AC is fine, or should we use something else? Thanks

**Comment by zutigrm** [comment] 2023-10-04 12:19
@marrrmarrr Yes, if custom dimensions creation failed, error would be displayed differently as covered in #7601 . This tile state would come after. 
Noted, will go with `Setup successful: Analytics is gathering data for this metric` in this case.
Thanks

**Comment by nfmohit** [comment] 2023-10-04 12:19
> @nfmohit @zutigrm Is it safe to assume here that if the user is seeing this notice the custom dimension has been successfully set up and it's just a matter of time before stats show up (assuming the site has traffic)?

Hi @marrrmarrr. That is correct. If the user sees this notice, it is safe to assume that custom dimensions have been set up.  Thank you.

Thank you for clarifying @zutigrm!

**Comment by zutigrm** [comment] 2023-10-05 09:01
@nfmohit I updated the copy in AC to the confirmed one.

**Comment by techanvil** [comment] 2023-10-06 11:12
Hi @zutigrm, thanks for drafting this IB. It's a good first effort, but there are a number of aspects that do need addressing.

#### First, some points about clarification and naming

- It's a bit unclear from the IB whether it's proposing to add a new store _creator_ or a new store, but from my read of it, it doesn't look like we need a store creator here as there are no arguments to pass to it. To be honest, I had envisaged that we'd have a store creator which takes a custom dimension parameter name and creates a store that handles that single custom dimension. However, on reflection it does seem we can take a simpler approach and instead provide one store that handles all of the custom dimensions.
- With this in mind, I'd suggest updating the first point as follows. It would also be good to specify where this will be created - when writing an IB, it's useful to be specific about (or at least make suggestions for) locations, interfaces (exported functions, public methods, API endpoint paths/datapoint names etc) and so forth where it helps to provide clarity, while not specifying every last detail of the code to be implemented.
  - _Create a new custom dimensions gathering data store, similar to what is returned by `createGatheringDataStore`, but specific to the `analytics-4` module._
    - _This should be created in `assets/js/modules/analytics-4/datastore/custom-dimensions-gathering-data.js`._
- The point about `moduleSlug` and `storeName` would then be a bit superfluous and can be removed.
- With regard to the point about naming, I'd also suggest going through the IB and providing some names for the other public-facing aspects of the implementation where one is not specced.
- In general the IB refers to "custom dimensions" in the plural, even when referring to a single custom dimension. Please can you update it to refer to a "custom dimension" where it should refer to one custom dimension. For example:
  - `custom-dimensions-data-available` - this should update the `data-available` state for a single custom dimension and should be `custom-dimension-data-available`. The following subpoint should also read "the custom dimension parameter name".
  - `IsGatheringCustomDimensionsData` - this will operate on a single custom dimension - also the initial should be lowercase, so this should read `isGatheringCustomDimensionData`.
  - Please review the IB for any additional updates needed along these lines.
- Rather a minor point but please uppercase initialised abbreviations like API :)

#### Now, some more structural / functional aspects

- With regard to the `initialState` - bear in mind this state will be merged with the `analytics-4` state so it would be a bit easier to manage if we grouped these state items, e.g. `initialState` could take the following shape (bear in mind I've also added state for "data available on load" here which I'll discuss futher below):

```js
const initialState = {
  customDimensionsGatheringData: {
    googlesitekit_post_date: undefined,
    googlesitekit_post_author: undefined,
    // etc
  },
  customDimensionsDataAvailableOnLoad:
    global._googlesitekitAnalyticsData?.customDimensionsDataAvailable,
};
```

- A minor point, but in the definition for `isGatheringCustomDimensionData`, I'm not sure it's correct to say "update/get the state", I don't think we need to do a get here, just update it...
- `selectDataAvailability` needs a bit of attention - this will be called from `isGatheringCustomDimensionData` and should be passed the custom dimension parameter name. AFAICT it should essentially do the following (refer to the GA4 [`selectDataAvailability`](https://github.com/google/site-kit-wp/blob/e9a4baa675590329a511dfc514c18702f8ea6e9a/assets/js/modules/analytics-4/datastore/report.js#L164`) for some relevant detail here):
  - Check if the custom dimension exists.
  - If so, get the creation date for the GA4 property.
  - Fetch a report for the custom dimension, using the date range of the property's creation date to now.
  - Specifically, the report options should specify the dimension `customEvent:<parameter name>` and it does not need to specify any metrics.
  - If the resulting report contains exactly one row, and the dimension value for that row is the special value ["(not set)"](https://support.google.com/analytics/answer/13504892), it means that we are still gathering data.
  - Otherwise, we now have data and can return true.
  - To illustrate, here are a couple of example reports from my testing:

<details>
    <summary>Example reports</summary>

```json
// This is for a custom dimension which _does_ have data:

// Request
{
  "dateRanges": [
    {
      "endDate": "2023-10-04",
      "startDate": "2023-07-07"
    }
  ],
  "dimensions": [
		{
      "name": "customEvent:anotherParam"
    }
  ]
}

// Response
{
	"dimensionHeaders": [
		{
			"name": "customEvent:anotherParam"
		}
	],
	"rows": [
		{
			"dimensionValues": [
				{
					"value": "(not set)"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "another-value"
				}
			]
		}
	],
	"rowCount": 2,
	"metadata": {
		"currencyCode": "USD",
		"timeZone": "Europe/London"
	},
	"kind": "analyticsData#runReport"
}
```

```json
// This is for a custom dimension which _does not_ have data:

// Request
{
  "dateRanges": [
    {
      "endDate": "2023-10-04",
      "startDate": "2023-07-07"
    }
  ],
  "dimensions": [
		{
      "name": "customEvent:yetAnotherParam"
    }
  ]
}

// Response
{
	"dimensionHeaders": [
		{
			"name": "customEvent:yetAnotherParam"
		}
	],
	"rows": [
		{
			"dimensionValues": [
				{
					"value": "(not set)"
				}
			]
		}
	],
	"rowCount": 1,
	"metadata": {
		"currencyCode": "USD",
		"timeZone": "Europe/London"
	},
	"kind": "analyticsData#runReport"
}
```

</details>

- As mentioned above, the "data availability on load" aspect has not been addressed here. As you can see by following the code from these entry points: [here](https://github.com/google/site-kit-wp/blob/9c5f9dc6714c657488ae99a9d193d12bfba8fa4c/includes/Core/Assets/Assets.php#L426-L434), [here](https://github.com/google/site-kit-wp/blob/9c5f9dc6714c657488ae99a9d193d12bfba8fa4c/includes/Core/Modules/Modules.php#L445-L455) and [here](https://github.com/google/site-kit-wp/blob/9c5f9dc6714c657488ae99a9d193d12bfba8fa4c/assets/js/modules/analytics-4/datastore/report.js#L160-L163), and as originally specced in #5933 - the existing gathering data store makes use of `data_available_{module slug}` properties of the `_googlesitekitModulesData` global object to determine data availability on page load. This allows the gathering data store to avoid making an additional request when there _is_ data available. We should take the same approach with this custom dimension gathering data store for the same reason.
  - Please can you update the IB to specify this "data availability on load" aspect.
  - I'd suggest we add a new global object called `_googlesitekitAnalyticsData` with a property `customDimensionsDataAvailable` to include the new data, as alluded to in the `initialState` snippet above.
  - This will mean we don't need a `GET` endpoint for the custom dimension data available endpoint as the data will always be provided on page load (note there's no `GET` for the existing `data-available` endpoint for this reason).

**Comment by zutigrm** [comment] 2023-10-06 15:03
@techanvil Thank you very much for the valuable feedback! It seems I misunderstood `gathering state` meaning a bit. I amended the IB per your suggestions. Let me know what you think.

Also, I would appreciate your opinion on my original estimate? Thanks

**Comment by techanvil** [comment] 2023-10-10 10:35
Thanks @zutigrm, this is looking better. I do have a bit more feedback (sorry if I didn't capture some of this the first time around, there was a fair amount to cover initially so I figured we can iterate a bit).

Again, a couple of more general points and then on to some details. 

- When referring to existing files as an example to follow, please permalink them so we can track back the version of the file that was being referred to for the implementation.
- Structurally, it's a bit of a long list that mixes front and backend concerns. It would be easier to read with a bit of reorganisation; I'd suggest reorganising along these lines which is effectively the dependency order.
  - ### Backend
    - ...
    ### Frontend
    #### Redux store
    - ...
    #### Widgets 
    - ...
- Rather than referring to the Design Doc for the list of custom dimensions, we already have them defined in a [constant](https://github.com/google/site-kit-wp/blob/c6325c0c86773fb83ba643538eea4d4c02cf302f/assets/js/modules/analytics-4/datastore/custom-dimensions.js#L47) which should be extracted to a suitable `constants.js` file and used as the single source of truth for the definitions within the codebase.
- It's probably worth mentioning that the methods of `Custom_Dimension_Data_Available` should take the custom dimension parameter name as an argument, and that an instance of it should be registered in the `Analytics_4` module class, for the sake of clarity. Also, maybe this is splitting hairs a bit, but I think we should probably name it `Custom_Dimensions_Data_Available` to be consistent as this class will operate on multiple custom dimensions, it's just at the method level that they should be singular.
- Sorry for the slight change of direction here but on reflection, I don't think we need to add a new `_googlesitekitAnalyticsData` global - primarily because it would mean we're either _always_ adding this new script tag + global regardless of whether Analytics is currently active, or we'd need to jump through some hoops to avoid that. Instead, I think we can add the `customDimensionsDataAvailable` property to the `_googlesitekitModulesData` global, which we can do by adding a `googlesitekit_inline_modules_data` filter to the `Analytics_4` class, in the same way that we do for [`Modules`](https://github.com/google/site-kit-wp/blob/c6325c0c86773fb83ba643538eea4d4c02cf302f/includes/Core/Modules/Modules.php#L293). I'd suggest we nest this property under `analytics-4` to make the distinction between pan-module and individual module data clear, i.e. the structure of `_googlesitekitModulesData` would be as follows:
  - ```js
    {
      'data_available_analytics': true,
      'data_available_analytics-4': false,
      // etc
      'analytics-4': {
        'customDimensionsDataAvailable': {
          googlesitekit_post_date: true,
          googlesitekit_post_author: false,
          // etc
        }
      }
    }
  ```
- An aspect that we've missed so far is the fact we'll need to reset the cached state (delete the transients) when the GA4 property changes, similarly to how we [reset the existing data available state](https://github.com/google/site-kit-wp/blob/c6325c0c86773fb83ba643538eea4d4c02cf302f/includes/Modules/Analytics_4.php#L113-L123).
- We'll need some PHPUnit test coverage as well for the PHP additions.


With regard to your question about the estimate, this is a fairly complex one, and the IB does refer to a existing code to follow in a number of places which means, although there is some prior art which helps, there's also a fair bit more code to write and test than might appear at first glance. Personally, I'd consider it perfectly reasonable to estimate this as a 19 _without_ the points experiement, which would mean bumping this up to a 30. Please feel free to do so!

**Comment by zutigrm** [comment] 2023-10-10 14:27
@techanvil Thank you. Especially for spotting the reset data issue.
Yes indeed `_googlesitekitModulesData` makes more sense to be used, based on the description you provided.

IB updated.

**Comment by techanvil** [comment] 2023-10-11 15:49
Thanks @zutigrm! The IB is now LGTM. Nice work. :white_check_mark:

**Comment by mohitwp** [comment] 2023-11-01 12:25
### QA Update ✅ 

- Tested on dev environment.
- Verified Gathering data state is showing as per AC.
- Verified that  the first time data is available for a custom dimension, a POST request is made to the custom-dimension-data-available endpoint with the `customDimension` specified in the payload.
- Verified that on subsequent page loads this endpoint is not get hit.
- Verified that upon changing the measurement ID in settings, or upon disconnecting Analytics, the data availability state is reset and that the stored transient state has been deleted from the DB.


<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/224027b0-7eed-417b-bc09-a66f429222d9)


https://github.com/google/site-kit-wp/assets/94359491/e6fcc0be-f842-4e0f-8fb7-118f730d368c


https://github.com/google/site-kit-wp/assets/94359491/33b418e1-067b-4126-ae84-93eb80c8a53e

</details>

**Closed** 2023-11-04 02:42 UTC
Labels: P0, Type: Enhancement
