### ISSUE TITLE
GDPR Compatibility

### ISSUE THREAD

**Issue by simea-simea** [google/site-kit-wp#928] opened 2019-11-28 10:29 UTC
## Feature Description

I would love to see a possibility to be GDPR compliant while using Google's Site Kit. Or at least a clear "How To" Page, where users with no (or small) knowledge of code can follow the steps. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## Changelog entry

*

**Comment by Zodiac1978** [comment] 2019-11-28 14:52
Duplicate of #462

**Closed** 2019-11-28 14:59 UTC
