### ISSUE TITLE
KMW admin settings allows users to remove top goals and save

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7473] opened 2023-08-21 13:13 UTC
## Bug Description

As reported by @10upsimon in Bug Bash:

If setting up the KMW via the initial banner CTA using the "Get tailored metrics" option, on step 3/3 the user is forced to select a minimum of 1 and a maximum of 3 items, yet if they proceed to edit their choices in Site Kit > Settings > Admin Settings > Key Metrics they're able to edit step 3 selections, clear all selections and save. This should be consistent with the initial CTA based setup IMO.

Noting that when the user removes and saves without a goal, this message displays, but they shouldn't be allowed to save without a goal:

![image](https://github.com/google/site-kit-wp/assets/12189958/ed7c4f04-140d-4bb7-9b27-1631ad7e46ad)

https://github.com/google/site-kit-wp/assets/90871/d776ba83-2252-4dfd-ae12-ef2396783284

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* It should not be possible to save 0 answers to the third step of `Site Kit > Settings > Admin Settings > Key Metrics`.
* The "Confirm Changes" button should be disabled when no answers are selected and it should not be possible to save that change in the UI.

## Implementation Brief

* Use the validation function `hasErrorForAnswer` that checks agains number of selected answers https://github.com/google/site-kit-wp/blob/b03c75c0af51101c95da85d5fdb8182b32c8713b/assets/js/components/user-input/util/validation.js#L32
* Result should be passed as additional OR condition to the `disable` prop  of the `SpinnerButton` if component is in `isEditing` mode - https://github.com/google/site-kit-wp/blob/b03c75c0af51101c95da85d5fdb8182b32c8713b/assets/js/components/user-input/UserInputPreviewGroup.js#L214

### Test Coverage

* No changes needed

## QA Brief

* Enable `ga4Reporting` and `userInput` flags.
* Setup Analytics and Key Metrics.
* Go to settings, and click on `Admin Settings` tab.
* Under `Key Metrics` edit `What are your top goals for this site?` option.
* Remove all checked items, and verify that `Confirm Changes` button gets disabled (and settings cannot be saved) if nothing is selected.
* Check at least 1 item, and verify that `Confirm Changes` button gets enabled.

## Changelog entry

* Ensure user cannot edit/save Key Metrics answers with the last question blank.

**Comment by techanvil** [comment] 2023-08-29 16:53
IB :white_check_mark:

**Comment by mohitwp** [comment] 2023-09-01 08:20
### QA Update ❌ 

@zutigrm 

- Tested on dev environment.

**Issue :>** If options are already selected and user unchecked every option and click on cancel button then user comes out from edit screen and no changes applies to already selected options which is expected. But, when user again` What are your top goals for this site?` then `Please select at least 1 Answer` notice appears which should not be display because answers are already selected.

<details>


https://github.com/google/site-kit-wp/assets/94359491/34054c43-8c93-48d5-a8e9-578df0ad123f

![image](https://github.com/google/site-kit-wp/assets/94359491/9b5d7e79-7f7a-4ea9-8cf6-698a0a5765cb)

</details>

**Comment by zutigrm** [comment] 2023-09-01 15:17
@aaemnnosttv There seems to be issue not directly relating to button being enabled/disabled when 0 answers are picked, but is concerning the state data (and `saveUserInputSettings` action) upon cancelation with 0 answers. Should I attend to this in this issue, or should we open a separate one for it? Thanks

**Comment by tofumatt** [comment] 2023-09-05 13:12
I think in this case, the Cancel button there should also reset any error encountered (or the "Edit" button that opens the screen should do so).

Though I'm a bit confused why `saveUserInputSettings` is getting called at all—it should only be called here: https://github.com/google/site-kit-wp/blob/954d8ddd1fa01e09e87a51f8a0e7805d9310f2b6/assets/js/components/user-input/UserInputPreviewGroup.js#L220

🤔 I'm going to test this out myself and see _why_ that error is coming up when the saving shouldn't be happening when the user can't submit the form.

**Comment by tofumatt** [comment] 2023-09-05 13:48
So, the answers are never being saved by `saveUserInputSettings` in this scenario:

https://github.com/google/site-kit-wp/assets/90871/0be682d3-fe6d-4bd2-9a23-8dccd99eede7

No network requests to save or `saveUserInputSettings` actions are being dispatched.

The issue is that the errors are checked only when the panels are saved (makes sense) or _collapsed_ (doesn't make sense): https://github.com/google/site-kit-wp/blob/954d8ddd1fa01e09e87a51f8a0e7805d9310f2b6/assets/js/components/user-input/UserInputPreview.js#L209

Realistically the error messages should be updated whenever the answers change, which would given more realistic/live feedback to users.

But this is a separate issue and not related to the issue at hand. I've filed #7543 for that issue, the errors appearing here after the answer section collapses is unrelated to this change or to the ACs here. QA here covers the ACs so moving to Approval.

**Closed** 2023-09-07 13:40 UTC
Labels: Type: Bug, P1, Good First Issue
