### ISSUE TITLE
Create the "Top cities driving traffic" key metric widget tile

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6252] opened 2022-12-02 01:04 UTC
## Feature Description

<img width="380" alt="Screenshot 2022-12-19 at 01 38 33" src="https://user-images.githubusercontent.com/1721319/210290616-f431a181-d538-46d3-afae-7dc8b7831b57.png">

- Refer to the widget tables in the [design doc](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#bookmark=id.qz6oxctz8fe7) and the [PRD](https://docs.google.com/document/d/1JvJ2gKxaX2PcYOnmA3-xqz4hK_ZHxj8Rd0svq6S8tiU/edit#bookmark=id.w8o73hf5pz1f) explaining the sources of data and other details.
- [Figma mock for all widgets](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=3407%3A73377&t=mxlhDsRNGXcli8tk-0)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component should be created for the 'Top cities driving traffic' Key metric widget and should be displayed within the Key Metrics widget area if it is selected (based on #6257 and #6313).
  * The component should reflect the screenshot supplied above, see the Figma link above for more detail.
* The top three cities with the highest number of `totalUsers` should be displayed from the [Google Analytics Data API](https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema) using the following metric/dimension and the global date range selected on the Site Kit dashboard:
    * metric: `totalUsers`
    * dimension: `city`
* Existing GA4 datapoints and datastore infrastructure that is being added as part of the [GA4 Reporting Epic](https://github.com/google/site-kit-wp/issues/6253#workspaces/execution-5e185a810bd7fc358af69885/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTAxNTQyOQ) should be used where available.

## Implementation Brief

* Once #6251 have been merged.
* In `assets/js/modules/analytics-4/components/widgets/TopCitiesWidget.js`:
  * Return `null` if the `GA4` module is not connected.
  * Using the `getKeyMetrics` selector, check if any of the selected Metric is from GA4. If not, return `null`. Otherwise, continue.
  * Most of the styles should already be in place as a result of #6251 - reuse the `MetricTileTable` reusable component.
  * To get the data for the component, use the following options:
      * metrics: `totalUsers`
      * dimensions: `city`
      * limit: `3`
      * orderBy: `city` (descending)
  * Query the GA4 data store via the `getReport` selector with the metric and dimension as mentioned above.
      * To get the selected date range, query the `core/user` data store via the `getDateRangeDates` with `compare` set to `true`.
  * To get the %, use the values from the `totals[0].metricValues` and the value for each city.
  * Use the `numFmt` function from `assets/js/util/i18n.js` to format the % number.
* Add stories for `AnalyticsTopCitiesWidget` in `assets/js/modules/analytics-4/components/widgets/AnalyticsTopCitiesWidget.stories.js`.

### Test Coverage
* Add tests for the newly added `TopCitiesWidget` component.

## QA Brief

* With the `userInput` feature flag enabled, answer the questionnaire. As part of this issue, test the design and metric values of the `Top Cities Widget` widget rendered in the Key Metrics section.
* To render the `Top Cities Widget` widget, run the following code on the browser console:
```js
googlesitekit.data.dispatch( 'core/user' ).receiveGetKeyMetricsSettings( {
    widgetSlugs: [ 'kmAnalyticsTopCities' ]
} )
```
* Verify the `Top Cities Widget` stories within the Key Metrics widget section in the Storybook.
* Note: Cities are displayed as non-interactive plain text. The color of the plain text is changed, as can be seen in the Figma design.

<img width="399" alt="Screenshot 2023-07-17 at 10 18 27 PM" src="https://github.com/google/site-kit-wp/assets/24408261/1f0b514b-11e9-4660-9b32-4df9d2792169">

## Changelog entry

* Add "Top cities driving traffic" key metric widget.

**Comment by tofumatt** [comment] 2023-01-31 22:30
ACs 👍🏻 Moving this to IB.

**Comment by eugene-manuilov** [comment] 2023-02-15 17:48
IB ✔️

**Comment by hussain-t** [comment] 2023-07-11 09:50
@nfmohit, I have moved it back to execution to apply the changes @sigal-teller provided for the non-interactive plain text.

**Comment by mohitwp** [comment] 2023-07-24 10:09
### QA Update ⚠️ 

- Tested on dev environment.
- Tested using oi.ie site.
- Verified the Top Cities Widget stories within the Key Metrics widget section in the Storybook.
- Verified the Top Cities Widget rendered in the Key Metrics section.
- Verified its design with Figma.

@hussain-t We already have one issue for data inconsistency under Key metrics widgets. For ' Top Cities Widget' I calculated the percentage with the data I'm getting in Analytics. I found percentage is different when I filter data for 'Last 7 days". In this case for first city Dublin percentage is same. But, getting different percentage for not set and cork city.  In my calculation, percentage is 15.6 for not set city whereas widget showing 13.9% . See screenshots below and let me know if I create a separate ticket to investigate this.

<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/13b6b47d-9721-4efc-9933-d6d33ac5feff)

![image](https://github.com/google/site-kit-wp/assets/94359491/50d7e315-6b70-4920-b862-d4e2f5fd72ca)

![image](https://github.com/google/site-kit-wp/assets/94359491/790c64b0-7791-43d7-8cc4-ea8ca89d1990)



</details>


![image](https://github.com/google/site-kit-wp/assets/94359491/4916a18e-77e7-420d-a6f9-c7254da229ac)

![image](https://github.com/google/site-kit-wp/assets/94359491/c86783ae-000a-468d-9c07-68992a79a35e)

</details>

**Comment by techanvil** [comment] 2023-07-24 10:40
Hey @mohitwp, the short answer here re. the data consistency is that you need to add a hostname filter in your report, to match the default hostname filter that is applied to all of our Analytics reports.

Every Analytics report is automatically filtered for the hostname dimension to only return rows matching the hostname or its `www` variant, as can be seen in this screengrab of an example report request:

![image](https://github.com/google/site-kit-wp/assets/18395600/8304e556-f114-459d-a049-e82f12a8d20a)

The main GA4 property we use for `oi.ie` is also used on some other sites so if we don't apply this filter when viewing data on the Analytics site, it's likely the data won't match.

So, please can you update your report by adding a hostname filter to match `oi.ie` (you don't actually need to filter by `www.oi.ie` because the `www` subdomain just redirects to `oi.ie`), and try again.

![image](https://github.com/google/site-kit-wp/assets/18395600/a5de04ea-8f59-41ca-8fe6-a87ffd3fa623)

**Comment by mohitwp** [comment] 2023-07-24 11:10
@techanvil @hussain-t I added dimension hostname and getting the same numbers in result.


![image](https://github.com/google/site-kit-wp/assets/94359491/cffd0c8f-d1e0-4779-8e93-44d7253bddf3)

**Comment by techanvil** [comment] 2023-07-24 12:08
Hi @mohitwp, thanks for checking. Apologies, I should have sounded a bit less certain in my previous comment - I've been looking into the GA4 data inconsistencies for #7214, and this is the reason for the discrepancy with other `totalUsers` based reports.

It does appear to be a different situation here and it's not yet evident what the cause is.

Seeing as this issue has been implemented as per the spec, I'd suggest we add this tile to the AC for #7214 where I can continue to investigate it further, and we can move this one to Approval.

**Comment by hussain-t** [comment] 2023-07-24 12:54
Thanks for jumping in and providing the information, @techanvil 👍

**Comment by mohitwp** [comment] 2023-07-24 13:46
### QA  Update ✅ 

Thank you @techanvil !

- Tested on dev environment.
- Tested using oi.ie site.
- Verified the Top Cities Widget stories within the Key Metrics widget section in the Storybook.
- Verified the Top Cities Widget rendered in the Key Metrics section.
- Verified its design with Figma.


<details>

![image](https://github.com/google/site-kit-wp/assets/94359491/4916a18e-77e7-420d-a6f9-c7254da229ac)

![image](https://github.com/google/site-kit-wp/assets/94359491/c86783ae-000a-468d-9c07-68992a79a35e)

</details>

**Comment by mohitwp** [comment] 2023-07-24 13:50
Date discrepancy issue reported [above](https://github.com/google/site-kit-wp/issues/6252#issuecomment-1647614583) will investigate as a part of #7214

**Closed** 2023-07-27 21:54 UTC
Labels: P0, Type: Enhancement, Exp: SP
