### ISSUE TITLE
Idea Hub notice not showing in editor

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#3827] opened 2021-08-11 11:01 UTC
## Bug Description

In #3272 we added a notice to the editor for posts created for Idea Hub ideas.

This has since stopped appearing due to a change in the way the script is built. Originally, it was added as a "basic module" in our Webpack config which is a separate section of entries which have minimal optimization. https://github.com/google/site-kit-wp/blob/93d2c1b3e902cd4d91aadf82e029d0d5fabaa830/webpack.config.js#L282-L289

The regression was caused when I asked for this to be moved into our primary list of JS entries due to its internal use of SK api/cache which made it less safe to use as a basic module. In particular, api/cache relies on a `GOOGLESITEKIT_VERSION` constant which is only provided to our primary modules, so cache keys were not generated properly when used as a basic module.

However, in doing so the script has stopped loading due to missing Webpack dependencies.

The asset in WP only requires our `googlesitekit-i18n`, but inspecting the built script shows it requires both our `runtime` (expected of all main entries), but also `googlesitekit-vendor`.

```
},[["./assets/js/googlesitekit-idea-hub-notice.js","runtime","googlesitekit-vendor"]]]);
```

The vendor dependency seems a bit unnecessary but from what I can tell there are at least two reasons for this:
* Use of `global` keyword – this is a node thing which we use for consistency everywhere so Webpack loads a compatibility module from `./node_modules/webpack/buildin/global.js` to handle this
* Apart from that – the only thing I can see are Babel runtime async-to-generator modules so that would imply any async function would require vendor as well

The fix is as simple as adding the missing dependencies to the `Asset` instance.

## Steps to reproduce

1. Create a draft from an Idea Hub idea
2. Edit the post
3. Note the notice at the top that identifies the source idea is not shown

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Idea Hub notice for display in the post editor should be shown when viewing a post created for an Idea Hub idea (unless dismissed)

## Implementation Brief

* Explicitly add the vendor and runtime assets to the `googlesitekit-idea-hub-notice` asset's dependencies
* Merge https://github.com/google/site-kit-wp/pull/3828

### Test Coverage

* No changes

### Visual Regression Changes

* No changes

## QA Brief

* Follow above steps to reproduce, you should see the notice now

## Changelog entry

* N/A

**Comment by aaemnnosttv** [comment] 2021-08-11 16:58
Here is the issue which would fix this in a more holistic way which would be nice to revisit https://github.com/google/site-kit-wp/issues/3195 (cc: @felixarntz)

**Comment by felixarntz** [comment] 2021-08-11 19:57
IB ✅

**Comment by wpdarren** [comment] 2021-08-16 14:10
### QA Update: ⚠️ 

@aaemnnosttv There wasn't a reference to the designs on the ticket, so had a look on Figma and the mocks look different to what I am seeing. I am thinking that the mocks are possibly out of date but would like the clarification. 

Here is what I am seeing on my test site (looks better IMO) 

![image](https://user-images.githubusercontent.com/73545194/129576873-83911639-4db5-4133-97bb-3f4aeb136faf.png)

Here is what I see in [Figma](https://www.figma.com/file/YB79eKcGOwyUjlWG8mjDZA/Prompt-Engine-%2F-Idea-Hub?node-id=20332%3A6297)

Please could you confirm if what I am seeing on my test site is expected.

**Comment by felixarntz** [comment] 2021-08-16 16:30
@wpdarren The difference is mostly expected, since we've decided to stick to the Gutenberg notices style over what was originally designed. However, shouldn't this notice still have something "blue" in it, as an info notice? Or is the left border just cot off in the screenshot?

cc @aaemnnosttv

**Comment by wpdarren** [comment] 2021-08-17 13:07
@felixarntz I do see a blue border on the left of the notice.  It would seem I cut it off my screenshot. So, this is looking as expected but I would like to add another observation. Let's pretend that a user has the 'Disable Gutenberg' plugin activated, no message appears.  I am assuming this is out of scope because we've gone with the Gutenberg notices?  

Thought I would throw that one out there, but that aside, this is looking good to approve. 

![image](https://user-images.githubusercontent.com/73545194/129728666-3d0c023d-81ac-4738-8b27-a1c644967d1e.png)

**Verified:**

- Can confirm that the notice appears when you edit a draft post created in Idea Hub. 
- The format of the notice message is `This post was created from an idea you picked in Site Kit’s Idea Hub: <Topic idea title>`
- Confirmed that the notice displays correctly on smaller screen sizes.  - [Screenshot](https://user-images.githubusercontent.com/73545194/129729558-834ab0b0-aadd-48fc-9e9a-5084074fcabc.png)
- Confirmed that the notice displays correctly on supported browsers.

**Comment by felixarntz** [comment] 2021-08-17 15:15
@wpdarren Yes, that is all correct then. So far we only support Gutenberg, so that is behaving as intended.

**Comment by wpdarren** [comment] 2021-08-17 15:41
Thanks for clarifying that @felixarntz 

### QA Update: ✅ 

**Verified:**

- Can confirm that the notice appears when you edit a draft post created in Idea Hub. 
- The format of the notice message is `This post was created from an idea you picked in Site Kit’s Idea Hub: <Topic idea title>`
- Confirmed that the notice displays correctly on smaller screen sizes.  - [Screenshot](https://user-images.githubusercontent.com/73545194/129729558-834ab0b0-aadd-48fc-9e9a-5084074fcabc.png)
- Confirmed that the notice displays correctly on supported browsers.

![image](https://user-images.githubusercontent.com/73545194/129728666-3d0c023d-81ac-4738-8b27-a1c644967d1e.png)

**Closed** 2021-08-30 19:25 UTC
Labels: Type: Bug, P1, Rollover, Module: Idea Hub
