### ISSUE TITLE
Enable easy code placement for Ads ID

### ISSUE THREAD

**Issue by marrrmarrr** [google/site-kit-wp#3161] opened 2021-04-15 14:43 UTC
## Feature Description

For sites with gtag.js (meaning Site Kit has placed the GA tag, can be either existing or newly provisioned accounts), enable the user to copy their Ads ID and incorporate that into the gtag.js snippet. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For sites with gtag.js (Analytics), display an "Ads Conversion ID" field in the GA settings tab
* As context, display text "If you're using Google Ads, insert your Ads conversion ID if you'd like Site Kit to place the snippet on your site"
* The field should only be displayed if the Analytics snippet is inserted from Site Kit (i.e. if `useSnippet` is enabled).
* The field should be the last in the Analytics settings panel, in its own row.
* Once the user copies their ID into the field and clicks "Confirm changes", place the extra line in the gtag.js snippet. The line will have the format `gtag( 'config', 'AW-CONVERSION_ID');`
    * This should be implemented for both the UA Analytics snippet as well as the GA4 snippet (see #3106).
    * The field input should be validated to start with `AW-`.
* After the user has clicked "confirm changes", display an entry with heading "Ads Conversion ID" and the inserted conversion ID (`AW-...`) in the GA settings _if_ the Analytics snippet is inserted from Site Kit (i.e. if `useSnippet` is enabled). 

### JS/Frontend

* Create a new setting for Analytics in [`settingsSlugs`](https://github.com/google/site-kit-wp/blob/df83274d9db0d795e2d02dda236ff24e5ce59b20/assets/js/modules/analytics/datastore/base.js#L28-L38): `adsID`
* Create a new component for the Analytics `SetupForm` to use in `assets/js/modules/analytics/components/common` named `AdsIDInput` containing a `TextField` that the user can use to submit the `adsID` setting to Analytics module, similar to how other settings are loaded and saved in the Analytics module. The label for the Ads ID value should read *"Insert your Ads Conversion ID here if you want Site Kit to place the Ads snippet on your site"*. `ProfileNameTextField` can serve as a reference for how to build this setting, as it is another text entry setting in Analytics.
  * This input should only appear if the settings `useSnippet` is enabled—if Site Kit isn't outputting the Analytics tag for this site, don't show this setting.
  * The form should do validation as outlined in the comment below: https://github.com/google/site-kit-wp/issues/3161#issuecomment-825793028. Essentially just check for an `AW-` prefix.
  * The component should dispatch changes made to the input to the Analytics module settings store (similar to, for instance, setting the `AnonmyizeIP` setting or any other setting in `MODULES_ANALYTICS` store, see: https://github.com/google/site-kit-wp/blob/df83274d9db0d795e2d02dda236ff24e5ce59b20/assets/js/modules/analytics/components/common/AnonymizeIPSwitch.js#L43 if they're valid.
* Add this new component below all other settings inputs/toggles in the Analytics settings form.
* In the `SettingsView` component in Analytics, if the Ads ID code is also set and inserted, output that below the Profile ID: https://github.com/google/site-kit-wp/blob/3fb4b73421597f329da0ce0022ba315a6cf18630/assets/js/modules/analytics/components/settings/SettingsView.js#L80. The output should only appear if the `adsID` setting is non-empty, and would be similar to the other IDs, something like:
```js
{ adsID && (
	<div className="googlesitekit-settings-module__meta-item">
		<h5 className="googlesitekit-settings-module__meta-item-type">
			{ __( 'Ads ID', 'google-site-kit' ) }
		</h5>
		<p className="googlesitekit-settings-module__meta-item-data">
			<DisplaySetting value={ adsID } />
		</p>
	</div>
) }
```

### PHP

* If the `adsID` setting is set, add the output to both the UA and GA4 snippets, https://github.com/google/site-kit-wp/blob/df83274d9db0d795e2d02dda236ff24e5ce59b20/includes/Modules/Analytics/Web_Tag.php#L89 (UA) and https://github.com/google/site-kit-wp/blob/df83274d9db0d795e2d02dda236ff24e5ce59b20/includes/Modules/Analytics_4/Web_Tag.php#L43 (GA4)
  * To determine if `adsID` setting is set, mimic the approach used for the approach used by [`set_anonymize_ip`](https://github.com/google/site-kit-wp/blob/df83274d9db0d795e2d02dda236ff24e5ce59b20/includes/Modules/Analytics/Web_Tag.php#L54-L63), but for `adsID`. Ensure that the setting is set on the tag here: https://github.com/google/site-kit-wp/blob/df83274d9db0d795e2d02dda236ff24e5ce59b20/includes/Modules/Analytics.php#L1260
  * The output added to the tag for non-AMP pages should match the ACs—`gtag( 'config', 'AW-CONVERSION_ID');`.
  * The AMP page output should be added to the AMP output here: https://github.com/google/site-kit-wp/blob/841a3a0a8bf82bc5bcbd5d6df4c3000614657fbd/includes/Modules/Analytics/AMP_Tag.php#L82-L89, as a config option. See: https://developers.google.com/google-ads/amp/conversion-measurement#option_1_global_site_tag for docs.

### Test Coverage

* Test coverage for the component to validate user input and display the appropriate errors would be great, but as the rest of the settings code is covered by using our `settingsSlug` approach little datastore tests are needed.

### Visual Regression Changes

* The Analytics Setup and Settings form will change as a result of the added field.

## QA Brief

* A new setting has been added to the Analytics module settings for providing an Ads conversion ID
* The setting only shows in the module settings, not during set up
* The setting should only appear if the snippet is enabled for GA
    * The setting should not appear if GTM takes over output of the GA tag/snippet (i.e. using a container that has a GA tag)
* If provided, the GA snippet should include the `gtag( 'config', 'AW-CONVERSION_ID' );` as noted in the ACs
* The setting has a required format `AW-#` where `#` is any number of digits
* If an invalid input is provided, a message should be shown and settings should not be able to be saved until the value is corrected or removed (the setting is not required, but a valid form is required if it is provided)

## Changelog entry

* Allow administrators to paste Google Ads conversion ID in Analytics settings so that it is integrated into the Site Kit-placed Analytics snippet.

**Comment by aaemnnosttv** [comment] 2021-04-21 17:10
@marrrmarrr @aarondruck would you please clarify where this new field should go in the settings interfaces? You can see [the current settings edit interface here](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-settings--edit-open-with-all-settings) for reference.

Also, should we do any validation on the input? For example, here's what it looks like when a user is [creating a view with a name that already exists](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-settings--edit-open-when-creating-new-view). This is also an example of the only other text input in this view. Here's an example from [GTM with error validation](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/tag-manager-module-settings--edit-with-a-non-unique-new-container) styling. We probably don't need to do anything sophisticated for validation, if any but just curious if we should only allow `AW-*` values maybe? Adding validation would increase the effort needed, but improve the experience IMO as well as be more consistent with other inputs for these kinds of things, such as the Optimize ID.

**Comment by felixarntz** [comment] 2021-04-23 17:03
@aaemnnosttv Let's do validation to ensure there is the `AW-` prefix. Regarding the positioning, for now let's put it at the very bottom - that should be easy to change even while a PR is being worked on though.

@marrrmarrr When you have a moment, please review the placement of the new field - we can change this easily on demand.

**Comment by marrrmarrr** [comment] 2021-04-27 13:11
Yeah, I think having this below all other existing settings should work for now. 
SGTM on using the [GTM validation error style](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/tag-manager-module-settings--edit-with-a-non-unique-new-container) for anything pasted that doesn't match the ads ID format.

**Comment by tofumatt** [comment] 2021-04-27 21:13
The requested text in the ACs is *"Copy your Ads Conversion ID here if you want Site Kit to place the snippet on your site"*, but I think starting the sentence with the word "copy" is confusing and leads me to think there is a value here I should copy and use elsewhere.

I think it would be better to use something like *"Insert your Ads Conversion ID here if you want Site Kit to place the Ads snippet on your site"*, so the verb at the start of the sentence matches the user action required (if any).

I made that suggestion in the IB; if that sounds good to the reviewer we can adjust the ACs. 🙂 

------

One thing I wasn't clear on in the ACs was:

> * After the user has clicked "confirm changes", Display an entry with heading "Ads Conversion ID" and content "Snippet is inserted" in the GA settings. 

What entry should be displayed and where? Is this to signify to the user that the snippet is live on their site? Should this text go under the text entry field? Presumably if the content is saved it's implied that the snippet is inserted. I'm not clear what this refers to.


-------

One last thing: should the adsID only be added on non-AMP output? I assume yes but I wasn't sure.

**Comment by felixarntz** [comment] 2021-04-27 22:25
@tofumatt 
> I think it would be better to use something like _"Insert your Ads Conversion ID here if you want Site Kit to place the Ads snippet on your site"_, so the verb at the start of the sentence matches the user action required (if any).

Sounds good, I've changed this to say "Insert" in the ACs.

> What entry should be displayed and where? Is this to signify to the user that the snippet is live on their site? Should this text go under the text entry field? Presumably if the content is saved it's implied that the snippet is inserted. I'm not clear what this refers to.

Ah yes, that didn't really make sense before. If the ads snippet is inserted, the ads ID should be displayed for the settings view. I've also added another point related to this to the ACs though, which is that this can only be done if the overall Analytics snippet is inserted via Site Kit. So the whole new setting should be dependent on that (i.e. not show otherwise).

> One last thing: should the adsID only be added on non-AMP output? I assume yes but I wasn't sure.

Hmm good point, yes this should support AMP too. I'm not entirely clear about how though. The example in the docs (https://developers.google.com/google-ads/amp/conversion-measurement#option_1_global_site_tag) makes it look like this should be a separate tag, but I'd expect this can be integrated with the existing `amp-analytics` snippet we have for `gtag` somehow. cc @marrrmarrr

**Comment by tofumatt** [comment] 2021-04-28 11:55
Sounds good—I've made updates assuming we'll insert this for AMP pages too using the `AMP_Tag` module, so I think this is good to review for @felixarntz, but I've left @marrrmarrr on this issue in case we _don't_ want to serve this on AMP pages or if there are other AMP considerations.

**Comment by marrrmarrr** [comment] 2021-04-29 13:28
By "snippet is inserted", I was referring to the string we show in UI once the settings are saved: 
<img width="197" alt="Screen Shot 2021-04-29 at 15 25 52" src="https://user-images.githubusercontent.com/13304791/116558176-75b73580-a8ff-11eb-91ca-89a8b0086569.png">

I'll check with the Ads team on whether we want to serve this on AMP pages or if there are other considerations and I'll update here as soon as I hear from them.

**Comment by felixarntz** [comment] 2021-04-29 15:20
@tofumatt One thing is slightly off in the IB: The new field in `SettingsEdit` shouldn't appear below the profile name text field, but at the very end of the settings (i.e. also after all the individual toggles etc.).

Can you update that bit? Otherwise IB ✅ 

A few bits of the settings UI and AMP have to be clarified, but let's get the work on this started already, as nothing should block most of it. Please eventually assign this to me for code review so I can cater for any small updates that come up in review with @marrrmarrr.

cc @aaemnnosttv

**Comment by aaemnnosttv** [comment] 2021-04-29 17:21
IB updated (no need to bother @tofumatt ), starting on this now 👍

**Comment by aaemnnosttv** [comment] 2021-04-30 10:03
@marrrmarrr you can see what we have in progress in Storybook here:
- [Settings View](https://google.github.io/site-kit-wp/storybook/pull/3257/?path=/story/analytics-module-settings--view-open-with-all-settings)
- [Settings Edit](https://google.github.io/site-kit-wp/storybook/pull/3257/?path=/story/analytics-module-settings--edit-open-with-all-settings)

I think right now the only thing we're waiting for is clarity regarding the tag integration with AMP Analytics.

**Comment by felixarntz** [comment] 2021-05-03 20:09
@aaemnnosttv In addition to the PR feedback, one tiny thing to update here is the description for the settings field. The original copy didn't provide enough context on the field and could set false expectations that this might be something generally worth including. I've confirmed new copy with @marrrmarrr and updated the ACs with it (it now clarifies that this field is only relevant if the user is using Google Ads).

**Comment by wpdarren** [comment] 2021-05-05 14:04
### QA Update:  Pass ✅ 

**Verified:**

- A new setting has been added to the Analytics module settings for providing an Ads conversion ID

![image](https://user-images.githubusercontent.com/73545194/117147898-9a9f2300-adad-11eb-98e0-7527f9f92b50.png)

- The setting only shows in the module settings, not during set up.

- The setting only appears if the snippet is enabled for GA.

![image](https://user-images.githubusercontent.com/73545194/117148219-ef429e00-adad-11eb-8b70-e6f09f552794.png)

- If an invalid input is used, a message is shown and settings are not able to be saved until the value is corrected or removed 

![image](https://user-images.githubusercontent.com/73545194/117148727-6aa44f80-adae-11eb-80b9-9ff167574efe.png)

- The GA snippet includeS the gtag( 'config', 'AW-CONVERSION_ID' ); and has a format of AW-# 

![image](https://user-images.githubusercontent.com/73545194/117150604-33cf3900-adb0-11eb-88e9-74c09c5872f2.png)

- Confirmed that the aw-# tag does not appear when snippet is not inserted or when Google Tag manager is displaying the GA snippet.

**Closed** 2021-05-06 17:44 UTC
Labels: Module: Analytics, P1, Type: Enhancement
