### ISSUE TITLE
Complete Ad Blocking Recovery onboarding screen

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6966] opened 2023-04-23 20:34 UTC
## Feature Description

This issue is about making use of all the pieces to fully complete the Ad Blocking Recovery on boarding screen according the [design doc](https://docs.google.com/document/d/1ilTyamxqIAInd8F-XYBL7GqamU6JIHmnbU9u9aGW3bU/edit#heading=h.raoi85wmdo5t) and [Figma design](https://www.figma.com/file/9jzqdDjP7pCL8MiYHtxxoJ/Ad-Blocker-Detection-2?node-id=20-3577&t=4rJVnIg0l5lGTq5G-0) once all the necessary pieces has been introduced to the code base. 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Ad Blocking Recovery onboarding screen should be completed as seen in the Figma design by stitching together the infrastructure introduced in the previous issues (namely- #6902, #6964 and #6965).
* In a nutshell-
    * The empty `Cell` on the left introduced in #6964 should be populated with the `Stepper` and `Step` contents.
        * In Step one, there should be a `Checkbox` for error protection tag (checked by default) and the "Place Tag" button.
        * In Step two, the "Create message" button should open "Privacy & Messaging -> Ad Blocking Recovery" page of AdSense publisher UI in a new tab and change the main CTA to "My message is ready" while the "Create message" will now appear as secondary CTA as seen in the design. 
            * Link for reference: `https://www.google.com/adsense/new/u/0/pub-XXX/privacymessaging/ad_blocking`
    * The tags should be fetched from API and stored in database using the `fetchAdBlockingRecoveryTags` action in the first step.
    * The `Cancel` button in the footer should be enhanced to behave exactly as described in the [linked](https://docs.google.com/document/d/1ilTyamxqIAInd8F-XYBL7GqamU6JIHmnbU9u9aGW3bU/edit#bookmark=id.p051utr3odnu) section of design doc. 
    * Once user completes the setup flow and clicks "My message is ready", they should be redirected to the Site Kit Dashboard and shown the success notification introduced in #6957.
* The layout, styles, typography, spacing, copies etc should match with the Figma design as closely as possible.
    * The design tokens already defined in the plugin should be used when needed. 

## Implementation Brief

* In `assets/js/modules/adsense/components/settings/AdBlockingRecoveryApp.js`..
    * Replace the Placeholer Text, render a `Stepper` component. It will have two `Step`s as seen in the Figma. 
        * Which step to show should depend on the value of `adBlockingRecoverySetupStatus` setting. 
            * If it is an empty string, the Step 1 is displayed. 
            * If it is `tag-placed`, Step 2 will be displayed instead.
        * `Step` 1:
            * `title`: Place the standard ad blocking recovery tag (required)
            * `children`: 
                * Render the content in a styled `p` tag.
                * Render the Error protection tag checkbox using the `Checkbox` component from `googlesitekit-component`. it should be checked by default. 
                * Render the text underneath the checkbox using a styled `p` tag. 
                * Render a `SnipperButton` for the "Place Tag" CTA. Clicking the CTA should do the following in order. 
                    * Run the syncAdBlockingRecoveryTags action from MODULES_ADSENSE store. 
                    * Update and save the following AdSense module settings.
                        * `adBlockingRecoverySetupStatus`: `tag-placed`
                        * `useAdBlockerDetectionSnippet`: `true`
                        * `useAdBlockerDetectionErrorSnippet`: `true`
                    * Take user to Step 2.
        * `Step` 1:
            * `title`: Create your site’s ad blocking recovery message (required)
            * `children`: 
                * Render the texts in `p` tags.
                * Render the `Create message` CTA with a regular button. Clicking this will:
                    * Open the defined link in the AC in a new tab.
                    * Replace the CTA with the following primary and secondary CTA as follows. 
                        * `My message is ready` primary CTA.
                            * Clicking this will update the `adBlockingRecoverySetupStatus` to `setup-confirmed`, save the setting and take the user back to the dashboard where Ad Blocking Recovery success notification (Implemented in [6957](https://github.com/google/site-kit-wp/issues/6957))  will be displayed.
                        * `Create message` secondary CTA.
                            * Open the defined link in the AC in a new tab.
    * `Cancel` Button enhancement:
        * The `Cancel` button should have its `href` replaced with an `onClick` handler. 
        * The handler should behave exactly as the linked section on Design doc suggests. Namely:
            * If the user is currently in the Step one:
                * They should be taken back to the SK Dashboard. 
            * If they're in step 2:
                * If they pressed cancel before clicking "Create message" CTA:
                    * The AdSense module Settings `adBlockingRecoverySetupStatus`, `useAdBlockerDetectionSnippet` and `useAdBlockerDetectionErrorSnippet` should get rolled back to an empty string. `false` and `false` respectively. 
                    * They should be taken back to SK dashboard. 
                * If they click "cancel" after clicking "create message", 
                    * The changed settings should remain as is and they should be taken back to the SK Settings.
                * This two condition should depend on the same internal state that determines whether one or two CTA is displayed in Step 2. 

### Test Coverage

* Add Story coverage for the setup flow and steps. 
* Add VRT images. 

## QA Brief

- Set up Site Kit and connect Adsense.
- Enable the `adBlockerDetection` feature flag.
- Go to `wp-admin/admin.php?page=googlesitekit-ad-blocking-recovery`.
- Verify that the screen now shows a stepper as shown in the Figma designs.
- Go through the steps and verify that the behavior is according to the ACs.
- Verify that the screen closely matches the Figma designs.

## Changelog entry

* Complete Ad Blocking Recovery set up interface.

**Comment by tofumatt** [comment] 2023-06-05 12:38
ACs look good, moving to IB 👍🏻

**Comment by tofumatt** [comment] 2023-06-15 21:11
IB ✅

**Comment by wpdarren** [comment] 2023-06-27 15:27
### QA Update: ⚠️ 

@kuasha420 I have a few observations and a question. 

1. The Site Kit side menu seems to have a styling issue on the Ad Blocking Recovery screens. Noticed this on desktop on Chrome and Safari. See screenshot below.  Should we include this as a known issue or, would you like to fix it? 

![image](https://github.com/google/site-kit-wp/assets/73545194/b01c6eec-d20b-4bb1-8a91-03b6d4fdbd05)

2. In the AC it mentions `The tags should be fetched from API and stored in database using the fetchAdBlockingRecoveryTags action in the first step.`  Can you explain what that means exactly?  I see these details in the database and it says that it's set up. Is that what this AC section means? 

![image](https://github.com/google/site-kit-wp/assets/73545194/4de4cab6-e1fb-4e40-ade4-8ecb4696cd75)

3. If you set up ABR, you get the success message on the dashboard. If you click on 'Ok, Got it!' and then later disconnect AdSense, and go through the ABR process again, the success notification does not appear.  Want me to add this as a known issue on the bug bash board, rather than fixing this here? 


**Verified:** 

- The empty Cell on the left is populated with the Stepper and Step contents.
- In Step one, there is a Checkbox for error protection tag (checked by default) and the `Place Tag` button.
- In Step two, the `Create message` button opens `Privacy & Messaging -> Ad Blocking Recovery` page of AdSense publisher UI in a new tab.
-  The main CTA changes to `My message is ready`
-  The `Create message` appears as secondary CTA.
- Once user completes the setup flow and clicks `My message is ready`, they should be redirected to the Site Kit Dashboard and shown the success notification.
- When clicking on Cancel link, I am redirected back to the Site Kit dashboard. 

**Note:** On Step two, I feel the behaviour is confusing. I will include it on the bug bash board for discussion, but in short - I click on the `Create message` CTA, the window appears and I go and create message. I come back to Site Kit,  and there's a link CTA there still asking me to create a message.  I can't help but feel this will confuse the user.

**Comment by nfmohit** [comment] 2023-06-27 17:02
Hi @wpdarren 👋 
Thank you for the thorough checks and for sharing the concerns.

> 1. The Site Kit side menu seems to have a styling issue on the Ad Blocking Recovery screens. Noticed this on desktop on Chrome and Safari. See screenshot below.  Should we include this as a known issue or, would you like to fix it?

It looks like this problem isn't specific to the Ad Blocking Recovery onboarding screen as it also appears on the User Input screen. Here's a screenshot:

![image](https://github.com/google/site-kit-wp/assets/20284937/69d16205-ab99-438c-963e-6d4de506e447)

I'd prefer to create a new issue for it. What do you think?

> 2\. In the AC it mentions `The tags should be fetched from API and stored in database using the fetchAdBlockingRecoveryTags action in the first step.`  Can you explain what that means exactly?  I see these details in the database and it says that it's set up. Is that what this AC section means?

The AC section that you referred to means that Site Kit will fetch the tags from the Adsense service and store the tags in the WP database. It is saved to the `googlesitekit_adsense_ad_blocking_recovery_tag` option in the `{prefix}_options` table. Here's a screenshot:

![image](https://github.com/google/site-kit-wp/assets/20284937/b751311f-88a6-4856-b10a-903071eceda4)

> 3\. If you set up ABR, you get the success message on the dashboard. If you click on 'Ok, Got it!' and then later disconnect AdSense, and go through the ABR process again, the success notification does not appear.  Want me to add this as a known issue on the bug bash board, rather than fixing this here?

That's a good catch. However, I'd prefer to add this to the bug bash board as a known issue, as it is not directly related to the onboarding screen.

Feel free to let me know if you have any further questions. Thank you!

**Comment by wpdarren** [comment] 2023-06-28 02:29
### QA Update: ✅ 

I have created tickets for point 1 and 3 on my [earlier comment](https://github.com/google/site-kit-wp/issues/6966#issuecomment-1609748879). 

**Verified:** 

- The empty cell on the left is populated with the Stepper and Step contents.
- In Step one, there is a Checkbox for error protection tag (checked by default) and the `Place Tag` button.
- In Step two, the `Create message` button opens `Privacy & Messaging -> Ad Blocking Recovery` page of AdSense publisher UI in a new tab.
-  The main CTA changes to `My message is ready`
-  The `Create message` appears as secondary CTA.
- Once user completes the setup flow and clicks `My message is ready`, they should be redirected to the Site Kit Dashboard and shown the success notification.
- When clicking on Cancel link, I am redirected back to the Site Kit dashboard. 

**Note:** On Step two, I feel the behaviour is confusing. I will include it on the bug bash board for discussion, but in short - I click on the `Create message` CTA, the window appears and I go and create message. I come back to Site Kit,  and there's a link CTA there still asking me to create a message.  I can't help but feel this will confuse the user.  


<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/b5685171-5374-46bc-a0fe-d2e49ca58ec3)
![image](https://github.com/google/site-kit-wp/assets/73545194/7e4c9f2d-65e0-4d02-8e40-352015b4d4c1)
![image](https://github.com/google/site-kit-wp/assets/73545194/59f67198-44e5-4abc-92de-3a7a5c7f2510)
![image](https://github.com/google/site-kit-wp/assets/73545194/d7a5d6ec-4a61-4c82-9e6b-d6da6479381b)
![image](https://github.com/google/site-kit-wp/assets/73545194/e5266e0d-2796-4085-86f8-c1a3b28f7c0a)

</details>

**Comment by aaemnnosttv** [comment] 2023-06-28 20:53
> I click on the `Create message` CTA, the window appears and I go and create message. I come back to Site Kit, and there's a link CTA there still asking me to create a message. I can't help but feel this will confuse the user.

@wpdarren The problem is that we can't know for sure if the user created the message or not. The link gives the user a way to easily get back to the message management part in AdSense in case they didn't finish it, closed the tab, etc.

In the future, we should be able to simplify this if/when we're able to check that a message has been set up via the API, but again this isn't possible right now and it's critical to the function of the feature.

**Closed by aaemnnosttv** 2023-06-28 20:53 UTC
Labels: Type: Feature, P0, Module: AdSense
