### ISSUE TITLE
Storybook padding causes issues (on small viewports)

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#3174] opened 2021-04-16 13:10 UTC
## Bug Description

As mentioned in this comment: https://github.com/google/site-kit-wp/pull/3143#issuecomment-820978323, Storybook's mobile viewport settings in our Storybook site adds `50px` of padding on the left and right. This causes issues using Storybook to test the output of our components, especially on mobile viewports where a `320px` width is actually more like `220px` 😓 

## Steps to reproduce

1. Open Storybook and view the story for a header with Help Icon and Date Range Selector: https://google.github.io/site-kit-wp/storybook/pull/3143/iframe.html?id=global--plugin-header-with-help-menu-and-date-range-selector&viewMode=story
2. Change the viewport to the "mobile viewport"
3. See screenshot for the error that happens

## Screenshots

<details>
	<summary>Big screenshots</summary>
	
<img width="502" alt="Screenshot 2021-04-15 at 21 00 52" src="https://user-images.githubusercontent.com/90871/114931304-f9682100-9e2d-11eb-90e8-145943d14f09.png">

Compare this with the same story without the Storybook "chrome", using a responsive developer tool screen:

![image](https://user-images.githubusercontent.com/31818/114988093-fa896480-9ea6-11eb-83a2-eb40a39304f6.png)

</details>

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* For "composite stories", eg stories of full-page components or any other component that should not be rendered with extra padding, there should be a way to customize/remove the padding used for said stories
  * This will allow some stories, like the ones mentioned above, to output the same layout as they would in the WordPress dashboard, without the "default" Storybook padding.
* There should be no padding around stories in any viewports that would cause differences between Storybook and the WordPress rendering. Paying particular attention to mobile/tablet viewports: all stories should render without extra padding causing their elements to be too tight together.

## Implementation Brief

* Finish and merge #3315
* The stories within the following files should have the padding in Storybook set to `0` via the story parameters. An example can be found in `stories/user-input.stories.js`.
    - stories/dashboard-details.stories.js
    - stories/dashboard.stories.js **except**:
        - `Module Header`
    - stories/module-adsense-components.stories.js
    - stories/module-adsense-settings.stories.js
    - stories/module-adsense-setup.stories.js
    - stories/module-adsense.stories.js **except**:
        - `Account Select, none selected`
        - `Account Select, selected`
        - `Use Snippet Switch, toggled on (default)`
        - `Use Snippet Switch, toggled off`
        - `AdBlocker Warning`
        - `User Profile`
    - stories/module-analytics-components.stories.js
    - stories/module-analytics-settings.stories.js
    - stories/module-analytics-setup.stories.js
    - stories/module-analytics.stories.js **except**:
        - `Account Property Profile Select`
        - `Property Select including GA4 properties`
        - `Anonymize IP switch, toggled on`
        - `Anonymize IP switch, toggled off`
        - `Use Snippet switch, toggled on (default)`
        - `Use Snippet switch, toggled off`
        - `Tracking exclusions (default)`
        - `Tracking exclusions (including loggedinUsers)`
        - `Tracking exclusions (including contentCreators)`
        - `GA4 notice`
    - stories/module-search-console-settings.stories.js
    - stories/module-search-console.stories.js
    - stories/modules-tagmanager-settings.stories.js
    - stories/settings.stories.js
    - stories/wp-dashboard.stories.js
    - stories/data-table.stories.js
    - stories/header.stories.js
    - stories/modules-list.stories.js
    - stories/page-header.stories.js
    - stories/notifications.stories.js
    - stories/report-table.stories.js
    - stories/widgets.stories.js only the `WidgetArea` child stories.
    - stories/module-optimize-settings.stories.js
    - stories/module-optimize-setup.stories.js
    - stories/module-pagespeed-insights-components.stories.js
    - stories/module-pagespeed-insights-settings.stories.js
    - stories/setup.stories.js
    - assets/js/modules/analytics/components/setup/SetupFormUA.stories.js
    - assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.stories.js
* The above list can change if new stories are added, so please review all stories and set the padding to `0` if the following conditions are met when viewing the story in the `Small mobile` viewport in storybook:
    - Component overflows the viewport/content area
    - UI looks broken due to lack of space.

### Test Coverage

* No changes needed

### Visual Regression Changes

* Stories with padding changed will need reference images updated

## QA Brief

* Due to CR feedback, zero padding has not been applied to many stories from the IB
* Just check nothing looks too bad

## Changelog entry

* Fix global storybook padding issues

**Comment by asvinb** [comment] 2021-04-20 14:08
@tofumatt @aaemnnosttv I think it's a good opportunity to have the viewports defined in Storybook to be the same as the one defined in our SASS config, for consistency. I have added the IB, taking that into account.
Let me know what you think.

**Comment by aaemnnosttv** [comment] 2021-04-22 08:45
@asvinb I agree that our Storybook viewports should match the sizes we have breakpoints for but there's a bit more to consider here I think. As it is, we never render anything edge-to-edge on the screen since we're always rendering in the context of wp-admin, the admin menu is always using some of the space on one side of the screen (more/less depending on whether the menu is collapsed or not, but it's always there). The only exception to this is on the front-end in the admin bar app.

So it's not perfect to remove all the padding in that regard but I think it would be better than having the arbitrary padding we do now.

This raises a question though: why keep the padding at all? For stories that want it, they could always add it as a decorator. Not sure we should apply it globally though.

Regarding the current IB: why not update the class to conditionally apply the padding with a `min-width` media query instead so that it only has an effect on larger viewports?

One last point to note: maybe the viewport changes should happen in a separate issue? It's important to note that the viewports defined by Storybook are not the same as those used for VRT which are currently defined in [`tests/backstop/viewports.js`](https://github.com/google/site-kit-wp/blob/46e0d0803e2fec749a9938e9bca171f3fab09ceb/tests/backstop/viewports.js). It would be great if we could define these in a central location and use them in both places.

Thoughts @tofumatt @felixarntz ?

**Comment by asvinb** [comment] 2021-04-22 12:03
@aaemnnosttv About "**why not update the class to conditionally apply the padding with a min-width media query instead so that it only has an effect on larger viewports?**" Since the stories are rendered within an iframe, we'll need to play with the media queries to get it working which is not impossible but requires some more work.
About the padding, I always thought it was added to make the stories look nice, meaning, they are not edge to edge with the sidebar and the browser.

**Comment by aaemnnosttv** [comment] 2021-04-23 05:47
> About the padding, I always thought it was added to make the stories look nice, meaning, they are not edge to edge with the sidebar and the browser.

@asvinb Sure, I think it makes sense for small things like buttons, or really anything that doesn't have responsive styles. For components with responsive styles (usually larger things with grids), then the added padding influences the total width of the viewport and result in inaccurate representation of the component at a particular breakpoint.

The added padding could be useful for ensuring things outside of the component are tested (e.g. a drop shadow), but I think that is more of an exception than a rule.

I'm thinking we probably shouldn't apply the padding in the global decorator, and instead add it per kind or story when desirable.

**Comment by tofumatt** [comment] 2021-04-26 17:29
Unless there's something I'm missing, I think requiring a decorator for the padding is my preference too.

It probably requires adding a lot of said decorators for "UI components"—things like buttons, select components, etc. But for screens or widgets not including "default" padding and instead letting the story specify what—if any—padding is required will result in more accurate stories. I think that's how we should change this around…

**Comment by aaemnnosttv** [comment] 2021-04-27 09:30
@felixarntz It seems like the consensus is that added padding should be added per story/kind rather than globally; what do you think?

**Comment by felixarntz** [comment] 2021-05-03 18:13
@aaemnnosttv @tofumatt @asvinb I'm not sure about this one. It seems to me that having a padding still makes sense as a default, as only very few particular components need to have no padding to reflect more how they look in Site Kit.

For example, atomic UI components, widgets, even combinations of widgets to make up almost a whole screen aren't really affected by what exact padding they have, but they should also not have no padding. Adding a decorator for that to almost all stories feels potentially counter-intuitive, being one more thing everyone has to follow for stories. Maybe it would be better to do it the other way around, use a decorator for the less common case (i.e. to _not_ have padding)?

**Comment by tofumatt** [comment] 2021-05-04 21:12
That's a great point, I feel like maybe we missed the forest through the trees here suggesting that the padding be removed from everything then added back in to many stories. Having an "opt-out" decorator is probably better than opting most things in.

The only issue here might be that it's awkward to remove said padding if its applied high-up in the styles—above where the story's components are created, if that makes sense.

Using a `useEffect()` that adds a class to the highest-most component/body tag would work though. (Or something like react-helmet that allows styles to be added to components outside the story's component hierarchy.)

Still, the opt-out approach sounds better, I think I'm for that 👍🏻

**Comment by aaemnnosttv** [comment] 2021-05-07 06:22
@felixarntz @tofumatt – if we want to keep with-padding as the default, that should be fine. My only thought there is that we will probably add more composite stories in the future than we will atomic like simple buttons, but either way it's easy to change if needed.

As for how we apply the styles in a way which can be controlled by the story, it's actually very easy using Story `parameters`. These are arbitrary values which can be defined at the story / decorator level and are also available in decorators via the 2nd parameter. So we can easily allow for a `padding` parameter, which could even be a numeric value to use for the exact padding rule to apply which could simply default to `50`. Then for any story we don't want padding on, we just define `parameters.padding = 0` 😄 

Using the current decorator, this would look like this:
```js
addDecorator( ( Story, { parameters } ) => {
	const { padding = 50 } = parameters || {};
	return (
		<div
			className="googlesitekit-plugin-preview js"
			style={ { padding } }
		>
			<div className="googlesitekit-plugin">
				<Story />
			</div>
		</div>
	);
} );
```

In legacy stories, this would then be customized using the 2nd argument to `add`:
```js
{
	padding: 0, // No added padding
} 
```
And with CSF this would be:
```js
const SomeStory = Template.bind( {} );
SomeStory.parameters =  {
	padding: 100, // Use 100px padding instead of default
};
```

Then all of the custom styles can be removed from `preview-head.html`. Another benefit of this is that changes to this padding don't require restarting storybook to take effect (changes to `preview-head` are not hot reloaded).

I'll push a branch with this and add it to the IB 👍

**Comment by aaemnnosttv** [comment] 2021-05-07 06:34
@tofumatt I've updated the IB to use this approach – I think the current ACs probably need revision though to match the alternate approach. We also need to define which stories should receive the alternate padding and add that to the IB, after which the rest should be very quick and easy.

**Comment by aaemnnosttv** [comment] 2021-06-01 12:16
> Stories not in the list below should have their padding set to 0

@asvinb – that's quite the list. Would it not be shorter to list only those which _should_ have their padding set to zero (i.e the exceptions requiring changes) rather than those that should keep the default padding? (i.e. no change)

Feel free to be a bit higher-level with the stories that should be changed. Maybe we can reference groups of stories instead since I think these changes probably apply at the "Kind" level rather than the individual story.

**Comment by asvinb** [comment] 2021-06-01 13:35
@aaemnnosttv Actually we do have an even bigger list for stories which we should set the padding to 0, that's why I ended up having a list of components where we should keep the padding. 😅 
Also the reason I listed the URLs is that it'll be easier for the engineer for implementation because he knows exactly what story and he can find out more easily which file is related, compared to if I list the kind of name the stories, it'll be harder for the engineer to find out.
Let me know what you think.

**Comment by aaemnnosttv** [comment] 2021-06-02 16:30
@asvinb I definitely think we should only reference stories which need changing rather than those that don't; even if there are technically less, I don't think it will be very easy to work from a large list of URLs of stories that won't change. Regarding the list being long, I would think in 99% of the cases (if not all) the style will apply to all related stories for a component, so if you think it would be more difficult to reference by kind, then let's reference files. If there are exceptions to files where it would apply to some stories and not others, that could be noted on those, but for the most part I think it will probably always apply to all in a file. We only have 50 `*.stories.js` files so this list would definitely be much less than the 75 individual stories currently in the IB.

Let's also outline the criteria for which stories should get the modified 0 padding so engineers can also use this to understand why these stories specifically in case there may be exceptions or other additions that qualify after the IB is finalized here.

**Comment by asvinb** [comment] 2021-06-03 10:27
@aaemnnosttv IB updated, let me know if it's better now and more easily readable/understandable.

**Comment by aaemnnosttv** [comment] 2021-06-11 08:20
Much better @asvinb – thank you! 😄 

IB ✅

**Comment by danielgent** [comment] 2021-06-24 12:25
@asvinb Just a query about one point in the IB  `stories/widgets.stories.js only the WidgetArea child stories.` I don't see child mentioned in any of the story names and I don't know enough about the widget API refactor to guess :see_no_evil:

**Comment by danielgent** [comment] 2021-06-24 15:04
![ib says not to do](https://user-images.githubusercontent.com/8496063/123286297-16942c80-d50e-11eb-860f-678c3ae15050.png)

There are a few that overflow when viewed as Small Mobile, but the IB says explicitly not to change these (under `stories/module-adsense.stories.js except:`)

**Comment by danielgent** [comment] 2021-06-24 16:20
I think for the QA It would be worth going through all the stories again viewing as small mobile

**Comment by danielgent** [comment] 2021-06-24 16:22
These stories are mentioned in the IB but they do not render for me, they're all blank for me on develop  :smile: 

![stories do not render](https://user-images.githubusercontent.com/8496063/123298590-f28a1880-d518-11eb-875c-75348e41c7f7.png)

**Comment by eugene-manuilov** [comment] 2021-06-29 14:05
> These stories are mentioned in the IB but they do not render for me, they're all blank for me on develop 
> 
> ![stories do not render](https://user-images.githubusercontent.com/8496063/123298590-f28a1880-d518-11eb-875c-75348e41c7f7.png)

@danielgent those stories seem to be broken. Could you please create a new ticket for it?

**Comment by danielgent** [comment] 2021-06-30 13:02
Ticket created _Broken stories in module-analytics-settings.stories.js_ - https://github.com/google/site-kit-wp/issues/3652

**Comment by danielgent** [comment] 2021-06-30 13:05
TIcket created for broken menu story https://github.com/google/site-kit-wp/issues/3653

**Comment by eugene-manuilov** [comment] 2021-06-30 19:30
@danielgent could you please add QAB?

**Comment by danielgent** [comment] 2021-07-01 07:46
@eugene-manuilov  I had a go! But as we've reverted so much from the IB (and it's pretty subjective as to whether something looks bad or not) I'm not too sure what to put!

Main thing is that nothing is broken

**Comment by Hazlitte** [comment] 2021-07-01 13:25
** QA Eng FAIL **
I realise that some of these examples may not be down to this ticket and may be being addressed elsewhere.  But from following the QA Brief I found small mobile layouts broken due to the extra padding.  Here are example local storybook URLs and screenshots.  In one of them there are errors and the component isn't being displayed at all:

http://localhost:9001/?path=/story/adsense-module-components-dashboard-summary-widget--loaded

http://localhost:9001/?path=/story/adsense-module-components-dashboard-top-earning-pages-widget--loaded

http://localhost:9001/?path=/story/adsense-module-components-module-top-earning-pages-widget--loaded

http://localhost:9001/?path=/story/adsense-module-components-module-overview-widget--loaded

http://localhost:9001/?path=/story/analytics-module-components-module-page-acquisition-channels-widget--loading

http://localhost:9001/?path=/story/analytics-module--use-snippet-switch-toggled-on-default

![Screenshot 2021-07-01 at 14 02 40](https://user-images.githubusercontent.com/5174233/124131650-ebfb2400-da77-11eb-97d6-1fa5dac0984d.png)
![Screenshot 2021-07-01 at 14 04 11](https://user-images.githubusercontent.com/5174233/124131654-ed2c5100-da77-11eb-88f3-0f19215c2599.png)
![Screenshot 2021-07-01 at 14 04 50](https://user-images.githubusercontent.com/5174233/124131656-edc4e780-da77-11eb-8772-7611e692a3cb.png)
![Screenshot 2021-07-01 at 14 05 28](https://user-images.githubusercontent.com/5174233/124131662-ee5d7e00-da77-11eb-93e3-caa5f6a7f570.png)
![Screenshot 2021-07-01 at 14 08 13](https://user-images.githubusercontent.com/5174233/124131664-ee5d7e00-da77-11eb-94ee-e58c2befb830.png)
![Screenshot 2021-07-01 at 14 10 21](https://user-images.githubusercontent.com/5174233/124131669-eef61480-da77-11eb-965a-9ea000990bc4.png)

**Comment by eugene-manuilov** [comment] 2021-07-02 11:01
@tofumatt could you please review #3663?

**Comment by johnPhillips** [comment] 2021-07-13 09:37
## QA - Fail ⛔️

It's tricky to understand which broken stories come from this issue because the code is now in `main`, so comparing local storybook to the one deployed on `main` isn't really helpful. If some of these issues are pre-existing, let me know!

The issues I'm seeing fall into three categories, which I'll go through.

### Errors
I'm seeing a number of stories broken (i.e. erroring). I guess these are highest priority, although I don't know if this issue introduced these breakages.
?path=/story/analytics-module-settings--no-tag-gtm-property-w-access
?path=/story/analytics-module-settings--no-tag-gtm-property-w-o-access
?path=/story/analytics-module-settings--existing-tag-w-access-gtm-property-w-access
?path=/story/analytics-module-settings--existing-tag-w-access-gtm-property-w-o-access
?path=/story/analytics-module-settings--existing-tag-w-o-access-gtm-property-w-access
?path=/story/analytics-module-settings--existing-tag-w-o-access-gtm-property-w-o-access

#### Example
![Screenshot 2021-07-13 at 10 14 56](https://user-images.githubusercontent.com/2470911/125426273-312f4f41-a26e-4451-b8d4-a8593b339682.png)

### Text cut off
There are a couple of stories / components that are broken due to text getting cut off. These might be a higher level of concern as it affects use-ability / readability.

#### Tab text cut off:
?path=/story/settings--settings-tabs
#### Overflow in widgets
(The text is white, so appears cut off when it overflows)
?path=/story/global-widgets-widget-area--special-combination-states

| Tabs | Widgets |
| --- | --- |
| ![Screenshot 2021-07-13 at 10 17 36](https://user-images.githubusercontent.com/2470911/125426766-cf1e3d4f-377f-4bb6-8d1e-190f58515a9a.png) | ![Screenshot 2021-07-13 at 10 18 01](https://user-images.githubusercontent.com/2470911/125426771-fc6cc77a-c316-40b6-b222-17475db21630.png) |

### Text overflow / component issues
I am seeing a number of issues which are due to a handful of particular components breaking in a number of stories rather than the stories themselves being broken or some sort of more global issue. In these cases I think fixing that single breaking component might fix a number of stories. I'm thinking therefore that these could be addressed separately as new issues and are a lower level of concern perhaps?

#### The select dropdown component overflows:
?path=/story/analytics-module-settings--edit-open-with-all-settings
?path=/story/analytics-module-setup--create-new-view
?path=/story/analytics-module-setup--create-account-scope-not-granted
?path=/story/analytics-module--property-select-including-ga4-properties
?path=/story/search-console-module-settings--edit-with-all-settings

#### Data table is still broken:
?path=/story/adsense-module-components-module-top-earning-pages-widget--loaded
?path=/story/analytics-module--top-acquisition-pie-chart

#### As is the spark line overflow
?path=/story/adsense-module-components-dashboard-summary-widget--loaded

#### And the pie chart loader:
?path=/story/analytics-module-components-module-page-acquisition-channels-widget--loading

| Select | Table | Spark line | Pie loader |
| --- | --- | --- | --- |
| ![Screenshot 2021-07-13 at 10 21 15](https://user-images.githubusercontent.com/2470911/125427275-77a13c42-3a68-419c-a6c6-bf5469fab66e.png) | ![Screenshot 2021-07-13 at 09 14 38](https://user-images.githubusercontent.com/2470911/125427308-3426ae15-d252-4de0-9961-7cb6fd687f25.png) | ![Screenshot 2021-07-13 at 09 14 17](https://user-images.githubusercontent.com/2470911/125427341-1d7dde96-f35b-46d2-baeb-9592cf76da0b.png) | ![Screenshot 2021-07-13 at 10 22 31](https://user-images.githubusercontent.com/2470911/125427488-1a439b71-9b72-4ff7-a8e9-6e8c5e1ac2bd.png) |

**Comment by johnPhillips** [comment] 2021-07-13 10:04
Assigning back to you @eugene-manuilov - can you advise on next steps for any of the above?

**Comment by eugene-manuilov** [comment] 2021-07-13 11:16
@johnPhillips the follow-up PR was intended to fix big paddings on mobile screens reported here: https://github.com/google/site-kit-wp/issues/3174#issuecomment-872245769. Regarding errors in stories, they will be fixed in other tickets.

**Comment by aaemnnosttv** [comment] 2021-07-13 11:24
@johnPhillips thanks for your thorough look through the stories. At first glance, it looks like most of this is unrelated to the changes made in this issue/PRs.

Regarding the broken (error boundary) stories: those wouldn't be a result of this issue and fixing those would be out of scope to fix here. We already have an issue to prevent this going forward in #3378 so I don't think we should invest extra time on that here.

As for the oddities you found in the various components, let's save these for follow-up issues as this issue was only about changing the "canvas size" of the story, so perhaps these problems are more visible now, but not directly a result of these changes. This would be good to review on our next sync to see which of these should get an issue and maybe how to group them.

Overall, this is an infrastructural enhancement to bring more consistency between what we see in Storybook and what we see in WordPress. This was a bit off before due to excess padding around the story which caused some components to look different than they otherwise would at the same viewport (particularly mobile). We shouldn't expect that it will all be perfect now but reasonably enhanced overall, then I think we can consider this one a pass. I realize that's maybe a bit subjective, but we have to be a bit more lenient with issues like this with large changes across the codebase.

**Comment by johnPhillips** [comment] 2021-07-13 12:45
@eugene-manuilov and @aaemnnosttv Thanks for the clarification! 

Overall the difference is night and day and this represents a huge improvement to what we previously had - the vast majority of the stories look great now. I just really wasn't sure which breakages had resulted from this and which were unrelated / pre-existing, so I made a list 😅. Even if none of the problems have any bearing on this issue, it's worth capturing them I suppose.

Thanks again. Let's move this across to approval ✅

**Closed** 2021-07-15 19:12 UTC
Labels: Good First Issue, P1, QA: Eng, Rollover, Type: Infrastructure
