### ISSUE TITLE
'Reset Sharing permissions' options not showing inside Dashboard sharing modal when if site is in gathering or zero data state.

### ISSUE THREAD

**Issue by mohitwp** [google/site-kit-wp#6692] opened 2023-03-07 07:08 UTC
## Bug Description

'Reset Sharing permissions' option is not showing under Dashboard sharing modal if site is in gathering or zero data state.

## Steps to reproduce

1. Go to DS sharing modal.
2.  Set DS permissions.
3. Click on Apply.
4. Again, open dashboard sharing option.
5. Notice that 'Reset Sharing Permissions' options is not showing.

## Screenshots

![image](https://user-images.githubusercontent.com/94359491/223349427-269f42a9-9c92-453c-ab7f-795ba5ba5de3.png)

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2023-05-16 20:13
Not able to reproduce this one. 

<img width="1582" alt="image" src="https://github.com/google/site-kit-wp/assets/1621608/a609289d-b18c-4b34-a252-078123beb437">

Closing for now

**Closed by aaemnnosttv** 2023-05-16 20:13 UTC
