### ISSUE TITLE
WP Dashboard Submenu not visible

### ISSUE THREAD

**Issue by derweili** [google/site-kit-wp#6907] opened 2023-04-19 07:57 UTC
On Site Kit Dashboard and Settings Page, the "WP Dashboard" submenu is invisible. Only it's shadow is shown.

<img width="399" alt="Dashboard submenu not shown" src="https://user-images.githubusercontent.com/6911678/233008173-3c3fea9a-1dd4-4bef-8109-a055b8272d2a.png">

## Steps to reproduce:

1. Open Site Kit Dashboard
2. Hover over the "Dashboard" in the WordPress nav.
3. Verify the submenu is not showing up.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The WordPress (and by extension, Site Kit) submenus that appear when hovering the left-hand-side WordPress menu should appear over all "normal" Site Kit content—eg anything that isn't a feature tour/modal/etc.

## Implementation Brief

Upon discovery and an investigation of the current surrounding admin menu bar, admin menu and admin content wrapper `z-index values`, the following findings were made:

* The admin bar, and it's sub menus enjoy the largest z-index value, at `99999`
* The left admin dashboard side/main menu contains the 3rd largest z-index value, at `9990`
* The left admin bars sub menus (on over) enjoy the 2nd largest z-index value, at `9999`
* The main content area (to the right of the admin side/main menu) contains no z-index value, nor are any inherited from it's parent container(s).

The image that follows demonstrates the elements with z-index values that need to be taken into account when applying overly high z-index values within the main content wrap area of the admin dashboard:

![Dashboard ‹ sitekit 10uplabs com — WordPress 2023-07-05 at 1 13 44 PM](https://github.com/google/site-kit-wp/assets/72872375/41c16378-2033-4b14-b458-ad748d62c3b5)

It can be noted from the above image that the following areas need to be respected when considering z-index values within the execution of this ticket:

* The top admin bar and its child menus, at z-index `99999`
* The left most main/side admin menu wrapper, at z-index `9990`
* The left most main/side admin menu sub menus on hover, at z-index `9999`

One should however also keep in mind that it is best practice within WordPress core to retain a 10 step count between z-index layers. 

z-index values `< 9990` should be employed so as not to interfere with important admin menu elements. The issue in this case was an excessive `z-index` value applied to the `<Header>` component within `<DashboardMainApp>`, in this case `9999` (which exceeds that of the admin main/side menu wrapper, which has a value of 9990). 

In a bid to reduce redundancy where repeat high z-index values are required, it likely makes sense to capture this "safe upper" z-index value (and potentially others) as SASS variables during the execution of this ticket.

The following guideline steps take into account the above mentioned information and resolve the issue:

* Locate the applicable SASS file that defines CSS variables, located at `assets/sass/config/_variables.scss`
* Create a new comment section specifically for z-index vars, something like `// Z-index values `
* Create a new variable to hold the z-index value for the sk header, one that can be used within the application without interfering/overlapping with admin elements such as the admin bar, left hand admin menu (including fly out menus) etc. Eg. `$z-index-sk-header: 9980;`
* Locate the applicable SASS file for the `<Header>` component, located at `assets/sass/components/global/_googlesitekit-header.scss`
* Search for the top level CSS selector `.googlesitekit-header`
* Amend the `z-index` CSS property to use the newly defined variable holding the z-index value, and update the property accordingly, i.e `z-index: $z-index-sk-header;`

### Test Coverage

* No new tests need to be added.

## QA Brief

* Install and activate the Site Kit plugin.
* Navigate to the Site Kit dashboard by clicking on the left admin menu labelled "Site Kit", or the "Dashboard" sub menu that appears when hovering over said menu item.
* Once in the Site Kit Dashboard view, hover over the left top most admin menu item labelled "Dashboard" (the core WordPress menu item, not the Site Kit variant).
* Validate that, on hover, the popup/fly-out submenu appears and is no longer hidden beneath/covered by the Site Kit header element. A reference image depicting correct display is to follow.

![Site Kit by Google Dashboard ‹ sitekit 10uplabs com — WordPress 2023-07-19 at 10 27 26 AM](https://github.com/google/site-kit-wp/assets/72872375/c3e2daf3-1511-4ac9-a1d5-9f9615e345eb)

## Changelog entry

* Ensure the WordPress Dashboard submenu can be seen when Site Kit is the current page.

**Comment by aaemnnosttv** [comment] 2023-06-07 16:54
Downgrading this to a P1 since it's not blocking the user from reaching these pages. This is specific to desktop as well because on mobile the sub-menus expand vertically rather than hovering to the side.

**Comment by aaemnnosttv** [comment] 2023-06-29 19:14
Thanks @10upsimon ! Does imply that our header currently has the same z-index as the WP submenu? The IB generally sounds good, however this could potentially have a knock-on effect if there is something else that is currently using `999` that we want to keep the header above, so it's worth doing a quick audit of our other z-index values to make sure we only need to change this one, and what the available range is to use (perhaps we want to allow for something to be above our header and below the submenu at some point).

**Comment by 10upsimon** [comment] 2023-07-05 10:47
Thanks for the feedback and direction @aaemnnosttv I will amend accordingly following a mini audit of x-index.

**Comment by 10upsimon** [comment] 2023-07-05 12:15
@aaemnnosttv (or whoever picks this up) this is now ready for IBR. I've conducted an audit of z-index values that we need to honour, and documented them in the IB.

**Comment by aaemnnosttv** [comment] 2023-07-05 22:38
Thanks @10upsimon ! This is very useful context, especially the annotated screenshot.

My immediate thought is that we potentially paint ourselves into a bit of a corner by leaving no gap between our header's z-index value, and the lowest wp-admin menu value.

Let's follow core's example by using a step of 10 between layers to allow some space in between.

I don't want us to get carried away here, but it would be nice to capture some of this audit that we've done in the form of some CSS variables for z-indexes so we don't need to completely re-audit this plane next time we need to place something. This is more of a nice to have, but should be relatively quick considering this has already been done for the WP elements. Maybe we could extract some of the explicit uses we have to variables for other things in the process.

If this sounds out of scope, it is a little but again I'm only suggesting it as a small extra. We could break this out into its own issue too, but I'm afraid that may not move for a long time 😄 

Finally, please add an estimate whenever you're adding/updating an IB. Thanks!

**Comment by 10upsimon** [comment] 2023-07-11 10:45
@aaemnnosttv I captured the fact that we can and should define a z-index variables section within `_variables.scss` and make use of said newly added `$safe-upper-z-index` variable within `_googlesitekit-header.scss`, but I've not suggested a full on refactor of other values (where applicable) as part of the IB itself, as that feels out of the scope of the issue at hand. 

I will, however, capture my observations around certain high z-index values used within the code base below, and perhaps we can/should open a separate issue to capture more z-index variables and update them accordingly?

### assets/sass/components/adminbar/_googlesitekit-adminbar.scss
```
.googlesitekit-plugin .googlesitekit-adminbar {
    ...
    z-index: 9999;
}
```
- Refers to the drop down menu on the front end of the web site, triggered via the "Site Kit" menu item within the wp admin bar.
- Is considerably lower than the other WordPress sub menu elements within the wp admin bar, which are `99999`
- We should consider storing this wp-admin-bar z-index value as a CSS variable if we want to retain the same rules as core wp admin bar sub menu items.

### assets/sass/components/adminbar/_googlesitekit-wp-adminbar.scss
```
.ab-top-menu > .googlesitekit-wp-adminbar.hover > .ab-item,
	&:not(.mobile) .quicklinks .ab-top-menu > .googlesitekit-wp-adminbar:hover > .ab-item,
	&:not(.mobile) .quicklinks .ab-top-menu > .googlesitekit-wp-adminbar > .ab-item:focus,
	&.nojq .quicklinks .ab-top-menu > .googlesitekit-wp-adminbar > .ab-item:focus {
    ....
    z-index: 10000;
}
```
- Refers to the "Site Kit" admin bar menu on the front end when hovered over, or actively focussed on
- Uses a value different to other wp admin bar elements, which tend to use 99999
- The final computed value is actually not 10000, but instead the 99999 inherited from the admin bar elements, and therefore has no effect
- Consider removing, or replacing with a variable that equals that of the wp admin bar sub item z-index values, currently 99999

### assets/sass/components/surveys/_googlesitekit-surveys-modal.scss
```
.googlesitekit-portal-survey {
    ...
    z-index: 99999;
}
```
- Refers to survey modals
- Will correctly render above most items, as equals upper limit for wp-admin bar
- Could potentially overlap left admin menu fly out sub menus on smaller screens
- Consider updating to `$safe-upper-z-index` value as defined in this tickets IB
- OR if intended to be "above all else" set a new var that is larger than that used by wp-admin bar, i.e 100000

### assets/sass/components/global/_googlesitekit-tooltip.scss
```
.googlesitekit-tooltip-popper.MuiTooltip-popper {
	z-index: 99999;
}
```
- Refers to tooltips
- Will correctly render above most items, as equals upper limit for wp-admin bar
- Do render above survey modals (as designed) as they're likely defined as elements after the survey elements
- Can potentially consider updating to a new var that is larger than that used by wp-admin bar, i.e 100000, as suggested in the survey rule in the section above

-----

I've not done a _complete_ audit on all  z-index values, a I feel that can potentially be done as part of the initial discovery process for a new ticket, would you agree?

**Comment by tofumatt** [comment] 2023-07-11 11:28
@10upsimon Looks good, but can you add an estimate to this one? 🙂

**Comment by 10upsimon** [comment] 2023-07-12 08:06
@tofumatt estimate added, thank you

**Comment by 10upsimon** [comment] 2023-07-12 13:02
Thank you @techanvil , well noted. I've bumped the estimate to 7. Putting back into IBR and over to @aaemnnosttv who did the initial review. 

Thank you for taking the time to give a thorough explanation/instruction above.

**Comment by aaemnnosttv** [comment] 2023-07-13 22:05
> I captured the fact that we can and should define a z-index variables section within `_variables.scss` and make use of said newly added `$safe-upper-z-index` variable within `_googlesitekit-header.scss`, but I've not suggested a full on refactor of other values (where applicable) as part of the IB itself, as that feels out of the scope of the issue at hand.

Thanks @10upsimon. That sounds good to me, and thanks for sharing those other values regarding surveys, adminbar, and tooltips. This is partly what I was getting at, which is that we have a number of things floating around and no central registry of these things which is something that I've been thinking about for a while.

I'm happy to tackle the rest in a follow-up issue where we address this more holistically like you're saying and keep this one focused at the task at hand.

Regarding the IB, using a value like `$safe-upper-z-index` sounds reasonable but is actually difficult to interpret (what does safe mean?) which diminishes the utility. Naming things is hard but in this case I think it's actually easiest to define the variable for the thing it controls. So in this case, it might be something like `z-index-sk-header` or something like that. Eventually, my thought is that we can have all these variables together in the sheet and it will be easy to see where everything is and where something should go. I imagine including references for the important WP-defined values you identified as well, which for now can even be added as comments (again to preserve the effort we've made here). 

So let's go with a single variable here and open an issue to revisit things holistically with some minor refactoring.

**Comment by aaemnnosttv** [comment] 2023-07-17 16:52
IB ✅ 

Thanks for your patience and diligence on this @10upsimon !

**Comment by 10upsimon** [comment] 2023-07-17 22:08
Thanks for _your_ patience @aaemnnosttv 🤣 You've been really helpful in pushing me to ensure that I get the correct state, and I appreciate it a lot, thank you.

**Comment by techanvil** [comment] 2023-07-20 10:52
Hey @10upsimon! Sorry, I should have spotted this one the first time round; it's a bit of a nitpick but worth mentioning nonetheless. Regarding your first point in the QAB:

> - Install and activate the Site Kit plugin, and perform basic configuration such as setting up GA.

Setting up GA doesn't really have any bearing on the issue at hand, and it arguably could be a bit of distraction to mention it here. I'd suggest a simplification of the point e.g.

> - Install and setup the Site Kit plugin.

As time goes on you'll notice that reviewers will make the occasional minor tweak like this themselves to save the extra cycle of Execution/CR, but I figured I'd be explicit about it as the feedback is more useful particularly in relatively early days on the project.

**Comment by 10upsimon** [comment] 2023-07-20 11:54
Thanks @techanvil appreciate the attention to detail here! I've amended accordingly.

**Comment by techanvil** [comment] 2023-07-20 12:06
Top stuff, thanks @10upsimon. Approved 'n merged. :)

**Closed** 2023-07-27 20:54 UTC
Labels: Type: Bug, P1
