### ISSUE TITLE
Analytics dashboard: Referral and social labels inverted

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1553] opened 2020-05-13 13:23 UTC
## Bug Description

As reported in [WP support forums](https://wordpress.org/support/topic/wrong-graphic-label/#post-12827429) the Analytics dashboard within Site Kit is showing inverted labels for referral and social acquisitions.

![image](https://user-images.githubusercontent.com/41326532/81817683-f8938480-9524-11ea-941f-fc610fdd22b4.png)

- Reproducible in support
- Social label within Site Kit is also capitalized compared to other labels 
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by cole10up** [comment] 2020-06-11 07:06
**Tested**

Installed latest SK develop, activated Analytics module. Compared GA with SK, was unable to reproduce.

![image](https://user-images.githubusercontent.com/57115907/84355353-51cbf380-ab77-11ea-90c3-2b3237a7bbb6.png)

Sending to Level 2

**Comment by aaemnnosttv** [comment] 2020-06-22 12:34
@ryanwelcher would you please take a look at this one when you get a chance?

**Comment by felixarntz** [comment] 2020-07-02 01:29
@adamsilverstein I assume this is also covered by #1719? If so, we can close this one as a duplicate and continue the work in #1719.

**Comment by Frisoni** [comment] 2020-07-02 01:47
@felixarntz I opened this topic in WP support forum.
I just tested change ga:medium to ga:channelGrouping as mentioned in https://github.com/google/site-kit-wp/issues/1719 and it solves inverted labels as well.
You can close this one for sure.
Thanks.

**Comment by felixarntz** [comment] 2020-07-02 01:58
Thanks for confirming @Frisoni!

**Closed by felixarntz** 2020-07-02 01:58 UTC
Labels: Group: Escalation, Type: Bug
