### ISSUE TITLE
Add E2E Tests for AMP integration

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#1255] opened 2020-03-16 21:07 UTC
## Feature Description

The plugin currently offers substantial integrations with the official AMP plugin, but there aren't any tests covering this yet.

Let's add a few E2E tests to cover important flows when the plugin is installed with the AMP plugin, both in standard (primary/AMP-first), and paired/secondary AMP configurations.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

There should be e2e tests for the following:
* With primary AMP, opening the homepage must not yield validation errors (green check mark in admin bar).
* With primary AMP, in the frontend the Site Kit admin bar opens when hovering over it.
* For Tag Manager setup:
    * If primary AMP, the container field should be for an AMP container.
    * If secondary AMP, there should be two container fields, one for non-AMP, one for AMP.

To all the tests the following should apply: only AMP plugin and Site Kit active, plus an AMP compatible theme like a core theme.

#### Infra
* Update `bin/local-env/install-wordpress.sh` to unconditionally install the latest `amp` plugin (without activating)

#### AMP-specific Tests
* Add a new test to `tests/e2e/specs/amp/admin-bar.test.js` to ensure that the admin bar hover works and app renders with primary AMP active
    - The `e2e-tests-admin-bar-visibility` utility plugin can be activated to force the admin bar item to display.
* Add a new test to `tests/e2e/specs/amp/home-validation.test.js` to ensure that the homepage has no validation errors with primary AMP active (with no additional modules activated)

#### Module Setup Cases
* Add a new test to `tests/e2e/specs/modules/analytics/setup-with-account-no-tag.test.js` to check for AMP validation errors on the homepage after finishing setup with primary AMP
* Add a new test to `tests/e2e/specs/modules/tagmanager/setup.test.js` to ensure that the proper container dropdowns are rendered in the following cases:
    - No AMP (Web Container only)
    - AMP primary (AMP Container only)
    - AMP secondary (Web Container and AMP Container both show)  
* Add a new test to `tests/e2e/specs/modules/adsense/setup-new-user.test.js`
* Add a new test to `tests/e2e/specs/modules/optimize/activation.test.js` to ensure AMP experiment JSON input is shown and validated
* The setup should complete successfully in each added case
* For the added AMP cases, the homepage should also be checked for validation errors after each successful set up (we may need to add a utility to clear the cached validation by the plugin between tests)  
This is important to do per-module as each module adds different snippets to the HTML so we should check the validity for each

#### Testing AMP Validation
We should test both that the output is valid AMP while logged-in, and not logged-in.

* For logged-in, we can navigate to the page, and check for the validity in the Admin Bar, added by the AMP plugin
* For non-logged-in, we can `fetch` the HTML for the URL we want to check, and pass it to the [official amp validator](https://www.npmjs.com/package/amphtml-validator)  
    This should only be used to check the validity for non-logged-in users as the AMP plugin's validator is better suited to handle exceptions which are only present when logged-in, such as dev-mode.  
    We can probably abstract this into a custom matcher with Jest so we can do something like `expect( URL ).toHaveValidAMP()`. We already have a place to add them here: `tests/e2e/matchers/index.js`

> Note: "primary" AMP is a Site Kit term. The AMP plugin refers to this as "AMP-first" and is the "Standard" mode in the plugin's settings.

## QA Brief

* 

## Changelog entry

* N/A

**Comment by felixarntz** [comment] 2020-04-07 15:10
@aaemnnosttv Let me know if there's anything else (other than what I added in the ACs) you think we should cover in e2e tests here.

**Comment by aaemnnosttv** [comment] 2020-04-07 17:30
* We need to update the E2E provisioning script to support installing the AMP plugin 😄 
* These tests should also probably have their own E2E job added in the Travis matrix. Maybe we can replace the job with Gutenberg now that we don't have any shared dependencies with it?
* We can add tests to check that tags are output properly (perhaps this should be a separate issue for an additional PHPUnit suite)
* Add tests for existing tags in module setup flows?

**Comment by felixarntz** [comment] 2020-04-07 19:18
@aaemnnosttv 
> * We need to update the E2E provisioning script to support installing the AMP plugin 😄
Right, I think that should go into the IB.

> * These tests should also probably have their own E2E job added in the Travis matrix. Maybe we can replace the job with Gutenberg now that we don't have any shared dependencies with it?

I'd prefer to add them to the 3 existing jobs. We'd simply only activating the AMP plugin for the specific tests where we need it. The Gutenberg job should be maintained, it's less unlikely to cause errors now, but still relevant.

> * We can add tests to check that tags are output properly (perhaps this should be a separate issue for an additional PHPUnit suite)

Yeah, I think that's not so much e2e test territory.

> * Add tests for existing tags in module setup flows?

Those are valid to be tested, but I'd say not as part of this issue. The existing tag detection taking AMP into account relies on a single function, so potentially this could even be a single Jest test with mocks to see if it works. Either way, that part is less critical than the more AMP compatibility specific coverage to prevent regressions.

**Comment by tofumatt** [comment] 2020-04-09 00:07
I've got nothing else to add—I agree that it's worth keeping the Gutenberg test around, but the test approach/proposed tests here look good, so IB ✅ from me.

Since @felixarntz and are both assigned I'll leave this assigned to him to review as well, but this sounds good to me. 👍

**Comment by felixarntz** [comment] 2020-04-09 14:52
@aaemnnosttv 
> Add a new test to `tests/e2e/specs/modules/analytics/setup-with-account-no-tag.test.js` to check for AMP validation errors on the homepage after finishing setup with primary AMP

You say further below we should do this everywhere. I'm not sure we should put these tests into any module-specific test suite, I think this could be something like `amp-compatibility` on the root level.

**Comment by aaemnnosttv** [comment] 2020-04-10 07:46
> The setup should complete successfully in each case

I just meant that the set up should still complete successfully in each case where we test for it. Definitely not everywhere.

I thought about putting the tests together, and maybe we should do that. My thinking was that most everything else about the test will be the same as other existing tests, other than activating the plugin. Adding cases to the existing files would be the smaller change and would have the context of the other tests around it. Having specific targeted tests separate in an AMP directory might make them harder to reason about.

One reason why I would advocate against putting them all in a separate directory in the root is that right now we can run `npm run test:js -- tests/e2e/specs/modules/analytics/setup-*` to run all of the setup tests for that module.

I can see how we would want to be able to do the same thing for all AMP tests as well. Perhaps we could add [`jest-runner-groups`](https://www.npmjs.com/package/jest-runner-groups) to get around this limitation? That way it wouldn't matter as much where tests are placed, we could run named groups of tests together, similar to what we can do in PHPUnit.

**Comment by tofumatt** [comment] 2020-04-10 11:20
> Having specific targeted tests separate in an AMP directory might make them harder to reason about.

My take is that I agree with this, and would prefer tests for particular components (like analytics) to have variations on setup based on AMP being on/off… not a section of AMP tests with tests for several, different modules in them.

I think of the test placement as being targeted, testing the "inner-most" thing in question. For this: it's analytics setup, but with the variation that AMP is disabled or enabled. I think it's better to think of it as an analytics test, not an AMP test.

**Comment by felixarntz** [comment] 2020-04-10 15:23
@aaemnnosttv @tofumatt The module-specific AMP tests should certainly be in that module's directory. But there are general AMP tests that are not related to any module. For example, if the admin bar displays and if it opens on hover in the frontend on AMP, that doesn't have to do anything with modules.

**Comment by aaemnnosttv** [comment] 2020-04-14 09:09
> For example, if the admin bar displays and if it opens on hover in the frontend on AMP, that doesn't have to do anything with modules.

That's not really the case though since the Admin bar is only displayed if the modules inside have data. As such the only E2E tests we have related to the admin bar are in Analytics and Search Console module tests respectively.

**Comment by felixarntz** [comment] 2020-04-14 15:47
> That's not really the case though since the Admin bar is only displayed if the modules inside have data. As such the only E2E tests we have related to the admin bar are in Analytics and Search Console module tests respectively.

That's true, but whether the admin bar is displayed or not is determined in PHP. What we need to test here for AMP is entirely module-independent, we need to test whether the admin bar menu opens on hover as expected and shows Site Kit UI - we could add an e2e PHP plugin to force it to be active.

**Comment by aaemnnosttv** [comment] 2020-04-14 18:32
Good point.

> we could add an e2e PHP plugin to force it to be active

We actually [already have one](https://github.com/google/site-kit-wp/blob/d0c0d9dc0f89e8516d17eb8b78d600a1780130ac/tests/e2e/plugins/admin-bar-visibility.php) 😄

To your point, for tests which are specific to AMP compatibility and not related to any other tests, I think it would be fine to put these in an `amp` directory of some kind.

IB updated to include other details per our discussion as well.

**Comment by felixarntz** [comment] 2020-04-14 18:45
IB ✅

**Comment by aaemnnosttv** [comment] 2020-05-27 17:42
CR ✅ but this won't be merged until after the release. Assigning to @felixarntz for now.

**Comment by cole10up** [comment] 2020-06-16 15:33
**Tested**

From a terminal session I ran the following tests:
tests/e2e/specs/amp/admin-bar.test.js
![image](https://user-images.githubusercontent.com/57115907/84793827-690d4580-afaa-11ea-8989-a019f5dc359b.png)

tests/e2e/specs/amp/home-validation.test.js
![image](https://user-images.githubusercontent.com/57115907/84793667-40854b80-afaa-11ea-90b4-ef83d419504d.png)

tests/e2e/specs/modules/analytics/setup-with-account-no-tag.test.js
![image](https://user-images.githubusercontent.com/57115907/84794024-9f4ac500-afaa-11ea-9ea7-ce53a29b5b23.png)

tests/e2e/specs/modules/tagmanager/setup.test.js

Note the console error:
![image](https://user-images.githubusercontent.com/57115907/84794540-3748ae80-afab-11ea-88d6-1ae377e7f7c1.png)

tests/e2e/specs/modules/adsense/setup-new-user.test.js
Note the console errors:
![image](https://user-images.githubusercontent.com/57115907/84794800-8c84c000-afab-11ea-9777-47a591e1d02d.png)

tests/e2e/specs/modules/optimize/activation.test.js
![image](https://user-images.githubusercontent.com/57115907/84795225-0d43bc00-afac-11ea-85cb-bac24d29bedf.png)

Passed QA ✅

**Closed** 2020-06-18 17:41 UTC
Labels: P1, Type: Enhancement
