### ISSUE TITLE
Fix Tag Manager `useExistingTagEffect` to properly work in case of primary AMP

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5044] opened 2022-04-06 20:04 UTC
The latest `useExistingTagEffect()` implementation always looks at the `containerID` module setting. However, in case of primary AMP, only the `ampContainerID` setting is set, and the hook should rely on that in such a case.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

**Relying on the `feature/existing-tag-simplification` branch:**

* The `modules/tagmanager` store should receive a new selector `getPrimaryContainerID()`.
    * If the site is using primary AMP (see `core/site` `isPrimaryAMP()` selector), the selector should return the value of `getAMPContainerID()`.
    * Otherwise (i.e. either no AMP or secondary AMP), the selector should return the value of `getContainerID()`.
    * In case any of the relevant selectors are still "loading" (i.e. returning `undefined`), the new selector should also return `undefined`.
* The Tag Manager `useExistingTagEffect()` hook should be fixed to also support AMP. Basically, instead of relying on `getContainerID()`, it should rely on the above `getPrimaryContainerID()` so that it works for either case.

## Implementation Brief

**Any PR for this must be based on and target the `feature/existing-tag-simplification` branch.**
* Using `assets/js/modules/tagmanager/datastore/containers.js`,
	* Add a new selector `getPrimaryContainerID` which should do the following:
		* Check if primary AMP is being used by querying the `core/site` datastore via the `isPrimaryAMP` selector.
			* If that is the case, then return the value of `getAMPContainerID` selector of the module.
			* Else return the value of `getContainerID` selector of the module.
		* Return `undefined` if the calls to above selectors return `undefined`, i.e are still in a "loading" state.
* Using `assets/js/modules/tagmanager/hooks/useExistingTagEffect.js`,
	* Replace `getContainerID` selector call with `getPrimaryContainerID` selector to get the container ID.

### Test Coverage
* Tests to be added for the new selector.

## QA Brief

* Connect AMP Plugin and set it as Primary. 
* All the behaviors from #4713 should still work like before. See it's QA Brief For Details. 
* Also Test WITHOUT AMP Primary.
* **Update**: To force a site in AMP Primary mode:
    *  Install AMP Plugin and set it up as Standard Mode. 
    * Add The AMP Existing Tag via a mu-plugin.
````php
<?php

const GTM_CONTAINER_ID = 'GTM-PNW4ZWH'; 

/**
 * Print amp-analytics.
 */
function add_amp_tag_manager() {
	printf(
		'<amp-analytics config="https://www.googletagmanager.com/amp.json?id=%s" data-credentials="include"></amp-analytics>',
		esc_attr( GTM_CONTAINER_ID )
	);
}

add_action(
	'wp_footer',
	function () {
		if ( function_exists( 'is_amp_endpoint' ) && is_amp_endpoint() ) {
			add_amp_tag_manager();
		}
	}
);

add_action( 'amp_post_template_footer', 'add_amp_tag_manager' );
````

* Go to Tag Manager Setup Page 
* Run this code in console.
````js
googlesitekit.data
	.dispatch( 'core/site' )
	.receiveSiteInfo( {
		...( await googlesitekit.data
			.__experimentalResolveSelect( 'core/site' )
			.getSiteInfo() ),
		ampMode: 'primary',
	} );
````
* Now when the selected `AMP Container` is the same as the Existing AMP Tag (Selected via dropdown) the snippet toggle will be disabled and vise versa. 

## Changelog entry

* Update the Tag Manager `useExistingTagEffect` hook to use AMP container ID when in the primary AMP mode.

**Comment by eugene-manuilov** [comment] 2022-04-07 10:40
IB ✔️

**Comment by wpdarren** [comment] 2022-04-21 11:39
### QA Update: ⚠️ 

We are unable to QA [this ticket](https://github.com/google/site-kit-wp/issues/5118) until this ticket is merged. On hold.

**Comment by wpdarren** [comment] 2022-04-25 15:35
### QA Update: ⚠️ 

@kuasha420 as per Slack, when I run the code only one container dropdown appears which has the AMP selection. The web container has disappeared.  The toggle does disable because the AMP selected is the same container ID in my mu-plugin.  

Here's what happens when you do not select any options but run the code

https://user-images.githubusercontent.com/73545194/165122792-a6f19915-189b-4a57-b67c-4e2176d1d880.mp4

This is what it looks like if you select the account, web and amp container and run the console code.

<img width="1270" alt="amp" src="https://user-images.githubusercontent.com/73545194/165122904-77d5f828-bfc8-42b8-b699-1cfae1ce883e.png">

This doesn't feel like it's expected behaviour, but I know we're hacking this a little so would like to check.

**Comment by wpdarren** [comment] 2022-04-26 12:40
### QA Update: ⚠️ 

@kuasha420 just another check before I approve this.  This is not specific to primary AMP, but more of an observation. Is there a scenario where a user could have AMP plugin installed and when setting up tag manager, selects only an account and web container, and leaves AMP container blank?  I have just tried this and the confirm and continue button is disabled. 

<img width="1268" alt="amp-1" src="https://user-images.githubusercontent.com/73545194/165301788-a9ce7763-534d-4299-8a28-a80a15d8a0d0.png">
 
I am not overly up with how tag manager works in this scenario.

Any thoughts?

**Comment by kuasha420** [comment] 2022-04-26 12:56
@wpdarren It's the same behavior in `develop` so I think it's correct. You must select (Or create new one/both) to be able to more forward. Cheers!

![Screenshot_20220426_185426](https://user-images.githubusercontent.com/6187401/165304660-4ca964e6-e130-407c-b074-cc136fef037f.png)

**Closed** 2022-05-19 16:23 UTC
Labels: P0, Type: Enhancement, Module: Tag Manager, Rollover
