### ISSUE TITLE
Connect TwG REST publications endpoint with actual API and add scope

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5534] opened 2022-07-08 19:04 UTC
The TwG `GET:publications` data point was scaffolded with dummy data in #5449. Once the actual Google TwG API endpoint is available for us to use, the endpoint should be updated in this issue to issue a request to the API.

This issue is effectively blocked until the TwG API endpoint for publications has been launched.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The TwG `GET:publications` endpoint needs to be adjusted to send a request to the above endpoint using the corresponding resource class from the API client service (instead of returning dummy data).  
Details on the request:
    - For now it should return all publications, although in the future, it will be amended to return a subset
    - The response should (like other list methods of a service resource) return just the resource (publications)
* The TwG module PHP class should receive a `https://www.googleapis.com/auth/subscribewithgoogle.publications.readonly` scope that it requires.

## Implementation Brief

* Update the `Thank_With_Google` module class:
    - Implement the `Module_With_Scopes` interface, and returning the scope from the ACs in the array returned by the `get_scopes` method
    - Update the datapoint definition for `GET:publications` to reference a new `subscribewithgoogle` service
    - Implement the `setup_services` method, with a single mapping of `subscribewithgoogle` of the `Google_Service_SubscribewithGoogle` class (added in #5650)
    - Update the `GET:publications` handler in `create_data_request` to return the request for `subscribewithgoogle->publications->list`
        - Leave a TODO for the filtering that will be implemented later
        - Update the corresponding handler in the `parse_data_response` to return just the publications
* Merge https://github.com/google/site-kit-wp/pull/5652

### Test Coverage

* No changes necessary

## QA Brief

**Note this will not work until #5650 is merged as well**

* Ensure the tester plugin is not configured to force anything for TwG
* ~~Using the staging proxy for a site's connection enable TwG~~ (this can now use production)
* Ensure activating TwG prompts to grant additional scopes
	* No additional permissions modal should pop-up for it afterwards
* When setting up the TwG module, observe the request for `publications` (note not everyone may have publications yet so you may need to request help getting one created for you or to be added to one)
    * You should see real publications from the API

## Changelog entry

* Add Thank with Google API functionality and scopes.

**Comment by techanvil** [comment] 2022-08-04 10:15
IB :white_check_mark:

**Comment by wpdarren** [comment] 2022-08-05 12:01
@aaemnnosttv please could you send me the plugin we can use for the staging proxy? Had a quick search and couldn't find anything but it has been a while.  Could you also add me to a publication for my Google account email address. Thanks!

**Comment by felixarntz** [comment] 2022-08-08 16:01
@aaemnnosttv What did the response shape for the publications request look like when you tested this? I'm asking since there have been several changes in the API field names since the original definition, and everything on our end (design doc, plugin, tester plugin) currently still uses the old names. That's why I was originally intending to make this issue and its ACs also about adjusting the field names in the relevant places (not really relevant on the PHP side, but critical for the JS side).

Maybe those additional changes haven't even been published to the API endpoint yet, but if they have, then this #5652 may have broken something without also adding the field name changes to the JS codebase. Can you check please?

In any case, we should probably open a separate issue then to monitor those changes, and also to eventually implement https://github.com/google/site-kit-wp/pull/5652/files#diff-f484944f8f737a196b627b845da4d99e5ebc0959adb9eb27b21fdb695b3e079eR244.

**Comment by aaemnnosttv** [comment] 2022-08-08 21:35
@felixarntz it looks like this:

```json
[
    {
        "publicationId": "ABcde6g8Ij",
        "displayName": "Evan's Site Kit Test Site",
        "verifiedDomains": [
            "example.com"
        ],
        "publicationPredicates": {
            "businessPredicates": {
                "canSell": true,
                "supportsSiteKit": true
            }
        },
        "paymentOptions": {
            "thankStickers": true
        },
        "onboardingState": "ONBOARDING_COMPLETE"
    }
]
```

Is this the final shape? I see `state` seems to be `onboardingState`, `virtualGifts` seems to be `thankStickers`, and the whole `publicationPredicates` seems to be new. I'm guessing our endpoint would only return those that `supportsSiteKit` as well (in #5653)?

**Comment by aaemnnosttv** [comment] 2022-08-09 02:20
## QA ⚠️ 

Bringing this back to fix something that was missed here which is the cause for #5664.

**Comment by felixarntz** [comment] 2022-08-09 07:27
@aaemnnosttv Correct, the `onboardingState` and `thankStickers` changes are the ones relevant to us. Note also that the possible values for `onboardingState` are at least partially different (what used to be `ACTIVE` is now `ONBOARDING_COMPLETE`). Any other changes shouldn't matter really because we don't use them.

> I'm guessing our endpoint would only return those that `supportsSiteKit` as well

We should return those that have both `supportsSiteKit` and `thankStickers` set and `true`.

Regarding the next steps here: As I mentioned before, this change now can technically break our implementation. Should we let that go through for now and fix the name changes and additional filtering required in a follow-up issue?

**Comment by wpdarren** [comment] 2022-08-09 09:48
@aaemnnosttv I thought I would try set this up on the site you set me up a publication for, and I see an error.  This was on develop branch and on production, rather than staging. Is this expected?

`Error: The response is not a valid JSON response.`

![image](https://user-images.githubusercontent.com/73545194/183618775-23af1032-da08-4214-b1e8-72bc116c21c6.png)

**Comment by felixarntz** [comment] 2022-08-09 12:23
@aaemnnosttv @eclarke1 Due to the API changes on the TwG side, there are now three follow-up issues for this (each rather small fortunately):
* #5653 
* #5669 
* #5671 

The first two are ready for IB. The last one still needs ACs and is waiting as we have to double check with the TwG API team how this is supposed to work.

**Comment by wpdarren** [comment] 2022-08-09 12:39
@felixarntz should we hang-fire testing this ticket until those tickets are merged or should I still be able to go through the QAB tasks successfully at this point?

**Comment by aaemnnosttv** [comment] 2022-08-09 16:51
@wpdarren I've opened one more PR to fix the JSON error that happens when a user has no publications.

**Comment by aaemnnosttv** [comment] 2022-08-09 19:13
@wpdarren should be good to go now 👍

**Comment by wpdarren** [comment] 2022-08-10 09:46
### QA Update: ⚠️ 

@aaemnnosttv I'm not getting the API error anymore but here is the behaviour I am seeing.  With no `Google publication status` set in the tester plugin, the `Create your Thank with Google account` splash screen appears. When I click on the 'Create account' button I am redirected to the Publisher Center.   I can see my publication there:

![image](https://user-images.githubusercontent.com/73545194/183868993-51c6cee6-7c75-4459-841c-73e93eda15f1.png)

When I go back to my site, and the splash page loading animation appears and then `Create your Thank with Google account` splash screen reappears.  Looking at the QAB:

> Ensure activating TwG prompts to grant additional scopes

I do not see any prompt to grand additional scopes. 

> When setting up the TwG module, observe the request for publications. You should see real publications from the API.

As per my observations above, all that happens is I am redirected to the publication center, with my publication. Is this expected, or, should I see something else within Site Kit?  

Recorded a screencast below:

https://user-images.githubusercontent.com/73545194/183870933-bfe5eb32-559a-46b3-9f01-90b89308ff86.mp4

**Comment by aaemnnosttv** [comment] 2022-08-10 18:19
> > Ensure activating TwG prompts to grant additional scopes
> 
> I do not see any prompt to grant additional scopes.

@wpdarren this is likely due to the scopes already granted – you can check this in Site Health:

![image](https://user-images.githubusercontent.com/1621608/183986275-4bc3b6a0-ef17-473d-b79b-c91da6602950.png)


If TwG was already active when you signed in then you would have granted these at that time. If that's not the case then maybe you're not on the most recent version?

I double checked this locally and with TwG inactive, I disconnected and reconnected. When activating TwG it prompted to grant scopes as expected.
 
> > When setting up the TwG module, observe the request for publications. You should see real publications from the API.
> 
> As per my observations above, all that happens is I am redirected to the publication center, with my publication. Is this expected, or, should I see something else within Site Kit?

You don't need to go to the publisher center, you only need to observe this in the console:

![image](https://user-images.githubusercontent.com/1621608/183986634-bab46ca9-5cf0-4dd0-a99e-8d7a9aff86bb.png)

In your case, you'll may need to confirm the publication's site verification if you haven't done this before (to do this go to the publication's settings in the publisher center) in order for it to show up in the request that SK makes.
<img width="318" alt="image" src="https://user-images.githubusercontent.com/1621608/183987096-8267df52-5a24-4238-ac1e-313d9b02bf33.png">

**Comment by wpdarren** [comment] 2022-08-11 02:54
### QA Update: ✅ 

@aaemnnosttv thank you for the additional information! 

**Verified:**

- When activating TwG prompts appear to grant additional scopes
- No additional permissions modal pop-up for it afterwards giving permission. 
- Setting up the TwG module, observed the request for publications
- Looking at the nwtwork tab within console, I see real publication from the API

![image](https://user-images.githubusercontent.com/73545194/184057368-317e6715-4a63-4630-84d3-5a83b977edf3.png)

**Closed** 2022-08-11 18:45 UTC
Labels: P0, Type: Enhancement, Module: Thank with Google
