### ISSUE TITLE
An error occurred: invalid Analytics redirect URI during Site Kit setup

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#2771] opened 2021-02-08 18:31 UTC
A number of users have recently reported encountering the below error message:
`An error occurred: invalid Analytics redirect URI
`
This started occurring just over one month ago, with the follow users impacted:
- [An error occurred: invalid Analytics redirect URI](https://wordpress.org/support/topic/an-error-occurred-invalid-analytics-redirect-uri/) - Resolved (possible site reset)
- [invalid Analytics redirect URI](https://wordpress.org/support/topic/invalid-analytics-redirect-uri/) - Open ([SH info provided](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNipvsEoOfslJFwsiPCZciXy87v2zm5FMmCkSrmEXsuzbtCotf8d_oaix6LPhgnz8BQ))
- [An error occurred: invalid Analytics redirect URI](https://wordpress.org/support/topic/an-error-occurred-invalid-analytics-redirect-uri-2/) - Open
- [An error occurred: invalid Analytics redirect URI](https://wordpress.org/support/topic/an-error-occurred-invalid-analytics-redirect-uri-3/) - Open
- [An error occurred: invalid redirect URI](https://wordpress.org/support/topic/an-error-occurred-invalid-redirect-uri/#post-14041389) - Open ([Site Health info](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/edit#response=ACYDBNhx-Pe1QNTtmLqHgCwo6i4MeXOvtwYWLz_KJ_Hb-CyLu-SsN9MjsORieg35iWOC-Do))

This issue occurs during Site Kit setup, and not specifically when connecting the Analytics module. 

## Screenshots

![Setup - Site Kit by Google 2020-12-24 06-44-30](https://user-images.githubusercontent.com/41326532/107264480-ec4c4180-6a3a-11eb-8e1d-ae32bc10b091.png)

[Video demonstrating issue
](https://drive.google.com/file/d/1EAZKaVk7RQ6YrZAGFBcFsH4pYpS3Agv8/view)

## Additional Context

 - Started occurring from Site Kit 1.23.0
 - Sites Impacted seem to have existing Analytics code added prior to setting up Site Kit
 - [One user](https://wordpress.org/support/topic/an-error-occurred-invalid-analytics-redirect-uri/) was able to proceed, although it may have involved their site being reset
 - Awaiting additional insights from impacted users

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment] 2021-02-09 09:45
One user shared their console errors encountered during setup, AMP related 400 proxy errors:

![image](https://user-images.githubusercontent.com/41326532/107345224-42f96000-6abb-11eb-9e22-bac2ce8eb86c.png)

**Comment by abdullah1908** [comment] 2021-02-11 18:41
Unable to reproduce at my end.

Activities done so far:
- Copied the [analytics script](https://developers.google.com/analytics/devguides/collection/analyticsjs) & pasted in <head> tag. Created the property & pasted in the relevant place.
- After that I setup Site Kit & configured Analytics. I didn't find any issue. Everything worked smoothly.

**Comment by jamesozzie** [comment] 2021-02-15 10:28
We now have the SH information from 2 impacted users. Observations on these 2 site setups:
- Different hosting providers
- No matching plugins or theme
- One impacted user has a connected "Domain type" Search Console property, the other no connected Search Console property
- One user has additional .htaccess rules
- Both PHP 7.4 upwards and cURL (7.71.1 & 7.68.0)

Once user encounters the below in their SH overview (not included in the SH output)
```
The REST API request failed due to an error.
Error: cURL error 35: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error (http_request_failed)
```
Despite the above REST endpoints for this over are accessible on the front end

**Comment by bethanylang** [comment] 2021-02-23 18:22
@abdullah1908 Can you please test again with the additional information that James has provided? Thank you!

**Comment by abdullah1908** [comment] 2021-02-23 18:30
Sure @bethanylang 👍

**Comment by abdullah1908** [comment] 2021-02-24 18:41
Couldn't recreate this issue at the CDN enabled website. Better to move in L2.
cc: @jamesozzie @bethanylang

**Comment by bethanylang** [comment] 2021-02-24 18:45
Thanks for reviewing again, @abdullah1908. changed to L2.

**Comment by adamsilverstein** [comment] 2021-03-10 19:07
I was not able to reproduce this in my testing so far. @jamesozzie have you noticed any common pattern among the users reporting this issue?

**Comment by jamesozzie** [comment] 2021-03-11 11:10
@adamsilverstein No common occurrences unfortunately. One site previously had mismatching URLs,  another site using an SSL Cert with Cloudflare. Undetermined is users had previously site setups before changing URLs,  I did raise a couple of questions with a couple of impacted users just now, asking if they had successfully setup Site Kit previously. Once the reset button is visible it would be interesting to know if they allows them to proceed.

**Comment by felixarntz** [comment] 2021-04-27 17:34
@adamsilverstein Any update on this one? It just came up in our triage meeting, that's why I'm asking.

**Comment by adamsilverstein** [comment] 2021-04-28 01:17
I'll take another look. @jamesozzie or @abdullah1908 - can you confirm - have users tried resetting since we made that available and that hasn't helped?

**Comment by jamesozzie** [comment] 2021-04-28 11:49
@adamsilverstein I've just followed up with the 3 remaining open support topics, proposing they perform the same check. I'll update you here should I have any updates. 

There haven't been any additional reports since February and previous attempts to troubleshoot with the impacted users have been unsuccessful.

**Comment by bethanylang** [comment] 2021-04-28 13:04
Thanks @adamsilverstein and @jamesozzie. If we don't get anything back from those users in the next week or two, let's close this issue out. We can always reopen if it's reported again.

**Comment by aaemnnosttv** [comment] 2021-06-15 09:38
@bethanylang @jamesozzie @adamsilverstein any update on this?

**Comment by jamesozzie** [comment] 2021-06-15 09:49
@aaemnnosttv No response from the impacted users, and unable to recreate in support. With no recent reports maybe we should close this one @bethanylang

**Comment by bethanylang** [comment] 2021-07-12 15:15
@jamesozzie Closing.

**Closed by bethanylang** 2021-07-12 15:15 UTC
Labels: P0, Type: Bug, Type: Support
