### ISSUE TITLE
Conflict with Visualizer plugin

### ISSUE THREAD

**Issue by LeonNabuurs** [google/site-kit-wp#3560] opened 2021-06-11 09:23 UTC
## Bug Description

I created a page on my website containing 2 charts made via Visualizer plugin. In Divi Visual Builder the charts show up normally, but when I visit the page in incognito mode the charts are not shown. The console indicates there is an error 'google is not defined'

## Steps to reproduce

1.Since this is a live website it is not possible to leave this page open for public now

## Screenshots

![image](https://user-images.githubusercontent.com/20581086/121663460-b9788f80-caa6-11eb-9d0c-5edf41b1430d.png)
## Additional Context
When I deactivate the Site Kit Google Plugin, it all works fine

 The issue occurs on all browsers
 It happens with actual versions of the plugins: Sit Kit Google (version 1.34.0) and Visualizer (version 3.5.1)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

### Test Coverage

* 

### Visual Regression Changes

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment] 2021-06-11 09:35
Thanks for reaching out. While this does seem like a potential bug we'd be be happy to check this and communicate through the WordPress support forums before revisiting this GitHub issue, where we perform initial support and troubleshooting before escalating here. 

If you'd like to open a [new support topic](https://wordpress.org/support/plugin/google-site-kit/#new-post) there we'd be happy to assist. That way you can also share your site URL or Site Health information via [this form](https://docs.google.com/forms/d/1lhjns2K7c0Ny7ME4gxTcsnYtNUtcMr8BvFpPQi23Y1E/), referencing the newly created support topic. This form is private, your site URL won't be publicly visible.  

I'll keep this GitHub issue open in the meantime while trying to recreate this on my side.

**Comment by jamesozzie** [comment] 2021-06-15 10:38
Testing done with 8 of the 12 chart types on a clean WP install. Unable to reproduce the same issue so far. 

Console error - support testing
```
render-google.js?ver=3.5.1:317 render.getImageURI not defined for visualizer-1422
(anonymous) @ render-google.js?ver=3.5.1:317
```

_Console error that appears (Site Kit deactivated)_ - Support testing

![image](https://user-images.githubusercontent.com/41326532/122036195-33708780-cdcb-11eb-94b1-4e848fc38e91.png)

_Google Charts Library request (Site Kit deactivated)_ - Support testing

![image](https://user-images.githubusercontent.com/41326532/122036428-75013280-cdcb-11eb-8b29-7b25bb1b3e18.png)

_GeoChart error in defautl editor (Site Kit deactivated)_ - Support testing

![image](https://user-images.githubusercontent.com/41326532/122036748-d1fce880-cdcb-11eb-9d45-b4601db41908.png)

Users console errors on the site where this is occurring

![image](https://user-images.githubusercontent.com/41326532/122037678-b8a86c00-cdcc-11eb-84c1-6e77c83190c7.png)


## Steps to reproduce


1. Setup a chart (pie chart for example) on a site with SK active
2. Using Chrome on occasions doesn't display the charts

## Screenshots



## Additional Context


 - Site Kit 1.34.0
 - Visualizer 3.5.1
 - All charts tested - on support side unreproducible, although console errors do appear with and without SK active
 - Unable to load GeoChart library in default editor
 - All testing done with default sample csv files (included with each chart)
 - On another users site the same charts appear fine
 - On the 1 website where this is occurring for the user there are also Divi theme console errors
 - The same occurs when using the Health Check & Troubleshooting plugin for the impacted user
 - Unable to reproduce in support so far

**Comment by jamesozzie** [comment] 2021-07-02 13:39
Closing as unreproducible. Comments added to the [related support topic](https://wordpress.org/support/topic/conflict-with-visualizer-plugin/#post-14619843).

**Closed by jamesozzie** 2021-07-02 13:39 UTC
Labels: Type: Support
