### ISSUE TITLE
Responsive design - IOS Safari

### ISSUE THREAD

**Issue by AlexandreOrlowski** [google/site-kit-wp#1376] opened 2020-04-11 22:49 UTC
Je trouve bien dommage de ne pas avoir intégré les statistiques de Google My Business. Un plus serait que l’extension soit responsive design.
![site-kit](https://user-images.githubusercontent.com/14998252/79056490-6a8f5a00-7c57-11ea-959a-b8afda70dfa9.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Tables in Safari on iOS should display correctly, without overlapping columns UI.

## Implementation Brief

* For **mobile screen sizes**, update CSS for tables
* Reduce left and right padding on `.googlesitekit-table__body-item` to 4px.
* In `getDataTableFromData` add extra CSS class for `<td>`s that contain numeric data.
* For numeric `<td>`s, center align text:
* Reduce right padding on `.googlesitekit-table__body-item:last-child` last child from `16px` to `0`.
* Add `overflow: hidden;` and `text-overflow: ellipsis;` to `.googlesitekit-table__head-item`.
* Update mobile tables for Analytics to hide `Unique Pageviews` and `Bounce Rate` columns on small screens.

## QA Brief

* 

## Changelog entry

* Fix table content overflow issues in narrow viewports.

**Comment by jamesozzie** [comment] 2020-04-14 10:07
@AlexandreOrlowski Many thanks for your suggestion. There is an existing open feature request in relation to My Business integration, #776. 

In relation to the responsive issue you reported what device are you using? If you're using an online or browser emulator it may not reflect fully the responsive elements.

**Comment by AlexandreOrlowski** [comment] 2020-04-14 14:27
> In relation to the responsive issue you reported what device are you using? If you're using an online or browser emulator it may not reflect fully the responsive elements.

iPhone SE

**Comment by jamesozzie** [comment] 2020-04-15 14:58
@AlexandreOrlowski I'm unable to reproduce the same issue from my side, see below. The issue may be specific to your phone or mobile browser used. The plugin does follow responsive design best practices and you can check all CSS used by browsing through the plugin files.

![image](https://user-images.githubusercontent.com/41326532/79352274-8766ae80-7f31-11ea-82f1-cf936f02dfe0.png)

I'll confirm with the team whether there is anything else we can identify which could be resulting in the behaviour on your phone. Can you share the browser used, along with verion?

**Comment by AlexandreOrlowski** [comment] 2020-04-15 15:23
An other view on iPhone X with the latest version of Safari.

![Uploading iphone-x.PNG…]()

**Comment by cole10up** [comment] 2020-05-01 06:58
This is confirmed on iOS using latest Safari

![image](https://user-images.githubusercontent.com/57115907/80788614-7b3c3d00-8b3e-11ea-8485-dd16605aebd8.png)

Sending to Execution

**Comment by jqlee85** [comment] 2020-05-05 23:57
I've outlined a CSS approach we could take to prevent the overlapping and to make more room. I end up with results like this for the `375px` wide iphone screen:
![iphone-x-375px-screenshot](https://user-images.githubusercontent.com/4214099/81126624-ba78de00-8ef0-11ea-9909-5549e4cb3f7b.png)

There's some clipping of the `<th>`s' text though. Which isn't ideal, but at least looks better than what is currently happening.

Another alternative that would be much more involved would be restructuring the markup to display each "row" of information as an `li` or something, which could allow for content wrapping in a more responsive manner. But that seems like that might be overkill to me, and we'd lose the semantic value of the table structure.

**Comment by felixarntz** [comment] 2020-05-06 00:28
@jqlee85 Could we possibly use an approach where for too small widths there is a horizontal scrollbar for such tables? I think the current approach is okay too, but having scrollbars to expose more useful content (it's quite a bit that gets cut off on these small widths) may be worth the trade-off. Not sure what's better for UX here though. cc @marrrmarrr @adamsilverstein

**Comment by jqlee85** [comment] 2020-05-06 01:02
@felixarntz Yeah I was thinking about horizontal scrollbars too, though I'm not sure it's the best UX on mobile, may be better than cutting off text though. Curious to know what the UX specialists prefer.

**Comment by felixarntz** [comment] 2020-05-06 22:33
@jqlee85 I've looked at the Google Analytics mobile app for inspiration on this. Looks like they only display "Pageviews" there, but not any other numeric data about the URL. I think it would make sense for us to do the same on narrow viewports, hide the other columns. I think hiding those columns on narrow viewports (I'm sure we already have some breakpoint for that somewhere) in addition with the fix you've already presented above would be a solid approach.

Could you look into that and share a screenshot here afterwards?

**Comment by felixarntz** [comment] 2020-05-06 22:35
I'll just approve this IB as is ✅ , with the above addition we should be good. After getting some UX feedback, it's probably better to avoid horizontal scrolling. Trimming too much content though is weird too, so only showing the most essential columns is a good approach.

**Comment by jqlee85** [comment] 2020-05-06 22:38
Great, thanks for following up on the UX @felixarntz. Will do.

**Comment by jqlee85** [comment] 2020-05-09 02:36
@felixarntz I've made those updates and opened up a PR. Here's a screenshot of the table with the last 2 columns hidden and the updates to the mobile padding:
![Screen Shot 2020-05-08 at 7 34 45 PM](https://user-images.githubusercontent.com/4214099/81461813-26627d00-9163-11ea-923b-eb30b1ae6377.png)

**Comment by aaemnnosttv** [comment] 2020-06-01 15:51
Assigning this back to @felixarntz as he did the initial review.

**Comment by cole10up** [comment] 2020-06-06 01:59
**Tested**
Confirmed unique page views and bounce rates are now hidden, look and feel is looking and feeling great.

![image](https://user-images.githubusercontent.com/57115907/83933576-ad087b00-a75e-11ea-8b36-735f1a253ebb.png)

Passed QA ✅

**Closed** 2020-06-18 17:40 UTC
Labels: Good First Issue, Group: Escalation, P1, Type: Bug, Type: Support
