### ISSUE TITLE
Add the dropdown and toggle controls to "existing GA4 property" setup variants

### ISSUE THREAD

**Issue by techanvil** [google/site-kit-wp#5276] opened 2022-05-25 17:42 UTC
## Feature Description

Add the dropdown and toggle controls to the following Setup Component variants:

- Existing GA4 property, no existing tag.
- Existing GA4 property, existing tag.

From the Design Doc:

> The dropdown and existing tag switch/notice should reuse existing components from the Analytics setup flow where possible, i.e. the GA4 PropertySelect and SetupUseSnippetSwitch components, and the Analytics setup flow can broadly serve as a reference for the implementation.

- Design Doc: https://docs.google.com/document/d/1DeWo38lcV7lvLFfcmt-mQ0iaxzB4qfiPArs_yZzYkIM/edit#heading=h.2g0r7ejoqctz
- Figma: https://www.figma.com/file/vMaCWwr6lpk4PrJWb7jIpz/GA4-Banner-Input?node-id=1082%3A1549

---

## Acceptance criteria

- For both the "existing GA4 property, no existing tag" and "existing GA4 property, existing tag" variants of the Setup Component:
  - A dropdown to select the GA4 property should be displayed.
  - The dropdown should contain all of the GA4 properties in the user's currently selected Analytics account.
  - It should also contain the option to create a new property.
- For the "existing GA4 property, existing tag" variant:
  - A switch to toggle the usage of the snippet should be displayed.
  - An informative notice about the presence of the existing tag should be displayed.
- The above controls should generally be aligned with the existing setup process and reused where possible.

## Implementation Brief

- Refer to the implementation of https://github.com/google/site-kit-wp/issues/5275 for the whereabouts of the two variants to update. Expected location `assets/js/modules/analytics-4/components/dashboard/ActivationBanner/SetupBanner.js` or possibly subcomponents.
- For both variants:
  - Render the `analytics-4` `PropertySelect` component to display the property dropdown.
    - Use the `label` prop to specify the dropdown label text: _Google Analytics 4 Property_
- For the "existing GA4 property, existing tag" variant:
  - Use the `analytics-4` `useExistingTagEffect` hook to keep snippet status in sync.
  - Render the `analytics-4` `SetupUseSnippetSwitch` component to display the switch and informative notice.

### Test Coverage

- Ensure Storybook stories are up-to-date and update relevant VRT tests.

## QA Brief

* Configure the Analytics module in Site Kit - use an account which does have GA4 properties associated with it.
* We need to model the scenario where GA4 is not setup, so once Analytics is setup, delete the `googlesitekit_analytics-4_settings` option in WordPress. This can be done in a number of ways, for example:
  * Using the WP CLI with `wp option delete googlesitekit_analytics-4_settings`.
  * Running the DB query `DELETE FROM wp_options WHERE option_name = 'googlesitekit_analytics-4_settings';`
  * Installing the WP Console plugin and running `delete_option( 'googlesitekit_analytics-4_settings' );` in the console.
* Go to the Site Kit Dashboard.
* Click on `Set up now` in the displayed banner.
* Verify that a property selector dropdown is displayed in the banner according to the ACs & Figma designs.
* In order to make the switch to toggle the usage of snippet show up, add an existing GA4 tag to the site.
    * To do so, add the following to your theme's `header.php` file:
        * Inside the `<head>` tag:
        ```
        <script async src="https://www.googletagmanager.com/gtag/js?id={ Your GA4 Property ID }"></script>
        ```
        * After the `<body>` tag starts:
        ```
        <script>
	        window.dataLayer = window.dataLayer || [];

	        function gtag() {
	            dataLayer.push(arguments);
	        }
	        gtag('js', new Date());

	        gtag('config', '{ Your GA4 Property ID }');
        </script>
        ```
* Verify that the toggle switch is also displayed according to the ACs & Figma designs.
    * Note that the colour of the text associated with the toggle switch is not implemented according to the Figma designs to keep it consistent with its usages across other parts of Site Kit, e.g. Setup and Settings.
* Verify the following stories in `Modules -> Analytics 4 -> SetupBanner`:
    * Existing GA4 Property - No Existing Tag
    * Existing GA4 Property - Existing Tag
* Test existing GA account setup and editing screens, specifically scenarios that involve loading/changing Properties. This select component has been updated and should be tested to ensure it's still working as-expected.

## Changelog entry

* Add a dropdown/toggle to GA4 activation banner when there is an existing GA4 property.

**Comment by eugene-manuilov** [comment] 2022-08-05 17:29
IB ✔️

**Comment by wpdarren** [comment] 2022-09-01 08:38
@nfmohit I am struggling to test this ticket.  Have spent quite some time trying to get the dropdown on the GA4 banner notification. No rush but could we jump on a call at some point to go through the QAB.  Thank you.

**Comment by wpdarren** [comment] 2022-09-02 10:47
### QA Update: ⚠️ 

@nfmohit I have included a screencast to prove that I am not losing my mind 😄  but the GA4 notifications aren't appearing. I am wondering if the issue is due to removal of the `ZeroDataState` feature flag where Mohit has [mentioned](https://github.com/google/site-kit-wp/issues/5148#issuecomment-1235316743) that the zero/gathering state notifications are not appearing.  The notifications were appearing earlier in the week when I tested this but the dropdown to select GA4 property was not appearing.  I am going to put this ticket on hold for now, will revisit on Monday.

**Comment by wpdarren** [comment] 2022-09-04 23:23
### QA Update: ⚠️ 

@nfmohit following on from our conversation last week, I am using the latest branch, with oi.ie setup.   I set up Site Kit with a UA and GA4 property.  After setup I am redirected back to the Site Kit Dashboard. I do not see any GA4 banner at all appear. As we discussed the banner was appearing earlier in the week but on the latest develop branch it's not.   I'm conscious that I have spent quite a lot of time trying to QA this ticket but unsuccessfully. 

There are more than one GA4 property on the account so the banner with dropdown should appear to select the property, but no banner is appearing.  I am not sure how to get around this since we need to set up a GA4 for Site Kit by default.  ANy ideas how we can move forward with this?

**Comment by techanvil** [comment] 2022-09-05 11:21
Having looked into it I have realised this was due to a mistake on my part in the IB for https://github.com/google/site-kit-wp/issues/5275 - which is closed and so it seems appropriate to add the fix here, although I have made a note about it on #5275.

So, I've created a followup PR for this issue with the fix, and also tweaked the QA Brief accordingly.

**Comment by techanvil** [comment] 2022-09-05 17:44
Hey @wpdarren, apologies for not spotting this earlier - I guess I applied the fix in a bit of a hurry.

I've realised it looks a bit glitchy when showing the "existing property" variant because it first shows the "no existing property" variant for a moment before switching.

https://user-images.githubusercontent.com/18395600/188495153-724314f1-7a6f-4d7d-ba55-8b51bdd8373e.mp4

I have a proposed fix here which shows a progress bar before showing either variant:

https://user-images.githubusercontent.com/18395600/188495915-a72a5c01-2258-4a78-8d5b-ef477a9a11e2.mp4

https://user-images.githubusercontent.com/18395600/188495931-079ba93b-4952-476a-adb0-36276085e4d0.mp4

From a QA perspective does this look OK to you (maybe the progress bar should be full width?), and would you like to see this fix applied to this issue or possibly create a separate issue for it?

Nb, here is a draft followup PR for the sake of reference. https://github.com/google/site-kit-wp/pull/5796

**Comment by wpdarren** [comment] 2022-09-06 10:06
@techanvil I've just set up a test and yes, I can see what you mean.  I think the progress bar is a good solution so that there's no confusion with the flicker.  I personally, feel that the fix should be part of this ticket.   With regard to the progress bar I feel it should be the full width since the previous notification is full width.

**Comment by techanvil** [comment] 2022-09-06 12:38
> @techanvil I've just set up a test and yes, I can see what you mean. I think the progress bar is a good solution so that there's no confusion with the flicker. I personally, feel that the fix should be part of this ticket. With regard to the progress bar I feel it should be the full width since the previous notification is full width.
> 
> A few other quick observations:
> 
> 1. There's a red border around the GA4 dropdown, couldn't see that on the figma design.
> 2. There's no default GA4 property appearing, I am assuming that's expected but the figma design shows one so wanted to make sure that I am assuming correctly.
> 
> ![image](https://user-images.githubusercontent.com/73545194/188618224-05c25b42-bfea-4b64-98ac-50dfae8d01aa.png)
> 
> Would you like me to send this back to Execution and when you've completed the PR on this, I'll give it a thorough test.

Thanks @wpdarren - good observations, we should be pre-selecting a GA4 property (or "Set up a new property") and with an option selected the dropdown should no longer have the red error outline.

I'll bring this back into Execution and address these points and the progress bar width too. Cheers.

**Comment by wpdarren** [comment] 2022-09-09 11:46
### QA Update:  ⚠️ 

@aaemnnosttv @techanvil  I have an observation:

1) As you can see from the screenshots below, the `Place Google Analytics 4 code` toggle is enabled.  Looking at the Stories and figma designs it is disabled. I think it should be enabled, but didn't want to assume. Please could you confirm? 

![image](https://user-images.githubusercontent.com/73545194/189339821-3789e39f-b9af-4061-bcf5-fb1452f15068.png)

**Verified:**

- A property selector dropdown is displayed in the banner according to the ACs & Figma designs.

![image](https://user-images.githubusercontent.com/73545194/189338366-dd3748c1-fd70-4538-bf78-fb1ac03c6d7a.png)

- The following stories in Modules -> Analytics 4 -> SetupBanner: Existing GA4 Property - No Existing Tag
and Existing GA4 Property - Existing Tag match the AC/Figma designs.

**Comment by wpdarren** [comment] 2022-09-12 15:24
@aaemnnosttv if the behaviour I detailed above is correct then this ticket can be sent to approved. I wasn't sure if the toggle should be disabled or enabled. The figma designs and stories suggest that it should be disabled.

**Comment by aaemnnosttv** [comment] 2022-09-12 18:25
@wpdarren the toggle will only be disabled if the associated measurement ID for the selected property matches the existing tag. I tested this locally and it seems to work as expected.

**Matching measurement ID**
![image](https://user-images.githubusercontent.com/1621608/189728313-b79e1503-8d8e-401e-805f-2dff6319adf9.png)

**Non-matching measurement ID**
![image](https://user-images.githubusercontent.com/1621608/189728348-6bfea04c-e056-49ce-bbb1-392174b26a83.png)

Thanks for clarifying!  Moving to Approval + approved 👍

**Closed by aaemnnosttv** 2022-09-12 18:25 UTC
Labels: Type: Feature, P1
