### ISSUE TITLE
Chart key date info icons should be clickable on touchscreen devices to show the tooltip

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#6933] opened 2023-04-19 16:09 UTC
## Bug Description

As reported by @techanvil in Bug Bash:

On a touchscreen device that doesn't allow hovering, the tooltips for the chart key date info icons are not currently displayable as they rely on a hover event.

To make these useful on these touchscreen devices, the info icons should be clickable to show the tooltip.

Screen-grabbed on a mobile device for illustration:

![image](https://user-images.githubusercontent.com/12189958/233135568-2ad98e1d-180b-40d6-b0a5-6d1ee375f99d.png)

Here is the tooltip when the info icon is hovered on a non-mobile device:

![image](https://user-images.githubusercontent.com/12189958/233135603-d24e56b1-889c-4793-afda-f95c68b4f3e4.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Tapping on the "i" icon above the date marker line in Google Charts should show the tooltip on mobile devices, the same as hovering over it would display it on desktop devices.

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment] 2023-04-20 23:44
🤔 I'm curious: does this apply to _every_ tooltip we use? I'm using our existing `Tooltip` component, so that might be the case—unless this is specifically caused by some interactions with the Google Chart.

If it's not specific to the chart this isn't _really_ a GA4 Reporting issue, but I'll take a look and find out 👍🏻

**Comment by techanvil** [comment] 2023-04-21 08:29
My thinking here is it doesn't apply to every tooltip, as some (most?) of them are applied to clickable elements themselves, so only make sense for a hover...

**Comment by tofumatt** [comment] 2023-04-21 15:42
Hmm, okay. That's a fair point, but it's worth checking to see if we can force the tooltip to be shown programmatically. If that's possible then we can implement this, but otherwise it might not be very feasible as we'd need to replicate the styles of the tooltip just for this instance.

I'll take a look and write the IB; if it's not straightforward to do I might skip this one 🤔

**Comment by techanvil** [comment] 2023-04-24 09:48
I recall looking at the [Tooltip documention](https://v4.mui.com/components/tooltips/) as part of https://github.com/google/site-kit-wp/issues/6552. Reading the [Triggers](https://v4.mui.com/components/tooltips/#triggers) section suggests it should be achievable (although it also seems to suggest the touch trigger should be enabled by default, so maybe there's a bit more to it).

**Comment by tofumatt** [comment] 2023-09-06 12:46
Oddly, the Tooltip's documentation shows "Hover or touch" as an option but that isn't working (as I'd expect it) on mobile.

https://github.com/google/site-kit-wp/assets/90871/cb830276-c9ca-4ca7-aee1-68f49684dc9d

The only option seems to be making them work on click when they don't otherwise have a click handler like in the nav menu—as in that case we don't want to have to click twice.

**Comment by tofumatt** [comment] 2023-09-06 14:57
I had a look at this component further and the title _does appear_ after a long-press of any `Tooltip`:

https://github.com/google/site-kit-wp/assets/90871/9fd489b9-1e72-4799-baf6-3b1547477d16

Given that, I think we can actually close this issue as invalid.

**Closed by tofumatt** 2023-09-06 14:57 UTC
Labels: P1, Type: Enhancement, Module: Analytics

**Comment by techanvil** [comment] 2023-09-06 15:18
Totally didn't spot that, nice one @tofumatt!
