### ISSUE TITLE
Scaffold Unified Dashboard tab bar with chip/pill dummy links

### ISSUE THREAD

**Issue by tofumatt** [google/site-kit-wp#4053] opened 2021-09-15 20:55 UTC
## Feature Description

We should implement a dummy chip/pill bar that will be used for navigation on the new Unified Dashboard.

Desktop should look like this:

<img width="698" alt="Screenshot 2021-09-17 at 10 55 18" src="https://user-images.githubusercontent.com/90871/133764166-3eb0fa8e-2162-410c-a04e-fba12e43ed51.png">

With mobile using the same the chip links:

<img width="342" alt="Screenshot 2021-09-15 at 21 47 21" src="https://user-images.githubusercontent.com/90871/133508191-6bfb75fc-3ae5-40b3-8e22-c705f80ad80a.png">

The Figma file can be found here: https://www.figma.com/file/VILRieNSLg2DOVyEgFBkXe?node-id=855:4304#109627477

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be a new component, `DashboardNavigation` created in `assets/js/component/DashboardNavigation`
* They should contain four "pill"/"choice" links as shown in the above screenshots/Figma mockup
* Each pill should link to a particular section on the page using hash URLs. These should be:
  * `#traffic`
  * `#content`
  * `#speed`
  * `#monetization`
* When the `unifiedDashboard` feature flag is enabled, these links should appear in the bottom of the `Header` component as shown in the Figma mockup.

## Implementation Brief

**Add Chips**
* Add `@material/react-chips` as a non-development dependency
* Update `assets/sass/admin.scss` to import the styles for chips (`@import "@material/react-chips/index"`)

**`<DashboardNavigation />`**
* Add a new `DashboardNavigation` component in the path defined in the ACs as the default export.
  * This component should be "sticky", such that it appears below the `subHeader` prop (see #4050), but should stay on the top of the page, underneath the `.googlesitekit-header` component when scrolled.
* From this component, return a `ChipSet` with the `choice` prop enabled to enable single-choice behavior ([see component docs for choice chips here](https://github.com/material-components/material-components-web-react/blob/master/packages/chips/README.md#choice-chips))
* Render a `<Chip />` as a child of the `ChipSet` for each pill referenced in the ACs, providing an `id` and `label` prop for each
  - `id` can be the same as the text after the hash (e.g. `traffic`)
  - `label` should be the translated string for each using the same labels as the design as the source string
  - In the future, we can use the `leadingIcon` prop to pass icon elements to be rendered in the icon before the text (we don't have icons ready to use for these yet)
* Pass a callback to the `handleSelect` prop of `ChipSet` which should accept an array of selected chip IDs as its first argument
  - Since it's a `choice` chipset, only one can be selected at a time (but the value will always be an array). For now we will want to set the `location.hash` from the first item in the array if one is present
* Add a new `DashboardNavigation.stories.js` module adjacent to the new `DashboardNavigation.js` component and add a story to show the default state
  - Use `title: 'Components/DashboardNavigation'` for the Storybook kind/top-level grouping

In the future we may also want to move the state for the selected chip to the datastore (such as `core/ui`) where this can be read or changed externally, this is just a scaffolding which could be easily extended to support this later using the other props available to `ChipSet`.

**Integration in `Header`**
* Add a new prop to the `<Header>` component: `showDashboardNavigation`; it should be `false` by default
* Add the `DashboardNavigation` component to the `Header` component, conditionally, when the `showDashboardNavigation` prop is true, underneath the component added in #4050 (eg. under the `subHeader` prop).
  * Update `DashboardApp` and `DashboardDetailsApp` to pass `showDashboardNavigation` prop, if the `unifiedDashboard` feature is enabled
  * Update `stories/header.stories.js` to add a new story for showing the header with `<Header showDashboardNavigation />`

### Test Coverage

* Add basic component tests in `DashboardNavigation.test.js`

## QA Brief

* Check for basic functionality and appearance of the Dashboard Navigation Chips.
* Should only be visible in unified dashboard. 
* Icons will be added later.
* Check for sticky behavior on all screen sizes! 

## Changelog entry

* Implement Unified Dashboard tab bar with chip/pill links to widget areas.

**Comment by aaemnnosttv** [comment] 2021-10-13 17:07
@tofumatt I'm not sure that we could use the same slot for this as the content area defined in #4050 since the latter is said to not be sticky, whereas the navigation component here would need to be (stuck below the header) so maybe these can't go together. In that case, I'm not sure either of these slots can go within `.googlesitekit-header` but should instead go below it, or we'd have to change which selector gets the `sticky` rule. We may need to take a closer look, but my understanding of sticky is that in order for the main header bar to be sticky, and some inner content area not to be, followed by the nav which is sticky, they would need to be sibling elements rather than nested.

**Comment by kuasha420** [comment] 2021-11-15 20:07
@tofumatt you attention is needed here. Please have a look at the conversation in the linked PR. :pray:

**Comment by wpdarren** [comment] 2021-11-22 16:24
### QA Update:  ❌ 

@kuasha420 I have found some observations below.

1. There's a styling issue with the URL search and chips. 

![image](https://user-images.githubusercontent.com/73545194/142896003-7c27a2d2-5a0f-486b-9631-a2375900b03a.png)

2. I click on the traffic chip, it is then highlighted. The URL is now `/wp-admin/admin.php?page=googlesitekit-dashboard#traffic` I then refresh the page and as expected the same URL appears,  but the chip is not highlighted. 

3. Differences in the Figma files (see below)

- Font weight. Should be 500. 
- Font size. Should be 16px, appears as 14px.
- Padding within the chip is not the same.
- Spacing between the chips is not the same.
- Different font color on unselected chip. Should be #5F6368. 
- Font color on selected chip.  Should be #1967D2.
- Background color on selected chip. Should be #E8F0FE

4. Can I assume the placement when a chip is clicked is to be decided since the current location is wrong?

**Verified:**

- Checked basic functionality and appearance of the Dashboard Navigation Chips. 
- The tab bar only appears when `unifiedDashboard` is enabled.
- Checked for sticky behavior on all screen sizes, including mobile and tablet.

**Comment by eugene-manuilov** [comment] 2021-11-22 16:29
> 1. There's a styling issue with the URL search and chips.

@wpdarren there is a separate ticket to fix this issue: #4370

**Comment by aaemnnosttv** [comment] 2021-11-22 17:08
@wpdarren I think we may need a separate issue for some of these finer styling details, but thanks for raising them! Part of the reason for this is that many of our Figma docs use a style which is something that we're working towards but not something that we can adopt entirely right away (without things looking very inconsistent throughout). So we need to somewhat translate the design to what works best in the product with the colors and styles we're using now. cc: @felixarntz

**Comment by wpdarren** [comment] 2021-11-22 17:14
> @wpdarren there is a separate ticket to fix this issue: #4370 

@eugene-manuilov Thank you, hadn't noticed that ticket. 

> @wpdarren I think we may need a separate issue for some of these finer styling details, but thanks for raising them! 

@aaemnnosttv Please let me know if you would like me to raise a ticket for this. 👍  If these aren't going to be fixed as part of this sprint then I guess they should be classed as known issues for bug bash? 

For point 4, I have just noticed #4367 so that should fix that issue. 

For point 2, I think this is the only outstanding issue, and not huge.

**Comment by kuasha420** [comment] 2021-11-23 05:36
I have fixed the issue of Point 2 in the follow up PR. It sets the chip as active based on URL Hash.

But there is a issue, as all the widgets aren't fully loaded yet, the page scrolls to undesirable places on page refresh. Is there any way to resolve that? 

I think we can wait for all the widgets to load before scrolling, but that feels odd. 

Any idea? 

CC: @wpdarren @tofumatt @aaemnnosttv @eugene-manuilov and @techanvil (you worked on the smooth scrolling behavior).

**Comment by techanvil** [comment] 2021-11-23 11:18
> I have fixed the issue of Point 2 in the follow up PR. It sets the chip as active based on URL Hash.
> 
> But there is a issue, as all the widgets aren't fully loaded yet, the page scrolls to undesirable places on page refresh. Is there any way to resolve that?
> 
> I think we can wait for all the widgets to load before scrolling, but that feels odd.
> 
> Any idea?
> 
> CC: @wpdarren @tofumatt @aaemnnosttv @eugene-manuilov and @techanvil (you worked on the smooth scrolling behavior).

Hi @kuasha420, would it be possible to share a screen capture to show us what's happening here?

**Comment by kuasha420** [comment] 2021-11-23 12:45
@techanvil Here's a screen recording. https://youtu.be/-1zYEC4T7CY

**Comment by techanvil** [comment] 2021-11-23 13:53
Thanks @kuasha420, that's very useful. I'm pretty sure what we're seeing is the default browser behaviour of scrolling the element (e.g. `#speed`) into view on page load - or, reloading at the previous scroll point. It's not caused by the Chip click handler with the JS-triggered scrolling, as it's not firing here - you can verify this by popping open `assets/js/components/DashboardNavigation.js` in the debugger and place a breakpoint in the click handler.

Due to the dynamic rendering of the page, I suspect we can't rely on the browser's default behaviour to scroll to the correct point on page load. We'll probably need to resolve it with an event/action of some sort, once all the widgets have been rendered.

This probably merits a separate ticket to flesh out a solution...

**Comment by eugene-manuilov** [comment] 2021-11-24 11:52
@wpdarren this is ready for another pass

**Comment by wpdarren** [comment] 2021-11-24 12:28
### QA Update:  ⚠️ 

This is looking good other than @aaemnnosttv @felixarntz I don't want to loose my observations on the differences between the tab bar and Figma designs. As mentioned in [this comment](https://github.com/google/site-kit-wp/issues/4053#issuecomment-975694897). Should we create a ticket for this, or, do you want me to add them as known issues for bug bash? 

**Verified:**

- Checked basic functionality and appearance of the Dashboard Navigation Chips. 
- The tab bar only appears when `unifiedDashboard` is enabled.
- Checked for sticky behavior on all screen sizes, including mobile and tablet.
- Issue note 2. reported above is now fixed. 

![image](https://user-images.githubusercontent.com/73545194/143238352-9740af97-6df8-4b34-8a31-4dddad8fe75f.png)

**Comment by felixarntz** [comment] 2021-11-24 19:03
@wpdarren @aaemnnosttv @eugene-manuilov @kuasha420 I reviewed the UX differences here in detail. In this case there are definitely a few places where we diverge from the designs too far. Specifically, it looks like the code right now is relying almost entirely on the `.mdc-chip` Material UI defaults - which makes sense as a starting point, but following the Figma designs here more precisely does not actually conflict with anything we already have in Site Kit.

For example, the default for `.mdc-chip`s is to reduce the font size, which is what was pointed out above (we have 14px now instead of the 16px from Figma): This default is probably (personal assumption) because the chips tend to be used as some sort of "tags". However, in our case they are not, they need to catch the focus of the user, so reducing the font size doesn't exactly make sense for our use-case. In other words, it is actually the `.mdc-chip` styles themselves that diverge from our "regular" design here, rather than the Figma file.

Anyway, as a summary we should still iterate on this as follows:
* Everything that is sizing/spacing-related should follow the Figma file. In other words, we should override (or almost "reset") the font size to `1rem`, font weight to `500`, and we should also ensure that padding and spacing match the Figma file.
* The colors can potentially remain as they are now. The difference is more minor there, and we shouldn't add slightly different colors to our palette than what we're using elsewhere. It may be worth cross-checking the shades of blue and gray with e.g. what we use in the Idea Hub widget.
* I noticed one more UI thing that needs to be fixed: There is some sort of double border above the bar with the pills when a notification is shown, also different from the Figma file (see screenshot below). If fixing this is straightforward, please include that here. If fixing this is complicated, please create a separate follow-up issue to fix this.

<img width="1089" alt="Screen Shot 2021-11-24 at 2 00 45 PM" src="https://user-images.githubusercontent.com/3531426/143298750-b26f9495-8a20-457f-872b-a9955ff9db72.png">

**Comment by asvinb** [comment] 2021-11-25 11:06
@kuasha420 The last issue that @felixarntz noted:
> I noticed one more UI thing that needs to be fixed: There is some sort of double border above the bar with the pills when a notification is shown, also different from the Figma file (see screenshot below). If fixing this is straightforward, please include that here. If fixing this is complicated, please create a separate follow-up issue to fix this.

has been fixed in the following PR: #4384 You can disregard that last point.

**Comment by eugene-manuilov** [comment] 2021-11-30 13:53
@felixarntz styles have been updated. Do you mind checking it on your end?

**Comment by wpdarren** [comment] 2021-12-01 14:38
### QA Update: ⚠️ 

@eugene-manuilov @kuasha420 @felixarntz this looking mostly good  but I wanted to confirm a few items:

1. These are differences between what I see and Figma. Can you confirm that these are differences that we are not changing.  If so, I'll then add them on to the known issues because they will likely come up in the bug bash. 

- Different font color on unselected chip. Should be #5F6368.
- Font color on selected chip. Should be #1967D2.
- Background color on selected chip. Should be #E8F0FE

2. It mentions in the QAB, that Icons will be added later.  Do we have a ticket for this? Again, like the Figma differences I am conscious that they will come up in bug bash. 

3. I again want to bring up the odd behaviour when you un-click a selected chip,, the background colour goes grey and does not go back to the white background until you click away from the chips. I remember someone saying there's nothing that can be done about that but I am conscious it will come up in bug bashing. Just wanted to double check. 

Other than this, it's looking good.

**Comment by kuasha420** [comment] 2021-12-01 16:23
Regarding colors, we don't have those exact colors in our color palate and the SCSS Mixins for changing color wasn't working, maybe @asvinb can elaborate on it more.

**Comment by felixarntz** [comment] 2021-12-01 18:43
@wpdarren The color differences are acceptable. Regarding the behavior when un-clicking a selected chip, I think that is okay for now, but it's worth raising this with UX, either now or as part of the bug bash. It's not clear to me whether this is acceptable behavior or something we need to fix, so it requires some discussion that shouldn't block this issue.

The icons are being added separately via #4438 now, so I think this issue here can be QA ✅

**Comment by wpdarren** [comment] 2021-12-02 02:39
@felixarntz thank you. I've added the color differences and the un-clicking a selected chip to the known issues board for bug bash.  I realise the colors won't change, but I am sure our eagle eyed bug bash testers will notice it. 

### QA Update: ✅ 

**Verified:**

- Checked basic functionality and appearance of the Dashboard Navigation Chips. 
- The tab bar only appears when `unifiedDashboard` is enabled.
- Checked for sticky behavior on all screen sizes, including mobile and tablet.
- Issues reported in this ticket are all fixed, including Felix's [comments here](https://github.com/google/site-kit-wp/issues/4053#issuecomment-978147043) 

![image](https://user-images.githubusercontent.com/73545194/144347323-6139c5c3-81b0-43f3-a04b-1cca9df5217b.png)

**Comment by marrrmarrr** [comment] 2021-12-02 15:42
with the issues Darren mentioned as added to the bug bash, this lgtm.

**Closed by marrrmarrr** 2021-12-02 15:42 UTC
Labels: P0, Type: Enhancement, Rollover
