### ISSUE TITLE
Dashboard error: Minified React error #200 with Groups plugin active

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1894] opened 2020-08-10 10:35 UTC
As reported in [WordPress support topic](https://wordpress.org/support/topic/site-kit-encountered-an-error-minified-react-error-200/#post-13231490) the following dashboard error appears, after clicking on activate during the setup process

```
Site Kit encountered an error
Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    in NotificationCounter
    in ActivationApp
    in RestoreSnapshots
    in ErrorHandler
    in Root

```

<details>
<summary>Console Errors</summary>

```
googlesitekit-vendor.js?ver=1.13.1:1 Error: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Bk (googlesitekit-vendor.js?ver=1.13.1:1)
    at NotificationCounter.value (googlesitekit-activation.js?ver=1.13.1:6)
    at ci (googlesitekit-vendor.js?ver=1.13.1:1)
    at si (googlesitekit-vendor.js?ver=1.13.1:1)
    at Oi (googlesitekit-vendor.js?ver=1.13.1:1)
    at ga (googlesitekit-vendor.js?ver=1.13.1:1)
    at Zj (googlesitekit-vendor.js?ver=1.13.1:1)
    at Lj (googlesitekit-vendor.js?ver=1.13.1:1)
    at googlesitekit-vendor.js?ver=1.13.1:1
    at e.unstable_runWithPriority (googlesitekit-vendor.js?ver=1.13.1:1)
googlesitekit-activation.js?ver=1.13.1:1 Caught an error: Error: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Bk (googlesitekit-vendor.js?ver=1.13.1:1)
    at NotificationCounter.value (googlesitekit-activation.js?ver=1.13.1:6)
    at ci (googlesitekit-vendor.js?ver=1.13.1:1)
    at si (googlesitekit-vendor.js?ver=1.13.1:1)
    at Oi (googlesitekit-vendor.js?ver=1.13.1:1)
    at ga (googlesitekit-vendor.js?ver=1.13.1:1)
    at Zj (googlesitekit-vendor.js?ver=1.13.1:1)
    at Lj (googlesitekit-vendor.js?ver=1.13.1:1)
    at googlesitekit-vendor.js?ver=1.13.1:1
    at e.unstable_runWithPriority (googlesitekit-vendor.js?ver=1.13.1:1) 
Object
componentStack: "↵    in NotificationCounter↵    in ActivationApp↵    in RestoreSnapshots↵    in ErrorHandler↵    in Root"
__proto__: Object
```

</details>

<details>

<summary>Site Health information</summary>

```
### wp-core ###

version: 5.4.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/%year%/index.php/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 11
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/agermanc/public_html
wordpress_size: 183.68 MB (192602643 bytes)
uploads_path: /home/agermanc/public_html/wp-content/uploads
uploads_size: 75.55 MB (79216764 bytes)
themes_path: /home/agermanc/public_html/wp-content/themes
themes_size: 17.57 MB (18424033 bytes)
plugins_path: /home/agermanc/public_html/wp-content/plugins
plugins_size: 146.60 MB (153721895 bytes)
database_size: 7.09 MB (7429899 bytes)
total_size: 430.48 MB (451395234 bytes)

### wp-active-theme ###

name: Mesmerize (mesmerize)
version: 1.6.90 (latest version: 1.6.94)
author: Horea Radu
author_website: https://extendthemes.com/
parent_theme: none
theme_features: post-thumbnails, automatic-feed-links, title-tag, custom-header, custom-logo, customize-selective-refresh-widgets, menus, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, widgets, custom-background
theme_path: /home/agermanc/public_html/wp-content/themes/mesmerize

### wp-themes-inactive (8) ###

Mins: version: 1.1.4, author: GoDaddy
Primer: version: 1.8.6, author: GoDaddy (latest version: 1.8.9)
Travelify: version: 3.0.4, author: Colorlib (latest version: 3.0.8)
Twenty Fifteen: version: 2.0, author: the WordPress team (latest version: 2.6)
Twenty Nineteen: version: 1.1, author: the WordPress team (latest version: 1.6)
Twenty Seventeen: version: 1.7, author: the WordPress team (latest version: 2.3)
Twenty Sixteen: version: 1.5, author: the WordPress team (latest version: 2.1)
Twenty Twenty: version: 1.2, author: the WordPress team (latest version: 1.4)

### wp-plugins-active (29) ###

Classic Editor: version: 1.5, author: WordPress Contributors
Custom Login Page Customizer: version: 2.0.1, author: Hardeep Asrani
Custom Template for LearnDash: version: 1.0.2, author: Brainstorm Force
Design Upgrade for LearnDash: version: 2.7, author: Escape Creative
Groups: version: 2.10.0, author: itthinx
Jetpack by WordPress.com: version: 7.6.1, author: Automattic (latest version: 8.8)
LearnDash LMS: version: 3.2.2, author: LearnDash
LearnDash LMS - Stripe Integration: version: 1.5.0, author: LearnDash (latest version: 1.6.0)
LearnDash LMS - WooCommerce Integration: version: 1.8.0, author: LearnDash
Login or Logout Menu Item: version: 1.2.0, author: cartpauj
Mesmerize Companion: version: 1.6.111, author: Horea Radu
PayPal for WooCommerce: version: 1.5.4, author: Angell EYE
Peter's Login Redirect: version: 2.9.7, author: Peter Keung
Polylang: version: 2.7.4, author: WP SYNTEX
Site Kit by Google: version: 1.13.1, author: Google
TablePress: version: 1.9.2, author: Tobias Bäthge (latest version: 1.11)
Toggles Shortcode And Widgets: version: 1.11, author: OTWthemes
UpdraftPlus - Backup/Restore: version: 1.16.26, author: UpdraftPlus.Com, DavidAnderson
WC Thanks Redirect: version: 2.2, author: Nitin Prakash
WooCommerce: version: 3.6.5, author: Automattic (latest version: 4.3.1)
WooCommerce Blocks: version: 2.2.1, author: Automattic (latest version: 3.1.0)
WooCommerce PayPal Checkout Gateway: version: 1.6.17, author: WooCommerce (latest version: 2.0.3)
WooCommerce Services: version: 1.21.0, author: Automattic (latest version: 1.24.0)
WooCommerce Shortcodes: version: 1.0.0, author: WooThemes, Claudio Sanches
WooCommerce Stripe Gateway: version: 4.2.3, author: WooCommerce (latest version: 4.5.0)
WPForms Lite: version: 1.5.4.2, author: WPForms (latest version: 1.6.1)
WP Meta and Date Remover: version: 1.7.6, author: Prasad Kirpekar (latest version: 1.7.9)
WP Rollback: version: 1.7.1, author: Impress.org
Yoast SEO: version: 14.6.1, author: Team Yoast (latest version: 14.7)

### wp-plugins-inactive (6) ###

Akismet Anti-Spam: version: 4.1.2, author: Automattic (latest version: 4.1.6)
Disable Site: version: 1.3.1, author: Jimmy K. <jimmy@nintencode.com>
Google XML Sitemaps: version: 4.1.0, author: Arne Brachhold
iFlyChat: version: 4.6.4, author: iFlyChat Team
Insert Headers and Footers: version: 1.4.6, author: WPBeginner
SEOPress: version: 3.8.9, author: SEOPress

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 8.70

### wp-server ###

server_architecture: Linux 2.6.32-954.3.5.lve1.4.77.el6.x86_64 x86_64
httpd_software: Apache/2.4.43 (cPanel) OpenSSL/1.1.1g mod_bwlimited/1.4 Phusion_Passenger/5.3.7
php_version: 7.0.33 64bit
php_sapi: cgi-fcgi
max_input_variables: 10000
time_limit: 600
memory_limit: 512M
max_input_time: 600
upload_max_size: 512M
php_post_max_size: 512M
curl_version: 7.62.0 OpenSSL/1.0.2k
suhosin: false
imagick_availability: false
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.31-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/agermanc/public_html/wp-content
WP_PLUGIN_DIR: /home/agermanc/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### jetpack ###

site_id: 156178166
ssl_cert: No
time_diff: undefined
version_option: 7.6.1:1574223717
old_version: 7.6:1565598452
public: Public
master_user: #1 admin (info@a1-german.com)
current_user: #1 admin (info@a1-german.com)
tokens_set: Blog User
blog_token: Q(BiZY5v(DDVrVZsx(shhhVB$6c5n&Qj
user_token: (eu!LgC&qQfuIg*3c@p$)iVuqaK%YkR4
version: 7.6.1
jp_plugin_dir: /home/agermanc/public_html/wp-content/plugins/jetpack/
plan: free
HTTP_HOST: a1-german.com
SERVER_PORT: 443
HTTPS: on
REMOTE_ADDR: 102.65.11.22
protect_header: {"trusted_header":"REMOTE_ADDR","segments":1,"reverse":false}
full_sync: {"started":"Fri, 28 Dec 2018 20:39:20 +0000","queue_finished":"Fri, 28 Dec 2018 20:39:20 +0000","send_started":"Fri, 28 Dec 2018 20:39:23 +0000","finished":"Fri, 28 Dec 2018 20:39:23 +0000","sent":{"constants":1,"functions":1,"options":1,"users":1},"sent_total":[],"queue":{"constants":1,"functions":1,"options":1,"users":1},"config":{"options":true,"functions":true,"constants":true,"users":[1]},"total":{"constants":1,"functions":1,"options":1,"users":1}}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/a1-german.com","siteurl":"https:\/\/a1-german.com","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

### google-site-kit ###

version: 1.13.1
php_version: 7.0.33
wp_version: 5.4.2
reference_url: https://a1-german.com
amp_mode: no
site_status: not-connected
user_status: not authenticated
active_modules: site-verification, search-console
required_scopes: 
	openid: ⭕
	https://www.googleapis.com/auth/userinfo.profile: ⭕
	https://www.googleapis.com/auth/userinfo.email: ⭕
	https://www.googleapis.com/auth/siteverification: ⭕
	https://www.googleapis.com/auth/webmasters: ⭕
search_console_property: none
```

</details>

## Additional Context

- Mesmerize theme
- JetPack & WooCommerce enabled
- [Original Support Topic](https://wordpress.org/support/topic/site-kit-encountered-an-error-minified-react-error-200/#post-13232559)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation Brief

* 

## QA Brief

* 

## Changelog entry

*

**Comment by jamesozzie** [comment] 2020-08-12 10:47
I was able to re-produce this issue following the below:
1. Installed and activated 4 of the plugins activated when user encountered the issue (Custom Login Page Customizer, Login or Logout Menu Item, Groups, Peter's Login Redirect). Default configurations with no alterations. 
2. Activated Site Kit (previously deactivated)
3. Error appears immediately after activation

![error](https://user-images.githubusercontent.com/41326532/90006178-53f22180-dc90-11ea-9786-de387d9e2ac0.gif)

Despite the error appearing Site Kit remains active but no dashboard icon appears, with no widget appearing in the main WordPress dashboard. 

Trying to access "http://www.orient.one/wp-admin/?page=googlesitekit-dashboard" results in a "Cannot load googlesitekit-dashboard." 500 error

![image](https://user-images.githubusercontent.com/41326532/90006327-974c9000-dc90-11ea-976f-909cb99c022e.png)

Updated to latest version of WP (5.5) on this test site and same issue as above. 

After deactivating the additional plugins one by one it looks like the Groups plugin (2.10.0) is resulting in the Site Kit tab not appearing & the dashboard not accessible. Once deactivating the tab appears and setup completes fine. 

Escalating to L1.

**Comment by EmilMoe** [comment] 2020-09-04 11:18
Facing the same error

**Comment by cole10up** [comment] 2020-10-20 06:03
**Tested**

Installed the following plugins on my test environment:

- Custom Login Page Customizer
- Login or Logout Menu Item
- Groups
- Peter's Login Redirect
- Site Kit

Activated all plugins

Was unable to reproduce this issue after setting up the latest Site Kit.
![image](https://user-images.githubusercontent.com/57115907/96546474-2eb8fb00-125f-11eb-8fd5-f099f7162256.png)

Since this ticket both Site Kit have been updated as well as Groups. 
![image](https://user-images.githubusercontent.com/57115907/96546536-4d1ef680-125f-11eb-96cd-128956f53eae.png)

Closing this as it seems to be fixed.

**Closed** 2020-10-20 06:03 UTC
Labels: Group: Escalation, Type: Bug
