### ISSUE TITLE
Move tile percentage badges to bottom of tile

### ISSUE THREAD

**Issue by bethanylang** [google/site-kit-wp#7769] opened 2023-10-25 15:18 UTC
## Feature Description

Per discussion in [this Asana Bug Bash task](https://app.asana.com/0/1205508124049666/1205795062821498/f), we should move the percentage badges on tiles to be below the tile data to match [this Figma design](https://www.figma.com/file/S2CNc1toIzC7UrGMgs79S6/Conversions?type=design&mode=design&t=18k6R3oLrJ1bHzQz-0):

![image](https://github.com/google/site-kit-wp/assets/12189958/b4b9b3c5-f421-4961-918b-c10cef13cfc9)

cc @sigal-teller 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

- The metric change badge in numeric and text type key metric tiles should be relocated to the bottom of the tile according to [the Figma design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7286-16900&mode=design&t=fQOYEZ5xbEsxBWDv-0).
- It should be ensured that the typography of & spacing between different elements of the metric tiles are consistent with [the Figma design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7286-16900&mode=design&t=fQOYEZ5xbEsxBWDv-0).
- It should be ensured that the increased height of the metric tiles due to the above changes is consistently reflected across all metric tiles.

## Implementation Brief

* Modify `assets/js/components/KeyMetrics/MetricTileNumeric.js`
  * Move `ChangeBadge` component bellow `p.googlesitekit-km-widget-tile__subtext`
    * Wrap it with `div.googlesitekit-km-widget-tile__metric-change-container`
    * Remove the [current wrapper](https://github.com/google/site-kit-wp/blob/b5b3f4a0c227a308ceddcc8345a6e87fc3385e3a/assets/js/components/KeyMetrics/MetricTileNumeric.js#L46) to prevent duplication
* Ensure all metric tiles align with the design. For reference, you can utilize the following style files:
  * `assets/sass/components/key-metrics/_googlesitekit-km-widget-tile.scss`
  * `assets/sass/components/global/_googlesitekit-change-badge.scss`
* Perform a cleanup to remove any styles that became redundant or unnecessary due to the aforementioned changes.

### Test Coverage

* Update VRT reference images

## QA Brief

* Setup Site Kit with `keyMetrics` and `ga4Reporting` feature flags
* Add key metrics that include badge
* Verify that they look like in the figma design

## Changelog entry

* Move the Key Metric tile percentage badges to below the metrics.

**Comment by sigal-teller** [comment] 2023-10-26 07:51
Noting that additional minor tweaks were made to the tiles so they would be able to contain the badge in the bottom:

1. Tiles height was increased to 150 px
2. String values (like top traffic source) font was changes to “title medium”
3. The spacing between the value and the text below (i.e “of x visitors) was reduced
4. In tiles that contains lists (like top pages, keywords etc.) the spacing between the list and the tile title was reduced by 3 pixels to align with the other tiles
5. Note that in the visit length value new format the “m” and the “s” are in smaller fonts then the numbers

**Comment by techanvil** [comment] 2023-10-31 16:28
Hi @zutigrm, thanks for this IB. It's generally looking good, albeit a bit of a "PR in text form". Sometimes it's appropriate to be very explicit, though. The only real concern I have is around the duplication of `.googlesitekit-km-widget-tile__metric-change-container` within `MetricTileNumeric`.

By moving the change badge out of the _current_ `.googlesitekit-km-widget-tile__metric-change-container` it means that current element is no longer a "change container" and more of a "metric container". Note how it would compare to `MetricTileText` where the metric and change badge are rendered separately but there's only one use of `.googlesitekit-km-widget-tile__metric-change-container`.

As an aside, drilling into the styling of `.googlesitekit-km-widget-tile__metric-change-container` it's evident that some of its styling will no longer be needed - `gap` for sure. It's not entirely clear the `align-items` would still have an effect either. This sort of thing would hopefully be addressed at implementation/review time anyway.

Of course, we don't need or want to get right into every last detail in the IB, but to my main point, I do think it's worth reconsidering the suggested use of `.googlesitekit-km-widget-tile__metric-change-container` to avoid a bit of semantic drift here. Wrapping the `ChangeBadge` in this class _does_ make sense but retaining its use on the current element would not be so appropriate.

**Comment by zutigrm** [comment] 2023-11-01 08:51
@techanvil thank you for the feedback. That is a very good point, thanks. I updated the IB

**Comment by techanvil** [comment] 2023-11-01 09:44
Thanks for the rewrite, that looks great! IB LGTM. :white_check_mark:

**Comment by wpdarren** [comment] 2023-11-08 13:28
### QA Update: ❌ 

@zutigrm on smaller viewports, i.e. mobile, the height of the `Most engaged traffic source` and `Top traffic source` metric tiles are different than the other numeric and text type key metric tiles.  See screenshots below.  In the example, for iPhone 12 Pro, the other tiles are `358 x 109.91`, but the height is different on these two tiles. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/d563c88c-c938-4929-9580-6102468b3f28)
![image](https://github.com/google/site-kit-wp/assets/73545194/53ff95c2-4552-4938-b0e9-65aa10fe473a)

</details>

**Verified:**

- The metric change badge in numeric and text type key metric tiles are relocated to the bottom of the tile according to [the Figma design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7286-16900&mode=design&t=fQOYEZ5xbEsxBWDv-0).
- The typography of & spacing between different elements of the metric tiles are consistent with [the Figma design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7286-16900&mode=design&t=fQOYEZ5xbEsxBWDv-0).

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/87aec1c3-55f5-4be9-9f1a-2453b8ce7d40)
![image](https://github.com/google/site-kit-wp/assets/73545194/6057c5dd-9e34-4d68-8739-a5818bb6a9f1)

</details>

**Comment by zutigrm** [comment] 2023-11-08 13:44
@wpdarren Thanks for checking this. 
I am not sure `height` of the tile is part of the scope, as per recent [discussion](https://10up.slack.com/archives/C01CA828ZPZ/p1699024149266829) `height` on mobile is supposed to be fluid, and there is this issue #7763 that is going to address some edits in design (and update the current design a bit). Changes we make to the `height` as part of this issue will most likely be overriden in the mentioned issue. 

@techanvil Let me know what is your opinion here, as you are familiar with both issues as well

**Comment by wpdarren** [comment] 2023-11-08 13:46
Thanks @zutigrm

 I am happy to go with what you think is best. The reason why I queried it was because of this section in the AC:

`It should be ensured that the increased height of the metric tiles due to the above changes is consistently reflected across all metric tiles.`

**Comment by zutigrm** [comment] 2023-11-08 13:54
@wpdarren Yeah the the new issue come after the AC is written for this one, as there is also new design added by Sigal just few days ago. Let's see what @techanvil thinks is the best approach here

**Comment by techanvil** [comment] 2023-11-08 14:11
Thanks both, definitively worth checking but as @zutigrm has pointed out, the mobile tile height is intended to be derived from the content, so it's OK for tile heights to differ on mobile viewports.

Admittedly, the height is out by a few pixels from the current design (see below), but as Aleksej also mentioned we've got an update to the design coming in #7763, which will affect the tile heights, so I think it's safe to approve this as it is and take a fresh look in the QA for 7763.

![image](https://github.com/google/site-kit-wp/assets/18395600/ef1e03c2-555d-4bbe-b4ce-39719fc053e7)

**Comment by zutigrm** [comment] 2023-11-08 15:12
Thanks @techanvil 

Moving it back with you @wpdarren

**Comment by wpdarren** [comment] 2023-11-09 09:27
### QA Update: ✅ 

**Verified:**

- The metric change badge in numeric and text type key metric tiles are relocated to the bottom of the tile according to [the Figma design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7286-16900&mode=design&t=fQOYEZ5xbEsxBWDv-0).
- The typography of & spacing between different elements of the metric tiles are consistent with [the Figma design](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?type=design&node-id=7286-16900&mode=design&t=fQOYEZ5xbEsxBWDv-0).
- The increased height of the metric tiles due to the above changes is consistently reflected across all metric tiles.

Note: I observed an issue with the height of the tiles on smaller viewports, and this should be improved in 7763. 

<details>
 <summary>Screenshots</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/87aec1c3-55f5-4be9-9f1a-2453b8ce7d40)
![image](https://github.com/google/site-kit-wp/assets/73545194/6057c5dd-9e34-4d68-8739-a5818bb6a9f1)

</details>

**Comment by nfmohit** [comment] 2023-11-13 08:30
Hi @zutigrm & @wpdarren.

I can reproduce a broken layout for the "numeric" tiles when there is another tile with an error state present in the KMW area. Please see this screenshot:

![image](https://github.com/google/site-kit-wp/assets/20284937/2868f64c-33e2-447b-aa35-c973af6d25b2)

It looks like this is a regression from this issue, specifically from [this change](https://github.com/google/site-kit-wp/commit/105aca942342cf2fdc12289f91a551a9a670b379#diff-28cb499b5e3058d0cf1ff55ad9f64eac4e7db6618558d03ca3de9c60d6cabb9fR58).

CC: @techanvil @aaemnnosttv

**Comment by wpdarren** [comment] 2023-11-13 09:10
### QA Update: ❌ 

Thanks, @nfmohit. I forgot to include error states in my testing. Good spot. I have moved this back to Execution.

**Comment by zutigrm** [comment] 2023-11-13 10:18
I have reverted the height which was there to align the content to the bottom of the tile. Since this was causing gaps when error tile is present. And error tile height, and content alignment in tiles is handled in other issues. For background, refer to this [thread](https://10up.slack.com/archives/CBKKQEBR9/p1699864318986299)

**Closed** 2023-11-16 21:45 UTC
Labels: P1, Type: Enhancement
