### ISSUE TITLE
Include verification method within a users Site Health information

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#3621] opened 2021-06-23 14:19 UTC
## Feature Description

Consider outputting a Search Console verification method within a users Site Health information. This would help with determining whether Site Kit was used to verify site owners or an alternate method, with alternate methods at present potentially causing disconnection issues or resulting in avoidable lengthy support topics. 

Example issues with a manual verification:
- A user may have their http site verified manually prior to Site Kit setup (http://wwww.example.com). Site Kit uses this existing verification and doesn't add other variations of that domain (non www / https). If a user removes the www from their site, or makes their site https they'll become disconnected. 
- Users are unable to remove their own verification at SC level as the message states that the verification file remains on their site if SK remains active. If they open a support topic the support team can determine from their SH info that SK is the verification method this notification if referring to. 

Possible Flag that may be useful:
- **Search Console verification**:  Site Kit || Prior verification

If not too trivial the below would be a further improvement:
- **Search Console verification method**: Site Kit || DNS || File upload || Existing snippet

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new field "Verification Status" should be incorporated into Site Kit's Site Health section, right below "User Status":
    * If the user is not verified (i.e. `Verification` user option false-y), it should say "Not verified" (debug: "not-verified").
    * Otherwise, if verified through a file token (i.e. `Verification_File` user option), it should say "Verified through file" (debug: "verified-file").
    * Otherwise, if verified through a meta token (i.e. `Verification_Meta` user option), it should say "Verified through meta tag" (debug: "verified-meta").
    * Otherwise, it should say "Verified outside of Site Kit" (debug: "verified-non-site-kit").

## Implementation Brief
* Using `includes/Core/Util/Debug_Data.php`,
	* Update the `get_fields` method to include the `verification_status` key to `$fields` array. The value should be a new private method `get_verification_status_field`.
	* `get_verification_status_field` should return an array with the keys below with their respective values as per the AC.
		* `label`
		* `value`
		* `debug`
	* To check whether the user is verified, use the `Authentication` class which is already instantiated in the `Debug_Data` class with the following options:
		* To check if user is verified: `$this->authentication->verification()->get();`
		* For file verification: `$this->authentication->verification_file()->get();`
		* For meta verification: `$this->authentication->verification_meta()->get();`

### Test Coverage
* No new tests to be added.

### Visual Regression Changes
* N/A

## QA Brief

* Check that the new field _"Verification Status"_ displays the correct values for each option mentioned in the AC

## Changelog entry

* Add a new "Verification Status" row to the Site Health information for Site Kit.

**Comment by aaemnnosttv** [comment] 2021-06-28 10:21
Sounds like a good addition, perhaps below "User Capabilities" we have now? cc: @felixarntz

**Comment by felixarntz** [comment] 2021-06-28 17:51
@aaemnnosttv I've defined ACs here, putting this under "User Status", since it's a similar type of value to "Site Status" and "User Status", plus it's closely related to the "User Status" value (since e.g. "not-verified" would also indicate a problem here).

We've decided to add this enhancement in a support team meeting last week, so moving it forward.

**Comment by eugene-manuilov** [comment] 2021-06-30 17:57
> * To check whether the user is verified, the get method of user_options can be called passing the appropriate meta key.
> * The meta keys are found in:
>   * includes/Core/Authentication/Verification.php
>   * includes/Core/Authentication/Verification_File.php
>   * includes/Core/Authentication/Verification_Meta.php

@asvinb we can get these options using the Authentication class instance which is available in the Debug_Data class:

```php
$verification = $this->authentication->verification()->get();
$verification_file = $this->authentication->verification_file()->get();
$verification_meta = $this->authentication->verification_meta()->get();
```

**Comment by asvinb** [comment] 2021-07-01 08:10
Nice! Thanks @eugene-manuilov 👍 
IB Updated.

**Comment by eugene-manuilov** [comment] 2021-07-01 09:10
Thanks, @asvinb! IB :heavy_check_mark:

**Comment by wpdarren** [comment] 2021-07-07 14:18
### QA Update:  ⚠️ Clarification from Engineer. 

@danielgent would like some clarification here, when I add a meta tag, in the <head> i.e. 
<meta name="google-site-verification" content="" /> in the Site Health I see the `verification status` is `Verified outside of Site Kit` Should that not be `Verified through meta tag` 

**Verified:**

When the user is not verified (Site Kit is not activated) then the `verification status` is `not verified`
![image](https://user-images.githubusercontent.com/73545194/124768786-40e7e000-df39-11eb-8d04-e3d24a79482b.png)

When a HTML tag is manually entered into the <head> of the site then the `verification status` is `Verified outside of Site Kit`
![image](https://user-images.githubusercontent.com/73545194/124769416-bc499180-df39-11eb-863a-355649529185.png)

When a HTML file is uploaded (or Site Kit creates Search console) then the `verification status` is `Verified through file
![image](https://user-images.githubusercontent.com/73545194/124774203-ea30d500-df3d-11eb-906f-f478130dd27b.png)

**Comment by danielgent** [comment] 2021-07-07 15:08
@wpdarren  Thanks for that.  I followed the IB (thus why it was merged) but I was also seeing similar results to you! I just assumed I'd done something wrong locally :thinking:   (in hindsight I should have tested it myself on jurassic.ninja!)

Happy for you to send this back to me to investigate again (and get some of the other engineers involved :smile: )

**Comment by wpdarren** [comment] 2021-07-07 15:29
Thanks @danielgent I'll send this back to Execution for discussion.

**Comment by felixarntz** [comment] 2021-07-07 18:56
@wpdarren @danielgent I _think_ your observations are all expected behavior: The information is supposed to say "Verified outside of Site Kit" anytime you manually put something. In other words, if you add a meta tag via some plugin or theme code change, or if you upload the verification file, it is outside of Site Kit - since you made the change.

It will only say "Verified through file" or "Verified through meta tag" if the respective verification happened automatically via Site Kit Service during the setup flow (i.e. the user basically doesn't notice that it happens). In order to fake that behavior you'd have to modify the respective WordPress database options.

**Comment by wpdarren** [comment] 2021-07-08 13:31
### QA Update: Pass ✅ 

**Verified:**

When the user is not verified (Site Kit is not activated) then the `verification status` is `not verified`
![image](https://user-images.githubusercontent.com/73545194/124768786-40e7e000-df39-11eb-8d04-e3d24a79482b.png)

When a HTML tag is manually entered into the <head> of the site then the `verification status` is `Verified outside of Site Kit`
![image](https://user-images.githubusercontent.com/73545194/124769416-bc499180-df39-11eb-863a-355649529185.png)

When a HTML file is uploaded (or Site Kit creates Search console) then the `verification status` is `Verified through file
![image](https://user-images.githubusercontent.com/73545194/124774203-ea30d500-df3d-11eb-906f-f478130dd27b.png)

When a Meta tag is used then the `verification status` is `Verified through meta tag`
![image](https://user-images.githubusercontent.com/73545194/124930262-7821c400-e001-11eb-9df6-8f4ef7559020.png)

**Closed** 2021-07-15 19:14 UTC
Labels: Module: Site Verification, P1, Type: Enhancement
