### ISSUE TITLE
Analytics Storybook stories slightly broken

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3948] opened 2021-08-26 21:53 UTC
## Bug Description

Various Analytics setup Storybook stories (e.g. https://google.github.io/site-kit-wp/storybook/main/?path=/story/analytics-module-setup--start-with-matched-property) have the "Configure Analytics" button disabled when it should actually be enabled given the circumstances / UI displayed.

This may have been introduced by some of the GA4 enhancements, where checking these scenarios might have been missed.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The following Storybook stories should have the "Configure Analytics" button enabled as expected:
    * https://google.github.io/site-kit-wp/storybook/main/?path=/story/analytics-module-setup--start-with-matched-property
    * https://google.github.io/site-kit-wp/storybook/main/?path=/story/analytics-module-setup--create-new-view
    * https://google.github.io/site-kit-wp/storybook/main/?path=/story/analytics-module-setup--existing-tag-w-access
    * https://google.github.io/site-kit-wp/storybook/main/?path=/story/analytics-module-setup--no-tag-gtm-property-w-access
    * https://google.github.io/site-kit-wp/storybook/main/?path=/story/analytics-module-setup--existing-tag-w-access-gtm-property-w-access
    * https://google.github.io/site-kit-wp/storybook/main/?path=/story/analytics-module-setup--existing-tag-w-access-gtm-property-w-o-access

## Implementation Brief

* In `stories/module-analytics-setup.stories.js`:
  * Update all stories that use an empty Analytics settings object to use the default settings (`fixture.defaultSettings`).
    ```diff
    - registry.dispatch( MODULES_ANALYTICS ).receiveGetSettings( {} );
    + registry.dispatch( MODULES_ANALYTICS ).receiveGetSettings( { ...fixtures.defaultSettings } );
    ```
  * Add default settings for the GA4 module using the `ga4Fixtures.defaultSettings` fixture to all stories where it is missing.
  * Set an existing tag for the GA4 module to be `null` in all stories where it is missing.
  * Add properties for the GA4 module using the `receiveGetProperties` action to all stories where it is missing.
  * Check all stories to make sure the `Configure Analytics` button is active where it makes sense to be active. If the button is disabled for a story where it should be active, then it means that something is missing in the setup and you need to fix it. You can see what is wrong by adding `console.log( error )` call to the catch section of the following try/catch block: https://github.com/google/site-kit-wp/blob/5dcbb1ecd2ae9d0e98cd7552ef38fcf9e22e5a36/assets/js/googlesitekit/data/utils.js#L372-L377

### Test Coverage

* N/A

## QA Brief

* Check the first five stories as listed in the AC to ensure the **Configure Analytics** button has been enabled:
  * https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-setup--start-with-matched-property
  * https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-setup--create-new-view
  * https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-setup--existing-tag-w-access
  * https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-setup--no-tag-gtm-property-w-access
  * https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-setup--existing-tag-w-access-gtm-property-w-access
* However, the final story listed in the AC should now show the following error message, as per these comments on this issue:
  * https://github.com/google/site-kit-wp/issues/3948#issuecomment-990842038
  * https://github.com/google/site-kit-wp/issues/3948#issuecomment-991153421
  * Story: https://google.github.io/site-kit-wp/storybook/develop/?path=/story/analytics-module-setup--existing-tag-w-access-gtm-property-w-o-access
  * Should now show error:
![image](https://user-images.githubusercontent.com/18395600/146048479-f185084f-1cf8-4ee5-a85f-9c8d5198eb69.png)

## Changelog entry

* Fix bug where error for an Analytics property in Tag Manager without access would not show up.

**Comment by tofumatt** [comment] 2021-12-07 23:30
IB ✅

**Comment by techanvil** [comment] 2021-12-09 10:02
Hi @felixarntz @eugene-manuilov, I've started this and have been able to fix all but one of the stories mentioned.

Regarding the last story, it doesn't seem like https://google.github.io/site-kit-wp/storybook/main/?path=/story/analytics-module-setup--existing-tag-w-access-gtm-property-w-o-access (Existing Tag w/ access, GTM property w/o access) can be made to enable the **Configure Analytics** button without some changes to production code.

This is because the story specifies a non-permissioned GTM property, but the `canSubmitChanges` boolean which is used for the button disabled state is derived from the `validateCanSubmitChanges` function which throws if GTM is active with a non-permissioned property.

https://github.com/google/site-kit-wp/blob/1735da6226a671f86b1e043796ec4710729e7e06/assets/js/modules/analytics/components/setup/SetupForm.js#L104

https://github.com/google/site-kit-wp/blob/1735da6226a671f86b1e043796ec4710729e7e06/assets/js/modules/analytics/datastore/settings.js#L192-L201

Looking at the actual story, though, it does *look* like the button should be disabled, so I'm wondering if we need to make a change in the component or in `validateCanSubmitChanges` so that `canSubmitChanges` is true if GTM is active with a non-permissioned property *but* there is also an existing permissioned tag present.

I'd be grateful if you could take a look and let me know what you think. Please let me know if any of the above needs clarification.

For reference I have created a draft PR, #4516 with the changes so far which do enable the Configure Analytics button for the other stories.

Thanks!

**Comment by felixarntz** [comment] 2021-12-09 19:04
@techanvil Hmm, this is indeed a bit of a weird scenario. @aaemnnosttv Is that experience even accurate? It's a bit strange that https://google.github.io/site-kit-wp/storybook/main/?path=/story/analytics-module-setup--existing-tag-w-access-gtm-property-w-o-access shows you UI as if you can proceed although you don't have access to the GTM tag. I guess that is somehow because an existing tag takes precedence for our UI, and since _that_ tag there is access for, we show the corresponding UI, but then the button still remains disabled. Unless I'm missing something here, that behavior is odd and should be fixed - although that would be responsibility of a separate issue.

Pending @aaemnnosttv's feedback above, I tend to agree that this one story you're outlining @techanvil should indeed not have the submit button enabled - in that case it's okay to proceed without that one, but based on the above probably worth opening another issue to fix the overall UI displayed there.

**Comment by aaemnnosttv** [comment] 2021-12-10 10:41
@felixarntz it looks like the `ExistingGTMPropertyError` is being bypassed here due to the condition requiring no existing tag (not sure why this is here) https://github.com/google/site-kit-wp/blob/e66e6901ccccb4a2aeba1bb408af3af727969863/assets/js/modules/analytics/components/setup/SetupMain.js#L111

In this situation using the current logic, the user should be blocked the same way as if there was an existing tag that they didn't have permission/access for. Removing the line above fixes this.

![image](https://user-images.githubusercontent.com/1621608/145560359-5889b8b7-5e81-4852-ac80-64ca90135c04.png)

It's also worth noting that right now the `ExistingGTMPropertyNotice` is not rendered as part of the GA4 and GA4Transitional setup forms. Since the notice is always for non-blocking scenarios I think this may have been removed (or not migrated) by mistake. We don't catch GA4 tags in GTM yet which is out of scope for this issue but I think the component should be here also.

**Comment by felixarntz** [comment] 2021-12-10 17:21
@aaemnnosttv Ahh, yeah that makes sense. I think we should remove this line, I don't think it should cause any problems and it will actually fix a bug 🎉 

@techanvil Per the above, can you make this one production code change to remove https://github.com/google/site-kit-wp/blob/e66e6901ccccb4a2aeba1bb408af3af727969863/assets/js/modules/analytics/components/setup/SetupMain.js#L111? This should make the button no longer relevant for that story, which is the correct behavior. Please verify this in the story for that scenario, which should then not require further adjustments.

I'm also gonna update the changelog here since now this issue fixes a user-relevant bug and not "just" broken Storybook stories.

**Comment by techanvil** [comment] 2021-12-14 17:21
Thanks @aaemnnosttv @felixarntz, good shout - I've removed that line. Cheers!

**Comment by wpdarren** [comment] 2021-12-15 13:02
### QA Update: ✅ 

**Verified:**

- Went through all of the links in the AC and confirmed the buttons are appearing and titled "Configure Analytics"
- Went through the last link in the AC and confirmed that the error message is appearing. 

<details>
 <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/73545194/146191152-4ae2ecb0-10eb-4c52-9b02-9ade908de4d9.png)

![image](https://user-images.githubusercontent.com/73545194/146191199-367c64e0-2785-470b-a7f9-fb53ce4c0f2d.png)

</details>

**Closed** 2021-12-20 21:22 UTC
Labels: Type: Bug, P2, Module: Analytics
