### ISSUE TITLE
Google Kit Plugin Is Unable to show Fetched Data 

### ISSUE THREAD

**Issue by akshayhirani** [google/site-kit-wp#150] opened 2019-07-06 02:42 UTC
![2](https://user-images.githubusercontent.com/29171885/60750423-b674ea80-9fc5-11e9-9c8e-729797389516.png)
![gk](https://user-images.githubusercontent.com/29171885/60750422-b5dc5400-9fc5-11e9-9b5b-043d90f50e48.png)

**Comment by ask543** [comment] 2019-07-07 10:12
google site kit installation error 
"Forbidden
You don't have permission to access / on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request"
what should i do ?

**Comment by jamesozzie** [comment] 2019-07-08 10:34
@akshayhirani @ask543 Thanks for reporting, do you mind starting the process again after resetting Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)? You can also try [deleting the project](https://i.imgur.com/EoA1edo.png) from your Cloud Console and [checking your API key](https://i.imgur.com/p9c4S3M.png), ensuring it has no restrictions. Please also install Site Kit by opening an [incognito](https://i.imgur.com/ALzgiHp.png) window. 

If that works then we can try the Analytics setup process again, if it fails we will need to troubleshoot further.

**Comment by ThSocialIntrovert** [comment] 2019-07-09 17:59
At this time I am also experiencing the same issue. All google accounts are connected and show as synced. 
After 48 hours, we are now looking at the same image as above. A pulsating grayed out dashboard for only Google Site Key App.
Running on Up to date Wordpress site.  
![Screen Shot 2019-07-09 at 1 44 13 PM](https://user-images.githubusercontent.com/52716087/60911665-b1c46680-a251-11e9-979d-f356fba5ab82.png)
![Screen Shot 2019-07-09 at 1 59 06 PM](https://user-images.githubusercontent.com/52716087/60911686-bee15580-a251-11e9-83f9-5ab1eace8960.png)

**Comment by jamesozzie** [comment] 2019-07-10 09:02
@ThSocialIntrovert Thanks for reporting. Do you mind trying the steps below so we can troubleshoot further?

- Reset Site Kit (Site Kit > Settings > Admin Settings > Reset Site Kit)
- Temporarily deactivate other plugins
- Deleting the existing Site Kit [project](https://i.imgur.com/EoA1edo.png) from your [Cloud Console ](https://console.cloud.google.com/cloud-resource-manager?previousPage=%2Fiam-admin%2Fsettings%3Fproject%3Dampfaces-prescho-1561454403106&folder=&organizationId=&project=ampfaces-prescho-1561454403106)and checking your [API key](https://console.cloud.google.com/apis/credentials), ensuring it has [no restrictions](https://i.imgur.com/p9c4S3M.png).
- Install Site Kit by opening an incognito window.

Let me know if the above works.

**Comment by ThSocialIntrovert** [comment] 2019-07-10 20:19
Hello.
Sorry for the delayed response...I wanted to make sure I gave this the proper attention before responding. 

I found the cause of the issue and figured I would share it since I have a feeling it will be common once fully released out of Beta. 

Most security plug-ins, my example is ithemes security pro, have a  " _Limits the number of characters that can be sent in the URL. Hackers often take advantage of long URLs to try to inject information into your database._" setting. When this is enabled, Google Kit can not fetch the info needed, but still shows a "connection in the site kit dashboard.

Once we unchecked this feature, the site kit dashboard reappeared and all information was visible.

Thank you for your quick response.  I hope this will help others with similar issues.
The Social Introvert

**Comment by jamesozzie** [comment] 2019-07-11 11:02
Thanks for your input, very useful indeed. I will checkout other plugins which may also have the same option/feature. 

@akshayhirani @ask543 Do you have a security plugins or configurations that limit characters?

**Comment by ask543** [comment] 2019-07-11 11:10
hi
when i am clicking on  allow (picture-1) , then next screen is showing
picture-2, what correction steps should i take ?

**Comment by jamesozzie** [comment] 2019-07-11 12:41
@ask543 There were no screenshots with your last post, can you share?

**Comment by jamesozzie** [comment] 2019-07-31 19:39
I will close this ticket as I didn't receive a response and I am unable to replicate the issue. If the problem persists feel free to reopen.

**Closed by jamesozzie** 2019-07-31 19:39 UTC
Labels: Type: Support

**Comment by nullfud** [comment] 2019-08-17 11:32
Failed to load resource: the server responded with a status of 404 ()
commons.js?ver=1.0.0-beta.1.0.4:1 error 
Object
code: "invalid_json"
message: "The response is not a valid JSON response."
__proto__: Object

I got this error in the console when i am on the plugins dashboard, nothing loads.

Ive tried disabling cloudflare, 3 browsers, incongito mode, reinstalling, disabling every plugin including my wordfence security one, i am out of ideas, please hlep me out.

**Comment by jamesozzie** [comment] 2019-08-19 08:58
@nullfud Can you try the following steps in order to generate your own response, which you can input to the JSON response window:

1. In the browser address bar (preferably using an incognito window) visit the following:
2. https://developers.google.com/web/site-kit/?sitename=yourwebsitecom&siteurl=http://yourwebsite.com
3. Replace the yourwebsitecom and also http://yourwebsite.com with your own site details. Include the https or http
4. Press enter, with your cursor in the address bar (as if you are visiting that URL)
5. The project details should appear, and you can then copy the credentials and paste them back into the requested field in Site Kit you highlighted.

If that fails to result in resolving your issue please provide the following:
- Your WordPress [Site Health information](https://i.imgur.com/Rtkmsba.png)
- Any security plugins or software in use (ModSecurity, iThemes, WordFence etc

**Comment by dallaswhitehat** [comment] 2019-11-15 01:13
Just in case anyone is still coming across google site kit installation error
"Forbidden 403
You don't have permission to access / on this server."

My issue was related to Modsecurity on my host server - I turned it off in cpanel and was able to install with no issues and turned it back on afterwards.

**Comment by akshayhirani** [comment] 2019-11-20 13:41
Hey my site kit is still throwing the same error

**Comment by akshayhirani** [comment] 2019-11-20 13:41
> I will close this ticket as I didn't receive a response and I am unable to replicate the issue. If the problem persists feel free to reopen.

i  was unable to reach so
