### ISSUE TITLE
Define new capabilities for dashboard sharing

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4522] opened 2021-12-09 16:25 UTC
## Feature Description

One of the cornerstones of dashboard sharing is perhaps the [new capabilities](https://docs.google.com/document/d/19OtWe7jXKC6dIUfs6J4gDrXujHgCuXnksxBM1uUWmOQ/edit#heading=h.11n1hkqhne10) coming to Site Kit's custom permissions. These control which users are able to view the shared dashboard, use shared module data, and manage sharing settings.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Core\Permissions` class should be extended with the following new capabilities:
	- `googlesitekit_view_shared_dashboard`  
	Granted dynamically for users that have a role which any module is explicitly shared with via the dashboard sharing settings AND have the `shared_dashboard_splash` dismissed item (see #4525)
	- `googlesitekit_read_shared_module_data(module_slug)` _module-specific meta capability_  
	Granted dynamically for users who have a role that the **given module** has been explicitly shared with via the dashboard sharing settings
	- `googlesitekit_manage_module_sharing_options(module_slug)` _module-specific meta capability_  
	Granted dynamically for users who are an authenticated admin who either:
		- Is the module owner of the given module
		- OR the given module's sharing management is set to “All admins” via the dashboard sharing settings
	- `googlesitekit_delegate_module_sharing_management(module_slug)` _module-specific meta capability_  
	Granted dynamically for the module owner of the given module only as long as they are authenticated.
* These capabilities should only be granted if the `dashboardSharing` feature flag is enabled
* Test coverage should be thoroughly added for each new capability

Note: shared roles for modules are managed by the new `Module_Sharing_Settings` class added in https://github.com/google/site-kit-wp/issues/4475

## Implementation Brief

- Use this [POC branch](https://github.com/google/site-kit-wp/tree/enhancement/4522-dashboard-sharing-capabilities) as a helpful starting point for Executing the IB below. Some pieces of added code may have to be modified.

- In `includes/Core/Permissions/Permissions.php`:
    - Define new constants for the new capabilities:
        ```php
        /*
         * Custom base capabilities.
         */
        const VIEW_SHARED_DASHBOARD = 'googlesitekit_view_shared_dashboard';
    
        /*
         * Custom meta capabilities
         */
        const READ_SHARED_MODULE_DATA            = 'googlesitekit_read_shared_module_data';
        const MANAGE_MODULE_SHARING_OPTIONS      = 'googlesitekit_manage_module_sharing_options';
        const DELEGATE_MODULE_SHARING_MANAGEMENT = 'googlesitekit_delegate_module_sharing_management';
        ```

    - Add these capabilities to a new `get_dashboard_sharing_capabilities()` method:
        ```php
        public static function get_dashboard_sharing_capabilities() {
            return array(
                self::VIEW_SHARED_DASHBOARD,
                self::READ_SHARED_MODULE_DATA,
                self::MANAGE_MODULE_SHARING_OPTIONS,
                self::DELEGATE_MODULE_SHARING_MANAGEMENT
            );
          }
        ```

    - Add the new base capability, `self::VIEW_SHARED_DASHBOARD` to the `get_capabilities()` method.
    
    - Add a new private property `$modules` which holds a reference to an instance of the `Google\Site_Kit\Core\Modules\Modules` class. Instantiate this property within the constructor.

    - In the constructor, map the new custom capabilities to the existing custom base capabilities by adding lines to the existing maps:
        ```php
        $this->base_to_core = array(
            // Allow editors and up to view shared dashboard data.
            self::VIEW_SHARED_DASHBOARD => 'edit_others_posts',
        )
        ```
        ```php
        $this->meta_to_base = array(
			// Allow users that can generally view the shared dashboard to read shared module data
			self::READ_SHARED_MODULE_DATA => self::VIEW_SHARED_DASHBOARD,
			// Admins who can manage options for SK can generally manage module sharing options.
			self::MANAGE_MODULE_SHARING_OPTIONS => self::MANAGE_OPTIONS,
			self::DELEGATE_MODULE_SHARING_MANAGEMENT => self::MANAGE_OPTIONS
		);
        ```
    - Action all TODOs in the constructor's existing mapped capabilities only if the DashboardSharing feature flag is enabled. Map the capabilities to `edit_posts` instead of `edit_others_posts`.
     
    - Call a function that contains logic to prevent access to the new capabilities as per the ACs at the end of `map_meta_capabilities()` as shown below:
        ```php
            if ( in_array( $cap, self::get_dashboard_sharing_capabilities() ) ) {
                $caps[] = $this->filter_dashboard_sharing_capabilities($cap, $user_id, $args);
            }
        ```

    - The new `filter_dashboard_sharing_capabilities()` private method called above should prevent access to capabilities as mentioned in the AC as follows:
        - Capabilities should be granted only if Dashboard Sharing feature flag is enabled.
            ```php
            if ( ! Feature_Flags::enabled( 'dashboardSharing' ) ) {
                return = array('do_not_allow');
            }
            ```
        - To check the rest of the conditions, fetch the following data:
            1. Fetch the settings which contain the `sharedRoles` from the `Module_Sharing_Settings` class. Refer to [4475](https://github.com/google/site-kit-wp/issues/4475) for the full format of `$settings`:
                ```php
                $settings = new Module_Sharing_Settings(new Options( $this->context ));    
                ```
            1. Also fetch the user's roles from the user's object using the `$user_id` passed to this method:
                ```php
                $user = new WP_User( $user_id );  // roles will be available on $user->roles 
                ```
        
        - Now check for each capability in the ACs and prevent access, i.e. return `array('do_not_allow')` if any of the checks fail as below:
            1. For `VIEW_SHARED_DASHBOARD`, compare the `sharedSettings` with the passed user's roles. Further, create an instance of the `Google\Site_Kit\Core\Dismissals\Dismissed_Items` class and call its `is_dismissed()` method to check if the `shared_dashboard_splash` item is dismissed.  E.g.
                ```php
                if ( $cap === self::VIEW_SHARED_DASHBOARD) {
                    $user_has_shared_role = ! empty(array_intersect($sharedRoles, $user->roles));
                    if ( ! $user_has_shared_role ) {
                        return array('do_not_allow');
                    }
                    // Instantiate a Dismissed_Items object and call the is_dismissed('shared_dashboard_splash') method 
                }
                ```
    
            1. For `READ_SHARED_MODULE_DATA`, compare the `sharedRoles` for the specific module slug passed into `$args[0]` (i.e. `$sharedSettings[$args[0]]`) with the user's roles (i.e. `$user->roles`).
            
            1. For `MANAGE_MODULE_SHARING_OPTIONS`:
                - First check if the user is an authenticated admin. If not, prevent access.
                - Otherwise, check the value of `$sharedSettings[$args[0]]['management']`. If the value is 'all_admins', pass the check (do nothing).  
                - If the `management` value above is 'owner', then fetch the owner of the module. To fetch the module owner, first get the module instance by calling `$this->modules->get_module()` passing the name of the module slug - `$sharedSettings[$args[0]]`. Then use the `Module_With_Owner::get_owner_id` method. Check if this owner_id is the same as the `$user_id`. If not, prevent access.
           
            1. For `DELEGATE_MODULE_SHARING_MANAGEMENT`:
                - Similar to the `MANAGE_MODULE_SHARING_OPTIONS` check above, fetch the owner_id and prevent access if it does not match the `$user_id`.

### Test Coverage

* Add phpunit tests along the lines of [Issue #4472](https://github.com/google/site-kit-wp/issues/4472) to cover the new capabilities.

### QA
 - Test current Site Kit user permissions with the `dashboardSharing` Feature Flag disabled. There should be no change, such as:
   - Non-admins should still not be able to use Site Kit. 
   - Admins should still be able to authenticate, verify and see all dashboard modules as usual.
- Quick smoke test with the `dashboardSharing` Feature flag enabled to check if the plugin doesn't throw any errors.

### QA Eng
- Check if new PHPUnit tests added are sufficient and pass.

## Changelog entry

* N/A

**Comment by felixarntz** [comment] 2021-12-22 23:07
@aaemnnosttv Maybe worth a note in the ACs to rely on `Module_Sharing_Settings` here? I've added #4475 as a dependency to this for that reason, I don't think this can be implemented before.

**Comment by aaemnnosttv** [comment] 2021-12-23 09:12
> Maybe worth a note in the ACs to rely on `Module_Sharing_Settings` here? I've added #4475 as a dependency to this for that reason, I don't think this can be implemented before.

It does say "via the dashboard sharing settings" which refers to the same thing but I'll update it to be more clear. Thanks for adding the dependency, we'll need that first indeed 😄

**Comment by FlicHollis** [comment] 2021-12-23 11:38
Hi @aaemnnosttv and @felixarntz when you are next looking at ACs please could we prioritise this one as it is blocking two tickets in IB - thanks so much!

**Comment by aaemnnosttv** [comment] 2022-01-18 10:59
Thanks @jimmymadon – the IB looks good overall, just a few comments but **there has also been one small change to the ACs** for the `googlesitekit_view_shared_dashboard` capability which was surfaced from another issue (this now requires a dismissal that will only be set on the splash screen).

> * Action all TODOs in the constructor's existing mapped capabilities only if the DashboardSharing feature flag is enabled.

These should be `edit_posts` rather than `edit_others_posts` as this is the base capability for available roles with Dashboard Sharing. These TODOs are rather old so it's okay that these may not match.

> * Modify the `get_capabilities()` method to include the new capabilities.

I think this should only get the `googlesitekit_view_shared_dashboard` capability as this has only returned primitive (non-meta) capabilities so far, so it would be incorrect to declare meta capabilities together with the others. Maybe we should introduce a new method for these? I'm not sure. Thoughts @felixarntz ?

> * Call a function that contains logic to prevent access to the new capabilities as per the ACs at the end of `map_meta_capabilities()` as shown below:

It isn't clear here how the capabilities that have logic relying on the module owner would work yet. We'll likely need to update `Permissions` to accept a `Modules` instance as a dependency (this is needed in another issue as well, see https://github.com/google/site-kit-wp/issues/4523) so we can get access to a module's owner ID via its `Module_With_Owner::get_owner_id` method.

---

As a general tip since this is one of your first IBs, please refrain from including copy/pasteable snippets of code in the IB. Instead, pseudo code can be nice where a description would be less useful although a simple description is usually sufficient 👍  If you've already gone through the trouble of fleshing out some of the implementation, feel free to share a branch for reference as a potential starting point as well.

**Comment by felixarntz** [comment] 2022-01-18 14:30
@aaemnnosttv 
> I think this should only get the `googlesitekit_view_shared_dashboard` capability as this has only returned primitive (non-meta) capabilities so far, so it would be incorrect to declare meta capabilities together with the others. Maybe we should introduce a new method for these? I'm not sure. Thoughts @felixarntz ?

Agreed, this should only return primitive capabilities. With that said, typically meta capabilities have some sort of "parent" primitive capability that they are based on, but then being "stricter" based on additional limtations (e.g. in WP "edit_post" is based on "edit_posts" plus custom logic). I think we already have some sort of "parent" primitive that fits each of the three. 

@jimmymadon This leads to one thing I think is slightly off in the IB though, which is:

> ```php
> $this->meta_to_core = array(
>    // Allow editors and up to read shared module data.
>    self::READ_SHARED_MODULE_DATA => 'edit_others_posts',
>    // Only admins can manage module sharing options.
>    self::MANAGE_MODULE_SHARING_OPTIONS => 'manage_options',
>    self::DELEGATE_MODULE_SHARING_MANAGEMENT => 'manage_options'
> );
> ```

I think it would make more sense for these to tie into primitive Site Kit capabilities, instead of core capabilities. For example `self::READ_SHARED_MODULE_DATA` should at its foundation be based on `self::VIEW_SHARED_DASHBOARD`, since that is the basic primitive capability that determines this (plus then being further restricted per module). You have this currently based on `edit_others_posts` which may end up resulting in a somewhat similar experience (because that's what `self::VIEW_SHARED_DASHBOARD` is based on too), but it would bypass any extra logic used on `self::VIEW_SHARED_DASHBOARD`, so it's a bit problematic to do so. I suggest the following:

```php
$this->meta_to_base = array(
    // Allow editors and up to read shared module data.
    self::READ_SHARED_MODULE_DATA => self::VIEW_SHARED_DASHBOARD,
    // Only admins can manage module sharing options.
    self::MANAGE_MODULE_SHARING_OPTIONS => self::MANAGE_OPTIONS,
    self::DELEGATE_MODULE_SHARING_MANAGEMENT => self::MANAGE_OPTIONS,
);
```

**Comment by jimmymadon** [comment] 2022-01-18 23:14
@aaemnnosttv Thanks for the feedback - I have hopefully addressed all your comments. And apologies for going a bit overboard with the code snippets there. Will definitely stick to pseudo code/instructions and avoid this in the future. Since I already added this implementation on my local, I've created a branch and added it to the IB this time like you suggested.

@felixarntz I actually started mapping self::READ_SHARED_MODULE_DATA to self::VIEW_SHARED_DASHBOARD in $meta_to_base but then for some reason I felt like avoiding mapping to our own base capabilities. But I now completely get the reason for mapping custom meta caps to custom base caps and have rectified the IB as you suggested. Thanks!

**Comment by aaemnnosttv** [comment] 2022-01-20 07:50
Thanks @felixarntz – I also didn't realize we could use our own custom cap as a base capability.

> * Add these capabilities to a new `get_dashboard_sharing_capabilities()` method:

@jimmymadon this method includes both the base/primitive and meta capabilities which makes it less useful because the meta caps require a module slug and the base cap doesn't. How about we repurpose this to return only the module meta caps? That way we'd know it only returns a list of capabilities that are all checked in the same way. Perhaps `get_module_meta_capabilities` would be a more appropriate name then as well as we probably don't need to handle dashboard sharing capabilities in a special way other than logic related to the feature flag.

Otherwise this LGTM 👍

**Comment by jimmymadon** [comment] 2022-01-20 10:59
@aaemnnosttv In addition to logic related to the feature flag, they also share logic that requires `settings` from the `Module_Sharing_Settings` which I thought was better off in its own method instead of making `map_meta_capabilities()` longer than it already is. Hence I suggested something like this: 
```php
if ( in_array( $cap, self::get_dashboard_sharing_capabilities(), true ) ) {
	$caps[] = $this->filter_dashboard_sharing_capabilities( $cap, $user_id, $args );
}
```

You are correct, when the first capability `self::VIEW_SHARED_DASHBOARD` is checked, it won't have `$args` set and it doesn't require it either. But it will still use the `FeatureFlag` and `Module_Sharing_Settings` logic.

However, I could remove this method from the IB as it would not be used anywhere other than in the above snippet for now and we can discuss this in a code review after it is executed?

**Comment by aaemnnosttv** [comment] 2022-01-21 08:30
> However, I could remove this method from the IB as it would not be used anywhere other than in the above snippet for now and we can discuss this in a code review after it is executed?

It's not a big deal and I imagine you'll be submitting the PR for this as well so we don't need to agonize over polishing the IB before this can move forward as this is indeed getting more into code review territory now 😄 

This looks good to move forward with, so we can address the finer details in CR 👍 

IB ✅

**Comment by techanvil** [comment] 2022-02-04 10:22
Hi @jimmymadon, thanks for addressing the comments on the PR.

I've spotted an issue in testing. I set up a fresh WP / SiteKit instance, running your branch, and created users with the different roles, Subscriber, Contributor, Author and Editor.

I noticed that with the `dashboardSharing` feature flag enabled, the Site Kit menu bar is visible for Contributor, Author and Editor users, although the main view is not present. Subscribers don't see the SK menu bar at all.

![image](https://user-images.githubusercontent.com/18395600/152512185-8416748f-8ef8-4650-8b25-584ff12e5b15.png)

For some reason, I don't see this on my local install.

It's not readily apparent to me what the cause is, and I don't want to spend too long digging just in case this is currently an expected behaviour that will be fixed in a forthcoming ticket, so I am sending it back your way to take a look.

**Comment by jimmymadon** [comment] 2022-02-04 12:30
@techanvil I saw this too when I tested this and I suspected it is because we removed the check to be an `authenticated admin` when the Dashboard Sharing feature flag is enabled. Since this issue is about creating the new capabilities, I thought we will have issues that then `use` these capabilities in other places both in the front and back end? There might be no point in "hiding" the menu links at this stage as I'm not sure of the ACs on these links. We may eventually do further checks and show the menu links again anyways. So as long as there are no fatal errors with dashboard sharing on and off and everything behaves the same with the feature flag off, we should be fine? 
@aaemnnosttv Could you confirm the above or should I dig deeper and finalise the menu links as part of this issue?

**Comment by jimmymadon** [comment] 2022-02-08 11:27
@techanvil @aaemnnosttv I can confirm that [changing the `VIEW_DASHBOARD` capability](https://github.com/google/site-kit-wp/pull/4710/files#diff-6a96d6ceb9110e7766917fc3e7f4a9be142ad07bf492e8fbacaabee9c29276fdR150) to allow users with `edit_posts` instead of `manage_options` is what causes that link to show. The below line will have to be updated to `VIEW_SHARED_DASHBOARD` - should this be done as part of this issue?
https://github.com/google/site-kit-wp/blob/5f3288819b42c21d0f5cbcc9c48bf8c0fdb46abc/includes/Core/Admin/Screens.php#L282

**Comment by techanvil** [comment] 2022-02-08 11:59
> @techanvil @aaemnnosttv I can confirm that [changing the `VIEW_DASHBOARD` capability](https://github.com/google/site-kit-wp/pull/4710/files#diff-6a96d6ceb9110e7766917fc3e7f4a9be142ad07bf492e8fbacaabee9c29276fdR150) to allow users with `edit_posts` instead of `manage_options` is what causes that link to show. The below line will have to be updated to `VIEW_SHARED_DASHBOARD` - should this be done as part of this issue?
> 
> https://github.com/google/site-kit-wp/blob/5f3288819b42c21d0f5cbcc9c48bf8c0fdb46abc/includes/Core/Admin/Screens.php#L282

Thanks for the update - I think @aaemnnosttv is better positioned to answer this one than I am.

**Comment by aaemnnosttv** [comment] 2022-02-08 11:59
> The below line will have to be updated to `VIEW_SHARED_DASHBOARD` - should this be done as part of this issue?

@jimmymadon this is largely what #4599 will handle. The permission for the screen should remain as is – the logic behind it will change in that issue to allow for either (ability to view main or shared dashboards) as well as splitting out new separate capabilities for each.

**Comment by wpdarren** [comment] 2022-02-21 12:18
### QA Update: ✅ 

**Verified:**

Tested current Site Kit user permissions with the dashboardSharing Feature Flag disabled. 

- There should be no change:  non-admins are not able to use Site Kit. Tested this with all user roles.
- Admins were able to authenticate, verify and see all dashboard modules as usual.
- Ran a smoke test with the `dashboardSharing` enabled and no errors appeared on the FE or in console.

**Comment by felixarntz** [comment] 2022-02-24 19:25
### Approval ⚠️ 

Looking at the code in the `Permissions` class from #4710, some things may not yet work as expected here, particularly related to the code within the condition https://github.com/google/site-kit-wp/pull/4710/files#diff-6a96d6ceb9110e7766917fc3e7f4a9be142ad07bf492e8fbacaabee9c29276fdR314: Even with the `dashboardSharing` feature flag enabled, that code still requires administrators to be verified for almost any permission (including `VIEW_SHARED_DASHBOARD`), which is not really accurate (see https://github.com/google/site-kit-wp/pull/4710/files#diff-6a96d6ceb9110e7766917fc3e7f4a9be142ad07bf492e8fbacaabee9c29276fdR326). The verification requirement is only relevant for administrators that are also authenticated, and that in turn is only needed to view the regular dashboard, but not to view the shared dashboard (which as far as I can tell will also go through this condition).

We may need to use more granular logic per permission there, or at least exclude the `VIEW_SHARED_DASHBOARD` permission from this logic.  At the same time, other permissions like `MANAGE_OPTIONS` or the `VIEW_AUTHENTICATED_DASHBOARD` permission that will be introduced later in #4599 should still require authentication and verification as before, even with the `dashboardSharing` flag enabled.

Since this is all behind a feature flag and also fairly complex, we don't need to rush a fix here, and I'm going to approve this, but it will require some follow-up work that would be good to capture and explore in a follow-up issue. cc @jimmymadon @techanvil @aaemnnosttv

**Closed by felixarntz** 2022-02-24 19:25 UTC
Labels: P0, Type: Enhancement, Rollover, PHP

**Comment by jimmymadon** [comment] 2022-02-25 01:30
> The verification requirement is only relevant for administrators that are also authenticated, and that in turn is only needed to view the regular dashboard, but not to view the shared dashboard (which as far as I can tell will also go through this condition).

Ah right, of course, didn't realise an admin would still need to view a shared dashboard! My tests only focused on checking `VIEW_SHARED_DASHBOARD` for non-admins! So yes, would be good to have a follow up issue to tweak the authentication and verification rules in the context of Dashboard Sharing, specially for admins.
