### ISSUE TITLE
Notification is hidden due to scroll position after page reload.

### ISSUE THREAD

**Issue by asvinb** [google/site-kit-wp#4356] opened 2021-11-16 08:03 UTC
## Bug Description
Currently, after dismissing a notification, for e.g the `authentication_success` one, the browser maintains the scroll position after page reload. This results in potential new notifications being missed by the user unless they scroll to the top of the page.

## Steps to reproduce

1. Disconnect any module and proceed to connect the module again.
2. A notification will be displayed on the main dashboard after successful setup.
3. Dismiss the notification.
4. Reload the page.
5. Notice the scroll position and how any new notifications are missed unless the user scrolls to the top of the page.

Context: https://github.com/google/site-kit-wp/issues/4274#issuecomment-966114096

https://user-images.githubusercontent.com/1621608/141852852-1b430925-6620-4cd8-94ed-e9be9a9f906c.mp4

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* New notifications on the dashboard should be fully visible when refreshing the page so long as they are within the current viewport

## Implementation Brief

* Prevent default autoscroll browser behaviour when a notification is added on the page by adding the below snippet to the `useMount` hook of the `BannerNotification` component:
```javascript
if ( global.history.scrollRestoration ) {
  global.history.scrollRestoration = 'manual';
}
```

### Test Coverage

* No new tests needed.

## QA Brief

* 

## Changelog entry

*

**Comment by jimmymadon** [comment] 2021-12-04 14:53
When the user dismisses the Success Notification, the 'Site Overview' heading is the first component below the Heading. On page reload, when a new `BannerNotification` is added, it appears that the default browser behaviour is to scroll down again to the 'Site Overview' heading as that is where the window position was before reload. The fix in the IB that would meet the AC would be to prevent this default behaviour. But that would apply every time a `BannerNotification` is on the screen. Would that be ok?

**Comment by eugene-manuilov** [comment] 2021-12-06 11:51
> The fix in the IB that would meet the AC would be to prevent this default behaviour. But that would apply every time a BannerNotification is on the screen. Would that be ok?

@jimmymadon, yes, that's unpleasant because it will prevent the expected scrolling to the previous window position for legit cases. I don't even think that this scrolling issue that we see is initiated by the browser itself because the current position of the scroll before reloading is `0, 0`. So, the browser should not scroll to the first widget area at all.

https://user-images.githubusercontent.com/873049/144841153-02ccc35c-23f5-441b-8ab4-e46aa36631c5.mp4

I have a feeling that something in our code scrolls to the first widget area, but I can't find it :confused:. @asvinb do you know what it can be?

**Comment by asvinb** [comment] 2021-12-08 14:22
@eugene-manuilov @jimmymadon I had another look and couldn't find anywhere in our code where we scroll to the first widget area 🤔  The reason why I'am thinking more about the scroll position is that if you open a new tab, you cannot reproduce the issue, i.e the user is at the top of the page thus seeing the notification. @jimmymadon does the code you suggested in the IB fix the issue so that at least we know it's about the browser scroll position?

**Comment by jimmymadon** [comment] 2021-12-08 14:55
@asvinb @eugene-manuilov The code suggested in the IB does fix the issue when I tested it. I tried a few other snippets which involved adding `global.window.scrollTo(0,0)` instead. However, they didn't work unless you called them in a `setTimeout()` after 5-10 seconds, as something was causing the page to scroll after page load.

**Comment by eugene-manuilov** [comment] 2021-12-10 12:59
@jimmymadon @asvinb can you reproduce this issue in FF on your end? I have tried it on my end and everything works correctly there 🤔

**Comment by jimmymadon** [comment] 2021-12-13 22:16
@eugene-manuilov I did some more testing - this issue occurs only on Google Chrome and Microsoft Edge. It is not reproducible on Firefox and Safari. So it is a browser specific issue.

**Comment by eugene-manuilov** [comment] 2021-12-14 13:49
Thanks, @jimmymadon. I think in this case we shouldn't try to fix this because any fix to this may affect the correct behaviour in other browsers. @felixarntz i am going to send this ticket to the Triage column and assign it to you to make the final decision whether we need to close this ticket or keep trying to find a workaround.

**Comment by felixarntz** [comment] 2021-12-14 22:35
@asvinb @jimmymadon @eugene-manuilov I agree that this is not worth fixing since it's a browser-specific default in refresh behavior. Marking this as `wontfix`.

**Closed by felixarntz** 2021-12-14 22:35 UTC
Labels: Type: Bug, P2
