### ISSUE TITLE
Refactor Autocomplete (Get rid of componentWillMount and componentWillReceiveProps)

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1761] opened 2020-07-10 19:55 UTC
## Bug Description

On the Site Kit dashboard, a console warning is currently triggered due to usage of legacy component lifecycle methods: https://fb.me/react-unsafe-component-lifecycles

<img width="1664" alt="Screenshot 2020-07-10 at 12 49 16" src="https://user-images.githubusercontent.com/3531426/87192863-36eebb00-c2ac-11ea-9caa-bb6358b039ae.png">

The warning is only emitted on the Site Kit dashboard (not on other Site Kit screens) so it has to be caused by something only in use there. I wasn't able to find any usage of these methods in our codebase, so I suspect it is something 3P-related. Let's find out the cause and see if we can upgrade the respective dependency so that this warning goes away.

Potentially related: #1356 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The Site Kit dashboard should not emit a console warning about usage of legacy React component lifecycle methods.

## Implementation Brief

* Remove the `accessible-autocomplete`  package from package.json
* Install the `@reach/combobox` package
* Create a new functional component called `PostSearcherAutoSuggest`  in `js/components/PostSearcherAutoSuggest.js`
	* Build out the new component to provide the same functionality as the existing `Autocomplete` component - https://github.com/google/site-kit-wp/blob/develop/assets/js/components/post-searcher.js#L172
	* Follow the docs available here  https://reach.tech/combobox#server-side-search
	* Update as required to match existing styles and confirm that there are no unexpected visual changes via VRT.
* Refactor `PostSearcher`  in `assets/js/components/post-searcher.js`  to be a functional component and rename the file  to `PostSearcher.js` to match updated naming conventions
	* Replace the existing `Autocomplete` component with the new `PostSearcherAutoSuggest`
* Update e2e tests in `tests/e2e/specs/dashboard/search.test.js` to match any changes to selectors as needed.

## QA Brief

* The post search component on the Site Kit dashboard should continue to work as it does in the latest release
* Minor differences may be present in terms of functionality particularly regarding use of the keyboard as the replacement is designed for accessibility first, so while there may be differences here it should actually be an improvement

## Changelog entry

* Update post search input to use a better maintained and more accessible autocomplete library.

**Comment by aaemnnosttv** [comment] 2020-07-22 19:45
I did a quick test and these seem to be triggered by `Autocomplete` in `assets/js/components/post-searcher.js`.
See https://github.com/alphagov/accessible-autocomplete/issues/418. We're already on the latest version and the repo states "We cannot currently respond to issues or pull requests" so it might be worth looking into an alternative.

We should also check other views as it may be that other pages use Components with dependencies where these warnings are shown for other components that aren't on the main dashboard.

We don't currently use these methods in any of our own components though as these were addressed in https://github.com/google/site-kit-wp/issues/860.

**Comment by felixarntz** [comment] 2020-07-22 23:38
@tofumatt Do you happen to know another accessible autocomplete? :)

**Comment by tofumatt** [comment] 2020-07-28 18:20
I enjoyed working with [react-autosuggest](https://github.com/moroshko/react-autosuggest) in the past—used it on addons.mozilla.org (it's still in use in the search box at the top of the page) and it worked quite well and is very accessible.

I'd nominate it as the library to use for react autocomplete. 👍

**Comment by aaemnnosttv** [comment] 2020-07-29 09:25
@tofumatt unfortunately it looks like that one is no longer maintained either 
![image](https://user-images.githubusercontent.com/1621608/88782648-7ebf7e80-d196-11ea-9233-efc916aea252.png)

**Comment by aaemnnosttv** [comment] 2020-07-29 13:01
I took a quick look around other screens and didn't see any other warnings, so it looks like the auto-suggest is indeed the only thing we need to update here.

**Comment by tofumatt** [comment] 2020-07-29 13:27
Huh, darn, didn't realise that. For what it's worth, though:

* https://github.com/moroshko/react-autosuggest/search?q=componentWillMount&unscoped_q=componentWillMount
* https://github.com/moroshko/react-autosuggest/search?q=componentWillReceiveProps&unscoped_q=componentWillReceiveProps

It doesn't have those deprecated calls, so would be safe to use 🤷‍♂️

**Comment by felixarntz** [comment] 2020-07-30 23:22
IB ✅

**Comment by cole10up** [comment] 2020-09-07 06:43
**Tested**

The post search component on the Site Kit dashboard should continue to work as it does in the latest release
Minor differences may be present in terms of functionality particularly regarding use of the keyboard as the replacement is designed for accessibility first, so while there may be differences here it should actually be an improvement

**Comment by cole10up** [comment] 2020-09-09 16:29
**Tested**

Installed latest SK, activated and setup modules.

Checked console for errors. Confirmed the above errors didn't exist.
![image](https://user-images.githubusercontent.com/57115907/92626534-e16c6580-f27e-11ea-9a69-cf50772f6b6e.png)

Checked basic functionality of post search and module metrics.

Passed QA ✅

**Comment by felixarntz** [comment] 2020-09-10 23:09
⚠️ There is a regression here found by @aaemnnosttv: Titles displayed in the dropdown are now missing spaces included, which seems to be caused by something in the modified client logic or the new library (the REST endpoint still returns the correct data like before).

<img width="1311" alt="Screenshot 2020-09-10 at 16 06 21" src="https://user-images.githubusercontent.com/3531426/92821511-fda3fb80-f37f-11ea-939a-b153c36ee84f.png">

**Comment by aaemnnosttv** [comment] 2020-09-11 08:21
@felixarntz PR ✅  – assigning back to you to merge.

**Comment by cole10up** [comment] 2020-09-11 18:16
Retested on a site that included many title pages with spaces.

![image](https://user-images.githubusercontent.com/57115907/92959020-0946ff00-f420-11ea-86d1-794d52b7faaf.png)

Verified spacing is present, no issues clicking into each item and navigating to the correct page metrics.

One thing to note - some items on the drop down without page names are showing blank.

Passed QA ✅

**Closed** 2020-09-11 22:50 UTC
Labels: P2, Type: Bug
