### ISSUE TITLE
Full width blue background on GA4 notices

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#3540] opened 2021-06-09 16:29 UTC
## Feature Description

Some Figma screens have the blue bar full width, others have the blue bar at the end of the dropdown, which is correct?

[Related Asana task](https://app.asana.com/0/1200316599642381/1200447894111324)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The "Learn more" link in the blue notice in the Analytics setup flow (UA, GA4, and GA4-transitional only) should always be aligned to the very right of the notice, even if the screen is very wide.
* Instead, the blue notice in that flow should have its maximum width limited in a way that prevents the "Learn more" link from appearing too far away / too decoupled from the notice main content. (There is no exact number given, please include @Pratheep-lab in the PR review for this.)

## Implementation Brief

Using `_googlesitekit-settings-notice.scss` update `.googlesitekit-settings-notice` adding a `max-width` of 1098px.

### Test Coverage

* n/a

### Visual Regression Changes

* Check visual tests

## QA Brief

* Using storybook and / or the analytics set up flow, verify that the maximum width of the GA4 notice is 1098px

## Changelog entry

* Improve Google Analytics 4 notices.

**Comment by aaemnnosttv** [comment] 2021-06-16 10:27
> update `&--info` adding a `max-width` of 1000px.

@Hazlitte this limit should really be applied to all notices, not just the info variant.

Regarding the max-width, it would be good to base this number on something to align with other elements. Unfortunately the select boxes vary a bit on the set up / settings forms depending on the length of the contents. I found `1098px` however lines up consistently on the account creation form since the text inputs all have the same width and gap between.

![image](https://user-images.githubusercontent.com/1621608/122202928-2ffdfe80-cea6-11eb-9409-16ef8d92e9b4.png)

In this case, it's 1098 because each text input is 350px wide with 24px between. The image above includes the extra 24px on the end so we remove that to come to 1098.

![image](https://user-images.githubusercontent.com/1621608/122202945-368c7600-cea6-11eb-826c-86cb3b1c2d78.png)

This looks pretty good on the setup/settings views as well

![image](https://user-images.githubusercontent.com/1621608/122203264-8703d380-cea6-11eb-8308-a8fb870e11c3.png)

Let's start with this and iterate if we get more input from design. cc: @Pratheep-lab

**Comment by Hazlitte** [comment] 2021-06-17 09:43
Thanks @aaemnnosttv,  I have updated the IB to make this change to the settings notice body class so that it is applied to all notices.

**Comment by aaemnnosttv** [comment] 2021-06-17 14:08
> Thanks @aaemnnosttv, I have updated the IB to make this change to the settings notice body class so that it is applied to all notices.

@Hazlitte – this would result in an overall larger element since `.googlesitekit-settings-notice` has padding which would be outside of the max-width applied to the body. Let's keep the max width applied to the `.googlesitekit-settings-notice` itself.

I'll update the IB with this since it's a simple change to the selector, otherwise –

IB ✅

**Comment by wpdarren** [comment] 2021-06-23 14:03
### QA Update: ❌ 

@johnPhillips while this is looking great on larger screens, on smaller screens there are issues.  This site has a Google Analytics account with UA and GA4 properties. When connecting, the GA4 notice is cut off as per screenshot.  Also, when I go to the Analytics settings page and edit, the same issue occurs. I've been through the other flows on mobile and the notices look fine. 

![image](https://user-images.githubusercontent.com/73545194/123108548-6ac9de80-d432-11eb-8fb6-abc8fcdaaf5a.png)


**Verified:**

While going through the different GA4 analytics flow, the notices are a maximum width of the GA4 notice is 1098px

![image](https://user-images.githubusercontent.com/73545194/123107480-7ec11080-d431-11eb-9bc9-d3fb74da8d6b.png)

![image](https://user-images.githubusercontent.com/73545194/123107521-85e81e80-d431-11eb-9f0a-15affb31f137.png)

**Comment by johnPhillips** [comment] 2021-06-23 15:45
@wpdarren Good catch, thanks. 
This appears to be a pre-existing issue as when I revert the change the issue is still visible. It might be to do with the dropdown overflowing the container, because the content wraps perfectly when I remove the dropdown from the markup:

![Screenshot 2021-06-23 at 16 41 30](https://user-images.githubusercontent.com/2470911/123127465-36f6b500-d442-11eb-9d71-3f87702eaec6.png)

I'm very happy to investigate further but am conscious this was estimated as a 3pt 1-liner to address a different problem.
@aaemnnosttv Should I investigate under this issue or is it out of scope?

**Comment by aaemnnosttv** [comment] 2021-06-24 15:21
@wpdarren the mobile issue looks like the same as this one: https://github.com/google/site-kit-wp/issues/3497 
If so, it would be great if you could add any additional information on that one if needed.

If that's the only issue here then I think we can leave it to be handled in that issue. Was there anything else?

**Comment by wpdarren** [comment] 2021-06-24 15:29
@aaemnnosttv I couldn't see anything else, so will have a quick run through it and then get this to approved.  I'll also have a look at #3497 and add any additional information :)

**Comment by wpdarren** [comment] 2021-06-25 11:59
### QA Update: ✅ 

- Verified that the maximum width of the GA4 notice is 1098px on large screen sizes 
- Also checked the notices on smaller screens to make sure no styling issues exist. 

[Screenshot 1](https://user-images.githubusercontent.com/73545194/123421623-fe2b1d00-d5b4-11eb-9092-83894279792b.png) - [Screenshot 2](https://user-images.githubusercontent.com/73545194/123421660-0aaf7580-d5b5-11eb-900f-ae3513511f58.png) - [Screenshot 3](https://user-images.githubusercontent.com/73545194/123421680-113ded00-d5b5-11eb-95bb-acb88a27f177.png)

**Closed** 2021-07-01 16:15 UTC
Labels: Good First Issue, Module: Analytics, P1, Type: Enhancement, UX
