### ISSUE TITLE
Implement infrastructure for detecting an existing GA4 tag and related permission

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3288] opened 2021-05-04 19:25 UTC
Infrastructure for detecting an existing GA4 tag and whether the current user has access to it should be implemented.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Functionality for detecting an existing GA4 tag should be added to the `modules/analytics-4` store, in an `assets/js/modules/analytics-4/datastore/tags.js` file:
    * The only tag matcher needed is similar to the first one that the `modules/analytics` store uses (i.e. the one that matches "https://www.googletagmanager.com/gtag..."), except that the matched ID should start with `G-` instead of `UA-` **and** only the part after `G-` should actually be the extracted ID, while for UA properties the `UA-` prefix is part of the actual extracted ID.
    * The ID found in an existing tag is the "measurement ID", so any docs etc. here should not call this "property ID" like it is in for UA snippets (i.e. in the `modules/analytics` store).
    * ~~A `getTagPermission( measurementID )` selector should be implemented that checks whether the current user has access to the property that owns the given `measurementID`.~~
        * ~~Its resolver should first call and wait for the `getAccountSummaries` (see #3103) selector to get all accounts with all properties, and then rely on the `matchPropertyByMeasurementID` action (see #3168) until it finds the matching property.~~
        * ~~If a matching property is found, an object with `accountID` and `propertyID` (both based on the matched property) should be returned.~~
        * ~~If no matching property is found, the user doesn't have access, so `null` should be returned.~~
        * ~~Results for either check should also be keyed in the store's state so that for any subsequent calls they can be immediately returned (as usual).~~

## Implementation Brief

Create a file: `assets/js/modules/analytics-4/datastore/tags.js`, and from the analytics equivalent file `assets/js/modules/analytics/datastore/tags.js` the only parts we need are:

```js
const existingTagStore = createExistingTagStore( {
	storeName: STORE_NAME,
	tagMatchers,
	isValidTag: isValidMeasurementID,
} );
```

`tagMatchers` param will contain the following based on the implementation from the analytics UA capturing tag:

```js
[
	// Detect gtag script calls.
	/<script [^>]*src=['|"]https:\/\/www.googletagmanager.com\/gtag\/js\?id=G-([a-z0-9]*?)['|"][^>]*><\/script>/i
];
```

`isValidTag: isValidMeasurementID` where `isValidMeasurementID` checks that we have an alphanumeric string only. - I couldn't find any more indepth validation rules per https://support.google.com/analytics/answer/7372977

~~Add a state item containing an empty object `const baseInitialState = { tagPermissions: {} }`~~

~~Add a selector: `getTagPermission( state, measurementID )` and a corresponding resolver `getTagPermission( measurementID )`.
In the selector we return the `measurementID` in our `tagPermissions` state object.~~

~~In the resolver:
Make a call to `getAccountSummaries` selector in~~ https://github.com/google/site-kit-wp/blob/5e0799853ac18b6d4c2c962b5150a2da58975c6c/assets/js/modules/analytics-4/datastore/accounts.js#L76 ~~and return an object containing `accountID` and `propertyID` properties if one exists, or `null` if it doesn't.~~

### Test Coverage

* Add jest tests for the new datastore.

### Visual Regression Changes

* N/A

## QA Brief

* Check the `assets/js/modules/analytics-4/datastore/tags.js` file and make sure it defines the existing tag store. 
* Verify tag matchers for the analytics-4 tag detection in the `assets/js/modules/analytics-4/utils/tag-matchers.js` file. Make sure all regular expressions are correct and there is nothing else to add.

## Changelog entry

* Added GA4 script tag detection.

**Comment by tofumatt** [comment] 2021-05-20 22:10
IB ✅ 

(Worth noting here to pay particular attention to the ACs, as they largely already spell out the implementation here, and provide a bit of extra context.)

**Comment by felixarntz** [comment] 2021-05-25 17:50
@eugene-manuilov I've reduced the scope of this issue here to only implement the regular existing tag detection but not the existing tag permission parts. Also see related #3289 where tag permission is no longer a concern with the updated ACs.

I'll confirm this tomorrow with @marrrmarrr - we can work based on the updated scope for now.

**Comment by felixarntz** [comment] 2021-05-25 17:50
@eugene-manuilov Also I'm suggesting to downsize this to either a 7 or a 3 after the reduction in scope - what do you think?

**Comment by eugene-manuilov** [comment] 2021-05-25 18:19
> @eugene-manuilov Also I'm suggesting to downsize this to either a 7 or a 3 after the reduction in scope - what do you think?

Yes, makes sense to me. I am going to reduce it to 7 since 3 is a little bit too low.

**Comment by Hazlitte** [comment] 2021-06-02 14:52
**QA Eng - advice needed**
@eugene-manuilov, @tofumat. I have: 
* checked the code and run the tests
* using a regex string generator and regex tester I confirmed that the `Detect gtag script calls.` regex in the constant `tagMatchers` works like the example in the IB although they differ slightly in syntax

I am unsure how to 'Make sure all regular expressions are correct and there is nothing else to add.' as per the QA brief. Can you advise?

**Comment by eugene-manuilov** [comment] 2021-06-02 15:56
@Hazlitte check the documentation for [the Google Analytics 4](https://developers.google.com/analytics/devguides/collection/ga4) tag and make sure that we have regular expressions (defined [here](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics-4/utils/tag-matchers.js#L19-L32)) for every possible way of adding a ga4 tag on a page. We need to be confident that we don't miss anything.

**Comment by Hazlitte** [comment] 2021-06-03 10:34
@eugene-manuilov Thanks for you advice.  I have spent some more time trying to complete the QA on this ticket.  I'm not very familiar with Google's products and can't find some of the settings in Analytics or be sure that I understand all the ways of adding ga4 tags.  I think it would be best if someone else who understands Analytics 4 better than me picks this up.

**Comment by ivankruchkoff** [comment] 2021-06-07 10:05
Let's add tests to test positive / negative matches for each scenario, this way we can't just test once and accidentally add regressions.

We currently have one in place which handles the scenario at the top of this page:
Example based on https://developers.google.com/analytics/devguides/collection/ga4
https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics-4/datastore/tags.test.js#L52 which covers off 
https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics-4/utils/tag-matchers.js#L21

Can we add tests for the following?
https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics-4/utils/tag-matchers.js#L23
https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics-4/utils/tag-matchers.js#L24
https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics-4/utils/tag-matchers.js#L26
https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics-4/utils/tag-matchers.js#L27
https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics-4/utils/tag-matchers.js#L29
https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics-4/utils/tag-matchers.js#L31

I couldn't see in the ga4 docs where any of these other scenarios above were mentioned, I'm guessing they're the equivalent from regular analytics and should work the same but would be good to reference some docs to see what's there.

Also it appears based on the documentation that we can define measurement IDs using gtag('config') as per
https://developers.google.com/analytics/devguides/collection/ga4#add_an_additional_google_analytics_property_to_an_existing_tag

So it seems the following is also valid:
```js
<script src="https://www.googletagmanager.com/gtag/js"></script>
<script>
  gtag('config', 'G-12345678');
</script>  

```

Finally do we want to handle more edge cases such as self closing script tags which chrome will handle just fine.
```js
<script async src="https://www.googletagmanager.com/gtag/js?id=G-12345678" />
```

**Comment by eugene-manuilov** [comment] 2021-06-07 12:53
Thanks, @ivankruchkoff. I've created a follow-up PR that improves tag matchers.

**Comment by ivankruchkoff** [comment] 2021-06-08 20:18
LGTM QA: ✅

**Closed** 2021-06-22 04:00 UTC
Labels: Module: Analytics, P1, QA: Eng, Rollover, Type: Enhancement
