### ISSUE TITLE
Switch login flow to use JS API

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#9677] opened 2024-11-13 03:06 UTC
## Feature Description

Due to complications with project provisioning, we need to switch to using the JS API for the time being – i.e. using the popup-based flow with JS callback for handling the credential.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The SiwG login flow should be updated to use the [`popup` UX mode instead of `redirect`](https://developers.google.com/identity/gsi/web/guides/integrate#pop-up_versus_redirect)
_See also [Handle credential response](https://developers.google.com/identity/gsi/web/guides/handle-credential-responses-js-functions#handle_credential_response)_

## Implementation Brief

* Update the rendering of the SiwG button + JS
	* Update the call to `google.accounts.id.initialize` to only include the `client_id` and define the `callback` with a reference to a function which will handle the credential response
	* The `callback` function should make a POST request to the login endpoint, passing the `response` it receives as the post body
	* If the response from the login endpoint is `ok` and `redirected`, navigate to the `url` of the response
* Conditionally call `google.accounts.id.prompt()` after initializing if one tap is enabled in the module settings
* Remove the functionality which verifies the `g_csrf_token` which is only present in the `redirect` flow

See POC PR https://github.com/google/site-kit-wp/pull/9683

### Test Coverage

* Remove tests around removed `g_csrf_token`

## QA Brief

* Follow the QA:Brief from #9339 
* Ensure Sign in flow works the same
* Verify that "One Tap" setting (when enabled from Sign In With Google settings) is working as expected (https://developers.google.com/identity/gsi/web/guides/offerings#one_tap), logging in the user directy

## Changelog entry

* Update the Sign in with Google login to use the popup approach.

**Comment by tofumatt** [comment] 2024-11-14 00:35
IB ✅

**Comment by kelvinballoo** [comment] 2024-11-26 19:20
### QA Update ⚠ 

This is tested good mostly. I have 2 queries though:

**ITEM 1:** ⚠ 
While testing the last point of the QAB from https://github.com/google/site-kit-wp/issues/9339 , the results were not as expected.
`When a user is registered, verify that you and the site admin receive emails.`

I did not receive any admin email or the user did not receive any email. The issue is illustrated in the attached video below.
I am not sure if my setup is wrong or indeed there is something wrong with the email not being sent.

<Details>

https://github.com/user-attachments/assets/81a77a2c-c161-4468-b06c-5a4102c12c41

</Details>

______________________________________________________________________

**ITEM 2:** ⚠ 
I am unsure on how to verify the "One Tap" setting is working as expected.
Refer to the below video, where I tested on Chrome incognito. The sign in button did not appear as illustrated on https://developers.google.com/identity/gsi/web/guides/offerings#one_tap 
<Details>

https://github.com/user-attachments/assets/b8020399-bb6d-46ff-bef9-6a95688673e5

</Details>

On the other hand, I tested in Safari and the button does appear different and is more as expected.
There are 2 things from here:
- What is the correct expectation? Is there any reason why it doesn't work similarly in the Chrome incognito browser?
- Happy to jump on a call if any clarification is required.

<Details>

https://github.com/user-attachments/assets/c0b0105a-6033-47a8-b00c-47dbb8f841d8

</Details>

_________________________________________

Other than that, everything else is working as expected: ✅ 

- Able to login with an existing user:
   <Details>

   https://github.com/user-attachments/assets/060c8bd7-ce23-44f0-82b6-0999371f47d5

   </Details>

- Redirect is working as expected as an argument:
   <Details>

   https://github.com/user-attachments/assets/a8b46980-b61d-4e2c-8dc5-cf479ac5b926

   </Details>

- When site is set to cannot register for any user, Sign in with Google fails accordingly.

   <Details>

   https://github.com/user-attachments/assets/111e0448-251c-436a-89b1-429db3287139

   </Details>

- When site is set to anyone can register, Sign in with Google works as expected.

   <Details>

   https://github.com/user-attachments/assets/5f7c6728-ad77-4d9d-9185-a4fb90253a15

   </Details>

- Under a multisite setup, if one site has SiwG setup, it will have the SiwG button. The other one which doesn't have it set up will not have the 'Sign in with Google' button.
   <Details>

   https://github.com/user-attachments/assets/ce491d06-e0e0-4c25-80d4-d4d5e3464928

   </Details>


- Same tests on multisite is working as expected. 
   <Details>

   https://github.com/user-attachments/assets/15b04f15-9808-41dd-97be-824ef03d135c

   </Details>


- Redirect works as expected on multisite setup.

   <Details>

   https://github.com/user-attachments/assets/29951fbc-e928-4f43-8ac4-46072e216e17

   </Details>

**Comment by zutigrm** [comment] 2024-11-27 09:31
> ITEM 1: ⚠
While testing the last point of the QAB from https://github.com/google/site-kit-wp/issues/9339 , the results were not as expected.
When a user is registered, verify that you and the site admin receive emails.

This issue was only about switching the sign in flow to popup modal from redirection, this is seems like multisite related, if only those emails are not received. Are you able to receive any email on the test site? You can verify if it is the email server issue (which is related to the test env), by creating a new user manually on the website, and tick the box to send the registration details, add some email you have access to, and verify if email is received. If it is, but only the emails from registration via SiWG button are not sent, you can open a follow up issue so this is investigated, if not spot already in the bug bash, best to check with @tofumatt he will have more context on this

> ITEM 2: ⚠
I am unsure on how to verify the "One Tap" setting is working as expected.
Refer to the below video, where I tested on Chrome incognito. The sign in button did not appear as illustrated on https://developers.google.com/identity/gsi/web/guides/offerings#one_tap

There is a chat about this in the [group](https://fueled10up.slack.com/archives/C0788NZMLF2/p1732202969760429) on the slack, as I recall there is a follow up issue around this after bug bash, since it is not directly related to this issue

> On the other hand, I tested in Safari and the button does appear different and is more as expected.
There are 2 things from here:

> What is the correct expectation? Is there any reason why it doesn't work similarly in the Chrome incognito browser?
Happy to jump on a call if any clarification is required.

This is out of scope of the current issue, which is not modifying the button. Although we are rendering the button using third party Google script, not sure we have much of a control how will button behave per browser. Regarding the behaviour and expectations @tofumatt might have more context on this

**Comment by tofumatt** [comment] 2024-11-27 12:42
You will not see any One-Tap popup on a browser you aren't signed in to, but also: **the Sign in with Google JS file determines when to show/not show the One-Tap popup. So even when it is enabled: you may not see it.**

Moving this to Approval as it seems like everything is functioning as-expected. 👍🏻

**Closed** 2024-11-29 15:23 UTC
Labels: P0, Type: Enhancement, Team S, Module: Sign in with Google
