### ISSUE TITLE
The Edit links on User Input Review/Settings do not have proper styling

### ISSUE THREAD

**Issue by kuasha420** [google/site-kit-wp#6452] opened 2023-01-24 14:02 UTC
## Bug Description

The Edit links that appear on right right side of the questions and are used to expand/collapse questions does not have proper styling when they are disabled. The links are disabled when the answer is being updated and will most likely be disabled as part of #6427 when answers are being submitted. 

Problem with the disabled state styles are as follows: 

1. Does not appear to be disabled unless hovering the links. 
2. Even on hovered state, the up/down arrow on the right of the link doesn't have proper color. 

## Steps to reproduce

1. Throttle connection for easier inspection. 
2. Go to User Input Settings, Edit an answer and submit.
3. Observe the Edit button state. 

#### Hover on disabled state. 
![Screenshot_20230124_200050](https://user-images.githubusercontent.com/6187401/214314576-9bcf1bb5-b271-443f-8e72-e8dd8f4d24eb.png)

#### Disabled state, doesn't look like it!
![Screenshot_20230124_200110](https://user-images.githubusercontent.com/6187401/214314590-49986e24-5fff-40a0-bc6d-e6818a0c61b2.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `Edit` links on User Input Review and Settings page should have proper disabled link style as seen in the story for [links](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/global--links). 
    * The text and icon of the link should have the disabled appearance. 
    * There should be no hover state. 

## Implementation Brief
* Using `assets/sass/components/user-input/googlesitekit-user-input-preview.scss`,
    * Add styles for `.googlesitekit-user-input__preview-group-title button.googlesitekit-cta-link--disabled` as per the AC.

### Test Coverage
* No new tests to be added.

## QA Brief

* 

## Changelog entry

*

**Comment by tofumatt** [comment] 2023-01-30 23:01
ACs are good here 👍🏻 

Moving to IB.

**Comment by techanvil** [comment] 2023-02-01 10:33
Hey @asvinb, is this estimate bumped up by one, i.e. should it have the `Exp: SP` label set?

**Comment by asvinb** [comment] 2023-02-01 11:17
@techanvil No, this estimate has not been bumped by one. The change here is straightforward and also easy to QA. Bumping to 11 might be too much for this task. What do you think?

**Comment by techanvil** [comment] 2023-02-01 13:04
Hey @asvinb, we are supposed to be applying the `Exp: SP` as a blanket rule, as an experiment so see how it averages out across all issues. So, with that in mind I'll bump it to an 11, and add the label - although I fully agree it seems on the high side for this issue.

**Comment by aaemnnosttv** [comment] 2023-02-10 15:06
Closing as a duplicate of #6427 which is in progress now.

**Closed by aaemnnosttv** 2023-02-10 15:06 UTC
Labels: Type: Bug, P1, Exp: SP
