### ISSUE TITLE
Create the "Most engaged traffic source" key metric widget tile

### ISSUE THREAD

**Issue by jimmymadon** [google/site-kit-wp#6246] opened 2022-12-02 01:01 UTC
## Feature Description

<img width="380" alt="Screenshot 2022-12-19 at 01 33 20" src="https://user-images.githubusercontent.com/1721319/210283067-80e1cd6a-6bf5-4c52-93ca-8f2a2f044788.png">

- Refer to the widget tables in the [design doc](https://docs.google.com/document/d/1k8NOo2xEHUQAcgYG0TB5sUjGcPiC8SWIalEdd9G8-9g/edit#bookmark=id.qz6oxctz8fe7) and the [PRD](https://docs.google.com/document/d/1JvJ2gKxaX2PcYOnmA3-xqz4hK_ZHxj8Rd0svq6S8tiU/edit#bookmark=id.w8o73hf5pz1f) explaining the sources of data and other details.
- [Figma mock for all widgets](https://www.figma.com/file/CdtrHB0HAjfGRWTnTMMQI0/Key-Metrics?node-id=3407%3A73377&t=mxlhDsRNGXcli8tk-0)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new component should be created for the 'Most engaged traffic source' Key metric widget and should be displayed within the Key Metrics widget area if it is selected (based on #6257 and #6313).
* The following data should be fetched from the [Google Analytics Data API](https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema) for the global date range selected on the Site Kit dashboard:
    * metric: `engagementRate`
    * dimension: `sessionSource`
* Values should be calculated as follows:
    * Display  `sessionSource` from the query’s top result as a percentage of total `engagementRate`.
* The percentage change figure (with a red for negative or green for positive highlight) should be calculated based on the 'previous' period before the selected date range. 

## Implementation Brief
* Wait for #6244 and #6245 to be merged.
* Create `assets/js/modules/analytics-4/components/widgets/EngagedTrafficSourceWidget.js` which exports the `EngagedTrafficSourceWidget` functional component.
* Most of the styles should already be in place as a result of #6245 - reuse the `MetricTileText` component introduced here.
* To get the data for the component, use the following options:
    * metrics: `engagementRate`
    * dimensions: `sessionSource`
    * limit: `1`
    * orderBy: `engagementRate` (descending)
* Query the GA4 data store via the `getReport` selector with the metric and dimension as mentioned above.
    * To get the selected date range, query the `core/user` data store via the `getDateRangeDates` with `compare` set to `true`.
* To get the % change, compare the metric values for the current and previous date range and use the `ChangeBadge` component introduced in #6244 to display the percentage increase or decrease.
* To get the % of engaged sessions compared to the total, use the value from `totals` and metric values for the current date range.
* Add stories for `EngagedTrafficSourceWidget` in `assets/js/modules/analytics-4/components/widgets/EngagedTrafficSourceWidget.stories.js`.

### Test Coverage
* Add tests for the newly added component.

## QA Brief

* Activate the `userInput` feature flag and complete the user input survey.
* Go to the dashboard page and ensure you see the `Most engaged traffic source` widget there and it shows the correct data.

## Changelog entry

* Add the "Most engaged traffic source" key metric widget tile.

**Comment by tofumatt** [comment] 2023-01-30 18:44
ACs look good, moving to IB 👍🏻

**Comment by eugene-manuilov** [comment] 2023-02-15 17:49
IB ✔️

**Comment by wpdarren** [comment] 2023-07-25 10:02
### QA Update: ⚠️ 

@jimmymadon two observations:

1. . The term on the tile is `Engaged Sessions`, which in GA4 is a value.  In the AC it mentions `Engagement Rate` which is a percentage in GA4.  I am confused by the reference to Engaged Sessions in the tile.  Am I missing something here?  I feel if its confusing for me, it'll be confusing for the user. 

<details>
 <summary>Screenshot</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/e9d2e2a3-2c59-46ce-8076-018c4a1806f1)

</details>


3. In the tile it says `Direct` at 99.3% but in Analytics it's appearing as is 99.4% `Engagement Rate`, which is very slightly different.  I made sure to filter on oi.ie and selected 28 days like in Site Kit.  Could this be one we need to investigate in the ticket that Tom is digging into?  It's not much different, but users could query the difference. 

<details>
 <summary>Screenshot</summary>

![image](https://github.com/google/site-kit-wp/assets/73545194/d0cc1997-cdce-4de8-99f5-c2dfa6eea1d9)

</details>

**Comment by wpdarren** [comment] 2023-07-26 04:00
@jimmymadon while Tom has brought up a really interesting point about the explore tool, I still feel I need some thoughts around point 1.  Trying to get around my terminology here, and I do feel it's a little confusing.  Would you be able to look at that point and offer some thoughts. Thank you.

**Comment by aaemnnosttv** [comment] 2023-07-27 03:36
Thanks @wpdarren and @jimmymadon – regarding the language here, it's implemented as designed. I also think it makes sense as-is but if we feel there is room for improvement this would be out of scope for this issue. Since this is not rolling out in this release, any iterations should happen in follow-up issues, unless of course something is broken 😄

**Comment by wpdarren** [comment] 2023-07-31 02:21
### QA Update: ✅ 

@jimmymadon Due to the amount of time left here - I am going to pass this for the design and that the tile is appearing, but for the result of `Email` as the most engaged traffic source, I do not believe that to be correct looking at my Analytics.   In the case of my site, I would have expected `Organic Video` to be the correct selection.  I will make a note to do some more testing around this and submit a ticket but will liaise with you before that.

**Closed** 2023-07-31 15:56 UTC
Labels: P0, Type: Enhancement, Exp: SP
