### ISSUE TITLE
Fix CTAs about linking Analytics with AdSense to show up

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1545] opened 2020-05-11 23:14 UTC
## Bug Description

There are two AdSense widgets that are sourced by the Analytics API (currently part of the Analytics module codebase, hooked into AdSense-specific UI via filters):

* full-width widget at the bottom of AdSense screen (below "Performance" widget, with similar heading)
* half-width widget at the bottom of Site Kit dashboard screen (on the right of the AdSense "Earnings" widget)

Both of these widgets display the most popular pages sorted by AdSense earnings. In order to get them to show up though, the user needs to link their Analytics and AdSense accounts. At least one of the two widgets has a CTA to inform the user about that, however due to a bug that CTA is not being displayed. The other widget doesn't provide it, but it should have one too.

The two widgets also have some error and zero data handling problems, partially because the error detection logic looks at error response formats that we generally don't use (maybe we did at some point way back?). The same applies to even the default error handler in the `withData` higher order component.

While looking into this issue, several more places for enhancements/fixes surfaced (too many blue boxes is obviously nothing new), but let's not get caught up in other UX issues too much at this point and focus on fixing the underlying problem.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* If the Analytics API returns the "Restricted metric(s): ..." error, the existing CTA should be displayed in both the above AdSense top pages tables: _You need to link Analytics and AdSense to get report for your top earning pages. Learn more: https://support.google.com/adsense/answer/6084409_
* If there is no data, the dashboard widget should show the regular CTA, while the AdSense module page widget should just not render at all.
    * While there will be already other similar blue CTAs in both screens in such a case, the difference is that in the dashboard it would look weird if we displayed nothing since the user would only see a half widget. Since we cannot modify outside UI at this point, it's okay to have double CTA there (like we have in some other cases too anyway). On the AdSense screen it's easy to just return null while keeping things looking fine because there the widget is full width.
* Ensure error format of having the error at the root of the response is supported by error handlers. Old error handling logic should be kept just in case, because we're not sure why it was added - all of this will get refactored away at some point anyway.

## Implementation Brief

* Modify `getDataError` in `AdSenseDashboardWidgetTopPagesTableSmall` (the dashboard one) to support the current error response format (by looking at existence of all `code`, `message`, and `data.status`) to ensure the CTA to link Analytics and AdSense is displayed.
* Modify `getDataError` in `AnalyticsAdSenseDashboardWidgetTopPagesTable` (the AdSense page one) to support the current error response format (see above) and add the same CTA from `AdSenseDashboardWidgetTopPagesTableSmall`, minus the grid wrap which is specific to the dashboard.
* Use the regular `isDataZeroForReporting` Analytics utility function in `AdSenseDashboardWidgetTopPagesTableSmall` to ensure the table is not rendered in an empty state and instead replaced with the regular blue zero data message.
* Keep the `isZeroData` function in `AnalyticsAdSenseDashboardWidgetTopPagesTable` forced to `false`, but add usage of `isDataZeroForReporting` in the component render function to return `null` in that case.
* Modify `withData` higher order component's default `getDataError` function to support the current error response format (see above).
* Remove irrelevant `adSenseLinked`-setting-based conditional from `getTopPagesReportDataDefaults` since this data is never displayed anywhere and could result in request errors that would otherwise not occur. It's unclear why this logic is there, but we decided to not include AdSense data in regular Analytics tables, so there is no need to request that here.
* Merge #1546.

## QA Brief

* 

## Changelog entry

* Fix bugs where CTAs to link Analytics to AdSense would never show.

**Comment by aaemnnosttv** [comment] 2020-05-13 13:08
IB ✅ 

> The two widgets also have some error and zero data handling problems, partially because the error detection logic looks at error response formats that we generally don't use (maybe we did at some point way back?). The same applies to even the default error handler in the withData higher order component.

The difference in error handling is legacy and should no longer be necessary. Previously, batch requests weren't consistent in the response returned for requests that resulted in exceptions/errors as we were relying on the WP REST API's response handling to convert `WP_Error`s into the proper format for a response. This didn't happen for batch requests because the response itself was not a `WP_Error` so the underlying Google exception was passed back in the response resulting in the odd structure we see checked for in some places. This was fixed in #986.

We can leave the legacy handling in place like you said, but it should never hit that anymore.

**Comment by felixarntz** [comment] 2020-05-13 17:15
Potential follow-up enhancement here: We could link directly to the area where users can link Analytics and AdSense: `https://analytics.google.com/analytics/web/?authuser={userEmail}#/a{analyticsAccountID}w{analyticsInternalWebPropertyID}p{analyticsProfileID}/admin/integrations/adsense/editor/new`

cc @marrrmarrr

**Comment by cole10up** [comment] 2020-05-22 06:44
**Tested**

Confirmed banner exists on dashboard after setting up latest develop with Adsense and Analytics:
![image](https://user-images.githubusercontent.com/57115907/82638639-2c714880-9bbc-11ea-8528-96c40f11c224.png)

Confirmed dashboard learn more link drives to:
![image](https://user-images.githubusercontent.com/57115907/82638966-a3a6dc80-9bbc-11ea-8d01-fef8aa8429f1.png)

Confirmed the banner on both Analytics and Adsense module pages:
![image](https://user-images.githubusercontent.com/57115907/82638676-3e52eb80-9bbc-11ea-904b-44b7786f8538.png)

Confirmed module learn more link drives to:
![image](https://user-images.githubusercontent.com/57115907/82639045-ce913080-9bbc-11ea-9ac3-5b3c0f0eb18d.png)


Checked mobile view:
![image](https://user-images.githubusercontent.com/57115907/82638854-75290180-9bbc-11ea-927b-c4f75e94d6a0.png)

Passed QA ✅

**Closed** 2020-06-01 04:14 UTC
Labels: P1, Type: Bug
