### ISSUE TITLE
User Input: Can't Delete Search Terms with Keyboard

### ISSUE THREAD

**Issue by ivankruchkoff** [google/site-kit-wp#2900] opened 2021-03-01 21:39 UTC
## Bug Description

When I fill out search terms, I can't then delete them with the backspace/delete key.

## Steps to reproduce

1. Go to user input flow
2. Get to 5/5 search terms
3. Fill out some search terms
4. Try and delete with backspace
5. See that search terms don't get deleted

## Additional Context

 - PHP Version: 
 - Plugin Version [e.g. 22]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* When pressing the backspace key within a search term (i.e. cursor is within the search term bubble), it should delete characters from that search term.
* When pressing the backspace key when right after a search term (i.e. the cursor is outside a search term bubble, right after one), it should delete that entire search term.

## Implementation Brief
* Once #2842 has been merged, using `/assets/js/components/user-input/UserInputKeywords.js`,
	* import `BACKSPACE` from `@wordpress/keycodes`.
	* create new function `deleteKeyword` which does the same thing as `onKeywordDelete`.
	* update `onKeywordDelete` to use the `deleteKeyword` function.
	* update the `onKeyDown` function to:
		* get the length of `nonEmptyValues`
		* if the length is less than `3` and the `BACKSPACE` key is pressed, call the `deleteKeyword` function passing `nonEmptyValuesLength - 1` as the index to delete.
		* set the focus to the input text again using the same logic when the `ENTER` or `COMMA` keys are pressed, but this time, having the following selector: `#${ slug }-keyword-${ nonEmptyValuesLength - 1 }`

### Test Coverage
N/A

### Visual Regression Changes
N/A

## QA Brief

* Fill out the user input flow until you reach step 5 (search terms)
* You should be able to:
  * Enter up to 3 words, pressing comma or enter/ return to enter a word
  * Delete within a word you are typing (i.e. hitting backspace while typing a word should delete the character you have just typed)
  * Delete a term after entering it (e.g. type `test`, hit comma to enter it, then `testing`, hitting comma again. Now hit the the backspace and `testing` should be removed, but not `test`).

## Changelog entry

* Fix accessibility problem where it wasn't possible to delete user input search terms using the keyboard.

**Comment by tofumatt** [comment] 2021-03-11 20:14
IB largely looks good but one thing I'm not clear on:

> if `nonEmptyValues.length` is than `3` and the `BACKSPACE` key is pressed, call the `deleteKeyword` function passing `nonEmptyValuesLength - 1` as the index to delete.

Why does it matter if there are fewer than the max number of keywords entered? Isn't the idea that if you can focus the text field and backspace in an empty bubble/outside a bubble that it deletes no matter what?

I'd think this check would instead be if `nonEmptyValues.length` is `0`—if that's the case we don't delete anything as there's nothing to delete.

**Comment by asvinb** [comment] 2021-03-15 12:37
@tofumatt As per the AC,
**When pressing the backspace key within a search term (i.e. cursor is within the search term bubble), it should delete characters from that search term.**
so if you are at the third item (max. number), if the backspace key is pressed, it should not delete the item, rather it should delete characters from that item.

**Comment by johnPhillips** [comment] 2021-03-15 15:08
Just realised this IB isn't finished, sorry! I'll pause work until it is passed review. My mistake 🙏

**Comment by tofumatt** [comment] 2021-03-15 20:21
@asvinb Ah, okay, thanks! Makes sense now. 👍🏻 

IB ✅

**Comment by wpdarren** [comment] 2021-04-07 11:38
### QA Update: Fail ❌ 

@johnPhillips when I hit backspace within a word, it will allow me to delete one letter but the cursor then jumps to the end of the word.  This is an issue if I am wanting to delete more than one letter within the word. When I hit the backspace once, I should then be able to hit the key again to delete the next letter. 

Here's a quick screencast

https://user-images.githubusercontent.com/73545194/113860473-ac0a0500-97d8-11eb-98fb-661ef1070e25.mp4


**Verified:**

Delete a term after entering it, is removed.  (e.g. type test, hit comma to enter it, then testing, hitting comma again. Now hit the the backspace and testing is  removed, but not test).

**Comment by tofumatt** [comment] 2021-04-07 17:55
@johnPhillips and I chatted about this and turns out this was an issue even before this fix landed—the way we store the data for these elements in state and then select them causes a known bug with input cursor jumping with controlled components. I found a fix for this and will have a PR soon… it's arguably almost a separate issue but I'll fix it as part of the QA here. 🙂

**Comment by wpdarren** [comment] 2021-04-12 12:31
### QA Update:  Pass ✅ 

- When you enter up to 3 words, you can delete within a word you are typing.
- You can delete a term after entering it.
- Also confirmed that these two tests in the QAB on mobile and tablet devices.


https://user-images.githubusercontent.com/73545194/114394439-c7588400-9bcd-11eb-8f6c-659ba1558671.mov

**Closed** 2021-04-26 18:52 UTC
Labels: Good First Issue, P1, Rollover, Type: Enhancement
