### ISSUE TITLE
Fix outdated files being loaded

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#1066] opened 2020-01-21 09:18 UTC
## Bug Description

In the past few days, several fatal errors were reported in the plugin repository:
* https://wordpress.org/support/topic/fatal-error-1-2-0/
* https://wordpress.org/support/topic/fatal-error-due-to-sitekit-update-attempt/
* https://wordpress.org/support/topic/triggered-a-fatal-error-10/

Each of them points to code locations that are not actually relevant for version 1.2.0, so I'm not quite sure what was causing it, whether it was just a partially failed download - which I cannot imagine, especially given that this was just now reported 3 times in a short period.

@swissspidy mentioned that there can be potential issues on upgrade as a result of using `file_exists()` checks (see https://github.com/ampproject/amp-wp/issues/2670). We're using the function twice in our plugin code (in `loader.php`), and we should be able to eliminate the need for them. Given the error messages from the three support tickets, I don't think this is the actual problem here, but it's still something worth improving.

A more likely cause could be that OpCache is not properly reset and does not detect the updated files, so that it partially loads old files (see WP core ticket https://core.trac.wordpress.org/ticket/36455).

Let's explore this a bit further and according fixes.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be no `file_exists()` checks in `loader.php`:
    * The one in `autoload_classes()` should simply be removed because that classmap should only include classes for files that exist.
    * In order to remove the one in `autoload_vendor_files()`, we need to fix how we generate the `third-party/vendor/autoload_files.php` file. At the moment, it is simply copied from the main Composer output (done in `composer.json`), which results in it including also dependencies that are only relevant for development. Let's implement it in a way that only the three files relevant for production are included.
* `opcache_reset()` should be called (if available) after Site Kit has been updated (see https://core.trac.wordpress.org/attachment/ticket/36455/36455.5.diff for possible approach).

## Implementation Brief

* Remove `file_exists()` condition in `\Google\Site_Kit\autoload_classes()`
* Remove `file_exists()` condition in `\Google\Site_Kit\autoload_vendor_files()`
* Add `@composer dump-autoload --no-dev` as a step between `@autoload-third-party` and copying `autoload_files.php` in the `prefix-dependencies` Composer script
    - This results in the `autoload_files.php` containing an array of only the 3 files needed
    - We don't load the main `vendor/autoload.php` so this shouldn't affect anything else
* Add a new `googlesitekit_opcache_reset` function in the plugin's entrypoint file
    - Wrapper for [`opcache_reset()`](https://www.php.net/manual/en/function.opcache-reset.php) with [additional checks to see if it is safely callable](https://core.trac.wordpress.org/attachment/ticket/36455/36455.5.diff)
    - Added in PHP 5.5, there is need to check if the function exists now that min PHP is 5.6.
    - Hook this on the core `upgrader_process_complete` action

## Changelog entry

* Fix partly outdated PHP files being served due to OpCache issues [currently not addressed by WordPress core](https://core.trac.wordpress.org/ticket/36455).

**Comment by swissspidy** [comment] 2020-01-21 09:44
Looking at those reports it indeed sounds more like an OpCache issue.

Totally forgot about https://core.trac.wordpress.org/ticket/36455. Dang that ticket is old! My comment there is from 2016 😮 👴

**Comment by aaemnnosttv** [comment] 2020-01-21 16:40
Regarding OpCache, I don't think this is an issue we can really fix on the Site Kit side. If the server is loading stale PHP, then nothing we write will matter because it won't be evaluated until the opcache is flushed or file caches are invalidated. That is, if we were to add a call to `opcache_reset`, it wouldn't prevent another fatal on the next release because that new code still wouldn't be loaded yet. It would take one release before it would take effect for the next. It seems like this is an infrastructural configuration issue. Also, if this were the culprit, the site would likely have problems with many other plugins as well. It's hard to imagine that this would only affect Site Kit somehow.

**Comment by felixarntz** [comment] 2020-01-22 09:56
@aaemnnosttv It is surely more of a core issue than a Site Kit issue, and I'm sure it does by far not only affect Site Kit. But it's still something we need to consider addressing. For at least [this ticket](https://wordpress.org/support/topic/triggered-a-fatal-error-10/), it was in fact the problem.

I see what you're saying regarding outdated files still being an issue, but if we for example added this into the main file with a hook that runs when updating Site Kit, it would at least run on subsequent updates.

**Comment by felixarntz** [comment] 2020-01-22 13:14
@aaemnnosttv 
> Update `release-zip` npm script to run `composer install --no-dev` as first step

What about during development though? Wouldn't `autoload_files.php` still include the other files in that case, which are on actually in the `third-party` directory though?

**Comment by aaemnnosttv** [comment] 2020-01-22 15:03
You're right @felixarntz, I've updated the IB with a better option.

**Comment by felixarntz** [comment] 2020-01-22 17:06
IB ✅

**Comment by cole10up** [comment] 2020-01-28 07:45
**Tested**
![Add Plugins ‹ Sound Royal — WordPress](https://user-images.githubusercontent.com/57115907/73244519-fb798d80-415e-11ea-932e-6ffcecad3134.gif)

Loaded up a 1.1.4 instance of SK with services, upgraded to 1.2.0. Was unable to reproduce. No issues discovered. Will reopen after pushing this fix if the issues persists. Moving to approval.

**Closed** 2020-02-14 00:14 UTC
Labels: P0, Type: Bug
