### ISSUE TITLE
When a site has no goals set up in Analytics, currently the 'Goals' data shows zero within Overview for the last 28 days widget

### ISSUE THREAD

**Issue by eclarke1** [google/site-kit-wp#4489] opened 2021-12-08 10:44 UTC
## Bug Description

As per bug bash ticket: https://app.asana.com/0/1201438453642602/1201439607546521

When a site has no goals set up in Analytics, currently the 'Goals' data shows zero within Overview for the last 28 days widget, where on the current dashboard there is a CTA. 

The new Search Funnel widget is completely missing the logic to check whether any goals are defined - it needs to be taken over from the DashboardGoalsWidget that we have today in place of that.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The `SearchFunnelWidget` widget displays the similar Goals CTA as in the `DashboardGoalsWidget` component when no goals have been created for the current property yet.

## Implementation Brief

Within `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js`:
* Following the existing pattern in the file, create three new variables with the results from `useSelect` calls:
  * `analyticsGoalsData` - should hold the result of `select( MODULES_ANALYTICS ).getGoals()`.
  * `analyticsGoalsLoading` - result of `! hasFinishedResolution` for `getGoals`, or `false` if analytics is not connected.
  * `analyticsGoalsError` - result of `getErrorForSelector` for `getGoals`, or `null` if analytics is not connected.
* Add a check for `analyticsGoalsLoading` to this block:
https://github.com/google/site-kit-wp/blob/e6b6890a69213a970cec7c1ca1837e72df9f1150/assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js#L268-L272
* Add a check for `analyticsGoalsError` to this block:
https://github.com/google/site-kit-wp/blob/e6b6890a69213a970cec7c1ca1837e72df9f1150/assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js#L311-L314
* Pass `analyticsGoalsData` as a prop to the `Overview` widget.

Within `assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Overview.js`:
* Retrieve `analyticsGoalsData` from props and add it to `PropTypes`.
* Locate the Goals `DataBlock` within the file:
https://github.com/google/site-kit-wp/blob/e6b6890a69213a970cec7c1ca1837e72df9f1150/assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/Overview.js#L242-L246
* Amend the rendering of the Goals `DataBlock` to conditionally render either the `DataBlock` or a `CTA` based on a check on `analyticsGoalsData.items.length`, taking the relevant code in `assets/js/modules/analytics/components/dashboard/DashboardGoalsWidget.js` as a reference (the `CTA` can be duplicated from here):
https://github.com/google/site-kit-wp/blob/e6b6890a69213a970cec7c1ca1837e72df9f1150/assets/js/modules/analytics/components/dashboard/DashboardGoalsWidget.js#L143-L159

### Test Coverage

* Fix any failing tests.

## QA Brief

- Go to the Site Kit dashboard
- Make sure the site has Analytics set up
- Make sure the Analytics goals are not set up
- Verify the `Goals` section in the `SearchFunnelWidget` has a CTA instead of displaying `0`
- Verify the CTA text is correct
- Verify the `CREATE A NEW GOAL` link in the CTA navigates to the create or edit analytics goals page

## Changelog entry

* Update the Overview widget to display Goals CTA when no goals are set yet.

**Comment by tofumatt** [comment] 2021-12-14 17:17
IB ✅

**Comment by wpdarren** [comment] 2021-12-17 15:23
### QA Update: ❌ 

@hussain-t  I'm not seeing the CTA. The site I am using is `oi.ie` and looking at the Google Analytics account, no active goals exist. The goals data is still showing zero.  I've created a new site, used the developer plugin to connect to `oi.ie` and connected Analytics. I also checked that this wasn't a caching issue.  I tested this on current and unified dashboard.

It is possible that goals might have been set up in the past and then trashed, could that be the cause? 

<details>
 <summary>Dashboard</summary>

![image](https://user-images.githubusercontent.com/73545194/146566532-eece1f23-3994-4146-8478-18949f1da7f8.png)

</details>

<details>
 <summary>Goals in Analytics</summary>

![image](https://user-images.githubusercontent.com/73545194/146566774-1607582e-cc9c-49e3-8206-c09a6a948d9c.png)

</details>

**Comment by eugene-manuilov** [comment] 2021-12-17 15:26
@wpdarren there are two goals in the `oi.ie` account: 
![image](https://user-images.githubusercontent.com/873049/146567635-09866802-e1a7-4618-9503-619b5ac0f1b2.png)

You probably need to test it on a new site with a new account. :thinking:

**Comment by wpdarren** [comment] 2021-12-17 16:53
@eugene-manuilov oh, um, I thought with it saying 'all goals' = 0 that none were active. Good shout, I'll look at it again.

**Comment by wpdarren** [comment] 2022-01-06 10:00
### QA Update: ⚠️ 

@hussain-t @eugene-manuilov okay, I've been having fun with this ticket 😄  I've tried it on two sites, and see the same behaviour.  When Unified Dashboard is connected, and Google Analytics account/property does not have any goals. There's a message `Analytics data is not yet available, please check back later` for the Goals data, even the Analytics data is appearing on other widgets, i.e. All Traffic.  Any idea why this would be? I've left it a few days and the message doesn't update.

![image](https://user-images.githubusercontent.com/73545194/148365186-6245aa7e-2c20-469a-a233-a12d782700c2.png)

**Comment by hussain-t** [comment] 2022-01-12 04:13
@wpdarren my changes in #4571 fix this issue. You can verify it by switching to `bug/4571-hide-search-funnel-blue-cta` branch or once it gets merged.

<img width="1138" alt="Screenshot 2022-01-12 at 9 41 36 AM" src="https://user-images.githubusercontent.com/24408261/149062654-d6681ae6-6303-430c-8f81-e35c522f7299.png">

**Comment by wpdarren** [comment] 2022-01-12 12:04
### QA Update: ✅ 

**Verified:**

- The Goals section in the SearchFunnelWidget has a CTA instead of displaying 0 when Unified Dashboard is enabled.
- The CTA text is correct and the CREATE A NEW GOAL link in the CTA navigates to the create analytics goals page.

<img width="1523" alt="cta" src="https://user-images.githubusercontent.com/73545194/149137051-a7a93063-e2f2-4fab-97d4-1232c2d66ff2.png">

**Closed** 2022-01-14 11:30 UTC
Labels: Type: Bug, P0, Rollover
