### ISSUE TITLE
Odd Behaviour on Unified Dashboard URL Search with Results

### ISSUE THREAD

**Issue by wpdarren** [google/site-kit-wp#4402] opened 2021-11-24 14:31 UTC
## Bug Description

While testing #4336 I noticed odd behaviour on the URL search that I didn't observe previously. 

1.  I typed a few letters and the search result appeared, but then changed to another page within a second or two. This is without typing any other letters. 

2. I typed the word `cat` and a result appeared for 'Sample page' the only letter in the search term is `a`  so I am wondering if this should have appeared?  I have few pages on the test site, but I'd have expected it to say 'No results found' to be honest. 

https://user-images.githubusercontent.com/73545194/143257367-2d168490-3e58-46bf-a5b1-816ea83af308.mp4

New related issue:

3.  While playing around with my live site tonight, I noticed more unusual behaviour of the URL search when you actually type in a URL. I type it in, and the correct result appears for a second but changes a few times and then displays 'No results found' but then 10 seconds later the correct result appears again, and stays there. 

This is the behaviour in the screencast. 

https://user-images.githubusercontent.com/73545194/143950832-e126cdd3-bf5e-407e-b610-0701a565ab9c.mov

This is what the result should be. 
![image](https://user-images.githubusercontent.com/73545194/143950927-a390002f-c1b4-4d09-ba6c-5fc742a48abb.png)

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A search results response from a request that came from a previous search input that is no longer current (e.g. typing `ca` sends a request, then `cat` sends another request) should be discarded. Either previous requests should be cancelled right away when the input changes, or any response should be discarded if there is a newer request that's still going on at the time.

### Cancel previous search requests:

As per the documention, [`apiFetch`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-api-fetch/#aborting-a-request) calls can be aborted via a [`signal`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/signal) from an [`AbortController`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController).

Within `assets/js/googlesitekit/api/index.js`:
* Update the `siteKitRequest` function to accept an optional `signal` property, of type [`AbortSignal`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal).
  * Pass this `signal` property to the `apiFetch` call.
* Similarly, update the `get` function to accept an optional `signal` property and pass it to `siteKitRequest`.

Within `assets/js/components/PostSearcherAutoSuggest.js`:
* In the `useEffect` that makes the API call, create an instance of `AbortController` and pass its `signal` property to `API.get`.
* Add a cleanup handler to `useEffect` that calls the [`abort`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort) method of the returned `AbortController` instance.
* The code should defensively handle the case where the `AbortController` API does not exist.

### Test Coverage

* Add JS test coverage for the changes made to `get`. These should be integrated tests, thus also validating the changes made to `siteKitRequest`.

## QA Brief

- Open the browser developer tool
- Navigate to the `Network` tab and clear if there are any previous requests
- Type any search term in the Entity Search input. For example, type `cat`, notice the previous request for `ca` should have been cancelled
- Verify it doesn't show any irrelevant search results

## Changelog entry

* Update the URL search to abort the current search request when the user changes the query.

**Comment by felixarntz** [comment] 2021-11-29 22:16
@wpdarren This may also be caused by the second point in the ACs. Let's revisit this in QA to see whether all of these problems will be covered from this issue.

**Comment by eugene-manuilov** [comment] 2021-12-06 12:27
> Create a new function called `getAbortable`, using the existing `get` function as a guide.
> * This function should create an instance of `AbortController` and pass its `signal` property to `siteKitRequest`.
> * `getAbortable` should not return `async`. Rather, it should return both the response of `siteKitRequest` and the `AbortController` instance.
> * Add `getAbortable` to the default export `API` object.

@techanvil this seems to be over-engineered, let's just add the ability to pass the `signal` property to the existing `API.get` method and not introduce the new `getAbortable` method.

> The search input for the URL search field should only show results which include the word (or full partial word) typed into the search input. For example, typing cat should show results that contain words like cat or categories or truncate, but not results that contain just a, ca, or at.

@felixarntz, the existing search functionality works correctly and it returns the correct results. It showed the `Sample Page` page in the result because that page contained the word "Lo**cat**ed" in the content. So, no changes are required in the search functionality, right? If we restrict it to search only by post titles, it will make the search less useful because titles usually contain little information.

**Comment by techanvil** [comment] 2021-12-06 15:58
> > Create a new function called `getAbortable`, using the existing `get` function as a guide.
> > 
> > * This function should create an instance of `AbortController` and pass its `signal` property to `siteKitRequest`.
> > * `getAbortable` should not return `async`. Rather, it should return both the response of `siteKitRequest` and the `AbortController` instance.
> > * Add `getAbortable` to the default export `API` object.
> 
> @techanvil this seems to be over-engineered, let's just add the ability to pass the `signal` property to the existing `API.get` method and not introduce the new `getAbortable` method.

Hi @eugene-manuilov, the reason I suggested a new function is so we can expose the `controller` to the caller, in order for the caller to be able to call `controller.abort()`.

At present we have `get` which is an async function and returns the result of `apiFetch` directly:

```js
export const get = async (
	type,
	identifier,
	datapoint,
	data,
	{ cacheTTL = 3600, useCache = undefined } = {}
) => {
	return siteKitRequest( type, identifier, datapoint, {
		cacheTTL,
		queryParams: data,
		useCache,
	} );
};
```

The proposed `getAbortable` would look something like this (note, not async):

```js
export const getAbortable = (
	type,
	identifier,
	datapoint,
	data,
	{ cacheTTL = 3600, useCache = undefined } = {}
) => {
	const controller =
		typeof AbortController === 'undefined'
			? undefined
			: new AbortController();

	return {
		response: siteKitRequest( type, identifier, datapoint, {
			cacheTTL,
			queryParams: data,
			useCache,
		} ),
		controller,
	};
};

// Then somewhere in caller territory:
controller?.abort()
```

Without the new function I don't see a nice way of returning the controller... Have you considered this aspect?

**Comment by eugene-manuilov** [comment] 2021-12-06 16:26
@techanvil, yes, I understand what you described in IB. IMO the problem with the `getAbortable` function is that it doesn't return a promise, thus it can't be considered as a drop-in replacement for the `API.get` method. So, I think it would be better and easier to understand/maintain for now if we just extend the existing `API.get` method to allow passing a `signal` property and instantiate an abort controller in a component.

What I suggest to do is the following:
```diff
 export const get = async (
 	type,
 	identifier,
 	datapoint,
 	data,
-	{ cacheTTL = 3600, useCache = undefined } = {}
+	{ cacheTTL = 3600, useCache = undefined, signal } = {}
 ) => {
 	return siteKitRequest( type, identifier, datapoint, {
 		cacheTTL,
 		queryParams: data,
 		useCache,
+ 		signal,
 	} );
 };
```

```diff
 	useEffect( () => {
 		if ( debouncedValue !== '' ) {
 			setIsLoading?.( true );
+			const controller = typeof AbortController === 'undefined' ? undefined : new AbortController();
 			API.get(
 				'core',
 				'search',
 				'post-search',
 				{ query: encodeURIComponent( debouncedValue ) },
-				{ useCache: false }
+				{ useCache: false, signal: controller?.signal }
 			)
 				.then( ( res ) => setResults( res ) )
 				.catch( () => setResults( [] ) )
 				.finally( () => setIsLoading?.( false ) );
+			return () => controller?.abort();
 		}
 	}, [ debouncedValue, setIsLoading ] );
```
In this case, we still use the same `API.get` method and can abort it at any time without a need to rework the logic of the `API.get` method call.

**Comment by techanvil** [comment] 2021-12-06 16:30
> @techanvil, yes, I understand what you described in IB. IMO the problem with the `getAbortable` function is that it doesn't return a promise, thus it can't be considered as a drop-in replacement for the `API.get` method. So, I think it would be better and easier to understand/maintain for now if we just extend the existing `API.get` method to allow passing a `signal` property and instantiate an abort controller in a component.
> 
> What I suggest to do is the following:
> 
> ```diff
>  export const get = async (
>  	type,
>  	identifier,
>  	datapoint,
>  	data,
> -	{ cacheTTL = 3600, useCache = undefined } = {}
> +	{ cacheTTL = 3600, useCache = undefined, signal } = {}
>  ) => {
>  	return siteKitRequest( type, identifier, datapoint, {
>  		cacheTTL,
>  		queryParams: data,
>  		useCache,
> + 		signal,
>  	} );
>  };
> ```
> 
> ```diff
>  	useEffect( () => {
>  		if ( debouncedValue !== '' ) {
>  			setIsLoading?.( true );
> +			const controller = typeof AbortController === 'undefined' ? undefined : new AbortController();
>  			API.get(
>  				'core',
>  				'search',
>  				'post-search',
>  				{ query: encodeURIComponent( debouncedValue ) },
> -				{ useCache: false }
> +				{ useCache: false, signal: controller?.signal }
>  			)
>  				.then( ( res ) => setResults( res ) )
>  				.catch( () => setResults( [] ) )
>  				.finally( () => setIsLoading?.( false ) );
> +			return () => controller?.abort();
>  		}
>  	}, [ debouncedValue, setIsLoading ] );
> ```
> 
> In this case, we still use the same `API.get` method and can abort it at any time without a need to rework the logic of the `API.get` method call.

@eugene-manuilov apologies for misunderstanding you the first time around. That seems like a good approach, I'll update the IB accordingly. :+1:

**Comment by techanvil** [comment] 2021-12-06 16:37
@eugene-manuilov, I've updated the IB. I'll assign this to @felixarntz so he can address the question in https://github.com/google/site-kit-wp/issues/4402#issuecomment-986730845

**Comment by felixarntz** [comment] 2021-12-06 18:04
@eugene-manuilov 

> the existing search functionality works correctly and it returns the correct results. It showed the `Sample Page` page in the result because that page contained the word "Lo**cat**ed" in the content. So, no changes are required in the search functionality, right? If we restrict it to search only by post titles, it will make the search less useful because titles usually contain little information.

Ah good catch - apologies for that point in the ACs then, it indeed shouldn't be necessary. I just removed it. So that part of the IB can also be discarded, which should keep the changes simpler as well. cc @techanvil

**Comment by techanvil** [comment] 2021-12-07 09:50
Thanks @felixarntz - I've updated the IB. Assigning back to @eugene-manuilov to complete the IBR.

**Comment by eugene-manuilov** [comment] 2021-12-07 10:51
IB ✔️

**Comment by wpdarren** [comment] 2021-12-09 14:59
### QA Update: ❌ 

@hussain-t @eugene-manuilov an observation. 

I still see an issue on point 1 in the description of the ticket. 

> I typed a few letters and the search result appeared, but then changed to another page within a second or two. This is without typing any other letters.

I am assuming this isn't expected?  

https://user-images.githubusercontent.com/73545194/145419701-80ee8c16-4623-4b63-96ce-d874c209be5f.mp4

Relating to the network tab in the QAB:

I can see the first entry is cancelled but when I enter the 3rd character, the 2nd character isn't. The results do change though as expected. 

Point 3. has been fixed. When I enter a URL the correct search result appears and does not change.

**Comment by hussain-t** [comment] 2021-12-09 15:33
Thanks for testing @wpdarren 
Re: Point 2 - If you notice the network tab the request was already made and received the response before you type the third character.

**Comment by hussain-t** [comment] 2021-12-09 15:45
@wpdarren @eugene-manuilov I think it showed `No results found` when you typed the second character because the first request was cancelled. Then the second call was made. But the loading indicator didn’t appear this time.

**Comment by wpdarren** [comment] 2021-12-10 12:23
### QA Update: ⚠️ 

@hussain-t @eugene-manuilov @felixarntz  I am sorry to be a pain 😄 but I am not 100% sure the search is fixed for point 1 in my original ticket description.  Taking away what is coming up in the network tab, when I type `cat` the 'no results found' appears pretty much straightaway and then around 2 seconds later search results appear.  Looking at my screencast, is this expected behaviour? 

https://user-images.githubusercontent.com/73545194/145572657-f05cadf8-a8a1-4ac8-8bd1-2b7daab5e9df.mp4

Let me actually give you a better real search.  I search for `remote` and this was typed very fast. I suspect the 'no results found' is appearing because it didn't find anything on my first or second key presses. If you feel this is expected then that's fine. 

https://user-images.githubusercontent.com/73545194/145573300-f276b2be-1464-45c1-80bd-9b947e73f665.mp4

**Comment by eugene-manuilov** [comment] 2021-12-10 15:49
@wpdarren the `No results` result that you see will be hidden on the Unified Dashboard pages once #4503 is implemented. The URL search on the unified dashboard pages wasn't supposed to display `No results` at all, but looks like after some changes it has been added by mistake.

In other words, what you see is incorrect, but it will be fixed in a separate issue. This issue is intended to cancel the current search request when the user keeps typing.

**Comment by wpdarren** [comment] 2021-12-10 16:09
### QA Update: ✅ 

**Verified:**

- When you type a search term in the Entity Search input. For example, type `cat,` the previous request for `ca` has been cancelled.  The search doesn't show any irrelevant search results.

![image](https://user-images.githubusercontent.com/73545194/145605024-91eb2793-67b3-44a6-9d13-836a83cf43af.png)

**Comment by eugene-manuilov** [comment] 2021-12-14 09:56
@wpdarren looks like I was wrong regarding the `No results` message in the new unified dashboard. See Matthew's comment: https://github.com/google/site-kit-wp/issues/4503#issuecomment-992984110

If you still think that the URL search functions incorrectly, then could you please create a new ticket for it?

**Comment by wpdarren** [comment] 2021-12-14 12:30
@eugene-manuilov yes, will do. I'll have another look at it today and create ticket.

**Closed** 2021-12-16 16:48 UTC
Labels: Type: Bug, P0, Good First Issue

**Comment by mitogh** [comment] 2021-12-17 23:47
While testing this ticket I found an unexpected behavior that I don't think relates to this ticket but wanted to flag it.

- #4584

cc @wpdarren
