### ISSUE TITLE
Dashboard scroll on load can sometimes be inaccurate

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4879] opened 2022-02-23 09:26 UTC
## Bug Description

When the unified dashboard is loaded, it performs a scroll-to section for the current area identified by the hash in the URL. This can sometimes miss the target due to changes in the dashboard that can happen simply due to the various logic in place for whether a widget should be shown or not that can still be "resolving" while the scroll is in progress. This can have the effect of the scroll destination being different on arrival from where it was intended to be when initiated.

E.g.

![](https://user-images.githubusercontent.com/90871/154925651-10d9b877-68ed-4e89-9e63-c4d1aea7ffe9.gif)

Part of the solution here could involve:
* Changing the scroll behavior on mount to be instant (rather than smooth)
* Finding a way to delay the scroll on mount until all widgets are known to be shown or not
* Ensuring more consistency between loaded and loading states (see #4878)

## Steps to reproduce

The easiest way to reproduce this is with Idea Hub enabled but inactive.

* Try refreshing the dashboard in different positions

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Scroll-to behavior on load should work consistently across dashboard configurations for both direct navigation and page reloads

## Implementation Brief

* 

### Test Coverage

* 

## QA Brief

* 

## Changelog entry

*

**Comment by aaemnnosttv** [comment] 2022-02-23 09:38
@felixarntz I think this one may depend on #4878 but I'm not sure. Any other thoughts on the ACs?

**Comment by techanvil** [comment] 2022-10-18 09:57
@aaemnnosttv I am unable to reproduce this one, looks like it's been fixed...

**Comment by techanvil** [comment] 2022-10-19 08:32
Closing as not reproducible.

**Closed by techanvil** 2022-10-19 08:32 UTC
Labels: Type: Bug, P1
