### ISSUE TITLE
Fix AdSense V2 main logic

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#5106] opened 2022-04-19 01:09 UTC
## Bug Description

Follow-up to #4758 and #4759: After a closer inspection of the V2 `SetupMain` component, I found that several requirements from the ACs of that issue were not quite correctly implemented in that issue. Most importantly, the `determineAccountStatus`, `determineSiteStatus` and any of the other `determine*` utility function must no longer be used as part of the V2 flow at all. Account status and site status should be determined and set by the new components, and the `SetupMain` component needs to look at the `accountStatus` and `siteStatus` _settings_, not the determined value using the old function.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

In the AdSense V2 `SetupMain` component:
* The component must no longer use `determineAccountStatus` and `determineSiteStatus`. Instead, it needs to look at the `accountStatus` and `siteStatus` settings from the AdSense module.
* The component must no longer use `determineAccountID`. Instead, custom logic in the `useEffect` hook should set the `accountID` setting, based on the logic defined in the ACs for #4758.
* The component must no longer use `determineClientID`. That handling should be entirely removed, the component should only look at the `clientID` setting. The setting should be set through another component (`SetupAccount`, to be specific).
* The usage of `getURLChannels` should be entirely removed, as that endpoint is no longer relevant as part of the V2 setup flow. The call to `resetURLChannels` should also be removed for the same reason.

In the AdSense V2 `SetupAccount` component:
* The component must no longer use `determineClientID`. Instead, custom logic in the `useEffect` hook should set the `clientID` setting, based on the logic defined in the ACs for #4759.
* There needs to be an additional `useEffect` hook that sets `siteStatus` to `SITE_STATUS_NONE` _if_ the current site (`site`) is `null` (**not `undefined`**). This was also originally defined in the ACs #4759, but missing from the implementation. Note that no other site status should be set here since the other possible site statuses are all being set via the separate `SetupAccountSite` component.

All Storybook coverage for the V2 AdSense setup flow should be reviewed to double-check that it shows the correct UI (still temporary placeholders describing the intended state) even with the fixed logic here. Due to the fixes, it is very likely that some of the dummy data for the stories will need adjusting.

### `SetupMain` component

Within file `assets/js/modules/adsense/components/setup/v2/SetupMain.js`:

- Replace the call to `determineAccountStatus` with a call to the `MODULES_ADSENSE` store's `getAccountStatus` selector. via `useSelect`.
- Similarly, replace the call to `determineSiteStatus` with a call to the `getSiteStatus` selector, and the call to `determineClientID` with a call to the `getClientID` selector.
- Rename the existing `previousAccountID` variable which is retrieved via `getAccountID` to `accountID`. Remove the call to `determineAccountID`.
- Within the [`useEffect` block](https://github.com/google/site-kit-wp/blob/64e9b6c7f7576d33b23f7105a1e4311c0fa40b4a/assets/js/modules/adsense/components/setup/v2/SetupMain.js#L181) that invokes `setAccountID`:
  - Remove the first condition and its early return, this will no longer be needed.
  - Modify the remaining condition to check that there is one account in `accounts`, and either `accountID` is not set, or the `_id` property of the single account in `accounts` (i.e. `accounts[0]._id`) does not match `accountID`.
  - Replace the call to `setAccountID( accountID )` with `setAccountID( accounts[0]._id )`.
- Remove the call to `resetURLChannels`.
- Remove all unused variables and related code.

### `SetupAccount` component

Within file `assets/js/modules/adsense/components/setup/v2/SetupAccount.js`:

- Remove the call to `determineClientID`, and replace usage of `acfClientID` with `clientID`.
- Within the [`useEffect` block](https://github.com/google/site-kit-wp/blob/64e9b6c7f7576d33b23f7105a1e4311c0fa40b4a/assets/js/modules/adsense/components/setup/v2/SetupAccount.js#L73) that invokes `setClientID`:
  - Modify the condition to check that there is one AFC in `clients`, and either `clientID` is not set, or the `_id` property of the single AFC client in `clients` does not match `clientID`.
    - A client is an AFC client if its `productCode` property is `'AFC`'. See [here](https://github.com/google/site-kit-wp/blob/64e9b6c7f7576d33b23f7105a1e4311c0fa40b4a/assets/js/modules/adsense/util/status.js#L218-L221) for an example.
  - Replace the `clientID` argument to `setClientID( clientID )` with the `_id` property of the single AFC client in `clients`.
- Add a `useEffect` with a callback that dispatches `setSiteStatus( SITE_STATUS_NONE )` when `site === null`.

### Storybook

- As per the last point of the AC, ensure the related Storybook stories still display correctly.

### Test Coverage

* No new tests needed.

## QA Brief

- Ensure the Adsense Setup V2 stories still display correctly as mentioned in the AC.

## Changelog entry

* N/A

**Comment by tofumatt** [comment] 2022-04-21 13:08
IB ✅

**Comment by felixarntz** [comment] 2022-04-26 20:07
@hussain-t Based on the change added as part of #5052, there is now a `getAFCClient` selector, which should probably be used here. Basically, it simplifies your IB because that way you can use the new selector instead of manually looking for the AFC client within `clients`. Please make sure to consider that for the implementation.

**Comment by hussain-t** [comment] 2022-04-27 06:54
Thanks for the heads up, @felixarntz 👍

**Comment by wpdarren** [comment] 2022-04-27 13:21
### QA Update: ⚠️ 

> QAB: Ensure the Adsense Setup V2 stories still display correctly as mentioned in the AC.

@hussain-t We need more guidance to QA this ticket.  I can go to the [v2 stories](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-adsense-components-setup-v2-setupmain--setup-account-site) but the checks in the AC seem quite technical. When I go through the stories, they all say `TODO:`  I can use the React developer tools to check components, but most of the changes in the AC are related to hooks, etc. 

Do you feel this is a `QA:Eng`, or can we have more detailed instructions.

**Comment by felixarntz** [comment] 2022-04-27 14:53
@hussain-t @wpdarren I agree that the QA Brief could be more extensive. Yesterday the 1.8.0 version of the tester plugin was published which allows mocking all the API responses to enforce the new AdSense account and site statuses, so we can now test this in a better way than before.

A good QA Brief could be to set all the new account statuses (except the ones marked "legacy", which are for the V1 AdSense setup) one after the other via the tester plugin, go to the AdSense setup flow each time to check whether the right "temporary UI message" is shown, and then also go to Site Kit's Site Health info section to check that in fact that expected account status was also detected by Site Kit. All of that with the `adsenseSetupV2` flag enabled of course.

**Comment by wpdarren** [comment] 2022-04-27 14:58
@felixarntz Thanks for updating the plugin and for the QAB!  👍

**Comment by wpdarren** [comment] 2022-04-27 16:06
### QA Update: ❌ 

@hussain-t @felixarntz I am seeing a few issues:

When `Force AdSense account status` is set to `None` on the tester plugin, and I start the setup flow, the progress bar animation continues with no message shown.  I do see an error appears in the console.  `API Error method:GET datapoint:accounts type:modules identifier:adsense error:"User does not have an AdSense account."`

Also, the AdSense logo does not appear underneath the Connect Service text. 

![image](https://user-images.githubusercontent.com/73545194/165557099-e1fee422-27d1-43bf-9f26-602f5b3188fd.png)

I am assuming that these issues are not expected? 

There also seems to be an issue with all the other statuses after `multiple` on the tester plugin.

E.g. when `Force AdSense account status is set to `Needs Attention` and I start the setup flow, I receive the `multiple` message but with just one account.  

![image](https://user-images.githubusercontent.com/73545194/165562313-92f5a483-a9c1-4e93-8599-e95e087b5930.png)

I was expecting to see the needs attention message for this scenario. 

**Verified:**

When `Force AdSense account status` is set to `Multiple` on the tester plugin, and I start the setup flow, the messsage appears askingg mee to select an account. Two accounts appear in the dropdown. When I go to Site Health I can see that the  `AdSense account status` is set to `multiple` which is expected.

**Comment by techanvil** [comment] 2022-04-27 18:04
Hi @wpdarren, I spotted that a mistake slipped through the net, I think it's the cause of the unexpected "Select your AdSense account" that you are seeing. I've raised a followup PR to fix it, and will move this issue back to Code Review, so when it's back in QA it will be ready to retest and hopefully that scenario will work (assuming a valid Tester plugin response too).

**Comment by wpdarren** [comment] 2022-04-28 10:23
### QA Update: ❌ 

@hussain-t @felixarntz I am still have a few issues:

1. When `Force AdSense account status` is set to `None` on the tester plugin, and I start the setup flow, the progress bar animation continues with no message shown.  I do see an error appears in the console.  `API Error method:GET datapoint:accounts type:modules identifier:adsense error:"User does not have an AdSense account."`

2. The AdSense logo does not appear underneath the Connect Service text. 

![image](https://user-images.githubusercontent.com/73545194/165557099-e1fee422-27d1-43bf-9f26-602f5b3188fd.png)

3. When `Force AdSense account status` is set to `no-client` `needs attention` `client requires review` `client getting ready` or `ready`, the loading behaviour is odd. It initially loads with the progress blue animation bar, but with no AdSense logo, then it refreshes and loads again with the logo and then the TODO message loads.  Here's a screencast. 

https://user-images.githubusercontent.com/73545194/165730619-31b4a0cb-56d7-4004-a97e-00ab5e63d3c4.mp4

4. Is it expected at this stage, that even when the temporary message loads, and I go into settings, the setup is not complete.  I see the message  `Setup incomplete: continue module setup` I suspect it is but did not want to make any assumptions here. 

**Verified:**

When `Force AdSense account status` is set to `Multiple` on the tester plugin, and I start the setup flow, the message appears asking me to select an account. Two accounts appear in the dropdown. When I go to Site Health I can see that the  `AdSense account status` is set to `multiple` which is expected.

![image](https://user-images.githubusercontent.com/73545194/165723928-503feae5-fbba-4f28-8908-e5b36db5d801.png)

**Comment by hussain-t** [comment] 2022-04-28 12:42
Thanks, @wpdarren. As for your observations:

>1. When Force AdSense account status is set to None on the tester plugin, and I start the setup flow, the progress bar animation continues with no message shown. I do see an error appears in the console. API Error method:GET datapoint:accounts type:modules identifier:adsense error:"User does not have an AdSense account."

In the tester plugin, if the account status is set to `ACCOUNT_STATUS_NONE` (none), it returns a `403` error. I think this is incorrect. Rather it should return an empty array like so:

<img width="655" alt="Screenshot 2022-04-28 at 5 42 26 PM" src="https://user-images.githubusercontent.com/24408261/165750635-3c8de08c-64e9-4d17-8f44-fc13b7af3d05.png">

In that case, the setup logic will render the `SetupCreateAccount` component, i.e., create an account screen will be displayed.

---------

>2. The AdSense logo does not appear underneath the Connect Service text.

This is a good point. However, I think this is out of the scope of this ticket as this refactors the existing setup logic. This can be addressed in a separate issue.

---------

>3. When Force AdSense account status is set to no-client needs attention client requires review client getting ready or ready, the loading behaviour is odd. It initially loads with the progress blue animation bar, but with no AdSense logo, then it refreshes and loads again with the logo and then the TODO message loads. Here's a screencast.

The `getAccounts()` selector returns `undefined` if the accounts haven't been loaded yet. In the `SetupMain` component, we return the `<ProgressBar />` if the `accounts` is `undefined`. That is expected since we need to indicate to the user that the data is being fetched. However, as for the odd behavior, `It initially loads with the progress blue animation bar, but with no AdSense logo, then it refreshes and loads again with the logo,` **it will get fixed if we fix the second issue.**

--------

>4. Is it expected at this stage, that even when the temporary message loads, and I go into settings, the setup is not complete. I see the message Setup incomplete: continue module setup I suspect it is but did not want to make any assumptions here.

This is expected since the module is not set up.

--------

@felixarntz, I would like to hear your thoughts on the above. Thanks!

**Comment by techanvil** [comment] 2022-04-28 12:52
Regarding @hussain-t's point about the Tester plugin returning an empty array in the case of no accounts - this does reflect what I'm seeing in real world testing with my personal Google account, which doesn't have an associated AdSense account. The `/v1/modules/adsense/data/accounts` endpoint is returning an empty array.

**Comment by wpdarren** [comment] 2022-04-28 12:56
Thanks @techanvil @hussain-t for your responses. 

I agree with Hussain that I would appreciate @felixarntz having a look over our observations 👍 

Happy to create a ticket for issues 2 and 3.  if it is out of scope.

**Comment by felixarntz** [comment] 2022-05-02 17:51
@hussain-t @wpdarren @techanvil Thank you all for the observations. Providing some feedback:

* **No accounts error:** Before the AdSense API changes last year that facilitate this epic, the accounts endpoint used to return an error in case there were none. I kept this like that in the tester plugin for BC and so that it still works with the V1 flow logic that supports looking for that error. However, just now because of your feedback I realized that I never added this in the V2 logic requirements to also support that error. Given that that error is only there for legacy reasons, I agree with your point though, I will update the tester plugin to return an empty array. We just need to double-check whether that also works with the existing V1 flow, but I think it does because the V1 flow as far as I remember checks for _either_ the error _or_ an empty array. I'll work on that today so that hopefully we can have the tester plugin version 1.8.2 with that fix out tomorrow.
* **Progress bar oddness:** This is indeed odd UX, we should fix it so that the logo heading is always there and only the content below is the progress bar when loading, and it should never switch between one or the other. I will indeed open a separate issue for that though as it's not really related to this one. That issue will then fix the points 2. and 3.
* **Setup incomplete:** +1 to what @hussain-t said here as well, this is expected.

So it looks like most of the QA work here is complete, the only thing would be to double-check the accounts error is gone when the new tester plugin version is there.

**Comment by wpdarren** [comment] 2022-05-03 01:55
@felixarntz thank you for the explanations!   I will wait for the tester plugin to be out and test the accounts error, will then moved this to approved.   With regard to #5159, this will need to be fixed before we commence testing/bug bashing, so I am assuming this ticket will now need to be part of this sprint? We could treat it as a known issue but wanted to check. 

c.c. @FlicHollis @eclarke1

**Comment by felixarntz** [comment] 2022-05-03 14:31
@wpdarren 
> With regard to #5159, this will need to be fixed before we commence testing/bug bashing, so I am assuming this ticket will now need to be part of this sprint? We could treat it as a known issue but wanted to check.

Not necessarily, indeed it could also be a known issue. But fixing it is also super simple, it only has a 3 estimate.

**Comment by wpdarren** [comment] 2022-05-04 13:03
### QA Update: ⚠️ 

@hussain-t @felixarntz this all passes other than this observation:

- When Force AdSense account status is set to `Ready` on the tester plugin.  I start the setup flow, the message appears `Your site isn’t ready to show ads yet`.  I was not expecting this message. Can you clarify if this is expected?  I do have `Force AdSense site status` to Needs attention, so is this why? 

**Verified:**

- When Force AdSense account status is set to `None` on the tester plugin.  I start the setup flow, the `Create your AdSense account` page is loaded.  I am then redirected to `https://www.google.com/adsense/signup/create` to create my AdSense account when the button is clicked.  When I go to Site Health I can see that the AdSense account status is set to none.

![image](https://user-images.githubusercontent.com/73545194/166683513-9a7e1453-4711-4ed6-a807-a02d7c33e9c1.png)

- When Force AdSense account status is set to `Multiple` on the tester plugin.  I start the setup flow, the message appears asking me to `Select your AdSense account`. Two accounts appear in the dropdown.  When I go to Site Health I can see that the AdSense account status is set to multiple.

![image](https://user-images.githubusercontent.com/73545194/166683616-fb658623-b2f3-4b2e-bd1f-f2382b823275.png)

- When Force AdSense account status is set to `No Client` on the tester plugin. I start the setup flow, the message `Looks like you need to upgrade your AdSense account` appears.  When I go to Site Health I can see that the AdSense account status is set to no client.

![image](https://user-images.githubusercontent.com/73545194/166684289-fc654c9f-5132-4b5b-ad76-f015339a5957.png)

- When Force AdSense account status is set to `Needs Attention` on the tester plugin.  I start the setup flow, the message `Your account isn’t ready to show ads yet` appears. When I go to Site Health I can see that the AdSense account status is set to needs attention. 

![image](https://user-images.githubusercontent.com/73545194/166684602-6a35fbae-3b6b-4fb6-9c01-3e0082e2e2fa.png)

- When Force AdSense account status is set to `Client Requires Review` on the tester plugin.  I start the setup flow, the message `Your account isn’t ready to show ads yet` appears.  When I go to Site Health I can see that the AdSense account status is set to your client requires review.

![image](https://user-images.githubusercontent.com/73545194/166685562-32967ce5-f1c8-4f07-82d3-7234857cd4e5.png)

**Closed** 2022-05-05 17:29 UTC
Labels: Type: Bug, P0, Module: AdSense, End of Sprint
