### ISSUE TITLE
Automatically pre-select GA4 property in dropdown based on current site URL

### ISSUE THREAD

**Issue by felixarntz** [google/site-kit-wp#3286] opened 2021-05-04 19:24 UTC
If the current user already has a GA4 property with a web data stream that refers to the current site URL, such a GA4 property should be pre-selected in the dropdown during Analytics module setup.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The functionality to find and set a "matched property" when selecting a specific account (relevant for `modules/analytics` store, as enhanced in #3291) should be expanded to cover GA4:
    * The `modules/analytics` action `selectAccount` should initially also reset the `analytics-4` property ID (to an empty string) **if the `modules/analytics-4` store is available**. It should also `setPrimaryPropertyType` to "ua" (i.e. reset the "primary property type", since "ua" is the default).
    * If the `modules/analytics-4` store is available, it should then call and wait for the `modules/analytics-4` selector `getProperties` and, once properties have been fetched, rely on the `matchPropertyByURL` action (see #3168) passing the `getSiteURLPermutations` array of URLs to attempt to find a matching property for the current site URL. If one is found, the matched property should be set via `setPropertyID`.
    * At the end of the `selectAccount` action, if a matching GA4 property was found (i.e. in `modules/analytics-4` store) and no matching UA property was found (i.e. in `modules/analytics` store), the "primary property type" should be set to "ga4", to indicate that the user likely already has a matching GA4 property but no matching UA property yet.
        * In any other scenario this is not necessary, since "ua" is the default anyway, and if matching properties for both types exist, then "ua" should still be preferred.
* The functionality to find and set a "matched property" on pageload (see `getAccounts` resolver in `modules/analytics` store) should be expanded to cover GA4 **if the `modules/analytics-4` store exists**:
    * At the end of the `getAccounts` resolver, if there is a matched property (based on which an account and UA property were just set) and if there either is no GA4 property set **or the GA4 property that is set is not within the account**, similar logic as implemented in the `selectAccount` action above should be implemented to also check for a matching GA4 property in the account, and set it if found.
    * The bold condition here is an important extra requirement, as the two properties selected between UA and GA4 must always be within the same Analytics account.

## Implementation Brief

* Add a new action `waitForProperties` to the properties datastore in the analytics-4 module. It should work similarly to the `waitForWebDataStreams` action from the same datastore but check for getProperties to be resolved using the `__experimentalResolveSelect` function:
  * https://github.com/google/site-kit-wp/blob/237a8c01c1279ff718dca7ccb7ebe191348692f4/assets/js/modules/analytics-4/datastore/webdatastreams.js#L149-L154
  * https://github.com/google/site-kit-wp/blob/237a8c01c1279ff718dca7ccb7ebe191348692f4/assets/js/modules/analytics-4/datastore/webdatastreams.js#L158-L163
* Update the `selectAccount` action in the `modules/analytics` datastore:
  * It shouldn't return if its properties haven't been resolved yet. Instead of returning, it should wait till they are resolved using the `waitForProperties` action.
  * At the very end of the function check whether the `ga4setup` feature flag is enabled using the `isFeatureEnabled` function. If it is enabled, then do the following:
    * Set the primary property type to `ua` using the `setPrimaryPropertyType` from the `modules/analytics` datastore.
    * Set an empty string for the `propertyID` setting of the `modules/analytics-4` datastore.
    * Get all ga4 properties using the `getProperties` selector from the `modules/analytics-4` datastore and wait till they are loaded/resolved. Use the `waitForProperties` action created above and see an example here: https://github.com/google/site-kit-wp/blob/237a8c01c1279ff718dca7ccb7ebe191348692f4/assets/js/modules/analytics-4/datastore/properties.js#L156
    * Use the `matchPropertyByURL` action from the `analytics-4` module to find matching ga4 property using URLs returned from the `getSiteURLPermutations` selector from the `core/sites` datastore (see #3291).
      * If a property is found, use it to set `propertyID` settings for the `analytics-4` module.
      * If a property is found and there is no matching property in the `modules/analytics` datastore (use the `getMatchedProperty` selector to determine it), then set the primary property type to `ga4`.
* Update the `getAccounts` resolver from the `modules/analytics` datastore. At the very end of the function, it should check whether the `ga4setup` feature flag is enabled using the `isFeatureEnabled` function. If it is enabled and GA4 propertyID is not set or if the property that is currently set has a different account ID, then repeat the logic from the `selectAccount` action to set matching property for the `analytics-4` module.

### Test Coverage

* Update existing js tests that are affected by the aforementioned changes.
* Add new js tests for the new actions.

### Visual Regression Changes

* N/A

## QA Brief

* Create a new jurassic.ninja site
* Create a new Google Analytics account
* Create a new UA property using URL of the newly created site
* Create a new GA4 property and a new web data stream using URL of the newly created site
* Install, activate and connect SK plugin
* Go to the settings page and activate the Analytics module
* Go to the analytics setup screen and select the newly created account from the accounts dropdown.
* Run the following snippet in the browser console, it should return an ID of your new GA4 property:
  ```
  googlesitekit.data.select( 'modules/analytics-4' ).getPropertyID()
  ```

## Changelog entry

* Update Analytics setup to pre-select the GA4 property based on current site URL.

**Comment by aaemnnosttv** [comment] 2021-05-07 18:07
> Create a similar `waitForProperties` action in the `modules/analytics` datastore.

@eugene-manuilov this action already exists in `modules/analytics`, did you perhaps mean to update it to use the same resolve-select implementation? 🤔 

Otherwise IB LGTM.

**Comment by eugene-manuilov** [comment] 2021-05-07 18:37
> this action already exists in `modules/analytics`, did you perhaps mean to update it to use the same resolve-select implementation? 

Ah... yes, you are right. I did miss it for some reason.  IB is updated.

**Comment by aaemnnosttv** [comment] 2021-05-12 07:20
IB ✅

**Comment by aaemnnosttv** [comment] 2021-05-19 08:05
@eugene-manuilov this issue is marked as blocked by #3291 yet that issue has not been started yet. Has the work for that issue been handled in your PR here or does that still need to be done first?

**Comment by eugene-manuilov** [comment] 2021-05-19 08:12
@aaemnnosttv ah... you are right... :man_facepalming: I'll take care of that ticket today and will update my PR accordingly...

**Comment by aaemnnosttv** [comment] 2021-05-25 07:56
@eugene-manuilov would you please add a QA brief?

**Comment by wpdarren** [comment] 2021-05-25 15:25
### QA Update: Clarify with Engineer ⚠️ 

@eugene-manuilov this could be user error :D but I have followed the steps in the QAB, created a new account, and a UA and GA4 property as you can see from the screenshot below. 

![image](https://user-images.githubusercontent.com/73545194/119523869-081eed80-bd75-11eb-978f-e31bcef33998.png)

When I connect Analytics, the account is selected and the UA property is selected by default.  When I go to put the snippet is run in console `googlesitekit.data.select( 'modules/analytics-4' ).getPropertyID()` an error appears `Uncaught TypeError: Cannot read property 'getPropertyID' of null at <anonymous>:1:51` Any ideas why this could be? 

The only thing I would say is the UA and GA4 properties were created separately, and I know you can create them together within Google Analytics, so unsure if this the cause of this issue? 

![image](https://user-images.githubusercontent.com/73545194/119524143-49af9880-bd75-11eb-8b48-2ba780fe75f3.png)

**Comment by eugene-manuilov** [comment] 2021-05-25 15:29
@wpdarren i forgot to mention that you need to enable `ga4setup` feature flag. Did you do it?

**Comment by wpdarren** [comment] 2021-05-25 15:44
@eugene-manuilov ahhhh no, and I completely forgot about the feature flag, thank you!

**Comment by wpdarren** [comment] 2021-05-25 16:12
### QA Update: Pass ✅ 

**Verified:**

Running the snippet in the browser console, returns an ID of my new GA4 property:

![image](https://user-images.githubusercontent.com/73545194/119530676-24be2400-bd7b-11eb-8052-0cbd6a8209aa.png)

![image](https://user-images.githubusercontent.com/73545194/119532000-64d1d680-bd7c-11eb-89ad-04aac8602db1.png)

**Closed** 2021-06-04 00:19 UTC
Labels: Module: Analytics, P0, Rollover, Type: Enhancement
