### ISSUE TITLE
Implement new action and selector for module recovery

### ISSUE THREAD

**Issue by aaemnnosttv** [google/site-kit-wp#4803] opened 2022-02-08 16:51 UTC
## Feature Description

Building on the foundation for using recoverable modules on the client added in https://github.com/google/site-kit-wp/issues/4527, this issue adds the necessary datastore to facilitate [module recovery](https://docs.google.com/document/d/19OtWe7jXKC6dIUfs6J4gDrXujHgCuXnksxBM1uUWmOQ/edit#heading=h.184kxp23btyr).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A new `getRecoverableModules` selector should be added to the `core/modules` store which returns a list of module objects (as returned by `getModules`) for each recoverable module defined in state
	- This selector should have a resolver which receives the list of recoverable module slugs into state from the `_googlesitekitDashboardSharing.recoverableModules` global
* A new `recoverModule( slug )` action should be added to the `core/modules` store which should make a POST request to the `core/modules/data/recover-module` endpoint with a post body of `{ data: { slug: slug } }`
	- This is an async action which should return a `{ response, error }` object
		- `response` should have the shape `{ success: Boolean }`, and `error` should be the same error returned from the fetch action
	- This endpoint was added in https://github.com/google/site-kit-wp/issues/4533
	- If the fetch request was successful and the response includes an `ownerID`:
		- The module's settings should be reloaded from the server (i.e. `fetchGetSettings`)
		- All modules should be reloaded from the server (i.e. `fetchGetModules`)
* Test coverage should be added for the new selector and action

## Implementation Brief

- In `assets/js/googlesitekit/modules/datastore/modules.js`, 
- Create a resolver generator function (method) `*getRecoverableModules()` with the following:
    - Call `getRecoverableModules()` selector and return early if the selector returns non-undefined value.
    - Destructure `recoverableModules` from `global._googlesitekitDashboardSharing`.
    - Dispatch `receiveRecoverableModules` action to set `recoverableModules` in the state.

- Create an action method `receiveRecoverableModules ` with the following:
    - It should accept a parameter `recoverableModules` and it should set it in the state as `state.recoverableModules`.
    - We should also add `recoverableModules` in the `baseInitialState` and set `undefined` as the default value.

- Create `getRecoverableModules()` selector with the following:
    - Get the `modules` from the `getModules` selector.
    - Return `undefined` if the `getModules` selector is not yet loaded.
    - Return `undefined` if the `recoverableModules` is `undefined` in the state.
    - It should return the modules object that maps/matches the `recoverableModules` from the `state`.

- Create `fetchRecoverModuleStore` with `createFetchStore`
    - `baseName` should be `recoverModule`
    - `controlCallback` method should accept `slug` as a parameter 
    - `controlCallback` should return `API.set()` that calls the new `recover-module` endpoint with the body `slug`. The backend is implemented in #4533
    - `reducerCallback` receives the `state` as the parameter and returns the state
    - `argsToParams` takes `slug` as a parameter and returns the `slug` in an object
        - `validateParams` takes `slug` as parameter. It should validate the `slug`

- Create an async action `*recoverModule( slug )` with the following:
    - Get `{ response, error }` from `fetchRecoverModuleStore.actions.fetchRecoverModule`.
    - If the fetch request was successful and the `response` includes an `ownerID`. Do the following as mentioned in the AC:
        - The module's settings should be reloaded from the server. (i.e. `fetchGetSettings`).
        - All modules should be reloaded from the server (i.e. `fetchGetModules`).
     - It should return `response` and `error` as defined in the AC.

### Test Coverage

- Add test cases for `getRecoverableModules` selector and `recoverModule` action

## QA Brief

- Make the module recoverable by adding the following options (add shared roles and change the owner to a non-authenticated / random user ID):
```bash
10updocker wp option update googlesitekit_dashboard_sharing '{ "search-console": { "sharedRoles": [ "editor" ], "management": "all_admins" } }' --format=json
10updocker wp option update googlesitekit_search-console_settings '{ "ownerID": 2 }' --format=json
```
- From the Site Kit dashboard browser console, run `window._googlesitekitDashboardSharingData.recoverableModules`.
- Ensure `['search-console']` is available in the  `recoverableModules`.
- Execute `getRecoverableModules()` selector from the browser console:
```js
window.googlesitekit.data.select('core/modules').getRecoverableModules()
```
- Ensure the `search-console` object is available with the properties.
- Execute `recoverModule()` action from the browser console:
```js
window.googlesitekit.data.dispatch('core/modules').recoverModule('search-console')
```
- Check the network tab and ensure the API call for the `recover-module` endpoint was successful and the response has the `ownerID` property.
- Execute `recoverModule()` action by passing a non-recoverable module:
```js
window.googlesitekit.data.dispatch('core/modules').recoverModule('analytics')
```
- Ensure the API encounters an error with `Module is not recoverable.`.

----------

### QA:Eng
- Verify the code changes met the AC and IB.
- Verify the newly added tests for the `getRecoverableModules` selector and `recoverModule` action are good enough and are passing.

## Changelog entry

* Add an action to recover a module and a selector to get recoverable modules.

**Comment by eugene-manuilov** [comment] 2022-04-07 10:31
Thanks, @hussain-t. Mostly looks good to me. Added a few comments to make sure new methods are consistent with others.

>   * We should also add `recoverableModules` in the `baseInitialState` and set an empty object as the value.

Let's use `undefined` as the default value to indicate that information hasn't been loaded yet.

> * Create a resolver generator function (method) `*getRecoverableModules()` with the following:
>   * Destructure `recoverableModules` from `global._googlesitekitDashboardSharing`.
>   * Dispatch `receiveGetRecoverableModules` action to set `recoverableModules` in the state.

Let's read this information only if the current value of the recoverable modules in the state is `undefined`. In other words, we need to call the `getRecoverableModules` selector in its resolver and return early if it returns non-undefined value.

> * Create `getRecoverableModules()` selector with the following:
>   * Get the `modules` from the `getModules` selector.
>   * It should return the modules object that maps/matches the `recoverableModules` from the `state`.

The selector should return `undefined` if the `recoverableModules` is `undefined` in the state.

> * Create an action method `receiveGetRecoverableModules` with the following

Let's call this action just `receiveRecoverableModules`.

> * Return the state and the new state with the slug as key and the obtained `response` as the value i.e. `[slug]: response.*`

Do we really need to save this information into the state? Seems like this information is useless and we can return the state with no changes in it.

**Comment by eugene-manuilov** [comment] 2022-04-08 13:55
Thanks, @hussain-t. IB ✔️

**Comment by wpdarren** [comment] 2022-05-03 12:31
### QA Update: ✅ 

**Verified:**

- When the command in QAB was run `['search-console']` is available in the recoverableModules.
- When the command in QAB was run the search-console object was available with the properties.
- When the command in QAB was run the network tab shows the API call for `recover-module` with the `ownerID` property.
- When the command in QAB was run the error message `Module is not recoverable` appeared in the console.

![image](https://user-images.githubusercontent.com/73545194/166452936-375d9692-fe98-4f55-ae10-976f9b153eb9.png)

Added the `QA:Eng` label as per the QAB.

**Comment by techanvil** [comment] 2022-05-05 12:51
### `QA:Eng` :x: 

Hi @hussain-t, while going through the `QA:Eng` steps I noticed a couple of issues.

Firstly, there has been a slightly deviation from the AC/IB in the implementation of `recoverModule`. According to the AC the returned `response` should have the shape `{ success: Boolean }`, however `response` is being passed directly from the fetch and has the shape `{ ownerID: number }`.

Next, a handful of minor comments relating to the tests.

- In the `getRecoverableModules` test ```should return undefined if `modules` list cannot be loaded```, the line `registry.select( CORE_MODULES ).getModules();` looks pretty redundant as it can't have any effect on the value of `recoverableModules` which is tested in the following line, and which is the last line of the test. Therefore, unless I am missing something, this call to `getModules` should be removed and the test may need to be reconsidered as a result, as it's pretty much a duplicate of the test above it. If there is a non-obvious reason for this call to `getModules` it would be good to mention it in a comment.
- There are a couple of minor typos:
  - `encourters` should be `encounters`
  - `each recoverable modules` should be `each recoverable module`
- Also, not essential but something to consider - the two `recoverModule` tests, `encounters an error if the module is not recoverable` and `encourters an error if an invalid module slug is passed` are almost identical and essentially are just checking that the error returned by the `recover-module` is being passed back from the action. It might be worth merging these into one test.
  - If keeping both tests you could also consider using `it.each` similarly to `isModuleConnected` tests in the same file.

**Comment by hussain-t** [comment] 2022-05-05 17:30
Thanks, @techanvil 👍 

I have fixed the `recoverModule` action response and the tests in the follow-up [PR](https://github.com/google/site-kit-wp/pull/5182). I do have an opinion on redundant tests, as you pointed out - I agree with the DRY principle; however, I feel it’s better to have explicit/separate cases for unit tests as it’s more readable and clear.

**Comment by techanvil** [comment] 2022-05-05 17:50
Thanks @hussain-t, and that sounds fair to me. Followup PR is now reviewed and merged. Nice one :tada:

**Comment by techanvil** [comment] 2022-05-05 18:13
## QA :white_check_mark: 

`QA:Eng`:

* Verified the code changes met the AC and IB.
* Verified the newly added tests for the `getRecoverableModules` selector and `recoverModule` action provide good coverage.

Additionally ran through the main body of the QA Brief again with flying colours. To echo @wpdarren's earlier test:

- When the command in QAB was run ['search-console'] is available in the recoverableModules.
- When the command in QAB was run the search-console object was available with the properties.
- When the command in QAB was run the network tab shows the API call for recover-module with the ownerID property.
- When the command in QAB was run the error message Module is not recoverable appeared in the console.

![image](https://user-images.githubusercontent.com/18395600/166986820-033d6ac9-eef2-4edb-8611-97bb2e120974.png)

**Closed** 2022-05-09 18:12 UTC
Labels: P0, Type: Enhancement, QA: Eng, Rollover
