### ISSUE TITLE
Analytics: Total "Users" not in sync with Analytics Web UI

### ISSUE THREAD

**Issue by jamesozzie** [google/site-kit-wp#1202] opened 2020-03-03 17:17 UTC
## Bug Description

In the Analytics dashboard the "Users" figure is off sync with the Analytics Web UI.

Sessions, Bounce Rates & Session Duration figures match fine. I can replicate with other sites, screenshot of one site below. 

Reported in WordPress support form as below:
[https://wordpress.org/support/topic/site-kit-user-stats-doesnt-match-google-analytics/#post-12499488](https://wordpress.org/support/topic/site-kit-user-stats-doesnt-match-google-analytics 
)

## Screenshots

![d6pSex05Qrz](https://user-images.githubusercontent.com/41326532/75800711-e8fffe80-5d71-11ea-9830-4e8b9fa19fef.png)

## Additional Context

- No views applied
- [Query explorer](https://ga-dev-tools.appspot.com/query-explorer) also results in off sync numbers

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The timeframe and stats displayed in Site Kit FE must match those in GA FE.
* In particular, when viewing the 90 day time range, the number of users must match exactly. 

## Implementation Brief

* In `AnalyticsDashboardWidgetOverview` (`assets/js/modules/analytics/dashboard/dashboard-widget-overview.js`) add an additional datapoint to the component for the direct total user query. This requires:
	* Add state with `report` and `directTotalUsers` properties.
	* Add `processCallbackData` handling similar to other multi-data point components (eg. `/assets/js/modules/analytics/dashboard/dashboard-widget-top-level.js`)
	* Switch to using the report from state in the component render method, waiting until both data points are resolved before rendering.
	* Add an additional datapoint to the data source array used when applying `withData` to the component. The data request object itself will be imported from `assets/js/modules/analytics/util/index.js`

* In `assets/js/modules/analytics/util/index.js`:
	* Add a `userReportDataDefaults` data structure that includes only the `ga:users` metric.

## QA Brief

* 

## Changelog entry

* Ensure the total user count in the Analytics module matches the numbers displayed in the Google Analytics frontend.

**Comment by cole10up** [comment] 2020-03-09 16:34
**Tested**

Tested latest develop of 1.5.0

Logged into GA:
![image](https://user-images.githubusercontent.com/57115907/76235738-c5f9a280-61e8-11ea-9ae5-8e030f468ad1.png)

Installed SK and activated GA service, compared SK's stats with GA's stats

![image](https://user-images.githubusercontent.com/57115907/76235845-ed506f80-61e8-11ea-876b-abb07347256d.png)

Confirmed missmatch.

**Changed duration:**
![image](https://user-images.githubusercontent.com/57115907/76235909-06f1b700-61e9-11ea-8789-c1516816f066.png)

Noticed an even greater missmatch

![image](https://user-images.githubusercontent.com/57115907/76235935-11ac4c00-61e9-11ea-9539-bfd4700fdfeb.png)

Sending to Execution.

**Comment by adamsilverstein** [comment] 2020-03-09 23:25
I researched this and made some progress. I discovered the following:

* This query involves two date ranges (we use them for past period comparison in the chart).
* The code uses the "total" value returned by the API call, which appears incorrect in the plugin 
* When I tested this on my personal site data, the returned number was off.
* The constructed dates for the query we send to the API seem correct. Checked on the PHP side in the constructed request
* When I tested **a simplified query** for just the date range via the api explorer, the returned value was correct
* Possibly something about including the `date` dimension is throwing the total off? The API may be totaling the users per day vs doing a total for the entire period, which would explain a higher number.

Next:

* I'm going to test totaling the users directly (via the row data) as well as sending a single date range request without the "range" to see if the result is different.

**Comment by adamsilverstein** [comment] 2020-03-10 15:29
I have confirmed the numeric discrepancy with users is due to introducing the `ga:date` dimension in the query. 

Querying the API for 90 days without the date range, my user total is `7094`:

![image](https://user-images.githubusercontent.com/2676022/76328221-a9c13880-62b0-11ea-8fe8-2f41ccc27c91.png)

Running the same query with the date dimension, my user total shows (inaccurately) as `7441`:

![image](https://user-images.githubusercontent.com/2676022/76328346-ce1d1500-62b0-11ea-820d-085661c7343a.png)

**Comment by adamsilverstein** [comment] 2020-03-10 21:13
To fix this issue, we should be able to add an additional data point that runs a query to obtain only the `ga:user` data for the entire period (without the dimension). I will work on the implementation brief.

**Comment by adamsilverstein** [comment] 2020-03-13 18:22
Adding an IB that fixes the issue described here. 

A couple of additional potential issues I noticed along the way:

* Our rounding may be off. In my case, the number I get back from the API for the user Query is 6852. This matches exactly what I see in Analytics:

![image](https://user-images.githubusercontent.com/2676022/76648213-e052b980-6523-11ea-89c8-09e2be4efdb8.png)

However, on the Analytics Dashboard this shows up as 6.8k:

![image](https://user-images.githubusercontent.com/2676022/76648281-04ae9600-6524-11ea-83ef-8e7f6b12d652.png)

Testing this datapoint in the plugin, our rounding turns the number into 6.9k:

![image](https://user-images.githubusercontent.com/2676022/76648340-214ace00-6524-11ea-91f1-194a97e7f0a3.png)

we may need to adjust `readableLargeNumber` slightly to `floor` larger number hundreds.

* The change percent change we show is also incorrect, even using a the direct query (without a dimension) using `compareDateRanges: 1,` (getting last/previous periods), our percent change calculation in `changeToPercent` doesn't match what I see in analytics:

![image](https://user-images.githubusercontent.com/2676022/76648719-d2e9ff00-6524-11ea-92bc-5b040e6c567d.png)

vs
![image](https://user-images.githubusercontent.com/2676022/76648642-ae8e2280-6524-11ea-819e-19c3d8d031a0.png)

The percent change on other data points also looks off. I'll need to dig in further to see where the math is off. If possible we should query the API for these change values directly instead of calculating them.

![image](https://user-images.githubusercontent.com/2676022/76648875-26f4e380-6525-11ea-96e5-f3209a6b192f.png)

![image](https://user-images.githubusercontent.com/2676022/76648883-2eb48800-6525-11ea-90dd-9d7c4410202b.png)

**Comment by adamsilverstein** [comment] 2020-03-13 18:35
@felixarntz over to you for IB review. 

I have a working branch for this using the approach described which I built to verify the data accuracy. Once you approve the approach I can take on implementation and open a PR.

**Comment by felixarntz** [comment] 2020-03-17 00:53
IB ✅

**Comment by adamsilverstein** [comment] 2020-03-24 17:58
I created a couple of follow up issues to track the other issues I noticed while working on this.

**Comment by felixarntz** [comment] 2020-04-08 16:14
Moving this to 1.8.0 - it's not a critical bug. It's almost ready, maybe it already is ready, but it's probably safer not including this just yet.

**Comment by felixarntz** [comment] 2020-04-08 17:00
Moving back to 1.7.0, since this is kind of a dependency for #1279

**Comment by felixarntz** [comment] 2020-04-08 18:35
@cole10up Ready for QA now alongside with #1279 from before. This one is for getting the overall number right, the other one for ensuring the numbers are correctly rounded.

**Comment by cole10up** [comment] 2020-04-09 07:22
**Tested**

Checked GA:
![image](https://user-images.githubusercontent.com/57115907/78868172-4a616000-79f7-11ea-9803-2a12316de42b.png)

Checked SK:
![image](https://user-images.githubusercontent.com/57115907/78868196-58af7c00-79f7-11ea-95b0-db3c410bc119.png)

28 Days:

GA:
![image](https://user-images.githubusercontent.com/57115907/78868445-ce1b4c80-79f7-11ea-8f8f-39002b9f77a2.png)

SK:
![image](https://user-images.githubusercontent.com/57115907/78868497-e1c6b300-79f7-11ea-90e2-7e8f3e21ae9f.png)

90 Days:

GA:
![image](https://user-images.githubusercontent.com/57115907/78868558-ff941800-79f7-11ea-9f60-63d8a732b502.png)

SK:
![image](https://user-images.githubusercontent.com/57115907/78868582-0a4ead00-79f8-11ea-8cd0-67d6fab75598.png)

Noticed mismatch on the percentage up and down from GA to SK, unrelated to user totals. Will explore this farther. Otherwise Passed QA ✅

**Comment by felixarntz** [comment] 2020-04-09 14:55
@cole10up Regarding the percentages, this is being tracked in #1280.

**Closed** 2020-04-09 16:44 UTC
Labels: Group: Escalation, P0, Type: Bug
